import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "diversifikasi",
    levelId: "portofolio",
    order: 1,
    title: "Diversifikasi: Jangan Taruh Semua Telur di Satu Keranjang",
    summary: "Menyebar investasi menurunkan risiko tanpa banyak mengorbankan imbal hasil. Dengan video & simulator.",
    durationMin: 13,
    tags: ["diversifikasi", "portofolio", "risiko"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Diversifikasi</strong> adalah menyebar dana ke banyak aset yang tidak bergerak seragam. Saat satu aset turun, yang lain bisa naik atau stabil, sehingga risiko keseluruhan portofolio berkurang. Inilah satu-satunya 'makan siang gratis' di keuangan.",
      },
      {
        type: "video",
        comp: "DiversifikasiVideo",
        title: "Video: Diversifikasi Menurunkan Risiko",
        caption: "Animasi risiko portofolio turun saat jumlah aset bertambah, sampai batas risiko pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua jenis risiko",
        html: "<strong>Risiko spesifik</strong> (masalah satu perusahaan) bisa dihilangkan dengan diversifikasi. <strong>Risiko pasar</strong> (resesi, krisis) tidak bisa didiversifikasi karena memengaruhi hampir semua aset.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur bobot dan korelasi dua aset, lihat bagaimana risiko portofolio bisa lebih rendah dari rata-rata risikonya.",
      },
      { type: "widget", widget: "SimulatorPortofolio" },
      {
        type: "case",
        title: "Studi Kasus: Karyawan yang terlalu cinta saham kantornya",
        html: "Seorang karyawan menaruh seluruh tabungan di saham perusahaan tempat ia bekerja. Saat perusahaan bermasalah, ia kehilangan pekerjaan <strong>dan</strong> tabungannya sekaligus, risiko ganda yang tidak terdiversifikasi. Andai ia menyebar ke banyak aset, satu masalah tidak akan menghancurkan seluruh kekayaannya.",
      },
      {
        type: "calcExercise",
        prompt: "Portofolio 60% aset A (return 8%) dan 40% aset B (return 15%). Berapa return tertimbang portofolio?",
        answer: 10.8,
        tolerance: 0.1,
        suffix: "%",
        solution: "Return = 0,6 x 8% + 0,4 x 15% = 4,8% + 6% = <strong>10,8%</strong>.",
        hint: "Kalikan bobot tiap aset dengan returnnya, lalu jumlahkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Risiko ini bisa dikurangi dengan diversifikasi atau tidak?",
        buckets: ["Bisa didiversifikasi", "Tidak bisa (risiko pasar)"],
        items: [
          { text: "Satu perusahaan bangkrut", bucket: "Bisa didiversifikasi" },
          { text: "Resesi ekonomi global", bucket: "Tidak bisa (risiko pasar)" },
          { text: "Pabrik satu emiten terbakar", bucket: "Bisa didiversifikasi" },
          { text: "Krisis keuangan menyeluruh", bucket: "Tidak bisa (risiko pasar)" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Risiko Portofolio Menurun Saat Jumlah Aset Bertambah",
        unit: "% volatilitas",
        source: "Ilustrasi edukasi",
        note: "Penambahan aset menurunkan risiko spesifik, tetapi risiko pasar (sekitar 15%) tidak bisa dihilangkan.",
        data: [
          { label: "1 aset", value: 40, color: "#ef4444" },
          { label: "5 aset", value: 26, color: "#f59e0b" },
          { label: "10 aset", value: 21, color: "#eab308" },
          { label: "20 aset", value: 18, color: "#84cc16" },
          { label: "30 aset", value: 16, color: "#22c55e" },
          { label: "50 aset", value: 15, color: "#16a34a" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan penjelasannya.",
        pairs: [
          { left: "Risiko spesifik", right: "Bisa dihilangkan dengan menyebar ke banyak aset" },
          { left: "Risiko pasar", right: "Tetap ada walau sudah terdiversifikasi" },
          { left: "Korelasi rendah", right: "Aset tidak bergerak seragam, manfaat diversifikasi besar" },
          { left: "Korelasi tinggi", right: "Aset bergerak searah, manfaat diversifikasi kecil" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Korelasi Melonjak pada Krisis 2008",
        html: "Dalam krisis keuangan 2008, indeks <strong>S&amp;P 500</strong> jatuh sekitar <strong>57%</strong> dari puncak Oktober 2007 ke titik terendah Maret 2009. Saat panik melanda, hampir semua jenis saham turun bersamaan sehingga korelasi antar aset melonjak dan diversifikasi antar saham saja tidak cukup. Yang relatif bertahan adalah <strong>obligasi pemerintah</strong>, menegaskan pentingnya menyebar ke kelas aset yang benar-benar berbeda.",
      },
      {
        type: "takeaways",
        items: [
          "Diversifikasi menyebar dana untuk menurunkan risiko.",
          "Risiko spesifik bisa dihilangkan; risiko pasar tidak.",
          "Korelasi rendah antar aset memperbesar manfaat diversifikasi.",
          "Hindari menaruh terlalu banyak di satu aset (apalagi saham kantor sendiri).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Diversifikasi terutama bertujuan?",
            options: ["Menaikkan imbal hasil setinggi mungkin", "Menurunkan risiko tanpa banyak korban imbal hasil", "Menghindari pajak", "Menjamin untung"],
            answer: 1,
            explain: "Diversifikasi mengurangi risiko untuk tingkat imbal hasil tertentu.",
          },
          {
            q: "Risiko yang TIDAK bisa dihilangkan dengan diversifikasi?",
            options: ["Risiko spesifik perusahaan", "Risiko pasar", "Risiko satu pabrik", "Risiko satu produk"],
            answer: 1,
            explain: "Risiko pasar memengaruhi hampir semua aset, jadi tidak bisa didiversifikasi.",
          },
          {
            q: "Manfaat diversifikasi paling besar saat antar aset?",
            options: ["Berkorelasi tinggi", "Berkorelasi rendah/negatif", "Identik", "Sama persis"],
            answer: 1,
            explain: "Korelasi rendah membuat aset tidak turun bersamaan, menurunkan risiko gabungan.",
          },
          {
            q: "60% return 10%, 40% return 20%. Return portofolio?",
            options: ["14%", "30%", "15%", "10%"],
            answer: 0,
            explain: "0,6x10 + 0,4x20 = 6 + 8 = 14%.",
          },
          {
            q: "Menaruh seluruh dana di saham tempat bekerja berisiko karena?",
            options: ["Pasti rugi", "Risiko ganda: pekerjaan dan tabungan bergantung pada satu perusahaan", "Pajak tinggi", "Tidak ada dividen"],
            answer: 1,
            explain: "Jika perusahaan jatuh, kehilangan gaji dan investasi sekaligus.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "alokasi-aset",
    levelId: "portofolio",
    order: 2,
    title: "Alokasi Aset Strategis: Saham, Obligasi, dan Kas Sesuai Tujuan",
    summary: "Menentukan porsi saham, obligasi, dan kas sesuai tujuan dan horizon waktu. Dengan simulator alokasi.",
    durationMin: 13,
    tags: ["alokasi aset", "portofolio", "horizon"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Alokasi aset</strong> adalah keputusan membagi dana ke kelas aset besar, yaitu saham, obligasi, dan kas. Penelitian klasik menunjukkan bahwa alokasi aset menjelaskan sebagian besar variasi hasil portofolio jangka panjang, jauh lebih besar daripada pemilihan satu per satu saham. Inilah keputusan terpenting sebelum memilih produk.",
      },
      {
        type: "paragraph",
        html: "Porsi yang tepat bergantung pada <strong>tujuan</strong> dan <strong>horizon waktu</strong>. Semakin panjang horizon dan semakin tinggi toleransi risiko, semakin besar porsi saham yang masuk akal. Semakin dekat tujuan, semakin besar porsi obligasi dan kas untuk menjaga nilai pokok.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Horizon menentukan porsi saham",
        html: "Dana yang dipakai &lt; 3 tahun sebaiknya di kas dan obligasi pendek. Dana &gt; 10 tahun bisa berat di saham karena ada waktu untuk pulih dari penurunan pasar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pedoman kasar 100 dikurangi usia",
        html: "Aturan praktis lama: porsi saham = 100 - usia. Usia 30 berarti sekitar 70% saham. Ini hanya titik awal, bukan rumus pasti, dan kini sering dipakai angka 110 atau 120 karena harapan hidup lebih panjang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur porsi saham, obligasi, dan kas, lalu lihat perkiraan imbal hasil dan rentang risiko portofolio Anda.",
      },
      { type: "widget", widget: "SimulatorAlokasiAset" },
      {
        type: "chart",
        variant: "donut",
        title: "Contoh Alokasi untuk Horizon Panjang (Agresif)",
        unit: "%",
        source: "Ilustrasi edukasi",
        note: "Komposisi contoh untuk tujuan jangka panjang di atas 10 tahun.",
        data: [
          { label: "Saham", value: 70, color: "#2563eb" },
          { label: "Obligasi", value: 25, color: "#16a34a" },
          { label: "Kas", value: 5, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua tujuan, dua alokasi",
        html: "Rina punya dua tujuan. Dana pendidikan anak yang dipakai 2 tahun lagi ia taruh 80% kas dan obligasi pendek, 20% saham, supaya nilai pokok aman. Dana pensiun yang masih 25 tahun lagi ia taruh 75% saham, 20% obligasi, 5% kas, supaya tumbuh maksimal. Satu orang, dua alokasi berbeda, karena horizonnya berbeda.",
      },
      {
        type: "calcExercise",
        prompt: "Portofolio 70% saham (return harapan 10%), 25% obligasi (return 5%), 5% kas (return 3%). Berapa return harapan portofolio?",
        answer: 8.4,
        tolerance: 0.1,
        suffix: "%",
        solution: "Return = 0,7 x 10% + 0,25 x 5% + 0,05 x 3% = 7% + 1,25% + 0,15% = <strong>8,4%</strong>.",
        hint: "Kalikan tiap bobot dengan returnnya, lalu jumlahkan ketiganya.",
      },
      {
        type: "classifyExercise",
        prompt: "Untuk tujuan berikut, alokasi mana yang lebih cocok?",
        buckets: ["Dominan saham (horizon panjang)", "Dominan kas/obligasi (horizon pendek)"],
        items: [
          { text: "Dana pensiun 30 tahun lagi", bucket: "Dominan saham (horizon panjang)" },
          { text: "Uang muka rumah 1 tahun lagi", bucket: "Dominan kas/obligasi (horizon pendek)" },
          { text: "Dana kuliah anak 20 tahun lagi", bucket: "Dominan saham (horizon panjang)" },
          { text: "Dana darurat yang sewaktu-waktu dipakai", bucket: "Dominan kas/obligasi (horizon pendek)" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Porsi Saham Menurun Seiring Pendeknya Horizon",
        unit: "% saham",
        source: "Ilustrasi edukasi",
        note: "Semakin dekat tujuan, porsi saham dikurangi dan porsi kas/obligasi diperbesar untuk menjaga pokok.",
        data: [
          { label: "> 20 tahun", value: 80, color: "#2563eb" },
          { label: "10-20 tahun", value: 65, color: "#16a34a" },
          { label: "5-10 tahun", value: 45, color: "#eab308" },
          { label: "3-5 tahun", value: 25, color: "#f59e0b" },
          { label: "< 3 tahun", value: 10, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Memakai aturan praktis 110 dikurangi usia, berapa persen porsi saham untuk orang berusia 35 tahun?",
        answer: 75,
        tolerance: 0.5,
        suffix: "%",
        solution: "Porsi saham = 110 - 35 = <strong>75%</strong>. Sisanya 25% di obligasi dan kas.",
        hint: "Kurangkan usia dari angka 110.",
      },
      {
        type: "case",
        title: "Sejarah: Obligasi sebagai Peredam pada 2008",
        html: "Ketika saham global anjlok sekitar <strong>57%</strong> selama krisis 2008-2009, harga <strong>obligasi pemerintah</strong> AS justru naik karena investor berlindung ke aset aman dan suku bunga dipangkas. Portofolio yang mengalokasikan sebagian dana ke obligasi mengalami penurunan jauh lebih kecil dibanding yang seluruhnya saham. Inilah bukti nyata bahwa alokasi aset, bukan sekadar pemilihan saham, yang menentukan ketahanan portofolio.",
      },
      {
        type: "takeaways",
        items: [
          "Alokasi aset adalah keputusan terbesar yang menentukan hasil jangka panjang.",
          "Horizon panjang membenarkan porsi saham lebih besar.",
          "Tujuan yang dekat butuh porsi kas dan obligasi lebih besar untuk menjaga pokok.",
          "Aturan praktis seperti 100 dikurangi usia hanya titik awal, bukan rumus baku.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa yang dimaksud alokasi aset?",
            options: ["Memilih satu saham terbaik", "Membagi dana ke kelas aset seperti saham, obligasi, kas", "Menentukan waktu jual beli", "Menghindari pajak"],
            answer: 1,
            explain: "Alokasi aset adalah pembagian dana antar kelas aset besar.",
          },
          {
            q: "Faktor utama yang menentukan porsi saham yang pantas?",
            options: ["Warna aplikasi broker", "Tujuan dan horizon waktu", "Jumlah teman yang investasi", "Berita harian"],
            answer: 1,
            explain: "Horizon dan tujuan menentukan seberapa besar risiko yang bisa ditanggung.",
          },
          {
            q: "Dana yang akan dipakai 1 tahun lagi sebaiknya?",
            options: ["Dominan saham", "Dominan kas dan obligasi pendek", "Seluruhnya kripto", "Seluruhnya saham gorengan"],
            answer: 1,
            explain: "Horizon pendek butuh nilai pokok yang stabil, jadi kas dan obligasi pendek.",
          },
          {
            q: "Menurut aturan praktis 100 dikurangi usia, orang berusia 40 punya porsi saham sekitar?",
            options: ["40%", "60%", "100%", "10%"],
            answer: 1,
            explain: "100 - 40 = 60%, hanya sebagai titik awal kasar.",
          },
          {
            q: "70% saham (10%), 30% obligasi (4%). Return harapan portofolio?",
            options: ["8,2%", "14%", "7%", "10%"],
            answer: 0,
            explain: "0,7x10 + 0,3x4 = 7 + 1,2 = 8,2%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "rebalancing",
    levelId: "portofolio",
    order: 3,
    title: "Rebalancing: Mengembalikan Bobot ke Target dengan Disiplin",
    summary: "Mengembalikan komposisi portofolio ke target: beli yang turun, jual yang naik, secara disiplin. Dengan simulator.",
    durationMin: 13,
    tags: ["rebalancing", "portofolio", "disiplin"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Rebalancing</strong> adalah menyesuaikan kembali bobot aset ke target semula setelah harga pasar membuatnya bergeser. Saat saham naik kencang, porsinya melebihi target, sehingga risiko portofolio diam-diam membesar. Rebalancing menjual sebagian yang naik dan membeli yang tertinggal untuk mengembalikan komposisi.",
      },
      {
        type: "paragraph",
        html: "Efek tak langsungnya elegan: Anda otomatis <strong>menjual mahal dan membeli murah</strong>. Ini kebalikan dari naluri kebanyakan orang yang ikut ramai membeli saat harga sudah tinggi dan panik menjual saat harga jatuh.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Beli yang turun, jual yang naik",
        html: "Rebalancing memaksa disiplin: aset yang porsinya membengkak dipangkas, aset yang menyusut ditambah. Tujuannya menjaga tingkat risiko, bukan mengejar untung sesaat.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kapan rebalancing dilakukan",
        html: "Dua pendekatan umum: berdasarkan <strong>waktu</strong> (misalnya tiap 6 atau 12 bulan) atau berdasarkan <strong>ambang</strong> (misalnya saat bobot melenceng lebih dari 5% dari target). Banyak investor menggabungkan keduanya.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Perhatikan biaya dan pajak",
        html: "Rebalancing terlalu sering menimbulkan biaya transaksi dan potensi pajak. Jangan berlebihan. Manfaatkan setoran rutin untuk menambah aset yang tertinggal agar lebih hemat biaya.",
      },
      {
        type: "widget", widget: "SimulatorPortofolio",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Bobot Sebelum dan Sesudah Rebalancing",
        unit: "%",
        source: "Ilustrasi edukasi",
        note: "Target 60% saham dan 40% obligasi. Setelah saham naik, bobot saham menjadi 70%, lalu dikembalikan ke 60%.",
        data: [
          { label: "Saham sebelum", value: 70, color: "#2563eb" },
          { label: "Saham sesudah", value: 60, color: "#16a34a" },
          { label: "Obligasi sebelum", value: 30, color: "#93c5fd" },
          { label: "Obligasi sesudah", value: 40, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Portofolio Rp100 juta yang melenceng",
        html: "Budi menargetkan 60% saham (Rp60 juta) dan 40% obligasi (Rp40 juta). Setelah setahun, saham naik sehingga senilai Rp77 juta dan obligasi Rp43 juta, total Rp120 juta. Bobot saham kini 64%. Untuk kembali ke 60%, target saham = 0,6 x 120 = Rp72 juta, jadi Budi menjual saham Rp5 juta dan membeli obligasi Rp5 juta. Ia menjual yang sudah naik dan menambah yang tertinggal.",
      },
      {
        type: "calcExercise",
        prompt: "Total portofolio Rp200 juta, target saham 50%. Saat ini saham bernilai Rp120 juta. Berapa rupiah saham yang harus dijual agar kembali ke target?",
        answer: 20,
        tolerance: 0.5,
        suffix: " juta",
        solution: "Target saham = 50% x 200 = Rp100 juta. Saat ini Rp120 juta, jadi jual Rp120 - Rp100 = <strong>Rp20 juta</strong>.",
        hint: "Hitung nilai target saham (50% x total), lalu kurangi dari nilai saham sekarang.",
      },
      {
        type: "classifyExercise",
        prompt: "Saat rebalancing ke target, aset ini dibeli atau dijual?",
        buckets: ["Dibeli (porsi di bawah target)", "Dijual (porsi di atas target)"],
        items: [
          { text: "Saham yang baru saja melonjak melebihi target", bucket: "Dijual (porsi di atas target)" },
          { text: "Obligasi yang porsinya menyusut di bawah target", bucket: "Dibeli (porsi di bawah target)" },
          { text: "Kelas aset yang harganya jatuh sehingga bobotnya turun", bucket: "Dibeli (porsi di bawah target)" },
          { text: "Aset terbaik tahun ini yang bobotnya membengkak", bucket: "Dijual (porsi di atas target)" },
        ],
      },
      {
        type: "video",
        comp: "RebalancingVideo",
        title: "Video: Cara Kerja Rebalancing",
        caption: "Animasi bobot saham dan obligasi bergeser oleh pasar, lalu dikembalikan ke target.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Perjalanan Bobot Saham Menjauh dari Target 60%",
        unit: "% saham",
        source: "Ilustrasi edukasi",
        note: "Karena saham naik, bobotnya menjauh dari target 60% sampai menembus ambang 65%, saat itu rebalancing dilakukan.",
        data: [
          { label: "Awal", value: 60, color: "#2563eb" },
          { label: "Bulan 3", value: 62, color: "#3b82f6" },
          { label: "Bulan 6", value: 64, color: "#60a5fa" },
          { label: "Bulan 9", value: 66, color: "#f59e0b" },
          { label: "Setelah rebalancing", value: 60, color: "#16a34a" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pendekatan rebalancing dengan ciri pemicunya.",
        pairs: [
          { left: "Berbasis waktu", right: "Dilakukan tiap 6 atau 12 bulan secara berkala" },
          { left: "Berbasis ambang", right: "Dilakukan saat bobot melenceng lebih dari 5%" },
          { left: "Lewat setoran rutin", right: "Menambah aset yang tertinggal tanpa menjual" },
          { left: "Gabungan", right: "Memakai jadwal berkala sekaligus batas deviasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Gelembung Dot-com 2000",
        html: "Menjelang tahun 2000, saham teknologi melambung sehingga bobotnya membengkak di portofolio banyak investor; indeks <strong>Nasdaq</strong> mencapai puncak sekitar <strong>5.048</strong> pada Maret 2000 sebelum anjlok sekitar <strong>78%</strong> hingga 2002. Investor yang disiplin melakukan rebalancing akan memangkas porsi teknologi yang berlebih dan memindahkannya ke aset lain sebelum gelembung pecah. Rebalancing memaksa menjual yang sudah mahal, persis saat godaan untuk terus menambah paling besar.",
      },
      {
        type: "takeaways",
        items: [
          "Rebalancing mengembalikan bobot aset ke target setelah bergeser oleh pasar.",
          "Efeknya: otomatis menjual mahal dan membeli murah secara disiplin.",
          "Bisa berbasis waktu (berkala) atau ambang (deviasi tertentu).",
          "Jangan terlalu sering karena ada biaya dan pajak; manfaatkan setoran rutin.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa tujuan utama rebalancing?",
            options: ["Memaksimalkan untung jangka pendek", "Mengembalikan bobot aset ke target agar risiko terjaga", "Menghindari pajak", "Menebak arah pasar"],
            answer: 1,
            explain: "Rebalancing menjaga komposisi dan tingkat risiko sesuai rencana.",
          },
          {
            q: "Saat saham naik melebihi target, rebalancing akan?",
            options: ["Menambah saham", "Menjual sebagian saham dan menambah aset lain", "Menjual semua aset", "Tidak berbuat apa-apa"],
            answer: 1,
            explain: "Aset yang bobotnya membengkak dipangkas kembali ke target.",
          },
          {
            q: "Mengapa rebalancing disebut mendorong beli murah jual mahal?",
            options: ["Karena menebak waktu pasar", "Karena memangkas aset yang naik dan menambah yang turun", "Karena selalu untung", "Karena bebas biaya"],
            answer: 1,
            explain: "Aset yang naik dijual sebagian, aset yang turun ditambah.",
          },
          {
            q: "Manakah pendekatan waktu untuk rebalancing?",
            options: ["Saat bobot melenceng 5%", "Setiap 12 bulan secara berkala", "Saat ada berita buruk", "Saat teman menyarankan"],
            answer: 1,
            explain: "Pendekatan waktu dilakukan pada interval tetap, misalnya tahunan.",
          },
          {
            q: "Total Rp100 juta, target obligasi 40%, kini obligasi Rp30 juta. Berapa yang harus dibeli?",
            options: ["Rp10 juta", "Rp40 juta", "Rp30 juta", "Tidak perlu beli"],
            answer: 0,
            explain: "Target = 40% x 100 = Rp40 juta. Kekurangan Rp40 - Rp30 = Rp10 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengukur-kinerja",
    levelId: "portofolio",
    order: 4,
    title: "Mengukur Kinerja: Return, Risiko, dan Sharpe Ratio Sederhana",
    summary: "Menilai portofolio bukan hanya dari return, tapi return dibanding risiko dan benchmark. Dengan Sharpe ratio sederhana.",
    durationMin: 14,
    tags: ["kinerja", "risiko", "sharpe ratio", "benchmark"],
    blocks: [
      {
        type: "paragraph",
        html: "Mengukur kinerja portofolio tidak cukup dengan melihat <strong>return</strong> saja. Return tinggi yang diraih dengan risiko sangat besar belum tentu lebih baik daripada return sedang dengan risiko kecil. Kita perlu menilai imbal hasil <strong>relatif terhadap risiko</strong> yang ditanggung dan membandingkannya dengan tolok ukur yang adil.",
      },
      {
        type: "paragraph",
        html: "Ukuran risiko yang umum adalah <strong>volatilitas</strong> (standar deviasi return). Untuk menggabungkan return dan risiko dalam satu angka, kita pakai <strong>Sharpe ratio</strong>: kelebihan return di atas aset bebas risiko dibagi volatilitas. Semakin tinggi Sharpe ratio, semakin baik imbal hasil per satuan risiko.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus Sharpe ratio sederhana",
        html: "Sharpe = (Return portofolio - Return bebas risiko) / Volatilitas. Contoh: return 12%, bebas risiko 4%, volatilitas 16%, maka Sharpe = (12 - 4) / 16 = 0,5.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Selalu bandingkan dengan benchmark",
        html: "Return 15% terdengar hebat, tetapi jika indeks acuan (benchmark) yang sebanding naik 20%, berarti portofolio Anda justru kalah. Pilih benchmark yang sejenis, misalnya indeks saham untuk portofolio saham.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Jangan tertipu return satu tahun",
        html: "Hasil satu tahun bisa karena keberuntungan. Lihat kinerja beberapa tahun dan konsistensinya, serta apakah return sepadan dengan risiko yang diambil.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dua Portofolio: Return Sama, Risiko Berbeda",
        unit: "%",
        source: "Ilustrasi edukasi",
        note: "Keduanya return 12%, tetapi Portofolio A jauh lebih bergejolak. Sharpe ratio A lebih rendah karena volatilitasnya tinggi.",
        data: [
          { label: "A: Return", value: 12, color: "#2563eb" },
          { label: "A: Volatilitas", value: 24, color: "#ef4444" },
          { label: "B: Return", value: 12, color: "#16a34a" },
          { label: "B: Volatilitas", value: 10, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua manajer, return sama",
        html: "Manajer A dan B sama-sama mencetak return 12% setahun, dengan aset bebas risiko 4%. Volatilitas A 24%, volatilitas B 10%. Sharpe A = (12 - 4) / 24 = 0,33. Sharpe B = (12 - 4) / 10 = 0,8. Walau returnnya identik, B memberikan imbal hasil jauh lebih efisien per satuan risiko, jadi B lebih unggul.",
      },
      {
        type: "calcExercise",
        prompt: "Portofolio return 14%, aset bebas risiko 5%, volatilitas 18%. Berapa Sharpe ratio-nya?",
        answer: 0.5,
        tolerance: 0.02,
        solution: "Sharpe = (14 - 5) / 18 = 9 / 18 = <strong>0,5</strong>.",
        hint: "Kurangi return bebas risiko dari return portofolio, lalu bagi dengan volatilitas.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan berikut tentang return atau tentang risiko?",
        buckets: ["Ukuran return", "Ukuran risiko"],
        items: [
          { text: "Imbal hasil tahunan 12%", bucket: "Ukuran return" },
          { text: "Volatilitas (standar deviasi) 18%", bucket: "Ukuran risiko" },
          { text: "Kenaikan nilai portofolio dalam setahun", bucket: "Ukuran return" },
          { text: "Seberapa besar nilai naik-turun dari rata-rata", bucket: "Ukuran risiko" },
        ],
      },
      { type: "widget", widget: "KalkulatorSharpe" },
      {
        type: "chart",
        variant: "bar",
        title: "Sharpe Ratio Tiga Portofolio (Bebas Risiko 4%)",
        unit: "Sharpe ratio",
        source: "Ilustrasi edukasi",
        note: "Sharpe = (return - 4%) / volatilitas. C unggul karena imbal hasil per satuan risiko paling tinggi.",
        data: [
          { label: "A: ret 12%, vol 24%", value: 0.33, color: "#ef4444" },
          { label: "B: ret 10%, vol 12%", value: 0.5, color: "#f59e0b" },
          { label: "C: ret 14%, vol 10%", value: 1.0, color: "#16a34a" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Portofolio return 9%, aset bebas risiko 3%, volatilitas 8%. Berapa Sharpe ratio-nya?",
        answer: 0.75,
        tolerance: 0.02,
        solution: "Sharpe = (9 - 3) / 8 = 6 / 8 = <strong>0,75</strong>.",
        hint: "Kurangi return bebas risiko dari return portofolio, lalu bagi dengan volatilitas.",
      },
      {
        type: "case",
        title: "Sejarah: Imbal Hasil 'Terlalu Mulus' ala Madoff",
        html: "Skema <strong>Bernie Madoff</strong> melaporkan imbal hasil positif yang sangat stabil, sekitar <strong>10-12% per tahun</strong> nyaris tanpa fluktuasi, selama bertahun-tahun. Konsistensi semacam itu menghasilkan <strong>Sharpe ratio</strong> yang tidak masuk akal tingginya dibanding pasar mana pun, sebuah sinyal bahaya yang diabaikan banyak orang sebelum skema kolaps pada 2008. Pelajarannya: imbal hasil tinggi tanpa volatilitas yang wajar justru patut dicurigai.",
      },
      {
        type: "takeaways",
        items: [
          "Nilai kinerja dari return relatif terhadap risiko, bukan return saja.",
          "Volatilitas (standar deviasi) adalah ukuran risiko yang umum.",
          "Sharpe ratio = (return - bebas risiko) / volatilitas; makin tinggi makin baik.",
          "Selalu bandingkan dengan benchmark sejenis dan lihat lebih dari satu tahun.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa return saja tidak cukup untuk menilai kinerja?",
            options: ["Karena return selalu salah", "Karena tidak memperhitungkan risiko yang ditanggung", "Karena return tidak penting", "Karena pajak"],
            answer: 1,
            explain: "Return tinggi bisa berasal dari risiko yang sangat besar.",
          },
          {
            q: "Sharpe ratio mengukur?",
            options: ["Return total saja", "Imbal hasil per satuan risiko di atas bebas risiko", "Jumlah aset", "Biaya transaksi"],
            answer: 1,
            explain: "Sharpe = (return - bebas risiko) / volatilitas, yaitu efisiensi imbal hasil terhadap risiko.",
          },
          {
            q: "Return 10%, bebas risiko 4%, volatilitas 12%. Sharpe ratio?",
            options: ["0,5", "1,2", "0,6", "6"],
            answer: 0,
            explain: "(10 - 4) / 12 = 6 / 12 = 0,5.",
          },
          {
            q: "Portofolio Anda naik 15%, benchmark sejenis naik 20%. Artinya?",
            options: ["Portofolio mengungguli pasar", "Portofolio kalah dari benchmark", "Tidak bisa dibandingkan", "Pasti rugi"],
            answer: 1,
            explain: "Naik 15% tetap kalah dari benchmark sebanding yang naik 20%.",
          },
          {
            q: "Dua portofolio return sama 12%. A volatilitas 24%, B volatilitas 10%. Mana lebih baik?",
            options: ["A, karena lebih bergejolak", "B, karena risiko lebih kecil untuk return sama", "Sama saja", "Tidak bisa ditentukan"],
            answer: 1,
            explain: "Return sama dengan risiko lebih kecil berarti Sharpe ratio lebih tinggi, jadi B lebih baik.",
          },
        ],
      },
    ],
  },
];
