import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "ebilling-bayar",
    levelId: "lapor",
    order: 1,
    title: "Cara Bayar Pajak lewat e-Billing",
    summary: "Membayar pajak kini semudah bayar tagihan online. Kenali alurnya.",
    durationMin: 9,
    tags: ["e-billing", "bayar", "praktik"],
    blocks: [
      {
        type: "paragraph",
        html: "Membayar pajak sekarang tidak perlu antre di kantor. Kamu cukup membuat <strong>kode billing</strong> secara online, lalu membayarnya seperti membayar tagihan biasa lewat m-banking, ATM, atau marketplace.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Alur 3 langkah",
        html: "1) Buat <strong>kode billing</strong> di DJP Online / Coretax (pilih jenis & masa pajak, isi jumlah). 2) Dapat kode billing 15 digit. 3) Bayar lewat bank/e-wallet, lalu simpan <strong>NTPN</strong> sebagai bukti sah.",
      },
      {
        type: "table",
        caption: "Istilah penting saat membayar",
        headers: ["Istilah", "Arti"],
        rows: [
          ["Kode billing", "Kode 15 digit untuk membayar pajak tertentu"],
          ["Kode jenis pajak (KAP/KJS)", "Kode yang menentukan jenis pajak yang dibayar"],
          ["NTPN", "Bukti bahwa pembayaran berhasil diterima negara"],
          ["Masa pajak", "Periode (bulan) yang dibayar"],
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Salah pilih jenis pajak",
        html: "Pak Yusuf membuat kode billing tapi salah memilih kode jenis pajak, sehingga uangnya tercatat untuk jenis pajak yang salah. Akibatnya kewajiban PPh finalnya tetap dianggap belum dibayar. Pelajaran: <strong>periksa kode jenis pajak dan masa pajak</strong> sebelum membuat kode billing.",
      },
      {
        type: "stats",
        items: [
          { value: "15", label: "Digit kode billing", sub: "panjang kode bayar" },
          { value: "NTPN", label: "Bukti sah", sub: "simpan setelah bayar", color: "#16a34a" },
          { value: "3", label: "Langkah bayar", sub: "buat, bayar, simpan" },
          { value: "24 jam", label: "Bisa kapan saja", sub: "lewat m-banking/e-wallet" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Kanal pembayaran pajak yang biasa dipakai UMKM (ilustrasi)",
        unit: "%",
        source: "ilustrasi",
        note: "Angka ilustrasi untuk menggambarkan ragam kanal, bukan data resmi.",
        data: [
          { label: "m-banking / mobile", value: 45, color: "#2563eb" },
          { label: "e-wallet / marketplace", value: 25, color: "#16a34a" },
          { label: "ATM", value: 20, color: "#f59e0b" },
          { label: "Teller bank / kantor pos", value: 10, color: "#94a3b8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bayar PPh final tepat waktu",
        html: "Bu Sinta beromzet Rp40 juta pada Mei. PPh final 0,5% = Rp200.000. Tanggal 12 Juni ia buka DJP Online, buat kode billing 15 digit untuk PPh Final masa Mei, lalu bayar Rp200.000 lewat m-banking. NTPN langsung terbit dan ia simpan. Karena dibayar sebelum tanggal 15, ia bebas dari bunga telat bayar. Total waktu yang dibutuhkan kurang dari 10 menit.",
      },
      {
        type: "calcExercise",
        prompt: "Omzet bulan ini Rp30.000.000. PPh Final UMKM 0,5%. Berapa nilai yang kamu isi saat membuat kode billing?",
        answer: 150000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh Final = Rp30.000.000 x 0,5% = <strong>Rp150.000</strong>. Itulah jumlah yang diisi pada kode billing.",
        hint: "Kalikan omzet dengan 0,5% (0,005).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah pembayaran dengan artinya.",
        pairs: [
          { left: "Kode billing", right: "Kode 15 digit untuk membayar" },
          { left: "NTPN", right: "Bukti pembayaran yang sah" },
          { left: "DJP Online / Coretax", right: "Tempat membuat kode billing" },
          { left: "Masa pajak", right: "Periode bulan yang dibayar" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini bagian dari proses membayar yang benar atau keliru?",
        buckets: ["Benar", "Keliru"],
        items: [
          { text: "Membuat kode billing sebelum bayar", bucket: "Benar" },
          { text: "Menyimpan NTPN setelah bayar", bucket: "Benar" },
          { text: "Mengabaikan kode jenis pajak", bucket: "Keliru" },
          { text: "Tidak mengecek masa pajak", bucket: "Keliru" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Bayar pajak kini online lewat kode billing, tanpa antre.",
          "Alur: buat kode billing, bayar, simpan NTPN.",
          "Periksa kode jenis pajak dan masa pajak agar tidak salah setor.",
          "NTPN adalah bukti pembayaran yang sah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Langkah pertama membayar pajak adalah?",
            options: ["Datang ke kantor pajak", "Membuat kode billing", "Mengisi SPT Tahunan", "Membuat faktur"],
            answer: 1,
            explain: "Kamu membuat kode billing dulu, lalu membayarnya secara online.",
          },
          {
            q: "Bukti sah bahwa pajak sudah dibayar adalah?",
            options: ["Kode billing", "NTPN", "Screenshot saja", "Email promosi"],
            answer: 1,
            explain: "NTPN (Nomor Transaksi Penerimaan Negara) adalah bukti pembayaran resmi.",
          },
          {
            q: "Kode billing terdiri dari berapa digit?",
            options: ["5", "10", "15", "20"],
            answer: 2,
            explain: "Kode billing terdiri dari 15 digit.",
          },
          {
            q: "Risiko salah memilih kode jenis pajak adalah?",
            options: [
              "Tidak ada",
              "Pembayaran tercatat untuk pajak yang salah, kewajiban dianggap belum lunas",
              "Dapat diskon",
              "Pajak jadi nol",
            ],
            answer: 1,
            explain: "Salah kode membuat setoran tercatat keliru sehingga kewajiban aslinya tetap terutang.",
          },
          {
            q: "Pajak bisa dibayar lewat?",
            options: ["Hanya kantor pajak", "m-banking, ATM, marketplace", "Hanya tunai", "Tidak bisa online"],
            answer: 1,
            explain: "Dengan kode billing, pembayaran bisa lewat berbagai kanal seperti m-banking dan marketplace.",
          },
          {
            q: "Di mana kode billing dibuat?",
            options: ["Di mesin ATM", "Di DJP Online / Coretax", "Di buku tabungan", "Di kantor pos"],
            answer: 1,
            explain: "Kode billing dibuat secara online di DJP Online atau Coretax.",
          },
          {
            q: "Omzet Rp20 juta, PPh Final 0,5%. Berapa yang diisi di kode billing?",
            options: ["Rp50.000", "Rp100.000", "Rp200.000", "Rp1.000.000"],
            answer: 1,
            explain: "Rp20.000.000 x 0,5% = Rp100.000.",
          },
          {
            q: "Apa yang menentukan jenis pajak yang dibayar pada kode billing?",
            options: ["Nomor HP", "Kode jenis pajak (KAP/KJS)", "Warna aplikasi", "Nama bank"],
            answer: 1,
            explain: "Kode jenis pajak (KAP/KJS) menentukan jenis pajak yang disetor.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "spt-lapor",
    levelId: "lapor",
    order: 2,
    title: "Lapor SPT: Masa & Tahunan",
    summary: "Bayar saja belum cukup, kamu juga wajib melapor. Kenali SPT Masa dan SPT Tahunan.",
    durationMin: 10,
    tags: ["SPT", "lapor", "tahunan"],
    blocks: [
      {
        type: "paragraph",
        html: "Membayar dan melapor adalah dua hal berbeda. <strong>SPT (Surat Pemberitahuan)</strong> adalah laporan pajakmu. Ada <strong>SPT Masa</strong> (bulanan, untuk PPN/PPh potong) dan <strong>SPT Tahunan</strong> (sekali setahun).",
      },
      {
        type: "table",
        caption: "Jenis SPT dan siapa yang wajib",
        headers: ["SPT", "Periode", "Untuk siapa"],
        rows: [
          ["SPT Tahunan OP", "Tahunan", "Semua wajib pajak orang pribadi"],
          ["SPT Tahunan Badan", "Tahunan", "PT, CV, dan badan lain"],
          ["SPT Masa PPN", "Bulanan", "PKP"],
          ["SPT Masa PPh 21/23", "Bulanan", "Yang memotong pajak karyawan/jasa"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Wajib lapor walau pajaknya Rp0",
        html: "Ini sering terlewat: <strong>SPT Tahunan tetap wajib dilaporkan walau pajakmu Rp0</strong>. Banyak UMKM kena denda bukan karena tidak bayar, tapi karena lupa lapor.",
      },
      {
        type: "case",
        title: "Studi Kasus: Lupa lapor padahal pajak nol",
        html: "Bu Eni beromzet di bawah Rp500 juta, jadi PPh finalnya Rp0. Ia merasa 'tidak ada pajak, tidak perlu lapor'. Padahal ia tetap wajib lapor SPT Tahunan. Karena tidak lapor, ia kena denda Rp100 ribu. Andai ia lapor (cukup beberapa menit online), denda itu tidak akan ada.",
      },
      {
        type: "stats",
        items: [
          { value: "1x", label: "SPT Tahunan", sub: "sekali setahun" },
          { value: "12x", label: "SPT Masa", sub: "tiap bulan bagi PKP" },
          { value: "Rp0", label: "Tetap wajib lapor", sub: "walau pajak nol", color: "#dc2626" },
          { value: "31 Mar", label: "Batas SPT OP", sub: "30 Apr untuk Badan" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Denda telat lapor per jenis SPT (nilai tetap)",
        unit: "Rp",
        source: "UU KUP Pasal 7",
        note: "Nilai denda bersifat tetap, tidak tergantung besar pajak.",
        data: [
          { label: "SPT Masa lain (mis. PPh)", value: 100000, color: "#94a3b8" },
          { label: "SPT Tahunan OP", value: 100000, color: "#2563eb" },
          { label: "SPT Masa PPN", value: 500000, color: "#f59e0b" },
          { label: "SPT Tahunan Badan", value: 1000000, color: "#dc2626" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: PT rutin lapor SPT Masa dan Tahunan",
        html: "PT Maju Jaya punya 5 karyawan dan berstatus PKP. Setiap bulan staf keuangannya lapor SPT Masa PPh 21 dan SPT Masa PPN (12 kali setahun masing-masing), lalu sekali setahun lapor SPT Tahunan Badan paling lambat 30 April. Karena disiplin, dalam setahun mereka melaporkan 24 SPT Masa plus 1 SPT Tahunan tanpa satu pun telat, sehingga nol rupiah denda lapor.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah UMKM lupa lapor SPT Tahunan OP selama 2 tahun berturut-turut. Berapa total denda telat lapornya?",
        answer: 200000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Denda SPT Tahunan OP Rp100.000 per tahun x 2 tahun = <strong>Rp200.000</strong>.",
        hint: "Denda SPT Tahunan OP Rp100.000 dikali jumlah tahun yang terlewat.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Panduan mengisi SPT Tahunan",
        html: "Ikuti panduan langkah demi langkah berikut. Centang tiap poin sambil kamu kerjakan agar tidak ada yang terlewat.",
      },
      { type: "widget", widget: "WizardSPT" },
      {
        type: "classifyExercise",
        prompt: "Laporan ini termasuk SPT Masa (bulanan) atau SPT Tahunan?",
        buckets: ["SPT Masa (bulanan)", "SPT Tahunan"],
        items: [
          { text: "Laporan PPN oleh PKP", bucket: "SPT Masa (bulanan)" },
          { text: "Laporan penghasilan setahun orang pribadi", bucket: "SPT Tahunan" },
          { text: "Laporan PPh 21 karyawan tiap bulan", bucket: "SPT Masa (bulanan)" },
          { text: "Laporan tahunan PT", bucket: "SPT Tahunan" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan SPT dengan periodenya.",
        pairs: [
          { left: "SPT Tahunan OP", right: "Sekali setahun" },
          { left: "SPT Masa PPN", right: "Setiap bulan" },
          { left: "SPT Masa PPh 21", right: "Setiap bulan" },
          { left: "SPT Tahunan Badan", right: "Sekali setahun" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Membayar dan melapor (SPT) adalah dua kewajiban berbeda.",
          "SPT Masa bersifat bulanan; SPT Tahunan sekali setahun.",
          "SPT Tahunan wajib walau pajaknya Rp0.",
          "Banyak denda terjadi karena lupa lapor, bukan karena tidak bayar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "SPT adalah?",
            options: ["Bukti bayar", "Laporan pajak", "Kartu identitas", "Kode billing"],
            answer: 1,
            explain: "SPT (Surat Pemberitahuan) adalah laporan kewajiban pajak.",
          },
          {
            q: "SPT Tahunan dilaporkan?",
            options: ["Setiap bulan", "Sekali setahun", "Setiap transaksi", "Tidak pernah"],
            answer: 1,
            explain: "SPT Tahunan dilaporkan sekali dalam setahun.",
          },
          {
            q: "Jika PPh final-mu Rp0, apakah tetap wajib lapor SPT Tahunan?",
            options: ["Tidak perlu", "Tetap wajib", "Hanya kalau diminta", "Hanya untuk PT"],
            answer: 1,
            explain: "SPT Tahunan tetap wajib dilaporkan meskipun pajaknya nol.",
          },
          {
            q: "SPT Masa PPN dilaporkan oleh?",
            options: ["Semua orang", "PKP", "Hanya karyawan", "Bank"],
            answer: 1,
            explain: "SPT Masa PPN adalah kewajiban bulanan Pengusaha Kena Pajak.",
          },
          {
            q: "Penyebab umum denda pada UMKM adalah?",
            options: [
              "Bayar terlalu banyak",
              "Lupa lapor SPT (walau pajak kecil/nol)",
              "Punya NPWP",
              "Mencatat omzet",
            ],
            answer: 1,
            explain: "Banyak denda muncul karena lupa atau telat lapor SPT, bukan karena nilai pajaknya.",
          },
          {
            q: "Denda telat lapor SPT Tahunan Badan adalah?",
            options: ["Rp100.000", "Rp500.000", "Rp1.000.000", "Rp0"],
            answer: 2,
            explain: "Denda telat lapor SPT Tahunan Badan adalah Rp1.000.000.",
          },
          {
            q: "Berapa kali setahun PKP umumnya melapor SPT Masa PPN?",
            options: ["1 kali", "4 kali", "12 kali", "Tidak pernah"],
            answer: 2,
            explain: "SPT Masa PPN bersifat bulanan, jadi 12 kali dalam setahun.",
          },
          {
            q: "Batas lapor SPT Tahunan Badan adalah?",
            options: ["31 Maret", "30 April", "31 Mei", "31 Desember"],
            answer: 1,
            explain: "SPT Tahunan Badan paling lambat 30 April.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "kalender-pajak",
    levelId: "lapor",
    order: 3,
    title: "Kalender & Tenggat Pajak",
    summary: "Hafalkan beberapa tanggal penting ini agar tidak pernah telat.",
    durationMin: 8,
    tags: ["tenggat", "kalender", "jatuh tempo"],
    blocks: [
      {
        type: "paragraph",
        html: "Kunci agar bebas denda itu sederhana: <strong>tahu tanggalnya</strong>. Berikut tenggat yang paling sering ditemui UMKM. Catat di kalender atau pasang pengingat.",
      },
      {
        type: "video",
        comp: "KalenderPajak",
        title: "Video: Kalender Pajak UMKM",
        caption: "Animasi tenggat penting: tanggal 15, 31 Maret, 30 April, dan lainnya.",
      },
      {
        type: "table",
        caption: "Tenggat pajak yang sering ditemui UMKM",
        headers: ["Kewajiban", "Bayar paling lambat", "Lapor paling lambat"],
        rows: [
          ["PPh Final UMKM (bulanan)", "Tgl 15 bulan berikutnya", "Cukup lewat validasi NTPN"],
          ["PPh 21 (bulanan)", "Tgl 10 bulan berikutnya", "Tgl 20 bulan berikutnya"],
          ["PPN (bulanan, PKP)", "Sebelum lapor", "Akhir bulan berikutnya"],
          ["SPT Tahunan Orang Pribadi", "Sebelum lapor", "31 Maret"],
          ["SPT Tahunan Badan", "Sebelum lapor", "30 April"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua tanggal yang wajib diingat UMKM",
        html: "<strong>Tanggal 15</strong>: batas bayar PPh Final bulanan. <strong>31 Maret</strong>: batas lapor SPT Tahunan Orang Pribadi. Dua ini saja sudah menyelamatkan mayoritas UMKM dari denda.",
      },
      {
        type: "case",
        title: "Studi Kasus: Pengingat sederhana",
        html: "Pak Rudi memasang dua alarm berulang di HP: tanggal 13 tiap bulan ('siapkan & bayar PPh final') dan 1 Maret ('mulai isi SPT Tahunan'). Sejak itu ia tidak pernah lagi kena denda. Solusi kecil yang sangat efektif.",
      },
      {
        type: "stats",
        items: [
          { value: "Tgl 15", label: "Bayar PPh Final", sub: "bulan berikutnya", color: "#2563eb" },
          { value: "Tgl 10", label: "Bayar PPh 21", sub: "bulan berikutnya" },
          { value: "31 Mar", label: "SPT Tahunan OP", sub: "sekali setahun", color: "#16a34a" },
          { value: "30 Apr", label: "SPT Tahunan Badan", sub: "sekali setahun" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tanggal jatuh tempo kewajiban bulanan UMKM",
        unit: "tanggal",
        source: "ilustrasi tenggat umum",
        note: "Angka menunjukkan tanggal batas pada bulan berikutnya.",
        data: [
          { label: "Bayar PPh 21", value: 10, color: "#94a3b8" },
          { label: "Bayar PPh Final UMKM", value: 15, color: "#2563eb" },
          { label: "Lapor PPh 21", value: 20, color: "#f59e0b" },
          { label: "Lapor PPN (akhir bulan)", value: 30, color: "#dc2626" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Telat sehari tetap dihitung telat",
        html: "Pak Andi baru membayar PPh Final masa Juni pada tanggal 16 Juli, padahal batasnya tanggal 15. Meski hanya selisih satu hari, sistem tetap mencatatnya sebagai telat dan keterlambatan dihitung sebagai 1 bulan penuh untuk perhitungan bunga. Pelajaran: jangan menunda sampai mepet tenggat, sediakan jeda 2 sampai 3 hari sebelum tanggal 15.",
      },
      {
        type: "calcExercise",
        prompt: "Hari ini tanggal 1 Maret. Berapa hari tersisa sampai batas lapor SPT Tahunan Orang Pribadi (31 Maret)?",
        answer: 30,
        tolerance: 0,
        suffix: " hari",
        solution: "Dari 1 Maret ke 31 Maret = 31 - 1 = <strong>30 hari</strong> tersisa. Manfaatkan untuk menyiapkan SPT tanpa terburu-buru.",
        hint: "Kurangi tanggal batas (31) dengan tanggal hari ini (1).",
      },
      {
        type: "classifyExercise",
        prompt: "Kewajiban ini bersifat bulanan atau tahunan?",
        buckets: ["Bulanan", "Tahunan"],
        items: [
          { text: "Bayar PPh Final UMKM", bucket: "Bulanan" },
          { text: "Lapor SPT Tahunan Orang Pribadi", bucket: "Tahunan" },
          { text: "Setor PPh 21 karyawan", bucket: "Bulanan" },
          { text: "Lapor SPT Tahunan Badan", bucket: "Tahunan" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kewajiban dengan tenggatnya.",
        pairs: [
          { left: "PPh Final UMKM (bayar)", right: "Tanggal 15 bulan berikutnya" },
          { left: "SPT Tahunan Orang Pribadi", right: "31 Maret" },
          { left: "SPT Tahunan Badan", right: "30 April" },
          { left: "SPT Masa PPN (lapor)", right: "Akhir bulan berikutnya" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Bebas denda dimulai dari tahu tanggalnya.",
          "Tanggal 15: batas bayar PPh Final bulanan.",
          "31 Maret: batas lapor SPT Tahunan Orang Pribadi; 30 April untuk Badan.",
          "Pasang pengingat berulang agar tidak pernah telat.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Batas bayar PPh Final UMKM bulanan adalah?",
            options: ["Tanggal 1", "Tanggal 15 bulan berikutnya", "Akhir tahun", "Tanggal 31"],
            answer: 1,
            explain: "PPh Final dibayar paling lambat tanggal 15 bulan berikutnya.",
          },
          {
            q: "Batas lapor SPT Tahunan Orang Pribadi adalah?",
            options: ["31 Januari", "31 Maret", "30 April", "31 Desember"],
            answer: 1,
            explain: "SPT Tahunan Orang Pribadi paling lambat 31 Maret.",
          },
          {
            q: "Batas lapor SPT Tahunan Badan adalah?",
            options: ["31 Maret", "30 April", "30 Juni", "31 Desember"],
            answer: 1,
            explain: "SPT Tahunan Badan paling lambat 30 April.",
          },
          {
            q: "Cara paling praktis agar tidak telat adalah?",
            options: [
              "Mengandalkan ingatan",
              "Memasang pengingat/alarm berulang",
              "Menunggu surat dari kantor pajak",
              "Tidak melakukan apa-apa",
            ],
            answer: 1,
            explain: "Pengingat berulang di HP efektif mencegah keterlambatan.",
          },
          {
            q: "Dua tanggal terpenting bagi mayoritas UMKM adalah?",
            options: [
              "Tanggal 1 dan 31 Desember",
              "Tanggal 15 (bayar PPh final) dan 31 Maret (SPT Tahunan OP)",
              "Tanggal 10 dan 20",
              "Tidak ada yang penting",
            ],
            answer: 1,
            explain: "Tanggal 15 untuk bayar PPh final bulanan dan 31 Maret untuk SPT Tahunan OP menutup sebagian besar kewajiban UMKM.",
          },
          {
            q: "Batas bayar PPh 21 (memotong gaji karyawan) adalah?",
            options: ["Tanggal 10 bulan berikutnya", "Tanggal 15", "Tanggal 20", "Akhir tahun"],
            answer: 0,
            explain: "PPh 21 disetor paling lambat tanggal 10 bulan berikutnya.",
          },
          {
            q: "Membayar PPh Final pada tanggal 16 (batas tanggal 15) dianggap?",
            options: ["Tepat waktu", "Telat, dihitung 1 bulan", "Tidak masalah", "Lebih awal"],
            answer: 1,
            explain: "Lewat tanggal 15 sudah dihitung telat, dan keterlambatan dihitung per bulan penuh.",
          },
          {
            q: "SPT Masa PPN dilaporkan paling lambat?",
            options: ["Tanggal 10", "Tanggal 15", "Akhir bulan berikutnya", "31 Maret"],
            answer: 2,
            explain: "SPT Masa PPN dilaporkan paling lambat akhir bulan berikutnya.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "denda-sanksi",
    levelId: "lapor",
    order: 4,
    title: "Denda & Sanksi: Hindari, Bukan Takuti",
    summary: "Telat itu mahal, tapi mudah dihindari. Hitung sendiri kerugiannya dengan simulator.",
    durationMin: 11,
    tags: ["denda", "sanksi", "kepatuhan"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagian ini bukan untuk menakuti, tapi menyadarkan: <strong>denda telat jauh lebih besar daripada pajaknya</strong>. Ada dua jenis: denda telat <strong>lapor</strong> (nilai tetap) dan bunga telat <strong>bayar</strong> (per bulan).",
      },
      {
        type: "video",
        comp: "DendaTumbuh",
        title: "Video: Denda yang Terus Membesar",
        caption: "Animasi: makin lama menunda, makin besar bunga telat bayarnya.",
      },
      {
        type: "table",
        caption: "Denda telat lapor SPT (nilai tetap)",
        headers: ["Jenis SPT", "Denda"],
        rows: [
          ["SPT Masa PPN", "Rp500.000"],
          ["SPT Masa lainnya (mis. PPh)", "Rp100.000"],
          ["SPT Tahunan Orang Pribadi", "Rp100.000"],
          ["SPT Tahunan Badan", "Rp1.000.000"],
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Telat bayar kena bunga",
        html: "Selain denda lapor, telat <strong>bayar</strong> dikenai bunga per bulan (tarifnya ditetapkan bulanan oleh Menteri Keuangan), dihitung sampai maksimal 24 bulan. Makin lama menunda, makin besar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hitung kerugiannya",
        html: "Pakai simulator ini untuk melihat total denda bila telat. Angkanya sering mengejutkan, dan itu justru memotivasi untuk tepat waktu.",
      },
      { type: "widget", widget: "SimulatorDendaPajak" },
      {
        type: "case",
        title: "Studi Kasus: Telat setahun",
        html: "Sebuah CV telat lapor SPT Tahunan Badan (denda Rp1 juta) dan telat membayar pajak Rp10 juta selama 12 bulan. Dengan bunga sekitar 1,1% per bulan, bunga telat bayarnya sekitar Rp1,32 juta. Total kerugian sekitar <strong>Rp2,32 juta</strong>, hanya karena menunda. Padahal lapor dan bayar tepat waktu gratis.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Pertumbuhan bunga telat bayar (pajak Rp10 juta, bunga 1,1%/bulan)",
        unit: "Rp",
        source: "ilustrasi, tarif 1,1%/bulan",
        note: "Ilustrasi: makin lama menunda, makin besar bunganya. Bunga dihitung maksimal 24 bulan.",
        data: [
          { label: "Bln 1", value: 110000, color: "#fca5a5" },
          { label: "Bln 2", value: 220000, color: "#f87171" },
          { label: "Bln 3", value: 330000, color: "#f87171" },
          { label: "Bln 6", value: 660000, color: "#ef4444" },
          { label: "Bln 9", value: 990000, color: "#dc2626" },
          { label: "Bln 12", value: 1320000, color: "#b91c1c" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "Rp1 jt", label: "Denda SPT Badan", sub: "telat lapor", color: "#dc2626" },
          { value: "Rp100 rb", label: "Denda SPT OP", sub: "telat lapor" },
          { value: "1,1%", label: "Bunga per bulan", sub: "ilustrasi telat bayar", color: "#f59e0b" },
          { value: "24 bln", label: "Batas bunga", sub: "maksimal dihitung" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua keterlambatan sekaligus",
        html: "Bu Wati telat lapor SPT Tahunan OP (denda Rp100.000) dan telat membayar PPh Rp4.000.000 selama 5 bulan. Bunga telat bayar = Rp4.000.000 x 1,1% x 5 = Rp220.000. Total beban = Rp100.000 + Rp220.000 = <strong>Rp320.000</strong>. Jika ia lapor dan bayar tepat waktu, semua biaya ini bernilai Rp0.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis SPT dengan denda telat lapornya.",
        pairs: [
          { left: "SPT Tahunan Orang Pribadi", right: "Rp100.000" },
          { left: "SPT Tahunan Badan", right: "Rp1.000.000" },
          { left: "SPT Masa PPN", right: "Rp500.000" },
          { left: "SPT Masa lainnya (mis. PPh)", right: "Rp100.000" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Telat bayar pajak Rp5.000.000 selama 4 bulan, bunga 1,1% per bulan. Berapa total bunga telat bayar?",
        answer: 220000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Bunga = Rp5.000.000 x 1,1% x 4 bulan = Rp55.000 x 4 = <strong>Rp220.000</strong>.",
        hint: "Kalikan pokok x tarif bulanan x jumlah bulan.",
      },
      {
        type: "classifyExercise",
        prompt: "Denda ini termasuk denda telat lapor atau bunga telat bayar?",
        buckets: ["Denda telat lapor", "Bunga telat bayar"],
        items: [
          { text: "Rp100.000 karena telat lapor SPT Tahunan OP", bucket: "Denda telat lapor" },
          { text: "Bunga 1,1% per bulan atas pajak yang belum dibayar", bucket: "Bunga telat bayar" },
          { text: "Rp500.000 karena telat lapor SPT Masa PPN", bucket: "Denda telat lapor" },
          { text: "Tambahan karena pajak baru dibayar 6 bulan kemudian", bucket: "Bunga telat bayar" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Denda telat sering lebih besar daripada pajaknya sendiri.",
          "Denda telat lapor bernilai tetap (mis. SPT Tahunan OP Rp100 ribu).",
          "Telat bayar kena bunga per bulan, hingga 24 bulan.",
          "Cara termurah selalu: lapor dan bayar tepat waktu.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Denda telat lapor SPT Tahunan Orang Pribadi adalah?",
            options: ["Rp100.000", "Rp500.000", "Rp1.000.000", "Rp0"],
            answer: 0,
            explain: "Denda telat lapor SPT Tahunan Orang Pribadi adalah Rp100.000.",
          },
          {
            q: "Denda telat lapor SPT Tahunan Badan adalah?",
            options: ["Rp100.000", "Rp500.000", "Rp1.000.000", "Rp50.000"],
            answer: 2,
            explain: "Denda telat lapor SPT Tahunan Badan adalah Rp1.000.000.",
          },
          {
            q: "Denda telat lapor SPT Masa PPN adalah?",
            options: ["Rp100.000", "Rp500.000", "Rp1.000.000", "Rp0"],
            answer: 1,
            explain: "Denda telat lapor SPT Masa PPN adalah Rp500.000.",
          },
          {
            q: "Telat bayar pajak dikenai?",
            options: ["Denda tetap saja", "Bunga per bulan", "Tidak ada sanksi", "Diskon"],
            answer: 1,
            explain: "Telat bayar dikenai bunga per bulan, ditetapkan bulanan, hingga maksimal 24 bulan.",
          },
          {
            q: "Telat bayar Rp10 juta selama 3 bulan, bunga 1,1%/bulan. Bunga totalnya?",
            options: ["Rp330.000", "Rp110.000", "Rp1.100.000", "Rp33.000"],
            answer: 0,
            explain: "Rp10.000.000 x 1,1% x 3 = Rp110.000 x 3 = Rp330.000.",
          },
          {
            q: "Bunga telat bayar dihitung maksimal berapa bulan?",
            options: ["6 bulan", "12 bulan", "24 bulan", "Tanpa batas"],
            answer: 2,
            explain: "Bunga telat bayar dihitung paling lama 24 bulan.",
          },
          {
            q: "Telat bayar Rp2 juta selama 5 bulan, bunga 1,1%/bulan. Bunga totalnya?",
            options: ["Rp22.000", "Rp110.000", "Rp220.000", "Rp1.100.000"],
            answer: 1,
            explain: "Rp2.000.000 x 1,1% x 5 = Rp22.000 x 5 = Rp110.000.",
          },
          {
            q: "Mana yang nilainya tetap (tidak tergantung lama menunda)?",
            options: [
              "Bunga telat bayar",
              "Denda telat lapor SPT",
              "Keduanya tetap",
              "Keduanya per bulan",
            ],
            answer: 1,
            explain: "Denda telat lapor bernilai tetap; bunga telat bayar bertambah tiap bulan.",
          },
        ],
      },
    ],
  },
];
