import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "pph21-karyawan",
    levelId: "karyawan",
    order: 1,
    title: "PPh 21: Pajak Gaji Karyawan",
    summary: "Saat UMKM mulai menggaji orang, kamu memotong PPh 21 dari gajinya. Dengan simulator.",
    durationMin: 12,
    tags: ["PPh 21", "karyawan", "gaji"],
    blocks: [
      {
        type: "paragraph",
        html: "Begitu usahamu menggaji karyawan, kamu menjadi <strong>pemotong PPh 21</strong>: memotong pajak dari gaji karyawan, lalu menyetorkannya ke negara. Tenang, gaji kecil sering kali tidak kena pajak sama sekali karena ada <strong>PTKP</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Konsep singkat",
        html: "Pajak dihitung dari penghasilan setahun dikurangi <strong>PTKP (Penghasilan Tidak Kena Pajak)</strong>. Bila gaji setahun masih di bawah PTKP, PPh 21 = Rp0.",
      },
      {
        type: "video",
        comp: "TarifProgresif",
        title: "Video: Tarif Progresif PPh",
        caption: "Animasi anak tangga tarif: tiap lapisan penghasilan dikenai tarifnya sendiri.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser gaji bulanan dan pilih status karyawan untuk melihat perkiraan potongan PPh 21.",
      },
      { type: "widget", widget: "SimulatorPPh21" },
      {
        type: "chart",
        variant: "bar",
        title: "Gaji Setahun vs PTKP Lajang (ilustrasi)",
        unit: "Rp juta setahun",
        source: "ilustrasi",
        note: "Garis PTKP lajang Rp54 juta: gaji di bawahnya berarti PPh 21 Rp0.",
        data: [
          { label: "Gaji 4jt/bln", value: 48, color: "#22c55e" },
          { label: "PTKP TK/0", value: 54, color: "#94a3b8" },
          { label: "Gaji 8jt/bln", value: 96, color: "#ef4444" },
          { label: "Gaji 12jt/bln", value: 144, color: "#ef4444" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "Rp54 jt", label: "PTKP lajang setahun", sub: "batas bebas pajak", color: "#2563eb" },
          { value: "5%", label: "Tarif lapisan pertama", sub: "PKP s.d Rp60 juta" },
          { value: "Rp0", label: "PPh 21 bila gaji di bawah PTKP", sub: "tetap dicatat", color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Barista bergaji UMR",
        html: "Mbak Sinta menggaji barista Rp4 juta per bulan (Rp48 juta setahun), status lajang (PTKP Rp54 juta). Karena penghasilan setahun di bawah PTKP, <strong>PPh 21-nya Rp0</strong>. Mbak Sinta tetap mencatatnya, tapi tidak ada pajak yang dipotong. Banyak karyawan UMKM berada di posisi ini.",
      },
      {
        type: "case",
        title: "Studi Kasus: Supervisor bergaji di atas PTKP",
        html: "Pak Doni menggaji supervisor Rp8 juta per bulan (Rp96 juta setahun), status lajang (TK/0, PTKP Rp54 juta). Penghasilan kena pajaknya kira-kira Rp96 juta - Rp54 juta = <strong>Rp42 juta</strong>. Karena masih di lapisan pertama, tarifnya 5%, sehingga PPh 21 setahun sekitar 5% x Rp42 juta = <strong>Rp2,1 juta</strong> atau sekitar Rp175 ribu per bulan. Inilah yang dipotong dan disetorkan Pak Doni.",
      },
      {
        type: "calcExercise",
        prompt: "Karyawan bergaji Rp4.000.000 sebulan. Berapa penghasilan brutonya setahun?",
        answer: 48000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Bruto setahun = Rp4.000.000 x 12 = <strong>Rp48.000.000</strong>. Karena di bawah PTKP lajang (Rp54 juta), PPh 21-nya Rp0.",
        hint: "Kalikan gaji bulanan dengan 12.",
      },
      {
        type: "classifyExercise",
        prompt: "Berdasarkan gaji setahun vs PTKP lajang (Rp54 juta), kena PPh 21 atau tidak?",
        buckets: ["Kena PPh 21", "Tidak kena (di bawah PTKP)"],
        items: [
          { text: "Gaji Rp4 juta/bulan (Rp48 juta setahun)", bucket: "Tidak kena (di bawah PTKP)" },
          { text: "Gaji Rp8 juta/bulan (Rp96 juta setahun)", bucket: "Kena PPh 21" },
          { text: "Gaji Rp3,5 juta/bulan", bucket: "Tidak kena (di bawah PTKP)" },
          { text: "Gaji Rp12 juta/bulan", bucket: "Kena PPh 21" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Karyawan lajang (PTKP Rp54 juta) berpenghasilan neto Rp74 juta setahun. Penghasilan Kena Pajak (PKP)-nya berapa?",
        answer: 20000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PKP = Neto - PTKP = Rp74.000.000 - Rp54.000.000 = <strong>Rp20.000.000</strong>. Masih di lapisan 5%, jadi PPh 21 setahun = Rp1.000.000.",
        hint: "Kurangkan PTKP lajang Rp54 juta dari penghasilan neto.",
      },
      {
        type: "takeaways",
        items: [
          "Memberi gaji menjadikan kamu pemotong PPh 21.",
          "Pajak dihitung dari penghasilan setahun dikurangi PTKP.",
          "Gaji di bawah PTKP berarti PPh 21 Rp0.",
          "Banyak karyawan UMKM tidak kena pajak karena gaji di bawah PTKP.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Siapa yang memotong PPh 21 karyawan?",
            options: ["Karyawan sendiri", "Pemberi kerja (pemilik usaha)", "Bank", "Pelanggan"],
            answer: 1,
            explain: "Pemberi kerja memotong PPh 21 dari gaji karyawan lalu menyetorkannya.",
          },
          {
            q: "PTKP adalah?",
            options: [
              "Pajak tambahan",
              "Penghasilan Tidak Kena Pajak (batas bebas pajak)",
              "Potongan gaji wajib",
              "Tunjangan",
            ],
            answer: 1,
            explain: "PTKP adalah batas penghasilan yang tidak kena pajak.",
          },
          {
            q: "Gaji setahun di bawah PTKP berarti PPh 21?",
            options: ["Tetap besar", "Rp0", "Naik dua kali", "Dihitung dari omzet"],
            answer: 1,
            explain: "Jika penghasilan di bawah PTKP, tidak ada PPh 21 yang dipotong.",
          },
          {
            q: "Gaji Rp4,5 juta/bulan. Bruto setahun?",
            options: ["Rp54 juta", "Rp45 juta", "Rp4,5 juta", "Rp48 juta"],
            answer: 0,
            explain: "Rp4,5 juta x 12 = Rp54 juta.",
          },
          {
            q: "PPh 21 dihitung berdasarkan?",
            options: ["Omzet usaha", "Penghasilan karyawan dikurangi PTKP", "Jumlah karyawan", "Aset usaha"],
            answer: 1,
            explain: "Dasarnya adalah penghasilan kena pajak karyawan, yaitu penghasilan neto dikurangi PTKP.",
          },
          {
            q: "Tarif lapisan pertama PPh Pasal 17 (PKP s.d Rp60 juta) adalah?",
            options: ["0,5%", "5%", "15%", "25%"],
            answer: 1,
            explain: "Lapisan pertama tarif progresif Pasal 17 adalah 5% untuk PKP sampai dengan Rp60 juta.",
          },
          {
            q: "Karyawan lajang neto Rp74 juta (PTKP Rp54 juta). Berapa PKP-nya?",
            options: ["Rp20 juta", "Rp74 juta", "Rp54 juta", "Rp128 juta"],
            answer: 0,
            explain: "PKP = Rp74 juta - Rp54 juta = Rp20 juta.",
          },
          {
            q: "PPh 21 yang sudah dipotong pemberi kerja disetorkan ke?",
            options: ["Karyawan", "Negara (kas negara)", "Bank pribadi", "Pelanggan"],
            answer: 1,
            explain: "Pemberi kerja menyetorkan PPh 21 yang dipotong ke kas negara, bukan menahannya.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "ptkp-status",
    levelId: "karyawan",
    order: 2,
    title: "PTKP & Status Keluarga",
    summary: "Besar PTKP tergantung status kawin dan jumlah tanggungan. Makin besar PTKP, makin kecil pajak.",
    durationMin: 11,
    tags: ["PTKP", "status", "tanggungan"],
    blocks: [
      {
        type: "paragraph",
        html: "Besarnya <strong>PTKP</strong> tidak sama untuk setiap orang. Ia bertambah jika karyawan sudah kawin dan punya tanggungan. Makin besar PTKP, makin kecil pajaknya.",
      },
      {
        type: "table",
        caption: "Daftar PTKP per status (setahun)",
        headers: ["Status", "Arti", "PTKP"],
        rows: [
          ["TK/0", "Lajang, tanpa tanggungan", "Rp54.000.000"],
          ["K/0", "Kawin, tanpa tanggungan", "Rp58.500.000"],
          ["K/1", "Kawin, 1 tanggungan", "Rp63.000.000"],
          ["K/2", "Kawin, 2 tanggungan", "Rp67.500.000"],
          ["K/3", "Kawin, 3 tanggungan", "Rp72.000.000"],
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Komponennya",
        html: "Diri WP Rp54 juta + status kawin Rp4,5 juta + tiap tanggungan Rp4,5 juta (maksimal 3 tanggungan).",
      },
      {
        type: "chart",
        variant: "bar",
        title: "PTKP Naik Sesuai Status",
        unit: "Rp juta setahun",
        source: "ketentuan PTKP",
        note: "Makin banyak tanggungan, makin besar penghasilan yang bebas pajak.",
        data: [
          { label: "TK/0", value: 54 },
          { label: "K/0", value: 58.5 },
          { label: "K/1", value: 63 },
          { label: "K/2", value: 67.5 },
          { label: "K/3", value: 72 },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "Rp54 jt", label: "Diri wajib pajak", sub: "komponen dasar", color: "#2563eb" },
          { value: "+Rp4,5 jt", label: "Status kawin", sub: "tambahan", color: "#22c55e" },
          { value: "+Rp4,5 jt", label: "Tiap tanggungan", sub: "maksimal 3 orang", color: "#22c55e" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Lihat pengaruh status",
        html: "Pada simulator, ubah status karyawan dan amati bagaimana PPh 21-nya ikut berubah.",
      },
      { type: "widget", widget: "SimulatorPPh21" },
      {
        type: "case",
        title: "Studi Kasus: Status mengubah pajak",
        html: "Dua karyawan bergaji sama Rp6 juta/bulan (Rp72 juta setahun). Yang lajang (TK/0, PTKP Rp54 juta) punya penghasilan kena pajak lebih besar sehingga PPh-nya ada. Yang kawin dengan 3 tanggungan (K/3, PTKP Rp72 juta) penghasilannya pas di PTKP, sehingga PPh 21-nya nyaris nol. Status keluarga benar-benar berpengaruh.",
      },
      {
        type: "case",
        title: "Studi Kasus: Selisih pajak karena tanggungan",
        html: "Bu Rina karyawati dengan penghasilan neto Rp70 juta setahun. Saat masih lajang (TK/0, PTKP Rp54 juta), PKP-nya Rp16 juta dan PPh 21 = 5% x Rp16 juta = <strong>Rp800 ribu</strong>. Setelah menikah dan punya 1 anak (K/1, PTKP Rp63 juta), PKP-nya turun jadi Rp7 juta dan PPh 21 = 5% x Rp7 juta = <strong>Rp350 ribu</strong>. Hanya karena status berubah, pajaknya turun Rp450 ribu setahun.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan status dengan nilai PTKP-nya.",
        pairs: [
          { left: "TK/0", right: "Rp54 juta" },
          { left: "K/0", right: "Rp58,5 juta" },
          { left: "K/1", right: "Rp63 juta" },
          { left: "K/3", right: "Rp72 juta" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Karyawan status K/2 (PTKP Rp67,5 juta) berpenghasilan neto Rp80 juta setahun. Berapa Penghasilan Kena Pajak (PKP)-nya?",
        answer: 12500000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PKP = Neto − PTKP = Rp80.000.000 − Rp67.500.000 = <strong>Rp12.500.000</strong>. Pajaknya 5% dari angka ini.",
        hint: "Kurangkan PTKP dari penghasilan neto.",
      },
      {
        type: "classifyExercise",
        prompt: "Pasangkan kondisi karyawan dengan besar PTKP setahunnya.",
        buckets: ["Rp54 juta", "Rp58,5 juta", "Rp67,5 juta"],
        items: [
          { text: "Lajang tanpa tanggungan (TK/0)", bucket: "Rp54 juta" },
          { text: "Kawin tanpa tanggungan (K/0)", bucket: "Rp58,5 juta" },
          { text: "Kawin dengan 2 tanggungan (K/2)", bucket: "Rp67,5 juta" },
          { text: "Bujangan baru lulus, belum punya tanggungan", bucket: "Rp54 juta" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "PTKP bertambah sesuai status kawin dan jumlah tanggungan.",
          "TK/0 = Rp54 juta; tiap komponen menambah Rp4,5 juta (maks 3 tanggungan).",
          "Makin besar PTKP, makin kecil PPh 21.",
          "PKP = penghasilan neto dikurangi PTKP.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "PTKP untuk lajang tanpa tanggungan (TK/0) adalah?",
            options: ["Rp4,5 juta", "Rp54 juta", "Rp72 juta", "Rp500 juta"],
            answer: 1,
            explain: "PTKP dasar untuk diri wajib pajak adalah Rp54 juta setahun.",
          },
          {
            q: "Tiap tanggungan menambah PTKP sebesar?",
            options: ["Rp4,5 juta", "Rp54 juta", "Rp1 juta", "Rp10 juta"],
            answer: 0,
            explain: "Status kawin dan tiap tanggungan masing-masing menambah Rp4,5 juta (maks 3 tanggungan).",
          },
          {
            q: "Makin besar PTKP, maka pajaknya?",
            options: ["Makin besar", "Makin kecil", "Tetap", "Nol selalu"],
            answer: 1,
            explain: "PTKP mengurangi penghasilan kena pajak, jadi makin besar PTKP makin kecil pajaknya.",
          },
          {
            q: "PTKP status K/3 adalah?",
            options: ["Rp54 juta", "Rp63 juta", "Rp72 juta", "Rp90 juta"],
            answer: 2,
            explain: "K/3 = Rp54 + 4,5 (kawin) + 13,5 (3 tanggungan) = Rp72 juta.",
          },
          {
            q: "Neto Rp70 juta, status TK/0 (PTKP Rp54 juta). PKP-nya?",
            options: ["Rp16 juta", "Rp70 juta", "Rp54 juta", "Rp124 juta"],
            answer: 0,
            explain: "PKP = 70 juta − 54 juta = Rp16 juta.",
          },
          {
            q: "Maksimal jumlah tanggungan yang diakui untuk menambah PTKP adalah?",
            options: ["1 orang", "2 orang", "3 orang", "Tak terbatas"],
            answer: 2,
            explain: "Tanggungan yang menambah PTKP dibatasi maksimal 3 orang.",
          },
          {
            q: "PTKP status K/1 adalah?",
            options: ["Rp54 juta", "Rp58,5 juta", "Rp63 juta", "Rp67,5 juta"],
            answer: 2,
            explain: "K/1 = Rp54 + 4,5 (kawin) + 4,5 (1 tanggungan) = Rp63 juta.",
          },
          {
            q: "Karyawan K/2 (PTKP Rp67,5 juta) neto Rp67,5 juta. Berapa PKP-nya?",
            options: ["Rp0", "Rp67,5 juta", "Rp4,5 juta", "Rp13,5 juta"],
            answer: 0,
            explain: "Neto pas sama dengan PTKP, jadi PKP = Rp0 dan PPh 21-nya Rp0.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "pph23-jasa",
    levelId: "karyawan",
    order: 3,
    title: "PPh 23: Saat Membayar Jasa Pihak Lain",
    summary: "Ketika usahamu membayar jasa ke pihak lain, sering ada kewajiban memotong PPh 23.",
    durationMin: 10,
    tags: ["PPh 23", "jasa", "potong"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>PPh 23</strong> muncul saat usahamu (terutama jika berbentuk badan) <strong>membayar jasa</strong> ke pihak lain, misalnya jasa desain, konsultan, servis, atau sewa peralatan. Kamu memotong sebagian pembayaran sebagai pajak, lalu menyetorkannya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tarif singkat PPh 23",
        html: "Umumnya <strong>2%</strong> dari nilai jasa (bila penerima ber-NPWP). Tanpa NPWP, tarifnya naik jadi <strong>4%</strong>. Untuk dividen, bunga, royalti tertentu tarifnya 15%.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "PPh 23 atas Jasa Rp10 Juta: Ber-NPWP vs Tanpa NPWP (ilustrasi)",
        unit: "Rp ribu",
        source: "ilustrasi",
        note: "Tanpa NPWP, tarif naik 100% sehingga potongan dua kali lipat.",
        data: [
          { label: "Ber-NPWP (2%)", value: 200, color: "#22c55e" },
          { label: "Tanpa NPWP (4%)", value: 400, color: "#ef4444" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "2%", label: "Tarif jasa ber-NPWP", sub: "tarif umum", color: "#22c55e" },
          { value: "4%", label: "Tarif jasa tanpa NPWP", sub: "naik 100%", color: "#ef4444" },
          { value: "15%", label: "Dividen, bunga, royalti", sub: "objek tertentu", color: "#2563eb" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membayar jasa desain",
        html: "PT Kreatif membayar jasa desain Rp10 juta ke seorang freelancer ber-NPWP. PT Kreatif wajib memotong PPh 23 sebesar 2% = Rp200 ribu. Jadi freelancer menerima Rp9,8 juta, dan Rp200 ribu disetor PT Kreatif ke negara atas nama freelancer (yang nanti jadi kredit pajak bagi si freelancer). Freelancer juga menerima <strong>bukti potong</strong> sebagai catatannya.",
      },
      {
        type: "case",
        title: "Studi Kasus: Vendor servis tanpa NPWP",
        html: "PT Boga memakai jasa servis mesin produksi senilai Rp25 juta dari sebuah bengkel yang <strong>tidak ber-NPWP</strong>. Karena tanpa NPWP, tarifnya 4%, sehingga PPh 23 yang dipotong = 4% x Rp25 juta = <strong>Rp1.000.000</strong> (dua kali lipat dibanding bila ber-NPWP yang hanya Rp500 ribu). Bengkel menerima Rp24 juta. Memiliki NPWP membuat vendor dipotong lebih kecil.",
      },
      {
        type: "calcExercise",
        prompt: "Membayar jasa konsultan Rp15.000.000 ke pihak ber-NPWP. Berapa PPh 23 (2%) yang dipotong?",
        answer: 300000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh 23 = 2% x Rp15.000.000 = <strong>Rp300.000</strong>. Konsultan menerima Rp14.700.000.",
        hint: "Kalikan nilai jasa dengan 2%.",
      },
      {
        type: "calcExercise",
        prompt: "Jasa Rp15.000.000 tetapi penerima TIDAK ber-NPWP (tarif 4%). Berapa PPh 23 yang dipotong?",
        answer: 600000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh 23 = 4% x Rp15.000.000 = <strong>Rp600.000</strong> (tarif naik 100% tanpa NPWP).",
        hint: "Tanpa NPWP, tarif menjadi 4%.",
      },
      {
        type: "classifyExercise",
        prompt: "Pembayaran ini umumnya kena PPh 23 atau tidak?",
        buckets: ["Kena PPh 23", "Bukan objek PPh 23"],
        items: [
          { text: "Bayar jasa konsultan", bucket: "Kena PPh 23" },
          { text: "Bayar jasa servis mesin", bucket: "Kena PPh 23" },
          { text: "Beli barang dagangan (bukan jasa)", bucket: "Bukan objek PPh 23" },
          { text: "Bayar gaji karyawan sendiri", bucket: "Bukan objek PPh 23" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan nilai jasa (ber-NPWP, tarif 2%) dengan PPh 23 yang dipotong.",
        pairs: [
          { left: "Jasa Rp5 juta", right: "Rp100.000" },
          { left: "Jasa Rp10 juta", right: "Rp200.000" },
          { left: "Jasa Rp25 juta", right: "Rp500.000" },
          { left: "Jasa Rp50 juta", right: "Rp1.000.000" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "PPh 23 muncul saat membayar jasa ke pihak lain.",
          "Tarif umum 2% (ber-NPWP), naik jadi 4% tanpa NPWP.",
          "Yang dibayar jasa menerima bukti potong sebagai kredit pajaknya.",
          "Pembelian barang dan gaji karyawan bukan objek PPh 23.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "PPh 23 dikenakan saat?",
            options: ["Menjual barang", "Membayar jasa ke pihak lain", "Membeli bahan baku", "Menerima gaji"],
            answer: 1,
            explain: "PPh 23 dipotong saat membayar jasa (dan beberapa objek lain) ke pihak lain.",
          },
          {
            q: "Tarif umum PPh 23 atas jasa (ber-NPWP) adalah?",
            options: ["0,5%", "2%", "11%", "15%"],
            answer: 1,
            explain: "Tarif umum PPh 23 atas jasa adalah 2% bagi penerima ber-NPWP.",
          },
          {
            q: "Tanpa NPWP, tarif PPh 23 menjadi?",
            options: ["1%", "2%", "4%", "0%"],
            answer: 2,
            explain: "Tarif dinaikkan 100% menjadi 4% bila penerima tidak ber-NPWP.",
          },
          {
            q: "Bayar jasa Rp20 juta ke pihak ber-NPWP. PPh 23?",
            options: ["Rp400.000", "Rp200.000", "Rp2.000.000", "Rp800.000"],
            answer: 0,
            explain: "2% x Rp20.000.000 = Rp400.000.",
          },
          {
            q: "Manakah yang BUKAN objek PPh 23?",
            options: ["Jasa konsultan", "Jasa servis", "Pembelian barang dagangan", "Sewa peralatan"],
            answer: 2,
            explain: "Pembelian barang bukan objek PPh 23; yang dipotong umumnya jasa, sewa, royalti, dividen.",
          },
          {
            q: "Bayar jasa Rp25 juta ke vendor TANPA NPWP. Berapa PPh 23-nya?",
            options: ["Rp500.000", "Rp1.000.000", "Rp250.000", "Rp2.500.000"],
            answer: 1,
            explain: "Tanpa NPWP tarif 4%: 4% x Rp25 juta = Rp1.000.000.",
          },
          {
            q: "Berapa selisih potongan jasa Rp10 juta antara ber-NPWP dan tanpa NPWP?",
            options: ["Rp100.000", "Rp200.000", "Rp400.000", "Tidak ada selisih"],
            answer: 1,
            explain: "Ber-NPWP Rp200 ribu (2%), tanpa NPWP Rp400 ribu (4%); selisihnya Rp200 ribu.",
          },
          {
            q: "Bagi penerima jasa yang dipotong, PPh 23 yang dipotong menjadi?",
            options: ["Biaya hangus", "Kredit pajak di SPT Tahunan", "Denda", "Tambahan omzet"],
            answer: 1,
            explain: "PPh 23 yang dipotong jadi kredit pajak yang mengurangi PPh terutang penerima jasa.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "bukti-potong",
    levelId: "karyawan",
    order: 4,
    title: "Bukti Potong & e-Bupot",
    summary: "Bukti bahwa pajak sudah dipotong. Penting bagi pemotong maupun yang dipotong.",
    durationMin: 8,
    tags: ["bukti potong", "e-bupot", "administrasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap kali memotong PPh 21 atau PPh 23, kamu wajib memberi <strong>bukti potong</strong> kepada pihak yang dipotong. Sekarang dibuat elektronik lewat <strong>e-Bupot</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kenapa penting?",
        html: "Bagi pihak yang dipotong, bukti potong adalah <strong>kredit pajak</strong>: pengurang pajak mereka di SPT Tahunan. Bagi pemotong, ini bukti bahwa kewajiban memotong sudah dijalankan.",
      },
      {
        type: "list",
        items: [
          "Dibuat oleh <strong>pemotong</strong> (pemberi kerja / pembayar jasa).",
          "Diberikan kepada pihak yang dipotong sebagai bukti.",
          "Dibuat lewat aplikasi <strong>e-Bupot</strong>.",
          "Menjadi dasar pelaporan SPT Masa PPh 21/23.",
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Akumulasi Kredit Pajak dari Bukti Potong Setahun (ilustrasi)",
        unit: "Rp ribu",
        source: "ilustrasi",
        note: "Tiap bukti potong yang disimpan menambah kredit pajak di SPT Tahunan.",
        data: [
          { label: "Kuartal 1", value: 600, color: "#60a5fa" },
          { label: "Kuartal 2", value: 1400, color: "#3b82f6" },
          { label: "Kuartal 3", value: 2200, color: "#2563eb" },
          { label: "Kuartal 4", value: 3000, color: "#1d4ed8" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "1", label: "Bukti potong per pemotongan", sub: "wajib diberikan", color: "#2563eb" },
          { value: "e-Bupot", label: "Aplikasi pembuatnya", sub: "elektronik" },
          { value: "Kredit pajak", label: "Fungsi bagi yang dipotong", sub: "pengurang di SPT Tahunan", color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bukti potong jadi pengurang pajak",
        html: "Bu Maya (freelancer) sepanjang tahun menerima beberapa bukti potong PPh 23 total Rp3 juta dari klien-kliennya. Saat mengisi SPT Tahunan, Rp3 juta itu menjadi <strong>kredit pajak</strong> yang mengurangi PPh terutangnya. Tanpa menyimpan bukti potong, ia bisa membayar pajak dua kali.",
      },
      {
        type: "case",
        title: "Studi Kasus: Pemotong lalai memberi bukti potong",
        html: "CV Sentosa memotong PPh 23 dari 5 vendor tetapi lupa menerbitkan bukti potong lewat e-Bupot. Akibatnya para vendor tidak bisa mengklaim <strong>kredit pajak</strong> di SPT Tahunan mereka, dan CV Sentosa kesulitan saat melaporkan SPT Masa karena rekap bukti potong tidak lengkap. Setelah ditertibkan, CV Sentosa membuat bukti potong untuk seluruh transaksi: 5 bukti potong untuk 5 vendor. Membuat bukti potong tepat waktu menghindari masalah pelaporan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "Bukti potong", right: "Bukti bahwa pajak sudah dipotong" },
          { left: "e-Bupot", right: "Aplikasi membuat bukti potong elektronik" },
          { left: "Pemotong", right: "Pihak yang memotong dan menyetor pajak" },
          { left: "Kredit pajak", right: "Pengurang pajak terutang di SPT Tahunan" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini benar atau keliru dalam mengurus bukti potong?",
        buckets: ["Benar", "Keliru"],
        items: [
          { text: "Memberi bukti potong ke pihak yang dipotong", bucket: "Benar" },
          { text: "Menyimpan bukti potong untuk SPT Tahunan", bucket: "Benar" },
          { text: "Memotong pajak tapi tidak memberi bukti potong", bucket: "Keliru" },
          { text: "Membuang bukti potong yang diterima", bucket: "Keliru" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Bu Maya menerima 4 bukti potong PPh 23 sepanjang tahun: Rp200 ribu, Rp300 ribu, Rp500 ribu, dan Rp1 juta. Berapa total kredit pajaknya?",
        answer: 2000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Total kredit pajak = Rp200.000 + Rp300.000 + Rp500.000 + Rp1.000.000 = <strong>Rp2.000.000</strong>. Angka ini mengurangi PPh terutang di SPT Tahunan.",
        hint: "Jumlahkan seluruh nilai bukti potong yang diterima.",
      },
      {
        type: "takeaways",
        items: [
          "Bukti potong wajib diberikan setiap memotong PPh 21/23.",
          "Dibuat lewat e-Bupot secara elektronik.",
          "Bagi yang dipotong, ini kredit pajak di SPT Tahunan.",
          "Simpan baik-baik agar tidak membayar pajak dua kali.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Bukti potong wajib diberikan oleh?",
            options: ["Pihak yang dipotong", "Pemotong pajak", "Bank", "Konsumen"],
            answer: 1,
            explain: "Pemotong (pemberi kerja/pembayar jasa) wajib memberi bukti potong.",
          },
          {
            q: "Bukti potong dibuat lewat aplikasi?",
            options: ["e-Faktur", "e-Bupot", "e-Filing saja", "e-Commerce"],
            answer: 1,
            explain: "Bukti potong elektronik dibuat lewat aplikasi e-Bupot.",
          },
          {
            q: "Bagi pihak yang dipotong, bukti potong berfungsi sebagai?",
            options: ["Hiasan", "Kredit pajak di SPT Tahunan", "Bukti garansi", "Faktur penjualan"],
            answer: 1,
            explain: "Bukti potong menjadi kredit pajak yang mengurangi PPh terutang di SPT Tahunan.",
          },
          {
            q: "Akibat tidak menyimpan bukti potong yang diterima?",
            options: [
              "Tidak ada akibat",
              "Bisa membayar pajak dua kali",
              "Dapat bonus",
              "Pajak jadi nol",
            ],
            answer: 1,
            explain: "Tanpa bukti potong, kredit pajak tidak bisa diklaim sehingga berisiko membayar dua kali.",
          },
          {
            q: "Bukti potong menjadi dasar pelaporan?",
            options: ["SPT Masa PPh 21/23", "Faktur pajak", "Kode billing", "Laporan keuangan bank"],
            answer: 0,
            explain: "Bukti potong direkap dalam SPT Masa PPh 21/23 oleh pemotong.",
          },
          {
            q: "Bu Maya punya 4 bukti potong: Rp200rb, Rp300rb, Rp500rb, Rp1jt. Total kredit pajaknya?",
            options: ["Rp1.000.000", "Rp2.000.000", "Rp1.500.000", "Rp3.000.000"],
            answer: 1,
            explain: "Rp200rb + Rp300rb + Rp500rb + Rp1jt = Rp2.000.000.",
          },
          {
            q: "Kapan bukti potong wajib dibuat?",
            options: [
              "Hanya akhir tahun",
              "Setiap kali memotong PPh 21/23",
              "Saat diminta kantor pajak saja",
              "Tidak pernah wajib",
            ],
            answer: 1,
            explain: "Setiap pemotongan PPh 21/23 wajib disertai penerbitan bukti potong.",
          },
          {
            q: "Memotong pajak vendor tetapi tidak menerbitkan bukti potong berakibat?",
            options: [
              "Vendor untung",
              "Vendor tidak bisa klaim kredit pajak dan pelaporan pemotong terganggu",
              "Pajak jadi nol",
              "Tidak ada akibat apa pun",
            ],
            answer: 1,
            explain: "Tanpa bukti potong, vendor kehilangan kredit pajak dan rekap SPT Masa pemotong tidak lengkap.",
          },
        ],
      },
    ],
  },
];
