import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "kenapa-bayar-pajak",
    levelId: "dasar",
    order: 1,
    title: "Kenapa UMKM Perlu Bayar Pajak?",
    summary: "Pajak terdengar menakutkan, padahal untuk UMKM aturannya dibuat sangat sederhana. Mari kenalan dulu.",
    durationMin: 10,
    tags: ["pemula", "dasar", "motivasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Banyak pemilik UMKM takut pada kata 'pajak'. Padahal, justru untuk usaha kecil, pemerintah membuat aturan yang <strong>jauh lebih sederhana</strong> daripada perusahaan besar. Di topik ini kita akan kupas pelan-pelan, tanpa istilah ribet.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kabar baik untuk UMKM",
        html: "Mayoritas UMKM cukup membayar <strong>PPh Final 0,5% dari omzet</strong>, dan omzet sampai <strong>Rp500 juta per tahun bahkan bebas pajak</strong> (untuk usaha perorangan). Sesederhana itu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Mitos vs Fakta",
        html: "<strong>Mitos:</strong> 'Pajak bikin usaha kecil bangkrut.' <strong>Fakta:</strong> tarif UMKM hanya 0,5% dari omzet. Dari penjualan Rp10 juta, pajaknya hanya Rp50 ribu. Yang membuat rugi justru <em>denda</em> karena lupa atau telat, bukan pajaknya.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Seberapa Besar Peran UMKM bagi Indonesia?",
        unit: "% kontribusi (ilustrasi)",
        source: "ilustrasi pola umum data nasional",
        note: "UMKM adalah tulang punggung ekonomi. Pajak yang kamu setor ikut menjaga roda ini tetap berputar.",
        data: [
          { label: "Tenaga kerja terserap", value: 97, color: "#10b981" },
          { label: "Unit usaha", value: 99, color: "#0ea5e9" },
          { label: "Kontribusi ke PDB", value: 60, color: "#f59e0b" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Ke Mana Uang Pajak Dipakai?",
        unit: "% (ilustrasi alokasi belanja negara)",
        source: "ilustrasi pola umum APBN",
        note: "Pajak yang kamu bayar kembali dalam bentuk jalan, sekolah, layanan kesehatan, dan bantuan usaha.",
        data: [
          { label: "Pendidikan", value: 20 },
          { label: "Infrastruktur", value: 18 },
          { label: "Perlindungan sosial", value: 17 },
          { label: "Kesehatan", value: 12 },
          { label: "Lainnya (keamanan, dll)", value: 33 },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "0,5%", label: "Tarif PPh Final UMKM", sub: "dari omzet, bukan dari laba", color: "#f59e0b" },
          { value: "Rp500 jt", label: "Omzet bebas pajak/tahun", sub: "untuk usaha perorangan", color: "#10b981" },
          { value: "Rp4,8 M", label: "Batas omzet skema UMKM", sub: "di atas ini aturannya beda", color: "#0ea5e9" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bu Rina takut daftar pajak",
        html: "Bu Rina punya toko kue dengan omzet Rp25 juta per bulan (Rp300 juta setahun). Ia takut pajak akan 'memakan' untungnya. Setelah belajar, ternyata karena omzetnya di bawah Rp500 juta setahun, <strong>PPh final-nya Rp0</strong>. Ia hanya perlu punya NPWP dan lapor SPT Tahunan sekali setahun. Ketakutannya selama ini tidak beralasan.",
      },
      {
        type: "case",
        title: "Studi Kasus: Pak Budi yang sudah melewati batas bebas",
        html: "Pak Budi punya bengkel motor dengan omzet Rp60 juta per bulan (Rp720 juta setahun). Karena sudah melewati batas bebas Rp500 juta, ia kena PPh final 0,5%. Hitungannya: dari Rp720 juta, bagian yang kena pajak adalah Rp720 juta dikurangi Rp500 juta = <strong>Rp220 juta</strong>. PPh final setahun = 0,5% x Rp220 juta = <strong>Rp1,1 juta</strong> saja, atau sekitar Rp92 ribu per bulan. Tetap sangat ringan dibanding omzetnya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba cek sendiri",
        html: "Masukkan jenis dan omzet usahamu di alat berikut untuk langsung tahu kewajiban pajakmu.",
      },
      { type: "widget", widget: "CekStatusPajak" },
      {
        type: "classifyExercise",
        prompt: "Mana yang benar (Fakta) dan mana yang keliru (Mitos) soal pajak UMKM?",
        buckets: ["Fakta", "Mitos"],
        items: [
          { text: "Tarif PPh final UMKM hanya 0,5% dari omzet", bucket: "Fakta" },
          { text: "Omzet sampai Rp500 juta/tahun bebas PPh final (OP)", bucket: "Fakta" },
          { text: "Pajak pasti membuat UMKM bangkrut", bucket: "Mitos" },
          { text: "Kalau omzet kecil, tidak perlu NPWP sama sekali", bucket: "Mitos" },
          { text: "Telat lapor bisa kena denda", bucket: "Fakta" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Omzet toko Rp10.000.000 sebulan. Berapa kira-kira PPh final 0,5% sebulan (anggap sudah melewati batas bebas)?",
        answer: 50000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh final = 0,5% x Rp10.000.000 = <strong>Rp50.000</strong>. Sangat kecil dibanding omzetnya.",
        hint: "Kalikan omzet dengan 0,5% (0,005).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan angka kunci pajak UMKM dengan artinya.",
        pairs: [
          { left: "0,5%", right: "Tarif PPh final dari omzet" },
          { left: "Rp500 juta", right: "Batas omzet bebas pajak per tahun (OP)" },
          { left: "Rp4,8 miliar", right: "Batas atas omzet skema PPh final UMKM" },
          { left: "Rp50.000", right: "PPh final dari omzet Rp10 juta" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Aturan pajak UMKM sengaja dibuat sederhana.",
          "Tarif utama hanya 0,5% dari omzet (bukan dari laba).",
          "Omzet sampai Rp500 juta/tahun bebas PPh final untuk usaha perorangan.",
          "Yang bikin rugi biasanya denda telat, bukan pajaknya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tarif PPh Final untuk UMKM adalah?",
            options: ["5% dari laba", "0,5% dari omzet", "11% dari omzet", "25% dari laba"],
            answer: 1,
            explain: "Skema UMKM memakai tarif 0,5% dari omzet (peredaran bruto), bukan dari laba.",
          },
          {
            q: "Untuk usaha perorangan, omzet setahun yang bebas PPh final adalah sampai?",
            options: ["Rp50 juta", "Rp500 juta", "Rp4,8 miliar", "Tidak ada"],
            answer: 1,
            explain: "Omzet sampai Rp500 juta per tahun tidak kena PPh final (fasilitas untuk WP Orang Pribadi).",
          },
          {
            q: "PPh final UMKM dihitung dari?",
            options: ["Laba bersih", "Omzet (peredaran bruto)", "Jumlah karyawan", "Aset"],
            answer: 1,
            explain: "Dasarnya adalah omzet, sehingga sangat mudah dihitung tanpa pembukuan rumit.",
          },
          {
            q: "Omzet Rp20 juta sebulan, sudah melewati batas bebas. PPh final sebulan?",
            options: ["Rp100.000", "Rp1.000.000", "Rp50.000", "Rp2.000.000"],
            answer: 0,
            explain: "0,5% x Rp20.000.000 = Rp100.000.",
          },
          {
            q: "Apa yang sering benar-benar merugikan UMKM soal pajak?",
            options: [
              "Tarif yang terlalu tinggi",
              "Denda karena telat atau lupa lapor",
              "Wajib punya pegawai pajak",
              "Harus sewa kantor",
            ],
            answer: 1,
            explain: "Tarifnya kecil; yang memberatkan biasanya denda akibat telat lapor atau bayar.",
          },
          {
            q: "Bu Rina beromzet Rp300 juta/tahun (perorangan). PPh final-nya?",
            options: ["Rp1,5 juta", "Rp0 karena di bawah Rp500 juta", "Rp15 juta", "Rp30 juta"],
            answer: 1,
            explain: "Karena omzetnya di bawah Rp500 juta setahun, PPh finalnya Rp0. Tetap wajib lapor SPT Tahunan.",
          },
          {
            q: "Batas omzet agar usaha masih bisa memakai skema PPh final 0,5% adalah?",
            options: ["Rp500 juta/tahun", "Rp1 miliar/tahun", "Rp4,8 miliar/tahun", "Tidak ada batas"],
            answer: 2,
            explain: "Skema PPh final 0,5% berlaku untuk omzet sampai Rp4,8 miliar per tahun. Di atas itu aturannya berbeda.",
          },
          {
            q: "Kira-kira ke mana sebagian besar uang pajak dialokasikan negara?",
            options: [
              "Hanya untuk gaji pejabat",
              "Pendidikan, infrastruktur, kesehatan, dan perlindungan sosial",
              "Disimpan dan tidak dipakai",
              "Hanya untuk militer",
            ],
            answer: 1,
            explain: "Pajak kembali ke masyarakat lewat layanan publik seperti pendidikan, jalan, kesehatan, dan bantuan sosial.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "npwp-nik",
    levelId: "dasar",
    order: 2,
    title: "NPWP & NIK: Identitas Pajakmu",
    summary: "NPWP itu seperti KTP-nya wajib pajak. Sekarang NIK pun berfungsi sebagai NPWP.",
    durationMin: 9,
    tags: ["NPWP", "NIK", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>NPWP (Nomor Pokok Wajib Pajak)</strong> adalah identitas kamu di mata pajak, ibarat KTP untuk urusan pajak. Kabar baiknya, untuk orang pribadi, <strong>NIK di KTP kini berfungsi sebagai NPWP</strong>, jadi makin praktis.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Mendaftar itu gratis dan online",
        html: "NPWP bisa dibuat gratis secara online lewat sistem DJP (ereg/Coretax). Tidak perlu calo dan tidak dipungut biaya.",
      },
      {
        type: "stats",
        items: [
          { value: "Rp0", label: "Biaya membuat NPWP", sub: "gratis, daftar online", color: "#10b981" },
          { value: "1 NIK", label: "= NPWP orang pribadi", sub: "cukup pakai NIK di KTP", color: "#0ea5e9" },
          { value: "2x lipat", label: "Potongan tanpa NPWP", sub: "tarif potong dinaikkan 100%", color: "#ef4444" },
        ],
      },
      {
        type: "heading",
        text: "Kenapa NPWP penting untuk UMKM?",
      },
      {
        type: "list",
        items: [
          "Sering jadi <strong>syarat</strong> mengajukan KUR atau pinjaman usaha ke bank.",
          "Syarat ikut <strong>tender</strong> atau jadi pemasok perusahaan/instansi.",
          "Menghindari <strong>potongan pajak lebih tinggi</strong> (banyak potongan naik bila tidak punya NPWP).",
          "Membuat usaha terlihat <strong>resmi dan kredibel</strong>.",
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Potongan lebih besar tanpa NPWP",
        html: "Pak Doni menyediakan jasa desain untuk sebuah perusahaan senilai Rp10 juta. Karena ia belum punya NPWP, perusahaan memotong PPh 23 sebesar <strong>4%</strong> (Rp400 ribu), bukan 2% (Rp200 ribu). Tarif potong memang dinaikkan 100% bagi yang tidak ber-NPWP. Hanya karena belum daftar, Pak Doni kehilangan Rp200 ribu.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Potongan PPh 23 atas Jasa Rp10 Juta: Punya vs Tanpa NPWP",
        unit: "Rp ribu (ilustrasi)",
        source: "ilustrasi tarif PPh 23",
        note: "Punya NPWP membuat tarif potong tidak dinaikkan. Selisihnya langsung jadi uang yang kamu hemat.",
        data: [
          { label: "Ber-NPWP (2%)", value: 200, color: "#10b981" },
          { label: "Tanpa NPWP (4%)", value: 400, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: NPWP jadi kunci pengajuan KUR",
        html: "Bu Sari ingin mengajukan KUR Rp50 juta untuk menambah modal warung sembakonya. Saat ke bank, ia diminta melampirkan NPWP sebagai salah satu syarat. Karena belum punya, prosesnya tertunda dua minggu. Setelah mendaftar NPWP online secara <strong>gratis</strong> dalam hitungan menit, pengajuannya bisa dilanjutkan dan disetujui. NPWP bukan sekadar urusan pajak, tapi juga pintu akses modal usaha.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "NPWP", right: "Nomor identitas wajib pajak" },
          { left: "NIK", right: "Nomor di KTP yang kini berfungsi sebagai NPWP" },
          { left: "Coretax / DJP Online", right: "Sistem untuk daftar, bayar, dan lapor pajak" },
          { left: "Wajib Pajak (WP)", right: "Orang atau badan yang punya kewajiban pajak" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Situasi ini sebaiknya sudah punya NPWP atau belum wajib?",
        buckets: ["Sebaiknya punya NPWP", "Belum mendesak"],
        items: [
          { text: "Mau mengajukan KUR ke bank", bucket: "Sebaiknya punya NPWP" },
          { text: "Jadi pemasok rutin sebuah perusahaan", bucket: "Sebaiknya punya NPWP" },
          { text: "Baru coba jualan kecil-kecilan ke tetangga", bucket: "Belum mendesak" },
          { text: "Menerima order jasa dari perusahaan (akan dipotong PPh 23)", bucket: "Sebaiknya punya NPWP" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jasa Rp10.000.000 dipotong PPh 23. Berapa selisih potongan antara TANPA NPWP (4%) dan PUNYA NPWP (2%)?",
        answer: 200000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Tanpa NPWP: 4% x Rp10.000.000 = Rp400.000. Punya NPWP: 2% x Rp10.000.000 = Rp200.000. Selisih = <strong>Rp200.000</strong> yang bisa dihemat hanya dengan punya NPWP.",
        hint: "Hitung 4% lalu 2% dari Rp10 juta, kemudian kurangkan.",
      },
      {
        type: "takeaways",
        items: [
          "NPWP adalah identitas pajak, seperti KTP untuk urusan pajak.",
          "NIK kini berfungsi sebagai NPWP untuk orang pribadi.",
          "Mendaftar gratis dan online, tanpa biaya.",
          "Tanpa NPWP, banyak potongan pajak jadi lebih tinggi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "NPWP paling tepat diibaratkan sebagai?",
            options: ["SIM kendaraan", "KTP untuk urusan pajak", "Kartu ATM", "Sertifikat tanah"],
            answer: 1,
            explain: "NPWP adalah identitas wajib pajak, ibarat KTP khusus urusan perpajakan.",
          },
          {
            q: "Untuk orang pribadi, apa yang kini berfungsi sebagai NPWP?",
            options: ["Nomor HP", "NIK di KTP", "Nomor rekening", "Nomor KK"],
            answer: 1,
            explain: "NIK pada KTP kini diintegrasikan sebagai NPWP orang pribadi.",
          },
          {
            q: "Berapa biaya membuat NPWP?",
            options: ["Rp500 ribu", "Gratis", "Rp1 juta", "Tergantung omzet"],
            answer: 1,
            explain: "Pembuatan NPWP gratis dan bisa dilakukan online.",
          },
          {
            q: "Tanpa NPWP, tarif potong PPh umumnya menjadi?",
            options: ["Lebih rendah", "Sama saja", "Lebih tinggi", "Nol"],
            answer: 2,
            explain: "Banyak tarif pemotongan dinaikkan bagi yang tidak ber-NPWP (mis. PPh 23 dari 2% jadi 4%).",
          },
          {
            q: "Jasa Rp10 juta dipotong PPh 23 tanpa NPWP (4%). Berapa potongannya?",
            options: ["Rp200.000", "Rp400.000", "Rp100.000", "Rp1.000.000"],
            answer: 1,
            explain: "4% x Rp10.000.000 = Rp400.000 (dua kali lipat dari tarif ber-NPWP).",
          },
          {
            q: "Manakah BUKAN manfaat punya NPWP bagi UMKM?",
            options: [
              "Memudahkan pengajuan KUR ke bank",
              "Menghindari potongan pajak yang lebih tinggi",
              "Membuat usaha terlihat resmi",
              "Otomatis membebaskan dari semua pajak",
            ],
            answer: 3,
            explain: "NPWP tidak membebaskan pajak. Ia mempermudah akses modal, tender, dan menghindari potongan yang lebih tinggi.",
          },
          {
            q: "Bu Sari ingin ajukan KUR tapi prosesnya tertunda. Apa penyebabnya?",
            options: ["Belum punya NPWP", "Omzet terlalu besar", "Sudah jadi PKP", "Tidak punya KTP"],
            answer: 0,
            explain: "NPWP sering jadi syarat pengajuan KUR. Tanpa itu, proses bisa tertunda.",
          },
          {
            q: "Cara mendaftar NPWP untuk orang pribadi yang paling tepat adalah?",
            options: [
              "Lewat calo agar cepat",
              "Online dan gratis lewat sistem DJP",
              "Wajib bayar Rp500 ribu",
              "Tidak bisa, harus badan usaha dulu",
            ],
            answer: 1,
            explain: "Pendaftaran NPWP gratis dan bisa dilakukan online sendiri lewat sistem DJP (ereg/Coretax).",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "jenis-pajak-umkm",
    levelId: "dasar",
    order: 3,
    title: "Peta Jenis Pajak untuk UMKM",
    summary: "Tidak semua pajak relevan untukmu. Kenali mana yang benar-benar perlu kamu urus.",
    durationMin: 11,
    tags: ["jenis pajak", "peta", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Ada banyak jenis pajak, tapi UMKM biasanya hanya berurusan dengan <strong>sedikit saja</strong>. Mari kita petakan mana yang relevan untukmu, supaya tidak pusing memikirkan yang tidak perlu.",
      },
      {
        type: "video",
        comp: "PetaPajakUMKM",
        title: "Video: Peta Pajak UMKM",
        caption: "Animasi pajak apa saja yang berlaku, tergantung kondisi usahamu.",
      },
      {
        type: "table",
        caption: "Jenis pajak yang mungkin relevan untuk UMKM",
        headers: ["Pajak", "Berlaku jika...", "Tarif singkat"],
        rows: [
          ["PPh Final UMKM", "Punya usaha, omzet sampai Rp4,8 M/tahun", "0,5% dari omzet"],
          ["PPN", "Sudah jadi PKP (omzet di atas Rp4,8 M)", "11% dari penjualan"],
          ["PPh 21", "Punya karyawan yang digaji", "Sesuai PTKP & tarif"],
          ["PPh 23", "Membayar jasa ke pihak lain", "2% dari nilai jasa"],
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Penerimaan Pajak Negara",
        unit: "% dari total penerimaan pajak (ilustrasi)",
        source: "ilustrasi pola umum penerimaan pajak",
        note: "PPh dan PPN menyumbang bagian terbesar. UMKM paling sering bersentuhan dengan PPh.",
        data: [
          { label: "PPh (Pajak Penghasilan)", value: 50, color: "#f59e0b" },
          { label: "PPN & PPnBM", value: 40, color: "#0ea5e9" },
          { label: "PBB & lainnya", value: 10, color: "#10b981" },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Mayoritas UMKM cukup yang pertama",
        html: "Kalau usahamu masih kecil dan dijalankan sendiri/keluarga, biasanya kamu <strong>hanya perlu mengurus PPh Final 0,5%</strong>. Sisanya muncul belakangan saat usaha membesar atau punya karyawan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Cek kewajibanmu",
        html: "Pakai alat ini lagi untuk melihat kombinasi pajak yang berlaku sesuai kondisi usahamu.",
      },
      { type: "widget", widget: "CekStatusPajak" },
      {
        type: "case",
        title: "Studi Kasus: Warung kopi yang berkembang",
        html: "Tahun pertama, Warung Kopi Mas Anto beromzet Rp400 juta, dijalankan sendiri: cukup urus PPh Final (bahkan Rp0 karena di bawah Rp500 juta). Tahun ketiga, omzet naik jadi Rp1,5 miliar dan ia merekrut 3 barista: kini ia juga mengurus <strong>PPh 21</strong> untuk gaji karyawan. Saat omzet menembus Rp5 miliar, ia wajib jadi <strong>PKP</strong> dan memungut <strong>PPN</strong>. Kewajiban pajak tumbuh mengikuti ukuran usaha.",
      },
      {
        type: "case",
        title: "Studi Kasus: Konveksi Bu Tina memetakan pajaknya",
        html: "Bu Tina punya usaha konveksi dengan omzet Rp2 miliar setahun dan 5 penjahit tetap. Mari kita petakan: (1) Karena omzet masih di bawah Rp4,8 miliar, ia memakai <strong>PPh Final 0,5%</strong> = Rp10 juta setahun. (2) Karena menggaji 5 karyawan, ia mengurus <strong>PPh 21</strong> atas gaji mereka. (3) Saat ia membayar jasa sablon ke vendor luar Rp20 juta, ia memotong <strong>PPh 23</strong> 2% = Rp400 ribu. (4) PPN belum berlaku karena ia belum jadi PKP. Tiga jenis pajak, semuanya masih sederhana.",
      },
      {
        type: "stats",
        items: [
          { value: "Rp4,8 M", label: "Ambang jadi PKP", sub: "wajib pungut PPN di atasnya", color: "#0ea5e9" },
          { value: "11%", label: "Tarif PPN", sub: "dipungut dari pembeli", color: "#f59e0b" },
          { value: "2%", label: "PPh 23 atas jasa", sub: "dipotong saat bayar jasa", color: "#10b981" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pajak mana yang relevan untuk tiap situasi UMKM ini?",
        buckets: ["PPh Final 0,5%", "PPh 21", "PPN"],
        items: [
          { text: "Usaha perorangan, omzet Rp600 juta, tanpa karyawan", bucket: "PPh Final 0,5%" },
          { text: "Mulai menggaji 2 karyawan tetap", bucket: "PPh 21" },
          { text: "Omzet menembus Rp5 miliar setahun", bucket: "PPN" },
          { text: "Toko kecil omzet Rp30 juta sebulan", bucket: "PPh Final 0,5%" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pajak dengan pemicunya.",
        pairs: [
          { left: "PPh Final 0,5%", right: "Punya usaha dengan omzet sampai Rp4,8 M" },
          { left: "PPN", right: "Sudah dikukuhkan sebagai PKP" },
          { left: "PPh 21", right: "Menggaji karyawan" },
          { left: "PPh 23", right: "Membayar jasa ke pihak lain" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Konveksi membayar jasa sablon ke vendor senilai Rp20.000.000. Berapa PPh 23 (2%) yang dipotong?",
        answer: 400000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh 23 = 2% x Rp20.000.000 = <strong>Rp400.000</strong>. Pajak ini dipotong dari pembayaran ke vendor jasa.",
        hint: "Kalikan nilai jasa dengan 2% (0,02).",
      },
      {
        type: "takeaways",
        items: [
          "UMKM biasanya hanya berurusan dengan sedikit jenis pajak.",
          "Mayoritas cukup mengurus PPh Final 0,5%.",
          "PPh 21 muncul saat punya karyawan; PPN saat jadi PKP.",
          "Kewajiban pajak tumbuh seiring ukuran usaha.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pajak yang paling umum diurus UMKM kecil adalah?",
            options: ["PPN", "PPh Final 0,5%", "Pajak kendaraan", "Bea masuk"],
            answer: 1,
            explain: "Mayoritas UMKM kecil cukup mengurus PPh Final 0,5% dari omzet.",
          },
          {
            q: "PPh 21 mulai relevan ketika UMKM?",
            options: ["Punya karyawan yang digaji", "Beromzet kecil", "Tidak punya NPWP", "Menjual online"],
            answer: 0,
            explain: "PPh 21 adalah pajak atas penghasilan karyawan, jadi relevan saat mulai menggaji orang.",
          },
          {
            q: "PPN baru wajib dipungut ketika UMKM?",
            options: ["Baru berdiri", "Sudah jadi PKP (omzet di atas Rp4,8 M)", "Punya NPWP", "Menjual jasa"],
            answer: 1,
            explain: "Kewajiban memungut PPN muncul setelah dikukuhkan sebagai PKP, umumnya saat omzet melewati Rp4,8 miliar.",
          },
          {
            q: "Saat membayar jasa ke pihak lain, pajak yang mungkin kamu potong adalah?",
            options: ["PPh 23", "PPN saja", "Pajak bumi", "Bea meterai"],
            answer: 0,
            explain: "Pembayaran jasa ke pihak lain umumnya dipotong PPh 23 sebesar 2%.",
          },
          {
            q: "Pernyataan yang benar tentang kewajiban pajak UMKM?",
            options: [
              "Semua UMKM wajib memungut PPN",
              "Kewajiban bertambah seiring usaha membesar",
              "UMKM tidak pernah punya kewajiban pajak",
              "PPh 21 wajib walau tanpa karyawan",
            ],
            answer: 1,
            explain: "Kewajiban pajak menyesuaikan skala usaha: makin besar dan kompleks, makin banyak yang diurus.",
          },
          {
            q: "Tarif PPN yang berlaku saat ini adalah?",
            options: ["0,5%", "2%", "11%", "25%"],
            answer: 2,
            explain: "PPN dipungut sebesar 11% dari nilai penjualan, hanya bagi pengusaha yang sudah dikukuhkan sebagai PKP.",
          },
          {
            q: "Jenis pajak yang menyumbang bagian terbesar penerimaan negara adalah?",
            options: ["PBB", "PPh dan PPN", "Bea meterai", "Pajak kendaraan"],
            answer: 1,
            explain: "PPh dan PPN menyumbang bagian terbesar penerimaan pajak. UMKM paling sering bersentuhan dengan PPh.",
          },
          {
            q: "Konveksi Bu Tina (omzet Rp2 M, 5 karyawan) mengurus pajak apa saja?",
            options: [
              "Hanya PPN",
              "PPh Final, PPh 21, dan PPh 23",
              "Tidak ada, karena UMKM",
              "Hanya pajak kendaraan",
            ],
            answer: 1,
            explain: "Karena di bawah Rp4,8 M ia pakai PPh Final 0,5%, punya karyawan jadi ada PPh 21, dan bayar jasa vendor kena PPh 23.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "istilah-dasar",
    levelId: "dasar",
    order: 4,
    title: "Istilah Pajak yang Sering Bikin Bingung",
    summary: "Omzet, DPP, SPT, masa pajak, PKP. Kita terjemahkan ke bahasa sehari-hari.",
    durationMin: 10,
    tags: ["istilah", "glosarium", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Pajak terasa sulit sering kali bukan karena hitungannya, tapi karena <strong>istilahnya asing</strong>. Mari terjemahkan istilah yang paling sering muncul ke bahasa sehari-hari.",
      },
      {
        type: "table",
        caption: "Kamus mini pajak UMKM",
        headers: ["Istilah", "Bahasa sehari-hari"],
        rows: [
          ["Omzet / Peredaran Bruto", "Total penjualan, sebelum dikurangi biaya apa pun"],
          ["DPP (Dasar Pengenaan Pajak)", "Angka yang dipakai untuk menghitung pajak"],
          ["Masa Pajak", "Periode bulanan"],
          ["Tahun Pajak", "Periode satu tahun"],
          ["SPT", "Formulir laporan pajak"],
          ["e-Billing", "Cara buat kode untuk membayar pajak"],
          ["NTPN", "Bukti bahwa pajak sudah dibayar"],
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati: 'PKP' punya dua arti",
        html: "<strong>PKP</strong> bisa berarti <strong>Pengusaha Kena Pajak</strong> (status untuk memungut PPN) ATAU <strong>Penghasilan Kena Pajak</strong> (angka untuk menghitung PPh). Lihat konteksnya. Di pembahasan PPN, PKP = Pengusaha Kena Pajak.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Ingat yang ini saja dulu",
        html: "Untuk UMKM, istilah terpenting adalah <strong>omzet</strong> (total penjualan). Karena pajak utamamu (0,5%) dihitung langsung dari omzet, bukan dari laba.",
      },
      {
        type: "case",
        title: "Studi Kasus: Salah paham omzet vs laba",
        html: "Pak Heri mengira PPh final 0,5% dihitung dari <em>keuntungan</em>. Ia bingung menghitung untungnya dulu. Padahal 0,5% dihitung dari <strong>omzet (total penjualan)</strong>. Jadi kalau jualan sebulan Rp30 juta, dasar pajaknya Rp30 juta, bukan labanya. Justru ini yang membuat skema UMKM mudah: tidak perlu menghitung laba.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Omzet vs Laba: Jangan Sampai Tertukar",
        unit: "Rp juta per bulan (ilustrasi)",
        source: "ilustrasi toko kue",
        note: "Omzet Rp30 juta terdiri dari biaya Rp22 juta dan laba Rp8 juta. PPh final 0,5% memakai omzet (Rp30 juta), bukan laba.",
        data: [
          { label: "Omzet (total penjualan)", value: 30, color: "#0ea5e9" },
          { label: "Biaya", value: 22, color: "#94a3b8" },
          { label: "Laba", value: 8, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bu Ningsih membaca SPT dengan tenang",
        html: "Bu Ningsih dulu panik tiap dengar istilah pajak. Sekarang ia paham: <strong>omzet</strong> = total jualan warungnya (Rp40 juta sebulan), <strong>masa pajak</strong> = laporan bulanan, <strong>SPT</strong> = formulir laporannya, dan setelah membayar ia menyimpan <strong>NTPN</strong> sebagai bukti. Dengan mengerti lima istilah ini, mengurus pajak terasa seperti mengisi formulir biasa, bukan lagi hal menakutkan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan arti sederhananya.",
        pairs: [
          { left: "Omzet", right: "Total penjualan sebelum dikurangi biaya" },
          { left: "SPT", right: "Formulir laporan pajak" },
          { left: "Masa Pajak", right: "Periode bulanan" },
          { left: "NTPN", right: "Bukti pajak sudah dibayar" },
          { left: "e-Billing", right: "Cara membuat kode untuk membayar" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Angka berikut termasuk 'omzet' atau 'laba'?",
        buckets: ["Omzet", "Laba"],
        items: [
          { text: "Total uang masuk dari semua penjualan bulan ini", bucket: "Omzet" },
          { text: "Sisa uang setelah dikurangi semua biaya", bucket: "Laba" },
          { text: "Rp30 juta hasil jualan kue sebulan", bucket: "Omzet" },
          { text: "Rp8 juta keuntungan bersih sebulan", bucket: "Laba" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Omzet warung Rp40.000.000 sebulan (di atas batas bebas). Berapa PPh final 0,5% sebulan, dihitung dari OMZET?",
        answer: 200000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh final = 0,5% x Rp40.000.000 (omzet, bukan laba) = <strong>Rp200.000</strong>. Ingat: dasarnya omzet, bukan keuntungan.",
        hint: "Kalikan omzet, bukan laba, dengan 0,5% (0,005).",
      },
      {
        type: "takeaways",
        items: [
          "Pajak sulit sering karena istilah, bukan hitungannya.",
          "Omzet = total penjualan sebelum dikurangi biaya apa pun.",
          "PPh final UMKM dihitung dari omzet, bukan laba.",
          "Waspada: PKP bisa berarti Pengusaha Kena Pajak atau Penghasilan Kena Pajak.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Omzet (peredaran bruto) artinya?",
            options: [
              "Keuntungan bersih",
              "Total penjualan sebelum dikurangi biaya",
              "Modal usaha",
              "Pajak terutang",
            ],
            answer: 1,
            explain: "Omzet adalah total penjualan kotor, belum dikurangi biaya apa pun.",
          },
          {
            q: "PPh Final UMKM 0,5% dihitung dari?",
            options: ["Laba", "Omzet", "Aset", "Modal"],
            answer: 1,
            explain: "Dihitung langsung dari omzet, sehingga tidak perlu menghitung laba lebih dulu.",
          },
          {
            q: "SPT adalah?",
            options: ["Surat tagihan", "Formulir laporan pajak", "Kartu identitas", "Bukti bayar"],
            answer: 1,
            explain: "SPT (Surat Pemberitahuan) adalah formulir untuk melaporkan pajak.",
          },
          {
            q: "Dalam konteks PPN, 'PKP' berarti?",
            options: [
              "Penghasilan Kena Pajak",
              "Pengusaha Kena Pajak",
              "Pajak Konsumsi Pribadi",
              "Pusat Kantor Pajak",
            ],
            answer: 1,
            explain: "Di konteks PPN, PKP = Pengusaha Kena Pajak, yaitu status untuk memungut PPN.",
          },
          {
            q: "Jualan kue Rp30 juta sebulan dengan untung Rp8 juta. Dasar PPh final 0,5% adalah?",
            options: ["Rp8 juta (laba)", "Rp30 juta (omzet)", "Rp22 juta", "Rp38 juta"],
            answer: 1,
            explain: "PPh final dihitung dari omzet Rp30 juta, bukan dari laba Rp8 juta.",
          },
          {
            q: "NTPN berfungsi sebagai?",
            options: [
              "Formulir laporan pajak",
              "Bukti bahwa pajak sudah dibayar",
              "Nomor identitas wajib pajak",
              "Kode untuk membuat tagihan",
            ],
            answer: 1,
            explain: "NTPN (Nomor Transaksi Penerimaan Negara) adalah bukti bahwa pembayaran pajak sudah masuk ke kas negara.",
          },
          {
            q: "'Masa Pajak' paling tepat diartikan sebagai?",
            options: ["Periode bulanan", "Periode lima tahunan", "Tanggal lahir wajib pajak", "Batas akhir usaha"],
            answer: 0,
            explain: "Masa Pajak adalah periode bulanan yang dipakai sebagai satuan pelaporan dan pembayaran pajak.",
          },
          {
            q: "Omzet Rp40 juta dengan biaya Rp22 juta. Berapa labanya, dan mana yang jadi dasar PPh final?",
            options: [
              "Laba Rp18 juta, dasar pajak pakai laba",
              "Laba Rp18 juta, dasar pajak tetap omzet Rp40 juta",
              "Laba Rp62 juta, dasar pajak pakai laba",
              "Tidak bisa dihitung",
            ],
            answer: 1,
            explain: "Laba = Rp40 juta - Rp22 juta = Rp18 juta. Namun PPh final tetap dihitung dari omzet Rp40 juta, bukan laba.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "self-assessment",
    levelId: "dasar",
    order: 5,
    title: "Self Assessment: Hitung, Setor, Lapor Sendiri",
    summary: "Sistem pajak Indonesia mempercayakan perhitungan pada wajib pajak. Kenali tiga langkah HSL dan tanggung jawabnya.",
    durationMin: 12,
    tags: ["self assessment", "HSL", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Pernah bertanya, siapa yang menghitung pajakmu? Di Indonesia jawabannya: <strong>kamu sendiri</strong>. Sistem kita bernama <strong>self assessment</strong>, artinya wajib pajak diberi kepercayaan untuk menghitung, menyetor, dan melaporkan pajaknya sendiri.",
      },
      {
        type: "paragraph",
        html: "Tiga langkah itu sering disingkat <strong>HSL: Hitung, Setor, Lapor</strong>. Kantor pajak (DJP) tidak menagih satu per satu, melainkan bertugas <strong>mengawasi</strong> dan menguji kebenaran lewat data dan pemeriksaan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga langkah HSL",
        html: "<strong>Hitung</strong> pajak dari catatanmu (mis. 0,5% dari omzet). <strong>Setor</strong> lewat kode billing sebelum tenggat. <strong>Lapor</strong> lewat SPT. Selama tiga langkah ini benar dan tepat waktu, urusan pajakmu aman.",
      },
      {
        type: "video",
        comp: "PetaPajakUMKM",
        title: "Video: Peta Pajak UMKM",
        caption: "Kenali dulu pajak apa saja yang jadi kewajibanmu sebelum menghitung sendiri.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kepercayaan disertai pengawasan",
        html: "Karena kamu yang menghitung, kamu juga bertanggung jawab atas kebenarannya. DJP bisa mencocokkan dengan data pihak ketiga (bank, marketplace, lawan transaksi). Maka catat omzet dengan jujur dan rapi.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Seberapa Sering Kamu Menjalankan Self Assessment dalam Setahun",
        unit: "kali per tahun",
        source: "ketentuan masa & tahun pajak",
        note: "Setor dan lapor bulanan berulang 12 kali; SPT Tahunan sekali. Inilah ritme yang kamu jalankan sendiri.",
        data: [
          { label: "Setor PPh final (bulanan)", value: 12, color: "#f59e0b" },
          { label: "Lapor SPT Masa (jika PKP)", value: 12, color: "#0ea5e9" },
          { label: "Lapor SPT Tahunan", value: 1, color: "#10b981" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "3 langkah", label: "Hitung, Setor, Lapor", sub: "inti self assessment", color: "#f59e0b" },
          { value: "Kamu", label: "yang menghitung pajak", sub: "bukan kantor pajak", color: "#0ea5e9" },
          { value: "DJP", label: "berperan mengawasi", sub: "lewat data & pemeriksaan", color: "#10b981" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Cek kewajibanmu dulu",
        html: "Sebelum menghitung, pastikan jenis pajak apa yang menjadi kewajibanmu lewat alat ini.",
      },
      { type: "widget", widget: "CekStatusPajak" },
      {
        type: "case",
        title: "Studi Kasus: Bu Lina menghitung sendiri",
        html: "Bu Lina punya toko kelontong dengan omzet Mei Rp35 juta (sudah lewat batas bebas). Tanpa menunggu tagihan, ia menghitung sendiri: 0,5% x Rp35 juta = <strong>Rp175.000</strong>. Ia buat kode billing, bayar sebelum 15 Juni, lalu simpan NTPN. Itulah self assessment: ia yang hitung, setor, dan lapor, bukan menunggu kantor pajak.",
      },
      {
        type: "case",
        title: "Sejarah: Reformasi Perpajakan 1983",
        html: "Sebelum 1983, Indonesia memakai <strong>official assessment</strong> warisan masa kolonial: petugas pajak yang menghitung dan menetapkan pajak tiap orang. Lewat <strong>Reformasi Perpajakan 1983</strong> (paket UU KUP, UU PPh, dan UU PPN), Indonesia beralih ke <strong>self assessment</strong>. Kepercayaan menghitung diserahkan kepada wajib pajak, sementara negara fokus mengawasi. Sistem inilah yang kita pakai sampai sekarang.",
      },
      {
        type: "classifyExercise",
        prompt: "Dalam self assessment, tugas ini dijalankan oleh wajib pajak atau DJP?",
        buckets: ["Wajib Pajak", "DJP (mengawasi)"],
        items: [
          { text: "Menghitung sendiri pajak terutang", bucket: "Wajib Pajak" },
          { text: "Menyetor lewat kode billing", bucket: "Wajib Pajak" },
          { text: "Melaporkan lewat SPT", bucket: "Wajib Pajak" },
          { text: "Memeriksa kebenaran lewat data pihak ketiga", bucket: "DJP (mengawasi)" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Self assessment: hitung sendiri. Omzet bulan ini Rp35.000.000 (sudah lewat batas bebas), PPh Final 0,5%. Berapa yang kamu setor?",
        answer: 175000,
        tolerance: 0,
        prefix: "Rp",
        solution: "0,5% x Rp35.000.000 = <strong>Rp175.000</strong>. Kamu hitung sendiri, lalu setor sebelum tanggal 15 bulan berikutnya.",
        hint: "Kalikan omzet dengan 0,5% (0,005).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan langkah HSL dengan kegiatannya.",
        pairs: [
          { left: "Hitung", right: "Menentukan pajak dari catatan omzet" },
          { left: "Setor", right: "Membayar lewat kode billing" },
          { left: "Lapor", right: "Menyampaikan SPT" },
          { left: "Self assessment", right: "Sistem: wajib pajak menghitung sendiri" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Indonesia memakai sistem self assessment sejak Reformasi 1983.",
          "Wajib pajak menghitung, menyetor, dan melapor sendiri (HSL).",
          "DJP berperan mengawasi lewat data dan pemeriksaan.",
          "Karena kamu yang menghitung, catat omzet dengan jujur dan rapi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Sistem perpajakan Indonesia disebut?",
            options: ["Official assessment", "Self assessment", "Withholding penuh", "Tanpa sistem"],
            answer: 1,
            explain: "Indonesia memakai self assessment: wajib pajak menghitung, menyetor, dan melapor sendiri.",
          },
          {
            q: "HSL adalah singkatan dari?",
            options: ["Hitung, Setor, Lapor", "Hemat, Simpan, Lunas", "Hitung, Simpan, Laba", "Hak, Sanksi, Lapor"],
            answer: 0,
            explain: "HSL adalah Hitung, Setor, Lapor, tiga langkah inti self assessment.",
          },
          {
            q: "Dalam self assessment, siapa yang menghitung pajak?",
            options: ["Kantor pajak", "Wajib pajak sendiri", "Bank", "Notaris"],
            answer: 1,
            explain: "Wajib pajak yang menghitung pajaknya sendiri, bukan ditetapkan kantor pajak.",
          },
          {
            q: "Peran utama DJP dalam sistem ini adalah?",
            options: ["Menghitungkan pajak tiap orang", "Mengawasi & menguji kebenaran", "Menjual barang", "Menggaji wajib pajak"],
            answer: 1,
            explain: "DJP mengawasi dan menguji kebenaran lewat data dan pemeriksaan.",
          },
          {
            q: "Sejak kapan Indonesia memakai self assessment?",
            options: ["Sejak masa kolonial", "Sejak Reformasi Perpajakan 1983", "Sejak 2022", "Belum pernah"],
            answer: 1,
            explain: "Reformasi Perpajakan 1983 mengubah sistem dari official assessment ke self assessment.",
          },
        ],
      },
    ],
  },
];
