import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "tujuan-corporate-finance",
    levelId: "fondasi",
    order: 1,
    title: "Tujuan & Tiga Keputusan Corporate Finance",
    summary: "Apa yang dikejar manajer keuangan dan tiga keputusan besar yang mereka ambil.",
    durationMin: 11,
    tags: ["fondasi", "tujuan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Corporate finance</strong> adalah ilmu mengelola uang perusahaan agar menciptakan <strong>nilai</strong> sebesar mungkin bagi pemiliknya, secara berkelanjutan. Semua keputusan keuangan bermuara pada satu pertanyaan: apakah ini menambah atau mengurangi nilai perusahaan?",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga keputusan besar",
        html: "1) <strong>Investasi</strong> (capital budgeting): proyek/aset apa yang dibeli? 2) <strong>Pendanaan</strong>: dari mana uangnya, utang atau ekuitas? 3) <strong>Dividen</strong>: laba dibagikan atau diinvestasikan lagi?",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Tiga Keputusan Inti Corporate Finance",
        unit: "ilustrasi cakupan",
        source: "ilustrasi konsep",
        note: "Ketiganya saling terkait: investasi butuh pendanaan, dan sisa laba menentukan kebijakan dividen.",
        data: [
          { label: "Keputusan Investasi", value: 40 },
          { label: "Keputusan Pendanaan", value: 35 },
          { label: "Keputusan Dividen", value: 25 },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Memaksimalkan nilai, bukan sekadar laba",
        html: "Tujuannya bukan laba jangka pendek semata, melainkan <strong>nilai jangka panjang</strong> yang memperhitungkan risiko dan waktu. Laba besar yang penuh risiko bisa menghancurkan nilai.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Pemangku Kepentingan yang Dilayani Perusahaan (ilustrasi prioritas)",
        unit: "bobot perhatian relatif",
        source: "ilustrasi konsep tata kelola",
        note: "Memaksimalkan nilai pemegang saham berkelanjutan tetap menuntut perusahaan melayani pelanggan, karyawan, dan kreditur dengan baik.",
        data: [
          { label: "Pemegang saham", value: 35, color: "#6366f1" },
          { label: "Pelanggan", value: 25, color: "#0ea5e9" },
          { label: "Karyawan", value: 20, color: "#10b981" },
          { label: "Kreditur", value: 12, color: "#f59e0b" },
          { label: "Masyarakat", value: 8, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bagi dividen atau ekspansi?",
        html: "Sebuah perusahaan punya laba Rp100 miliar. Pilihan A: bagikan semua sebagai dividen. Pilihan B: tahan untuk membangun pabrik baru yang diperkirakan menghasilkan imbal hasil 20% per tahun, jauh di atas biaya modalnya 12%. Karena proyek menambah nilai (imbal hasil di atas biaya modal), menahan laba untuk ekspansi justru lebih menguntungkan pemegang saham dalam jangka panjang. Inilah keterkaitan keputusan investasi, pendanaan, dan dividen.",
      },
      {
        type: "classifyExercise",
        prompt: "Keputusan ini termasuk jenis keputusan yang mana?",
        buckets: ["Investasi", "Pendanaan", "Dividen"],
        items: [
          { text: "Membangun pabrik baru", bucket: "Investasi" },
          { text: "Menerbitkan obligasi", bucket: "Pendanaan" },
          { text: "Membagikan laba ke pemegang saham", bucket: "Dividen" },
          { text: "Membeli mesin produksi", bucket: "Investasi" },
          { text: "Memilih pinjaman bank atau saham baru", bucket: "Pendanaan" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "Capital budgeting", right: "Keputusan investasi proyek/aset" },
          { left: "Struktur modal", right: "Komposisi utang dan ekuitas" },
          { left: "Kebijakan dividen", right: "Berapa laba dibagikan vs ditahan" },
          { left: "Nilai perusahaan", right: "Yang ingin dimaksimalkan" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah proyek diperkirakan menghasilkan imbal hasil 18% per tahun, sedangkan biaya modal perusahaan 11%. Berapa kelebihan imbal hasil (spread) yang diciptakan proyek ini?",
        answer: 7,
        tolerance: 0,
        suffix: "%",
        solution: "Spread = imbal hasil proyek - biaya modal = 18% - 11% = <strong>7%</strong>. Spread positif berarti proyek menambah nilai.",
        hint: "Kurangkan biaya modal dari imbal hasil proyek.",
      },
      {
        type: "case",
        title: "Sejarah: Runtuhnya Enron 2001",
        html: "<strong>Enron</strong>, raksasa energi AS, bangkrut pada <strong>Desember 2001</strong> dengan aset sekitar USD 63 miliar, saat itu kebangkrutan terbesar dalam sejarah AS. Manajemen mengejar laba dan harga saham jangka pendek lewat rekayasa akuntansi dan tata kelola yang buruk, alih-alih membangun nilai berkelanjutan. Kasus ini menegaskan bahwa tujuan corporate finance adalah <strong>nilai jangka panjang</strong>, bukan laba semu yang menutupi risiko.",
      },
      {
        type: "takeaways",
        items: [
          "Corporate finance bertujuan memaksimalkan nilai perusahaan.",
          "Tiga keputusan besar: investasi, pendanaan, dividen.",
          "Yang dikejar adalah nilai jangka panjang, bukan laba sesaat.",
          "Proyek menambah nilai bila imbal hasilnya di atas biaya modal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama corporate finance adalah?",
            options: ["Laba sebesar mungkin tahun ini", "Memaksimalkan nilai perusahaan jangka panjang", "Menghindari pajak", "Memperbesar aset"],
            answer: 1,
            explain: "Fokusnya nilai jangka panjang yang memperhitungkan risiko dan waktu.",
          },
          {
            q: "Membangun pabrik baru termasuk keputusan?",
            options: ["Pendanaan", "Investasi", "Dividen", "Pajak"],
            answer: 1,
            explain: "Memilih proyek/aset adalah keputusan investasi (capital budgeting).",
          },
          {
            q: "Memilih antara utang dan ekuitas adalah keputusan?",
            options: ["Investasi", "Pendanaan", "Dividen", "Operasional"],
            answer: 1,
            explain: "Sumber dana (utang vs ekuitas) adalah keputusan pendanaan.",
          },
          {
            q: "Sebuah proyek menambah nilai bila?",
            options: [
              "Imbal hasilnya di bawah biaya modal",
              "Imbal hasilnya di atas biaya modal",
              "Selalu, apa pun imbal hasilnya",
              "Tidak pernah",
            ],
            answer: 1,
            explain: "Proyek menciptakan nilai jika imbal hasilnya melebihi biaya modal (WACC).",
          },
          {
            q: "Kebijakan dividen menyangkut?",
            options: [
              "Proyek mana yang dipilih",
              "Berapa laba dibagikan vs ditahan",
              "Jenis pajak",
              "Jumlah karyawan",
            ],
            answer: 1,
            explain: "Kebijakan dividen menentukan porsi laba yang dibagikan dan yang ditahan untuk reinvestasi.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "nilai-waktu-uang",
    levelId: "fondasi",
    order: 2,
    title: "Nilai Waktu Uang",
    summary: "Konsep paling fundamental di keuangan: Rp1 hari ini lebih berharga dari Rp1 nanti. Dengan video.",
    durationMin: 12,
    tags: ["nilai waktu uang", "PV", "FV"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Nilai waktu uang (time value of money)</strong> adalah fondasi seluruh keuangan. Uang yang kamu pegang hari ini bisa diinvestasikan dan berkembang, sehingga lebih berharga daripada jumlah yang sama di masa depan. Dua operasi kuncinya: <strong>compounding</strong> (ke depan) dan <strong>discounting</strong> (ke belakang).",
      },
      {
        type: "video",
        comp: "NilaiWaktuUang",
        title: "Video: Nilai Waktu Uang",
        caption: "Animasi Rp100 tumbuh dengan bunga majemuk, dan kebalikannya (discounting).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua rumus inti",
        html: "<strong>Future Value:</strong> FV = PV x (1 + r)^n. <strong>Present Value:</strong> PV = FV / (1 + r)^n. Di sini r adalah tingkat bunga/diskonto dan n adalah jumlah periode.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Pertumbuhan Rp100 dengan Bunga Majemuk 10% (ilustrasi)",
        unit: "Rp",
        source: "perhitungan FV = 100 x (1,1)^n",
        note: "Bunga majemuk membuat pertumbuhan makin cepat seiring waktu (efek bola salju).",
        data: [
          { label: "Th 0", value: 100 },
          { label: "Th 2", value: 121 },
          { label: "Th 4", value: 146 },
          { label: "Th 6", value: 177 },
          { label: "Th 8", value: 214 },
          { label: "Th 10", value: 259 },
        ],
      },
      {
        type: "chart",
        variant: "area",
        title: "Pertumbuhan Rp1 Juta dengan Bunga Majemuk 12% (ilustrasi)",
        unit: "Rp ribu",
        source: "perhitungan FV = 1.000 x (1,12)^n",
        note: "Dalam jangka panjang, efek bunga majemuk membuat nilai melonjak jauh dari setoran awal.",
        data: [
          { label: "Th 0", value: 1000 },
          { label: "Th 5", value: 1762 },
          { label: "Th 10", value: 3106 },
          { label: "Th 15", value: 5474 },
          { label: "Th 20", value: 9646 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tawaran yang menyesatkan",
        html: "Seseorang menawarkan: 'Bayar Rp10 juta sekarang, nanti 5 tahun lagi saya kembalikan Rp13 juta.' Terdengar untung Rp3 juta. Tetapi jika uang Rp10 juta itu diinvestasikan pada 8% per tahun, dalam 5 tahun menjadi sekitar Rp14,7 juta, lebih besar dari Rp13 juta. Jadi tawaran itu sebenarnya <strong>merugikan</strong> setelah memperhitungkan nilai waktu uang. Tanpa konsep ini, kita mudah tertipu angka nominal.",
      },
      {
        type: "calcExercise",
        prompt: "Berapa nilai masa depan (FV) dari Rp100 juta yang diinvestasikan 10% per tahun selama 2 tahun? (dalam juta)",
        answer: 121,
        tolerance: 0.5,
        prefix: "Rp",
        suffix: "juta",
        solution: "FV = 100 x (1,1)^2 = 100 x 1,21 = <strong>Rp121 juta</strong>.",
        hint: "FV = PV x (1 + r)^n.",
      },
      {
        type: "calcExercise",
        prompt: "Berapa nilai kini (PV) dari Rp121 juta yang diterima 2 tahun lagi, diskonto 10%? (dalam juta)",
        answer: 100,
        tolerance: 0.5,
        prefix: "Rp",
        suffix: "juta",
        solution: "PV = 121 / (1,1)^2 = 121 / 1,21 = <strong>Rp100 juta</strong>. Discounting adalah kebalikan compounding.",
        hint: "PV = FV / (1 + r)^n.",
      },
      {
        type: "calcExercise",
        prompt: "Berapa nilai masa depan (FV) dari Rp50 juta yang diinvestasikan 8% per tahun selama 3 tahun? (dalam juta)",
        answer: 62.99,
        tolerance: 0.5,
        prefix: "Rp",
        suffix: "juta",
        solution: "FV = 50 x (1,08)^3 = 50 x 1,2597 = <strong>Rp62,99 juta</strong> (sekitar Rp63 juta).",
        hint: "FV = PV x (1 + r)^n, dengan (1,08)^3 = 1,2597.",
      },
      {
        type: "classifyExercise",
        prompt: "Operasi ini compounding (ke depan) atau discounting (ke belakang)?",
        buckets: ["Compounding", "Discounting"],
        items: [
          { text: "Menghitung nilai tabungan 5 tahun lagi", bucket: "Compounding" },
          { text: "Menghitung nilai kini dari arus kas masa depan", bucket: "Discounting" },
          { text: "Menentukan NPV proyek", bucket: "Discounting" },
          { text: "Memproyeksikan saldo deposito ke depan", bucket: "Compounding" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Pembelian Pulau Manhattan 1626",
        html: "Pada <strong>1626</strong>, Peter Minuit konon membeli Pulau Manhattan dari penduduk asli dengan barang senilai sekitar <strong>USD 24</strong>. Terdengar sangat murah, tetapi bila uang sekecil itu diinvestasikan dengan bunga majemuk selama hampir <strong>400 tahun</strong>, nilainya bisa membengkak menjadi triliunan dolar. Inilah ilustrasi klasik kekuatan <strong>nilai waktu uang</strong> dan efek bunga majemuk dalam jangka sangat panjang.",
      },
      {
        type: "takeaways",
        items: [
          "Uang hari ini lebih berharga dari jumlah sama di masa depan.",
          "Compounding membawa nilai ke depan; discounting membawanya ke kini.",
          "FV = PV x (1+r)^n; PV = FV / (1+r)^n.",
          "Konsep ini mendasari NPV, valuasi, dan hampir semua keputusan keuangan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa Rp1 hari ini lebih berharga dari Rp1 tahun depan?",
            options: [
              "Karena inflasi saja",
              "Karena bisa diinvestasikan dan berkembang",
              "Karena uang cepat rusak",
              "Tidak benar, sama saja",
            ],
            answer: 1,
            explain: "Uang hari ini bisa diinvestasikan sehingga punya potensi berkembang (plus faktor risiko dan inflasi).",
          },
          {
            q: "Rumus Future Value adalah?",
            options: ["FV = PV / (1+r)^n", "FV = PV x (1+r)^n", "FV = PV x r x n", "FV = PV + r"],
            answer: 1,
            explain: "FV = PV x (1 + r)^n (bunga majemuk).",
          },
          {
            q: "Rp100 juta, bunga 10%, 1 tahun. FV-nya?",
            options: ["Rp110 juta", "Rp100 juta", "Rp90 juta", "Rp121 juta"],
            answer: 0,
            explain: "100 x 1,1 = Rp110 juta.",
          },
          {
            q: "Proses mengubah nilai masa depan menjadi nilai sekarang disebut?",
            options: ["Compounding", "Discounting", "Amortisasi", "Depresiasi"],
            answer: 1,
            explain: "Discounting membawa arus kas masa depan ke nilai kini.",
          },
          {
            q: "Diskonto yang lebih tinggi membuat present value?",
            options: ["Lebih besar", "Lebih kecil", "Tetap", "Negatif"],
            answer: 1,
            explain: "Pembagi makin besar, sehingga PV makin kecil. Risiko tinggi menurunkan nilai kini.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "risiko-imbal-hasil",
    levelId: "fondasi",
    order: 3,
    title: "Risiko & Imbal Hasil",
    summary: "Hubungan mendasar: imbal hasil lebih tinggi menuntut risiko lebih tinggi.",
    durationMin: 11,
    tags: ["risiko", "imbal hasil", "return"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak ada makan siang gratis di keuangan. Untuk mengharap <strong>imbal hasil</strong> lebih tinggi, investor harus menanggung <strong>risiko</strong> lebih tinggi. Memahami hubungan ini menjelaskan kenapa biaya modal berbeda antar perusahaan dan proyek.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Imbal Hasil Diharapkan per Kelas Aset (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi pola umum, bukan jaminan",
        note: "Makin tinggi potensi imbal hasil, makin besar risiko (fluktuasi) yang menyertainya.",
        data: [
          { label: "Deposito", value: 5, color: "#10b981" },
          { label: "Obligasi", value: 8, color: "#0ea5e9" },
          { label: "Saham besar", value: 12, color: "#f59e0b" },
          { label: "Saham kecil/startup", value: 20, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Tingkat Risiko (volatilitas) per Kelas Aset (ilustrasi)",
        unit: "% fluktuasi per tahun",
        source: "ilustrasi pola umum, bukan jaminan",
        note: "Perhatikan polanya sejajar dengan grafik imbal hasil: aset dengan imbal hasil diharapkan lebih tinggi juga berfluktuasi lebih besar. Inilah tradeoff risiko-imbal hasil.",
        data: [
          { label: "Deposito", value: 1, color: "#10b981" },
          { label: "Obligasi", value: 6, color: "#0ea5e9" },
          { label: "Saham besar", value: 18, color: "#f59e0b" },
          { label: "Saham kecil/startup", value: 35, color: "#ef4444" },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Premi risiko",
        html: "Imbal hasil yang diminta = imbal hasil bebas risiko + <strong>premi risiko</strong>. Makin berisiko sebuah investasi, makin besar premi yang dituntut investor, sehingga biaya modal (mis. biaya ekuitas) makin tinggi.",
      },
      {
        type: "case",
        title: "Studi Kasus: Dua proyek, imbal hasil sama",
        html: "Dua proyek sama-sama menjanjikan imbal hasil 15%. Proyek A stabil (kontrak jangka panjang), proyek B sangat fluktuatif (pasar baru). Investor rasional akan memilih A, atau menuntut imbal hasil lebih tinggi dari B sebagai kompensasi risiko. Imbal hasil tidak bisa dinilai tanpa melihat risikonya.",
      },
      {
        type: "calcExercise",
        prompt: "Imbal hasil bebas risiko 6% dan premi risiko saham 7%. Berapa imbal hasil yang diminta untuk saham itu?",
        answer: 13,
        tolerance: 0,
        suffix: "%",
        solution: "Imbal hasil diminta = 6% + 7% = <strong>13%</strong>.",
        hint: "Jumlahkan tingkat bebas risiko dengan premi risiko.",
      },
      {
        type: "classifyExercise",
        prompt: "Urutkan: investasi ini umumnya berisiko rendah atau tinggi?",
        buckets: ["Risiko rendah", "Risiko tinggi"],
        items: [
          { text: "Deposito bank", bucket: "Risiko rendah" },
          { text: "Obligasi pemerintah", bucket: "Risiko rendah" },
          { text: "Saham startup tahap awal", bucket: "Risiko tinggi" },
          { text: "Modal ventura", bucket: "Risiko tinggi" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kelas aset dengan profil imbal hasil diharapkannya (ilustrasi).",
        pairs: [
          { left: "Deposito", right: "Sekitar 5% per tahun, risiko rendah" },
          { left: "Obligasi", right: "Sekitar 8% per tahun, risiko menengah" },
          { left: "Saham besar", right: "Sekitar 12% per tahun, risiko tinggi" },
          { left: "Saham kecil/startup", right: "Sekitar 20% per tahun, risiko sangat tinggi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Keruntuhan LTCM 1998",
        html: "<strong>Long-Term Capital Management (LTCM)</strong>, hedge fund yang diperkuat dua peraih Nobel, mengejar imbal hasil tinggi dengan leverage sangat besar (rasio utang terhadap modal di atas <strong>25 kali</strong>). Ketika pasar bergejolak pada <strong>1998</strong>, kerugian melonjak dan dana ini nyaris runtuh, hingga Federal Reserve mengoordinasikan dana talangan sekitar <strong>USD 3,6 miliar</strong> dari 14 bank. Imbal hasil tinggi ternyata datang bersama risiko tinggi yang nyaris menghancurkannya.",
      },
      {
        type: "takeaways",
        items: [
          "Imbal hasil lebih tinggi menuntut risiko lebih tinggi.",
          "Imbal hasil diminta = bebas risiko + premi risiko.",
          "Risiko menentukan biaya modal perusahaan.",
          "Imbal hasil tidak bermakna tanpa melihat risikonya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Hubungan dasar risiko dan imbal hasil adalah?",
            options: [
              "Risiko tinggi, imbal hasil rendah",
              "Imbal hasil lebih tinggi menuntut risiko lebih tinggi",
              "Tidak ada hubungan",
              "Risiko selalu nol",
            ],
            answer: 1,
            explain: "Investor menuntut kompensasi (imbal hasil) lebih besar untuk risiko lebih besar.",
          },
          {
            q: "Imbal hasil yang diminta investor terdiri dari?",
            options: [
              "Hanya inflasi",
              "Tingkat bebas risiko + premi risiko",
              "Hanya pajak",
              "Hanya bunga bank",
            ],
            answer: 1,
            explain: "Imbal hasil diminta = tingkat bebas risiko ditambah premi risiko.",
          },
          {
            q: "Mana yang umumnya paling berisiko?",
            options: ["Deposito", "Obligasi pemerintah", "Saham startup", "Tabungan"],
            answer: 2,
            explain: "Saham startup tahap awal punya ketidakpastian tertinggi.",
          },
          {
            q: "Bebas risiko 5%, premi risiko 8%. Imbal hasil diminta?",
            options: ["3%", "13%", "8%", "40%"],
            answer: 1,
            explain: "5% + 8% = 13%.",
          },
          {
            q: "Proyek berisiko lebih tinggi seharusnya dinilai dengan diskonto?",
            options: ["Lebih rendah", "Lebih tinggi", "Nol", "Sama saja"],
            answer: 1,
            explain: "Risiko lebih tinggi berarti biaya modal/diskonto lebih tinggi, sehingga nilai kini lebih kecil.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "utang-vs-ekuitas",
    levelId: "fondasi",
    order: 4,
    title: "Utang vs Ekuitas",
    summary: "Dua cara mendanai perusahaan, masing-masing dengan biaya, risiko, dan konsekuensi berbeda. Dengan kalkulator WACC.",
    durationMin: 12,
    tags: ["utang", "ekuitas", "WACC"],
    blocks: [
      {
        type: "paragraph",
        html: "Untuk mendanai usahanya, perusahaan punya dua sumber utama: <strong>utang</strong> (pinjaman/obligasi) dan <strong>ekuitas</strong> (modal pemilik/saham). Keduanya punya biaya dan konsekuensi berbeda, dan kombinasinya membentuk <strong>biaya modal (WACC)</strong>.",
      },
      {
        type: "table",
        caption: "Utang vs Ekuitas",
        headers: ["Aspek", "Utang", "Ekuitas"],
        rows: [
          ["Kewajiban", "Wajib bayar bunga & pokok", "Tidak wajib (dividen opsional)"],
          ["Risiko bagi perusahaan", "Tinggi (bisa gagal bayar)", "Rendah"],
          ["Biaya", "Lebih murah (ada tax shield)", "Lebih mahal"],
          ["Kontrol", "Tidak mengencerkan kepemilikan", "Mengencerkan kepemilikan"],
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Contoh Struktur Modal Perusahaan (capital mix, ilustrasi)",
        unit: "% dari total modal",
        source: "ilustrasi konsep",
        note: "Komposisi 60% ekuitas dan 40% utang ini dipakai pada latihan WACC di bawah. Tidak ada rasio ideal tunggal, tergantung industri dan stabilitas arus kas.",
        data: [
          { label: "Ekuitas", value: 60, color: "#6366f1" },
          { label: "Utang", value: 40, color: "#f59e0b" },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Kenapa utang lebih murah?",
        html: "Bunga utang <strong>mengurangi pajak</strong> (tax shield), dan pemberi utang menanggung risiko lebih kecil dari pemegang saham. Tapi utang menambah kewajiban tetap, sehingga terlalu banyak utang berbahaya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulator WACC",
        html: "Atur porsi utang dan ekuitas beserta biayanya untuk melihat biaya modal rata-rata (WACC) perusahaan.",
      },
      { type: "widget", widget: "KalkulatorWACC" },
      {
        type: "case",
        title: "Studi Kasus: Terlalu banyak utang",
        html: "Sebuah perusahaan tergiur memakai banyak utang karena murah. Saat penjualan turun, ia tetap wajib membayar bunga besar, kasnya tergerus, dan nyaris gagal bayar. Sebaliknya, pesaing yang seimbang antara utang dan ekuitas tetap bertahan. Pelajaran: utang menambah imbal hasil saat baik, tetapi memperbesar risiko saat buruk. Keseimbangan adalah kuncinya.",
      },
      {
        type: "calcExercise",
        prompt: "Ekuitas Rp600 M (biaya 15%) dan utang Rp400 M (biaya setelah pajak 7%). Berapa WACC-nya? (total Rp1.000 M)",
        answer: 11.8,
        tolerance: 0.2,
        suffix: "%",
        solution: "WACC = (600/1000 x 15%) + (400/1000 x 7%) = 9% + 2,8% = <strong>11,8%</strong>.",
        hint: "Bobot tiap sumber dikali biayanya, lalu dijumlahkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri ini milik utang atau ekuitas?",
        buckets: ["Utang", "Ekuitas"],
        items: [
          { text: "Wajib membayar bunga", bucket: "Utang" },
          { text: "Mengencerkan kepemilikan", bucket: "Ekuitas" },
          { text: "Mendapat tax shield", bucket: "Utang" },
          { text: "Tidak ada kewajiban bayar tetap", bucket: "Ekuitas" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah pendanaan dengan maknanya.",
        pairs: [
          { left: "Tax shield", right: "Penghematan pajak dari bunga utang" },
          { left: "Dilusi", right: "Pengenceran kepemilikan akibat saham baru" },
          { left: "WACC", right: "Biaya modal rata-rata tertimbang" },
          { left: "Gagal bayar", right: "Risiko utama dari utang berlebih" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Kebangkrutan Lehman Brothers 2008",
        html: "<strong>Lehman Brothers</strong> mendanai dirinya dengan utang yang sangat besar, dengan rasio leverage sekitar <strong>30 banding 1</strong> terhadap ekuitasnya. Saat nilai asetnya jatuh pada krisis 2008, bantalan ekuitas yang tipis tidak cukup menyerap kerugian, dan bank ini bangkrut pada <strong>September 2008</strong> dengan aset sekitar USD 600 miliar, kebangkrutan terbesar dalam sejarah AS. Terlalu banyak utang membuat perusahaan rapuh ketika keadaan memburuk.",
      },
      {
        type: "takeaways",
        items: [
          "Dua sumber dana: utang dan ekuitas.",
          "Utang lebih murah (tax shield) tetapi menambah kewajiban tetap.",
          "Ekuitas lebih mahal tetapi tidak membebani kas wajib.",
          "Kombinasinya membentuk WACC; keseimbangan penting.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa utang umumnya lebih murah dari ekuitas?",
            options: [
              "Karena tidak perlu dibayar",
              "Karena bunga mengurangi pajak dan risikonya lebih kecil",
              "Karena selalu gratis",
              "Karena dilarang",
            ],
            answer: 1,
            explain: "Bunga memberi tax shield, dan kreditur menanggung risiko lebih kecil dari pemegang saham.",
          },
          {
            q: "Kelemahan utama utang adalah?",
            options: [
              "Mengencerkan kepemilikan",
              "Kewajiban bayar tetap yang berisiko saat laba turun",
              "Tidak ada bunganya",
              "Selalu lebih mahal",
            ],
            answer: 1,
            explain: "Utang menambah kewajiban tetap; saat pendapatan turun, risiko gagal bayar meningkat.",
          },
          {
            q: "Menerbitkan saham baru akan?",
            options: ["Menambah utang", "Mengencerkan kepemilikan pemegang saham lama", "Mengurangi pajak", "Menghapus risiko"],
            answer: 1,
            explain: "Saham baru menambah jumlah pemilik, sehingga porsi pemegang lama mengecil (dilusi).",
          },
          {
            q: "WACC adalah?",
            options: [
              "Pajak perusahaan",
              "Biaya modal rata-rata tertimbang dari utang dan ekuitas",
              "Laba bersih",
              "Nilai saham",
            ],
            answer: 1,
            explain: "WACC menggabungkan biaya utang dan ekuitas sesuai bobotnya.",
          },
          {
            q: "Ekuitas Rp500 M (12%), utang Rp500 M (8% setelah pajak). WACC?",
            options: ["10%", "20%", "8%", "12%"],
            answer: 0,
            explain: "(0,5 x 12%) + (0,5 x 8%) = 6% + 4% = 10%.",
          },
        ],
      },
    ],
  },
];
