import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "manajemen-kas-modal-kerja",
    levelId: "treasury",
    order: 1,
    title: "Manajemen Kas & Modal Kerja",
    summary: "Menjaga perusahaan punya cukup uang untuk operasi sehari-hari. Dengan simulator cash conversion cycle.",
    durationMin: 13,
    tags: ["treasury", "modal kerja", "likuiditas"],
    blocks: [
      {
        type: "paragraph",
        html: "Banyak perusahaan untung di atas kertas tetapi kolaps karena kehabisan kas. <strong>Treasury</strong> menjaga likuiditas: memastikan selalu ada uang untuk bayar gaji, pemasok, dan utang. Inti operasionalnya adalah mengelola <strong>modal kerja</strong>.",
      },
      {
        type: "video",
        comp: "CashConversionVideo",
        title: "Memahami Cash Conversion Cycle",
        caption: "Animasi alur uang dari kas ke persediaan, piutang, lalu kembali jadi kas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cash Conversion Cycle (CCC)",
        html: "CCC = DIO + DSO - DPO. <strong>DIO</strong> (hari persediaan), <strong>DSO</strong> (hari piutang), <strong>DPO</strong> (hari utang). Makin pendek CCC, makin cepat uang berputar kembali jadi kas.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur DIO, DSO, dan DPO untuk melihat berapa hari uang 'terjebak' di modal kerja.",
      },
      { type: "widget", widget: "SimulatorCashConversion" },
      {
        type: "callout",
        tone: "tip",
        title: "Hitung kebutuhan modal kerja",
        html: "Gunakan kalkulator berikut untuk mengestimasi berapa rupiah modal kerja yang harus didanai berdasarkan persediaan, piutang, dan utang usaha.",
      },
      { type: "widget", widget: "KalkulatorModalKerja" },
      {
        type: "chart",
        variant: "bar",
        title: "Laba Tinggi Tapi Kas Tipis (ilustrasi)",
        unit: "Rp miliar",
        source: "ilustrasi konsep",
        note: "Laba besar bisa 'terkunci' di piutang dan persediaan, sehingga kas justru menipis.",
        data: [
          { label: "Laba (akuntansi)", value: 50, color: "#10b981" },
          { label: "Tertahan di piutang", value: 30, color: "#f59e0b" },
          { label: "Tertahan di persediaan", value: 25, color: "#f59e0b" },
          { label: "Kas riil", value: -5, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komponen Cash Conversion Cycle (ilustrasi)",
        unit: "hari",
        source: "ilustrasi konsep",
        note: "DIO dan DSO memperpanjang CCC, sedangkan DPO memperpendeknya. CCC = 60 + 45 - 30 = 75 hari.",
        data: [
          { label: "DIO (persediaan)", value: 60, color: "#f59e0b" },
          { label: "DSO (piutang)", value: 45, color: "#3b82f6" },
          { label: "DPO (utang, mengurangi)", value: 30, color: "#10b981" },
          { label: "CCC bersih", value: 75, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Untung tapi nyaris bangkrut",
        html: "Sebuah distributor tumbuh pesat dan membukukan laba besar. Namun pelanggan membayar 90 hari (DSO tinggi), sementara pemasok harus dibayar 30 hari (DPO rendah), dan stok menumpuk (DIO tinggi). CCC-nya sangat panjang, kas terkuras untuk mendanai pertumbuhan. Solusinya: percepat penagihan, negosiasi tempo pemasok lebih panjang, dan kurangi stok berlebih. Likuiditas, bukan laba, yang menjaga perusahaan tetap hidup.",
      },
      {
        type: "calcExercise",
        prompt: "DIO 60 hari, DSO 45 hari, DPO 30 hari. Berapa Cash Conversion Cycle-nya?",
        answer: 75,
        tolerance: 0,
        suffix: "hari",
        solution: "CCC = DIO + DSO - DPO = 60 + 45 - 30 = <strong>75 hari</strong>.",
        hint: "CCC = DIO + DSO - DPO.",
      },
      {
        type: "calcExercise",
        prompt: "Awalnya DSO 50 hari. Setelah penagihan dipercepat, DSO turun jadi 35 hari (DIO dan DPO tetap). Berapa hari CCC memendek?",
        answer: 15,
        tolerance: 0,
        suffix: "hari",
        solution: "Penurunan DSO langsung menurunkan CCC dengan jumlah sama: 50 - 35 = <strong>15 hari</strong> lebih pendek.",
        hint: "Perubahan CCC = perubahan DSO bila DIO dan DPO tidak berubah.",
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini memperpendek (baik) atau memperpanjang (buruk) CCC?",
        buckets: ["Memperpendek (baik)", "Memperpanjang (buruk)"],
        items: [
          { text: "Mempercepat penagihan piutang", bucket: "Memperpendek (baik)" },
          { text: "Menumpuk persediaan berlebih", bucket: "Memperpanjang (buruk)" },
          { text: "Menegosiasi tempo bayar pemasok lebih lama", bucket: "Memperpendek (baik)" },
          { text: "Memberi pelanggan tempo bayar sangat panjang", bucket: "Memperpanjang (buruk)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Modal Kerja Negatif Dell",
        html: "Pada akhir <strong>1990-an</strong>, <strong>Dell</strong> merevolusi manajemen modal kerja lewat model build-to-order: pelanggan membayar di muka sementara pemasok dibayar belakangan. Akibatnya Dell mencapai <strong>cash conversion cycle negatif</strong>, artinya perusahaan justru menerima kas sebelum harus mengeluarkannya. Pengelolaan modal kerja yang ketat ini mendanai pertumbuhan Dell tanpa banyak bergantung pada utang.",
      },
      {
        type: "takeaways",
        items: [
          "Treasury menjaga likuiditas: selalu ada kas untuk operasi.",
          "CCC = DIO + DSO - DPO; makin pendek makin sehat.",
          "Laba tinggi tidak menjamin kas cukup.",
          "Percepat penagihan, kelola stok, atur tempo pemasok.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fokus utama treasury adalah?",
            options: ["Memaksimalkan laba akuntansi", "Menjaga likuiditas (ketersediaan kas)", "Membayar pajak", "Menambah aset"],
            answer: 1,
            explain: "Treasury memastikan perusahaan selalu punya kas untuk kewajibannya.",
          },
          {
            q: "Rumus Cash Conversion Cycle adalah?",
            options: ["DIO + DSO + DPO", "DIO + DSO - DPO", "DPO - DIO - DSO", "DSO - DIO"],
            answer: 1,
            explain: "CCC = DIO + DSO - DPO.",
          },
          {
            q: "DIO 50, DSO 40, DPO 30. CCC?",
            options: ["60 hari", "120 hari", "20 hari", "90 hari"],
            answer: 0,
            explain: "50 + 40 - 30 = 60 hari.",
          },
          {
            q: "Perusahaan bisa bangkrut walau untung karena?",
            options: ["Pajak terlalu kecil", "Kehabisan kas (likuiditas)", "Laba terlalu besar", "Tidak ada utang"],
            answer: 1,
            explain: "Tanpa kas untuk kewajiban jatuh tempo, perusahaan bisa kolaps meski laba di atas kertas.",
          },
          {
            q: "Mana yang memperpendek CCC?",
            options: ["Menumpuk stok", "Mempercepat penagihan piutang", "Membayar pemasok lebih cepat", "Memberi tempo panjang ke pelanggan"],
            answer: 1,
            explain: "Penagihan lebih cepat menurunkan DSO sehingga CCC memendek.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "risiko-nilai-tukar",
    levelId: "treasury",
    order: 2,
    title: "Risiko Nilai Tukar (FX) & Hedging",
    summary: "Mengenali eksposur valuta asing dan cara melindungi nilai dengan forward serta natural hedge.",
    durationMin: 14,
    tags: ["treasury", "fx", "hedging", "risiko"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan yang berdagang lintas negara menghadapi <strong>risiko nilai tukar</strong>: nilai kas, piutang, atau utang dalam mata uang asing bisa berubah saat kurs bergerak. Bagi importir dan eksportir Indonesia, fluktuasi rupiah terhadap dolar AS bisa menggerus margin secara tiba-tiba.",
      },
      {
        type: "video",
        comp: "HedgingFXVideo",
        title: "Cara Kerja Hedging Nilai Tukar",
        caption: "Penjelasan visual bagaimana kontrak forward mengunci kurs dan meredam risiko valas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga jenis eksposur FX",
        html: "<strong>Eksposur transaksi:</strong> arus kas masa depan dalam valas (misal tagihan impor jatuh tempo). <strong>Eksposur translasi:</strong> konversi laporan keuangan anak usaha luar negeri ke rupiah. <strong>Eksposur ekonomi:</strong> dampak jangka panjang kurs pada daya saing dan arus kas.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Lindung nilai dengan forward",
        html: "<strong>Kontrak forward</strong> mengunci kurs untuk transaksi di masa depan. Importir yang harus bayar USD 3 bulan lagi bisa mengunci kurs sekarang, sehingga biaya rupiahnya pasti, tidak peduli kurs naik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulator hedging",
        html: "Atur jumlah valas, kurs spot, kurs forward, dan skenario pergerakan kurs untuk membandingkan biaya posisi yang di-hedge dan yang tidak.",
      },
      { type: "widget", widget: "SimulatorHedgingFX" },
      {
        type: "chart",
        variant: "line",
        title: "Dampak Pelemahan Rupiah ke Biaya Impor (ilustrasi)",
        unit: "Rp juta per USD 100k",
        source: "ilustrasi konsep",
        note: "Saat rupiah melemah dari Rp15.000 ke Rp16.500 per USD, biaya impor yang sama membengkak.",
        data: [
          { label: "Rp15.000/USD", value: 1500, color: "#10b981" },
          { label: "Rp15.500/USD", value: 1550, color: "#f59e0b" },
          { label: "Rp16.000/USD", value: 1600, color: "#f59e0b" },
          { label: "Rp16.500/USD", value: 1650, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Impor USD 500k: Hedged vs Unhedged (ilustrasi)",
        unit: "Rp miliar",
        source: "ilustrasi konsep",
        note: "Forward mengunci biaya di Rp7,55 M. Tanpa hedging, biaya membengkak mengikuti pelemahan rupiah.",
        data: [
          { label: "Hedged (terkunci Rp15.100)", value: 7.55, color: "#10b981" },
          { label: "Unhedged @Rp15.500", value: 7.75, color: "#f59e0b" },
          { label: "Unhedged @Rp16.000", value: 8.0, color: "#f59e0b" },
          { label: "Unhedged @Rp16.500", value: 8.25, color: "#ef4444" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "+10%", label: "Pelemahan rupiah", sub: "kurs naik dari 15.000 ke 16.500", color: "#ef4444" },
          { value: "+Rp150 jt", label: "Tambahan biaya impor", sub: "per USD 100k (ilustrasi)", color: "#f59e0b" },
          { value: "Rp0", label: "Tambahan biaya jika di-hedge", sub: "kurs sudah dikunci forward", color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Importir terkena lonjakan kurs",
        html: "Sebuah importir mesin memesan barang senilai USD 500.000 dengan pembayaran 90 hari. Saat pesan, kurs Rp15.000/USD (nilai Rp7,5 miliar). Tiga bulan kemudian rupiah melemah ke Rp16.500/USD, sehingga harus membayar Rp8,25 miliar, membengkak Rp750 juta yang menghapus seluruh margin. Bila perusahaan membeli forward USD 500.000 di kurs Rp15.100, biayanya terkunci Rp7,55 miliar. Alternatif lain: <strong>natural hedge</strong>, yaitu mencocokkan pendapatan valas dengan biaya valas agar saling meredam.",
      },
      {
        type: "calcExercise",
        prompt: "Tagihan impor USD 200.000. Kurs naik dari Rp15.000 ke Rp15.800 per USD. Berapa tambahan biaya rupiah (juta) tanpa hedging?",
        answer: 160,
        tolerance: 0,
        suffix: "juta",
        solution: "Selisih kurs = Rp800/USD. 200.000 x 800 = Rp160.000.000 = <strong>Rp160 juta</strong>.",
        hint: "Selisih kurs x jumlah USD.",
      },
      {
        type: "calcExercise",
        prompt: "Importir mengunci forward USD 500.000 di Rp15.100. Saat jatuh tempo kurs spot Rp16.500. Berapa rupiah (juta) yang dihemat berkat hedging?",
        answer: 700,
        tolerance: 0,
        suffix: "juta",
        solution: "Selisih kurs = 16.500 - 15.100 = Rp1.400/USD. 500.000 x 1.400 = Rp700.000.000 = <strong>Rp700 juta</strong> lebih murah dibanding membeli di spot.",
        hint: "(Kurs spot - kurs forward) x jumlah USD.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan situasi ini ke jenis eksposur FX yang sesuai.",
        buckets: ["Eksposur transaksi", "Eksposur translasi"],
        items: [
          { text: "Tagihan impor USD jatuh tempo 60 hari lagi", bucket: "Eksposur transaksi" },
          { text: "Konversi laporan anak usaha di Singapura ke rupiah", bucket: "Eksposur translasi" },
          { text: "Piutang ekspor dalam EUR belum diterima", bucket: "Eksposur transaksi" },
          { text: "Penggabungan neraca cabang luar negeri ke induk", bucket: "Eksposur translasi" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan definisinya.",
        pairs: [
          { left: "Kontrak forward", right: "Mengunci kurs untuk transaksi masa depan" },
          { left: "Natural hedge", right: "Mencocokkan pendapatan valas dengan biaya valas" },
          { left: "Eksposur translasi", right: "Risiko saat mengonversi laporan valas ke rupiah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Rupiah 1997-1998",
        html: "Selama <strong>Krisis Moneter Asia 1997-1998</strong>, nilai tukar rupiah ambruk dari sekitar <strong>Rp2.400 per USD</strong> menjadi sempat hampir <strong>Rp16.000 per USD</strong>. Banyak perusahaan Indonesia yang berutang dalam dolar AS tanpa lindung nilai mendadak melihat beban utangnya melonjak berkali-kali lipat dalam rupiah, dan sebagian besar bangkrut. Peristiwa ini menjadi pelajaran pahit tentang pentingnya hedging dan natural hedge terhadap risiko nilai tukar.",
      },
      {
        type: "takeaways",
        items: [
          "Eksposur FX ada tiga: transaksi, translasi, dan ekonomi.",
          "Forward mengunci kurs sehingga biaya/penerimaan menjadi pasti.",
          "Natural hedge mencocokkan arus masuk dan keluar valas.",
          "Pelemahan rupiah memukul importir, menguntungkan eksportir.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Eksposur transaksi berkaitan dengan?",
            options: ["Konversi laporan keuangan valas", "Arus kas masa depan dalam valuta asing", "Pembayaran pajak", "Harga saham"],
            answer: 1,
            explain: "Eksposur transaksi adalah risiko pada arus kas valas yang akan terjadi, seperti tagihan impor.",
          },
          {
            q: "Fungsi utama kontrak forward adalah?",
            options: ["Menaikkan laba", "Mengunci kurs untuk masa depan", "Menghindari pajak", "Menambah modal"],
            answer: 1,
            explain: "Forward mengunci kurs sehingga biaya atau penerimaan valas menjadi pasti.",
          },
          {
            q: "Pelemahan rupiah paling merugikan?",
            options: ["Eksportir", "Importir", "Bank sentral", "Pemegang obligasi rupiah"],
            answer: 1,
            explain: "Importir membayar lebih banyak rupiah untuk jumlah valas yang sama.",
          },
          {
            q: "Natural hedge dilakukan dengan?",
            options: ["Membeli opsi", "Mencocokkan pendapatan dan biaya dalam mata uang sama", "Menambah utang rupiah", "Menahan kas"],
            answer: 1,
            explain: "Natural hedge mencocokkan arus masuk dan keluar valas agar saling meredam.",
          },
          {
            q: "Tagihan impor USD 100k, kurs naik Rp1.000/USD. Tambahan biaya?",
            options: ["Rp10 juta", "Rp100 juta", "Rp1 miliar", "Rp1 juta"],
            answer: 1,
            explain: "100.000 x 1.000 = Rp100 juta.",
          },
          {
            q: "Eksposur translasi muncul saat?",
            options: ["Menjual produk lokal", "Mengonversi laporan anak usaha luar negeri ke rupiah", "Membayar gaji rupiah", "Membeli bahan baku lokal"],
            answer: 1,
            explain: "Eksposur translasi terjadi ketika laporan keuangan valas dikonversi ke mata uang induk.",
          },
          {
            q: "Eksportir Indonesia diuntungkan saat?",
            options: ["Rupiah menguat", "Rupiah melemah", "Kurs tetap", "Suku bunga naik"],
            answer: 1,
            explain: "Rupiah melemah membuat penerimaan valas eksportir bernilai lebih banyak rupiah.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pendanaan-jangka-pendek",
    levelId: "treasury",
    order: 3,
    title: "Pendanaan Jangka Pendek",
    summary: "Instrumen menutup kebutuhan kas sementara: revolving credit, commercial paper, supply chain financing, dan anjak piutang.",
    durationMin: 13,
    tags: ["treasury", "pendanaan", "likuiditas", "modal kerja"],
    blocks: [
      {
        type: "paragraph",
        html: "Kebutuhan kas sering bersifat musiman atau sementara: pembelian stok menjelang puncak penjualan, atau jeda sebelum pelanggan membayar. <strong>Pendanaan jangka pendek</strong> menjembatani celah ini tanpa harus menambah modal permanen atau utang jangka panjang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat instrumen utama",
        html: "<strong>Revolving credit:</strong> plafon pinjaman yang bisa ditarik dan dilunasi berulang. <strong>Commercial paper:</strong> surat utang tanpa jaminan jangka pendek dari perusahaan bonafide. <strong>Supply chain financing:</strong> bank membayar pemasok lebih awal, pembeli bayar belakangan. <strong>Anjak piutang (factoring):</strong> menjual piutang ke pihak ketiga untuk kas segera.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Cocokkan tenor dengan kebutuhan",
        html: "Gunakan dana jangka pendek untuk kebutuhan jangka pendek (modal kerja), bukan untuk aset jangka panjang. Ketidakcocokan tenor adalah sumber krisis likuiditas.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Biaya Efektif Tahunan (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi konsep",
        note: "Biaya efektif bervariasi menurut risiko dan jaminan; angka hanya gambaran relatif.",
        data: [
          { label: "Revolving credit", value: 11, color: "#10b981" },
          { label: "Commercial paper", value: 9, color: "#3b82f6" },
          { label: "Supply chain financing", value: 12, color: "#f59e0b" },
          { label: "Anjak piutang", value: 16, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Pendanaan Jangka Pendek (ilustrasi)",
        unit: "%",
        source: "ilustrasi konsep",
        note: "Banyak perusahaan mengandalkan revolving credit sebagai tulang punggung, dilengkapi instrumen lain sesuai kebutuhan.",
        data: [
          { label: "Revolving credit", value: 45, color: "#10b981" },
          { label: "Commercial paper", value: 25, color: "#3b82f6" },
          { label: "Supply chain financing", value: 18, color: "#f59e0b" },
          { label: "Anjak piutang", value: 12, color: "#ef4444" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "Rp10 M", label: "Plafon revolving", sub: "ditarik sesuai kebutuhan", color: "#10b981" },
          { value: "Rp4 M", label: "Terpakai bulan ini", sub: "bunga hanya atas yang ditarik", color: "#3b82f6" },
          { value: "Rp6 M", label: "Sisa plafon", sub: "siap dipakai bila perlu", color: "#64748b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menutup celah kas musiman",
        html: "Sebuah produsen makanan menumpuk stok bahan baku menjelang Lebaran, butuh tambahan kas Rp5 miliar selama 2 bulan. Daripada menjual aset, perusahaan menarik <strong>revolving credit</strong> Rp5 miliar dengan bunga 12% per tahun. Biaya bunga 2 bulan = Rp5 M x 12% x (2/12) = Rp100 juta. Setelah penjualan Lebaran masuk, pinjaman dilunasi dan plafon kembali penuh untuk siklus berikutnya. Untuk mempercepat kas, sebagian piutang grosir juga dianjak-piutangkan agar tidak menunggu tempo 60 hari.",
      },
      {
        type: "calcExercise",
        prompt: "Menarik revolving credit Rp5 miliar, bunga 12% per tahun, selama 3 bulan. Berapa biaya bunga (juta)?",
        answer: 150,
        tolerance: 0,
        suffix: "juta",
        solution: "Bunga = 5.000 x 12% x (3/12) = Rp150 juta.",
        hint: "Pokok x bunga tahunan x (bulan/12).",
      },
      {
        type: "calcExercise",
        prompt: "Perusahaan menganjak-piutangkan tagihan Rp1 miliar dengan biaya (diskonto) 4%. Berapa kas yang diterima sekarang (juta)?",
        answer: 960,
        tolerance: 0,
        suffix: "juta",
        solution: "Biaya = 1.000 x 4% = Rp40 juta. Kas diterima = 1.000 - 40 = <strong>Rp960 juta</strong>.",
        hint: "Kas diterima = nilai piutang - (nilai piutang x diskonto).",
      },
      {
        type: "classifyExercise",
        prompt: "Pasangkan kebutuhan dengan instrumen yang paling cocok.",
        buckets: ["Anjak piutang", "Revolving credit"],
        items: [
          { text: "Butuh kas segera dari tagihan pelanggan tempo 60 hari", bucket: "Anjak piutang" },
          { text: "Kebutuhan kas naik-turun yang ingin ditarik fleksibel", bucket: "Revolving credit" },
          { text: "Mencairkan piutang tanpa menunggu jatuh tempo", bucket: "Anjak piutang" },
          { text: "Plafon siaga untuk lonjakan modal kerja musiman", bucket: "Revolving credit" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen dengan ciri khasnya.",
        pairs: [
          { left: "Commercial paper", right: "Surat utang jangka pendek tanpa jaminan" },
          { left: "Supply chain financing", right: "Bank bayar pemasok lebih awal, pembeli bayar belakangan" },
          { left: "Revolving credit", right: "Plafon yang bisa ditarik dan dilunasi berulang" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Bank Run Northern Rock 2007",
        html: "Bank Inggris <strong>Northern Rock</strong> mendanai kredit hipotek jangka panjangnya dengan terlalu banyak pinjaman jangka pendek dari pasar uang. Ketika pasar pendanaan membeku pada <strong>2007</strong>, bank tak bisa memperpanjang pinjamannya dan mengalami antrean penarikan dana nasabah pertama di Inggris sejak <strong>1866</strong>, hingga akhirnya dinasionalisasi pada 2008. Kasus ini menegaskan bahaya ketidakcocokan tenor: mendanai kebutuhan jangka panjang dengan dana jangka pendek.",
      },
      {
        type: "takeaways",
        items: [
          "Pendanaan jangka pendek menjembatani celah kas sementara.",
          "Revolving credit fleksibel; bunga hanya atas yang ditarik.",
          "Commercial paper murah tapi hanya untuk emiten bonafide.",
          "Anjak piutang mencairkan piutang lebih cepat dengan biaya lebih tinggi.",
          "Cocokkan tenor pendanaan dengan tenor kebutuhan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ciri utama revolving credit adalah?",
            options: ["Sekali tarik, tidak bisa diulang", "Bisa ditarik dan dilunasi berulang dalam plafon", "Wajib ada jaminan saham", "Hanya untuk aset tetap"],
            answer: 1,
            explain: "Revolving credit memberi plafon yang dapat ditarik dan dilunasi berkali-kali.",
          },
          {
            q: "Commercial paper umumnya?",
            options: ["Surat utang jangka panjang berjaminan", "Surat utang jangka pendek tanpa jaminan dari emiten bonafide", "Saham preferen", "Pinjaman bank bersubsidi"],
            answer: 1,
            explain: "Commercial paper adalah surat utang jangka pendek tanpa jaminan yang diterbitkan perusahaan kuat.",
          },
          {
            q: "Anjak piutang (factoring) berarti?",
            options: ["Menjual aset tetap", "Menjual piutang untuk kas segera", "Menerbitkan saham baru", "Menunda bayar pemasok"],
            answer: 1,
            explain: "Factoring menjual piutang ke pihak ketiga agar kas masuk lebih cepat.",
          },
          {
            q: "Supply chain financing membuat?",
            options: ["Pemasok dibayar lebih awal, pembeli bayar belakangan", "Pembeli bayar lebih cepat", "Piutang dihapus", "Modal saham bertambah"],
            answer: 0,
            explain: "Skema ini membayar pemasok lebih awal lewat bank, sementara pembeli menunda pembayaran.",
          },
          {
            q: "Tarik Rp2 M, bunga 12% setahun, 6 bulan. Biaya bunga?",
            options: ["Rp120 juta", "Rp240 juta", "Rp24 juta", "Rp60 juta"],
            answer: 0,
            explain: "2.000 x 12% x (6/12) = Rp120 juta.",
          },
          {
            q: "Kesalahan tenor yang berbahaya adalah?",
            options: ["Mendanai modal kerja dengan dana jangka pendek", "Mendanai aset jangka panjang dengan dana jangka pendek", "Melunasi utang lebih cepat", "Menambah plafon siaga"],
            answer: 1,
            explain: "Mendanai aset jangka panjang dengan dana jangka pendek menciptakan risiko refinancing dan krisis likuiditas.",
          },
          {
            q: "Mengapa biaya efektif anjak piutang cenderung lebih tinggi?",
            options: ["Karena selalu tanpa risiko", "Karena menanggung risiko penagihan dan kecepatan kas", "Karena dijamin pemerintah", "Karena tenornya panjang"],
            answer: 1,
            explain: "Penyedia factoring menanggung risiko dan memberi kas cepat, sehingga menuntut imbalan lebih besar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "manajemen-likuiditas",
    levelId: "treasury",
    order: 4,
    title: "Manajemen Likuiditas & Kas",
    summary: "Menjaga kas selalu cukup lewat cash pooling, buffer likuiditas, hubungan bank, dan proyeksi arus kas.",
    durationMin: 14,
    tags: ["treasury", "likuiditas", "kas", "arus kas"],
    blocks: [
      {
        type: "paragraph",
        html: "Manajemen likuiditas memastikan perusahaan punya kas yang cukup, di tempat yang tepat, pada waktu yang tepat, tanpa menahan terlalu banyak kas menganggur. Empat pilarnya: <strong>cash pooling</strong>, <strong>buffer likuiditas</strong>, <strong>hubungan bank</strong>, dan <strong>proyeksi arus kas</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cash pooling",
        html: "Menggabungkan saldo kas dari banyak rekening atau anak usaha ke satu posisi terpusat. Saldo unit yang surplus menutup unit yang defisit, sehingga perusahaan mengurangi pinjaman dan memaksimalkan bunga atas kas total.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Buffer secukupnya",
        html: "Buffer likuiditas adalah kas cadangan untuk kejutan. Terlalu kecil berisiko gagal bayar; terlalu besar berarti uang menganggur yang seharusnya bisa diinvestasikan. Cari titik seimbang lewat proyeksi arus kas.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Proyeksi Arus Kas Mingguan vs Buffer Minimum (ilustrasi)",
        unit: "Rp miliar",
        source: "ilustrasi konsep",
        note: "Saldo kas proyeksi menyentuh batas minimum di minggu 3, sinyal perlu menarik fasilitas atau menunda pengeluaran.",
        data: [
          { label: "Minggu 1", value: 8, color: "#10b981" },
          { label: "Minggu 2", value: 5, color: "#f59e0b" },
          { label: "Minggu 3", value: 2, color: "#ef4444" },
          { label: "Minggu 4", value: 6, color: "#10b981" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Current Ratio vs Quick Ratio (ilustrasi)",
        unit: "x (kali)",
        source: "ilustrasi konsep",
        note: "Quick ratio mengeluarkan persediaan, sehingga lebih konservatif. Selisih besar menandakan likuiditas bergantung pada persediaan.",
        data: [
          { label: "Current ratio", value: 2.0, color: "#10b981" },
          { label: "Quick ratio", value: 1.1, color: "#3b82f6" },
          { label: "Batas aman umum (1.0)", value: 1.0, color: "#64748b" },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "Rp2 M", label: "Buffer minimum", sub: "batas kas aman", color: "#ef4444" },
          { value: "13 minggu", label: "Horizon proyeksi", sub: "rolling cash forecast", color: "#3b82f6" },
          { value: "5 rekening", label: "Digabung cash pooling", sub: "jadi 1 posisi terpusat", color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Grup dengan kas tercerai-berai",
        html: "Sebuah grup memiliki lima anak usaha. Tiga surplus kas total Rp12 miliar di deposito berbunga rendah, sementara dua lainnya menarik pinjaman bank Rp8 miliar berbunga 12%. Tanpa cash pooling, grup membayar bunga pinjaman Rp960 juta per tahun sambil menyimpan kas idle. Dengan <strong>cash pooling</strong>, surplus menutup defisit sehingga pinjaman turun ke nol, menghemat sekitar Rp960 juta bunga setahun. Treasury juga menjalankan <strong>proyeksi arus kas 13 minggu</strong> dan menjaga hubungan dengan dua bank agar fasilitas siaga tersedia saat dibutuhkan.",
      },
      {
        type: "calcExercise",
        prompt: "Cash pooling menghapus pinjaman Rp8 miliar berbunga 12% per tahun. Berapa penghematan bunga setahun (juta)?",
        answer: 960,
        tolerance: 0,
        suffix: "juta",
        solution: "Penghematan = 8.000 x 12% = Rp960 juta per tahun.",
        hint: "Pokok pinjaman x bunga tahunan.",
      },
      {
        type: "calcExercise",
        prompt: "Aset lancar Rp900 juta, termasuk persediaan Rp300 juta. Utang lancar Rp500 juta. Berapa quick ratio-nya?",
        answer: 1.2,
        tolerance: 0.05,
        suffix: "x",
        solution: "Quick ratio = (Aset lancar - persediaan) / utang lancar = (900 - 300) / 500 = 600 / 500 = <strong>1,2x</strong>.",
        hint: "Quick ratio = (aset lancar - persediaan) / utang lancar.",
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini memperkuat atau melemahkan posisi likuiditas?",
        buckets: ["Memperkuat likuiditas", "Melemahkan likuiditas"],
        items: [
          { text: "Menjalankan proyeksi arus kas rolling 13 minggu", bucket: "Memperkuat likuiditas" },
          { text: "Menyimpan seluruh kas di satu unit tanpa pooling", bucket: "Melemahkan likuiditas" },
          { text: "Menjaga fasilitas kredit siaga dengan bank", bucket: "Memperkuat likuiditas" },
          { text: "Menghabiskan buffer untuk aset tetap jangka panjang", bucket: "Melemahkan likuiditas" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pilar likuiditas dengan tujuannya.",
        pairs: [
          { left: "Cash pooling", right: "Memusatkan saldo agar surplus menutup defisit" },
          { left: "Buffer likuiditas", right: "Cadangan kas untuk menghadapi kejutan" },
          { left: "Proyeksi arus kas", right: "Memperkirakan kapan kas akan menipis" },
          { left: "Hubungan bank", right: "Menjamin akses fasilitas siaga saat dibutuhkan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Likuiditas Bear Stearns 2008",
        html: "Pada <strong>Maret 2008</strong>, bank investasi <strong>Bear Stearns</strong> kehabisan likuiditas hanya dalam hitungan hari ketika para pemberi pinjaman jangka pendek serentak menarik dana, meski di atas kertas asetnya masih melebihi kewajibannya. Tanpa kas untuk beroperasi, bank ini terpaksa diakuisisi JPMorgan dengan harga awal hanya <strong>USD 2 per saham</strong> (kemudian dinaikkan menjadi USD 10), dibantu jaminan Federal Reserve. Solvabilitas tidak menyelamatkan perusahaan bila likuiditasnya menguap.",
      },
      {
        type: "takeaways",
        items: [
          "Likuiditas: kas yang cukup, di tempat dan waktu yang tepat.",
          "Cash pooling memusatkan saldo, mengurangi pinjaman dan bunga.",
          "Buffer harus seimbang: tidak terlalu kecil, tidak terlalu besar.",
          "Proyeksi arus kas mendeteksi kekurangan kas lebih dini.",
          "Hubungan bank yang kuat memberi akses fasilitas saat krisis.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan cash pooling adalah?",
            options: ["Memaksimalkan laba akuntansi", "Memusatkan saldo agar surplus menutup defisit", "Menambah jumlah rekening", "Menghindari pajak"],
            answer: 1,
            explain: "Cash pooling menggabungkan saldo sehingga unit surplus mendanai unit defisit, mengurangi pinjaman.",
          },
          {
            q: "Buffer likuiditas yang terlalu besar berarti?",
            options: ["Risiko gagal bayar tinggi", "Banyak kas menganggur yang tidak produktif", "Bunga pinjaman naik", "Proyeksi kas akurat"],
            answer: 1,
            explain: "Buffer berlebih berarti uang idle yang sebenarnya bisa diinvestasikan untuk imbal hasil.",
          },
          {
            q: "Proyeksi arus kas berguna untuk?",
            options: ["Menghitung laba bersih", "Memperkirakan kapan kas akan menipis", "Menentukan tarif pajak", "Menilai saham"],
            answer: 1,
            explain: "Proyeksi arus kas menunjukkan kapan saldo mendekati batas minimum sehingga bisa diantisipasi.",
          },
          {
            q: "Mengapa hubungan bank penting bagi treasury?",
            options: ["Agar dapat hadiah", "Agar fasilitas kredit siaga tersedia saat dibutuhkan", "Agar pajak lebih kecil", "Agar laba naik"],
            answer: 1,
            explain: "Hubungan bank yang kuat menjamin akses cepat ke fasilitas pendanaan saat likuiditas ketat.",
          },
          {
            q: "Pooling menghapus pinjaman Rp5 M bunga 10%. Penghematan setahun?",
            options: ["Rp500 juta", "Rp50 juta", "Rp5 miliar", "Rp100 juta"],
            answer: 0,
            explain: "5.000 x 10% = Rp500 juta per tahun.",
          },
          {
            q: "Buffer likuiditas yang terlalu kecil menimbulkan risiko?",
            options: ["Kas menganggur", "Gagal bayar saat ada kejutan", "Bunga deposito naik", "Laba terlalu besar"],
            answer: 1,
            explain: "Buffer terlalu tipis membuat perusahaan rentan gagal bayar saat terjadi guncangan kas.",
          },
          {
            q: "Horizon umum rolling cash forecast jangka pendek adalah?",
            options: ["13 minggu", "10 tahun", "1 hari", "5 tahun"],
            answer: 0,
            explain: "Proyeksi arus kas operasional sering disusun dalam horizon rolling 13 minggu.",
          },
        ],
      },
    ],
  },
];
