import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "capital-budgeting",
    levelId: "keputusan",
    order: 1,
    title: "Capital Budgeting: NPV & IRR",
    summary: "Cara perusahaan memutuskan proyek mana yang layak dibiayai. Dengan kalkulator NPV/IRR.",
    durationMin: 13,
    tags: ["capital budgeting", "NPV", "IRR"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Capital budgeting</strong> adalah proses menilai dan memilih investasi jangka panjang. Alat utamanya: <strong>NPV (Net Present Value)</strong>, <strong>IRR (Internal Rate of Return)</strong>, dan <strong>payback</strong>. Intinya membandingkan arus kas masa depan (yang didiskon) dengan biaya investasi.",
      },
      {
        type: "video",
        comp: "NPVIRRVideo",
        title: "Memahami NPV dan IRR",
        caption: "Cara mendiskon arus kas masa depan ke nilai kini dan menafsirkan NPV serta IRR sebuah proyek.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aturan keputusan",
        html: "Terima proyek bila <strong>NPV positif</strong>, atau setara, bila <strong>IRR lebih besar dari WACC</strong> (biaya modal). NPV adalah ukuran paling andal karena langsung mengukur tambahan nilai dalam rupiah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur capex, arus kas, umur, dan WACC untuk melihat NPV, IRR, dan payback sebuah proyek.",
      },
      { type: "widget", widget: "KalkulatorCapitalBudgeting" },
      {
        type: "chart",
        variant: "bar",
        title: "NPV Berubah Mengikuti Biaya Modal (ilustrasi)",
        unit: "Rp miliar NPV",
        source: "ilustrasi konsep",
        note: "Makin tinggi WACC (diskonto), makin kecil NPV. Pada titik tertentu (IRR), NPV menjadi nol.",
        data: [
          { label: "WACC 8%", value: 35, color: "#10b981" },
          { label: "WACC 12%", value: 18, color: "#10b981" },
          { label: "WACC 16%", value: 4, color: "#f59e0b" },
          { label: "WACC 20%", value: -8, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Membandingkan NPV Dua Proyek (ilustrasi)",
        unit: "Rp miliar NPV",
        source: "ilustrasi konsep",
        note: "Pada WACC yang sama, Proyek A menambah nilai lebih besar daripada Proyek B meski capex serupa.",
        data: [
          { label: "Proyek A", value: 20, color: "#10b981" },
          { label: "Proyek B", value: 12, color: "#3b82f6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua proyek, anggaran terbatas",
        html: "Perusahaan punya dua proyek tetapi dana hanya cukup untuk satu. Proyek A: NPV Rp20 miliar. Proyek B: NPV Rp12 miliar tetapi IRR-nya lebih tinggi. Karena tujuannya memaksimalkan nilai, dan NPV mengukur tambahan nilai absolut, perusahaan memilih <strong>Proyek A</strong>. IRR berguna, tetapi saat berkonflik dengan NPV pada proyek yang saling meniadakan, NPV yang dimenangkan.",
      },
      {
        type: "calcExercise",
        prompt: "Proyek butuh capex Rp100 miliar dan menghasilkan arus kas Rp30 miliar/tahun selama 5 tahun. Berapa total arus kas nominal (belum didiskon)?",
        answer: 150,
        tolerance: 0,
        prefix: "Rp",
        suffix: "miliar",
        solution: "Total nominal = Rp30 miliar x 5 = <strong>Rp150 miliar</strong>. NPV akan lebih kecil karena arus kas masa depan didiskon.",
        hint: "Kalikan arus kas tahunan dengan jumlah tahun.",
      },
      {
        type: "calcExercise",
        prompt: "Capex Rp100 miliar dengan arus kas Rp30 miliar per tahun. Berapa periode payback (tahun)?",
        answer: 3.33,
        tolerance: 0.05,
        suffix: "tahun",
        solution: "Payback = capex / arus kas tahunan = 100 / 30 = <strong>3,33 tahun</strong>. Payback mengabaikan nilai waktu uang, jadi hanya pelengkap NPV.",
        hint: "Bagi capex dengan arus kas tahunan.",
      },
      {
        type: "classifyExercise",
        prompt: "Berdasarkan hasil, proyek ini diterima atau ditolak?",
        buckets: ["Terima", "Tolak"],
        items: [
          { text: "NPV positif Rp10 miliar", bucket: "Terima" },
          { text: "NPV negatif Rp5 miliar", bucket: "Tolak" },
          { text: "IRR 18%, WACC 12%", bucket: "Terima" },
          { text: "IRR 9%, WACC 13%", bucket: "Tolak" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Proyek Satelit Iridium",
        html: "<strong>Iridium</strong>, proyek telepon satelit yang didukung Motorola, menanam investasi sekitar <strong>USD 5 miliar</strong> untuk meluncurkan 66 satelit. Namun proyeksi jumlah pelanggan jauh meleset dari kenyataan, sehingga arus kas masa depan yang diharapkan tidak pernah terwujud dan perusahaan bangkrut pada <strong>1999</strong>. Ini mengingatkan bahwa NPV positif hanya berarti bila proyeksi arus kasnya realistis, bukan terlalu optimistis.",
      },
      {
        type: "takeaways",
        items: [
          "Capital budgeting memilih investasi jangka panjang.",
          "Terima bila NPV positif atau IRR di atas WACC.",
          "NPV adalah ukuran paling andal (tambahan nilai dalam rupiah).",
          "Makin tinggi diskonto, makin kecil NPV.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Aturan dasar menerima proyek dengan NPV adalah?",
            options: ["NPV negatif", "NPV positif", "NPV nol", "Apa saja"],
            answer: 1,
            explain: "Proyek dengan NPV positif menambah nilai, jadi diterima.",
          },
          {
            q: "IRR sebuah proyek adalah tingkat diskonto yang membuat?",
            options: ["NPV maksimum", "NPV = 0", "Payback nol", "Laba tertinggi"],
            answer: 1,
            explain: "IRR adalah tingkat diskonto yang membuat NPV sama dengan nol.",
          },
          {
            q: "Proyek layak bila IRR?",
            options: ["Di bawah WACC", "Di atas WACC", "Nol", "Negatif"],
            answer: 1,
            explain: "IRR di atas biaya modal (WACC) menandakan proyek menambah nilai.",
          },
          {
            q: "Saat NPV dan IRR berkonflik pada proyek yang saling meniadakan, pilih berdasarkan?",
            options: ["IRR", "NPV", "Payback", "Undian"],
            answer: 1,
            explain: "NPV lebih andal karena mengukur tambahan nilai absolut.",
          },
          {
            q: "Diskonto naik, NPV cenderung?",
            options: ["Naik", "Turun", "Tetap", "Selalu positif"],
            answer: 1,
            explain: "Diskonto lebih tinggi menurunkan nilai kini arus kas, sehingga NPV turun.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "wacc-biaya-modal",
    levelId: "keputusan",
    order: 2,
    title: "WACC: Biaya Modal Perusahaan",
    summary: "Biaya rata-rata tertimbang utang dan ekuitas, yang menjadi hurdle rate setiap proyek. Dengan kalkulator WACC.",
    durationMin: 14,
    tags: ["WACC", "biaya modal", "CAPM", "hurdle rate"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>WACC (Weighted Average Cost of Capital)</strong> adalah biaya rata-rata tertimbang dari semua sumber dana perusahaan, yaitu <strong>utang</strong> dan <strong>ekuitas</strong>. Karena setiap rupiah yang dipakai perusahaan ada biayanya (bunga untuk kreditur, imbal hasil yang diharapkan untuk pemegang saham), WACC mencerminkan berapa minimal sebuah proyek harus menghasilkan agar tidak merusak nilai.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus inti",
        html: "WACC = (E/V x Re) + (D/V x Rd x (1 - pajak)). E = ekuitas, D = utang, V = E + D, Re = biaya ekuitas, Rd = biaya utang, pajak = tarif PPh badan. Perhatikan <strong>(1 - pajak)</strong> hanya menempel pada utang, itulah <strong>tax shield</strong>.",
      },
      {
        type: "heading",
        level: 3,
        text: "Biaya utang: lebih murah karena tax shield",
      },
      {
        type: "paragraph",
        html: "Biaya utang (Rd) adalah bunga efektif yang dibayar perusahaan. Karena bunga mengurangi laba kena pajak, beban bunga sebenarnya lebih ringan. Dengan PPh badan <strong>22%</strong>, bunga 10% secara efektif hanya menanggung 10% x (1 - 0,22) = <strong>7,8%</strong>. Inilah <strong>tax shield</strong>: pemerintah ikut menanggung sebagian biaya utang.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Biaya ekuitas (intuisi CAPM)",
        html: "Biaya ekuitas (Re) adalah imbal hasil yang diminta pemegang saham. CAPM memperkirakannya: Re = Rf + beta x (Rm - Rf). Rf = bunga bebas risiko (mis. obligasi negara), Rm - Rf = premi risiko pasar, beta = kepekaan saham terhadap pasar. Saham yang lebih bergejolak (beta tinggi) menuntut imbal hasil lebih besar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Ubah proporsi utang-ekuitas, biaya masing-masing, dan tarif pajak untuk melihat bagaimana WACC bergerak.",
      },
      { type: "widget", widget: "KalkulatorWACC" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Tiap Sumber Dana (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi konsep",
        note: "Biaya utang efektif lebih rendah dari biaya ekuitas karena bunga dapat mengurangi pajak.",
        data: [
          { label: "Biaya utang (sebelum pajak)", value: 10, color: "#f59e0b" },
          { label: "Biaya utang (setelah pajak)", value: 7.8, color: "#10b981" },
          { label: "Biaya ekuitas", value: 15, color: "#3b82f6" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Sumbangan Tiap Sumber ke WACC PT Sentosa (ilustrasi)",
        unit: "% poin ke WACC",
        source: "ilustrasi konsep",
        note: "Ekuitas (bobot 60% x 15%) menyumbang 9%, utang (bobot 40% x 7,8% setelah pajak) menyumbang 3,12%. Totalnya WACC 12,12%.",
        data: [
          { label: "Sumbangan ekuitas", value: 9, color: "#3b82f6" },
          { label: "Sumbangan utang (setelah pajak)", value: 3.12, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung WACC PT Sentosa",
        html: "PT Sentosa didanai ekuitas Rp600 miliar dan utang Rp400 miliar (total Rp1.000 miliar). Biaya ekuitas 15%, biaya utang 10%, PPh badan 22%. Bobot ekuitas 60%, bobot utang 40%. WACC = (0,60 x 15%) + (0,40 x 10% x (1 - 0,22)) = 9% + 3,12% = <strong>12,12%</strong>. Artinya setiap proyek baru harus menghasilkan imbal hasil di atas 12,12% agar layak.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "WACC adalah hurdle rate",
        html: "WACC dipakai sebagai tingkat diskonto di perhitungan NPV dan sebagai pembanding IRR. Proyek dengan imbal hasil di bawah WACC menghancurkan nilai meskipun labanya positif, karena belum menutup biaya modal.",
      },
      {
        type: "calcExercise",
        prompt: "Perusahaan: 50% ekuitas (biaya 16%), 50% utang (biaya 12%), PPh badan 22%. Berapa WACC?",
        answer: 12.68,
        tolerance: 0.1,
        suffix: "%",
        solution: "WACC = (0,5 x 16%) + (0,5 x 12% x (1 - 0,22)) = 8% + (0,5 x 9,36%) = 8% + 4,68% = <strong>12,68%</strong>.",
        hint: "Kalikan biaya utang dengan (1 - 0,22) sebelum ditimbang.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya utang sebelum pajak 14%. Dengan PPh badan 22%, berapa biaya utang setelah pajak?",
        answer: 10.92,
        tolerance: 0.05,
        suffix: "%",
        solution: "Biaya utang setelah pajak = 14% x (1 - 0,22) = 14% x 0,78 = <strong>10,92%</strong>.",
        hint: "Kalikan dengan 0,78.",
      },
      {
        type: "calcExercise",
        prompt: "Ekuitas Rp700 miliar dan utang Rp300 miliar. Berapa bobot utang (D/V)?",
        answer: 30,
        tolerance: 0,
        suffix: "%",
        solution: "V = 700 + 300 = 1.000. Bobot utang = D/V = 300 / 1.000 = 0,30 = <strong>30%</strong>.",
        hint: "Bagi utang dengan total dana (utang + ekuitas).",
      },
      {
        type: "classifyExercise",
        prompt: "Faktor ini menaikkan atau menurunkan WACC?",
        buckets: ["Menaikkan WACC", "Menurunkan WACC"],
        items: [
          { text: "Beta saham naik", bucket: "Menaikkan WACC" },
          { text: "Tarif pajak badan naik", bucket: "Menurunkan WACC" },
          { text: "Bunga pasar naik", bucket: "Menaikkan WACC" },
          { text: "Porsi utang murah diperbesar (wajar)", bucket: "Menurunkan WACC" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lonjakan Suku Bunga 2022",
        html: "Sepanjang <strong>2022</strong>, Federal Reserve menaikkan suku bunga acuan dari mendekati <strong>0%</strong> menjadi sekitar <strong>4,25%-4,5%</strong>, salah satu kenaikan tercepat dalam beberapa dekade. Bunga yang lebih tinggi menaikkan biaya utang sekaligus imbal hasil yang diminta investor, sehingga WACC banyak perusahaan ikut naik. Akibatnya tingkat diskonto membesar dan valuasi saham, terutama perusahaan teknologi, anjlok tajam.",
      },
      {
        type: "takeaways",
        items: [
          "WACC adalah biaya rata-rata tertimbang utang dan ekuitas.",
          "Biaya utang dihitung setelah pajak karena ada tax shield (PPh badan 22%).",
          "Biaya ekuitas diperkirakan via CAPM: Rf + beta x premi risiko pasar.",
          "WACC menjadi hurdle rate: proyek harus menghasilkan di atas WACC.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "WACC adalah biaya rata-rata tertimbang dari?",
            options: ["Hanya utang", "Hanya ekuitas", "Utang dan ekuitas", "Kas dan persediaan"],
            answer: 2,
            explain: "WACC menimbang biaya utang dan biaya ekuitas sesuai proporsinya.",
          },
          {
            q: "Mengapa biaya utang dikalikan (1 - pajak)?",
            options: ["Karena ada inflasi", "Karena bunga mengurangi pajak (tax shield)", "Karena utang berisiko", "Tanpa alasan"],
            answer: 1,
            explain: "Bunga mengurangi laba kena pajak, sehingga biaya efektif utang lebih rendah.",
          },
          {
            q: "Dengan PPh badan 22%, biaya utang efektif dari bunga 10% adalah?",
            options: ["10%", "7,8%", "12,2%", "2,2%"],
            answer: 1,
            explain: "10% x (1 - 0,22) = 7,8%.",
          },
          {
            q: "Dalam CAPM, beta mengukur?",
            options: ["Imbal hasil bebas risiko", "Kepekaan saham terhadap pasar", "Tarif pajak", "Rasio utang"],
            answer: 1,
            explain: "Beta mengukur seberapa peka return saham terhadap pergerakan pasar.",
          },
          {
            q: "WACC berfungsi sebagai?",
            options: ["Target laba bersih", "Hurdle rate / tingkat diskonto", "Harga saham", "Pajak dividen"],
            answer: 1,
            explain: "WACC menjadi tingkat minimal yang harus dilampaui imbal hasil proyek.",
          },
          {
            q: "Proyek dengan IRR 10% sementara WACC 12% sebaiknya?",
            options: ["Diterima", "Ditolak", "Ditunda tanpa alasan", "Selalu untung"],
            answer: 1,
            explain: "IRR di bawah WACC berarti proyek tidak menutup biaya modal, jadi ditolak.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "struktur-modal",
    levelId: "keputusan",
    order: 3,
    title: "Struktur Modal & Leverage",
    summary: "Komposisi utang dan ekuitas yang optimal, trade-off theory, dan efek leverage ke ROE. Dengan simulator.",
    durationMin: 14,
    tags: ["struktur modal", "leverage", "trade-off theory", "ROE"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Struktur modal</strong> adalah bauran antara <strong>utang</strong> dan <strong>ekuitas</strong> yang dipakai membiayai perusahaan. Pertanyaan klasiknya: berapa banyak utang yang ideal? Sedikit utang menambah nilai lewat tax shield, tetapi terlalu banyak utang menambah risiko kebangkrutan.",
      },
      {
        type: "video",
        comp: "StrukturModalVideo",
        title: "Trade-off Struktur Modal",
        caption: "Bagaimana tax shield dan biaya financial distress menentukan bauran utang-ekuitas yang optimal.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Trade-off theory",
        html: "Struktur modal optimal terletak di titik keseimbangan antara <strong>manfaat tax shield</strong> dari utang dan <strong>biaya financial distress</strong> (risiko gagal bayar, biaya kebangkrutan). Tambahan utang menguntungkan sampai biaya distress mulai melebihi manfaat pajaknya.",
      },
      {
        type: "heading",
        level: 3,
        text: "Leverage memperbesar ROE (dua arah)",
      },
      {
        type: "paragraph",
        html: "<strong>Leverage</strong> (penggunaan utang) memperbesar <strong>ROE (Return on Equity)</strong> saat bisnis untung, karena laba dibagi basis ekuitas yang lebih kecil. Namun saat bisnis rugi, leverage juga memperbesar kerugian per rupiah ekuitas. Utang menambah daya ungkit sekaligus menambah risiko.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser rasio utang-ekuitas untuk melihat efeknya pada WACC, ROE, dan tingkat risiko.",
      },
      { type: "widget", widget: "SimulatorStrukturModal" },
      {
        type: "chart",
        variant: "line",
        title: "WACC vs Rasio Utang (ilustrasi)",
        unit: "% WACC",
        source: "ilustrasi konsep",
        note: "WACC turun saat utang ditambah (tax shield), lalu naik kembali saat risiko distress mendominasi. Titik terendah adalah struktur modal optimal.",
        data: [
          { label: "Utang 0%", value: 15, color: "#3b82f6" },
          { label: "Utang 20%", value: 13, color: "#3b82f6" },
          { label: "Utang 40%", value: 11.5, color: "#10b981" },
          { label: "Utang 60%", value: 12.5, color: "#f59e0b" },
          { label: "Utang 80%", value: 15.5, color: "#ef4444" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "ROE Naik Mengikuti Leverage saat Bisnis Untung (ilustrasi)",
        unit: "% ROE",
        source: "ilustrasi konsep",
        note: "Aset Rp1.000 miliar, EBIT Rp150 miliar, bunga 10%, PPh 22%. Makin besar porsi utang, makin tinggi ROE saat untung, tetapi risiko ikut naik.",
        data: [
          { label: "Utang 0", value: 11.7, color: "#3b82f6" },
          { label: "Utang 250", value: 13.0, color: "#10b981" },
          { label: "Utang 500", value: 15.6, color: "#f59e0b" },
          { label: "Utang 750", value: 23.4, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Efek leverage ke ROE PT Maju",
        html: "PT Maju butuh aset Rp1.000 miliar dan menghasilkan laba operasi (EBIT) Rp150 miliar. <strong>Skenario A (tanpa utang):</strong> ekuitas Rp1.000 miliar, laba bersih (setelah PPh 22%) = Rp150 miliar x 0,78 = Rp117 miliar, ROE = 117/1.000 = <strong>11,7%</strong>. <strong>Skenario B (utang Rp500 miliar bunga 10%):</strong> bunga Rp50 miliar, laba sebelum pajak Rp100 miliar, laba bersih = Rp100 miliar x 0,78 = Rp78 miliar, ekuitas Rp500 miliar, ROE = 78/500 = <strong>15,6%</strong>. Leverage menaikkan ROE dari 11,7% ke 15,6%, tetapi risiko ikut naik.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Sisi gelap leverage",
        html: "Jika EBIT PT Maju turun jadi Rp40 miliar, skenario B harus tetap bayar bunga Rp50 miliar, sehingga rugi. Tanpa utang, perusahaan masih untung. Utang membuat laba lebih sensitif terhadap penurunan penjualan.",
      },
      {
        type: "calcExercise",
        prompt: "Laba bersih Rp78 miliar dengan ekuitas Rp500 miliar. Berapa ROE?",
        answer: 15.6,
        tolerance: 0.1,
        suffix: "%",
        solution: "ROE = laba bersih / ekuitas = 78 / 500 = 0,156 = <strong>15,6%</strong>.",
        hint: "Bagi laba bersih dengan ekuitas, lalu kali 100%.",
      },
      {
        type: "calcExercise",
        prompt: "Utang Rp400 miliar dengan bunga 11% per tahun. Berapa beban bunga setahun?",
        answer: 44,
        tolerance: 0,
        prefix: "Rp",
        suffix: "miliar",
        solution: "Beban bunga = Rp400 miliar x 11% = <strong>Rp44 miliar</strong>.",
        hint: "Kalikan pokok utang dengan tingkat bunga.",
      },
      {
        type: "calcExercise",
        prompt: "EBIT Rp150 miliar, beban bunga Rp50 miliar, PPh badan 22%. Berapa laba bersih?",
        answer: 78,
        tolerance: 0.1,
        prefix: "Rp",
        suffix: "miliar",
        solution: "Laba sebelum pajak = 150 - 50 = 100. Laba bersih = 100 x (1 - 0,22) = 100 x 0,78 = <strong>Rp78 miliar</strong>.",
        hint: "Kurangi EBIT dengan bunga, lalu kalikan 0,78.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Tax shield", right: "Penghematan pajak dari beban bunga" },
          { left: "Financial distress", right: "Risiko dan biaya akibat kesulitan bayar utang" },
          { left: "Leverage", right: "Penggunaan utang untuk memperbesar daya ungkit" },
          { left: "Struktur modal optimal", right: "Titik WACC terendah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Beban Utang Toys R Us",
        html: "Pada <strong>2005</strong>, peritel mainan <strong>Toys R Us</strong> diakuisisi lewat leveraged buyout senilai sekitar <strong>USD 6,6 miliar</strong> yang membebani perusahaan dengan utang sekitar USD 5 miliar. Bunga yang harus dibayar mencapai ratusan juta dolar setiap tahun, menyedot kas yang seharusnya dipakai berinovasi melawan pesaing daring. Terjepit beban tetap ini, perusahaan akhirnya mengajukan kebangkrutan pada <strong>2017</strong> dan menutup gerai-gerainya, contoh nyata bahaya struktur modal yang terlalu berat utang.",
      },
      {
        type: "takeaways",
        items: [
          "Struktur modal adalah bauran utang dan ekuitas.",
          "Trade-off theory: seimbangkan tax shield melawan biaya financial distress.",
          "Struktur optimal berada di titik WACC terendah.",
          "Leverage memperbesar ROE saat untung dan memperbesar rugi saat merugi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Struktur modal membahas bauran antara?",
            options: ["Kas dan piutang", "Utang dan ekuitas", "Aset dan liabilitas", "Pendapatan dan biaya"],
            answer: 1,
            explain: "Struktur modal adalah komposisi pendanaan dari utang dan ekuitas.",
          },
          {
            q: "Menurut trade-off theory, utang menguntungkan sampai?",
            options: ["Utang habis", "Biaya distress melebihi manfaat tax shield", "Bunga nol", "Selamanya"],
            answer: 1,
            explain: "Manfaat tax shield berhenti menambah nilai saat biaya financial distress mendominasi.",
          },
          {
            q: "Manfaat utama utang dalam struktur modal adalah?",
            options: ["Tax shield", "Mengurangi penjualan", "Menaikkan pajak", "Menghapus risiko"],
            answer: 0,
            explain: "Bunga utang mengurangi pajak sehingga menambah nilai (tax shield).",
          },
          {
            q: "Efek leverage saat perusahaan untung adalah?",
            options: ["ROE turun", "ROE naik", "ROE tetap", "Tidak ada efek"],
            answer: 1,
            explain: "Leverage memperbesar ROE karena laba dibagi basis ekuitas yang lebih kecil.",
          },
          {
            q: "Risiko utama dari leverage tinggi adalah?",
            options: ["Pajak nol", "Financial distress / gagal bayar", "Laba selalu naik", "WACC selalu turun"],
            answer: 1,
            explain: "Utang tinggi memperbesar risiko kesulitan keuangan dan kebangkrutan.",
          },
          {
            q: "Struktur modal optimal terjadi pada saat?",
            options: ["WACC tertinggi", "WACC terendah", "Utang 100%", "Ekuitas 100%"],
            answer: 1,
            explain: "Pada WACC terendah, nilai perusahaan maksimal.",
          },
          {
            q: "Bila EBIT turun tajam, perusahaan berutang besar lebih rentan karena?",
            options: ["Tidak ada dividen", "Beban bunga tetap harus dibayar", "Pajak naik", "Saham turun"],
            answer: 1,
            explain: "Bunga bersifat tetap, sehingga laba lebih sensitif terhadap penurunan EBIT.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kebijakan-dividen",
    levelId: "keputusan",
    order: 4,
    title: "Kebijakan Dividen & Buyback",
    summary: "Pilihan perusahaan atas laba: bagi dividen, tahan untuk reinvestasi, atau buyback saham, beserta sinyalnya ke pasar.",
    durationMin: 13,
    tags: ["dividen", "buyback", "payout ratio", "sinyal pasar"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah meraih laba, perusahaan punya tiga pilihan dasar: <strong>membagikan dividen</strong> ke pemegang saham, <strong>menahan laba</strong> untuk reinvestasi (laba ditahan), atau <strong>membeli kembali saham (buyback)</strong>. Keputusan ini disebut kebijakan dividen dan mencerminkan prioritas alokasi modal perusahaan.",
      },
      {
        type: "video",
        comp: "KebijakanDividenVideo",
        title: "Dividen, Laba Ditahan, dan Buyback",
        caption: "Tiga jalur alokasi laba dan apa sinyal yang ditangkap pasar dari masing-masing keputusan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Payout ratio",
        html: "<strong>Payout ratio</strong> = dividen / laba bersih. Rasio ini menunjukkan porsi laba yang dibagikan. Sisanya (1 - payout ratio) disebut <strong>retention ratio</strong>, yaitu porsi yang ditahan untuk pertumbuhan.",
      },
      {
        type: "heading",
        level: 3,
        text: "Tiga jalur alokasi laba",
      },
      {
        type: "list",
        ordered: false,
        items: [
          "<strong>Dividen tunai:</strong> cocok untuk perusahaan matang dengan arus kas stabil dan sedikit peluang ekspansi.",
          "<strong>Tahan laba (reinvestasi):</strong> cocok untuk perusahaan bertumbuh yang punya banyak proyek ber-NPV positif.",
          "<strong>Buyback saham:</strong> mengurangi jumlah saham beredar sehingga laba per saham (EPS) naik, fleksibel dan sering dipakai saat manajemen menilai saham undervalued.",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Sinyal ke pasar",
        html: "Kenaikan dividen sering dibaca pasar sebagai sinyal bahwa manajemen <strong>yakin laba masa depan kuat dan berkelanjutan</strong>. Sebaliknya, pemotongan dividen biasanya direspons negatif. Buyback juga bisa menjadi sinyal bahwa manajemen menilai harga saham terlalu murah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur payout ratio dan jumlah dana buyback untuk melihat dampaknya pada dividen per saham, laba ditahan, dan EPS.",
      },
      { type: "widget", widget: "SimulatorDividen" },
      {
        type: "chart",
        variant: "donut",
        title: "Alokasi Laba Bersih PT Lestari (ilustrasi)",
        unit: "Rp miliar",
        source: "ilustrasi konsep",
        note: "Dari laba Rp200 miliar: sebagian dibagi dividen, sebagian buyback, sisanya ditahan untuk ekspansi.",
        data: [
          { label: "Dividen tunai", value: 80, color: "#3b82f6" },
          { label: "Buyback saham", value: 40, color: "#10b981" },
          { label: "Laba ditahan", value: 80, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dividen vs buyback PT Lestari",
        html: "PT Lestari meraih laba bersih Rp200 miliar dengan 1.000 juta lembar saham beredar (EPS = Rp200). <strong>Opsi dividen:</strong> bagikan Rp80 miliar berarti dividen per saham Rp80 (payout ratio 40%). <strong>Opsi buyback:</strong> pakai Rp80 miliar untuk membeli saham di harga Rp2.000 berarti menarik 40 juta lembar, saham tinggal 960 juta, sehingga EPS naik menjadi 200 miliar / 960 juta = <strong>Rp208,3</strong>. Keduanya mengembalikan kas ke pemegang saham, tetapi caranya berbeda.",
      },
      {
        type: "table",
        caption: "Perbandingan ringkas tiga jalur alokasi laba",
        headers: ["Jalur", "Dampak utama", "Cocok untuk"],
        rows: [
          ["Dividen tunai", "Kas langsung ke investor", "Perusahaan matang"],
          ["Laba ditahan", "Mendanai pertumbuhan", "Perusahaan bertumbuh"],
          ["Buyback", "EPS naik, jumlah saham turun", "Saham dinilai murah"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dividen per Saham pada Berbagai Payout Ratio (ilustrasi)",
        unit: "Rp DPS",
        source: "ilustrasi konsep",
        note: "Laba Rp200 miliar dengan 1.000 juta lembar saham. Makin tinggi payout ratio, makin besar dividen per saham, tetapi makin sedikit laba yang ditahan untuk pertumbuhan.",
        data: [
          { label: "Payout 20%", value: 40, color: "#3b82f6" },
          { label: "Payout 40%", value: 80, color: "#10b981" },
          { label: "Payout 60%", value: 120, color: "#f59e0b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Laba bersih Rp200 miliar, dibagikan dividen Rp80 miliar. Berapa payout ratio?",
        answer: 40,
        tolerance: 0,
        suffix: "%",
        solution: "Payout ratio = dividen / laba bersih = 80 / 200 = 0,40 = <strong>40%</strong>.",
        hint: "Bagi dividen dengan laba bersih.",
      },
      {
        type: "calcExercise",
        prompt: "Laba bersih Rp200 miliar dengan 960 juta lembar saham setelah buyback. Berapa EPS (Rp)?",
        answer: 208.33,
        tolerance: 0.5,
        prefix: "Rp",
        solution: "EPS = laba bersih / jumlah saham = 200.000 juta / 960 juta = <strong>Rp208,3</strong> per lembar.",
        hint: "Bagi laba bersih (dalam juta rupiah) dengan jumlah saham (juta lembar).",
      },
      {
        type: "calcExercise",
        prompt: "ROE 20% dengan payout ratio 40%. Berapa tingkat pertumbuhan berkelanjutan (g)?",
        answer: 12,
        tolerance: 0.1,
        suffix: "%",
        solution: "Retention ratio = 1 - 0,40 = 0,60. g = ROE x retention = 20% x 0,60 = <strong>12%</strong>. Makin besar laba yang ditahan, makin tinggi potensi pertumbuhan.",
        hint: "Pertumbuhan g = ROE x (1 - payout ratio).",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi ini lebih condong ke jalur alokasi laba yang mana?",
        buckets: ["Bagi dividen", "Tahan laba"],
        items: [
          { text: "Perusahaan matang, arus kas stabil, sedikit proyek baru", bucket: "Bagi dividen" },
          { text: "Startup bertumbuh dengan banyak proyek NPV positif", bucket: "Tahan laba" },
          { text: "Investor butuh pendapatan rutin", bucket: "Bagi dividen" },
          { text: "Butuh dana ekspansi pabrik baru", bucket: "Tahan laba" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Dividen dan Buyback Apple",
        html: "Setelah bertahun-tahun tanpa dividen, <strong>Apple</strong> kembali membagikan dividen pada <strong>2012</strong> seiring kasnya yang menggunung. Sebagai perusahaan yang sangat mapan dengan kas berlimpah, Apple juga menjalankan program <strong>buyback</strong> raksasa, membeli kembali sahamnya senilai lebih dari <strong>USD 500 miliar</strong> sejak 2012. Kombinasi dividen dan buyback ini menunjukkan bagaimana perusahaan matang mengembalikan kas berlebih kepada pemegang saham.",
      },
      {
        type: "takeaways",
        items: [
          "Laba bisa dibagi dividen, ditahan, atau dipakai buyback.",
          "Payout ratio = dividen / laba bersih.",
          "Buyback menurunkan jumlah saham sehingga EPS naik.",
          "Perubahan dividen dan buyback menjadi sinyal keyakinan manajemen ke pasar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Payout ratio dihitung dengan?",
            options: ["Laba / aset", "Dividen / laba bersih", "Utang / ekuitas", "Dividen / harga saham"],
            answer: 1,
            explain: "Payout ratio = dividen dibagi laba bersih.",
          },
          {
            q: "Buyback saham umumnya membuat EPS?",
            options: ["Turun", "Naik", "Tetap", "Nol"],
            answer: 1,
            explain: "Jumlah saham berkurang sehingga laba per saham (EPS) naik.",
          },
          {
            q: "Menahan laba paling cocok untuk perusahaan yang?",
            options: ["Tidak punya peluang investasi", "Punya banyak proyek NPV positif", "Ingin membayar utang saja", "Sudah bangkrut"],
            answer: 1,
            explain: "Laba ditahan mendanai proyek bertumbuh yang menambah nilai.",
          },
          {
            q: "Kenaikan dividen sering dibaca pasar sebagai sinyal?",
            options: ["Laba masa depan diperkirakan kuat", "Perusahaan akan bangkrut", "Pajak naik", "Saham mahal"],
            answer: 0,
            explain: "Dividen yang dinaikkan menandakan keyakinan manajemen atas laba berkelanjutan.",
          },
          {
            q: "Retention ratio adalah?",
            options: ["Porsi laba dibagikan", "Porsi laba ditahan", "Rasio utang", "Harga saham"],
            answer: 1,
            explain: "Retention ratio = 1 - payout ratio, yaitu porsi laba yang ditahan.",
          },
          {
            q: "Dividen tunai paling cocok untuk perusahaan?",
            options: ["Startup cepat tumbuh", "Matang dengan arus kas stabil", "Yang merugi", "Tanpa pemegang saham"],
            answer: 1,
            explain: "Perusahaan matang dengan kas stabil dan sedikit peluang ekspansi cocok membagi dividen.",
          },
          {
            q: "Manajemen melakukan buyback saat menilai sahamnya?",
            options: ["Terlalu mahal", "Undervalued / murah", "Tidak likuid", "Tidak ada hubungan"],
            answer: 1,
            explain: "Buyback sering menjadi sinyal bahwa manajemen menilai harga saham terlalu murah.",
          },
        ],
      },
    ],
  },
];
