// AUTO-GENERATED oleh scripts/gen-manifest.mts. JANGAN sunting manual.
// Peta id topik -> dynamic import meta.ts, sehingga tiap topik menjadi chunk terpisah
// dan isi pelajaran (blocks) hanya dimuat saat topik itu dibuka.
export const topicLoaders: Record<string, () => Promise<Record<string, unknown>>> = {
  "akuntansi": () => import("./akuntansi/meta"),
  "aljabar": () => import("./aljabar/meta"),
  "arus-listrik": () => import("./arus-listrik/meta"),
  "carbon": () => import("./carbon/meta"),
  "climate-finance": () => import("./climate-finance/meta"),
  "corporate-finance": () => import("./corporate-finance/meta"),
  "cryptocurrency": () => import("./cryptocurrency/meta"),
  "demokrasi": () => import("./demokrasi/meta"),
  "dinamika": () => import("./dinamika/meta"),
  "ekonomi-syariah": () => import("./ekonomi-syariah/meta"),
  "filsafat": () => import("./filsafat/meta"),
  "fluida": () => import("./fluida/meta"),
  "fungsi-grafik": () => import("./fungsi-grafik/meta"),
  "geometri": () => import("./geometri/meta"),
  "getaran-gelombang": () => import("./getaran-gelombang/meta"),
  "gravitasi": () => import("./gravitasi/meta"),
  "investasi": () => import("./investasi/meta"),
  "kalkulus": () => import("./kalkulus/meta"),
  "kapitalisme": () => import("./kapitalisme/meta"),
  "kebijakan-fiskal": () => import("./kebijakan-fiskal/meta"),
  "kebijakan-moneter": () => import("./kebijakan-moneter/meta"),
  "kepabeanan": () => import("./kepabeanan/meta"),
  "kinematika": () => import("./kinematika/meta"),
  "listrik-statis": () => import("./listrik-statis/meta"),
  "logika": () => import("./logika/meta"),
  "logika-matematika": () => import("./logika-matematika/meta"),
  "magnetisme": () => import("./magnetisme/meta"),
  "makroekonomi": () => import("./makroekonomi/meta"),
  "marxisme": () => import("./marxisme/meta"),
  "matematika-dasar": () => import("./matematika-dasar/meta"),
  "mikroekonomi": () => import("./mikroekonomi/meta"),
  "momentum": () => import("./momentum/meta"),
  "optika": () => import("./optika/meta"),
  "pajak": () => import("./pajak/meta"),
  "pasar-keuangan": () => import("./pasar-keuangan/meta"),
  "pengantar-fisika": () => import("./pengantar-fisika/meta"),
  "perencanaan-keuangan": () => import("./perencanaan-keuangan/meta"),
  "rotasi": () => import("./rotasi/meta"),
  "sejarah-pemikiran-ekonomi": () => import("./sejarah-pemikiran-ekonomi/meta"),
  "statistika": () => import("./statistika/meta"),
  "supply-chain": () => import("./supply-chain/meta"),
  "tax-planning": () => import("./tax-planning/meta"),
  "termodinamika": () => import("./termodinamika/meta"),
  "trigonometri": () => import("./trigonometri/meta"),
  "usaha-energi": () => import("./usaha-energi/meta"),
};
