import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "revolusi-marginal-neoklasik",
    levelId: "marginal",
    order: 1,
    title: "Revolusi Marginal & Neoklasik",
    summary: "Pergeseran besar teori nilai: dari kerja ke utilitas marginal, dan sintesis neoklasik Alfred Marshall.",
    durationMin: 14,
    tags: ["marginal", "neoklasik", "Marshall", "utilitas"],
    blocks: [
      {
        type: "paragraph",
        html: "Sekitar <strong>1871</strong>, tiga ekonom secara terpisah, <strong>Jevons</strong> (Inggris), <strong>Menger</strong> (Austria), dan <strong>Walras</strong> (Prancis-Swiss), mengubah cara memahami nilai. Nilai bukan dari kerja atau total kegunaan, melainkan dari <strong>utilitas marginal</strong>, yaitu kegunaan unit terakhir yang dikonsumsi.",
      },
      {
        type: "video",
        comp: "RevolusiMarginalVideo",
        title: "Video: Revolusi Marginal",
        caption: "Paradoks air dan berlian terpecahkan oleh utilitas marginal.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/William_Stanley_Jevons.jpg?width=400",
        alt: "Potret William Stanley Jevons",
        caption: "William Stanley Jevons (1835-1882), salah satu pelopor revolusi marginal.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Utilitas marginal & paradoks nilai",
        html: "Mengapa air yang vital murah, sedangkan berlian yang kurang perlu mahal? Karena air melimpah sehingga <strong>utilitas marginal</strong>nya rendah, sedangkan berlian langka sehingga utilitas marginalnya tinggi. Nilai ditentukan kelangkaan dan kegunaan unit terakhir.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Sintesis neoklasik Marshall",
        html: "<strong>Alfred Marshall</strong> (Principles of Economics, 1890) menyatukan sisi permintaan (utilitas) dan penawaran (biaya) lewat <strong>kurva penawaran dan permintaan</strong>. Ia mengumpamakan keduanya seperti dua bilah gunting yang bersama-sama menentukan harga.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana utilitas marginal menurun saat konsumsi bertambah, dasar dari kurva permintaan.",
      },
      { type: "widget", widget: "KalkulatorUtilitas" },
      {
        type: "chart",
        variant: "line",
        title: "Utilitas Marginal Menurun saat Konsumsi Bertambah (ilustrasi)",
        unit: "utilitas unit tambahan",
        source: "ilustrasi konsep utilitas marginal menurun",
        note: "Gelas air pertama sangat berharga saat haus; gelas kelima jauh kurang bernilai. Inilah utilitas marginal yang menurun.",
        data: [
          { label: "Gelas 1", value: 10 },
          { label: "Gelas 2", value: 7 },
          { label: "Gelas 3", value: 4 },
          { label: "Gelas 4", value: 2 },
          { label: "Gelas 5", value: 1 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Paradoks air dan berlian",
        html: "Air jauh lebih berguna bagi hidup daripada berlian, tetapi harganya jauh lebih murah. Ekonomi klasik kesulitan menjelaskan ini. Revolusi marginal menjawab: yang menentukan harga bukan total kegunaan, melainkan <strong>utilitas unit terakhir</strong>. Karena air melimpah, unit terakhirnya bernilai kecil; karena berlian langka, unit terakhirnya bernilai besar. Paradoks pun terpecahkan.",
      },
      {
        type: "calcExercise",
        prompt: "Utilitas gelas air ke-1 sampai ke-4 adalah 10, 7, 4, dan 2. Berapa total utilitas dari empat gelas?",
        answer: 23,
        tolerance: 0,
        solution: "Total = 10 + 7 + 4 + 2 = <strong>23</strong>. Perhatikan tiap tambahan gelas memberi utilitas makin kecil.",
        hint: "Jumlahkan utilitas keempat gelas.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh dengan sumbangannya.",
        pairs: [
          { left: "Jevons, Menger, Walras", right: "Revolusi marginal (sekitar 1871)" },
          { left: "Alfred Marshall", right: "Sintesis penawaran dan permintaan" },
          { left: "Carl Menger", right: "Pendiri mazhab Austria" },
          { left: "Leon Walras", right: "Teori keseimbangan umum" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Principles of Economics 1890",
        html: "<strong>Alfred Marshall</strong> menerbitkan <strong>Principles of Economics</strong> pada <strong>1890</strong>, buku teks yang mendominasi pengajaran ekonomi selama puluhan tahun. Ia memperkenalkan banyak alat yang masih dipakai sampai kini, termasuk kurva penawaran-permintaan, elastisitas, dan surplus konsumen. Ekonomi neoklasik yang ia bentuk menjadi arus utama ilmu ekonomi modern.",
      },
      {
        type: "takeaways",
        items: [
          "Revolusi marginal (sekitar 1871) menggeser nilai ke utilitas marginal.",
          "Utilitas marginal menurun saat konsumsi bertambah.",
          "Paradoks air-berlian terpecahkan oleh kelangkaan dan unit terakhir.",
          "Marshall menyatukan permintaan dan penawaran dalam sintesis neoklasik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Revolusi marginal mengubah teori nilai menjadi berbasis?",
            options: ["Jam kerja", "Utilitas marginal", "Berat barang", "Biaya bahan"],
            answer: 1,
            explain: "Nilai ditentukan kegunaan unit terakhir (utilitas marginal), bukan kerja.",
          },
          {
            q: "Mengapa berlian lebih mahal dari air?",
            options: [
              "Berlian lebih berguna",
              "Berlian langka sehingga utilitas marginalnya tinggi",
              "Air tidak berguna",
              "Air sulit ditemukan",
            ],
            answer: 1,
            explain: "Kelangkaan membuat utilitas marginal berlian tinggi, air rendah.",
          },
          {
            q: "Siapa yang menyatukan permintaan dan penawaran (sintesis neoklasik)?",
            options: ["Adam Smith", "Alfred Marshall", "Karl Marx", "Thomas Malthus"],
            answer: 1,
            explain: "Alfred Marshall lewat Principles of Economics (1890).",
          },
          {
            q: "Utilitas marginal umumnya bersifat?",
            options: ["Meningkat terus", "Menurun saat konsumsi bertambah", "Tetap", "Nol"],
            answer: 1,
            explain: "Tambahan unit memberi utilitas yang makin kecil (utilitas marginal menurun).",
          },
          {
            q: "Pendiri mazhab Austria dalam revolusi marginal adalah?",
            options: ["Carl Menger", "Leon Walras", "Alfred Marshall", "David Ricardo"],
            answer: 0,
            explain: "Carl Menger adalah pelopor mazhab Austria.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "tiga-pelopor-marginal",
    levelId: "marginal",
    order: 2,
    title: "Tiga Pelopor Revolusi Marginal",
    summary: "Jevons, Menger, dan Walras merumuskan utilitas marginal secara terpisah pada awal 1870-an, dan menemukan hukum utilitas marginal yang menurun.",
    durationMin: 14,
    tags: ["Jevons", "Menger", "Walras", "utilitas marginal"],
    blocks: [
      {
        type: "paragraph",
        html: "Salah satu keajaiban sejarah ekonomi adalah <strong>penemuan serentak</strong>. Dalam rentang beberapa tahun sekitar <strong>1871</strong>, tiga ekonom yang tidak saling kenal, <strong>William Stanley Jevons</strong> di Inggris, <strong>Carl Menger</strong> di Austria, dan <strong>Leon Walras</strong> di Swiss, sampai pada gagasan yang sama: nilai suatu barang ditentukan oleh <strong>utilitas marginal</strong>, yaitu kepuasan dari unit terakhir yang dikonsumsi.",
      },
      {
        type: "paragraph",
        html: "Ketiganya mengganti fokus teori nilai dari <strong>biaya produksi</strong> (kerja, tanah, modal) menjadi <strong>penilaian subjektif konsumen</strong>. Dari sini lahir hukum penting: makin banyak suatu barang dikonsumsi, makin kecil utilitas marginal setiap unit tambahannya.",
      },
      {
        type: "video",
        comp: "RevolusiMarginalVideo",
        title: "Video: Revolusi Marginal",
        caption: "Tiga pelopor menemukan utilitas marginal hampir bersamaan.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Carl_Menger.jpg?width=400",
        alt: "Potret Carl Menger",
        caption: "Carl Menger (1840-1921), pendiri mazhab Austria.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Hukum utilitas marginal menurun",
        html: "Semakin banyak unit suatu barang yang kita miliki, semakin kecil tambahan kepuasan dari unit berikutnya. Suapan nasi pertama saat lapar terasa nikmat; suapan kesepuluh jauh berkurang nilainya. Inilah <strong>hukum utilitas marginal yang menurun</strong>, tulang punggung kurva permintaan yang melandai turun.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga jalur, satu tujuan",
        html: "<strong>Jevons</strong> memakai pendekatan matematis (kalkulus kepuasan), <strong>Menger</strong> memakai penalaran verbal dan penekanan pada kelangkaan serta hierarki kebutuhan, sedangkan <strong>Walras</strong> membangun sistem persamaan keseimbangan. Metodenya berbeda, tetapi intinya sama: utilitas marginal menentukan nilai.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Gunakan kalkulator utilitas untuk melihat bagaimana utilitas total bertambah tetapi utilitas marginal menyusut tiap unit.",
      },
      { type: "widget", widget: "KalkulatorUtilitas" },
      {
        type: "chart",
        variant: "bar",
        title: "Utilitas Marginal Tiap Suapan Menurun (ilustrasi)",
        unit: "utilitas unit tambahan",
        source: "ilustrasi hukum utilitas marginal menurun",
        note: "Tambahan kepuasan tiap suapan menyusut; ketika mendekati kenyang, suapan berikutnya nyaris tak bernilai.",
        data: [
          { label: "Suapan 1", value: 12 },
          { label: "Suapan 2", value: 9 },
          { label: "Suapan 3", value: 6 },
          { label: "Suapan 4", value: 3 },
          { label: "Suapan 5", value: 1 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menawar di pasar",
        html: "Bayangkan Anda sudah punya lima kaus. Kaus keenam hanya menambah sedikit kepuasan, jadi Anda hanya mau membayar murah untuknya. Penjual pun tahu, konsumen menilai unit tambahan lebih rendah. Karena itu diskon untuk pembelian banyak masuk akal: <strong>utilitas marginal</strong> pembeli menurun, sehingga harga yang bersedia dibayar untuk unit tambahan ikut turun.",
      },
      {
        type: "calcExercise",
        prompt: "Utilitas suapan ke-1 sampai ke-5 adalah 12, 9, 6, 3, dan 1. Berapa total utilitas dari lima suapan?",
        answer: 31,
        tolerance: 0,
        solution: "Total = 12 + 9 + 6 + 3 + 1 = <strong>31</strong>. Meski total naik, tambahan tiap suapan makin kecil.",
        hint: "Jumlahkan kelima nilai utilitas.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan berikut ke pendekatan yang tepat.",
        buckets: ["Teori nilai klasik", "Teori utilitas marginal"],
        items: [
          { text: "Nilai berasal dari jam kerja yang dipakai", bucket: "Teori nilai klasik" },
          { text: "Nilai ditentukan kegunaan unit terakhir", bucket: "Teori utilitas marginal" },
          { text: "Biaya produksi menentukan harga", bucket: "Teori nilai klasik" },
          { text: "Kelangkaan menaikkan utilitas marginal", bucket: "Teori utilitas marginal" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Penemuan serentak 1871-1874",
        html: "<strong>William Stanley Jevons</strong> menerbitkan <strong>The Theory of Political Economy</strong> pada <strong>1871</strong>, tahun yang sama dengan terbitnya <strong>Grundsatze der Volkswirtschaftslehre</strong> karya <strong>Carl Menger</strong>. Tiga tahun kemudian, pada <strong>1874</strong>, <strong>Leon Walras</strong> menerbitkan <strong>Elements of Pure Economics</strong>. Ketiga karya independen ini menandai lahirnya revolusi marginal dan fondasi ekonomi neoklasik.",
      },
      {
        type: "takeaways",
        items: [
          "Jevons, Menger, dan Walras menemukan utilitas marginal secara terpisah sekitar 1871.",
          "Nilai bergeser dari biaya produksi ke penilaian subjektif konsumen.",
          "Hukum utilitas marginal menurun menjelaskan kurva permintaan yang melandai.",
          "Metode ketiganya berbeda (matematis, verbal, sistem persamaan) tetapi intinya sama.",
          "Walras melengkapi revolusi ini dengan Elements of Pure Economics (1874).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ketiga pelopor revolusi marginal menemukan gagasannya secara?",
            options: ["Bersama dalam satu tim", "Terpisah dan hampir bersamaan", "Diwariskan dari Adam Smith", "Meniru Karl Marx"],
            answer: 1,
            explain: "Jevons, Menger, dan Walras sampai pada utilitas marginal secara independen sekitar 1871.",
          },
          {
            q: "Utilitas marginal barang cenderung bagaimana saat konsumsi bertambah?",
            options: ["Naik", "Menurun", "Tetap", "Menjadi tak terhingga"],
            answer: 1,
            explain: "Hukum utilitas marginal menurun: unit tambahan memberi kepuasan makin kecil.",
          },
          {
            q: "Siapa pendiri mazhab Austria di antara ketiga pelopor?",
            options: ["Jevons", "Menger", "Walras", "Marshall"],
            answer: 1,
            explain: "Carl Menger adalah pendiri mazhab Austria.",
          },
          {
            q: "Menurut teori marginal, nilai barang ditentukan oleh?",
            options: ["Jam kerja", "Berat barang", "Penilaian subjektif atas unit terakhir", "Jarak angkut"],
            answer: 2,
            explain: "Nilai berasal dari utilitas marginal, yaitu penilaian subjektif atas unit terakhir.",
          },
          {
            q: "Karya Leon Walras yang terbit 1874 berjudul?",
            options: ["The Wealth of Nations", "Elements of Pure Economics", "Das Kapital", "Principles of Economics"],
            answer: 1,
            explain: "Elements of Pure Economics (1874) memuat teori keseimbangan umum Walras.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "alfred-marshall-neoklasik",
    levelId: "marginal",
    order: 3,
    title: "Alfred Marshall & Sintesis Neoklasik",
    summary: "Marshall menyatukan permintaan dan penawaran seperti dua bilah gunting, memperkenalkan elastisitas, ceteris paribus, dan surplus konsumen.",
    durationMin: 15,
    tags: ["Marshall", "neoklasik", "elastisitas", "surplus konsumen"],
    blocks: [
      {
        type: "paragraph",
        html: "Revolusi marginal menonjolkan sisi permintaan, tetapi ekonom klasik menekankan biaya produksi di sisi penawaran. <strong>Alfred Marshall</strong> mendamaikan keduanya. Dalam <strong>Principles of Economics (1890)</strong>, ia menggambarkan harga pasar sebagai hasil pertemuan <strong>permintaan</strong> dan <strong>penawaran</strong>.",
      },
      {
        type: "paragraph",
        html: "Perumpamaan Marshall yang terkenal: bertanya apakah harga ditentukan permintaan atau penawaran sama seperti bertanya bilah gunting mana yang memotong kertas. <strong>Keduanya bekerja bersama</strong>. Ia juga memperkenalkan alat analisis yang masih dipakai hingga kini.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Sintesis neoklasik Marshall dalam alur sejarah ekonomi.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Alfred_Marshall.jpg?width=400",
        alt: "Potret Alfred Marshall",
        caption: "Alfred Marshall (1842-1924).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua bilah gunting",
        html: "Harga bukan ditentukan permintaan saja atau penawaran saja, melainkan oleh <strong>perpotongan keduanya</strong>. Seperti gunting, satu bilah tak bisa memotong sendiri. Titik potong kurva menentukan harga dan jumlah keseimbangan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Elastisitas & ceteris paribus",
        html: "Marshall memperkenalkan <strong>elastisitas permintaan</strong>, ukuran seberapa peka jumlah yang diminta terhadap perubahan harga. Ia juga membakukan metode <strong>ceteris paribus</strong> (menganggap faktor lain tetap) agar satu variabel bisa dianalisis terpisah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser kurva permintaan dan penawaran, lalu amati bagaimana titik keseimbangan (harga dan jumlah) bergeser.",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "line",
        title: "Elastisitas: Jumlah Diminta vs Harga (ilustrasi)",
        unit: "unit diminta",
        source: "ilustrasi konsep elastisitas permintaan",
        note: "Saat harga naik, jumlah yang diminta turun; kemiringan kurva mencerminkan elastisitas permintaan.",
        data: [
          { label: "Rp5.000", value: 100 },
          { label: "Rp10.000", value: 70 },
          { label: "Rp15.000", value: 45 },
          { label: "Rp20.000", value: 25 },
          { label: "Rp25.000", value: 10 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Surplus konsumen tiket konser",
        html: "Seseorang bersedia membayar Rp500.000 untuk tiket konser, tetapi harganya hanya Rp300.000. Selisih Rp200.000 adalah <strong>surplus konsumen</strong>, keuntungan yang dinikmati pembeli karena membayar kurang dari nilai yang ia rasakan. Marshall memakai konsep ini untuk mengukur kesejahteraan yang diperoleh konsumen dari transaksi pasar.",
      },
      {
        type: "calcExercise",
        prompt: "Seorang pembeli bersedia membayar Rp500.000 untuk tiket, tetapi harga pasar Rp300.000. Berapa surplus konsumennya (dalam rupiah)?",
        answer: 200000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Surplus konsumen = kesediaan membayar - harga = 500.000 - 300.000 = <strong>Rp200.000</strong>.",
        hint: "Kurangi harga pasar dari kesediaan membayar.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan konsep Marshall dengan artinya.",
        pairs: [
          { left: "Dua bilah gunting", right: "Harga dari permintaan dan penawaran bersama" },
          { left: "Elastisitas", right: "Kepekaan jumlah diminta terhadap harga" },
          { left: "Ceteris paribus", right: "Menganggap faktor lain tetap" },
          { left: "Surplus konsumen", right: "Selisih kesediaan bayar dan harga" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Principles of Economics 1890",
        html: "<strong>Alfred Marshall</strong> menerbitkan <strong>Principles of Economics</strong> pada <strong>1890</strong>. Buku ini menjadi teks standar pengajaran ekonomi selama beberapa dekade dan mempopulerkan diagram kurva penawaran-permintaan. Melalui karya ini, pendekatan neoklasik yang menggabungkan utilitas marginal dengan biaya produksi menjadi kerangka utama ilmu ekonomi.",
      },
      {
        type: "takeaways",
        items: [
          "Marshall menyatukan sisi permintaan dan penawaran dalam sintesis neoklasik.",
          "Perumpamaan dua bilah gunting: harga hasil kerja kedua kurva.",
          "Ia memperkenalkan elastisitas permintaan dan metode ceteris paribus.",
          "Surplus konsumen mengukur keuntungan pembeli di atas harga bayar.",
          "Principles of Economics (1890) menjadikan neoklasik arus utama.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Perumpamaan dua bilah gunting Marshall menjelaskan bahwa harga ditentukan oleh?",
            options: ["Permintaan saja", "Penawaran saja", "Permintaan dan penawaran bersama", "Pemerintah"],
            answer: 2,
            explain: "Seperti gunting, permintaan dan penawaran bekerja bersama menentukan harga.",
          },
          {
            q: "Elastisitas permintaan mengukur?",
            options: [
              "Berat barang",
              "Kepekaan jumlah diminta terhadap perubahan harga",
              "Biaya produksi",
              "Jumlah penjual",
            ],
            answer: 1,
            explain: "Elastisitas menunjukkan seberapa peka jumlah yang diminta terhadap harga.",
          },
          {
            q: "Metode ceteris paribus berarti?",
            options: ["Semua berubah", "Menganggap faktor lain tetap", "Tanpa data", "Harga selalu naik"],
            answer: 1,
            explain: "Ceteris paribus menganggap faktor lain tetap agar satu variabel bisa dianalisis.",
          },
          {
            q: "Surplus konsumen adalah?",
            options: [
              "Keuntungan penjual",
              "Selisih kesediaan membayar dan harga yang dibayar",
              "Pajak konsumen",
              "Biaya transaksi",
            ],
            answer: 1,
            explain: "Surplus konsumen adalah selisih antara nilai yang dirasakan pembeli dan harga pasar.",
          },
          {
            q: "Buku utama Alfred Marshall terbit tahun?",
            options: ["1776", "1867", "1890", "1936"],
            answer: 2,
            explain: "Principles of Economics terbit pada 1890.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "keseimbangan-umum-walras",
    levelId: "marginal",
    order: 4,
    title: "Keseimbangan Umum Walras",
    summary: "Walras membayangkan seluruh pasar saling terkait dan seimbang bersamaan, memakai matematika dan proses coba-coba yang disebut tatonnement.",
    durationMin: 15,
    tags: ["Walras", "keseimbangan umum", "tatonnement", "matematika"],
    blocks: [
      {
        type: "paragraph",
        html: "Marshall menganalisis satu pasar sekaligus (keseimbangan parsial). <strong>Leon Walras</strong> melangkah lebih jauh: ia bertanya bagaimana <strong>semua pasar sekaligus</strong> bisa seimbang. Harga roti memengaruhi permintaan mentega, upah tukang roti, harga gandum, dan seterusnya. Semua saling terkait.",
      },
      {
        type: "paragraph",
        html: "Dalam <strong>Elements of Pure Economics (1874)</strong>, Walras menyusun sistem persamaan yang menggambarkan seluruh perekonomian. Ia menunjukkan bahwa, secara prinsip, ada satu set harga yang membuat penawaran sama dengan permintaan di <strong>setiap pasar secara bersamaan</strong>. Inilah <strong>keseimbangan umum</strong>.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Walras dan kelahiran ekonomi matematis.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Semua pasar saling terkait",
        html: "Keseimbangan umum menegaskan bahwa perubahan di satu pasar merambat ke pasar lain. Tidak ada pasar yang benar-benar berdiri sendiri. Keseimbangan sejati tercapai ketika <strong>penawaran sama dengan permintaan di semua pasar sekaligus</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tatonnement: proses coba-coba",
        html: "Walras membayangkan seorang <strong>juru lelang</strong> yang mengumumkan harga, melihat kelebihan permintaan atau penawaran, lalu menyesuaikan harga naik-turun sampai semua pasar bersih. Proses coba-coba menuju keseimbangan ini disebut <strong>tatonnement</strong> (meraba-raba).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana harga menyesuaikan diri ketika terjadi kelebihan permintaan atau kelebihan penawaran, mirip mekanisme tatonnement.",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "line",
        title: "Tatonnement: Harga Menuju Keseimbangan (ilustrasi)",
        unit: "harga (Rp ribu)",
        source: "ilustrasi proses tatonnement Walras",
        note: "Harga disesuaikan naik-turun tiap putaran lelang hingga kelebihan permintaan hilang dan pasar bersih.",
        data: [
          { label: "Putaran 1", value: 8 },
          { label: "Putaran 2", value: 13 },
          { label: "Putaran 3", value: 11 },
          { label: "Putaran 4", value: 12 },
          { label: "Putaran 5", value: 12 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Efek berantai gagal panen",
        html: "Gagal panen gandum menaikkan harga gandum. Roti ikut mahal, permintaan mentega yang biasa dipadu roti turun, sementara petani jagung sebagai pengganti panen laris. Upah dan harga di banyak pasar bergeser bersamaan. Contoh ini menunjukkan mengapa Walras menolak menganalisis satu pasar terisolasi: <strong>semua pasar saling menyeimbangkan</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Pada suatu harga, jumlah diminta 120 unit dan jumlah ditawarkan 90 unit. Berapa besar kelebihan permintaan (unit)?",
        answer: 30,
        tolerance: 0,
        suffix: " unit",
        solution: "Kelebihan permintaan = jumlah diminta - jumlah ditawarkan = 120 - 90 = <strong>30 unit</strong>. Ini mendorong harga naik dalam tatonnement.",
        hint: "Kurangi jumlah ditawarkan dari jumlah diminta.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan ke jenis analisis keseimbangan.",
        buckets: ["Keseimbangan parsial", "Keseimbangan umum"],
        items: [
          { text: "Menganalisis satu pasar dengan asumsi lain tetap", bucket: "Keseimbangan parsial" },
          { text: "Semua pasar seimbang bersamaan", bucket: "Keseimbangan umum" },
          { text: "Fokus pendekatan Marshall", bucket: "Keseimbangan parsial" },
          { text: "Sistem persamaan seluruh perekonomian", bucket: "Keseimbangan umum" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Elements of Pure Economics 1874",
        html: "<strong>Leon Walras</strong> menerbitkan <strong>Elements of Pure Economics</strong> pada <strong>1874</strong>. Karya ini merumuskan teori keseimbangan umum dengan bahasa matematika dan menjadi fondasi ekonomi matematis modern. Gagasannya kelak dikembangkan lebih ketat pada abad ke-20 oleh Kenneth Arrow dan Gerard Debreu, yang membuktikan syarat keberadaan keseimbangan umum.",
      },
      {
        type: "takeaways",
        items: [
          "Walras memikirkan keseimbangan seluruh pasar sekaligus (keseimbangan umum).",
          "Semua pasar saling terkait; perubahan satu pasar merambat ke pasar lain.",
          "Tatonnement adalah proses coba-coba harga menuju keseimbangan.",
          "Elements of Pure Economics (1874) meletakkan dasar ekonomi matematis.",
          "Kelebihan permintaan mendorong harga naik, kelebihan penawaran menurunkannya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Keseimbangan umum Walras memandang bahwa?",
            options: [
              "Setiap pasar berdiri sendiri",
              "Semua pasar seimbang secara bersamaan dan saling terkait",
              "Hanya pasar tenaga kerja penting",
              "Harga ditetapkan pemerintah",
            ],
            answer: 1,
            explain: "Keseimbangan umum menuntut penawaran sama dengan permintaan di semua pasar sekaligus.",
          },
          {
            q: "Tatonnement adalah?",
            options: [
              "Nama pajak",
              "Proses coba-coba harga menuju keseimbangan",
              "Jenis barang mewah",
              "Undang-undang dagang",
            ],
            answer: 1,
            explain: "Tatonnement (meraba-raba) adalah penyesuaian harga bertahap hingga pasar bersih.",
          },
          {
            q: "Analisis Walras berbeda dari Marshall karena Walras menekankan?",
            options: ["Keseimbangan parsial", "Keseimbangan umum seluruh pasar", "Teori kerja", "Perdagangan luar negeri"],
            answer: 1,
            explain: "Marshall memakai keseimbangan parsial, Walras keseimbangan umum.",
          },
          {
            q: "Jika jumlah diminta melebihi jumlah ditawarkan, dalam tatonnement harga akan?",
            options: ["Turun", "Naik", "Tetap", "Menjadi nol"],
            answer: 1,
            explain: "Kelebihan permintaan mendorong juru lelang menaikkan harga.",
          },
          {
            q: "Elements of Pure Economics terbit tahun?",
            options: ["1848", "1874", "1890", "1936"],
            answer: 1,
            explain: "Walras menerbitkannya pada 1874.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mazhab-austria",
    levelId: "marginal",
    order: 5,
    title: "Mazhab Austria: Subjektivisme & Pasar",
    summary: "Dari Menger ke Mises dan Hayek: nilai bersifat subjektif, pengetahuan tersebar di masyarakat, dan perencanaan terpusat menghadapi masalah mendasar.",
    durationMin: 15,
    tags: ["mazhab Austria", "Hayek", "Mises", "subjektivisme"],
    blocks: [
      {
        type: "paragraph",
        html: "Dari Carl Menger tumbuh <strong>mazhab Austria</strong>, yang menekankan bahwa nilai bersifat <strong>subjektif</strong> dan bahwa perekonomian adalah proses yang terus berjalan, bukan keseimbangan statis. Tokoh besarnya antara lain <strong>Ludwig von Mises</strong> dan <strong>Friedrich Hayek</strong>.",
      },
      {
        type: "paragraph",
        html: "Wawasan khas mazhab Austria adalah soal <strong>pengetahuan yang tersebar</strong>. Tidak ada satu pihak pun yang tahu semua selera, biaya, dan kelangkaan. Harga pasar bekerja sebagai <strong>sinyal</strong> yang meringkas pengetahuan jutaan orang, sesuatu yang sulit ditiru perencana terpusat.",
      },
      {
        type: "video",
        comp: "DebatKeynesHayekVideo",
        title: "Video: Debat Keynes vs Hayek",
        caption: "Hayek membela peran pasar dan bahaya perencanaan terpusat.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Friedrich_Hayek_portrait.jpg?width=400",
        alt: "Potret Friedrich Hayek",
        caption: "Friedrich Hayek (1899-1992).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Harga sebagai penyampai pengetahuan",
        html: "Hayek berpendapat harga menyampaikan informasi yang tersebar di masyarakat. Ketika timah langka, harganya naik, dan tanpa perlu tahu penyebabnya, semua pengguna timah otomatis berhemat. <strong>Pasar mengoordinasi tanpa komando pusat</strong>, itulah yang disebut Hayek keajaiban sistem harga.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kritik perencanaan terpusat",
        html: "Mises dan Hayek menilai <strong>perencanaan terpusat</strong> menghadapi masalah mendasar: tanpa harga pasar, perencana tidak punya cara menghitung kelangkaan relatif sumber daya. Akibatnya alokasi menjadi buta dan boros. Ini inti <strong>debat kalkulasi sosialis</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Siklus bisnis Austria",
        html: "Teori <strong>siklus bisnis Austria</strong> berpendapat bahwa suku bunga yang ditekan terlalu rendah mendorong investasi berlebih yang keliru (malinvestasi). Ketika ketidakcocokan terungkap, terjadi koreksi berupa resesi. Bagi mazhab Austria, resesi adalah pembersihan malinvestasi, bukan sekadar kurangnya permintaan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser spektrum dari pasar bebas ke perencanaan terpusat dan lihat implikasinya menurut sudut pandang berbeda.",
      },
      { type: "widget", widget: "SimulatorSpektrumEkonomi" },
      {
        type: "chart",
        variant: "bar",
        title: "Sinyal Harga: Respons Konsumsi saat Timah Langka (ilustrasi)",
        unit: "indeks konsumsi (awal = 100)",
        source: "ilustrasi mekanisme sinyal harga Hayek",
        note: "Saat harga naik akibat kelangkaan, pengguna menghemat tanpa perlu tahu penyebab kelangkaan; pasar mengoordinasi lewat harga.",
        data: [
          { label: "Harga awal", value: 100 },
          { label: "Harga naik 20%", value: 82 },
          { label: "Harga naik 50%", value: 60 },
          { label: "Harga naik 100%", value: 40 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Sebatang pensil",
        html: "Tidak ada satu orang pun yang tahu cara membuat pensil dari nol: menambang grafit, menebang kayu, mengolah karet penghapus, mengangkut semuanya. Namun pensil tetap tersedia murah. Mengapa? Karena <strong>harga dan pasar</strong> mengoordinasi jutaan orang yang tak saling kenal. Inilah contoh nyata gagasan Hayek tentang pengetahuan tersebar dan koordinasi tanpa komando pusat.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh atau konsep mazhab Austria dengan penjelasannya.",
        pairs: [
          { left: "Carl Menger", right: "Pendiri mazhab Austria, nilai subjektif" },
          { left: "Friedrich Hayek", right: "Harga sebagai penyampai pengetahuan tersebar" },
          { left: "Ludwig von Mises", right: "Kritik kalkulasi ekonomi tanpa harga pasar" },
          { left: "Siklus bisnis Austria", right: "Suku bunga rendah memicu malinvestasi" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan sesuai pandangan yang tepat.",
        buckets: ["Mendukung pasar (Austria)", "Mendukung perencanaan terpusat"],
        items: [
          { text: "Harga meringkas pengetahuan yang tersebar", bucket: "Mendukung pasar (Austria)" },
          { text: "Satu badan pusat mengatur semua produksi", bucket: "Mendukung perencanaan terpusat" },
          { text: "Tanpa harga pasar, alokasi sumber daya jadi buta", bucket: "Mendukung pasar (Austria)" },
          { text: "Kelangkaan ditentukan target rencana negara", bucket: "Mendukung perencanaan terpusat" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Debat kalkulasi sosialis 1920",
        html: "Pada <strong>1920</strong>, <strong>Ludwig von Mises</strong> menerbitkan esai yang berpendapat bahwa perekonomian sosialis tanpa harga pasar mustahil melakukan <strong>kalkulasi ekonomi</strong> yang rasional. Ini memicu <strong>debat kalkulasi sosialis</strong> sepanjang 1920-an sampai 1930-an, dengan Hayek melanjutkan argumen soal pengetahuan tersebar melawan pendukung perencanaan seperti Oskar Lange.",
      },
      {
        type: "takeaways",
        items: [
          "Mazhab Austria menekankan nilai subjektif dan ekonomi sebagai proses.",
          "Hayek: harga adalah sinyal yang menyampaikan pengetahuan tersebar.",
          "Mises dan Hayek mengkritik perencanaan terpusat karena tak punya kalkulasi harga.",
          "Siklus bisnis Austria menyoroti malinvestasi akibat suku bunga terlalu rendah.",
          "Debat kalkulasi sosialis dimulai dari esai Mises pada 1920.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Hayek, fungsi utama harga adalah?",
            options: [
              "Menghukum konsumen",
              "Menyampaikan pengetahuan yang tersebar di masyarakat",
              "Menaikkan pajak",
              "Menstabilkan nilai tukar",
            ],
            answer: 1,
            explain: "Harga meringkas informasi tersebar sehingga pasar terkoordinasi tanpa komando pusat.",
          },
          {
            q: "Kritik Mises terhadap perencanaan terpusat adalah?",
            options: [
              "Terlalu banyak pasar",
              "Tanpa harga pasar, kalkulasi ekonomi rasional mustahil",
              "Terlalu sedikit pajak",
              "Upah terlalu tinggi",
            ],
            answer: 1,
            explain: "Tanpa harga, perencana tak bisa menghitung kelangkaan relatif sumber daya.",
          },
          {
            q: "Nilai menurut mazhab Austria bersifat?",
            options: ["Objektif dari jam kerja", "Subjektif menurut penilaian individu", "Ditetapkan negara", "Sama untuk semua orang"],
            answer: 1,
            explain: "Mazhab Austria menekankan subjektivisme nilai.",
          },
          {
            q: "Teori siklus bisnis Austria menyalahkan resesi terutama pada?",
            options: [
              "Kurangnya permintaan agregat",
              "Malinvestasi akibat suku bunga yang terlalu rendah",
              "Terlalu banyak tabungan",
              "Perdagangan bebas",
            ],
            answer: 1,
            explain: "Suku bunga terlalu rendah mendorong investasi keliru yang kemudian dikoreksi.",
          },
          {
            q: "Debat kalkulasi sosialis dipicu esai Mises pada tahun?",
            options: ["1890", "1920", "1936", "1971"],
            answer: 1,
            explain: "Mises menerbitkan argumennya pada 1920.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekonomi-kesejahteraan",
    levelId: "marginal",
    order: 6,
    title: "Ekonomi Kesejahteraan & Eksternalitas",
    summary: "Pareto merumuskan efisiensi, Pigou menyoroti eksternalitas dan mengusulkan pajak korektif; keduanya membangun cabang ekonomi kesejahteraan.",
    durationMin: 15,
    tags: ["Pareto", "Pigou", "eksternalitas", "kegagalan pasar"],
    blocks: [
      {
        type: "paragraph",
        html: "Neoklasik tidak hanya menjelaskan harga, tetapi juga menilai apakah hasil pasar <strong>baik</strong>. Cabang ini disebut <strong>ekonomi kesejahteraan</strong>. Dua tokoh pentingnya adalah <strong>Vilfredo Pareto</strong> dan <strong>Arthur Cecil Pigou</strong>.",
      },
      {
        type: "paragraph",
        html: "Pareto memberi tolok ukur efisiensi, sedangkan Pigou menunjukkan bahwa pasar bisa <strong>gagal</strong> ketika ada dampak yang tidak masuk harga, yang disebut <strong>eksternalitas</strong>. Dari sinilah lahir gagasan intervensi korektif seperti pajak.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Kelahiran ekonomi kesejahteraan dan analisis eksternalitas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Efisiensi Pareto",
        html: "Suatu keadaan disebut <strong>efisien Pareto</strong> bila tidak ada perubahan yang bisa membuat satu orang lebih baik tanpa membuat orang lain lebih buruk. Ini standar minimal efisiensi: jika masih ada perbaikan yang menguntungkan seseorang tanpa merugikan siapa pun, keadaan itu belum efisien.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Eksternalitas & kegagalan pasar",
        html: "<strong>Eksternalitas</strong> adalah dampak transaksi terhadap pihak ketiga yang tidak tercermin dalam harga. Contohnya polusi pabrik yang merugikan warga sekitar. Karena biayanya tidak ditanggung produsen, pasar menghasilkan terlalu banyak polusi. Inilah salah satu bentuk <strong>kegagalan pasar</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pajak Pigou",
        html: "<strong>Arthur Pigou</strong> mengusulkan <strong>pajak korektif</strong> sebesar biaya kerugian yang ditimbulkan pada pihak ketiga. Dengan pajak Pigou, produsen menanggung biaya sosial penuh, sehingga produksi turun ke tingkat yang efisien. Pajak karbon adalah contoh modern gagasan ini.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah tingkat produksi dan besar pajak, lalu lihat bagaimana biaya eksternalitas dan biaya sosial berubah.",
      },
      { type: "widget", widget: "KalkulatorEksternalitas" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Sosial vs Biaya Pribadi Akibat Eksternalitas (ilustrasi)",
        unit: "biaya per unit (Rp ribu)",
        source: "ilustrasi konsep eksternalitas negatif",
        note: "Biaya sosial melebihi biaya pribadi karena ada biaya eksternal; selisihnya menjadi dasar besaran pajak Pigou.",
        data: [
          { label: "Biaya pribadi", value: 40 },
          { label: "Biaya eksternal", value: 25 },
          { label: "Biaya sosial", value: 65 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik dan sungai",
        html: "Sebuah pabrik membuang limbah ke sungai. Bagi pabrik, biaya produksi hanya Rp40.000 per unit. Namun warga menanggung kerugian Rp25.000 per unit karena air tercemar. <strong>Biaya sosial</strong> sebenarnya Rp65.000 per unit. Karena pabrik tidak menanggung Rp25.000 itu, ia memproduksi terlalu banyak. Pajak Pigou sebesar Rp25.000 per unit menyelaraskan biaya pribadi dengan biaya sosial.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya produksi pribadi Rp40.000 per unit dan biaya eksternal yang ditanggung warga Rp25.000 per unit. Berapa biaya sosial per unit (dalam rupiah)?",
        answer: 65000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Biaya sosial = biaya pribadi + biaya eksternal = 40.000 + 25.000 = <strong>Rp65.000</strong>. Pajak Pigou ideal = Rp25.000 per unit.",
        hint: "Jumlahkan biaya pribadi dan biaya eksternal.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan contoh berikut ke jenis eksternalitasnya.",
        buckets: ["Eksternalitas negatif", "Eksternalitas positif"],
        items: [
          { text: "Polusi asap pabrik", bucket: "Eksternalitas negatif" },
          { text: "Vaksinasi yang melindungi tetangga", bucket: "Eksternalitas positif" },
          { text: "Kemacetan akibat mobil tambahan", bucket: "Eksternalitas negatif" },
          { text: "Taman kota yang dinikmati warga sekitar", bucket: "Eksternalitas positif" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: The Economics of Welfare 1920",
        html: "<strong>Arthur Cecil Pigou</strong> menerbitkan <strong>The Economics of Welfare</strong> pada <strong>1920</strong>. Buku ini membakukan analisis eksternalitas dan mengusulkan pajak korektif yang kini disebut pajak Pigou. Karyanya menjadi dasar teoretis kebijakan lingkungan modern, termasuk pajak karbon dan cukai atas rokok serta polusi.",
      },
      {
        type: "takeaways",
        items: [
          "Ekonomi kesejahteraan menilai apakah hasil pasar baik, bukan sekadar bagaimana harga terbentuk.",
          "Efisiensi Pareto: tak ada perbaikan yang menguntungkan seseorang tanpa merugikan orang lain.",
          "Eksternalitas adalah dampak pada pihak ketiga yang tidak masuk harga.",
          "Pajak Pigou menyelaraskan biaya pribadi dengan biaya sosial.",
          "Pigou membakukan analisis ini dalam The Economics of Welfare (1920).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Keadaan efisien Pareto berarti?",
            options: [
              "Semua orang kaya",
              "Tak ada perubahan yang menguntungkan seseorang tanpa merugikan orang lain",
              "Harga selalu nol",
              "Pemerintah mengatur semua",
            ],
            answer: 1,
            explain: "Efisiensi Pareto tercapai bila tidak ada lagi perbaikan tanpa merugikan pihak lain.",
          },
          {
            q: "Eksternalitas adalah?",
            options: [
              "Pajak impor",
              "Dampak transaksi pada pihak ketiga yang tidak masuk harga",
              "Biaya iklan",
              "Selisih kurs",
            ],
            answer: 1,
            explain: "Eksternalitas adalah dampak pada pihak ketiga yang tidak tercermin di harga pasar.",
          },
          {
            q: "Pajak Pigou bertujuan?",
            options: [
              "Menaikkan laba pabrik",
              "Menyelaraskan biaya pribadi dengan biaya sosial",
              "Menghapus semua pajak",
              "Menaikkan ekspor",
            ],
            answer: 1,
            explain: "Pajak Pigou membebankan biaya eksternal kepada produsen agar produksi efisien.",
          },
          {
            q: "Polusi pabrik yang merugikan warga adalah contoh?",
            options: ["Eksternalitas positif", "Eksternalitas negatif", "Surplus konsumen", "Efisiensi Pareto"],
            answer: 1,
            explain: "Polusi membebani pihak ketiga tanpa kompensasi, yaitu eksternalitas negatif.",
          },
          {
            q: "Buku The Economics of Welfare karya Pigou terbit tahun?",
            options: ["1890", "1920", "1936", "1958"],
            answer: 1,
            explain: "The Economics of Welfare terbit pada 1920.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "neoklasik-jadi-arus-utama",
    levelId: "marginal",
    order: 7,
    title: "Neoklasik Menjadi Arus Utama",
    summary: "Marginalisme mendominasi ekonomi abad ke-20 dengan model homo economicus, tetapi menuai kritik dari Keynes, kaum institusionalis, dan ekonomi perilaku.",
    durationMin: 15,
    tags: ["neoklasik", "homo economicus", "kritik", "ekonomi perilaku"],
    blocks: [
      {
        type: "paragraph",
        html: "Sepanjang abad ke-20, pendekatan <strong>neoklasik</strong> menjadi kerangka baku ilmu ekonomi. Buku teks, kurikulum, dan kebijakan banyak berpijak pada model optimasi marginal, kurva penawaran-permintaan, dan gagasan keseimbangan pasar.",
      },
      {
        type: "paragraph",
        html: "Inti model ini adalah <strong>homo economicus</strong>: manusia dianggap rasional, punya informasi memadai, dan konsisten memaksimalkan kepuasan atau keuntungan. Asumsi ini membuat ekonomi bisa dimodelkan secara matematis, tetapi justru menjadi sasaran kritik.",
      },
      {
        type: "video",
        comp: "RevolusiMarginalVideo",
        title: "Video: Revolusi Marginal",
        caption: "Warisan marginalisme yang mendominasi ekonomi modern.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Homo economicus",
        html: "Model neoklasik mengandaikan pelaku ekonomi yang <strong>rasional</strong> dan konsisten memaksimalkan utilitas atau laba di bawah kendala anggaran. Asumsi ini memudahkan pemodelan, tetapi menyederhanakan perilaku manusia yang sebenarnya jauh lebih rumit.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kritik Keynes dan institusionalis",
        html: "<strong>John Maynard Keynes</strong> menilai ekonomi bisa terjebak pengangguran tinggi dalam waktu lama, sehingga pasar tak selalu menyeimbangkan diri seperti anggapan neoklasik. Kaum <strong>institusionalis</strong> menegaskan pentingnya lembaga, kebiasaan, dan kekuasaan yang sering diabaikan model murni.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ekonomi perilaku",
        html: "Sejak akhir abad ke-20, <strong>ekonomi perilaku</strong> (Kahneman, Tversky, lalu Thaler) menunjukkan manusia sering bias dan tidak sepenuhnya rasional. Orang memakai jalan pintas berpikir, terpengaruh cara pilihan disajikan, dan tidak selalu konsisten. Ini memperbaiki, bukan menggantikan, kerangka neoklasik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana surplus konsumen dan produsen terbentuk pada model pasar neoklasik yang sudah kita pelajari.",
      },
      { type: "widget", widget: "SimulatorSurplus" },
      {
        type: "chart",
        variant: "line",
        title: "Perkiraan Pangsa Kerangka Neoklasik dalam Pengajaran Ekonomi (ilustrasi)",
        unit: "pangsa perkiraan (%)",
        source: "ilustrasi tren dominasi neoklasik, bukan data survei resmi",
        note: "Neoklasik naik menjadi arus utama pada pertengahan abad ke-20, lalu sedikit menurun seiring munculnya ekonomi perilaku dan pendekatan lain.",
        data: [
          { label: "1900", value: 40 },
          { label: "1930", value: 55 },
          { label: "1960", value: 80 },
          { label: "1990", value: 78 },
          { label: "2020", value: 70 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Homo economicus vs manusia nyata",
        html: "Model neoklasik meramalkan orang akan selalu memilih opsi dengan nilai harapan tertinggi. Namun eksperimen menunjukkan banyak orang menolak taruhan yang secara matematis menguntungkan karena takut rugi (loss aversion), atau membeli barang hanya karena diskon meski tak butuh. Perilaku nyata ini menjadi bahan bakar <strong>ekonomi perilaku</strong> yang melengkapi asumsi rasionalitas.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah taruhan memberi peluang 50% menang Rp200.000 dan 50% menang Rp0. Berapa nilai harapan taruhan ini (dalam rupiah)?",
        answer: 100000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai harapan = 0,5 x 200.000 + 0,5 x 0 = <strong>Rp100.000</strong>. Homo economicus akan ikut bila biayanya di bawah Rp100.000, tetapi manusia nyata sering menolak karena menghindari risiko.",
        hint: "Kalikan tiap hasil dengan peluangnya lalu jumlahkan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan aliran atau tokoh dengan kritik atau sumbangannya terhadap neoklasik.",
        pairs: [
          { left: "Homo economicus", right: "Asumsi pelaku rasional pemaksimal utilitas" },
          { left: "John Maynard Keynes", right: "Pasar bisa lama terjebak pengangguran" },
          { left: "Institusionalis", right: "Menekankan peran lembaga dan kebiasaan" },
          { left: "Ekonomi perilaku", right: "Manusia sering bias dan tak selalu rasional" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Dominasi neoklasik sepanjang abad ke-20",
        html: "Setelah revolusi marginal dan sintesis Marshall (1890), pendekatan neoklasik menyebar melalui buku teks dan universitas. Pada pertengahan abad ke-20, ia bergabung dengan gagasan Keynes menjadi <strong>sintesis neoklasik-Keynesian</strong> yang mendominasi kebijakan pascaperang. Menjelang akhir abad, kritik ekonomi perilaku dan institusional memperkaya, tetapi kerangka marginal tetap menjadi bahasa dasar ilmu ekonomi.",
      },
      {
        type: "takeaways",
        items: [
          "Neoklasik menjadi kerangka baku ilmu ekonomi sepanjang abad ke-20.",
          "Homo economicus mengandaikan pelaku rasional pemaksimal utilitas atau laba.",
          "Keynes dan institusionalis mengkritik asumsi pasar yang selalu seimbang.",
          "Ekonomi perilaku menunjukkan manusia sering bias dan tak sepenuhnya rasional.",
          "Kritik ini memperkaya, bukan menghapus, kerangka marginal neoklasik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Istilah homo economicus mengacu pada asumsi bahwa pelaku ekonomi?",
            options: [
              "Selalu altruistik",
              "Rasional dan memaksimalkan utilitas atau laba",
              "Tidak punya tujuan",
              "Ditentukan negara",
            ],
            answer: 1,
            explain: "Homo economicus adalah pelaku rasional yang konsisten memaksimalkan kepuasan atau keuntungan.",
          },
          {
            q: "Kritik utama Keynes terhadap pandangan neoklasik adalah?",
            options: [
              "Pasar selalu seimbang",
              "Ekonomi bisa lama terjebak pengangguran, pasar tak selalu menyeimbangkan diri",
              "Harga tidak penting",
              "Uang tidak berguna",
            ],
            answer: 1,
            explain: "Keynes menilai pasar bisa terjebak pengangguran tinggi tanpa koreksi otomatis.",
          },
          {
            q: "Ekonomi perilaku menekankan bahwa manusia?",
            options: [
              "Selalu rasional sempurna",
              "Sering bias dan tidak sepenuhnya rasional",
              "Tak pernah salah hitung",
              "Tidak dipengaruhi cara pilihan disajikan",
            ],
            answer: 1,
            explain: "Ekonomi perilaku menunjukkan bias dan keterbatasan rasionalitas manusia.",
          },
          {
            q: "Kaum institusionalis menekankan pentingnya?",
            options: [
              "Hanya rumus matematika",
              "Lembaga, kebiasaan, dan kekuasaan dalam ekonomi",
              "Menghapus pemerintah",
              "Kurva permintaan saja",
            ],
            answer: 1,
            explain: "Institusionalis menyoroti peran lembaga, kebiasaan, dan kekuasaan yang diabaikan model murni.",
          },
          {
            q: "Terhadap kerangka neoklasik, kritik perilaku dan institusional umumnya bersifat?",
            options: [
              "Menghapus total neoklasik",
              "Memperkaya dan memperbaiki, bukan menggantikan sepenuhnya",
              "Tidak relevan",
              "Kembali ke teori nilai kerja",
            ],
            answer: 1,
            explain: "Kritik ini memperkaya kerangka marginal, yang tetap menjadi bahasa dasar ekonomi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "schumpeter-inovasi",
    levelId: "marginal",
    order: 8,
    title: "Schumpeter: Inovasi & Penghancuran Kreatif",
    summary: "Kewirausahaan dan inovasi sebagai motor kapitalisme, serta penghancuran kreatif yang menggusur produk dan teknologi lama.",
    durationMin: 14,
    tags: ["Schumpeter", "inovasi", "kewirausahaan", "penghancuran kreatif"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Joseph Schumpeter</strong> (1883-1950) menolak gambaran ekonomi yang selalu tenang menuju keseimbangan. Baginya, inti kapitalisme adalah <strong>perubahan</strong>: pengusaha (entrepreneur) memperkenalkan produk baru, metode produksi baru, pasar baru, dan cara berorganisasi baru. Inovasi inilah, bukan sekadar penumpukan modal, yang menggerakkan pertumbuhan.",
      },
      {
        type: "paragraph",
        html: "Schumpeter menyebut proses ini <strong>penghancuran kreatif</strong> (creative destruction): setiap gelombang inovasi menciptakan industri baru sekaligus menghancurkan yang lama. Kereta kuda digusur mobil, telegram digusur telepon, kaset digusur CD lalu digusur streaming. Kerusakan bagi sebagian pihak adalah harga dari kemajuan bagi keseluruhan.",
      },
      {
        type: "video",
        comp: "CreativeDestructionVideo",
        title: "Video: Penghancuran Kreatif",
        caption: "Gelombang inovasi menggusur teknologi lama dan melahirkan yang baru.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Joseph_Schumpeter_ekonomialaria.jpg?width=400",
        alt: "Potret Joseph Schumpeter",
        caption: "Joseph Schumpeter (1883-1950).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pengusaha sebagai penggerak",
        html: "Bagi Schumpeter, <strong>pengusaha</strong> bukan sekadar pemilik modal, melainkan sosok yang berani menggabungkan sumber daya dengan cara baru. Laba adalah imbalan sementara bagi inovator, yang lambat laun terkikis saat pesaing meniru.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Siklus bisnis dari gelombang inovasi",
        html: "Schumpeter mengaitkan naik turun ekonomi dengan gerombolan inovasi (clusters of innovation). Ketika terobosan besar muncul, investasi melonjak; ketika peluangnya habis, ekonomi melambat sampai gelombang berikutnya datang.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Ongkos sosial perubahan",
        html: "Penghancuran kreatif bukan tanpa korban. Pekerja dan perusahaan yang tergusur menanggung biaya nyata. Karena itu Schumpeter justru khawatir kapitalisme bisa runtuh secara sosial-politik, bukan karena gagal, melainkan karena keberhasilannya melahirkan penolakan.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Umur rata-rata perusahaan besar makin pendek",
        unit: "tahun",
        source: "Ilustrasi edukatif berdasarkan tren umur perusahaan indeks pasar",
        note: "Penghancuran kreatif mempercepat pergantian perusahaan dominan dari waktu ke waktu.",
        data: [
          { label: "1960-an", value: 60, color: "#60a5fa" },
          { label: "1980-an", value: 35, color: "#818cf8" },
          { label: "2000-an", value: 22, color: "#f59e0b" },
          { label: "2020-an", value: 18, color: "#ef4444" },
        ],
      },
      {
        type: "widget",
        widget: "SimulatorSpektrumEkonomi",
      },
      {
        type: "case",
        title: "Kodak dan kamera digital",
        html: "Kodak pernah menguasai pasar film foto. Ironisnya, insinyur Kodak menciptakan kamera digital pertama pada <strong>1975</strong>, tetapi perusahaan enggan mengganggu bisnis film yang menguntungkan. Ketika fotografi digital meledak, Kodak terlambat dan akhirnya mengajukan kebangkrutan pada <strong>2012</strong>. Contoh telak penghancuran kreatif: teknologi baru menggusur pemimpin lama yang gagal beradaptasi.",
      },
      {
        type: "case",
        title: "Sejarah: Capitalism, Socialism and Democracy (1942)",
        html: "Dalam buku <strong>Capitalism, Socialism and Democracy</strong> (terbit <strong>1942</strong>), Schumpeter merumuskan istilah <strong>creative destruction</strong> sebagai fakta esensial kapitalisme. Menariknya, ia meramalkan kapitalisme akan digantikan sosialisme bukan karena kegagalan ekonomi, melainkan karena kaum intelektual dan birokrasi yang tumbuh dari kemakmurannya akan menggerus semangat kewirausahaan. Ramalan itu tidak terbukti persis, tetapi analisis inovasinya tetap berpengaruh besar.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah industri lama beromzet Rp 500 miliar. Inovasi baru menggusur 40% pasarnya dalam setahun. Berapa omzet yang tersisa bagi pemain lama?",
        answer: 300,
        tolerance: 1,
        prefix: "Rp",
        suffix: " miliar",
        solution: "Tersisa 60% dari Rp 500 miliar = 0,6 x 500 = Rp 300 miliar.",
        hint: "Jika 40% tergusur, 60% tersisa.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan contoh berikut: teknologi baru yang menggusur, atau teknologi lama yang tergusur.",
        buckets: ["Teknologi baru", "Teknologi lama tergusur"],
        items: [
          { text: "Layanan streaming musik", bucket: "Teknologi baru" },
          { text: "Kaset dan CD fisik", bucket: "Teknologi lama tergusur" },
          { text: "Kamera digital", bucket: "Teknologi baru" },
          { text: "Film foto seluloid", bucket: "Teknologi lama tergusur" },
          { text: "Mobil listrik", bucket: "Teknologi baru" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Schumpeter menempatkan inovasi dan pengusaha sebagai motor utama kapitalisme.",
          "Penghancuran kreatif: inovasi baru menciptakan industri sekaligus menggusur yang lama.",
          "Laba inovator bersifat sementara karena akan ditiru pesaing.",
          "Siklus bisnis terkait gelombang inovasi yang datang bergerombol.",
          "Perubahan membawa ongkos sosial nyata bagi pihak yang tergusur.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Istilah penghancuran kreatif merujuk pada?",
            options: [
              "Perang menghancurkan pabrik",
              "Inovasi baru menggusur produk dan teknologi lama",
              "Bank mencetak uang",
              "Pemerintah menutup usaha",
            ],
            answer: 1,
            explain: "Creative destruction adalah proses inovasi yang menciptakan industri baru sekaligus menghancurkan yang lama.",
          },
          {
            q: "Menurut Schumpeter, motor utama pertumbuhan kapitalisme adalah?",
            options: [
              "Penumpukan modal semata",
              "Inovasi dan kewirausahaan",
              "Subsidi negara",
              "Utang luar negeri",
            ],
            answer: 1,
            explain: "Schumpeter menekankan inovasi oleh pengusaha, bukan sekadar akumulasi modal.",
          },
          {
            q: "Mengapa laba inovator cenderung bersifat sementara?",
            options: [
              "Karena pajak naik",
              "Karena pesaing akan meniru inovasinya",
              "Karena inovasi dilarang",
              "Karena harga selalu turun",
            ],
            answer: 1,
            explain: "Setelah pesaing meniru, keunggulan dan laba ekstra inovator terkikis.",
          },
          {
            q: "Kasus Kodak menggambarkan?",
            options: [
              "Perusahaan lama gagal beradaptasi pada teknologi baru",
              "Keberhasilan monopoli abadi",
              "Peran bank sentral",
              "Teori nilai kerja",
            ],
            answer: 0,
            explain: "Kodak tergusur fotografi digital meski ikut menciptakannya, contoh penghancuran kreatif.",
          },
          {
            q: "Dalam buku 1942, Schumpeter memperkirakan kapitalisme akan?",
            options: [
              "Bertahan selamanya tanpa perubahan",
              "Digantikan sosialisme karena keberhasilannya sendiri",
              "Runtuh karena kekurangan modal",
              "Menghapus semua inovasi",
            ],
            answer: 1,
            explain: "Ia menduga kemakmuran kapitalisme akan menggerus semangat kewirausahaan dan membuka jalan sosialisme.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "irving-fisher-uang-dan-bunga",
    levelId: "marginal",
    order: 9,
    title: "Irving Fisher: Uang, Bunga & Deflasi Utang",
    summary: "Teori bunga, persamaan pertukaran MV = PT, dan gagasan deflasi utang yang menjelaskan dalamnya Depresi Besar.",
    durationMin: 15,
    tags: ["Fisher", "uang", "bunga", "deflasi utang", "MV=PT"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Irving Fisher</strong> (1867-1947) adalah salah satu ekonom Amerika paling berpengaruh dan pelopor ekonomi matematis. Ia merumuskan <strong>teori bunga</strong> sebagai harga waktu: bunga muncul karena orang lebih menghargai konsumsi sekarang dibanding nanti (ketaksabaran), dan karena modal bisa dipakai produktif.",
      },
      {
        type: "paragraph",
        html: "Karyanya yang paling terkenal adalah <strong>persamaan pertukaran</strong> <strong>MV = PT</strong>: jumlah uang (M) dikali kecepatan peredarannya (V) sama dengan tingkat harga (P) dikali volume transaksi (T). Persamaan ini menjadi fondasi teori kuantitas uang: bila M naik cepat sementara V dan T stabil, maka P (harga) ikut naik, itulah inflasi.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Bagaimana Uang Menggerakkan Harga",
        caption: "Hubungan jumlah uang, kecepatan edar, dan tingkat harga.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_Irving_Fisher.jpg?width=400",
        alt: "Potret Irving Fisher",
        caption: "Irving Fisher (1867-1947).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Persamaan pertukaran MV = PT",
        html: "<strong>M</strong> = jumlah uang beredar, <strong>V</strong> = kecepatan edar uang, <strong>P</strong> = tingkat harga, <strong>T</strong> = volume transaksi. Jika V dan T relatif tetap, perubahan jumlah uang langsung terpantul pada tingkat harga. Inilah inti teori kuantitas uang.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bunga nominal vs riil",
        html: "Fisher membedakan bunga <strong>nominal</strong> dan <strong>riil</strong>. Efek Fisher menyatakan bunga nominal kira-kira sama dengan bunga riil ditambah ekspektasi inflasi. Jadi jika inflasi diperkirakan 5% dan bunga riil 3%, bunga nominal sekitar 8%.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bahaya spiral deflasi utang",
        html: "Fisher memperingatkan bahwa saat harga jatuh (deflasi), beban <strong>utang</strong> secara riil justru membengkak. Orang beramai-ramai menjual aset untuk melunasi utang, harga makin jatuh, dan utang makin berat. Spiral inilah yang membuat depresi begitu dalam.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Tingkat harga AS anjlok saat Depresi Besar",
        unit: "indeks (1926=100)",
        source: "Ilustrasi edukatif berdasarkan tren harga konsumen AS 1929-1933",
        note: "Deflasi tajam menaikkan beban riil utang, sesuai teori deflasi utang Fisher.",
        data: [
          { label: "1929", value: 100, color: "#60a5fa" },
          { label: "1930", value: 97, color: "#818cf8" },
          { label: "1931", value: 89, color: "#f59e0b" },
          { label: "1932", value: 80, color: "#ef4444" },
          { label: "1933", value: 76, color: "#dc2626" },
        ],
      },
      {
        type: "widget",
        widget: "KalkulatorInflasi",
      },
      {
        type: "case",
        title: "Petani terjerat deflasi 1930-an",
        html: "Seorang petani berutang <strong>Rp 100 juta</strong> saat harga panen tinggi. Ketika deflasi menekan harga hasil tani hingga separuh, pendapatannya anjlok, tetapi nilai utangnya tetap Rp 100 juta. Secara riil beban utang berlipat: ia harus menjual dua kali lipat hasil panen untuk melunasi jumlah yang sama. Inilah mekanisme deflasi utang yang dijelaskan Fisher.",
      },
      {
        type: "case",
        title: "Sejarah: teori deflasi utang Fisher (1933)",
        html: "Pada <strong>1933</strong>, di tengah Depresi Besar, Fisher menerbitkan artikel <strong>The Debt-Deflation Theory of Great Depressions</strong>. Ia berargumen bahwa dua faktor, utang berlebih (over-indebtedness) dan deflasi, saling memperkuat menjadi spiral yang menghancurkan. Reputasi Fisher sendiri sempat rusak karena ia keliru menyatakan saham berada di dataran tinggi permanen tepat sebelum kejatuhan pasar <strong>1929</strong>, dan ia kehilangan kekayaannya. Namun teori deflasi utangnya kini diakui sebagai penjelasan penting krisis keuangan.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan persamaan MV = PT, jika M = 200, V = 6, dan T = 400, berapa tingkat harga P?",
        answer: 3,
        tolerance: 0.05,
        solution: "MV = PT, maka P = MV / T = (200 x 6) / 400 = 1200 / 400 = 3.",
        hint: "Susun ulang menjadi P = MV / T.",
      },
      {
        type: "calcExercise",
        prompt: "Menurut efek Fisher, jika bunga riil 4% dan ekspektasi inflasi 6%, berapa perkiraan bunga nominal?",
        answer: 10,
        tolerance: 0.1,
        suffix: "%",
        solution: "Bunga nominal kira-kira bunga riil + ekspektasi inflasi = 4% + 6% = 10%.",
        hint: "Jumlahkan bunga riil dan ekspektasi inflasi.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan simbol dalam persamaan pertukaran dengan artinya.",
        pairs: [
          { left: "M", right: "Jumlah uang beredar" },
          { left: "V", right: "Kecepatan edar uang" },
          { left: "P", right: "Tingkat harga" },
          { left: "T", right: "Volume transaksi" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Fisher memandang bunga sebagai harga waktu: gabungan ketaksabaran dan produktivitas modal.",
          "Persamaan pertukaran MV = PT adalah fondasi teori kuantitas uang.",
          "Efek Fisher: bunga nominal kira-kira sama dengan bunga riil ditambah ekspektasi inflasi.",
          "Deflasi utang: jatuhnya harga membengkakkan beban riil utang dan memperdalam depresi.",
          "Teori deflasi utang 1933 menjelaskan mengapa Depresi Besar begitu parah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Persamaan pertukaran Fisher ditulis sebagai?",
            options: [
              "M + V = P + T",
              "MV = PT",
              "M / V = P / T",
              "MP = VT",
            ],
            answer: 1,
            explain: "MV = PT menghubungkan jumlah dan kecepatan uang dengan harga dan volume transaksi.",
          },
          {
            q: "Menurut efek Fisher, bunga nominal kira-kira sama dengan?",
            options: [
              "Bunga riil dikurangi inflasi",
              "Bunga riil ditambah ekspektasi inflasi",
              "Hanya tingkat inflasi",
              "Nol saat deflasi",
            ],
            answer: 1,
            explain: "Efek Fisher: bunga nominal kurang lebih bunga riil ditambah ekspektasi inflasi.",
          },
          {
            q: "Dalam teori deflasi utang, jatuhnya harga membuat beban riil utang?",
            options: [
              "Berkurang",
              "Tetap",
              "Membengkak",
              "Hilang",
            ],
            answer: 2,
            explain: "Saat harga turun, nilai riil utang naik sehingga beban debitur bertambah berat.",
          },
          {
            q: "Jika M dan V naik sementara T tetap, maka menurut MV = PT?",
            options: [
              "Harga P cenderung naik",
              "Harga P pasti turun",
              "T ikut nol",
              "Uang lenyap",
            ],
            answer: 0,
            explain: "Karena MV = PT, kenaikan sisi kiri dengan T tetap mendorong tingkat harga P naik.",
          },
          {
            q: "Artikel Fisher tahun 1933 membahas?",
            options: [
              "Teori nilai kerja",
              "Teori deflasi utang pada depresi besar",
              "Utilitas marginal",
              "Perdagangan bebas",
            ],
            answer: 1,
            explain: "The Debt-Deflation Theory of Great Depressions (1933) menjelaskan spiral utang dan deflasi.",
          },
        ],
      },
    ],
  },
];
