import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "akar-pemikiran-ekonomi",
    levelId: "praklasik",
    order: 1,
    title: "Akar Pemikiran Ekonomi",
    summary: "Gagasan ekonomi sebelum ilmu ekonomi lahir: Aristoteles, Ibn Khaldun, skolastik, merkantilisme, dan fisiokrat.",
    durationMin: 13,
    tags: ["praklasik", "merkantilisme", "fisiokrat", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Ilmu ekonomi sebagai disiplin baru lahir pada 1776 lewat Adam Smith. Tetapi manusia sudah <strong>memikirkan ekonomi</strong> jauh sebelumnya: soal harga adil, uang, perdagangan, dan kekayaan negara. Memahami akar ini membantu kita melihat bagaimana ide-ide besar tumbuh.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Dari zaman kuno sampai modern, tiap mazhab menjawab persoalan zamannya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg?width=400",
        alt: "Patung Aristoteles",
        caption: "Aristoteles (384-322 SM), yang membedakan pertukaran untuk kebutuhan dari pengejaran uang tanpa batas.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Zaman kuno dan skolastik",
        html: "<strong>Aristoteles</strong> membedakan pertukaran untuk memenuhi kebutuhan dari pengejaran uang tanpa batas, dan mengkritik riba. Kaum <strong>skolastik</strong> (mis. Thomas Aquinas) membahas <strong>harga adil</strong> dan larangan bunga. <strong>Ibn Khaldun</strong> menulis tentang pembagian kerja dan pajak.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Merkantilisme & fisiokrat",
        html: "<strong>Merkantilisme</strong> (abad 16-18) menganggap kekayaan negara adalah emas, sehingga ekspor didorong dan impor dibatasi. <strong>Fisiokrat</strong> (Prancis, abad 18) menilai sumber kekayaan adalah alam/pertanian dan menyerukan <strong>laissez-faire</strong>, biarkan ekonomi berjalan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab pemikiran ekonomi untuk melihat era, tokoh, dan gagasan inti masing-masing.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "case",
        title: "Studi Kasus: Kebijakan merkantilis",
        html: "Sebuah kerajaan abad ke-17 melarang impor kain jadi dan memberi subsidi ekspor, agar emas mengalir masuk dan tidak keluar. Kebijakan ini khas <strong>merkantilisme</strong>: kekayaan diukur dari cadangan logam mulia. Adam Smith kelak mengkritiknya, dengan menegaskan bahwa kekayaan sejati adalah barang dan jasa yang bisa dinikmati rakyat, bukan tumpukan emas.",
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini milik aliran yang mana?",
        buckets: ["Merkantilisme", "Fisiokrat", "Skolastik"],
        items: [
          { text: "Kekayaan negara diukur dari cadangan emas", bucket: "Merkantilisme" },
          { text: "Dorong ekspor, batasi impor", bucket: "Merkantilisme" },
          { text: "Alam dan pertanian sumber kekayaan sejati", bucket: "Fisiokrat" },
          { text: "Harga harus adil, bunga dilarang", bucket: "Skolastik" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Adam Smith menerbitkan The Wealth of Nations pada 1776. Berapa tahun yang lalu dari tahun 2026?",
        answer: 250,
        tolerance: 0,
        suffix: " tahun",
        solution: "2026 - 1776 = <strong>250 tahun</strong>. Terbitnya buku ini menandai kelahiran ilmu ekonomi modern.",
        hint: "Kurangkan tahun terbit dari 2026.",
      },
      {
        type: "case",
        title: "Sejarah: Tableau Economique Quesnay 1758",
        html: "Pada <strong>1758</strong>, dokter istana Prancis <strong>Francois Quesnay</strong> menerbitkan <strong>Tableau Economique</strong>, salah satu upaya pertama menggambarkan ekonomi sebagai <strong>sistem aliran</strong> antarkelas (petani, pemilik tanah, pengrajin). Ini adalah cikal bakal cara berpikir ekonomi modern yang memandang perekonomian sebagai lingkaran aliran pendapatan dan produksi.",
      },
      {
        type: "takeaways",
        items: [
          "Manusia memikirkan ekonomi jauh sebelum ilmu ekonomi lahir 1776.",
          "Aristoteles dan skolastik menyoroti harga adil dan larangan riba.",
          "Merkantilisme menyamakan kekayaan dengan emas dan neraca dagang.",
          "Fisiokrat menekankan alam dan menyerukan laissez-faire.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ilmu ekonomi modern umumnya dianggap lahir tahun?",
            options: ["1776", "1500", "1900", "1867"],
            answer: 0,
            explain: "The Wealth of Nations (Adam Smith) terbit 1776, menandai kelahiran ilmu ekonomi.",
          },
          {
            q: "Merkantilisme mengukur kekayaan negara dari?",
            options: ["Cadangan emas dan neraca dagang", "Jumlah penduduk", "Luas tanah", "Kebahagiaan"],
            answer: 0,
            explain: "Merkantilis menyamakan kekayaan dengan logam mulia dan surplus dagang.",
          },
          {
            q: "Kaum fisiokrat menilai sumber kekayaan sejati adalah?",
            options: ["Emas", "Alam dan pertanian", "Perdagangan", "Industri"],
            answer: 1,
            explain: "Fisiokrat menekankan tanah dan pertanian sebagai sumber kekayaan.",
          },
          {
            q: "Laissez-faire berarti?",
            options: ["Negara mengatur ketat", "Biarkan ekonomi berjalan", "Larang perdagangan", "Naikkan pajak"],
            answer: 1,
            explain: "Laissez-faire adalah seruan agar campur tangan negara diminimalkan.",
          },
          {
            q: "Cendekiawan Muslim yang menulis gagasan ekonomi dalam Muqaddimah adalah?",
            options: ["Al-Farabi", "Ibn Khaldun", "Ibn Sina", "Al-Ghazali"],
            answer: 1,
            explain: "Ibn Khaldun membahas pembagian kerja, harga, dan pajak dalam Muqaddimah.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekonomi-zaman-kuno",
    levelId: "praklasik",
    order: 2,
    title: "Ekonomi Zaman Kuno",
    summary: "Yunani kuno memikirkan ekonomi: Aristoteles membedakan oikonomia dari pengejaran uang, Plato membahas pembagian kerja, dan riba dikritik.",
    durationMin: 14,
    tags: ["yunani", "aristoteles", "plato", "riba", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Di <strong>Yunani kuno</strong> (abad ke-5 sampai ke-4 SM), para filsuf sudah membahas pengelolaan rumah tangga dan negara. Dari sinilah lahir kata <strong>ekonomi</strong>, dari <em>oikonomia</em>: <em>oikos</em> (rumah tangga) dan <em>nomos</em> (aturan/hukum). Ekonomi awalnya berarti seni mengurus rumah tangga.",
      },
      {
        type: "paragraph",
        html: "<strong>Aristoteles</strong> membedakan dua hal: <strong>oikonomia</strong>, memenuhi kebutuhan hidup yang punya batas alami, dan <strong>chrematistike</strong>, seni menimbun uang demi uang yang menurutnya tak berbatas dan tidak alami. Ia menganggap <strong>riba</strong> (bunga atas pinjaman) sebagai bentuk paling tidak alami sebab uang seolah 'beranak' dari uang.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Yunani kuno adalah titik awal pemikiran ekonomi Barat.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg?width=400",
        alt: "Patung Aristoteles",
        caption: "Aristoteles (384-322 SM).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Oikonomia vs chrematistike",
        html: "<strong>Oikonomia</strong> = mengurus rumah tangga untuk memenuhi kebutuhan (punya batas). <strong>Chrematistike</strong> = mengejar uang demi uang (tanpa batas). Aristoteles memuji yang pertama dan mencurigai yang kedua.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Plato dan pembagian kerja",
        html: "Dalam <strong>Republik</strong>, <strong>Plato</strong> menjelaskan bahwa negara muncul karena tak seorang pun mandiri; tiap orang mengkhususkan diri pada satu pekerjaan (petani, tukang, penjaga). Ini adalah gagasan awal <strong>pembagian kerja</strong> yang kelak diperdalam Adam Smith.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kritik terhadap riba",
        html: "Aristoteles menolak bunga karena menganggap uang hanyalah alat tukar, bukan barang yang seharusnya menghasilkan lebih banyak uang. Pandangan ini sangat memengaruhi larangan riba di dunia Kristen dan Islam berabad-abad kemudian.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab untuk melihat posisi pemikiran Yunani kuno dalam rentang sejarah ekonomi.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "chart",
        variant: "bar",
        title: "Perkiraan Rentang Hidup Pemikir Ekonomi Yunani Kuno",
        unit: "tahun (SM)",
        source: "berdasarkan tahun lahir-wafat yang tercatat",
        note: "Ketiganya hidup dalam rentang abad ke-5 sampai ke-4 SM; Socrates guru Plato, dan Plato guru Aristoteles.",
        data: [
          { label: "Socrates (~470-399 SM)", value: 71, color: "#60a5fa" },
          { label: "Plato (~428-348 SM)", value: 80, color: "#34d399" },
          { label: "Aristoteles (384-322 SM)", value: 62, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pedagang dan petani",
        html: "Seorang petani menjual gandum untuk membeli sepatu; ia bertukar demi <strong>kebutuhan</strong>. Ini oikonomia. Seorang lain membeli murah dan menjual mahal berulang kali hanya untuk menumpuk koin, tanpa tujuan konsumsi. Menurut Aristoteles ini <strong>chrematistike</strong>, aktivitas yang secara moral ia curigai karena tak punya batas alami.",
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya kata oikonomia",
        html: "Sekitar <strong>abad ke-4 SM</strong>, Aristoteles menulis <em>Politika</em> dan risalah <em>Oikonomikos</em> beredar di lingkaran Yunani. Kata <strong>oikonomia</strong> saat itu berarti 'pengelolaan rumah tangga', bukan ekonomi negara seperti sekarang. Kata inilah yang, lewat bahasa Latin dan Prancis, menjadi kata <strong>ekonomi</strong> modern lebih dari dua ribu tahun kemudian.",
      },
      {
        type: "classifyExercise",
        prompt: "Aktivitas ini termasuk oikonomia atau chrematistike menurut Aristoteles?",
        buckets: ["Oikonomia", "Chrematistike"],
        items: [
          { text: "Menukar hasil panen untuk membeli pakaian yang dibutuhkan", bucket: "Oikonomia" },
          { text: "Menimbun uang demi uang tanpa batas", bucket: "Chrematistike" },
          { text: "Mengurus kebutuhan keluarga sehari-hari", bucket: "Oikonomia" },
          { text: "Meminjamkan uang demi bunga (riba)", bucket: "Chrematistike" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Aristoteles wafat 322 SM. Berapa tahun yang lalu dari tahun 2026 M? (ingat: tidak ada tahun 0)",
        answer: 2347,
        tolerance: 1,
        suffix: " tahun",
        solution: "322 + 2026 = 2348, dikurangi 1 karena tidak ada tahun 0, menjadi sekitar <strong>2347 tahun</strong> yang lalu.",
        hint: "Jumlahkan tahun SM dan tahun M, lalu kurangi 1.",
      },
      {
        type: "takeaways",
        items: [
          "Kata ekonomi berasal dari oikonomia Yunani: seni mengurus rumah tangga.",
          "Aristoteles memisahkan pemenuhan kebutuhan (oikonomia) dari pengejaran uang (chrematistike).",
          "Plato dalam Republik menjelaskan pembagian kerja demi efisiensi.",
          "Kritik Aristoteles atas riba memengaruhi etika ekonomi selama berabad-abad.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kata 'ekonomi' berasal dari kata Yunani yang berarti?",
            options: ["Pengelolaan rumah tangga", "Perang dagang", "Uang dan emas", "Pasar bebas"],
            answer: 0,
            explain: "Oikonomia berasal dari oikos (rumah tangga) dan nomos (aturan).",
          },
          {
            q: "Menurut Aristoteles, mengejar uang demi uang tanpa batas disebut?",
            options: ["Oikonomia", "Chrematistike", "Laissez-faire", "Bullionism"],
            answer: 1,
            explain: "Chrematistike adalah seni menimbun uang yang menurutnya tidak alami.",
          },
          {
            q: "Dalam karya mana Plato membahas pembagian kerja?",
            options: ["Republik", "Politika", "Muqaddimah", "Summa Theologica"],
            answer: 0,
            explain: "Dalam Republik, Plato menjelaskan spesialisasi pekerjaan dalam negara.",
          },
          {
            q: "Mengapa Aristoteles menolak riba?",
            options: ["Karena uang seolah beranak dari uang", "Karena pajak terlalu tinggi", "Karena emas langka", "Karena pasar tidak seimbang"],
            answer: 0,
            explain: "Ia menganggap uang hanya alat tukar, bukan sumber uang baru.",
          },
          {
            q: "Aristoteles adalah murid dari?",
            options: ["Socrates", "Plato", "Ibn Khaldun", "Thomas Aquinas"],
            answer: 1,
            explain: "Aristoteles murid Plato, yang merupakan murid Socrates.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pemikiran-ekonomi-islam-klasik",
    levelId: "praklasik",
    order: 3,
    title: "Pemikiran Ekonomi Islam Klasik",
    summary: "Ibn Khaldun soal pembagian kerja, siklus dinasti, dan hubungan tarif pajak dengan penerimaan negara; Abu Yusuf soal perpajakan; Al-Ghazali soal fungsi uang.",
    durationMin: 15,
    tags: ["islam", "ibn-khaldun", "abu-yusuf", "al-ghazali", "pajak", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Pada Abad Pertengahan, ketika Eropa masih dalam masa gelap, dunia Islam menjadi pusat ilmu. Para cendekiawan Muslim membahas <strong>pembagian kerja</strong>, <strong>harga</strong>, <strong>pajak</strong>, dan <strong>uang</strong> dengan tajam. Gagasan mereka sering mendahului pemikir Eropa berabad-abad kemudian.",
      },
      {
        type: "paragraph",
        html: "Tokoh paling menonjol adalah <strong>Ibn Khaldun</strong> (1332-1406). Dalam <em>Muqaddimah</em> (sekitar 1377), ia menjelaskan bahwa masyarakat sejahtera lewat <strong>pembagian kerja</strong> dan kerja sama, bahwa peradaban bergerak dalam <strong>siklus dinasti</strong> (bangkit, jaya, lalu runtuh), dan bahwa <strong>tarif pajak yang terlalu tinggi justru menurunkan penerimaan negara</strong>, sebuah gagasan yang mirip kurva Laffer modern.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Dunia Islam klasik menyumbang gagasan penting sebelum ekonomi modern lahir.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Ibn_Khaldoun-Kassus.jpg?width=400",
        alt: "Patung Ibn Khaldun",
        caption: "Ibn Khaldun (1332-1406).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ibn Khaldun dan tarif pajak",
        html: "Ibn Khaldun menulis bahwa di awal dinasti, <strong>tarif pajak rendah</strong> mendorong usaha sehingga penerimaan besar; menjelang akhir dinasti, <strong>tarif dinaikkan</strong> namun usaha melemah sehingga penerimaan malah menyusut. Inti gagasan <strong>kurva Laffer</strong> ini ia tulis sekitar 1377, hampir enam abad sebelum Arthur Laffer.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Abu Yusuf dan Al-Ghazali",
        html: "<strong>Abu Yusuf</strong> (731-798) dalam <em>Kitab al-Kharaj</em> menasihati khalifah soal perpajakan yang adil, menganjurkan <strong>pajak proporsional</strong> atas hasil tanah ketimbang sewa tetap. <strong>Al-Ghazali</strong> (1058-1111) menjelaskan <strong>fungsi uang</strong> sebagai alat tukar dan satuan hitung, serta mengecam penimbunan dan pemalsuan uang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab untuk menempatkan pemikiran ekonomi Islam klasik dalam rentang panjang sejarah ekonomi.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "chart",
        variant: "line",
        title: "Gagasan Ibn Khaldun: Tarif Pajak vs Penerimaan Negara (ilustrasi konsep, mirip kurva Laffer)",
        unit: "penerimaan relatif",
        source: "ilustrasi konsep berdasarkan uraian Muqaddimah",
        note: "Pada tarif sangat rendah maupun sangat tinggi, penerimaan negara kecil; ada titik tengah yang memaksimalkan penerimaan.",
        data: [
          { label: "0%", value: 0, color: "#60a5fa" },
          { label: "20%", value: 60, color: "#60a5fa" },
          { label: "40%", value: 90, color: "#34d399" },
          { label: "60%", value: 70, color: "#f59e0b" },
          { label: "80%", value: 35, color: "#f59e0b" },
          { label: "100%", value: 0, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pajak yang mencekik usaha",
        html: "Sebuah kesultanan menaikkan pajak pasar dari 10% menjadi 50% untuk membiayai perang. Awalnya kas negara terisi, tetapi setahun kemudian banyak pedagang tutup atau pindah, dan penerimaan pajak justru <strong>turun</strong> di bawah tingkat semula. Inilah yang diperingatkan <strong>Ibn Khaldun</strong>: tarif terlalu tinggi mematikan aktivitas yang menjadi sumber pajak itu sendiri.",
      },
      {
        type: "case",
        title: "Sejarah: Muqaddimah 1377 mendahului Laffer enam abad",
        html: "Ibn Khaldun menuntaskan <em>Muqaddimah</em> sekitar <strong>1377</strong>. Di dalamnya ia sudah menjelaskan hubungan lengkung antara tarif pajak dan penerimaan negara. Baru pada <strong>1974</strong> ekonom Amerika <strong>Arthur Laffer</strong> mempopulerkan gagasan serupa lewat 'kurva Laffer'. Jarak keduanya sekitar <strong>enam abad</strong>, bukti bahwa pemikiran ekonomi Islam klasik jauh mendahului zamannya.",
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan berikut milik tokoh yang mana?",
        buckets: ["Ibn Khaldun", "Abu Yusuf", "Al-Ghazali"],
        items: [
          { text: "Tarif pajak terlalu tinggi menurunkan penerimaan negara", bucket: "Ibn Khaldun" },
          { text: "Siklus bangkit dan runtuhnya dinasti", bucket: "Ibn Khaldun" },
          { text: "Pajak proporsional atas hasil tanah dalam Kitab al-Kharaj", bucket: "Abu Yusuf" },
          { text: "Uang sebagai alat tukar dan satuan hitung", bucket: "Al-Ghazali" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Ibn Khaldun menulis Muqaddimah sekitar 1377 dan Arthur Laffer mempopulerkan kurvanya pada 1974. Berapa selisih tahunnya?",
        answer: 597,
        tolerance: 0,
        suffix: " tahun",
        solution: "1974 - 1377 = <strong>597 tahun</strong>, sekitar enam abad lebih awal.",
        hint: "Kurangkan 1377 dari 1974.",
      },
      {
        type: "takeaways",
        items: [
          "Ibn Khaldun (Muqaddimah, ~1377) membahas pembagian kerja dan siklus dinasti.",
          "Ia menjelaskan hubungan tarif pajak dan penerimaan, mirip kurva Laffer, enam abad sebelum Laffer.",
          "Abu Yusuf dalam Kitab al-Kharaj menganjurkan perpajakan yang adil dan proporsional.",
          "Al-Ghazali menjelaskan fungsi uang sebagai alat tukar dan satuan hitung.",
          "Dunia Islam klasik menyumbang gagasan ekonomi penting sebelum era modern.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Karya utama Ibn Khaldun yang memuat gagasan ekonomi adalah?",
            options: ["Muqaddimah", "Kitab al-Kharaj", "Republik", "Summa Theologica"],
            answer: 0,
            explain: "Muqaddimah (sekitar 1377) memuat gagasan pembagian kerja, siklus dinasti, dan pajak.",
          },
          {
            q: "Gagasan Ibn Khaldun tentang tarif pajak menyerupai konsep modern apa?",
            options: ["Kurva Laffer", "Kurva Phillips", "Kurva permintaan", "Hukum Say"],
            answer: 0,
            explain: "Ia menjelaskan bahwa tarif terlalu tinggi menurunkan penerimaan, inti kurva Laffer.",
          },
          {
            q: "Kitab al-Kharaj yang membahas perpajakan ditulis oleh?",
            options: ["Al-Ghazali", "Abu Yusuf", "Ibn Sina", "Ibn Khaldun"],
            answer: 1,
            explain: "Abu Yusuf menulis Kitab al-Kharaj sebagai nasihat perpajakan kepada khalifah.",
          },
          {
            q: "Al-Ghazali terutama membahas ekonomi dalam hal?",
            options: ["Fungsi uang", "Neraca dagang", "Kurva penawaran", "Pembagian kerja industri"],
            answer: 0,
            explain: "Al-Ghazali menjelaskan uang sebagai alat tukar dan satuan hitung, serta mengecam penimbunan.",
          },
          {
            q: "Kira-kira berapa lama gagasan pajak Ibn Khaldun mendahului Arthur Laffer?",
            options: ["Enam abad", "Satu abad", "Dua puluh tahun", "Sepuluh abad"],
            answer: 0,
            explain: "Muqaddimah ~1377 dan Laffer 1974, selisih sekitar 597 tahun atau enam abad.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "skolastik-harga-adil",
    levelId: "praklasik",
    order: 4,
    title: "Skolastik: Harga Adil & Riba",
    summary: "Thomas Aquinas dan kaum skolastik abad ke-13: konsep harga adil (just price), larangan bunga (usury), dan etika ekonomi Abad Pertengahan.",
    durationMin: 14,
    tags: ["skolastik", "aquinas", "harga-adil", "riba", "abad-pertengahan", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Pada Abad Pertengahan di Eropa, pemikiran ekonomi berkembang di dalam <strong>gereja</strong> dan universitas. Para pemikir <strong>skolastik</strong> memadukan filsafat Aristoteles dengan ajaran Kristen. Pertanyaan utamanya bukan 'bagaimana untung sebesar-besarnya', melainkan 'apa yang <strong>adil</strong> dan sesuai moral' dalam berdagang dan meminjamkan uang.",
      },
      {
        type: "paragraph",
        html: "Tokoh terbesarnya adalah <strong>Thomas Aquinas</strong> (1225-1274). Dalam <em>Summa Theologica</em> (abad ke-13), ia membahas <strong>harga adil</strong> (<em>justum pretium</em>): harga yang wajar, tidak menipu, dan mencerminkan biaya serta kebutuhan, bukan hasil memanfaatkan kesulitan orang lain. Ia juga menegaskan larangan <strong>riba</strong> (<em>usury</em>), yaitu membebankan bunga atas pinjaman uang.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Skolastik menjembatani pemikiran Yunani kuno dengan ekonomi modern.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Saint_Thomas_Aquinas.jpg?width=400",
        alt: "Lukisan Thomas Aquinas",
        caption: "Thomas Aquinas (1225-1274).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Harga adil (just price)",
        html: "Menurut <strong>Aquinas</strong>, menjual barang jauh di atas nilai wajarnya, atau menaikkan harga karena pembeli sedang sangat membutuhkan, adalah <strong>tidak adil</strong> secara moral. Harga adil dekat dengan harga pasar yang normal, bukan harga yang lahir dari paksaan atau penipuan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Larangan riba (usury)",
        html: "Skolastik melarang <strong>bunga atas pinjaman uang</strong>. Alasannya mewarisi Aristoteles: uang hanya alat tukar, tidak seharusnya 'beranak'. Menjual 'waktu' lewat bunga dianggap salah karena waktu milik Tuhan. Larangan ini kelak melonggar seiring tumbuhnya perdagangan dan perbankan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser penawaran dan permintaan untuk melihat harga keseimbangan pasar, lalu bandingkan dengan gagasan harga adil kaum skolastik.",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "bar",
        title: "Rentang Hidup Pemikir Skolastik & Sekitarnya (fakta biografi)",
        unit: "tahun usia",
        source: "berdasarkan tahun lahir-wafat yang tercatat",
        note: "Aquinas hidup di puncak skolastik abad ke-13; ia menautkan filsafat Aristoteles ke etika ekonomi Kristen.",
        data: [
          { label: "Albertus Magnus (~1200-1280)", value: 80, color: "#60a5fa" },
          { label: "Thomas Aquinas (1225-1274)", value: 49, color: "#f59e0b" },
          { label: "Duns Scotus (~1266-1308)", value: 42, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pedagang gandum saat kelaparan",
        html: "Sebuah kota dilanda paceklik. Seorang pedagang membawa gandum dan tahu warga sangat lapar. Bolehkah ia menaikkan harga berlipat-lipat? Menurut <strong>Aquinas</strong>, menjual dengan harga wajar tetap boleh, tetapi <strong>memeras</strong> penderitaan orang lewat harga selangit adalah dosa, melanggar prinsip <strong>harga adil</strong>. Etika mendahului keuntungan maksimal.",
      },
      {
        type: "case",
        title: "Sejarah: Summa Theologica abad ke-13",
        html: "Thomas Aquinas menulis <em>Summa Theologica</em> pada <strong>abad ke-13</strong> (disusun sekitar 1265-1274, tidak selesai sebelum wafatnya 1274). Karya raksasa ini membahas teologi sekaligus etika, termasuk <strong>harga adil</strong> dan larangan <strong>riba</strong>. Selama berabad-abad, buku ini menjadi rujukan moral ekonomi Eropa sebelum lahirnya ilmu ekonomi modern.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Just price", right: "Harga wajar yang tidak menipu atau memeras" },
          { left: "Usury", right: "Bunga atas pinjaman yang dilarang skolastik" },
          { left: "Summa Theologica", right: "Karya Thomas Aquinas abad ke-13" },
          { left: "Skolastik", right: "Pemikiran gereja yang memadukan Aristoteles dan ajaran Kristen" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Thomas Aquinas wafat pada 1274. Berapa tahun yang lalu dari tahun 2026?",
        answer: 752,
        tolerance: 0,
        suffix: " tahun",
        solution: "2026 - 1274 = <strong>752 tahun</strong>.",
        hint: "Kurangkan 1274 dari 2026.",
      },
      {
        type: "takeaways",
        items: [
          "Skolastik memadukan filsafat Aristoteles dengan etika Kristen.",
          "Thomas Aquinas (1225-1274) mengembangkan konsep harga adil (just price).",
          "Menaikkan harga karena kesulitan orang lain dianggap tidak adil.",
          "Riba (bunga atas pinjaman) dilarang karena uang dianggap tak seharusnya beranak.",
          "Summa Theologica abad ke-13 menjadi rujukan moral ekonomi Eropa.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Konsep 'harga adil' terutama dikaitkan dengan?",
            options: ["Thomas Aquinas", "Thomas Mun", "Francois Quesnay", "Adam Smith"],
            answer: 0,
            explain: "Aquinas mengembangkan gagasan justum pretium dalam Summa Theologica.",
          },
          {
            q: "Apa yang dimaksud usury dalam pemikiran skolastik?",
            options: ["Bunga atas pinjaman uang", "Pajak perdagangan", "Harga keseimbangan", "Subsidi ekspor"],
            answer: 0,
            explain: "Usury adalah membebankan bunga atas pinjaman, yang dilarang skolastik.",
          },
          {
            q: "Skolastik memadukan ajaran Kristen dengan filsafat?",
            options: ["Aristoteles", "Plato", "Konfusius", "Descartes"],
            answer: 0,
            explain: "Aquinas menautkan filsafat Aristoteles dengan teologi Kristen.",
          },
          {
            q: "Menurut Aquinas, menaikkan harga berlipat saat orang kelaparan adalah?",
            options: ["Tidak adil secara moral", "Wajar dan dianjurkan", "Wajib demi laba", "Netral secara etika"],
            answer: 0,
            explain: "Memeras kesulitan orang lewat harga selangit melanggar prinsip harga adil.",
          },
          {
            q: "Karya besar Thomas Aquinas berjudul?",
            options: ["Summa Theologica", "Muqaddimah", "Republik", "The Wealth of Nations"],
            answer: 0,
            explain: "Summa Theologica ditulis pada abad ke-13.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "merkantilisme",
    levelId: "praklasik",
    order: 5,
    title: "Merkantilisme",
    summary: "Aliran dominan Eropa abad 16-18: kekayaan diukur dari emas, neraca dagang harus positif, proteksionisme, dan bullionism. Thomas Mun dan Colbert.",
    durationMin: 15,
    tags: ["merkantilisme", "thomas-mun", "colbert", "proteksionisme", "bullionism", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Antara <strong>abad ke-16 dan ke-18</strong>, kebijakan ekonomi Eropa didominasi <strong>merkantilisme</strong>. Inti keyakinannya: kekayaan sebuah negara diukur dari jumlah <strong>emas dan perak</strong> yang dimilikinya. Karena stok logam mulia dunia dianggap tetap, satu negara hanya bisa kaya dengan mengambil bagian yang lebih besar, sering lewat perdagangan dan penjajahan.",
      },
      {
        type: "paragraph",
        html: "Dari keyakinan itu lahir dua kebijakan pokok: <strong>neraca dagang positif</strong> (ekspor harus lebih besar daripada impor agar emas mengalir masuk) dan <strong>proteksionisme</strong> (impor dibatasi dengan tarif tinggi, ekspor didorong dengan subsidi). Pandangan bahwa emas adalah wujud kekayaan sejati disebut <strong>bullionism</strong>.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Merkantilisme mendominasi kebijakan Eropa selama tiga abad sebelum Adam Smith.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Neraca dagang positif",
        html: "Bagi merkantilis, negara yang <strong>ekspornya lebih besar</strong> daripada impor akan menerima pembayaran dalam <strong>emas</strong>, sehingga bertambah kaya. Maka tujuan kebijakan adalah menjaga surplus dagang terus-menerus, kalau perlu dengan mengorbankan negara lain.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Thomas Mun dan Colbert",
        html: "<strong>Thomas Mun</strong> (1571-1641), pedagang Inggris, menulis bahwa yang penting adalah <strong>surplus dagang total</strong> negara, bukan tiap transaksi. <strong>Jean-Baptiste Colbert</strong> (1619-1683), menteri Louis XIV, menerapkan merkantilisme di Prancis: membangun manufaktur negara, menaikkan tarif, dan mendorong ekspor.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kelemahan merkantilisme",
        html: "Adam Smith kelak menyerang merkantilisme: kekayaan sejati bukan emas, melainkan <strong>barang dan jasa</strong> yang bisa dinikmati rakyat. Jika semua negara berebut surplus dan menghambat impor, perdagangan menyusut dan semua rugi. Perdagangan sebenarnya bisa <strong>saling menguntungkan</strong>, bukan permainan menang-kalah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab untuk melihat posisi merkantilisme di antara skolastik sebelumnya dan ekonomi klasik sesudahnya.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "case",
        title: "Studi Kasus: Menekan impor demi emas",
        html: "Sebuah negara mengenakan tarif 40% atas kain impor dan memberi subsidi bagi eksportir kain lokal. Tujuannya jelas <strong>merkantilis</strong>: menahan emas agar tidak keluar dan menarik emas dari luar lewat ekspor. Dalam jangka pendek cadangan emas naik, tetapi harga di dalam negeri menjadi mahal dan konsumen rugi, kritik yang kelak diangkat ekonom klasik.",
      },
      {
        type: "case",
        title: "Sejarah: Dominasi kebijakan merkantilis abad 16-18",
        html: "Sepanjang <strong>abad ke-16 hingga ke-18</strong>, negara-negara seperti Inggris, Prancis, Spanyol, dan Belanda menjalankan kebijakan merkantilis. Inggris memberlakukan <strong>Navigation Acts</strong> (mulai 1651) agar perdagangan koloni memakai kapal Inggris. Di Prancis, <strong>Colbert</strong> (menjabat sejak 1665) membangun industri dan tarif. Dominasi ini baru goyah setelah <strong>Adam Smith</strong> menerbitkan The Wealth of Nations pada 1776.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebijakan atau gagasan ini sejalan dengan merkantilisme atau menentangnya?",
        buckets: ["Sejalan merkantilisme", "Menentang merkantilisme"],
        items: [
          { text: "Menaikkan tarif impor agar emas tidak keluar", bucket: "Sejalan merkantilisme" },
          { text: "Memberi subsidi kepada eksportir", bucket: "Sejalan merkantilisme" },
          { text: "Menimbun cadangan emas dan perak", bucket: "Sejalan merkantilisme" },
          { text: "Perdagangan bebas yang saling menguntungkan", bucket: "Menentang merkantilisme" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah negara mencatat ekspor senilai 120 juta koin emas dan impor 90 juta koin emas dalam setahun. Berapa surplus neraca dagangnya (juta koin emas)?",
        answer: 30,
        tolerance: 0,
        suffix: " juta koin",
        solution: "Surplus = ekspor - impor = 120 - 90 = <strong>30 juta koin emas</strong>. Bagi merkantilis, surplus inilah tambahan emas yang masuk.",
        hint: "Kurangkan impor dari ekspor.",
      },
      {
        type: "takeaways",
        items: [
          "Merkantilisme mendominasi kebijakan Eropa abad ke-16 hingga ke-18.",
          "Kekayaan negara diukur dari cadangan emas dan perak (bullionism).",
          "Kebijakan intinya: neraca dagang positif dan proteksionisme.",
          "Thomas Mun dan Colbert adalah tokoh penting penerapnya.",
          "Adam Smith mengkritiknya: kekayaan sejati adalah barang dan jasa, bukan emas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Merkantilisme mengukur kekayaan negara terutama dari?",
            options: ["Cadangan emas dan perak", "Jumlah penduduk", "Luas hutan", "Tingkat pendidikan"],
            answer: 0,
            explain: "Bullionism memandang logam mulia sebagai wujud kekayaan sejati.",
          },
          {
            q: "Agar emas masuk, merkantilis menginginkan neraca dagang yang?",
            options: ["Positif (ekspor > impor)", "Negatif (impor > ekspor)", "Seimbang", "Nol"],
            answer: 0,
            explain: "Surplus dagang membawa pembayaran dalam emas ke dalam negeri.",
          },
          {
            q: "Menteri Louis XIV yang menerapkan merkantilisme di Prancis adalah?",
            options: ["Jean-Baptiste Colbert", "Francois Quesnay", "Thomas Mun", "Turgot"],
            answer: 0,
            explain: "Colbert membangun manufaktur negara dan menaikkan tarif impor.",
          },
          {
            q: "Istilah bullionism paling tepat berarti?",
            options: ["Kekayaan berwujud emas dan perak", "Perdagangan bebas", "Pembagian kerja", "Harga adil"],
            answer: 0,
            explain: "Bullionism menyamakan kekayaan dengan timbunan logam mulia.",
          },
          {
            q: "Siapa yang mengkritik merkantilisme dan menegaskan kekayaan sejati adalah barang dan jasa?",
            options: ["Adam Smith", "Thomas Mun", "Colbert", "Aquinas"],
            answer: 0,
            explain: "Adam Smith dalam The Wealth of Nations (1776) menyerang logika merkantilis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "fisiokrat-laissez-faire",
    levelId: "praklasik",
    order: 6,
    title: "Fisiokrat & Laissez-faire",
    summary: "Aliran Prancis abad ke-18: Francois Quesnay dan Tableau Economique 1758, gagasan pertanian sebagai sumber kekayaan (produit net), Turgot, dan laissez-faire.",
    durationMin: 15,
    tags: ["fisiokrat", "quesnay", "tableau-economique", "turgot", "laissez-faire", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Di <strong>Prancis pada abad ke-18</strong>, sekelompok pemikir menentang merkantilisme dan lahir sebagai <strong>fisiokrat</strong>. Kata itu berarti 'pemerintahan oleh alam'. Bagi mereka, sumber kekayaan sejati bukan emas atau perdagangan, melainkan <strong>alam dan pertanian</strong>, karena hanya tanah yang menghasilkan lebih banyak daripada yang dimasukkan ke dalamnya.",
      },
      {
        type: "paragraph",
        html: "Pemimpinnya, <strong>Francois Quesnay</strong> (1694-1774), seorang dokter istana, menerbitkan <strong>Tableau Economique</strong> pada <strong>1758</strong>. Ini adalah upaya pertama menggambarkan ekonomi sebagai <strong>sistem aliran</strong> antarkelas: petani, pemilik tanah, dan kelas mandul (pengrajin, pedagang). Ia memperkenalkan gagasan <strong>produit net</strong>, surplus bersih yang hanya diyakini muncul dari sektor pertanian.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Fisiokrat menjadi jembatan langsung menuju ekonomi klasik Adam Smith.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Francois_Quesnay.jpg?width=400",
        alt: "Potret Francois Quesnay",
        caption: "Francois Quesnay (1694-1774).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Produit net dari tanah",
        html: "Fisiokrat percaya hanya <strong>pertanian</strong> menghasilkan <strong>produit net</strong>, yaitu keluaran yang lebih besar daripada masukan. Perdagangan dan kerajinan dianggap 'mandul' (steril), hanya mengubah bentuk barang tanpa menambah kekayaan baru. Pandangan ini keliru soal industri, tetapi tajam dalam gagasan surplus.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Quesnay, Turgot, dan laissez-faire",
        html: "<strong>Turgot</strong> (1727-1781), pengikut fisiokrat yang sempat jadi menteri keuangan Prancis, mencoba melonggarkan pasar biji-bijian dan memangkas hambatan. Semboyan aliran ini adalah <strong>laissez-faire, laissez-passer</strong>: biarkan berbuat, biarkan berlalu. Negara sebaiknya tidak terlalu mengatur ekonomi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab untuk melihat bagaimana fisiokrat menjadi jembatan dari merkantilisme menuju ekonomi klasik.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "chart",
        variant: "donut",
        title: "Tiga Kelas dalam Tableau Economique Quesnay (ilustrasi konsep)",
        unit: "peran dalam aliran",
        source: "ilustrasi konsep berdasarkan Tableau Economique 1758",
        note: "Quesnay membagi ekonomi jadi tiga kelas; hanya kelas produktif (petani) yang diyakini menghasilkan surplus bersih.",
        data: [
          { label: "Kelas produktif (petani)", value: 45, color: "#34d399" },
          { label: "Pemilik tanah", value: 30, color: "#f59e0b" },
          { label: "Kelas mandul (pengrajin, pedagang)", value: 25, color: "#60a5fa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Biarkan pasar biji-bijian bebas",
        html: "Untuk mencegah kelaparan, pemerintah biasa mengatur ketat harga dan peredaran gandum. Kaum <strong>fisiokrat</strong> berpendapat sebaliknya: bila perdagangan gandum <strong>dibebaskan</strong>, petani terdorong menanam lebih banyak dan pasokan justru membaik. Turgot mencoba menerapkan ini, meski menghadapi banyak tentangan dari kepentingan lama.",
      },
      {
        type: "case",
        title: "Sejarah: Tableau Economique 1758",
        html: "Pada <strong>1758</strong>, Francois Quesnay menerbitkan <strong>Tableau Economique</strong>, diagram yang menggambarkan bagaimana pendapatan dan produksi <strong>mengalir</strong> antara petani, pemilik tanah, dan kelas mandul. Ini adalah salah satu <strong>model ekonomi pertama</strong> dalam sejarah, cikal bakal analisis aliran pendapatan yang dipakai ekonomi modern. Karya ini terbit hanya <strong>18 tahun</strong> sebelum The Wealth of Nations 1776.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh atau istilah fisiokrat dengan maknanya.",
        pairs: [
          { left: "Francois Quesnay", right: "Penulis Tableau Economique 1758" },
          { left: "Produit net", right: "Surplus bersih yang diyakini hanya dari pertanian" },
          { left: "Laissez-faire", right: "Biarkan ekonomi berjalan tanpa banyak campur tangan negara" },
          { left: "Turgot", right: "Menteri keuangan Prancis pengikut fisiokrat" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Tableau Economique terbit 1758 dan The Wealth of Nations terbit 1776. Berapa selisih tahunnya?",
        answer: 18,
        tolerance: 0,
        suffix: " tahun",
        solution: "1776 - 1758 = <strong>18 tahun</strong>. Fisiokrat langsung mendahului dan memengaruhi Adam Smith.",
        hint: "Kurangkan 1758 dari 1776.",
      },
      {
        type: "takeaways",
        items: [
          "Fisiokrat (Prancis, abad ke-18) menilai alam dan pertanian sumber kekayaan sejati.",
          "Francois Quesnay menerbitkan Tableau Economique 1758, salah satu model ekonomi pertama.",
          "Gagasan produit net: hanya pertanian menghasilkan surplus bersih.",
          "Semboyan laissez-faire menyerukan campur tangan negara diminimalkan.",
          "Fisiokrat menjadi jembatan langsung menuju ekonomi klasik Adam Smith 1776.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fisiokrat menilai sumber kekayaan sejati adalah?",
            options: ["Alam dan pertanian", "Emas dan perak", "Perdagangan luar negeri", "Industri manufaktur"],
            answer: 0,
            explain: "Fisiokrat percaya hanya tanah/pertanian menghasilkan produit net.",
          },
          {
            q: "Tableau Economique 1758 ditulis oleh?",
            options: ["Francois Quesnay", "Thomas Mun", "Adam Smith", "Colbert"],
            answer: 0,
            explain: "Quesnay menggambarkan ekonomi sebagai sistem aliran antarkelas.",
          },
          {
            q: "Istilah produit net merujuk pada?",
            options: ["Surplus bersih dari pertanian", "Cadangan emas negara", "Bunga pinjaman", "Harga adil"],
            answer: 0,
            explain: "Produit net adalah keluaran yang melebihi masukan, diyakini hanya dari tanah.",
          },
          {
            q: "Semboyan laissez-faire berarti?",
            options: ["Biarkan ekonomi berjalan", "Timbun emas", "Naikkan tarif impor", "Larang perdagangan"],
            answer: 0,
            explain: "Laissez-faire menyerukan agar campur tangan negara diminimalkan.",
          },
          {
            q: "Pengikut fisiokrat yang menjadi menteri keuangan Prancis adalah?",
            options: ["Turgot", "Thomas Mun", "Aquinas", "Ibn Khaldun"],
            answer: 0,
            explain: "Turgot mencoba menerapkan gagasan fisiokrat, termasuk pembebasan pasar biji-bijian.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "menuju-ilmu-ekonomi",
    levelId: "praklasik",
    order: 7,
    title: "Menuju Kelahiran Ilmu Ekonomi",
    summary: "Perintis sebelum Adam Smith: William Petty dan aritmetika politik, Richard Cantillon, serta pengaruh Pencerahan yang mengantar menuju 1776.",
    durationMin: 15,
    tags: ["petty", "cantillon", "pencerahan", "praklasik", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Menjelang tahun <strong>1776</strong>, banyak benih pemikiran ekonomi sudah tumbuh. Sebelum Adam Smith merangkumnya menjadi ilmu yang utuh, beberapa perintis abad ke-17 dan ke-18 sudah mencoba <strong>mengukur</strong> dan <strong>menganalisis</strong> ekonomi secara sistematis. Mereka mengubah pembahasan ekonomi dari sekadar moral dan kebijakan menjadi upaya memahami cara kerja perekonomian.",
      },
      {
        type: "paragraph",
        html: "<strong>William Petty</strong> (1623-1687) di Inggris memelopori <strong>aritmetika politik</strong>: gagasan bahwa negara dan ekonomi bisa dipelajari lewat <strong>angka dan pengukuran</strong>, cikal bakal statistik ekonomi. <strong>Richard Cantillon</strong> (sekitar 1680-1734) menulis <em>Essai sur la Nature du Commerce en General</em>, yang membahas peran <strong>wirausahawan</strong>, harga, dan aliran uang dengan tajam dan memengaruhi fisiokrat maupun Smith.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Perintis abad ke-17 dan ke-18 membuka jalan menuju kelahiran ilmu ekonomi 1776.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aritmetika politik William Petty",
        html: "<strong>Petty</strong> percaya negara sebaiknya diperintah dengan '<strong>bilangan, bobot, dan ukuran</strong>', bukan sekadar pendapat. Ia mencoba menaksir pendapatan nasional dan jumlah penduduk. Ini adalah awal dari kebiasaan <strong>mengukur ekonomi dengan data</strong> yang kini menjadi tulang punggung ilmu ekonomi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Richard Cantillon dan wirausahawan",
        html: "<strong>Cantillon</strong> menjelaskan peran <strong>wirausahawan</strong> (entrepreneur): orang yang membeli dengan harga pasti dan menjual dengan harga tak pasti, sehingga menanggung <strong>risiko</strong>. Ia juga menganalisis bagaimana penambahan uang menyebar ke seluruh ekonomi, gagasan yang jauh mendahului zamannya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Pengaruh Pencerahan",
        html: "Abad <strong>Pencerahan</strong> menekankan <strong>akal</strong>, pengamatan, dan hukum alam. Semangat inilah yang mendorong para pemikir memperlakukan ekonomi sebagai sistem yang punya <strong>keteraturan</strong> dan bisa dianalisis, bukan sekadar urusan kebijakan raja. Dari sini jalan menuju sintesis besar Adam Smith terbuka.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "chart",
        variant: "bar",
        title: "Perintis Menuju Ilmu Ekonomi dan Jarak ke 1776 (fakta tahun karya)",
        unit: "tahun sebelum 1776",
        source: "berdasarkan tahun terbit atau puncak karya masing-masing",
        note: "Petty dan Cantillon menulis puluhan tahun sebelum 1776, menyiapkan bahan yang dirangkum Adam Smith.",
        data: [
          { label: "Petty, Political Arithmetick (~1676)", value: 100, color: "#60a5fa" },
          { label: "Cantillon, Essai (ditulis ~1730)", value: 46, color: "#f59e0b" },
          { label: "Quesnay, Tableau (1758)", value: 18, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menaksir kekayaan negara dengan angka",
        html: "Alih-alih hanya berkata 'negara ini kaya', <strong>William Petty</strong> mencoba <strong>menghitung</strong>: berapa penduduknya, berapa hasil tanahnya, berapa nilai kerja rakyatnya. Dengan menaksir angka-angka ini, ia meletakkan dasar bagi apa yang kini kita sebut <strong>statistik ekonomi</strong> dan pengukuran pendapatan nasional, alat pokok ekonomi modern.",
      },
      {
        type: "case",
        title: "Sejarah: Cantillon dan Petty pada abad ke-17 dan ke-18",
        html: "<strong>William Petty</strong> aktif pada <strong>abad ke-17</strong> (1623-1687) dan menulis Political Arithmetick sekitar 1670-an. <strong>Richard Cantillon</strong> (sekitar 1680-1734) menyusun <em>Essai</em>-nya pada awal <strong>abad ke-18</strong>, terbit anumerta pada <strong>1755</strong>. Keduanya menulis puluhan tahun sebelum <strong>1776</strong>, menyiapkan konsep harga, uang, dan wirausaha yang kemudian dirangkum dan disempurnakan oleh Adam Smith.",
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan atau sumbangan berikut milik tokoh yang mana?",
        buckets: ["William Petty", "Richard Cantillon"],
        items: [
          { text: "Aritmetika politik: memerintah dengan bilangan, bobot, dan ukuran", bucket: "William Petty" },
          { text: "Menaksir pendapatan nasional dan jumlah penduduk", bucket: "William Petty" },
          { text: "Peran wirausahawan yang menanggung risiko harga tak pasti", bucket: "Richard Cantillon" },
          { text: "Analisis bagaimana penambahan uang menyebar ke ekonomi", bucket: "Richard Cantillon" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "William Petty wafat pada 1687 dan The Wealth of Nations terbit 1776. Berapa selisih tahunnya?",
        answer: 89,
        tolerance: 0,
        suffix: " tahun",
        solution: "1776 - 1687 = <strong>89 tahun</strong>. Gagasan Petty sudah muncul hampir seabad sebelum Smith.",
        hint: "Kurangkan 1687 dari 1776.",
      },
      {
        type: "takeaways",
        items: [
          "Sebelum Adam Smith, sudah ada perintis yang mencoba menganalisis ekonomi secara sistematis.",
          "William Petty memelopori aritmetika politik, cikal bakal statistik ekonomi.",
          "Richard Cantillon menjelaskan peran wirausahawan dan penyebaran uang.",
          "Semangat Pencerahan mendorong ekonomi dipandang sebagai sistem yang teratur.",
          "Semua benih ini bertemu dan dirangkum Adam Smith pada 1776.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "William Petty dikenal sebagai pelopor?",
            options: ["Aritmetika politik", "Merkantilisme", "Just price", "Laissez-faire"],
            answer: 0,
            explain: "Petty mempelopori pengukuran ekonomi dengan angka, cikal bakal statistik ekonomi.",
          },
          {
            q: "Richard Cantillon terutama dikenal karena menganalisis peran?",
            options: ["Wirausahawan dan aliran uang", "Cadangan emas", "Harga adil skolastik", "Pajak dinasti"],
            answer: 0,
            explain: "Cantillon menyoroti wirausahawan penanggung risiko dan penyebaran uang.",
          },
          {
            q: "Menurut Petty, negara sebaiknya diperintah dengan?",
            options: ["Bilangan, bobot, dan ukuran", "Emas dan perak", "Tarif tinggi", "Larangan riba"],
            answer: 0,
            explain: "Ia menekankan pengambilan keputusan berdasarkan angka dan pengukuran.",
          },
          {
            q: "Semangat abad Pencerahan yang memengaruhi ekonomi menekankan?",
            options: ["Akal dan pengamatan", "Penimbunan emas", "Kepatuhan pada raja", "Larangan perdagangan"],
            answer: 0,
            explain: "Pencerahan mendorong ekonomi dipandang sebagai sistem teratur yang bisa dianalisis.",
          },
          {
            q: "Semua benih pemikiran praklasik akhirnya dirangkum oleh Adam Smith pada tahun?",
            options: ["1776", "1867", "1936", "1690"],
            answer: 0,
            explain: "The Wealth of Nations terbit 1776, menandai kelahiran ilmu ekonomi modern.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekonomi-moral-dan-agama",
    levelId: "praklasik",
    order: 8,
    title: "Ekonomi dalam Tradisi Moral & Agama",
    summary: "Sebelum menjadi ilmu terpisah, ekonomi adalah cabang etika: gagasan keadilan, larangan riba, dan harga adil muncul lintas peradaban di Yunani, Kristen Abad Pertengahan, dan Islam.",
    durationMin: 14,
    tags: ["etika", "agama", "riba", "harga-adil", "keadilan", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Selama ribuan tahun, memikirkan ekonomi berarti memikirkan <strong>apa yang benar dan adil</strong>, bukan sekadar apa yang menguntungkan. Ekonomi bukan ilmu tersendiri, melainkan <strong>cabang etika dan agama</strong>. Pertanyaan pokoknya bukan 'bagaimana memaksimalkan laba', melainkan 'berapa harga yang pantas' dan 'bolehkah mengambil bunga atas pinjaman'.",
      },
      {
        type: "paragraph",
        html: "Yang menarik, tiga persoalan yang sama muncul <strong>lintas peradaban</strong>: keadilan dalam pertukaran, <strong>larangan riba</strong> (bunga), dan gagasan <strong>harga adil</strong>. Yunani, tradisi Kristen Abad Pertengahan, dan Islam sama-sama membahasnya secara mendalam, sering saling memengaruhi lewat warisan pemikiran Aristoteles.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Etika dan agama menjadi bingkai awal semua pemikiran ekonomi sebelum era modern.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ekonomi awalnya cabang etika",
        html: "Bagi Aristoteles, kaum skolastik, maupun cendekiawan Muslim, ekonomi adalah bagian dari <strong>filsafat moral</strong>. Barang punya nilai guna, tetapi pertukaran harus <strong>adil</strong>. Baru pada 1776 Adam Smith memisahkan analisis ekonomi menjadi disiplin tersendiri, meski ia sendiri seorang <strong>guru filsafat moral</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga tradisi, satu keprihatinan",
        html: "<strong>Yunani</strong> (Aristoteles) mencurigai pengejaran uang tanpa batas dan menolak riba. <strong>Kristen Abad Pertengahan</strong> (skolastik) merumuskan harga adil dan melarang bunga. <strong>Islam</strong> melarang riba dan mendorong perdagangan yang jujur. Ketiganya menempatkan keadilan di atas keuntungan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri peta mazhab untuk melihat betapa panjang rentang waktu ketika ekonomi dipahami sebagai bagian dari etika dan agama.",
      },
      { type: "widget", widget: "TimelineMazhabEkonomi" },
      {
        type: "chart",
        variant: "bar",
        title: "Rentang Panjang Manusia Bergulat dengan Bunga Pinjaman (perkiraan, tahun lalu dari 2026)",
        unit: "tahun yang lalu",
        source: "berdasarkan penanggalan teks dan peristiwa yang tercatat, angka bersifat perkiraan",
        note: "Aturan dan larangan atas bunga muncul berulang di banyak peradaban selama lebih dari tiga milenium, tanda bahwa ini persoalan moral yang tua.",
        data: [
          { label: "Kode Hammurabi batasi bunga (~1750 SM)", value: 3775, color: "#f59e0b" },
          { label: "Aristoteles kritik riba (~340 SM)", value: 2365, color: "#60a5fa" },
          { label: "Konsili Nicea batasi riba klerus (325 M)", value: 1701, color: "#34d399" },
          { label: "Larangan riba dalam Islam (~630 M)", value: 1396, color: "#a78bfa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Harga adil di pasar Abad Pertengahan",
        html: "Di sebuah kota Abad Pertengahan, seorang tukang roti ingin menjual roti jauh di atas harga biasa saat panen buruk. Menurut ajaran <strong>skolastik</strong> tentang <strong>harga adil</strong>, ini tidak dibenarkan: harga wajar mencerminkan biaya dan kebutuhan, bukan hasil memanfaatkan kesulitan orang. Prinsip yang sama, keadilan mendahului laba, juga ditegaskan tradisi Yunani dan Islam.",
      },
      {
        type: "case",
        title: "Sejarah: Larangan riba yang muncul lintas tradisi",
        html: "Larangan atas bunga muncul berkali-kali dalam sejarah. <strong>Kode Hammurabi</strong> (sekitar 1750 SM) sudah membatasi tingkat bunga. Kitab <strong>Taurat</strong> melarang membebani bunga kepada sesama. <strong>Aristoteles</strong> (sekitar 340 SM) menolak riba karena uang dianggap tak seharusnya beranak. Gereja Kristen menegaskannya lewat <strong>Konsili Nicea 325 M</strong> dan <strong>Konsili Lateran Ketiga 1179</strong>. Dalam <strong>Islam</strong> abad ke-7 M, riba dilarang tegas. Kesamaan lintas peradaban ini menunjukkan bunga adalah persoalan moral yang tua dan universal.",
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan atau aturan ekonomi ini paling erat dengan tradisi yang mana?",
        buckets: ["Yunani (Aristoteles)", "Kristen skolastik", "Islam"],
        items: [
          { text: "Membedakan oikonomia dari chrematistike", bucket: "Yunani (Aristoteles)" },
          { text: "Konsep harga adil (just price) dalam Summa Theologica", bucket: "Kristen skolastik" },
          { text: "Larangan riba dalam Al-Qur'an dan anjuran dagang yang jujur", bucket: "Islam" },
          { text: "Konsili Lateran Ketiga 1179 mengutuk usury", bucket: "Kristen skolastik" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Konsili Nicea membatasi praktik riba bagi para klerus pada tahun 325 M. Berapa tahun yang lalu dari tahun 2026?",
        answer: 1701,
        tolerance: 0,
        suffix: " tahun",
        solution: "2026 - 325 = <strong>1701 tahun</strong>. Larangan bunga sudah ditegaskan gereja hampir tujuh belas abad lalu.",
        hint: "Kurangkan 325 dari 2026.",
      },
      {
        type: "takeaways",
        items: [
          "Selama ribuan tahun ekonomi dipahami sebagai cabang etika dan agama, bukan ilmu terpisah.",
          "Tiga persoalan yang sama muncul lintas peradaban: keadilan pertukaran, larangan riba, dan harga adil.",
          "Yunani, Kristen Abad Pertengahan, dan Islam sama-sama menempatkan keadilan di atas keuntungan.",
          "Larangan bunga muncul berulang dari Kode Hammurabi, Taurat, Aristoteles, konsili gereja, hingga Islam.",
          "Adam Smith, yang memisahkan ekonomi jadi ilmu tersendiri pada 1776, sendiri seorang guru filsafat moral.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Sebelum era modern, ekonomi umumnya dipahami sebagai?",
            options: ["Cabang etika dan agama", "Ilmu pasti tersendiri", "Cabang kedokteran", "Seni militer"],
            answer: 0,
            explain: "Ekonomi dibahas dalam bingkai moral: keadilan, harga adil, dan larangan riba.",
          },
          {
            q: "Tiga tradisi (Yunani, Kristen, Islam) sama-sama membahas larangan atas?",
            options: ["Riba atau bunga pinjaman", "Ekspor barang", "Penggunaan uang logam", "Pembagian kerja"],
            answer: 0,
            explain: "Ketiganya menolak atau membatasi bunga atas pinjaman uang.",
          },
          {
            q: "Konsep 'harga adil' paling erat dengan tradisi?",
            options: ["Kristen skolastik", "Merkantilis", "Fisiokrat", "Pencerahan"],
            answer: 0,
            explain: "Kaum skolastik seperti Aquinas merumuskan just price dalam bingkai moral Kristen.",
          },
          {
            q: "Kode hukum kuno yang sudah membatasi tingkat bunga adalah?",
            options: ["Kode Hammurabi", "Magna Carta", "Kode Napoleon", "Navigation Acts"],
            answer: 0,
            explain: "Kode Hammurabi (sekitar 1750 SM) mengatur batas bunga atas pinjaman.",
          },
          {
            q: "Adam Smith, yang memisahkan ekonomi menjadi ilmu tersendiri, berlatar belakang sebagai?",
            options: ["Guru filsafat moral", "Panglima perang", "Pendeta paus", "Pedagang emas"],
            answer: 0,
            explain: "Smith adalah profesor filsafat moral, menegaskan akar etika dari ilmu ekonomi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "proteksi-vs-perdagangan-bebas",
    levelId: "praklasik",
    order: 9,
    title: "Debat Proteksi vs Perdagangan Bebas",
    summary: "Pertentangan lama antara merkantilis yang melindungi industri dalam negeri dan klasik yang meyakini perdagangan bebas menguntungkan semua, berlanjut ke Friedrich List dan argumen industri muda.",
    durationMin: 15,
    tags: ["proteksionisme", "perdagangan-bebas", "keunggulan-komparatif", "friedrich-list", "corn-laws", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "Salah satu debat tertua dalam ekonomi: haruskah negara <strong>melindungi</strong> industri dalam negeri dengan tarif, atau membuka diri pada <strong>perdagangan bebas</strong>? Kaum <strong>merkantilis</strong> membela proteksi demi menahan emas dan menjaga industri lokal. Ekonom <strong>klasik</strong> membalikkannya: perdagangan bebas membuat setiap negara berspesialisasi pada yang paling efisien, sehingga semua pihak menang.",
      },
      {
        type: "paragraph",
        html: "Senjata teoretis kaum klasik adalah <strong>keunggulan komparatif</strong> dari <strong>David Ricardo</strong> (1817). Intinya: sekalipun satu negara lebih unggul di segala barang, ia tetap untung dengan berdagang, asal masing-masing memusatkan diri pada barang yang <strong>biaya peluangnya paling rendah</strong>. Tetapi <strong>Friedrich List</strong> (1789-1846) membantah, bahwa negara yang industrinya masih <strong>muda</strong> perlu proteksi sementara sampai cukup kuat bersaing.",
      },
      {
        type: "video",
        comp: "KeunggulanKomparatif",
        title: "Video: Keunggulan Komparatif",
        caption: "Mengapa dua negara bisa sama-sama untung dari perdagangan, bahkan bila salah satu lebih unggul di segalanya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Keunggulan komparatif Ricardo",
        html: "<strong>Ricardo</strong> menunjukkan lewat contoh Inggris (kain) dan Portugal (anggur): kunci bukan siapa lebih unggul mutlak, melainkan siapa yang <strong>biaya peluangnya</strong> lebih rendah untuk tiap barang. Dengan berspesialisasi lalu berdagang, total produksi kedua negara naik dan keduanya lebih makmur.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Friedrich List dan industri muda",
        html: "<strong>List</strong> dalam <em>The National System of Political Economy</em> (1841) menilai perdagangan bebas menguntungkan negara yang sudah maju lebih dulu. Negara terlambat, katanya, perlu <strong>tarif proteksi sementara</strong> agar 'industri muda'-nya tumbuh, baru kemudian membuka diri. Argumen ini masih dipakai negara berkembang hingga kini.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah tingkat produktivitas dua negara dan lihat siapa punya keunggulan komparatif di barang apa, lalu buktikan bahwa berdagang menaikkan total keluaran.",
      },
      { type: "widget", widget: "SimulatorKeunggulanKomparatif" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Peluang 1 Unit Anggur (dalam unit kain) - ilustrasi keunggulan komparatif",
        unit: "unit kain",
        source: "ilustrasi konsep keunggulan komparatif ala Ricardo",
        note: "Negara B mengorbankan lebih sedikit kain untuk tiap anggur, jadi B sebaiknya berspesialisasi di anggur dan A di kain.",
        data: [
          { label: "Negara A: biaya peluang anggur", value: 2, color: "#f59e0b" },
          { label: "Negara B: biaya peluang anggur", value: 0.5, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua negara, dua barang",
        html: "Dengan sumber daya yang sama, <strong>Negara A</strong> bisa membuat 100 unit kain atau 50 unit anggur; <strong>Negara B</strong> bisa membuat 40 unit kain atau 80 unit anggur. Biaya peluang 1 anggur bagi A adalah 2 kain, bagi B hanya 0,5 kain. Maka A sebaiknya fokus pada <strong>kain</strong>, B pada <strong>anggur</strong>, lalu keduanya berdagang. Total kain dan anggur yang tersedia menjadi lebih banyak dibanding jika masing-masing berusaha sendiri.",
      },
      {
        type: "case",
        title: "Sejarah: Pencabutan Corn Laws 1846",
        html: "Sejak <strong>1815</strong>, Inggris memberlakukan <strong>Corn Laws</strong>, tarif yang membuat harga gandum impor mahal demi melindungi tuan tanah. Harga roti pun tinggi dan rakyat menderita. <strong>Anti-Corn Law League</strong> pimpinan <strong>Richard Cobden</strong> dan <strong>John Bright</strong> menuntut perdagangan bebas. Pada <strong>1846</strong>, Perdana Menteri <strong>Robert Peel</strong> mencabut Corn Laws, sebuah kemenangan besar bagi kubu <strong>perdagangan bebas</strong> dan penerapan nyata gagasan ekonomi klasik.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebijakan atau argumen ini condong ke proteksionisme atau perdagangan bebas?",
        buckets: ["Proteksionisme", "Perdagangan bebas"],
        items: [
          { text: "Tarif tinggi atas gandum impor demi melindungi tuan tanah", bucket: "Proteksionisme" },
          { text: "Argumen industri muda Friedrich List", bucket: "Proteksionisme" },
          { text: "Setiap negara berspesialisasi sesuai keunggulan komparatif", bucket: "Perdagangan bebas" },
          { text: "Pencabutan Corn Laws Inggris pada 1846", bucket: "Perdagangan bebas" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Dengan sumber daya yang sama, Negara A bisa menghasilkan 100 unit kain ATAU 50 unit anggur. Berapa biaya peluang memproduksi 1 unit anggur, dinyatakan dalam unit kain?",
        answer: 2,
        tolerance: 0,
        suffix: " unit kain",
        solution: "Biaya peluang 1 anggur = kain yang dikorbankan = 100 / 50 = <strong>2 unit kain</strong>. Untuk tiap anggur, A melepas 2 kain.",
        hint: "Bagi jumlah kain maksimum dengan jumlah anggur maksimum.",
      },
      {
        type: "takeaways",
        items: [
          "Proteksi vs perdagangan bebas adalah salah satu debat tertua dalam ekonomi.",
          "Merkantilis membela tarif; ekonom klasik meyakini perdagangan bebas menguntungkan semua.",
          "Keunggulan komparatif Ricardo (1817): berdaganglah sesuai biaya peluang terendah, bukan keunggulan mutlak.",
          "Friedrich List membela proteksi sementara bagi industri muda negara terlambat.",
          "Pencabutan Corn Laws Inggris 1846 menjadi kemenangan nyata kubu perdagangan bebas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Gagasan keunggulan komparatif dirumuskan oleh?",
            options: ["David Ricardo", "Thomas Mun", "Friedrich List", "Colbert"],
            answer: 0,
            explain: "Ricardo (1817) menunjukkan dua negara bisa sama-sama untung lewat spesialisasi.",
          },
          {
            q: "Inti keunggulan komparatif adalah berdagang menurut?",
            options: ["Biaya peluang terendah", "Cadangan emas terbesar", "Jumlah penduduk terbanyak", "Luas wilayah terluas"],
            answer: 0,
            explain: "Yang menentukan bukan keunggulan mutlak, tetapi biaya peluang tiap barang.",
          },
          {
            q: "Argumen 'industri muda' yang membela proteksi sementara dikemukakan oleh?",
            options: ["Friedrich List", "David Ricardo", "Adam Smith", "Richard Cobden"],
            answer: 0,
            explain: "List menilai industri muda negara terlambat perlu tarif sementara sebelum bersaing bebas.",
          },
          {
            q: "Corn Laws Inggris dicabut pada tahun?",
            options: ["1846", "1776", "1815", "1929"],
            answer: 0,
            explain: "Pada 1846 PM Robert Peel mencabut Corn Laws, kemenangan bagi perdagangan bebas.",
          },
          {
            q: "Jika Negara A bisa membuat 100 kain atau 50 anggur, biaya peluang 1 anggur adalah?",
            options: ["2 kain", "0,5 kain", "50 kain", "100 kain"],
            answer: 0,
            explain: "100 dibagi 50 sama dengan 2 kain yang dikorbankan per anggur.",
          },
        ],
      },
    ],
  },
];
