import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "adam-smith-mazhab-klasik",
    levelId: "klasik",
    order: 1,
    title: "Adam Smith & Mazhab Klasik",
    summary: "Kelahiran ilmu ekonomi: tangan tak tampak, pembagian kerja, dan gagasan pasar bebas yang menata kepentingan pribadi menjadi kemakmuran.",
    durationMin: 14,
    tags: ["Adam Smith", "klasik", "tangan tak tampak", "pasar bebas"],
    blocks: [
      {
        type: "paragraph",
        html: "Pada 1776, <strong>Adam Smith</strong> menerbitkan <em>The Wealth of Nations</em>, buku yang menandai kelahiran ilmu ekonomi. Gagasan intinya: dalam pasar bebas, individu yang mengejar kepentingannya sendiri sering kali, seolah dituntun <strong>tangan tak tampak</strong>, menghasilkan kemakmuran bagi masyarakat luas.",
      },
      {
        type: "video",
        comp: "TanganTakTampak",
        title: "Video: Tangan Tak Tampak",
        caption: "Bagaimana kepentingan pribadi di pasar bebas bisa menata kemakmuran bersama.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Adam_Smith_The_Muir_portrait.jpg?width=400",
        alt: "Potret Adam Smith",
        caption: "Adam Smith (1723-1790), bapak ilmu ekonomi modern, penulis The Wealth of Nations (1776).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua gagasan besar Smith",
        html: "<strong>Tangan tak tampak:</strong> pasar mengoordinasikan jutaan keputusan tanpa komando pusat. <strong>Pembagian kerja:</strong> memecah pekerjaan menjadi tahap-tahap khusus melipatgandakan produktivitas, seperti contohnya pada pabrik peniti.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tokoh klasik lain",
        html: "<strong>Thomas Malthus:</strong> populasi tumbuh lebih cepat dari pangan. <strong>David Ricardo:</strong> keunggulan komparatif dan teori sewa. <strong>Jean-Baptiste Say:</strong> penawaran menciptakan permintaannya sendiri. <strong>John Stuart Mill:</strong> menyempurnakan dan memberi wajah sosial pada ekonomi klasik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana pasar bebas mengoordinasikan keputusan lewat mekanisme tangan tak tampak.",
      },
      { type: "widget", widget: "SimulatorTanganTakTampak" },
      {
        type: "chart",
        variant: "bar",
        title: "Pembagian Kerja Melipatgandakan Produktivitas (ilustrasi Smith)",
        unit: "peniti per pekerja per hari",
        source: "ilustrasi contoh pabrik peniti dalam The Wealth of Nations",
        note: "Smith mencontohkan bahwa satu pekerja sendiri hampir tak menghasilkan peniti, tetapi lewat pembagian kerja produktivitas melonjak drastis.",
        data: [
          { label: "Kerja sendiri", value: 20, color: "#fb7185" },
          { label: "Dengan pembagian kerja", value: 4800, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik peniti",
        html: "Smith mengamati bahwa satu orang yang membuat peniti sendirian dari awal sampai akhir mungkin hanya menghasilkan beberapa peniti sehari. Tetapi ketika pekerjaan dipecah menjadi 18 tahap khusus (menarik kawat, meluruskan, memotong, meruncingkan, dan seterusnya), sepuluh pekerja bisa menghasilkan <strong>sekitar 48.000 peniti sehari</strong>. Inilah kekuatan <strong>pembagian kerja</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Sepuluh pekerja menghasilkan 48.000 peniti sehari lewat pembagian kerja. Berapa rata-rata peniti per pekerja per hari?",
        answer: 4800,
        tolerance: 0,
        solution: "48.000 / 10 = <strong>4.800 peniti per pekerja</strong>, jauh di atas jika bekerja sendiri-sendiri.",
        hint: "Bagi total peniti dengan jumlah pekerja.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh klasik dengan gagasannya.",
        pairs: [
          { left: "Adam Smith", right: "Tangan tak tampak & pembagian kerja" },
          { left: "Thomas Malthus", right: "Populasi vs pangan" },
          { left: "David Ricardo", right: "Keunggulan komparatif" },
          { left: "Jean-Baptiste Say", right: "Penawaran menciptakan permintaan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: The Wealth of Nations 1776",
        html: "<strong>The Wealth of Nations</strong> terbit pada <strong>1776</strong>, tahun yang sama dengan Deklarasi Kemerdekaan Amerika. Buku ini menyerang merkantilisme dan proteksionisme, serta membela perdagangan bebas dan pasar. Pengaruhnya begitu besar sehingga Adam Smith dikenang sebagai <strong>bapak ilmu ekonomi</strong>, dan gagasannya masih diperdebatkan sampai hari ini.",
      },
      {
        type: "takeaways",
        items: [
          "Ilmu ekonomi lahir lewat The Wealth of Nations (Adam Smith, 1776).",
          "Tangan tak tampak: pasar mengoordinasikan tanpa komando pusat.",
          "Pembagian kerja melipatgandakan produktivitas.",
          "Tokoh klasik lain: Malthus, Ricardo, Say, dan Mill.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Siapa yang dikenal sebagai bapak ilmu ekonomi?",
            options: ["Karl Marx", "Adam Smith", "John Keynes", "David Ricardo"],
            answer: 1,
            explain: "Adam Smith, lewat The Wealth of Nations (1776).",
          },
          {
            q: "Tangan tak tampak menggambarkan?",
            options: [
              "Campur tangan negara",
              "Pasar mengoordinasikan keputusan tanpa komando pusat",
              "Perencanaan terpusat",
              "Larangan dagang",
            ],
            answer: 1,
            explain: "Kepentingan pribadi di pasar bebas dapat menghasilkan kemakmuran bersama.",
          },
          {
            q: "Pembagian kerja menurut Smith?",
            options: ["Menurunkan produktivitas", "Melipatgandakan produktivitas", "Tidak berpengaruh", "Menghapus perdagangan"],
            answer: 1,
            explain: "Memecah pekerjaan jadi tahap khusus melipatgandakan hasil (contoh pabrik peniti).",
          },
          {
            q: "David Ricardo terkenal dengan gagasan?",
            options: ["Tangan tak tampak", "Keunggulan komparatif", "Permintaan agregat", "Utilitas marginal"],
            answer: 1,
            explain: "Ricardo merumuskan keunggulan komparatif dan teori sewa.",
          },
          {
            q: "The Wealth of Nations terbit pada tahun?",
            options: ["1776", "1867", "1936", "1690"],
            answer: 0,
            explain: "Terbit 1776, tahun yang sama dengan Deklarasi Kemerdekaan AS.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "adam-smith-lebih-dalam",
    levelId: "klasik",
    order: 2,
    title: "Adam Smith: Lebih dari Tangan Tak Tampak",
    summary: "Sebelum menulis ekonomi, Smith adalah filsuf moral. The Theory of Moral Sentiments melengkapi The Wealth of Nations: kepentingan pribadi selalu dibingkai empati dan aturan main.",
    durationMin: 14,
    tags: ["Adam Smith", "moral", "simpati", "peran negara"],
    blocks: [
      {
        type: "paragraph",
        html: "Banyak orang mengira Adam Smith hanya pembela egoisme pasar. Padahal karya besarnya yang pertama, <em>The Theory of Moral Sentiments</em> (1759), justru tentang <strong>empati</strong> dan <strong>simpati</strong>. Bagi Smith, manusia tidak semata makhluk serakah, melainkan makhluk yang membayangkan penilaian orang lain lewat sosok <strong>penonton yang tidak memihak</strong> (impartial spectator) di dalam dirinya.",
      },
      {
        type: "paragraph",
        html: "Kedua bukunya saling melengkapi: <em>Moral Sentiments</em> menjelaskan bagaimana masyarakat menahan diri lewat moral, sedangkan <em>The Wealth of Nations</em> (1776) menjelaskan bagaimana kepentingan pribadi, di dalam bingkai keadilan dan hukum, menghasilkan kemakmuran. Kepentingan pribadi bukan berarti bebas tanpa batas.",
      },
      {
        type: "video",
        comp: "TanganTakTampak",
        title: "Video: Tangan Tak Tampak",
        caption: "Kepentingan pribadi menata kemakmuran, tetapi selalu di dalam bingkai aturan dan moral.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Adam_Smith_The_Muir_portrait.jpg?width=400",
        alt: "Potret Adam Smith",
        caption: "Adam Smith (1723-1790).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kepentingan pribadi dalam bingkai moral",
        html: "Kalimat Smith yang terkenal: kita mendapat makan malam bukan dari kebaikan hati tukang daging, melainkan dari kepentingan dirinya. Namun bagi Smith kepentingan itu hanya menghasilkan kebaikan bila dibatasi <strong>keadilan</strong>, <strong>hukum</strong>, dan rasa <strong>simpati</strong> antarmanusia.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga fungsi negara menurut Smith",
        html: "Smith bukan penganjur negara nol. Ia menyebut tiga tugas pokok negara: <strong>(1) pertahanan</strong> dari serangan luar, <strong>(2) keadilan</strong> (peradilan dan perlindungan hak), dan <strong>(3) barang publik</strong> serta infrastruktur yang tidak menguntungkan bila diserahkan ke swasta, seperti jalan, jembatan, dan pendidikan dasar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana pasar mengoordinasikan keputusan, lalu bayangkan apa yang terjadi bila keadilan dan aturan main tidak ada.",
      },
      { type: "widget", widget: "SimulatorTanganTakTampak" },
      {
        type: "chart",
        variant: "bar",
        title: "Dua Sisi Pemikiran Adam Smith",
        unit: "tahun terbit",
        source: "sejarah penerbitan karya Adam Smith",
        note: "Moral Sentiments (1759) mendahului The Wealth of Nations (1776) selama 17 tahun; keduanya adalah satu paket pemikiran.",
        data: [
          { label: "Moral Sentiments (moral/empati)", value: 1759, color: "#a78bfa" },
          { label: "Wealth of Nations (ekonomi)", value: 1776, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tukang roti dan aturan main",
        html: "Seorang tukang roti menjual roti demi keuntungan, bukan demi cinta pada pelanggan. Tetapi ia tidak boleh mencampur tepung dengan bahan berbahaya, tidak boleh menipu timbangan, dan harus menepati kontrak. <strong>Keadilan dan hukum</strong> inilah yang membuat kepentingan pribadi berubah menjadi kebaikan bersama. Tanpa fungsi negara ketiga (menegakkan keadilan), pasar Smith tidak akan bekerja.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan berikut sesuai karya Adam Smith yang membahasnya.",
        buckets: ["Moral Sentiments", "Wealth of Nations"],
        items: [
          { text: "Empati dan penonton yang tidak memihak", bucket: "Moral Sentiments" },
          { text: "Pembagian kerja di pabrik peniti", bucket: "Wealth of Nations" },
          { text: "Simpati sebagai dasar penilaian moral", bucket: "Moral Sentiments" },
          { text: "Tangan tak tampak di pasar", bucket: "Wealth of Nations" },
          { text: "Manusia menahan diri karena membayangkan penilaian orang lain", bucket: "Moral Sentiments" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Berapa selisih tahun antara terbitnya The Theory of Moral Sentiments (1759) dan The Wealth of Nations (1776)?",
        answer: 17,
        tolerance: 0,
        suffix: " tahun",
        solution: "1776 - 1759 = <strong>17 tahun</strong>. Smith mengembangkan pemikiran ekonominya setelah membangun landasan moralnya.",
        hint: "Kurangkan tahun yang lebih awal dari yang lebih akhir.",
      },
      {
        type: "case",
        title: "Sejarah: The Theory of Moral Sentiments 1759",
        html: "<strong>The Theory of Moral Sentiments</strong> terbit pada <strong>1759</strong>, saat Smith mengajar filsafat moral di Universitas Glasgow. Buku ini membuatnya terkenal di Eropa jauh sebelum ia menulis ekonomi. Smith terus merevisinya sepanjang hidup, dengan edisi keenam terbit pada 1790, tahun ia wafat. Ini membuktikan bahwa dimensi moral tidak pernah ia tinggalkan.",
      },
      {
        type: "takeaways",
        items: [
          "Adam Smith adalah filsuf moral sebelum menjadi ekonom.",
          "The Theory of Moral Sentiments (1759) menekankan empati dan simpati.",
          "Kepentingan pribadi hanya bermanfaat dalam bingkai keadilan dan hukum.",
          "Smith mengakui tiga fungsi negara: pertahanan, keadilan, dan barang publik.",
          "Kedua karyanya adalah satu kesatuan pemikiran, bukan bertentangan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Karya Adam Smith yang membahas empati dan simpati adalah?",
            options: ["The Wealth of Nations", "The Theory of Moral Sentiments", "Das Kapital", "Principles of Economics"],
            answer: 1,
            explain: "The Theory of Moral Sentiments (1759) adalah karya filsafat moral Smith.",
          },
          {
            q: "Menurut Smith, kepentingan pribadi menghasilkan kebaikan bersama bila?",
            options: [
              "Dibiarkan tanpa batas",
              "Dibingkai keadilan dan hukum",
              "Diganti perencanaan negara",
              "Dihapus sama sekali",
            ],
            answer: 1,
            explain: "Tanpa keadilan dan hukum, kepentingan pribadi bisa merugikan orang lain.",
          },
          {
            q: "Manakah yang BUKAN termasuk tiga fungsi negara menurut Smith?",
            options: ["Pertahanan", "Keadilan", "Menetapkan harga semua barang", "Barang publik"],
            answer: 2,
            explain: "Smith menyebut pertahanan, keadilan, dan barang publik, bukan penetapan harga.",
          },
          {
            q: "Sosok internal yang menurut Smith menilai tindakan kita disebut?",
            options: ["Tangan tak tampak", "Penonton yang tidak memihak", "Homo economicus", "Leviathan"],
            answer: 1,
            explain: "Impartial spectator, penonton yang tidak memihak, menilai moralitas tindakan kita.",
          },
          {
            q: "The Theory of Moral Sentiments terbit pada tahun?",
            options: ["1759", "1776", "1798", "1817"],
            answer: 0,
            explain: "Terbit 1759, tujuh belas tahun sebelum The Wealth of Nations.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "malthus-populasi",
    levelId: "klasik",
    order: 3,
    title: "Malthus: Populasi vs Pangan",
    summary: "Populasi cenderung tumbuh berlipat (geometris), sedangkan pangan hanya bertambah bertahap (aritmetis). Malthus meramalkan tekanan kemiskinan abadi, ramalan yang kelak dipatahkan teknologi.",
    durationMin: 14,
    tags: ["Malthus", "populasi", "pangan", "dismal science"],
    blocks: [
      {
        type: "paragraph",
        html: "Pada 1798, pendeta dan ekonom Inggris <strong>Thomas Robert Malthus</strong> menulis bahwa manusia menghadapi jebakan mendasar: <strong>populasi cenderung tumbuh secara geometris</strong> (2, 4, 8, 16), sedangkan <strong>produksi pangan hanya tumbuh secara aritmetis</strong> (1, 2, 3, 4). Bila keduanya berbeda kecepatan, cepat atau lambat jumlah mulut akan melampaui jumlah makanan.",
      },
      {
        type: "paragraph",
        html: "Akibatnya, menurut Malthus, kemiskinan dan kelaparan bukan kecelakaan, melainkan hasil hukum alam. Ketika populasi tumbuh terlalu cepat, kelaparan, wabah, dan perang akan menekannya kembali. Pandangan suram inilah yang membuat ekonomi dijuluki <strong>ilmu yang muram</strong> (the dismal science).",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Robert_Malthus_Wellcome_L0069037_-crop.jpg?width=400",
        alt: "Potret Thomas Malthus",
        caption: "Thomas Robert Malthus (1766-1834).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Malthus dan para pemikir klasik lain dalam alur sejarah ekonomi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Inti ramalan Malthus",
        html: "<strong>Deret geometris</strong> (1, 2, 4, 8, 16) melipatgandakan diri tiap periode, sedangkan <strong>deret aritmetis</strong> (1, 2, 3, 4, 5) hanya bertambah tetap. Jarak keduanya melebar tanpa batas, sehingga populasi selalu cenderung menekan batas pangan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Mengapa disebut ilmu yang muram",
        html: "Ramalan Malthus menyiratkan bahwa perbaikan upah pekerja akan sia-sia: begitu hidup membaik, orang punya lebih banyak anak, populasi naik, dan upah kembali tertekan ke batas subsisten. Kesimpulan pahit inilah yang membuat Thomas Carlyle menjuluki ekonomi <strong>the dismal science</strong>.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana harga bergeser saat penawaran (pangan) langka dibanding permintaan (mulut yang harus diberi makan).",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "line",
        title: "Geometris vs Aritmetis: Mengapa Malthus Cemas",
        unit: "indeks (mulai dari 1)",
        source: "ilustrasi model Malthus (An Essay on the Principle of Population, 1798)",
        note: "Populasi (geometris) melejit menjauhi pangan (aritmetis); di titik perpotongan itulah Malthus melihat kelaparan mulai menekan.",
        data: [
          { label: "Periode 1", value: 1 },
          { label: "Periode 2", value: 2 },
          { label: "Periode 3", value: 4 },
          { label: "Periode 4", value: 8 },
          { label: "Periode 5", value: 16 },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ramalan Malthus vs Kenyataan: Produksi Pangan Dunia",
        unit: "indeks produksi pangan (1961 = 100)",
        source: "FAO, indeks produksi pangan dunia (angka pembulatan)",
        note: "Berlawanan dengan ramalan Malthus, produksi pangan justru meningkat berlipat berkat revolusi hijau dan teknologi pertanian.",
        data: [
          { label: "1961", value: 100, color: "#fb7185" },
          { label: "1990", value: 200, color: "#fbbf24" },
          { label: "2020", value: 350, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Revolusi hijau mematahkan ramalan",
        html: "Malthus tidak memperhitungkan lompatan teknologi. Pada pertengahan abad ke-20, <strong>revolusi hijau</strong> menghadirkan bibit unggul, pupuk, irigasi, dan mekanisasi. Hasilnya, produksi pangan dunia tumbuh jauh lebih cepat daripada populasi. Meski jumlah manusia meningkat dari sekitar 1 miliar pada zaman Malthus menjadi lebih dari 8 miliar hari ini, porsi penduduk dunia yang kelaparan justru turun drastis. Faktor yang diabaikan Malthus, yakni <strong>kemajuan teknologi</strong>, mengubah deret aritmetis pangan menjadi jauh lebih curam.",
      },
      {
        type: "calcExercise",
        prompt: "Populasi tumbuh geometris: 1, 2, 4, 8, ... Berapa nilainya pada periode ke-5 jika periode ke-1 bernilai 1?",
        answer: 16,
        tolerance: 0,
        solution: "Deret geometris berkelipatan 2: periode 1=1, 2=2, 3=4, 4=8, 5=<strong>16</strong>. Bandingkan dengan pangan aritmetis yang di periode ke-5 baru bernilai 5.",
        hint: "Kalikan dua setiap periode, mulai dari 1.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pertumbuhan berikut sebagai geometris atau aritmetis.",
        buckets: ["Geometris", "Aritmetis"],
        items: [
          { text: "1, 2, 4, 8, 16 (kelipatan tetap)", bucket: "Geometris" },
          { text: "1, 2, 3, 4, 5 (selisih tetap)", bucket: "Aritmetis" },
          { text: "Ramalan Malthus untuk populasi", bucket: "Geometris" },
          { text: "Ramalan Malthus untuk pangan", bucket: "Aritmetis" },
          { text: "3, 6, 12, 24 (berlipat dua)", bucket: "Geometris" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: An Essay on the Principle of Population 1798",
        html: "<strong>An Essay on the Principle of Population</strong> terbit pada <strong>1798</strong>, awalnya tanpa nama penulis. Malthus menulisnya untuk membantah optimisme para pemikir Pencerahan seperti William Godwin dan Condorcet yang percaya masyarakat akan terus membaik tanpa batas. Buku ini sangat berpengaruh, bahkan kelak mengilhami <strong>Charles Darwin</strong> yang membaca gagasan Malthus tentang perebutan sumber daya saat merumuskan teori seleksi alam.",
      },
      {
        type: "takeaways",
        items: [
          "Malthus: populasi tumbuh geometris, pangan tumbuh aritmetis.",
          "Ramalannya: kemiskinan dan kelaparan menekan populasi kembali ke batas subsisten.",
          "Pandangan suram ini memberi ekonomi julukan the dismal science.",
          "Teknologi dan revolusi hijau mematahkan ramalan Malthus.",
          "Gagasan Malthus mengilhami teori seleksi alam Darwin.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Malthus, populasi tumbuh secara?",
            options: ["Aritmetis", "Geometris", "Tetap", "Menurun"],
            answer: 1,
            explain: "Populasi tumbuh geometris (berlipat), sedangkan pangan hanya aritmetis.",
          },
          {
            q: "Produksi pangan menurut Malthus tumbuh secara?",
            options: ["Geometris", "Eksponensial", "Aritmetis", "Berlipat ganda"],
            answer: 2,
            explain: "Pangan hanya bertambah bertahap (aritmetis), lebih lambat dari populasi.",
          },
          {
            q: "Julukan the dismal science muncul karena?",
            options: [
              "Ekonomi terlalu rumit",
              "Ramalan Malthus yang suram tentang kemiskinan abadi",
              "Ekonomi tidak ilmiah",
              "Ekonomi membosankan",
            ],
            answer: 1,
            explain: "Kesimpulan pahit Malthus membuat Carlyle menjuluki ekonomi ilmu yang muram.",
          },
          {
            q: "Apa yang mematahkan ramalan Malthus?",
            options: ["Perang dunia", "Kemajuan teknologi dan revolusi hijau", "Penurunan populasi", "Larangan pernikahan"],
            answer: 1,
            explain: "Teknologi pertanian membuat pangan tumbuh jauh lebih cepat dari perkiraan Malthus.",
          },
          {
            q: "An Essay on the Principle of Population terbit pada tahun?",
            options: ["1776", "1798", "1817", "1848"],
            answer: 1,
            explain: "Terbit 1798, membantah optimisme Godwin dan Condorcet.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ricardo-keunggulan-komparatif",
    levelId: "klasik",
    order: 4,
    title: "Ricardo: Keunggulan Komparatif",
    summary: "David Ricardo menunjukkan bahwa dua negara tetap untung berdagang selama mereka berspesialisasi pada barang dengan biaya peluang terendah, meski satu negara lebih unggul dalam segala hal.",
    durationMin: 15,
    tags: ["Ricardo", "keunggulan komparatif", "perdagangan", "biaya peluang"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>David Ricardo</strong> menyempurnakan gagasan perdagangan bebas Adam Smith dengan satu ide yang mengejutkan: dua negara tetap saling untung berdagang <strong>meski satu negara lebih efisien dalam memproduksi segala barang</strong>. Kuncinya bukan keunggulan mutlak, melainkan <strong>keunggulan komparatif</strong>, yaitu memproduksi barang dengan <strong>biaya peluang</strong> paling rendah.",
      },
      {
        type: "paragraph",
        html: "Biaya peluang adalah barang yang dikorbankan saat kita memilih memproduksi barang lain. Menurut Ricardo, setiap negara sebaiknya berspesialisasi pada barang yang pengorbanannya paling kecil, lalu berdagang. Dengan begitu, total produksi dunia naik dan kedua belah pihak menikmati lebih banyak barang daripada bila mencoba memproduksi semuanya sendiri.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_David_Ricardo_by_Thomas_Phillips.jpg?width=400",
        alt: "Potret David Ricardo",
        caption: "David Ricardo (1772-1823).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "KeunggulanKomparatif",
        title: "Video: Keunggulan Komparatif",
        caption: "Mengapa spesialisasi dan perdagangan menguntungkan kedua negara.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Contoh klasik Inggris vs Portugal",
        html: "Ricardo memakai contoh <strong>kain</strong> dan <strong>anggur</strong>. Portugal lebih efisien memproduksi keduanya, tetapi keunggulannya di anggur lebih besar. Maka Portugal sebaiknya spesialisasi <strong>anggur</strong> dan Inggris spesialisasi <strong>kain</strong>, lalu keduanya berdagang. Hasilnya, kedua negara menikmati lebih banyak kain dan anggur.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Teori sewa tanah (rent)",
        html: "Ricardo juga terkenal dengan <strong>teori sewa</strong>: sewa muncul karena tanah berbeda kesuburannya. Saat kebutuhan pangan naik, tanah kurang subur ikut digarap, dan selisih hasil antara tanah subur dan tanah marjinal menjadi <strong>sewa</strong> bagi pemilik tanah subur. Ini menjelaskan mengapa pemilik tanah diuntungkan saat harga pangan tinggi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser produktivitas tiap negara dan lihat pola spesialisasi serta keuntungan dagang yang muncul.",
      },
      { type: "widget", widget: "SimulatorKeunggulanKomparatif" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Tenaga Kerja (jam) untuk 1 Unit Barang: Inggris vs Portugal",
        unit: "jam kerja per unit",
        source: "ilustrasi angka contoh Ricardo (On the Principles of Political Economy and Taxation, 1817)",
        note: "Portugal lebih efisien pada keduanya, tetapi keunggulan komparatifnya paling besar pada anggur, sehingga ia sebaiknya spesialisasi anggur.",
        data: [
          { label: "Kain (Inggris)", value: 100, color: "#60a5fa" },
          { label: "Kain (Portugal)", value: 90, color: "#a78bfa" },
          { label: "Anggur (Inggris)", value: 120, color: "#fb7185" },
          { label: "Anggur (Portugal)", value: 80, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung biaya peluang",
        html: "Di Inggris, 1 unit anggur butuh 120 jam dan 1 unit kain 100 jam, sehingga biaya peluang 1 anggur = 120/100 = <strong>1,2 kain</strong>. Di Portugal, 1 anggur butuh 80 jam dan 1 kain 90 jam, sehingga 1 anggur = 80/90 = <strong>0,89 kain</strong>. Karena biaya peluang anggur lebih murah di Portugal (0,89 &lt; 1,2), Portugal berspesialisasi anggur dan Inggris kain. Meski Portugal unggul mutlak di keduanya, perdagangan tetap menguntungkan kedua negara.",
      },
      {
        type: "calcExercise",
        prompt: "Di Inggris, 1 unit anggur butuh 120 jam dan 1 unit kain butuh 100 jam. Berapa biaya peluang 1 unit anggur dalam satuan kain?",
        answer: 1.2,
        tolerance: 0.05,
        suffix: " kain",
        solution: "Biaya peluang 1 anggur = 120 / 100 = <strong>1,2 kain</strong>. Artinya membuat 1 anggur di Inggris berarti mengorbankan 1,2 kain.",
        hint: "Bagi jam untuk anggur dengan jam untuk kain.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya dalam teori Ricardo.",
        pairs: [
          { left: "Keunggulan komparatif", right: "Produksi dengan biaya peluang terendah" },
          { left: "Keunggulan mutlak", right: "Produksi dengan sumber daya paling sedikit" },
          { left: "Biaya peluang", right: "Barang yang dikorbankan untuk memproduksi barang lain" },
          { left: "Sewa (rent)", right: "Selisih hasil tanah subur dan tanah marjinal" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Principles of Political Economy and Taxation 1817",
        html: "<strong>On the Principles of Political Economy and Taxation</strong> terbit pada <strong>1817</strong>. Di dalamnya Ricardo merumuskan keunggulan komparatif, teori sewa, dan teori nilai kerja. Ricardo, seorang pialang saham yang kaya raya, juga terlibat dalam perdebatan <strong>Corn Laws</strong>, hukum yang membatasi impor gandum ke Inggris. Ia menentang proteksi tersebut karena hanya menguntungkan pemilik tanah dan merugikan konsumen serta industri. Corn Laws akhirnya dicabut pada 1846.",
      },
      {
        type: "takeaways",
        items: [
          "Keunggulan komparatif: berdagang berdasarkan biaya peluang terendah.",
          "Perdagangan menguntungkan meski satu negara unggul mutlak dalam segala hal.",
          "Contoh klasik: Inggris (kain) dan Portugal (anggur).",
          "Teori sewa: sewa muncul dari perbedaan kesuburan tanah.",
          "Ricardo menentang Corn Laws yang proteksionis.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Keunggulan komparatif berarti memproduksi barang dengan?",
            options: ["Keunggulan mutlak terbesar", "Biaya peluang terendah", "Harga jual tertinggi", "Tenaga kerja terbanyak"],
            answer: 1,
            explain: "Spesialisasi pada barang dengan biaya peluang paling rendah menguntungkan kedua negara.",
          },
          {
            q: "Menurut Ricardo, dua negara sebaiknya berdagang jika?",
            options: [
              "Hanya bila satu unggul mutlak",
              "Selama biaya peluangnya berbeda",
              "Hanya bila keduanya sama efisien",
              "Tidak pernah menguntungkan",
            ],
            answer: 1,
            explain: "Selama biaya peluang berbeda, spesialisasi dan perdagangan menaikkan total produksi.",
          },
          {
            q: "Dalam contoh Ricardo, Portugal sebaiknya berspesialisasi pada?",
            options: ["Kain", "Anggur", "Keduanya", "Tidak berspesialisasi"],
            answer: 1,
            explain: "Biaya peluang anggur lebih rendah di Portugal, sehingga ia spesialisasi anggur.",
          },
          {
            q: "Teori sewa Ricardo menjelaskan bahwa sewa muncul dari?",
            options: ["Jumlah uang beredar", "Perbedaan kesuburan tanah", "Tingkat upah", "Suku bunga"],
            answer: 1,
            explain: "Selisih hasil antara tanah subur dan tanah marjinal menjadi sewa.",
          },
          {
            q: "Principles of Political Economy and Taxation terbit pada tahun?",
            options: ["1776", "1798", "1817", "1867"],
            answer: 2,
            explain: "Terbit 1817, memuat keunggulan komparatif dan teori sewa.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "hukum-say",
    levelId: "klasik",
    order: 5,
    title: "Hukum Say: Penawaran & Permintaan",
    summary: "Jean-Baptiste Say merumuskan bahwa penawaran menciptakan permintaannya sendiri. Gagasan ini melahirkan debat sengit dengan Malthus soal general glut, dan kelak ditantang oleh Keynes.",
    durationMin: 14,
    tags: ["Say", "hukum Say", "penawaran", "permintaan"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonom Prancis <strong>Jean-Baptiste Say</strong> merumuskan prinsip yang dikenal sebagai <strong>Hukum Say</strong>: <em>penawaran menciptakan permintaannya sendiri</em>. Maksudnya, tindakan memproduksi barang sekaligus menciptakan pendapatan (upah, sewa, laba) yang persis cukup untuk membeli barang yang diproduksi. Dengan kata lain, produksi adalah sumber permintaan.",
      },
      {
        type: "paragraph",
        html: "Konsekuensinya, menurut para pengikut klasik, tidak mungkin terjadi <strong>kelebihan produksi menyeluruh</strong> (general glut) yang berkepanjangan. Bila satu barang berlebih, barang lain pasti kekurangan, dan pasar akan menyesuaikan diri lewat harga. Perekonomian selalu cenderung kembali ke keseimbangan dengan tenaga kerja penuh.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Hukum Say dalam perdebatan panjang tentang keseimbangan pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Inti Hukum Say",
        html: "<strong>Penawaran menciptakan permintaannya sendiri.</strong> Setiap barang yang diproduksi menghasilkan pendapatan senilai barang itu, dan pendapatan itu akan dibelanjakan untuk barang lain. Uang hanyalah perantara pertukaran, bukan tujuan akhir.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Debat general glut dengan Malthus",
        html: "<strong>Malthus tidak setuju.</strong> Ia berpendapat bahwa masyarakat bisa mengalami <strong>kelebihan produksi menyeluruh</strong> karena permintaan tidak cukup: orang bisa menimbun uang alih-alih membelanjakannya. Debat Say vs Malthus di awal abad ke-19 ini menjadi cikal bakal perdebatan besar tentang resesi dan pengangguran.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser penawaran dan permintaan, amati bagaimana harga bergerak menuju titik keseimbangan seperti yang diyakini para ekonom klasik.",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "line",
        title: "Keseimbangan Pasar: Titik Temu Penawaran & Permintaan",
        unit: "harga (ilustrasi)",
        source: "ilustrasi kurva penawaran dan permintaan (model klasik)",
        note: "Dalam pandangan klasik, harga selalu bergerak menuju titik keseimbangan sehingga tidak ada kelebihan produksi permanen.",
        data: [
          { label: "Kuantitas rendah", value: 90, color: "#fb7185" },
          { label: "Mendekati seimbang", value: 60, color: "#fbbf24" },
          { label: "Titik keseimbangan", value: 50, color: "#34d399" },
          { label: "Kelebihan pasok", value: 40, color: "#60a5fa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tukang sepatu dan tukang roti",
        html: "Bayangkan seorang tukang sepatu membuat sepatu senilai Rp500.000. Uang yang ia terima dari menjual sepatu itu ia pakai membeli roti, pakaian, dan jasa lain. Dengan memproduksi sepatu, ia menciptakan <strong>daya beli</strong> senilai Rp500.000 untuk barang orang lain. Bila setiap produsen berlaku sama, total produksi menciptakan total permintaan yang seimbang. Inilah logika Hukum Say: <strong>produksi membiayai konsumsi</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Seorang produsen membuat barang senilai Rp500.000 dan membelanjakan seluruh pendapatannya. Berapa rupiah daya beli baru yang ia ciptakan untuk barang orang lain?",
        answer: 500000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Menurut Hukum Say, memproduksi barang Rp500.000 menciptakan pendapatan Rp500.000 yang dibelanjakan penuh, jadi <strong>Rp500.000</strong> daya beli baru.",
        hint: "Penawaran menciptakan permintaan senilai barang yang diproduksi.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan sesuai pihak yang mendukungnya dalam debat general glut.",
        buckets: ["Say (klasik)", "Malthus (kritik)"],
        items: [
          { text: "Penawaran menciptakan permintaannya sendiri", bucket: "Say (klasik)" },
          { text: "Bisa terjadi kelebihan produksi menyeluruh", bucket: "Malthus (kritik)" },
          { text: "Orang bisa menimbun uang, bukan membelanjakannya", bucket: "Malthus (kritik)" },
          { text: "Pasar selalu cenderung ke tenaga kerja penuh", bucket: "Say (klasik)" },
          { text: "Uang hanya perantara pertukaran", bucket: "Say (klasik)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Say's Law awal abad ke-19",
        html: "Jean-Baptiste Say memaparkan gagasannya dalam <strong>Traite d'economie politique</strong> (1803). Selama lebih dari satu abad, <strong>Hukum Say</strong> menjadi tiang penyangga ekonomi klasik. Namun pada 1936, di tengah <strong>Depresi Besar</strong> yang menunjukkan pengangguran massal dan kelebihan kapasitas, <strong>John Maynard Keynes</strong> menyerang Hukum Say dalam <em>The General Theory</em>. Keynes berpendapat bahwa permintaan agregat bisa terlalu rendah sehingga ekonomi terjebak dalam pengangguran, membenarkan kekhawatiran Malthus lebih dari seabad sebelumnya.",
      },
      {
        type: "takeaways",
        items: [
          "Hukum Say: penawaran menciptakan permintaannya sendiri.",
          "Produksi menciptakan pendapatan yang cukup untuk membeli barang yang diproduksi.",
          "Klasik meyakini tidak ada kelebihan produksi menyeluruh yang permanen.",
          "Malthus menantangnya dengan gagasan general glut.",
          "Keynes kelak mematahkan Hukum Say pada 1936 lewat The General Theory.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti Hukum Say adalah?",
            options: [
              "Permintaan menciptakan penawaran",
              "Penawaran menciptakan permintaannya sendiri",
              "Uang adalah tujuan akhir",
              "Pemerintah harus mengatur harga",
            ],
            answer: 1,
            explain: "Produksi menciptakan pendapatan yang menjadi permintaan atas barang lain.",
          },
          {
            q: "Menurut Hukum Say, kelebihan produksi menyeluruh yang permanen?",
            options: ["Selalu terjadi", "Tidak mungkin terjadi", "Disebabkan pemerintah", "Menguntungkan"],
            answer: 1,
            explain: "Bila satu barang berlebih, barang lain kekurangan; pasar menyesuaikan lewat harga.",
          },
          {
            q: "Siapa yang menantang Hukum Say dengan gagasan general glut?",
            options: ["David Ricardo", "Thomas Malthus", "Adam Smith", "John Stuart Mill"],
            answer: 1,
            explain: "Malthus berpendapat masyarakat bisa mengalami kelebihan produksi menyeluruh.",
          },
          {
            q: "Tokoh yang mematahkan Hukum Say pada 1936 adalah?",
            options: ["Karl Marx", "John Maynard Keynes", "Milton Friedman", "Jean-Baptiste Say"],
            answer: 1,
            explain: "Keynes menyerang Hukum Say dalam The General Theory (1936).",
          },
          {
            q: "Dalam Hukum Say, uang berperan sebagai?",
            options: ["Tujuan akhir", "Perantara pertukaran", "Komoditas utama", "Alat spekulasi"],
            answer: 1,
            explain: "Uang hanya perantara; orang memproduksi untuk pada akhirnya membeli barang lain.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "john-stuart-mill",
    levelId: "klasik",
    order: 6,
    title: "John Stuart Mill: Penyempurna Klasik",
    summary: "Mill memisahkan hukum produksi dari hukum distribusi. Produksi tunduk pada hukum alam, tetapi distribusi adalah pilihan masyarakat yang bisa diubah, membuka pintu reformasi sosial tanpa meninggalkan pasar.",
    durationMin: 15,
    tags: ["Mill", "distribusi", "reformasi sosial", "kebebasan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>John Stuart Mill</strong> adalah tokoh yang menyempurnakan dan memberi wajah manusiawi pada ekonomi klasik. Gagasannya yang paling berpengaruh: memisahkan <strong>hukum produksi</strong> dari <strong>hukum distribusi</strong>. Menurut Mill, cara barang <em>diproduksi</em> tunduk pada hukum alam dan teknologi yang tidak bisa kita ubah sesuka hati. Tetapi cara barang <em>dibagi</em> di antara manusia adalah <strong>pilihan masyarakat</strong>, bukan takdir.",
      },
      {
        type: "paragraph",
        html: "Pembedaan ini penting. Bila distribusi hanya soal aturan dan kelembagaan buatan manusia, maka masyarakat berhak mengubahnya lewat pajak, warisan, dan kebijakan sosial untuk mengurangi ketimpangan, tanpa harus membongkar mekanisme pasar. Mill membuka jalan bagi <strong>reformasi sosial</strong> di dalam kerangka ekonomi pasar.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/John_Stuart_Mill_by_London_Stereoscopic_Company,_c1870.jpg?width=400",
        alt: "Potret John Stuart Mill",
        caption: "John Stuart Mill (1806-1873).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Mill sebagai jembatan antara ekonomi klasik dan pemikiran reformis.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Produksi vs distribusi",
        html: "<strong>Hukum produksi</strong> ditentukan alam dan teknologi (tidak bisa kita ubah). <strong>Hukum distribusi</strong> ditentukan lembaga dan kebiasaan manusia (bisa kita ubah). Inilah dasar Mill untuk membenarkan reformasi sosial tanpa menolak pasar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kebebasan individu",
        html: "Dalam <em>On Liberty</em> (1859), Mill membela <strong>kebebasan individu</strong> lewat prinsip kerugian (harm principle): negara hanya boleh membatasi kebebasan seseorang untuk mencegah kerugian pada orang lain. Ia juga pendukung awal <strong>hak suara perempuan</strong> dan reformasi pendidikan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser posisi di spektrum ekonomi dan lihat bagaimana pilihan tentang peran pasar dan negara menghasilkan corak distribusi yang berbeda.",
      },
      { type: "widget", widget: "SimulatorSpektrumEkonomi" },
      {
        type: "chart",
        variant: "donut",
        title: "Dua Ranah Menurut Mill: Yang Tetap vs Yang Bisa Diubah",
        unit: "ilustrasi konseptual",
        source: "ilustrasi gagasan Mill (Principles of Political Economy, 1848)",
        note: "Mill menegaskan bahwa distribusi, tidak seperti produksi, adalah wilayah pilihan sosial yang terbuka untuk direformasi.",
        data: [
          { label: "Produksi (hukum alam, tetap)", value: 50, color: "#fb7185" },
          { label: "Distribusi (pilihan sosial, bisa diubah)", value: 50, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Panen yang sama, pembagian yang berbeda",
        html: "Dua desa memanen padi dalam jumlah yang sama karena tanah dan teknologinya identik (hukum produksi sama). Tetapi desa pertama membagi hasil rata melalui koperasi, sedangkan desa kedua membiarkan segelintir tuan tanah menguasai sebagian besar hasil. <strong>Total produksi sama, tetapi distribusinya berbeda jauh.</strong> Inilah maksud Mill: pembagian kekayaan adalah keputusan masyarakat, bukan hukum alam yang tak bisa diubah.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah desa memanen 1.000 kg padi. Bila dibagi rata untuk 50 keluarga, berapa kg yang diterima tiap keluarga?",
        answer: 20,
        tolerance: 0,
        suffix: " kg",
        solution: "1.000 / 50 = <strong>20 kg</strong> per keluarga. Total panen (produksi) tetap, tetapi cara membagi (distribusi) adalah pilihan masyarakat.",
        hint: "Bagi total panen dengan jumlah keluarga.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan karya atau gagasan dengan John Stuart Mill.",
        pairs: [
          { left: "Principles of Political Economy (1848)", right: "Memisahkan hukum produksi dan distribusi" },
          { left: "On Liberty (1859)", right: "Prinsip kerugian dan kebebasan individu" },
          { left: "The Subjection of Women (1869)", right: "Kesetaraan hak perempuan" },
          { left: "Utilitarianism (1863)", right: "Etika kebahagiaan terbesar" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Principles of Political Economy 1848",
        html: "<strong>Principles of Political Economy</strong> terbit pada <strong>1848</strong>, tahun yang penuh revolusi di Eropa dan tahun yang sama dengan <em>Manifesto Komunis</em> Marx dan Engels. Buku Mill menjadi <strong>buku teks ekonomi standar</strong> selama hampir setengah abad. Mill, yang sejak kecil dididik sangat ketat oleh ayahnya James Mill, tumbuh menjadi tokoh yang menggabungkan ketajaman analisis klasik dengan kepedulian sosial, menjadikannya jembatan menuju pemikiran ekonomi abad ke-20.",
      },
      {
        type: "takeaways",
        items: [
          "Mill memisahkan hukum produksi (tetap) dari hukum distribusi (bisa diubah).",
          "Distribusi adalah pilihan masyarakat, membuka jalan reformasi sosial.",
          "On Liberty (1859): kebebasan individu dan prinsip kerugian.",
          "Mill mendukung kesetaraan perempuan dan reformasi pendidikan.",
          "Principles (1848) jadi buku teks ekonomi standar hampir 50 tahun.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Gagasan khas Mill adalah memisahkan?",
            options: [
              "Uang dan barang",
              "Hukum produksi dari hukum distribusi",
              "Negara dan pasar sepenuhnya",
              "Nilai dan harga",
            ],
            answer: 1,
            explain: "Produksi tunduk pada hukum alam, distribusi adalah pilihan masyarakat.",
          },
          {
            q: "Menurut Mill, distribusi kekayaan bersifat?",
            options: [
              "Hukum alam yang tak bisa diubah",
              "Pilihan sosial yang bisa direformasi",
              "Ditentukan sepenuhnya oleh pasar",
              "Tidak penting",
            ],
            answer: 1,
            explain: "Karena distribusi buatan manusia, masyarakat bisa mengubahnya lewat kebijakan.",
          },
          {
            q: "Karya Mill yang membela kebebasan individu adalah?",
            options: ["On Liberty", "The Wealth of Nations", "Das Kapital", "The General Theory"],
            answer: 0,
            explain: "On Liberty (1859) memuat prinsip kerugian dan pembelaan kebebasan individu.",
          },
          {
            q: "Prinsip kerugian (harm principle) Mill berarti?",
            options: [
              "Negara mengatur semua tindakan warga",
              "Kebebasan hanya dibatasi untuk mencegah kerugian pada orang lain",
              "Semua kebebasan dilarang",
              "Pasar tidak boleh diatur sama sekali",
            ],
            answer: 1,
            explain: "Negara hanya boleh membatasi kebebasan untuk mencegah kerugian pada pihak lain.",
          },
          {
            q: "Principles of Political Economy terbit pada tahun?",
            options: ["1817", "1848", "1859", "1867"],
            answer: 1,
            explain: "Terbit 1848, tahun yang sama dengan Manifesto Komunis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "warisan-mazhab-klasik",
    levelId: "klasik",
    order: 7,
    title: "Warisan & Batas Mazhab Klasik",
    summary: "Mazhab klasik mewariskan gagasan pasar, perdagangan bebas, dan spesialisasi yang masih hidup hari ini. Namun ia mengabaikan krisis dan ketimpangan, memberi celah bagi Marx dan revolusi marginal.",
    durationMin: 14,
    tags: ["klasik", "warisan", "kritik", "revolusi marginal"],
    blocks: [
      {
        type: "paragraph",
        html: "Selama hampir seratus tahun, dari <strong>Adam Smith</strong> (1776) hingga sekitar <strong>1870</strong>, mazhab klasik mendominasi cara dunia memikirkan ekonomi. Warisannya besar: keyakinan pada <strong>pasar</strong> sebagai penata kegiatan ekonomi, <strong>perdagangan bebas</strong> antarnegara, dan <strong>spesialisasi</strong> lewat pembagian kerja. Banyak dari gagasan ini masih menjadi fondasi ekonomi modern.",
      },
      {
        type: "paragraph",
        html: "Namun mazhab klasik juga punya batas. Ia cenderung <strong>mengabaikan krisis dan resesi</strong> (percaya Hukum Say membuat ekonomi selalu pulih sendiri) dan kurang menaruh perhatian pada <strong>ketimpangan distribusi</strong> serta nasib buruh. Celah inilah yang kelak diisi oleh <strong>Karl Marx</strong> dengan kritik radikalnya dan oleh <strong>revolusi marginal</strong> yang mengubah dasar teori nilai.",
      },
      {
        type: "video",
        comp: "TanganTakTampak",
        title: "Video: Tangan Tak Tampak",
        caption: "Gagasan inti klasik yang bertahan: pasar sebagai penata kemakmuran.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Warisan besar mazhab klasik",
        html: "<strong>Pasar</strong> mengoordinasikan tanpa komando pusat, <strong>perdagangan bebas</strong> menguntungkan semua pihak lewat keunggulan komparatif, dan <strong>spesialisasi</strong> melipatgandakan produktivitas. Tiga pilar ini masih menjadi dasar ekonomi arus utama sampai hari ini.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Batas dan kritik",
        html: "Klasik kurang menjelaskan mengapa terjadi <strong>krisis dan pengangguran massal</strong>, dan sering mengabaikan <strong>ketimpangan</strong>. Marx menuding klasik menutup mata pada eksploitasi buruh, sementara para ekonom marginal menilai teori nilai kerja klasik keliru menjelaskan harga.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dua jalan setelah klasik",
        html: "Dari kritik terhadap klasik lahir dua arah besar. <strong>Karl Marx</strong> (Das Kapital, 1867) mengembangkan kritik atas kapitalisme dan eksploitasi. <strong>Revolusi marginal</strong> (Jevons, Menger, Walras sekitar 1871) mengganti teori nilai kerja dengan <strong>utilitas marginal</strong>, melahirkan ekonomi neoklasik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati kembali bagaimana tangan tak tampak menata pasar, lalu bayangkan situasi (krisis, ketimpangan) yang tidak dijelaskan oleh model klasik.",
      },
      { type: "widget", widget: "SimulatorTanganTakTampak" },
      {
        type: "chart",
        variant: "bar",
        title: "Tonggak Pemikiran Ekonomi: Dari Klasik ke Penerusnya",
        unit: "tahun terbit karya kunci",
        source: "sejarah penerbitan karya-karya ekonomi",
        note: "Mazhab klasik mendominasi 1776 sampai sekitar 1870, lalu Marx dan revolusi marginal membuka babak baru.",
        data: [
          { label: "Smith (Wealth of Nations)", value: 1776, color: "#34d399" },
          { label: "Ricardo (Principles)", value: 1817, color: "#60a5fa" },
          { label: "Mill (Principles)", value: 1848, color: "#a78bfa" },
          { label: "Marx (Das Kapital)", value: 1867, color: "#fb7185" },
          { label: "Revolusi marginal", value: 1871, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Apa yang tidak bisa dijelaskan klasik",
        html: "Bayangkan sebuah pabrik yang tiba-tiba menutup ribuan pekerja karena barangnya tidak laku, memicu gelombang pengangguran. Model klasik, bersandar pada Hukum Say, memperkirakan pasar akan cepat pulih sendiri. Tetapi <strong>krisis nyata sering berlarut</strong>. Ketidakmampuan menjelaskan resesi berkepanjangan inilah salah satu batas terbesar mazhab klasik, yang baru dijawab tuntas oleh Keynes pada abad ke-20.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan hal berikut sebagai warisan (kontribusi) atau keterbatasan (kritik) mazhab klasik.",
        buckets: ["Warisan", "Keterbatasan"],
        items: [
          { text: "Pasar mengoordinasikan tanpa komando pusat", bucket: "Warisan" },
          { text: "Perdagangan bebas dan keunggulan komparatif", bucket: "Warisan" },
          { text: "Spesialisasi lewat pembagian kerja", bucket: "Warisan" },
          { text: "Mengabaikan krisis dan pengangguran massal", bucket: "Keterbatasan" },
          { text: "Kurang memperhatikan ketimpangan distribusi", bucket: "Keterbatasan" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Berapa lama kira-kira mazhab klasik mendominasi, dari terbitnya Wealth of Nations (1776) hingga revolusi marginal (sekitar 1871)?",
        answer: 95,
        tolerance: 2,
        suffix: " tahun",
        solution: "1871 - 1776 = <strong>95 tahun</strong>, hampir satu abad dominasi pemikiran klasik.",
        hint: "Kurangkan tahun awal dari tahun akhir.",
      },
      {
        type: "case",
        title: "Sejarah: Dominasi klasik sampai sekitar 1870",
        html: "Mazhab klasik menjadi arus utama sejak <strong>1776</strong> hingga sekitar <strong>1870</strong>. Titik balik datang saat <strong>Karl Marx</strong> menerbitkan jilid pertama <em>Das Kapital</em> pada <strong>1867</strong>, dan tak lama kemudian <strong>revolusi marginal</strong> meletus hampir bersamaan lewat karya <strong>William Stanley Jevons</strong>, <strong>Carl Menger</strong>, dan <strong>Leon Walras</strong> sekitar <strong>1871</strong>. Sejak saat itu teori nilai kerja klasik memudar, digantikan gagasan utilitas marginal yang menjadi fondasi ekonomi neoklasik modern.",
      },
      {
        type: "takeaways",
        items: [
          "Klasik mendominasi 1776 sampai sekitar 1870, hampir satu abad.",
          "Warisan utama: pasar, perdagangan bebas, dan spesialisasi.",
          "Keterbatasan: mengabaikan krisis dan ketimpangan distribusi.",
          "Marx (Das Kapital, 1867) mengembangkan kritik atas kapitalisme.",
          "Revolusi marginal (sekitar 1871) melahirkan ekonomi neoklasik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah yang termasuk warisan besar mazhab klasik?",
            options: [
              "Perencanaan terpusat",
              "Pasar, perdagangan bebas, dan spesialisasi",
              "Utilitas marginal",
              "Permintaan agregat",
            ],
            answer: 1,
            explain: "Tiga pilar klasik ini masih menjadi dasar ekonomi arus utama.",
          },
          {
            q: "Salah satu keterbatasan mazhab klasik adalah?",
            options: [
              "Terlalu memperhatikan buruh",
              "Mengabaikan krisis dan ketimpangan",
              "Menolak pasar",
              "Menolak perdagangan bebas",
            ],
            answer: 1,
            explain: "Klasik kurang menjelaskan resesi dan kurang menaruh perhatian pada ketimpangan.",
          },
          {
            q: "Karya kritik atas kapitalisme yang terbit 1867 adalah?",
            options: ["The Wealth of Nations", "Das Kapital", "On Liberty", "The General Theory"],
            answer: 1,
            explain: "Karl Marx menerbitkan jilid pertama Das Kapital pada 1867.",
          },
          {
            q: "Revolusi marginal (sekitar 1871) mengganti teori nilai kerja dengan?",
            options: ["Tangan tak tampak", "Utilitas marginal", "Hukum Say", "Teori sewa"],
            answer: 1,
            explain: "Jevons, Menger, dan Walras memperkenalkan utilitas marginal.",
          },
          {
            q: "Mazhab klasik kira-kira mendominasi sampai tahun?",
            options: ["Sekitar 1870", "Sekitar 1930", "Sekitar 1980", "Sekitar 2000"],
            answer: 0,
            explain: "Dominasi klasik berlangsung 1776 hingga sekitar 1870, lalu digantikan penerusnya.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ricardo-sewa-dan-distribusi",
    levelId: "klasik",
    order: 8,
    title: "Ricardo: Teori Sewa & Distribusi",
    summary: "Ricardo menjelaskan mengapa tanah lebih subur memberi sewa lebih besar, dan bagaimana hasil produksi terbagi menjadi sewa, upah, dan laba di tengah hukum hasil yang menurun.",
    durationMin: 15,
    tags: ["Ricardo", "sewa diferensial", "distribusi", "hasil menurun"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain keunggulan komparatif, <strong>David Ricardo</strong> terkenal dengan pertanyaan yang lebih mendasar: setelah barang diproduksi, <strong>bagaimana hasilnya dibagi</strong>? Menurut Ricardo, hasil ekonomi terbagi di antara tiga kelas: <strong>pemilik tanah</strong> yang menerima <strong>sewa</strong>, <strong>buruh</strong> yang menerima <strong>upah</strong>, dan <strong>kapitalis</strong> yang menerima <strong>laba</strong>. Memahami distribusi inilah, kata Ricardo, adalah persoalan utama ilmu ekonomi.",
      },
      {
        type: "paragraph",
        html: "Inti gagasannya adalah <strong>teori sewa diferensial</strong>. Tanah tidak seragam: sebagian lebih subur, sebagian gersang. Karena permintaan pangan menaikkan harga, tanah kurang subur pun akhirnya ikut digarap. Selisih hasil antara tanah subur dan <strong>tanah marjinal</strong> (tanah paling tidak subur yang masih layak digarap) itulah yang menjadi <strong>sewa</strong> bagi pemilik tanah yang lebih subur.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Garis Waktu Pemikiran Ekonomi",
        caption: "Ricardo dan gagasan distribusi dalam alur sejarah ekonomi klasik.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_David_Ricardo_by_Thomas_Phillips.jpg?width=400",
        alt: "Potret David Ricardo",
        caption: "David Ricardo (1772-1823).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Sewa diferensial",
        html: "<strong>Sewa muncul dari perbedaan kesuburan tanah.</strong> Tanah paling subur memberi hasil paling besar, sehingga selisihnya terhadap tanah marjinal menjadi sewa terbesar. <strong>Tanah marjinal sendiri tidak menghasilkan sewa</strong>, karena hasilnya hanya cukup menutup upah dan laba biasa.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga bagian hasil produksi",
        html: "Bagi Ricardo, kue ekonomi dibagi menjadi tiga: <strong>sewa</strong> untuk pemilik tanah, <strong>upah</strong> untuk buruh, dan <strong>laba</strong> untuk kapitalis. Bila salah satu bagian membesar, bagian lain cenderung mengecil, sehingga distribusi selalu menjadi arena tarik-menarik antar kelas.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hukum hasil yang menurun",
        html: "Saat penduduk bertambah, tanah subur habis dan orang terpaksa menggarap tanah yang makin buruk. <strong>Hukum hasil yang menurun</strong> membuat tiap tambahan tenaga kerja menghasilkan pangan yang makin sedikit. Akibatnya sewa naik, upah tertekan ke batas subsisten, dan <strong>laba cenderung turun</strong>, ramalan suram yang mewarnai ekonomi klasik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Amati bagaimana harga bergeser saat permintaan pangan naik, faktor yang mendorong penggarapan tanah kurang subur dan menaikkan sewa dalam model Ricardo.",
      },
      { type: "widget", widget: "SimulatorKeseimbanganPasar" },
      {
        type: "chart",
        variant: "bar",
        title: "Sewa Diferensial: Hasil Tiga Petak Tanah dengan Kerja Sama",
        unit: "kwintal panen per petak",
        source: "ilustrasi teori sewa diferensial Ricardo (Principles of Political Economy and Taxation, 1817)",
        note: "Dengan tenaga dan modal yang sama, tanah lebih subur menghasilkan lebih banyak; selisih terhadap tanah marjinal (60) menjadi sewa: 40 dan 20, sedangkan tanah marjinal tidak menghasilkan sewa.",
        data: [
          { label: "Tanah A (subur)", value: 100, color: "#34d399" },
          { label: "Tanah B (sedang)", value: 80, color: "#60a5fa" },
          { label: "Tanah C (marjinal)", value: 60, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung sewa tiga petak",
        html: "Tiga petak digarap dengan tenaga dan modal yang sama. Tanah A menghasilkan 100 kwintal, tanah B 80 kwintal, dan tanah C (marjinal) 60 kwintal. Karena tanah C hanya cukup menutup upah dan laba, sewanya <strong>nol</strong>. Sewa petak lain adalah selisih hasilnya terhadap tanah marjinal: sewa A = 100 - 60 = <strong>40 kwintal</strong>, sewa B = 80 - 60 = <strong>20 kwintal</strong>. Makin subur tanahnya, makin besar sewa yang dinikmati pemiliknya.",
      },
      {
        type: "calcExercise",
        prompt: "Tanah subur menghasilkan 100 kwintal dan tanah marjinal 60 kwintal dengan biaya kerja yang sama. Menurut teori sewa Ricardo, berapa sewa tanah subur?",
        answer: 40,
        tolerance: 0,
        suffix: " kwintal",
        solution: "Sewa = hasil tanah subur - hasil tanah marjinal = 100 - 60 = <strong>40 kwintal</strong>. Tanah marjinal sendiri tidak menghasilkan sewa.",
        hint: "Kurangkan hasil tanah marjinal dari hasil tanah subur.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pihak dengan bagian hasil yang diterimanya menurut Ricardo.",
        pairs: [
          { left: "Pemilik tanah", right: "Sewa" },
          { left: "Buruh", right: "Upah" },
          { left: "Kapitalis", right: "Laba" },
          { left: "Tanah marjinal", right: "Tidak menghasilkan sewa" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Principles of Political Economy and Taxation 1817",
        html: "Teori sewa dan distribusi Ricardo dipaparkan dalam <strong>On the Principles of Political Economy and Taxation</strong> yang terbit pada <strong>1817</strong>. Di dalamnya Ricardo menggunakan teori sewa untuk menyerang <strong>Corn Laws</strong>, hukum yang membatasi impor gandum ke Inggris. Ia berpendapat proteksi itu menaikkan harga pangan, memperluas penggarapan tanah buruk, dan memperkaya pemilik tanah dengan mengorbankan buruh serta kapitalis. Corn Laws akhirnya dicabut pada <strong>1846</strong>, beberapa tahun setelah Ricardo wafat pada 1823.",
      },
      {
        type: "takeaways",
        items: [
          "Ricardo menjadikan distribusi sebagai persoalan utama ekonomi.",
          "Hasil produksi terbagi menjadi sewa, upah, dan laba.",
          "Sewa diferensial: selisih hasil tanah subur dan tanah marjinal.",
          "Tanah marjinal tidak menghasilkan sewa.",
          "Hukum hasil yang menurun menekan laba dan upah ke bawah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Ricardo, hasil produksi terbagi menjadi?",
            options: [
              "Hanya upah dan laba",
              "Sewa, upah, dan laba",
              "Pajak dan subsidi",
              "Uang dan barang",
            ],
            answer: 1,
            explain: "Ricardo membagi hasil ke pemilik tanah (sewa), buruh (upah), dan kapitalis (laba).",
          },
          {
            q: "Sewa diferensial muncul karena?",
            options: [
              "Jumlah uang beredar",
              "Perbedaan kesuburan tanah",
              "Tingkat suku bunga",
              "Kebijakan pajak",
            ],
            answer: 1,
            explain: "Selisih hasil tanah subur terhadap tanah marjinal menjadi sewa.",
          },
          {
            q: "Berapa sewa tanah marjinal menurut Ricardo?",
            options: ["Paling besar", "Nol", "Sama dengan upah", "Setengah hasil"],
            answer: 1,
            explain: "Tanah marjinal hanya menutup upah dan laba biasa, sehingga sewanya nol.",
          },
          {
            q: "Hukum hasil yang menurun menyebabkan?",
            options: [
              "Laba cenderung naik terus",
              "Tiap tambahan kerja menghasilkan pangan makin sedikit",
              "Sewa selalu nol",
              "Upah selalu tinggi",
            ],
            answer: 1,
            explain: "Menggarap tanah makin buruk membuat tambahan hasil mengecil, menekan laba dan upah.",
          },
          {
            q: "Teori sewa Ricardo terbit dalam karya tahun?",
            options: ["1776", "1798", "1817", "1848"],
            answer: 2,
            explain: "Principles of Political Economy and Taxation terbit 1817.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "uang-dalam-ekonomi-klasik",
    levelId: "klasik",
    order: 9,
    title: "Uang dalam Ekonomi Klasik",
    summary: "Bagi ekonom klasik, uang hanyalah selubung: menambah jumlahnya hanya menaikkan harga. Hume merumuskan teori kuantitas dan mekanisme aliran logam-harga, memicu debat currency school vs banking school.",
    durationMin: 15,
    tags: ["uang", "teori kuantitas", "Hume", "price-specie flow"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagaimana ekonom klasik memandang uang? Jawaban mereka sederhana namun kuat: uang adalah <strong>selubung</strong> yang menutupi kegiatan ekonomi yang sesungguhnya. Menurut <strong>teori kuantitas uang</strong>, bila jumlah uang yang beredar bertambah sedangkan barang yang diproduksi tetap, yang naik hanyalah <strong>harga</strong>, bukan kemakmuran nyata. Hubungan ini dirangkum dalam persamaan <strong>MV = PT</strong>: jumlah uang (M) dikali kecepatan peredaran (V) sama dengan tingkat harga (P) dikali volume transaksi (T).",
      },
      {
        type: "paragraph",
        html: "Filsuf Skotlandia <strong>David Hume</strong> mempertajam gagasan ini pada abad ke-18. Ia menjelaskan bahwa menambah emas dan perak di suatu negara tidak membuat negara itu lebih kaya dalam jangka panjang, melainkan hanya menaikkan harga-harga. Inilah gagasan <strong>netralitas uang</strong>: dalam jangka panjang, uang tidak mengubah jumlah barang riil yang dihasilkan.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Inflasi",
        caption: "Mengapa menambah uang tanpa menambah barang hanya menaikkan harga.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/David_Hume.jpg?width=400",
        alt: "Potret David Hume",
        caption: "David Hume (1711-1776).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Teori kuantitas uang",
        html: "<strong>MV = PT.</strong> Bila kecepatan uang (V) dan volume transaksi (T) relatif tetap, maka menambah jumlah uang (M) hanya menaikkan tingkat harga (P) sebanding. Uang menentukan harga, bukan kekayaan riil.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mekanisme aliran logam-harga",
        html: "Hume menjelaskan <strong>price-specie flow mechanism</strong>: negara yang surplus dagang menerima aliran emas masuk, sehingga harga di dalam negeri naik. Harga tinggi membuat ekspornya melemah dan impor menguat, emas pun mengalir keluar lagi. Dengan sendirinya perdagangan antarnegara cenderung <strong>menyeimbangkan diri</strong>, sebuah kritik terhadap merkantilisme yang menimbun emas.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Currency school vs banking school",
        html: "Pada abad ke-19 muncul debat sengit. <strong>Currency school</strong> berpendapat penerbitan uang kertas harus dijamin penuh oleh emas agar harga stabil, gagasan yang mendasari Bank Charter Act 1844. <strong>Banking school</strong> membalas bahwa jumlah uang seharusnya mengikuti <strong>kebutuhan perdagangan</strong> dan menyesuaikan diri secara wajar. Perdebatan ini menyangkut jantung kebijakan moneter modern.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung bagaimana kenaikan jumlah uang berubah menjadi kenaikan harga, gambaran nyata dari teori kuantitas uang.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "line",
        title: "Jumlah Uang Naik, Harga Ikut Naik (ilustrasi teori kuantitas)",
        unit: "indeks (mulai dari 100)",
        source: "ilustrasi teori kuantitas uang klasik (MV = PT dengan V dan T tetap)",
        note: "Ketika output riil tetap, penambahan jumlah uang bergerak nyaris sejajar dengan tingkat harga, persis prediksi Hume dan teori kuantitas.",
        data: [
          { label: "Awal", value: 100, color: "#60a5fa" },
          { label: "Uang +25%", value: 125, color: "#fbbf24" },
          { label: "Uang +50%", value: 150, color: "#fb7185" },
          { label: "Uang +100%", value: 200, color: "#f472b6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Uang menggandakan diri",
        html: "Bayangkan sebuah negeri dengan jumlah uang Rp100 triliun, kecepatan uang tetap, dan output barang yang tidak berubah. Bila jumlah uang naik menjadi Rp150 triliun, menurut teori kuantitas (MV = PT), tingkat harga naik sebanding: <strong>50 persen</strong>. Rakyat memegang lebih banyak uang, tetapi jumlah barang yang bisa dibeli tidak bertambah. Inilah cara Hume menunjukkan bahwa <strong>menimbun logam mulia tidak membuat bangsa lebih kaya secara riil</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Jumlah uang beredar naik dari Rp100 triliun menjadi Rp150 triliun. Bila kecepatan uang dan output riil tetap, berapa persen kenaikan tingkat harga menurut teori kuantitas?",
        answer: 50,
        tolerance: 0,
        suffix: "%",
        solution: "Karena MV = PT dengan V dan T tetap, harga naik sebanding dengan uang: (150 - 100) / 100 = <strong>50%</strong>.",
        hint: "Bila V dan T tetap, persentase kenaikan P sama dengan persentase kenaikan M.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan sesuai mazhab yang mendukungnya dalam debat abad ke-19.",
        buckets: ["Currency school", "Banking school"],
        items: [
          { text: "Uang kertas harus dijamin penuh oleh emas", bucket: "Currency school" },
          { text: "Jumlah uang mengikuti kebutuhan perdagangan", bucket: "Banking school" },
          { text: "Mendukung Bank Charter Act 1844", bucket: "Currency school" },
          { text: "Uang menyesuaikan diri secara wajar mengikuti transaksi", bucket: "Banking school" },
          { text: "Inflasi berasal dari penerbitan uang yang berlebih", bucket: "Currency school" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Esai Hume Of Money 1752",
        html: "David Hume memaparkan gagasannya dalam esai <strong>Of Money</strong> dan <strong>Of the Balance of Trade</strong> yang terbit dalam <em>Political Discourses</em> pada <strong>1752</strong>. Dalam <em>Of Money</em> ia merumuskan teori kuantitas dan menekankan bahwa jumlah uang menentukan harga, bukan kekayaan riil. Gagasan Hume mengilhami Adam Smith, sahabat dekatnya, dan menjadi cikal bakal <strong>monetarisme modern</strong> yang kelak dihidupkan kembali oleh Milton Friedman pada abad ke-20.",
      },
      {
        type: "takeaways",
        items: [
          "Bagi klasik, uang adalah selubung: menambahnya hanya menaikkan harga.",
          "Teori kuantitas uang: MV = PT.",
          "Netralitas uang: dalam jangka panjang uang tidak mengubah output riil.",
          "Hume merumuskan mekanisme aliran logam-harga yang menyeimbangkan perdagangan.",
          "Debat currency school vs banking school membentuk kebijakan moneter.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Persamaan teori kuantitas uang adalah?",
            options: ["MV = PT", "Y = C + I + G", "P = MC", "S = I"],
            answer: 0,
            explain: "MV = PT menghubungkan jumlah uang dan kecepatannya dengan harga dan transaksi.",
          },
          {
            q: "Menurut teori kuantitas, menambah uang saat output tetap akan?",
            options: [
              "Menaikkan kekayaan riil",
              "Menaikkan tingkat harga",
              "Menurunkan harga",
              "Menambah jumlah barang",
            ],
            answer: 1,
            explain: "Bila barang tetap, tambahan uang hanya menaikkan harga (inflasi).",
          },
          {
            q: "Mekanisme aliran logam-harga (price-specie flow) Hume menjelaskan bahwa?",
            options: [
              "Menimbun emas membuat bangsa makin kaya selamanya",
              "Perdagangan antarnegara cenderung menyeimbangkan diri",
              "Harga tidak pernah berubah",
              "Emas harus dilarang beredar",
            ],
            answer: 1,
            explain: "Aliran emas menaikkan harga, melemahkan ekspor, lalu emas mengalir keluar lagi.",
          },
          {
            q: "Currency school berpendapat bahwa uang kertas harus?",
            options: [
              "Mengikuti kebutuhan perdagangan",
              "Dijamin penuh oleh emas",
              "Dicetak tanpa batas",
              "Dihapus sama sekali",
            ],
            answer: 1,
            explain: "Currency school menuntut jaminan emas penuh, dasar Bank Charter Act 1844.",
          },
          {
            q: "Esai Of Money karya Hume terbit pada tahun?",
            options: ["1752", "1776", "1798", "1817"],
            answer: 0,
            explain: "Of Money terbit dalam Political Discourses pada 1752.",
          },
        ],
      },
    ],
  },
];
