import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "marx-dan-kritik-klasik",
    levelId: "kritik",
    order: 1,
    title: "Marx & Kritik atas Ekonomi Klasik",
    summary: "Bagaimana Karl Marx menggugat kapitalisme dan ekonomi klasik lewat teori nilai lebih, serta lahirnya institusionalisme.",
    durationMin: 14,
    tags: ["Marx", "nilai lebih", "kritik", "institusionalisme"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi klasik memuji pasar bebas, tetapi tidak semua sepakat. <strong>Karl Marx</strong> menggunakan alat analisis klasik, terutama teori nilai kerja, untuk sampai pada kesimpulan yang berlawanan: kapitalisme mengandung ketimpangan dan kontradiksi yang dalam.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Menimbang Kapitalisme",
        caption: "Klasik memuji pasar; Marx menyoroti ketimpangan dan konflik kelas di baliknya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_001.jpg?width=400",
        alt: "Potret Karl Marx",
        caption: "Karl Marx (1818-1883), pengkritik kapitalisme paling berpengaruh, penulis Das Kapital.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Teori nilai lebih",
        html: "Marx berpendapat buruh menciptakan nilai lebih besar daripada upahnya. Selisihnya, <strong>nilai lebih (surplus value)</strong>, diambil pemilik modal sebagai laba. Dari sini ia menyimpulkan adanya <strong>eksploitasi</strong> yang melekat pada hubungan kerja kapitalis.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kritik lain atas klasik",
        html: "<strong>Mazhab historis Jerman</strong> menolak hukum ekonomi universal dan menekankan konteks sejarah. <strong>Institusionalisme</strong> (Thorstein Veblen) menyoroti peran lembaga, kebiasaan, dan konsumsi status (<em>conspicuous consumption</em>), bukan sekadar individu rasional.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Teori nilai kerja yang dipakai Marx kemudian <strong>ditinggalkan</strong> ekonomi arus utama setelah revolusi marginal. Penerapan gagasan Marx dalam rezim komunis juga menuai kritik serius. Ia dibaca di sini sebagai bagian penting sejarah pemikiran, bukan kebenaran final.",
      },
      {
        type: "widget",
        widget: "KalkulatorGini",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Fokus Perhatian: Klasik vs Marx (ilustrasi konsep)",
        unit: "penekanan relatif",
        source: "ilustrasi konsep perbandingan pandangan",
        note: "Klasik menonjolkan efisiensi dan pertumbuhan; Marx menonjolkan distribusi, kelas, dan konflik.",
        data: [
          { label: "Klasik: efisiensi & pasar", value: 85, color: "#34d399" },
          { label: "Marx: distribusi & kelas", value: 85, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung nilai lebih",
        html: "Seorang buruh menciptakan nilai <strong>Rp400 ribu</strong> sehari, tetapi upahnya hanya <strong>Rp150 ribu</strong>. Menurut Marx, selisih <strong>Rp250 ribu</strong> adalah nilai lebih yang diambil pemilik modal. Ekonom klasik dan neoklasik menjawab berbeda: imbalan modal dan risiko juga menciptakan nilai. Perdebatan tentang dari mana laba berasal ini menjadi salah satu poros sejarah pemikiran ekonomi.",
      },
      {
        type: "calcExercise",
        prompt: "Buruh menciptakan nilai Rp400 ribu sehari, upahnya Rp150 ribu. Berapa nilai lebih menurut Marx (dalam ribu rupiah)?",
        answer: 250,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "Nilai lebih = nilai diciptakan - upah = 400 - 150 = <strong>Rp250 ribu</strong>.",
        hint: "Kurangkan upah dari nilai yang diciptakan.",
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini lebih dekat ke ekonomi klasik atau kritik Marx?",
        buckets: ["Klasik", "Marx"],
        items: [
          { text: "Pasar bebas menghasilkan kemakmuran umum", bucket: "Klasik" },
          { text: "Laba berasal dari kerja buruh yang tak dibayar penuh", bucket: "Marx" },
          { text: "Sejarah digerakkan perjuangan kelas", bucket: "Marx" },
          { text: "Kepentingan pribadi menata efisiensi", bucket: "Klasik" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Das Kapital 1867",
        html: "Marx menerbitkan jilid pertama <strong>Das Kapital</strong> pada <strong>1867</strong>. Buku ini membedah cara kerja kapitalisme secara sistematis dan menjadi salah satu karya paling berpengaruh sekaligus paling diperdebatkan dalam sejarah. Terlepas dari pro dan kontra, Marx memaksa para ekonom sesudahnya untuk serius memikirkan soal distribusi, kelas, dan krisis.",
      },
      {
        type: "takeaways",
        items: [
          "Marx memakai alat klasik untuk mengkritik kapitalisme.",
          "Teori nilai lebih: laba dari kerja buruh yang tak dibayar penuh.",
          "Institusionalisme (Veblen) menyoroti peran lembaga dan kebiasaan.",
          "Teori nilai kerja kemudian ditinggalkan ekonomi arus utama.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Nilai lebih menurut Marx adalah?",
            options: [
              "Upah buruh",
              "Selisih nilai yang diciptakan buruh dan upahnya",
              "Pajak",
              "Bunga bank",
            ],
            answer: 1,
            explain: "Nilai lebih adalah selisih yang, menurut Marx, diambil pemilik modal.",
          },
          {
            q: "Karya utama Marx adalah?",
            options: ["The Wealth of Nations", "Das Kapital", "General Theory", "Principles of Economics"],
            answer: 1,
            explain: "Das Kapital (jilid I, 1867) adalah analisis ekonomi utama Marx.",
          },
          {
            q: "Institusionalisme (Veblen) menekankan?",
            options: [
              "Individu selalu rasional",
              "Peran lembaga, kebiasaan, dan konsumsi status",
              "Tangan tak tampak",
              "Utilitas marginal",
            ],
            answer: 1,
            explain: "Veblen menyoroti lembaga dan perilaku sosial, termasuk conspicuous consumption.",
          },
          {
            q: "Teori nilai kerja yang dipakai Marx kemudian?",
            options: [
              "Menjadi arus utama",
              "Ditinggalkan ekonomi arus utama setelah revolusi marginal",
              "Tidak pernah dibahas",
              "Diterima semua ekonom",
            ],
            answer: 1,
            explain: "Revolusi marginal menggeser teori nilai ke utilitas marginal.",
          },
          {
            q: "Buruh menciptakan Rp300 ribu, upah Rp100 ribu. Nilai lebihnya?",
            options: ["Rp200 ribu", "Rp100 ribu", "Rp300 ribu", "Rp400 ribu"],
            answer: 0,
            explain: "300 - 100 = Rp200 ribu.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "teori-nilai-lebih-marx",
    levelId: "kritik",
    order: 2,
    title: "Teori Nilai Lebih Marx",
    summary: "Membedah inti kritik Marx: nilai lebih (surplus value), rumus nilai komoditas W = c + v + s, dan tingkat eksploitasi s/v.",
    durationMin: 15,
    tags: ["Marx", "nilai lebih", "eksploitasi", "Das Kapital"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi Marx, laba bukan misteri. Ia lahir dari selisih antara nilai yang diciptakan buruh dan upah yang dibayarkan. Untuk menjelaskannya, Marx memecah nilai sebuah komoditas menjadi tiga bagian.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus nilai komoditas",
        html: "Marx menulis nilai satu komoditas sebagai <strong>W = c + v + s</strong>. Di sini <strong>c</strong> = modal konstan (bahan, mesin, aus alat), <strong>v</strong> = modal variabel (upah buruh), dan <strong>s</strong> = nilai lebih (<em>surplus value</em>) yang diambil pemilik modal.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tingkat eksploitasi",
        html: "Marx menyebut rasio <strong>s/v</strong> sebagai <strong>tingkat nilai lebih</strong> atau tingkat eksploitasi. Semakin besar s dibanding v, semakin besar bagian kerja buruh yang tidak dibayar menurut kerangka Marx.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Ekonomi arus utama menolak teori nilai kerja ini: nilai ditentukan utilitas marginal dan kelangkaan, bukan semata jam kerja. Rumus W = c + v + s dibaca di sini sebagai peta gagasan Marx, bukan hukum yang diterima semua ekonom.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Dari Mana Laba Berasal?",
        caption: "Marx melacak laba ke selisih antara nilai yang diciptakan buruh dan upahnya.",
      },
      {
        type: "widget",
        widget: "KalkulatorUpahProduktivitas",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Pembagian Nilai Komoditas menurut Marx (ilustrasi)",
        unit: "bagian nilai",
        source: "ilustrasi kerangka W = c + v + s",
        note: "Dari total nilai, sebagian mengganti modal (c) dan upah (v), sisanya nilai lebih (s) bagi pemilik modal.",
        data: [
          { label: "c: modal konstan", value: 40, color: "#60a5fa" },
          { label: "v: upah buruh", value: 25, color: "#34d399" },
          { label: "s: nilai lebih", value: 35, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung tingkat eksploitasi",
        html: "Sebuah pabrik: modal konstan <strong>c = Rp60</strong>, upah <strong>v = Rp40</strong>, nilai lebih <strong>s = Rp80</strong> per unit. Nilai komoditas W = 60 + 40 + 80 = <strong>Rp180</strong>. Tingkat eksploitasi = s/v = 80/40 = <strong>2,0</strong> atau 200%. Menurut Marx, buruh bekerja dua kali lebih lama daripada yang diperlukan untuk menghasilkan upahnya sendiri.",
      },
      {
        type: "calcExercise",
        prompt: "Jika nilai lebih s = Rp80 dan upah v = Rp40, berapa tingkat eksploitasi s/v?",
        answer: 2,
        tolerance: 0.05,
        solution: "s/v = 80 / 40 = <strong>2,0</strong> (atau 200%).",
        hint: "Bagi nilai lebih dengan upah (modal variabel).",
      },
      {
        type: "calcExercise",
        prompt: "Komoditas dengan c = Rp50, v = Rp30, s = Rp45. Berapa nilai total W?",
        answer: 125,
        tolerance: 0,
        prefix: "Rp",
        solution: "W = c + v + s = 50 + 30 + 45 = <strong>Rp125</strong>.",
        hint: "Jumlahkan ketiga komponen.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan simbol dengan artinya dalam W = c + v + s.",
        pairs: [
          { left: "c", right: "Modal konstan (bahan & mesin)" },
          { left: "v", right: "Modal variabel (upah buruh)" },
          { left: "s", right: "Nilai lebih (surplus)" },
          { left: "s/v", right: "Tingkat eksploitasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Das Kapital jilid I, 1867",
        html: "Marx menerbitkan jilid pertama <strong>Das Kapital</strong> pada <strong>1867</strong>, tempat rumus W = c + v + s dan konsep nilai lebih dibedah secara rinci. Jilid II dan III baru disunting dan diterbitkan Friedrich Engels setelah Marx wafat, masing-masing pada <strong>1885</strong> dan <strong>1894</strong>. Karya ini menjadi rujukan utama analisis kapitalisme dari sudut kritis.",
      },
      {
        type: "takeaways",
        items: [
          "Nilai komoditas menurut Marx: W = c + v + s.",
          "c = modal konstan, v = upah, s = nilai lebih.",
          "Tingkat eksploitasi diukur dengan rasio s/v.",
          "Nilai lebih adalah sumber laba menurut Marx.",
          "Das Kapital jilid I terbit 1867; jilid II dan III diselesaikan Engels.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam rumus W = c + v + s, apa arti v?",
            options: ["Modal konstan", "Upah buruh (modal variabel)", "Nilai lebih", "Nilai total"],
            answer: 1,
            explain: "v adalah modal variabel, yaitu upah yang dibayarkan kepada buruh.",
          },
          {
            q: "Tingkat eksploitasi menurut Marx dihitung dengan?",
            options: ["c/v", "s/v", "s/c", "v/s"],
            answer: 1,
            explain: "Tingkat nilai lebih (eksploitasi) = s/v.",
          },
          {
            q: "Jika c = Rp60, v = Rp40, s = Rp80, berapa W?",
            options: ["Rp120", "Rp180", "Rp200", "Rp140"],
            answer: 1,
            explain: "W = 60 + 40 + 80 = Rp180.",
          },
          {
            q: "Nilai lebih (s) menurut Marx menjadi sumber?",
            options: ["Upah", "Pajak", "Laba pemilik modal", "Bunga tabungan"],
            answer: 2,
            explain: "Nilai lebih diambil pemilik modal sebagai laba.",
          },
          {
            q: "Jilid I Das Kapital terbit tahun?",
            options: ["1848", "1859", "1867", "1894"],
            answer: 2,
            explain: "Jilid I terbit 1867; jilid III baru terbit 1894 lewat suntingan Engels.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "materialisme-historis-ekonomi",
    levelId: "kritik",
    order: 3,
    title: "Materialisme Historis dalam Ekonomi",
    summary: "Bagaimana Marx menjelaskan sejarah lewat cara produksi: hubungan basis (ekonomi) dan suprastruktur (hukum, politik, ide), serta pergantian mode produksi.",
    durationMin: 15,
    tags: ["materialisme historis", "basis-suprastruktur", "mode produksi", "Marx"],
    blocks: [
      {
        type: "paragraph",
        html: "Marx tidak hanya mengkritik kapitalisme; ia menawarkan teori tentang <strong>bagaimana sejarah bergerak</strong>. Menurutnya, penggeraknya bukan ide besar atau tokoh hebat, melainkan <strong>cara manusia memproduksi kebutuhan hidupnya</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Basis dan suprastruktur",
        html: "Marx membedakan <strong>basis</strong> (kondisi ekonomi: alat produksi dan hubungan produksi) dari <strong>suprastruktur</strong> (hukum, politik, agama, budaya, ide). Ia berpendapat basis ekonomi sangat memengaruhi bentuk suprastruktur, bukan sebaliknya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mode produksi bergantian",
        html: "Sejarah dilihat sebagai rangkaian <strong>mode produksi</strong>: komunal purba, perbudakan, feodalisme, kapitalisme, dan (dalam ramalan Marx) sosialisme. Setiap transisi didorong ketegangan antara <em>kekuatan produksi</em> dan <em>hubungan produksi</em> yang usang.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Banyak sejarawan menilai skema ini terlalu deterministik: ide, agama, dan politik juga bisa mengubah ekonomi, bukan cuma sebaliknya. Ramalan bahwa kapitalisme pasti runtuh menuju sosialisme juga tidak terbukti umum. Materialisme historis berguna sebagai lensa, bukan hukum pasti.",
      },
      {
        type: "video",
        comp: "SejarahKapitalismeVideo",
        title: "Video: Bagaimana Cara Produksi Membentuk Zaman",
        caption: "Dari feodalisme ke kapitalisme: perubahan cara produksi mengubah masyarakat.",
      },
      {
        type: "widget",
        widget: "SimulatorSpektrumEkonomi",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Mode Produksi & Ciri Dominan (ilustrasi konsep)",
        unit: "penekanan relatif",
        source: "ilustrasi kerangka materialisme historis",
        note: "Tiap mode produksi punya hubungan produksi khasnya: siapa memiliki alat produksi dan bagaimana surplus dibagi.",
        data: [
          { label: "Feodal: tanah & bangsawan", value: 70, color: "#a78bfa" },
          { label: "Kapitalis: modal & pasar", value: 90, color: "#fb7185" },
          { label: "Sosialis (ramalan): milik bersama", value: 60, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dari feodal ke kapitalis",
        html: "Di Eropa, ketika perdagangan dan manufaktur tumbuh, hubungan tuan-tanah dan hamba yang mengikat mulai menghambat. Kaum pedagang dan pemilik modal membutuhkan buruh yang bebas berpindah dan pasar yang terbuka. Menurut Marx, <strong>kekuatan produksi baru</strong> (perdagangan, mesin) berbenturan dengan <strong>hubungan produksi lama</strong> (feodal), dan benturan itu melahirkan kapitalisme.",
      },
      {
        type: "classifyExercise",
        prompt: "Termasuk basis (ekonomi) atau suprastruktur menurut Marx?",
        buckets: ["Basis", "Suprastruktur"],
        items: [
          { text: "Alat dan mesin produksi", bucket: "Basis" },
          { text: "Hubungan majikan dan buruh", bucket: "Basis" },
          { text: "Undang-undang dan pengadilan", bucket: "Suprastruktur" },
          { text: "Agama dan seni", bucket: "Suprastruktur" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan mode produksi dengan pemilik alat produksi utamanya.",
        pairs: [
          { left: "Feodalisme", right: "Bangsawan pemilik tanah" },
          { left: "Perbudakan", right: "Tuan pemilik budak" },
          { left: "Kapitalisme", right: "Pemilik modal (kapitalis)" },
          { left: "Sosialisme (ramalan)", right: "Kepemilikan bersama" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: A Contribution to the Critique of Political Economy, 1859",
        html: "Rumusan paling ringkas materialisme historis muncul di kata pengantar <strong>A Contribution to the Critique of Political Economy</strong> (1859). Di sana Marx menulis bahwa 'bukan kesadaran manusia yang menentukan keberadaannya, melainkan keberadaan sosialnya yang menentukan kesadarannya', ide inti bahwa basis ekonomi membentuk suprastruktur.",
      },
      {
        type: "takeaways",
        items: [
          "Materialisme historis: cara produksi menggerakkan sejarah.",
          "Basis (ekonomi) memengaruhi suprastruktur (hukum, politik, ide).",
          "Sejarah dilihat sebagai pergantian mode produksi.",
          "Transisi didorong benturan kekuatan vs hubungan produksi.",
          "Rumusan ringkasnya ada di karya 1859.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut materialisme historis, penggerak utama sejarah adalah?",
            options: ["Ide besar tokoh", "Cara produksi ekonomi", "Kehendak Tuhan", "Iklim"],
            answer: 1,
            explain: "Marx menekankan cara produksi sebagai penggerak sejarah.",
          },
          {
            q: "Hukum, politik, dan agama termasuk?",
            options: ["Basis", "Suprastruktur", "Mode produksi", "Kekuatan produksi"],
            answer: 1,
            explain: "Itu bagian suprastruktur yang dipengaruhi basis ekonomi.",
          },
          {
            q: "Urutan mode produksi menurut Marx (garis besar) adalah?",
            options: [
              "Kapitalis lalu feodal",
              "Feodal lalu kapitalis lalu sosialis (ramalan)",
              "Sosialis lalu feodal",
              "Perbudakan lalu komunal purba",
            ],
            answer: 1,
            explain: "Garis besarnya feodal, kapitalis, lalu ramalan sosialis.",
          },
          {
            q: "Transisi antar-mode produksi didorong oleh?",
            options: [
              "Benturan kekuatan produksi dan hubungan produksi",
              "Pergantian raja",
              "Bencana alam",
              "Perubahan mata uang",
            ],
            answer: 0,
            explain: "Benturan antara kekuatan produksi baru dan hubungan produksi lama.",
          },
          {
            q: "Rumusan ringkas materialisme historis muncul di karya tahun?",
            options: ["1848", "1859", "1867", "1880"],
            answer: 1,
            explain: "A Contribution to the Critique of Political Economy terbit 1859.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sosialisme-utopis-ilmiah",
    levelId: "kritik",
    order: 4,
    title: "Sosialisme Utopis vs Ilmiah",
    summary: "Perbandingan sosialisme utopis (Saint-Simon, Fourier, Owen) yang membayangkan komunitas ideal dengan klaim sosialisme 'ilmiah' Marx-Engels berbasis analisis sejarah.",
    durationMin: 14,
    tags: ["sosialisme utopis", "Owen", "Fourier", "Engels"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum Marx, sejumlah pemikir sudah membayangkan masyarakat tanpa ketimpangan. Marx dan Engels menyebut mereka <strong>sosialis utopis</strong>: mulia niatnya, tetapi menurut Engels lemah karena tidak menjelaskan bagaimana perubahan itu benar-benar terjadi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga tokoh utopis",
        html: "<strong>Henri de Saint-Simon</strong> mengagungkan industri dan sains sebagai penata masyarakat. <strong>Charles Fourier</strong> merancang komunitas kecil bernama <em>falang</em> (phalanstere). <strong>Robert Owen</strong>, pengusaha tekstil, mempraktikkan pabrik yang lebih manusiawi dan mendirikan komunitas percontohan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Klaim 'ilmiah' Marx-Engels",
        html: "Marx dan Engels mengklaim pendekatan mereka <strong>ilmiah</strong>: perubahan tidak datang dari cita-cita moral, melainkan dari <strong>kontradiksi internal kapitalisme</strong> dan perjuangan kelas yang, menurut mereka, dapat dianalisis secara sistematis.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Label 'ilmiah' itu klaim Marx-Engels sendiri, bukan penilaian netral. Banyak ilmuwan sosial menilai ramalan Marx justru tidak teruji, sedangkan sebagian gagasan Owen (koperasi, jam kerja manusiawi) malah berdampak nyata. Baca kedua kubu secara kritis.",
      },
      {
        type: "video",
        comp: "SejarahKapitalismeVideo",
        title: "Video: Impian Masyarakat Adil",
        caption: "Dari komunitas percontohan Owen hingga klaim analisis 'ilmiah' Marx.",
      },
      {
        type: "widget",
        widget: "SimulatorSpektrumEkonomi",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Penekanan: Utopis vs 'Ilmiah' (ilustrasi konsep)",
        unit: "penekanan relatif",
        source: "ilustrasi perbandingan pendekatan",
        note: "Utopis menekankan rancangan komunitas ideal & moral; Marx-Engels menekankan analisis sejarah & perjuangan kelas.",
        data: [
          { label: "Utopis: komunitas & moral", value: 80, color: "#34d399" },
          { label: "Marx-Engels: sejarah & kelas", value: 80, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik New Lanark milik Owen",
        html: "Di pabrik tekstil <strong>New Lanark</strong>, Skotlandia, Robert Owen memangkas jam kerja, melarang anak kecil bekerja, dan menyediakan sekolah serta perumahan layak, namun pabrik tetap untung. Bagi Owen ini bukti bahwa memperlakukan buruh dengan baik bisa sejalan dengan bisnis. Marx menghargai niatnya, tetapi menilai model komunitas kecil tak cukup mengubah struktur kapitalisme secara keseluruhan.",
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini lebih dekat sosialisme utopis atau klaim 'ilmiah' Marx-Engels?",
        buckets: ["Utopis", "Marx-Engels"],
        items: [
          { text: "Membangun komunitas percontohan yang ideal", bucket: "Utopis" },
          { text: "Perubahan lahir dari kontradiksi kapitalisme", bucket: "Marx-Engels" },
          { text: "Merancang falang (phalanstere) kecil", bucket: "Utopis" },
          { text: "Sejarah digerakkan perjuangan kelas", bucket: "Marx-Engels" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh dengan gagasannya.",
        pairs: [
          { left: "Saint-Simon", right: "Industri & sains menata masyarakat" },
          { left: "Fourier", right: "Komunitas falang (phalanstere)" },
          { left: "Owen", right: "Pabrik manusiawi & komunitas percontohan" },
          { left: "Marx-Engels", right: "Sosialisme 'ilmiah' berbasis analisis kelas" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: New Harmony 1825 & istilah dari Engels 1880",
        html: "Pada <strong>1825</strong> Robert Owen mendirikan komunitas percontohan <strong>New Harmony</strong> di Indiana, Amerika Serikat, yang bubar hanya beberapa tahun kemudian karena persoalan internal. Istilah <strong>sosialisme utopis vs ilmiah</strong> sendiri dipopulerkan Friedrich Engels lewat tulisan <em>Socialism: Utopian and Scientific</em> pada <strong>1880</strong>.",
      },
      {
        type: "takeaways",
        items: [
          "Sosialis utopis: Saint-Simon, Fourier, Owen.",
          "Mereka membayangkan komunitas ideal berbasis moral.",
          "Marx-Engels mengklaim pendekatan 'ilmiah' berbasis analisis kelas.",
          "Owen mempraktikkan pabrik manusiawi (New Lanark, New Harmony 1825).",
          "Istilah utopis vs ilmiah dipopulerkan Engels (1880).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Siapa yang bukan tokoh sosialisme utopis?",
            options: ["Saint-Simon", "Fourier", "Owen", "Ricardo"],
            answer: 3,
            explain: "David Ricardo adalah ekonom klasik, bukan sosialis utopis.",
          },
          {
            q: "Komunitas kecil rancangan Fourier disebut?",
            options: ["Falang (phalanstere)", "Polis", "Kibbutz", "Guild"],
            answer: 0,
            explain: "Fourier merancang komunitas bernama falang atau phalanstere.",
          },
          {
            q: "Robert Owen dikenal karena?",
            options: [
              "Teori utilitas marginal",
              "Pabrik manusiawi dan komunitas percontohan",
              "Hukum keunggulan komparatif",
              "Teori kuantitas uang",
            ],
            answer: 1,
            explain: "Owen mempraktikkan pabrik manusiawi (New Lanark) dan komunitas (New Harmony).",
          },
          {
            q: "Klaim 'ilmiah' Marx-Engels menekankan bahwa perubahan lahir dari?",
            options: [
              "Cita-cita moral",
              "Kontradiksi kapitalisme dan perjuangan kelas",
              "Wahyu agama",
              "Kehendak raja",
            ],
            answer: 1,
            explain: "Mereka menekankan kontradiksi internal kapitalisme dan perjuangan kelas.",
          },
          {
            q: "Komunitas New Harmony didirikan Owen pada tahun?",
            options: ["1815", "1825", "1848", "1867"],
            answer: 1,
            explain: "New Harmony didirikan 1825 di Indiana, AS.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mazhab-historis-jerman",
    levelId: "kritik",
    order: 5,
    title: "Mazhab Historis Jerman & Proteksi Industri",
    summary: "Mazhab historis Jerman menolak hukum ekonomi universal; Friedrich List membela proteksi bagi industri muda melawan resep perdagangan bebas ala Ricardo.",
    durationMin: 15,
    tags: ["mazhab historis", "Friedrich List", "proteksi", "industri muda"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi klasik Inggris menganggap hukum ekonominya berlaku di mana saja dan kapan saja. Di Jerman abad ke-19, sekelompok pemikir menolak itu: menurut mereka ekonomi harus dipahami lewat <strong>sejarah dan konteks tiap bangsa</strong>, bukan rumus universal.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mazhab historis Jerman",
        html: "Tokoh seperti <strong>Wilhelm Roscher</strong> dan <strong>Gustav Schmoller</strong> menekankan bahwa institusi, budaya, dan tahap perkembangan berbeda antarbangsa. Karena itu resep yang cocok untuk Inggris yang sudah maju belum tentu cocok untuk negara yang baru berindustri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Argumen industri muda List",
        html: "<strong>Friedrich List</strong> membela <strong>proteksi industri muda</strong> (<em>infant industry</em>): industri baru di negara yang tertinggal perlu tarif sementara agar bisa tumbuh sebelum bersaing dengan raksasa asing. Setelah kuat, proteksi bisa dilepas. Ini menantang resep <strong>perdagangan bebas</strong> Ricardo.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Argumen industri muda punya sisi rawan: proteksi sering sulit dicabut dan bisa memanjakan industri yang tak kunjung efisien. Keunggulan komparatif Ricardo tetap menjelaskan manfaat spesialisasi. Debat proteksi vs perdagangan bebas ini masih hidup sampai kini.",
      },
      {
        type: "video",
        comp: "GarisWaktuEkonomiVideo",
        title: "Video: Perdagangan Bebas vs Proteksi",
        caption: "List menantang Ricardo: negara yang tertinggal perlu melindungi industri mudanya dulu.",
      },
      {
        type: "widget",
        widget: "SimulatorKeunggulanKomparatif",
      },
      {
        type: "chart",
        variant: "line",
        title: "Ide Industri Muda: Biaya Produksi Menurun seiring Pengalaman (ilustrasi)",
        unit: "biaya per unit (indeks)",
        source: "ilustrasi argumen infant industry",
        note: "Argumen List: dengan proteksi sementara, industri baru belajar dan biayanya turun hingga mampu bersaing.",
        data: [
          { label: "Tahun 1", value: 100, color: "#fb7185" },
          { label: "Tahun 3", value: 82, color: "#fbbf24" },
          { label: "Tahun 5", value: 68, color: "#a3e635" },
          { label: "Tahun 7", value: 58, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Jerman menyusul Inggris",
        html: "Pada awal abad ke-19, industri Inggris jauh di depan. Negara-negara Jerman masih terpecah dan tertinggal. List berpendapat perdagangan bebas total justru akan mengunci Jerman sebagai pemasok bahan mentah. Ia mendorong <strong>Zollverein</strong> (uni bea cukai antar-negara Jerman, mulai <strong>1834</strong>) yang menghapus tarif internal tetapi melindungi dari luar. Industri Jerman kemudian tumbuh pesat.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya produksi turun dari indeks 100 menjadi 68 setelah beberapa tahun. Berapa persen penurunannya?",
        answer: 32,
        tolerance: 0,
        suffix: "%",
        solution: "Penurunan = (100 - 68) / 100 x 100% = <strong>32%</strong>.",
        hint: "Selisih dibagi nilai awal, dikali 100%.",
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini condong ke List (proteksi industri muda) atau Ricardo (perdagangan bebas)?",
        buckets: ["List", "Ricardo"],
        items: [
          { text: "Industri baru perlu tarif sementara agar bisa tumbuh", bucket: "List" },
          { text: "Spesialisasi sesuai keunggulan komparatif menguntungkan semua", bucket: "Ricardo" },
          { text: "Hukum ekonomi harus menyesuaikan tahap perkembangan bangsa", bucket: "List" },
          { text: "Perdagangan bebas memaksimalkan output dunia", bucket: "Ricardo" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: The National System of Political Economy, 1841",
        html: "Friedrich List merumuskan gagasannya dalam <strong>The National System of Political Economy</strong> (Das nationale System der politischen Oekonomie) pada <strong>1841</strong>. Ia berargumen bahwa 'kekuatan produktif' bangsa lebih penting daripada nilai tukar sesaat, dan bahwa negara yang tertinggal berhak melindungi industrinya sampai mampu bersaing. Buku ini kelak sering dikutip negara-negara yang sedang mengejar industrialisasi.",
      },
      {
        type: "takeaways",
        items: [
          "Mazhab historis Jerman menolak hukum ekonomi universal.",
          "Roscher dan Schmoller menekankan sejarah dan konteks bangsa.",
          "Friedrich List membela proteksi industri muda.",
          "List menantang resep perdagangan bebas Ricardo.",
          "Karya utama List terbit 1841.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mazhab historis Jerman menolak?",
            options: [
              "Adanya perdagangan",
              "Hukum ekonomi universal yang berlaku di mana saja",
              "Penggunaan uang",
              "Peran pemerintah",
            ],
            answer: 1,
            explain: "Mereka menolak klaim hukum ekonomi universal, menekankan konteks sejarah.",
          },
          {
            q: "Argumen 'industri muda' Friedrich List membela?",
            options: [
              "Perdagangan bebas total",
              "Proteksi sementara bagi industri baru",
              "Penghapusan semua pajak",
              "Standar emas",
            ],
            answer: 1,
            explain: "List membela tarif sementara agar industri baru bisa tumbuh.",
          },
          {
            q: "List menantang resep perdagangan bebas dari?",
            options: ["Keynes", "Ricardo", "Veblen", "Owen"],
            answer: 1,
            explain: "Ia menantang keunggulan komparatif dan perdagangan bebas Ricardo.",
          },
          {
            q: "Uni bea cukai antar-negara Jerman yang didukung List disebut?",
            options: ["Zollverein", "Bundestag", "Hansa", "Reichsbank"],
            answer: 0,
            explain: "Zollverein, uni bea cukai yang mulai 1834.",
          },
          {
            q: "Karya utama List, The National System of Political Economy, terbit tahun?",
            options: ["1817", "1841", "1867", "1890"],
            answer: 1,
            explain: "Terbit 1841.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "institusionalisme-veblen",
    levelId: "kritik",
    order: 6,
    title: "Institusionalisme: Veblen",
    summary: "Thorstein Veblen menyoroti peran lembaga dan kebiasaan, memperkenalkan konsumsi status (conspicuous consumption), dan mengkritik gambaran manusia yang selalu rasional.",
    durationMin: 14,
    tags: ["institusionalisme", "Veblen", "conspicuous consumption", "lembaga"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi neoklasik mengandaikan manusia sebagai penghitung untung-rugi yang rasional. <strong>Thorstein Veblen</strong> menolak gambaran itu. Baginya perilaku ekonomi dibentuk <strong>lembaga, kebiasaan, dan gengsi sosial</strong>, bukan sekadar kalkulasi utilitas.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Veblen3a.jpg?width=400",
        alt: "Potret Thorstein Veblen",
        caption: "Thorstein Veblen (1857-1929).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Konsumsi status",
        html: "Veblen memperkenalkan <strong>konsumsi status</strong> (<em>conspicuous consumption</em>): orang membeli barang mahal bukan karena butuh, melainkan untuk <strong>menunjukkan status</strong>. Ada pula <em>efek Veblen</em>, ketika barang justru makin diminati saat harganya makin mahal.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran lembaga & kebiasaan",
        html: "Institusionalisme melihat ekonomi sebagai proses yang tumbuh dari <strong>lembaga</strong> (aturan, adat, organisasi) dan <strong>kebiasaan</strong> yang berubah perlahan. Ekonomi bukan mesin keseimbangan yang statis, melainkan sistem yang berevolusi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Kritik Veblen tajam, tetapi ia lemah dalam menawarkan model formal yang bisa diuji dan diramalkan. Ekonomi arus utama justru berkembang lewat model matematis. Belakangan, ekonomi perilaku mempertemukan keduanya: mengakui manusia tak selalu rasional, tetapi tetap menguji datanya.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Belanja demi Gengsi",
        caption: "Veblen: konsumsi sering soal status sosial, bukan cuma kebutuhan.",
      },
      {
        type: "widget",
        widget: "KalkulatorGini",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Motif Membeli Barang Mewah (ilustrasi konsep)",
        unit: "penekanan relatif",
        source: "ilustrasi konsep conspicuous consumption",
        note: "Veblen menyoroti bahwa sebagian besar daya tarik barang mewah adalah sinyal status, bukan fungsi.",
        data: [
          { label: "Fungsi/kebutuhan nyata", value: 30, color: "#60a5fa" },
          { label: "Status & gengsi sosial", value: 85, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tas mahal & efek Veblen",
        html: "Sebuah tas edisi terbatas dijual <strong>Rp80 juta</strong>, jauh di atas biaya bahan dan jahitannya. Secara fungsi, tas Rp1 juta pun cukup membawa barang. Namun bagi sebagian pembeli, harga tinggi justru <strong>menaikkan</strong> daya tarik karena menandakan status. Inilah efek Veblen: permintaan naik seiring harga, kebalikan dari hukum permintaan biasa.",
      },
      {
        type: "calcExercise",
        prompt: "Tas dijual Rp80 juta, biaya produksinya Rp5 juta. Berapa juta rupiah selisih harga di atas biaya produksi?",
        answer: 75,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Selisih = 80 - 5 = <strong>Rp75 juta</strong>, sebagian besar adalah nilai status, bukan fungsi.",
        hint: "Kurangkan biaya produksi dari harga jual.",
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini lebih dekat institusionalisme Veblen atau neoklasik?",
        buckets: ["Veblen", "Neoklasik"],
        items: [
          { text: "Konsumsi banyak didorong gengsi dan status", bucket: "Veblen" },
          { text: "Individu memaksimalkan utilitas secara rasional", bucket: "Neoklasik" },
          { text: "Lembaga dan kebiasaan membentuk perilaku ekonomi", bucket: "Veblen" },
          { text: "Harga terbentuk dari perpotongan permintaan dan penawaran", bucket: "Neoklasik" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: The Theory of the Leisure Class, 1899",
        html: "Veblen memperkenalkan istilah <strong>conspicuous consumption</strong> dalam <strong>The Theory of the Leisure Class</strong> (1899). Ia mengamati bahwa kelas kaya memamerkan kekayaan lewat konsumsi dan waktu luang yang mencolok sebagai penanda status. Buku ini menjadi klasik dan menandai lahirnya aliran <strong>institusionalisme</strong> dalam ilmu ekonomi.",
      },
      {
        type: "takeaways",
        items: [
          "Institusionalisme (Veblen) menyoroti lembaga dan kebiasaan.",
          "Konsumsi status (conspicuous consumption): beli demi gengsi.",
          "Efek Veblen: permintaan bisa naik saat harga naik.",
          "Veblen mengkritik asumsi manusia selalu rasional.",
          "Istilahnya lahir di The Theory of the Leisure Class (1899).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Conspicuous consumption berarti?",
            options: [
              "Konsumsi hemat",
              "Konsumsi demi menunjukkan status",
              "Konsumsi barang pokok",
              "Konsumsi pemerintah",
            ],
            answer: 1,
            explain: "Konsumsi mencolok untuk memamerkan status sosial.",
          },
          {
            q: "Veblen mengkritik asumsi bahwa manusia?",
            options: [
              "Selalu rasional memaksimalkan utilitas",
              "Punya kebiasaan",
              "Hidup dalam lembaga",
              "Bekerja untuk upah",
            ],
            answer: 0,
            explain: "Ia menolak gambaran manusia yang selalu rasional.",
          },
          {
            q: "Efek Veblen adalah ketika?",
            options: [
              "Permintaan turun saat harga naik",
              "Permintaan naik saat harga naik (karena status)",
              "Harga selalu tetap",
              "Penawaran naik saat harga turun",
            ],
            answer: 1,
            explain: "Barang justru lebih diminati saat harganya makin tinggi.",
          },
          {
            q: "Institusionalisme menekankan peran?",
            options: ["Utilitas marginal", "Lembaga dan kebiasaan", "Tangan tak tampak", "Standar emas"],
            answer: 1,
            explain: "Lembaga, adat, dan kebiasaan yang berevolusi.",
          },
          {
            q: "The Theory of the Leisure Class terbit tahun?",
            options: ["1867", "1890", "1899", "1936"],
            answer: 2,
            explain: "Terbit 1899 karya Thorstein Veblen.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kritik-ketimpangan-hari-ini",
    levelId: "kritik",
    order: 7,
    title: "Warisan Kritik: Ketimpangan Hari Ini",
    summary: "Perhatian pada distribusi dan konsentrasi modal tetap relevan; Thomas Piketty (2013) menghidupkannya lagi lewat tesis r > g, disajikan sebagai debat terbuka.",
    durationMin: 15,
    tags: ["ketimpangan", "Piketty", "distribusi", "modal"],
    blocks: [
      {
        type: "paragraph",
        html: "Banyak resep Marx ditinggalkan, tetapi satu pertanyaannya bertahan: <strong>bagaimana hasil ekonomi dibagi?</strong> Setelah lama terpinggirkan, isu distribusi dan konsentrasi kekayaan kembali jadi pusat perhatian di abad ke-21.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tesis r > g Piketty",
        html: "Ekonom Prancis <strong>Thomas Piketty</strong> berargumen bahwa bila <strong>tingkat imbal hasil modal (r)</strong> lebih tinggi daripada <strong>laju pertumbuhan ekonomi (g)</strong>, maka kekayaan cenderung menumpuk pada pemilik modal lebih cepat daripada pendapatan tumbuh, sehingga ketimpangan membesar. Ringkasnya: <strong>r &gt; g</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bukan mengulang Marx",
        html: "Piketty tidak menyerukan penghapusan pasar. Ia memakai <strong>data historis</strong> lintas negara dan mengusulkan kebijakan seperti <strong>pajak progresif</strong> atas kekayaan. Fokusnya pada pengukuran empiris, bukan ramalan keruntuhan kapitalisme.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Sebuah debat, bukan vonis",
        html: "Kritikus menilai r &gt; g terlalu menyederhanakan: r tidak tetap, inovasi dan mobilitas dapat menekan ketimpangan, dan pajak kekayaan global sulit diterapkan. Pendukung menilai datanya membuka mata. Sajikan ini sebagai <strong>debat terbuka</strong>, bukan kesimpulan final.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Ketimpangan di Abad Modern",
        caption: "Isu distribusi kembali ke panggung utama lewat data, bukan ideologi semata.",
      },
      {
        type: "widget",
        widget: "KalkulatorGini",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Skema r vs g: Kapan Ketimpangan Membesar? (ilustrasi konsep)",
        unit: "persen per tahun",
        source: "ilustrasi tesis Piketty r > g",
        note: "Bila imbal hasil modal (r) melampaui pertumbuhan ekonomi (g), kekayaan pemilik modal tumbuh lebih cepat daripada rata-rata.",
        data: [
          { label: "r: imbal hasil modal", value: 5, color: "#fb7185" },
          { label: "g: pertumbuhan ekonomi", value: 2, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Ketika r melampaui g",
        html: "Misalkan imbal hasil modal <strong>r = 5%</strong> per tahun, sedangkan pertumbuhan ekonomi <strong>g = 2%</strong>. Pemilik modal besar melihat kekayaannya tumbuh 5% setahun, sementara upah rata-rata (mengikuti g) hanya tumbuh 2%. Selisih <strong>3 poin persen</strong> ini, bila bertahan puluhan tahun, membuat porsi kekayaan makin terkonsentrasi. Inilah mekanisme yang disorot Piketty.",
      },
      {
        type: "calcExercise",
        prompt: "Jika imbal hasil modal r = 5% dan pertumbuhan ekonomi g = 2%, berapa poin persen selisih r dikurangi g?",
        answer: 3,
        tolerance: 0,
        suffix: " poin persen",
        solution: "r - g = 5% - 2% = <strong>3 poin persen</strong>. Selisih positif inilah yang, menurut Piketty, mendorong ketimpangan.",
        hint: "Kurangkan g dari r.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini mendukung atau mengkritik tesis Piketty?",
        buckets: ["Mendukung", "Mengkritik"],
        items: [
          { text: "Data menunjukkan modal menumpuk lebih cepat dari upah", bucket: "Mendukung" },
          { text: "Imbal hasil modal r tidak selalu tetap tinggi", bucket: "Mengkritik" },
          { text: "Pajak progresif kekayaan dapat menekan ketimpangan", bucket: "Mendukung" },
          { text: "Inovasi dan mobilitas bisa mengurangi ketimpangan sendiri", bucket: "Mengkritik" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Capital in the Twenty-First Century, 2013",
        html: "Thomas Piketty menerbitkan <strong>Le Capital au XXIe siecle</strong> pada <strong>2013</strong> (edisi Inggris <em>Capital in the Twenty-First Century</em>, <strong>2014</strong>). Berbasis data pajak dan kekayaan berabad-abad, buku ini menjadi laris secara mengejutkan untuk karya ekonomi dan menghidupkan kembali perdebatan tentang distribusi yang sempat surut sejak era klasik dan Marx.",
      },
      {
        type: "takeaways",
        items: [
          "Isu distribusi dan konsentrasi modal kembali relevan di abad ke-21.",
          "Piketty: bila r > g, ketimpangan cenderung membesar.",
          "Ia memakai data historis, bukan ramalan keruntuhan.",
          "Usulannya antara lain pajak progresif atas kekayaan.",
          "Sajikan sebagai debat terbuka; kritik atasnya juga kuat.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tesis inti Piketty diringkas sebagai?",
            options: ["g > r", "r > g", "r = g", "r + g = 0"],
            answer: 1,
            explain: "Bila r (imbal hasil modal) lebih besar dari g (pertumbuhan), ketimpangan membesar.",
          },
          {
            q: "Dalam r > g, huruf g melambangkan?",
            options: [
              "Imbal hasil modal",
              "Laju pertumbuhan ekonomi",
              "Tingkat pajak",
              "Rasio Gini",
            ],
            answer: 1,
            explain: "g adalah laju pertumbuhan ekonomi; r adalah imbal hasil modal.",
          },
          {
            q: "Jika r = 5% dan g = 2%, selisih r - g adalah?",
            options: ["2 poin persen", "3 poin persen", "5 poin persen", "7 poin persen"],
            answer: 1,
            explain: "5% - 2% = 3 poin persen.",
          },
          {
            q: "Usulan kebijakan yang diasosiasikan dengan Piketty adalah?",
            options: [
              "Menghapus pasar",
              "Pajak progresif atas kekayaan",
              "Standar emas",
              "Menghentikan perdagangan",
            ],
            answer: 1,
            explain: "Ia mengusulkan pajak progresif atas kekayaan, bukan penghapusan pasar.",
          },
          {
            q: "Capital in the Twenty-First Century (edisi Prancis) terbit tahun?",
            options: ["1999", "2008", "2013", "2020"],
            answer: 2,
            explain: "Edisi Prancis terbit 2013; edisi Inggris 2014.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "rosa-luxemburg-akumulasi",
    levelId: "kritik",
    order: 8,
    title: "Rosa Luxemburg & Akumulasi Kapital",
    summary: "Rosa Luxemburg berpendapat kapitalisme butuh pasar dan wilayah non-kapitalis baru untuk menyerap kelebihan produksi, sehingga cenderung berekspansi dan mendorong imperialisme.",
    durationMin: 15,
    tags: ["Rosa Luxemburg", "akumulasi", "imperialisme", "pasar"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah Marx, sejumlah pemikir mencoba menjawab pertanyaan yang ia tinggalkan: jika buruh dibayar kurang dari nilai yang mereka ciptakan, <strong>siapa yang akan membeli seluruh barang</strong> yang diproduksi? <strong>Rosa Luxemburg</strong> menjawab bahwa kapitalisme tidak bisa menyerap semua hasilnya sendiri, sehingga harus terus mencari pasar baru di luar dirinya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_Luxemburg.jpg?width=400",
        alt: "Potret Rosa Luxemburg",
        caption: "Rosa Luxemburg (1871-1919).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Butuh pasar di luar dirinya",
        html: "Menurut Luxemburg, karena upah buruh tak cukup untuk membeli semua barang, ada <strong>kelebihan produksi (surplus)</strong> yang tidak terserap di dalam ekonomi kapitalis. Untuk mewujudkan laba dari surplus itu, kapitalisme harus menjualnya ke <strong>wilayah non-kapitalis</strong>: pedesaan, ekonomi pra-industri, dan koloni.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dari akumulasi ke imperialisme",
        html: "Konsekuensinya, kapitalisme cenderung <strong>berekspansi terus</strong> mencari pasar dan sumber bahan mentah baru. Bagi Luxemburg, inilah akar ekonomi <strong>imperialisme</strong>: perebutan wilayah jajahan bukan sekadar politik, melainkan kebutuhan struktural sistem untuk melanjutkan akumulasi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Banyak ekonom, termasuk sesama Marxis, menilai argumen 'kurang konsumsi' Luxemburg keliru secara teknis: kredit, investasi, dan pertumbuhan upah dapat menyerap surplus tanpa perlu koloni. Namun perhatiannya pada <strong>ekspansi dan globalisasi</strong> kapital tetap dianggap tajam. Baca sebagai lensa, bukan hukum pasti.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Mengapa Kapital Terus Melebar",
        caption: "Luxemburg: kelebihan produksi mendorong kapitalisme mencari pasar baru di luar dirinya.",
      },
      {
        type: "widget",
        widget: "KalkulatorGini",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Kemana Barang Diserap menurut Luxemburg (ilustrasi konsep)",
        unit: "penyerapan relatif",
        source: "ilustrasi kerangka akumulasi Luxemburg",
        note: "Karena upah domestik tak cukup menyerap semua barang, sebagian surplus harus dijual ke wilayah non-kapitalis.",
        data: [
          { label: "Diserap upah buruh domestik", value: 40, color: "#34d399" },
          { label: "Diserap konsumsi pemilik modal", value: 20, color: "#60a5fa" },
          { label: "Harus dijual ke pasar non-kapitalis", value: 40, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Surplus yang harus keluar",
        html: "Sebuah ekonomi memproduksi barang senilai <strong>Rp1.000 miliar</strong>. Upah buruh total hanya <strong>Rp600 miliar</strong> dan konsumsi pemilik modal <strong>Rp200 miliar</strong>. Berarti ada <strong>Rp200 miliar</strong> barang yang tidak terbeli di dalam negeri. Menurut Luxemburg, surplus Rp200 miliar inilah yang mendorong sistem mencari pembeli di pasar non-kapitalis, misalnya lewat ekspor ke koloni.",
      },
      {
        type: "calcExercise",
        prompt: "Produksi Rp1.000 miliar, upah buruh Rp600 miliar, konsumsi pemilik modal Rp200 miliar. Berapa miliar rupiah surplus yang tak terserap di dalam negeri?",
        answer: 200,
        tolerance: 0,
        prefix: "Rp",
        suffix: " miliar",
        solution: "Surplus = 1.000 - 600 - 200 = <strong>Rp200 miliar</strong> yang, menurut Luxemburg, harus dijual ke pasar non-kapitalis.",
        hint: "Kurangkan upah dan konsumsi pemilik modal dari total produksi.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini sejalan dengan Luxemburg atau merupakan kritik terhadapnya?",
        buckets: ["Sejalan Luxemburg", "Kritik"],
        items: [
          { text: "Kapitalisme perlu pasar non-kapitalis untuk menyerap surplus", bucket: "Sejalan Luxemburg" },
          { text: "Imperialisme berakar pada kebutuhan akumulasi modal", bucket: "Sejalan Luxemburg" },
          { text: "Kredit dan investasi bisa menyerap surplus tanpa koloni", bucket: "Kritik" },
          { text: "Kenaikan upah dapat memperbesar daya beli domestik", bucket: "Kritik" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: The Accumulation of Capital, 1913",
        html: "Rosa Luxemburg menerbitkan <strong>Die Akkumulation des Kapitals</strong> (<em>The Accumulation of Capital</em>) pada <strong>1913</strong>. Di dalamnya ia berargumen bahwa akumulasi kapital mustahil berlangsung dalam ekonomi kapitalis murni yang tertutup, sehingga sistem selalu memerlukan lingkungan non-kapitalis. Luxemburg, seorang tokoh sosialis Jerman kelahiran Polandia, kelak dibunuh pada <strong>1919</strong> di tengah gejolak revolusi Jerman.",
      },
      {
        type: "takeaways",
        items: [
          "Luxemburg: upah buruh tak cukup menyerap semua barang yang diproduksi.",
          "Surplus produksi mendorong kapitalisme mencari pasar di luar dirinya.",
          "Ia mengaitkan kebutuhan akumulasi ini dengan akar imperialisme.",
          "Kritikus menilai argumen 'kurang konsumsi' ini secara teknis lemah.",
          "Karya utamanya, The Accumulation of Capital, terbit 1913.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Luxemburg, mengapa kapitalisme perlu pasar baru?",
            options: [
              "Karena buruh terlalu kaya",
              "Karena upah buruh tak cukup menyerap semua barang yang diproduksi",
              "Karena pemerintah melarang ekspor",
              "Karena harga selalu turun",
            ],
            answer: 1,
            explain: "Ada surplus produksi yang tak terbeli di dalam negeri, sehingga dicari pasar di luar.",
          },
          {
            q: "Luxemburg mengaitkan kebutuhan akumulasi modal dengan?",
            options: ["Standar emas", "Imperialisme", "Deflasi", "Serikat buruh"],
            answer: 1,
            explain: "Ekspansi mencari pasar dan bahan mentah menjadi akar ekonomi imperialisme.",
          },
          {
            q: "Wilayah tempat surplus dijual menurut Luxemburg adalah?",
            options: [
              "Sesama negara kapitalis maju saja",
              "Wilayah non-kapitalis seperti pedesaan dan koloni",
              "Bank sentral",
              "Pasar saham",
            ],
            answer: 1,
            explain: "Ekonomi non-kapitalis dianggap tempat menyerap kelebihan produksi.",
          },
          {
            q: "Produksi Rp500 miliar, upah Rp300 miliar, konsumsi pemilik modal Rp100 miliar. Surplus tak terserap?",
            options: ["Rp100 miliar", "Rp200 miliar", "Rp300 miliar", "Rp400 miliar"],
            answer: 0,
            explain: "500 - 300 - 100 = Rp100 miliar.",
          },
          {
            q: "The Accumulation of Capital terbit tahun?",
            options: ["1867", "1899", "1913", "1936"],
            answer: 2,
            explain: "Karya utama Rosa Luxemburg ini terbit 1913.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mazhab-frankfurt-teori-kritis",
    levelId: "kritik",
    order: 9,
    title: "Mazhab Frankfurt & Teori Kritis",
    summary: "Adorno, Horkheimer, dan Marcuse mengembangkan teori kritis: kritik atas komodifikasi budaya lewat konsep industri budaya, dan bagaimana konsumsi massal membentuk kesadaran.",
    durationMin: 15,
    tags: ["Mazhab Frankfurt", "teori kritis", "industri budaya", "Marcuse"],
    blocks: [
      {
        type: "paragraph",
        html: "Kritik atas kapitalisme tidak berhenti pada ekonomi. Sekelompok pemikir di Jerman, yang dikenal sebagai <strong>Mazhab Frankfurt</strong>, memperluasnya ke budaya, media, dan cara berpikir. Mereka bertanya: jika kapitalisme begitu timpang, mengapa banyak orang justru menerimanya dengan senang hati?",
      },
      {
        type: "callout",
        tone: "key",
        title: "Industri budaya",
        html: "<strong>Theodor Adorno</strong> dan <strong>Max Horkheimer</strong> memperkenalkan istilah <strong>industri budaya</strong> (<em>culture industry</em>): film, musik populer, dan hiburan massal diproduksi seperti barang pabrik yang seragam. Menurut mereka, budaya berubah menjadi <strong>komoditas</strong> yang menstandarkan selera dan meredam sikap kritis.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Konsumsi membentuk kesadaran",
        html: "<strong>Herbert Marcuse</strong> berargumen konsumsi massal menciptakan <strong>kebutuhan palsu</strong>: orang merasa bebas karena bisa memilih banyak produk, padahal pilihan itu dangkal. Kepuasan berbelanja membuat orang <strong>puas dengan sistem</strong> dan kehilangan daya untuk membayangkan alternatif. Ia menyebutnya manusia 'satu dimensi'.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan berimbang",
        html: "Kritik ini sering dinilai <strong>terlalu elitis</strong>: menganggap selera massa pasif dan mudah dibodohi, padahal riset media menunjukkan penonton kerap menafsir dan menolak pesan secara aktif. Teori kritis kuat sebagai pengingat, tetapi lemah dalam prediksi yang bisa diuji. Baca kritis, jangan telan bulat.",
      },
      {
        type: "video",
        comp: "SejarahKapitalismeVideo",
        title: "Video: Ketika Budaya Jadi Barang",
        caption: "Mazhab Frankfurt: hiburan massal bisa meredam sikap kritis, bukan sekadar menghibur.",
      },
      {
        type: "widget",
        widget: "SimulatorSpektrumEkonomi",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Kebutuhan Sejati vs Kebutuhan Palsu menurut Marcuse (ilustrasi konsep)",
        unit: "penekanan relatif",
        source: "ilustrasi konsep kebutuhan palsu Marcuse",
        note: "Marcuse membedakan kebutuhan dasar yang nyata dari kebutuhan yang ditanamkan iklan dan konsumsi massal.",
        data: [
          { label: "Kebutuhan sejati (pangan, tempat tinggal)", value: 45, color: "#34d399" },
          { label: "Kebutuhan palsu (ditanamkan iklan)", value: 80, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung 'kebutuhan palsu'",
        html: "Seseorang berpenghasilan <strong>Rp5 juta</strong> per bulan. Untuk kebutuhan pokok (makan, sewa, transportasi) ia habiskan <strong>Rp3 juta</strong>. Sisanya <strong>Rp2 juta</strong> habis untuk gawai model terbaru, langganan hiburan, dan barang bermerek yang didorong iklan. Bagi Marcuse, sebagian besar Rp2 juta itu adalah pemenuhan <strong>kebutuhan palsu</strong>: memberi kepuasan sesaat sekaligus mengikat orang lebih erat pada sistem konsumsi.",
      },
      {
        type: "calcExercise",
        prompt: "Penghasilan Rp5 juta, kebutuhan pokok Rp3 juta. Berapa juta rupiah sisa yang, menurut Marcuse, rawan jadi konsumsi kebutuhan palsu?",
        answer: 2,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Sisa = 5 - 3 = <strong>Rp2 juta</strong>, bagian yang menurut Marcuse rentan diarahkan ke kebutuhan palsu.",
        hint: "Kurangkan kebutuhan pokok dari penghasilan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh atau istilah dengan gagasannya.",
        pairs: [
          { left: "Adorno & Horkheimer", right: "Industri budaya (culture industry)" },
          { left: "Marcuse", right: "Kebutuhan palsu & manusia satu dimensi" },
          { left: "Komodifikasi budaya", right: "Budaya diproduksi & dijual seperti barang" },
          { left: "Teori kritis", right: "Kritik masyarakat untuk membuka jalan perubahan" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini sejalan dengan Mazhab Frankfurt atau merupakan kritik terhadapnya?",
        buckets: ["Mazhab Frankfurt", "Kritik"],
        items: [
          { text: "Hiburan massal seragam meredam sikap kritis", bucket: "Mazhab Frankfurt" },
          { text: "Konsumsi menciptakan kebutuhan palsu", bucket: "Mazhab Frankfurt" },
          { text: "Penonton aktif menafsir dan menolak pesan media", bucket: "Kritik" },
          { text: "Menganggap selera massa pasif terlalu elitis", bucket: "Kritik" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Institut Frankfurt 1923 & Dialectic of Enlightenment 1947",
        html: "<strong>Institut Penelitian Sosial</strong> (Institut fuer Sozialforschung) di Frankfurt berdiri pada <strong>1923</strong> dan menjadi rumah bagi teori kritis. Saat Nazi berkuasa, banyak tokohnya mengungsi ke Amerika Serikat. Di masa itu Adorno dan Horkheimer menulis <strong>Dialectic of Enlightenment</strong> (Dialektik der Aufklaerung), yang terbit pada <strong>1947</strong> dan memuat bab termasyhur tentang industri budaya.",
      },
      {
        type: "takeaways",
        items: [
          "Mazhab Frankfurt memperluas kritik kapitalisme ke budaya dan kesadaran.",
          "Adorno & Horkheimer: industri budaya menstandarkan selera dan meredam kritik.",
          "Marcuse: konsumsi massal menciptakan kebutuhan palsu (manusia satu dimensi).",
          "Kritik: pendekatan ini dinilai terlalu elitis dan sulit diuji.",
          "Institut Frankfurt berdiri 1923; Dialectic of Enlightenment terbit 1947.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Istilah 'industri budaya' diperkenalkan oleh?",
            options: [
              "Ricardo & Malthus",
              "Adorno & Horkheimer",
              "Saint-Simon & Fourier",
              "Piketty & Veblen",
            ],
            answer: 1,
            explain: "Adorno dan Horkheimer memperkenalkan konsep culture industry.",
          },
          {
            q: "Menurut Marcuse, konsumsi massal menciptakan?",
            options: [
              "Kebutuhan palsu",
              "Standar emas",
              "Keunggulan komparatif",
              "Nilai lebih",
            ],
            answer: 0,
            explain: "Marcuse menyebut kebutuhan palsu yang membuat manusia menjadi 'satu dimensi'.",
          },
          {
            q: "Kritik utama terhadap Mazhab Frankfurt adalah bahwa mereka?",
            options: [
              "Terlalu memuji pasar bebas",
              "Menganggap selera massa pasif (terlalu elitis)",
              "Mengabaikan sejarah",
              "Menolak semua budaya",
            ],
            answer: 1,
            explain: "Mereka dinilai meremehkan kemampuan penonton menafsir dan menolak pesan.",
          },
          {
            q: "Institut Penelitian Sosial di Frankfurt berdiri tahun?",
            options: ["1899", "1913", "1923", "1947"],
            answer: 2,
            explain: "Institut fuer Sozialforschung berdiri 1923.",
          },
          {
            q: "Dialectic of Enlightenment karya Adorno & Horkheimer terbit tahun?",
            options: ["1923", "1936", "1947", "1968"],
            answer: 2,
            explain: "Dialectic of Enlightenment terbit 1947.",
          },
        ],
      },
    ],
  },
];
