import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "mekanisme-perdagangan-saham",
    levelId: "saham",
    order: 1,
    title: "Mekanisme Perdagangan Saham",
    summary: "Bagaimana order beli dan jual dicocokkan di bursa: bid, ask, lot, spread, dan T+2. Dengan video & simulator.",
    durationMin: 14,
    tags: ["saham", "bursa", "order book", "T+2"],
    blocks: [
      {
        type: "paragraph",
        html: "Di <strong>bursa efek</strong> (di Indonesia: BEI), saham diperdagangkan lewat sistem yang mencocokkan <strong>order beli (bid)</strong> dan <strong>order jual (ask)</strong> secara otomatis. Transaksi terjadi saat harga keduanya bertemu, mengikuti prioritas harga dan waktu.",
      },
      {
        type: "video",
        comp: "MekanismePerdaganganSaham",
        title: "Video: Order Book & Pencocokan Order",
        caption: "Animasi antrean bid dan ask serta bagaimana transaksi terjadi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Istilah dasar",
        html: "<strong>Bid</strong>: harga tertinggi yang mau dibayar pembeli. <strong>Ask</strong>: harga terendah yang diminta penjual. <strong>Spread</strong>: selisih keduanya. <strong>Lot</strong>: satuan perdagangan (1 lot = 100 lembar di BEI).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Penyelesaian T+2",
        html: "Setelah transaksi terjadi (matched), penyelesaian dana dan kepemilikan saham terjadi pada <strong>T+2</strong>, yaitu dua hari bursa setelah transaksi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pasang order beli atau jual pada harga tertentu, lihat apakah langsung tereksekusi atau masuk antrean menunggu lawan.",
      },
      { type: "widget", widget: "SimulatorOrderBook" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Antrean Order Book (lot)",
        unit: "lot",
        source: "ilustrasi edukatif",
        note: "Bid tertinggi (1.000) dan ask terendah (1.005) membentuk spread; transaksi terjadi saat keduanya bertemu.",
        data: [
          { label: "Bid 990", value: 200, color: "#10b981" },
          { label: "Bid 995", value: 120, color: "#34d399" },
          { label: "Bid 1.000", value: 50, color: "#6ee7b7" },
          { label: "Ask 1.005", value: 80, color: "#fca5a5" },
          { label: "Ask 1.010", value: 140, color: "#f87171" },
          { label: "Ask 1.015", value: 90, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Order limit vs langsung",
        html: "Andi ingin membeli 10 lot saham. Best ask (jual terendah) di Rp1.005. Jika Andi pasang order beli di <strong>Rp1.005</strong>, langsung tereksekusi. Jika ia pasang di <strong>Rp1.000</strong> (limit), ordernya masuk antrean dan baru terisi bila ada penjual mau melepas di Rp1.000. Order limit memberi kendali harga, tetapi belum tentu langsung terjadi.",
      },
      {
        type: "calcExercise",
        prompt: "Andi membeli 10 lot saham di harga Rp1.005 (1 lot = 100 lembar). Berapa nilai transaksinya?",
        answer: 1005000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai = 10 lot x 100 lembar x Rp1.005 = <strong>Rp1.005.000</strong> (belum termasuk biaya broker).",
        hint: "Kalikan jumlah lot, 100 lembar per lot, dan harga.",
      },
      {
        type: "classifyExercise",
        prompt: "Istilah ini terkait sisi beli atau jual?",
        buckets: ["Sisi beli (bid)", "Sisi jual (ask/offer)"],
        items: [
          { text: "Harga tertinggi yang mau dibayar", bucket: "Sisi beli (bid)" },
          { text: "Harga terendah yang diminta penjual", bucket: "Sisi jual (ask/offer)" },
          { text: "Antrean permintaan beli", bucket: "Sisi beli (bid)" },
          { text: "Antrean penawaran jual", bucket: "Sisi jual (ask/offer)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Black Monday 1987 dan lahirnya circuit breaker",
        html: "Mekanisme perdagangan bisa memperparah kepanikan. Pada <strong>Senin, 19 Oktober 1987</strong>, indeks <strong>Dow Jones</strong> jatuh sekitar <strong>22,6% dalam satu hari</strong>, penurunan harian terbesar dalam sejarahnya. Salah satu pemicunya adalah <strong>program trading</strong> otomatis yang menjual besar-besaran. Setelah peristiwa ini, bursa memperkenalkan <strong>circuit breaker</strong> yang menghentikan perdagangan sementara saat harga jatuh terlalu cepat.",
      },
      {
        type: "takeaways",
        items: [
          "Bursa mencocokkan order beli (bid) dan jual (ask) otomatis.",
          "Prioritas mengikuti harga lalu waktu.",
          "1 lot = 100 lembar; spread = selisih bid dan ask.",
          "Penyelesaian dana & saham terjadi pada T+2.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Bid adalah?",
            options: ["Harga jual terendah", "Harga beli tertinggi yang ditawarkan", "Biaya broker", "Indeks pasar"],
            answer: 1,
            explain: "Bid adalah harga tertinggi yang bersedia dibayar pembeli.",
          },
          {
            q: "1 lot saham di BEI sama dengan?",
            options: ["10 lembar", "100 lembar", "1.000 lembar", "1 lembar"],
            answer: 1,
            explain: "Satu lot di BEI adalah 100 lembar saham.",
          },
          {
            q: "Penyelesaian transaksi saham terjadi pada?",
            options: ["Hari yang sama", "T+2 (dua hari bursa)", "T+30", "Akhir bulan"],
            answer: 1,
            explain: "Penyelesaian dana dan saham terjadi pada T+2.",
          },
          {
            q: "Spread adalah?",
            options: ["Selisih harga bid dan ask", "Pajak transaksi", "Jumlah lot", "Dividen"],
            answer: 0,
            explain: "Spread adalah selisih antara harga beli tertinggi dan jual terendah.",
          },
          {
            q: "Beli 5 lot di Rp2.000 (1 lot = 100 lembar). Nilai transaksi?",
            options: ["Rp1.000.000", "Rp100.000", "Rp10.000", "Rp2.000.000"],
            answer: 0,
            explain: "5 x 100 x Rp2.000 = Rp1.000.000.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "bursa-dan-indeks",
    levelId: "saham",
    order: 2,
    title: "Bursa Efek dan Indeks Saham",
    summary: "Peran Bursa Efek Indonesia (BEI) serta cara membaca indeks IHSG, LQ45, dan indeks sektoral.",
    durationMin: 15,
    tags: ["saham", "BEI", "IHSG", "LQ45", "indeks"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Bursa Efek Indonesia (BEI)</strong> adalah penyelenggara pasar tempat saham diperdagangkan. BEI menyediakan sistem perdagangan, menetapkan aturan, mengawasi anggota bursa, dan memastikan transaksi berlangsung teratur, wajar, dan transparan.",
      },
      {
        type: "paragraph",
        html: "<strong>Indeks saham</strong> adalah angka yang merangkum pergerakan harga sekumpulan saham. <strong>IHSG</strong> (Indeks Harga Saham Gabungan) mencakup hampir seluruh saham tercatat. <strong>LQ45</strong> berisi 45 saham paling likuid dengan kapitalisasi besar. <strong>Indeks sektoral</strong> mengelompokkan saham per sektor industri, misalnya keuangan atau energi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cara indeks dihitung",
        html: "Sebagian besar indeks BEI memakai metode <strong>kapitalisasi pasar tertimbang</strong> (market cap weighted). Saham dengan kapitalisasi lebih besar punya bobot lebih besar, sehingga pergerakannya lebih memengaruhi indeks.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Cara membaca indeks",
        html: "Indeks naik berarti rata-rata tertimbang harga saham di dalamnya naik dibanding hari sebelumnya. Indeks adalah indikator arah pasar, bukan harga satu saham tertentu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Gunakan indeks sebagai pembanding",
        html: "Bandingkan kinerja portofolio Anda dengan indeks acuan (benchmark). Jika portofolio naik 8% sementara IHSG naik 12%, kinerja Anda tertinggal dari pasar.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Ilustrasi Bobot Sektor dalam Indeks",
        unit: "%",
        source: "Ilustrasi edukatif",
        note: "Angka contoh untuk memahami konsep kapitalisasi tertimbang, bukan data real-time.",
        data: [
          { label: "Keuangan", value: 35, color: "#2563eb" },
          { label: "Energi", value: 18, color: "#f59e0b" },
          { label: "Barang Konsumsi", value: 15, color: "#10b981" },
          { label: "Telekomunikasi", value: 12, color: "#8b5cf6" },
          { label: "Lainnya", value: 20, color: "#94a3b8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pengaruh bobot terhadap indeks",
        html: "Sebuah indeks berisi dua saham. Saham A berkapitalisasi Rp800 miliar dan saham B Rp200 miliar, total Rp1.000 miliar. Bobot A = 80%, B = 20%. Jika harga A naik 10% dan B turun 5%, kontribusi ke indeks = (80% x 10%) + (20% x -5%) = 8% - 1% = <strong>+7%</strong>. Saham besar lebih menentukan arah indeks.",
      },
      {
        type: "calcExercise",
        prompt: "Indeks berisi saham A (bobot 80%) naik 10% dan saham B (bobot 20%) turun 5%. Berapa persen perubahan indeks?",
        answer: 7,
        tolerance: 0.1,
        suffix: "%",
        solution: "Perubahan = (0,8 x 10%) + (0,2 x -5%) = 8% - 1% = <strong>7%</strong>.",
        hint: "Kalikan bobot tiap saham dengan perubahannya, lalu jumlahkan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan pengertiannya.",
        pairs: [
          { left: "IHSG", right: "Indeks gabungan hampir seluruh saham tercatat" },
          { left: "LQ45", right: "45 saham paling likuid berkapitalisasi besar" },
          { left: "Indeks sektoral", right: "Kelompok saham per sektor industri" },
          { left: "BEI", right: "Penyelenggara pasar saham di Indonesia" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Indeks Dow dan Depresi Besar 1929-1932",
        html: "Indeks saham bisa mengukur kehancuran sebuah pasar. Setelah puncaknya pada <strong>1929</strong>, indeks <strong>Dow Jones</strong> terus merosot akibat Depresi Besar hingga kehilangan sekitar <strong>89%</strong> nilainya pada titik terendah tahun <strong>1932</strong>. Butuh waktu sampai <strong>1954</strong> bagi Dow untuk kembali ke level sebelum krisis, menunjukkan bahwa indeks merangkum arah seluruh pasar, bukan satu saham saja.",
      },
      {
        type: "takeaways",
        items: [
          "BEI menyelenggarakan dan mengawasi perdagangan saham.",
          "IHSG mencakup hampir seluruh saham; LQ45 berisi 45 saham paling likuid.",
          "Indeks sektoral mengelompokkan saham per sektor industri.",
          "Banyak indeks memakai metode kapitalisasi pasar tertimbang.",
          "Indeks dipakai sebagai indikator arah pasar dan benchmark.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa kepanjangan IHSG?",
            options: ["Indeks Harga Saham Gabungan", "Indeks Harga Surat Garansi", "Indeks Hasil Saham Global", "Indeks Harian Saham Gabungan"],
            answer: 0,
            explain: "IHSG adalah Indeks Harga Saham Gabungan yang mencakup hampir seluruh saham tercatat.",
          },
          {
            q: "LQ45 berisi berapa saham?",
            options: ["20 saham", "30 saham", "45 saham", "100 saham"],
            answer: 2,
            explain: "LQ45 berisi 45 saham paling likuid dengan kapitalisasi besar.",
          },
          {
            q: "Metode perhitungan indeks yang umum di BEI adalah?",
            options: ["Rata-rata harga sederhana", "Kapitalisasi pasar tertimbang", "Jumlah lembar saham", "Urutan abjad"],
            answer: 1,
            explain: "Indeks umumnya memakai bobot kapitalisasi pasar.",
          },
          {
            q: "Lembaga penyelenggara pasar saham di Indonesia adalah?",
            options: ["OJK", "BEI", "BI", "LPS"],
            answer: 1,
            explain: "Bursa Efek Indonesia (BEI) menyelenggarakan perdagangan saham.",
          },
          {
            q: "Indeks berisi saham A bobot 60% naik 5% dan saham B bobot 40% naik 10%. Perubahan indeks?",
            options: ["7%", "15%", "5%", "10%"],
            answer: 0,
            explain: "(0,6 x 5%) + (0,4 x 10%) = 3% + 4% = 7%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ipo-pasar-perdana",
    levelId: "saham",
    order: 3,
    title: "IPO dan Pasar Perdana",
    summary: "Proses penawaran umum perdana (IPO) serta perbedaan pasar perdana dan pasar sekunder. Dengan video alur IPO.",
    durationMin: 15,
    tags: ["saham", "IPO", "pasar perdana", "pasar sekunder"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>IPO (Initial Public Offering)</strong> atau penawaran umum perdana adalah saat sebuah perusahaan untuk pertama kali menjual sahamnya ke publik dan tercatat di bursa. Lewat IPO, perusahaan menghimpun dana segar dari masyarakat untuk ekspansi, melunasi utang, atau modal kerja.",
      },
      {
        type: "paragraph",
        html: "Saham yang dibeli saat IPO terjadi di <strong>pasar perdana</strong>: dana dari investor masuk langsung ke perusahaan (emiten). Setelah saham tercatat, perdagangan selanjutnya antar investor terjadi di <strong>pasar sekunder</strong>, yaitu di bursa; di sini emiten tidak lagi menerima dana.",
      },
      {
        type: "video",
        comp: "IPOFlow",
        title: "Video: Alur Proses IPO",
        caption: "Dari persiapan dan pernyataan pendaftaran ke OJK, masa penawaran, hingga pencatatan saham di bursa.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pasar perdana vs sekunder",
        html: "<strong>Pasar perdana</strong>: saham dijual pertama kali, dana masuk ke emiten, harga ditetapkan saat penawaran. <strong>Pasar sekunder</strong>: jual beli antar investor di bursa, harga bergerak sesuai permintaan dan penawaran.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran OJK dan penjamin emisi",
        html: "Perusahaan menyusun prospektus dan mengajukan pernyataan pendaftaran ke <strong>OJK</strong>. <strong>Penjamin emisi (underwriter)</strong> membantu menentukan harga, memasarkan, dan menjamin penyerapan saham.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "IPO bukan jaminan untung",
        html: "Harga saham bisa naik atau turun setelah pencatatan. Bacalah prospektus dan pahami fundamental serta risikonya sebelum ikut IPO.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Tahapan Waktu Proses IPO",
        unit: "minggu (estimasi)",
        source: "Ilustrasi edukatif",
        note: "Durasi contoh tiap tahap; waktu sebenarnya bervariasi per perusahaan.",
        data: [
          { label: "Persiapan & due diligence", value: 12, color: "#2563eb" },
          { label: "Pendaftaran ke OJK", value: 6, color: "#f59e0b" },
          { label: "Masa penawaran", value: 1, color: "#10b981" },
          { label: "Pencatatan di bursa", value: 1, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membeli saat IPO",
        html: "PT Maju menawarkan saham IPO seharga Rp1.000 per lembar. Sinta memesan 20 lot (1 lot = 100 lembar). Nilai pesanan = 20 x 100 x Rp1.000 = <strong>Rp2.000.000</strong>, dana ini masuk ke perusahaan (pasar perdana). Saat tercatat, harga naik ke Rp1.150 di pasar sekunder. Jika Sinta menjual, keuntungannya berasal dari investor lain, bukan dari emiten.",
      },
      {
        type: "calcExercise",
        prompt: "Harga IPO Rp1.000 per lembar. Sinta memesan 20 lot (1 lot = 100 lembar). Berapa nilai pesanannya?",
        answer: 2000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai = 20 lot x 100 lembar x Rp1.000 = <strong>Rp2.000.000</strong>.",
        hint: "Kalikan jumlah lot, 100 lembar per lot, dan harga IPO.",
      },
      {
        type: "classifyExercise",
        prompt: "Peristiwa ini terjadi di pasar perdana atau pasar sekunder?",
        buckets: ["Pasar perdana", "Pasar sekunder"],
        items: [
          { text: "Membeli saham saat IPO", bucket: "Pasar perdana" },
          { text: "Dana investor masuk ke emiten", bucket: "Pasar perdana" },
          { text: "Jual beli saham antar investor di bursa", bucket: "Pasar sekunder" },
          { text: "Harga bergerak naik turun setiap hari bursa", bucket: "Pasar sekunder" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Demam IPO pada gelembung dot-com 2000",
        html: "Era <strong>gelembung dot-com</strong> memperlihatkan sisi liar pasar perdana. Pada akhir 1990-an, banyak perusahaan internet melakukan <strong>IPO</strong> dan harganya melonjak di hari pertama meski belum pernah untung. Indeks <strong>Nasdaq</strong> mencapai puncak sekitar <strong>5.048 pada Maret 2000</strong>, lalu runtuh hingga turun sekitar <strong>78%</strong> pada 2002. Banyak investor yang masuk di puncak menderita kerugian besar.",
      },
      {
        type: "takeaways",
        items: [
          "IPO adalah penjualan saham pertama kali ke publik.",
          "Di pasar perdana, dana masuk langsung ke emiten.",
          "Di pasar sekunder, saham diperjualbelikan antar investor di bursa.",
          "OJK mengawasi proses dan penjamin emisi membantu penawaran.",
          "IPO tidak menjamin keuntungan; baca prospektus dulu.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "IPO adalah?",
            options: ["Penjualan saham pertama kali ke publik", "Pembagian dividen", "Pembelian obligasi", "Penutupan perusahaan"],
            answer: 0,
            explain: "IPO adalah penawaran umum perdana saham ke publik.",
          },
          {
            q: "Di pasar perdana, dana hasil penjualan saham masuk ke?",
            options: ["Investor lain", "Emiten (perusahaan)", "Bursa", "Broker"],
            answer: 1,
            explain: "Pada pasar perdana, dana mengalir langsung ke perusahaan penerbit.",
          },
          {
            q: "Perdagangan saham antar investor setelah tercatat terjadi di?",
            options: ["Pasar perdana", "Pasar sekunder", "Pasar uang", "Pasar valas"],
            answer: 1,
            explain: "Setelah pencatatan, jual beli antar investor terjadi di pasar sekunder.",
          },
          {
            q: "Lembaga yang menerima pernyataan pendaftaran IPO adalah?",
            options: ["OJK", "BEI semata", "LPS", "Bank Indonesia"],
            answer: 0,
            explain: "Perusahaan mengajukan pernyataan pendaftaran ke OJK.",
          },
          {
            q: "Harga IPO Rp500, memesan 10 lot (1 lot = 100 lembar). Nilai pesanan?",
            options: ["Rp500.000", "Rp50.000", "Rp5.000.000", "Rp100.000"],
            answer: 0,
            explain: "10 x 100 x Rp500 = Rp500.000.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "imbal-hasil-saham",
    levelId: "saham",
    order: 4,
    title: "Imbal Hasil dan Risiko Saham",
    summary: "Sumber imbal hasil saham: capital gain dan dividen, konsep total return, serta risikonya. Dengan kalkulator return.",
    durationMin: 16,
    tags: ["saham", "capital gain", "dividen", "total return", "risiko"],
    blocks: [
      {
        type: "paragraph",
        html: "Imbal hasil (return) saham datang dari dua sumber. <strong>Capital gain</strong> adalah selisih harga jual lebih tinggi dari harga beli. <strong>Dividen</strong> adalah bagian laba yang dibagikan perusahaan kepada pemegang saham. Bila harga jual lebih rendah, terjadi <strong>capital loss</strong>.",
      },
      {
        type: "paragraph",
        html: "<strong>Total return</strong> menggabungkan keduanya: total return = capital gain + dividen, lalu dibagi harga beli untuk mendapatkan persentase. Inilah ukuran keuntungan menyeluruh dari sebuah investasi saham.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus total return",
        html: "<strong>Total return (%) = ((Harga jual - Harga beli) + Dividen) / Harga beli x 100%</strong>. Capital gain dan dividen dihitung bersama, bukan terpisah.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dividen tidak selalu ada",
        html: "Perusahaan dapat memilih menahan laba untuk ekspansi (laba ditahan) dan tidak membagikan dividen. Tidak semua saham rutin membagi dividen.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko saham",
        html: "Saham berisiko: harga bisa turun (capital loss), dividen bisa nol, dan dalam kondisi terburuk perusahaan bisa bangkrut. Imbal hasil yang lebih tinggi diiringi risiko yang lebih besar.",
      },
      { type: "widget", widget: "KalkulatorReturnSaham" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Komponen Total Return",
        unit: "Rp per lembar",
        source: "Ilustrasi edukatif",
        note: "Contoh: beli Rp1.000, jual Rp1.150, dividen Rp30. Total return Rp180 atau 18%.",
        data: [
          { label: "Capital gain", value: 150, color: "#10b981" },
          { label: "Dividen", value: 30, color: "#2563eb" },
          { label: "Total return", value: 180, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung total return",
        html: "Budi membeli saham di <strong>Rp2.000</strong> per lembar, menerima dividen <strong>Rp50</strong>, lalu menjual di <strong>Rp2.200</strong>. Capital gain = Rp2.200 - Rp2.000 = Rp200. Total return per lembar = Rp200 + Rp50 = Rp250. Persentase = Rp250 / Rp2.000 = <strong>12,5%</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Beli saham Rp2.000, terima dividen Rp50, jual Rp2.200. Berapa persen total return-nya?",
        answer: 12.5,
        tolerance: 0.1,
        suffix: "%",
        solution: "Total return = ((2.200 - 2.000) + 50) / 2.000 = 250 / 2.000 = <strong>12,5%</strong>.",
        hint: "Jumlahkan capital gain dan dividen, lalu bagi dengan harga beli.",
      },
      {
        type: "classifyExercise",
        prompt: "Komponen ini termasuk capital gain/loss atau dividen?",
        buckets: ["Capital gain/loss", "Dividen"],
        items: [
          { text: "Selisih harga jual di atas harga beli", bucket: "Capital gain/loss" },
          { text: "Bagian laba yang dibagikan perusahaan", bucket: "Dividen" },
          { text: "Kerugian karena harga jual lebih rendah", bucket: "Capital gain/loss" },
          { text: "Pembayaran tunai rutin dari laba emiten", bucket: "Dividen" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Tulip Mania 1637, pelajaran tertua soal risiko",
        html: "Salah satu pelajaran tertua tentang risiko spekulasi adalah <strong>Tulip Mania</strong> di Belanda. Pada puncaknya sekitar <strong>1636-1637</strong>, harga umbi tulip langka melambung hingga setara harga sebuah rumah, didorong euforia spekulasi. Ketika pembeli tiba-tiba menghilang pada <strong>Februari 1637</strong>, harga runtuh dengan cepat, mengingatkan bahwa imbal hasil tinggi selalu beriringan dengan risiko kerugian besar.",
      },
      {
        type: "takeaways",
        items: [
          "Imbal hasil saham berasal dari capital gain dan dividen.",
          "Total return = (capital gain + dividen) / harga beli.",
          "Dividen tidak selalu dibagikan; sebagian laba bisa ditahan.",
          "Harga turun menimbulkan capital loss.",
          "Return lebih tinggi umumnya diiringi risiko lebih besar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dua sumber imbal hasil saham adalah?",
            options: ["Bunga dan kupon", "Capital gain dan dividen", "Premi dan diskon", "Pajak dan biaya"],
            answer: 1,
            explain: "Imbal hasil saham berasal dari capital gain dan dividen.",
          },
          {
            q: "Capital gain terjadi ketika?",
            options: ["Harga jual lebih tinggi dari harga beli", "Perusahaan membagi dividen", "Harga turun", "Saham didelisting"],
            answer: 0,
            explain: "Capital gain adalah selisih harga jual yang lebih tinggi dari harga beli.",
          },
          {
            q: "Total return per lembar dihitung dari?",
            options: ["Dividen saja", "Capital gain saja", "Capital gain ditambah dividen", "Harga beli saja"],
            answer: 2,
            explain: "Total return menggabungkan capital gain dan dividen.",
          },
          {
            q: "Beli Rp1.000, jual Rp1.100, dividen Rp50. Total return persen?",
            options: ["10%", "5%", "15%", "20%"],
            answer: 2,
            explain: "((1.100 - 1.000) + 50) / 1.000 = 150 / 1.000 = 15%.",
          },
          {
            q: "Pernyataan yang benar tentang risiko saham?",
            options: ["Harga selalu naik", "Dividen dijamin setiap tahun", "Harga bisa turun dan menimbulkan capital loss", "Tidak ada risiko bangkrut"],
            answer: 2,
            explain: "Harga saham bisa turun sehingga investor mengalami capital loss.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "valuasi-saham-per-pbv",
    levelId: "saham",
    order: 5,
    title: "Valuasi Saham: PER dan PBV",
    summary: "Menilai mahal atau murahnya saham dengan rasio PER dan PBV, serta makna earnings yield. Dengan kalkulator return.",
    durationMin: 15,
    tags: ["saham", "valuasi", "PER", "PBV", "EPS"],
    blocks: [
      {
        type: "paragraph",
        html: "Harga saham yang tinggi belum tentu mahal, dan harga rendah belum tentu murah. Untuk menilainya, investor memakai <strong>rasio valuasi</strong> yang membandingkan harga dengan kinerja perusahaan. Dua yang paling umum adalah <strong>PER</strong> dan <strong>PBV</strong>.",
      },
      {
        type: "paragraph",
        html: "<strong>PER (Price to Earnings Ratio) = Harga saham / Laba per saham (EPS)</strong>. PER 10 berarti investor membayar Rp10 untuk setiap Rp1 laba tahunan, atau secara kasar butuh 10 tahun laba untuk menutup harga. <strong>PBV (Price to Book Value) = Harga saham / Nilai buku per saham</strong>, membandingkan harga dengan nilai ekuitas bersih per lembar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Membaca PER dan PBV",
        html: "PER atau PBV <strong>tinggi</strong> berarti pasar berani membayar mahal, sering karena ekspektasi pertumbuhan tinggi. PER atau PBV <strong>rendah</strong> bisa berarti murah, tetapi bisa juga sinyal masalah. Bandingkan selalu dengan perusahaan sejenis di sektor yang sama.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Earnings yield: kebalikan PER",
        html: "<strong>Earnings yield = 1 / PER</strong>. PER 10 setara earnings yield 10%, PER 20 setara 5%, PER 40 setara 2,5%. Makin tinggi PER, makin kecil laba tahunan relatif terhadap harga yang dibayar.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Rasio bukan segalanya",
        html: "PER dan PBV hanya potret sesaat. Perusahaan dengan PER tinggi bisa wajar bila labanya tumbuh cepat; PER rendah bisa jadi jebakan nilai (value trap) bila bisnisnya menurun. Pahami juga prospek dan kualitas labanya.",
      },
      { type: "widget", widget: "KalkulatorReturnSaham" },
      {
        type: "chart",
        variant: "bar",
        title: "Earnings Yield untuk Berbagai Tingkat PER",
        unit: "% earnings yield",
        source: "perhitungan: earnings yield = 1 / PER",
        note: "Makin tinggi PER, makin rendah laba tahunan relatif terhadap harga (earnings yield kecil).",
        data: [
          { label: "PER 8", value: 12.5, color: "#16a34a" },
          { label: "PER 10", value: 10, color: "#0ea5e9" },
          { label: "PER 20", value: 5, color: "#f59e0b" },
          { label: "PER 40", value: 2.5, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua saham, harga sama, PER beda",
        html: "Saham A dan saham B sama-sama berharga <strong>Rp5.000</strong>. Saham A memiliki EPS Rp1.000, sehingga PER A = 5.000 / 1.000 = <strong>5</strong>. Saham B memiliki EPS Rp250, sehingga PER B = 5.000 / 250 = <strong>20</strong>. Meski harganya identik, saham A jauh lebih murah relatif terhadap labanya. Investor membayar 5 tahun laba untuk A, tetapi 20 tahun laba untuk B.",
      },
      {
        type: "calcExercise",
        prompt: "Harga saham Rp5.000 dan laba per saham (EPS) Rp500. Berapa PER-nya?",
        answer: 10,
        tolerance: 0,
        solution: "PER = Harga / EPS = Rp5.000 / Rp500 = <strong>10</strong>. Artinya investor membayar 10 kali laba tahunan.",
        hint: "Bagi harga saham dengan laba per saham (EPS).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah valuasi dengan pengertiannya.",
        pairs: [
          { left: "PER", right: "Harga saham dibagi laba per saham" },
          { left: "PBV", right: "Harga saham dibagi nilai buku per saham" },
          { left: "EPS", right: "Laba bersih dibagi jumlah saham beredar" },
          { left: "Earnings yield", right: "Kebalikan PER, laba relatif terhadap harga" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Nifty Fifty dan bahaya PER tinggi 1972-1974",
        html: "Pada awal 1970-an di Amerika Serikat, sekelompok saham unggulan yang dijuluki <strong>Nifty Fifty</strong> dianggap layak dibeli pada harga berapa pun. Sebagian diperdagangkan pada <strong>PER 40 hingga lebih dari 80</strong>, jauh di atas rata-rata pasar. Ketika bear market (pasar beruang) <strong>1973-1974</strong> datang, banyak di antaranya jatuh <strong>50% hingga lebih dari 80%</strong>. Pelajarannya: bahkan perusahaan bagus bisa menjadi investasi buruk bila dibeli pada valuasi yang terlalu mahal.",
      },
      {
        type: "takeaways",
        items: [
          "PER = harga / EPS, mengukur berapa kali laba yang dibayar investor.",
          "PBV = harga / nilai buku per saham.",
          "Earnings yield = 1 / PER; PER tinggi berarti earnings yield rendah.",
          "Bandingkan rasio dengan perusahaan sejenis, bukan lintas sektor.",
          "PER rendah belum tentu murah; PER tinggi belum tentu mahal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "PER dihitung dengan rumus?",
            options: ["EPS dibagi harga", "Harga saham dibagi EPS", "Harga dibagi dividen", "Nilai buku dibagi harga"],
            answer: 1,
            explain: "PER = Harga saham dibagi laba per saham (EPS).",
          },
          {
            q: "PER 25 secara kasar berarti?",
            options: ["Investor membayar 25 kali laba tahunan", "Saham naik 25%", "Dividen 25%", "Nilai buku 25"],
            answer: 0,
            explain: "PER 25 berarti harga setara 25 kali laba tahunan per saham.",
          },
          {
            q: "Earnings yield dari saham ber-PER 20 adalah?",
            options: ["20%", "10%", "5%", "2%"],
            answer: 2,
            explain: "Earnings yield = 1 / PER = 1/20 = 5%.",
          },
          {
            q: "PBV membandingkan harga saham dengan?",
            options: ["Laba per saham", "Nilai buku per saham", "Dividen per saham", "Harga IPO"],
            answer: 1,
            explain: "PBV = Harga saham dibagi nilai buku (ekuitas bersih) per saham.",
          },
          {
            q: "Harga Rp8.000, EPS Rp400. Berapa PER-nya?",
            options: ["10", "20", "4", "32"],
            answer: 1,
            explain: "8.000 / 400 = 20.",
          },
        ],
      },
    ],
  },
];
