import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "pasar-obligasi",
    levelId: "obligasi",
    order: 1,
    title: "Pasar Obligasi & Yield Curve",
    summary: "Pasar surat utang pemerintah dan korporasi, peringkat, serta membaca kurva imbal hasil. Dengan video & simulator.",
    durationMin: 14,
    tags: ["obligasi", "SBN", "yield curve", "rating"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pasar obligasi</strong> memperdagangkan surat utang. Penerbit (pemerintah atau perusahaan) meminjam dana dari investor, membayar <strong>kupon</strong> berkala, dan mengembalikan pokok saat jatuh tempo. Obligasi pemerintah Indonesia disebut <strong>SBN</strong> (mis. SUN, ORI, sukuk negara).",
      },
      {
        type: "video",
        comp: "YieldCurveVideo",
        title: "Video: Kurva Imbal Hasil (Yield Curve)",
        caption: "Animasi kurva normal vs terbalik (inverted) dan maknanya bagi ekonomi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Harga dan yield berlawanan",
        html: "Kupon obligasi tetap, tetapi harganya bergerak. Saat suku bunga (yield) <strong>naik</strong>, harga obligasi yang beredar <strong>turun</strong>, dan sebaliknya. Inilah risiko suku bunga.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peringkat (rating)",
        html: "Lembaga pemeringkat menilai risiko gagal bayar penerbit. Peringkat tinggi (mis. AAA) berarti risiko rendah dan yield lebih kecil; peringkat rendah (high yield) memberi yield lebih tinggi sebagai kompensasi risiko.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur yield tenor pendek dan panjang, lihat bentuk kurva (normal, datar, atau terbalik) dan artinya.",
      },
      { type: "widget", widget: "SimulatorYieldCurve" },
      {
        type: "chart",
        variant: "line",
        title: "Kurva Imbal Hasil Normal per Tenor (ilustrasi)",
        unit: "% yield",
        source: "ilustrasi pola umum",
        note: "Pada kurva normal, tenor lebih panjang memberi yield lebih tinggi sebagai kompensasi risiko waktu.",
        data: [
          { label: "1 th", value: 5.5, color: "#f59e0b" },
          { label: "3 th", value: 6.1, color: "#f59e0b" },
          { label: "5 th", value: 6.5, color: "#f59e0b" },
          { label: "10 th", value: 6.9, color: "#f59e0b" },
          { label: "20 th", value: 7.2, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: ORI untuk investor ritel",
        html: "Pemerintah menerbitkan <strong>ORI</strong> bertenor 3 tahun dengan kupon 6,25% per tahun dibayar bulanan. Investor ritel membeli Rp10 juta. Tiap bulan menerima kupon, dan pokok kembali saat jatuh tempo. ORI menjadi cara aman bagi masyarakat ikut mendanai negara sambil memperoleh imbal hasil tetap di atas bunga deposito.",
      },
      {
        type: "calcExercise",
        prompt: "Investor membeli ORI Rp10 juta dengan kupon 6% per tahun. Berapa kupon yang diterima per tahun (Rp)?",
        answer: 600000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Kupon = 6% x Rp10 juta = <strong>Rp600.000</strong> per tahun (sering dibayar bulanan Rp50.000).",
        hint: "Kalikan kupon dengan nilai nominal obligasi.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi ini membuat harga obligasi beredar naik atau turun?",
        buckets: ["Harga naik", "Harga turun"],
        items: [
          { text: "Suku bunga pasar turun", bucket: "Harga naik" },
          { text: "Suku bunga pasar naik", bucket: "Harga turun" },
          { text: "Yield diminta investor turun", bucket: "Harga naik" },
          { text: "Risiko gagal bayar meningkat", bucket: "Harga turun" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Inversi kurva imbal hasil sebagai sinyal resesi",
        html: "<strong>Inversi kurva imbal hasil</strong> (yield curve terbalik), saat imbal hasil obligasi jangka pendek lebih tinggi daripada jangka panjang, dikenal sebagai salah satu sinyal resesi paling andal. Di Amerika Serikat, hampir setiap resesi sejak <strong>1950-an</strong> didahului oleh inversi kurva. Sebagai contoh, kurva AS terbalik pada <strong>2006-2007</strong>, beberapa waktu sebelum krisis keuangan <strong>2008</strong> meletus.",
      },
      {
        type: "takeaways",
        items: [
          "Obligasi adalah surat utang dengan kupon dan jatuh tempo.",
          "SBN adalah obligasi pemerintah (SUN, ORI, sukuk).",
          "Harga obligasi bergerak berlawanan dengan yield.",
          "Rating mengukur risiko gagal bayar; makin rendah rating, makin tinggi yield.",
          "Yield curve terbalik sering dianggap sinyal risiko resesi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Saat suku bunga pasar naik, harga obligasi beredar?",
            options: ["Naik", "Turun", "Tetap", "Hilang"],
            answer: 1,
            explain: "Harga dan yield berlawanan: yield naik membuat harga turun.",
          },
          {
            q: "SBN adalah?",
            options: ["Saham bank", "Surat utang pemerintah", "Reksa dana", "Mata uang"],
            answer: 1,
            explain: "SBN (Surat Berharga Negara) adalah obligasi yang diterbitkan pemerintah.",
          },
          {
            q: "Obligasi dengan rating rendah biasanya menawarkan?",
            options: ["Yield lebih tinggi", "Yield lebih rendah", "Tanpa kupon", "Bebas risiko"],
            answer: 0,
            explain: "Risiko lebih tinggi dikompensasi dengan yield (imbal hasil) lebih tinggi.",
          },
          {
            q: "Yield curve terbalik (inverted) sering ditafsirkan sebagai?",
            options: ["Tanda ekonomi sangat sehat", "Sinyal risiko perlambatan/resesi", "Bebas risiko", "Tidak bermakna"],
            answer: 1,
            explain: "Inverted curve sering dianggap sinyal pasar memperkirakan perlambatan.",
          },
          {
            q: "Obligasi Rp20 juta, kupon 7%/tahun. Kupon setahun?",
            options: ["Rp1,4 juta", "Rp700 ribu", "Rp2 juta", "Rp140 ribu"],
            answer: 0,
            explain: "7% x Rp20 juta = Rp1,4 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "obligasi-pemerintah-korporasi",
    levelId: "obligasi",
    order: 2,
    title: "Obligasi Pemerintah vs Korporasi",
    summary: "Membedakan SBN (SUN, ORI, sukuk negara) dengan obligasi korporasi, serta perbandingan risiko dan imbal hasilnya.",
    durationMin: 13,
    tags: ["SBN", "SUN", "ORI", "sukuk", "korporasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Obligasi diterbitkan oleh dua jenis penerbit utama. <strong>Pemerintah</strong> menerbitkan <strong>SBN</strong> (Surat Berharga Negara) untuk membiayai APBN, sedangkan <strong>perusahaan</strong> menerbitkan <strong>obligasi korporasi</strong> untuk membiayai ekspansi atau melunasi utang. Keduanya membayar kupon, tetapi profil risikonya berbeda.",
      },
      {
        type: "paragraph",
        html: "SBN terdiri dari beberapa bentuk: <strong>SUN</strong> (Surat Utang Negara) konvensional, <strong>ORI</strong> (Obligasi Negara Ritel) yang ditujukan bagi investor perorangan, dan <strong>sukuk negara</strong> yang berbasis prinsip syariah (imbalan, bukan bunga). Semua dijamin oleh negara melalui undang-undang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Risiko gagal bayar berbeda",
        html: "SBN dianggap nyaris bebas risiko gagal bayar karena dijamin negara, sehingga yield-nya menjadi acuan (benchmark). Obligasi korporasi membawa risiko gagal bayar penerbit, jadi harus menawarkan yield lebih tinggi sebagai kompensasi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Selisih yield (spread)",
        html: "Selisih antara yield obligasi korporasi dan SBN bertenor sama disebut <strong>credit spread</strong>. Makin besar risiko penerbit, makin lebar spread yang diminta investor.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Sukuk bukan bunga",
        html: "Pada sukuk negara, imbal hasil disebut <strong>imbalan</strong> dan didasarkan pada aset yang mendasari (underlying), sesuai prinsip syariah. Secara arus kas tetap mirip kupon berkala.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Yield Tahunan per Jenis Obligasi (Tenor 5 Tahun)",
        unit: "% per tahun",
        source: "Ilustrasi edukasi",
        note: "Makin tinggi risiko penerbit, makin tinggi yield yang ditawarkan.",
        data: [
          { label: "SUN", value: 6.5, color: "#16a34a" },
          { label: "Sukuk Negara", value: 6.6, color: "#0ea5e9" },
          { label: "Korporasi AAA", value: 7.4, color: "#f59e0b" },
          { label: "Korporasi A", value: 8.8, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: SUN vs obligasi korporasi",
        html: "Dua obligasi bertenor 5 tahun ditawarkan. <strong>SUN</strong> memberi yield 6,5% per tahun, sedangkan <strong>obligasi korporasi A</strong> memberi yield 8,8% per tahun. Selisih (credit spread) sebesar 2,3% adalah harga risiko gagal bayar yang ditanggung investor korporasi. Untuk investasi Rp100 juta, selisih ini berarti tambahan Rp2,3 juta imbal hasil per tahun, tetapi dengan risiko penerbit yang lebih besar.",
      },
      {
        type: "calcExercise",
        prompt: "SUN memberi yield 6,5% dan obligasi korporasi 8,8% untuk tenor sama. Berapa credit spread-nya (dalam %)?",
        answer: 2.3,
        tolerance: 0.05,
        suffix: "%",
        solution: "Credit spread = 8,8% - 6,5% = <strong>2,3%</strong>. Inilah tambahan yield sebagai kompensasi risiko korporasi.",
        hint: "Kurangkan yield SUN dari yield korporasi.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan instrumen berikut sebagai obligasi pemerintah atau korporasi.",
        buckets: ["Obligasi Pemerintah", "Obligasi Korporasi"],
        items: [
          { text: "ORI (Obligasi Negara Ritel)", bucket: "Obligasi Pemerintah" },
          { text: "Sukuk negara", bucket: "Obligasi Pemerintah" },
          { text: "SUN", bucket: "Obligasi Pemerintah" },
          { text: "Obligasi PT Telkom", bucket: "Obligasi Korporasi" },
          { text: "Obligasi bank swasta", bucket: "Obligasi Korporasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Obligasi rekapitalisasi pasca Krisis Asia 1998",
        html: "<strong>Krisis Asia 1997-1998</strong> turut membentuk pasar obligasi pemerintah Indonesia modern. Untuk menyelamatkan perbankan yang ambruk, pemerintah menerbitkan <strong>obligasi rekapitalisasi</strong> dalam jumlah sangat besar, mencapai ratusan triliun rupiah. Berbeda dengan banyak obligasi korporasi yang gagal bayar saat krisis, obligasi pemerintah ini dijamin negara dan belakangan menjadi tulang punggung pasar SBN.",
      },
      {
        type: "takeaways",
        items: [
          "SBN diterbitkan pemerintah: SUN, ORI, dan sukuk negara.",
          "Obligasi korporasi diterbitkan perusahaan dengan risiko gagal bayar lebih tinggi.",
          "Yield SBN menjadi acuan (benchmark) pasar obligasi.",
          "Credit spread adalah selisih yield korporasi terhadap SBN sebagai harga risiko.",
          "Sukuk memberi imbalan berbasis aset, bukan bunga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah yang termasuk SBN?",
            options: ["Obligasi PT Astra", "ORI", "Saham BCA", "Deposito bank"],
            answer: 1,
            explain: "ORI (Obligasi Negara Ritel) adalah salah satu bentuk SBN.",
          },
          {
            q: "Mengapa obligasi korporasi umumnya memberi yield lebih tinggi dari SBN?",
            options: ["Karena kuponnya bebas pajak", "Sebagai kompensasi risiko gagal bayar yang lebih besar", "Karena dijamin negara", "Karena tenornya selalu lebih pendek"],
            answer: 1,
            explain: "Risiko gagal bayar penerbit korporasi lebih tinggi sehingga yield-nya harus lebih besar.",
          },
          {
            q: "Selisih yield korporasi terhadap SBN bertenor sama disebut?",
            options: ["Kupon", "Credit spread", "Par value", "Yield curve"],
            answer: 1,
            explain: "Selisih ini disebut credit spread, harga risiko kredit.",
          },
          {
            q: "Sukuk negara memberi imbal hasil berupa?",
            options: ["Bunga tetap", "Imbalan berbasis aset (syariah)", "Dividen saham", "Capital gain saja"],
            answer: 1,
            explain: "Sukuk berbasis prinsip syariah memberi imbalan dari aset yang mendasari, bukan bunga.",
          },
          {
            q: "SUN yield 6%, korporasi yield 9% tenor sama. Credit spread-nya?",
            options: ["3%", "1,5%", "6%", "15%"],
            answer: 0,
            explain: "9% - 6% = 3%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "harga-dan-yield-obligasi",
    levelId: "obligasi",
    order: 3,
    title: "Harga dan Yield Obligasi",
    summary: "Cara harga obligasi dihitung dari nilai kini kupon dan pokok, hubungan terbalik harga-yield, serta kondisi premium, discount, dan par.",
    durationMin: 15,
    tags: ["harga", "yield", "premium", "discount", "par"],
    blocks: [
      {
        type: "paragraph",
        html: "Harga wajar obligasi adalah <strong>nilai kini (present value)</strong> dari seluruh arus kas masa depannya, yaitu kupon yang dibayar berkala ditambah pokok yang dikembalikan saat jatuh tempo. Tiap arus kas didiskon dengan yield pasar yang berlaku.",
      },
      {
        type: "paragraph",
        html: "Karena kupon sudah ditetapkan saat penerbitan, satu-satunya yang menyesuaikan adalah <strong>harga</strong>. Ketika yield pasar berubah, harga bergerak ke arah berlawanan agar imbal hasil efektif obligasi sama dengan yield pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Premium, par, dan discount",
        html: "Jika kupon obligasi <strong>lebih besar</strong> dari yield pasar, harga di atas nominal (<strong>premium</strong>). Jika kupon <strong>sama</strong> dengan yield, harga sama dengan nominal (<strong>par</strong>). Jika kupon <strong>lebih kecil</strong> dari yield, harga di bawah nominal (<strong>discount</strong>).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Hubungan terbalik harga-yield",
        html: "Saat yield pasar naik di atas kupon, obligasi lama jadi kurang menarik sehingga harganya turun (discount). Saat yield pasar turun di bawah kupon, harganya naik (premium).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Gunakan kalkulatornya",
        html: "Coba ubah kupon, yield pasar, dan tenor pada kalkulator untuk melihat kapan harga menjadi premium, par, atau discount.",
      },
      { type: "widget", widget: "KalkulatorObligasi" },
      {
        type: "chart",
        variant: "line",
        title: "Harga Obligasi (Nominal Rp1.000) terhadap Yield Pasar (Kupon 6%)",
        unit: "Rp harga",
        source: "Ilustrasi edukasi, tenor 5 tahun",
        note: "Saat yield = kupon 6%, harga = par Rp1.000. Yield naik membuat harga turun.",
        data: [
          { label: "Yield 4%", value: 1089, color: "#16a34a" },
          { label: "Yield 5%", value: 1043, color: "#0ea5e9" },
          { label: "Yield 6% (par)", value: 1000, color: "#64748b" },
          { label: "Yield 7%", value: 959, color: "#f59e0b" },
          { label: "Yield 8%", value: 920, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: obligasi menjadi discount",
        html: "Sebuah obligasi nominal Rp1.000.000 dengan kupon 6% per tahun diterbitkan saat yield pasar 6% (harga par Rp1.000.000). Setahun kemudian yield pasar naik menjadi 8%. Karena kupon tetap 6% sementara pasar minta 8%, harga obligasi turun di bawah nominal menjadi sekitar Rp920.000 (discount). Investor yang menjual sekarang menanggung kerugian harga, sedangkan pembeli baru mendapat yield efektif 8%.",
      },
      {
        type: "calcExercise",
        prompt: "Obligasi nominal Rp1.000 membayar kupon 5% per tahun. Berapa nilai kupon tahunan dalam rupiah?",
        answer: 50,
        tolerance: 0,
        prefix: "Rp",
        solution: "Kupon = 5% x Rp1.000 = <strong>Rp50</strong> per tahun. Nilai kupon ini tetap meski harga pasar berubah.",
        hint: "Kalikan tingkat kupon dengan nilai nominal.",
      },
      {
        type: "classifyExercise",
        prompt: "Tentukan kondisi harga obligasi berdasarkan hubungan kupon dan yield pasar.",
        buckets: ["Premium", "Par", "Discount"],
        items: [
          { text: "Kupon 7% > yield pasar 5%", bucket: "Premium" },
          { text: "Kupon 6% = yield pasar 6%", bucket: "Par" },
          { text: "Kupon 4% < yield pasar 7%", bucket: "Discount" },
          { text: "Kupon 8% > yield pasar 6%", bucket: "Premium" },
          { text: "Kupon 5% < yield pasar 8%", bucket: "Discount" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Era Volcker dan anjloknya harga obligasi",
        html: "Hubungan terbalik harga dan yield terlihat dramatis di era <strong>Paul Volcker</strong>. Ketika bank sentral AS menaikkan suku bunga hingga mendekati <strong>20% pada 1981</strong> untuk melawan inflasi, yield melonjak dan <strong>harga obligasi yang beredar anjlok</strong>. Pemegang obligasi lama berkupon rendah menderita kerugian harga besar, bukti nyata bahwa kenaikan yield menekan harga obligasi.",
      },
      {
        type: "takeaways",
        items: [
          "Harga obligasi adalah nilai kini kupon ditambah pokok.",
          "Kupon tetap; harga yang menyesuaikan terhadap yield pasar.",
          "Kupon > yield = premium; kupon = yield = par; kupon < yield = discount.",
          "Harga dan yield selalu bergerak berlawanan arah.",
          "Pembeli pada harga discount memperoleh yield efektif lebih tinggi dari kupon.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Harga wajar obligasi pada dasarnya adalah?",
            options: ["Jumlah kupon saja", "Nilai kini kupon ditambah pokok", "Nilai nominal selalu", "Harga beli awal"],
            answer: 1,
            explain: "Harga = present value dari kupon masa depan ditambah pokok saat jatuh tempo.",
          },
          {
            q: "Jika kupon lebih kecil dari yield pasar, harga obligasi?",
            options: ["Premium (di atas nominal)", "Par (sama nominal)", "Discount (di bawah nominal)", "Tidak berubah"],
            answer: 2,
            explain: "Kupon < yield membuat harga turun di bawah nominal (discount).",
          },
          {
            q: "Saat yield pasar turun di bawah kupon, harga obligasi cenderung?",
            options: ["Turun", "Naik", "Tetap", "Nol"],
            answer: 1,
            explain: "Yield turun di bawah kupon membuat obligasi lebih menarik sehingga harganya naik (premium).",
          },
          {
            q: "Obligasi dijual pada harga par berarti?",
            options: ["Kupon > yield", "Kupon = yield pasar", "Kupon < yield", "Tanpa kupon"],
            answer: 1,
            explain: "Harga par terjadi ketika tingkat kupon sama dengan yield pasar.",
          },
          {
            q: "Obligasi nominal Rp1.000, kupon 6%. Nilai kupon setahun?",
            options: ["Rp60", "Rp6", "Rp600", "Rp16"],
            answer: 0,
            explain: "6% x Rp1.000 = Rp60.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "rating-dan-pasar-sekunder",
    levelId: "obligasi",
    order: 4,
    title: "Rating dan Pasar Sekunder",
    summary: "Memahami peringkat (rating) dan risiko gagal bayar, perbedaan pasar primer dan sekunder, serta likuiditas obligasi.",
    durationMin: 13,
    tags: ["rating", "gagal bayar", "pasar sekunder", "likuiditas"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum membeli obligasi, investor menilai <strong>risiko gagal bayar</strong> (default), yaitu kemungkinan penerbit tidak mampu membayar kupon atau pokok. Lembaga pemeringkat memberi <strong>rating</strong> sebagai ringkasan risiko ini, mulai dari yang paling aman hingga spekulatif.",
      },
      {
        type: "paragraph",
        html: "Setelah diterbitkan di <strong>pasar primer</strong>, obligasi diperdagangkan kembali antar investor di <strong>pasar sekunder</strong>. Di sinilah harga bergerak mengikuti yield, dan <strong>likuiditas</strong> menentukan seberapa mudah obligasi dijual tanpa menekan harga.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Investment grade vs high yield",
        html: "Peringkat <strong>AAA hingga BBB</strong> disebut investment grade (risiko rendah). Peringkat <strong>BB ke bawah</strong> disebut high yield atau non-investment grade (risiko tinggi, yield besar). Makin rendah rating, makin tinggi yield yang diminta.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pasar primer vs sekunder",
        html: "Di <strong>pasar primer</strong> penerbit menjual obligasi pertama kali dan menerima dana. Di <strong>pasar sekunder</strong> investor saling jual-beli obligasi yang sudah beredar; penerbit tidak menerima dana tambahan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko likuiditas",
        html: "Obligasi yang jarang diperdagangkan sulit dijual cepat tanpa menurunkan harga. SBN umumnya lebih likuid dibanding obligasi korporasi kecil.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Yield Berdasarkan Peringkat Obligasi (Tenor 5 Tahun)",
        unit: "% per tahun",
        source: "Ilustrasi edukasi",
        note: "Rating lebih rendah membawa risiko gagal bayar lebih tinggi sehingga yield naik.",
        data: [
          { label: "AAA", value: 6.8, color: "#16a34a" },
          { label: "AA", value: 7.3, color: "#0ea5e9" },
          { label: "A", value: 8.2, color: "#f59e0b" },
          { label: "BBB", value: 9.5, color: "#f97316" },
          { label: "BB (high yield)", value: 12.0, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: penurunan rating",
        html: "Sebuah perusahaan memiliki obligasi beredar dengan rating A dan yield 8,2%. Karena kinerja memburuk, ratingnya diturunkan menjadi BBB. Investor kini menuntut yield sekitar 9,5% untuk menahan obligasi tersebut. Akibatnya harga di pasar sekunder turun, sebab yield yang lebih tinggi hanya bisa dicapai lewat harga yang lebih murah. Pemegang lama menanggung kerugian harga meski kuponnya tidak berubah.",
      },
      {
        type: "calcExercise",
        prompt: "Setelah rating turun, yield obligasi naik dari 8,2% menjadi 9,5%. Berapa kenaikan yield (dalam %)?",
        answer: 1.3,
        tolerance: 0.05,
        suffix: "%",
        solution: "Kenaikan yield = 9,5% - 8,2% = <strong>1,3%</strong>. Yield yang lebih tinggi ini menekan harga di pasar sekunder.",
        hint: "Kurangkan yield lama dari yield baru.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan pengertian yang tepat.",
        pairs: [
          { left: "Pasar primer", right: "Tempat penerbit menjual obligasi pertama kali" },
          { left: "Pasar sekunder", right: "Tempat investor saling jual-beli obligasi beredar" },
          { left: "Investment grade", right: "Peringkat AAA hingga BBB, risiko rendah" },
          { left: "High yield", right: "Peringkat BB ke bawah, risiko tinggi" },
          { left: "Likuiditas", right: "Kemudahan menjual tanpa menekan harga" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Peringkat AAA yang runtuh pada krisis 2008",
        html: "<strong>Krisis subprime 2008</strong> menelanjangi kelemahan peringkat. Banyak sekuritas berbasis KPR (mortgage) diberi peringkat tertinggi <strong>AAA</strong>, lalu diturunkan tajam menjadi kategori sampah (junk) saat gagal bayar melonjak. Harganya runtuh di pasar sekunder dan turut menyeret <strong>Lehman Brothers</strong> bangkrut pada September 2008, menunjukkan bahwa peringkat tinggi tidak menjamin bebas risiko.",
      },
      {
        type: "takeaways",
        items: [
          "Rating meringkas risiko gagal bayar penerbit.",
          "AAA hingga BBB adalah investment grade; BB ke bawah adalah high yield.",
          "Pasar primer untuk penerbitan baru, pasar sekunder untuk perdagangan ulang.",
          "Penurunan rating menaikkan yield dan menekan harga obligasi.",
          "Likuiditas menentukan kemudahan menjual obligasi tanpa rugi harga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Obligasi dengan peringkat BB ke bawah disebut?",
            options: ["Investment grade", "High yield", "Bebas risiko", "Par bond"],
            answer: 1,
            explain: "BB ke bawah tergolong high yield (non-investment grade), risiko tinggi.",
          },
          {
            q: "Di pasar manakah penerbit menerima dana dari penjualan obligasi?",
            options: ["Pasar primer", "Pasar sekunder", "Pasar valas", "Pasar uang"],
            answer: 0,
            explain: "Penerbit menerima dana saat penjualan perdana di pasar primer.",
          },
          {
            q: "Jika rating penerbit diturunkan, yield yang diminta investor cenderung?",
            options: ["Turun", "Naik", "Tetap", "Hilang"],
            answer: 1,
            explain: "Risiko naik membuat investor menuntut yield lebih tinggi, harga pun turun.",
          },
          {
            q: "Likuiditas obligasi mengukur?",
            options: ["Besar kupon", "Kemudahan menjual tanpa menekan harga", "Lama jatuh tempo", "Nilai nominal"],
            answer: 1,
            explain: "Likuiditas adalah seberapa mudah obligasi dijual cepat tanpa menurunkan harga.",
          },
          {
            q: "Manakah yang termasuk investment grade?",
            options: ["BB", "BBB", "CCC", "D"],
            answer: 1,
            explain: "BBB adalah batas terendah investment grade; di bawahnya tergolong high yield.",
          },
        ],
      },
    ],
  },
];
