import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "apa-itu-pasar-keuangan",
    levelId: "fondasi",
    order: 1,
    title: "Apa Itu Pasar Keuangan?",
    summary: "Bagaimana pasar keuangan menyalurkan dana dari yang kelebihan ke yang membutuhkan. Dengan video & grafik.",
    durationMin: 13,
    tags: ["pasar keuangan", "intermediasi", "fungsi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pasar keuangan</strong> adalah tempat bertemunya pihak yang memiliki kelebihan dana (penabung, investor) dengan pihak yang membutuhkan dana (perusahaan, pemerintah). Lewat pasar ini, dana mengalir ke tempat yang paling produktif, dan pemilik dana memperoleh imbal hasil.",
      },
      {
        type: "video",
        comp: "AlurPasarKeuangan",
        title: "Video: Fungsi Pasar Keuangan",
        caption: "Animasi aliran dana dari pihak surplus ke pihak defisit melalui pasar keuangan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga fungsi utama",
        html: "<strong>Menyalurkan dana</strong> dari penabung ke peminjam, <strong>menentukan harga</strong> (suku bunga, harga saham) lewat mekanisme pasar, dan menyediakan <strong>likuiditas</strong> agar aset mudah dijual kembali.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa penting bagi ekonomi",
        html: "Tanpa pasar keuangan, perusahaan sulit mendapat modal untuk tumbuh dan masyarakat sulit menyimpan atau mengembangkan dana. Pasar yang efisien menurunkan biaya dan risiko penyaluran modal.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Sumber Pendanaan Perusahaan (ilustrasi)",
        unit: "% pendanaan",
        source: "ilustrasi pola umum",
        note: "Pasar keuangan (utang & ekuitas publik) melengkapi pinjaman bank sebagai sumber dana.",
        data: [
          { label: "Pinjaman bank", value: 45, color: "#0ea5e9" },
          { label: "Obligasi", value: 25, color: "#f59e0b" },
          { label: "Saham/ekuitas", value: 20, color: "#10b981" },
          { label: "Laba ditahan", value: 10, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua sisi pasar",
        html: "Bu Sari menyimpan Rp50 juta dan ingin mengembangkannya. PT Maju butuh Rp50 miliar untuk membangun pabrik. Lewat <strong>pasar keuangan</strong>, dana Bu Sari (dan ribuan investor lain) bisa mengalir ke PT Maju melalui pembelian saham atau obligasi. Bu Sari memperoleh imbal hasil, PT Maju memperoleh modal, dan ekonomi tumbuh. Inilah peran intermediasi pasar keuangan.",
      },
      {
        type: "calcExercise",
        prompt: "Seorang investor menanam Rp50 juta dan menerima imbal hasil 8% setahun. Berapa imbal hasil dalam rupiah?",
        answer: 4000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Imbal hasil = 8% x Rp50 juta = <strong>Rp4 juta</strong>.",
        hint: "Kalikan persentase imbal hasil dengan jumlah investasi.",
      },
      {
        type: "classifyExercise",
        prompt: "Pihak ini termasuk surplus dana atau defisit dana?",
        buckets: ["Surplus dana (pemilik)", "Defisit dana (pencari)"],
        items: [
          { text: "Karyawan yang rutin menabung", bucket: "Surplus dana (pemilik)" },
          { text: "Perusahaan yang menerbitkan saham", bucket: "Defisit dana (pencari)" },
          { text: "Pemerintah menerbitkan obligasi", bucket: "Defisit dana (pencari)" },
          { text: "Investor membeli reksa dana", bucket: "Surplus dana (pemilik)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Perbankan dagang Medici & letter of credit",
        html: "Jauh sebelum ada bursa modern, fungsi intermediasi keuangan sudah berjalan lewat <strong>perbankan dagang</strong>. Pada abad ke-14 dan ke-15, keluarga <strong>Medici</strong> di Florence mengembangkan jaringan bank yang menyalurkan dana antarkota dan antarnegara serta mempopulerkan <strong>surat kredit (letter of credit)</strong>. Instrumen ini memungkinkan pedagang berdagang lintas wilayah tanpa membawa emas secara fisik, menjadi cikal bakal pasar yang mempertemukan pemilik dan pencari dana.",
      },
      {
        type: "takeaways",
        items: [
          "Pasar keuangan mempertemukan pemilik dana dengan pencari dana.",
          "Fungsinya: menyalurkan dana, menentukan harga, dan menyediakan likuiditas.",
          "Pihak surplus memperoleh imbal hasil; pihak defisit memperoleh modal.",
          "Pasar yang efisien menurunkan biaya dan risiko penyaluran modal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fungsi utama pasar keuangan adalah?",
            options: ["Mencetak uang", "Menyalurkan dana dari pihak surplus ke defisit", "Menentukan pajak", "Menjamin untung"],
            answer: 1,
            explain: "Pasar keuangan menyalurkan dana dari yang kelebihan ke yang membutuhkan.",
          },
          {
            q: "Yang termasuk pihak defisit dana?",
            options: ["Penabung", "Perusahaan yang butuh modal", "Investor", "Pemilik deposito"],
            answer: 1,
            explain: "Pihak defisit adalah yang membutuhkan dana, seperti perusahaan dan pemerintah.",
          },
          {
            q: "Likuiditas dalam pasar keuangan berarti?",
            options: ["Aset mudah dijual kembali menjadi uang", "Pasti untung", "Bebas pajak", "Tanpa risiko"],
            answer: 0,
            explain: "Likuiditas adalah kemudahan mengubah aset menjadi uang tunai.",
          },
          {
            q: "Manfaat pasar keuangan bagi perusahaan?",
            options: ["Menghindari pajak", "Memperoleh modal untuk tumbuh", "Menetapkan harga jual produk", "Menjamin laba"],
            answer: 1,
            explain: "Perusahaan memperoleh modal dari pasar untuk membiayai pertumbuhan.",
          },
          {
            q: "Investasi Rp20 juta dengan imbal hasil 10%. Imbal hasil rupiah?",
            options: ["Rp2 juta", "Rp200 ribu", "Rp20 juta", "Rp1 juta"],
            answer: 0,
            explain: "10% x Rp20 juta = Rp2 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jenis-pasar-keuangan",
    levelId: "fondasi",
    order: 2,
    title: "Jenis-Jenis Pasar Keuangan",
    summary: "Membedah pasar uang vs pasar modal, pasar primer vs sekunder, serta pasar spot vs derivatif.",
    durationMin: 13,
    tags: ["pasar uang", "pasar modal", "pasar primer", "pasar sekunder", "derivatif"],
    blocks: [
      {
        type: "paragraph",
        html: "Pasar keuangan tidak tunggal, melainkan terbagi menjadi beberapa jenis sesuai jangka waktu instrumen, tahap penerbitan, dan cara penyelesaian transaksi. Memahami pembagian ini membantu kita memilih instrumen yang tepat sesuai tujuan dan toleransi risiko.",
      },
      {
        type: "paragraph",
        html: "Tiga sumbu pembagian yang paling umum adalah: <strong>pasar uang vs pasar modal</strong> (berdasarkan jangka waktu), <strong>pasar primer vs sekunder</strong> (berdasarkan tahap penerbitan), dan <strong>pasar spot vs derivatif</strong> (berdasarkan waktu penyerahan aset).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pasar uang vs pasar modal",
        html: "<strong>Pasar uang</strong> memperdagangkan instrumen jangka pendek (kurang dari 1 tahun) seperti SBN jangka pendek, Sertifikat Bank Indonesia, dan deposito. <strong>Pasar modal</strong> memperdagangkan instrumen jangka panjang (lebih dari 1 tahun) seperti saham dan obligasi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pasar primer vs sekunder",
        html: "Di <strong>pasar primer</strong>, efek dijual pertama kali oleh emiten, misalnya saat IPO (penawaran umum perdana). Dana hasil penjualan masuk ke emiten. Di <strong>pasar sekunder</strong>, investor saling memperdagangkan efek yang sudah beredar; dana berpindah antarinvestor, bukan ke emiten.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Pasar spot vs derivatif",
        html: "Di <strong>pasar spot</strong>, transaksi diselesaikan segera dengan harga saat ini. Di <strong>pasar derivatif</strong>, nilai kontrak diturunkan dari aset lain (saham, indeks, komoditas) dan penyerahan dilakukan di masa depan, contohnya kontrak berjangka dan opsi.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Jangka Waktu Instrumen per Jenis Pasar (ilustrasi)",
        unit: "bulan (maksimum tipikal)",
        source: "ilustrasi pola umum",
        note: "Instrumen pasar uang berjangka pendek, sedangkan instrumen pasar modal berjangka panjang.",
        data: [
          { label: "SBI/SPN", value: 9, color: "#0ea5e9" },
          { label: "Deposito", value: 12, color: "#f59e0b" },
          { label: "Obligasi", value: 120, color: "#10b981" },
          { label: "Saham", value: 240, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Perjalanan satu lembar saham",
        html: "PT Sejahtera melakukan IPO dan menjual 100 juta saham seharga Rp1.000 per lembar di <strong>pasar primer</strong>, sehingga memperoleh Rp100 miliar untuk ekspansi. Sebulan kemudian, Pak Budi membeli 1.000 saham PT Sejahtera dari investor lain di Bursa Efek Indonesia seharga Rp1.200 per lembar. Transaksi Pak Budi terjadi di <strong>pasar sekunder</strong>, dan uangnya Rp1,2 juta mengalir ke penjual, bukan ke PT Sejahtera.",
      },
      {
        type: "calcExercise",
        prompt: "Emiten menjual 100 juta saham seharga Rp1.000 per lembar saat IPO. Berapa dana yang diperoleh emiten di pasar primer?",
        answer: 100000000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Dana = 100.000.000 lembar x Rp1.000 = <strong>Rp100 miliar</strong>.",
        hint: "Kalikan jumlah lembar saham dengan harga per lembar.",
      },
      {
        type: "classifyExercise",
        prompt: "Instrumen atau transaksi ini termasuk pasar uang atau pasar modal?",
        buckets: ["Pasar uang", "Pasar modal"],
        items: [
          { text: "Saham PT yang tercatat di BEI", bucket: "Pasar modal" },
          { text: "Sertifikat Bank Indonesia 9 bulan", bucket: "Pasar uang" },
          { text: "Obligasi korporasi 10 tahun", bucket: "Pasar modal" },
          { text: "Deposito berjangka 3 bulan", bucket: "Pasar uang" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya Bursa Efek Indonesia (BEI) 2007",
        html: "Pasar modal Indonesia dulu terbagi dua: <strong>Bursa Efek Jakarta (BEJ)</strong> yang fokus pada saham dan <strong>Bursa Efek Surabaya (BES)</strong> yang antara lain memperdagangkan obligasi dan derivatif. Pada <strong>1 Desember 2007</strong>, keduanya digabung menjadi <strong>Bursa Efek Indonesia (BEI)</strong> atau IDX. Penggabungan ini menyatukan berbagai jenis pasar dalam satu penyelenggara agar perdagangan lebih efisien.",
      },
      {
        type: "takeaways",
        items: [
          "Pasar uang untuk instrumen jangka pendek, pasar modal untuk jangka panjang.",
          "Pasar primer adalah penerbitan perdana; dananya masuk ke emiten.",
          "Pasar sekunder adalah perdagangan efek yang sudah beredar antarinvestor.",
          "Pasar derivatif menggunakan kontrak yang nilainya diturunkan dari aset lain.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Instrumen pasar uang memiliki ciri utama?",
            options: ["Jangka panjang lebih dari 1 tahun", "Jangka pendek kurang dari 1 tahun", "Selalu berupa saham", "Bebas risiko"],
            answer: 1,
            explain: "Pasar uang memperdagangkan instrumen jangka pendek, biasanya kurang dari satu tahun.",
          },
          {
            q: "Saat IPO, transaksi terjadi di pasar?",
            options: ["Pasar sekunder", "Pasar primer", "Pasar spot saja", "Pasar derivatif"],
            answer: 1,
            explain: "IPO adalah penawaran perdana yang terjadi di pasar primer, dananya masuk ke emiten.",
          },
          {
            q: "Ciri pasar sekunder adalah?",
            options: ["Dana masuk ke emiten", "Investor saling memperdagangkan efek yang sudah beredar", "Hanya untuk obligasi", "Tidak ada harga pasar"],
            answer: 1,
            explain: "Di pasar sekunder, investor memperdagangkan efek yang sudah beredar; dana berpindah antarinvestor.",
          },
          {
            q: "Kontrak berjangka dan opsi diperdagangkan di pasar?",
            options: ["Pasar spot", "Pasar derivatif", "Pasar uang", "Pasar primer"],
            answer: 1,
            explain: "Kontrak berjangka dan opsi adalah produk derivatif yang nilainya diturunkan dari aset lain.",
          },
          {
            q: "Investor membeli 1.000 saham seharga Rp1.200 di bursa. Total yang dibayar?",
            options: ["Rp120 ribu", "Rp1,2 juta", "Rp12 juta", "Rp120 juta"],
            answer: 1,
            explain: "1.000 lembar x Rp1.200 = Rp1,2 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pelaku-pasar-keuangan",
    levelId: "fondasi",
    order: 3,
    title: "Pelaku Pasar Keuangan",
    summary: "Mengenal investor ritel dan institusi, emiten, perusahaan sekuritas, manajer investasi, dan bank.",
    durationMin: 13,
    tags: ["investor", "emiten", "sekuritas", "manajer investasi", "bank"],
    blocks: [
      {
        type: "paragraph",
        html: "Pasar keuangan digerakkan oleh banyak pihak dengan peran berbeda. Sebagian menyediakan dana, sebagian membutuhkan dana, dan sebagian lagi menjadi perantara yang memperlancar transaksi. Memahami siapa berperan apa membantu kita melihat alur dana secara utuh.",
      },
      {
        type: "paragraph",
        html: "Pelaku utama meliputi <strong>investor</strong> (ritel dan institusi), <strong>emiten</strong>, <strong>perusahaan sekuritas atau broker</strong>, <strong>manajer investasi</strong>, dan <strong>bank</strong>. Masing-masing memiliki fungsi yang saling melengkapi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Investor ritel vs institusi",
        html: "<strong>Investor ritel</strong> adalah individu yang berinvestasi dengan dana pribadi, biasanya bernilai relatif kecil. <strong>Investor institusi</strong> adalah lembaga seperti dana pensiun, perusahaan asuransi, dan reksa dana yang mengelola dana besar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Emiten dan perantara",
        html: "<strong>Emiten</strong> adalah perusahaan yang menerbitkan efek (saham atau obligasi) untuk memperoleh dana. <strong>Perusahaan sekuritas</strong> menjadi perantara jual beli efek di bursa untuk investor. <strong>Manajer investasi</strong> mengelola dana investor secara kolektif lewat reksa dana.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Peran bank",
        html: "<strong>Bank</strong> menghimpun dana masyarakat lewat tabungan dan deposito, lalu menyalurkannya sebagai kredit. Bank juga aktif di pasar uang dan menjadi bank kustodian yang menyimpan efek investor.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Pelaku Pasar (ilustrasi)",
        unit: "% nilai transaksi",
        source: "ilustrasi pola umum",
        note: "Investor institusi sering mendominasi nilai transaksi meski jumlah investor ritel jauh lebih banyak.",
        data: [
          { label: "Investor institusi", value: 50, color: "#0ea5e9" },
          { label: "Investor ritel", value: 25, color: "#f59e0b" },
          { label: "Bank", value: 15, color: "#10b981" },
          { label: "Manajer investasi", value: 10, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Satu transaksi, banyak pelaku",
        html: "Bu Rina (investor ritel) ingin membeli saham PT Andalan (emiten) senilai Rp10 juta. Ia memberi order lewat aplikasi perusahaan sekuritas (broker), yang meneruskan order ke bursa. Karena tak punya waktu memilih saham satu per satu, Bu Rina juga menaruh Rp5 juta di reksa dana yang dikelola manajer investasi. Sementara itu, dana darurat Rp20 juta ia simpan sebagai deposito di bank. Dalam satu hari, Bu Rina berinteraksi dengan empat jenis pelaku pasar sekaligus.",
      },
      {
        type: "calcExercise",
        prompt: "Bu Rina berinvestasi Rp10 juta di saham, Rp5 juta di reksa dana, dan Rp20 juta di deposito. Berapa total dana yang ia tempatkan?",
        answer: 35000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Total = Rp10 juta + Rp5 juta + Rp20 juta = <strong>Rp35 juta</strong>.",
        hint: "Jumlahkan ketiga penempatan dana tersebut.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan setiap pelaku pasar dengan perannya.",
        pairs: [
          { left: "Investor ritel", right: "Individu yang berinvestasi dengan dana pribadi" },
          { left: "Emiten", right: "Perusahaan yang menerbitkan efek untuk memperoleh dana" },
          { left: "Perusahaan sekuritas", right: "Perantara jual beli efek di bursa" },
          { left: "Manajer investasi", right: "Mengelola dana investor lewat reksa dana" },
          { left: "Bank", right: "Menghimpun dan menyalurkan dana lewat tabungan dan kredit" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Skema Ponzi Bernie Madoff 2008",
        html: "Salah satu pelaku pasar paling terkenal karena penipuan adalah <strong>Bernie Madoff</strong>, manajer investasi terpandang yang pernah menjadi ketua bursa Nasdaq. Pada <strong>Desember 2008</strong> terungkap bahwa ia menjalankan <strong>skema Ponzi</strong> raksasa, membayar imbal hasil investor lama dari setoran investor baru, bukan dari hasil investasi nyata. Kerugian yang dilaporkan mencapai sekitar <strong>USD 65 miliar</strong> (termasuk keuntungan fiktif), mengingatkan bahwa reputasi pelaku pasar tidak menjamin kejujuran.",
      },
      {
        type: "takeaways",
        items: [
          "Investor ritel adalah individu; investor institusi adalah lembaga pengelola dana besar.",
          "Emiten menerbitkan efek untuk memperoleh dana dari pasar.",
          "Perusahaan sekuritas menjadi perantara jual beli efek di bursa.",
          "Manajer investasi mengelola dana investor secara kolektif lewat reksa dana.",
          "Bank menghimpun dan menyalurkan dana serta dapat menjadi kustodian.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Yang termasuk investor institusi adalah?",
            options: ["Karyawan yang menabung sendiri", "Dana pensiun", "Mahasiswa pembeli reksa dana", "Pedagang kecil"],
            answer: 1,
            explain: "Dana pensiun adalah lembaga pengelola dana besar, sehingga tergolong investor institusi.",
          },
          {
            q: "Pihak yang menerbitkan saham untuk memperoleh dana disebut?",
            options: ["Broker", "Emiten", "Kustodian", "Manajer investasi"],
            answer: 1,
            explain: "Emiten adalah perusahaan yang menerbitkan efek untuk memperoleh dana.",
          },
          {
            q: "Peran utama perusahaan sekuritas adalah?",
            options: ["Mencetak uang", "Menjadi perantara jual beli efek di bursa", "Menetapkan suku bunga acuan", "Mengawasi pasar modal"],
            answer: 1,
            explain: "Perusahaan sekuritas atau broker menjadi perantara order jual beli efek di bursa.",
          },
          {
            q: "Manajer investasi bertugas?",
            options: ["Mengelola dana investor lewat reksa dana", "Menerbitkan obligasi pemerintah", "Mengatur kebijakan moneter", "Menjamin keuntungan"],
            answer: 0,
            explain: "Manajer investasi mengelola dana investor secara kolektif melalui produk reksa dana.",
          },
          {
            q: "Bu Rina menempatkan Rp10 juta, Rp5 juta, dan Rp20 juta. Total dananya?",
            options: ["Rp25 juta", "Rp30 juta", "Rp35 juta", "Rp40 juta"],
            answer: 2,
            explain: "Rp10 juta + Rp5 juta + Rp20 juta = Rp35 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "regulator-dan-lembaga",
    levelId: "fondasi",
    order: 4,
    title: "Regulator dan Lembaga Penunjang",
    summary: "Mengenal OJK, Bank Indonesia, BEI, KSEI, dan KPEI serta peran masing-masing di pasar keuangan Indonesia.",
    durationMin: 14,
    tags: ["OJK", "Bank Indonesia", "BEI", "KSEI", "KPEI", "regulator"],
    blocks: [
      {
        type: "paragraph",
        html: "Agar pasar keuangan berjalan adil, aman, dan teratur, dibutuhkan regulator dan lembaga penunjang. Di Indonesia, beberapa lembaga bekerja bersama: ada yang mengawasi, ada yang menjaga stabilitas moneter, ada yang menyediakan tempat transaksi, dan ada yang menyelesaikan administrasi pasca-transaksi.",
      },
      {
        type: "paragraph",
        html: "Lima lembaga utama yang perlu dikenal adalah <strong>OJK</strong>, <strong>Bank Indonesia</strong>, <strong>Bursa Efek Indonesia (BEI)</strong>, <strong>KSEI</strong>, dan <strong>KPEI</strong>. Tiga yang terakhir membentuk infrastruktur inti pasar modal Indonesia.",
      },
      {
        type: "callout",
        tone: "key",
        title: "OJK dan Bank Indonesia",
        html: "<strong>OJK (Otoritas Jasa Keuangan)</strong> mengatur dan mengawasi seluruh sektor jasa keuangan: perbankan, pasar modal, dan industri keuangan non-bank. <strong>Bank Indonesia</strong> adalah bank sentral yang menjaga stabilitas nilai rupiah lewat kebijakan moneter dan mengawasi sistem pembayaran.",
      },
      {
        type: "callout",
        tone: "info",
        title: "BEI, KSEI, dan KPEI",
        html: "<strong>BEI</strong> menyediakan sistem perdagangan tempat efek diperjualbelikan. <strong>KSEI (Kustodian Sentral Efek Indonesia)</strong> menyimpan dan mengadministrasikan efek (kustodian sentral). <strong>KPEI (Kliring Penjaminan Efek Indonesia)</strong> melakukan kliring dan penjaminan penyelesaian transaksi bursa.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan tertukar",
        html: "OJK adalah pengawas, bukan tempat transaksi. Bank Indonesia mengurus kebijakan moneter, bukan mengawasi emiten saham. Selalu cocokkan setiap lembaga dengan fungsinya agar tidak keliru.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Fokus Pengawasan dan Fungsi Lembaga (ilustrasi bobot peran)",
        unit: "skor relatif",
        source: "ilustrasi pola umum",
        note: "Setiap lembaga memiliki domain fokus yang berbeda namun saling melengkapi.",
        data: [
          { label: "OJK (pengawasan)", value: 100, color: "#0ea5e9" },
          { label: "BI (moneter)", value: 90, color: "#f59e0b" },
          { label: "BEI (bursa)", value: 80, color: "#10b981" },
          { label: "KSEI (kustodi)", value: 70, color: "#8b5cf6" },
          { label: "KPEI (kliring)", value: 65, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Perjalanan transaksi saham Pak Joko",
        html: "Pak Joko membeli 5.000 saham seharga Rp2.000 per lembar lewat aplikasi sekuritas, total Rp10 juta. Order diteruskan ke sistem <strong>BEI</strong> dan bertemu penjual. Setelah transaksi cocok, <strong>KPEI</strong> melakukan kliring dan menjamin penyelesaiannya, lalu <strong>KSEI</strong> mencatat 5.000 saham tersebut atas nama Pak Joko di rekening efeknya. Sepanjang proses, <strong>OJK</strong> memastikan semua pihak mematuhi aturan, sementara <strong>Bank Indonesia</strong> menjaga kelancaran sistem pembayaran rupiah yang mendasarinya.",
      },
      {
        type: "calcExercise",
        prompt: "Pak Joko membeli 5.000 saham seharga Rp2.000 per lembar. Berapa nilai transaksinya?",
        answer: 10000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai transaksi = 5.000 lembar x Rp2.000 = <strong>Rp10 juta</strong>.",
        hint: "Kalikan jumlah lembar saham dengan harga per lembar.",
      },
      {
        type: "classifyExercise",
        prompt: "Tugas berikut menjadi tanggung jawab lembaga mana?",
        buckets: ["OJK", "Bank Indonesia", "BEI", "KSEI", "KPEI"],
        items: [
          { text: "Mengawasi sektor jasa keuangan", bucket: "OJK" },
          { text: "Menjaga stabilitas nilai rupiah lewat kebijakan moneter", bucket: "Bank Indonesia" },
          { text: "Menyediakan sistem perdagangan efek", bucket: "BEI" },
          { text: "Menyimpan dan mengadministrasikan efek investor", bucket: "KSEI" },
          { text: "Melakukan kliring dan penjaminan transaksi bursa", bucket: "KPEI" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Crash Wall Street 1929 melahirkan regulator pasar",
        html: "Regulator pasar modal modern banyak lahir dari krisis. <strong>Keruntuhan bursa Wall Street pada Oktober 1929</strong> menghapus kekayaan investor dalam waktu singkat dan menjadi pemicu Depresi Besar. Sebagai respons, Amerika Serikat membentuk <strong>Securities and Exchange Commission (SEC)</strong> pada <strong>1934</strong> untuk mengawasi pasar dan melindungi investor. Di Indonesia, peran pengawasan serupa kini diemban <strong>OJK</strong>.",
      },
      {
        type: "takeaways",
        items: [
          "OJK mengatur dan mengawasi seluruh sektor jasa keuangan.",
          "Bank Indonesia menjaga stabilitas rupiah lewat kebijakan moneter.",
          "BEI menyediakan sistem perdagangan tempat efek diperjualbelikan.",
          "KSEI adalah kustodian sentral yang menyimpan dan mencatat efek.",
          "KPEI melakukan kliring dan penjaminan penyelesaian transaksi bursa.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Lembaga yang mengatur dan mengawasi seluruh sektor jasa keuangan adalah?",
            options: ["Bank Indonesia", "OJK", "BEI", "KSEI"],
            answer: 1,
            explain: "OJK mengatur dan mengawasi perbankan, pasar modal, dan industri keuangan non-bank.",
          },
          {
            q: "Fungsi utama Bank Indonesia adalah?",
            options: ["Mengawasi emiten", "Menjaga stabilitas nilai rupiah lewat kebijakan moneter", "Menyimpan efek investor", "Menyediakan sistem bursa"],
            answer: 1,
            explain: "Bank Indonesia adalah bank sentral yang menjaga stabilitas rupiah dan sistem pembayaran.",
          },
          {
            q: "Lembaga yang menyimpan dan mengadministrasikan efek (kustodian sentral) adalah?",
            options: ["KPEI", "BEI", "KSEI", "OJK"],
            answer: 2,
            explain: "KSEI adalah Kustodian Sentral Efek Indonesia yang menyimpan dan mencatat efek.",
          },
          {
            q: "Kliring dan penjaminan penyelesaian transaksi bursa dilakukan oleh?",
            options: ["KPEI", "KSEI", "Bank Indonesia", "BEI"],
            answer: 0,
            explain: "KPEI (Kliring Penjaminan Efek Indonesia) melakukan kliring dan penjaminan transaksi bursa.",
          },
          {
            q: "Pak Joko membeli 5.000 saham seharga Rp2.000 per lembar. Nilai transaksinya?",
            options: ["Rp1 juta", "Rp10 juta", "Rp100 juta", "Rp5 juta"],
            answer: 1,
            explain: "5.000 lembar x Rp2.000 = Rp10 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "risiko-dan-imbal-hasil",
    levelId: "fondasi",
    order: 5,
    title: "Risiko dan Imbal Hasil",
    summary: "Prinsip dasar yang menjiwai seluruh pasar keuangan: imbal hasil lebih tinggi menuntut risiko lebih besar.",
    durationMin: 13,
    tags: ["risiko", "imbal hasil", "premi risiko", "trade-off"],
    blocks: [
      {
        type: "paragraph",
        html: "Satu prinsip menjiwai seluruh pasar keuangan: <strong>imbal hasil (return)</strong> yang lebih tinggi hampir selalu menuntut <strong>risiko</strong> yang lebih besar. Tidak ada makan siang gratis. Bila sebuah produk menjanjikan imbal hasil tinggi tanpa risiko, itu pertanda untuk waspada.",
      },
      {
        type: "paragraph",
        html: "<strong>Risiko</strong> adalah kemungkinan hasil nyata berbeda dari yang diharapkan, termasuk kemungkinan rugi. <strong>Premi risiko</strong> adalah tambahan imbal hasil yang diminta investor sebagai kompensasi karena menanggung risiko lebih besar dibanding aset paling aman.",
      },
      {
        type: "video",
        comp: "AlurPasarKeuangan",
        title: "Video: Aliran Dana dan Imbal Hasil",
        caption: "Pemilik dana menyalurkan modal dan menuntut imbal hasil sesuai risiko yang ditanggung.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Trade-off risiko dan imbal hasil",
        html: "Semakin besar potensi imbal hasil, semakin besar pula potensi kerugian. Deposito aman tetapi imbal hasilnya kecil; saham berpotensi tinggi tetapi harganya bisa turun tajam.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Kelola, bukan hindari",
        html: "Risiko tidak bisa dihilangkan sepenuhnya, tetapi bisa dikelola lewat <strong>diversifikasi</strong> (menyebar dana ke banyak aset) dan menyesuaikan pilihan dengan jangka waktu serta tujuan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Waspadai janji manis",
        html: "Imbal hasil tinggi yang dijanjikan pasti dan tanpa risiko adalah ciri klasik penipuan. Cocokkan selalu tingkat imbal hasil dengan risiko yang masuk akal.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tangga Risiko dan Imbal Hasil per Jenis Aset (ilustrasi)",
        unit: "% imbal hasil tahunan (perkiraan)",
        source: "ilustrasi pola umum jangka panjang",
        note: "Makin tinggi posisi pada tangga, makin besar imbal hasil yang diharapkan dan makin besar risikonya.",
        data: [
          { label: "Deposito", value: 6, color: "#10b981" },
          { label: "Obligasi negara", value: 7, color: "#0ea5e9" },
          { label: "Obligasi korporasi", value: 9, color: "#f59e0b" },
          { label: "Saham", value: 12, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Premi risiko saham",
        html: "Bu Dewi membandingkan dua pilihan. <strong>Deposito</strong> memberi imbal hasil 6% per tahun dengan risiko sangat rendah. <strong>Saham</strong> secara historis memberi rata-rata sekitar 12% per tahun, tetapi nilainya bisa turun tajam dalam setahun tertentu. Selisih 12% - 6% = <strong>6% per tahun</strong> adalah premi risiko, yaitu imbalan tambahan yang dituntut Bu Dewi karena bersedia menanggung naik turunnya harga saham.",
      },
      {
        type: "calcExercise",
        prompt: "Saham diharapkan beri imbal hasil 12% per tahun, deposito 6%. Berapa premi risiko saham (dalam poin persen)?",
        answer: 6,
        tolerance: 0,
        suffix: "%",
        solution: "Premi risiko = imbal hasil saham - imbal hasil aset aman = 12% - 6% = <strong>6 poin persen</strong>.",
        hint: "Kurangkan imbal hasil aset paling aman dari imbal hasil aset berisiko.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan instrumen berikut sebagai risiko rendah atau risiko tinggi.",
        buckets: ["Risiko rendah", "Risiko tinggi"],
        items: [
          { text: "Deposito berjangka", bucket: "Risiko rendah" },
          { text: "Obligasi negara (SBN)", bucket: "Risiko rendah" },
          { text: "Saham perusahaan kecil", bucket: "Risiko tinggi" },
          { text: "Obligasi korporasi high yield", bucket: "Risiko tinggi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis 2008 dan ilusi imbal hasil tinggi tanpa risiko",
        html: "Menjelang <strong>krisis keuangan 2008</strong>, banyak produk berbasis kredit perumahan (KPR subprime) dikemas ulang dan diberi peringkat tertinggi <strong>AAA</strong> sambil menawarkan imbal hasil lebih tinggi dari obligasi negara. Investor mengira mereka mendapat imbal hasil ekstra nyaris tanpa tambahan risiko. Ketika gagal bayar KPR melonjak pada <strong>2007-2008</strong>, nilai produk itu runtuh dan turut menjatuhkan <strong>Lehman Brothers</strong> pada September 2008. Pelajarannya jelas: imbal hasil ekstra selalu membawa risiko ekstra, meski sempat tersembunyi.",
      },
      {
        type: "takeaways",
        items: [
          "Imbal hasil lebih tinggi hampir selalu menuntut risiko lebih besar.",
          "Premi risiko adalah tambahan imbal hasil sebagai kompensasi risiko.",
          "Deposito aman dengan imbal hasil kecil; saham berpotensi tinggi tetapi fluktuatif.",
          "Risiko dikelola lewat diversifikasi dan penyesuaian dengan tujuan.",
          "Janji imbal hasil tinggi tanpa risiko adalah tanda bahaya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Prinsip dasar yang menjiwai pasar keuangan adalah?",
            options: ["Imbal hasil tinggi selalu aman", "Imbal hasil lebih tinggi menuntut risiko lebih besar", "Risiko selalu bisa dihilangkan", "Deposito paling menguntungkan"],
            answer: 1,
            explain: "Trade-off risiko dan imbal hasil: potensi imbal hasil lebih tinggi diiringi risiko lebih besar.",
          },
          {
            q: "Premi risiko adalah?",
            options: ["Biaya broker", "Tambahan imbal hasil sebagai kompensasi risiko", "Pajak atas keuntungan", "Bunga deposito"],
            answer: 1,
            explain: "Premi risiko adalah imbal hasil ekstra yang dituntut karena menanggung risiko lebih besar.",
          },
          {
            q: "Cara utama mengelola risiko investasi adalah?",
            options: ["Menaruh semua dana di satu saham", "Diversifikasi ke banyak aset", "Menghindari pasar sepenuhnya", "Mengejar imbal hasil tertinggi"],
            answer: 1,
            explain: "Diversifikasi menyebar dana sehingga kerugian satu aset tidak menghancurkan seluruh portofolio.",
          },
          {
            q: "Produk yang menjanjikan imbal hasil tinggi tanpa risiko sebaiknya?",
            options: ["Langsung dibeli", "Diwaspadai sebagai tanda bahaya", "Disebarkan ke teman", "Dianggap pasti benar"],
            answer: 1,
            explain: "Imbal hasil tinggi tanpa risiko bertentangan dengan prinsip pasar dan sering jadi ciri penipuan.",
          },
          {
            q: "Saham diharapkan 11%, deposito 5%. Premi risikonya?",
            options: ["5%", "6%", "11%", "16%"],
            answer: 1,
            explain: "11% - 5% = 6 poin persen.",
          },
        ],
      },
    ],
  },
];
