import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "derivatif-futures-opsi",
    levelId: "derivatif",
    order: 1,
    title: "Derivatif: Futures, Opsi & Swap",
    summary: "Instrumen yang nilainya berasal dari aset lain, untuk hedging maupun spekulasi. Dengan video & kalkulator opsi.",
    durationMin: 14,
    tags: ["derivatif", "opsi", "futures", "hedging"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Derivatif</strong> adalah kontrak yang nilainya <strong>diturunkan</strong> dari aset lain (saham, indeks, komoditas, valas, suku bunga). Tiga jenis utama: <strong>futures</strong> (kontrak beli/jual di masa depan pada harga disepakati), <strong>opsi</strong> (hak, bukan kewajiban), dan <strong>swap</strong> (pertukaran arus kas).",
      },
      {
        type: "video",
        comp: "OpsiCallPut",
        title: "Video: Opsi Call vs Put",
        caption: "Animasi payoff opsi call (taruhan naik) dan put (taruhan turun).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua fungsi derivatif",
        html: "<strong>Hedging</strong>: melindungi dari risiko harga (mis. eksportir mengunci kurs). <strong>Spekulasi</strong>: bertaruh pada arah harga dengan modal relatif kecil (leverage). Derivatif memperbesar potensi untung sekaligus rugi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Pedang bermata dua",
        html: "Karena memakai leverage, derivatif bisa menghasilkan kerugian jauh lebih besar dari modal awal bila dipakai untuk spekulasi tanpa pemahaman. Pembeli opsi, namun, kerugiannya terbatas pada premi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur tipe opsi (call/put), strike, premi, dan harga spot untuk melihat payoff dan titik impasnya.",
      },
      { type: "widget", widget: "KalkulatorOpsi" },
      {
        type: "chart",
        variant: "bar",
        title: "Payoff Opsi Call saat Jatuh Tempo (strike 10.000, premi 500)",
        unit: "Rp payoff per saham",
        source: "ilustrasi edukatif",
        note: "Kerugian terbatas pada premi (Rp500) saat harga di bawah strike; potensi untung naik seiring harga.",
        data: [
          { label: "Spot 9.000", value: -500, color: "#ef4444" },
          { label: "Spot 10.000", value: -500, color: "#ef4444" },
          { label: "Spot 10.500", value: 0, color: "#f59e0b" },
          { label: "Spot 11.000", value: 500, color: "#10b981" },
          { label: "Spot 12.000", value: 1500, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Petani mengunci harga dengan futures",
        html: "Seorang petani kopi khawatir harga turun saat panen 3 bulan lagi. Ia menjual <strong>kontrak futures</strong> kopi pada harga Rp60.000/kg untuk pengiriman 3 bulan. Saat panen, apa pun harga pasar, ia sudah mengunci Rp60.000/kg. Jika harga turun ke Rp50.000, ia terlindungi; jika naik ke Rp70.000, ia melepas potensi untung itu. Inilah hedging: menukar ketidakpastian dengan kepastian.",
      },
      {
        type: "calcExercise",
        prompt: "Investor beli opsi call, strike Rp10.000, premi Rp500. Saat jatuh tempo harga Rp11.200. Berapa payoff bersih per saham (Rp)?",
        answer: 700,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai intrinsik = Rp11.200 - Rp10.000 = Rp1.200. Payoff bersih = Rp1.200 - Rp500 premi = <strong>Rp700</strong>.",
        hint: "Intrinsik = spot - strike. Lalu kurangi premi.",
      },
      {
        type: "classifyExercise",
        prompt: "Aktivitas ini termasuk hedging atau spekulasi?",
        buckets: ["Hedging (lindung nilai)", "Spekulasi"],
        items: [
          { text: "Eksportir mengunci kurs dengan forward", bucket: "Hedging (lindung nilai)" },
          { text: "Trader beli opsi bertaruh harga melonjak", bucket: "Spekulasi" },
          { text: "Petani menjual futures atas panennya", bucket: "Hedging (lindung nilai)" },
          { text: "Membeli kontrak hanya untuk untung jangka pendek", bucket: "Spekulasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Portfolio insurance memperparah Black Monday 1987",
        html: "Strategi berbasis derivatif dapat memperbesar guncangan pasar. Pada <strong>Black Monday, 19 Oktober 1987</strong>, strategi <strong>portfolio insurance</strong> yang otomatis menjual kontrak <strong>futures</strong> indeks saat harga turun justru memicu gelombang jual beruntun. Indeks <strong>Dow Jones</strong> anjlok sekitar <strong>22,6% dalam sehari</strong>, memperlihatkan bahwa derivatif dan leverage bisa menjadi pedang bermata dua.",
      },
      {
        type: "takeaways",
        items: [
          "Derivatif memperoleh nilai dari aset lain (underlying).",
          "Jenis utama: futures, opsi, dan swap.",
          "Fungsinya untuk hedging (lindung nilai) dan spekulasi.",
          "Leverage memperbesar untung dan rugi; kerugian pembeli opsi terbatas pada premi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Derivatif adalah kontrak yang nilainya berasal dari?",
            options: ["Cetakan uang baru", "Aset lain (underlying)", "Pajak", "Gaji"],
            answer: 1,
            explain: "Nilai derivatif diturunkan dari aset acuan seperti saham, komoditas, atau valas.",
          },
          {
            q: "Opsi memberi pemegangnya?",
            options: ["Kewajiban membeli", "Hak, bukan kewajiban", "Jaminan untung", "Dividen"],
            answer: 1,
            explain: "Opsi adalah hak (bukan kewajiban) membeli/menjual pada harga tertentu.",
          },
          {
            q: "Tujuan hedging adalah?",
            options: ["Memperbesar risiko", "Melindungi dari risiko harga", "Menghindari pajak", "Menjamin untung besar"],
            answer: 1,
            explain: "Hedging menukar ketidakpastian harga dengan kepastian.",
          },
          {
            q: "Kerugian maksimum pembeli opsi adalah?",
            options: ["Tak terbatas", "Sebesar premi yang dibayar", "Nol", "Seluruh kekayaan"],
            answer: 1,
            explain: "Pembeli opsi paling banyak kehilangan premi bila opsi tak bernilai.",
          },
          {
            q: "Call strike Rp5.000, premi Rp300, spot jatuh tempo Rp5.800. Payoff bersih?",
            options: ["Rp500", "Rp800", "Rp300", "Rp1.100"],
            answer: 0,
            explain: "Intrinsik 5.800-5.000=800; dikurangi premi 300 = Rp500.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pasar-valas",
    levelId: "derivatif",
    order: 2,
    title: "Pasar Valuta Asing (Valas)",
    summary: "Pasangan mata uang, kurs jual/beli, spread, apresiasi vs depresiasi, dan dampaknya ke importir & eksportir. Dengan simulator valas.",
    durationMin: 13,
    tags: ["valas", "forex", "kurs", "mata uang"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pasar valuta asing (valas/forex)</strong> adalah pasar tempat mata uang diperdagangkan satu sama lain. Ini adalah pasar terbesar di dunia dengan volume harian melebihi USD 7 triliun. Mata uang selalu diperdagangkan dalam <strong>pasangan</strong>, misalnya USD/IDR, karena harga satu mata uang dinyatakan dalam mata uang lain.",
      },
      {
        type: "paragraph",
        html: "Dalam pasangan <strong>USD/IDR = 16.000</strong>, USD adalah mata uang dasar (base) dan IDR mata uang penghitung (quote). Artinya 1 USD bernilai Rp16.000. Bank dan money changer mengutip dua harga: <strong>kurs beli</strong> (harga mereka membeli USD dari Anda) dan <strong>kurs jual</strong> (harga mereka menjual USD ke Anda). Selisihnya disebut <strong>spread</strong>, yaitu keuntungan penyedia jasa.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Apresiasi vs depresiasi",
        html: "<strong>Apresiasi</strong>: nilai mata uang menguat (butuh lebih sedikit rupiah untuk 1 USD, mis. dari Rp16.000 ke Rp15.500). <strong>Depresiasi</strong>: nilai mata uang melemah (butuh lebih banyak rupiah, mis. dari Rp16.000 ke Rp16.500). Saat USD/IDR naik, rupiah melemah (depresiasi) terhadap dolar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kurs jual selalu lebih tinggi dari kurs beli",
        html: "Dari sudut pandang bank, mereka membeli USD murah (kurs beli) dan menjual mahal (kurs jual). Bagi nasabah, membeli USD memakai kurs jual bank. Spread inilah biaya tersembunyi setiap kali Anda menukar uang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah kurs, jumlah, dan arah transaksi untuk melihat berapa rupiah atau dolar yang Anda terima setelah memperhitungkan spread.",
      },
      { type: "widget", widget: "SimulatorValas" },
      {
        type: "chart",
        variant: "line",
        title: "Ilustrasi pergerakan kurs USD/IDR",
        unit: "Rp per USD",
        source: "Ilustrasi edukatif",
        note: "Kurs naik berarti rupiah terdepresiasi terhadap dolar.",
        data: [
          { label: "Jan", value: 15600, color: "#2563eb" },
          { label: "Feb", value: 15800, color: "#2563eb" },
          { label: "Mar", value: 16100, color: "#2563eb" },
          { label: "Apr", value: 15900, color: "#2563eb" },
          { label: "Mei", value: 16300, color: "#2563eb" },
          { label: "Jun", value: 16500, color: "#2563eb" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dampak depresiasi ke importir & eksportir",
        html: "Rupiah melemah dari Rp15.000 ke Rp16.500 per USD. <strong>Importir</strong> yang membeli barang USD 100.000 kini membayar Rp1,65 miliar, naik dari Rp1,5 miliar, jadi biayanya bertambah Rp150 juta, merugikan. <strong>Eksportir</strong> yang menerima USD 100.000 kini memperoleh Rp1,65 miliar, naik Rp150 juta dalam rupiah, jadi diuntungkan. Karena itu depresiasi rupiah baik bagi eksportir tetapi memberatkan importir.",
      },
      {
        type: "calcExercise",
        prompt: "Money changer pasang kurs beli USD Rp15.800 dan kurs jual Rp16.200. Berapa spread per USD (Rp)?",
        answer: 400,
        tolerance: 0,
        prefix: "Rp",
        solution: "Spread = kurs jual - kurs beli = Rp16.200 - Rp15.800 = <strong>Rp400</strong> per USD.",
        hint: "Spread = kurs jual dikurangi kurs beli.",
      },
      {
        type: "classifyExercise",
        prompt: "Peristiwa ini menggambarkan apresiasi atau depresiasi rupiah?",
        buckets: ["Apresiasi rupiah", "Depresiasi rupiah"],
        items: [
          { text: "USD/IDR turun dari Rp16.000 ke Rp15.400", bucket: "Apresiasi rupiah" },
          { text: "USD/IDR naik dari Rp15.500 ke Rp16.300", bucket: "Depresiasi rupiah" },
          { text: "Butuh lebih banyak rupiah untuk membeli 1 USD", bucket: "Depresiasi rupiah" },
          { text: "Rupiah menguat, 1 USD jadi lebih murah", bucket: "Apresiasi rupiah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Asia 1997 berawal di pasar valas",
        html: "<strong>Krisis Moneter Asia</strong> bermula di pasar valas. Pada <strong>2 Juli 1997</strong>, Thailand melepas patokan <strong>baht</strong> terhadap dolar AS sehingga baht jatuh, lalu krisis menjalar ke kawasan. Rupiah ikut terjun dari sekitar <strong>Rp2.400</strong> menjadi sempat menembus <strong>Rp16.000 per USD</strong> pada awal 1998, memukul importir dan perusahaan berutang dolar, tetapi menolong sebagian eksportir.",
      },
      {
        type: "takeaways",
        items: [
          "Valas diperdagangkan dalam pasangan, mis. USD/IDR.",
          "Kurs jual lebih tinggi dari kurs beli; selisihnya adalah spread.",
          "Apresiasi = mata uang menguat; depresiasi = melemah.",
          "Depresiasi rupiah menguntungkan eksportir dan memberatkan importir.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam pasangan USD/IDR, IDR berperan sebagai?",
            options: ["Mata uang dasar (base)", "Mata uang penghitung (quote)", "Komoditas", "Suku bunga"],
            answer: 1,
            explain: "Mata uang yang disebut belakangan adalah quote; harga base dinyatakan dalam quote.",
          },
          {
            q: "Spread adalah?",
            options: ["Pajak transaksi", "Selisih kurs jual dan kurs beli", "Bunga deposito", "Kurs tengah BI"],
            answer: 1,
            explain: "Spread = kurs jual - kurs beli, yaitu keuntungan penyedia jasa penukaran.",
          },
          {
            q: "USD/IDR naik dari Rp16.000 ke Rp16.800 berarti rupiah?",
            options: ["Apresiasi", "Depresiasi", "Stabil", "Didevaluasi pemerintah"],
            answer: 1,
            explain: "Butuh lebih banyak rupiah untuk 1 USD, jadi rupiah melemah (depresiasi).",
          },
          {
            q: "Depresiasi rupiah umumnya menguntungkan?",
            options: ["Importir", "Eksportir", "Wisatawan ke luar negeri", "Pembayar utang dolar"],
            answer: 1,
            explain: "Pendapatan dolar eksportir bernilai lebih banyak rupiah saat rupiah melemah.",
          },
          {
            q: "Kurs beli Rp15.700, kurs jual Rp16.100. Spread per USD?",
            options: ["Rp300", "Rp400", "Rp500", "Rp600"],
            answer: 1,
            explain: "16.100 - 15.700 = Rp400.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "hedging-dengan-derivatif",
    levelId: "derivatif",
    order: 3,
    title: "Hedging dengan Derivatif",
    summary: "Memakai forward, futures, dan opsi untuk lindung nilai risiko kurs dan harga. Dengan simulator hedging FX.",
    durationMin: 14,
    tags: ["hedging", "forward", "lindung nilai", "kurs"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Hedging</strong> (lindung nilai) adalah strategi mengurangi risiko kerugian akibat pergerakan harga atau kurs yang merugikan. Perusahaan dengan pendapatan atau biaya dalam mata uang asing menghadapi <strong>risiko kurs</strong>; produsen komoditas menghadapi <strong>risiko harga</strong>. Derivatif seperti forward, futures, dan opsi adalah alat utama untuk mengelola risiko ini.",
      },
      {
        type: "paragraph",
        html: "Tiga instrumen umum: <strong>Forward</strong> mengunci kurs untuk transaksi di masa depan lewat kontrak bilateral dengan bank (kewajiban). <strong>Futures</strong> serupa tetapi terstandar dan diperdagangkan di bursa. <strong>Opsi</strong> memberi hak (bukan kewajiban) sehingga Anda terlindungi dari sisi buruk namun tetap bisa menikmati sisi baik, dengan membayar premi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Forward mengunci, opsi memberi pilihan",
        html: "Dengan <strong>forward</strong> Anda terkunci pada satu kurs apa pun yang terjadi. Dengan <strong>opsi</strong> Anda bisa memilih tidak mengeksekusi bila pasar bergerak menguntungkan, tetapi membayar premi di muka sebagai biaya fleksibilitas.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hedging bukan untuk cari untung",
        html: "Tujuan hedging adalah kepastian, bukan memaksimalkan laba. Bila pasar bergerak menguntungkan, posisi hedge bisa terlihat rugi di atas kertas, tetapi itu adalah harga dari kepastian. Over-hedging atau memakai hedge untuk berspekulasi justru menambah risiko.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan posisi tanpa hedge versus dengan forward/opsi pada berbagai skenario kurs untuk melihat bagaimana hedging meratakan hasil.",
      },
      { type: "widget", widget: "SimulatorHedgingFX" },
      {
        type: "chart",
        variant: "bar",
        title: "Hasil rupiah importir: tanpa hedge vs dengan forward",
        unit: "Rp juta untuk USD 100.000",
        source: "Ilustrasi edukatif",
        note: "Forward mengunci biaya di Rp1.600 juta apa pun kurs spot.",
        data: [
          { label: "Spot Rp15.500 (tanpa hedge)", value: 1550, color: "#16a34a" },
          { label: "Spot Rp16.800 (tanpa hedge)", value: 1680, color: "#dc2626" },
          { label: "Forward Rp16.000 (terkunci)", value: 1600, color: "#2563eb" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Importir mengunci kurs dengan forward",
        html: "Sebuah pabrik harus membayar pemasok USD 100.000 dalam 3 bulan. Kurs spot sekarang Rp16.000. Khawatir rupiah melemah, ia membeli <strong>kontrak forward</strong> pada Rp16.000. Tiga bulan kemudian kurs spot naik ke Rp16.800. Tanpa hedge ia harus membayar Rp1,68 miliar, tetapi dengan forward ia tetap membayar Rp1,6 miliar, sehingga menghemat Rp80 juta. Bila kurs justru turun ke Rp15.500, ia tetap terkunci di Rp1,6 miliar dan kehilangan potensi penghematan Rp50 juta, itulah harga kepastian.",
      },
      {
        type: "calcExercise",
        prompt: "Importir kunci forward USD 50.000 pada Rp16.000. Saat jatuh tempo kurs spot Rp16.700. Berapa rupiah yang dihemat berkat hedge (Rp juta)?",
        answer: 35,
        tolerance: 0,
        suffix: " juta",
        solution: "Tanpa hedge = 50.000 x Rp16.700 = Rp835 juta. Dengan forward = 50.000 x Rp16.000 = Rp800 juta. Penghematan = Rp835 juta - Rp800 juta = <strong>Rp35 juta</strong>.",
        hint: "Hitung biaya kurs spot dikurangi biaya kurs forward.",
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan instrumen hedging dengan ciri utamanya.",
        pairs: [
          { left: "Forward", right: "Kontrak bilateral dengan bank, mengunci kurs, fleksibel ukuran" },
          { left: "Futures", right: "Terstandar dan diperdagangkan di bursa" },
          { left: "Opsi", right: "Hak (bukan kewajiban), bayar premi, terlindungi sisi buruk" },
          { left: "Tujuan hedging", right: "Kepastian, bukan memaksimalkan laba" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Utang dolar tanpa hedging dan Krisis Asia 1998",
        html: "<strong>Krisis Asia 1997-1998</strong> menjadi pelajaran mahal tentang pentingnya lindung nilai. Banyak perusahaan Indonesia meminjam dalam <strong>dolar AS tanpa hedging</strong> karena bunganya lebih murah, sementara pendapatan mereka dalam rupiah. Ketika rupiah anjlok dari sekitar <strong>Rp2.400</strong> ke kisaran <strong>Rp16.000 per USD</strong>, nilai utang mereka membengkak berkali lipat dan banyak yang bangkrut, padahal risiko itu bisa diredam dengan hedging kurs.",
      },
      {
        type: "takeaways",
        items: [
          "Hedging mengurangi risiko kurs dan harga, bukan mencari untung.",
          "Forward dan futures mengunci harga (kewajiban); opsi memberi hak dengan premi.",
          "Posisi hedge bisa tampak rugi di atas kertas saat pasar menguntungkan, itu harga kepastian.",
          "Importir terlindungi dari pelemahan rupiah; eksportir dari penguatan rupiah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama hedging adalah?",
            options: ["Memaksimalkan laba", "Mengurangi risiko / kepastian", "Menghindari pajak", "Spekulasi agresif"],
            answer: 1,
            explain: "Hedging menukar ketidakpastian dengan kepastian, bukan mengejar laba maksimum.",
          },
          {
            q: "Perbedaan utama opsi dibanding forward adalah?",
            options: ["Opsi memberi hak, bukan kewajiban", "Opsi selalu lebih murah", "Forward diperdagangkan di bursa", "Opsi tanpa biaya"],
            answer: 0,
            explain: "Opsi adalah hak bukan kewajiban, ditebus dengan premi di muka.",
          },
          {
            q: "Futures berbeda dari forward karena futures?",
            options: ["Tidak punya jatuh tempo", "Terstandar dan diperdagangkan di bursa", "Selalu rugi", "Tanpa risiko"],
            answer: 1,
            explain: "Futures adalah kontrak terstandar yang diperdagangkan di bursa.",
          },
          {
            q: "Importir yang takut rupiah melemah sebaiknya?",
            options: ["Menjual forward rupiah", "Membeli forward valas (kunci kurs)", "Tidak melakukan apa-apa", "Menambah utang dolar"],
            answer: 1,
            explain: "Mengunci kurs beli valas lewat forward melindungi dari pelemahan rupiah.",
          },
          {
            q: "Forward USD 50.000 dikunci Rp16.000; spot jatuh tempo Rp16.600. Penghematan vs tanpa hedge?",
            options: ["Rp20 juta", "Rp30 juta", "Rp40 juta", "Rp60 juta"],
            answer: 1,
            explain: "Selisih kurs Rp600 x 50.000 = Rp30 juta dihemat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "efisiensi-pasar-dan-perilaku",
    levelId: "derivatif",
    order: 4,
    title: "Efisiensi Pasar & Perilaku Investor",
    summary: "Hipotesis pasar efisien (bentuk lemah, semi-kuat, kuat), random walk, bias perilaku, dan gelembung (bubble). Dengan video.",
    durationMin: 14,
    tags: ["efisiensi pasar", "random walk", "bias perilaku", "bubble"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Hipotesis Pasar Efisien (Efficient Market Hypothesis/EMH)</strong> menyatakan bahwa harga aset sudah mencerminkan semua informasi yang tersedia, sehingga sulit secara konsisten mengalahkan pasar. Gagasan ini dipopulerkan oleh Eugene Fama dan berkaitan erat dengan konsep <strong>random walk</strong>: pergerakan harga jangka pendek tak bisa diprediksi karena informasi baru datang secara acak.",
      },
      {
        type: "paragraph",
        html: "EMH punya tiga bentuk. <strong>Bentuk lemah</strong>: harga mencerminkan semua data harga masa lalu, sehingga analisis teknikal tak memberi keunggulan. <strong>Bentuk semi-kuat</strong>: harga mencerminkan semua informasi publik, sehingga analisis fundamental atas info publik pun tak unggul. <strong>Bentuk kuat</strong>: harga mencerminkan semua informasi termasuk yang privat (orang dalam), sehingga bahkan insider pun tak bisa unggul, bentuk ini paling sulit dipenuhi di dunia nyata.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga bentuk EMH",
        html: "<strong>Lemah</strong>: info = harga historis. <strong>Semi-kuat</strong>: info = semua data publik. <strong>Kuat</strong>: info = publik + privat. Semakin kuat bentuknya, semakin sulit siapa pun mengalahkan pasar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Keuangan perilaku menantang EMH",
        html: "EMH mengasumsikan investor rasional, tetapi keuangan perilaku (behavioral finance) menunjukkan manusia kerap irasional: <strong>herding</strong> (ikut-ikutan kerumunan), <strong>overconfidence</strong> (terlalu percaya diri sehingga overtrading), serta <strong>loss aversion</strong> dan <strong>anchoring</strong>.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Gelembung (bubble)",
        html: "Ketika harga melambung jauh di atas nilai wajar karena euforia dan herding, terbentuklah <strong>bubble</strong> yang akhirnya pecah dan jatuh tajam. Contoh historis: Tulip Mania (1637) dan Dot-com (2000). Bubble adalah bukti bahwa pasar tidak selalu seefisien yang diasumsikan.",
      },
      {
        type: "video",
        comp: "EfisiensiPasar",
        title: "Video: Tiga Bentuk Efisiensi Pasar",
        caption: "Visualisasi bagaimana informasi terserap ke harga pada bentuk lemah, semi-kuat, dan kuat.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Anatomi sebuah gelembung harga aset",
        unit: "Indeks harga (ilustrasi)",
        source: "Ilustrasi edukatif",
        note: "Euforia mendorong harga jauh di atas nilai wajar sebelum pecah.",
        data: [
          { label: "Awal", value: 100, color: "#2563eb" },
          { label: "Minat naik", value: 140, color: "#2563eb" },
          { label: "Euforia", value: 240, color: "#f59e0b" },
          { label: "Puncak", value: 300, color: "#dc2626" },
          { label: "Panik", value: 170, color: "#dc2626" },
          { label: "Kembali wajar", value: 110, color: "#16a34a" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Herding dan gelembung",
        html: "Sebuah saham bernilai wajar Rp1.000 mulai diperbincangkan di media sosial. Karena <strong>herding</strong>, banyak orang membeli hanya karena orang lain membeli, mendorong harga ke Rp3.000 dalam dua bulan, tiga kali nilai wajarnya. Saat sentimen berbalik, harga anjlok kembali ke Rp1.100. Investor yang masuk di puncak Rp3.000 mengalami kerugian sekitar 63 persen, sementara nilai fundamental perusahaan nyaris tak berubah.",
      },
      {
        type: "calcExercise",
        prompt: "Saham nilai wajar Rp1.000 melonjak ke puncak Rp3.000 lalu jatuh ke Rp1.100. Berapa persen kerugian investor yang beli di puncak (persen)?",
        answer: 63,
        tolerance: 1,
        suffix: "%",
        solution: "Kerugian = (3.000 - 1.100) / 3.000 = 1.900 / 3.000 = 0,633 = <strong>sekitar 63%</strong>.",
        hint: "Kerugian persen = (harga beli - harga akhir) / harga beli x 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Klasifikasikan tiap kasus ke bentuk EMH yang terlanggar atau bias perilakunya.",
        buckets: ["Bentuk EMH", "Bias perilaku"],
        items: [
          { text: "Harga sudah cerminkan semua data harga masa lalu (bentuk lemah)", bucket: "Bentuk EMH" },
          { text: "Ikut beli hanya karena kerumunan membeli (herding)", bucket: "Bias perilaku" },
          { text: "Harga cerminkan semua info publik (bentuk semi-kuat)", bucket: "Bentuk EMH" },
          { text: "Overtrading karena terlalu percaya diri (overconfidence)", bucket: "Bias perilaku" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Fenomena GameStop 2021 dan herding",
        html: "Fenomena <strong>GameStop pada Januari 2021</strong> menantang gagasan pasar yang selalu efisien dan rasional. Investor ritel yang berkoordinasi lewat forum <strong>Reddit</strong> beramai-ramai membeli saham GameStop, mendorong harganya melonjak dari sekitar <strong>USD 17</strong> menjadi puncak intraday sekitar <strong>USD 483</strong> dalam hitungan minggu. Lonjakan ini didorong <strong>herding</strong> dan short squeeze, bukan perubahan nilai fundamental perusahaan.",
      },
      {
        type: "takeaways",
        items: [
          "EMH: harga mencerminkan informasi, sulit konsisten mengalahkan pasar.",
          "Tiga bentuk: lemah (harga historis), semi-kuat (info publik), kuat (publik + privat).",
          "Random walk: pergerakan harga jangka pendek tak bisa diprediksi.",
          "Bias perilaku (herding, overconfidence) memicu gelembung yang akhirnya pecah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti hipotesis pasar efisien adalah?",
            options: ["Harga selalu salah", "Harga mencerminkan informasi yang tersedia", "Pasar selalu naik", "Hanya insider yang untung"],
            answer: 1,
            explain: "EMH menyatakan harga sudah mencerminkan informasi yang tersedia.",
          },
          {
            q: "Bentuk EMH yang menyatakan harga mencerminkan semua informasi publik adalah?",
            options: ["Bentuk lemah", "Bentuk semi-kuat", "Bentuk kuat", "Bentuk acak"],
            answer: 1,
            explain: "Semi-kuat mencakup semua informasi publik, bukan hanya harga historis.",
          },
          {
            q: "Random walk berarti?",
            options: ["Harga mudah diprediksi", "Pergerakan harga jangka pendek tak bisa diprediksi", "Pasar selalu turun", "Tidak ada risiko"],
            answer: 1,
            explain: "Informasi baru datang acak, sehingga harga bergerak seperti jalan acak.",
          },
          {
            q: "Membeli aset hanya karena banyak orang lain membeli disebut?",
            options: ["Hedging", "Herding", "Arbitrase", "Diversifikasi"],
            answer: 1,
            explain: "Herding adalah perilaku ikut-ikutan kerumunan tanpa analisis sendiri.",
          },
          {
            q: "Gelembung (bubble) terjadi ketika?",
            options: ["Harga jauh di bawah nilai wajar", "Harga melambung jauh di atas nilai wajar lalu pecah", "Pasar berhenti berdagang", "Inflasi nol"],
            answer: 1,
            explain: "Bubble adalah harga yang melonjak jauh di atas nilai wajar lalu jatuh tajam.",
          },
        ],
      },
    ],
  },
];
