import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "materialisme-historis",
    levelId: "historis",
    order: 1,
    title: "Materialisme Historis & Dialektika",
    summary: "Bagaimana Marx menjelaskan gerak sejarah lewat cara produksi, hubungan basis dan suprastruktur, serta dialektika yang ia warisi dari Hegel.",
    durationMin: 14,
    tags: ["materialisme historis", "dialektika", "basis suprastruktur"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Materialisme historis</strong> adalah inti cara Marx membaca sejarah: yang menggerakkan perubahan masyarakat bukan ide-ide besar, melainkan <strong>cara manusia memproduksi</strong> kebutuhan materialnya. Ekonomi adalah fondasi; politik, hukum, dan budaya tumbuh di atasnya.",
      },
      {
        type: "video",
        comp: "MaterialismeHistorisVideo",
        title: "Video: Basis & Suprastruktur",
        caption: "Cara produksi ekonomi menopang hukum, politik, dan ideologi masyarakat.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Georg_Wilhelm_Friedrich_Hegel00.jpg?width=400",
        alt: "Potret G.W.F. Hegel",
        caption: "G.W.F. Hegel (1770-1831), filsuf yang dialektikanya diadaptasi Marx menjadi materialis.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Basis dan suprastruktur",
        html: "<strong>Basis</strong> adalah cara produksi ekonomi (tenaga produktif dan hubungan produksi). <strong>Suprastruktur</strong> adalah hukum, negara, agama, dan budaya yang tumbuh dari basis itu dan cenderung membenarkannya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dialektika: dari Hegel ke Marx",
        html: "Hegel melihat sejarah bergerak lewat <strong>dialektika</strong> ide (tesis, antitesis, sintesis). Marx membalikkannya menjadi <strong>materialis</strong>: yang berdialektika adalah kondisi material dan kontradiksi kelas, bukan ide.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri tiap mode produksi untuk melihat siapa kelas dominan, siapa yang tertindas, dan kontradiksi yang mendorong perubahan.",
      },
      { type: "widget", widget: "SimulatorModaProduksi" },
      {
        type: "case",
        title: "Studi Kasus: Dari feodalisme ke kapitalisme",
        html: "Di Eropa, ketika perdagangan dan manufaktur tumbuh, kelas pedagang dan pemilik modal (<strong>borjuasi</strong>) makin kuat, sementara hubungan produksi feodal (tuan tanah dan hamba) makin menghambat. Kontradiksi ini, kata Marx, akhirnya meruntuhkan feodalisme dan melahirkan kapitalisme. Perubahan basis ekonomi diikuti perubahan suprastruktur: hukum, negara, dan nilai-nilai ikut berubah.",
      },
      {
        type: "classifyExercise",
        prompt: "Unsur ini termasuk basis ekonomi atau suprastruktur?",
        buckets: ["Basis ekonomi", "Suprastruktur"],
        items: [
          { text: "Pabrik dan mesin produksi", bucket: "Basis ekonomi" },
          { text: "Hubungan antara pemilik modal dan buruh", bucket: "Basis ekonomi" },
          { text: "Undang-undang dan pengadilan", bucket: "Suprastruktur" },
          { text: "Agama, seni, dan ideologi", bucket: "Suprastruktur" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan mode produksi dengan kontradiksi kelas utamanya.",
        pairs: [
          { left: "Perbudakan", right: "Budak vs pemilik budak" },
          { left: "Feodalisme", right: "Hamba/petani vs tuan tanah" },
          { left: "Kapitalisme", right: "Buruh vs pemilik modal" },
          { left: "Komunal primitif", right: "Belum ada kelas" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Dialektika Hegel dan Pembalikan Marx",
        html: "<strong>G.W.F. Hegel</strong> (1770-1831) berpendapat sejarah adalah gerak <strong>Roh</strong> atau ide yang berkembang lewat dialektika. Marx, yang muda terpengaruh kelompok Hegelian, kemudian <strong>membalikkannya</strong>: bukan ide yang menentukan kehidupan material, melainkan kehidupan material yang menentukan kesadaran. Pembalikan ini, kadang disebut menempatkan dialektika Hegel kembali pada kakinya, menjadi dasar materialisme historis.",
      },
      {
        type: "takeaways",
        items: [
          "Materialisme historis: cara produksi ekonomi menggerakkan sejarah.",
          "Basis ekonomi menopang suprastruktur (hukum, politik, budaya).",
          "Marx mengubah dialektika ide Hegel menjadi dialektika material.",
          "Sejarah dilihat sebagai pergantian mode produksi lewat kontradiksi kelas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Materialisme historis menyatakan sejarah digerakkan oleh?",
            options: ["Ide besar tokoh", "Cara manusia memproduksi kebutuhan materialnya", "Cuaca", "Kebetulan"],
            answer: 1,
            explain: "Bagi Marx, basis ekonomi (cara produksi) menggerakkan perubahan sejarah.",
          },
          {
            q: "Hukum, agama, dan budaya termasuk dalam?",
            options: ["Basis ekonomi", "Suprastruktur", "Tenaga produktif", "Modal"],
            answer: 1,
            explain: "Mereka adalah suprastruktur yang tumbuh dari basis ekonomi.",
          },
          {
            q: "Apa yang Marx ubah dari dialektika Hegel?",
            options: [
              "Menghapusnya",
              "Membalikkannya menjadi materialis, bukan idealis",
              "Menambah tahap keempat",
              "Tidak ada hubungannya",
            ],
            answer: 1,
            explain: "Marx menjadikan dialektika berpijak pada kondisi material, bukan ide.",
          },
          {
            q: "Kontradiksi utama dalam kapitalisme menurut Marx adalah?",
            options: ["Raja vs rakyat", "Buruh vs pemilik modal", "Kota vs desa", "Tua vs muda"],
            answer: 1,
            explain: "Kapitalisme dicirikan pertentangan proletariat dan borjuasi.",
          },
          {
            q: "Apa yang mendorong peralihan antar mode produksi?",
            options: ["Bencana alam", "Kontradiksi internal antarkelas", "Perubahan iklim", "Mode busana"],
            answer: 1,
            explain: "Kontradiksi di dalam tiap mode mendorong peralihan ke mode berikutnya.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "dialektika-tesis-antitesis",
    levelId: "historis",
    order: 2,
    title: "Dialektika: Tesis, Antitesis, Sintesis",
    summary: "Dialektika sebagai cara berpikir tentang perubahan lewat kontradiksi, dan bagaimana Marx mengubahnya menjadi dialektika materialis yang menyoroti konflik kelas.",
    durationMin: 14,
    tags: ["dialektika", "Hegel", "kontradiksi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Dialektika</strong> adalah cara berpikir yang melihat kenyataan selalu bergerak dan berubah karena ada <strong>kontradiksi</strong> di dalamnya. Sesuatu (tesis) memunculkan lawannya (antitesis), dan ketegangan keduanya melahirkan keadaan baru (sintesis) yang membawa unsur dari keduanya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Catatan jujur soal istilah",
        html: "Skema <strong>tesis-antitesis-sintesis</strong> sering dilekatkan pada Hegel, tetapi Hegel sendiri jarang memakai ketiga istilah itu secara persis. Rumusan ini lebih banyak dipopulerkan penafsir kemudian. Ia tetap berguna sebagai alat bantu memahami gerak lewat kontradiksi.",
      },
      {
        type: "video",
        comp: "MaterialismeHistorisVideo",
        title: "Video: Gerak Sejarah lewat Kontradiksi",
        caption: "Tesis bertemu antitesis, lalu lahir sintesis yang menjadi tesis baru.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Georg_Wilhelm_Friedrich_Hegel00.jpg?width=400",
        alt: "Potret Hegel",
        caption: "G.W.F. Hegel (1770-1831), sumber dialektika yang diadaptasi Marx.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dialektika idealis vs materialis",
        html: "Bagi Hegel, yang berdialektika adalah <strong>ide</strong> atau Roh. Marx membaliknya: yang berdialektika adalah <strong>kondisi material</strong> dan kontradiksi antarkelas. Perubahan masyarakat lahir dari benturan kepentingan ekonomi yang nyata, bukan dari pergulatan gagasan semata.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri tiap mode produksi dan perhatikan kontradiksi kelas yang ada di dalamnya. Itulah antitesis yang mendorong lahirnya tatanan baru.",
      },
      { type: "widget", widget: "SimulatorModaProduksi" },
      {
        type: "case",
        title: "Studi Kasus: Buruh dan modal sebagai kontradiksi",
        html: "Dalam pabrik, <strong>pemilik modal</strong> (tesis) butuh menekan upah agar laba naik, sementara <strong>buruh</strong> (antitesis) menuntut upah lebih layak. Benturan ini, kata Marx, tidak bisa hilang dengan kompromi kecil; ia adalah kontradiksi yang melekat pada hubungan produksi kapitalis. Bagi Marx, penyelesaiannya (sintesis) menuntut perubahan pada hubungan produksi itu sendiri.",
      },
      {
        type: "case",
        title: "Sejarah: Hegelian Muda, 1830-an hingga 1840-an",
        html: "Setelah Hegel wafat (1831), pengikutnya terbelah. Kelompok <strong>Hegelian Muda</strong> (antara lain Bruno Bauer dan Ludwig Feuerbach) memakai dialektika untuk mengkritik agama dan negara. Marx muda, sekitar 1837-1843, bergerak di lingkaran ini, lalu menjauh dan mengkritik mereka karena dianggap berhenti pada gagasan. Dari sinilah Marx merumuskan dialektika <strong>materialis</strong>.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini lebih cocok untuk dialektika idealis (Hegel) atau materialis (Marx)?",
        buckets: ["Idealis (Hegel)", "Materialis (Marx)"],
        items: [
          { text: "Yang menggerakkan sejarah adalah perkembangan Roh atau ide", bucket: "Idealis (Hegel)" },
          { text: "Yang menggerakkan sejarah adalah kontradiksi kondisi material", bucket: "Materialis (Marx)" },
          { text: "Konflik kelas ekonomi mendorong perubahan", bucket: "Materialis (Marx)" },
          { text: "Kesadaran menentukan kehidupan", bucket: "Idealis (Hegel)" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dialektika dengan maknanya.",
        pairs: [
          { left: "Tesis", right: "Keadaan atau gagasan awal" },
          { left: "Antitesis", right: "Lawan atau pertentangan yang muncul" },
          { left: "Sintesis", right: "Keadaan baru hasil benturan keduanya" },
          { left: "Kontradiksi", right: "Ketegangan internal pendorong perubahan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Dialektika melihat kenyataan bergerak karena kontradiksi di dalamnya.",
          "Skema tesis-antitesis-sintesis populer, tetapi jarang dipakai Hegel persis demikian.",
          "Marx mengubah dialektika idealis Hegel menjadi materialis.",
          "Bagi Marx, mesin perubahan adalah konflik kelas dan kondisi material.",
          "Sintesis bukan jalan tengah datar, melainkan tatanan baru yang melampaui keduanya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam skema dialektika, apa yang dimaksud antitesis?",
            options: ["Keadaan awal", "Lawan atau pertentangan yang muncul", "Hasil akhir", "Kesimpulan netral"],
            answer: 1,
            explain: "Antitesis adalah pertentangan yang muncul terhadap tesis.",
          },
          {
            q: "Mengapa skema tesis-antitesis-sintesis perlu disikapi hati-hati?",
            options: [
              "Karena salah total",
              "Karena Hegel sendiri jarang memakai ketiga istilah itu persis",
              "Karena Marx menolaknya",
              "Karena tidak ada hubungannya dengan dialektika",
            ],
            answer: 1,
            explain: "Rumusan itu lebih banyak dipopulerkan penafsir kemudian, bukan Hegel sendiri.",
          },
          {
            q: "Apa inti pembalikan Marx atas dialektika Hegel?",
            options: [
              "Mengganti ide dengan kondisi material sebagai penggerak",
              "Menambah tahap keempat",
              "Menghapus konsep kontradiksi",
              "Menjadikannya soal seni",
            ],
            answer: 0,
            explain: "Marx menjadikan kondisi material dan konflik kelas sebagai motor dialektika.",
          },
          {
            q: "Kelompok pemikir tempat Marx muda bergerak disebut?",
            options: ["Kaum Romantik", "Hegelian Muda", "Kaum Positivis", "Kaum Skolastik"],
            answer: 1,
            explain: "Marx muda aktif di lingkaran Hegelian Muda sebelum mengkritik mereka.",
          },
          {
            q: "Apa makna sintesis dalam dialektika?",
            options: [
              "Kembali ke keadaan semula",
              "Keadaan baru yang menyerap dan melampaui tesis dan antitesis",
              "Penghapusan total kedua sisi",
              "Jeda tanpa perubahan",
            ],
            answer: 1,
            explain: "Sintesis adalah tatanan baru yang membawa unsur keduanya namun melampauinya.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "tenaga-dan-hubungan-produksi",
    levelId: "historis",
    order: 3,
    title: "Tenaga Produktif & Hubungan Produksi",
    summary: "Cara produksi terdiri dari tenaga produktif dan hubungan produksi. Ketika teknologi berkembang melampaui hubungan kelas yang ada, muncul ketegangan yang mendorong perubahan sosial.",
    durationMin: 14,
    tags: ["tenaga produktif", "hubungan produksi", "revolusi sosial"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi Marx, <strong>cara produksi</strong> punya dua sisi. <strong>Tenaga produktif</strong> mencakup alat, mesin, teknologi, dan keterampilan manusia. <strong>Hubungan produksi</strong> adalah relasi sosial soal siapa memiliki alat produksi dan bagaimana hasil kerja dibagi. Keduanya saling terkait, tetapi bisa juga bertabrakan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Inti tesisnya",
        html: "Ketika <strong>tenaga produktif berkembang</strong> melampaui <strong>hubungan produksi</strong> yang lama, hubungan itu berubah dari pendorong menjadi penghambat. Ketegangan inilah, kata Marx, yang membuka masa <strong>revolusi sosial</strong>.",
      },
      {
        type: "video",
        comp: "MaterialismeHistorisVideo",
        title: "Video: Dua Sisi Cara Produksi",
        caption: "Tenaga produktif (alat dan keterampilan) bertemu hubungan produksi (relasi kepemilikan).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Contoh sederhana",
        html: "Mesin uap dan pabrik (tenaga produktif baru) sulit berjalan dalam hubungan feodal yang mengikat petani ke tanah. Dibutuhkan buruh bebas yang bisa berpindah ke kota dan dipekerjakan dengan upah. Maka hubungan produksi pun bergeser.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan tiap mode produksi: perhatikan bagaimana tingkat teknologi (tenaga produktif) berpasangan dengan pola kepemilikan (hubungan produksi).",
      },
      { type: "widget", widget: "SimulatorModaProduksi" },
      {
        type: "chart",
        variant: "line",
        title: "Lonjakan Produktivitas pada Revolusi Industri (ilustrasi tren)",
        unit: "indeks output per pekerja",
        source: "ilustrasi edukatif berbasis tren historis pertumbuhan produktivitas",
        note: "Tenaga produktif melonjak tajam sejak akhir abad ke-18, jauh melampaui hubungan produksi feodal yang lama.",
        data: [
          { label: "1700", value: 100, color: "#94a3b8" },
          { label: "1760", value: 115, color: "#94a3b8" },
          { label: "1820", value: 160, color: "#fbbf24" },
          { label: "1870", value: 260, color: "#f59e0b" },
          { label: "1900", value: 360, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tenaga produktif menekan hubungan lama",
        html: "Bayangkan sebuah desa yang semula bertani dengan cangkul (tenaga produktif rendah) dan tanah dikuasai tuan tanah (hubungan feodal). Ketika traktor dan pabrik pengolahan masuk, produktivitas melonjak, tetapi pola bagi hasil lama tidak lagi cocok. Pemilik modal butuh pekerja upahan, bukan hamba terikat tanah. Hubungan produksi terpaksa berubah mengikuti tenaga produktif yang baru.",
      },
      {
        type: "case",
        title: "Sejarah: Revolusi Industri, sekitar 1760-1840",
        html: "Di Inggris, sejak sekitar <strong>1760</strong> hingga <strong>1840</strong>, mesin uap (dipatenkan James Watt, 1769), mesin tenun, dan pabrik melipatgandakan tenaga produktif. Hubungan produksi feodal yang mengikat petani ke tanah runtuh, digantikan hubungan <strong>kapitalis</strong>: pemilik pabrik dan buruh upahan. Bagi Marx, ini contoh nyata tenaga produktif baru memaksa lahirnya hubungan produksi baru.",
      },
      {
        type: "calcExercise",
        prompt: "Output per pekerja naik dari indeks 100 (tahun 1700) menjadi 360 (tahun 1900). Berapa persen kenaikannya?",
        answer: 260,
        tolerance: 1,
        suffix: "%",
        solution: "Kenaikan = (360 - 100) / 100 x 100% = 260%.",
        hint: "Selisih dibagi nilai awal, lalu dikalikan 100 persen.",
      },
      {
        type: "classifyExercise",
        prompt: "Unsur ini termasuk tenaga produktif atau hubungan produksi?",
        buckets: ["Tenaga produktif", "Hubungan produksi"],
        items: [
          { text: "Mesin tenun dan traktor", bucket: "Tenaga produktif" },
          { text: "Keterampilan dan pengetahuan pekerja", bucket: "Tenaga produktif" },
          { text: "Siapa yang memiliki pabrik", bucket: "Hubungan produksi" },
          { text: "Pola bagi hasil antara pemilik dan buruh", bucket: "Hubungan produksi" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Cara produksi = tenaga produktif + hubungan produksi.",
          "Tenaga produktif: alat, mesin, teknologi, keterampilan.",
          "Hubungan produksi: relasi kepemilikan dan pembagian hasil.",
          "Tenaga produktif yang melampaui hubungan lama memicu revolusi sosial.",
          "Revolusi Industri adalah contoh tenaga produktif mengubah hubungan produksi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Yang termasuk tenaga produktif adalah?",
            options: ["Undang-undang kepemilikan", "Mesin, alat, dan keterampilan", "Pola bagi hasil", "Hak waris"],
            answer: 1,
            explain: "Tenaga produktif mencakup alat, mesin, teknologi, dan keterampilan manusia.",
          },
          {
            q: "Hubungan produksi terutama menyangkut?",
            options: ["Jenis mesin", "Siapa memiliki alat produksi dan bagaimana hasil dibagi", "Cuaca", "Tingkat pendidikan saja"],
            answer: 1,
            explain: "Hubungan produksi adalah relasi sosial kepemilikan dan pembagian hasil.",
          },
          {
            q: "Menurut Marx, apa yang terjadi bila tenaga produktif melampaui hubungan produksi lama?",
            options: [
              "Tidak ada perubahan",
              "Hubungan lama jadi penghambat dan membuka masa revolusi sosial",
              "Teknologi mundur",
              "Kelas hilang seketika",
            ],
            answer: 1,
            explain: "Ketegangan ini, kata Marx, memicu perubahan hubungan produksi.",
          },
          {
            q: "Revolusi Industri di Inggris berlangsung sekitar tahun?",
            options: ["1300-1400", "1760-1840", "1500-1550", "1900-1950"],
            answer: 1,
            explain: "Revolusi Industri umumnya ditarik sekitar 1760 hingga 1840.",
          },
          {
            q: "Apa dampak Revolusi Industri pada hubungan produksi feodal?",
            options: [
              "Memperkuatnya",
              "Menggantinya dengan hubungan kapitalis pemilik pabrik dan buruh upahan",
              "Tidak berpengaruh",
              "Menghapus semua kepemilikan",
            ],
            answer: 1,
            explain: "Hubungan feodal runtuh dan digantikan relasi kapitalis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "tahap-tahap-sejarah",
    levelId: "historis",
    order: 4,
    title: "Tahap-Tahap Perkembangan Masyarakat",
    summary: "Skema tahap sejarah Marx, dari komunal primitif hingga komunisme, beserta kelas dominan dan tertindas tiap tahap, serta kritik bahwa skema ini terlalu linear dan Eurosentris.",
    durationMin: 15,
    tags: ["tahap sejarah", "mode produksi", "kritik linearitas"],
    blocks: [
      {
        type: "paragraph",
        html: "Marx kerap menggambarkan sejarah sebagai pergantian <strong>mode produksi</strong>: komunal primitif, perbudakan, feodalisme, kapitalisme, lalu sosialisme dan komunisme. Tiap tahap punya <strong>kelas dominan</strong> yang menguasai alat produksi dan <strong>kelas tertindas</strong> yang kerjanya diambil sebagian.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati: skema yang disederhanakan",
        html: "Skema lima tahap ini banyak dikritik sebagai terlalu <strong>linear</strong> dan <strong>Eurosentris</strong>, seolah semua masyarakat harus melewati urutan yang sama. Banyak sejarawan menilai jalannya jauh lebih beragam. Pakailah skema ini sebagai peta kasar, bukan hukum pasti.",
      },
      {
        type: "video",
        comp: "AkumulasiKrisisVideo",
        title: "Video: Pergantian Mode Produksi",
        caption: "Tiap tahap sejarah membawa kelas dominan dan kontradiksinya sendiri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pola tiap tahap",
        html: "Di tiap tahap selalu ada pasangan <strong>penguasa alat produksi</strong> dan <strong>yang bekerja untuknya</strong>: tuan budak dan budak, tuan tanah dan hamba, pemilik modal dan buruh. Komunisme dibayangkan sebagai tahap tanpa kelas.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat tiap mode produksi dan kenali pasangan kelas dominan dan tertindasnya. Perhatikan bagaimana kontradiksi mendorong ke tahap berikut.",
      },
      { type: "widget", widget: "SimulatorModaProduksi" },
      {
        type: "case",
        title: "Studi Kasus: Kelas dominan berganti, polanya tetap",
        html: "Pada perbudakan, kerja diambil lewat <strong>paksaan langsung</strong>: budak adalah milik. Pada feodalisme, hamba menyerahkan sebagian panen atau kerja wajib kepada tuan tanah. Pada kapitalisme, buruh tampak bebas, tetapi menjual tenaganya dan menghasilkan <strong>nilai lebih</strong> bagi pemilik modal. Bentuk berubah, tetapi pola satu kelas hidup dari kerja kelas lain berulang.",
      },
      {
        type: "case",
        title: "Sejarah: Kritik linearitas dan cara produksi Asiatik",
        html: "Marx sendiri sadar skema Eropa tidak pas di mana-mana. Sekitar tahun <strong>1850-an</strong>, ia membahas yang ia sebut <strong>cara produksi Asiatik</strong>, yakni masyarakat dengan negara terpusat yang menguasai irigasi dan tanah, yang tidak mudah dimasukkan ke urutan perbudakan-feodalisme-kapitalisme. Konsep ini, meski kontroversial dan kemudian banyak diperdebatkan, menunjukkan jalan sejarah tidak selalu lurus.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tahap sejarah dengan pasangan kelas dominan dan tertindasnya.",
        pairs: [
          { left: "Komunal primitif", right: "Belum ada kelas" },
          { left: "Perbudakan", right: "Pemilik budak dan budak" },
          { left: "Feodalisme", right: "Tuan tanah dan hamba/petani" },
          { left: "Kapitalisme", right: "Pemilik modal dan buruh" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini menggambarkan ciri skema tahap atau justru kritik terhadapnya?",
        buckets: ["Ciri skema tahap", "Kritik terhadap skema"],
        items: [
          { text: "Tiap tahap punya kelas dominan dan tertindas", bucket: "Ciri skema tahap" },
          { text: "Komunisme dibayangkan sebagai tahap tanpa kelas", bucket: "Ciri skema tahap" },
          { text: "Urutannya terlalu linear dan Eurosentris", bucket: "Kritik terhadap skema" },
          { text: "Banyak masyarakat tidak mengikuti urutan yang sama", bucket: "Kritik terhadap skema" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Marx menyusun sejarah sebagai pergantian mode produksi.",
          "Tiap tahap punya kelas dominan dan kelas tertindas.",
          "Bentuk pengambilan kerja berubah, tetapi polanya berulang.",
          "Skema lima tahap dikritik terlalu linear dan Eurosentris.",
          "Marx sendiri mengakui pengecualian lewat konsep cara produksi Asiatik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Urutan tahap mode produksi menurut skema Marx adalah?",
            options: [
              "Kapitalisme, feodalisme, perbudakan, komunal",
              "Komunal, perbudakan, feodalisme, kapitalisme, komunisme",
              "Feodalisme, komunal, kapitalisme",
              "Perbudakan, kapitalisme, feodalisme",
            ],
            answer: 1,
            explain: "Skemanya: komunal primitif, perbudakan, feodalisme, kapitalisme, lalu sosialisme/komunisme.",
          },
          {
            q: "Kelas tertindas pada feodalisme adalah?",
            options: ["Buruh pabrik", "Hamba atau petani", "Budak", "Pemilik modal"],
            answer: 1,
            explain: "Pada feodalisme, hamba/petani menyerahkan kerja atau hasil kepada tuan tanah.",
          },
          {
            q: "Apa kritik utama terhadap skema lima tahap?",
            options: [
              "Terlalu rumit",
              "Terlalu linear dan Eurosentris",
              "Tidak menyebut kelas",
              "Mengabaikan ekonomi",
            ],
            answer: 1,
            explain: "Kritik umum: skema ini menyamaratakan jalan sejarah yang sebenarnya beragam.",
          },
          {
            q: "Konsep apa yang Marx bahas untuk masyarakat di luar pola Eropa?",
            options: ["Cara produksi Asiatik", "Cara produksi digital", "Cara produksi nomaden", "Cara produksi modern"],
            answer: 0,
            explain: "Cara produksi Asiatik dibahas Marx sebagai pengecualian atas urutan Eropa.",
          },
          {
            q: "Komunisme dalam skema ini dibayangkan sebagai tahap?",
            options: ["Dengan dua kelas baru", "Tanpa kelas", "Dengan kelas budak", "Kembali ke feodalisme"],
            answer: 1,
            explain: "Komunisme dibayangkan sebagai masyarakat tanpa kelas.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ideologi-dan-kesadaran",
    levelId: "historis",
    order: 5,
    title: "Ideologi & Kesadaran Palsu",
    summary: "Ideologi sebagai gagasan kelas dominan yang menyamar jadi akal sehat universal, dan konsep kesadaran palsu di mana yang tertindas menerima tatanan yang merugikannya.",
    durationMin: 14,
    tags: ["ideologi", "kesadaran palsu", "hegemoni"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi Marx dan Engels, <strong>ideologi</strong> bukan sekadar pandangan politik. Ia adalah seperangkat gagasan yang membuat tatanan yang menguntungkan kelas dominan tampak <strong>wajar, alami, dan untuk semua orang</strong>. Kalimat terkenalnya: gagasan kelas yang berkuasa adalah gagasan yang berkuasa di tiap zaman.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kesadaran palsu",
        html: "<strong>Kesadaran palsu</strong> (false consciousness) adalah keadaan ketika kelas tertindas justru menerima dan membela tatanan yang merugikannya, karena memandang dunia lewat kacamata ideologi kelas dominan. Mereka menganggap ketimpangan sebagai nasib atau hal yang wajar.",
      },
      {
        type: "video",
        comp: "SejarahKapitalismeVideo",
        title: "Video: Gagasan yang Berkuasa",
        caption: "Bagaimana nilai-nilai kelas dominan menyebar dan tampak seperti akal sehat bersama.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Contoh sehari-hari",
        html: "Gagasan seperti yang miskin pasti malas atau pasar selalu adil bisa menjadi ideologi bila membuat orang menerima ketimpangan tanpa bertanya. Marx mengajak menelusuri kepentingan kelas mana yang diuntungkan oleh gagasan yang dianggap akal sehat itu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur sebaran pendapatan dan lihat koefisien Gini bergerak. Ketimpangan yang sering dianggap wajar bisa diukur dan dipertanyakan.",
      },
      { type: "widget", widget: "KalkulatorGini" },
      {
        type: "chart",
        variant: "donut",
        title: "Penguasaan Saluran Penyebar Gagasan (ilustrasi konsep)",
        unit: "bagian pengaruh",
        source: "ilustrasi edukatif konsep ideologi",
        note: "Marx menyoroti bahwa kelas yang menguasai alat produksi juga cenderung menguasai alat penyebar gagasan.",
        data: [
          { label: "Dikuasai kelas dominan", value: 70, color: "#fb7185" },
          { label: "Suara alternatif", value: 30, color: "#60a5fa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Ketika ketimpangan dianggap takdir",
        html: "Bayangkan masyarakat dengan jurang kaya-miskin lebar, tetapi banyak orang percaya bahwa itu murni soal kerja keras pribadi, bukan soal kepemilikan alat produksi. Keyakinan ini meredam tuntutan perubahan. Bagi Marx, inilah kerja <strong>ideologi</strong>: ia menutupi akar struktural ketimpangan dan menjadikannya tampak adil. Kesadaran palsu membuat yang dirugikan ikut membela tatanan itu.",
      },
      {
        type: "case",
        title: "Sejarah: The German Ideology, sekitar 1845-1846",
        html: "Dalam naskah <strong>The German Ideology</strong> (Ideologi Jerman), yang ditulis Marx dan Engels sekitar <strong>1845-1846</strong>, mereka merumuskan bahwa gagasan kelas penguasa adalah gagasan yang berkuasa di tiap zaman. Naskah ini baru terbit lengkap jauh kemudian, tetapi menjadi salah satu sumber penting konsep ideologi dalam pemikiran Marx.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini contoh gagasan ideologis (menormalkan tatanan) atau pertanyaan kritis (membongkarnya)?",
        buckets: ["Gagasan ideologis", "Pertanyaan kritis"],
        items: [
          { text: "Yang miskin pasti kurang berusaha", bucket: "Gagasan ideologis" },
          { text: "Ketimpangan adalah hal yang sudah seharusnya", bucket: "Gagasan ideologis" },
          { text: "Siapa yang diuntungkan oleh aturan ini?", bucket: "Pertanyaan kritis" },
          { text: "Apakah akar ketimpangan ada pada kepemilikan alat produksi?", bucket: "Pertanyaan kritis" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jika kelas dominan menguasai 70% saluran penyebar gagasan, berapa persen sisanya untuk suara alternatif?",
        answer: 30,
        tolerance: 0,
        suffix: "%",
        solution: "Sisanya = 100% - 70% = 30%.",
        hint: "Total selalu 100 persen.",
      },
      {
        type: "takeaways",
        items: [
          "Ideologi membuat tatanan yang menguntungkan kelas dominan tampak wajar.",
          "Gagasan kelas berkuasa cenderung menjadi gagasan yang berkuasa.",
          "Kesadaran palsu: yang tertindas menerima tatanan yang merugikannya.",
          "Marx mengajak bertanya: kepentingan kelas mana yang diuntungkan gagasan ini?",
          "Konsep ideologi dirumuskan dalam The German Ideology (sekitar 1845-1846).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa makna ideologi menurut Marx dan Engels?",
            options: [
              "Sekadar pilihan partai",
              "Gagasan yang membuat tatanan menguntungkan kelas dominan tampak wajar",
              "Ilmu pengetahuan murni",
              "Selera pribadi",
            ],
            answer: 1,
            explain: "Ideologi menormalkan tatanan yang menguntungkan kelas penguasa.",
          },
          {
            q: "Kalimat terkenal Marx-Engels tentang gagasan berbunyi?",
            options: [
              "Gagasan tidak punya kelas",
              "Gagasan kelas yang berkuasa adalah gagasan yang berkuasa",
              "Gagasan lahir dari alam",
              "Gagasan hanya milik kaum terpelajar",
            ],
            answer: 1,
            explain: "Inilah rumusan inti soal dominasi gagasan kelas penguasa.",
          },
          {
            q: "Kesadaran palsu adalah keadaan ketika?",
            options: [
              "Kelas dominan menolak kekuasaannya",
              "Kelas tertindas menerima tatanan yang merugikannya",
              "Semua orang sadar penuh",
              "Tidak ada kelas",
            ],
            answer: 1,
            explain: "Kesadaran palsu membuat yang dirugikan ikut membela tatanan yang menindasnya.",
          },
          {
            q: "Naskah yang merumuskan konsep ini, The German Ideology, ditulis sekitar tahun?",
            options: ["1789-1790", "1845-1846", "1917-1918", "1867-1868"],
            answer: 1,
            explain: "The German Ideology ditulis Marx dan Engels sekitar 1845-1846.",
          },
          {
            q: "Pertanyaan kritis ala Marx terhadap sebuah gagasan akal sehat adalah?",
            options: [
              "Apakah gagasan ini populer?",
              "Kepentingan kelas mana yang diuntungkan gagasan ini?",
              "Siapa yang pertama mengucapkannya?",
              "Apakah terdengar indah?",
            ],
            answer: 1,
            explain: "Marx mengajak menelusuri kepentingan kelas di balik gagasan yang dianggap wajar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "revolusi-sosial",
    levelId: "historis",
    order: 6,
    title: "Revolusi Sosial: Bagaimana Sejarah Berganti Babak",
    summary: "Bagi Marx, peralihan antar mode produksi terjadi lewat revolusi sosial saat tenaga produktif berkembang melampaui hubungan produksi lama. Termasuk peran kesadaran kelas, beda revolusi dari kudeta, dan catatan kritis bahwa ramalan Marx tidak selalu terbukti.",
    durationMin: 15,
    tags: ["revolusi sosial", "kesadaran kelas", "kontradiksi"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi Marx, sejarah tidak berganti babak secara perlahan dan mulus saja. Pada titik tertentu, <strong>tenaga produktif</strong> (teknologi dan kemampuan produksi) berkembang melampaui <strong>hubungan produksi</strong> lama yang justru menghambatnya. Ketegangan itu memuncak, dan terbukalah masa <strong>revolusi sosial</strong>: kelas baru yang lebih sesuai dengan tenaga produktif baru naik dan mengganti tatanan lama.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumusan Marx (Kata Pengantar 1859)",
        html: "Dalam kata pengantar <em>A Contribution to the Critique of Political Economy</em> (1859), Marx menulis bahwa ketika tenaga produktif berbenturan dengan hubungan produksi yang ada, mulailah <strong>era revolusi sosial</strong>. Perubahan basis ekonomi cepat atau lambat mengubah seluruh suprastruktur.",
      },
      {
        type: "video",
        comp: "AkumulasiKrisisVideo",
        title: "Video: Kontradiksi yang Memuncak",
        caption: "Ketika hubungan produksi lama tak lagi menampung tenaga produktif baru, kontradiksi pecah jadi revolusi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Revolusi sosial bukan kudeta",
        html: "<strong>Kudeta</strong> hanya mengganti penguasa di puncak tanpa mengubah siapa yang menguasai alat produksi. <strong>Revolusi sosial</strong> mengubah hubungan produksi itu sendiri, yakni kelas mana yang berkuasa secara ekonomi. Bagi Marx, ganti presiden saja bukan revolusi; yang berubah harus struktur kepemilikan dan kelasnya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Telusuri tiap mode produksi dan bayangkan momen peralihannya: tenaga produktif apa yang baru, hubungan lama mana yang menghambat, dan kelas mana yang naik.",
      },
      { type: "widget", widget: "SimulatorModaProduksi" },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan kritis: ramalan yang meleset",
        html: "Marx menduga revolusi proletariat akan meletus lebih dulu di negara <strong>industri maju</strong> seperti Inggris atau Jerman. Kenyataannya, revolusi besar justru pecah di <strong>Rusia (1917)</strong> yang sebagian besar masih agraris, bukan di pusat kapitalisme matang. Banyak penafsir menilai ini menunjukkan ramalan Marx tidak otomatis terbukti.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tingkat Industrialisasi saat Revolusi: dugaan Marx vs kenyataan (ilustrasi konsep)",
        unit: "indeks industrialisasi relatif",
        source: "ilustrasi edukatif perbandingan, bukan data statistik resmi",
        note: "Marx menduga revolusi muncul di negara paling industri, tetapi 1917 justru meletus di Rusia yang industrinya jauh lebih rendah dari Inggris atau Jerman.",
        data: [
          { label: "Inggris ~1900", value: 90, color: "#94a3b8" },
          { label: "Jerman ~1900", value: 75, color: "#94a3b8" },
          { label: "Rusia ~1917", value: 25, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Peran kesadaran kelas",
        html: "Bagi Marx, kontradiksi ekonomi saja belum cukup. Buruh perlu beralih dari <strong>kelas pada dirinya</strong> (sekadar punya posisi sama secara ekonomi) menjadi <strong>kelas bagi dirinya</strong> (sadar akan kepentingan bersama dan mau bertindak). Tanpa <strong>kesadaran kelas</strong> dan momen yang tepat, ketegangan bisa mereda tanpa revolusi. Inilah sebabnya Marx menekankan organisasi dan kesadaran, bukan hanya tunggu otomatis.",
      },
      {
        type: "case",
        title: "Sejarah: Revolusi Prancis 1789",
        html: "<strong>Revolusi Prancis</strong> yang meletus pada <strong>1789</strong> sering dipakai Marxis sebagai contoh revolusi borjuis: kelas <strong>borjuasi</strong> (pedagang, pemilik modal, profesional) yang ekonominya menguat menggulingkan tatanan <strong>feodal</strong> dengan raja absolut dan bangsawan istimewa. Hak istimewa feodal dihapus, dan tatanan hukum serta politik baru yang lebih cocok dengan kapitalisme lahir. Bagi Marx, ini contoh perubahan basis ekonomi yang menyeret perubahan suprastruktur.",
      },
      {
        type: "classifyExercise",
        prompt: "Peristiwa ini lebih tepat disebut revolusi sosial atau sekadar kudeta?",
        buckets: ["Revolusi sosial", "Sekadar kudeta"],
        items: [
          { text: "Kelas borjuasi menggulingkan tatanan feodal dan mengubah kepemilikan", bucket: "Revolusi sosial" },
          { text: "Hubungan produksi berubah menyeluruh, kelas baru berkuasa", bucket: "Revolusi sosial" },
          { text: "Seorang jenderal merebut kursi presiden, struktur kepemilikan tetap", bucket: "Sekadar kudeta" },
          { text: "Penguasa di puncak berganti tanpa mengubah siapa pemilik alat produksi", bucket: "Sekadar kudeta" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Revolusi sosial", right: "Perubahan hubungan produksi dan kelas yang berkuasa" },
          { left: "Kudeta", right: "Pergantian penguasa tanpa ubah struktur ekonomi" },
          { left: "Kelas bagi dirinya", right: "Kelas yang sudah sadar kepentingan bersamanya" },
          { left: "Era revolusi", right: "Saat tenaga produktif berbenturan dengan hubungan lama" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Revolusi sosial terjadi saat tenaga produktif melampaui hubungan produksi lama.",
          "Marx merumuskannya di kata pengantar 1859: kontradiksi memuncak jadi era revolusi.",
          "Revolusi sosial mengubah kelas yang berkuasa, beda dari kudeta yang hanya ganti penguasa.",
          "Kesadaran kelas mengubah buruh dari kelas pada dirinya jadi kelas bagi dirinya.",
          "Kritik: ramalan revolusi di negara industri maju meleset; 1917 justru di Rusia yang agraris.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Marx, kapan terbuka era revolusi sosial?",
            options: [
              "Saat cuaca memburuk",
              "Saat tenaga produktif berkembang melampaui hubungan produksi lama",
              "Saat penguasa berganti",
              "Saat harga naik sedikit",
            ],
            answer: 1,
            explain: "Kontradiksi antara tenaga produktif baru dan hubungan produksi lama membuka era revolusi.",
          },
          {
            q: "Apa beda revolusi sosial dari kudeta?",
            options: [
              "Tidak ada bedanya",
              "Revolusi mengubah hubungan produksi dan kelas berkuasa, kudeta hanya ganti penguasa",
              "Kudeta lebih besar",
              "Revolusi selalu damai",
            ],
            answer: 1,
            explain: "Revolusi sosial mengubah struktur kepemilikan dan kelas, bukan sekadar puncak kekuasaan.",
          },
          {
            q: "Peralihan dari kelas pada dirinya menjadi kelas bagi dirinya menandai?",
            options: [
              "Tumbuhnya kesadaran kelas",
              "Hilangnya semua kelas",
              "Kembalinya feodalisme",
              "Naiknya borjuasi",
            ],
            answer: 0,
            explain: "Itu berarti kelas mulai sadar akan kepentingan bersamanya dan siap bertindak.",
          },
          {
            q: "Revolusi Prancis 1789 dipakai sebagai contoh?",
            options: [
              "Revolusi proletariat",
              "Borjuasi menggulingkan tatanan feodal",
              "Kudeta militer",
              "Restorasi monarki",
            ],
            answer: 1,
            explain: "Borjuasi yang menguat ekonominya menggulingkan tatanan feodal dan raja absolut.",
          },
          {
            q: "Apa catatan kritis terhadap ramalan revolusi Marx?",
            options: [
              "Terbukti tepat di Inggris lebih dulu",
              "Revolusi besar justru meletus di Rusia agraris (1917), bukan di negara industri maju",
              "Tidak ada revolusi sama sekali",
              "Revolusi hanya terjadi di Prancis",
            ],
            answer: 1,
            explain: "Marx menduga negara industri maju lebih dulu, tetapi 1917 pecah di Rusia yang agraris.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "negara-dan-kelas",
    levelId: "historis",
    order: 7,
    title: "Negara, Kelas & Memudarnya Negara",
    summary: "Teori negara Marxis: negara dipandang sebagai alat kelas dominan, lahir bersama kelas dan kepemilikan pribadi (Engels). Visi memudarnya negara setelah masyarakat tanpa kelas, dan kritik tajam bahwa dalam praktik negara komunis justru membesar.",
    durationMin: 15,
    tags: ["negara", "kelas", "memudarnya negara"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam pemikiran Marxis, <strong>negara</strong> bukan wasit netral yang berdiri di atas semua golongan. Ia dipandang sebagai <strong>alat kelas dominan</strong> untuk mempertahankan kekuasaannya, lewat hukum, polisi, tentara, dan pengadilan. Engels menambahkan bahwa negara bukan hal abadi: ia <strong>muncul bersama</strong> lahirnya kelas dan kepemilikan pribadi.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Friedrich_Engels.jpg?width=400",
        alt: "Potret Friedrich Engels",
        caption: "Friedrich Engels, penulis Asal-usul Keluarga, Kepemilikan Pribadi, dan Negara (1884).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Negara sebagai alat kelas",
        html: "Dalam <strong>Manifesto Komunis</strong> (1848), Marx dan Engels menulis bahwa pemerintahan modern hanyalah <strong>komite yang mengurus urusan bersama seluruh kaum borjuis</strong>. Negara dipandang melayani kepentingan kelas yang menguasai alat produksi, bukan kepentingan semua orang secara setara.",
      },
      {
        type: "video",
        comp: "NegaraKelasVideo",
        title: "Video: Negara dan Kelas",
        caption: "Bagaimana negara dilihat sebagai alat kelas dominan, lalu dibayangkan memudar di masyarakat tanpa kelas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Memudarnya negara (withering away)",
        html: "Marx dan Engels membayangkan bahwa setelah revolusi dan terbentuk masyarakat <strong>tanpa kelas</strong>, fungsi negara sebagai alat penindas satu kelas atas kelas lain kehilangan alasannya. Negara dalam arti itu akan <strong>memudar</strong> dengan sendirinya, bukan dihapus dalam semalam, dan yang tersisa hanyalah pengurusan urusan bersama.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser spektrum dari pasar bebas penuh ke kendali negara penuh. Perhatikan bahwa baik pasar tanpa batas maupun negara yang sangat besar punya konsekuensinya sendiri.",
      },
      { type: "widget", widget: "SimulatorSpektrumEkonomi" },
      {
        type: "callout",
        tone: "warn",
        title: "Kritik tajam: praktik berkata lain",
        html: "Dalam praktik negara-negara yang mengaku komunis pada abad ke-20 (mis. Uni Soviet di bawah Stalin), negara justru <strong>membesar dan makin represif</strong>: birokrasi raksasa, polisi rahasia, dan kontrol ketat, bukan memudar. Banyak pengamat menilai ini ironi besar antara visi memudarnya negara dan kenyataan negara yang menggurita.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Visi vs Praktik: ukuran aparatus negara setelah revolusi (ilustrasi konsep)",
        unit: "ukuran aparatus negara (relatif)",
        source: "ilustrasi edukatif perbandingan, bukan data statistik resmi",
        note: "Teori membayangkan negara memudar setelah masyarakat tanpa kelas; praktik abad ke-20 menunjukkan aparatus negara justru membesar.",
        data: [
          { label: "Sebelum revolusi", value: 50, color: "#94a3b8" },
          { label: "Segera sesudah", value: 60, color: "#94a3b8" },
          { label: "Visi (memudar)", value: 15, color: "#34d399" },
          { label: "Praktik (membesar)", value: 95, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Negara sebagai komite borjuasi",
        html: "Bayangkan aturan yang melindungi hak milik pabrik secara ketat, sementara hak buruh untuk berorganisasi dibatasi. Bagi Marxis, ini contoh negara bertindak sebagai <strong>alat kelas pemilik modal</strong>: hukum, polisi, dan pengadilan menjaga tatanan yang menguntungkan borjuasi dan tampil seolah netral. Itulah maksud rumusan negara sebagai komite yang mengurus urusan bersama kaum borjuis.",
      },
      {
        type: "case",
        title: "Sejarah: Engels dan Asal-usul Negara, 1884",
        html: "Pada tahun <strong>1884</strong>, Engels menerbitkan <strong>Asal-usul Keluarga, Kepemilikan Pribadi, dan Negara</strong>. Dengan memakai riset antropolog Lewis Morgan, Engels berargumen bahwa pada masyarakat tanpa kelas yang sangat awal, negara belum ada; negara baru <strong>muncul</strong> ketika kepemilikan pribadi dan pembagian kelas lahir, sebagai alat menjaga ketimpangan itu. Maka, simpulnya, bila kelas hilang, negara dalam arti penindas pun bisa hilang.",
      },
      {
        type: "calcExercise",
        prompt: "Pada ilustrasi grafik, ukuran aparatus 'segera sesudah revolusi' bernilai 60, lalu pada 'praktik' menjadi 95. Berapa persen kenaikannya?",
        answer: 58.3,
        tolerance: 1,
        suffix: "%",
        solution: "Kenaikan = (95 - 60) / 60 x 100% = 58,3%.",
        hint: "Selisih dibagi nilai awal, lalu dikalikan 100 persen.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini menggambarkan teori (visi Marxis) atau kritik atas praktiknya?",
        buckets: ["Teori/visi Marxis", "Kritik atas praktik"],
        items: [
          { text: "Negara adalah alat kelas dominan untuk mempertahankan kekuasaan", bucket: "Teori/visi Marxis" },
          { text: "Setelah masyarakat tanpa kelas, negara akan memudar", bucket: "Teori/visi Marxis" },
          { text: "Di negara komunis abad ke-20, aparatus negara justru membesar dan represif", bucket: "Kritik atas praktik" },
          { text: "Birokrasi dan polisi rahasia menggurita, bukan memudar", bucket: "Kritik atas praktik" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Negara dalam teori Marxis dipandang sebagai alat kelas dominan, bukan wasit netral.",
          "Manifesto: pemerintahan modern sebagai komite yang mengurus urusan kaum borjuis.",
          "Engels (1884): negara muncul bersama kelas dan kepemilikan pribadi.",
          "Visi: setelah masyarakat tanpa kelas, negara penindas akan memudar.",
          "Kritik: dalam praktik negara komunis justru membesar dan represif, bukan memudar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam teori Marxis, negara terutama dipandang sebagai?",
            options: [
              "Wasit netral di atas semua golongan",
              "Alat kelas dominan untuk mempertahankan kekuasaan",
              "Lembaga keagamaan",
              "Organisasi sukarela",
            ],
            answer: 1,
            explain: "Negara dilihat melayani kepentingan kelas yang menguasai alat produksi.",
          },
          {
            q: "Manifesto Komunis menyebut pemerintahan modern sebagai?",
            options: [
              "Pelayan rakyat sejati",
              "Komite yang mengurus urusan bersama seluruh kaum borjuis",
              "Lembaga tanpa kelas",
              "Alat kaum buruh",
            ],
            answer: 1,
            explain: "Itulah rumusan terkenal soal negara sebagai alat kelas borjuasi.",
          },
          {
            q: "Menurut Engels, kapan negara muncul?",
            options: [
              "Sejak awal mula manusia",
              "Bersama lahirnya kelas dan kepemilikan pribadi",
              "Setelah revolusi industri saja",
              "Tidak pernah ada",
            ],
            answer: 1,
            explain: "Engels berargumen negara muncul ketika kepemilikan pribadi dan kelas lahir.",
          },
          {
            q: "Apa yang dimaksud memudarnya negara (withering away)?",
            options: [
              "Negara dihapus dalam semalam",
              "Setelah masyarakat tanpa kelas, negara penindas kehilangan alasan dan memudar",
              "Negara berganti nama",
              "Negara menjadi kerajaan",
            ],
            answer: 1,
            explain: "Tanpa kelas, fungsi negara sebagai alat penindas hilang dan negara memudar.",
          },
          {
            q: "Apa kritik tajam atas praktik negara komunis abad ke-20?",
            options: [
              "Negara benar-benar memudar",
              "Negara justru membesar dan represif, bukan memudar",
              "Tidak ada negara sama sekali",
              "Negara menjadi pasar bebas",
            ],
            answer: 1,
            explain: "Praktiknya, aparatus negara menggurita dan represif, berlawanan dengan visi memudar.",
          },
        ],
      },
    ],
  },
];
