import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "siapa-marx-dan-engels",
    levelId: "dasar",
    order: 1,
    title: "Siapa Marx & Engels, dan Apa yang Mereka Kritik",
    summary: "Latar Revolusi Industri yang melahirkan Marxisme, tokoh Karl Marx dan Friedrich Engels, serta gambaran besar kritiknya atas kapitalisme.",
    durationMin: 13,
    tags: ["dasar", "Marx", "Engels", "sejarah"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Marxisme</strong> adalah kumpulan pemikiran <strong>Karl Marx</strong> (1818-1883) dan kawannya <strong>Friedrich Engels</strong> (1820-1895) tentang ekonomi, sejarah, dan masyarakat. Inti besarnya: sejarah digerakkan oleh cara manusia memproduksi kebutuhan hidupnya, dan kapitalisme mengandung ketimpangan serta kontradiksi yang dalam.",
      },
      {
        type: "paragraph",
        html: "Pemikiran ini lahir di tengah <strong>Revolusi Industri</strong> abad ke-19, saat pabrik tumbuh pesat, buruh bekerja belasan jam dengan upah rendah, dan jurang antara pemilik modal dan pekerja melebar. Marx ingin menjelaskan, secara ilmiah, mengapa itu terjadi.",
      },
      {
        type: "video",
        comp: "MarxEngelsVideo",
        title: "Video: Marx & Engels dalam Garis Waktu",
        caption: "Dari Manifesto Komunis 1848 sampai Das Kapital, karya yang membentuk Marxisme.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_001.jpg?width=400",
        alt: "Potret Karl Marx",
        caption: "Karl Marx (1818-1883), filsuf dan ekonom Jerman, penulis Das Kapital.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua karya kunci",
        html: "<strong>Manifesto Komunis</strong> (1848, bersama Engels) adalah seruan politik ringkas. <strong>Das Kapital</strong> (jilid I terbit 1867) adalah analisis ekonomi mendalam tentang cara kerja kapitalisme.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Marxisme bukan satu hal tunggal",
        html: "Ada Marxisme sebagai <strong>analisis</strong> (cara memahami ekonomi dan sejarah), sebagai <strong>kritik</strong> atas kapitalisme, dan sebagai <strong>gerakan politik</strong>. Topik ini menyajikannya secara kritis dan berimbang, bukan sebagai propaganda.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Lonjakan Urbanisasi Inggris pada Era Industri (ilustrasi historis)",
        unit: "% penduduk tinggal di kota",
        source: "ilustrasi tren historis Revolusi Industri",
        note: "Perpindahan massal ke kota pabrik menciptakan kelas buruh industri baru, latar sosial yang dianalisis Marx.",
        data: [
          { label: "1800", value: 20 },
          { label: "1840", value: 30 },
          { label: "1870", value: 45 },
          { label: "1900", value: 60 },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana ketimpangan distribusi dapat diukur dengan koefisien Gini, salah satu isu yang disorot kritik Marxis.",
      },
      { type: "widget", widget: "KalkulatorGini" },
      {
        type: "case",
        title: "Studi Kasus: Buruh anak di pabrik tekstil",
        html: "Pada pertengahan abad ke-19, banyak pabrik tekstil Inggris mempekerjakan anak-anak <strong>12 sampai 16 jam sehari</strong> dengan upah sangat kecil. Kondisi inilah yang dilihat Marx dan Engels sebagai bukti bahwa keuntungan pemilik modal dibangun di atas kerja yang diperas. Pengamatan Engels di Manchester menjadi bahan bukunya tentang kondisi kelas pekerja.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini lebih mencerminkan pandangan Marxis atau pandangan kapitalis klasik?",
        buckets: ["Marxis", "Kapitalis klasik"],
        items: [
          { text: "Laba berasal dari kerja buruh yang tidak dibayar penuh", bucket: "Marxis" },
          { text: "Pasar bebas mengalokasikan sumber daya paling efisien", bucket: "Kapitalis klasik" },
          { text: "Sejarah digerakkan oleh perjuangan kelas", bucket: "Marxis" },
          { text: "Kepemilikan pribadi mendorong inovasi", bucket: "Kapitalis klasik" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Seorang buruh bekerja 14 jam, tetapi nilai yang setara upahnya tercipta dalam 6 jam pertama. Berapa jam ia bekerja tanpa dibayar (kerja lebih)?",
        answer: 8,
        tolerance: 0,
        suffix: " jam",
        solution: "Kerja lebih = total - kerja perlu = 14 - 6 = <strong>8 jam</strong>. Inilah yang Marx sebut sumber nilai lebih.",
        hint: "Kurangi jam kerja perlu dari total jam kerja.",
      },
      {
        type: "case",
        title: "Sejarah: Manifesto Komunis 1848",
        html: "Pada <strong>1848</strong>, tahun yang dipenuhi revolusi di seluruh Eropa, Marx dan Engels menerbitkan <strong>Manifesto Komunis</strong>. Pamflet tipis ini dibuka dengan kalimat terkenal bahwa sejarah masyarakat adalah sejarah perjuangan kelas, dan ditutup dengan seruan agar kaum pekerja seluruh dunia bersatu. Teksnya menjadi salah satu tulisan politik paling berpengaruh dalam sejarah modern.",
      },
      {
        type: "takeaways",
        items: [
          "Marxisme adalah pemikiran Marx dan Engels tentang ekonomi, sejarah, dan masyarakat.",
          "Lahir dari ketimpangan Revolusi Industri abad ke-19.",
          "Dua karya kunci: Manifesto Komunis (1848) dan Das Kapital (1867).",
          "Inti kritik: kapitalisme membangun laba di atas kerja yang diperas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Siapa dua tokoh utama pendiri Marxisme?",
            options: ["Adam Smith & Ricardo", "Karl Marx & Friedrich Engels", "Lenin & Stalin", "Hegel & Kant"],
            answer: 1,
            explain: "Marxisme dirumuskan Karl Marx bersama Friedrich Engels.",
          },
          {
            q: "Latar sosial yang melahirkan Marxisme adalah?",
            options: ["Revolusi Industri abad ke-19", "Abad Pertengahan", "Era digital", "Zaman Yunani kuno"],
            answer: 0,
            explain: "Ketimpangan Revolusi Industri menjadi latar pemikiran Marx.",
          },
          {
            q: "Karya ekonomi utama Marx adalah?",
            options: ["The Wealth of Nations", "Das Kapital", "Leviathan", "The Republic"],
            answer: 1,
            explain: "Das Kapital (1867) adalah analisis ekonomi mendalam Marx.",
          },
          {
            q: "Menurut Marx, sumber laba kapitalis terutama berasal dari?",
            options: ["Keberuntungan", "Kerja buruh yang tidak dibayar penuh", "Bunga bank", "Pajak"],
            answer: 1,
            explain: "Marx menyebutnya nilai lebih, hasil kerja yang melebihi upah.",
          },
          {
            q: "Manifesto Komunis terbit pada tahun?",
            options: ["1776", "1848", "1917", "1867"],
            answer: 1,
            explain: "Manifesto Komunis terbit pada 1848.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "materialisme-vs-idealisme",
    levelId: "dasar",
    order: 2,
    title: "Materialisme vs Idealisme",
    summary: "Dua cara memandang dunia: idealisme menaruh ide sebagai yang utama, materialisme menaruh kondisi material. Marx memilih materialisme dan membaliknya dari Hegel.",
    durationMin: 14,
    tags: ["dasar", "filsafat", "materialisme", "Hegel"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum bicara ekonomi, Marx menjawab pertanyaan filsafat dasar: <strong>apa yang lebih dulu menentukan, ide atau kenyataan material?</strong> Jawaban atas pertanyaan ini membentuk seluruh cara berpikirnya.",
      },
      {
        type: "paragraph",
        html: "Aliran <strong>idealisme</strong> (dari Plato sampai Hegel) menganggap <strong>ide, roh, atau kesadaran</strong> sebagai yang utama, dan dunia material hanyalah cerminannya. Aliran <strong>materialisme</strong> membalik urutan itu: <strong>kondisi material</strong> (ekonomi, cara produksi, tubuh, alam) yang lebih dulu, dan kesadaran tumbuh darinya.",
      },
      {
        type: "video",
        comp: "MaterialismeHistorisVideo",
        title: "Video: Materialisme Historis",
        caption: "Bagaimana cara manusia memproduksi kebutuhan membentuk gagasan, hukum, dan budayanya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_and_Friedrich_Engels.jpg?width=400",
        alt: "Marx dan Engels",
        caption: "Marx dan Engels, perumus materialisme historis.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kalimat kunci Marx",
        html: "\"Bukan kesadaran manusia yang menentukan keberadaannya, melainkan sebaliknya, keberadaan sosialnya yang menentukan kesadarannya.\" Singkatnya: <strong>bukan kesadaran yang menentukan hidup, melainkan hidup yang menentukan kesadaran</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Marx membalik Hegel",
        html: "Hegel melihat sejarah sebagai gerak <strong>Roh</strong> (ide) menuju kebebasan. Marx memakai cara berpikir dialektis Hegel tetapi membaliknya: yang bergerak bukan ide, melainkan <strong>kondisi material dan hubungan produksi</strong>. Ia menyebutnya menempatkan dialektika Hegel \"berdiri di atas kakinya\".",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan disederhanakan berlebihan",
        html: "Materialisme Marx <strong>bukan</strong> berarti ide tidak penting atau manusia hanya digerakkan uang. Ide, hukum, dan budaya tetap berpengaruh balik. Marx hanya menegaskan basis materialnya lebih menentukan dalam jangka panjang. Banyak pemikir mengkritik ini sebagai terlalu menekankan ekonomi.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dua Aliran, Dua Urutan Sebab (ilustrasi konsep)",
        unit: "yang dianggap utama (skor ilustratif)",
        source: "ilustrasi konsep filsafat",
        note: "Idealisme menaruh ide sebagai penentu utama, materialisme menaruh kondisi material sebagai penentu utama. Keduanya mengakui keduanya ada, hanya berbeda urutan sebab.",
        data: [
          { label: "Idealisme: ide", value: 80, color: "#a855f7" },
          { label: "Idealisme: materi", value: 20, color: "#c4b5fd" },
          { label: "Materialisme: ide", value: 25, color: "#f59e0b" },
          { label: "Materialisme: materi", value: 75, color: "#ef4444" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser posisi pada spektrum ekonomi untuk melihat bagaimana penekanan pada peran negara dan pasar bisa berbeda-beda, bukan hitam-putih.",
      },
      { type: "widget", widget: "SimulatorSpektrumEkonomi" },
      {
        type: "case",
        title: "Studi Kasus: Mengapa orang berpikir berbeda di zaman berbeda",
        html: "Petani abad pertengahan hidup dengan gagasan bahwa kedudukan sosial sudah ditakdirkan. Pedagang kota di era kapitalisme awal mulai percaya pada usaha, untung, dan kebebasan kontrak. Bagi Marx, perubahan gagasan ini <strong>bukan kebetulan</strong>: cara mereka mencari nafkah berubah, maka cara mereka memandang dunia ikut berubah. Material lebih dulu, kesadaran menyusul.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan penjelasannya.",
        pairs: [
          { left: "Idealisme", right: "Ide atau kesadaran dianggap menentukan realitas" },
          { left: "Materialisme", right: "Kondisi material dianggap menentukan kesadaran" },
          { left: "Dialektika Hegel", right: "Sejarah sebagai gerak Roh menuju kebebasan" },
          { left: "Materialisme historis", right: "Sejarah digerakkan oleh cara produksi material" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan ini lebih dekat ke idealisme atau materialisme?",
        buckets: ["Idealisme", "Materialisme"],
        items: [
          { text: "Dunia adalah perwujudan dari Ide atau Roh", bucket: "Idealisme" },
          { text: "Cara orang mencari nafkah membentuk gagasannya", bucket: "Materialisme" },
          { text: "Kesadaran lebih dulu, dunia mengikuti", bucket: "Idealisme" },
          { text: "Ubah basis ekonomi, maka budaya akan berubah", bucket: "Materialisme" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jika idealisme memberi bobot 80 untuk ide dan 20 untuk materi, sedangkan materialisme memberi 25 untuk ide, berapa selisih bobot ide antara kedua aliran?",
        answer: 55,
        tolerance: 0,
        solution: "Selisih = 80 - 25 = <strong>55</strong>. Idealisme menaruh bobot jauh lebih besar pada ide dibanding materialisme.",
        hint: "Kurangi bobot ide materialisme dari bobot ide idealisme.",
      },
      {
        type: "case",
        title: "Sejarah: Pengaruh Ludwig Feuerbach (sekitar 1841)",
        html: "Sekitar <strong>1841</strong>, Ludwig Feuerbach menerbitkan <strong>The Essence of Christianity</strong>, yang berargumen bahwa Tuhan adalah proyeksi sifat-sifat manusia, bukan sebaliknya. Buku ini menggeser Marx muda dari idealisme Hegel menuju materialisme. Belakangan Marx tetap mengkritik Feuerbach karena materialismenya dianggap pasif, lalu menambahkan unsur <strong>praktik dan sejarah</strong>. Dari sinilah lahir materialisme historis.",
      },
      {
        type: "takeaways",
        items: [
          "Idealisme menaruh ide sebagai yang utama, materialisme menaruh kondisi material.",
          "Marx memilih materialisme: hidup menentukan kesadaran, bukan sebaliknya.",
          "Marx memakai dialektika Hegel tetapi membaliknya ke basis material.",
          "Feuerbach (sekitar 1841) menjembatani Marx dari Hegel ke materialisme.",
          "Materialisme bukan berarti ide tak penting, hanya soal urutan sebab.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Aliran yang menganggap ide atau kesadaran sebagai yang utama disebut?",
            options: ["Materialisme", "Idealisme", "Empirisme", "Positivisme"],
            answer: 1,
            explain: "Idealisme menempatkan ide atau kesadaran sebagai penentu realitas.",
          },
          {
            q: "Menurut Marx, hubungan antara hidup dan kesadaran adalah?",
            options: ["Kesadaran menentukan hidup", "Hidup menentukan kesadaran", "Keduanya tak berhubungan", "Hanya Tuhan yang menentukan"],
            answer: 1,
            explain: "Bagi Marx, keberadaan sosial menentukan kesadaran, bukan sebaliknya.",
          },
          {
            q: "Apa yang Marx lakukan terhadap dialektika Hegel?",
            options: ["Menolaknya sepenuhnya", "Membaliknya ke basis material", "Menyalinnya tanpa ubahan", "Mengganti dengan logika formal"],
            answer: 1,
            explain: "Marx memakai dialektika Hegel tetapi menempatkannya pada basis material.",
          },
          {
            q: "Pemikir yang membantu Marx muda beralih ke materialisme adalah?",
            options: ["Immanuel Kant", "Ludwig Feuerbach", "Adam Smith", "David Hume"],
            answer: 1,
            explain: "Feuerbach lewat The Essence of Christianity (sekitar 1841) memengaruhi Marx.",
          },
          {
            q: "Materialisme Marx berarti?",
            options: ["Ide sama sekali tidak penting", "Kondisi material menentukan kesadaran sosial", "Manusia hanya peduli uang", "Dunia hanya khayalan"],
            answer: 1,
            explain: "Materialisme menekankan basis material membentuk kesadaran, bukan meniadakan ide.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kelas-dan-perjuangan-kelas",
    levelId: "dasar",
    order: 3,
    title: "Kelas Sosial & Perjuangan Kelas",
    summary: "Bagaimana Marx membagi masyarakat berdasarkan hubungan dengan alat produksi: borjuasi vs proletariat, dan mengapa perjuangan kelas ia sebut motor sejarah.",
    durationMin: 14,
    tags: ["dasar", "kelas", "proletariat", "borjuasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi Marx, yang menentukan kelas seseorang bukan gaya hidup atau pendapatan semata, melainkan <strong>hubungannya dengan alat produksi</strong>: apakah ia memiliki pabrik, tanah, dan modal, atau hanya memiliki tenaga kerja yang harus dijual.",
      },
      {
        type: "paragraph",
        html: "Dari sini lahir dua kelas pokok dalam kapitalisme: <strong>borjuasi</strong> (pemilik alat produksi) dan <strong>proletariat</strong> (buruh yang menjual tenaga kerjanya untuk upah). Manifesto Komunis membuka dengan kalimat bahwa sejarah segala masyarakat sampai kini adalah <strong>sejarah perjuangan kelas</strong>.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Cara Kerja Kapitalisme",
        caption: "Modal, upah, dan laba: bagaimana hubungan antarkelas terbentuk dalam produksi.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Friedrich_Engels.jpg?width=400",
        alt: "Potret Friedrich Engels",
        caption: "Friedrich Engels (1820-1895), rekan Marx dan penyandang dananya.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua kelas pokok",
        html: "<strong>Borjuasi</strong>: memiliki modal dan alat produksi, hidup dari laba. <strong>Proletariat</strong>: tidak punya alat produksi, hidup dari menjual tenaga kerja. Marx melihat kepentingan keduanya pada dasarnya berlawanan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kesadaran kelas",
        html: "Marx membedakan kelas \"pada dirinya\" (sekadar punya posisi ekonomi sama) dan kelas \"untuk dirinya\" (sadar akan kepentingan bersama dan bertindak). Peralihan ini disebut <strong>kesadaran kelas</strong> (class consciousness), syarat agar buruh bisa bergerak bersama.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan kritis",
        html: "Model dua kelas ini sering dianggap <strong>terlalu sederhana</strong> untuk masyarakat modern, yang punya kelas menengah besar, profesional, dan pemilik saham kecil. Banyak sosiolog memakai stratifikasi yang lebih bertingkat. Pahami model Marx sebagai alat analisis, bukan peta lengkap masyarakat.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Kepemilikan Kekayaan Sangat Terpusat (ilustrasi pola umum)",
        unit: "% kekayaan nasional",
        source: "ilustrasi pola ketimpangan kekayaan yang umum diamati",
        note: "Pola umum di banyak negara: sebagian kecil rumah tangga teratas menguasai porsi kekayaan yang jauh lebih besar dari porsi penduduknya. Ini jenis ketimpangan kepemilikan yang disorot analisis kelas.",
        data: [
          { label: "10% teratas", value: 60, color: "#ef4444" },
          { label: "40% menengah", value: 33, color: "#f59e0b" },
          { label: "50% terbawah", value: 7, color: "#94a3b8" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung koefisien Gini untuk berbagai sebaran pendapatan, dan rasakan bagaimana pemusatan kekayaan menaikkan angka ketimpangan.",
      },
      { type: "widget", widget: "KalkulatorGini" },
      {
        type: "case",
        title: "Studi Kasus: Buruh pabrik dan pemilik pabrik",
        html: "Bayangkan sebuah pabrik sepatu. <strong>Pemilik</strong> menyediakan modal, mesin, dan bahan, lalu mengambil laba. <strong>Buruh</strong> menyumbang tenaga dan keterampilan, lalu menerima upah tetap berapa pun laba pabrik. Saat permintaan turun, pemilik bisa memangkas jam atau merumahkan buruh untuk menjaga laba. Posisi tawar yang timpang inilah yang dilihat Marx sebagai akar perjuangan kelas.",
      },
      {
        type: "classifyExercise",
        prompt: "Tergolong borjuasi atau proletariat menurut definisi Marx?",
        buckets: ["Borjuasi", "Proletariat"],
        items: [
          { text: "Pemilik pabrik yang hidup dari laba", bucket: "Borjuasi" },
          { text: "Operator mesin yang digaji per bulan", bucket: "Proletariat" },
          { text: "Pemodal yang menyewakan tanah dan alat", bucket: "Borjuasi" },
          { text: "Kasir yang menjual tenaga kerjanya untuk upah", bucket: "Proletariat" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah pabrik menghasilkan laba Rp 1.000.000.000 setahun. Pemilik (1% dari 100 orang di pabrik) mengambil 70% laba, sisanya dibagi rata ke 99 buruh. Berapa bagian satu buruh (dalam rupiah)?",
        answer: 3030303,
        tolerance: 5000,
        prefix: "Rp",
        solution: "Sisa untuk buruh = 30% x Rp 1.000.000.000 = Rp 300.000.000. Per buruh = 300.000.000 / 99 = sekitar <strong>Rp 3.030.303</strong>, sedangkan pemilik tunggal mengambil Rp 700.000.000.",
        hint: "Hitung dulu 30% dari laba, lalu bagi 99.",
      },
      {
        type: "case",
        title: "Sejarah: Gelombang Revolusi 1848 di Eropa",
        html: "Pada <strong>1848</strong>, gelombang revolusi meletus di Prancis, negara-negara Jerman, Austria, Italia, dan lainnya. Buruh kota, kelas menengah, dan kaum nasionalis menuntut hak politik dan perbaikan hidup. Tahun yang sama Manifesto Komunis terbit. Walau sebagian besar revolusi ini akhirnya dipadamkan, peristiwa 1848 memperlihatkan kekuatan baru gerakan buruh dan menjadi bukti hidup bagi tesis Marx tentang perjuangan kelas.",
      },
      {
        type: "takeaways",
        items: [
          "Kelas ditentukan oleh hubungan dengan alat produksi, bukan sekadar pendapatan.",
          "Dua kelas pokok kapitalisme: borjuasi (pemilik modal) dan proletariat (buruh).",
          "Perjuangan kelas disebut Marx sebagai motor penggerak sejarah.",
          "Kesadaran kelas adalah saat buruh menyadari dan memperjuangkan kepentingan bersama.",
          "Model dua kelas berguna sebagai analisis, tetapi dikritik terlalu menyederhanakan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menurut Marx, kelas seseorang terutama ditentukan oleh?",
            options: ["Gaya hidupnya", "Hubungannya dengan alat produksi", "Tingkat pendidikannya", "Agamanya"],
            answer: 1,
            explain: "Kelas ditentukan oleh apakah seseorang memiliki alat produksi atau menjual tenaga kerja.",
          },
          {
            q: "Kelas yang menjual tenaga kerjanya untuk upah disebut?",
            options: ["Borjuasi", "Proletariat", "Aristokrasi", "Bangsawan"],
            answer: 1,
            explain: "Proletariat adalah buruh yang hidup dari menjual tenaga kerjanya.",
          },
          {
            q: "Kalimat pembuka Manifesto Komunis menyebut sejarah masyarakat sebagai?",
            options: ["Sejarah para raja", "Sejarah perjuangan kelas", "Sejarah teknologi", "Sejarah perang agama"],
            answer: 1,
            explain: "Manifesto membuka dengan tesis bahwa sejarah adalah sejarah perjuangan kelas.",
          },
          {
            q: "Kesadaran kelas (class consciousness) berarti?",
            options: ["Rasa bangga kebangsaan", "Buruh menyadari kepentingan bersama dan bertindak", "Kesadaran beragama", "Kesadaran lingkungan"],
            answer: 1,
            explain: "Kesadaran kelas adalah saat sebuah kelas sadar akan kepentingan bersamanya.",
          },
          {
            q: "Kritik umum atas model dua kelas Marx adalah?",
            options: ["Terlalu rumit", "Terlalu menyederhanakan masyarakat modern", "Mengabaikan ekonomi", "Hanya berlaku di Asia"],
            answer: 1,
            explain: "Banyak yang menilai model dua kelas terlalu sederhana untuk masyarakat dengan kelas menengah besar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "komodifikasi-dan-fetisisme",
    levelId: "dasar",
    order: 4,
    title: "Komodifikasi & Fetisisme Komoditas",
    summary: "Mengapa dalam kapitalisme segala hal cenderung jadi komoditas, dan bagaimana nilai yang sebenarnya berasal dari kerja sosial seakan melekat alami pada barang.",
    durationMin: 14,
    tags: ["dasar", "komoditas", "fetisisme", "Das Kapital"],
    blocks: [
      {
        type: "paragraph",
        html: "Das Kapital tidak dibuka dengan kelas atau revolusi, melainkan dengan benda yang paling sehari-hari: <strong>komoditas</strong>, yaitu barang yang diproduksi untuk dijual di pasar. Bagi Marx, memahami komoditas adalah kunci memahami seluruh kapitalisme.",
      },
      {
        type: "paragraph",
        html: "Dalam kapitalisme, makin banyak hal berubah menjadi komoditas: pangan, perumahan, hiburan, bahkan <strong>tenaga kerja manusia</strong>. Proses menjadikan sesuatu sebagai barang dagangan inilah yang disebut <strong>komodifikasi</strong>.",
      },
      {
        type: "video",
        comp: "KapitalismeVideo",
        title: "Video: Cara Kerja Kapitalisme",
        caption: "Dari nilai pakai ke nilai tukar: bagaimana barang menjadi komoditas di pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Nilai pakai vs nilai tukar",
        html: "Sebuah barang punya <strong>nilai pakai</strong> (gunanya, misalnya roti mengenyangkan) dan <strong>nilai tukar</strong> (berapa ia ditukar dengan barang lain atau uang). Dalam kapitalisme, produksi diarahkan pada nilai tukar, yaitu untuk dijual dan menghasilkan laba, bukan sekadar untuk dipakai.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Fetisisme komoditas",
        html: "Marx menyebut <strong>fetisisme komoditas</strong>: hubungan sosial antarmanusia (siapa membuat apa, dengan kerja siapa) tampak seolah-olah hanya hubungan antarbarang dan harga. Nilai seakan <strong>melekat alami</strong> pada barang, padahal sebenarnya berasal dari <strong>kerja sosial</strong> manusia yang membuatnya.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Catatan kritis",
        html: "Teori nilai-kerja yang mendasari analisis ini <strong>diperdebatkan</strong>. Ekonomi arus utama menjelaskan harga lewat penawaran, permintaan, dan kelangkaan, bukan jumlah kerja. Pelajari fetisisme komoditas sebagai kritik budaya dan sosial yang tajam, sambil sadar bahwa landasan ekonominya tidak diterima semua ekonom.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Makin Banyak Bidang Hidup yang Dikomodifikasi (ilustrasi tren)",
        unit: "cakupan komodifikasi (skor ilustratif)",
        source: "ilustrasi tren konseptual",
        note: "Seiring meluasnya pasar, makin banyak aspek hidup (air, pendidikan, layanan, data pribadi) yang dijual sebagai komoditas. Ini menggambarkan arah komodifikasi, bukan data statistik resmi.",
        data: [
          { label: "Pra-industri", value: 20 },
          { label: "Industri awal", value: 40 },
          { label: "Industri lanjut", value: 60 },
          { label: "Pascaindustri", value: 80 },
          { label: "Digital", value: 95 },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dari Mana Nilai Sebuah Barang Berasal (menurut Marx)",
        unit: "kontribusi nilai (ilustratif)",
        source: "ilustrasi teori nilai-kerja Marx",
        note: "Bagi Marx, sebagian besar nilai berasal dari kerja manusia yang sering tak terlihat di balik harga. Bahan dan mesin memindahkan nilai, tetapi nilai baru ditambahkan oleh kerja hidup.",
        data: [
          { label: "Kerja manusia", value: 55, color: "#ef4444" },
          { label: "Bahan baku", value: 30, color: "#f59e0b" },
          { label: "Aus mesin", value: 15, color: "#94a3b8" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan kenaikan upah dengan kenaikan produktivitas. Jika produktivitas naik jauh lebih cepat dari upah, selisihnya inilah yang menjadi sorotan analisis nilai lebih.",
      },
      { type: "widget", widget: "KalkulatorUpahProduktivitas" },
      {
        type: "case",
        title: "Studi Kasus: Secangkir kopi dan kerja yang tersembunyi",
        html: "Saat membeli kopi, kita melihat harga di menu, bukan petani yang memetik biji, pekerja yang mengolah, atau pengantar yang membawanya. Bagi Marx, harga itu <strong>menyembunyikan</strong> rantai kerja sosial di baliknya, seolah nilai melekat pada cangkir itu sendiri. Itulah fetisisme komoditas dalam kehidupan sehari-hari.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Komoditas", right: "Barang yang diproduksi untuk dijual" },
          { left: "Komodifikasi", right: "Proses menjadikan sesuatu sebagai barang dagangan" },
          { left: "Nilai pakai", right: "Kegunaan barang dalam memenuhi kebutuhan" },
          { left: "Fetisisme komoditas", right: "Hubungan antarmanusia tampak sebagai hubungan antarbarang" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah meja dijual Rp 500.000. Menurut estimasi nilai-kerja, kerja manusia menyumbang 55% dari nilainya. Berapa rupiah nilai dari kerja manusia itu?",
        answer: 275000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai kerja = 55% x Rp 500.000 = <strong>Rp 275.000</strong>. Sisanya berasal dari bahan dan aus mesin.",
        hint: "Hitung 55% dari Rp 500.000.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini sesuai pandangan Marx atau lebih sesuai ekonomi arus utama?",
        buckets: ["Pandangan Marx", "Ekonomi arus utama"],
        items: [
          { text: "Nilai barang terutama berasal dari kerja sosial", bucket: "Pandangan Marx" },
          { text: "Harga ditentukan penawaran dan permintaan", bucket: "Ekonomi arus utama" },
          { text: "Komoditas menyembunyikan hubungan kerja di baliknya", bucket: "Pandangan Marx" },
          { text: "Kelangkaan menaikkan harga sebuah barang", bucket: "Ekonomi arus utama" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Das Kapital Bab 1 (1867)",
        html: "Pada <strong>1867</strong>, jilid pertama <strong>Das Kapital</strong> terbit. Bab pembukanya membahas komoditas, nilai pakai, dan nilai tukar, lalu memuncak pada bagian terkenal tentang <strong>fetisisme komoditas</strong>. Di situ Marx menulis bahwa di tangan kapitalisme, produk kerja manusia memperoleh \"karakter mistis\", seakan barang punya nilai dari dirinya sendiri, lepas dari kerja yang menciptakannya. Bagian ini menjadi salah satu yang paling banyak dibahas dalam seluruh karya Marx.",
      },
      {
        type: "takeaways",
        items: [
          "Komoditas adalah barang yang diproduksi untuk dijual, fokus utama Das Kapital.",
          "Komodifikasi: makin banyak hal, termasuk tenaga kerja, menjadi barang dagangan.",
          "Nilai pakai adalah kegunaan, nilai tukar adalah nilai dalam pertukaran pasar.",
          "Fetisisme komoditas: nilai seakan melekat pada barang, padahal berasal dari kerja sosial.",
          "Landasan teori nilai-kerja diperdebatkan; ekonomi arus utama menekankan penawaran-permintaan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa yang dimaksud komoditas dalam analisis Marx?",
            options: ["Barang yang diproduksi untuk dijual", "Uang tunai", "Barang warisan", "Hadiah dari negara"],
            answer: 0,
            explain: "Komoditas adalah barang yang diproduksi untuk ditukar atau dijual di pasar.",
          },
          {
            q: "Proses menjadikan makin banyak hal sebagai barang dagangan disebut?",
            options: ["Privatisasi", "Komodifikasi", "Nasionalisasi", "Inflasi"],
            answer: 1,
            explain: "Komodifikasi adalah proses menjadikan sesuatu sebagai komoditas.",
          },
          {
            q: "Nilai tukar sebuah barang adalah?",
            options: ["Kegunaannya memenuhi kebutuhan", "Nilainya saat ditukar dengan barang lain atau uang", "Berat fisiknya", "Usia barang"],
            answer: 1,
            explain: "Nilai tukar adalah nilai barang dalam pertukaran, berbeda dari nilai pakai.",
          },
          {
            q: "Fetisisme komoditas menurut Marx berarti?",
            options: ["Orang menyembah patung", "Hubungan antarmanusia tampak sebagai hubungan antarbarang", "Harga selalu naik", "Barang langka jadi mahal"],
            answer: 1,
            explain: "Fetisisme komoditas membuat kerja sosial tersembunyi di balik tampilan barang dan harga.",
          },
          {
            q: "Mana kritik yang tepat atas landasan teori ini?",
            options: ["Tidak ada yang mengkritiknya", "Ekonomi arus utama menjelaskan harga lewat penawaran dan permintaan, bukan jumlah kerja", "Marx tidak pernah menulisnya", "Hanya berlaku untuk emas"],
            answer: 1,
            explain: "Teori nilai-kerja diperdebatkan; arus utama menekankan penawaran, permintaan, dan kelangkaan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "gambaran-besar-marxisme",
    levelId: "dasar",
    order: 5,
    title: "Gambaran Besar: Apa yang Ditawarkan Marxisme",
    summary: "Rangkuman visi Marx dari kritik kapitalisme menuju sosialisme lalu komunisme tanpa kelas, beserta kritik atasnya dan pelajaran dari kenyataan sejarah.",
    durationMin: 15,
    tags: ["dasar", "sosialisme", "komunisme", "kritik"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah mengenal materialisme, kelas, dan komoditas, kita bisa menyusun gambaran besarnya. Marxisme bukan sekadar mengeluhkan kapitalisme, melainkan menawarkan <strong>arah perubahan</strong>: dari kapitalisme, menuju sosialisme, lalu cita-cita akhir komunisme.",
      },
      {
        type: "paragraph",
        html: "Penting ditegaskan: ini adalah <strong>visi dan teori</strong>. Bagaimana ia dijalankan di dunia nyata sangat diperdebatkan, dan banyak praktik yang mengaku Marxis menghasilkan hal yang jauh dari cita-cita aslinya.",
      },
      {
        type: "video",
        comp: "SejarahKapitalismeVideo",
        title: "Video: Sejarah Kapitalisme",
        caption: "Dari mana kapitalisme datang, dan ke mana Marx membayangkan sejarah akan bergerak.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_Luxemburg.jpg?width=400",
        alt: "Potret Rosa Luxemburg",
        caption: "Rosa Luxemburg (1871-1919), Marxis yang menekankan demokrasi dan spontanitas massa.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga tahap dalam visi Marx",
        html: "<strong>Kapitalisme</strong>: produksi swasta, laba, dan kelas. <strong>Sosialisme</strong>: alat produksi dikuasai bersama, masa transisi. <strong>Komunisme</strong>: cita-cita masyarakat tanpa kelas dan tanpa negara, dengan prinsip \"dari tiap orang sesuai kemampuan, untuk tiap orang sesuai kebutuhan\".",
      },
      {
        type: "callout",
        tone: "info",
        title: "Marxisme itu beragam",
        html: "Tidak ada satu Marxisme. Ada yang menekankan <strong>demokrasi</strong> dan jalan damai (mis. Rosa Luxemburg menolak teror dan menekankan peran massa), ada yang menekankan partai dan revolusi. Banyak gagasan Marx juga memengaruhi sosiologi, ekonomi, dan studi budaya tanpa harus menjadi gerakan politik.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kritik dan kenyataan sejarah",
        html: "Banyak negara yang mengaku komunis pada abad ke-20 justru berakhir <strong>otoriter</strong>, dengan ekonomi terpusat yang tidak efisien dan pelanggaran HAM berat. Kritikus menilai cita-cita tanpa kelas sulit dicapai dan rentan disalahgunakan. Pendukung membalas bahwa praktik itu mengkhianati ide aslinya. Topik ini menyajikan perdebatan, bukan memihak.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Pasang Surut Jumlah Negara Berhaluan Sosialis-Komunis Abad ke-20 (ilustrasi tren)",
        unit: "jumlah negara (ilustratif)",
        source: "ilustrasi tren sejarah abad ke-20",
        note: "Blok ini tumbuh setelah 1917 dan 1945, memuncak sekitar dekade 1980-an, lalu menyusut tajam setelah 1989-1991. Angka bersifat ilustratif untuk menunjukkan arah, bukan hitungan resmi.",
        data: [
          { label: "1917", value: 1 },
          { label: "1950", value: 9 },
          { label: "1980", value: 24 },
          { label: "1991", value: 18 },
          { label: "2000", value: 5 },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser posisi pada spektrum ekonomi: murni pasar, campuran, sampai terencana penuh. Banyak negara nyata berada di tengah, bukan di ujung mana pun.",
      },
      { type: "widget", widget: "SimulatorSpektrumEkonomi" },
      {
        type: "case",
        title: "Studi Kasus: Negara kesejahteraan yang menyerap kritik Marx",
        html: "Banyak negara demokrasi tidak menjadi komunis, tetapi menyerap sebagian kritik Marxis lewat <strong>negara kesejahteraan</strong>: jam kerja dibatasi, ada upah minimum, jaminan sosial, dan serikat buruh yang diakui. Ini contoh bagaimana gagasan Marx ikut mendorong reformasi di dalam kapitalisme, bukan hanya lewat revolusi.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri ini paling sesuai tahap yang mana dalam kerangka Marx?",
        buckets: ["Kapitalisme", "Sosialisme", "Komunisme"],
        items: [
          { text: "Alat produksi dimiliki swasta, hidup dari laba", bucket: "Kapitalisme" },
          { text: "Alat produksi dikuasai bersama sebagai masa transisi", bucket: "Sosialisme" },
          { text: "Masyarakat tanpa kelas dan tanpa negara", bucket: "Komunisme" },
          { text: "Distribusi menurut kebutuhan tiap orang", bucket: "Komunisme" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jumlah negara berhaluan sosialis-komunis (ilustratif) memuncak 24 pada 1980 lalu turun ke 5 pada 2000. Berapa persen penurunannya?",
        answer: 79,
        tolerance: 1,
        suffix: "%",
        solution: "Penurunan = (24 - 5) / 24 x 100% = 19/24 x 100% = sekitar <strong>79%</strong>. Penyusutan tajam setelah berakhirnya Perang Dingin.",
        hint: "Bagi selisihnya dengan angka puncak, lalu kali 100%.",
      },
      {
        type: "case",
        title: "Sejarah: Keruntuhan Uni Soviet 1991",
        html: "Pada <strong>1991</strong>, Uni Soviet bubar setelah ekonomi terpusatnya stagnan, ditambah keterbukaan politik (glasnost) dan reformasi (perestroika) yang dijalankan Mikhail Gorbachev sejak pertengahan 1980-an. Bagi banyak orang, ini menjadi bukti kegagalan model ekonomi komando. Bagi sebagian Marxis, yang runtuh adalah sistem birokratis-otoriter tertentu, bukan seluruh gagasan Marx. Peristiwa ini menjadi bahan evaluasi kritis yang penting saat menilai Marxisme.",
      },
      {
        type: "takeaways",
        items: [
          "Visi Marx: kapitalisme menuju sosialisme, lalu cita-cita komunisme tanpa kelas.",
          "Marxisme beragam, dari yang menekankan demokrasi sampai yang menekankan revolusi.",
          "Banyak negara komunis abad ke-20 berakhir otoriter dan tidak efisien.",
          "Sebagian kritik Marx terserap lewat negara kesejahteraan di dalam kapitalisme.",
          "Keruntuhan Uni Soviet 1991 menjadi bahan evaluasi kritis yang penting.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Urutan tahap dalam visi besar Marx adalah?",
            options: ["Komunisme - sosialisme - kapitalisme", "Kapitalisme - sosialisme - komunisme", "Feodalisme - kapitalisme - feodalisme", "Pasar - pasar - pasar"],
            answer: 1,
            explain: "Marx membayangkan gerak dari kapitalisme, ke sosialisme, menuju komunisme.",
          },
          {
            q: "Cita-cita komunisme menurut Marx adalah masyarakat?",
            options: ["Dengan raja yang adil", "Tanpa kelas dan tanpa negara", "Dengan pasar bebas penuh", "Dengan kasta tetap"],
            answer: 1,
            explain: "Komunisme dibayangkan sebagai masyarakat tanpa kelas dan tanpa negara.",
          },
          {
            q: "Rosa Luxemburg dikenal menekankan?",
            options: ["Teror dan kediktatoran", "Demokrasi dan spontanitas massa", "Monarki absolut", "Pasar tanpa aturan"],
            answer: 1,
            explain: "Luxemburg menekankan demokrasi dan peran spontan massa, menolak teror.",
          },
          {
            q: "Salah satu kritik atas praktik negara komunis abad ke-20 adalah?",
            options: ["Terlalu demokratis", "Cenderung otoriter dan ekonomi tak efisien", "Terlalu banyak pasar bebas", "Tidak punya pemerintah"],
            answer: 1,
            explain: "Banyak negara komunis berakhir otoriter dengan ekonomi komando yang tidak efisien.",
          },
          {
            q: "Uni Soviet bubar pada tahun?",
            options: ["1945", "1968", "1991", "2008"],
            answer: 2,
            explain: "Uni Soviet bubar pada 1991, menjadi bahan evaluasi kritis atas model ekonomi komando.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "tiga-sumber-marxisme",
    levelId: "dasar",
    order: 6,
    title: "Tiga Sumber & Tiga Unsur Marxisme",
    summary: "Akar pemikiran Marx menurut esai Lenin 1913: filsafat klasik Jerman, ekonomi politik Inggris, dan sosialisme Prancis, serta beda sosialisme utopis dan ilmiah.",
    durationMin: 14,
    tags: ["dasar", "Lenin", "sosialisme utopis", "filsafat"],
    blocks: [
      {
        type: "paragraph",
        html: "Pemikiran Marx tidak muncul dari ruang kosong. Dalam esai pendek <strong>Tiga Sumber dan Tiga Unsur Marxisme</strong> (1913), <strong>Lenin</strong> meringkas bahwa Marxisme adalah pewaris sah tiga arus pemikiran terbaik abad ke-19 dari tiga negara yang paling maju saat itu.",
      },
      {
        type: "paragraph",
        html: "Tiga sumber itu adalah <strong>filsafat klasik Jerman</strong>, <strong>ekonomi politik Inggris</strong>, dan <strong>sosialisme Prancis</strong>. Marx tidak sekadar menjiplak ketiganya, tetapi mengkritik, menyaring, dan memadukannya menjadi satu kerangka baru.",
      },
      {
        type: "video",
        comp: "TigaSumberMarxismeVideo",
        title: "Video: Tiga Sumber Marxisme",
        caption: "Bagaimana filsafat Jerman, ekonomi Inggris, dan sosialisme Prancis berpadu dalam pemikiran Marx.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga sumber, satu sintesis",
        html: "(1) <strong>Filsafat Jerman</strong>: dialektika Hegel dan materialisme Feuerbach. (2) <strong>Ekonomi politik Inggris</strong>: teori nilai kerja Adam Smith dan David Ricardo. (3) <strong>Sosialisme Prancis</strong>: cita-cita Saint-Simon, Fourier, dan Robert Owen.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Robert_Owen_by_William_Henry_Brooke.jpg?width=400",
        alt: "Potret Robert Owen",
        caption: "Robert Owen (1771-1858), sosialis utopis Inggris yang membangun komunitas pekerja New Lanark.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Charles_Fourier.jpg?width=400",
        alt: "Potret Charles Fourier",
        caption: "Charles Fourier (1772-1837), sosialis utopis Prancis.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "info",
        title: "Utopis vs ilmiah",
        html: "<strong>Sosialisme utopis</strong> membayangkan masyarakat ideal yang adil lalu mengajak orang mewujudkannya. <strong>Sosialisme ilmiah</strong> ala Marx justru menganalisis kontradiksi nyata dalam kapitalisme untuk menjelaskan dari mana perubahan akan datang.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bukan berarti utopis tak berjasa",
        html: "Owen dan Fourier sering disebut naif, tetapi merekalah yang pertama menuntut hari kerja lebih pendek, pendidikan anak buruh, dan koperasi. Marx menghargai keberanian moral mereka, lalu mencari dasar yang lebih analitis.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Asal tiga unsur Marxisme menurut Lenin (1913)",
        unit: "tokoh kunci tiap sumber",
        source: "esai Lenin, Tiga Sumber dan Tiga Unsur Marxisme (1913)",
        note: "Tiap sumber dipinjam dari negara yang paling maju di bidangnya: filsafat dari Jerman, ekonomi dari Inggris, sosialisme dari Prancis.",
        data: [
          { label: "Filsafat (Jerman)", value: 2, color: "#6366f1" },
          { label: "Ekonomi (Inggris)", value: 2, color: "#0ea5e9" },
          { label: "Sosialisme (Prancis)", value: 3, color: "#f59e0b" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Gerakkan slider untuk melihat di mana berbagai gagasan ekonomi berada pada spektrum dari pasar bebas penuh sampai kepemilikan kolektif penuh.",
      },
      {
        type: "widget",
        widget: "SimulatorSpektrumEkonomi",
      },
      {
        type: "case",
        title: "Dari mana nilai sebuah barang?",
        html: "Adam Smith dan David Ricardo berpendapat nilai sebuah barang berakar pada <strong>kerja</strong> yang dibutuhkan untuk membuatnya (teori nilai kerja). Marx memungut ide ini, lalu bertanya lebih jauh: jika kerja yang menciptakan nilai, mengapa keuntungan justru mengalir ke pemilik modal, bukan ke pekerja? Pertanyaan itulah yang melahirkan konsep nilai lebih di Das Kapital.",
      },
      {
        type: "case",
        title: "Sejarah: New Lanark & New Harmony (1800-1828)",
        html: "Robert Owen mengelola pabrik kapas <strong>New Lanark</strong> di Skotlandia sejak 1800. Ia memperpendek jam kerja, melarang anak kecil bekerja, dan membangun sekolah, dan pabriknya tetap untung. Pada 1825 ia membeli tanah di Indiana, Amerika, untuk komunitas ideal <strong>New Harmony</strong>. Eksperimen itu bubar sekitar 1828 karena perselisihan internal, contoh klasik keberanian sekaligus keterbatasan sosialisme utopis.",
      },
      {
        type: "calcExercise",
        prompt: "Lenin menyebut TIGA sumber Marxisme. Berapa banyak negara berbeda yang menjadi asal ketiga sumber itu (Jerman, Inggris, Prancis)?",
        answer: 3,
        solution: "Filsafat dari Jerman, ekonomi politik dari Inggris, sosialisme dari Prancis. Ada tiga negara berbeda.",
        hint: "Hitung negara asal tiap sumber.",
      },
      {
        type: "calcExercise",
        prompt: "Robert Owen mulai mengelola New Lanark pada 1800 dan eksperimen New Harmony bubar sekitar 1828. Berapa selisih tahun keduanya?",
        answer: 28,
        suffix: " tahun",
        solution: "1828 - 1800 = 28 tahun.",
        hint: "Kurangkan tahun awal dari tahun akhir.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap tokoh atau gagasan ke sumber Marxisme yang tepat.",
        buckets: ["Filsafat Jerman", "Ekonomi Inggris", "Sosialisme Prancis"],
        items: [
          { text: "Dialektika Hegel", bucket: "Filsafat Jerman" },
          { text: "Materialisme Feuerbach", bucket: "Filsafat Jerman" },
          { text: "Teori nilai kerja Ricardo", bucket: "Ekonomi Inggris" },
          { text: "Adam Smith", bucket: "Ekonomi Inggris" },
          { text: "Charles Fourier", bucket: "Sosialisme Prancis" },
          { text: "Saint-Simon", bucket: "Sosialisme Prancis" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Lenin (1913) merangkum Marxisme sebagai pewaris tiga arus pemikiran abad ke-19.",
          "Tiga sumber: filsafat klasik Jerman, ekonomi politik Inggris, sosialisme Prancis.",
          "Marx mengkritik dan memadukan ketiganya, bukan sekadar menyalin.",
          "Sosialisme utopis membayangkan masyarakat ideal; sosialisme ilmiah menganalisis kontradiksi nyata.",
          "Owen dan Fourier perintis tuntutan jam kerja pendek dan pendidikan buruh, meski eksperimennya gagal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Esai siapa yang merumuskan Tiga Sumber dan Tiga Unsur Marxisme (1913)?",
            options: ["Karl Marx", "Friedrich Engels", "Lenin", "Rosa Luxemburg"],
            answer: 2,
            explain: "Lenin menulis esai itu pada 1913 untuk meringkas akar pemikiran Marx.",
          },
          {
            q: "Manakah yang termasuk sumber filsafat klasik Jerman?",
            options: ["Teori nilai kerja Ricardo", "Dialektika Hegel", "Komunitas New Harmony", "Pasar bebas Smith"],
            answer: 1,
            explain: "Dialektika Hegel dan materialisme Feuerbach adalah sumber filsafat Jerman.",
          },
          {
            q: "Teori nilai kerja yang dipungut Marx berasal dari ekonom?",
            options: ["Smith dan Ricardo", "Saint-Simon dan Fourier", "Hegel dan Feuerbach", "Owen dan Engels"],
            answer: 0,
            explain: "Adam Smith dan David Ricardo adalah tokoh ekonomi politik Inggris.",
          },
          {
            q: "Apa yang membedakan sosialisme utopis dari sosialisme ilmiah Marx?",
            options: ["Utopis menganalisis kontradiksi nyata", "Ilmiah hanya membayangkan masyarakat ideal", "Utopis membayangkan masyarakat ideal, ilmiah menganalisis kontradiksi nyata", "Keduanya sama persis"],
            answer: 2,
            explain: "Utopis membayangkan cita-cita; Marx menganalisis kontradiksi nyata kapitalisme.",
          },
          {
            q: "Robert Owen dikenal karena eksperimen komunitas pekerja di?",
            options: ["Paris dan Brussels", "New Lanark dan New Harmony", "London dan Manchester", "Trier dan Berlin"],
            answer: 1,
            explain: "Owen mengelola New Lanark di Skotlandia dan mendirikan New Harmony di Amerika.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "marx-sang-pemikir-dan-eksil",
    levelId: "dasar",
    order: 7,
    title: "Karl Marx: Jurnalis, Eksil & Persahabatan dengan Engels",
    summary: "Riwayat hidup Marx dari Trier ke London: jurnalis yang dibredel, hidup miskin dalam pengasingan, ditopang Engels, dan Internasional Pertama 1864.",
    durationMin: 14,
    tags: ["dasar", "Marx", "Engels", "biografi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Karl Marx</strong> lahir di <strong>Trier</strong>, Jerman, pada 1818. Ia belajar hukum lalu filsafat, dan sempat bercita-cita jadi dosen. Namun jalannya berbelok ke jurnalisme, dan tulisan-tulisannya yang tajam membuatnya berkali-kali berbenturan dengan penguasa.",
      },
      {
        type: "paragraph",
        html: "Sebagai editor surat kabar <strong>Rheinische Zeitung</strong>, Marx mengkritik sensor dan ketimpangan. Koran itu dibredel pemerintah pada 1843. Sejak itu hidupnya berpindah dari satu pengasingan ke pengasingan lain: Paris, Brussels, dan akhirnya London.",
      },
      {
        type: "video",
        comp: "MarxEngelsVideo",
        title: "Video: Marx & Engels dalam Garis Waktu",
        caption: "Persahabatan dan kerja sama dua pemikir yang membentuk Marxisme.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Friedrich_Engels.jpg?width=400",
        alt: "Potret Friedrich Engels",
        caption: "Friedrich Engels (1820-1895), sahabat dan penyokong Marx.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tanpa Engels, tak ada Das Kapital lengkap",
        html: "Engels mengelola pabrik tekstil keluarga di <strong>Manchester</strong> dan secara rutin mengirim uang agar keluarga Marx bertahan. Setelah Marx wafat, Engels menyunting dan menyelesaikan <strong>jilid II dan III Das Kapital</strong> dari tumpukan catatan Marx.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ditempa di ruang baca",
        html: "Di London, Marx menghabiskan tahun demi tahun di ruang baca <strong>British Museum</strong>, membaca laporan pabrik, statistik, dan ekonomi politik. Dari riset panjang itulah Das Kapital tersusun.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hidup dalam kemiskinan",
        html: "Marx kerap menunggak sewa, beberapa anaknya meninggal saat kecil, dan ia bergantung pada bantuan Engels serta honor sebagai koresponden surat kabar. Idenya besar, tetapi hidupnya jauh dari nyaman.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Kota-kota pengasingan Karl Marx",
        unit: "tahun mulai menetap",
        source: "kronologi biografi Karl Marx (1818-1883)",
        note: "Setelah Rheinische Zeitung dibredel 1843, Marx terus berpindah hingga menetap di London sejak 1849 sampai wafat 1883.",
        data: [
          { label: "Trier (lahir)", value: 1818, color: "#94a3b8" },
          { label: "Paris", value: 1843, color: "#6366f1" },
          { label: "Brussels", value: 1845, color: "#0ea5e9" },
          { label: "London", value: 1849, color: "#ef4444" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Marx memandang kapitalisme melahirkan ketimpangan. Gunakan kalkulator ini untuk merasakan bagaimana koefisien Gini mengukur seberapa timpang pembagian pendapatan.",
      },
      {
        type: "widget",
        widget: "KalkulatorGini",
      },
      {
        type: "case",
        title: "Persahabatan yang menopang sebuah karya",
        html: "Marx dan Engels bertemu pada 1844 di Paris dan langsung akrab. Selama hampir 40 tahun Engels tidak hanya berdiskusi, tetapi juga menanggung biaya hidup keluarga Marx dari laba pabrik di Manchester. Tanpa sokongan finansial itu, kemungkinan besar Marx tak akan sanggup bertahun-tahun meriset dan menulis Das Kapital.",
      },
      {
        type: "case",
        title: "Sejarah: Internasional Pertama (1864)",
        html: "Pada 1864 berdiri <strong>Asosiasi Pekerja Internasional</strong> atau Internasional Pertama di London. Marx menjadi salah satu tokoh paling berpengaruh di dalamnya dan menyusun pidato pembukaan serta banyak dokumennya. Organisasi ini menghubungkan serikat buruh lintas negara, tetapi pecah sekitar 1872-1876 karena perselisihan dengan kelompok anarkis pimpinan Bakunin.",
      },
      {
        type: "calcExercise",
        prompt: "Karl Marx lahir pada 1818 dan wafat pada 1883. Berapa usianya saat wafat?",
        answer: 65,
        suffix: " tahun",
        solution: "1883 - 1818 = 65 tahun.",
        hint: "Kurangkan tahun lahir dari tahun wafat.",
      },
      {
        type: "calcExercise",
        prompt: "Marx menetap di London sejak 1849 sampai wafat pada 1883. Berapa lama ia tinggal di London?",
        answer: 34,
        suffix: " tahun",
        solution: "1883 - 1849 = 34 tahun.",
        hint: "Selisih tahun menetap dan tahun wafat.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tiap peristiwa atau tempat dengan keterangan yang tepat.",
        pairs: [
          { left: "Trier", right: "Kota kelahiran Marx (1818)" },
          { left: "Rheinische Zeitung", right: "Surat kabar Marx yang dibredel 1843" },
          { left: "Manchester", right: "Lokasi pabrik keluarga Engels" },
          { left: "British Museum", right: "Tempat Marx meriset Das Kapital" },
          { left: "Highgate", right: "Pemakaman Marx di London" },
          { left: "Internasional Pertama", right: "Asosiasi pekerja yang berdiri 1864" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Marx lahir di Trier (1818), belajar hukum dan filsafat, lalu menjadi jurnalis.",
          "Rheinische Zeitung dibredel 1843, memulai hidupnya dalam pengasingan: Paris, Brussels, London.",
          "Marx hidup miskin dan ditopang Engels yang mengelola pabrik di Manchester.",
          "Das Kapital sebagian besar diriset di ruang baca British Museum; Engels menyelesaikan jilid II dan III.",
          "Marx aktif dalam Internasional Pertama (1864), wafat 1883 dan dimakamkan di Highgate, London.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Di kota mana Karl Marx dilahirkan pada 1818?",
            options: ["London", "Trier", "Manchester", "Brussels"],
            answer: 1,
            explain: "Marx lahir di Trier, Jerman, pada 1818.",
          },
          {
            q: "Surat kabar yang dipimpin Marx dan kemudian dibredel pemerintah bernama?",
            options: ["Rheinische Zeitung", "Das Kapital", "Manifesto", "British Times"],
            answer: 0,
            explain: "Rheinische Zeitung dibredel pada 1843, memicu pengasingan Marx.",
          },
          {
            q: "Bagaimana Engels menopang Marx selama bertahun-tahun?",
            options: ["Dengan jabatan pemerintah", "Dengan laba pabrik keluarga di Manchester", "Dengan warisan kerajaan", "Dengan hasil pertanian"],
            answer: 1,
            explain: "Engels mengelola pabrik tekstil keluarga di Manchester dan mengirim uang ke Marx.",
          },
          {
            q: "Apa kontribusi Engels setelah Marx wafat?",
            options: ["Menulis Manifesto sendirian", "Menyelesaikan jilid II dan III Das Kapital", "Mendirikan Uni Soviet", "Membredel surat kabar"],
            answer: 1,
            explain: "Engels menyunting dan menyelesaikan jilid II dan III Das Kapital dari catatan Marx.",
          },
          {
            q: "Organisasi pekerja lintas negara tempat Marx aktif, yang berdiri 1864, adalah?",
            options: ["Liga Komunis", "Internasional Pertama", "Komintern", "Serikat Manchester"],
            answer: 1,
            explain: "Asosiasi Pekerja Internasional atau Internasional Pertama berdiri di London pada 1864.",
          },
        ],
      },
    ],
  },
];
