import type { Lesson } from "../../../types";

export const level11: Lesson[] = [
  // ============================================================
  {
    id: "manajemen-risiko-perdagangan",
    levelId: "risiko",
    order: 1,
    title: "Manajemen Risiko & Pelanggaran Perdagangan",
    summary: "Mengenali bentuk fraud seperti under-valuation dan misclassification, serta cara mencegahnya secara legal.",
    durationMin: 13,
    tags: ["risiko", "fraud", "under-valuation", "smuggling"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebagian pelaku mencoba menekan bea dengan cara melanggar hukum. Memahami bentuk-bentuk <strong>pelanggaran</strong> ini penting bukan untuk menirunya, melainkan agar bisnis Anda tidak terjebak, baik sengaja maupun karena kelalaian mitra.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bentuk pelanggaran umum",
        html: "<strong>Under-valuation</strong>: menurunkan nilai barang agar bea kecil. <strong>Misclassification</strong>: memakai HS Code bertarif rendah yang salah. <strong>Smuggling</strong>: menyelundupkan tanpa pemberitahuan. Semuanya berisiko sanksi berat hingga pidana.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Risiko pihak berelasi",
        html: "Transaksi dengan <strong>related party</strong> (perusahaan satu grup) diawasi ketat karena harga bisa diatur tidak wajar. Importir wajib membuktikan harga tetap wajar (arm's length).",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tingkat Risiko Sanksi per Jenis Pelanggaran (ilustrasi)",
        unit: "skor risiko",
        source: "ilustrasi edukatif",
        note: "Penyelundupan paling berat karena bisa berujung pidana, bukan sekadar denda.",
        data: [
          { label: "Under-valuation", value: 60, color: "#f59e0b" },
          { label: "Misclassification", value: 55, color: "#fb923c" },
          { label: "Smuggling", value: 95, color: "#ef4444" },
          { label: "Dokumen palsu", value: 90, color: "#dc2626" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Diskon yang berubah jadi denda",
        html: "Importir 'menghemat' bea dengan meminta supplier menulis nilai invoice 30% lebih rendah dari nilai sebenarnya. Saat audit, selisih ketahuan dari pembayaran bank yang tidak cocok. Selain menagih kekurangan bea, otoritas mengenakan sanksi administrasi berlipat. 'Penghematan' itu akhirnya jauh lebih mahal.",
      },
      {
        type: "calcExercise",
        prompt: "Nilai sebenarnya Rp1 miliar di-under-value 30%. Berapa nilai yang disembunyikan (Rp)?",
        answer: 300000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Nilai disembunyikan = 30% x Rp1 miliar = <strong>Rp300 juta</strong>, menjadi dasar tagihan bea dan sanksi saat ketahuan.",
        hint: "Kalikan persentase under-value dengan nilai sebenarnya.",
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini legal (mitigasi risiko) atau ilegal (pelanggaran)?",
        buckets: ["Legal", "Ilegal"],
        items: [
          { text: "Memanfaatkan tarif preferensi FTA dengan COO sah", bucket: "Legal" },
          { text: "Menurunkan nilai invoice agar bea kecil", bucket: "Ilegal" },
          { text: "Klasifikasi HS yang benar walau tarif tinggi", bucket: "Legal" },
          { text: "Memecah kiriman untuk menghindari pemeriksaan", bucket: "Ilegal" },
        ],
      },
      {
        type: "video",
        comp: "RisikoPelanggaranVideo",
        title: "Anatomi Pelanggaran: Under-valuation, Misclassification, Smuggling",
        caption: "Visualisasi bagaimana tiga modus pelanggaran terbentuk dan terdeteksi saat audit.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Temuan Pelanggaran Kepabeanan (ilustrasi)",
        unit: "% temuan",
        source: "ilustrasi edukatif",
        note: "Under-valuation paling sering ditemukan karena relatif mudah dilakukan namun mudah terlacak lewat data pembayaran.",
        data: [
          { label: "Under-valuation", value: 42, color: "#f59e0b" },
          { label: "Misclassification", value: 28, color: "#fb923c" },
          { label: "Smuggling", value: 18, color: "#ef4444" },
          { label: "Dokumen palsu", value: 12, color: "#dc2626" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan istilah pelanggaran dengan definisinya.",
        pairs: [
          { left: "Under-valuation", right: "Menurunkan nilai barang agar bea kecil" },
          { left: "Misclassification", right: "Memakai HS Code bertarif rendah yang salah" },
          { left: "Smuggling", right: "Memasukkan barang tanpa pemberitahuan pabean" },
          { left: "Related party", right: "Transaksi antar perusahaan satu grup" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Akal-akalan asal barang di perang dagang",
        html: "Ketika Amerika Serikat menaikkan tarif atas barang China sejak <strong>2018</strong>, sebagian pihak mencoba mengelabui dengan <strong>transshipment</strong>, yaitu mengirim barang lewat negara ketiga lalu memalsukan negara asalnya agar lolos tarif tinggi. Praktik memanipulasi asal dan klasifikasi ini adalah bentuk pelanggaran yang justru memicu pengawasan lebih ketat. Sejarah menunjukkan tarif tinggi sering menggoda orang menempuh jalan curang yang berisiko sanksi berat.",
      },
      {
        type: "takeaways",
        items: [
          "Under-valuation, misclassification, dan smuggling adalah pelanggaran berisiko tinggi.",
          "Transaksi pihak berelasi diawasi ketat soal kewajaran harga.",
          "Penyelundupan dapat berujung pidana, bukan sekadar denda.",
          "Mitigasi risiko yang sah: dokumen benar dan memanfaatkan fasilitas resmi.",
          "Penghematan ilegal hampir selalu lebih mahal saat ketahuan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Under-valuation adalah?",
            options: ["Menaikkan nilai barang", "Menurunkan nilai barang agar bea kecil", "Salah negara asal", "Asuransi ganda"],
            answer: 1,
            explain: "Under-valuation menurunkan nilai barang secara tidak benar agar bea lebih kecil.",
          },
          {
            q: "Misclassification berarti?",
            options: [
              "Memakai HS Code yang salah untuk tarif lebih rendah",
              "Salah nama kapal",
              "Telat bayar",
              "Salah mata uang",
            ],
            answer: 0,
            explain: "Misclassification adalah menyalahgunakan klasifikasi HS demi tarif rendah.",
          },
          {
            q: "Mengapa transaksi related party diawasi ketat?",
            options: ["Selalu ilegal", "Harga bisa diatur tidak wajar", "Tidak kena pajak", "Bebas dokumen"],
            answer: 1,
            explain: "Harga antar perusahaan satu grup bisa diatur, sehingga kewajarannya diuji.",
          },
          {
            q: "Pelanggaran dengan risiko paling berat (bisa pidana)?",
            options: ["Telat lapor", "Smuggling/penyelundupan", "Salah ketik", "Pakai FTA"],
            answer: 1,
            explain: "Penyelundupan dapat berujung sanksi pidana, bukan sekadar denda.",
          },
          {
            q: "Nilai Rp2 miliar di-under-value 25%. Nilai disembunyikan?",
            options: ["Rp500 juta", "Rp250 juta", "Rp50 juta", "Rp2 miliar"],
            answer: 0,
            explain: "25% x Rp2 miliar = Rp500 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mitigasi-risiko",
    levelId: "risiko",
    order: 2,
    title: "Strategi Mitigasi Risiko Pabean yang Legal",
    summary: "Mengurangi risiko sanksi secara sah: verifikasi HS, dokumentasi nilai pabean, vetting supplier, dan memanfaatkan ruling.",
    durationMin: 13,
    tags: ["mitigasi risiko", "HS classification", "ruling", "due diligence"],
    blocks: [
      {
        type: "paragraph",
        html: "Risiko pabean tidak harus dihadapi dengan cara melanggar hukum. Justru strategi <strong>mitigasi yang legal</strong> menekan risiko sekaligus melindungi bisnis. Intinya: pastikan klasifikasi dan nilai benar sejak awal, dokumentasikan dengan rapi, dan minta kepastian resmi bila ragu.",
      },
      {
        type: "paragraph",
        html: "Bandingkan dua jalan saat menghadapi tarif tinggi: jalan ilegal (menurunkan nilai, memalsukan HS) memberi 'hemat' sesaat tetapi berisiko denda berlipat hingga pidana. Jalan legal (verifikasi HS, manfaatkan FTA, minta ruling) memberi kepastian biaya tanpa risiko sanksi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat strategi mitigasi legal",
        html: "<strong>Verifikasi HS di muka</strong>: klasifikasikan barang dengan benar sebelum impor. <strong>Dokumentasi nilai pabean</strong>: catat semua komponen (termasuk royalti dan freight) sesuai fakta. <strong>Vetting supplier</strong>: pastikan mitra patuh dan dokumennya sahih. <strong>Manfaatkan ruling</strong>: minta penetapan resmi agar tidak ada sengketa kemudian.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Ruling memberi kepastian hukum",
        html: "Jika ragu atas klasifikasi atau nilai, importir bisa meminta <strong>penetapan/ruling</strong> resmi (mis. penetapan klasifikasi sebelum impor). Keputusan tertulis ini menjadi pegangan yang sah dan mencegah koreksi mendadak saat audit.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hemat ilegal selalu lebih mahal",
        html: "Under-value atau misclassification mungkin menghemat bea hari ini, tetapi saat ketahuan, tagihan kekurangan ditambah sanksi administrasi bisa berlipat dari 'penghematan' awal, dan reputasi rusak. Mitigasi legal adalah investasi, bukan biaya.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Total Biaya: Mitigasi Legal vs Jalan Ilegal Saat Ketahuan (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Mitigasi legal biayanya kecil dan pasti; jalan ilegal membengkak karena denda saat audit.",
        data: [
          { label: "Mitigasi legal (verifikasi + ruling)", value: 15, color: "#22c55e" },
          { label: "Bea benar yang seharusnya", value: 100, color: "#0ea5e9" },
          { label: "Jalan ilegal saat ketahuan", value: 200, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Ruling klasifikasi menyelamatkan margin",
        html: "Importir ragu apakah komponennya kena tarif 5% atau 15%. Alih-alih menebak rendah, ia meminta <strong>penetapan klasifikasi</strong> resmi. Ternyata tarif yang benar 5%. Dengan ruling tertulis, ia membayar Bea Masuk yang pasti dan kebal koreksi audit. Atas CIF Rp1 miliar, kepastian ini menghindari risiko tagihan selisih 10% = Rp100 juta plus sanksi seandainya ia salah menebak tarif tinggi sebagai rendah.",
      },
      {
        type: "calcExercise",
        prompt: "CIF Rp1 miliar. Importir keliru menebak tarif 5% padahal seharusnya 15%. Berapa kekurangan bea masuk yang bisa ditagih saat audit?",
        answer: 100000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Selisih tarif = 15% - 5% = 10%. Kekurangan = 10% x Rp1 miliar = <strong>Rp100 juta</strong>, belum termasuk sanksi. Ruling di muka mencegah risiko ini.",
        hint: "Kalikan selisih tarif (15% - 5%) dengan nilai CIF.",
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini mitigasi risiko yang legal atau jalan pintas ilegal?",
        buckets: ["Mitigasi legal", "Jalan pintas ilegal"],
        items: [
          { text: "Meminta ruling klasifikasi sebelum impor", bucket: "Mitigasi legal" },
          { text: "Menulis nilai invoice lebih rendah dari sebenarnya", bucket: "Jalan pintas ilegal" },
          { text: "Mendokumentasikan royalti dalam nilai pabean", bucket: "Mitigasi legal" },
          { text: "Memakai HS Code salah agar tarif rendah", bucket: "Jalan pintas ilegal" },
          { text: "Vetting legalitas dan dokumen supplier", bucket: "Mitigasi legal" },
        ],
      },
      {
        type: "widget",
        widget: "KalkulatorSanksiPabean",
      },
      {
        type: "chart",
        variant: "line",
        title: "Eskalasi Biaya Jalan Ilegal Seiring Waktu hingga Audit (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Selisih bea yang 'dihemat' tetap, tetapi sanksi dan bunga menumpuk hingga audit menemukannya.",
        data: [
          { label: "Tahun 0 (saat impor)", value: 0, color: "#22c55e" },
          { label: "Tahun 1", value: 50, color: "#f59e0b" },
          { label: "Tahun 2", value: 120, color: "#fb923c" },
          { label: "Tahun 3 (audit)", value: 200, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Importir 'hemat' Bea Masuk Rp80 juta lewat under-valuation. Saat audit, dikenakan sanksi administrasi 200% dari kekurangan bea. Berapa total yang harus dibayar (kekurangan bea + sanksi) dalam Rp?",
        answer: 240000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Kekurangan bea = Rp80 juta. Sanksi = 200% x Rp80 juta = Rp160 juta. Total = Rp80 juta + Rp160 juta = <strong>Rp240 juta</strong>, tiga kali lipat 'penghematan'.",
        hint: "Jumlahkan kekurangan bea dengan sanksi (200% x kekurangan).",
      },
      {
        type: "case",
        title: "Sejarah: WTO dan aturan nilai pabean yang transparan",
        html: "Sebelum ada aturan baku, otoritas bisa menetapkan nilai pabean secara sepihak sehingga importir tidak punya kepastian. Lewat <strong>WTO Customs Valuation Agreement</strong> yang berlaku sejak era <strong>WTO 1995</strong>, dunia menyepakati <strong>nilai transaksi</strong> sebagai dasar utama yang objektif. Kerangka inilah yang memungkinkan mitigasi legal: mendokumentasikan nilai dengan benar dan meminta penetapan resmi bila ragu.",
      },
      {
        type: "takeaways",
        items: [
          "Mitigasi risiko yang legal menekan sanksi tanpa melanggar hukum.",
          "Verifikasi HS dan dokumentasi nilai pabean yang benar sejak awal adalah kunci.",
          "Vetting supplier mencegah risiko mitra menular ke perusahaan Anda.",
          "Ruling resmi memberi kepastian hukum dan kebal koreksi audit.",
          "Hemat ilegal hampir selalu lebih mahal saat ketahuan, plus reputasi rusak.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Strategi mitigasi risiko pabean yang legal adalah?",
            options: ["Menurunkan nilai invoice", "Verifikasi HS dan dokumentasi nilai yang benar di muka", "Memecah kiriman agar lolos pemeriksaan", "Memakai dokumen palsu"],
            answer: 1,
            explain: "Mitigasi legal berarti memastikan klasifikasi dan nilai benar sejak awal, bukan memanipulasi.",
          },
          {
            q: "Apa fungsi ruling/penetapan klasifikasi resmi?",
            options: ["Menghapus seluruh bea", "Memberi kepastian hukum agar kebal koreksi audit", "Mempercepat kapal", "Mengganti PPN"],
            answer: 1,
            explain: "Ruling adalah keputusan resmi yang menjadi pegangan sah dan mencegah sengketa kemudian.",
          },
          {
            q: "Mengapa vetting supplier penting untuk mitigasi risiko?",
            options: ["Agar harga naik", "Agar risiko mitra yang tidak patuh tidak menular ke perusahaan", "Agar bebas dokumen", "Agar tidak perlu ekspor"],
            answer: 1,
            explain: "Supplier bermasalah bisa menyeret importir, sehingga legalitas mitra perlu diperiksa.",
          },
          {
            q: "Manakah jalan pintas ilegal, bukan mitigasi?",
            options: ["Meminta ruling", "Mendokumentasikan freight dan royalti", "Menulis nilai invoice lebih rendah dari sebenarnya", "Memanfaatkan tarif FTA dengan COO sah"],
            answer: 2,
            explain: "Menurunkan nilai invoice adalah under-valuation, sebuah pelanggaran, bukan mitigasi legal.",
          },
          {
            q: "CIF Rp2 miliar, tarif benar 20% tapi ditebak 10%. Kekurangan bea saat audit?",
            options: ["Rp200 juta", "Rp100 juta", "Rp400 juta", "Rp20 juta"],
            answer: 0,
            explain: "Selisih tarif 10% x Rp2 miliar = Rp200 juta.",
          },
        ],
      },
    ],
  },
];
