import type { Lesson } from "../../../types";

export const level9: Lesson[] = [
  // ============================================================
  {
    id: "pajak-impor",
    levelId: "perpajakan",
    order: 1,
    title: "Perpajakan Impor: Bea Masuk, PPN & PPh 22",
    summary: "Menghitung total pungutan negara atas barang impor sampai jadi landed cost. Dengan video & kalkulator.",
    durationMin: 15,
    tags: ["bea masuk", "PPN impor", "PPh 22", "landed cost"],
    blocks: [
      {
        type: "paragraph",
        html: "Harga barang dari supplier bukanlah biaya akhir. Saat masuk Indonesia, ada tiga pungutan utama: <strong>Bea Masuk</strong>, <strong>PPN Impor</strong>, dan <strong>PPh Pasal 22 Impor</strong>. Menjumlahkan semuanya menghasilkan <strong>landed cost</strong>, yaitu biaya barang siap di gudang.",
      },
      {
        type: "video",
        comp: "PungutanImpor",
        title: "Video: Pungutan Impor Menumpuk",
        caption: "Animasi bagaimana bea masuk, PPN, dan PPh menumpuk di atas nilai pabean.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Urutan perhitungan",
        html: "1) <strong>Nilai pabean (CIF)</strong> = harga barang + freight + asuransi. 2) <strong>Bea Masuk</strong> = tarif x CIF. 3) Dasar pajak = CIF + Bea Masuk. 4) <strong>PPN</strong> = 11% x dasar pajak. 5) <strong>PPh 22</strong> = tarif x dasar pajak.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Punya API menurunkan PPh 22",
        html: "Importir dengan <strong>API</strong> (Angka Pengenal Impor) umumnya dikenakan PPh 22 tarif lebih rendah (2,5%) dibanding yang tidak punya (7,5%). Status importir memengaruhi biaya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan nilai barang, freight, asuransi, dan tarif bea masuk untuk melihat rincian pungutan dan total landed cost.",
      },
      { type: "widget", widget: "KalkulatorLandedCost" },
      {
        type: "case",
        title: "Studi Kasus: Hitung pungutan satu pengapalan",
        html: "Nilai pabean (CIF) Rp100 juta, bea masuk 10%. Bea Masuk = Rp10 juta. Dasar pajak = Rp110 juta. PPN 11% = Rp12,1 juta. PPh 22 (punya API, 2,5%) = Rp2,75 juta. <strong>Total pungutan = Rp24,85 juta</strong>, sehingga landed cost = Rp124,85 juta. Banyak importir pemula lupa pungutan ini dan salah menetapkan harga jual.",
      },
      {
        type: "calcExercise",
        prompt: "CIF Rp100 juta, bea masuk 10%. Berapa nilai Bea Masuk?",
        answer: 10000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Bea Masuk = 10% x Rp100 juta = <strong>Rp10 juta</strong>. Ini menjadi bagian dari dasar pengenaan PPN dan PPh.",
        hint: "Kalikan tarif bea masuk dengan nilai pabean (CIF).",
      },
      {
        type: "classifyExercise",
        prompt: "Komponen ini termasuk pembentuk nilai pabean (CIF) atau pungutan negara?",
        buckets: ["Pembentuk CIF", "Pungutan negara"],
        items: [
          { text: "Harga barang (FOB)", bucket: "Pembentuk CIF" },
          { text: "Freight (ongkos angkut)", bucket: "Pembentuk CIF" },
          { text: "Bea Masuk", bucket: "Pungutan negara" },
          { text: "PPN Impor 11%", bucket: "Pungutan negara" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Landed Cost Satu Pengapalan (CIF Rp100 juta, BM 10%)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Total landed cost Rp124,85 juta: CIF Rp100 juta plus pungutan Rp24,85 juta.",
        data: [
          { label: "Nilai pabean (CIF)", value: 100, color: "#0ea5e9" },
          { label: "Bea Masuk 10%", value: 10, color: "#ef4444" },
          { label: "PPN Impor 11%", value: 12.1, color: "#f59e0b" },
          { label: "PPh 22 (API 2,5%)", value: 2.75, color: "#22c55e" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Lanjutan kasus: CIF Rp100 juta, total pungutan Rp24,85 juta. Berapa landed cost barang siap di gudang?",
        answer: 124850000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Landed cost = CIF + seluruh pungutan = Rp100 juta + Rp24,85 juta = <strong>Rp124,85 juta</strong>. Inilah dasar menetapkan harga jual.",
        hint: "Jumlahkan nilai pabean (CIF) dengan total pungutan negara.",
      },
      {
        type: "calcExercise",
        prompt: "Jika importir TIDAK punya API, PPh 22 menjadi 7,5%. Dasar pajak Rp110 juta. Berapa PPh 22 yang terutang?",
        answer: 8250000,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPh 22 = 7,5% x Rp110 juta = <strong>Rp8,25 juta</strong>. Bandingkan dengan Rp2,75 juta bila punya API; selisihnya Rp5,5 juta.",
        hint: "Kalikan tarif 7,5% dengan dasar pajak (CIF + Bea Masuk).",
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan komponen perhitungan dengan rumus atau nilainya (kasus CIF Rp100 juta, BM 10%).",
        pairs: [
          { left: "Nilai pabean (CIF)", right: "Harga barang + freight + asuransi" },
          { left: "Bea Masuk", right: "Tarif x CIF = Rp10 juta" },
          { left: "Dasar pajak", right: "CIF + Bea Masuk = Rp110 juta" },
          { left: "PPN Impor", right: "11% x dasar pajak = Rp12,1 juta" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Perang dagang AS-China dan beban tarif",
        html: "Sejak <strong>2018</strong>, Amerika Serikat dan China saling menaikkan <strong>tarif</strong> atas ratusan miliar dolar barang dalam sebuah perang dagang. Kenaikan bea masuk itu langsung menambah <strong>landed cost</strong> dan akhirnya ditanggung konsumen lewat harga yang lebih tinggi. Kasus ini menegaskan bahwa bea masuk dan pajak impor bukan angka di atas kertas, melainkan biaya nyata yang membentuk harga jual.",
      },
      {
        type: "takeaways",
        items: [
          "Pungutan impor utama: Bea Masuk, PPN Impor, dan PPh Pasal 22.",
          "Nilai pabean (CIF) = harga barang + freight + asuransi.",
          "PPN dan PPh dihitung dari CIF ditambah Bea Masuk.",
          "Punya API menurunkan tarif PPh 22.",
          "Landed cost = CIF + seluruh pungutan, dasar penetapan harga jual.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Nilai pabean impor dihitung dari?",
            options: ["Harga jual eceran", "Harga barang + freight + asuransi (CIF)", "Hanya harga barang", "Biaya gudang"],
            answer: 1,
            explain: "Nilai pabean memakai CIF: harga barang ditambah freight dan asuransi.",
          },
          {
            q: "PPN Impor di Indonesia sebesar?",
            options: ["10%", "11%", "5%", "2,5%"],
            answer: 1,
            explain: "Tarif PPN saat ini 11%, dikenakan atas dasar CIF + Bea Masuk.",
          },
          {
            q: "Dasar pengenaan PPN dan PPh impor adalah?",
            options: ["CIF saja", "CIF + Bea Masuk", "Harga FOB", "Freight"],
            answer: 1,
            explain: "Dasar pajak impor adalah nilai pabean (CIF) ditambah Bea Masuk.",
          },
          {
            q: "Importir dengan API biasanya kena PPh 22 sebesar?",
            options: ["2,5%", "7,5%", "11%", "15%"],
            answer: 0,
            explain: "Punya API umumnya dikenakan PPh 22 tarif lebih rendah, 2,5%.",
          },
          {
            q: "CIF Rp200 juta, bea masuk 5%. Bea Masuk?",
            options: ["Rp10 juta", "Rp20 juta", "Rp5 juta", "Rp1 juta"],
            answer: 0,
            explain: "5% x Rp200 juta = Rp10 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "fasilitas-fiskal",
    levelId: "perpajakan",
    order: 2,
    title: "Fasilitas Fiskal: KITE, Kawasan Berikat, KEK & FTZ",
    summary: "Memahami fasilitas penangguhan dan pembebasan bea masuk untuk eksportir, serta kapan tiap fasilitas dipakai.",
    durationMin: 13,
    tags: ["KITE", "kawasan berikat", "KEK", "free trade zone", "fasilitas fiskal"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi eksportir, membayar bea masuk dan pajak impor penuh atas bahan baku bisa menggerus daya saing. Pemerintah menyediakan <strong>fasilitas fiskal</strong> yang menangguhkan atau membebaskan pungutan impor, asalkan barang diolah lalu diekspor kembali. Empat yang utama: <strong>KITE</strong>, <strong>Kawasan Berikat</strong>, <strong>KEK</strong>, dan <strong>Free Trade Zone</strong>.",
      },
      {
        type: "paragraph",
        html: "Logikanya sederhana: jika hasil akhirnya diekspor, negara tidak ingin pungutan impor menjadi beban yang menempel pada produk ekspor. Maka bea masuk dan PDRI (Pajak Dalam Rangka Impor) atas bahan baku ditangguhkan atau dibebaskan, sehingga harga pokok produk ekspor lebih bersaing.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat fasilitas utama",
        html: "<strong>KITE</strong> (Kemudahan Impor Tujuan Ekspor): pembebasan atau pengembalian bea masuk atas bahan baku yang diolah lalu diekspor. <strong>Kawasan Berikat</strong>: kawasan pabean tempat impor bahan baku ditangguhkan sampai produk jadi keluar. <strong>KEK</strong> (Kawasan Ekonomi Khusus): kawasan dengan paket insentif fiskal luas. <strong>FTZ</strong> (Free Trade Zone, mis. Batam): kawasan bebas bea masuk dan PPN.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Penangguhan vs pembebasan",
        html: "<strong>Penangguhan</strong> berarti pungutan ditunda, baru wajib dibayar jika barang dijual ke dalam negeri (Tempat Lain Dalam Daerah Pabean). <strong>Pembebasan</strong> berarti pungutan tidak ditagih sama sekali sepanjang syarat ekspor terpenuhi. Salah paham di sini bisa membuat arus kas keliru.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Fasilitas menuntut administrasi ketat",
        html: "Semua fasilitas mensyaratkan pencatatan bahan baku, proses, dan hasil ekspor yang rapi (IT Inventory). Jika ada selisih atau barang fasilitas bocor ke pasar domestik tanpa membayar, otoritas akan menagih pungutan plus sanksi.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Landed Cost Bahan Baku: Tanpa vs Dengan Fasilitas (ilustrasi)",
        unit: "Rp juta per pengapalan",
        source: "ilustrasi edukatif",
        note: "Dengan fasilitas, bea masuk dan PDRI ditangguhkan sehingga biaya bahan baku ekspor jauh lebih ringan.",
        data: [
          { label: "Tanpa fasilitas", value: 125, color: "#ef4444" },
          { label: "Dengan KITE/Berikat", value: 100, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik garmen masuk Kawasan Berikat",
        html: "Sebuah pabrik garmen mengimpor kain CIF Rp100 juta dengan bea masuk 10%. Tanpa fasilitas, ia membayar Bea Masuk Rp10 juta, PPN Rp12,1 juta, dan PPh 22 (2,5%) Rp2,75 juta, total pungutan Rp24,85 juta. Setelah masuk <strong>Kawasan Berikat</strong>, seluruh pungutan itu ditangguhkan karena kain akan diolah jadi pakaian yang diekspor. Arus kas Rp24,85 juta per pengapalan tidak lagi tertahan di kas negara.",
      },
      {
        type: "calcExercise",
        prompt: "CIF kain Rp100 juta, bea masuk 10%, PPN 11%, PPh 22 2,5%. Berapa total pungutan yang ditangguhkan oleh fasilitas Kawasan Berikat?",
        answer: 24850000,
        tolerance: 100000,
        prefix: "Rp",
        solution: "Bea Masuk = Rp10 juta. Dasar pajak = Rp110 juta. PPN 11% = Rp12,1 juta. PPh 22 2,5% = Rp2,75 juta. Total = <strong>Rp24,85 juta</strong> yang ditangguhkan selama bahan diolah untuk ekspor.",
        hint: "Jumlahkan Bea Masuk + PPN + PPh 22 seperti pada lesson landed cost.",
      },
      {
        type: "classifyExercise",
        prompt: "Cocokkan ciri ini dengan fasilitas yang paling tepat.",
        buckets: ["KITE", "Kawasan Berikat", "KEK / FTZ"],
        items: [
          { text: "Pembebasan/pengembalian bea atas bahan baku tujuan ekspor", bucket: "KITE" },
          { text: "Kawasan pabean tempat impor ditangguhkan sampai produk keluar", bucket: "Kawasan Berikat" },
          { text: "Kawasan dengan paket insentif luas, mis. Batam dan KEK", bucket: "KEK / FTZ" },
          { text: "Cocok untuk eksportir tanpa membangun kawasan khusus", bucket: "KITE" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah nilai CIF, tarif bea masuk, dan jumlah pengapalan untuk melihat berapa arus kas yang ditangguhkan saat memakai KITE atau Kawasan Berikat.",
      },
      { type: "widget", widget: "SimulatorFasilitasFiskal" },
      {
        type: "chart",
        variant: "area",
        title: "Arus Kas Tertahan yang Ditangguhkan secara Kumulatif (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Tiap pengapalan menangguhkan Rp24,85 juta; setelah 4 pengapalan total Rp99,4 juta tidak tertahan di kas negara.",
        data: [
          { label: "Pengapalan 1", value: 24.85, color: "#22c55e" },
          { label: "Pengapalan 2", value: 49.7, color: "#22c55e" },
          { label: "Pengapalan 3", value: 74.55, color: "#22c55e" },
          { label: "Pengapalan 4", value: 99.4, color: "#22c55e" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Tiap pengapalan menangguhkan Rp24,85 juta. Berapa total arus kas yang ditangguhkan setelah 4 pengapalan?",
        answer: 99400000,
        tolerance: 0,
        prefix: "Rp",
        solution: "4 x Rp24,85 juta = <strong>Rp99,4 juta</strong> yang tidak tertahan di kas negara selama bahan baku diolah untuk ekspor.",
        hint: "Kalikan nilai per pengapalan dengan jumlah pengapalan.",
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan istilah fasilitas fiskal dengan pengertiannya.",
        pairs: [
          { left: "Penangguhan", right: "Pungutan ditunda, ditagih bila barang dijual domestik" },
          { left: "Pembebasan", right: "Pungutan tidak ditagih sepanjang syarat ekspor terpenuhi" },
          { left: "IT Inventory", right: "Sistem pencatatan bahan baku dan hasil produksi" },
          { left: "TLDDP", right: "Tempat Lain Dalam Daerah Pabean (pasar domestik)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Hilirisasi nikel dan insentif kawasan",
        html: "Untuk mendorong pengolahan di dalam negeri, Indonesia melarang ekspor bijih <strong>nikel mentah</strong> sejak <strong>2020</strong> dan menggenjot pembangunan smelter. Banyak smelter dibangun di <strong>Kawasan Ekonomi Khusus</strong> yang menawarkan insentif fiskal seperti penangguhan dan pembebasan bea masuk atas mesin serta bahan baku. Fasilitas inilah yang membuat investasi pengolahan menjadi lebih ekonomis.",
      },
      {
        type: "takeaways",
        items: [
          "Fasilitas fiskal menangguhkan atau membebaskan pungutan impor bahan baku tujuan ekspor.",
          "KITE memberi pembebasan atau pengembalian bea masuk untuk eksportir.",
          "Kawasan Berikat dan KEK/FTZ adalah kawasan dengan perlakuan pabean khusus.",
          "Penangguhan menunda pungutan; pembebasan menghapusnya sepanjang syarat ekspor terpenuhi.",
          "Fasilitas menuntut IT Inventory dan administrasi ketat agar tidak kena sanksi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama fasilitas fiskal seperti KITE adalah?",
            options: ["Menaikkan bea masuk", "Membuat produk ekspor lebih bersaing dengan menangguhkan/membebaskan pungutan", "Menghindari pajak penghasilan badan", "Mempercepat impor barang konsumsi"],
            answer: 1,
            explain: "Fasilitas meringankan pungutan impor bahan baku agar harga pokok produk ekspor lebih kompetitif.",
          },
          {
            q: "KITE adalah singkatan dari?",
            options: ["Kawasan Industri Terpadu Ekspor", "Kemudahan Impor Tujuan Ekspor", "Komite Impor Tarif Ekonomi", "Kredit Insentif Tarif Ekspor"],
            answer: 1,
            explain: "KITE adalah Kemudahan Impor Tujuan Ekspor: pembebasan atau pengembalian bea masuk untuk bahan baku yang diekspor.",
          },
          {
            q: "Pada Kawasan Berikat, pungutan impor bahan baku?",
            options: ["Dibayar penuh di muka", "Ditangguhkan sampai produk keluar/dijual domestik", "Selalu dihapus tanpa syarat", "Diganti pajak daerah"],
            answer: 1,
            explain: "Di Kawasan Berikat pungutan ditangguhkan, baru ditagih bila barang dijual ke dalam negeri.",
          },
          {
            q: "Contoh Free Trade Zone di Indonesia adalah?",
            options: ["Jakarta Pusat", "Batam", "Bandung", "Yogyakarta"],
            answer: 1,
            explain: "Batam termasuk kawasan bebas (FTZ) dengan pembebasan bea masuk dan PPN.",
          },
          {
            q: "Risiko utama saat memakai fasilitas fiskal?",
            options: ["Tarif PPN naik otomatis", "Barang fasilitas bocor ke domestik tanpa bayar lalu kena tagihan plus sanksi", "Tidak boleh ekspor", "Wajib lapor harian ke bank"],
            answer: 1,
            explain: "Jika barang fasilitas dijual domestik tanpa melunasi pungutan, otoritas menagih kembali plus sanksi.",
          },
        ],
      },
    ],
  },
];
