import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "logistik-internasional",
    levelId: "logistik",
    order: 1,
    title: "Logistik Internasional: FCL, LCL & Freight",
    summary: "Cara barang diangkut lintas negara, peran freight forwarder, dan biaya tersembunyi seperti demurrage.",
    durationMin: 13,
    tags: ["logistik", "freight forwarder", "FCL", "LCL"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah sepakat berdagang, barang harus benar-benar dipindahkan. Di sinilah <strong>logistik internasional</strong> bekerja: memilih moda angkut, mengatur kontainer, mengurus pelabuhan, dan menekan biaya. Mitra utamanya adalah <strong>freight forwarder</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "FCL vs LCL",
        html: "<strong>FCL</strong> (Full Container Load): satu kontainer penuh milik satu pengirim. <strong>LCL</strong> (Less than Container Load): barang beberapa pengirim digabung (konsolidasi) dalam satu kontainer. LCL hemat untuk volume kecil, FCL lebih efisien untuk volume besar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran freight forwarder",
        html: "Freight forwarder mengatur pengangkutan, dokumen, konsolidasi, dan koordinasi pelabuhan. Ia bukan pemilik kapal, tetapi 'arsitek perjalanan' barang dari pintu ke pintu.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Moda Angkut (ilustrasi)",
        unit: "skor relatif",
        source: "ilustrasi edukatif",
        note: "Laut paling murah untuk volume besar; udara tercepat tetapi termahal.",
        data: [
          { label: "Laut (biaya)", value: 20, color: "#0ea5e9" },
          { label: "Laut (kecepatan)", value: 25, color: "#38bdf8" },
          { label: "Udara (biaya)", value: 80, color: "#ef4444" },
          { label: "Udara (kecepatan)", value: 90, color: "#f87171" },
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Awas demurrage & detention",
        html: "<strong>Demurrage</strong>: denda karena kontainer terlalu lama di pelabuhan. <strong>Detention</strong>: denda karena kontainer terlambat dikembalikan ke pelayaran. Keduanya bisa membengkak diam-diam.",
      },
      {
        type: "case",
        title: "Studi Kasus: LCL vs FCL untuk UMKM",
        html: "Sebuah UMKM hanya mengimpor 8 m3 barang, jauh di bawah kapasitas kontainer 20 kaki (sekitar 28 m3). Dengan <strong>LCL</strong>, ia hanya membayar sesuai volume sehingga lebih murah daripada menyewa satu kontainer penuh. Saat volumenya nanti tumbuh melewati titik impas, barulah <strong>FCL</strong> menjadi lebih hemat.",
      },
      {
        type: "calcExercise",
        prompt: "Tarif LCL USD 45 per m3, barang 8 m3. Berapa ongkos angkut LCL (USD)?",
        answer: 360,
        tolerance: 0,
        prefix: "USD ",
        solution: "Ongkos = 8 x USD 45 = <strong>USD 360</strong>. Untuk volume kecil, LCL biasanya lebih hemat.",
        hint: "Kalikan volume dengan tarif per m3.",
      },
      {
        type: "classifyExercise",
        prompt: "Situasi ini lebih cocok dengan FCL atau LCL?",
        buckets: ["FCL (kontainer penuh)", "LCL (gabungan)"],
        items: [
          { text: "Impor 25 m3 barang sejenis", bucket: "FCL (kontainer penuh)" },
          { text: "Impor 5 m3 barang", bucket: "LCL (gabungan)" },
          { text: "Volume kecil dari banyak supplier", bucket: "LCL (gabungan)" },
          { text: "Volume besar rutin tiap bulan", bucket: "FCL (kontainer penuh)" },
        ],
      },
      {
        type: "video",
        comp: "LogistikKontainerVideo",
        title: "Video: Perjalanan Kontainer Pintu ke Pintu",
        caption: "Animasi alur barang dari gudang pengirim, konsolidasi, pelabuhan muat, kapal, hingga gudang penerima.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Masukkan volume kiriman dan bandingkan total biaya FCL versus LCL, lalu lihat di titik volume berapa FCL mulai lebih hemat.",
      },
      { type: "widget", widget: "SimulatorFCLvsLCL" },
      {
        type: "chart",
        variant: "line",
        title: "Biaya FCL vs LCL terhadap Volume (ilustrasi)",
        unit: "USD total",
        source: "ilustrasi edukatif",
        note: "LCL (USD 45/m3) lebih murah untuk volume kecil; FCL (flat USD 1.000 per kontainer 20ft) lebih hemat setelah titik impas sekitar 22 m3.",
        data: [
          { label: "5 m3", value: 225, color: "#0ea5e9" },
          { label: "10 m3", value: 450, color: "#38bdf8" },
          { label: "15 m3", value: 675, color: "#22c55e" },
          { label: "20 m3", value: 900, color: "#f59e0b" },
          { label: "25 m3 (LCL)", value: 1125, color: "#ef4444" },
          { label: "FCL 20ft (flat)", value: 1000, color: "#94a3b8" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "FCL 20ft flat USD 1.000. Tarif LCL USD 45/m3. Pada volume berapa m3 biaya LCL menyamai FCL (pembulatan ke atas)?",
        answer: 23,
        tolerance: 1,
        suffix: " m3",
        solution: "Titik impas = USD 1.000 / USD 45 = 22,2 m3, dibulatkan ke atas menjadi <strong>23 m3</strong>. Di atas titik ini FCL lebih hemat.",
        hint: "Bagi biaya flat FCL dengan tarif per m3 LCL, lalu bulatkan ke atas.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah logistik dengan definisinya.",
        pairs: [
          { left: "FCL", right: "Satu kontainer penuh milik satu pengirim" },
          { left: "LCL", right: "Konsolidasi barang beberapa pengirim" },
          { left: "Freight forwarder", right: "Pengatur pengangkutan dan dokumen" },
          { left: "Demurrage", right: "Denda kontainer terlalu lama di pelabuhan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Revolusi peti kemas dan biaya logistik",
        html: "Sebelum <strong>1956</strong>, bongkar muat dilakukan manual karung demi karung sehingga lambat dan mahal. <strong>Malcom McLean</strong> memperkenalkan <strong>peti kemas</strong> standar yang dapat dipindahkan utuh dari truk ke kapal. Standardisasi ukuran yang kelak menjadi standar ISO menekan biaya bongkar muat hingga lebih dari <strong>90%</strong> dan melahirkan konsep FCL serta LCL yang kita pakai hari ini.",
      },
      {
        type: "takeaways",
        items: [
          "Logistik internasional memindahkan barang secara efisien lintas negara.",
          "FCL untuk volume besar, LCL untuk volume kecil (konsolidasi).",
          "Freight forwarder mengatur pengangkutan dan dokumen pintu ke pintu.",
          "Angkutan laut murah tapi lambat; udara cepat tapi mahal.",
          "Demurrage dan detention adalah biaya yang harus diwaspadai.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "FCL berarti?",
            options: ["Barang gabungan banyak pengirim", "Satu kontainer penuh milik satu pengirim", "Angkutan udara", "Gudang berikat"],
            answer: 1,
            explain: "FCL (Full Container Load) adalah satu kontainer penuh milik satu pengirim.",
          },
          {
            q: "Peran freight forwarder?",
            options: ["Pemilik kapal", "Mengatur pengangkutan, dokumen, dan koordinasi", "Otoritas pabean", "Penjual barang"],
            answer: 1,
            explain: "Freight forwarder mengatur perjalanan dan dokumen barang, bukan pemilik kapal.",
          },
          {
            q: "Demurrage adalah denda karena?",
            options: [
              "Kontainer terlalu lama di pelabuhan",
              "Barang rusak",
              "Salah klasifikasi",
              "Kurs naik",
            ],
            answer: 0,
            explain: "Demurrage muncul saat kontainer terlalu lama berada di area pelabuhan.",
          },
          {
            q: "Untuk volume kecil, biasanya lebih hemat?",
            options: ["FCL", "LCL", "Charter kapal", "Air freight"],
            answer: 1,
            explain: "LCL membayar sesuai volume, lebih hemat untuk muatan kecil.",
          },
          {
            q: "Tarif LCL USD 50/m3, barang 6 m3. Ongkos?",
            options: ["USD 300", "USD 56", "USD 250", "USD 600"],
            answer: 0,
            explain: "6 x USD 50 = USD 300.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "shipping-kontainer",
    levelId: "logistik",
    order: 2,
    title: "Shipping & Kontainer: Vessel, Jadwal & Biaya",
    summary: "Memahami jenis kontainer, kapal, jadwal pelayaran, demurrage, detention, dan port charge dalam pengapalan.",
    durationMin: 13,
    tags: ["shipping", "kontainer", "demurrage", "port charge"],
    blocks: [
      {
        type: "paragraph",
        html: "Tulang punggung perdagangan global adalah <strong>pengapalan</strong> (shipping). Lebih dari 80% barang dunia bergerak lewat laut dalam kotak baja standar bernama <strong>kontainer</strong>. Memahami jenis kontainer, jadwal kapal, dan struktur biayanya membantu menekan ongkos dan menghindari denda.",
      },
      {
        type: "paragraph",
        html: "Kontainer umum berukuran <strong>20 kaki</strong> dan <strong>40 kaki</strong>, dengan varian seperti <strong>reefer</strong> (berpendingin), <strong>open top</strong>, dan <strong>flat rack</strong> untuk muatan khusus. Kapal pengangkutnya disebut <strong>vessel</strong>, yang berlayar mengikuti <strong>jadwal pelayaran</strong> tetap antar pelabuhan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Jenis kontainer utama",
        html: "<strong>Dry container</strong> 20ft dan 40ft untuk barang umum, <strong>reefer</strong> untuk barang dingin (buah, ikan, obat), <strong>open top</strong> untuk muatan tinggi, dan <strong>flat rack</strong> untuk barang besar atau berat yang tidak muat di kontainer biasa.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Vessel & jadwal pelayaran",
        html: "<strong>Vessel</strong> adalah kapal pengangkut kontainer. Pelayaran punya <strong>jadwal</strong> dengan ETD (Estimated Time of Departure) dan ETA (Estimated Time of Arrival). Cut-off adalah batas akhir kontainer masuk sebelum kapal berangkat. Telat dari cut-off berarti barang ketinggalan kapal.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tiga biaya yang mudah membengkak",
        html: "<strong>Demurrage</strong>: denda kontainer terlalu lama di pelabuhan. <strong>Detention</strong>: denda kontainer terlambat dikembalikan ke pelayaran setelah keluar pelabuhan. <strong>Port charge</strong>: biaya jasa pelabuhan seperti bongkar muat, lift on/lift off, dan penumpukan.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Struktur Biaya Pengapalan per Kontainer (ilustrasi)",
        unit: "% total biaya",
        source: "ilustrasi edukatif",
        note: "Ocean freight dominan, tetapi port charge dan potensi denda tidak boleh diabaikan.",
        data: [
          { label: "Ocean freight", value: 50, color: "#0ea5e9" },
          { label: "Port charge", value: 22, color: "#22c55e" },
          { label: "Demurrage/detention", value: 15, color: "#ef4444" },
          { label: "Dokumen & lainnya", value: 13, color: "#94a3b8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Demurrage karena dokumen telat",
        html: "Sebuah kontainer 40 kaki menginap di pelabuhan melewati masa bebas (free time) selama 5 hari karena izin impor belum selesai. Tarif <strong>demurrage</strong> USD 80 per hari. Importir membayar denda demurrage USD 400, belum termasuk port charge. Menyelesaikan dokumen sebelum kapal tiba akan menghemat biaya ini sepenuhnya.",
      },
      {
        type: "calcExercise",
        prompt: "Demurrage USD 80 per hari, kontainer telat 5 hari melewati free time. Berapa total denda (USD)?",
        answer: 400,
        tolerance: 0,
        prefix: "USD ",
        solution: "Total = 5 x USD 80 = <strong>USD 400</strong>. Menyiapkan dokumen lebih awal menghindari denda ini.",
        hint: "Kalikan jumlah hari telat dengan tarif demurrage harian.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan biaya berikut sebagai demurrage, detention, atau port charge.",
        buckets: ["Demurrage", "Detention", "Port charge"],
        items: [
          { text: "Kontainer menginap lama di terminal pelabuhan", bucket: "Demurrage" },
          { text: "Kontainer kosong telat dikembalikan ke depo pelayaran", bucket: "Detention" },
          { text: "Biaya bongkar muat dan lift on/lift off", bucket: "Port charge" },
          { text: "Biaya penumpukan di area pelabuhan", bucket: "Port charge" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan jumlah hari kontainer melewati free time dan tarif harian, lalu lihat akumulasi denda demurrage yang harus dibayar.",
      },
      { type: "widget", widget: "KalkulatorDemurrage" },
      {
        type: "chart",
        variant: "line",
        title: "Akumulasi Demurrage per Hari Keterlambatan (ilustrasi)",
        unit: "USD kumulatif",
        source: "ilustrasi edukatif",
        note: "Tarif demurrage sering bertingkat naik; di sini diasumsikan USD 80/hari datar untuk kontainer 40ft.",
        data: [
          { label: "Hari 1", value: 80, color: "#22c55e" },
          { label: "Hari 2", value: 160, color: "#84cc16" },
          { label: "Hari 3", value: 240, color: "#f59e0b" },
          { label: "Hari 4", value: 320, color: "#f97316" },
          { label: "Hari 5", value: 400, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Ocean freight USD 1.200, port charge USD 350, demurrage 4 hari x USD 80. Berapa total biaya pengapalan (USD)?",
        answer: 1870,
        tolerance: 0,
        prefix: "USD ",
        solution: "Demurrage = 4 x USD 80 = USD 320. Total = USD 1.200 + USD 350 + USD 320 = <strong>USD 1.870</strong>.",
        hint: "Hitung dulu total demurrage, lalu jumlahkan dengan freight dan port charge.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah pengapalan dengan artinya.",
        pairs: [
          { left: "ETD", right: "Perkiraan waktu kapal berangkat" },
          { left: "ETA", right: "Perkiraan waktu kapal tiba" },
          { left: "Cut-off", right: "Batas akhir kontainer masuk sebelum kapal berangkat" },
          { left: "Reefer", right: "Kontainer berpendingin" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Jalur laut, tulang punggung perdagangan",
        html: "Pelayaran sebagai tulang punggung dagang sudah berlangsung ribuan tahun, dari <strong>Jalur Sutra maritim</strong> yang menghubungkan Asia, Timur Tengah, dan Eropa. Hingga kini, lebih dari <strong>80%</strong> volume perdagangan dunia tetap diangkut lewat laut. Itulah sebabnya jadwal kapal, pelabuhan, dan biaya seperti demurrage menjadi penentu daya saing harga barang.",
      },
      {
        type: "takeaways",
        items: [
          "Sebagian besar barang dunia diangkut laut dalam kontainer standar.",
          "Kontainer umum 20ft dan 40ft, dengan varian reefer, open top, flat rack.",
          "Vessel berlayar sesuai jadwal dengan ETD, ETA, dan cut-off.",
          "Demurrage di pelabuhan, detention saat kontainer telat dikembalikan.",
          "Port charge adalah biaya jasa pelabuhan yang melekat pada tiap kontainer.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kontainer berpendingin untuk barang seperti buah dan ikan disebut?",
            options: ["Flat rack", "Reefer", "Open top", "Dry container"],
            answer: 1,
            explain: "Reefer adalah kontainer berpendingin untuk barang yang butuh suhu terjaga.",
          },
          {
            q: "Apa itu cut-off dalam jadwal pelayaran?",
            options: [
              "Waktu kapal tiba",
              "Batas akhir kontainer masuk sebelum kapal berangkat",
              "Biaya pelabuhan",
              "Denda keterlambatan",
            ],
            answer: 1,
            explain: "Cut-off adalah batas akhir kontainer harus masuk sebelum kapal berangkat.",
          },
          {
            q: "Detention adalah denda karena?",
            options: [
              "Kontainer terlalu lama di pelabuhan",
              "Kontainer telat dikembalikan ke pelayaran setelah keluar pelabuhan",
              "Barang salah klasifikasi",
              "Kurs naik",
            ],
            answer: 1,
            explain: "Detention muncul saat kontainer telat dikembalikan ke depo pelayaran.",
          },
          {
            q: "Port charge mencakup?",
            options: [
              "Tarif bea masuk",
              "Biaya jasa pelabuhan seperti bongkar muat dan penumpukan",
              "Premi asuransi",
              "Pajak ekspor",
            ],
            answer: 1,
            explain: "Port charge adalah biaya jasa pelabuhan seperti bongkar muat dan penumpukan.",
          },
          {
            q: "Demurrage USD 60/hari, telat 3 hari. Total denda?",
            options: ["USD 180", "USD 63", "USD 120", "USD 600"],
            answer: 0,
            explain: "3 x USD 60 = USD 180.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "warehousing",
    levelId: "logistik",
    order: 3,
    title: "Warehousing: Gudang Berikat & Fulfillment",
    summary: "Memahami gudang berikat, manajemen inventory, cross docking, dan fulfillment dalam rantai pasok modern.",
    durationMin: 13,
    tags: ["warehousing", "gudang berikat", "inventory", "fulfillment"],
    blocks: [
      {
        type: "paragraph",
        html: "Barang yang sudah tiba tidak selalu langsung dipakai atau dijual. Ia perlu disimpan, ditata, dan disiapkan. Inilah peran <strong>pergudangan</strong> (warehousing): menjaga barang tetap aman, terdata, dan siap bergerak ke tahap berikutnya dengan biaya seefisien mungkin.",
      },
      {
        type: "paragraph",
        html: "Dalam konteks kepabeanan, ada fasilitas khusus bernama <strong>gudang berikat</strong> (bonded warehouse), tempat barang impor dapat ditimbun dengan penangguhan bea masuk dan pajak. Selain itu ada konsep operasional seperti <strong>inventory</strong>, <strong>cross docking</strong>, dan <strong>fulfillment</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Gudang berikat (bonded warehouse)",
        html: "<strong>Gudang berikat</strong> adalah Tempat Penimbunan Berikat tempat barang impor disimpan dengan <strong>penangguhan bea masuk dan pajak</strong>. Bea baru dibayar saat barang dikeluarkan untuk diimpor. Ini membantu arus kas dan cocok untuk barang yang akan diolah atau diekspor kembali.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Cross docking vs penyimpanan",
        html: "<strong>Cross docking</strong> adalah memindahkan barang dari truk masuk langsung ke truk keluar dengan waktu simpan minimal. Berbeda dengan penyimpanan biasa, tujuannya mempercepat distribusi dan menekan biaya inventory.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Fulfillment & inventory",
        html: "<strong>Fulfillment</strong> adalah proses memenuhi pesanan: menerima, menyimpan, memetik (picking), mengemas (packing), dan mengirim ke pelanggan. <strong>Inventory</strong> yang akurat adalah jantungnya, karena stok yang salah catat menyebabkan kehabisan barang atau modal mengendap.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi Biaya Operasional Gudang (ilustrasi)",
        unit: "% biaya",
        source: "ilustrasi edukatif",
        note: "Tenaga kerja dan sewa ruang biasanya mendominasi biaya gudang.",
        data: [
          { label: "Tenaga kerja", value: 40, color: "#0ea5e9" },
          { label: "Sewa ruang", value: 30, color: "#22c55e" },
          { label: "Sistem & peralatan", value: 18, color: "#f59e0b" },
          { label: "Lainnya", value: 12, color: "#94a3b8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Gudang berikat menjaga arus kas",
        html: "Perusahaan manufaktur mengimpor bahan baku senilai Rp2 miliar dengan bea masuk dan pajak total 20% (Rp400 juta). Dengan menimbun di <strong>gudang berikat</strong>, pembayaran Rp400 juta ditangguhkan sampai bahan dikeluarkan untuk produksi. Selama bahan masih di gudang berikat, modal Rp400 juta tetap bisa dipakai untuk operasional lain.",
      },
      {
        type: "calcExercise",
        prompt: "Bahan baku Rp2 miliar, bea masuk dan pajak total 20%. Berapa nilai pungutan yang ditangguhkan di gudang berikat?",
        answer: 400000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Pungutan = 20% x Rp2 miliar = <strong>Rp400 juta</strong> yang ditangguhkan sampai barang dikeluarkan.",
        hint: "Hitung 20% dari nilai bahan baku.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan aktivitas berikut sesuai konsep pergudangan yang tepat.",
        buckets: ["Cross docking", "Fulfillment", "Gudang berikat"],
        items: [
          { text: "Barang langsung pindah dari truk masuk ke truk keluar", bucket: "Cross docking" },
          { text: "Picking dan packing pesanan pelanggan e-commerce", bucket: "Fulfillment" },
          { text: "Menimbun barang impor dengan penangguhan bea", bucket: "Gudang berikat" },
          { text: "Mengirim paket pesanan ke alamat pembeli", bucket: "Fulfillment" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Alokasi Aktivitas Tenaga Kerja Gudang (ilustrasi)",
        unit: "% waktu kerja",
        source: "ilustrasi edukatif",
        note: "Picking biasanya menyerap porsi waktu terbesar dalam operasi fulfillment.",
        data: [
          { label: "Picking", value: 45, color: "#0ea5e9" },
          { label: "Packing", value: 25, color: "#22c55e" },
          { label: "Receiving", value: 18, color: "#f59e0b" },
          { label: "Putaway & lainnya", value: 12, color: "#94a3b8" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Gudang punya 12.000 unit stok, 480 unit tercatat salah. Berapa persen akurasi inventory?",
        answer: 96,
        tolerance: 0,
        suffix: "%",
        solution: "Akurasi = (12.000 - 480) / 12.000 x 100% = 11.520 / 12.000 = <strong>96%</strong>. Target gudang sehat umumnya di atas 98%.",
        hint: "Kurangi unit salah dari total, bagi total, lalu jadikan persen.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan konsep pergudangan dengan deskripsinya.",
        pairs: [
          { left: "Gudang berikat", right: "Penangguhan bea masuk dan pajak" },
          { left: "Cross docking", right: "Waktu simpan minimal, langsung diteruskan" },
          { left: "Picking", right: "Mengambil barang sesuai pesanan" },
          { left: "Inventory", right: "Catatan stok barang di gudang" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Gudang rempah VOC di Batavia",
        html: "Pada era <strong>VOC</strong> sejak <strong>1602</strong>, rempah dari Maluku ditimbun di gudang-gudang besar di Batavia sebelum dikapalkan ke Eropa demi menjaga pasokan dan harga. Konsep menahan barang di lokasi terkendali ini sejalan dengan <strong>gudang berikat</strong> modern, tempat barang impor disimpan dengan penangguhan bea hingga siap dikeluarkan.",
      },
      {
        type: "takeaways",
        items: [
          "Warehousing menjaga barang aman, terdata, dan siap bergerak.",
          "Gudang berikat menangguhkan bea masuk dan pajak hingga barang dikeluarkan.",
          "Cross docking meminimalkan waktu simpan untuk mempercepat distribusi.",
          "Fulfillment mencakup picking, packing, dan pengiriman pesanan.",
          "Inventory yang akurat mencegah kehabisan stok dan modal mengendap.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Keunggulan utama gudang berikat?",
            options: [
              "Gratis biaya sewa",
              "Penangguhan bea masuk dan pajak",
              "Kapal lebih cepat",
              "Tidak perlu dokumen",
            ],
            answer: 1,
            explain: "Gudang berikat memungkinkan penangguhan bea masuk dan pajak hingga barang dikeluarkan.",
          },
          {
            q: "Cross docking bertujuan?",
            options: [
              "Menyimpan barang selama mungkin",
              "Meminimalkan waktu simpan dan mempercepat distribusi",
              "Menaikkan bea masuk",
              "Menambah inventory",
            ],
            answer: 1,
            explain: "Cross docking memindahkan barang dengan waktu simpan minimal untuk distribusi cepat.",
          },
          {
            q: "Yang termasuk proses fulfillment?",
            options: [
              "Menghitung tarif bea",
              "Picking, packing, dan pengiriman pesanan",
              "Menerbitkan Bill of Lading",
              "Menentukan jadwal kapal",
            ],
            answer: 1,
            explain: "Fulfillment mencakup picking, packing, dan pengiriman pesanan ke pelanggan.",
          },
          {
            q: "Mengapa inventory akurat penting?",
            options: [
              "Agar tarif preferensi turun",
              "Mencegah kehabisan stok dan modal mengendap",
              "Mempercepat kapal",
              "Menghapus bea masuk",
            ],
            answer: 1,
            explain: "Inventory akurat mencegah kehabisan barang sekaligus modal yang mengendap di stok.",
          },
          {
            q: "Barang Rp1 miliar, bea dan pajak 15%. Berapa yang ditangguhkan di gudang berikat?",
            options: ["Rp150 juta", "Rp100 juta", "Rp15 juta", "Rp1,15 miliar"],
            answer: 0,
            explain: "15% x Rp1 miliar = Rp150 juta.",
          },
        ],
      },
    ],
  },
];
