import type { Lesson } from "../../../types";

export const level6: Lesson[] = [
  // ============================================================
  {
    id: "incoterms-2020",
    levelId: "incoterms",
    order: 1,
    title: "Incoterms 2020: Siapa Tanggung Apa",
    summary: "Sebelas istilah yang menentukan pembagian biaya dan risiko antara penjual dan pembeli. Dengan video & simulator.",
    durationMin: 15,
    tags: ["Incoterms", "FOB", "CIF", "DDP"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Incoterms</strong> (International Commercial Terms) adalah aturan baku yang menjawab pertanyaan paling sering muncul dalam perdagangan: sampai titik mana <strong>penjual</strong> menanggung biaya dan risiko, dan sejak kapan beralih ke <strong>pembeli</strong>? Versi terbaru adalah Incoterms 2020.",
      },
      {
        type: "video",
        comp: "IncotermsVideo",
        title: "Video: Titik Perpindahan Tanggung Jawab",
        caption: "Animasi perjalanan barang dan titik perpindahan biaya & risiko dari EXW sampai DDP.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dari EXW ke DDP",
        html: "Urutan dari beban penjual paling ringan ke paling berat: <strong>EXW</strong> (pembeli ambil di gudang penjual) sampai <strong>DDP</strong> (penjual antar sampai gudang pembeli, termasuk bea masuk).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pilih satu Incoterm dan lihat sampai tahap mana penjual menanggung biaya dan risiko, lalu bandingkan antar term.",
      },
      { type: "widget", widget: "SimulatorIncoterms" },
      {
        type: "callout",
        tone: "warn",
        title: "CFR/CIF: biaya dan risiko bisa terpisah",
        html: "Pada <strong>CFR</strong> dan <strong>CIF</strong>, penjual membayar freight sampai pelabuhan tujuan, tetapi <strong>risiko</strong> sudah pindah ke pembeli sejak barang di atas kapal. Banyak orang salah mengira keduanya berpindah bersamaan.",
      },
      {
        type: "case",
        title: "Studi Kasus: Salah pilih term, untung tergerus",
        html: "Eksportir pemula menyepakati <strong>DDP</strong> karena ingin terlihat melayani penuh, tanpa menghitung bea masuk dan pajak di negara tujuan yang ternyata 25% dari nilai barang. Margin yang tadinya 20% berubah menjadi rugi. Memilih Incoterm yang tepat adalah keputusan komersial, bukan sekadar administratif.",
      },
      {
        type: "calcExercise",
        prompt: "Nilai barang USD 10.000, eksportir setuju DDP. Bea & pajak tujuan 25%. Berapa beban tambahan eksportir (USD)?",
        answer: 2500,
        tolerance: 0,
        prefix: "USD ",
        solution: "Beban = 25% x USD 10.000 = <strong>USD 2.500</strong> yang ditanggung penjual pada term DDP.",
        hint: "Kalikan persentase bea & pajak dengan nilai barang.",
      },
      {
        type: "classifyExercise",
        prompt: "Pada term ini, siapa yang menanggung bea masuk di negara tujuan?",
        buckets: ["Penjual", "Pembeli"],
        items: [
          { text: "DDP (Delivered Duty Paid)", bucket: "Penjual" },
          { text: "FOB (Free On Board)", bucket: "Pembeli" },
          { text: "EXW (Ex Works)", bucket: "Pembeli" },
          { text: "DAP (Delivered At Place)", bucket: "Pembeli" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Cakupan Biaya yang Ditanggung Penjual per Incoterm (ilustrasi)",
        unit: "% rantai biaya",
        source: "ilustrasi edukatif Incoterms 2020",
        note: "Makin ke kanan, makin banyak biaya rantai pengiriman ditanggung penjual; EXW paling ringan, DDP paling berat.",
        data: [
          { label: "EXW", value: 5, color: "#22c55e" },
          { label: "FOB", value: 35, color: "#84cc16" },
          { label: "CIF", value: 60, color: "#f59e0b" },
          { label: "DAP", value: 85, color: "#f97316" },
          { label: "DDP", value: 100, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Nilai barang USD 8.000. CIF: penjual bayar freight USD 600 dan asuransi 0,5% dari nilai barang. Berapa total tambahan beban penjual (USD)?",
        answer: 640,
        tolerance: 0,
        prefix: "USD ",
        solution: "Asuransi = 0,5% x USD 8.000 = USD 40. Total = USD 600 + USD 40 = <strong>USD 640</strong>. Pada CIF penjual menanggung freight dan asuransi minimum.",
        hint: "Hitung asuransi sebagai persen dari nilai barang, lalu tambahkan freight.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan Incoterm dengan ciri utamanya.",
        pairs: [
          { left: "EXW", right: "Pembeli ambil di gudang penjual" },
          { left: "FOB", right: "Risiko pindah saat barang di atas kapal" },
          { left: "CIF", right: "Penjual bayar freight dan asuransi minimum" },
          { left: "DDP", right: "Penjual antar sampai gudang pembeli termasuk bea masuk" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: ICC dan lahirnya Incoterms 1936",
        html: "<strong>International Chamber of Commerce (ICC)</strong>, lembaga yang juga membakukan Letter of Credit lewat UCP <strong>1933</strong>, menerbitkan <strong>Incoterms</strong> pertama pada <strong>1936</strong> untuk mengakhiri kerancuan istilah dagang antarnegara. Sejak itu Incoterms diperbarui secara berkala mengikuti perkembangan perdagangan, hingga versi <strong>Incoterms 2020</strong>.",
      },
      {
        type: "takeaways",
        items: [
          "Incoterms membagi biaya dan risiko antara penjual dan pembeli.",
          "Urutan beban penjual: EXW paling ringan, DDP paling berat.",
          "Pada CFR/CIF, biaya dan risiko berpindah di titik berbeda.",
          "Memilih Incoterm adalah keputusan komersial yang memengaruhi margin.",
          "FOB dan CIF lazim untuk angkutan laut.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Incoterm dengan beban paling berat bagi penjual?",
            options: ["EXW", "FOB", "DDP", "FCA"],
            answer: 2,
            explain: "DDP membuat penjual menanggung sampai gudang pembeli termasuk bea masuk.",
          },
          {
            q: "Pada FOB, risiko berpindah ke pembeli saat?",
            options: ["Di gudang penjual", "Barang berada di atas kapal", "Tiba di tujuan", "Setelah bea dibayar"],
            answer: 1,
            explain: "Pada FOB, risiko pindah ke pembeli ketika barang sudah di atas kapal.",
          },
          {
            q: "Perbedaan CIF dari CFR?",
            options: ["CIF tanpa freight", "CIF menambah kewajiban asuransi oleh penjual", "CIF untuk udara", "Tidak ada beda"],
            answer: 1,
            explain: "CIF sama seperti CFR ditambah kewajiban penjual membayar asuransi minimum.",
          },
          {
            q: "Pada EXW, siapa menanggung paling banyak?",
            options: ["Penjual", "Pembeli", "Bank", "Forwarder"],
            answer: 1,
            explain: "EXW membebankan hampir semua biaya & risiko kepada pembeli.",
          },
          {
            q: "Nilai USD 20.000, DDP, bea & pajak tujuan 10%. Beban tambahan penjual?",
            options: ["USD 2.000", "USD 200", "USD 2.200", "USD 1.800"],
            answer: 0,
            explain: "10% x USD 20.000 = USD 2.000.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "memilih-incoterm",
    levelId: "incoterms",
    order: 2,
    title: "Cara Memilih Incoterm yang Tepat",
    summary: "Menentukan Incoterm berdasarkan moda angkutan, kontrol, biaya, dan selera risiko, plus kesalahan umum FOB vs FCA untuk kontainer.",
    durationMin: 13,
    tags: ["Incoterms", "FCA", "FOB", "pemilihan"],
    blocks: [
      {
        type: "paragraph",
        html: "Mengetahui sebelas Incoterm saja tidak cukup. Keterampilan yang sesungguhnya adalah <strong>memilih</strong> term yang tepat untuk setiap transaksi. Pilihan yang baik mempertimbangkan empat hal: <strong>moda angkutan</strong>, seberapa besar <strong>kontrol</strong> yang Anda inginkan atas pengiriman, <strong>struktur biaya</strong>, dan <strong>selera risiko</strong> Anda.",
      },
      {
        type: "paragraph",
        html: "Aturan pertama yang sering dilupakan: empat term (<strong>FAS, FOB, CFR, CIF</strong>) hanya boleh dipakai untuk angkutan <strong>laut atau perairan darat</strong>. Tujuh term lainnya (EXW, FCA, CPT, CIP, DAP, DPU, DDP) bisa untuk semua moda termasuk udara dan multimoda.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat pertanyaan kunci",
        html: "1) Apa moda angkutannya? 2) Siapa yang lebih piawai mengurus logistik dan bea? 3) Sisi mana yang mendapat tarif freight dan asuransi lebih murah? 4) Berapa besar risiko yang siap Anda tanggung? Jawabannya menentukan term.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan pakai FOB untuk kontainer",
        html: "Kesalahan paling umum: memakai <strong>FOB</strong> untuk barang dalam <strong>kontainer</strong>. Pada FOB, risiko baru pindah saat barang di atas kapal, padahal kontainer sudah lepas dari kendali penjual sejak diserahkan ke terminal. Untuk kontainer, gunakan <strong>FCA</strong> agar titik perpindahan sesuai kenyataan, yaitu saat serah terima di terminal atau gudang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan FOB dan FCA pada pengiriman kontainer, lalu perhatikan bagaimana titik perpindahan biaya dan risiko bergeser sesuai moda angkutan.",
      },
      { type: "widget", widget: "SimulatorIncoterms" },
      {
        type: "case",
        title: "Studi Kasus: FOB vs FCA pada kontainer",
        html: "Eksportir mengirim 1 kontainer furnitur dan memakai <strong>FOB</strong>. Kontainer rusak saat ditumpuk di terminal, sebelum naik kapal. Karena FOB, risiko secara teknis masih di penjual sampai barang di atas kapal, sehingga klaim jadi rumit dan saling lempar tanggung jawab. Jika memakai <strong>FCA terminal</strong>, risiko sudah berpindah ke pembeli saat serah terima di terminal, dan tanggung jawab jelas sejak awal.",
      },
      {
        type: "calcExercise",
        prompt: "Tarif freight via penjual USD 1.200, via pembeli USD 1.500. Berapa penghematan jika penjual yang mengatur freight (USD)?",
        answer: 300,
        tolerance: 0,
        prefix: "USD ",
        solution: "Penghematan = USD 1.500 - USD 1.200 = <strong>USD 300</strong>. Pilih sisi yang mendapat tarif lebih murah untuk mengatur freight, lalu sesuaikan Incoterm-nya.",
        hint: "Kurangkan tarif yang lebih murah dari yang lebih mahal.",
      },
      {
        type: "classifyExercise",
        prompt: "Term ini cocok untuk moda angkutan yang mana?",
        buckets: ["Khusus laut/perairan", "Semua moda"],
        items: [
          { text: "FOB (Free On Board)", bucket: "Khusus laut/perairan" },
          { text: "CIF (Cost Insurance Freight)", bucket: "Khusus laut/perairan" },
          { text: "FCA (Free Carrier)", bucket: "Semua moda" },
          { text: "CIP (Carriage Insurance Paid)", bucket: "Semua moda" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Penggunaan Incoterm pada Pengiriman Kontainer (ilustrasi)",
        unit: "% transaksi",
        source: "ilustrasi edukatif",
        note: "Banyak eksportir masih keliru memakai FOB untuk kontainer, padahal FCA lebih tepat.",
        data: [
          { label: "FOB (kurang tepat)", value: 40, color: "#ef4444" },
          { label: "FCA (tepat)", value: 35, color: "#22c55e" },
          { label: "CIF", value: 15, color: "#f59e0b" },
          { label: "Lainnya", value: 10, color: "#94a3b8" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Asuransi via penjual (CIP) USD 90, via pembeli USD 150. Berapa penghematan jika penjual yang mengasuransikan (USD)?",
        answer: 60,
        tolerance: 0,
        prefix: "USD ",
        solution: "Penghematan = USD 150 - USD 90 = <strong>USD 60</strong>. Pihak dengan tarif lebih murah sebaiknya mengatur asuransi, lalu pilih term yang sesuai.",
        hint: "Kurangkan tarif yang lebih murah dari yang lebih mahal.",
      },
      {
        type: "classifyExercise",
        prompt: "Untuk situasi berikut, term mana yang lebih tepat?",
        buckets: ["FCA", "FOB"],
        items: [
          { text: "Ekspor furnitur dalam kontainer 40ft", bucket: "FCA" },
          { text: "Ekspor batu bara curah lewat kapal bulk", bucket: "FOB" },
          { text: "Serah terima di terminal peti kemas", bucket: "FCA" },
          { text: "Muatan dimuat langsung ke palka kapal", bucket: "FOB" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Peti kemas membuat FOB usang untuk kontainer",
        html: "Sejak revolusi peti kemas yang dimulai <strong>Malcom McLean</strong> pada <strong>1956</strong>, barang tidak lagi dimuat satu per satu ke palka, melainkan diserahkan utuh di terminal jauh sebelum naik kapal. Karena itu titik risiko <strong>FOB</strong> (saat barang di atas kapal) tidak lagi sesuai kenyataan kontainer. ICC pun menganjurkan <strong>FCA</strong> sebagai term yang tepat untuk era kontainer.",
      },
      {
        type: "takeaways",
        items: [
          "Memilih Incoterm mempertimbangkan moda, kontrol, biaya, dan risiko.",
          "FAS, FOB, CFR, CIF hanya untuk angkutan laut/perairan darat.",
          "Untuk kontainer, gunakan FCA, bukan FOB.",
          "Pihak dengan tarif freight/asuransi lebih murah sebaiknya yang mengaturnya.",
          "Term yang tepat membuat titik risiko sesuai kenyataan logistik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Term yang tepat untuk barang dalam kontainer adalah?",
            options: ["FOB", "FCA", "CFR", "FAS"],
            answer: 1,
            explain: "FCA membuat titik perpindahan sesuai kenyataan kontainer, yaitu saat serah terima di terminal.",
          },
          {
            q: "Term berikut yang HANYA untuk angkutan laut?",
            options: ["CPT", "CIP", "CIF", "DAP"],
            answer: 2,
            explain: "CIF termasuk empat term yang hanya untuk angkutan laut/perairan darat.",
          },
          {
            q: "Faktor yang TIDAK relevan saat memilih Incoterm?",
            options: ["Moda angkutan", "Selera risiko", "Warna kemasan", "Struktur biaya"],
            answer: 2,
            explain: "Warna kemasan tidak memengaruhi pembagian biaya dan risiko Incoterm.",
          },
          {
            q: "Kesalahan umum pada pengiriman kontainer adalah?",
            options: ["Memakai FCA", "Memakai FOB", "Memakai DAP", "Memakai CIP"],
            answer: 1,
            explain: "FOB tidak cocok untuk kontainer karena titik risikonya tidak sesuai kenyataan.",
          },
          {
            q: "Freight via penjual USD 1.000, via pembeli USD 1.300. Penghematan jika penjual mengatur?",
            options: ["USD 300", "USD 2.300", "USD 1.300", "USD 100"],
            answer: 0,
            explain: "USD 1.300 - USD 1.000 = USD 300.",
          },
        ],
      },
    ],
  },
];
