import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "pengantar-perdagangan-internasional",
    levelId: "dasar",
    order: 1,
    title: "Pengantar Perdagangan Internasional",
    summary: "Mengapa negara berdagang, bagaimana barang berpindah antarnegara, dan peran lembaga seperti WTO.",
    durationMin: 13,
    tags: ["perdagangan internasional", "WTO", "ekspor impor"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak ada negara yang bisa memproduksi semua kebutuhannya sendiri secara efisien. <strong>Perdagangan internasional</strong> memungkinkan tiap negara fokus pada apa yang paling efisien diproduksinya, lalu menukarnya dengan negara lain. Inilah dasar ekspor dan impor.",
      },
      {
        type: "paragraph",
        html: "Barang bergerak melalui rantai pasok global (<strong>global supply chain</strong>): produsen, eksportir, pengangkut, pelabuhan, otoritas pabean, importir, sampai konsumen akhir. Setiap simpul punya aturan dan dokumennya sendiri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tarif vs non-tarif",
        html: "Negara melindungi industrinya dengan dua jenis hambatan: <strong>tarif</strong> (bea masuk berupa pajak atas barang impor) dan <strong>non-tarif</strong> (kuota, perizinan, standar mutu/SNI, larangan).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran WTO",
        html: "<strong>WTO</strong> (World Trade Organization) menjadi wasit perdagangan dunia: menyusun aturan, mendorong penurunan tarif, dan menyelesaikan sengketa antarnegara agar perdagangan lebih adil dan terprediksi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Istilah penting",
        html: "<strong>Dumping</strong>: menjual barang ekspor lebih murah dari harga di negara asal. <strong>Safeguard</strong>: tindakan pengamanan saat lonjakan impor merugikan industri dalam negeri. <strong>Embargo</strong>: larangan dagang total terhadap negara tertentu.",
      },
      {
        type: "case",
        title: "Studi Kasus: Neraca perdagangan Indonesia",
        html: "Jika dalam satu tahun Indonesia mengekspor barang senilai USD 250 miliar dan mengimpor senilai USD 230 miliar, maka <strong>neraca perdagangan surplus</strong> sebesar USD 20 miliar. Surplus berarti devisa masuk lebih besar dari yang keluar. Sebaliknya, bila impor lebih besar, terjadi defisit yang dapat menekan nilai tukar rupiah.",
      },
      {
        type: "calcExercise",
        prompt: "Ekspor USD 250 miliar, impor USD 230 miliar. Berapa surplus neraca perdagangan (USD miliar)?",
        answer: 20,
        tolerance: 0,
        suffix: " miliar USD",
        solution: "Neraca perdagangan = Ekspor - Impor = 250 - 230 = <strong>20 miliar USD surplus</strong>.",
        hint: "Kurangi nilai impor dari nilai ekspor.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebijakan ini termasuk hambatan tarif atau non-tarif?",
        buckets: ["Hambatan tarif", "Hambatan non-tarif"],
        items: [
          { text: "Bea masuk 10% atas baja impor", bucket: "Hambatan tarif" },
          { text: "Kuota maksimal impor gula", bucket: "Hambatan non-tarif" },
          { text: "Wajib sertifikat SNI", bucket: "Hambatan non-tarif" },
          { text: "Tarif progresif atas mobil mewah", bucket: "Hambatan tarif" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah perdagangan internasional dengan maknanya.",
        pairs: [
          { left: "Tarif", right: "Pajak atas barang impor" },
          { left: "Kuota", right: "Batas jumlah barang yang boleh diimpor" },
          { left: "Dumping", right: "Menjual ekspor lebih murah dari harga di negara asal" },
          { left: "Safeguard", right: "Tindakan pengamanan saat lonjakan impor" },
          { left: "Embargo", right: "Larangan dagang total terhadap negara tertentu" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren Nilai Ekspor dan Impor Indonesia (ilustrasi)",
        unit: "miliar USD",
        source: "ilustrasi edukatif",
        note: "Selisih ekspor dan impor membentuk surplus atau defisit neraca perdagangan.",
        data: [
          { label: "2021", value: 230, color: "#0ea5e9" },
          { label: "2022", value: 292, color: "#10b981" },
          { label: "2023", value: 259, color: "#f59e0b" },
          { label: "2024", value: 264, color: "#6366f1" },
        ],
      },
      {
        type: "video",
        comp: "SupplyChainVideo",
        title: "Video: Perjalanan Barang di Rantai Pasok Global",
        caption: "Animasi alur barang dari produsen, eksportir, pelabuhan, otoritas pabean, importir, sampai konsumen akhir.",
      },
      {
        type: "case",
        title: "Sejarah: Dari GATT 1947 ke WTO 1995",
        html: "Setelah Perang Dunia II, sekitar <strong>23 negara</strong> menandatangani <strong>GATT</strong> pada <strong>1947</strong> untuk menurunkan tarif yang sempat memicu perang dagang pada era Depresi. Lewat berbagai putaran perundingan, rata-rata tarif dunia turun dari sekitar <strong>40%</strong> menjadi di bawah <strong>5%</strong>. Pada <strong>1995</strong>, GATT bertransformasi menjadi <strong>WTO</strong> yang kini menjadi wasit perdagangan global.",
      },
      {
        type: "takeaways",
        items: [
          "Perdagangan internasional memungkinkan negara fokus pada keunggulannya.",
          "Barang bergerak lewat rantai pasok global dengan banyak simpul dan aturan.",
          "Proteksi dilakukan lewat hambatan tarif dan non-tarif.",
          "WTO mengatur dan menengahi perdagangan dunia.",
          "Neraca perdagangan = ekspor dikurangi impor.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Alasan utama negara berdagang internasional?",
            options: ["Agar harga selalu naik", "Fokus pada produksi yang paling efisien lalu menukarnya", "Menghindari pajak", "Menutup ekonomi"],
            answer: 1,
            explain: "Tiap negara berspesialisasi pada keunggulannya, lalu menukar lewat ekspor-impor.",
          },
          {
            q: "Bea masuk adalah contoh hambatan?",
            options: ["Non-tarif", "Tarif", "Kuota", "Embargo"],
            answer: 1,
            explain: "Bea masuk adalah pajak atas barang impor, yaitu hambatan tarif.",
          },
          {
            q: "Peran utama WTO?",
            options: ["Menetapkan harga barang", "Mengatur aturan & menyelesaikan sengketa dagang dunia", "Mengangkut barang", "Memberi pinjaman"],
            answer: 1,
            explain: "WTO menyusun aturan perdagangan dan menengahi sengketa antarnegara.",
          },
          {
            q: "Dumping berarti?",
            options: [
              "Menjual ekspor lebih murah dari harga di negara asal",
              "Melarang impor",
              "Menaikkan tarif",
              "Menumpuk barang di gudang",
            ],
            answer: 0,
            explain: "Dumping adalah menjual barang ekspor di bawah harga normal di negara asal.",
          },
          {
            q: "Ekspor USD 100 miliar, impor USD 120 miliar. Neraca perdagangan?",
            options: ["Surplus 20", "Defisit 20", "Seimbang", "Surplus 220"],
            answer: 1,
            explain: "100 - 120 = -20, artinya defisit 20 miliar USD.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jenis-ekspor-impor",
    levelId: "dasar",
    order: 2,
    title: "Jenis Ekspor dan Impor serta Pelaku Usahanya",
    summary: "Mengenal ekspor langsung vs tidak langsung, trading house, distributor, manufaktur, OEM/ODM, dan cross-border e-commerce.",
    durationMin: 13,
    tags: ["ekspor impor", "OEM ODM", "e-commerce"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua kegiatan ekspor dan impor dilakukan dengan cara yang sama. Ada <strong>ekspor langsung</strong> (produsen menjual sendiri ke pembeli luar negeri) dan <strong>ekspor tidak langsung</strong> (produsen menjual lewat perantara seperti trading house yang mengurus ekspornya).",
      },
      {
        type: "paragraph",
        html: "Memahami peran tiap pelaku membantu menentukan siapa yang bertanggung jawab atas dokumen, biaya, dan risiko. Pilihan jalur juga memengaruhi margin keuntungan dan kecepatan masuk pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Langsung vs tidak langsung",
        html: "<strong>Ekspor langsung</strong>: kontrol penuh atas harga dan pelanggan, tetapi butuh kapasitas administrasi. <strong>Ekspor tidak langsung</strong>: lebih praktis lewat perantara, tetapi margin terpotong komisi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Trading house, distributor, manufaktur",
        html: "<strong>Trading house</strong> membeli dan menjual kembali barang lintas negara. <strong>Distributor</strong> memasarkan barang di wilayah tertentu. <strong>Manufaktur</strong> adalah produsen yang membuat barang itu sendiri.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "OEM vs ODM",
        html: "<strong>OEM</strong> (Original Equipment Manufacturer): pabrik membuat barang sesuai desain pemesan, lalu diberi merek pemesan. <strong>ODM</strong> (Original Design Manufacturer): pabrik merancang sekaligus membuat, pemesan tinggal memberi merek.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Cross-border e-commerce",
        html: "Penjualan lintas negara lewat platform digital memungkinkan produsen kecil menjangkau konsumen global tanpa perantara besar. Tetap tunduk pada aturan pabean, termasuk batas nilai pembebasan (de minimis) untuk barang kiriman.",
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih jalur ekspor",
        html: "Sebuah produsen mebel menjual ke pasar Eropa. Lewat <strong>ekspor langsung</strong> ia mendapat harga USD 100 per unit. Lewat <strong>trading house</strong> ia hanya menerima USD 80 per unit karena komisi 20%. Jika menjual 500 unit, selisih pendapatannya adalah USD 10.000. Namun ekspor langsung menuntut tim ekspor sendiri.",
      },
      {
        type: "calcExercise",
        prompt: "Harga ekspor langsung USD 100/unit, lewat trading house USD 80/unit. Untuk 500 unit, berapa selisih pendapatan (USD)?",
        answer: 10000,
        tolerance: 0,
        suffix: " USD",
        solution: "Selisih per unit = 100 - 80 = USD 20. Total = 20 x 500 = <strong>USD 10.000</strong>.",
        hint: "Kalikan selisih harga per unit dengan jumlah unit.",
      },
      {
        type: "classifyExercise",
        prompt: "Pelaku usaha ini termasuk kategori apa?",
        buckets: ["Perantara dagang", "Produsen"],
        items: [
          { text: "Trading house yang membeli lalu menjual kembali", bucket: "Perantara dagang" },
          { text: "Pabrik OEM yang membuat barang sesuai desain pemesan", bucket: "Produsen" },
          { text: "Distributor regional di luar negeri", bucket: "Perantara dagang" },
          { text: "Pabrik ODM yang merancang dan membuat barang", bucket: "Produsen" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Margin per Unit Antar Jalur Ekspor (ilustrasi)",
        unit: "USD per unit",
        source: "ilustrasi edukatif",
        note: "Ekspor langsung memberi margin tertinggi, tetapi menuntut kapasitas administrasi sendiri.",
        data: [
          { label: "Ekspor langsung", value: 40, color: "#10b981" },
          { label: "Cross-border e-commerce", value: 32, color: "#0ea5e9" },
          { label: "Distributor", value: 24, color: "#f59e0b" },
          { label: "Trading house", value: 18, color: "#ef4444" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pelaku usaha dengan perannya.",
        pairs: [
          { left: "Trading house", right: "Membeli dan menjual kembali barang lintas negara" },
          { left: "Distributor", right: "Memasarkan barang di wilayah tertentu" },
          { left: "Manufaktur", right: "Produsen yang membuat barang sendiri" },
          { left: "OEM", right: "Membuat barang sesuai desain pemesan" },
          { left: "ODM", right: "Merancang sekaligus membuat barang" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: VOC dan perdagangan rempah Nusantara",
        html: "Pada <strong>1602</strong>, Belanda mendirikan <strong>VOC</strong>, kongsi dagang yang memonopoli perdagangan rempah dari Nusantara ke Eropa selama hampir <strong>dua abad</strong>. VOC adalah contoh awal <strong>perantara dagang</strong> raksasa yang membeli rempah seperti pala dan cengkeh, lalu menjualnya kembali di Eropa dengan margin sangat besar. Pola perantara dagang lintas negara ini menjadi cikal bakal trading house modern.",
      },
      {
        type: "takeaways",
        items: [
          "Ekspor bisa langsung (kontrol penuh) atau tidak langsung (lewat perantara).",
          "Trading house dan distributor adalah perantara, manufaktur adalah produsen.",
          "OEM membuat sesuai desain pemesan, ODM merancang sekaligus membuat.",
          "Cross-border e-commerce membuka pasar global bagi pelaku kecil.",
          "Pemilihan jalur memengaruhi margin, risiko, dan tanggung jawab dokumen.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ekspor langsung berarti?",
            options: ["Menjual lewat trading house", "Produsen menjual sendiri ke pembeli luar negeri", "Menjual hanya di dalam negeri", "Membeli barang impor"],
            answer: 1,
            explain: "Ekspor langsung berarti produsen berhubungan langsung dengan pembeli luar negeri.",
          },
          {
            q: "Apa peran trading house?",
            options: ["Membuat barang", "Membeli dan menjual kembali barang lintas negara", "Mengangkut barang saja", "Menetapkan tarif"],
            answer: 1,
            explain: "Trading house adalah perantara yang membeli lalu menjual kembali barang.",
          },
          {
            q: "Perbedaan OEM dan ODM?",
            options: [
              "OEM merancang sendiri, ODM tidak",
              "OEM membuat sesuai desain pemesan, ODM merancang sekaligus membuat",
              "Keduanya sama",
              "ODM hanya menjual",
            ],
            answer: 1,
            explain: "OEM membuat sesuai desain pemesan; ODM merancang sekaligus memproduksi.",
          },
          {
            q: "Cross-border e-commerce memungkinkan?",
            options: ["Menghindari pabean sepenuhnya", "Pelaku kecil menjangkau konsumen global lewat platform digital", "Hanya perusahaan besar berdagang", "Tarif selalu nol"],
            answer: 1,
            explain: "Platform digital memudahkan pelaku kecil menjual lintas negara, namun tetap tunduk aturan pabean.",
          },
          {
            q: "Harga langsung USD 50/unit, lewat perantara USD 40/unit. Untuk 200 unit, selisihnya?",
            options: ["USD 2.000", "USD 1.000", "USD 200", "USD 10.000"],
            answer: 0,
            explain: "Selisih per unit USD 10 x 200 unit = USD 2.000.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "komunikasi-bisnis-trade",
    levelId: "dasar",
    order: 3,
    title: "Komunikasi Bisnis dalam Perdagangan",
    summary: "Alur dokumen komersial dari inquiry, quotation, purchase order, sales contract, negosiasi, hingga penanganan complaint.",
    durationMin: 13,
    tags: ["komunikasi bisnis", "quotation", "kontrak"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum barang dikirim, terjadi serangkaian komunikasi bisnis yang menentukan harga, jumlah, dan syarat dagang. Alur klasiknya: <strong>inquiry</strong> (permintaan informasi), <strong>quotation</strong> (penawaran harga), <strong>purchase order</strong> (pesanan), lalu <strong>sales contract</strong> (kontrak jual beli).",
      },
      {
        type: "paragraph",
        html: "Komunikasi yang jelas mencegah salah paham yang mahal. Setiap tahap menghasilkan dokumen yang menjadi rujukan hukum bila terjadi sengketa, termasuk penanganan <strong>complaint</strong> atau klaim atas barang yang tidak sesuai.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Urutan dokumen",
        html: "<strong>Inquiry</strong> dikirim pembeli, dibalas dengan <strong>quotation</strong> dari penjual. Bila sepakat, pembeli menerbitkan <strong>purchase order</strong>, lalu kedua pihak menandatangani <strong>sales contract</strong> yang mengikat.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Negosiasi yang sehat",
        html: "Negosiasi bukan hanya soal harga, tetapi juga Incoterms, jadwal pengiriman, syarat pembayaran, dan kualitas. Catat setiap kesepakatan secara tertulis agar tidak menjadi sengketa.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Menangani complaint",
        html: "Bila barang tidak sesuai, pembeli mengajukan <strong>complaint</strong> atau klaim. Tanggapi cepat dengan bukti (foto, surveyor) dan rujuk klausul kontrak. Reputasi jangka panjang lebih berharga daripada satu transaksi.",
      },
      {
        type: "case",
        title: "Studi Kasus: Quotation yang mengikat margin",
        html: "Seorang eksportir mengirim quotation USD 12 per kg untuk 1.000 kg kopi, dengan biaya produksi USD 9 per kg. Pembeli menegosiasi turun ke USD 11 per kg. Margin per kg turun dari USD 3 menjadi USD 2, sehingga total margin dari USD 3.000 menjadi USD 2.000. Eksportir harus memastikan harga negosiasi tetap menutup biaya.",
      },
      {
        type: "calcExercise",
        prompt: "Harga negosiasi USD 11/kg, biaya produksi USD 9/kg, untuk 1.000 kg. Berapa total margin (USD)?",
        answer: 2000,
        tolerance: 0,
        suffix: " USD",
        solution: "Margin per kg = 11 - 9 = USD 2. Total = 2 x 1.000 = <strong>USD 2.000</strong>.",
        hint: "Kurangi biaya dari harga, lalu kalikan dengan jumlah kg.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah komunikasi dagang dengan maknanya.",
        pairs: [
          { left: "Inquiry", right: "Permintaan informasi atau penawaran dari pembeli" },
          { left: "Quotation", right: "Penawaran harga resmi dari penjual" },
          { left: "Purchase Order", right: "Surat pesanan yang diterbitkan pembeli" },
          { left: "Sales Contract", right: "Kontrak jual beli yang mengikat kedua pihak" },
          { left: "Complaint", right: "Klaim atas barang yang tidak sesuai" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Dokumen atau aksi ini dilakukan oleh pembeli atau penjual?",
        buckets: ["Pembeli", "Penjual"],
        items: [
          { text: "Mengirim inquiry", bucket: "Pembeli" },
          { text: "Menerbitkan quotation", bucket: "Penjual" },
          { text: "Menerbitkan purchase order", bucket: "Pembeli" },
          { text: "Mengajukan complaint atas barang tidak sesuai", bucket: "Pembeli" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Jalur Sutra dan komunikasi dagang lintas benua",
        html: "Sejak sekitar <strong>abad ke-2 SM</strong>, <strong>Jalur Sutra</strong> menghubungkan Tiongkok dengan Eropa sepanjang lebih dari <strong>6.000 km</strong>. Karena satu perjalanan bisa memakan waktu berbulan-bulan, para pedagang harus menyepakati harga, jumlah, dan syarat dagang dengan cermat sebelum berangkat. Inilah bentuk awal komunikasi bisnis seperti penawaran, pesanan, dan kontrak yang kita kenal sekarang.",
      },
      {
        type: "takeaways",
        items: [
          "Alur dagang: inquiry, quotation, purchase order, lalu sales contract.",
          "Inquiry datang dari pembeli, quotation adalah penawaran penjual.",
          "Negosiasi mencakup harga, Incoterms, pembayaran, dan jadwal.",
          "Sales contract mengikat secara hukum bila terjadi sengketa.",
          "Complaint ditangani cepat dengan bukti dan rujukan kontrak.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dokumen pertama dalam alur komunikasi dagang biasanya?",
            options: ["Sales contract", "Inquiry dari pembeli", "Bill of Lading", "Complaint"],
            answer: 1,
            explain: "Alur diawali inquiry, yaitu permintaan informasi dari calon pembeli.",
          },
          {
            q: "Quotation diterbitkan oleh?",
            options: ["Pembeli", "Penjual sebagai penawaran harga", "Bea Cukai", "Bank"],
            answer: 1,
            explain: "Quotation adalah penawaran harga resmi yang dikeluarkan penjual.",
          },
          {
            q: "Purchase order adalah?",
            options: ["Penawaran penjual", "Surat pesanan dari pembeli", "Kontrak final", "Klaim barang rusak"],
            answer: 1,
            explain: "Purchase order adalah surat pesanan resmi yang diterbitkan pembeli.",
          },
          {
            q: "Negosiasi dagang yang baik mencakup, kecuali?",
            options: ["Harga", "Incoterms dan syarat pembayaran", "Jadwal pengiriman", "Warna logo Bea Cukai"],
            answer: 3,
            explain: "Negosiasi membahas harga, Incoterms, pembayaran, dan jadwal, bukan hal yang tak relevan.",
          },
          {
            q: "Harga jual USD 15/kg, biaya USD 10/kg, untuk 500 kg. Total margin?",
            options: ["USD 2.500", "USD 5.000", "USD 500", "USD 7.500"],
            answer: 0,
            explain: "Margin per kg USD 5 x 500 kg = USD 2.500.",
          },
        ],
      },
    ],
  },
];
