import type { Lesson } from "../../../types";

export const level7: Lesson[] = [
  // ============================================================
  {
    id: "metode-pembayaran-internasional",
    levelId: "pembayaran",
    order: 1,
    title: "Pembayaran Internasional & Letter of Credit",
    summary: "Bagaimana eksportir memastikan dibayar dan importir memastikan barang datang. Dengan simulator risiko pembayaran.",
    durationMin: 14,
    tags: ["letter of credit", "pembayaran", "trade finance"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam perdagangan lintas negara, penjual dan pembeli sering belum saling kenal dan dipisahkan jarak serta hukum berbeda. Pertanyaan intinya: bagaimana eksportir yakin dibayar, dan importir yakin barang datang? Jawabannya ada pada <strong>metode pembayaran internasional</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Spektrum risiko",
        html: "<strong>Advance payment</strong> aman bagi eksportir, berisiko bagi importir. <strong>Open account</strong> sebaliknya. <strong>Letter of Credit (LC)</strong> dan <strong>documentary collection</strong> berada di tengah dengan bank sebagai penengah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pilih metode pembayaran dan bandingkan tingkat risiko bagi eksportir dan importir, lalu lihat kapan tiap metode paling cocok.",
      },
      { type: "widget", widget: "SimulatorPembayaranEkspor" },
      {
        type: "callout",
        tone: "info",
        title: "Cara kerja LC",
        html: "Bank importir berjanji membayar eksportir <strong>jika</strong> dokumen yang diserahkan sesuai syarat LC. Bank menilai dokumen, bukan barang. Karena itu kesesuaian dokumen menjadi sangat penting.",
      },
      {
        type: "case",
        title: "Studi Kasus: Transaksi pertama dengan mitra baru",
        html: "Eksportir Indonesia menerima pesanan besar dari pembeli baru di luar negeri. Karena belum saling percaya, mereka memakai <strong>LC</strong>. Bank menjamin pembayaran setelah eksportir menyerahkan B/L dan invoice sesuai syarat. Eksportir terlindungi dari risiko tidak dibayar, importir terlindungi karena pembayaran baru cair setelah ada bukti pengapalan.",
      },
      {
        type: "calcExercise",
        prompt: "Nilai LC USD 100.000, biaya bank 0,5%. Berapa biaya LC yang ditanggung (USD)?",
        answer: 500,
        tolerance: 0,
        prefix: "USD ",
        solution: "Biaya = 0,5% x USD 100.000 = <strong>USD 500</strong>. Ini harga dari keamanan transaksi.",
        hint: "Kalikan persentase biaya bank dengan nilai LC.",
      },
      {
        type: "classifyExercise",
        prompt: "Metode pembayaran ini lebih aman bagi siapa?",
        buckets: ["Lebih aman bagi eksportir", "Lebih aman bagi importir"],
        items: [
          { text: "Advance payment (bayar di muka)", bucket: "Lebih aman bagi eksportir" },
          { text: "Open account (bayar belakangan)", bucket: "Lebih aman bagi importir" },
          { text: "Cash before delivery", bucket: "Lebih aman bagi eksportir" },
          { text: "Bayar 60 hari setelah barang diterima", bucket: "Lebih aman bagi importir" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tingkat Risiko Eksportir per Metode Pembayaran (ilustrasi)",
        unit: "skor risiko 0-100",
        source: "ilustrasi edukatif",
        note: "Open account paling berisiko bagi eksportir; advance payment paling aman.",
        data: [
          { label: "Advance payment", value: 10, color: "#10b981" },
          { label: "Letter of Credit", value: 30, color: "#0ea5e9" },
          { label: "Documentary collection", value: 55, color: "#f59e0b" },
          { label: "Open account", value: 90, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Nilai LC USD 250.000, biaya konfirmasi bank 0,75%. Berapa biaya konfirmasi (USD)?",
        answer: 1875,
        tolerance: 0,
        prefix: "USD ",
        solution: "Biaya = 0,75% x USD 250.000 = <strong>USD 1.875</strong>. Konfirmasi menambah jaminan dari bank kedua.",
        hint: "Kalikan 0,75% dengan nilai LC.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah pembayaran internasional dengan definisinya.",
        pairs: [
          { left: "Letter of Credit", right: "Bank menjamin bayar bila dokumen sesuai syarat" },
          { left: "Advance payment", right: "Importir bayar penuh sebelum barang dikirim" },
          { left: "Open account", right: "Eksportir kirim dulu, importir bayar belakangan" },
          { left: "Documentary collection", right: "Bank menyerahkan dokumen setelah pembayaran/akseptasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Letter of Credit menjembatani kepercayaan",
        html: "Masalah saling percaya antarpedagang yang terpisah jarak sudah ada sejak <strong>abad pertengahan</strong>, saat para saudagar memakai surat wesel agar tidak perlu membawa emas dalam perjalanan berbahaya. Bentuk modernnya, <strong>Letter of Credit</strong>, dibakukan oleh <strong>ICC</strong> lewat aturan <strong>UCP</strong> sejak <strong>1933</strong>. Hingga kini LC menjadi salah satu instrumen yang menopang sebagian besar pembiayaan perdagangan dunia.",
      },
      {
        type: "takeaways",
        items: [
          "Metode pembayaran menyeimbangkan risiko eksportir dan importir.",
          "Advance payment aman bagi penjual; open account aman bagi pembeli.",
          "LC menempatkan bank sebagai penjamin pembayaran berbasis dokumen.",
          "Pada LC, kesesuaian dokumen menentukan pencairan.",
          "Trade finance membantu arus kas eksportir dan importir.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Letter of Credit menjamin pembayaran berdasarkan?",
            options: ["Kondisi barang", "Kesesuaian dokumen dengan syarat LC", "Cuaca", "Harga pasar"],
            answer: 1,
            explain: "Bank membayar jika dokumen sesuai syarat LC, bukan menilai barang fisik.",
          },
          {
            q: "Metode paling aman bagi eksportir?",
            options: ["Open account", "Advance payment", "Documentary collection", "Konsinyasi"],
            answer: 1,
            explain: "Advance payment membuat eksportir dibayar sebelum mengirim barang.",
          },
          {
            q: "Open account paling nyaman bagi?",
            options: ["Eksportir", "Importir", "Bank", "Forwarder"],
            answer: 1,
            explain: "Open account menguntungkan importir karena bayar setelah barang diterima.",
          },
          {
            q: "Kapan LC paling tepat dipakai?",
            options: [
              "Mitra lama yang sangat terpercaya",
              "Nilai besar dengan mitra yang belum saling percaya",
              "Transaksi tunai kecil",
              "Pembelian eceran",
            ],
            answer: 1,
            explain: "LC ideal untuk transaksi besar saat kepercayaan antar mitra belum terbangun.",
          },
          {
            q: "Nilai LC USD 50.000, biaya bank 1%. Biaya LC?",
            options: ["USD 500", "USD 5.000", "USD 50", "USD 5"],
            answer: 0,
            explain: "1% x USD 50.000 = USD 500.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "trade-finance",
    levelId: "pembayaran",
    order: 2,
    title: "Trade Finance: Mendanai Perdagangan",
    summary: "Pembiayaan ekspor-impor, factoring, forfaiting, dan bank guarantee, serta cara instrumen ini menjaga arus kas.",
    durationMin: 13,
    tags: ["trade finance", "factoring", "forfaiting", "bank guarantee"],
    blocks: [
      {
        type: "paragraph",
        html: "Perdagangan internasional sering menciptakan <strong>jeda arus kas</strong>: eksportir mengeluarkan biaya produksi hari ini, tetapi baru dibayar 60-90 hari kemudian. <strong>Trade finance</strong> adalah kumpulan instrumen yang menutup jeda itu sehingga eksportir maupun importir tetap memiliki modal kerja untuk berputar.",
      },
      {
        type: "paragraph",
        html: "Bentuknya beragam: <strong>pembiayaan ekspor</strong> (pinjaman dengan jaminan pesanan atau dokumen ekspor), <strong>pembiayaan impor</strong> (talangan untuk membayar pemasok), <strong>factoring</strong>, <strong>forfaiting</strong>, dan <strong>bank guarantee</strong>. Masing-masing menyelesaikan kebutuhan kas yang berbeda.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Factoring vs forfaiting",
        html: "<strong>Factoring</strong>: menjual piutang jangka pendek ke lembaga keuangan untuk kas segera, sering tanpa jaminan bank dan bisa <em>with</em> atau <em>without recourse</em>. <strong>Forfaiting</strong>: menjual piutang ekspor jangka menengah-panjang, selalu <strong>without recourse</strong>, biasanya dijamin instrumen seperti wesel atau aval bank.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bank guarantee",
        html: "<strong>Bank guarantee</strong> adalah janji bank untuk membayar pihak penerima jika nasabah gagal memenuhi kewajiban. Contohnya <em>performance bond</em> dan <em>advance payment guarantee</em>, yang menambah kepercayaan tanpa harus menyetor uang penuh di muka.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tenor Khas Instrumen Trade Finance (ilustrasi)",
        unit: "hari",
        source: "ilustrasi edukatif",
        note: "Factoring umumnya jangka pendek; forfaiting menjangkau tenor lebih panjang.",
        data: [
          { label: "Factoring", value: 90, color: "#0ea5e9" },
          { label: "Pembiayaan ekspor", value: 180, color: "#10b981" },
          { label: "Forfaiting", value: 720, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Factoring menyelamatkan arus kas",
        html: "Eksportir tekstil menjual barang USD 100.000 dengan tempo bayar 90 hari, tetapi harus membeli bahan baku batch berikutnya sekarang. Lewat <strong>factoring</strong>, ia menjual piutang itu dan menerima 80% di muka (USD 80.000) dengan biaya 2%. Kas langsung tersedia untuk produksi, sisa 20% cair setelah pembeli melunasi.",
      },
      {
        type: "calcExercise",
        prompt: "Piutang USD 100.000, factoring mencairkan 80% di muka. Berapa kas yang diterima di muka (USD)?",
        answer: 80000,
        tolerance: 0,
        prefix: "USD ",
        solution: "Kas di muka = 80% x USD 100.000 = <strong>USD 80.000</strong>. Sisanya cair setelah pembeli melunasi, dikurangi biaya factoring.",
        hint: "Kalikan persentase pencairan di muka dengan nilai piutang.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebutuhan ini paling cocok diselesaikan instrumen yang mana?",
        buckets: ["Factoring", "Forfaiting", "Bank guarantee"],
        items: [
          { text: "Kas cepat dari piutang jangka pendek", bucket: "Factoring" },
          { text: "Menjual piutang ekspor jangka panjang tanpa recourse", bucket: "Forfaiting" },
          { text: "Jaminan kinerja kontrak kepada pembeli", bucket: "Bank guarantee" },
          { text: "Talangan piutang tempo 60 hari", bucket: "Factoring" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hitung biaya trade finance",
        html: "Gunakan kalkulator untuk memperkirakan kas di muka dan biaya factoring/forfaiting dari nilai piutang dan tarif yang berlaku.",
      },
      { type: "widget", widget: "KalkulatorTradeFinance" },
      {
        type: "calcExercise",
        prompt: "Piutang USD 100.000 difactoring, dicairkan 80% di muka dengan biaya factoring 2% dari nilai piutang. Berapa kas bersih yang diterima di muka (USD)?",
        answer: 78000,
        tolerance: 0,
        prefix: "USD ",
        solution: "Kas di muka = 80% x USD 100.000 = USD 80.000. Biaya = 2% x USD 100.000 = USD 2.000. Kas bersih = 80.000 - 2.000 = <strong>USD 78.000</strong>.",
        hint: "Kurangi pencairan di muka dengan biaya factoring.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen trade finance dengan ciri utamanya.",
        pairs: [
          { left: "Factoring", right: "Jual piutang jangka pendek, bisa with/without recourse" },
          { left: "Forfaiting", right: "Jual piutang jangka panjang, selalu without recourse" },
          { left: "Performance bond", right: "Jaminan bank atas kinerja kontrak" },
          { left: "Advance payment guarantee", right: "Jaminan bank atas uang muka pembeli" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: VOC dan kelahiran pembiayaan modern",
        html: "Untuk mendanai pelayaran dagang yang mahal dan berisiko, <strong>VOC</strong> pada <strong>1602</strong> menjadi perusahaan pertama yang menjual <strong>saham</strong> kepada publik lewat bursa di Amsterdam. Gagasan menghimpun modal dari banyak pihak untuk membiayai perdagangan inilah cikal bakal <strong>trade finance</strong> modern, dari factoring hingga bank guarantee yang menjaga arus kas eksportir.",
      },
      {
        type: "takeaways",
        items: [
          "Trade finance menutup jeda arus kas dalam perdagangan internasional.",
          "Factoring menjual piutang jangka pendek untuk kas segera.",
          "Forfaiting menjual piutang jangka panjang, selalu without recourse.",
          "Bank guarantee menambah kepercayaan tanpa menyetor uang penuh.",
          "Instrumen yang tepat menjaga modal kerja tetap berputar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama trade finance adalah?",
            options: ["Menaikkan harga jual", "Menutup jeda arus kas perdagangan", "Menghindari pajak", "Mengganti Incoterm"],
            answer: 1,
            explain: "Trade finance menyediakan modal kerja untuk menutup jeda antara biaya dan penerimaan.",
          },
          {
            q: "Ciri khas forfaiting adalah?",
            options: ["Selalu with recourse", "Selalu without recourse", "Hanya jangka pendek", "Tanpa instrumen jaminan"],
            answer: 1,
            explain: "Forfaiting selalu without recourse dan menjangkau tenor menengah-panjang.",
          },
          {
            q: "Factoring paling tepat untuk?",
            options: ["Piutang jangka pendek", "Pinjaman properti", "Pembelian saham", "Pembayaran pajak ekspor"],
            answer: 0,
            explain: "Factoring menjual piutang jangka pendek untuk memperoleh kas segera.",
          },
          {
            q: "Performance bond adalah contoh dari?",
            options: ["Factoring", "Forfaiting", "Bank guarantee", "Open account"],
            answer: 2,
            explain: "Performance bond adalah salah satu bentuk bank guarantee.",
          },
          {
            q: "Piutang USD 50.000, dicairkan 80% di muka. Kas di muka?",
            options: ["USD 40.000", "USD 50.000", "USD 10.000", "USD 4.000"],
            answer: 0,
            explain: "80% x USD 50.000 = USD 40.000.",
          },
        ],
      },
    ],
  },
];
