import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "instrumen-kebijakan-moneter",
    levelId: "instrumen",
    order: 1,
    title: "Instrumen Kebijakan Moneter",
    summary: "Alat-alat bank sentral untuk mengatur uang beredar: suku bunga acuan, operasi pasar terbuka, giro wajib minimum, dan fasilitas standing.",
    durationMin: 14,
    tags: ["instrumen", "BI-Rate", "operasi pasar terbuka", "GWM"],
    blocks: [
      {
        type: "paragraph",
        html: "Bank sentral punya beberapa <strong>alat</strong> untuk mengatur jumlah uang beredar dan biaya kredit. Dengan alat-alat ini, ia bisa <strong>mengerem</strong> ekonomi yang memanas (kontraktif) atau <strong>memacu</strong> ekonomi yang lesu (ekspansif).",
      },
      {
        type: "video",
        comp: "OperasiPasarTerbukaVideo",
        title: "Video: Operasi Pasar Terbuka",
        caption: "Menjual surat berharga menyerap uang, membelinya menambah uang beredar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat instrumen utama",
        html: "<strong>Suku bunga acuan (BI-Rate):</strong> sinyal arah kebijakan. <strong>Operasi pasar terbuka:</strong> jual-beli surat berharga. <strong>Giro wajib minimum (GWM):</strong> porsi simpanan yang wajib diendapkan bank. <strong>Fasilitas standing:</strong> tempat bank menaruh atau meminjam dana harian.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kontraktif vs ekspansif",
        html: "<strong>Kontraktif</strong> (menaikkan bunga, menjual surat berharga, menaikkan GWM) menyerap uang dan menekan inflasi. <strong>Ekspansif</strong> (kebalikannya) menambah uang dan mendorong pertumbuhan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser suku bunga acuan dari titik 6% untuk melihat arah dampaknya pada inflasi, pertumbuhan, dan nilai tukar.",
      },
      { type: "widget", widget: "SimulatorBIRate" },
      {
        type: "chart",
        variant: "bar",
        title: "Arah Dampak Instrumen Kontraktif (ilustrasi konsep)",
        unit: "arah perubahan",
        source: "ilustrasi konsep transmisi, bukan besaran pasti",
        note: "Langkah kontraktif menyerap likuiditas: uang beredar turun, suku bunga pasar naik, inflasi tertekan.",
        data: [
          { label: "Uang beredar", value: -1, color: "#fb7185" },
          { label: "Suku bunga pasar", value: 1, color: "#60a5fa" },
          { label: "Tekanan inflasi", value: -1, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menjinakkan inflasi tinggi",
        html: "Misalkan inflasi melonjak jauh di atas sasaran. Bank sentral merespons dengan <strong>menaikkan suku bunga acuan</strong> dan <strong>menjual surat berharga</strong> lewat operasi pasar terbuka. Likuiditas tersedot, suku bunga kredit naik, masyarakat menahan belanja dan utang, lalu permintaan mereda sehingga laju inflasi melambat. Konsekuensinya, pertumbuhan ekonomi ikut melambat, ongkos yang harus ditimbang.",
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini bersifat kontraktif (mengerem) atau ekspansif (memacu)?",
        buckets: ["Kontraktif", "Ekspansif"],
        items: [
          { text: "Menaikkan suku bunga acuan", bucket: "Kontraktif" },
          { text: "Membeli surat berharga dari pasar", bucket: "Ekspansif" },
          { text: "Menaikkan giro wajib minimum", bucket: "Kontraktif" },
          { text: "Menurunkan suku bunga acuan", bucket: "Ekspansif" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jika bank sentral menaikkan GWM dari 5% menjadi 8%, angka pengganda uang turun dari 20 menjadi berapa kali? (1/0,08)",
        answer: 12.5,
        tolerance: 0.1,
        suffix: " kali",
        solution: "Angka pengganda baru = 1 / 0,08 = <strong>12,5 kali</strong>, turun dari 20 kali. Uang beredar pun mengecil.",
        hint: "Hitung 1 dibagi GWM yang baru (0,08).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen dengan cara kerjanya.",
        pairs: [
          { left: "Suku bunga acuan", right: "Sinyal arah kebijakan moneter" },
          { left: "Operasi pasar terbuka", right: "Jual-beli surat berharga" },
          { left: "Giro wajib minimum", right: "Porsi simpanan yang wajib diendapkan" },
          { left: "Fasilitas standing", right: "Tempat bank menaruh/meminjam dana harian" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Moneter 1998 dan Suku Bunga Tinggi",
        html: "Saat <strong>krisis moneter 1997-1998</strong>, rupiah anjlok dan inflasi meroket. Sebagai respons, suku bunga acuan sempat dinaikkan sangat tinggi, bahkan <strong>melampaui 60% per tahun</strong> pada puncaknya, untuk menahan pelarian modal dan menstabilkan rupiah. Langkah ekstrem ini menstabilkan harga tetapi memukul dunia usaha, menggambarkan betapa tajamnya trade-off dalam kebijakan moneter.",
      },
      {
        type: "takeaways",
        items: [
          "Instrumen utama: suku bunga acuan, operasi pasar terbuka, GWM, fasilitas standing.",
          "Kontraktif menyerap uang dan menekan inflasi; ekspansif sebaliknya.",
          "Menaikkan GWM menurunkan angka pengganda uang.",
          "Setiap langkah punya trade-off antara inflasi dan pertumbuhan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menjual surat berharga lewat operasi pasar terbuka akan?",
            options: ["Menambah uang beredar", "Menyerap uang beredar", "Tidak berpengaruh", "Menaikkan pajak"],
            answer: 1,
            explain: "Menjual surat berharga menarik uang dari peredaran (kontraktif).",
          },
          {
            q: "Menaikkan suku bunga acuan termasuk kebijakan?",
            options: ["Ekspansif", "Kontraktif", "Fiskal", "Netral selamanya"],
            answer: 1,
            explain: "Menaikkan bunga adalah langkah kontraktif untuk menekan inflasi.",
          },
          {
            q: "Giro wajib minimum adalah?",
            options: [
              "Pajak bank",
              "Porsi simpanan yang wajib diendapkan di bank sentral",
              "Bunga deposito",
              "Modal minimum bank",
            ],
            answer: 1,
            explain: "GWM adalah bagian simpanan yang wajib dicadangkan, bukan dipinjamkan.",
          },
          {
            q: "GWM dinaikkan dari 5% ke 10%. Angka pengganda uang?",
            options: ["Naik dari 20 ke 40", "Turun dari 20 ke 10", "Tetap", "Jadi nol"],
            answer: 1,
            explain: "1/0,05 = 20 menjadi 1/0,10 = 10, sehingga uang beredar mengecil.",
          },
          {
            q: "Kebijakan kontraktif umumnya berdampak pada pertumbuhan?",
            options: ["Mempercepat", "Memperlambat", "Tidak ada kaitan", "Menghapusnya"],
            answer: 1,
            explain: "Mengerem uang beredar menekan inflasi tetapi memperlambat ekonomi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "suku-bunga-acuan",
    levelId: "instrumen",
    order: 2,
    title: "Suku Bunga Acuan (BI-Rate)",
    summary: "Suku bunga acuan adalah instrumen utama dan sinyal arah kebijakan moneter Bank Indonesia, dari BI Rate ke BI 7-Day Reverse Repo Rate, kembali disebut BI-Rate.",
    durationMin: 14,
    tags: ["BI-Rate", "suku bunga acuan", "transmisi", "Bank Indonesia"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Suku bunga acuan</strong> adalah instrumen <strong>utama</strong> kebijakan moneter sekaligus sinyal paling jelas tentang arah kebijakan bank sentral. Saat Bank Indonesia mengumumkan tingkat suku bunga acuan, seluruh pasar membaca pesannya: apakah BI sedang mengerem atau memacu ekonomi.",
      },
      {
        type: "paragraph",
        html: "Sejak tahun <strong>2016</strong>, Bank Indonesia memakai <strong>BI 7-Day (Reverse) Repo Rate</strong> sebagai suku bunga acuan, menggantikan BI Rate lama agar transmisi ke pasar lebih cepat. Sejak <strong>2024</strong>, nama yang dipakai kembali menjadi <strong>BI-Rate</strong>, namun perannya tetap sebagai jangkar suku bunga jangka pendek.",
      },
      {
        type: "video",
        comp: "SukuBungaAcuan",
        title: "Video: Suku Bunga Acuan",
        caption: "Bagaimana satu angka suku bunga menjadi sinyal arah seluruh kebijakan moneter.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Naik vs turun",
        html: "<strong>Menaikkan</strong> suku bunga = kontraktif: menekan inflasi, menarik modal masuk, rupiah cenderung menguat, ekonomi melambat. <strong>Menurunkan</strong> suku bunga = ekspansif: kredit lebih murah, belanja dan investasi terdorong, ekonomi dipacu.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa disebut acuan",
        html: "Suku bunga acuan menjadi <strong>patokan</strong> bagi suku bunga antarbank, deposito, hingga kredit. Ia tidak langsung mengatur bunga di bank, tetapi menggerakkan seluruh rantai melalui mekanisme transmisi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser suku bunga acuan dan amati arah dampaknya pada inflasi, pertumbuhan, dan nilai tukar rupiah.",
      },
      { type: "widget", widget: "SimulatorBIRate" },
      {
        type: "chart",
        variant: "line",
        title: "Ilustrasi Arah BI-Rate dan Inflasi",
        unit: "% per tahun",
        source: "ilustrasi pola kebijakan, bukan data periode tertentu",
        note: "Saat inflasi naik, suku bunga acuan biasanya dinaikkan; ketika inflasi mereda, bunga dapat diturunkan.",
        data: [
          { label: "T1", value: 3.5, color: "#60a5fa" },
          { label: "T2", value: 4.5, color: "#60a5fa" },
          { label: "T3", value: 5.75, color: "#60a5fa" },
          { label: "T4", value: 6.0, color: "#60a5fa" },
          { label: "T5", value: 5.75, color: "#60a5fa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menahan tekanan rupiah",
        html: "Misalkan modal asing keluar dan rupiah tertekan. Bank Indonesia <strong>menaikkan BI-Rate dari 5,75% menjadi 6,25%</strong>. Imbal hasil aset rupiah menjadi lebih menarik, sebagian modal tertahan atau masuk kembali, dan tekanan terhadap rupiah mereda. Biayanya, kredit menjadi lebih mahal sehingga pertumbuhan ekonomi sedikit melambat.",
      },
      {
        type: "case",
        title: "Sejarah: Pengenalan BI 7-Day Reverse Repo Rate 2016",
        html: "Pada <strong>19 Agustus 2016</strong>, Bank Indonesia resmi menjadikan <strong>BI 7-Day (Reverse) Repo Rate</strong> sebagai suku bunga acuan, menggantikan BI Rate yang berjangka 12 bulan. Tujuannya memperkuat <strong>transmisi</strong> kebijakan: dengan tenor 7 hari, perubahan suku bunga acuan lebih cepat tercermin di pasar uang dan suku bunga perbankan. Sejak 2024, istilah resmi kembali menjadi BI-Rate.",
      },
      {
        type: "calcExercise",
        prompt: "BI-Rate naik dari 5,75% menjadi 6,25%. Berapa basis poin (bps) kenaikannya? (1% = 100 bps)",
        answer: 50,
        tolerance: 1,
        suffix: " bps",
        solution: "Selisih 6,25% - 5,75% = 0,5% = <strong>50 bps</strong>.",
        hint: "Kurangkan kedua angka, lalu kalikan 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Dampak dari menaikkan suku bunga acuan termasuk yang mana?",
        buckets: ["Dampak menaikkan bunga", "Dampak menurunkan bunga"],
        items: [
          { text: "Rupiah cenderung menguat", bucket: "Dampak menaikkan bunga" },
          { text: "Kredit menjadi lebih murah", bucket: "Dampak menurunkan bunga" },
          { text: "Tekanan inflasi menurun", bucket: "Dampak menaikkan bunga" },
          { text: "Belanja dan investasi terdorong", bucket: "Dampak menurunkan bunga" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Suku bunga acuan adalah instrumen utama dan sinyal arah kebijakan moneter.",
          "Sejak 2016 dipakai BI 7-Day (Reverse) Repo Rate; sejak 2024 disebut BI-Rate lagi.",
          "Menaikkan bunga bersifat kontraktif; menurunkan bunga bersifat ekspansif.",
          "Bunga acuan menjadi patokan bunga antarbank, deposito, dan kredit.",
          "Perubahan bunga acuan menggerakkan inflasi, pertumbuhan, dan nilai tukar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Sejak 2016, suku bunga acuan Bank Indonesia adalah?",
            options: ["BI Rate 12 bulan", "BI 7-Day (Reverse) Repo Rate", "Suku bunga deposito", "LPS Rate"],
            answer: 1,
            explain: "Sejak 19 Agustus 2016 acuannya BI 7-Day (Reverse) Repo Rate agar transmisi lebih cepat.",
          },
          {
            q: "Menaikkan suku bunga acuan umumnya membuat rupiah?",
            options: ["Melemah", "Menguat", "Tidak berubah", "Hilang"],
            answer: 1,
            explain: "Imbal hasil aset rupiah naik sehingga menarik modal dan menguatkan rupiah.",
          },
          {
            q: "Menurunkan suku bunga acuan termasuk kebijakan?",
            options: ["Kontraktif", "Ekspansif", "Fiskal", "Netral"],
            answer: 1,
            explain: "Bunga turun membuat kredit murah dan memacu ekonomi, ini ekspansif.",
          },
          {
            q: "BI-Rate naik dari 6% ke 6,5%. Berapa basis poin?",
            options: ["5 bps", "50 bps", "500 bps", "0,5 bps"],
            answer: 1,
            explain: "0,5% setara 50 basis poin (1% = 100 bps).",
          },
          {
            q: "Mengapa suku bunga acuan disebut sinyal arah kebijakan?",
            options: [
              "Karena ditetapkan harian oleh bank",
              "Karena pasar membacanya sebagai arah mengerem atau memacu ekonomi",
              "Karena menggantikan pajak",
              "Karena hanya berlaku untuk valas",
            ],
            answer: 1,
            explain: "Pengumuman bunga acuan memberi tahu pasar apakah BI mengetatkan atau melonggarkan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "operasi-pasar-terbuka",
    levelId: "instrumen",
    order: 3,
    title: "Operasi Pasar Terbuka",
    summary: "Bank sentral menjual atau membeli surat berharga untuk menyerap atau menambah likuiditas di pasar uang.",
    durationMin: 14,
    tags: ["operasi pasar terbuka", "SBI", "likuiditas", "reverse repo"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Operasi pasar terbuka (OPT)</strong> adalah cara bank sentral mengatur likuiditas dengan <strong>menjual atau membeli surat berharga</strong> di pasar uang. Inilah instrumen paling lentur karena bisa dilakukan setiap hari sesuai kebutuhan likuiditas perbankan.",
      },
      {
        type: "paragraph",
        html: "Surat berharga yang dipakai antara lain <strong>SBI (Sertifikat Bank Indonesia)</strong>, <strong>SBN (Surat Berharga Negara)</strong>, transaksi <strong>reverse repo</strong>, dan <strong>term deposit</strong>. Lewat instrumen-instrumen ini BI bisa menyetel jumlah uang yang beredar di sistem perbankan.",
      },
      {
        type: "video",
        comp: "OperasiPasarTerbukaVideo",
        title: "Video: Operasi Pasar Terbuka",
        caption: "Menjual surat berharga menyerap uang, membelinya menambah uang beredar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Menjual vs membeli",
        html: "<strong>Menjual</strong> surat berharga = bank membayar tunai ke BI, uang tersedot keluar dari peredaran (kontraktif). <strong>Membeli</strong> surat berharga = BI membayar tunai ke bank, uang masuk ke peredaran (ekspansif).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Menyerap atau menambah likuiditas",
        html: "OPT bersifat dua arah. Saat likuiditas berlebih dan inflasi mengancam, BI <strong>menyerap</strong> uang. Saat likuiditas seret, BI <strong>menambah</strong> uang agar pasar uang tetap lancar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung bagaimana suntikan atau penyerapan likuiditas berlipat melalui sistem perbankan dengan angka pengganda uang.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Likuiditas yang Diserap vs Ditambah",
        unit: "Rp triliun",
        source: "ilustrasi konsep OPT, bukan data lelang tertentu",
        note: "Saldo positif berarti BI menyerap likuiditas (menjual); saldo negatif berarti menambah likuiditas (membeli).",
        data: [
          { label: "Serap (jual SBI)", value: 40, color: "#fb7185" },
          { label: "Serap (term deposit)", value: 25, color: "#fb7185" },
          { label: "Tambah (beli SBN)", value: -30, color: "#34d399" },
          { label: "Tambah (repo)", value: -15, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menyerap kelebihan likuiditas",
        html: "Misalkan perbankan kelebihan dana sehingga ada tekanan inflasi. BI <strong>menjual SBI senilai Rp40 triliun</strong> lewat lelang. Bank-bank membayar tunai dan menerima sertifikat, sehingga <strong>Rp40 triliun tersedot</strong> dari peredaran. Likuiditas mengetat, suku bunga pasar uang naik, dan tekanan permintaan mereda.",
      },
      {
        type: "case",
        title: "Sejarah: SBI sebagai instrumen utama OPT sejak 1984",
        html: "Sejak <strong>1984</strong>, Bank Indonesia menerbitkan <strong>Sertifikat Bank Indonesia (SBI)</strong> dan menjadikannya instrumen utama operasi pasar terbuka. SBI memungkinkan BI menyerap kelebihan likuiditas perbankan secara berkala melalui lelang. Selama puluhan tahun SBI menjadi tulang punggung pengelolaan likuiditas, sebelum dilengkapi instrumen lain seperti reverse repo SBN dan term deposit.",
      },
      {
        type: "calcExercise",
        prompt: "BI membeli SBN Rp10 triliun. Jika GWM 10% (angka pengganda 1/0,10), berapa triliun potensi penambahan uang beredar maksimal?",
        answer: 100,
        tolerance: 1,
        prefix: "Rp",
        suffix: " triliun",
        solution: "Angka pengganda = 1/0,10 = 10. Maka 10 x Rp10 triliun = <strong>Rp100 triliun</strong> potensi maksimal.",
        hint: "Kalikan suntikan awal dengan angka pengganda uang 1/GWM.",
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan OPT ini menyerap atau menambah likuiditas?",
        buckets: ["Menyerap likuiditas", "Menambah likuiditas"],
        items: [
          { text: "BI menjual SBI ke bank", bucket: "Menyerap likuiditas" },
          { text: "BI membeli SBN dari pasar", bucket: "Menambah likuiditas" },
          { text: "BI menerima term deposit dari bank", bucket: "Menyerap likuiditas" },
          { text: "BI melakukan repo (memberi pinjaman) ke bank", bucket: "Menambah likuiditas" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "OPT mengatur likuiditas dengan menjual atau membeli surat berharga.",
          "Instrumennya antara lain SBI, SBN, reverse repo, dan term deposit.",
          "Menjual surat berharga menyerap uang (kontraktif).",
          "Membeli surat berharga menambah uang (ekspansif).",
          "OPT lentur karena bisa dilakukan harian sesuai kebutuhan likuiditas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Saat BI menjual surat berharga lewat OPT, likuiditas?",
            options: ["Bertambah", "Berkurang (tersedot)", "Tetap", "Tidak terkait"],
            answer: 1,
            explain: "Bank membayar tunai untuk surat berharga, uang tersedot dari peredaran.",
          },
          {
            q: "Manakah yang termasuk instrumen OPT?",
            options: ["KTP", "SBI dan SBN", "Pajak penghasilan", "Setoran modal"],
            answer: 1,
            explain: "SBI, SBN, reverse repo, dan term deposit adalah instrumen OPT.",
          },
          {
            q: "Membeli surat berharga oleh BI bersifat?",
            options: ["Kontraktif", "Ekspansif", "Fiskal", "Netral"],
            answer: 1,
            explain: "Membeli surat berharga menambah uang beredar, ini ekspansif.",
          },
          {
            q: "Sejak tahun berapa SBI menjadi instrumen utama OPT?",
            options: ["1966", "1984", "1998", "2016"],
            answer: 1,
            explain: "SBI diterbitkan dan menjadi instrumen utama OPT sejak 1984.",
          },
          {
            q: "Mengapa OPT disebut instrumen yang lentur?",
            options: [
              "Karena hanya dipakai sekali setahun",
              "Karena bisa dilakukan harian sesuai kebutuhan likuiditas",
              "Karena mengubah undang-undang",
              "Karena menggantikan pajak",
            ],
            answer: 1,
            explain: "OPT dapat dilakukan setiap hari untuk menyetel likuiditas secara cepat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "giro-wajib-minimum",
    levelId: "instrumen",
    order: 4,
    title: "Giro Wajib Minimum (GWM)",
    summary: "Persentase dana pihak ketiga yang wajib diendapkan bank di bank sentral, yang mengatur kemampuan bank menyalurkan kredit dan angka pengganda uang.",
    durationMin: 14,
    tags: ["GWM", "giro wajib minimum", "angka pengganda uang", "likuiditas"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Giro Wajib Minimum (GWM)</strong> adalah <strong>persentase dana pihak ketiga</strong> (simpanan nasabah) yang wajib diendapkan setiap bank di bank sentral. Dana ini tidak boleh dipinjamkan, sehingga GWM langsung mengatur seberapa besar bank bisa menyalurkan kredit.",
      },
      {
        type: "paragraph",
        html: "GWM punya dua jenis: <strong>GWM rupiah</strong> untuk simpanan rupiah dan <strong>GWM valas</strong> untuk simpanan valuta asing. Dengan menyetel GWM, BI mengubah <strong>angka pengganda uang</strong>, yaitu 1 dibagi GWM, yang menentukan seberapa berlipat uang beredar di sistem perbankan.",
      },
      {
        type: "video",
        comp: "KebijakanMoneterVideo",
        title: "Video: Kebijakan Moneter",
        caption: "Bagaimana cadangan wajib bank mengatur jumlah uang yang berputar di ekonomi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Naik vs turun",
        html: "<strong>Menaikkan GWM</strong> = bank harus mengendapkan lebih banyak, dana untuk kredit berkurang, angka pengganda uang turun (kontraktif). <strong>Menurunkan GWM</strong> = lebih banyak dana bisa dipinjamkan, angka pengganda naik (ekspansif).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Angka pengganda uang",
        html: "Secara sederhana, angka pengganda uang = <strong>1 / GWM</strong>. Jika GWM 5%, angka pengganda 1/0,05 = 20 kali. Jika GWM 10%, turun menjadi 1/0,10 = 10 kali.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah tingkat GWM dan lihat bagaimana angka pengganda uang dan potensi uang beredar ikut berubah.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "bar",
        title: "GWM dan Angka Pengganda Uang (1/GWM)",
        unit: "kali lipat",
        source: "perhitungan rumus 1/GWM, ilustrasi edukatif",
        note: "Semakin tinggi GWM, semakin kecil angka pengganda uang, sehingga uang beredar lebih tertahan.",
        data: [
          { label: "GWM 4%", value: 25, color: "#34d399" },
          { label: "GWM 5%", value: 20, color: "#60a5fa" },
          { label: "GWM 8%", value: 12.5, color: "#fbbf24" },
          { label: "GWM 10%", value: 10, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Mengerem kredit yang terlalu panas",
        html: "Misalkan kredit tumbuh terlalu cepat dan inflasi mengancam. BI <strong>menaikkan GWM rupiah dari 5% menjadi 8%</strong>. Dana yang harus diendapkan bertambah, sehingga ruang bank menyalurkan kredit menyempit. Angka pengganda uang turun dari 20 menjadi 12,5 kali, dan laju pertumbuhan uang beredar melambat.",
      },
      {
        type: "case",
        title: "Sejarah: GWM averaging untuk fleksibilitas",
        html: "Selama bertahun-tahun GWM dipenuhi secara harian penuh, sehingga kaku. Bank Indonesia kemudian menerapkan konsep <strong>GWM rata-rata (averaging)</strong>, yaitu bank cukup memenuhi rata-rata GWM selama satu periode pemeliharaan, bukan setiap hari persis. Pendekatan ini membuat pengelolaan likuiditas harian bank lebih <strong>fleksibel</strong> dan pasar uang lebih stabil, tanpa mengubah fungsi GWM sebagai pengatur likuiditas.",
      },
      {
        type: "calcExercise",
        prompt: "Jika GWM 5%, berapa kali angka pengganda uang (1/GWM)?",
        answer: 20,
        tolerance: 0.1,
        suffix: " kali",
        solution: "Angka pengganda = 1 / 0,05 = <strong>20 kali</strong>.",
        hint: "Bagi 1 dengan 0,05.",
      },
      {
        type: "calcExercise",
        prompt: "BI menaikkan GWM menjadi 8%. Berapa kali angka pengganda uang sekarang (1/0,08)?",
        answer: 12.5,
        tolerance: 0.1,
        suffix: " kali",
        solution: "Angka pengganda = 1 / 0,08 = <strong>12,5 kali</strong>, turun dari 20 kali saat GWM 5%.",
        hint: "Bagi 1 dengan 0,08.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tingkat GWM dengan angka pengganda uangnya (1/GWM).",
        pairs: [
          { left: "GWM 4%", right: "25 kali" },
          { left: "GWM 5%", right: "20 kali" },
          { left: "GWM 8%", right: "12,5 kali" },
          { left: "GWM 10%", right: "10 kali" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "GWM adalah persentase dana pihak ketiga yang wajib diendapkan di bank sentral.",
          "Menaikkan GWM bersifat kontraktif; menurunkan GWM bersifat ekspansif.",
          "Angka pengganda uang = 1 / GWM.",
          "Ada GWM rupiah dan GWM valas.",
          "GWM averaging membuat pemenuhan cadangan lebih fleksibel.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "GWM adalah?",
            options: [
              "Pajak yang dibayar bank",
              "Persentase dana pihak ketiga yang wajib diendapkan di bank sentral",
              "Bunga kredit minimum",
              "Modal inti bank",
            ],
            answer: 1,
            explain: "GWM adalah porsi simpanan nasabah yang wajib dicadangkan, bukan dipinjamkan.",
          },
          {
            q: "Menaikkan GWM bersifat?",
            options: ["Ekspansif", "Kontraktif", "Fiskal", "Netral"],
            answer: 1,
            explain: "GWM naik mengurangi dana yang bisa dipinjamkan, ini kontraktif.",
          },
          {
            q: "Jika GWM 10%, angka pengganda uang (1/GWM) adalah?",
            options: ["100 kali", "10 kali", "1 kali", "0,1 kali"],
            answer: 1,
            explain: "1 / 0,10 = 10 kali.",
          },
          {
            q: "Menurunkan GWM akan membuat angka pengganda uang?",
            options: ["Turun", "Naik", "Tetap", "Nol"],
            answer: 1,
            explain: "GWM lebih kecil berarti 1/GWM lebih besar, angka pengganda naik.",
          },
          {
            q: "GWM averaging dimaksudkan untuk?",
            options: [
              "Menaikkan pajak bank",
              "Membuat pemenuhan cadangan lebih fleksibel selama periode pemeliharaan",
              "Menghapus GWM valas",
              "Mengganti suku bunga acuan",
            ],
            answer: 1,
            explain: "Bank cukup memenuhi rata-rata GWM sepanjang periode, bukan harian persis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kebijakan-makroprudensial",
    levelId: "instrumen",
    order: 5,
    title: "Kebijakan Makroprudensial",
    summary: "Kebijakan untuk menjaga stabilitas sistem keuangan secara menyeluruh, bukan per bank, dengan instrumen countercyclical seperti LTV, RIM, dan CCB.",
    durationMin: 14,
    tags: ["makroprudensial", "LTV", "RIM", "CCB", "stabilitas sistem keuangan"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain kebijakan moneter, Bank Indonesia juga menjalankan <strong>kebijakan makroprudensial</strong>, yaitu kebijakan untuk menjaga <strong>stabilitas sistem keuangan secara menyeluruh</strong>. Fokusnya bukan kesehatan satu bank, melainkan risiko yang bisa menjalar ke seluruh sistem.",
      },
      {
        type: "paragraph",
        html: "Bedanya dengan pengawasan mikroprudensial: mikroprudensial menjaga <strong>satu bank</strong> agar sehat, sedangkan makroprudensial menjaga <strong>sistem</strong> agar tidak runtuh bersama-sama, misalnya ketika kredit tumbuh berlebihan dan membentuk gelembung.",
      },
      {
        type: "video",
        comp: "KebijakanMoneterVideo",
        title: "Video: Kebijakan Moneter",
        caption: "Menjaga stabilitas sistem keuangan agar risiko tidak menjalar ke seluruh ekonomi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga instrumen contoh",
        html: "<strong>LTV (Loan to Value):</strong> batas rasio kredit terhadap nilai agunan untuk KPR dan kendaraan. <strong>RIM (Rasio Intermediasi Makroprudensial):</strong> mendorong bank menyalurkan kredit secara seimbang. <strong>CCB (Countercyclical Capital Buffer):</strong> bantalan modal tambahan saat kredit tumbuh terlalu cepat.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bersifat countercyclical",
        html: "Kebijakan makroprudensial bekerja melawan siklus: <strong>diperketat saat ekonomi memanas</strong> agar tidak terbentuk gelembung, dan <strong>dilonggarkan saat ekonomi lesu</strong> agar kredit kembali mengalir.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur kondisi ekonomi dan amati bagaimana bauran kebijakan diperketat atau dilonggarkan untuk menjaga keseimbangan.",
      },
      { type: "widget", widget: "SimulatorKebijakanMoneter" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Rasio LTV pada Fase Siklus",
        unit: "% maksimal kredit terhadap agunan",
        source: "ilustrasi konsep countercyclical, bukan angka regulasi tertentu",
        note: "LTV diperketat (lebih rendah) saat ekonomi memanas dan dilonggarkan (lebih tinggi) saat lesu untuk menggerakkan kredit.",
        data: [
          { label: "Ekonomi memanas (ketat)", value: 80, color: "#fb7185" },
          { label: "Kondisi normal", value: 90, color: "#60a5fa" },
          { label: "Ekonomi lesu (longgar)", value: 100, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Melonggarkan LTV untuk memacu KPR",
        html: "Misalkan ekonomi lesu dan penjualan properti seret. BI <strong>melonggarkan rasio LTV</strong> sehingga uang muka KPR bisa lebih kecil. Dengan LTV naik dari 85% menjadi 100%, pembeli rumah seharga Rp500 juta yang tadinya butuh uang muka Rp75 juta kini bisa nyaris tanpa uang muka. Permintaan KPR terdorong dan sektor properti bergerak.",
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya makroprudensial setelah krisis 2008",
        html: "Krisis keuangan global <strong>2008</strong> menunjukkan bahwa bank yang sehat satu per satu pun bisa runtuh bersama ketika risiko sistemik menumpuk. Sejak itu, otoritas di seluruh dunia memperkuat <strong>kebijakan makroprudensial</strong>. Kerangka <strong>Basel III</strong> yang disepakati setelah krisis memperkenalkan antara lain bantalan modal countercyclical (CCB), dan banyak bank sentral, termasuk Bank Indonesia, mengadopsi instrumen seperti LTV dan RIM untuk meredam siklus kredit.",
      },
      {
        type: "calcExercise",
        prompt: "Harga rumah Rp500 juta. Dengan LTV 80%, berapa juta rupiah uang muka minimal yang harus disiapkan pembeli?",
        answer: 100,
        tolerance: 1,
        prefix: "Rp",
        suffix: " juta",
        solution: "Kredit maksimal = 80% x Rp500 juta = Rp400 juta. Uang muka = Rp500 juta - Rp400 juta = <strong>Rp100 juta</strong>.",
        hint: "Uang muka = (1 - LTV) x harga rumah.",
      },
      {
        type: "classifyExercise",
        prompt: "Instrumen ini termasuk kebijakan makroprudensial atau kebijakan moneter?",
        buckets: ["Makroprudensial", "Moneter"],
        items: [
          { text: "Rasio Loan to Value (LTV)", bucket: "Makroprudensial" },
          { text: "Suku bunga acuan (BI-Rate)", bucket: "Moneter" },
          { text: "Countercyclical Capital Buffer (CCB)", bucket: "Makroprudensial" },
          { text: "Operasi pasar terbuka", bucket: "Moneter" },
          { text: "Rasio Intermediasi Makroprudensial (RIM)", bucket: "Makroprudensial" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Makroprudensial menjaga stabilitas sistem keuangan secara menyeluruh, bukan per bank.",
          "Contoh instrumen: LTV, RIM, dan CCB.",
          "Bersifat countercyclical: diperketat saat memanas, dilonggarkan saat lesu.",
          "Berbeda dari mikroprudensial yang menjaga kesehatan satu bank.",
          "Diperkuat secara global setelah krisis keuangan 2008 (kerangka Basel III).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fokus kebijakan makroprudensial adalah?",
            options: [
              "Kesehatan satu bank tertentu",
              "Stabilitas sistem keuangan secara menyeluruh",
              "Penerimaan pajak negara",
              "Harga saham satu perusahaan",
            ],
            answer: 1,
            explain: "Makroprudensial menjaga sistem keuangan agar risiko tidak menjalar ke seluruhnya.",
          },
          {
            q: "Manakah instrumen makroprudensial?",
            options: ["BI-Rate", "Rasio Loan to Value (LTV)", "Operasi pasar terbuka", "Term deposit"],
            answer: 1,
            explain: "LTV, RIM, dan CCB adalah instrumen makroprudensial.",
          },
          {
            q: "Sifat countercyclical berarti kebijakan?",
            options: [
              "Selalu diperketat",
              "Diperketat saat memanas, dilonggarkan saat lesu",
              "Tidak pernah berubah",
              "Hanya berlaku saat krisis",
            ],
            answer: 1,
            explain: "Kebijakan bekerja melawan siklus untuk meredam gelembung dan menopang saat lesu.",
          },
          {
            q: "Rumah Rp600 juta, LTV 90%. Berapa uang muka minimal?",
            options: ["Rp30 juta", "Rp60 juta", "Rp90 juta", "Rp120 juta"],
            answer: 1,
            explain: "Uang muka = (1 - 0,90) x Rp600 juta = Rp60 juta.",
          },
          {
            q: "Kebijakan makroprudensial diperkuat secara global setelah?",
            options: ["Krisis 1929", "Krisis keuangan global 2008", "Pandemi 2020", "Krisis 1998"],
            answer: 1,
            explain: "Setelah krisis 2008, kerangka Basel III memperkuat instrumen makroprudensial.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "koridor-suku-bunga",
    levelId: "instrumen",
    order: 6,
    title: "Koridor Suku Bunga & Pasar Uang Antarbank",
    summary: "Bank sentral memagari suku bunga pasar uang antarbank dengan koridor: lantai dari fasilitas simpanan dan atap dari fasilitas pinjaman, dengan suku bunga acuan di tengah.",
    durationMin: 15,
    tags: ["koridor suku bunga", "pasar uang antarbank", "fasilitas standing", "deposit facility", "lending facility"],
    blocks: [
      {
        type: "paragraph",
        html: "Bank sentral tidak menyetir suku bunga pasar uang satu per satu. Sebaliknya, ia memasang sebuah <strong>koridor suku bunga</strong>, yaitu pagar atas dan pagar bawah, lalu membiarkan suku bunga <strong>pasar uang antarbank</strong> bergerak di dalamnya. Dengan begitu, suku bunga harian tetap berada dekat suku bunga acuan tanpa harus dipatok kaku.",
      },
      {
        type: "paragraph",
        html: "Pagar bawah (<strong>lantai</strong>) berasal dari <strong>fasilitas simpanan</strong> (deposit facility), yaitu bunga yang diterima bank ketika menaruh kelebihan dana di bank sentral. Pagar atas (<strong>atap</strong>) berasal dari <strong>fasilitas pinjaman</strong> (lending facility), yaitu bunga yang dibayar bank ketika meminjam dana dari bank sentral. <strong>Suku bunga acuan</strong> berada di tengah koridor.",
      },
      {
        type: "video",
        comp: "KoridorSukuBungaVideo",
        title: "Video: Koridor Suku Bunga",
        caption: "Bagaimana lantai dan atap memagari pergerakan suku bunga antarbank.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lantai, atap, dan tengah",
        html: "<strong>Lantai = fasilitas simpanan (deposit facility):</strong> bunga saat bank menaruh kelebihan dana di bank sentral. <strong>Atap = fasilitas pinjaman (lending facility):</strong> bunga saat bank meminjam dari bank sentral. <strong>Suku bunga acuan</strong> ada di tengah sebagai jangkar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa suku bunga antarbank tak menembus pagar",
        html: "Tidak ada bank yang mau <strong>meminjam di pasar lebih mahal daripada atap</strong>, karena bisa langsung pinjam ke bank sentral di tingkat atap. Tidak ada pula bank yang mau <strong>menyimpan di pasar lebih murah daripada lantai</strong>, karena bisa menaruhnya di bank sentral di tingkat lantai. Maka suku bunga antarbank terkurung di dalam koridor.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur suku bunga acuan dan lebar koridor, lalu lihat di mana lantai dan atap berada serta bagaimana suku bunga antarbank ikut bergeser.",
      },
      { type: "widget", widget: "SimulatorKoridorSukuBunga" },
      {
        type: "chart",
        variant: "line",
        title: "Koridor Suku Bunga (acuan 6%, koridor plus minus 1%)",
        unit: "% per tahun",
        source: "ilustrasi konsep koridor, bukan data periode tertentu",
        note: "Suku bunga antarbank bergerak di antara lantai 5% dan atap 7%, mengikuti suku bunga acuan 6% di tengah.",
        data: [
          { label: "Atap (lending)", value: 7.0, color: "#fb7185" },
          { label: "Antarbank", value: 6.1, color: "#fbbf24" },
          { label: "Acuan", value: 6.0, color: "#60a5fa" },
          { label: "Antarbank", value: 5.9, color: "#fbbf24" },
          { label: "Lantai (deposit)", value: 5.0, color: "#34d399" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Koridor sempit = kendali ketat",
        html: "Semakin <strong>sempit</strong> koridor, semakin sedikit ruang gerak suku bunga antarbank, sehingga kendali bank sentral makin <strong>ketat</strong> dan suku bunga harian makin stabil di dekat acuan. Koridor yang lebar memberi pasar lebih banyak ruang berfluktuasi.",
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung lantai dan atap",
        html: "Suku bunga acuan ditetapkan <strong>6%</strong> dengan koridor <strong>plus minus 1%</strong>. Maka <strong>lantai = 6% - 1% = 5%</strong> (fasilitas simpanan) dan <strong>atap = 6% + 1% = 7%</strong> (fasilitas pinjaman). Lebar koridor 2%, atau 200 basis poin. Suku bunga pasar uang antarbank, misalnya 6,1%, tetap berada di antara 5% dan 7%.",
      },
      {
        type: "case",
        title: "Sejarah: Kerangka koridor operasional sejak 1990-an dan 2000-an",
        html: "Banyak bank sentral modern beralih ke <strong>kerangka koridor (channel/corridor system)</strong> untuk operasi moneter sejak <strong>era 1990-an hingga 2000-an</strong>. Bank sentral seperti Bank Sentral Eropa (yang mulai beroperasi <strong>1999</strong>) menjalankan koridor dengan fasilitas simpanan sebagai lantai dan fasilitas pinjaman marjinal sebagai atap. Pendekatan ini menggeser fokus dari menarget jumlah uang ke <strong>menarget suku bunga jangka pendek</strong> secara langsung lewat pagar lantai dan atap.",
      },
      {
        type: "calcExercise",
        prompt: "Suku bunga acuan 6% dengan koridor plus minus 1%. Berapa persen tingkat atap (fasilitas pinjaman)?",
        answer: 7,
        tolerance: 0.01,
        suffix: "%",
        solution: "Atap = acuan + lebar atas = 6% + 1% = <strong>7%</strong>.",
        hint: "Tambahkan lebar koridor ke suku bunga acuan.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan lantai 5% dan atap 7%, berapa basis poin lebar koridor seluruhnya? (1% = 100 bps)",
        answer: 200,
        tolerance: 1,
        suffix: " bps",
        solution: "Lebar = atap - lantai = 7% - 5% = 2% = <strong>200 bps</strong>.",
        hint: "Kurangkan lantai dari atap, lalu kalikan 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Tingkat ini adalah lantai, atap, atau acuan dalam koridor?",
        buckets: ["Lantai (deposit facility)", "Atap (lending facility)", "Acuan (tengah)"],
        items: [
          { text: "Bunga saat bank menaruh kelebihan dana di bank sentral", bucket: "Lantai (deposit facility)" },
          { text: "Bunga saat bank meminjam dana dari bank sentral", bucket: "Atap (lending facility)" },
          { text: "Suku bunga jangkar di tengah koridor", bucket: "Acuan (tengah)" },
          { text: "Pagar bawah pergerakan suku bunga antarbank", bucket: "Lantai (deposit facility)" },
          { text: "Pagar atas pergerakan suku bunga antarbank", bucket: "Atap (lending facility)" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Koridor suku bunga memagari pergerakan suku bunga pasar uang antarbank.",
          "Lantai = fasilitas simpanan (deposit facility); atap = fasilitas pinjaman (lending facility).",
          "Suku bunga acuan berada di tengah koridor sebagai jangkar.",
          "Suku bunga antarbank tak menembus pagar karena ada alternatif di bank sentral.",
          "Koridor sempit berarti kendali lebih ketat dan suku bunga harian lebih stabil.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Lantai koridor suku bunga berasal dari?",
            options: [
              "Fasilitas pinjaman (lending facility)",
              "Fasilitas simpanan (deposit facility)",
              "Pajak bank",
              "Giro wajib minimum",
            ],
            answer: 1,
            explain: "Lantai adalah bunga fasilitas simpanan saat bank menaruh kelebihan dana di bank sentral.",
          },
          {
            q: "Suku bunga acuan 6% dengan koridor plus minus 1%. Atapnya?",
            options: ["5%", "6%", "7%", "8%"],
            answer: 2,
            explain: "Atap = 6% + 1% = 7% (fasilitas pinjaman).",
          },
          {
            q: "Mengapa suku bunga antarbank tidak naik di atas atap?",
            options: [
              "Karena dilarang undang-undang pidana",
              "Karena bank bisa meminjam langsung ke bank sentral di tingkat atap",
              "Karena tidak ada yang butuh dana",
              "Karena GWM melarangnya",
            ],
            answer: 1,
            explain: "Tak ada bank mau pinjam lebih mahal daripada atap karena bisa pinjam ke bank sentral.",
          },
          {
            q: "Koridor yang lebih sempit berarti?",
            options: [
              "Kendali bank sentral lebih longgar",
              "Kendali bank sentral lebih ketat dan suku bunga lebih stabil",
              "Suku bunga bebas berfluktuasi",
              "Suku bunga acuan dihapus",
            ],
            answer: 1,
            explain: "Koridor sempit menyisakan sedikit ruang gerak sehingga kendali makin ketat.",
          },
          {
            q: "Dengan lantai 5% dan atap 7%, lebar koridornya?",
            options: ["100 bps", "200 bps", "500 bps", "700 bps"],
            answer: 1,
            explain: "7% - 5% = 2% = 200 basis poin.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekspansif-vs-kontraktif",
    levelId: "instrumen",
    order: 7,
    title: "Kebijakan Moneter Ekspansif vs Kontraktif",
    summary: "Dua arah besar kebijakan moneter: ekspansif (longgar) untuk memacu ekonomi lesu dan kontraktif (ketat) untuk menekan inflasi saat ekonomi memanas.",
    durationMin: 15,
    tags: ["ekspansif", "kontraktif", "kebijakan longgar", "kebijakan ketat", "output gap"],
    blocks: [
      {
        type: "paragraph",
        html: "Apa pun instrumennya, arah kebijakan moneter selalu mengerucut ke dua pilihan: <strong>ekspansif (longgar)</strong> atau <strong>kontraktif (ketat)</strong>. Ekspansif memacu ekonomi yang lesu, kontraktif mengerem ekonomi yang memanas. Bank sentral memilih arah dengan menimbang kondisi <strong>inflasi terhadap sasaran</strong> dan <strong>output gap</strong> (jarak antara output aktual dan potensialnya).",
      },
      {
        type: "paragraph",
        html: "Arah <strong>ekspansif</strong> ditempuh dengan menurunkan suku bunga, membeli surat berharga, dan menurunkan GWM, sehingga uang beredar naik dan kredit lebih murah. Arah <strong>kontraktif</strong> adalah kebalikannya: menaikkan suku bunga, menjual surat berharga, dan menaikkan GWM, sehingga uang beredar tertahan dan inflasi tertekan.",
      },
      {
        type: "video",
        comp: "KebijakanMoneterVideo",
        title: "Video: Kebijakan Moneter",
        caption: "Dua arah kebijakan: melonggarkan untuk memacu, mengetatkan untuk mengerem.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ekspansif vs kontraktif",
        html: "<strong>Ekspansif (longgar):</strong> bunga turun, beli surat berharga, GWM turun, uang beredar naik, mendorong pertumbuhan. Dipakai saat ekonomi lesu atau resesi. <strong>Kontraktif (ketat):</strong> bunga naik, jual surat berharga, GWM naik, uang beredar turun, menekan inflasi. Dipakai saat ekonomi memanas.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Setiap arah punya risiko",
        html: "Kebijakan <strong>ekspansif</strong> berlebihan berisiko memicu <strong>inflasi</strong> dan gelembung harga aset. Kebijakan <strong>kontraktif</strong> yang terlalu kencang berisiko <strong>memperlambat pertumbuhan</strong> bahkan mendorong resesi. Karena itu dosis dan waktunya harus pas.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pilih kondisi ekonomi, lalu lihat apakah bauran kebijakan sebaiknya ekspansif atau kontraktif dan bagaimana dampaknya pada inflasi dan pertumbuhan.",
      },
      { type: "widget", widget: "SimulatorKebijakanMoneter" },
      {
        type: "chart",
        variant: "bar",
        title: "Arah Dampak: Ekspansif vs Kontraktif (ilustrasi konsep)",
        unit: "arah perubahan",
        source: "ilustrasi konsep transmisi, bukan besaran pasti",
        note: "Ekspansif menambah uang beredar dan pertumbuhan dengan risiko inflasi; kontraktif kebalikannya untuk menekan inflasi.",
        data: [
          { label: "Uang beredar (ekspansif)", value: 1, color: "#34d399" },
          { label: "Pertumbuhan (ekspansif)", value: 1, color: "#34d399" },
          { label: "Uang beredar (kontraktif)", value: -1, color: "#fb7185" },
          { label: "Tekanan inflasi (kontraktif)", value: -1, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih arah saat inflasi melebihi sasaran",
        html: "Misalkan sasaran inflasi 3% plus minus 1% (rentang 2% sampai 4%), tetapi inflasi aktual mencapai <strong>6%</strong>, jauh di atas batas atas. Karena ekonomi memanas dan inflasi terlampaui, bank sentral memilih arah <strong>kontraktif</strong>: menaikkan suku bunga acuan dan menjual surat berharga. Tujuannya menarik inflasi turun mendekati rentang sasaran, dengan konsekuensi pertumbuhan sedikit melambat.",
      },
      {
        type: "case",
        title: "Sejarah: Pelonggaran 2020 lalu pengetatan 2022-2023",
        html: "Saat <strong>pandemi COVID-19 pada 2020</strong>, hampir semua bank sentral besar menempuh kebijakan <strong>ekspansif</strong> agresif: memangkas suku bunga mendekati nol dan membeli surat berharga besar-besaran untuk menahan ekonomi yang anjlok. Ketika inflasi global melonjak pada <strong>2022 hingga 2023</strong>, arah berbalik menjadi <strong>kontraktif</strong>: bank sentral seperti Federal Reserve dan Bank Indonesia menaikkan suku bunga secara beruntun untuk menjinakkan inflasi. Satu siklus utuh dari longgar ke ketat dalam waktu singkat.",
      },
      {
        type: "calcExercise",
        prompt: "Sasaran inflasi 3% plus minus 1%. Jika inflasi aktual 6%, berapa poin persen inflasi melampaui batas ATAS sasaran (4%)?",
        answer: 2,
        tolerance: 0.01,
        suffix: " poin persen",
        solution: "Batas atas = 3% + 1% = 4%. Selisih = 6% - 4% = <strong>2 poin persen</strong>, sinyal kuat untuk arah kontraktif.",
        hint: "Hitung batas atas dulu (3% + 1%), lalu kurangkan dari inflasi aktual.",
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini termasuk kebijakan ekspansif atau kontraktif?",
        buckets: ["Ekspansif", "Kontraktif"],
        items: [
          { text: "Menurunkan suku bunga acuan", bucket: "Ekspansif" },
          { text: "Menjual surat berharga lewat operasi pasar terbuka", bucket: "Kontraktif" },
          { text: "Menurunkan giro wajib minimum", bucket: "Ekspansif" },
          { text: "Menaikkan suku bunga acuan", bucket: "Kontraktif" },
          { text: "Membeli surat berharga dari pasar", bucket: "Ekspansif" },
          { text: "Menaikkan giro wajib minimum", bucket: "Kontraktif" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Arah kebijakan moneter mengerucut ke dua pilihan: ekspansif atau kontraktif.",
          "Ekspansif (bunga turun, beli surat berharga, GWM turun) memacu ekonomi lesu.",
          "Kontraktif (bunga naik, jual surat berharga, GWM naik) menekan inflasi saat memanas.",
          "Bank sentral memilih arah sesuai inflasi terhadap sasaran dan output gap.",
          "Ekspansif berlebihan berisiko inflasi; kontraktif berlebihan memperlambat pertumbuhan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kebijakan moneter ekspansif umumnya membuat uang beredar?",
            options: ["Turun", "Naik", "Tetap", "Hilang"],
            answer: 1,
            explain: "Ekspansif menurunkan bunga dan menambah likuiditas sehingga uang beredar naik.",
          },
          {
            q: "Kapan kebijakan kontraktif biasanya dipakai?",
            options: [
              "Saat ekonomi lesu atau resesi",
              "Saat ekonomi memanas dan inflasi tinggi",
              "Saat tidak ada inflasi sama sekali",
              "Hanya saat pemilu",
            ],
            answer: 1,
            explain: "Kontraktif dipakai untuk mengerem ekonomi yang memanas dan menekan inflasi.",
          },
          {
            q: "Manakah langkah ekspansif?",
            options: [
              "Menaikkan suku bunga acuan",
              "Membeli surat berharga dan menurunkan GWM",
              "Menjual surat berharga",
              "Menaikkan GWM",
            ],
            answer: 1,
            explain: "Membeli surat berharga dan menurunkan GWM menambah uang beredar, ini ekspansif.",
          },
          {
            q: "Risiko utama kebijakan ekspansif yang berlebihan adalah?",
            options: [
              "Deflasi parah",
              "Inflasi dan gelembung harga aset",
              "Suku bunga negatif permanen",
              "Hilangnya bank sentral",
            ],
            answer: 1,
            explain: "Uang beredar yang terlalu banyak berisiko memicu inflasi dan gelembung.",
          },
          {
            q: "Pada 2020 lalu 2022-2023, arah kebijakan bank sentral besar berubah dari?",
            options: [
              "Kontraktif ke ekspansif",
              "Ekspansif (2020) ke kontraktif (2022-2023)",
              "Tidak berubah sama sekali",
              "Fiskal ke moneter",
            ],
            answer: 1,
            explain: "Pelonggaran agresif saat pandemi 2020 berbalik menjadi pengetatan saat inflasi melonjak 2022-2023.",
          },
        ],
      },
    ],
  },
];
