import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "nilai-tukar-dan-trilemma",
    levelId: "eksternal",
    order: 1,
    title: "Nilai Tukar, Cadangan Devisa & Trilemma",
    summary: "Rezim nilai tukar, peran cadangan devisa, dan dilema mendasar memilih dua dari tiga tujuan kebijakan (impossible trinity).",
    durationMin: 14,
    tags: ["nilai tukar", "cadangan devisa", "trilemma"],
    blocks: [
      {
        type: "paragraph",
        html: "Di ekonomi yang terbuka, kebijakan moneter tidak bisa mengabaikan dunia luar. <strong>Nilai tukar rupiah</strong>, arus modal asing, dan <strong>cadangan devisa</strong> saling terkait erat dengan suku bunga dan inflasi.",
      },
      {
        type: "video",
        comp: "TrilemmaVideo",
        title: "Video: Trilemma Kebijakan (Impossible Trinity)",
        caption: "Sebuah negara hanya bisa memilih dua dari tiga: kurs tetap, modal bebas, moneter mandiri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rezim nilai tukar",
        html: "<strong>Tetap (fixed):</strong> kurs dipatok, butuh cadangan besar. <strong>Mengambang bebas (free float):</strong> ditentukan pasar. <strong>Mengambang terkendali (managed float):</strong> ditentukan pasar tetapi bank sentral sesekali masuk menstabilkan. Indonesia menganut mengambang terkendali.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Trilemma kebijakan",
        html: "Sebuah negara <strong>tidak bisa</strong> sekaligus memiliki nilai tukar tetap, arus modal bebas, dan kebijakan moneter mandiri. Hanya <strong>dua dari tiga</strong> yang bisa dipilih bersamaan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pilih dua tujuan yang ingin dicapai, lalu lihat tujuan ketiga mana yang harus dikorbankan.",
      },
      { type: "widget", widget: "SimulatorTrilemma" },
      {
        type: "chart",
        variant: "area",
        title: "Cadangan Devisa sebagai Bulan Impor (ilustrasi konsep)",
        unit: "bulan impor",
        source: "ilustrasi konsep kecukupan cadangan",
        note: "Ambang aman internasional sekitar 3 bulan impor; cadangan yang tebal memberi ruang intervensi menjaga rupiah.",
        data: [
          { label: "Krisis", value: 2 },
          { label: "Minimum aman", value: 3 },
          { label: "Nyaman", value: 6 },
          { label: "Sangat kuat", value: 9 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Kecukupan cadangan devisa",
        html: "Sebuah negara punya cadangan devisa <strong>USD 140 miliar</strong> dengan impor sekitar <strong>USD 20 miliar per bulan</strong>. Maka cadangan setara 140 / 20 = <strong>7 bulan impor</strong>, jauh di atas ambang aman 3 bulan. Cadangan setebal ini memberi bank sentral amunisi untuk masuk ke pasar valas dan meredam gejolak rupiah saat modal asing keluar tiba-tiba.",
      },
      {
        type: "calcExercise",
        prompt: "Cadangan devisa USD 140 miliar, impor USD 20 miliar per bulan. Berapa bulan impor yang bisa dibiayai?",
        answer: 7,
        tolerance: 0,
        suffix: " bulan",
        solution: "Bulan impor = 140 / 20 = <strong>7 bulan</strong>, di atas ambang aman 3 bulan.",
        hint: "Bagi cadangan devisa dengan impor bulanan.",
      },
      {
        type: "calcExercise",
        prompt: "Jika impor naik menjadi USD 28 miliar per bulan dengan cadangan tetap USD 140 miliar, berapa bulan impor sekarang?",
        answer: 5,
        tolerance: 0,
        suffix: " bulan",
        solution: "140 / 28 = <strong>5 bulan</strong>, masih di atas ambang aman tetapi menurun.",
        hint: "Bagi cadangan dengan impor bulanan yang baru.",
      },
      {
        type: "classifyExercise",
        prompt: "Kombinasi pilihan ini mengorbankan tujuan yang mana (trilemma)?",
        buckets: ["Korbankan moneter mandiri", "Korbankan kurs tetap", "Korbankan modal bebas"],
        items: [
          { text: "Kurs tetap + arus modal bebas", bucket: "Korbankan moneter mandiri" },
          { text: "Arus modal bebas + moneter mandiri", bucket: "Korbankan kurs tetap" },
          { text: "Kurs tetap + moneter mandiri", bucket: "Korbankan modal bebas" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Runtuhnya Bretton Woods 1971",
        html: "Setelah Perang Dunia II, sistem <strong>Bretton Woods</strong> mematok mata uang dunia ke dolar AS yang dijamin emas. Sistem kurs tetap ini akhirnya runtuh ketika Amerika Serikat menghentikan konversi dolar ke emas pada <strong>1971</strong>. Dunia lalu beralih ke kurs mengambang. Peristiwa ini menegaskan betapa sulitnya mempertahankan kurs tetap ketika arus modal global makin bebas, persis inti trilemma kebijakan.",
      },
      {
        type: "takeaways",
        items: [
          "Rezim nilai tukar: tetap, mengambang bebas, atau mengambang terkendali.",
          "Indonesia menganut mengambang terkendali.",
          "Trilemma: hanya dua dari tiga (kurs tetap, modal bebas, moneter mandiri).",
          "Cadangan devisa diukur dalam bulan impor; ambang aman sekitar 3 bulan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Trilemma kebijakan menyatakan sebuah negara bisa memilih?",
            options: ["Ketiga tujuan", "Hanya dua dari tiga tujuan", "Hanya satu", "Tidak satu pun"],
            answer: 1,
            explain: "Impossible trinity: hanya dua dari tiga yang bisa dicapai bersamaan.",
          },
          {
            q: "Rezim nilai tukar Indonesia saat ini adalah?",
            options: ["Tetap (fixed)", "Mengambang terkendali", "Dipatok ke emas", "Tanpa nilai tukar"],
            answer: 1,
            explain: "Indonesia menganut mengambang terkendali (managed float).",
          },
          {
            q: "Cadangan devisa biasanya diukur kecukupannya dalam?",
            options: ["Jumlah bank", "Bulan impor", "Jumlah penduduk", "Persen pajak"],
            answer: 1,
            explain: "Kecukupan cadangan diukur dalam berapa bulan impor yang bisa dibiayai.",
          },
          {
            q: "Cadangan USD 120 miliar, impor USD 20 miliar/bulan. Berapa bulan impor?",
            options: ["3 bulan", "6 bulan", "9 bulan", "12 bulan"],
            answer: 1,
            explain: "120 / 20 = 6 bulan.",
          },
          {
            q: "Memilih kurs tetap dan arus modal bebas berarti mengorbankan?",
            options: ["Kemandirian moneter", "Cadangan devisa", "Ekspor", "Pajak"],
            answer: 0,
            explain: "Kombinasi itu menuntut suku bunga mengikuti luar negeri, hilang kemandirian moneter.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "rezim-nilai-tukar",
    levelId: "eksternal",
    order: 2,
    title: "Rezim Nilai Tukar: Tetap, Mengambang & Terkendali",
    summary: "Tiga cara negara mengelola kurs: dipatok (tetap), dilepas ke pasar (mengambang bebas), atau campuran (mengambang terkendali). Kelebihan, kekurangan, dan pilihan Indonesia.",
    durationMin: 14,
    tags: ["rezim kurs", "nilai tukar", "managed float"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap negara harus memilih bagaimana <strong>nilai tukar</strong> mata uangnya ditentukan. Pilihan ini bukan sekadar teknis, melainkan menentukan ruang gerak kebijakan moneter, kebutuhan cadangan devisa, dan kerentanan terhadap gejolak global.",
      },
      {
        type: "video",
        comp: "NilaiTukarVideo",
        title: "Video: Bagaimana Nilai Tukar Terbentuk",
        caption: "Permintaan dan penawaran mata uang menggerakkan kurs di pasar valas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga rezim utama",
        html: "<strong>Tetap (fixed):</strong> kurs dipatok pada nilai tertentu, sering lewat currency board; butuh cadangan devisa besar untuk mempertahankannya. <strong>Mengambang bebas (free float):</strong> kurs ditentukan murni oleh pasar tanpa campur tangan. <strong>Mengambang terkendali (managed float):</strong> kurs digerakkan pasar, tetapi bank sentral sesekali masuk meredam volatilitas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pilihan Indonesia",
        html: "Indonesia menganut <strong>mengambang terkendali</strong> sejak meninggalkan sistem rentang kurs (band) pada <strong>14 Agustus 1997</strong> di tengah krisis. Bank Indonesia tidak menargetkan level kurs tertentu, tetapi menjaga agar pergerakan rupiah tidak terlalu liar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser tekanan permintaan dan penawaran valas, lihat bagaimana kurs rupiah bergerak di tiap rezim.",
      },
      { type: "widget", widget: "SimulatorValas" },
      {
        type: "chart",
        variant: "bar",
        title: "Kebutuhan Cadangan Devisa per Rezim (ilustrasi konsep)",
        unit: "kebutuhan relatif",
        source: "ilustrasi konsep perbandingan rezim kurs",
        note: "Kurs tetap menuntut cadangan paling besar untuk mempertahankan patokan; mengambang bebas paling hemat cadangan.",
        data: [
          { label: "Tetap", value: 9, color: "#ef4444" },
          { label: "Terkendali", value: 5, color: "#f59e0b" },
          { label: "Mengambang bebas", value: 2, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tekanan pada kurs tetap",
        html: "Bayangkan bank sentral mematok kurs di <strong>Rp10.000 per dolar</strong>. Saat permintaan dolar melonjak, untuk menahan patokan bank sentral harus menjual cadangan. Jika ia menjual <strong>USD 2 miliar per hari</strong> dan cadangannya hanya <strong>USD 20 miliar</strong>, secara teori amunisi habis dalam 20 / 2 = <strong>10 hari</strong> bila tekanan tidak reda. Inilah kerapuhan rezim tetap saat kepercayaan pasar goyah.",
      },
      {
        type: "calcExercise",
        prompt: "Cadangan USD 20 miliar, bank sentral menjual USD 2 miliar per hari untuk menahan patokan. Berapa hari amunisi bertahan?",
        answer: 10,
        tolerance: 0,
        suffix: " hari",
        solution: "20 / 2 = <strong>10 hari</strong>. Tanpa reda, patokan tidak bisa dipertahankan.",
        hint: "Bagi cadangan dengan penjualan harian.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan ciri berikut ke rezim nilai tukar yang tepat.",
        buckets: ["Tetap", "Mengambang bebas", "Mengambang terkendali"],
        items: [
          { text: "Kurs dipatok pada nilai tertentu", bucket: "Tetap" },
          { text: "Butuh cadangan devisa paling besar", bucket: "Tetap" },
          { text: "Kurs ditentukan murni pasar", bucket: "Mengambang bebas" },
          { text: "Pasar menentukan, bank sentral sesekali intervensi", bucket: "Mengambang terkendali" },
          { text: "Dipakai Indonesia sejak 1997", bucket: "Mengambang terkendali" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Indonesia mengambangkan rupiah, 14 Agustus 1997",
        html: "Saat Krisis Finansial Asia menjalar, Bank Indonesia awalnya mempertahankan rupiah dengan sistem rentang kurs (intervention band) yang terus diperlebar. Tekanan jual yang dahsyat menguras cadangan, sehingga pada <strong>14 Agustus 1997</strong> rentang itu dihapus dan rupiah dibiarkan <strong>mengambang</strong>. Rupiah yang sebelumnya sekitar Rp2.500 per dolar lalu merosot tajam. Sejak itu Indonesia menganut mengambang terkendali.",
      },
      {
        type: "takeaways",
        items: [
          "Rezim tetap mematok kurs tetapi menuntut cadangan devisa besar.",
          "Mengambang bebas menyerahkan kurs sepenuhnya ke pasar.",
          "Mengambang terkendali adalah jalan tengah: pasar plus intervensi sesekali.",
          "Indonesia memakai mengambang terkendali sejak 14 Agustus 1997.",
          "Memilih rezim berarti menukar antara stabilitas kurs dan kebutuhan cadangan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Rezim nilai tukar yang menuntut cadangan devisa paling besar adalah?",
            options: ["Mengambang bebas", "Tetap (fixed)", "Mengambang terkendali", "Tanpa rezim"],
            answer: 1,
            explain: "Mempertahankan patokan kurs menuntut bank sentral siap menjual cadangan dalam jumlah besar.",
          },
          {
            q: "Pada rezim mengambang bebas, kurs ditentukan oleh?",
            options: ["Keputusan presiden", "Murni pasar", "Patokan emas", "Bank sentral asing"],
            answer: 1,
            explain: "Free float menyerahkan penentuan kurs sepenuhnya kepada permintaan dan penawaran pasar.",
          },
          {
            q: "Indonesia mulai mengambangkan rupiah pada?",
            options: ["1 Januari 1990", "14 Agustus 1997", "17 Agustus 1945", "1 Mei 2000"],
            answer: 1,
            explain: "Rentang kurs dihapus dan rupiah diambangkan pada 14 Agustus 1997 saat krisis.",
          },
          {
            q: "Ciri utama mengambang terkendali (managed float) adalah?",
            options: ["Kurs dipatok kaku", "Pasar menentukan, bank sentral sesekali intervensi", "Tidak ada pasar valas", "Kurs ditetapkan IMF"],
            answer: 1,
            explain: "Managed float menggabungkan mekanisme pasar dengan intervensi sesekali untuk meredam volatilitas.",
          },
          {
            q: "Cadangan USD 20 miliar, dijual USD 4 miliar per hari. Amunisi bertahan?",
            options: ["2 hari", "5 hari", "10 hari", "20 hari"],
            answer: 1,
            explain: "20 / 4 = 5 hari.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "intervensi-dan-cadangan-devisa",
    levelId: "eksternal",
    order: 3,
    title: "Intervensi Valas & Cadangan Devisa",
    summary: "Bagaimana bank sentral masuk ke pasar valas untuk meredam gejolak rupiah, mengapa amunisinya cadangan devisa, dan bagaimana mengukur kecukupannya dalam bulan impor.",
    durationMin: 15,
    tags: ["intervensi", "cadangan devisa", "valas"],
    blocks: [
      {
        type: "paragraph",
        html: "Saat rupiah bergerak terlalu liar, Bank Indonesia bisa masuk ke <strong>pasar valas</strong> membeli atau menjual dolar untuk meredam volatilitas. Tindakan ini disebut <strong>intervensi</strong>, dan amunisinya adalah <strong>cadangan devisa</strong>.",
      },
      {
        type: "video",
        comp: "BankSentralVideo",
        title: "Video: Peran Bank Sentral di Pasar Valas",
        caption: "Bank sentral menjaga stabilitas, bukan mematok level kurs tertentu.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Apa itu intervensi valas",
        html: "Saat rupiah melemah tajam, BI <strong>menjual dolar</strong> dari cadangan untuk menambah pasokan dan menahan pelemahan. Saat rupiah menguat berlebihan, BI bisa <strong>membeli dolar</strong> sekaligus menambah cadangan. Tujuannya meredam volatilitas, bukan melawan tren fundamental.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Triple intervention",
        html: "Bank Indonesia menjaga rupiah lewat tiga pintu sekaligus: pasar <strong>spot</strong> valas, <strong>DNDF</strong> (Domestic Non-Deliverable Forward), dan pembelian <strong>SBN</strong> (Surat Berharga Negara) di pasar sekunder. Pendekatan ini memperkuat efektivitas stabilisasi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung berapa bulan impor yang bisa dibiayai cadangan devisa, lalu lihat apakah masih di atas ambang aman.",
      },
      { type: "widget", widget: "KalkulatorCadanganDevisa" },
      {
        type: "callout",
        tone: "warn",
        title: "Ambang kecukupan",
        html: "Standar internasional menilai cadangan aman bila menutup <strong>sekitar 3 bulan impor</strong>. Standar lain yang lebih ketat: cadangan harus cukup menutup impor <strong>plus</strong> utang luar negeri jangka pendek yang jatuh tempo dalam setahun.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Cadangan Devisa dalam Bulan Impor (ilustrasi konsep)",
        unit: "bulan impor",
        source: "ilustrasi konsep kecukupan cadangan",
        note: "Saat impor naik atau cadangan terkuras intervensi, rasio bulan impor turun mendekati ambang aman 3 bulan.",
        data: [
          { label: "Tenang", value: 8 },
          { label: "Tekanan ringan", value: 7 },
          { label: "Intervensi besar", value: 5 },
          { label: "Krisis", value: 3 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Mengukur kecukupan cadangan",
        html: "Cadangan devisa <strong>USD 150 miliar</strong> dengan rata-rata impor <strong>USD 25 miliar per bulan</strong> setara 150 / 25 = <strong>6 bulan impor</strong>, dua kali lipat ambang aman 3 bulan. Jika BI lalu menjual <strong>USD 30 miliar</strong> untuk intervensi besar, cadangan turun ke USD 120 miliar atau 120 / 25 = <strong>4,8 bulan impor</strong>, masih aman tetapi menipis.",
      },
      {
        type: "calcExercise",
        prompt: "Cadangan devisa USD 150 miliar, impor USD 25 miliar per bulan. Berapa bulan impor?",
        answer: 6,
        tolerance: 0,
        suffix: " bulan",
        solution: "150 / 25 = <strong>6 bulan impor</strong>, dua kali ambang aman 3 bulan.",
        hint: "Bagi cadangan dengan impor bulanan.",
      },
      {
        type: "calcExercise",
        prompt: "Setelah intervensi menjual USD 30 miliar, cadangan jadi USD 120 miliar. Dengan impor USD 25 miliar/bulan, berapa bulan impor (1 desimal)?",
        answer: 4.8,
        tolerance: 0.1,
        suffix: " bulan",
        solution: "120 / 25 = <strong>4,8 bulan impor</strong>, masih di atas ambang aman tetapi menurun.",
        hint: "Kurangi cadangan dengan intervensi dulu, lalu bagi dengan impor bulanan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah intervensi valas dengan maknanya.",
        pairs: [
          { left: "Intervensi spot", right: "Jual/beli dolar langsung di pasar tunai valas" },
          { left: "DNDF", right: "Kontrak forward valas yang diselesaikan dalam rupiah" },
          { left: "Pembelian SBN", right: "Stabilisasi lewat pasar surat berharga negara" },
          { left: "Bulan impor", right: "Ukuran kecukupan cadangan devisa" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Cadangan terkuras saat krisis 1997-1998",
        html: "Pada Krisis Finansial Asia <strong>1997-1998</strong>, Bank Indonesia mencoba menahan rupiah dengan intervensi besar-besaran sehingga cadangan devisa tergerus deras. Ketika amunisi menipis dan tekanan jual tak reda, mempertahankan kurs menjadi mustahil, dan rupiah pun diambangkan lalu terjun bebas. Pelajaran utamanya: intervensi hanya efektif meredam gejolak, bukan melawan arus modal yang fundamental.",
      },
      {
        type: "takeaways",
        items: [
          "Intervensi valas: bank sentral jual/beli dolar untuk meredam volatilitas rupiah.",
          "Amunisi intervensi adalah cadangan devisa.",
          "Kecukupan cadangan diukur dalam bulan impor; ambang aman sekitar 3 bulan.",
          "Triple intervention BI: spot, DNDF, dan pembelian SBN.",
          "Intervensi meredam gejolak, bukan melawan tren fundamental.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Saat rupiah melemah tajam, intervensi BI biasanya berupa?",
            options: ["Membeli dolar", "Menjual dolar dari cadangan", "Mencetak dolar", "Menutup pasar valas"],
            answer: 1,
            explain: "Menjual dolar menambah pasokan valas dan menahan pelemahan rupiah.",
          },
          {
            q: "Amunisi utama untuk intervensi valas adalah?",
            options: ["Pajak", "Cadangan devisa", "Utang baru", "Setoran modal bank"],
            answer: 1,
            explain: "Cadangan devisa adalah stok valas yang dipakai bank sentral untuk intervensi.",
          },
          {
            q: "Ambang aman kecukupan cadangan menurut standar internasional sekitar?",
            options: ["1 bulan impor", "3 bulan impor", "10 bulan impor", "24 bulan impor"],
            answer: 1,
            explain: "Standar umum menilai cadangan aman bila menutup sekitar 3 bulan impor.",
          },
          {
            q: "Yang BUKAN bagian triple intervention Bank Indonesia adalah?",
            options: ["Pasar spot", "DNDF", "Pembelian SBN", "Menaikkan pajak ekspor"],
            answer: 3,
            explain: "Triple intervention mencakup spot, DNDF, dan pembelian SBN, bukan kebijakan pajak.",
          },
          {
            q: "Cadangan USD 90 miliar, impor USD 30 miliar/bulan. Berapa bulan impor?",
            options: ["2 bulan", "3 bulan", "6 bulan", "9 bulan"],
            answer: 1,
            explain: "90 / 30 = 3 bulan, tepat di ambang aman.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "neraca-pembayaran-dan-moneter",
    levelId: "eksternal",
    order: 4,
    title: "Neraca Pembayaran & Kaitannya dengan Moneter",
    summary: "Neraca pembayaran mencatat seluruh transaksi suatu negara dengan dunia luar. Pahami transaksi berjalan, transaksi modal & finansial, dan bagaimana keduanya berkaitan dengan rupiah serta suku bunga.",
    durationMin: 15,
    tags: ["neraca pembayaran", "transaksi berjalan", "arus modal"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Neraca pembayaran</strong> (Balance of Payments/BoP) adalah catatan menyeluruh seluruh transaksi ekonomi suatu negara dengan dunia luar dalam suatu periode. Ia menjadi peta penting bagi kebijakan moneter karena menggerakkan permintaan dan penawaran rupiah.",
      },
      {
        type: "video",
        comp: "NeracaPembayaran",
        title: "Video: Anatomi Neraca Pembayaran",
        caption: "Transaksi berjalan dan transaksi modal yang saling menyeimbangkan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua komponen utama",
        html: "<strong>Transaksi berjalan (current account):</strong> ekspor dan impor barang & jasa, pendapatan primer (mis. bunga, dividen), dan transfer. <strong>Transaksi modal & finansial (capital & financial account):</strong> arus investasi langsung, investasi portofolio, dan utang luar negeri.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Defisit ditutup arus modal",
        html: "Jika <strong>transaksi berjalan defisit</strong> (impor lebih besar dari ekspor), kekurangannya ditutup oleh <strong>arus modal masuk</strong> seperti investasi asing dan utang. Selama modal terus masuk, defisit transaksi berjalan bisa dibiayai dengan tenang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Susun komponen ekspor, impor, dan arus modal, lalu lihat apakah neraca pembayaran surplus atau defisit.",
      },
      { type: "widget", widget: "KalkulatorNeracaPembayaran" },
      {
        type: "callout",
        tone: "warn",
        title: "Jembatan ke moneter",
        html: "Arus modal memengaruhi <strong>nilai tukar</strong> dan <strong>likuiditas</strong> dalam negeri. Sebaliknya, <strong>suku bunga</strong> memengaruhi arus modal: bunga yang lebih tinggi menarik modal masuk, menopang rupiah. Inilah mengapa BI memperhatikan neraca pembayaran saat menetapkan suku bunga.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komponen Neraca Pembayaran (ilustrasi konsep, USD miliar)",
        unit: "USD miliar",
        source: "ilustrasi konsep struktur BoP",
        note: "Defisit transaksi berjalan ditutup surplus transaksi modal & finansial sehingga neraca keseluruhan dapat surplus tipis.",
        data: [
          { label: "Transaksi berjalan", value: -8, color: "#ef4444" },
          { label: "Modal & finansial", value: 12, color: "#22c55e" },
          { label: "Neraca keseluruhan", value: 4, color: "#3b82f6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menutup defisit transaksi berjalan",
        html: "Sebuah negara mencatat <strong>transaksi berjalan defisit USD 8 miliar</strong> (impor melebihi ekspor) namun <strong>transaksi modal & finansial surplus USD 12 miliar</strong> berkat investasi asing dan utang. Maka neraca pembayaran keseluruhan = -8 + 12 = <strong>surplus USD 4 miliar</strong>, dan cadangan devisa bertambah. Selama modal masuk lebih besar dari defisit berjalan, rupiah relatif aman.",
      },
      {
        type: "calcExercise",
        prompt: "Transaksi berjalan defisit USD 8 miliar, transaksi modal & finansial surplus USD 12 miliar. Berapa neraca pembayaran keseluruhan (USD miliar)?",
        answer: 4,
        tolerance: 0,
        prefix: "USD ",
        suffix: " miliar",
        solution: "-8 + 12 = <strong>surplus USD 4 miliar</strong>; cadangan devisa bertambah.",
        hint: "Jumlahkan saldo transaksi berjalan dan transaksi modal & finansial.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan setiap transaksi ke komponen neraca pembayaran yang tepat.",
        buckets: ["Transaksi berjalan", "Transaksi modal & finansial"],
        items: [
          { text: "Ekspor batu bara ke luar negeri", bucket: "Transaksi berjalan" },
          { text: "Impor mesin pabrik", bucket: "Transaksi berjalan" },
          { text: "Pembayaran bunga utang ke kreditur asing", bucket: "Transaksi berjalan" },
          { text: "Investasi asing langsung membangun pabrik", bucket: "Transaksi modal & finansial" },
          { text: "Pembelian saham domestik oleh investor asing", bucket: "Transaksi modal & finansial" },
          { text: "Penarikan utang luar negeri baru", bucket: "Transaksi modal & finansial" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Taper tantrum 2013 menekan rupiah",
        html: "Pada <strong>2013</strong>, sinyal The Fed akan mengurangi pembelian obligasi (tapering) memicu <strong>taper tantrum</strong>: modal portofolio kabur dari negara berkembang. Indonesia yang saat itu menanggung <strong>defisit transaksi berjalan</strong> menjadi rentan, arus modal masuk berkurang, dan rupiah melemah signifikan. Bank Indonesia merespons dengan menaikkan suku bunga acuan untuk menahan arus keluar modal, contoh nyata jembatan antara neraca pembayaran dan kebijakan moneter.",
      },
      {
        type: "takeaways",
        items: [
          "Neraca pembayaran mencatat semua transaksi dengan dunia luar.",
          "Transaksi berjalan: ekspor-impor barang/jasa, pendapatan, transfer.",
          "Transaksi modal & finansial: investasi dan utang.",
          "Defisit transaksi berjalan ditutup arus modal masuk.",
          "Suku bunga memengaruhi arus modal; arus modal memengaruhi rupiah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ekspor dan impor barang masuk ke komponen?",
            options: ["Transaksi berjalan", "Transaksi modal", "Cadangan emas", "Anggaran negara"],
            answer: 0,
            explain: "Ekspor-impor barang & jasa adalah inti transaksi berjalan (current account).",
          },
          {
            q: "Defisit transaksi berjalan biasanya ditutup oleh?",
            options: ["Pajak", "Arus modal masuk", "Cetak uang", "Subsidi"],
            answer: 1,
            explain: "Kekurangan transaksi berjalan dibiayai arus modal masuk seperti investasi dan utang.",
          },
          {
            q: "Investasi asing langsung membangun pabrik dicatat di?",
            options: ["Transaksi berjalan", "Transaksi modal & finansial", "Neraca pajak", "Subsidi energi"],
            answer: 1,
            explain: "FDI adalah arus finansial, masuk transaksi modal & finansial.",
          },
          {
            q: "Suku bunga domestik yang lebih tinggi cenderung membuat arus modal?",
            options: ["Keluar", "Masuk", "Tidak berubah", "Berhenti total"],
            answer: 1,
            explain: "Imbal hasil yang lebih tinggi menarik modal asing masuk, menopang rupiah.",
          },
          {
            q: "Transaksi berjalan defisit USD 5 miliar, modal surplus USD 9 miliar. Neraca keseluruhan?",
            options: ["Defisit USD 4 miliar", "Surplus USD 4 miliar", "Nol", "Surplus USD 14 miliar"],
            answer: 1,
            explain: "-5 + 9 = surplus USD 4 miliar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "krisis-nilai-tukar",
    levelId: "eksternal",
    order: 5,
    title: "Krisis Nilai Tukar & Serangan Spekulatif",
    summary: "Saat kepercayaan jatuh dan modal kabur, kurs tetap diserang dan cadangan terkuras. Pahami anatomi krisis mata uang, model generasi krisis, dan dua kasus historis besar.",
    durationMin: 15,
    tags: ["krisis mata uang", "serangan spekulatif", "sudden stop"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Krisis nilai tukar</strong> terjadi ketika kepercayaan pasar runtuh, modal asing kabur tiba-tiba (<strong>sudden stop</strong>), dan kurs tetap diserang spekulan hingga cadangan devisa terkuras. Pelemahan mata uang bisa berlangsung sangat cepat dan dalam.",
      },
      {
        type: "video",
        comp: "NilaiTukarVideo",
        title: "Video: Saat Kurs Diserang Pasar",
        caption: "Bagaimana tekanan jual mengubah arah nilai tukar dengan cepat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Anatomi krisis",
        html: "Pemicunya bisa <strong>fundamental lemah</strong> (defisit besar, cadangan tipis, utang jangka pendek menumpuk) atau <strong>sudden stop</strong> arus modal. Spekulan menyerang kurs tetap dengan menjual mata uang dalam jumlah besar; bila cadangan habis, patokan jebol dan kurs terjun.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Generasi model krisis",
        html: "<strong>Generasi pertama:</strong> krisis akibat fundamental yang tidak konsisten (mis. defisit fiskal dibiayai cetak uang sambil mematok kurs). <strong>Generasi kedua:</strong> krisis <strong>self-fulfilling</strong>, yaitu ekspektasi pasar bahwa patokan akan jebol membuat semua orang menyerang sekaligus, sehingga patokan benar-benar jebol.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat trilemma saat krisis: mempertahankan kurs tetap di tengah arus modal bebas menuntut pengorbanan kemandirian moneter.",
      },
      { type: "widget", widget: "SimulatorTrilemma" },
      {
        type: "chart",
        variant: "line",
        title: "Depresiasi Rupiah saat Krisis 1997-1998 (Rp per USD, perkiraan)",
        unit: "Rp/USD",
        source: "perkiraan historis Krisis Finansial Asia",
        note: "Rupiah jatuh dari sekitar Rp2.500 menjadi lebih dari Rp16.000 per dolar pada puncaknya pertengahan 1998.",
        data: [
          { label: "Pertengahan 1997", value: 2500 },
          { label: "Akhir 1997", value: 5000 },
          { label: "Awal 1998", value: 10000 },
          { label: "Puncak 1998", value: 16000 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung dalamnya depresiasi",
        html: "Rupiah melemah dari <strong>Rp2.500</strong> menjadi <strong>Rp16.000 per dolar</strong>. Secara persentase, nilai rupiah terhadap dolar anjlok: (16.000 - 2.500) / 16.000 = sekitar <strong>84%</strong> kehilangan daya beli terhadap dolar bila dihitung dari kurs baru. Importir dan penanggung utang dolar terpukul keras, sementara cadangan devisa tak sanggup menahan tekanan jual.",
      },
      {
        type: "calcExercise",
        prompt: "Kurs melemah dari Rp2.500 menjadi Rp10.000 per dolar. Berapa kali lipat dolar menjadi lebih mahal dalam rupiah?",
        answer: 4,
        tolerance: 0,
        suffix: " kali",
        solution: "10.000 / 2.500 = <strong>4 kali lipat</strong>. Biaya impor dan utang dolar membengkak empat kali.",
        hint: "Bagi kurs baru dengan kurs lama.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan faktor berikut sebagai pemicu/penanda krisis atau peredam krisis.",
        buckets: ["Pemicu/penanda krisis", "Peredam krisis"],
        items: [
          { text: "Sudden stop arus modal asing", bucket: "Pemicu/penanda krisis" },
          { text: "Cadangan devisa tipis", bucket: "Pemicu/penanda krisis" },
          { text: "Utang luar negeri jangka pendek menumpuk", bucket: "Pemicu/penanda krisis" },
          { text: "Cadangan devisa tebal", bucket: "Peredam krisis" },
          { text: "Fundamental ekonomi sehat", bucket: "Peredam krisis" },
          { text: "Nilai tukar fleksibel sebagai peredam kejut", bucket: "Peredam krisis" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Asia 1997-1998 dan serangan pound 1992",
        html: "Pada <strong>Krisis Finansial Asia 1997-1998</strong>, rupiah jatuh dari sekitar <strong>Rp2.500</strong> ke lebih dari <strong>Rp16.000 per dolar</strong> pada puncaknya tahun 1998, menyeret krisis perbankan dan ekonomi. Sebelumnya, pada <strong>16 September 1992</strong> (Black Wednesday), spekulan termasuk <strong>George Soros</strong> menyerang <strong>pound sterling</strong> hingga Inggris terpaksa keluar dari mekanisme nilai tukar Eropa (ERM). Keduanya menunjukkan bahwa kurs tetap yang tak ditopang fundamental kuat akan jebol saat diserang.",
      },
      {
        type: "takeaways",
        items: [
          "Krisis mata uang muncul saat kepercayaan jatuh dan modal kabur (sudden stop).",
          "Spekulan menyerang kurs tetap; cadangan yang habis membuat patokan jebol.",
          "Generasi pertama: fundamental lemah. Generasi kedua: self-fulfilling.",
          "Rupiah jatuh dari sekitar Rp2.500 ke lebih dari Rp16.000/USD pada 1997-1998.",
          "Serangan pound 1992 (Soros) memaksa Inggris keluar dari ERM.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kaburnya modal asing secara tiba-tiba disebut?",
            options: ["Sudden stop", "Soft landing", "Quantitative easing", "Carry trade"],
            answer: 0,
            explain: "Sudden stop adalah penghentian mendadak arus modal masuk yang memicu krisis.",
          },
          {
            q: "Model krisis generasi kedua menekankan?",
            options: ["Hanya fundamental lemah", "Krisis self-fulfilling karena ekspektasi pasar", "Tidak ada peran spekulan", "Krisis akibat surplus besar"],
            answer: 1,
            explain: "Generasi kedua: ekspektasi bahwa patokan jebol membuat semua menyerang, sehingga benar-benar jebol.",
          },
          {
            q: "Pada puncak krisis 1998, rupiah melemah hingga sekitar?",
            options: ["Rp5.000/USD", "Rp16.000/USD", "Rp3.000/USD", "Rp50.000/USD"],
            answer: 1,
            explain: "Rupiah jatuh dari sekitar Rp2.500 ke lebih dari Rp16.000 per dolar pada puncaknya 1998.",
          },
          {
            q: "Black Wednesday 1992 adalah serangan spekulatif terhadap?",
            options: ["Rupiah", "Pound sterling Inggris", "Yen Jepang", "Dolar AS"],
            answer: 1,
            explain: "Pada 16 September 1992 spekulan termasuk Soros menyerang pound hingga Inggris keluar dari ERM.",
          },
          {
            q: "Kurs melemah dari Rp2.500 ke Rp7.500/USD. Dolar menjadi berapa kali lebih mahal?",
            options: ["2 kali", "3 kali", "4 kali", "5 kali"],
            answer: 1,
            explain: "7.500 / 2.500 = 3 kali lipat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "penentu-nilai-tukar",
    levelId: "eksternal",
    order: 6,
    title: "Apa yang Menentukan Nilai Tukar",
    summary: "Kekuatan yang membentuk kurs rupiah: paritas daya beli, paritas suku bunga, neraca pembayaran, dan sentimen pasar.",
    durationMin: 14,
    tags: ["nilai tukar", "PPP", "paritas", "Big Mac"],
    blocks: [
      {
        type: "paragraph",
        html: "Mengapa rupiah bisa Rp16.000 per dolar, bukan Rp7.000 atau Rp25.000? Nilai tukar dibentuk banyak kekuatan sekaligus, sebagian bekerja dalam jangka panjang, sebagian menggerakkan kurs dari hari ke hari.",
      },
      {
        type: "video",
        comp: "PenentuNilaiTukarVideo",
        title: "Video: Apa yang Menggerakkan Nilai Tukar",
        caption: "Paritas daya beli, paritas suku bunga, neraca pembayaran, dan sentimen pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Paritas Daya Beli (PPP)",
        html: "Dalam jangka panjang, kurs cenderung menyamakan harga barang yang sama antarnegara. Jika sekeranjang barang berharga lebih murah di Indonesia, rupiah cenderung menguat menuju nilai wajarnya. <strong>Indeks Big Mac</strong> adalah ilustrasi populer konsep ini.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Faktor lain",
        html: "<strong>Paritas suku bunga:</strong> bunga tinggi menarik modal masuk dan menguatkan mata uang. <strong>Neraca pembayaran:</strong> surplus menguatkan, defisit melemahkan. <strong>Sentimen pasar:</strong> dalam jangka pendek, ekspektasi dan risiko paling dominan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan harga Big Mac di Indonesia dan AS untuk menghitung kurs PPP, lalu bandingkan dengan kurs pasar.",
      },
      { type: "widget", widget: "KalkulatorPPP" },
      {
        type: "chart",
        variant: "bar",
        title: "Kurs PPP vs Kurs Pasar (ilustrasi indeks Big Mac)",
        unit: "Rp per USD",
        source: "ilustrasi konsep paritas daya beli",
        note: "Bila kurs PPP jauh di bawah kurs pasar, rupiah dinilai undervalued terhadap daya belinya.",
        data: [
          { label: "Kurs PPP (implied)", value: 7000, color: "#34d399" },
          { label: "Kurs pasar", value: 16000, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung kurs PPP ala Big Mac",
        html: "Sebuah Big Mac berharga <strong>Rp35.000</strong> di Indonesia dan <strong>USD 5</strong> di Amerika Serikat. Kurs PPP yang tersirat = 35.000 / 5 = <strong>Rp7.000 per USD</strong>. Jika kurs pasar Rp16.000, maka secara paritas daya beli rupiah tampak <strong>undervalued</strong> (lebih murah dari nilai wajarnya). Namun jangka pendek, kurs pasar bisa jauh menyimpang dari PPP karena arus modal dan sentimen.",
      },
      {
        type: "calcExercise",
        prompt: "Big Mac Rp35.000 di Indonesia dan USD 5 di AS. Berapa kurs PPP yang tersirat (Rp per USD)?",
        answer: 7000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Kurs PPP = harga di Indonesia / harga di AS = 35.000 / 5 = <strong>Rp7.000 per USD</strong>.",
        hint: "Bagi harga dalam rupiah dengan harga dalam dolar.",
      },
      {
        type: "calcExercise",
        prompt: "Jika harga Big Mac di Indonesia Rp48.000 dan di AS USD 6, berapa kurs PPP-nya (Rp per USD)?",
        answer: 8000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Kurs PPP = 48.000 / 6 = <strong>Rp8.000 per USD</strong>.",
        hint: "Bagi harga rupiah dengan harga dolar.",
      },
      {
        type: "classifyExercise",
        prompt: "Faktor ini lebih memengaruhi nilai tukar dalam jangka panjang atau jangka pendek?",
        buckets: ["Jangka panjang", "Jangka pendek"],
        items: [
          { text: "Paritas daya beli (harga barang setara)", bucket: "Jangka panjang" },
          { text: "Sentimen dan kepanikan pasar", bucket: "Jangka pendek" },
          { text: "Selisih inflasi antarnegara", bucket: "Jangka panjang" },
          { text: "Berita politik mendadak", bucket: "Jangka pendek" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Indeks Big Mac 1986",
        html: "Majalah <strong>The Economist</strong> memperkenalkan <strong>indeks Big Mac</strong> pada <strong>1986</strong> sebagai cara ringan menjelaskan paritas daya beli: karena Big Mac dijual di banyak negara dengan bahan serupa, membandingkan harganya memberi gambaran apakah sebuah mata uang terlalu kuat atau terlalu lemah. Meski sederhana dan tidak sempurna, indeks ini menjadi alat edukasi kurs yang populer di seluruh dunia.",
      },
      {
        type: "takeaways",
        items: [
          "Paritas daya beli (PPP) adalah jangkar nilai tukar jangka panjang.",
          "Kurs PPP = harga barang sama di dalam negeri dibagi harga di luar negeri.",
          "Paritas suku bunga dan neraca pembayaran ikut menentukan kurs.",
          "Jangka pendek, sentimen dan ekspektasi pasar paling dominan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Paritas daya beli (PPP) menyatakan bahwa dalam jangka panjang kurs cenderung?",
            options: [
              "Selalu tetap",
              "Menyamakan harga barang yang sama antarnegara",
              "Naik terus",
              "Tidak bisa diprediksi",
            ],
            answer: 1,
            explain: "PPP menyatakan kurs menyesuaikan agar harga barang setara antarnegara.",
          },
          {
            q: "Indeks Big Mac adalah ilustrasi dari?",
            options: ["Inflasi", "Paritas daya beli", "Suku bunga", "Pajak"],
            answer: 1,
            explain: "Indeks Big Mac mengilustrasikan paritas daya beli.",
          },
          {
            q: "Big Mac Rp40.000 di RI dan USD 5 di AS. Kurs PPP-nya?",
            options: ["Rp8.000", "Rp5.000", "Rp40.000", "Rp200.000"],
            answer: 0,
            explain: "40.000 / 5 = Rp8.000 per USD.",
          },
          {
            q: "Dalam jangka pendek, kurs paling dipengaruhi oleh?",
            options: ["Paritas daya beli", "Sentimen dan ekspektasi pasar", "Jumlah penduduk", "Harga emas saja"],
            answer: 1,
            explain: "Sentimen dan ekspektasi mendominasi pergerakan kurs jangka pendek.",
          },
          {
            q: "Bunga dalam negeri yang lebih tinggi cenderung membuat mata uang?",
            options: ["Melemah", "Menguat karena menarik modal masuk", "Tidak berubah", "Hilang"],
            answer: 1,
            explain: "Bunga tinggi menarik arus modal masuk sehingga mata uang menguat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "arus-modal-dan-hot-money",
    levelId: "eksternal",
    order: 7,
    title: "Arus Modal Asing & Uang Panas (Hot Money)",
    summary: "Beda investasi langsung yang stabil dengan uang panas jangka pendek, dan bagaimana pembalikan arus modal mengguncang rupiah.",
    durationMin: 14,
    tags: ["arus modal", "hot money", "taper tantrum", "sudden stop"],
    blocks: [
      {
        type: "paragraph",
        html: "Modal asing yang masuk bisa menjadi berkah sekaligus risiko. Tergantung jenisnya, modal asing dapat memperkuat ekonomi dalam jangka panjang, atau justru mengguncang rupiah ketika tiba-tiba keluar.",
      },
      {
        type: "video",
        comp: "NeracaPembayaran",
        title: "Video: Neraca Pembayaran",
        caption: "Arus modal asing tercatat dalam transaksi modal dan finansial neraca pembayaran.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua jenis arus modal",
        html: "<strong>Investasi langsung (FDI):</strong> membangun pabrik, jangka panjang, stabil, sulit ditarik mendadak. <strong>Investasi portofolio (uang panas / hot money):</strong> membeli saham dan surat utang jangka pendek, mudah masuk dan keluar mengejar imbal hasil.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko pembalikan arus (sudden stop)",
        html: "Uang panas menguatkan rupiah saat masuk, tetapi saat keluar tiba-tiba (mis. karena bunga global naik), rupiah bisa <strong>melemah tajam</strong> dalam waktu singkat. Inilah yang disebut sudden stop atau pembalikan arus modal.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Lihat bagaimana cadangan devisa, yang diukur dalam bulan impor, menjadi bantalan saat modal asing keluar.",
      },
      { type: "widget", widget: "KalkulatorCadanganDevisa" },
      {
        type: "chart",
        variant: "bar",
        title: "Stabilitas Jenis Arus Modal (ilustrasi konsep)",
        unit: "tingkat kestabilan relatif",
        source: "ilustrasi konsep arus modal",
        note: "FDI relatif stabil dan tahan guncangan; uang panas paling mudah membalik arah secara tiba-tiba.",
        data: [
          { label: "Investasi langsung (FDI)", value: 90, color: "#34d399" },
          { label: "Portofolio obligasi", value: 50, color: "#fbbf24" },
          { label: "Uang panas saham jk pendek", value: 25, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Cadangan sebagai bantalan",
        html: "Sebuah negara punya cadangan devisa <strong>USD 120 miliar</strong> dengan impor <strong>USD 20 miliar per bulan</strong>, setara <strong>6 bulan impor</strong>. Saat uang panas keluar dan menekan rupiah, bank sentral memakai sebagian cadangan untuk intervensi. Jika cadangan turun ke USD 100 miliar, daya tahannya menjadi 5 bulan impor, masih di atas ambang aman 3 bulan. Cadangan yang tebal memberi waktu meredam gejolak.",
      },
      {
        type: "calcExercise",
        prompt: "Cadangan devisa USD 120 miliar, impor USD 20 miliar per bulan. Berapa bulan impor daya tahannya?",
        answer: 6,
        tolerance: 0,
        suffix: " bulan",
        solution: "Bulan impor = 120 / 20 = <strong>6 bulan</strong>, di atas ambang aman 3 bulan.",
        hint: "Bagi cadangan devisa dengan impor bulanan.",
      },
      {
        type: "calcExercise",
        prompt: "Jika setelah intervensi cadangan turun ke USD 90 miliar dengan impor tetap USD 20 miliar per bulan, berapa bulan impor sekarang?",
        answer: 4.5,
        tolerance: 0.1,
        suffix: " bulan",
        solution: "90 / 20 = <strong>4,5 bulan</strong>, menurun tetapi masih di atas ambang aman.",
        hint: "Bagi cadangan yang baru dengan impor bulanan.",
      },
      {
        type: "classifyExercise",
        prompt: "Arus modal ini termasuk investasi langsung (stabil) atau uang panas (jangka pendek)?",
        buckets: ["Investasi langsung (FDI)", "Uang panas (hot money)"],
        items: [
          { text: "Perusahaan asing membangun pabrik di Indonesia", bucket: "Investasi langsung (FDI)" },
          { text: "Dana asing membeli surat utang jangka pendek mengejar bunga", bucket: "Uang panas (hot money)" },
          { text: "Investor membeli saham untuk dijual cepat saat untung", bucket: "Uang panas (hot money)" },
          { text: "Pendirian fasilitas produksi jangka panjang", bucket: "Investasi langsung (FDI)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Taper Tantrum 2013",
        html: "Pada <strong>2013</strong>, ketika bank sentral Amerika Serikat (The Fed) memberi sinyal akan mengurangi pembelian aset (tapering), investor global menarik dana dari negara berkembang untuk kembali ke aset dolar. Indonesia, yang saat itu mengandalkan arus modal portofolio, mengalami pelemahan rupiah yang tajam. Peristiwa <strong>taper tantrum</strong> ini menunjukkan betapa rentannya ekonomi terhadap pembalikan uang panas, dan mendorong penguatan cadangan serta bauran kebijakan.",
      },
      {
        type: "takeaways",
        items: [
          "Investasi langsung (FDI) stabil; investasi portofolio (uang panas) mudah membalik.",
          "Uang panas menguatkan rupiah saat masuk, menekan tajam saat keluar.",
          "Cadangan devisa menjadi bantalan saat terjadi pembalikan arus modal.",
          "Taper tantrum 2013 menunjukkan kerentanan terhadap uang panas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Yang termasuk arus modal jangka panjang dan stabil adalah?",
            options: ["Uang panas", "Investasi langsung (FDI)", "Portofolio jangka pendek", "Spekulasi harian"],
            answer: 1,
            explain: "FDI (membangun usaha) bersifat jangka panjang dan stabil.",
          },
          {
            q: "Uang panas (hot money) cirinya?",
            options: [
              "Sulit ditarik",
              "Mudah masuk dan keluar mengejar imbal hasil",
              "Selalu menguntungkan negara",
              "Tidak memengaruhi kurs",
            ],
            answer: 1,
            explain: "Uang panas adalah modal jangka pendek yang mudah berpindah.",
          },
          {
            q: "Saat uang panas keluar tiba-tiba, rupiah cenderung?",
            options: ["Menguat", "Melemah tajam", "Tetap", "Hilang"],
            answer: 1,
            explain: "Pembalikan arus modal menekan rupiah dengan cepat.",
          },
          {
            q: "Apa bantalan utama bank sentral menghadapi pembalikan arus modal?",
            options: ["Pajak", "Cadangan devisa", "Subsidi", "Utang baru"],
            answer: 1,
            explain: "Cadangan devisa dipakai untuk intervensi meredam gejolak rupiah.",
          },
          {
            q: "Peristiwa 2013 yang memicu arus modal keluar dari negara berkembang disebut?",
            options: ["Taper tantrum", "Krisis minyak", "Tulip mania", "Black Monday"],
            answer: 0,
            explain: "Taper tantrum 2013 dipicu sinyal pengetatan The Fed.",
          },
        ],
      },
    ],
  },
];
