import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "uang-dan-bank-sentral",
    levelId: "dasar",
    order: 1,
    title: "Uang, Fungsinya & Peran Bank Sentral",
    summary: "Apa itu uang dan fungsinya, bagaimana bank menciptakan uang, serta peran Bank Indonesia menjaga stabilitas nilai rupiah.",
    durationMin: 13,
    tags: ["dasar", "uang", "bank sentral", "Bank Indonesia"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Kebijakan moneter</strong> adalah upaya bank sentral mengelola jumlah uang dan suku bunga demi menjaga perekonomian. Untuk memahaminya, kita mulai dari yang paling dasar: apa itu <strong>uang</strong>, dan siapa yang menjaganya.",
      },
      {
        type: "video",
        comp: "SejarahUangVideo",
        title: "Video: Evolusi Uang",
        caption: "Dari barter, uang logam, uang kertas, uang giral, sampai uang digital.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/David_Hume.jpg?width=400",
        alt: "Potret David Hume",
        caption: "David Hume (1711-1776), pemikir awal hubungan jumlah uang dan harga (teori kuantitas uang).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga fungsi uang",
        html: "<strong>Alat tukar</strong> (menggantikan barter), <strong>satuan hitung</strong> (mengukur nilai barang), dan <strong>penyimpan nilai</strong> (menyimpan daya beli ke masa depan). Uang yang baik memenuhi ketiganya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bank menciptakan uang",
        html: "Saat bank menyalurkan kembali sebagian besar simpanan sebagai kredit, satu setoran bisa berlipat menjadi uang beredar yang lebih besar. Bank sentral mengatur batasnya lewat <strong>giro wajib minimum (GWM)</strong>.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur setoran awal dan GWM untuk melihat bagaimana perbankan menggandakan uang beredar.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "donut",
        title: "Tujuan Utama Bank Indonesia (ilustrasi konsep)",
        unit: "bobot peran",
        source: "ilustrasi konsep mandat bank sentral",
        note: "Tujuan tunggal BI adalah kestabilan nilai rupiah, mencakup stabilitas harga (inflasi) dan nilai tukar.",
        data: [
          { label: "Stabilitas harga (inflasi)", value: 45, color: "#34d399" },
          { label: "Stabilitas nilai tukar", value: 35, color: "#60a5fa" },
          { label: "Stabilitas sistem keuangan", value: 20, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Penggandaan uang oleh bank",
        html: "Seseorang menyetor <strong>Rp100 juta</strong> ke bank. Dengan giro wajib minimum <strong>5%</strong>, angka pengganda uang = 1 / 0,05 = <strong>20 kali</strong>. Secara teori, sistem perbankan dapat menciptakan uang beredar hingga Rp2 miliar dari setoran awal itu lewat siklus simpan-pinjam. Inilah sebabnya bank sentral mengendalikan GWM untuk mengatur likuiditas.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan giro wajib minimum (GWM) 5%, berapa angka pengganda uang (money multiplier)?",
        answer: 20,
        tolerance: 0,
        suffix: " kali",
        solution: "Angka pengganda = 1 / GWM = 1 / 0,05 = <strong>20 kali</strong>.",
        hint: "Angka pengganda uang = 1 dibagi rasio GWM.",
      },
      {
        type: "calcExercise",
        prompt: "Setoran awal Rp100 juta dengan pengganda 20 kali. Berapa potensi total uang beredar (dalam juta)?",
        answer: 2000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Total = 100 x 20 = <strong>Rp2.000 juta</strong> (Rp2 miliar).",
        hint: "Kalikan setoran awal dengan angka pengganda.",
      },
      {
        type: "classifyExercise",
        prompt: "Peran ini fungsi uang yang mana?",
        buckets: ["Alat tukar", "Satuan hitung", "Penyimpan nilai"],
        items: [
          { text: "Membayar belanja di pasar", bucket: "Alat tukar" },
          { text: "Mencantumkan harga barang dalam rupiah", bucket: "Satuan hitung" },
          { text: "Menabung untuk kebutuhan tahun depan", bucket: "Penyimpan nilai" },
          { text: "Menggantikan tukar-menukar barang langsung", bucket: "Alat tukar" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya Bank Indonesia 1953",
        html: "Bank sentral Indonesia, <strong>Bank Indonesia</strong>, lahir pada <strong>1953</strong> dari nasionalisasi De Javasche Bank yang berdiri sejak masa kolonial (1828). Sejak <strong>UU Nomor 23 Tahun 1999</strong>, BI menjadi lembaga independen dengan tujuan tunggal menjaga kestabilan nilai rupiah. Independensi ini dimaksudkan agar kebijakan moneter tidak tunduk pada kepentingan politik jangka pendek.",
      },
      {
        type: "takeaways",
        items: [
          "Uang berfungsi sebagai alat tukar, satuan hitung, dan penyimpan nilai.",
          "Perbankan menciptakan uang lewat siklus simpan-pinjam, dibatasi GWM.",
          "Angka pengganda uang = 1 dibagi GWM.",
          "Tujuan utama Bank Indonesia adalah kestabilan nilai rupiah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah yang BUKAN fungsi uang?",
            options: ["Alat tukar", "Satuan hitung", "Penyimpan nilai", "Sumber inflasi"],
            answer: 3,
            explain: "Fungsi uang adalah alat tukar, satuan hitung, dan penyimpan nilai.",
          },
          {
            q: "Angka pengganda uang dihitung sebagai?",
            options: ["GWM x 100", "1 / GWM", "GWM / 2", "1 + GWM"],
            answer: 1,
            explain: "Money multiplier = 1 dibagi rasio giro wajib minimum.",
          },
          {
            q: "Tujuan utama Bank Indonesia adalah?",
            options: ["Memaksimalkan laba", "Menjaga kestabilan nilai rupiah", "Menaikkan pajak", "Mengatur ekspor"],
            answer: 1,
            explain: "Mandat BI adalah mencapai dan memelihara kestabilan nilai rupiah.",
          },
          {
            q: "GWM 10%. Berapa angka pengganda uangnya?",
            options: ["5 kali", "10 kali", "20 kali", "100 kali"],
            answer: 1,
            explain: "1 / 0,10 = 10 kali.",
          },
          {
            q: "Independensi bank sentral dimaksudkan agar?",
            options: [
              "Bebas dari kepentingan politik jangka pendek",
              "Bisa mencetak uang sebanyak-banyaknya",
              "Menggantikan pemerintah",
              "Menghapus pajak",
            ],
            answer: 0,
            explain: "Independensi menjaga kebijakan moneter dari tekanan politik sesaat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sejarah-dan-evolusi-uang",
    levelId: "dasar",
    order: 2,
    title: "Sejarah & Evolusi Uang",
    summary: "Dari barter yang merepotkan, uang barang, uang logam, uang kertas berstandar emas, sampai uang fiat dan uang digital masa kini.",
    durationMin: 14,
    tags: ["dasar", "uang", "sejarah", "fiat"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum ada uang, orang bertukar barang langsung lewat <strong>barter</strong>. Masalahnya, barter butuh <strong>kebetulan ganda keinginan</strong> (double coincidence of wants): petani yang ingin sandal harus menemukan pembuat sandal yang kebetulan ingin beras. Sulit dan lambat. Dari sinilah uang lahir untuk mempermudah pertukaran.",
      },
      {
        type: "paragraph",
        html: "Uang lalu berkembang melalui beberapa tahap: <strong>uang barang</strong> (komoditas seperti garam, kerang, ternak), <strong>uang logam</strong> (emas dan perak), <strong>uang kertas</strong> (awalnya dijamin emas lewat standar emas), <strong>uang fiat</strong> (dijamin kepercayaan dan negara, tanpa cadangan emas), lalu <strong>uang giral</strong> (saldo rekening bank) serta <strong>uang elektronik dan digital</strong>.",
      },
      {
        type: "video",
        comp: "SejarahUangVideo",
        title: "Video: Evolusi Uang",
        caption: "Perjalanan uang dari barter sampai uang digital.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Masalah inti barter",
        html: "<strong>Kebetulan ganda keinginan</strong>: kedua pihak harus sama-sama menginginkan barang yang dimiliki lawannya, pada saat yang sama. Uang memutus syarat ini karena diterima semua orang.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Uang barang ke uang logam",
        html: "Komoditas seperti garam pernah jadi alat tukar (kata <em>gaji</em> dalam bahasa Inggris, <em>salary</em>, berakar pada <em>salt</em>). Logam mulia lalu menang karena tahan lama, mudah dibagi, dan langka.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Uang modern sebagian besar berupa uang giral yang diciptakan perbankan. Atur setoran dan GWM untuk melihat penggandaan uang.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "bar",
        title: "Tahapan Evolusi Uang (urutan kemunculan)",
        unit: "abad/tahun perkiraan",
        source: "ilustrasi konsep sejarah uang",
        note: "Setiap tahap muncul karena tahap sebelumnya punya keterbatasan, sampai uang menjadi murni kepercayaan (fiat) dan digital.",
        data: [
          { label: "Barter", value: 1, color: "#94a3b8" },
          { label: "Uang barang", value: 2, color: "#fbbf24" },
          { label: "Uang logam", value: 3, color: "#f59e0b" },
          { label: "Uang kertas (standar emas)", value: 4, color: "#60a5fa" },
          { label: "Uang fiat", value: 5, color: "#34d399" },
          { label: "Uang digital", value: 6, color: "#a78bfa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Mengapa standar emas membatasi",
        html: "Pada standar emas, setiap selembar uang kertas dijamin bisa ditukar sejumlah emas tetap. Jika sebuah negara hanya punya emas senilai <strong>Rp100 triliun</strong>, jumlah uang yang boleh dicetak ikut terbatas pada angka itu. Saat ekonomi tumbuh dan butuh lebih banyak uang, sistem ini menjadi kaku. Inilah salah satu alasan dunia bergeser ke uang fiat yang lebih lentur dikelola bank sentral.",
      },
      {
        type: "case",
        title: "Sejarah: Berakhirnya standar emas, 1971",
        html: "Sejak perjanjian <strong>Bretton Woods 1944</strong>, dolar AS dipatok ke emas (sekitar 35 dolar per ons) dan mata uang lain dipatok ke dolar. Pada <strong>15 Agustus 1971</strong>, Presiden <strong>Richard Nixon</strong> menutup konversi dolar ke emas (dikenal sebagai <em>Nixon Shock</em>). Sejak saat itu mata uang dunia menjadi <strong>uang fiat</strong>, yaitu bernilai karena kepercayaan dan dukungan negara, bukan karena cadangan emas.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah negara punya cadangan emas senilai Rp100 triliun dan menjamin penuh uangnya dengan emas (standar emas 100%). Berapa maksimum uang kertas yang boleh dicetak (dalam triliun)?",
        answer: 100,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "Pada standar emas penuh, uang dibatasi nilai cadangan emas, yaitu <strong>Rp100 triliun</strong>.",
        hint: "Standar emas penuh berarti uang = nilai cadangan emas.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis uang dengan ciri utamanya.",
        pairs: [
          { left: "Uang barang", right: "Komoditas seperti garam atau kerang" },
          { left: "Uang logam", right: "Emas atau perak yang dicetak jadi koin" },
          { left: "Uang kertas standar emas", right: "Kertas yang dijamin bisa ditukar emas" },
          { left: "Uang fiat", right: "Bernilai karena kepercayaan dan negara" },
          { left: "Uang giral", right: "Saldo di rekening bank" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Barter terhambat masalah kebetulan ganda keinginan.",
          "Uang berevolusi: barang, logam, kertas, fiat, lalu digital.",
          "Standar emas membatasi jumlah uang pada cadangan emas.",
          "Sejak 1971 (Nixon Shock) uang dunia menjadi fiat.",
          "Uang fiat bernilai karena kepercayaan dan dukungan negara.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Masalah utama sistem barter adalah?",
            options: [
              "Terlalu banyak uang beredar",
              "Kebetulan ganda keinginan",
              "Inflasi tinggi",
              "Suku bunga naik",
            ],
            answer: 1,
            explain: "Barter butuh kedua pihak sama-sama menginginkan barang lawannya pada saat yang sama.",
          },
          {
            q: "Uang fiat bernilai karena?",
            options: [
              "Dijamin penuh oleh emas",
              "Terbuat dari logam mulia",
              "Kepercayaan dan dukungan negara",
              "Bisa dimakan",
            ],
            answer: 2,
            explain: "Uang fiat tidak dijamin emas; nilainya berasal dari kepercayaan dan negara.",
          },
          {
            q: "Peristiwa 1971 yang mengakhiri konversi dolar ke emas disebut?",
            options: ["Bretton Woods", "Nixon Shock", "Great Depression", "Plaza Accord"],
            answer: 1,
            explain: "Pada 15 Agustus 1971 Nixon menutup konversi dolar-emas (Nixon Shock).",
          },
          {
            q: "Urutan evolusi uang yang benar adalah?",
            options: [
              "Fiat, logam, barter, kertas",
              "Barter, uang barang, uang logam, uang kertas, fiat",
              "Digital, kertas, logam, barter",
              "Logam, barter, fiat, barang",
            ],
            answer: 1,
            explain: "Uang berkembang dari barter, uang barang, uang logam, uang kertas, lalu fiat dan digital.",
          },
          {
            q: "Uang giral adalah?",
            options: [
              "Uang logam emas",
              "Saldo di rekening bank",
              "Kerang sebagai alat tukar",
              "Cadangan emas negara",
            ],
            answer: 1,
            explain: "Uang giral adalah simpanan di rekening bank yang dapat dipakai bertransaksi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jenis-dan-agregat-uang",
    levelId: "dasar",
    order: 3,
    title: "Jenis Uang & Agregat Moneter (M0, M1, M2)",
    summary: "Membedakan uang kartal dan uang giral, lalu memahami agregat moneter M0, M1, dan M2 yang dipakai bank sentral mengukur uang beredar.",
    durationMin: 14,
    tags: ["dasar", "uang beredar", "M1", "M2", "agregat moneter"],
    blocks: [
      {
        type: "paragraph",
        html: "Uang yang kita pegang sehari-hari hanyalah sebagian dari semua uang yang beredar. Ada <strong>uang kartal</strong> (uang fisik berupa kertas dan logam yang beredar di masyarakat) dan <strong>uang giral</strong> (saldo rekening giro yang bisa dipindah lewat cek atau transfer). Bank sentral mengelompokkan semua bentuk uang ke dalam <strong>agregat moneter</strong>.",
      },
      {
        type: "paragraph",
        html: "Agregat moneter disusun berdasarkan <strong>likuiditas</strong>, yaitu seberapa cepat sesuatu bisa dipakai membayar. Semakin tinggi nomor agregat (M0 ke M2), semakin luas cakupannya tetapi semakin rendah likuiditasnya.",
      },
      {
        type: "video",
        comp: "SejarahUangVideo",
        title: "Video: Bentuk-bentuk Uang",
        caption: "Dari uang fisik sampai saldo bank yang menjadi bagian uang beredar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "M0, M1, M2 secara ringkas",
        html: "<strong>M0 (uang primer)</strong> = uang kartal + cadangan bank di bank sentral. <strong>M1</strong> = uang kartal + giro + uang elektronik. <strong>M2</strong> = M1 + uang kuasi (tabungan, deposito) + surat berharga selain saham.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Uang kuasi",
        html: "Tabungan dan deposito disebut <strong>uang kuasi</strong> karena tidak langsung bisa dibelanjakan, tetapi mudah dicairkan menjadi uang tunai. Itu sebabnya masuk M2, bukan M1.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Uang giral di M1 lahir dari penggandaan oleh perbankan. Otak-atik setoran dan GWM di simulator ini.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "bar",
        title: "Cakupan Agregat Moneter (ilustrasi proporsi)",
        unit: "indeks relatif",
        source: "ilustrasi konsep agregat moneter",
        note: "M2 selalu paling besar karena mencakup M1 plus uang kuasi; M0 paling sempit. Angka ini ilustrasi, bukan data resmi.",
        data: [
          { label: "M0 (uang primer)", value: 30, color: "#fbbf24" },
          { label: "M1", value: 55, color: "#60a5fa" },
          { label: "M2", value: 100, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung M1 dan M2",
        html: "Misal uang kartal di masyarakat <strong>Rp900 triliun</strong>, giro dan uang elektronik <strong>Rp1.100 triliun</strong>, serta tabungan dan deposito (uang kuasi) <strong>Rp5.000 triliun</strong>. Maka <strong>M1 = 900 + 1.100 = Rp2.000 triliun</strong>, dan <strong>M2 = M1 + 5.000 = Rp7.000 triliun</strong>. Terlihat M2 jauh lebih besar karena memuat simpanan yang kurang likuid.",
      },
      {
        type: "case",
        title: "Sejarah: Definisi uang beredar di Indonesia",
        html: "Sejak dekade 1970-an, <strong>Bank Indonesia</strong> rutin menerbitkan data uang beredar dalam arti sempit (<strong>M1</strong>) dan arti luas (<strong>M2</strong>). Seiring perkembangan sistem pembayaran, cakupan M1 diperluas memasukkan <strong>uang elektronik</strong>. Penyempurnaan definisi ini penting agar ukuran uang beredar tetap mencerminkan cara masyarakat bertransaksi.",
      },
      {
        type: "calcExercise",
        prompt: "Uang kartal Rp900 triliun, giro dan uang elektronik Rp1.100 triliun. Berapa M1 (dalam triliun)?",
        answer: 2000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "M1 = uang kartal + giro + uang elektronik = 900 + 1.100 = <strong>Rp2.000 triliun</strong>.",
        hint: "M1 = uang kartal + giro + uang elektronik.",
      },
      {
        type: "calcExercise",
        prompt: "M1 = Rp2.000 triliun dan uang kuasi = Rp5.000 triliun. Berapa M2 (dalam triliun)?",
        answer: 7000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "M2 = M1 + uang kuasi = 2.000 + 5.000 = <strong>Rp7.000 triliun</strong>.",
        hint: "M2 = M1 ditambah uang kuasi (tabungan dan deposito).",
      },
      {
        type: "classifyExercise",
        prompt: "Komponen ini masuk agregat yang mana?",
        buckets: ["M0", "M1", "M2"],
        items: [
          { text: "Cadangan bank di bank sentral", bucket: "M0" },
          { text: "Saldo giro perusahaan", bucket: "M1" },
          { text: "Uang elektronik di dompet digital", bucket: "M1" },
          { text: "Deposito berjangka 6 bulan", bucket: "M2" },
          { text: "Tabungan masyarakat di bank", bucket: "M2" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Uang kartal adalah uang fisik; uang giral adalah saldo rekening giro.",
          "M0 = uang kartal + cadangan bank di bank sentral.",
          "M1 = uang kartal + giro + uang elektronik.",
          "M2 = M1 + uang kuasi (tabungan, deposito) + surat berharga selain saham.",
          "Likuiditas menurun dari M1 ke M2; M2 paling luas cakupannya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Uang giral adalah?",
            options: [
              "Uang logam yang beredar",
              "Saldo rekening giro",
              "Cadangan emas",
              "Deposito berjangka",
            ],
            answer: 1,
            explain: "Uang giral adalah saldo rekening giro yang dapat dipindahkan lewat cek atau transfer.",
          },
          {
            q: "M1 terdiri atas?",
            options: [
              "Hanya uang kartal",
              "Uang kartal + giro + uang elektronik",
              "Tabungan dan deposito saja",
              "Cadangan bank di bank sentral",
            ],
            answer: 1,
            explain: "M1 = uang kartal + giro + uang elektronik (uang paling likuid).",
          },
          {
            q: "Tabungan dan deposito disebut uang kuasi dan masuk ke?",
            options: ["M0", "M1", "M2", "Tidak dihitung"],
            answer: 2,
            explain: "Uang kuasi kurang likuid sehingga masuk M2, bukan M1.",
          },
          {
            q: "Manakah pernyataan yang benar tentang likuiditas?",
            options: [
              "M2 lebih likuid daripada M1",
              "Likuiditas menurun dari M1 ke M2",
              "M0 paling tidak likuid",
              "Semua agregat sama likuidnya",
            ],
            answer: 1,
            explain: "Semakin luas agregat (M1 ke M2), semakin rendah likuiditasnya.",
          },
          {
            q: "Jika M1 = Rp2.000 triliun dan uang kuasi = Rp4.000 triliun, maka M2 = ?",
            options: ["Rp2.000 triliun", "Rp4.000 triliun", "Rp6.000 triliun", "Rp8.000 triliun"],
            answer: 2,
            explain: "M2 = M1 + uang kuasi = 2.000 + 4.000 = Rp6.000 triliun.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "tujuan-kebijakan-moneter",
    levelId: "dasar",
    order: 4,
    title: "Tujuan Kebijakan Moneter",
    summary: "Apa sebenarnya yang ingin dicapai bank sentral: stabilitas harga, pertumbuhan, kesempatan kerja, dan keseimbangan eksternal, serta mengapa ada trade-off.",
    durationMin: 14,
    tags: ["dasar", "tujuan", "stabilitas harga", "mandat tunggal"],
    blocks: [
      {
        type: "paragraph",
        html: "Tujuan akhir kebijakan moneter adalah <strong>kemakmuran masyarakat</strong>. Untuk ke sana, bank sentral mengejar beberapa <strong>sasaran antara</strong>: stabilitas harga (inflasi rendah dan stabil), pertumbuhan ekonomi, kesempatan kerja yang tinggi, serta keseimbangan neraca pembayaran dan nilai tukar yang sehat.",
      },
      {
        type: "paragraph",
        html: "Masalahnya, sasaran-sasaran itu tidak selalu searah. Ada <strong>trade-off</strong>: mendorong pertumbuhan dan lapangan kerja secara agresif bisa memanaskan permintaan dan menaikkan inflasi. Karena itu banyak bank sentral memilih fokus yang jelas. Di Indonesia, <strong>Bank Indonesia</strong> diberi <strong>mandat tunggal</strong>, yaitu menjaga kestabilan nilai rupiah.",
      },
      {
        type: "video",
        comp: "BankSentralVideo",
        title: "Video: Peran Bank Sentral",
        caption: "Bagaimana bank sentral menyeimbangkan berbagai tujuan ekonomi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kestabilan nilai rupiah",
        html: "Bagi BI, kestabilan nilai rupiah punya dua sisi: <strong>stabilitas harga</strong> (inflasi terkendali, daya beli terjaga) dan <strong>stabilitas nilai tukar</strong> (kurs rupiah terhadap mata uang lain relatif stabil).",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati trade-off",
        html: "Menurunkan suku bunga dapat menggairahkan ekonomi dan menambah lapangan kerja, tetapi bila berlebihan dapat mendorong inflasi. Tidak ada kebijakan tanpa konsekuensi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Gerakkan BI Rate dan amati bagaimana arah kebijakan memengaruhi keseimbangan antara pertumbuhan dan inflasi.",
      },
      { type: "widget", widget: "SimulatorBIRate" },
      {
        type: "chart",
        variant: "bar",
        title: "Empat Sasaran Antara Kebijakan Moneter (ilustrasi penekanan)",
        unit: "bobot perhatian",
        source: "ilustrasi konsep tujuan kebijakan moneter",
        note: "Dengan mandat tunggal, BI menempatkan stabilitas harga dan nilai tukar sebagai prioritas, tanpa mengabaikan pertumbuhan.",
        data: [
          { label: "Stabilitas harga", value: 40, color: "#34d399" },
          { label: "Stabilitas nilai tukar", value: 30, color: "#60a5fa" },
          { label: "Pertumbuhan ekonomi", value: 18, color: "#fbbf24" },
          { label: "Kesempatan kerja", value: 12, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Trade-off inflasi dan pengangguran",
        html: "Sebuah bank sentral memangkas suku bunga agar dunia usaha berani berinvestasi. Pengangguran turun dari <strong>6%</strong> ke <strong>5%</strong>, tetapi inflasi naik dari <strong>3%</strong> ke <strong>5%</strong>. Trade-off ini, yang secara klasik digambarkan <strong>kurva Phillips</strong>, menunjukkan bahwa menekan pengangguran terlalu jauh dapat memicu inflasi. Bank sentral harus memilih titik keseimbangan.",
      },
      {
        type: "case",
        title: "Sejarah: Mandat tunggal lewat UU 23/1999",
        html: "Sebelum reformasi, bank sentral Indonesia mengemban banyak tugas sekaligus, termasuk mendorong pembangunan. Setelah krisis 1997 hingga 1998, lahir <strong>UU Nomor 23 Tahun 1999</strong> yang menjadikan <strong>Bank Indonesia</strong> independen dengan <strong>tujuan tunggal</strong>: mencapai dan memelihara kestabilan nilai rupiah. Fokus tunggal ini dianggap membuat kebijakan moneter lebih kredibel dan terukur.",
      },
      {
        type: "calcExercise",
        prompt: "Pengangguran turun dari 6% menjadi 5%. Berapa poin persen penurunannya?",
        answer: 1,
        tolerance: 0,
        suffix: " poin persen",
        solution: "Penurunan = 6% - 5% = <strong>1 poin persen</strong>.",
        hint: "Kurangkan angka akhir dari angka awal.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini sasaran antara atau tujuan akhir kebijakan moneter?",
        buckets: ["Sasaran antara", "Tujuan akhir"],
        items: [
          { text: "Inflasi rendah dan stabil", bucket: "Sasaran antara" },
          { text: "Nilai tukar rupiah stabil", bucket: "Sasaran antara" },
          { text: "Kemakmuran masyarakat", bucket: "Tujuan akhir" },
          { text: "Kesempatan kerja tinggi", bucket: "Sasaran antara" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Tujuan akhir kebijakan moneter adalah kemakmuran masyarakat.",
          "Sasaran antara: stabilitas harga, pertumbuhan, kesempatan kerja, keseimbangan eksternal.",
          "Sasaran-sasaran itu dapat saling tukar (trade-off), mis. inflasi vs pengangguran.",
          "Bank Indonesia memegang mandat tunggal: kestabilan nilai rupiah.",
          "Mandat tunggal lahir lewat UU Nomor 23 Tahun 1999.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mandat tunggal Bank Indonesia adalah?",
            options: [
              "Memaksimalkan pertumbuhan apa pun risikonya",
              "Menjaga kestabilan nilai rupiah",
              "Menurunkan pajak",
              "Menambah utang negara",
            ],
            answer: 1,
            explain: "Mandat tunggal BI adalah mencapai dan memelihara kestabilan nilai rupiah.",
          },
          {
            q: "Kestabilan nilai rupiah mencakup dua hal, yaitu?",
            options: [
              "Stabilitas harga dan stabilitas nilai tukar",
              "Pajak dan subsidi",
              "Ekspor dan impor",
              "Laba bank dan dividen",
            ],
            answer: 0,
            explain: "Kestabilan nilai rupiah meliputi stabilitas harga (inflasi) dan stabilitas nilai tukar (kurs).",
          },
          {
            q: "Contoh trade-off dalam kebijakan moneter adalah?",
            options: [
              "Inflasi naik bersama pengangguran turun",
              "Semua tujuan tercapai sekaligus tanpa biaya",
              "Pajak dan inflasi selalu sama",
              "Tidak ada konsekuensi kebijakan",
            ],
            answer: 0,
            explain: "Menekan pengangguran terlalu jauh dapat mendorong inflasi naik (kurva Phillips).",
          },
          {
            q: "Tujuan akhir kebijakan moneter adalah?",
            options: [
              "Inflasi nol mutlak",
              "Kemakmuran masyarakat",
              "Suku bunga setinggi mungkin",
              "Cadangan emas maksimal",
            ],
            answer: 1,
            explain: "Sasaran antara hanyalah jalan menuju tujuan akhir, yaitu kemakmuran masyarakat.",
          },
          {
            q: "Mandat tunggal Bank Indonesia ditetapkan melalui?",
            options: [
              "UU Nomor 23 Tahun 1999",
              "UU Nomor 10 Tahun 1998",
              "Perjanjian Bretton Woods",
              "Keppres tahun 1953",
            ],
            answer: 0,
            explain: "UU Nomor 23 Tahun 1999 menjadikan BI independen dengan tujuan tunggal kestabilan nilai rupiah.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "inflasi-mengapa-penting",
    levelId: "dasar",
    order: 5,
    title: "Inflasi: Mengapa Bank Sentral Menjaganya",
    summary: "Memahami inflasi sebagai kenaikan harga umum, cara mengukurnya lewat IHK, jenis demand-pull dan cost-push, serta mengapa inflasi tinggi dan deflasi sama-sama berbahaya.",
    durationMin: 15,
    tags: ["dasar", "inflasi", "IHK", "deflasi", "daya beli"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Inflasi</strong> adalah kenaikan harga barang dan jasa secara umum dan berkelanjutan. Bukan satu harga naik sesaat, melainkan tingkat harga rata-rata yang terus merangkak. Inflasi diukur lewat <strong>Indeks Harga Konsumen (IHK)</strong> atau <em>Consumer Price Index</em>, yang memantau harga sekeranjang barang dan jasa yang lazim dibeli rumah tangga.",
      },
      {
        type: "paragraph",
        html: "Ada dua sumber utama inflasi. <strong>Demand-pull</strong> terjadi saat permintaan masyarakat melebihi kemampuan produksi, sehingga harga terdorong naik. <strong>Cost-push</strong> terjadi saat biaya produksi naik, misalnya harga energi atau bahan baku, lalu diteruskan ke harga jual.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Memahami Inflasi",
        caption: "Mengapa harga naik dan bagaimana bank sentral menjaganya.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bahaya inflasi tinggi",
        html: "Inflasi tinggi menggerus <strong>daya beli</strong>, menambah ketidakpastian, dan merugikan <strong>penabung</strong> karena nilai riil tabungan menyusut. Perencanaan bisnis dan rumah tangga jadi sulit.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Deflasi juga berbahaya",
        html: "<strong>Deflasi</strong> (harga turun terus-menerus) terdengar enak, tetapi membuat orang menunda belanja sambil menunggu harga lebih murah. Permintaan anjlok, produksi melambat, dan ekonomi bisa lesu berkepanjangan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung sendiri bagaimana inflasi menggerus nilai uang dari waktu ke waktu memakai kalkulator ini.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "callout",
        tone: "key",
        title: "Inflasi sehat itu moderat",
        html: "Bukan nol, melainkan rendah dan stabil. Bank Indonesia menetapkan <strong>sasaran inflasi</strong> sebagai jangkar, misalnya kisaran target tahunan, agar ekonomi tumbuh tanpa harga liar.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Dua Jenis Inflasi (ilustrasi konsep)",
        unit: "kontribusi konsep",
        source: "ilustrasi konsep jenis inflasi",
        note: "Demand-pull berasal dari sisi permintaan, cost-push dari sisi biaya. Inflasi nyata sering campuran keduanya.",
        data: [
          { label: "Demand-pull (permintaan)", value: 50, color: "#60a5fa" },
          { label: "Cost-push (biaya)", value: 50, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung laju inflasi dari IHK",
        html: "Indeks Harga Konsumen (IHK) tahun lalu <strong>110</strong>, tahun ini <strong>115,5</strong>. Laju inflasi = (115,5 - 110) / 110 x 100% = <strong>5%</strong>. Artinya, barang yang tahun lalu seharga Rp1.000.000 kini rata-rata menjadi Rp1.050.000. Uang yang sama membeli lebih sedikit.",
      },
      {
        type: "case",
        title: "Sejarah: Hiperinflasi Indonesia pertengahan 1960-an",
        html: "Pada pertengahan <strong>1960-an</strong>, Indonesia mengalami <strong>hiperinflasi</strong> dengan laju mencapai <strong>ratusan persen</strong> per tahun (sekitar 600% pada 1965 hingga 1966). Harga meroket, uang lama nyaris tak bernilai, dan pemerintah sempat melakukan pemotongan nilai mata uang (sanering). Episode ini menjadi pelajaran keras betapa pentingnya menjaga inflasi tetap rendah dan stabil.",
      },
      {
        type: "calcExercise",
        prompt: "IHK tahun lalu 110 dan tahun ini 115,5. Berapa laju inflasi tahunan (dalam persen)?",
        answer: 5,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi = (115,5 - 110) / 110 x 100% = 5,5 / 110 x 100% = <strong>5%</strong>.",
        hint: "Inflasi = (IHK baru - IHK lama) / IHK lama x 100%.",
      },
      {
        type: "calcExercise",
        prompt: "Harga rata-rata barang Rp1.000.000 dengan inflasi 5%. Berapa harganya tahun depan (dalam rupiah)?",
        answer: 1050000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Harga baru = 1.000.000 x (1 + 0,05) = <strong>Rp1.050.000</strong>.",
        hint: "Kalikan harga dengan (1 + laju inflasi).",
      },
      {
        type: "classifyExercise",
        prompt: "Peristiwa ini menyebabkan inflasi jenis apa?",
        buckets: ["Demand-pull", "Cost-push"],
        items: [
          { text: "Lonjakan permintaan saat masyarakat ramai berbelanja", bucket: "Demand-pull" },
          { text: "Harga energi dunia melonjak", bucket: "Cost-push" },
          { text: "Upah dan bahan baku naik tajam", bucket: "Cost-push" },
          { text: "Belanja meningkat melampaui kapasitas produksi", bucket: "Demand-pull" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Inflasi adalah kenaikan harga umum yang berkelanjutan, diukur lewat IHK.",
          "Laju inflasi = (IHK baru - IHK lama) / IHK lama x 100%.",
          "Demand-pull berasal dari permintaan; cost-push dari kenaikan biaya.",
          "Inflasi tinggi menggerus daya beli dan merugikan penabung.",
          "Deflasi juga berbahaya; inflasi moderat dan stabil dianggap sehat.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inflasi diukur dengan?",
            options: [
              "Nilai tukar harian",
              "Indeks Harga Konsumen (IHK)",
              "Jumlah uang logam",
              "Harga emas saja",
            ],
            answer: 1,
            explain: "Inflasi umumnya diukur lewat IHK yang memantau sekeranjang barang dan jasa.",
          },
          {
            q: "IHK naik dari 100 menjadi 104. Berapa laju inflasinya?",
            options: ["2%", "4%", "8%", "10%"],
            answer: 1,
            explain: "(104 - 100) / 100 x 100% = 4%.",
          },
          {
            q: "Inflasi yang dipicu lonjakan harga energi termasuk jenis?",
            options: ["Demand-pull", "Cost-push", "Deflasi", "Sanering"],
            answer: 1,
            explain: "Kenaikan biaya produksi seperti energi adalah inflasi cost-push.",
          },
          {
            q: "Mengapa deflasi berbahaya?",
            options: [
              "Membuat orang menunda belanja sehingga ekonomi lesu",
              "Selalu menaikkan daya beli tanpa risiko",
              "Membuat tabungan tumbuh sangat cepat",
              "Tidak berpengaruh pada ekonomi",
            ],
            answer: 0,
            explain: "Saat harga terus turun, orang menunda konsumsi, permintaan anjlok, ekonomi melambat.",
          },
          {
            q: "Tingkat inflasi yang dianggap sehat adalah?",
            options: [
              "Setinggi mungkin",
              "Nol mutlak",
              "Rendah dan stabil (moderat)",
              "Negatif (deflasi)",
            ],
            answer: 2,
            explain: "Inflasi yang rendah dan stabil mendukung pertumbuhan tanpa mengganggu daya beli.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sistem-perbankan-dan-intermediasi",
    levelId: "dasar",
    order: 6,
    title: "Sistem Perbankan & Intermediasi Keuangan",
    summary: "Bagaimana bank berperan sebagai perantara dana, sistem cadangan fraksional yang menciptakan uang, sumber pendapatan bank (spread), risiko rush, dan peran bank sentral menjaga stabilitas.",
    durationMin: 14,
    tags: ["dasar", "perbankan", "intermediasi", "cadangan fraksional", "bank run"],
    blocks: [
      {
        type: "paragraph",
        html: "Bank adalah <strong>perantara keuangan</strong> (intermediasi): ia menghimpun dana dari para penabung yang punya kelebihan uang, lalu menyalurkannya sebagai <strong>kredit</strong> kepada peminjam yang membutuhkan dana. Tanpa bank, penabung dan peminjam harus saling mencari sendiri, mahal dan berisiko. Bank mempertemukan keduanya secara efisien.",
      },
      {
        type: "paragraph",
        html: "Kunci sistem perbankan modern adalah <strong>cadangan fraksional</strong> (fractional reserve): bank tidak menyimpan seluruh simpanan sebagai uang menganggur. Ia hanya menahan <strong>sebagian</strong> sebagai cadangan, dan meminjamkan sisanya. Karena pinjaman itu kembali mengendap sebagai simpanan di bank lain lalu dipinjamkan lagi, sistem perbankan secara keseluruhan <strong>menciptakan uang</strong> berlipat ganda dari setoran awal.",
      },
      {
        type: "video",
        comp: "BankSentralVideo",
        title: "Video: Peran Bank Sentral",
        caption: "Bagaimana bank sentral menjaga stabilitas perbankan yang menjalankan intermediasi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Spread, sumber laba bank",
        html: "Bank membayar <strong>bunga simpanan</strong> kepada penabung dan menerima <strong>bunga kredit</strong> dari peminjam. Selisihnya, disebut <strong>spread</strong>, menjadi pendapatan utama bank. Contoh: bunga kredit 12% dikurangi bunga simpanan 4% memberi spread 8%.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko penarikan massal (bank run)",
        html: "Karena bank hanya menyimpan sebagian dana sebagai cadangan, ia tidak bisa membayar semua penabung sekaligus. Bila kepercayaan runtuh dan banyak orang menarik dana serentak (<strong>rush</strong> atau <strong>bank run</strong>), bank yang sehat pun bisa kolaps. Inilah kerentanan bawaan cadangan fraksional.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur setoran awal dan rasio cadangan untuk melihat bagaimana sistem perbankan menggandakan uang beredar.",
      },
      { type: "widget", widget: "KalkulatorMultiplierUang" },
      {
        type: "chart",
        variant: "bar",
        title: "Penciptaan Uang lewat Cadangan Fraksional (cadangan 10%)",
        unit: "Rp juta per putaran",
        source: "ilustrasi konsep penggandaan simpanan",
        note: "Setiap putaran, bank menahan 10% sebagai cadangan dan meminjamkan 90%. Total simpanan yang tercipta menuju Rp1.000 juta dari setoran awal Rp100 juta.",
        data: [
          { label: "Putaran 1 (setoran awal)", value: 100, color: "#34d399" },
          { label: "Putaran 2", value: 90, color: "#60a5fa" },
          { label: "Putaran 3", value: 81, color: "#818cf8" },
          { label: "Putaran 4", value: 72.9, color: "#a78bfa" },
          { label: "Putaran 5", value: 65.6, color: "#c084fc" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Spread dan penggandaan uang",
        html: "Sebuah bank menerima setoran <strong>Rp100 juta</strong> dengan rasio cadangan <strong>10%</strong>. Angka pengganda uang = 1 / 0,10 = <strong>10 kali</strong>, sehingga sistem perbankan dapat menciptakan simpanan hingga <strong>Rp1 miliar</strong>. Atas kredit yang disalurkan, bank menetapkan bunga kredit 12% dan membayar bunga simpanan 4%, sehingga menikmati <strong>spread 8 poin persen</strong> sebagai pendapatannya.",
      },
      {
        type: "case",
        title: "Sejarah: Pandai emas Eropa abad ke-17",
        html: "Cikal bakal perbankan modern adalah para <strong>pandai emas</strong> (goldsmith) di Eropa pada <strong>abad ke-17</strong>. Mereka menyimpan emas titipan orang dan menerbitkan <strong>tanda terima emas</strong>. Lama-kelamaan tanda terima itu beredar sebagai alat pembayaran, cikal bakal <strong>uang kertas</strong>. Para pandai emas juga menyadari tidak semua orang menarik emasnya bersamaan, sehingga mereka berani meminjamkan sebagian, lahirlah praktik <strong>cadangan fraksional</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Bunga kredit sebuah bank 12% dan bunga simpanan 4%. Berapa spread bunganya (dalam poin persen)?",
        answer: 8,
        tolerance: 0,
        suffix: " poin persen",
        solution: "Spread = bunga kredit - bunga simpanan = 12% - 4% = <strong>8 poin persen</strong>.",
        hint: "Kurangkan bunga simpanan dari bunga kredit.",
      },
      {
        type: "calcExercise",
        prompt: "Setoran awal Rp100 juta dengan rasio cadangan 10%. Berapa potensi total simpanan yang tercipta (dalam juta)?",
        answer: 1000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Pengganda = 1 / 0,10 = 10 kali, maka total = 100 x 10 = <strong>Rp1.000 juta</strong> (Rp1 miliar).",
        hint: "Total = setoran awal x (1 / rasio cadangan).",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini terkait fungsi/risiko bank yang mana?",
        buckets: ["Intermediasi", "Spread", "Risiko rush"],
        items: [
          { text: "Menghimpun tabungan dan menyalurkannya jadi kredit", bucket: "Intermediasi" },
          { text: "Selisih bunga kredit dan bunga simpanan", bucket: "Spread" },
          { text: "Banyak nasabah menarik dana serentak", bucket: "Risiko rush" },
          { text: "Mempertemukan penabung dengan peminjam", bucket: "Intermediasi" },
          { text: "Pendapatan utama dari menyalurkan kredit", bucket: "Spread" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Bank berperan sebagai perantara (intermediasi) penabung dan peminjam.",
          "Cadangan fraksional: bank menahan sebagian simpanan, meminjamkan sisanya.",
          "Sistem perbankan menciptakan uang berlipat dari setoran awal.",
          "Spread (bunga kredit dikurangi bunga simpanan) adalah pendapatan utama bank.",
          "Cadangan fraksional rentan terhadap penarikan massal (bank run).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fungsi intermediasi bank berarti?",
            options: [
              "Mencetak uang kertas sendiri",
              "Menghimpun dana penabung dan menyalurkannya sebagai kredit",
              "Menentukan kurs mata uang",
              "Memungut pajak masyarakat",
            ],
            answer: 1,
            explain: "Bank menjadi perantara yang mempertemukan penabung dan peminjam.",
          },
          {
            q: "Sistem cadangan fraksional berarti bank?",
            options: [
              "Menyimpan seluruh simpanan sebagai cadangan",
              "Hanya menahan sebagian simpanan, sisanya dipinjamkan",
              "Tidak boleh menyalurkan kredit",
              "Menyimpan emas, bukan uang",
            ],
            answer: 1,
            explain: "Cadangan fraksional menahan sebagian simpanan dan meminjamkan sisanya.",
          },
          {
            q: "Pendapatan utama bank dari intermediasi disebut?",
            options: ["Pajak", "Spread bunga", "Dividen", "Subsidi"],
            answer: 1,
            explain: "Spread adalah selisih bunga kredit dan bunga simpanan.",
          },
          {
            q: "Rasio cadangan 10%. Berapa angka pengganda uangnya?",
            options: ["5 kali", "10 kali", "20 kali", "100 kali"],
            answer: 1,
            explain: "Pengganda = 1 / 0,10 = 10 kali.",
          },
          {
            q: "Bank run terjadi ketika?",
            options: [
              "Bank menaikkan bunga simpanan",
              "Banyak nasabah menarik dananya serentak",
              "Bank sentral menurunkan suku bunga",
              "Inflasi turun",
            ],
            answer: 1,
            explain: "Penarikan massal serentak dapat melampaui cadangan bank dan memicu kolaps.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sejarah-bank-sentral-dunia",
    levelId: "dasar",
    order: 7,
    title: "Sejarah Bank Sentral di Dunia & Indonesia",
    summary: "Menelusuri kelahiran bank sentral, dari Sveriges Riksbank 1668 dan Bank of England 1694, Federal Reserve 1913, hingga De Javasche Bank 1828 yang menjadi Bank Indonesia pada 1953.",
    durationMin: 14,
    tags: ["dasar", "sejarah", "bank sentral", "Bank Indonesia", "De Javasche Bank"],
    blocks: [
      {
        type: "paragraph",
        html: "Bank sentral tidak lahir sekaligus dengan peran lengkap seperti sekarang. Awalnya banyak yang dibentuk untuk <strong>mendanai pemerintah atau perang</strong>, lalu perlahan berkembang menjadi <strong>penjaga stabilitas moneter dan sistem keuangan</strong>. Memahami sejarahnya membantu kita melihat mengapa bank sentral modern diberi mandat dan independensi seperti hari ini.",
      },
      {
        type: "paragraph",
        html: "Bank sentral tertua di dunia adalah <strong>Sveriges Riksbank</strong> di Swedia, berdiri pada <strong>1668</strong>. Disusul <strong>Bank of England</strong> pada <strong>1694</strong>, yang mulanya didirikan untuk membantu mendanai perang lalu menjelma menjadi penjaga moneter Inggris. Di Amerika Serikat, <strong>Federal Reserve</strong> baru dibentuk pada <strong>1913</strong> setelah serangkaian panik perbankan yang mengguncang ekonomi.",
      },
      {
        type: "video",
        comp: "BankSentralVideo",
        title: "Video: Peran Bank Sentral",
        caption: "Evolusi peran bank sentral dari pencetak uang menjadi penjaga stabilitas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dari pencetak uang ke penjaga stabilitas",
        html: "Peran bank sentral berkembang: dari sekadar <strong>menerbitkan uang</strong> dan membiayai negara, menjadi <strong>penjaga stabilitas harga</strong> (inflasi terkendali) dan <strong>stabilitas sistem keuangan</strong>. Inilah inti mandat bank sentral modern.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Akar Bank Indonesia",
        html: "Di Hindia Belanda, <strong>De Javasche Bank</strong> berdiri pada <strong>1828</strong> sebagai bank sirkulasi. Setelah Indonesia merdeka, bank ini dinasionalisasi dan resmi menjadi <strong>Bank Indonesia</strong> pada <strong>1953</strong>.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bank sentral modern mengelola suku bunga acuan. Gerakkan BI Rate dan amati arah kebijakannya.",
      },
      { type: "widget", widget: "SimulatorBIRate" },
      {
        type: "chart",
        variant: "bar",
        title: "Tahun Berdirinya Beberapa Bank Sentral",
        unit: "tahun",
        source: "catatan sejarah kelembagaan bank sentral",
        note: "Sveriges Riksbank (1668) tertua, lalu Bank of England (1694); Bank Indonesia menjadi bank sentral nasional pada 1953 dari De Javasche Bank (1828).",
        data: [
          { label: "Sveriges Riksbank (Swedia)", value: 1668, color: "#34d399" },
          { label: "Bank of England (Inggris)", value: 1694, color: "#60a5fa" },
          { label: "De Javasche Bank (Hindia Belanda)", value: 1828, color: "#fbbf24" },
          { label: "Federal Reserve (AS)", value: 1913, color: "#f59e0b" },
          { label: "Bank Indonesia", value: 1953, color: "#a78bfa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Rentang usia kelembagaan",
        html: "Bila kita hitung dari tahun berdiri sampai <strong>2025</strong>: Sveriges Riksbank (<strong>1668</strong>) berusia sekitar <strong>357 tahun</strong>, Bank of England (<strong>1694</strong>) sekitar <strong>331 tahun</strong>, dan Bank Indonesia sebagai bank sentral nasional (<strong>1953</strong>) sekitar <strong>72 tahun</strong>. Sejarah panjang ini menunjukkan bank sentral adalah institusi yang dirancang untuk bertahan lintas generasi.",
      },
      {
        type: "case",
        title: "Sejarah: Pendirian Bank of England 1694",
        html: "<strong>Bank of England</strong> didirikan pada <strong>1694</strong> di tengah kebutuhan Kerajaan Inggris mendanai perang melawan Prancis. Sekelompok pemodal meminjamkan dana kepada pemerintah, dan sebagai imbalan memperoleh hak menerbitkan uang kertas. Dari fungsi awal sebagai <strong>pemberi pinjaman bagi negara</strong>, lembaga ini perlahan menjadi pusat sistem moneter Inggris dan model bagi bank sentral di banyak negara lain.",
      },
      {
        type: "calcExercise",
        prompt: "Bank of England berdiri tahun 1694. Berapa tahun usianya pada 2025?",
        answer: 331,
        tolerance: 0,
        suffix: " tahun",
        solution: "Usia = 2025 - 1694 = <strong>331 tahun</strong>.",
        hint: "Kurangkan tahun berdiri dari tahun 2025.",
      },
      {
        type: "calcExercise",
        prompt: "De Javasche Bank berdiri 1828 dan dinasionalisasi menjadi Bank Indonesia pada 1953. Berapa tahun rentang antara keduanya?",
        answer: 125,
        tolerance: 0,
        suffix: " tahun",
        solution: "Rentang = 1953 - 1828 = <strong>125 tahun</strong>.",
        hint: "Kurangkan tahun pendirian dari tahun nasionalisasi.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan bank sentral dengan tahun berdirinya.",
        pairs: [
          { left: "Sveriges Riksbank (Swedia)", right: "1668" },
          { left: "Bank of England (Inggris)", right: "1694" },
          { left: "De Javasche Bank (Hindia Belanda)", right: "1828" },
          { left: "Federal Reserve (AS)", right: "1913" },
          { left: "Bank Indonesia", right: "1953" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Sveriges Riksbank (1668) adalah bank sentral tertua, disusul Bank of England (1694).",
          "Federal Reserve AS dibentuk 1913 setelah serangkaian panik perbankan.",
          "De Javasche Bank berdiri 1828, dinasionalisasi menjadi Bank Indonesia pada 1953.",
          "Banyak bank sentral lahir untuk mendanai negara, lalu jadi penjaga moneter.",
          "Peran modern bank sentral: penjaga stabilitas harga dan sistem keuangan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Bank sentral tertua di dunia adalah?",
            options: [
              "Bank of England",
              "Sveriges Riksbank (Swedia)",
              "Federal Reserve",
              "De Javasche Bank",
            ],
            answer: 1,
            explain: "Sveriges Riksbank Swedia berdiri pada 1668, lebih tua dari Bank of England (1694).",
          },
          {
            q: "Bank of England didirikan pada 1694 awalnya untuk?",
            options: [
              "Mengatur ekspor teh",
              "Membantu mendanai perang",
              "Mencetak perangko",
              "Menetapkan upah minimum",
            ],
            answer: 1,
            explain: "Bank of England awalnya didirikan untuk mendanai perang, lalu menjadi penjaga moneter.",
          },
          {
            q: "Federal Reserve AS dibentuk pada 1913 setelah?",
            options: [
              "Perang Dunia II",
              "Serangkaian panik perbankan",
              "Penemuan uang digital",
              "Berakhirnya standar emas",
            ],
            answer: 1,
            explain: "The Fed dibentuk 1913 menyusul serangkaian panik perbankan yang mengguncang ekonomi AS.",
          },
          {
            q: "Bank Indonesia berasal dari nasionalisasi bank kolonial bernama?",
            options: ["Bank of England", "De Javasche Bank", "Sveriges Riksbank", "Bank Batavia"],
            answer: 1,
            explain: "De Javasche Bank (berdiri 1828) dinasionalisasi menjadi Bank Indonesia pada 1953.",
          },
          {
            q: "Peran bank sentral modern berkembang menjadi?",
            options: [
              "Sekadar pencetak uang",
              "Penjaga stabilitas harga dan sistem keuangan",
              "Pemungut pajak utama",
              "Pengelola ekspor-impor",
            ],
            answer: 1,
            explain: "Dari sekadar menerbitkan uang, bank sentral kini menjaga stabilitas harga dan sistem keuangan.",
          },
        ],
      },
    ],
  },
];
