import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "transmisi-dan-inflasi",
    levelId: "transmisi",
    order: 1,
    title: "Mekanisme Transmisi & Sasaran Inflasi",
    summary: "Bagaimana keputusan suku bunga menjalar ke ekonomi nyata, kerangka sasaran inflasi, serta hubungan inflasi dan pengangguran.",
    durationMin: 14,
    tags: ["transmisi", "inflasi", "inflation targeting", "kurva Phillips"],
    blocks: [
      {
        type: "paragraph",
        html: "Saat bank sentral menggerakkan suku bunga acuan, dampaknya tidak langsung terasa di harga. Ada <strong>mekanisme transmisi</strong>, rantai yang membawa keputusan moneter sampai ke inflasi dan pertumbuhan, dengan jeda waktu berbulan-bulan.",
      },
      {
        type: "video",
        comp: "KurvaPhillips",
        title: "Video: Kurva Phillips",
        caption: "Hubungan jangka pendek antara inflasi dan pengangguran yang dihadapi pembuat kebijakan.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Portrait_of_Irving_Fisher.jpg?width=400",
        alt: "Potret Irving Fisher",
        caption: "Irving Fisher (1867-1947), perumus teori kuantitas uang modern (MV = PT).",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat jalur transmisi",
        html: "<strong>Jalur suku bunga:</strong> bunga kredit memengaruhi investasi dan konsumsi. <strong>Jalur kredit:</strong> kesediaan bank menyalurkan pinjaman. <strong>Jalur nilai tukar:</strong> bunga memengaruhi rupiah dan harga impor. <strong>Jalur ekspektasi:</strong> perkiraan masyarakat tentang inflasi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kerangka sasaran inflasi (ITF)",
        html: "Sejak 2005, Bank Indonesia menerapkan <strong>Inflation Targeting Framework</strong>: menetapkan sasaran inflasi dan mengarahkan suku bunga agar inflasi mendekati sasaran itu. Sasaran diumumkan agar ekspektasi publik terjangkar.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana perubahan suku bunga acuan menjalar ke suku bunga kredit dan aktivitas ekonomi.",
      },
      { type: "widget", widget: "SimulatorTransmisiSukuBunga" },
      {
        type: "chart",
        variant: "line",
        title: "Jeda Transmisi: Suku Bunga ke Inflasi (ilustrasi konsep)",
        unit: "dampak relatif",
        source: "ilustrasi konsep lag kebijakan moneter",
        note: "Dampak penuh kebijakan moneter pada inflasi biasanya baru terasa setelah beberapa kuartal, bukan seketika.",
        data: [
          { label: "Bulan 0", value: 5 },
          { label: "Bulan 3", value: 25 },
          { label: "Bulan 6", value: 60 },
          { label: "Bulan 12", value: 90 },
          { label: "Bulan 18", value: 100 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menjangkar ekspektasi inflasi",
        html: "Jika masyarakat yakin inflasi akan tinggi, pekerja menuntut kenaikan upah dan pedagang menaikkan harga lebih dulu, sehingga inflasi benar-benar terjadi (ramalan yang mewujudkan diri). Karena itu bank sentral mengumumkan <strong>sasaran inflasi</strong>, misalnya sekitar <strong>3% plus minus 1%</strong>, agar ekspektasi terjangkar dan inflasi lebih mudah dikendalikan tanpa harus menaikkan bunga setinggi-tingginya.",
      },
      {
        type: "calcExercise",
        prompt: "Sasaran inflasi ditetapkan 3% dengan toleransi plus minus 1%. Berapa batas atas kisaran sasaran itu?",
        answer: 4,
        tolerance: 0,
        suffix: "%",
        solution: "Batas atas = 3% + 1% = <strong>4%</strong> (batas bawah 2%).",
        hint: "Tambahkan toleransi ke titik tengah sasaran.",
      },
      {
        type: "calcExercise",
        prompt: "Menurut teori kuantitas uang MV = PT, jika jumlah uang M naik 10% sementara V dan T tetap, berapa persen kira-kira kenaikan tingkat harga P?",
        answer: 10,
        tolerance: 0,
        suffix: "%",
        solution: "Bila V dan T tetap, kenaikan M sepenuhnya tercermin pada P, jadi P naik sekitar <strong>10%</strong>.",
        hint: "Pada MV = PT dengan V dan T tetap, perubahan M sebanding dengan perubahan P.",
      },
      {
        type: "classifyExercise",
        prompt: "Dampak ini menjalar lewat jalur transmisi yang mana?",
        buckets: ["Jalur suku bunga", "Jalur nilai tukar", "Jalur ekspektasi"],
        items: [
          { text: "Bunga KPR naik sehingga orang menunda beli rumah", bucket: "Jalur suku bunga" },
          { text: "Bunga naik menarik modal asing, rupiah menguat", bucket: "Jalur nilai tukar" },
          { text: "Harga impor turun karena rupiah menguat", bucket: "Jalur nilai tukar" },
          { text: "Masyarakat percaya inflasi akan rendah, harga stabil", bucket: "Jalur ekspektasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Teori Kuantitas Uang dan Monetarisme",
        html: "Gagasan bahwa jumlah uang menentukan tingkat harga sudah dirumuskan <strong>Irving Fisher</strong> lewat persamaan <strong>MV = PT</strong> pada awal abad ke-20. Pada 1960-an sampai 1970-an, <strong>Milton Friedman</strong> dan kaum monetaris menegaskan bahwa inflasi pada dasarnya adalah fenomena moneter: terlalu banyak uang mengejar terlalu sedikit barang. Pemikiran ini sangat memengaruhi cara bank sentral modern menjaga inflasi.",
      },
      {
        type: "takeaways",
        items: [
          "Kebijakan moneter menjalar lewat jalur suku bunga, kredit, nilai tukar, dan ekspektasi.",
          "Dampaknya pada inflasi datang dengan jeda berbulan-bulan.",
          "Bank Indonesia memakai kerangka sasaran inflasi sejak 2005.",
          "Menjangkar ekspektasi inflasi mempermudah pengendalian harga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mekanisme transmisi adalah?",
            options: [
              "Cara mencetak uang",
              "Rantai yang membawa kebijakan moneter ke inflasi dan output",
              "Pajak bank",
              "Sistem pembayaran",
            ],
            answer: 1,
            explain: "Transmisi adalah jalur dari keputusan moneter sampai ke ekonomi nyata.",
          },
          {
            q: "Manakah salah satu jalur transmisi?",
            options: ["Jalur cuaca", "Jalur nilai tukar", "Jalur pajak", "Jalur ekspor saja"],
            answer: 1,
            explain: "Jalur nilai tukar adalah salah satu dari empat jalur transmisi utama.",
          },
          {
            q: "Inflation Targeting Framework berarti bank sentral?",
            options: [
              "Menetapkan sasaran inflasi dan mengarahkan bunga ke sana",
              "Menargetkan kurs tetap",
              "Menghapus inflasi selamanya",
              "Menaikkan pajak",
            ],
            answer: 0,
            explain: "ITF menetapkan sasaran inflasi sebagai jangkar kebijakan.",
          },
          {
            q: "Dampak kebijakan moneter pada inflasi umumnya?",
            options: ["Seketika", "Datang dengan jeda berbulan-bulan", "Tidak pernah", "Hanya saat krisis"],
            answer: 1,
            explain: "Ada lag; dampak penuh baru terasa setelah beberapa kuartal.",
          },
          {
            q: "Menurut MV = PT, jika M naik 8% (V, T tetap), P kira-kira naik?",
            options: ["0%", "4%", "8%", "80%"],
            answer: 2,
            explain: "Dengan V dan T tetap, kenaikan M tercermin penuh pada P, sekitar 8%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jalur-jalur-transmisi",
    levelId: "transmisi",
    order: 2,
    title: "Lima Jalur Transmisi Kebijakan Moneter",
    summary: "Menelusuri lima jalur yang membawa keputusan suku bunga acuan sampai ke harga, output, dan kesempatan kerja.",
    durationMin: 15,
    tags: ["transmisi", "suku bunga", "kredit", "nilai tukar", "ekspektasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Satu keputusan suku bunga acuan menyebar ke seluruh ekonomi lewat banyak jalan sekaligus. Para ekonom biasanya mengelompokkannya menjadi <strong>lima jalur transmisi</strong>: suku bunga, kredit, nilai tukar, harga aset, dan ekspektasi. Memahami kelimanya membantu kita melihat mengapa dampak kebijakan tidak seketika dan tidak merata.",
      },
      {
        type: "paragraph",
        html: "Setiap jalur bekerja dengan kekuatan dan kecepatan berbeda di tiap negara, bergantung pada struktur perbankan, keterbukaan ekonomi, dan kedalaman pasar keuangannya.",
      },
      {
        type: "video",
        comp: "KebijakanMoneterVideo",
        title: "Video: Bagaimana Kebijakan Moneter Bekerja",
        caption: "Animasi alur keputusan bank sentral sampai ke aktivitas ekonomi sehari-hari.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lima jalur transmisi",
        html: "<strong>1. Suku bunga:</strong> bunga kredit memengaruhi investasi dan konsumsi. <strong>2. Kredit:</strong> kesediaan dan kemampuan bank menyalurkan pinjaman serta kondisi neraca bank. <strong>3. Nilai tukar:</strong> bunga memengaruhi kurs, lalu harga impor dan ekspor. <strong>4. Harga aset:</strong> bunga menggerakkan harga saham dan properti, lalu kekayaan dan konsumsi. <strong>5. Ekspektasi:</strong> perkiraan masyarakat tentang inflasi memengaruhi perilaku mereka hari ini.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Jalur harga aset",
        html: "Saat bunga turun, harga saham dan properti cenderung naik. Pemiliknya merasa lebih kaya (efek kekayaan) sehingga belanja lebih banyak. Perusahaan juga lebih mudah memperoleh dana karena nilai pasarnya naik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser suku bunga acuan dan amati bagaimana ia menjalar ke suku bunga kredit serta aktivitas ekonomi.",
      },
      { type: "widget", widget: "SimulatorTransmisiSukuBunga" },
      {
        type: "chart",
        variant: "bar",
        title: "Perkiraan Kekuatan Relatif Tiap Jalur (ilustrasi konsep)",
        unit: "kekuatan relatif",
        source: "ilustrasi konsep, kekuatan jalur berbeda antar ekonomi",
        note: "Di ekonomi yang masih didominasi bank, jalur suku bunga dan kredit umumnya lebih kuat daripada jalur harga aset.",
        data: [
          { label: "Suku bunga", value: 85 },
          { label: "Kredit", value: 80 },
          { label: "Nilai tukar", value: 65 },
          { label: "Harga aset", value: 45 },
          { label: "Ekspektasi", value: 70 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Satu kenaikan bunga, banyak jalan",
        html: "Bank sentral menaikkan suku bunga acuan 0,5 poin persen. Lewat <strong>jalur suku bunga</strong>, bunga KPR ikut naik sehingga sebagian orang menunda beli rumah. Lewat <strong>jalur nilai tukar</strong>, modal asing masuk dan rupiah menguat sekitar 1%, menurunkan harga barang impor. Lewat <strong>jalur ekspektasi</strong>, publik makin yakin bank sentral serius menjaga inflasi. Ketiganya bersama-sama menekan inflasi, meski dengan jeda waktu.",
      },
      {
        type: "calcExercise",
        prompt: "Suku bunga acuan naik 0,5 poin persen dan bank meneruskan 80% kenaikan itu ke bunga kredit. Berapa poin persen kenaikan bunga kredit?",
        answer: 0.4,
        tolerance: 0.01,
        suffix: " poin persen",
        solution: "Kenaikan bunga kredit = 0,5 x 80% = <strong>0,4 poin persen</strong>.",
        hint: "Kalikan kenaikan acuan dengan rasio penerusan (pass-through).",
      },
      {
        type: "classifyExercise",
        prompt: "Peristiwa ini bekerja lewat jalur transmisi yang mana?",
        buckets: ["Jalur kredit", "Jalur harga aset", "Jalur ekspektasi"],
        items: [
          { text: "Bank memperketat syarat pinjaman sehingga kredit baru turun", bucket: "Jalur kredit" },
          { text: "Harga saham naik, pemiliknya merasa kaya dan belanja lebih banyak", bucket: "Jalur harga aset" },
          { text: "Neraca bank membaik sehingga lebih berani menyalurkan kredit", bucket: "Jalur kredit" },
          { text: "Masyarakat yakin inflasi akan rendah, lalu menunda menaikkan harga", bucket: "Jalur ekspektasi" },
          { text: "Harga properti naik sehingga kekayaan rumah tangga bertambah", bucket: "Jalur harga aset" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Memperkuat transmisi lewat reformasi kerangka operasional",
        html: "Awalnya banyak bank sentral menargetkan jumlah uang beredar, tetapi transmisinya kabur. Sejak 1990-an hingga 2000-an, banyak bank sentral, termasuk <strong>Bank Indonesia</strong>, beralih ke kerangka berbasis suku bunga acuan. Bank Indonesia memperkenalkan <strong>BI Rate</strong> pada 2005 dan menyempurnakannya menjadi <strong>BI 7-Day Reverse Repo Rate</strong> pada 2016 agar sinyal kebijakan lebih cepat menjalar ke suku bunga pasar uang dan kredit. Penyempurnaan kerangka operasional ini membuat jalur suku bunga bekerja lebih kuat dan lebih jelas.",
      },
      {
        type: "takeaways",
        items: [
          "Ada lima jalur transmisi: suku bunga, kredit, nilai tukar, harga aset, dan ekspektasi.",
          "Jalur kredit menyangkut kesediaan bank menyalurkan pinjaman dan kondisi neracanya.",
          "Jalur harga aset bekerja lewat efek kekayaan pada konsumsi.",
          "Kekuatan tiap jalur berbeda antar negara sesuai struktur ekonominya.",
          "Penyempurnaan kerangka operasional BI memperkuat transmisi jalur suku bunga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Berapa jumlah jalur transmisi utama yang dibahas?",
            options: ["Tiga", "Empat", "Lima", "Tujuh"],
            answer: 2,
            explain: "Lima jalur: suku bunga, kredit, nilai tukar, harga aset, dan ekspektasi.",
          },
          {
            q: "Jalur kredit berkaitan terutama dengan?",
            options: [
              "Harga saham di bursa",
              "Kesediaan dan kemampuan bank menyalurkan pinjaman",
              "Nilai tukar rupiah",
              "Pajak penghasilan",
            ],
            answer: 1,
            explain: "Jalur kredit menyangkut penyaluran pinjaman bank dan kondisi neracanya.",
          },
          {
            q: "Efek kekayaan adalah inti dari jalur?",
            options: ["Jalur harga aset", "Jalur nilai tukar", "Jalur ekspektasi", "Jalur pajak"],
            answer: 0,
            explain: "Naiknya harga aset membuat pemiliknya merasa lebih kaya dan belanja lebih banyak.",
          },
          {
            q: "Bunga naik menarik modal asing sehingga rupiah menguat. Ini jalur?",
            options: ["Jalur kredit", "Jalur nilai tukar", "Jalur harga aset", "Jalur suku bunga"],
            answer: 1,
            explain: "Pergerakan kurs akibat perubahan bunga adalah jalur nilai tukar.",
          },
          {
            q: "BI 7-Day Reverse Repo Rate diperkenalkan pada tahun?",
            options: ["2005", "2010", "2016", "2020"],
            answer: 2,
            explain: "Pada 2016 BI menyempurnakan acuan menjadi BI 7-Day Reverse Repo Rate.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "teori-kuantitas-uang",
    levelId: "transmisi",
    order: 3,
    title: "Teori Kuantitas Uang & Monetarisme",
    summary: "Persamaan MV = PT, gagasan bahwa inflasi adalah fenomena moneter, dan warisan Milton Friedman bagi bank sentral modern.",
    durationMin: 15,
    tags: ["teori kuantitas uang", "MV=PT", "monetarisme", "Friedman", "inflasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Mengapa harga-harga bisa naik terus? Salah satu jawaban tertua dan paling berpengaruh datang dari <strong>teori kuantitas uang</strong>. Inti gagasannya sederhana: jika jumlah uang tumbuh jauh lebih cepat daripada barang dan jasa, nilai uang turun dan harga naik.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Milton_Friedman.jpg?width=400",
        alt: "Potret Milton Friedman",
        caption: "Milton Friedman (1912-2006), tokoh monetarisme yang menegaskan inflasi sebagai fenomena moneter.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Apa Itu Inflasi",
        caption: "Mengapa harga naik dan bagaimana jumlah uang berperan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Persamaan pertukaran Irving Fisher",
        html: "<strong>MV = PT</strong>. <strong>M</strong> = jumlah uang beredar, <strong>V</strong> = kecepatan perputaran uang (berapa kali satu rupiah berpindah tangan dalam setahun), <strong>P</strong> = tingkat harga, <strong>T</strong> = volume transaksi. Bila <strong>V</strong> dan <strong>T</strong> relatif stabil, perubahan <strong>M</strong> langsung menentukan <strong>P</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Inflasi sebagai fenomena moneter",
        html: "Milton Friedman terkenal menyatakan bahwa <strong>inflasi selalu dan di mana pun merupakan fenomena moneter</strong>: ia muncul karena jumlah uang tumbuh lebih cepat daripada output. Aliran pemikiran ini disebut <strong>monetarisme</strong> dan menguat pada 1960-an sampai 1970-an.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung sendiri dampak pertumbuhan uang dan harga dengan kalkulator inflasi.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "line",
        title: "Hubungan Pertumbuhan Uang dan Inflasi (ilustrasi konsep MV = PT)",
        unit: "% per tahun",
        source: "ilustrasi konsep, dengan asumsi V dan T stabil",
        note: "Bila V dan T tetap, makin cepat M tumbuh, makin tinggi inflasi yang dihasilkan.",
        data: [
          { label: "M +2%", value: 2 },
          { label: "M +5%", value: 5 },
          { label: "M +8%", value: 8 },
          { label: "M +12%", value: 12 },
          { label: "M +20%", value: 20 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung inflasi dari MV = PT",
        html: "Misalkan jumlah uang <strong>M</strong> tumbuh 12% setahun, kecepatan perputaran <strong>V</strong> tetap, dan volume transaksi riil <strong>T</strong> tumbuh 5% (sejalan pertumbuhan ekonomi). Karena MV = PT, pertumbuhan harga kira-kira = pertumbuhan M dikurangi pertumbuhan T = 12% - 5% = <strong>7%</strong>. Jadi sebagian pertumbuhan uang terserap oleh ekonomi yang membesar, sisanya menjadi inflasi.",
      },
      {
        type: "calcExercise",
        prompt: "Jumlah uang M tumbuh 12% per tahun, V tetap, dan output riil T tumbuh 5%. Berapa persen kira-kira inflasi (pertumbuhan P)?",
        answer: 7,
        tolerance: 0.5,
        suffix: "%",
        solution: "Dari MV = PT dengan V tetap: pertumbuhan P = pertumbuhan M - pertumbuhan T = 12% - 5% = <strong>7%</strong>.",
        hint: "Inflasi kira-kira sama dengan pertumbuhan uang dikurangi pertumbuhan output riil.",
      },
      {
        type: "calcExercise",
        prompt: "Jika M naik 15% sementara V dan T sama-sama tetap, berapa persen kira-kira kenaikan tingkat harga P?",
        answer: 15,
        tolerance: 0,
        suffix: "%",
        solution: "Dengan V dan T tetap, seluruh kenaikan M tercermin pada P, jadi P naik sekitar <strong>15%</strong>.",
        hint: "Pada MV = PT dengan V dan T tetap, perubahan M sebanding penuh dengan perubahan P.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan simbol pada persamaan MV = PT dengan artinya.",
        pairs: [
          { left: "M", right: "Jumlah uang beredar" },
          { left: "V", right: "Kecepatan perputaran uang" },
          { left: "P", right: "Tingkat harga" },
          { left: "T", right: "Volume transaksi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Monetarisme dan Paul Volcker melawan inflasi",
        html: "Gagasan monetaris sangat memengaruhi kebijakan bank sentral pada akhir 1970-an dan 1980-an. Di Amerika Serikat, inflasi sempat menembus belasan persen. Ketua bank sentral <strong>Paul Volcker</strong> sejak 1979 menaikkan suku bunga sangat tinggi, bahkan melampaui 19% pada awal 1980-an, untuk menekan pertumbuhan uang dan ekspektasi inflasi. Kebijakan ini memicu resesi tajam, tetapi berhasil menurunkan inflasi AS dari sekitar 13% pada 1980 menjadi sekitar 4% pada 1983. Ini menjadi bukti nyata pengaruh pemikiran monetaris.",
      },
      {
        type: "takeaways",
        items: [
          "Teori kuantitas uang dirangkum dalam persamaan MV = PT.",
          "Bila V dan T stabil, pertumbuhan jumlah uang menentukan tingkat harga.",
          "Milton Friedman dan monetarisme menegaskan inflasi sebagai fenomena moneter.",
          "Inflasi kira-kira sama dengan pertumbuhan uang dikurangi pertumbuhan output riil.",
          "Paul Volcker pada awal 1980-an membuktikan pengaruh monetarisme dengan menekan inflasi AS lewat bunga tinggi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam persamaan MV = PT, huruf V melambangkan?",
            options: [
              "Volume transaksi",
              "Kecepatan perputaran uang",
              "Nilai tukar",
              "Tingkat harga",
            ],
            answer: 1,
            explain: "V adalah kecepatan perputaran uang, berapa kali satu unit uang berpindah tangan setahun.",
          },
          {
            q: "Bila V dan T stabil, kenaikan jumlah uang M terutama akan?",
            options: [
              "Menurunkan harga",
              "Menaikkan tingkat harga P",
              "Tidak berpengaruh apa pun",
              "Menaikkan kurs saja",
            ],
            answer: 1,
            explain: "Dengan V dan T tetap, kenaikan M tercermin pada kenaikan P.",
          },
          {
            q: "Pernyataan 'inflasi selalu dan di mana pun merupakan fenomena moneter' dikaitkan dengan?",
            options: ["John Maynard Keynes", "Milton Friedman", "Adam Smith", "Karl Marx"],
            answer: 1,
            explain: "Pernyataan ini terkenal diucapkan Milton Friedman, tokoh monetarisme.",
          },
          {
            q: "M tumbuh 10%, V tetap, output riil T tumbuh 4%. Inflasi kira-kira?",
            options: ["4%", "6%", "10%", "14%"],
            answer: 1,
            explain: "Inflasi kira-kira = pertumbuhan M - pertumbuhan T = 10% - 4% = 6%.",
          },
          {
            q: "Apa yang dilakukan Paul Volcker untuk menekan inflasi AS sekitar 1980?",
            options: [
              "Menurunkan suku bunga drastis",
              "Menaikkan suku bunga sangat tinggi",
              "Mencetak lebih banyak uang",
              "Menetapkan kurs tetap",
            ],
            answer: 1,
            explain: "Volcker menaikkan bunga sampai melampaui 19% untuk menekan inflasi, meski memicu resesi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kurva-phillips-dan-stagflasi",
    levelId: "transmisi",
    order: 4,
    title: "Kurva Phillips & Stagflasi",
    summary: "Trade-off inflasi dan pengangguran dalam jangka pendek, mengapa ia hilang dalam jangka panjang, dan pelajaran dari stagflasi 1970-an.",
    durationMin: 15,
    tags: ["kurva Phillips", "stagflasi", "pengangguran", "inflasi", "krisis minyak"],
    blocks: [
      {
        type: "paragraph",
        html: "Pada 1958, ekonom A.W. Phillips menemukan pola: saat pengangguran rendah, inflasi (atau kenaikan upah) cenderung tinggi, dan sebaliknya. Pola ini, yang kemudian disebut <strong>kurva Phillips</strong>, sempat dianggap sebagai menu pilihan bagi pemerintah: tukar sedikit inflasi untuk pengangguran yang lebih rendah.",
      },
      {
        type: "paragraph",
        html: "Namun keyakinan itu runtuh pada 1970-an, ketika inflasi tinggi dan pengangguran tinggi muncul bersamaan, sebuah keadaan yang disebut <strong>stagflasi</strong>.",
      },
      {
        type: "video",
        comp: "KurvaPhillips",
        title: "Video: Kurva Phillips",
        caption: "Trade-off jangka pendek antara inflasi dan pengangguran, serta batasnya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Jangka pendek vs jangka panjang",
        html: "<strong>Jangka pendek:</strong> ada trade-off, menurunkan pengangguran biasanya menaikkan inflasi. <strong>Jangka panjang:</strong> trade-off ini melemah atau hilang. Kurva Phillips menjadi <strong>vertikal</strong> pada tingkat pengangguran alami, karena ekspektasi inflasi akhirnya menyesuaikan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Stagflasi mematahkan keyakinan lama",
        html: "Stagflasi adalah kombinasi <strong>inflasi tinggi dan pengangguran tinggi</strong> sekaligus. Hal ini mestinya mustahil menurut kurva Phillips sederhana, tetapi benar-benar terjadi pada 1970-an, terutama dipicu lonjakan harga minyak.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur sikap kebijakan moneter dan amati dampaknya pada inflasi serta aktivitas ekonomi.",
      },
      { type: "widget", widget: "SimulatorKebijakanMoneter" },
      {
        type: "chart",
        variant: "line",
        title: "Kurva Phillips Jangka Pendek (ilustrasi konsep)",
        unit: "inflasi (%)",
        source: "ilustrasi konsep hubungan inflasi dan pengangguran",
        note: "Makin rendah pengangguran (ke kanan grafik), makin tinggi inflasi yang menyertainya dalam jangka pendek.",
        data: [
          { label: "Pengangguran 9%", value: 2 },
          { label: "Pengangguran 7%", value: 4 },
          { label: "Pengangguran 5%", value: 7 },
          { label: "Pengangguran 4%", value: 10 },
          { label: "Pengangguran 3%", value: 14 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Stagflasi dalam angka",
        html: "Bayangkan sebuah ekonomi yang biasanya punya inflasi 4% dan pengangguran 5%. Lalu harga energi melonjak dua kali lipat. Biaya produksi naik, perusahaan menaikkan harga sekaligus mengurangi pekerja. Inflasi melonjak ke <strong>11%</strong> sementara pengangguran naik ke <strong>8%</strong>. Keduanya memburuk bersamaan, persis ciri stagflasi. Bank sentral menghadapi dilema: menaikkan bunga melawan inflasi malah memperparah pengangguran.",
      },
      {
        type: "calcExercise",
        prompt: "Inflasi awal 4% lalu naik menjadi 11% akibat guncangan harga energi. Berapa poin persen kenaikan inflasinya?",
        answer: 7,
        tolerance: 0,
        suffix: " poin persen",
        solution: "Kenaikan = 11% - 4% = <strong>7 poin persen</strong>.",
        hint: "Kurangkan inflasi awal dari inflasi akhir.",
      },
      {
        type: "calcExercise",
        prompt: "Misalkan 'indeks kesengsaraan' (misery index) = inflasi + pengangguran. Jika inflasi 11% dan pengangguran 8%, berapa nilai indeksnya?",
        answer: 19,
        tolerance: 0,
        suffix: "",
        solution: "Misery index = 11% + 8% = <strong>19</strong>. Stagflasi membuat indeks ini melonjak.",
        hint: "Jumlahkan tingkat inflasi dan tingkat pengangguran.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini menggambarkan kurva Phillips jangka pendek, jangka panjang, atau stagflasi?",
        buckets: ["Jangka pendek", "Jangka panjang", "Stagflasi"],
        items: [
          { text: "Menurunkan pengangguran menaikkan inflasi", bucket: "Jangka pendek" },
          { text: "Kurva menjadi vertikal di tingkat pengangguran alami", bucket: "Jangka panjang" },
          { text: "Inflasi tinggi dan pengangguran tinggi terjadi bersamaan", bucket: "Stagflasi" },
          { text: "Trade-off hilang karena ekspektasi menyesuaikan", bucket: "Jangka panjang" },
          { text: "Guncangan harga minyak menaikkan harga sekaligus PHK", bucket: "Stagflasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Minyak 1973 dan Stagflasi 1970-an",
        html: "Pada Oktober <strong>1973</strong>, negara-negara pengekspor minyak yang tergabung dalam OPEC memberlakukan embargo, dan harga minyak dunia melonjak sekitar empat kali lipat dalam beberapa bulan. Biaya energi yang melonjak menaikkan harga di seluruh ekonomi sekaligus menekan produksi, sehingga banyak negara maju mengalami inflasi tinggi dan pengangguran tinggi secara bersamaan sepanjang 1970-an. Krisis minyak kedua pada <strong>1979</strong> memperparah keadaan. Pengalaman ini mematahkan keyakinan bahwa pemerintah bisa selalu menukar inflasi dengan pengangguran, dan mendorong perhatian pada peran ekspektasi.",
      },
      {
        type: "takeaways",
        items: [
          "Kurva Phillips jangka pendek menunjukkan trade-off inflasi dan pengangguran.",
          "Dalam jangka panjang trade-off itu hilang; kurva menjadi vertikal di pengangguran alami.",
          "Ekspektasi inflasi yang menyesuaikan adalah alasan trade-off jangka panjang lenyap.",
          "Stagflasi adalah inflasi tinggi dan pengangguran tinggi yang terjadi bersamaan.",
          "Krisis minyak 1973 memicu stagflasi 1970-an dan mengubah cara pandang kebijakan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kurva Phillips jangka pendek menggambarkan hubungan antara?",
            options: [
              "Kurs dan ekspor",
              "Inflasi dan pengangguran",
              "Pajak dan belanja",
              "Bunga dan saham",
            ],
            answer: 1,
            explain: "Kurva Phillips jangka pendek menghubungkan inflasi dan pengangguran secara terbalik.",
          },
          {
            q: "Dalam jangka panjang, kurva Phillips diperkirakan?",
            options: [
              "Tetap miring tajam",
              "Menjadi vertikal di tingkat pengangguran alami",
              "Menjadi horizontal",
              "Hilang sama sekali tanpa bentuk",
            ],
            answer: 1,
            explain: "Karena ekspektasi menyesuaikan, kurva jangka panjang menjadi vertikal di pengangguran alami.",
          },
          {
            q: "Stagflasi berarti?",
            options: [
              "Inflasi rendah dan pengangguran rendah",
              "Inflasi tinggi dan pengangguran tinggi bersamaan",
              "Deflasi berkepanjangan",
              "Pertumbuhan sangat cepat",
            ],
            answer: 1,
            explain: "Stagflasi adalah kombinasi inflasi tinggi dan pengangguran tinggi sekaligus.",
          },
          {
            q: "Apa pemicu utama stagflasi 1970-an?",
            options: [
              "Lonjakan harga minyak akibat embargo OPEC",
              "Penemuan internet",
              "Kebijakan kurs tetap",
              "Penurunan pajak besar",
            ],
            answer: 0,
            explain: "Embargo OPEC 1973 melonjakkan harga minyak dan memicu stagflasi.",
          },
          {
            q: "Mengapa stagflasi mematahkan keyakinan pada kurva Phillips sederhana?",
            options: [
              "Karena inflasi dan pengangguran ternyata bisa tinggi bersamaan",
              "Karena pengangguran tidak pernah berubah",
              "Karena inflasi selalu nol",
              "Karena bunga tidak berpengaruh",
            ],
            answer: 0,
            explain: "Kurva sederhana menyiratkan trade-off, tetapi stagflasi menunjukkan keduanya bisa memburuk bersama.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekspektasi-dan-kredibilitas",
    levelId: "transmisi",
    order: 5,
    title: "Ekspektasi Inflasi & Kredibilitas Bank Sentral",
    summary: "Bagaimana ekspektasi menjadi ramalan yang mewujudkan diri, mengapa kredibilitas menurunkan biaya menjaga inflasi, dan peran komunikasi bank sentral.",
    durationMin: 15,
    tags: ["ekspektasi", "kredibilitas", "inflation targeting", "forward guidance", "rational expectations"],
    blocks: [
      {
        type: "paragraph",
        html: "Inflasi tidak hanya soal jumlah uang hari ini, tetapi juga soal apa yang <strong>diperkirakan</strong> orang akan terjadi besok. Jika semua orang yakin harga akan naik 10%, pekerja menuntut upah lebih tinggi dan pedagang menaikkan harga lebih dulu, sehingga inflasi 10% benar-benar terwujud. Inilah sifat <strong>ramalan yang mewujudkan diri</strong>.",
      },
      {
        type: "paragraph",
        html: "Karena itu, tugas penting bank sentral bukan hanya mengatur bunga, melainkan juga mengelola ekspektasi lewat <strong>kredibilitas</strong> dan <strong>komunikasi</strong>.",
      },
      {
        type: "video",
        comp: "SukuBungaAcuan",
        title: "Video: Suku Bunga Acuan",
        caption: "Bagaimana sinyal dan komunikasi bank sentral memengaruhi ekspektasi pasar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kredibilitas menjangkar ekspektasi",
        html: "Bila publik percaya bank sentral akan menjaga inflasi di sekitar sasaran, ekspektasi inflasi menjadi <strong>terjangkar</strong>. Akibatnya, inflasi lebih mudah dijaga dengan biaya lebih kecil, yaitu tanpa harus menaikkan bunga setinggi-tingginya atau memicu resesi dalam.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ekspektasi rasional",
        html: "Teori <strong>ekspektasi rasional</strong> menyatakan orang membentuk perkiraan dengan memakai semua informasi yang tersedia, termasuk pengumuman kebijakan. Karena itu, janji yang kredibel bisa langsung memengaruhi perilaku bahkan sebelum bunga benar-benar diubah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur sasaran dan respons bunga, lalu lihat bagaimana ekspektasi serta inflasi bergerak.",
      },
      { type: "widget", widget: "SimulatorBIRate" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Menurunkan Inflasi: Kredibel vs Tidak Kredibel (ilustrasi konsep)",
        unit: "kehilangan output (indeks)",
        source: "ilustrasi konsep rasio pengorbanan (sacrifice ratio)",
        note: "Bank sentral yang kredibel bisa menurunkan inflasi dengan kehilangan output jauh lebih kecil.",
        data: [
          { label: "Tidak kredibel", value: 100, color: "#ef4444" },
          { label: "Cukup kredibel", value: 55 },
          { label: "Sangat kredibel", value: 25, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Janji yang kredibel menghemat biaya",
        html: "Dua bank sentral sama-sama ingin menurunkan inflasi dari 8% ke 4%. Bank <strong>A</strong> tidak dipercaya, sehingga ekspektasi publik tetap 8%; ia harus menaikkan bunga sangat tinggi dan ekonomi kehilangan banyak output. Bank <strong>B</strong> kredibel: begitu mengumumkan sasaran 4%, ekspektasi publik langsung turun ke sekitar 5%, sehingga kenaikan bunga yang dibutuhkan jauh lebih ringan. Hasil inflasinya sama, tetapi biaya Bank B jauh lebih kecil.",
      },
      {
        type: "calcExercise",
        prompt: "Bank sentral ingin menurunkan inflasi dari 8% ke sasaran 4%. Berapa poin persen penurunan inflasi yang ditargetkan?",
        answer: 4,
        tolerance: 0,
        suffix: " poin persen",
        solution: "Penurunan = 8% - 4% = <strong>4 poin persen</strong>.",
        hint: "Kurangkan sasaran dari inflasi awal.",
      },
      {
        type: "calcExercise",
        prompt: "Tanpa kredibilitas, menurunkan inflasi 1 poin persen butuh kehilangan output 4% (sacrifice ratio = 4). Berapa persen total output yang hilang untuk menurunkan inflasi 4 poin persen?",
        answer: 16,
        tolerance: 0,
        suffix: "%",
        solution: "Total kehilangan output = 4 (poin persen) x 4 (rasio) = <strong>16%</strong>.",
        hint: "Kalikan besar penurunan inflasi dengan sacrifice ratio.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan alat atau konsep dengan penjelasannya.",
        pairs: [
          { left: "Sasaran inflasi", right: "Angka yang diumumkan sebagai jangkar ekspektasi" },
          { left: "Forward guidance", right: "Sinyal arah kebijakan bunga ke depan" },
          { left: "Kredibilitas", right: "Kepercayaan publik bahwa janji bank sentral ditepati" },
          { left: "Ekspektasi rasional", right: "Perkiraan dibentuk memakai semua informasi tersedia" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Inflation Targeting dan Selandia Baru 1990",
        html: "Pada <strong>1990</strong>, <strong>Selandia Baru</strong> menjadi negara pertama yang secara resmi menerapkan <strong>inflation targeting</strong>: bank sentralnya mengumumkan sasaran inflasi yang jelas dan bertanggung jawab mencapainya. Pendekatan ini terbukti efektif menjangkar ekspektasi, sehingga inflasi turun dan stabil. Banyak negara lain mengikuti, antara lain Kanada (1991), Inggris (1992), dan kemudian <strong>Indonesia</strong> yang resmi memakai kerangka sasaran inflasi pada 2005. Pengalaman ini menunjukkan bahwa transparansi dan komitmen yang kredibel adalah alat ampuh menjaga inflasi.",
      },
      {
        type: "takeaways",
        items: [
          "Ekspektasi inflasi bisa menjadi ramalan yang mewujudkan diri.",
          "Kredibilitas bank sentral menjangkar ekspektasi sehingga inflasi lebih murah dijaga.",
          "Alat komunikasi utama: pengumuman sasaran inflasi dan forward guidance.",
          "Teori ekspektasi rasional menjelaskan mengapa janji kredibel langsung berdampak.",
          "Selandia Baru memelopori inflation targeting pada 1990; Indonesia menyusul pada 2005.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa ekspektasi inflasi disebut bisa mewujudkan diri?",
            options: [
              "Karena bank sentral memaksa harga naik",
              "Karena keyakinan akan inflasi mendorong upah dan harga naik lebih dulu",
              "Karena kurs selalu tetap",
              "Karena pajak naik otomatis",
            ],
            answer: 1,
            explain: "Jika orang yakin inflasi tinggi, mereka menaikkan upah dan harga, sehingga inflasi benar terjadi.",
          },
          {
            q: "Apa manfaat utama kredibilitas bank sentral?",
            options: [
              "Inflasi lebih mudah dijaga dengan biaya lebih kecil",
              "Pajak bisa dihapus",
              "Kurs menjadi tetap selamanya",
              "Bunga tidak pernah berubah",
            ],
            answer: 0,
            explain: "Kredibilitas menjangkar ekspektasi sehingga inflasi terjaga tanpa biaya output yang besar.",
          },
          {
            q: "Forward guidance adalah?",
            options: [
              "Pajak atas transaksi maju",
              "Sinyal bank sentral tentang arah kebijakan bunga ke depan",
              "Kurs masa depan",
              "Jenis pinjaman jangka panjang",
            ],
            answer: 1,
            explain: "Forward guidance adalah komunikasi arah kebijakan bunga untuk membentuk ekspektasi.",
          },
          {
            q: "Negara mana yang pertama menerapkan inflation targeting resmi pada 1990?",
            options: ["Amerika Serikat", "Selandia Baru", "Indonesia", "Jepang"],
            answer: 1,
            explain: "Selandia Baru menjadi pelopor inflation targeting pada 1990.",
          },
          {
            q: "Dengan sacrifice ratio 4, menurunkan inflasi 3 poin persen menyebabkan kehilangan output?",
            options: ["3%", "7%", "12%", "1,3%"],
            answer: 2,
            explain: "Kehilangan output = 3 x 4 = 12%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengukur-inflasi-inti",
    levelId: "transmisi",
    order: 6,
    title: "Mengukur Inflasi: Headline vs Inti",
    summary: "Bagaimana inflasi diukur lewat IHK dan mengapa bank sentral lebih memperhatikan inflasi inti daripada lonjakan harga pangan atau BBM sesaat.",
    durationMin: 14,
    tags: ["inflasi", "IHK", "inflasi inti", "BPS"],
    blocks: [
      {
        type: "paragraph",
        html: "Inflasi diukur lewat <strong>Indeks Harga Konsumen (IHK)</strong> yang dihitung BPS dari sekeranjang barang dan jasa yang biasa dikonsumsi rumah tangga. Tetapi tidak semua kenaikan harga bermakna sama bagi kebijakan moneter.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Memahami Inflasi",
        caption: "Inflasi umum terdiri dari komponen inti yang stabil dan komponen yang bergejolak.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga komponen inflasi",
        html: "<strong>Inflasi inti (core):</strong> barang dan jasa yang harganya relatif stabil, dipengaruhi permintaan, ekspektasi, dan kebijakan moneter. <strong>Harga bergejolak (volatile foods):</strong> pangan seperti cabai dan beras. <strong>Harga diatur pemerintah (administered prices):</strong> BBM, tarif listrik, rokok.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa fokus ke inflasi inti",
        html: "Bank Indonesia menjadikan <strong>inflasi inti</strong> acuan utama karena paling responsif terhadap kebijakan moneter. Lonjakan harga cabai atau kenaikan BBM bersifat sementara dan di luar kendali suku bunga.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur inflasi inti, harga bergejolak, dan harga diatur untuk melihat bagaimana ketiganya membentuk inflasi umum (headline).",
      },
      { type: "widget", widget: "SimulatorInflasiInti" },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Pembentuk Inflasi Umum (ilustrasi bobot)",
        unit: "% bobot dalam IHK",
        source: "ilustrasi konsep berdasarkan struktur IHK",
        note: "Inflasi inti mendominasi keranjang; tetapi harga bergejolak dan diatur bisa membuat headline melonjak sesaat.",
        data: [
          { label: "Inti (core)", value: 65, color: "#34d399" },
          { label: "Bergejolak (pangan)", value: 18, color: "#fb7185" },
          { label: "Diatur pemerintah", value: 17, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung inflasi umum dari komponen",
        html: "Misalkan inflasi inti 2,5% (bobot 65%), harga bergejolak 6% (bobot 18%), dan harga diatur 3% (bobot 17%). Inflasi umum = (2,5 x 0,65) + (6 x 0,18) + (3 x 0,17) = 1,625 + 1,08 + 0,51 = sekitar <strong>3,2%</strong>. Meski headline 3,2%, inflasi inti yang jadi perhatian utama bank sentral hanya 2,5%, menandakan tekanan harga mendasar masih jinak.",
      },
      {
        type: "calcExercise",
        prompt: "Inflasi inti 2,5% (bobot 0,65), bergejolak 6% (bobot 0,18), diatur 3% (bobot 0,17). Berapa inflasi umum (headline) dalam persen?",
        answer: 3.2,
        tolerance: 0.1,
        suffix: "%",
        solution: "Headline = (2,5 x 0,65) + (6 x 0,18) + (3 x 0,17) = 1,625 + 1,08 + 0,51 = sekitar <strong>3,2%</strong>.",
        hint: "Kalikan tiap komponen dengan bobotnya, lalu jumlahkan.",
      },
      {
        type: "calcExercise",
        prompt: "IHK naik dari 110 menjadi 113,3 dalam setahun. Berapa laju inflasi tahunannya dalam persen?",
        answer: 3,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi = (113,3 - 110) / 110 x 100% = 3,3 / 110 = <strong>3%</strong>.",
        hint: "Selisih IHK dibagi IHK awal, dikali 100%.",
      },
      {
        type: "classifyExercise",
        prompt: "Kenaikan harga ini termasuk komponen inflasi yang mana?",
        buckets: ["Inti", "Bergejolak", "Diatur pemerintah"],
        items: [
          { text: "Harga sewa dan jasa potong rambut naik perlahan", bucket: "Inti" },
          { text: "Harga cabai melonjak karena gagal panen", bucket: "Bergejolak" },
          { text: "Pemerintah menaikkan harga BBM bersubsidi", bucket: "Diatur pemerintah" },
          { text: "Tarif listrik dinaikkan", bucket: "Diatur pemerintah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lonjakan Inflasi saat Kenaikan Harga BBM",
        html: "Pada <strong>2005</strong> dan <strong>2013</strong>, pemerintah Indonesia menaikkan harga BBM bersubsidi secara signifikan. Akibatnya inflasi umum (headline) melonjak tajam sesaat, bahkan menembus dua digit pada 2005. Namun ini adalah inflasi <strong>administered prices</strong> yang bersifat sementara; bank sentral merespons terukur dengan menjaga ekspektasi, bukan menaikkan suku bunga setinggi-tingginya seolah inflasi mendasar memburuk.",
      },
      {
        type: "takeaways",
        items: [
          "Inflasi diukur lewat Indeks Harga Konsumen (IHK) oleh BPS.",
          "Inflasi umum terdiri dari komponen inti, bergejolak, dan diatur pemerintah.",
          "Inflasi inti paling responsif terhadap kebijakan moneter.",
          "Lonjakan harga pangan atau BBM bersifat sementara dan tidak selalu butuh kenaikan bunga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inflasi diukur terutama lewat?",
            options: ["Harga emas", "Indeks Harga Konsumen (IHK)", "Nilai tukar", "Harga saham"],
            answer: 1,
            explain: "IHK mengukur perubahan harga sekeranjang barang dan jasa konsumen.",
          },
          {
            q: "Komponen inflasi yang paling diperhatikan bank sentral adalah?",
            options: ["Harga bergejolak", "Inflasi inti", "Harga diatur", "Harga emas"],
            answer: 1,
            explain: "Inflasi inti paling mencerminkan tekanan harga mendasar dan responsif terhadap kebijakan.",
          },
          {
            q: "Kenaikan harga cabai termasuk?",
            options: ["Inflasi inti", "Harga bergejolak (volatile foods)", "Harga diatur", "Deflasi"],
            answer: 1,
            explain: "Harga pangan seperti cabai termasuk komponen bergejolak.",
          },
          {
            q: "Kenaikan harga BBM bersubsidi termasuk?",
            options: ["Inflasi inti", "Harga bergejolak", "Harga diatur pemerintah", "Bukan inflasi"],
            answer: 2,
            explain: "Harga yang ditetapkan pemerintah termasuk administered prices.",
          },
          {
            q: "IHK naik dari 100 ke 104. Laju inflasinya?",
            options: ["2%", "4%", "40%", "0,4%"],
            answer: 1,
            explain: "(104 - 100)/100 = 4%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "deflasi-dan-jebakan-likuiditas",
    levelId: "transmisi",
    order: 7,
    title: "Deflasi & Jebakan Likuiditas",
    summary: "Mengapa harga yang terus turun justru berbahaya, dan bagaimana kebijakan moneter bisa mentok saat suku bunga sudah mendekati nol.",
    durationMin: 14,
    tags: ["deflasi", "jebakan likuiditas", "Keynes", "Jepang"],
    blocks: [
      {
        type: "paragraph",
        html: "Inflasi yang terlalu tinggi buruk, tetapi kebalikannya, <strong>deflasi</strong> (harga turun terus-menerus), bisa lebih berbahaya. Dan ketika suku bunga sudah mendekati nol, kebijakan moneter bisa kehilangan dayanya.",
      },
      {
        type: "video",
        comp: "KurvaPhillips",
        title: "Video: Inflasi, Pengangguran & Kebijakan",
        caption: "Pembuat kebijakan tidak hanya melawan inflasi tinggi, tetapi juga menghindari deflasi.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/John_Maynard_Keynes.jpg?width=400",
        alt: "Potret John Maynard Keynes",
        caption: "John Maynard Keynes (1883-1946), yang merumuskan konsep jebakan likuiditas.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Spiral deflasi",
        html: "Saat harga turun, konsumen <strong>menunda belanja</strong> menunggu lebih murah, permintaan jatuh, produksi dipotong, upah turun, beban utang terasa makin berat (nilai riil utang naik), dan harga turun lagi. Lingkaran setan ini sulit diputus.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Jebakan likuiditas (liquidity trap)",
        html: "Konsep Keynes: ketika suku bunga sudah <strong>mendekati nol</strong>, menurunkannya lebih jauh tak lagi mendorong belanja dan investasi. Uang yang disuntik hanya ditimbun, bukan dibelanjakan. Kebijakan moneter <strong>mentok</strong>.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung laju inflasi dari indeks harga, dan amati kasus saat nilainya negatif (deflasi).",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "line",
        title: "Inflasi Jepang Mendekati Nol selama Dekade yang Hilang (ilustrasi)",
        unit: "% inflasi tahunan",
        source: "ilustrasi tren historis Jepang pasca-1990",
        note: "Jepang terjebak inflasi sangat rendah bahkan negatif selama bertahun-tahun, dengan suku bunga mentok di sekitar nol.",
        data: [
          { label: "1995", value: -0.1 },
          { label: "2000", value: -0.7 },
          { label: "2005", value: -0.3 },
          { label: "2010", value: -0.7 },
          { label: "2015", value: 0.8 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Saat penurunan bunga tak lagi mempan",
        html: "Sebuah bank sentral menurunkan suku bunga dari 2% ke 0,25% untuk melawan resesi, tetapi belanja dan kredit tetap lesu karena rumah tangga dan perusahaan pesimistis dan memilih menabung. Inilah <strong>jebakan likuiditas</strong>: ruang penurunan bunga habis sementara permintaan tak bergerak. Solusinya sering memerlukan dorongan <strong>fiskal</strong> (belanja pemerintah) dan kebijakan tak konvensional seperti quantitative easing.",
      },
      {
        type: "calcExercise",
        prompt: "Indeks harga turun dari 102 menjadi 101 dalam setahun. Berapa laju inflasinya dalam persen (negatif berarti deflasi)?",
        answer: -0.98,
        tolerance: 0.05,
        suffix: "%",
        solution: "Inflasi = (101 - 102) / 102 x 100% = -1/102 = sekitar <strong>-0,98%</strong>, yaitu deflasi.",
        hint: "Selisih indeks dibagi indeks awal; hasil negatif berarti deflasi.",
      },
      {
        type: "calcExercise",
        prompt: "Suku bunga acuan diturunkan dari 2% menjadi 0,25%. Berapa poin persen (pp) penurunannya?",
        answer: 1.75,
        tolerance: 0,
        suffix: " pp",
        solution: "Penurunan = 2% - 0,25% = <strong>1,75 poin persen</strong>. Setelah ini, ruang penurunan hampir habis.",
        hint: "Kurangi suku bunga akhir dari suku bunga awal.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi ini gejala inflasi tinggi atau deflasi/jebakan likuiditas?",
        buckets: ["Inflasi tinggi", "Deflasi / jebakan likuiditas"],
        items: [
          { text: "Konsumen menunda belanja menunggu harga lebih murah", bucket: "Deflasi / jebakan likuiditas" },
          { text: "Suku bunga nol tetapi kredit tetap lesu", bucket: "Deflasi / jebakan likuiditas" },
          { text: "Harga melonjak, uang cepat dibelanjakan", bucket: "Inflasi tinggi" },
          { text: "Beban riil utang meningkat karena harga turun", bucket: "Deflasi / jebakan likuiditas" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Dekade yang Hilang Jepang",
        html: "Setelah gelembung aset pecah pada awal <strong>1990-an</strong>, Jepang masuk ke periode panjang pertumbuhan rendah, deflasi, dan suku bunga mendekati nol yang dikenal sebagai <strong>dekade yang hilang</strong> (bahkan berlanjut lebih dari dua dekade). Bank of Japan menjadi pelopor kebijakan tak konvensional seperti quantitative easing sejak <strong>2001</strong>. Pengalaman Jepang menjadi peringatan dunia bahwa deflasi dan jebakan likuiditas sangat sulit diatasi.",
      },
      {
        type: "takeaways",
        items: [
          "Deflasi (harga turun terus) memicu spiral menunda belanja dan beban utang riil naik.",
          "Jebakan likuiditas: saat bunga mendekati nol, penurunan lebih lanjut tak efektif.",
          "Solusi sering butuh dorongan fiskal dan kebijakan tak konvensional (QE).",
          "Pengalaman Jepang sejak 1990-an menjadi peringatan klasik tentang deflasi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Deflasi adalah?",
            options: ["Harga naik terus", "Harga turun terus-menerus", "Kurs melemah", "Bunga naik"],
            answer: 1,
            explain: "Deflasi adalah penurunan tingkat harga umum yang berkelanjutan.",
          },
          {
            q: "Mengapa deflasi berbahaya?",
            options: [
              "Membuat orang menunda belanja dan menaikkan beban utang riil",
              "Menaikkan ekspor saja",
              "Tidak ada bahayanya",
              "Menghapus pajak",
            ],
            answer: 0,
            explain: "Spiral deflasi menekan permintaan dan memperberat utang secara riil.",
          },
          {
            q: "Jebakan likuiditas terjadi ketika?",
            options: [
              "Inflasi sangat tinggi",
              "Suku bunga mendekati nol dan penurunan lebih lanjut tak efektif",
              "Surplus anggaran besar",
              "Ekspor melonjak",
            ],
            answer: 1,
            explain: "Pada bunga mendekati nol, kebijakan moneter kehilangan daya dorongnya.",
          },
          {
            q: "Saat terjebak likuiditas, dorongan apa yang sering dibutuhkan?",
            options: ["Menaikkan pajak", "Kebijakan fiskal dan tak konvensional (QE)", "Menaikkan bunga", "Menghentikan belanja"],
            answer: 1,
            explain: "Dorongan fiskal dan QE melengkapi kebijakan moneter yang mentok.",
          },
          {
            q: "Negara yang terkenal mengalami deflasi berkepanjangan sejak 1990-an adalah?",
            options: ["Jerman", "Jepang", "Brasil", "Indonesia"],
            answer: 1,
            explain: "Jepang mengalami dekade yang hilang dengan deflasi dan bunga nol.",
          },
        ],
      },
    ],
  },
];
