import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "siklus-dan-pertumbuhan",
    levelId: "siklus",
    order: 1,
    title: "Siklus Bisnis & Pertumbuhan",
    summary: "Mengapa ekonomi naik-turun (boom & resesi) dan apa sumber pertumbuhan jangka panjang. Dengan video & simulator.",
    durationMin: 14,
    tags: ["siklus bisnis", "resesi", "pertumbuhan"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi tidak tumbuh mulus, melainkan berfluktuasi dalam <strong>siklus bisnis</strong>: ekspansi (boom), puncak, kontraksi (resesi), lalu palung, kemudian pulih. Di balik gejolak ini, ada <strong>tren pertumbuhan jangka panjang</strong> yang ditentukan oleh produktivitas.",
      },
      {
        type: "video",
        comp: "SiklusBisnis",
        title: "Video: Siklus Bisnis",
        caption: "Animasi gelombang ekspansi dan resesi di sekitar tren jangka panjang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Apa itu resesi",
        html: "<strong>Resesi</strong> sering didefinisikan sebagai PDB riil menyusut dua kuartal berturut-turut. Ditandai pengangguran naik, konsumsi turun, dan dunia usaha lesu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana selisih kecil tingkat pertumbuhan menghasilkan perbedaan besar dalam jangka panjang (efek majemuk).",
      },
      { type: "widget", widget: "SimulatorPertumbuhanEkonomi" },
      {
        type: "chart",
        variant: "bar",
        title: "Sumber Pertumbuhan Jangka Panjang (ilustrasi kontribusi)",
        unit: "% kontribusi",
        source: "ilustrasi pola umum",
        note: "Pertumbuhan berkelanjutan terutama berasal dari peningkatan produktivitas.",
        data: [
          { label: "Produktivitas/teknologi", value: 45, color: "#10b981" },
          { label: "Modal (investasi)", value: 30, color: "#0ea5e9" },
          { label: "Tenaga kerja", value: 25, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Kekuatan pertumbuhan majemuk",
        html: "Dua negara berangkat dari PDB sama. Negara A tumbuh 3% per tahun, negara B tumbuh 6%. Setelah 24 tahun, ekonomi A menggandakan sekali, sedangkan B menggandakan dua kali (menjadi 4 kali lipat). Selisih 3 poin pertumbuhan tampak kecil per tahun, tetapi berlipat besar dalam satu generasi.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan aturan 72, berapa tahun ekonomi menggandakan jika tumbuh 6% per tahun?",
        answer: 12,
        tolerance: 0,
        suffix: " tahun",
        solution: "Aturan 72: 72 / 6 = <strong>12 tahun</strong> untuk menggandakan PDB.",
        hint: "Bagi 72 dengan tingkat pertumbuhan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi ini menandai fase apa dalam siklus bisnis?",
        buckets: ["Ekspansi (boom)", "Kontraksi (resesi)"],
        items: [
          { text: "Pengangguran turun, konsumsi naik", bucket: "Ekspansi (boom)" },
          { text: "PDB menyusut dua kuartal berturut", bucket: "Kontraksi (resesi)" },
          { text: "Investasi & laba meningkat", bucket: "Ekspansi (boom)" },
          { text: "PHK meningkat, permintaan lesu", bucket: "Kontraksi (resesi)" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Rata-rata Durasi Fase Siklus (ilustrasi)",
        unit: "% durasi siklus",
        source: "ilustrasi pola umum siklus bisnis",
        note: "Fase ekspansi biasanya berlangsung lebih lama daripada kontraksi.",
        data: [
          { label: "Ekspansi", value: 70, color: "#10b981" },
          { label: "Kontraksi (resesi)", value: 30, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Jika PDB riil turun dari 1.000 triliun menjadi 980 triliun selama resesi, berapa persen kontraksinya?",
        answer: 2,
        tolerance: 0.1,
        suffix: "%",
        solution: "Kontraksi = (980 - 1.000) / 1.000 x 100 = -2%, jadi <strong>2%</strong>.",
        hint: "Persentase perubahan = (akhir - awal) / awal x 100.",
      },
      {
        type: "case",
        title: "Sejarah: Resesi Besar 2008",
        html: "<strong>Krisis keuangan global 2008</strong> memicu resesi terdalam sejak Depresi Besar. Pada 2009 output dunia berkontraksi untuk pertama kalinya dalam beberapa dekade dan volume perdagangan global anjlok tajam. Peristiwa ini adalah contoh nyata fase kontraksi siklus bisnis yang menyebar ke hampir seluruh dunia.",
      },
      {
        type: "takeaways",
        items: [
          "Ekonomi berfluktuasi dalam siklus bisnis: boom dan resesi.",
          "Resesi: PDB riil menyusut dua kuartal berturut-turut.",
          "Pertumbuhan jangka panjang berasal dari produktivitas, modal, dan tenaga kerja.",
          "Aturan 72 memperkirakan waktu menggandakan ekonomi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Urutan siklus bisnis yang benar?",
            options: ["Resesi, puncak, ekspansi, palung", "Ekspansi, puncak, kontraksi, palung", "Palung, resesi, puncak, boom", "Tidak ada pola"],
            answer: 1,
            explain: "Siklus: ekspansi naik ke puncak, lalu kontraksi turun ke palung, lalu pulih.",
          },
          {
            q: "Resesi sering didefinisikan sebagai?",
            options: ["Inflasi tinggi", "PDB riil menyusut dua kuartal berturut", "Ekspor naik", "Suku bunga nol"],
            answer: 1,
            explain: "Definisi umum resesi: dua kuartal berturut PDB riil menyusut.",
          },
          {
            q: "Sumber utama pertumbuhan jangka panjang?",
            options: ["Mencetak uang", "Peningkatan produktivitas", "Menaikkan harga", "Menambah utang"],
            answer: 1,
            explain: "Produktivitas (teknologi & efisiensi) adalah mesin pertumbuhan berkelanjutan.",
          },
          {
            q: "Aturan 72: tumbuh 8% menggandakan dalam?",
            options: ["9 tahun", "8 tahun", "18 tahun", "72 tahun"],
            answer: 0,
            explain: "72 / 8 = 9 tahun.",
          },
          {
            q: "Tanda fase ekspansi adalah?",
            options: ["Pengangguran naik", "Konsumsi & investasi meningkat", "PDB menyusut", "PHK massal"],
            answer: 1,
            explain: "Ekspansi ditandai naiknya konsumsi, investasi, dan lapangan kerja.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ad-as",
    levelId: "siklus",
    order: 2,
    title: "Permintaan Agregat & Penawaran Agregat",
    summary: "Model AD-AS menjelaskan keseimbangan makro: bagaimana output dan tingkat harga ditentukan, serta dampak guncangan permintaan dan penawaran.",
    durationMin: 13,
    tags: ["AD-AS", "keseimbangan makro", "guncangan"],
    blocks: [
      {
        type: "paragraph",
        html: "Model <strong>AD-AS</strong> (Aggregate Demand - Aggregate Supply) memetakan keseluruhan ekonomi pada dua sumbu: tingkat harga (vertikal) dan output riil/PDB (horizontal). Kurva <strong>permintaan agregat (AD)</strong> melandai turun karena saat tingkat harga lebih rendah, daya beli, ekspor, dan investasi cenderung naik sehingga jumlah barang yang diminta meningkat.",
      },
      {
        type: "paragraph",
        html: "Kurva <strong>penawaran agregat (AS)</strong> menanjak dalam jangka pendek karena harga jual naik lebih cepat daripada biaya, mendorong produsen menambah produksi. Dalam jangka panjang, AS bersifat tegak di tingkat output potensial yang ditentukan oleh kapasitas (modal, tenaga kerja, teknologi), bukan oleh tingkat harga. <strong>Keseimbangan makro</strong> terjadi di titik potong AD dan AS, menentukan tingkat harga dan output keseimbangan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Keseimbangan makro",
        html: "Titik potong AD dan AS menentukan <strong>tingkat harga keseimbangan</strong> dan <strong>output riil keseimbangan</strong> secara bersamaan untuk seluruh perekonomian.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Guncangan permintaan vs penawaran",
        html: "<strong>Guncangan permintaan</strong> menggeser AD (mis. lonjakan belanja pemerintah). <strong>Guncangan penawaran</strong> menggeser AS (mis. harga minyak melonjak), yang bisa memicu <strong>stagflasi</strong>: output turun sekaligus harga naik.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati menafsirkan",
        html: "Output keseimbangan jangka pendek bisa berada di bawah output potensial (kesenjangan resesi) atau di atasnya (kesenjangan inflasi). Yang di atas potensial tidak berkelanjutan dan memicu tekanan inflasi.",
      },
      {
        type: "video",
        comp: "ADASVideo",
        title: "Video: Model AD-AS",
        caption: "Animasi pergeseran kurva AD dan AS serta pembentukan titik keseimbangan makro.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Guncangan terhadap Output & Harga (arah perubahan)",
        unit: "indeks arah (+naik / -turun)",
        source: "ilustrasi model AD-AS",
        note: "Guncangan penawaran negatif menaikkan harga tetapi menurunkan output (stagflasi).",
        data: [
          { label: "AD naik: output", value: 1, color: "#10b981" },
          { label: "AD naik: harga", value: 1, color: "#f59e0b" },
          { label: "AS turun: output", value: -1, color: "#ef4444" },
          { label: "AS turun: harga", value: 1, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Guncangan harga energi",
        html: "Sebuah negara mengalami lonjakan harga minyak impor sebesar 40%. Biaya produksi naik di hampir semua sektor sehingga kurva AS bergeser ke kiri. Akibatnya output riil turun dari 100 menjadi 96 (kontraksi sekitar 4%), sementara tingkat harga melonjak dari indeks 110 menjadi 118. Inilah gambaran stagflasi: pertumbuhan negatif berbarengan dengan inflasi tinggi.",
      },
      {
        type: "calcExercise",
        prompt: "Jika output riil turun dari 100 menjadi 96 akibat guncangan penawaran, berapa persen kontraksi output?",
        answer: 4,
        tolerance: 0.1,
        suffix: "%",
        solution: "Perubahan = (96 - 100) / 100 = -0,04 = <strong>-4%</strong>, jadi kontraksi 4%.",
        hint: "Persentase perubahan = (nilai akhir - nilai awal) / nilai awal x 100.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan peristiwa dengan pergeseran kurva yang ditimbulkannya.",
        pairs: [
          { left: "Belanja pemerintah naik tajam", right: "AD bergeser ke kanan" },
          { left: "Harga minyak dunia melonjak", right: "AS bergeser ke kiri" },
          { left: "Kepercayaan konsumen anjlok", right: "AD bergeser ke kiri" },
          { left: "Teknologi produksi membaik", right: "AS bergeser ke kanan" },
        ],
      },
      { type: "widget", widget: "SimulatorADAS" },
      {
        type: "chart",
        variant: "line",
        title: "Tingkat Harga Indeks Setelah Guncangan Penawaran",
        unit: "indeks harga",
        source: "ilustrasi model AD-AS",
        note: "Guncangan penawaran negatif menggeser AS ke kiri dan menaikkan tingkat harga keseimbangan.",
        data: [
          { label: "Sebelum guncangan", value: 110, color: "#0ea5e9" },
          { label: "Saat guncangan", value: 114, color: "#f59e0b" },
          { label: "Keseimbangan baru", value: 118, color: "#ef4444" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap peristiwa sebagai guncangan permintaan atau guncangan penawaran.",
        buckets: ["Guncangan permintaan", "Guncangan penawaran"],
        items: [
          { text: "Belanja pemerintah melonjak", bucket: "Guncangan permintaan" },
          { text: "Harga energi impor naik tajam", bucket: "Guncangan penawaran" },
          { text: "Kepercayaan konsumen anjlok", bucket: "Guncangan permintaan" },
          { text: "Gagal panen menaikkan biaya pangan", bucket: "Guncangan penawaran" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Guncangan minyak OPEC 1973",
        html: "<strong>Guncangan minyak OPEC 1973</strong> melipatgandakan harga minyak dunia dan menggeser kurva penawaran agregat (AS) ke kiri. Akibatnya negara-negara industri mengalami <strong>stagflasi</strong>: output turun sekaligus inflasi naik. Kombinasi ini sulit dijelaskan oleh model permintaan semata dan menjadi bukti nyata dampak guncangan penawaran dalam kerangka AD-AS.",
      },
      {
        type: "takeaways",
        items: [
          "AD melandai turun; AS jangka pendek menanjak; AS jangka panjang tegak di output potensial.",
          "Keseimbangan makro adalah titik potong AD dan AS yang menentukan harga dan output.",
          "Guncangan permintaan menggeser AD; guncangan penawaran menggeser AS.",
          "Guncangan penawaran negatif dapat memicu stagflasi: output turun, harga naik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa kurva permintaan agregat melandai turun?",
            options: ["Karena biaya produksi naik", "Karena tingkat harga lebih rendah meningkatkan jumlah barang yang diminta", "Karena pajak naik", "Karena output potensial tetap"],
            answer: 1,
            explain: "Tingkat harga lebih rendah menaikkan daya beli, ekspor, dan investasi sehingga jumlah diminta naik.",
          },
          {
            q: "Kurva penawaran agregat jangka panjang berbentuk?",
            options: ["Melandai turun", "Menanjak", "Tegak di output potensial", "Datar sempurna"],
            answer: 2,
            explain: "Dalam jangka panjang output ditentukan kapasitas, bukan tingkat harga, sehingga AS tegak.",
          },
          {
            q: "Keseimbangan makro terjadi di?",
            options: ["Titik potong AD dan AS", "Titik tertinggi AD", "Titik terendah AS", "Saat harga nol"],
            answer: 0,
            explain: "Keseimbangan adalah titik potong AD dan AS yang menentukan harga dan output bersamaan.",
          },
          {
            q: "Lonjakan harga minyak impor adalah contoh?",
            options: ["Guncangan permintaan positif", "Guncangan penawaran negatif", "Kenaikan output potensial", "Penurunan pajak"],
            answer: 1,
            explain: "Kenaikan biaya input menggeser AS ke kiri, yaitu guncangan penawaran negatif.",
          },
          {
            q: "Stagflasi ditandai oleh?",
            options: ["Output naik, harga turun", "Output turun, harga naik", "Output dan harga sama-sama turun", "Output dan harga sama-sama naik"],
            answer: 1,
            explain: "Stagflasi: kontraksi output berbarengan dengan inflasi tinggi akibat guncangan penawaran.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pertumbuhan-jangka-panjang",
    levelId: "siklus",
    order: 3,
    title: "Pertumbuhan Ekonomi Jangka Panjang",
    summary: "Tiga sumber pertumbuhan: akumulasi modal, tenaga kerja, dan produktivitas/teknologi. Plus aturan 72 untuk memperkirakan waktu menggandakan PDB.",
    durationMin: 13,
    tags: ["pertumbuhan", "produktivitas", "aturan 72"],
    blocks: [
      {
        type: "paragraph",
        html: "Pertumbuhan jangka panjang berarti meningkatnya kapasitas produksi ekonomi seiring waktu. Sumbernya dapat dibagi menjadi tiga: <strong>akumulasi modal</strong> (mesin, infrastruktur), <strong>pertumbuhan tenaga kerja</strong> (jumlah dan kualitas/keterampilan pekerja), serta <strong>produktivitas dan teknologi</strong> (seberapa efisien input diubah menjadi output).",
      },
      {
        type: "paragraph",
        html: "Modal dan tenaga kerja menghadapi <strong>hasil yang menurun</strong> (diminishing returns): menambah mesin terus-menerus pada jumlah pekerja tetap memberi tambahan output yang makin kecil. Karena itu, mesin pertumbuhan yang berkelanjutan adalah <strong>produktivitas</strong> yang naik berkat inovasi teknologi, pendidikan, dan perbaikan kelembagaan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Mengapa produktivitas raja",
        html: "Produktivitas (output per pekerja) adalah satu-satunya sumber yang dapat menaikkan standar hidup secara terus-menerus tanpa batas hasil yang menurun.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Aturan 72",
        html: "Waktu menggandakan PDB kira-kira <strong>72 dibagi tingkat pertumbuhan (%)</strong>. Tumbuh 6% berarti menggandakan dalam sekitar 12 tahun.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Modal manusia",
        html: "Tenaga kerja bukan hanya soal jumlah. <strong>Modal manusia</strong> (pendidikan, kesehatan, keterampilan) meningkatkan produktivitas tiap pekerja dan menjadi penentu penting pertumbuhan.",
      },
      { type: "widget", widget: "SimulatorPertumbuhanEkonomi" },
      {
        type: "chart",
        variant: "line",
        title: "PDB Indeks: Pertumbuhan 3% vs 6% per Tahun",
        unit: "indeks (awal = 100)",
        source: "ilustrasi efek majemuk",
        note: "Selisih kecil tingkat pertumbuhan menghasilkan jurang besar dalam jangka panjang.",
        data: [
          { label: "Tahun 0", value: 100, color: "#0ea5e9" },
          { label: "Tahun 12 (3%)", value: 143, color: "#0ea5e9" },
          { label: "Tahun 24 (3%)", value: 203, color: "#0ea5e9" },
          { label: "Tahun 12 (6%)", value: 201, color: "#10b981" },
          { label: "Tahun 24 (6%)", value: 405, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua jalur pertumbuhan",
        html: "Negara X menambah pabrik dan jalan tol (akumulasi modal) tetapi produktivitasnya stagnan; pertumbuhannya melambat saat hasil modal menurun, dari 7% menjadi 3% dalam satu dekade. Negara Y berinvestasi pada pendidikan dan riset sehingga produktivitas naik 2% per tahun; pertumbuhannya bertahan di sekitar 6%. Dengan aturan 72, Y menggandakan PDB tiap 12 tahun, sedangkan X butuh 24 tahun.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan aturan 72, berapa tahun PDB menggandakan jika tumbuh 4% per tahun?",
        answer: 18,
        tolerance: 0,
        suffix: " tahun",
        solution: "Aturan 72: 72 / 4 = <strong>18 tahun</strong>.",
        hint: "Bagi 72 dengan tingkat pertumbuhan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap faktor ke sumber pertumbuhan yang paling tepat.",
        buckets: ["Akumulasi modal", "Tenaga kerja", "Produktivitas/teknologi"],
        items: [
          { text: "Membangun pelabuhan dan pabrik baru", bucket: "Akumulasi modal" },
          { text: "Bonus demografi menambah angkatan kerja", bucket: "Tenaga kerja" },
          { text: "Adopsi otomasi dan perangkat lunak", bucket: "Produktivitas/teknologi" },
          { text: "Investasi mesin produksi", bucket: "Akumulasi modal" },
          { text: "Pelatihan keterampilan menaikkan efisiensi", bucket: "Produktivitas/teknologi" },
        ],
      },
      {
        type: "chart",
        variant: "area",
        title: "Hasil yang Menurun pada Akumulasi Modal (ilustrasi)",
        unit: "tambahan output per unit modal",
        source: "ilustrasi diminishing returns",
        note: "Tambahan output dari setiap unit modal baru makin kecil saat tenaga kerja tetap.",
        data: [
          { label: "Modal unit 1", value: 40, color: "#0ea5e9" },
          { label: "Modal unit 2", value: 28, color: "#0ea5e9" },
          { label: "Modal unit 3", value: 18, color: "#10b981" },
          { label: "Modal unit 4", value: 10, color: "#10b981" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tingkat pertumbuhan dengan waktu menggandakan PDB menurut aturan 72.",
        pairs: [
          { left: "Tumbuh 2% per tahun", right: "36 tahun" },
          { left: "Tumbuh 3% per tahun", right: "24 tahun" },
          { left: "Tumbuh 6% per tahun", right: "12 tahun" },
          { left: "Tumbuh 8% per tahun", right: "9 tahun" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Transformasi produktivitas Korea Selatan",
        html: "<strong>Korea Selatan</strong> mengubah diri dari negara agraris miskin pada 1960 menjadi ekonomi maju dalam satu generasi. Kuncinya bukan sekadar menumpuk modal, melainkan investasi besar pada pendidikan dan teknologi yang menaikkan <strong>produktivitas</strong>. Pendapatan per kapitanya melonjak dari sekitar <strong>USD 100</strong> menjadi lebih dari <strong>USD 30.000</strong>, menegaskan peran produktivitas sebagai mesin pertumbuhan jangka panjang.",
      },
      {
        type: "takeaways",
        items: [
          "Tiga sumber pertumbuhan: modal, tenaga kerja, dan produktivitas/teknologi.",
          "Modal dan tenaga kerja menghadapi hasil yang menurun.",
          "Produktivitas adalah mesin pertumbuhan berkelanjutan dan penaik standar hidup.",
          "Aturan 72: waktu menggandakan PDB = 72 / tingkat pertumbuhan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah yang bukan sumber utama pertumbuhan jangka panjang?",
            options: ["Akumulasi modal", "Pertumbuhan tenaga kerja", "Produktivitas/teknologi", "Mencetak lebih banyak uang"],
            answer: 3,
            explain: "Mencetak uang memicu inflasi, bukan menambah kapasitas produksi riil.",
          },
          {
            q: "Apa itu hasil yang menurun (diminishing returns)?",
            options: ["Tambahan input memberi tambahan output makin kecil", "Output selalu naik konstan", "Produktivitas tak terbatas", "Modal tidak pernah usang"],
            answer: 0,
            explain: "Menambah satu input pada input lain yang tetap memberi tambahan output yang makin kecil.",
          },
          {
            q: "Sumber pertumbuhan yang paling berkelanjutan adalah?",
            options: ["Menambah mesin terus-menerus", "Produktivitas/teknologi", "Menambah jam kerja saja", "Menaikkan harga"],
            answer: 1,
            explain: "Produktivitas tidak terkena batas hasil menurun yang sama, sehingga berkelanjutan.",
          },
          {
            q: "Aturan 72: tumbuh 9% menggandakan PDB dalam?",
            options: ["6 tahun", "8 tahun", "9 tahun", "12 tahun"],
            answer: 1,
            explain: "72 / 9 = 8 tahun.",
          },
          {
            q: "Modal manusia mengacu pada?",
            options: ["Jumlah uang tunai", "Pendidikan, kesehatan, dan keterampilan pekerja", "Mesin pabrik", "Cadangan devisa"],
            answer: 1,
            explain: "Modal manusia adalah kualitas tenaga kerja yang menaikkan produktivitas.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pembangunan-ekonomi",
    levelId: "siklus",
    order: 4,
    title: "Pembangunan Ekonomi",
    summary: "Beda pertumbuhan dan pembangunan, indikator IPM/HDI, kemiskinan dan ketimpangan (koefisien Gini), serta pembangunan berkelanjutan dalam konteks Indonesia.",
    durationMin: 14,
    tags: ["pembangunan", "IPM", "Gini", "Indonesia"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pertumbuhan ekonomi</strong> mengukur kenaikan output (PDB) secara kuantitatif. <strong>Pembangunan ekonomi</strong> lebih luas: ia mencakup perbaikan kualitas hidup, distribusi pendapatan, kesehatan, pendidikan, dan keberlanjutan. Sebuah negara bisa tumbuh tetapi gagal membangun bila hasilnya hanya dinikmati segelintir orang.",
      },
      {
        type: "paragraph",
        html: "Untuk menangkap dimensi yang lebih kaya, dipakai <strong>Indeks Pembangunan Manusia (IPM/HDI)</strong> yang menggabungkan tiga dimensi: kesehatan (umur harapan hidup), pendidikan (harapan & rata-rata lama sekolah), dan standar hidup (pendapatan per kapita). Nilainya berkisar 0 sampai 1 (atau 0 sampai 100 pada skala BPS).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pertumbuhan vs pembangunan",
        html: "Pertumbuhan = naiknya PDB (kuantitas). Pembangunan = naiknya kesejahteraan menyeluruh: kesehatan, pendidikan, pemerataan, dan keberlanjutan (kualitas).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Koefisien Gini",
        html: "<strong>Koefisien Gini</strong> mengukur ketimpangan pendapatan dari 0 (pemerataan sempurna) sampai 1 (satu orang menguasai semua). Indonesia berada di sekitar 0,38, tergolong ketimpangan sedang.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kemiskinan tetap PR",
        html: "Meski tingkat kemiskinan Indonesia turun ke kisaran 9%, masih ada sekitar 25 juta penduduk miskin. Pembangunan berkelanjutan menuntut pertumbuhan yang inklusif dan ramah lingkungan.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren IPM Indonesia (skala BPS 0-100)",
        unit: "indeks IPM",
        source: "ilustrasi berbasis data BPS",
        note: "IPM Indonesia terus naik dan masuk kategori tinggi (di atas 70).",
        data: [
          { label: "2010", value: 66.5, color: "#0ea5e9" },
          { label: "2015", value: 69.6, color: "#0ea5e9" },
          { label: "2020", value: 71.9, color: "#10b981" },
          { label: "2023", value: 74.4, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pertumbuhan tanpa pemerataan",
        html: "Sebuah daerah mencatat PDB tumbuh 6% per tahun, namun koefisien Gini-nya naik dari 0,35 menjadi 0,42 dan tingkat kemiskinan hanya turun tipis. Artinya buah pertumbuhan terkonsentrasi pada kelompok atas. Ini contoh pertumbuhan yang belum menjadi pembangunan: angka PDB membaik, tetapi kesejahteraan tidak merata.",
      },
      {
        type: "calcExercise",
        prompt: "Jika ada 25,2 juta penduduk miskin dari total 280 juta penduduk, berapa tingkat kemiskinan (%)?",
        answer: 9,
        tolerance: 0.2,
        suffix: "%",
        solution: "Tingkat kemiskinan = 25,2 / 280 x 100 = <strong>9,0%</strong>.",
        hint: "Bagi jumlah penduduk miskin dengan total penduduk, lalu kalikan 100.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan indikator dengan apa yang diukurnya.",
        pairs: [
          { left: "IPM/HDI", right: "Capaian pembangunan manusia (kesehatan, pendidikan, pendapatan)" },
          { left: "Koefisien Gini", right: "Tingkat ketimpangan pendapatan" },
          { left: "Tingkat kemiskinan", right: "Persentase penduduk di bawah garis kemiskinan" },
          { left: "Pertumbuhan PDB", right: "Kenaikan output ekonomi secara kuantitatif" },
        ],
      },
      {
        type: "video",
        comp: "PembangunanEkonomi",
        title: "Video: Pembangunan Ekonomi",
        caption: "Animasi beda pertumbuhan dan pembangunan serta tiga dimensi IPM.",
      },
      { type: "widget", widget: "KalkulatorIPM" },
      {
        type: "chart",
        variant: "bar",
        title: "Tiga Dimensi Penyusun IPM (indeks dimensi, ilustrasi)",
        unit: "indeks dimensi (0-1)",
        source: "ilustrasi berbasis metode UNDP/BPS",
        note: "IPM adalah rata-rata geometrik dari ketiga indeks dimensi ini.",
        data: [
          { label: "Kesehatan", value: 0.8, color: "#10b981" },
          { label: "Pendidikan", value: 0.65, color: "#0ea5e9" },
          { label: "Standar hidup", value: 0.72, color: "#f59e0b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Indeks kesehatan 0,6, indeks pendidikan 0,7, indeks pendapatan 0,8. Berapa IPM (rata-rata geometrik tiga dimensi)?",
        answer: 0.695,
        tolerance: 0.01,
        solution: "IPM = (0,6 x 0,7 x 0,8)^(1/3) = (0,336)^(1/3) = <strong>0,695</strong>. IPM memakai rata-rata geometrik, bukan rata-rata biasa.",
        hint: "Kalikan ketiga indeks lalu ambil akar pangkat tiga.",
      },
      {
        type: "case",
        title: "Sejarah: Lonjakan IPM dan turunnya kemiskinan Indonesia",
        html: "Pembangunan Indonesia terlihat dari indikator jangka panjang: tingkat kemiskinan turun dari sekitar <strong>40%</strong> pada pertengahan 1970-an menjadi sekitar <strong>9%</strong> belakangan ini, sementara IPM naik dari <strong>66,5 (2010)</strong> menjadi <strong>74,4 (2023)</strong>. Perbaikan ini, yang ditopang antara lain oleh reformasi subsidi dan belanja sosial, menunjukkan pembangunan yang melampaui sekadar angka PDB.",
      },
      {
        type: "takeaways",
        items: [
          "Pertumbuhan mengukur kuantitas output; pembangunan mengukur kualitas kesejahteraan.",
          "IPM/HDI menggabungkan kesehatan, pendidikan, dan standar hidup (0 sampai 1).",
          "Koefisien Gini mengukur ketimpangan: 0 merata sempurna, 1 sangat timpang; Indonesia sekitar 0,38.",
          "Pembangunan berkelanjutan menuntut pertumbuhan inklusif dan ramah lingkungan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Perbedaan utama pertumbuhan dan pembangunan ekonomi?",
            options: ["Keduanya sama persis", "Pertumbuhan soal kuantitas output; pembangunan soal kualitas kesejahteraan menyeluruh", "Pembangunan hanya soal PDB", "Pertumbuhan mengukur ketimpangan"],
            answer: 1,
            explain: "Pertumbuhan = kenaikan PDB; pembangunan mencakup kesehatan, pendidikan, pemerataan, keberlanjutan.",
          },
          {
            q: "Tiga dimensi IPM/HDI adalah?",
            options: ["Inflasi, pengangguran, ekspor", "Kesehatan, pendidikan, standar hidup", "Modal, tenaga kerja, teknologi", "Konsumsi, investasi, ekspor"],
            answer: 1,
            explain: "IPM menggabungkan umur harapan hidup, lama sekolah, dan pendapatan per kapita.",
          },
          {
            q: "Koefisien Gini bernilai 0 berarti?",
            options: ["Ketimpangan maksimum", "Pemerataan pendapatan sempurna", "Tidak ada data", "Kemiskinan nol"],
            answer: 1,
            explain: "Gini 0 = setiap orang berpendapatan sama (merata sempurna); 1 = sangat timpang.",
          },
          {
            q: "Koefisien Gini Indonesia berada di kisaran?",
            options: ["0,05", "0,38", "0,75", "0,95"],
            answer: 1,
            explain: "Gini Indonesia sekitar 0,38, tergolong ketimpangan sedang.",
          },
          {
            q: "Pembangunan berkelanjutan menekankan?",
            options: ["Pertumbuhan secepat mungkin tanpa batas", "Pertumbuhan inklusif dan ramah lingkungan bagi generasi mendatang", "Hanya PDB tinggi", "Mengabaikan kemiskinan"],
            answer: 1,
            explain: "Pembangunan berkelanjutan menyeimbangkan ekonomi, sosial, dan lingkungan lintas generasi.",
          },
        ],
      },
    ],
  },
];
