import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "inflasi",
    levelId: "inflasi",
    order: 1,
    title: "Inflasi: Penyebab & Dampak",
    summary: "Mengapa harga naik, bagaimana mengukurnya dengan IHK, dan dampaknya pada daya beli. Dengan video & kalkulator.",
    durationMin: 14,
    tags: ["inflasi", "IHK", "daya beli"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Inflasi</strong> adalah kenaikan tingkat harga secara umum dan terus-menerus. Diukur dari perubahan <strong>Indeks Harga Konsumen (IHK)</strong>, yaitu harga sekeranjang barang dan jasa yang biasa dikonsumsi rumah tangga.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Inflasi & Daya Beli",
        caption: "Animasi harga naik dari waktu ke waktu dan daya beli uang yang menurun.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua sumber inflasi",
        html: "<strong>Demand-pull</strong>: permintaan melebihi kapasitas (ekonomi memanas). <strong>Cost-push</strong>: biaya produksi naik (mis. harga BBM atau bahan baku), mendorong harga jual naik.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung tingkat inflasi dari perubahan IHK dan lihat bagaimana daya beli uangmu tergerus.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "line",
        title: "Indeks Harga Konsumen Naik dari Tahun ke Tahun (ilustrasi)",
        unit: "indeks (2019=100)",
        source: "ilustrasi edukatif",
        note: "Tingkat inflasi adalah persentase kenaikan IHK antar periode.",
        data: [
          { label: "2019", value: 100, color: "#ef4444" },
          { label: "2020", value: 102, color: "#ef4444" },
          { label: "2021", value: 104, color: "#ef4444" },
          { label: "2022", value: 110, color: "#ef4444" },
          { label: "2023", value: 114, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tabungan tergerus inflasi",
        html: "Pak Budi menabung Rp100 juta dengan bunga 3% per tahun, sementara inflasi 5%. Secara nominal uangnya bertambah, tetapi <strong>daya belinya turun</strong> karena bunga (3%) lebih rendah dari inflasi (5%). Imbal hasil riilnya negatif 2%. Inilah mengapa menjaga inflasi rendah penting bagi penabung.",
      },
      {
        type: "calcExercise",
        prompt: "IHK naik dari 110 menjadi 116,6. Berapa tingkat inflasinya (%)?",
        answer: 6,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi = (116,6 - 110) / 110 x 100 = 6,6/110 x 100 = <strong>6%</strong>.",
        hint: "Selisih IHK dibagi IHK awal, dikali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Penyebab inflasi ini demand-pull atau cost-push?",
        buckets: ["Demand-pull", "Cost-push"],
        items: [
          { text: "Belanja masyarakat melonjak saat ekonomi boom", bucket: "Demand-pull" },
          { text: "Harga BBM dunia naik tajam", bucket: "Cost-push" },
          { text: "Stimulus besar mendorong permintaan", bucket: "Demand-pull" },
          { text: "Upah dan bahan baku naik", bucket: "Cost-push" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Nilai Riil Uang Rp1.000.000 Tergerus Inflasi (ilustrasi)",
        unit: "ribu rupiah (daya beli)",
        source: "ilustrasi edukatif, IHK 2019=100",
        note: "Nilai riil = Rp1.000.000 x 100 / IHK. Saat IHK naik, daya beli uang yang sama menurun.",
        data: [
          { label: "2019", value: 1000, color: "#10b981" },
          { label: "2020", value: 980, color: "#84cc16" },
          { label: "2021", value: 962, color: "#f59e0b" },
          { label: "2022", value: 909, color: "#f97316" },
          { label: "2023", value: 877, color: "#ef4444" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah inflasi dengan pengertiannya.",
        pairs: [
          { left: "Demand-pull", right: "Permintaan melebihi kapasitas produksi" },
          { left: "Cost-push", right: "Biaya produksi naik mendorong harga jual" },
          { left: "Daya beli", right: "Jumlah barang yang bisa dibeli dengan sejumlah uang" },
          { left: "Imbal hasil riil", right: "Bunga nominal dikurangi inflasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Hiperinflasi Weimar 1923",
        html: "Pada <strong>1923</strong>, Republik Weimar (Jerman) mengalami hiperinflasi ekstrem: harga berlipat ganda dalam hitungan hari dan pada puncaknya 1 dolar AS setara sekitar <strong>4,2 triliun mark</strong>. Uang kertas menjadi nyaris tak berharga sehingga rakyat membawanya dengan gerobak. Ini contoh paling terkenal bagaimana inflasi tak terkendali menghancurkan daya beli.",
      },
      {
        type: "takeaways",
        items: [
          "Inflasi adalah kenaikan harga umum yang terus-menerus.",
          "Diukur lewat perubahan Indeks Harga Konsumen (IHK).",
          "Penyebab: demand-pull dan cost-push.",
          "Inflasi menggerus daya beli; imbal hasil riil = nominal dikurangi inflasi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inflasi adalah?",
            options: ["Kenaikan harga satu barang", "Kenaikan tingkat harga umum yang terus-menerus", "Penurunan produksi", "Kenaikan pajak"],
            answer: 1,
            explain: "Inflasi adalah kenaikan harga secara umum dan berkelanjutan.",
          },
          {
            q: "Inflasi diukur dengan?",
            options: ["PDB", "Indeks Harga Konsumen (IHK)", "Nilai tukar", "Suku bunga"],
            answer: 1,
            explain: "IHK mengukur harga sekeranjang barang konsumsi rumah tangga.",
          },
          {
            q: "Inflasi cost-push disebabkan?",
            options: ["Permintaan melonjak", "Biaya produksi naik", "Pajak turun", "Ekspor naik"],
            answer: 1,
            explain: "Cost-push terjadi saat biaya produksi (mis. BBM) mendorong harga naik.",
          },
          {
            q: "Bunga tabungan 4%, inflasi 6%. Imbal hasil riil?",
            options: ["+2%", "-2%", "+10%", "0%"],
            answer: 1,
            explain: "Riil = nominal - inflasi = 4% - 6% = -2%.",
          },
          {
            q: "IHK dari 100 ke 105. Inflasi?",
            options: ["5%", "0,5%", "105%", "50%"],
            answer: 0,
            explain: "(105-100)/100 x 100 = 5%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengukur-inflasi",
    levelId: "inflasi",
    order: 2,
    title: "Mengukur Inflasi: IHK & Keranjang Barang",
    summary: "Bagaimana BPS menyusun keranjang barang, menghitung IHK, serta beda inflasi umum dan inflasi inti.",
    durationMin: 13,
    tags: ["IHK", "inflasi inti", "BPS"],
    blocks: [
      {
        type: "paragraph",
        html: "Untuk mengukur inflasi, <strong>Badan Pusat Statistik (BPS)</strong> memantau harga sebuah <strong>keranjang barang dan jasa</strong> yang biasa dikonsumsi rumah tangga. Keranjang ini disusun dari hasil Survei Biaya Hidup, lalu setiap kelompok pengeluaran diberi <strong>bobot</strong> sesuai porsinya dalam pengeluaran rumah tangga.",
      },
      {
        type: "paragraph",
        html: "Harga keranjang diringkas menjadi <strong>Indeks Harga Konsumen (IHK)</strong> dengan tahun dasar tertentu (mis. 2018=100). Tingkat inflasi adalah persentase perubahan IHK antar periode. BPS membedakan <strong>inflasi umum</strong> (semua komponen) dengan <strong>inflasi inti</strong> yang mengeluarkan komponen harga bergejolak (volatile food) dan harga diatur pemerintah (administered prices).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Inflasi umum vs inflasi inti",
        html: "<strong>Inflasi umum</strong> mencakup semua barang dalam keranjang. <strong>Inflasi inti</strong> membuang komponen yang harganya sangat fluktuatif (cabai, bawang) dan yang diatur pemerintah (BBM, listrik, rokok) agar tren inflasi yang lebih persisten terlihat jelas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bobot menentukan dampak",
        html: "Kelompok makanan punya bobot besar dalam keranjang rumah tangga Indonesia, sehingga kenaikan harga pangan terasa kuat di angka inflasi umum.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan IHK dua periode dan lihat berapa tingkat inflasi yang dihasilkan.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "bar",
        title: "Inflasi Umum vs Inflasi Inti (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi edukatif",
        note: "Inflasi inti cenderung lebih stabil karena membuang komponen bergejolak dan harga diatur pemerintah.",
        data: [
          { label: "Umum", value: 3.0, color: "#ef4444" },
          { label: "Inti", value: 2.4, color: "#3b82f6" },
          { label: "Bergejolak", value: 5.5, color: "#f59e0b" },
          { label: "Diatur Pemerintah", value: 1.8, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Cabai melonjak, inflasi inti tenang",
        html: "Pada suatu bulan harga cabai dan bawang melonjak akibat gagal panen, mendorong <strong>inflasi umum naik ke 0,6% (month-to-month)</strong>. Namun <strong>inflasi inti hanya 0,2%</strong> karena lonjakan itu masuk komponen bergejolak yang dikeluarkan dari hitungan inti. Bank sentral lebih memperhatikan inflasi inti agar tidak salah menilai tekanan harga yang sifatnya sementara.",
      },
      {
        type: "calcExercise",
        prompt: "IHK keranjang naik dari 120 menjadi 123,6. Berapa inflasi umumnya (%)?",
        answer: 3,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi = (123,6 - 120) / 120 x 100 = 3,6/120 x 100 = <strong>3%</strong>.",
        hint: "Selisih IHK dibagi IHK awal, lalu dikali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Menurut metode BPS, komponen ini masuk inflasi inti atau di luar inti?",
        buckets: ["Inflasi Inti", "Di Luar Inti"],
        items: [
          { text: "Harga sewa rumah", bucket: "Inflasi Inti" },
          { text: "Cabai merah dan bawang", bucket: "Di Luar Inti" },
          { text: "Tarif listrik dan BBM", bucket: "Di Luar Inti" },
          { text: "Harga pakaian jadi", bucket: "Inflasi Inti" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Bobot Kelompok Pengeluaran dalam Keranjang IHK (ilustrasi)",
        unit: "% bobot",
        source: "ilustrasi edukatif, pola BPS",
        note: "Makanan dan minuman berbobot besar, sehingga kenaikan harga pangan kuat memengaruhi inflasi umum.",
        data: [
          { label: "Makanan & minuman", value: 30, color: "#ef4444" },
          { label: "Perumahan & utilitas", value: 20, color: "#3b82f6" },
          { label: "Transportasi", value: 13, color: "#f59e0b" },
          { label: "Kesehatan & pendidikan", value: 10, color: "#10b981" },
          { label: "Pakaian", value: 7, color: "#8b5cf6" },
          { label: "Lainnya", value: 20, color: "#64748b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Kelompok makanan berbobot 30% dalam keranjang dan harganya naik 10%. Berapa kontribusinya terhadap inflasi umum (poin persen)?",
        answer: 3,
        tolerance: 0.1,
        suffix: " poin",
        solution: "Kontribusi = bobot x kenaikan harga = 0,30 x 10% = <strong>3 poin persen</strong>.",
        hint: "Kalikan bobot kelompok (dalam desimal) dengan persentase kenaikan harganya.",
      },
      {
        type: "case",
        title: "Sejarah: Hiperinflasi Zimbabwe 2008",
        html: "Pada <strong>2008</strong>, Zimbabwe mengalami hiperinflasi yang begitu cepat sehingga harga berubah beberapa kali dalam sehari; inflasi resmi tahunan mencapai ratusan juta persen pada pertengahan tahun. Mengukur inflasi lewat keranjang IHK menjadi nyaris mustahil, dan pada 2009 negara itu akhirnya meninggalkan mata uangnya sendiri. Ini menunjukkan tantangan ekstrem dalam mengukur inflasi.",
      },
      {
        type: "takeaways",
        items: [
          "BPS memantau keranjang barang dengan bobot sesuai pola pengeluaran rumah tangga.",
          "IHK meringkas harga keranjang; inflasi adalah persentase perubahan IHK.",
          "Inflasi umum mencakup semua komponen; inflasi inti membuang volatile food dan administered prices.",
          "Inflasi inti menunjukkan tren harga yang lebih persisten.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Lembaga yang menghitung IHK dan inflasi di Indonesia adalah?",
            options: ["Bank Indonesia", "Badan Pusat Statistik (BPS)", "Kementerian Keuangan", "OJK"],
            answer: 1,
            explain: "BPS menyusun keranjang barang dan menghitung IHK serta inflasi.",
          },
          {
            q: "Bobot dalam keranjang IHK ditentukan berdasarkan?",
            options: ["Harga termahal", "Porsi pengeluaran rumah tangga", "Jumlah produsen", "Nilai ekspor"],
            answer: 1,
            explain: "Bobot mencerminkan besarnya porsi tiap kelompok dalam pengeluaran rumah tangga.",
          },
          {
            q: "Inflasi inti mengeluarkan komponen?",
            options: ["Semua jasa", "Volatile food dan administered prices", "Barang impor", "Barang mewah"],
            answer: 1,
            explain: "Inflasi inti membuang harga bergejolak dan harga yang diatur pemerintah.",
          },
          {
            q: "Contoh komponen harga diatur pemerintah (administered price) adalah?",
            options: ["Cabai", "BBM dan tarif listrik", "Sewa rumah", "Pakaian"],
            answer: 1,
            explain: "BBM, listrik, dan rokok termasuk administered prices.",
          },
          {
            q: "IHK dari 150 menjadi 153. Inflasinya?",
            options: ["2%", "3%", "0,2%", "20%"],
            answer: 0,
            explain: "(153-150)/150 x 100 = 3/150 x 100 = 2%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pengangguran",
    levelId: "inflasi",
    order: 3,
    title: "Pengangguran: Jenis & Cara Mengukurnya",
    summary: "Pengangguran friksional, struktural, dan siklikal, serta cara menghitung tingkat pengangguran dan partisipasi angkatan kerja.",
    durationMin: 13,
    tags: ["pengangguran", "angkatan kerja", "TPAK"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pengangguran</strong> adalah orang usia kerja yang tidak bekerja namun sedang aktif mencari pekerjaan dan siap bekerja. Bukan setiap orang tanpa pekerjaan disebut penganggur: pelajar, ibu rumah tangga, dan pensiunan yang tidak mencari kerja masuk kategori <strong>bukan angkatan kerja</strong>.",
      },
      {
        type: "paragraph",
        html: "Ada tiga jenis utama. <strong>Friksional</strong>: sementara, karena orang berpindah atau mencari kerja pertama. <strong>Struktural</strong>: keterampilan pekerja tidak cocok dengan kebutuhan pasar (mis. otomasi). <strong>Siklikal</strong>: muncul saat ekonomi lesu/resesi karena permintaan tenaga kerja turun.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua ukuran kunci",
        html: "<strong>Tingkat Pengangguran (TPT)</strong> = penganggur / angkatan kerja x 100. <strong>Tingkat Partisipasi Angkatan Kerja (TPAK)</strong> = angkatan kerja / penduduk usia kerja x 100.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Angkatan kerja itu apa?",
        html: "Angkatan kerja = orang yang bekerja + penganggur (yang aktif mencari kerja). Yang tidak bekerja dan tidak mencari kerja tidak dihitung sebagai penganggur.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan jumlah penganggur dan angkatan kerja untuk menghitung tingkat pengangguran.",
      },
      { type: "widget", widget: "KalkulatorPengangguran" },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi Jenis Pengangguran (ilustrasi)",
        unit: "% dari total penganggur",
        source: "ilustrasi edukatif",
        note: "Pengangguran siklikal naik tajam saat resesi, sedangkan friksional relatif tetap ada.",
        data: [
          { label: "Friksional", value: 35, color: "#3b82f6" },
          { label: "Struktural", value: 40, color: "#f59e0b" },
          { label: "Siklikal", value: 25, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung TPT sebuah negara",
        html: "Suatu negara punya penduduk usia kerja 200 juta. Angkatan kerjanya 140 juta (sisanya bukan angkatan kerja). Dari angkatan kerja itu, 7 juta menganggur. Maka <strong>TPT = 7/140 x 100 = 5%</strong> dan <strong>TPAK = 140/200 x 100 = 70%</strong>. Saat resesi, banyak yang kehilangan kerja sehingga pengangguran siklikal mendorong TPT naik.",
      },
      {
        type: "calcExercise",
        prompt: "Angkatan kerja 140 juta, penganggur 7 juta. Berapa tingkat pengangguran (%)?",
        answer: 5,
        tolerance: 0.1,
        suffix: "%",
        solution: "TPT = penganggur / angkatan kerja x 100 = 7/140 x 100 = <strong>5%</strong>.",
        hint: "Bagi jumlah penganggur dengan angkatan kerja, lalu kali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Termasuk jenis pengangguran apa kasus berikut?",
        buckets: ["Friksional", "Struktural", "Siklikal"],
        items: [
          { text: "Fresh graduate sedang melamar kerja pertama", bucket: "Friksional" },
          { text: "Pekerja pabrik di-PHK karena resesi", bucket: "Siklikal" },
          { text: "Operator mesin tergantikan otomasi dan butuh keterampilan baru", bucket: "Struktural" },
          { text: "Karyawan resign untuk pindah ke kota lain dan mencari kerja baru", bucket: "Friksional" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Status Penduduk Usia Kerja (ilustrasi, 200 juta orang)",
        unit: "juta orang",
        source: "ilustrasi edukatif",
        note: "Angkatan kerja = bekerja + penganggur = 133 + 7 = 140 juta. Sisanya 60 juta bukan angkatan kerja.",
        data: [
          { label: "Bekerja", value: 133, color: "#10b981" },
          { label: "Penganggur", value: 7, color: "#ef4444" },
          { label: "Bukan angkatan kerja", value: 60, color: "#64748b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Penduduk usia kerja 200 juta dan angkatan kerja 140 juta. Berapa Tingkat Partisipasi Angkatan Kerja (TPAK) dalam %?",
        answer: 70,
        tolerance: 0.1,
        suffix: "%",
        solution: "TPAK = angkatan kerja / penduduk usia kerja x 100 = 140/200 x 100 = <strong>70%</strong>.",
        hint: "Bagi angkatan kerja dengan penduduk usia kerja, lalu kali 100.",
      },
      {
        type: "case",
        title: "Sejarah: Pengangguran saat Depresi Besar",
        html: "Pada puncak <strong>Depresi Besar (1933)</strong>, tingkat pengangguran di Amerika Serikat mencapai sekitar <strong>25%</strong>, artinya satu dari empat angkatan kerja menganggur. Sebagian besar adalah pengangguran siklikal akibat anjloknya permintaan. Peristiwa ini menjadi contoh paling dramatis bagaimana resesi berat mendorong tingkat pengangguran melonjak.",
      },
      {
        type: "takeaways",
        items: [
          "Penganggur = usia kerja, tidak bekerja, tapi aktif mencari kerja.",
          "Jenis: friksional (sementara), struktural (mismatch keterampilan), siklikal (akibat resesi).",
          "TPT = penganggur / angkatan kerja x 100.",
          "TPAK = angkatan kerja / penduduk usia kerja x 100.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Siapa yang dihitung sebagai penganggur?",
            options: ["Semua orang tanpa kerja", "Usia kerja yang tidak bekerja tapi aktif mencari kerja", "Pelajar dan pensiunan", "Ibu rumah tangga"],
            answer: 1,
            explain: "Penganggur harus usia kerja, tidak bekerja, dan aktif mencari kerja.",
          },
          {
            q: "Pengangguran akibat keterampilan tidak cocok dengan kebutuhan pasar disebut?",
            options: ["Friksional", "Struktural", "Siklikal", "Musiman"],
            answer: 1,
            explain: "Struktural muncul karena mismatch keterampilan, mis. akibat otomasi.",
          },
          {
            q: "Pengangguran yang meningkat saat resesi disebut?",
            options: ["Friksional", "Struktural", "Siklikal", "Sukarela"],
            answer: 2,
            explain: "Siklikal mengikuti siklus bisnis dan naik saat ekonomi lesu.",
          },
          {
            q: "Rumus tingkat pengangguran (TPT) adalah?",
            options: ["Penganggur / penduduk x 100", "Penganggur / angkatan kerja x 100", "Angkatan kerja / penduduk x 100", "Bekerja / penganggur x 100"],
            answer: 1,
            explain: "TPT = penganggur dibagi angkatan kerja, dikali 100.",
          },
          {
            q: "Angkatan kerja 50 juta, penganggur 4 juta. TPT?",
            options: ["8%", "4%", "12,5%", "0,8%"],
            answer: 0,
            explain: "4/50 x 100 = 8%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kurva-phillips",
    levelId: "inflasi",
    order: 4,
    title: "Kurva Phillips: Inflasi vs Pengangguran",
    summary: "Trade-off antara inflasi dan pengangguran dalam jangka pendek, serta mengapa hubungan ini lenyap dalam jangka panjang.",
    durationMin: 13,
    tags: ["kurva phillips", "inflasi", "pengangguran"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Kurva Phillips</strong> menggambarkan hubungan terbalik antara inflasi dan pengangguran dalam <strong>jangka pendek</strong>: ketika pengangguran turun, inflasi cenderung naik, dan sebaliknya. Saat permintaan kuat, perusahaan menambah pekerja dan menaikkan harga sekaligus.",
      },
      {
        type: "paragraph",
        html: "Trade-off ini hanya berlaku jangka pendek. Dalam <strong>jangka panjang</strong>, perekonomian kembali ke <strong>tingkat pengangguran alamiah</strong>, sehingga kurva Phillips menjadi tegak lurus (vertikal): mendorong inflasi lebih tinggi tidak lagi menurunkan pengangguran secara permanen, hanya menaikkan harga.",
      },
      {
        type: "video",
        comp: "KurvaPhillips",
        title: "Video: Kurva Phillips Jangka Pendek",
        caption: "Animasi pergerakan di sepanjang kurva: pengangguran turun, inflasi naik.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Inti trade-off jangka pendek",
        html: "Kebijakan yang memanaskan ekonomi bisa menurunkan pengangguran tetapi dengan ongkos inflasi yang lebih tinggi. Tidak ada makan siang gratis.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangka panjang berbeda",
        html: "Begitu ekspektasi inflasi menyesuaikan, pengangguran kembali ke tingkat alamiah. Inflasi tinggi yang menetap tidak membeli lapangan kerja permanen, bahkan bisa berujung stagflasi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Stagflasi",
        html: "Pada 1970-an, inflasi dan pengangguran naik bersamaan akibat guncangan biaya (harga minyak). Ini menantang versi sederhana kurva Phillips dan menegaskan peran ekspektasi.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Kurva Phillips Jangka Pendek (ilustrasi)",
        unit: "inflasi (%) terhadap tingkat pengangguran",
        source: "ilustrasi edukatif",
        note: "Saat pengangguran turun dari 8% ke 4%, inflasi naik: hubungan terbalik.",
        data: [
          { label: "Pengangguran 8%", value: 1, color: "#3b82f6" },
          { label: "Pengangguran 7%", value: 2, color: "#3b82f6" },
          { label: "Pengangguran 6%", value: 3, color: "#3b82f6" },
          { label: "Pengangguran 5%", value: 4, color: "#3b82f6" },
          { label: "Pengangguran 4%", value: 5, color: "#3b82f6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memanaskan ekonomi",
        html: "Bank sentral melonggarkan kebijakan untuk menurunkan pengangguran dari 6% menjadi 5%. Mengikuti kurva Phillips jangka pendek, setiap penurunan 1 poin pengangguran menaikkan inflasi sekitar 0,5 poin. Maka <strong>inflasi naik dari 3% menjadi 3,5%</strong>. Dalam jangka panjang, pengangguran kembali ke tingkat alamiahnya dan yang tersisa hanyalah inflasi yang lebih tinggi.",
      },
      {
        type: "calcExercise",
        prompt: "Inflasi awal 3%. Pengangguran turun 1 poin dan menaikkan inflasi 0,5 poin per 1 poin penurunan. Berapa inflasi barunya (%)?",
        answer: 3.5,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi baru = 3% + (1 x 0,5%) = <strong>3,5%</strong>.",
        hint: "Tambahkan kenaikan inflasi ke inflasi awal.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini berlaku untuk kurva Phillips jangka pendek atau jangka panjang?",
        buckets: ["Jangka Pendek", "Jangka Panjang"],
        items: [
          { text: "Ada trade-off: pengangguran turun, inflasi naik", bucket: "Jangka Pendek" },
          { text: "Kurva tegak lurus di tingkat pengangguran alamiah", bucket: "Jangka Panjang" },
          { text: "Inflasi lebih tinggi tidak menurunkan pengangguran secara permanen", bucket: "Jangka Panjang" },
          { text: "Memanaskan ekonomi sementara menekan pengangguran", bucket: "Jangka Pendek" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Kurva Phillips Jangka Panjang: Vertikal di Pengangguran Alamiah (ilustrasi)",
        unit: "tingkat pengangguran (%)",
        source: "ilustrasi edukatif",
        note: "Berapa pun tingkat inflasinya, pengangguran tetap di tingkat alamiah 5%: kurva jangka panjang vertikal.",
        data: [
          { label: "Inflasi 2%", value: 5, color: "#3b82f6" },
          { label: "Inflasi 4%", value: 5, color: "#3b82f6" },
          { label: "Inflasi 6%", value: 5, color: "#3b82f6" },
          { label: "Inflasi 8%", value: 5, color: "#3b82f6" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Inflasi awal 2%. Pengangguran turun 3 poin, dan tiap 1 poin penurunan menaikkan inflasi 0,5 poin. Berapa inflasi barunya (%)?",
        answer: 3.5,
        tolerance: 0.1,
        suffix: "%",
        solution: "Inflasi baru = 2% + (3 x 0,5%) = 2% + 1,5% = <strong>3,5%</strong>.",
        hint: "Kalikan penurunan pengangguran dengan 0,5 poin, lalu tambahkan ke inflasi awal.",
      },
      {
        type: "case",
        title: "Sejarah: Stagflasi 1970-an meruntuhkan kurva Phillips",
        html: "Pada <strong>1970-an</strong>, guncangan harga minyak OPEC (1973) membuat banyak negara industri mengalami inflasi tinggi dan pengangguran tinggi <strong>secara bersamaan</strong>, kondisi yang disebut stagflasi. Fakta ini meruntuhkan keyakinan pada kurva Phillips sederhana yang menjanjikan trade-off stabil, dan menegaskan pentingnya peran ekspektasi serta guncangan penawaran.",
      },
      {
        type: "takeaways",
        items: [
          "Kurva Phillips jangka pendek menunjukkan hubungan terbalik inflasi-pengangguran.",
          "Menurunkan pengangguran lewat permintaan biasanya menaikkan inflasi.",
          "Jangka panjang: kurva vertikal di tingkat pengangguran alamiah.",
          "Ekspektasi inflasi dan guncangan biaya (stagflasi) dapat menggeser kurva.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kurva Phillips jangka pendek menggambarkan hubungan antara?",
            options: ["PDB dan ekspor", "Inflasi dan pengangguran", "Suku bunga dan nilai tukar", "Pajak dan belanja"],
            answer: 1,
            explain: "Kurva Phillips menghubungkan inflasi dengan tingkat pengangguran.",
          },
          {
            q: "Dalam jangka pendek, ketika pengangguran turun maka inflasi cenderung?",
            options: ["Naik", "Turun", "Tetap", "Nol"],
            answer: 0,
            explain: "Hubungannya terbalik: pengangguran turun, inflasi naik.",
          },
          {
            q: "Dalam jangka panjang, kurva Phillips berbentuk?",
            options: ["Mendatar", "Vertikal di tingkat pengangguran alamiah", "Naik ke kanan", "Lingkaran"],
            answer: 1,
            explain: "Jangka panjang pengangguran kembali ke tingkat alamiah, kurva vertikal.",
          },
          {
            q: "Kondisi inflasi dan pengangguran naik bersamaan disebut?",
            options: ["Deflasi", "Stagflasi", "Resesi ringan", "Disinflasi"],
            answer: 1,
            explain: "Stagflasi: inflasi tinggi bersamaan dengan pengangguran tinggi.",
          },
          {
            q: "Inflasi 4%, pengangguran turun 2 poin, tiap poin menaikkan inflasi 0,5 poin. Inflasi baru?",
            options: ["5%", "4,5%", "6%", "3%"],
            answer: 0,
            explain: "4% + (2 x 0,5%) = 4% + 1% = 5%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "inflasi-daya-beli",
    levelId: "inflasi",
    order: 5,
    title: "Inflasi & Daya Beli Uang",
    summary: "Bagaimana inflasi menggerus nilai riil uang, beda upah nominal dan riil, serta peran indeksasi untuk melindungi daya beli.",
    durationMin: 14,
    tags: ["daya beli", "nilai riil", "upah riil", "indeksasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Inflasi tidak hanya soal angka harga; ia menggerus <strong>daya beli</strong> uang. Rp100 ribu hari ini membeli lebih banyak barang daripada Rp100 ribu lima tahun mendatang jika harga terus naik. Untuk mengukurnya kita memakai <strong>nilai riil</strong>: nilai uang setelah disesuaikan dengan tingkat harga. Nilai riil = nilai nominal / (IHK / 100).",
      },
      {
        type: "paragraph",
        html: "Konsep yang sama berlaku untuk gaji. <strong>Upah nominal</strong> adalah angka rupiah di slip gaji, sedangkan <strong>upah riil</strong> adalah daya belinya. Jika upah nominal naik 8% tetapi inflasi 6%, kenaikan kesejahteraan sebenarnya hanya sekitar 2%. Karena itulah banyak kontrak memakai <strong>indeksasi</strong>: penyesuaian otomatis nilai (upah, pensiun, kontrak) mengikuti inflasi agar daya beli tidak tergerus.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Inflasi Menggerus Daya Beli",
        caption: "Animasi bagaimana nilai uang yang sama membeli makin sedikit barang ketika harga naik.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus nilai riil",
        html: "Nilai riil = nilai nominal / (IHK / 100). Upah riil = upah nominal / (IHK / 100). Perubahan upah riil kira-kira = kenaikan upah nominal (%) - inflasi (%).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa target inflasi positif kecil?",
        html: "Bank Indonesia menargetkan inflasi sekitar 2,5% plus minus 1%, bukan nol. Inflasi rendah yang stabil memberi ruang penyesuaian harga dan menjauhkan ekonomi dari deflasi yang justru bisa menahan belanja.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tabungan tunai bisa menyusut",
        html: "Uang yang disimpan tunai kehilangan daya beli saat inflasi. Jika bunga tabungan lebih rendah dari inflasi, nilai riil simpanan justru turun meski angka nominalnya bertambah.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Daya Beli Rp1 Juta dengan Inflasi 5% per Tahun (ilustrasi)",
        unit: "ribu rupiah (nilai riil)",
        source: "ilustrasi perhitungan, inflasi 5% per tahun",
        note: "Pada inflasi 5%, daya beli Rp1 juta turun menjadi sekitar Rp784 ribu setelah 5 tahun.",
        data: [
          { label: "Tahun 0", value: 1000, color: "#f59e0b" },
          { label: "Tahun 1", value: 952, color: "#f59e0b" },
          { label: "Tahun 3", value: 864, color: "#f59e0b" },
          { label: "Tahun 5", value: 784, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: kenaikan gaji yang semu",
        html: "Gaji Andi naik dari Rp5 juta menjadi Rp5,4 juta, naik 8%. Tetapi pada tahun yang sama inflasi 6%, sehingga IHK naik dari 100 ke 106. Upah riilnya = 5,4 juta / (106 / 100) = Rp5,09 juta. Daya belinya hanya naik sekitar <strong>1,9%</strong>, jauh lebih kecil dari angka 8% yang terlihat di slip gaji.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur IHK dan harga untuk melihat berapa laju inflasi, lalu bayangkan dampaknya pada nilai riil gaji dan tabunganmu.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "calcExercise",
        prompt: "Upah nominal Rp6 juta, IHK = 120 (tahun dasar = 100). Berapa upah riil (rupiah, dalam juta)?",
        answer: 5,
        tolerance: 0.05,
        prefix: "Rp",
        suffix: " juta",
        solution: "Upah riil = 6 / (120 / 100) = 6 / 1,2 = <strong>Rp5 juta</strong>. Daya beli setara Rp5 juta pada harga tahun dasar.",
        hint: "Bagi upah nominal dengan (IHK / 100).",
      },
      {
        type: "calcExercise",
        prompt: "Upah nominal naik 9% setahun, inflasi 4%. Berapa kira-kira kenaikan upah riil (%)?",
        answer: 5,
        tolerance: 0.2,
        suffix: "%",
        solution: "Kenaikan upah riil kira-kira = kenaikan nominal - inflasi = 9% - 4% = <strong>5%</strong>.",
        hint: "Kurangkan inflasi dari kenaikan upah nominal.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Nilai nominal", right: "Angka rupiah apa adanya" },
          { left: "Nilai riil", right: "Nilai setelah disesuaikan tingkat harga" },
          { left: "Indeksasi", right: "Penyesuaian otomatis nilai mengikuti inflasi" },
          { left: "Daya beli", right: "Jumlah barang yang bisa dibeli sejumlah uang" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Hiperinflasi Jerman 1923",
        html: "Pada <strong>1923</strong>, Republik Weimar Jerman mengalami hiperinflasi ekstrem: harga berlipat ganda dalam hitungan hari dan pada November 1923 satu dolar AS setara sekitar <strong>4,2 triliun mark</strong>. Daya beli tabungan rakyat lenyap; orang membawa uang dengan gerobak dan upah dibayar dua kali sehari agar bisa segera dibelanjakan sebelum nilainya anjlok. Kasus ini adalah contoh paling ekstrem bagaimana inflasi menghancurkan nilai riil uang.",
      },
      {
        type: "takeaways",
        items: [
          "Inflasi menggerus daya beli; nilai riil = nominal / (IHK / 100).",
          "Upah riil mencerminkan daya beli, bukan angka di slip gaji.",
          "Kenaikan upah riil kira-kira = kenaikan nominal - inflasi.",
          "Indeksasi melindungi nilai dari gerusan inflasi.",
          "Bunga tabungan di bawah inflasi membuat nilai riil simpanan turun.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Daya beli uang saat inflasi naik akan?",
            options: ["Naik", "Turun", "Tetap", "Menjadi nol"],
            answer: 1,
            explain: "Inflasi membuat uang yang sama membeli lebih sedikit barang, sehingga daya beli turun.",
          },
          {
            q: "Rumus nilai riil?",
            options: ["nominal x IHK", "nominal / (IHK / 100)", "IHK / nominal", "nominal + inflasi"],
            answer: 1,
            explain: "Nilai riil = nilai nominal dibagi (IHK / 100).",
          },
          {
            q: "Upah nominal naik 7%, inflasi 5%. Upah riil naik sekitar?",
            options: ["12%", "2%", "7%", "5%"],
            answer: 1,
            explain: "Kira-kira 7% - 5% = 2%.",
          },
          {
            q: "Indeksasi bertujuan?",
            options: ["Menaikkan pajak", "Menyesuaikan nilai mengikuti inflasi", "Menambah ekspor", "Menghapus inflasi"],
            answer: 1,
            explain: "Indeksasi menyesuaikan nilai (upah, pensiun) otomatis agar daya beli terjaga.",
          },
          {
            q: "Upah Rp9 juta, IHK = 150. Upah riil (juta)?",
            options: ["Rp6 juta", "Rp13,5 juta", "Rp9 juta", "Rp4,5 juta"],
            answer: 0,
            explain: "9 / (150 / 100) = 9 / 1,5 = Rp6 juta.",
          },
        ],
      },
    ],
  },
];
