import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "utang-baik-vs-buruk",
    levelId: "utang",
    order: 1,
    title: "Utang Baik vs Utang Buruk",
    summary: "Membedakan utang yang membangun dari utang yang menjebak, dan cara aman menggunakan paylater serta pinjol.",
    durationMin: 13,
    tags: ["utang", "paylater", "pinjol", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua utang itu jahat. Ada <strong>utang baik</strong> yang membantumu memiliki aset produktif atau meningkatkan penghasilan, dan ada <strong>utang buruk</strong> yang hanya membiayai gaya hidup dan menjebakmu dalam bunga. Membedakan keduanya adalah kunci keuangan yang sehat.",
      },
      {
        type: "video",
        comp: "BolaSaljuUtangVideo",
        title: "Video: Metode Bola Salju Utang",
        caption: "Cara melunasi banyak utang secara bertahap agar cepat bebas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Baik vs buruk",
        html: "<strong>Utang baik:</strong> KPR rumah (aset naik nilai), modal usaha, biaya pendidikan yang meningkatkan penghasilan. <strong>Utang buruk:</strong> paylater untuk gaya hidup, kartu kredit yang tak dilunasi, pinjol untuk konsumsi. Cirinya: apakah utang itu membuatmu lebih kaya atau makin miskin?",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Waspada pinjol & paylater",
        html: "Paylater dan pinjaman online membuat belanja terasa ringan karena dicicil, tetapi bisa menumpuk cepat. Selalu pastikan pemberi pinjaman <strong>berizin OJK</strong>, dan jaga total cicilan di bawah <strong>30% penghasilan</strong>.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana beberapa cicilan paylater sekaligus bisa melahap sebagian besar penghasilanmu.",
      },
      { type: "widget", widget: "SimulatorPaylater" },
      {
        type: "chart",
        variant: "bar",
        title: "Batas Aman Rasio Cicilan Utang (panduan umum)",
        unit: "% dari penghasilan",
        source: "ilustrasi panduan rasio cicilan sehat",
        note: "Total cicilan utang sebaiknya tidak melebihi 30 sampai 35% penghasilan agar keuangan tetap sehat.",
        data: [
          { label: "Aman", value: 20, color: "#34d399" },
          { label: "Batas maksimal", value: 35, color: "#fbbf24" },
          { label: "Bahaya", value: 55, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Terjerat paylater",
        html: "Dina bergaji <strong>Rp5 juta</strong> dan tergoda mencicil 4 barang lewat paylater, masing-masing Rp400 ribu, total <strong>Rp1,6 juta</strong> per bulan. Itu setara <strong>32%</strong> penghasilannya, belum termasuk kebutuhan pokok. Akibatnya ia kesulitan dan menutup cicilan dengan pinjol baru. Utang untuk gaya hidup dengan mudah menjadi lubang yang makin dalam.",
      },
      {
        type: "calcExercise",
        prompt: "Total cicilan utang Rp1,6 juta per bulan, penghasilan Rp5 juta. Berapa rasio cicilan terhadap penghasilan dalam persen?",
        answer: 32,
        tolerance: 0,
        suffix: "%",
        solution: "Rasio = 1,6 / 5 x 100% = <strong>32%</strong>, sudah mendekati batas bahaya di atas 35%.",
        hint: "Bagi total cicilan dengan penghasilan, lalu kali 100%.",
      },
      {
        type: "classifyExercise",
        prompt: "Utang ini tergolong baik atau buruk?",
        buckets: ["Utang baik", "Utang buruk"],
        items: [
          { text: "KPR untuk rumah yang ditinggali", bucket: "Utang baik" },
          { text: "Modal untuk usaha yang menghasilkan", bucket: "Utang baik" },
          { text: "Paylater untuk gawai terbaru demi gengsi", bucket: "Utang buruk" },
          { text: "Pinjol untuk liburan mewah", bucket: "Utang buruk" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Maraknya Pinjol dan Peran OJK",
        html: "Beberapa tahun terakhir, pinjaman online tumbuh pesat di Indonesia, memudahkan akses kredit tetapi juga memunculkan banyak <strong>pinjol ilegal</strong> berbunga mencekik dan penagihan kasar. <strong>OJK</strong> bersama Satuan Tugas menutup ribuan entitas ilegal dan mengimbau masyarakat hanya memakai penyelenggara berizin. Pelajarannya: kemudahan berutang menuntut kewaspadaan yang lebih besar, bukan lebih kecil.",
      },
      {
        type: "takeaways",
        items: [
          "Utang baik membangun aset atau penghasilan; utang buruk membiayai gaya hidup.",
          "Jaga total cicilan di bawah 30 sampai 35% penghasilan.",
          "Paylater dan pinjol terasa ringan tetapi mudah menumpuk.",
          "Pastikan pemberi pinjaman berizin OJK.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah contoh utang baik?",
            options: ["Paylater untuk gengsi", "KPR rumah yang ditinggali", "Pinjol untuk liburan", "Kartu kredit tak dilunasi"],
            answer: 1,
            explain: "KPR membeli aset yang cenderung naik nilai dan dipakai, tergolong utang baik.",
          },
          {
            q: "Total cicilan utang sebaiknya di bawah?",
            options: ["10% penghasilan", "30 sampai 35% penghasilan", "80% penghasilan", "Tanpa batas"],
            answer: 1,
            explain: "Panduan umum menjaga rasio cicilan di bawah 30 sampai 35%.",
          },
          {
            q: "Sebelum memakai pinjol, hal terpenting dipastikan adalah?",
            options: ["Bunganya tinggi", "Berizin OJK", "Bisa cepat cair saja", "Ada di iklan"],
            answer: 1,
            explain: "Hanya gunakan penyelenggara yang berizin dan diawasi OJK.",
          },
          {
            q: "Cicilan Rp2 juta, penghasilan Rp5 juta. Rasionya?",
            options: ["40%", "20%", "10%", "50%"],
            answer: 0,
            explain: "2 / 5 = 40%, sudah melewati batas aman.",
          },
          {
            q: "Ciri utama utang buruk adalah?",
            options: [
              "Membeli aset produktif",
              "Membiayai konsumsi/gaya hidup dan menjebak bunga",
              "Menaikkan penghasilan",
              "Berbunga rendah",
            ],
            answer: 1,
            explain: "Utang buruk membiayai gaya hidup dan membuat makin miskin.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengelola-kartu-kredit",
    levelId: "utang",
    order: 2,
    title: "Mengelola Kartu Kredit",
    summary: "Cara kerja kartu kredit, masa tenggang tanpa bunga, dan mengapa membayar minimum adalah jebakan mahal.",
    durationMin: 14,
    tags: ["kartu kredit", "bunga", "utang", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Kartu kredit sebenarnya adalah <strong>pinjaman jangka pendek</strong> dari bank. Setiap kali kamu menggesek, bank menalangi pembayaranmu, lalu menagihmu di akhir bulan. Bila kamu melunasi <strong>penuh</strong> tepat waktu, kamu bahkan tidak membayar bunga sama sekali. Masalah muncul ketika kamu hanya membayar sebagian.",
      },
      {
        type: "paragraph",
        html: "Kunci memahami kartu kredit ada pada dua hal: <strong>masa tenggang</strong> (grace period) dan <strong>bunga</strong>. Selama kamu berteman dengan masa tenggang dan menjauhi bunga, kartu kredit adalah alat yang aman dan bahkan menguntungkan.",
      },
      {
        type: "video",
        comp: "BolaSaljuUtangVideo",
        title: "Video: Bola Salju Utang Kartu Kredit",
        caption: "Bagaimana bunga berbunga membuat tagihan menggelinding makin besar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Masa tenggang: senjata rahasiamu",
        html: "Bila kamu melunasi <strong>seluruh tagihan</strong> sebelum tanggal jatuh tempo, kamu menikmati barang lebih dulu dan membayar belakangan <strong>tanpa bunga</strong>. Ini disebut masa tenggang. Rahasianya sederhana: perlakukan kartu kredit seperti kartu debit, hanya belanjakan yang sanggup kamu lunasi penuh.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jebakan bayar minimum",
        html: "Tagihan sering menampilkan <strong>pembayaran minimum</strong> (misalnya 5% atau 10% dari total). Membayar minimum terasa ringan, tetapi sisa tagihan langsung dikenai bunga, dan bulan depan bunga itu ikut berbunga. Ini cara tercepat terjebak utang bertahun-tahun.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Masukkan tagihanmu dan lihat berapa lama utang lunas bila hanya membayar minimum, versus melunasi penuh.",
      },
      { type: "widget", widget: "KalkulatorKartuKredit" },
      {
        type: "chart",
        variant: "line",
        title: "Sisa Utang bila Hanya Bayar Minimum vs Lunas Penuh",
        unit: "juta rupiah",
        source: "ilustrasi tagihan Rp5 juta, bunga sekitar 1,75% per bulan",
        note: "Bayar minimum membuat utang nyaris tak berkurang karena sebagian besar setoran habis untuk bunga.",
        data: [
          { label: "Bln 0", value: 5.0, color: "#fb7185" },
          { label: "Bln 3", value: 4.8, color: "#fb7185" },
          { label: "Bln 6", value: 4.6, color: "#fb7185" },
          { label: "Bln 12", value: 4.2, color: "#fb7185" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Batas bunga diatur OJK",
        html: "Bunga kartu kredit di Indonesia dibatasi oleh regulasi. Sejak beberapa waktu terakhir batasnya berada di kisaran <strong>1,75% per bulan</strong> (sekitar 21% per tahun). Angka ini tetap besar, jadi lunasi penuh selagi bisa.",
      },
      {
        type: "case",
        title: "Studi Kasus: Bunga bulan pertama",
        html: "Rudi punya tagihan <strong>Rp5.000.000</strong> dan hanya membayar minimum. Sisa Rp5 juta dikenai bunga <strong>1,75% per bulan</strong>, yaitu <strong>Rp87.500</strong> hanya untuk bulan pertama. Bila kebiasaan ini berlanjut, ia bisa membayar bunga ratusan ribu tiap bulan tanpa tagihan pokok banyak berkurang.",
      },
      {
        type: "calcExercise",
        prompt: "Sisa tagihan kartu kredit Rp5.000.000 dikenai bunga 1,75% per bulan. Berapa rupiah bunga bulan pertama?",
        answer: 87500,
        tolerance: 100,
        prefix: "Rp",
        solution: "Bunga = Rp5.000.000 x 1,75% = Rp5.000.000 x 0,0175 = <strong>Rp87.500</strong>.",
        hint: "Kalikan sisa tagihan dengan 0,0175.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebiasaan kartu kredit ini sehat atau berbahaya?",
        buckets: ["Sehat", "Berbahaya"],
        items: [
          { text: "Melunasi seluruh tagihan sebelum jatuh tempo", bucket: "Sehat" },
          { text: "Belanja hanya sebesar yang sanggup dilunasi", bucket: "Sehat" },
          { text: "Rutin membayar minimum saja", bucket: "Berbahaya" },
          { text: "Menarik tunai lewat kartu kredit untuk kebutuhan harian", bucket: "Berbahaya" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Kartu Kredit Masuk Indonesia era 1980-an",
        html: "Kartu kredit mulai dikenal luas di Indonesia pada <strong>era 1980-an</strong>, ketika bank-bank menggandeng jaringan internasional. Awalnya kartu ini adalah simbol status kelas menengah atas di kota besar. Seiring waktu, penggunaannya meluas dan kini diawasi ketat, termasuk pembatasan bunga oleh regulator. Pelajarannya: alat pembayaran yang dulu eksklusif kini merakyat, sehingga literasi mengelolanya jadi makin penting.",
      },
      {
        type: "takeaways",
        items: [
          "Kartu kredit adalah pinjaman jangka pendek dari bank.",
          "Lunasi penuh sebelum jatuh tempo agar bebas bunga (masa tenggang).",
          "Bayar minimum adalah jebakan: sisa tagihan berbunga dan berbunga lagi.",
          "Bunga dibatasi OJK di kisaran 1,75% per bulan, tetap besar.",
          "Perlakukan kartu kredit seperti kartu debit.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Agar tidak dikenai bunga kartu kredit, kamu harus?",
            options: ["Membayar minimum", "Melunasi seluruh tagihan sebelum jatuh tempo", "Menunda pembayaran", "Menarik tunai"],
            answer: 1,
            explain: "Melunasi penuh dalam masa tenggang membuatmu bebas bunga.",
          },
          {
            q: "Apa itu masa tenggang (grace period)?",
            options: [
              "Denda keterlambatan",
              "Periode saat kamu bisa membayar penuh tanpa bunga",
              "Batas maksimal belanja",
              "Bunga tahunan",
            ],
            answer: 1,
            explain: "Masa tenggang adalah jendela waktu melunasi penuh tanpa bunga.",
          },
          {
            q: "Mengapa bayar minimum berbahaya?",
            options: [
              "Karena kartu diblokir",
              "Karena sisa tagihan dikenai bunga yang lalu berbunga lagi",
              "Karena tidak dapat poin",
              "Karena limit turun",
            ],
            answer: 1,
            explain: "Sisa tagihan terus berbunga sehingga utang sulit lunas.",
          },
          {
            q: "Sisa tagihan Rp4.000.000, bunga 1,75% per bulan. Bunga bulan pertama?",
            options: ["Rp70.000", "Rp40.000", "Rp175.000", "Rp700.000"],
            answer: 0,
            explain: "Rp4.000.000 x 0,0175 = Rp70.000.",
          },
          {
            q: "Batas bunga kartu kredit yang diatur OJK sekitar?",
            options: ["0,1% per bulan", "1,75% per bulan", "10% per bulan", "Tanpa batas"],
            answer: 1,
            explain: "Regulasi membatasi bunga di kisaran 1,75% per bulan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kpr-membeli-rumah",
    levelId: "utang",
    order: 3,
    title: "KPR: Membeli Rumah dengan Cicilan",
    summary: "Memahami DP, tenor, bunga fixed vs floating, metode anuitas, dan pilihan KPR syariah yang cicilannya tetap.",
    durationMin: 15,
    tags: ["kpr", "rumah", "properti", "syariah", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Rumah biasanya terlalu mahal untuk dibeli tunai, jadi kebanyakan orang memakai <strong>KPR</strong> (Kredit Pemilikan Rumah). Kamu membayar <strong>uang muka</strong> (DP) di depan, lalu mencicil sisanya ke bank selama bertahun-tahun. Inilah contoh utang baik: rumah adalah aset yang dipakai dan cenderung naik nilainya.",
      },
      {
        type: "paragraph",
        html: "Tiga angka menentukan cicilanmu: <strong>pokok</strong> (harga rumah dikurangi DP), <strong>tenor</strong> (lama cicilan), dan <strong>bunga</strong>. Makin panjang tenor, makin ringan cicilan bulanan, tetapi total bunga yang dibayar makin besar.",
      },
      {
        type: "video",
        comp: "PiramidaKeuanganVideo",
        title: "Video: Piramida Keuangan dan Posisi KPR",
        caption: "Di mana cicilan rumah berada dalam pondasi keuangan yang sehat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "DP dan Loan to Value (LTV)",
        html: "Bank tidak membiayai 100% harga rumah. <strong>LTV</strong> adalah rasio pinjaman terhadap nilai rumah. Bila LTV maksimal 90%, artinya kamu wajib menyiapkan DP minimal <strong>10%</strong>. Contoh rumah Rp500 juta dengan DP 10% berarti DP Rp50 juta dan pokok pinjaman Rp450 juta.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Fixed vs floating",
        html: "Bunga <strong>fixed</strong> tetap selama beberapa tahun pertama sehingga cicilanmu pasti. Setelah masa fixed habis, bunga menjadi <strong>floating</strong> (mengambang) mengikuti pasar, sehingga cicilan bisa naik. Banyak orang terkejut ketika masa fixed berakhir. Siapkan bantalan untuk kemungkinan kenaikan ini.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser harga rumah, DP, tenor, dan bunga untuk melihat perkiraan cicilan bulanan KPR-mu.",
      },
      { type: "widget", widget: "SimulatorKPR" },
      {
        type: "chart",
        variant: "bar",
        title: "Pengaruh Tenor terhadap Cicilan Bulanan (pokok Rp450 juta, bunga 8%/th)",
        unit: "juta rupiah per bulan",
        source: "ilustrasi perhitungan anuitas",
        note: "Tenor lebih panjang meringankan cicilan bulanan, tetapi total bunga sepanjang pinjaman jadi lebih besar.",
        data: [
          { label: "10 thn", value: 5.46, color: "#fb7185" },
          { label: "15 thn", value: 4.30, color: "#fbbf24" },
          { label: "20 thn", value: 3.76, color: "#34d399" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "KPR syariah: cicilan tetap",
        html: "Pada KPR syariah dengan akad <strong>murabahah</strong>, bank membeli rumah lalu menjualnya kepadamu dengan margin yang disepakati di awal, sehingga cicilan <strong>tetap</strong> sampai lunas, tanpa kejutan floating. Ada juga akad <strong>MMQ</strong> (Musyarakah Mutanaqisah), yaitu kepemilikan bersama yang porsimu bertambah seiring cicilan. Ini pilihan bagi yang menghindari bunga.",
      },
      {
        type: "case",
        title: "Studi Kasus: Hitung DP dan pokok",
        html: "Sari ingin membeli rumah seharga <strong>Rp500 juta</strong>. Bank menerapkan LTV 90%, sehingga DP minimal <strong>10%</strong> yaitu <strong>Rp50 juta</strong>. Pokok pinjaman menjadi Rp450 juta. Dengan tenor 20 tahun dan bunga sekitar 8% per tahun (anuitas), cicilannya sekitar <strong>Rp3,76 juta</strong> per bulan. Sari memastikan cicilan itu di bawah 30% penghasilannya sebelum mengajukan.",
      },
      {
        type: "calcExercise",
        prompt: "Harga rumah Rp500.000.000 dengan DP minimal 10%. Berapa rupiah uang muka yang harus disiapkan?",
        answer: 50000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "DP = 10% x Rp500.000.000 = 0,10 x Rp500.000.000 = <strong>Rp50.000.000</strong>.",
        hint: "Kalikan harga rumah dengan 0,10.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah KPR dengan artinya.",
        pairs: [
          { left: "DP", right: "Uang muka yang dibayar di depan" },
          { left: "Tenor", right: "Lama waktu cicilan" },
          { left: "Bunga floating", right: "Bunga mengambang mengikuti pasar" },
          { left: "Murabahah", right: "Akad syariah dengan margin tetap" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Bank Tabungan Negara (BTN) sejak 1974",
        html: "Pada tahun <strong>1974</strong>, pemerintah menugaskan <strong>Bank Tabungan Negara (BTN)</strong> sebagai bank penyalur <strong>KPR</strong>, dan KPR pertama disalurkan pada tahun 1976. Sejak itu BTN identik dengan pembiayaan rumah rakyat dan membantu jutaan keluarga Indonesia memiliki rumah pertama. Pelajarannya: KPR bertenor panjang membuat rumah yang tampak mustahil menjadi terjangkau lewat cicilan.",
      },
      {
        type: "takeaways",
        items: [
          "KPR: bayar DP di depan, cicil sisanya bertahun-tahun.",
          "LTV menentukan DP minimal; makin tinggi LTV, makin kecil DP.",
          "Tenor panjang meringankan cicilan tetapi menambah total bunga.",
          "Bunga fixed bisa berubah menjadi floating; siapkan bantalan.",
          "KPR syariah (murabahah/MMQ) menawarkan cicilan tetap tanpa bunga mengambang.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Rumah Rp600 juta, DP minimal 10%. Berapa DP-nya?",
            options: ["Rp6 juta", "Rp60 juta", "Rp100 juta", "Rp600 juta"],
            answer: 1,
            explain: "10% x Rp600 juta = Rp60 juta.",
          },
          {
            q: "Apa dampak memilih tenor lebih panjang?",
            options: [
              "Cicilan bulanan lebih ringan, total bunga lebih besar",
              "Cicilan lebih berat, bunga lebih kecil",
              "Tidak berpengaruh apa-apa",
              "Rumah jadi lebih murah",
            ],
            answer: 0,
            explain: "Tenor panjang meringankan cicilan bulanan tetapi menambah total bunga.",
          },
          {
            q: "Bunga floating artinya?",
            options: [
              "Bunga tetap selamanya",
              "Bunga mengambang mengikuti pasar sehingga cicilan bisa naik",
              "Bunga nol",
              "Bunga hanya untuk syariah",
            ],
            answer: 1,
            explain: "Floating berarti bunga mengikuti pasar, cicilan bisa berubah.",
          },
          {
            q: "Keunggulan KPR syariah murabahah adalah?",
            options: [
              "Cicilan tetap sampai lunas",
              "Bunga selalu turun",
              "Tanpa DP",
              "Tenor tak terbatas",
            ],
            answer: 0,
            explain: "Margin disepakati di awal sehingga cicilan tetap, tanpa floating.",
          },
          {
            q: "LTV (Loan to Value) adalah?",
            options: [
              "Rasio pinjaman terhadap nilai rumah",
              "Besarnya bunga tahunan",
              "Lama tenor",
              "Denda keterlambatan",
            ],
            answer: 0,
            explain: "LTV membandingkan besar pinjaman dengan nilai rumah dan menentukan DP.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "strategi-melunasi-utang",
    levelId: "utang",
    order: 4,
    title: "Strategi Melunasi Utang",
    summary: "Metode bola salju vs longsor, konsolidasi utang, dan bahaya gali lubang tutup lubang.",
    durationMin: 14,
    tags: ["utang", "bola salju", "longsor", "konsolidasi", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Kalau kamu punya beberapa utang sekaligus, jangan panik. Ada strategi terbukti untuk melunasinya satu per satu. Dua yang paling terkenal adalah <strong>metode bola salju</strong> dan <strong>metode longsor</strong>. Keduanya menyuruhmu membayar minimum semua utang, lalu mengarahkan uang lebih ke satu utang target.",
      },
      {
        type: "paragraph",
        html: "Bedanya hanya pada <strong>urutan target</strong>. Bola salju melunasi <strong>saldo terkecil dulu</strong> agar cepat merasakan kemenangan dan termotivasi. Longsor melunasi <strong>bunga tertinggi dulu</strong> agar total bunga yang dibayar paling kecil.",
      },
      {
        type: "video",
        comp: "BolaSaljuUtangVideo",
        title: "Video: Metode Bola Salju Utang",
        caption: "Melunasi utang satu per satu hingga momentum makin besar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Bola salju vs longsor",
        html: "<strong>Bola salju:</strong> urutkan dari saldo terkecil ke terbesar, lunasi yang kecil dulu. Menang secara psikologis. <strong>Longsor:</strong> urutkan dari bunga tertinggi ke terendah, lunasi bunga besar dulu. Menang secara matematis (paling hemat bunga). Pilih yang membuatmu konsisten.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Konsolidasi utang",
        html: "<strong>Konsolidasi</strong> berarti menggabungkan beberapa utang berbunga tinggi menjadi satu pinjaman berbunga lebih rendah. Cicilan jadi satu dan lebih ringan. Syaratnya: bunga baru benar-benar lebih rendah dan kamu berhenti menambah utang lama.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan gali lubang tutup lubang",
        html: "Menutup utang lama dengan utang baru berbunga sama atau lebih tinggi hanya memindahkan masalah sambil menambah bunga. Lubangnya makin dalam. Solusi sejati adalah menurunkan pengeluaran dan menambah setoran ke pokok, bukan menambah pinjaman.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana menumpuk cicilan paylater bisa melampaui batas aman penghasilanmu.",
      },
      { type: "widget", widget: "SimulatorPaylater" },
      {
        type: "chart",
        variant: "bar",
        title: "Total Bunga Dibayar: Bola Salju vs Longsor (ilustrasi 3 utang)",
        unit: "juta rupiah",
        source: "ilustrasi edukatif perbandingan strategi",
        note: "Longsor biasanya paling hemat bunga; bola salju sedikit lebih mahal tetapi lebih memotivasi.",
        data: [
          { label: "Longsor", value: 2.4, color: "#34d399" },
          { label: "Bola salju", value: 2.9, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih target pertama",
        html: "Budi punya tiga utang: paylater <strong>Rp1 juta</strong> (bunga 2%/bln), kartu kredit <strong>Rp3 juta</strong> (bunga 1,75%/bln), dan pinjaman teman <strong>Rp2 juta</strong> (tanpa bunga). Dengan <strong>bola salju</strong>, ia menyerang paylater Rp1 juta dulu karena terkecil. Dengan <strong>longsor</strong>, ia menyerang paylater dulu juga karena bunganya tertinggi (2%). Kebetulan keduanya sepakat: paylater lunas duluan.",
      },
      {
        type: "calcExercise",
        prompt: "Budi bisa menyisihkan Rp1,5 juta per bulan untuk utang. Cicilan minimum semua utang totalnya Rp900 ribu. Berapa rupiah dana ekstra untuk menyerang utang target?",
        answer: 600000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Dana ekstra = Rp1.500.000 - Rp900.000 = <strong>Rp600.000</strong> diarahkan ke utang target.",
        hint: "Kurangi total dana dengan total cicilan minimum.",
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini termasuk strategi sehat atau jebakan?",
        buckets: ["Strategi sehat", "Jebakan"],
        items: [
          { text: "Melunasi utang berbunga tertinggi dulu (longsor)", bucket: "Strategi sehat" },
          { text: "Menggabungkan utang ke pinjaman berbunga lebih rendah", bucket: "Strategi sehat" },
          { text: "Menutup pinjol lama dengan pinjol baru", bucket: "Jebakan" },
          { text: "Menambah paylater untuk membayar kartu kredit", bucket: "Jebakan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Fenomena Gali Lubang Tutup Lubang",
        html: "Istilah <strong>gali lubang tutup lubang</strong> sudah lama akrab di masyarakat Indonesia untuk menggambarkan orang yang membayar utang dengan berutang lagi. Fenomena ini melonjak seiring maraknya <strong>pinjol</strong> dalam beberapa tahun terakhir, ketika sebagian orang meminjam dari satu aplikasi untuk membayar aplikasi lain hingga terjerat banyak pinjaman sekaligus. Pelajarannya: menambah utang tidak pernah menyelesaikan utang, hanya menunda sambil memperbesarnya.",
      },
      {
        type: "takeaways",
        items: [
          "Bayar minimum semua utang, arahkan dana ekstra ke satu target.",
          "Bola salju (saldo terkecil dulu) menang secara psikologis.",
          "Longsor (bunga tertinggi dulu) menang secara matematis.",
          "Konsolidasi menggabungkan utang ke bunga lebih rendah.",
          "Gali lubang tutup lubang hanya memperdalam masalah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Metode bola salju melunasi utang berdasarkan?",
            options: ["Bunga tertinggi dulu", "Saldo terkecil dulu", "Saldo terbesar dulu", "Acak"],
            answer: 1,
            explain: "Bola salju menyerang saldo terkecil dulu untuk motivasi.",
          },
          {
            q: "Metode longsor paling unggul dalam hal?",
            options: [
              "Paling hemat total bunga",
              "Paling cepat memberi rasa menang",
              "Tidak butuh disiplin",
              "Menambah utang",
            ],
            answer: 0,
            explain: "Longsor melunasi bunga tertinggi dulu sehingga total bunga terkecil.",
          },
          {
            q: "Konsolidasi utang yang sehat mensyaratkan?",
            options: [
              "Bunga baru lebih rendah dan berhenti menambah utang",
              "Bunga baru lebih tinggi",
              "Menambah jumlah pinjaman",
              "Membayar hanya minimum",
            ],
            answer: 0,
            explain: "Konsolidasi bermanfaat bila bunga turun dan tidak menambah utang baru.",
          },
          {
            q: "Dana utang Rp2 juta, cicilan minimum total Rp1,2 juta. Dana ekstra untuk target?",
            options: ["Rp800 ribu", "Rp1,2 juta", "Rp2 juta", "Rp3,2 juta"],
            answer: 0,
            explain: "Rp2 juta - Rp1,2 juta = Rp800 ribu untuk utang target.",
          },
          {
            q: "Mengapa gali lubang tutup lubang berbahaya?",
            options: [
              "Membuat rumah naik nilai",
              "Memindahkan utang sambil menambah bunga, lubang makin dalam",
              "Menghapus utang",
              "Menurunkan bunga",
            ],
            answer: 1,
            explain: "Menambah utang untuk bayar utang hanya memperbesar total kewajiban.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "skor-kredit-slik-ojk",
    levelId: "utang",
    order: 5,
    title: "Skor Kredit & SLIK OJK",
    summary: "Bagaimana riwayat kreditmu dicatat di SLIK OJK, arti kolektibilitas 1 sampai 5, dan cara menjaga catatan tetap bersih.",
    durationMin: 14,
    tags: ["slik", "bi checking", "kolektibilitas", "skor kredit", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap kali kamu meminjam dari bank atau lembaga resmi, perilaku bayarmu <strong>dicatat</strong>. Rekam jejak ini disimpan dalam <strong>SLIK</strong> (Sistem Layanan Informasi Keuangan) yang dikelola <strong>OJK</strong>. Dulu sistem serupa dikenal sebagai <strong>BI Checking</strong>. Saat kamu mengajukan KPR atau pinjaman, bank mengintip catatan ini lebih dulu.",
      },
      {
        type: "paragraph",
        html: "Catatan yang bersih membuka pintu: pengajuan KPR lancar, bunga bisa lebih baik, limit lebih tinggi. Catatan yang buruk menutup pintu itu bertahun-tahun. Menjaga reputasi kredit sama pentingnya dengan menabung.",
      },
      {
        type: "video",
        comp: "SiklusHidupKeuanganVideo",
        title: "Video: Siklus Hidup Keuangan",
        caption: "Reputasi kredit yang dibangun hari ini menentukan pilihan di masa depan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kolektibilitas 1 sampai 5",
        html: "OJK menilai kualitas pinjaman lewat <strong>kolektibilitas</strong>: <strong>Kol 1 Lancar</strong> (bayar tepat waktu), <strong>Kol 2 Dalam Perhatian Khusus</strong> (menunggak 1 sampai 90 hari), <strong>Kol 3 Kurang Lancar</strong> (91 sampai 120 hari), <strong>Kol 4 Diragukan</strong> (121 sampai 180 hari), <strong>Kol 5 Macet</strong> (lebih dari 180 hari). Incarlah selalu Kol 1.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Skor buruk sulit dihapus",
        html: "Tunggakan yang membuatmu masuk Kol 2 ke atas akan terekam dan bisa menghambat pengajuan kredit baru. Bahkan setelah dilunasi, jejak historisnya masih terlihat beberapa waktu. Mencegah jauh lebih mudah daripada memperbaiki.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Cek rasio-rasio keuangan pribadimu, termasuk rasio cicilan utang, untuk memastikan kamu berada di zona sehat sebelum menambah pinjaman.",
      },
      { type: "widget", widget: "KalkulatorRasioPribadi" },
      {
        type: "chart",
        variant: "bar",
        title: "Kolektibilitas dan Lama Tunggakan",
        unit: "hari menunggak",
        source: "ilustrasi berdasarkan ketentuan kolektibilitas OJK",
        note: "Makin lama menunggak, makin tinggi angka kolektibilitas dan makin buruk catatan kreditmu.",
        data: [
          { label: "Kol 1", value: 0, color: "#34d399" },
          { label: "Kol 2", value: 90, color: "#a3e635" },
          { label: "Kol 3", value: 120, color: "#fbbf24" },
          { label: "Kol 4", value: 180, color: "#fb923c" },
          { label: "Kol 5", value: 210, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pengajuan KPR yang tertahan",
        html: "Andi ingin mengajukan KPR, tetapi dua tahun lalu ia sempat menunggak kartu kredit hingga <strong>100 hari</strong> sehingga tercatat <strong>Kol 3 (Kurang Lancar)</strong>. Meski kini sudah lunas, catatan itu membuat bank berhati-hati. Andi harus menunjukkan riwayat bayar lancar selama beberapa waktu dan melunasi sisa utang lain agar pengajuannya dipertimbangkan kembali.",
      },
      {
        type: "calcExercise",
        prompt: "Seseorang menunggak selama 100 hari. Menurut rentang kolektibilitas, ia masuk kolektibilitas nomor berapa?",
        answer: 3,
        tolerance: 0,
        solution: "Rentang 91 sampai 120 hari adalah <strong>Kol 3 (Kurang Lancar)</strong>. Jadi jawabannya 3.",
        hint: "Kol 2 = 1 sampai 90 hari; Kol 3 = 91 sampai 120 hari.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebiasaan ini menjaga skor kredit bersih atau merusaknya?",
        buckets: ["Menjaga bersih", "Merusak"],
        items: [
          { text: "Membayar cicilan tepat waktu setiap bulan", bucket: "Menjaga bersih" },
          { text: "Menyisihkan dana agar tidak pernah telat bayar", bucket: "Menjaga bersih" },
          { text: "Menunggak kartu kredit berbulan-bulan", bucket: "Merusak" },
          { text: "Mengabaikan tagihan pinjol resmi hingga macet", bucket: "Merusak" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Peralihan BI Checking ke SLIK OJK 2018",
        html: "Sistem informasi kredit dulu dikelola Bank Indonesia dan populer disebut <strong>BI Checking</strong>. Sejak <strong>1 Januari 2018</strong>, fungsi ini beralih ke <strong>OJK</strong> melalui <strong>SLIK</strong> (Sistem Layanan Informasi Keuangan), yang cakupannya lebih luas karena mencakup lebih banyak lembaga keuangan, termasuk multifinance. Pelajarannya: rekam jejak kredit kini terpantau lebih menyeluruh, jadi jagalah setiap cicilan.",
      },
      {
        type: "takeaways",
        items: [
          "Riwayat kreditmu dicatat di SLIK OJK, dulu dikenal BI Checking.",
          "Kolektibilitas menilai kualitas pinjaman dari Kol 1 (Lancar) sampai Kol 5 (Macet).",
          "Selalu bayar tepat waktu agar tetap di Kol 1.",
          "Catatan buruk sulit dihapus dan menghambat pengajuan KPR.",
          "SLIK menggantikan BI Checking sejak 2018 dengan cakupan lebih luas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Riwayat kredit di Indonesia kini dicatat dalam sistem?",
            options: ["SLIK OJK", "Kartu keluarga", "NPWP", "BPJS"],
            answer: 0,
            explain: "SLIK (Sistem Layanan Informasi Keuangan) dikelola OJK.",
          },
          {
            q: "Kolektibilitas 1 berarti?",
            options: ["Macet", "Lancar, bayar tepat waktu", "Diragukan", "Kurang lancar"],
            answer: 1,
            explain: "Kol 1 adalah Lancar, kondisi yang harus dijaga.",
          },
          {
            q: "Menunggak lebih dari 180 hari masuk kolektibilitas?",
            options: ["Kol 1", "Kol 2", "Kol 5 (Macet)", "Kol 3"],
            answer: 2,
            explain: "Tunggakan lebih dari 180 hari tergolong Kol 5 Macet.",
          },
          {
            q: "BI Checking beralih menjadi SLIK OJK sejak tahun?",
            options: ["2010", "2018", "2023", "1998"],
            answer: 1,
            explain: "Peralihan ke SLIK OJK berlaku sejak 1 Januari 2018.",
          },
          {
            q: "Mengapa menjaga skor kredit penting?",
            options: [
              "Agar pengajuan KPR dan kredit lain lebih mudah disetujui",
              "Agar pajak lebih murah",
              "Agar gaji naik otomatis",
              "Tidak ada gunanya",
            ],
            answer: 0,
            explain: "Catatan bersih memperlancar persetujuan kredit di masa depan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "asuransi-jiwa",
    levelId: "utang",
    order: 6,
    title: "Asuransi Jiwa: Melindungi Keluarga",
    summary: "Mengapa pencari nafkah butuh asuransi jiwa, cara menaksir uang pertanggungan, serta beda term life, unit link, dan takaful.",
    durationMin: 15,
    tags: ["asuransi jiwa", "term life", "unit link", "takaful", "proteksi", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Asuransi jiwa bukan untuk dirimu, melainkan untuk <strong>orang-orang yang bergantung padamu</strong>. Bila kamu pencari nafkah utama dan tiba-tiba tiada, keluarga bisa kehilangan sumber penghasilan. Asuransi jiwa membayarkan sejumlah <strong>uang pertanggungan</strong> agar keluarga tetap bisa hidup, membayar cicilan, dan anak tetap sekolah.",
      },
      {
        type: "paragraph",
        html: "Kalau kamu masih lajang tanpa tanggungan, kebutuhan asuransi jiwa kecil. Begitu ada pasangan, anak, atau orang tua yang kamu tanggung, asuransi jiwa menjadi penting. Prinsipnya sederhana: lindungi penghasilan yang menjadi sandaran orang lain.",
      },
      {
        type: "video",
        comp: "ProteksiBPJSVideo",
        title: "Video: Lapisan Proteksi Keuangan",
        caption: "Bagaimana asuransi melindungi keluarga dari guncangan tak terduga.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Siapa yang butuh?",
        html: "Yang paling butuh asuransi jiwa adalah <strong>pencari nafkah dengan tanggungan</strong>. Anak kecil dan orang yang tidak dinafkahi orang lain umumnya tidak perlu. Fokuskan proteksi pada tulang punggung keluarga, bukan pada setiap anggota.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Term life murah, unit link mahal",
        html: "<strong>Asuransi jiwa berjangka (term life)</strong> murni proteksi: premi murah, uang pertanggungan besar, berlaku selama jangka tertentu. <strong>Unit link</strong> menggabungkan proteksi dan investasi, preminya jauh lebih mahal dan hasil investasinya sering mengecewakan. Untuk kebanyakan orang, term life lebih efisien: beli proteksi murah, investasikan sisanya sendiri.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Opsi syariah: takaful",
        html: "<strong>Takaful</strong> adalah asuransi berbasis syariah dengan prinsip tolong-menolong (ta'awun), di mana peserta saling menanggung lewat dana tabarru'. Cocok bagi yang ingin proteksi tanpa unsur riba dan gharar berlebih.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Hitung perkiraan uang pertanggungan yang keluargamu butuhkan berdasarkan pengeluaran dan tanggunganmu.",
      },
      { type: "widget", widget: "KalkulatorUangPertanggungan" },
      {
        type: "chart",
        variant: "bar",
        title: "Premi Tahunan: Term Life vs Unit Link (uang pertanggungan setara)",
        unit: "juta rupiah per tahun",
        source: "ilustrasi edukatif perbandingan premi",
        note: "Untuk uang pertanggungan sama, premi term life jauh lebih murah karena murni proteksi.",
        data: [
          { label: "Term life", value: 2.5, color: "#34d399" },
          { label: "Unit link", value: 12.0, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menaksir uang pertanggungan",
        html: "Pak Joko menanggung istri dan dua anak. Pengeluaran keluarga sekitar <strong>Rp8 juta</strong> per bulan atau <strong>Rp96 juta</strong> per tahun. Ia ingin keluarganya tetap tercukupi selama <strong>10 tahun</strong> sampai anak-anak mandiri. Dengan pendekatan sederhana, uang pertanggungan yang dibutuhkan sekitar Rp96 juta x 10 = <strong>Rp960 juta</strong>. Term life membuat pertanggungan sebesar ini terjangkau preminya.",
      },
      {
        type: "calcExercise",
        prompt: "Pengeluaran keluarga Rp96.000.000 per tahun, ingin tercukupi selama 10 tahun. Berapa perkiraan uang pertanggungan (pendekatan sederhana)?",
        answer: 960000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Uang pertanggungan = Rp96.000.000 x 10 = <strong>Rp960.000.000</strong>.",
        hint: "Kalikan pengeluaran tahunan dengan jumlah tahun perlindungan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis produk dengan cirinya.",
        pairs: [
          { left: "Term life", right: "Proteksi murni, premi murah, jangka tertentu" },
          { left: "Unit link", right: "Gabungan proteksi dan investasi, premi mahal" },
          { left: "Takaful", right: "Asuransi syariah berbasis tolong-menolong" },
          { left: "Uang pertanggungan", right: "Dana yang cair untuk keluarga" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Asuransi Jiwa di Indonesia sejak 1912",
        html: "Perusahaan asuransi jiwa pribumi pertama, <strong>Bumiputera</strong>, didirikan di Magelang pada tahun <strong>1912</strong> dengan bentuk usaha bersama (mutual). Kehadirannya menandai kesadaran akan pentingnya melindungi keluarga dari risiko kehilangan pencari nafkah, jauh sebelum industri asuransi modern berkembang. Pelajarannya: gagasan saling menanggung risiko sudah lama mengakar di Indonesia.",
      },
      {
        type: "takeaways",
        items: [
          "Asuransi jiwa melindungi keluarga yang bergantung pada penghasilanmu.",
          "Paling dibutuhkan oleh pencari nafkah dengan tanggungan.",
          "Term life murni proteksi dan murah; unit link mahal karena bercampur investasi.",
          "Takaful adalah opsi syariah berbasis tolong-menolong.",
          "Taksir uang pertanggungan dari pengeluaran keluarga dikali tahun perlindungan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Asuransi jiwa paling dibutuhkan oleh?",
            options: ["Anak balita", "Pencari nafkah dengan tanggungan", "Lajang tanpa tanggungan", "Semua orang sama"],
            answer: 1,
            explain: "Tulang punggung keluarga yang menafkahi orang lain paling butuh proteksi ini.",
          },
          {
            q: "Keunggulan term life dibanding unit link?",
            options: [
              "Premi lebih murah untuk uang pertanggungan besar",
              "Selalu memberi untung investasi",
              "Tidak pernah berakhir",
              "Preminya paling mahal",
            ],
            answer: 0,
            explain: "Term life murni proteksi sehingga premi jauh lebih murah.",
          },
          {
            q: "Takaful adalah?",
            options: [
              "Asuransi syariah berbasis tolong-menolong",
              "Deposito bank",
              "Kartu kredit",
              "Pinjaman online",
            ],
            answer: 0,
            explain: "Takaful adalah asuransi syariah dengan prinsip saling menanggung.",
          },
          {
            q: "Pengeluaran Rp5 juta/bln, ingin tercukupi 10 tahun. Perkiraan uang pertanggungan?",
            options: ["Rp60 juta", "Rp600 juta", "Rp50 juta", "Rp6 miliar"],
            answer: 1,
            explain: "Rp5 juta x 12 x 10 = Rp600 juta.",
          },
          {
            q: "Uang pertanggungan dalam asuransi jiwa digunakan untuk?",
            options: [
              "Membeli mobil asuransi",
              "Menopang kebutuhan keluarga bila pencari nafkah tiada",
              "Membayar pajak perusahaan",
              "Menambah gaji saat sehat",
            ],
            answer: 1,
            explain: "Dana ini menjaga keluarga tetap tercukupi setelah kehilangan penghasilan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "bpjs-dan-asuransi-kesehatan",
    levelId: "utang",
    order: 7,
    title: "BPJS Kesehatan & Asuransi Kesehatan",
    summary: "BPJS Kesehatan sebagai proteksi dasar wajib, sistem rujukan berjenjang, kelas iuran, serta pelengkap asuransi swasta dan umum.",
    durationMin: 15,
    tags: ["bpjs", "jkn", "asuransi kesehatan", "rujukan", "proteksi", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Satu kali rawat inap bisa menghabiskan tabungan bertahun-tahun. Itulah mengapa <strong>proteksi kesehatan</strong> adalah pondasi keuangan. Di Indonesia, lapisan pertama adalah <strong>BPJS Kesehatan</strong>, penyelenggara program <strong>JKN</strong> (Jaminan Kesehatan Nasional) yang bersifat wajib bagi seluruh penduduk.",
      },
      {
        type: "paragraph",
        html: "BPJS Kesehatan memberi proteksi <strong>dasar</strong> dengan iuran terjangkau. Untuk kenyamanan lebih (kamar lebih baik, akses lebih cepat), banyak orang menambah <strong>asuransi kesehatan swasta</strong>. Keduanya bisa saling melengkapi, bukan saling menggantikan.",
      },
      {
        type: "video",
        comp: "ProteksiBPJSVideo",
        title: "Video: Proteksi BPJS Kesehatan",
        caption: "Bagaimana iuran gotong royong menanggung biaya sakit bersama.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rujukan berjenjang",
        html: "BPJS memakai <strong>sistem rujukan berjenjang</strong>. Kecuali gawat darurat, kamu berobat dulu ke <strong>Fasilitas Kesehatan Tingkat Pertama</strong> (FKTP, misalnya puskesmas atau klinik). Bila perlu, FKTP merujukmu ke rumah sakit. Datang langsung ke rumah sakit tanpa rujukan bisa membuat klaim tidak ditanggung.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kelas iuran",
        html: "Peserta mandiri memilih kelas iuran yang membedakan hak kelas kamar rawat inap. Bayarlah iuran <strong>rutin tiap bulan</strong> agar kepesertaan tetap aktif, karena tunggakan membuat kartu nonaktif saat kamu justru membutuhkannya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Lengkapi dengan asuransi swasta & umum",
        html: "Setelah BPJS, pertimbangkan <strong>asuransi kesehatan swasta</strong> untuk melengkapi. Jangan lupa <strong>asuransi umum</strong> untuk aset besar: <strong>kendaraan</strong> (mis. all risk atau TLO) dan <strong>properti</strong> (kebakaran, gempa). Aset yang dibeli dengan susah payah layak dilindungi.",
      },
      { type: "widget", widget: "KalkulatorUangPertanggungan" },
      {
        type: "chart",
        variant: "donut",
        title: "Lapisan Proteksi Kesehatan Ideal",
        unit: "porsi peran",
        source: "ilustrasi edukatif susunan proteksi",
        note: "BPJS menjadi fondasi wajib, lalu asuransi swasta dan dana darurat melengkapinya.",
        data: [
          { label: "BPJS Kesehatan (dasar)", value: 50, color: "#34d399" },
          { label: "Asuransi swasta (pelengkap)", value: 30, color: "#60a5fa" },
          { label: "Dana darurat kesehatan", value: 20, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Selisih biaya rawat inap",
        html: "Bu Rina dirawat 5 hari. Total biaya rumah sakit <strong>Rp15.000.000</strong>. Karena mengikuti rujukan berjenjang dengan benar, <strong>BPJS menanggung Rp13.000.000</strong> sesuai haknya. Sisa <strong>Rp2.000.000</strong> berupa selisih kelas kamar ditanggung asuransi kesehatan swastanya. Berkat dua lapisan proteksi, tabungan keluarganya tidak terganggu sama sekali.",
      },
      {
        type: "calcExercise",
        prompt: "Total biaya rawat inap Rp15.000.000. BPJS menanggung Rp13.000.000. Berapa rupiah selisih yang perlu ditanggung sendiri atau asuransi swasta?",
        answer: 2000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Selisih = Rp15.000.000 - Rp13.000.000 = <strong>Rp2.000.000</strong>.",
        hint: "Kurangi total biaya dengan yang ditanggung BPJS.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan proteksi ini sesuai jenisnya.",
        buckets: ["Proteksi kesehatan", "Asuransi umum (aset)"],
        items: [
          { text: "BPJS Kesehatan / JKN", bucket: "Proteksi kesehatan" },
          { text: "Asuransi kesehatan swasta", bucket: "Proteksi kesehatan" },
          { text: "Asuransi kendaraan all risk", bucket: "Asuransi umum (aset)" },
          { text: "Asuransi kebakaran rumah", bucket: "Asuransi umum (aset)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Peluncuran BPJS Kesehatan dan JKN 2014",
        html: "Program <strong>Jaminan Kesehatan Nasional (JKN)</strong> resmi diselenggarakan oleh <strong>BPJS Kesehatan</strong> mulai <strong>1 Januari 2014</strong>, hasil transformasi dari PT Askes. Program ini menyatukan berbagai skema jaminan kesehatan menjadi satu sistem gotong royong nasional yang wajib. Pelajarannya: prinsip banyak orang sehat menanggung yang sakit membuat biaya kesehatan menjadi terjangkau bagi semua.",
      },
      {
        type: "takeaways",
        items: [
          "BPJS Kesehatan (JKN) adalah proteksi kesehatan dasar yang wajib.",
          "Ikuti sistem rujukan berjenjang: mulai dari FKTP, kecuali gawat darurat.",
          "Bayar iuran rutin agar kepesertaan tetap aktif.",
          "Lengkapi dengan asuransi kesehatan swasta untuk kenyamanan lebih.",
          "Lindungi aset besar dengan asuransi umum (kendaraan, properti).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "BPJS Kesehatan menyelenggarakan program?",
            options: ["JKN (Jaminan Kesehatan Nasional)", "KPR", "SLIK", "Paylater"],
            answer: 0,
            explain: "BPJS Kesehatan adalah penyelenggara program JKN.",
          },
          {
            q: "Dalam sistem rujukan berjenjang, kamu berobat dulu ke?",
            options: [
              "Langsung rumah sakit besar",
              "FKTP seperti puskesmas atau klinik (kecuali gawat darurat)",
              "Apotek",
              "Kantor BPJS",
            ],
            answer: 1,
            explain: "Kecuali darurat, mulai dari FKTP lalu dirujuk bila perlu.",
          },
          {
            q: "Agar kepesertaan BPJS tetap aktif, kamu harus?",
            options: ["Membayar iuran rutin tiap bulan", "Jarang sakit", "Punya asuransi swasta", "Tinggal di kota"],
            answer: 0,
            explain: "Tunggakan iuran membuat kartu nonaktif saat dibutuhkan.",
          },
          {
            q: "Total biaya Rp10 juta, BPJS menanggung Rp9 juta. Selisihnya?",
            options: ["Rp1 juta", "Rp9 juta", "Rp19 juta", "Rp0"],
            answer: 0,
            explain: "Rp10 juta - Rp9 juta = Rp1 juta selisih.",
          },
          {
            q: "JKN oleh BPJS Kesehatan resmi berjalan sejak tahun?",
            options: ["2004", "2014", "2020", "1998"],
            answer: 1,
            explain: "JKN mulai diselenggarakan BPJS Kesehatan pada 1 Januari 2014.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "asuransi-umum-mitigasi-risiko",
    levelId: "utang",
    order: 8,
    title: "Asuransi Umum & Mitigasi Risiko",
    summary: "Mengalihkan risiko kerugian besar ke perusahaan asuransi: kendaraan (TLO vs all risk), properti/kebakaran, dan perjalanan, serta prinsip hanya mengasuransikan yang tak sanggup ditanggung sendiri.",
    durationMin: 14,
    tags: ["asuransi umum", "all risk", "tlo", "properti", "syariah", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Beberapa musibah terlalu mahal untuk ditanggung sendiri: mobil hancur, rumah terbakar, atau tas hilang di luar negeri. <strong>Asuransi umum</strong> memungkinkanmu <strong>mengalihkan risiko</strong> kerugian besar itu ke perusahaan asuransi. Kamu membayar premi kecil rutin, dan bila musibah datang, perusahaan menanggung sebagian besar biayanya.",
      },
      {
        type: "paragraph",
        html: "Berbeda dengan asuransi jiwa yang melindungi penghasilan, asuransi umum melindungi <strong>harta dan aktivitas</strong>: kendaraan, properti, sampai perjalanan. Inti mitigasi risiko sederhana, tanggung sendiri kerugian kecil, alihkan ke asuransi kerugian besar yang bisa menghancurkan keuanganmu.",
      },
      {
        type: "video",
        comp: "ProteksiBPJSVideo",
        title: "Video: Lapisan Proteksi Keuangan",
        caption: "Bagaimana asuransi menanggung kerugian besar agar tabunganmu tetap aman.",
      },
      {
        type: "callout",
        tone: "key",
        title: "TLO vs all risk",
        html: "Untuk kendaraan ada dua jenis utama. <strong>TLO (Total Loss Only)</strong> hanya menanggung bila kendaraan hilang dicuri atau rusak berat (kerugian di atas sekitar 75% nilainya), preminya murah. <strong>All risk</strong> (comprehensive) menanggung juga kerusakan kecil seperti lecet dan penyok, tetapi preminya jauh lebih mahal. Mobil baru bernilai tinggi cocok all risk; mobil tua yang murah sering cukup TLO.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan asuransikan yang sanggup kamu tanggung",
        html: "Asuransi ada biayanya. Mengasuransikan barang murah yang sanggup kamu ganti sendiri (misalnya ponsel lama) justru boros. <strong>Prinsipnya:</strong> asuransikan hanya risiko yang <strong>tidak sanggup kamu tanggung sendiri</strong>, seperti rumah terbakar atau mobil hancur, bukan kerugian kecil yang tertutup dana darurat.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Opsi syariah: asuransi umum syariah",
        html: "Tersedia juga <strong>asuransi umum syariah</strong> dengan prinsip tolong-menolong (ta'awun) lewat dana tabarru', tanpa unsur riba dan gharar berlebih. Produknya mencakup asuransi kendaraan, kebakaran, dan perjalanan berbasis akad syariah, cocok bagi yang ingin proteksi sesuai prinsip syariah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Taksir seberapa besar dana yang perlu kamu siapkan bila menanggung sendiri kerugian besar tanpa asuransi, lalu bandingkan dengan premi tahunan yang jauh lebih ringan.",
      },
      { type: "widget", widget: "KalkulatorUangPertanggungan" },
      {
        type: "chart",
        variant: "bar",
        title: "Perkiraan Premi Tahunan Asuransi Mobil (nilai mobil Rp200 juta)",
        unit: "juta rupiah per tahun",
        source: "ilustrasi mengikuti kisaran tarif premi kendaraan yang diatur OJK",
        note: "All risk berpremi jauh lebih besar karena menanggung kerusakan kecil sekalipun, sedangkan TLO hanya untuk kehilangan atau kerusakan berat.",
        data: [
          { label: "TLO", value: 1.0, color: "#34d399" },
          { label: "All risk", value: 6.0, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih all risk atau TLO",
        html: "Rendi membeli mobil baru seharga <strong>Rp200 juta</strong>. Karena mobil masih baru dan sering dipakai di kota yang ramai, ia memilih <strong>all risk</strong> dengan premi sekitar <strong>3%</strong> nilai mobil, yaitu <strong>Rp6 juta</strong> per tahun, agar lecet dan penyok pun tertanggung. Adiknya yang punya mobil tua senilai Rp60 juta memilih <strong>TLO</strong> saja, karena hanya ingin berjaga dari risiko mobil hilang atau hancur total.",
      },
      {
        type: "calcExercise",
        prompt: "Premi asuransi mobil all risk sekitar 3% dari nilai mobil. Untuk mobil senilai Rp200.000.000, berapa rupiah premi setahun?",
        answer: 6000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Premi = 3% x Rp200.000.000 = 0,03 x Rp200.000.000 = <strong>Rp6.000.000</strong> per tahun.",
        hint: "Kalikan nilai mobil dengan 0,03.",
      },
      {
        type: "classifyExercise",
        prompt: "Risiko ini sebaiknya diasuransikan atau ditanggung sendiri?",
        buckets: ["Diasuransikan", "Ditanggung sendiri"],
        items: [
          { text: "Rumah terbakar habis", bucket: "Diasuransikan" },
          { text: "Mobil baru hancur ditabrak", bucket: "Diasuransikan" },
          { text: "Payung hilang di angkot", bucket: "Ditanggung sendiri" },
          { text: "Ganti gelas pecah di rumah", bucket: "Ditanggung sendiri" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya Asuransi Kebakaran setelah Kebakaran Besar London 1666",
        html: "Pada tahun <strong>1666</strong>, <strong>Kebakaran Besar London</strong> menghanguskan puluhan ribu rumah dan menyadarkan orang akan perlunya proteksi. Tak lama kemudian, <strong>Nicholas Barbon</strong> mendirikan perusahaan asuransi kebakaran pertama (dikenal sebagai The Fire Office) sekitar tahun <strong>1681</strong>. Sementara itu, asuransi laut modern tumbuh dari kedai kopi <strong>Edward Lloyd</strong> di London sekitar tahun <strong>1688</strong>, yang kelak menjadi Lloyd's of London. Pelajarannya: asuransi umum lahir dari kebutuhan nyata menanggung bersama kerugian besar yang tak sanggup dipikul sendiri.",
      },
      {
        type: "takeaways",
        items: [
          "Asuransi umum mengalihkan risiko kerugian besar atas harta ke perusahaan asuransi.",
          "TLO menanggung kehilangan atau kerusakan berat dengan premi murah; all risk menanggung kerusakan kecil dengan premi mahal.",
          "Asuransikan hanya yang tak sanggup kamu tanggung sendiri.",
          "Lindungi properti (kebakaran) dan perjalanan sesuai kebutuhan.",
          "Tersedia asuransi umum syariah berbasis tolong-menolong.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Asuransi kendaraan jenis TLO menanggung?",
            options: [
              "Semua lecet dan penyok kecil",
              "Hanya kehilangan atau kerusakan berat (total loss)",
              "Biaya bensin",
              "Cicilan kredit mobil",
            ],
            answer: 1,
            explain: "TLO (Total Loss Only) hanya untuk kendaraan hilang atau rusak berat.",
          },
          {
            q: "Prinsip utama memilih apa yang diasuransikan?",
            options: [
              "Asuransikan semua barang sekecil apa pun",
              "Asuransikan hanya risiko yang tak sanggup ditanggung sendiri",
              "Asuransikan hanya barang murah",
              "Jangan pernah berasuransi",
            ],
            answer: 1,
            explain: "Alihkan ke asuransi kerugian besar yang bisa menghancurkan keuanganmu.",
          },
          {
            q: "Mobil senilai Rp100 juta, premi all risk 3%. Preminya setahun?",
            options: ["Rp300 ribu", "Rp3 juta", "Rp30 juta", "Rp3 miliar"],
            answer: 1,
            explain: "3% x Rp100 juta = Rp3 juta per tahun.",
          },
          {
            q: "Manakah yang lebih tepat ditanggung sendiri, bukan diasuransikan?",
            options: [
              "Rumah terbakar habis",
              "Mobil baru hancur total",
              "Gelas pecah di rumah",
              "Kapal kargo tenggelam",
            ],
            answer: 2,
            explain: "Kerugian kecil yang sanggup diganti sendiri tidak perlu diasuransikan.",
          },
          {
            q: "Asuransi kebakaran modern pertama muncul terkait peristiwa?",
            options: [
              "Kebakaran Besar London 1666",
              "Krisis moneter 1998",
              "Peluncuran BPJS 2014",
              "Depresi Besar 1929",
            ],
            answer: 0,
            explain: "Kebakaran Besar London 1666 mendorong lahirnya perusahaan asuransi kebakaran pertama.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "keluar-dari-jerat-utang",
    levelId: "utang",
    order: 9,
    title: "Keluar dari Jerat Utang",
    summary: "Langkah nyata keluar dari utang berat: berhenti menambah utang, mendata semua utang, restrukturisasi ke pemberi pinjaman resmi, dan menerapkan metode bola salju atau longsor tanpa gali lubang tutup lubang.",
    durationMin: 15,
    tags: ["utang", "restrukturisasi", "galbay", "pinjol", "bola salju", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Terjerat utang berat terasa seperti tenggelam, tetapi selalu ada jalan keluar yang tertata. Kuncinya bukan panik atau kabur, melainkan menghadapi angka-angkanya dengan tenang lalu melunasinya satu per satu. Ribuan orang sudah keluar dari jerat utang dengan langkah yang sama.",
      },
      {
        type: "paragraph",
        html: "Langkah pertama justru yang paling menentukan: <strong>berhenti menambah utang baru</strong>. Selama kamu masih menggali utang untuk menambal utang lama, dasar kolamnya terus menjauh. Setelah keran ditutup, barulah strategi pelunasan bisa bekerja.",
      },
      {
        type: "video",
        comp: "BolaSaljuUtangVideo",
        title: "Video: Metode Bola Salju Utang",
        caption: "Melunasi utang satu per satu hingga momentum makin besar dan kamu bebas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lima langkah keluar dari jerat utang",
        html: "<strong>1)</strong> Berhenti menambah utang baru. <strong>2)</strong> Data semua utang (saldo, bunga, jatuh tempo). <strong>3)</strong> Negosiasi atau <strong>restrukturisasi</strong> ke pemberi pinjaman resmi. <strong>4)</strong> Terapkan metode <strong>bola salju</strong> (saldo terkecil dulu) atau <strong>longsor</strong> (bunga tertinggi dulu). <strong>5)</strong> Pangkas pengeluaran dan tambah setoran ke pokok.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Restrukturisasi lewat jalur resmi",
        html: "Bila cicilan tak lagi terjangkau, hubungi pemberi pinjaman <strong>resmi</strong> (bank, multifinance, atau pinjol berizin OJK) untuk minta <strong>restrukturisasi</strong>: perpanjangan tenor, penurunan bunga, atau keringanan. Jalur resmi punya mekanisme ini. Menghindar justru membuat statusmu memburuk di SLIK OJK.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan gali lubang tutup lubang",
        html: "Membayar pinjol lama dengan pinjol baru hanya memindahkan masalah sambil menambah bunga. Lubangnya makin dalam dan kamu bisa terjerat banyak aplikasi sekaligus. Solusi sejati adalah memangkas pengeluaran dan menyerang pokok utang, <strong>bukan</strong> menambah pinjaman.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana menumpuk cicilan paylater bisa melampaui batas aman penghasilan, agar kamu paham betapa pentingnya menutup keran utang lebih dulu.",
      },
      { type: "widget", widget: "SimulatorPaylater" },
      {
        type: "chart",
        variant: "line",
        title: "Sisa Utang setelah Berhenti Menambah dan Menyerang Pokok",
        unit: "juta rupiah",
        source: "ilustrasi total utang Rp10 juta dengan setoran ekstra rutin",
        note: "Begitu keran utang baru ditutup dan setoran diarahkan ke pokok, sisa utang menurun konsisten sampai lunas.",
        data: [
          { label: "Bln 0", value: 10.0, color: "#fb7185" },
          { label: "Bln 3", value: 7.6, color: "#fbbf24" },
          { label: "Bln 6", value: 5.0, color: "#a3e635" },
          { label: "Bln 9", value: 2.4, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menata ulang utang Sinta",
        html: "Sinta punya total utang <strong>Rp10 juta</strong> tersebar di beberapa paylater dan pinjol berizin. Ia berhenti berbelanja cicilan, mendata semua utangnya, lalu meminta <strong>restrukturisasi</strong> untuk memperpanjang tenor agar cicilan bulanan turun. Setiap bulan ia menyisihkan <strong>Rp2 juta</strong> untuk menyerang utang bunga tertinggi lebih dulu (longsor). Dalam waktu sekitar 5 bulan utangnya tinggal separuh, dan momentumnya terus membesar.",
      },
      {
        type: "calcExercise",
        prompt: "Total utang Sinta Rp10.000.000. Ia mampu menyetor Rp2.000.000 per bulan untuk pokok. Bila diabaikan bunganya, berapa bulan utang lunas?",
        answer: 5,
        tolerance: 0,
        suffix: " bulan",
        solution: "Lama = Rp10.000.000 / Rp2.000.000 = <strong>5 bulan</strong> (perkiraan sederhana tanpa memperhitungkan bunga).",
        hint: "Bagi total utang dengan setoran bulanan.",
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini membantu keluar dari utang atau memperdalam jerat?",
        buckets: ["Membantu keluar", "Memperdalam jerat"],
        items: [
          { text: "Berhenti membuka cicilan baru", bucket: "Membantu keluar" },
          { text: "Meminta restrukturisasi ke pinjol berizin OJK", bucket: "Membantu keluar" },
          { text: "Menutup pinjol lama dengan pinjol baru", bucket: "Memperdalam jerat" },
          { text: "Mengabaikan tagihan resmi sampai macet", bucket: "Memperdalam jerat" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Fenomena Galbay Pinjol dan Jalur Restrukturisasi",
        html: "Seiring maraknya pinjaman online sejak sekitar <strong>2018</strong> dan melonjak selama pandemi <strong>2020 sampai 2021</strong>, muncul fenomena <strong>galbay</strong> (gagal bayar), termasuk ajakan keliru untuk sengaja tidak membayar pinjol ilegal. Padahal menunggak pinjol <strong>resmi</strong> tetap terekam di <strong>SLIK OJK</strong> dan menutup akses kredit masa depan. Jalan yang benar adalah menempuh <strong>restrukturisasi</strong> lewat penyelenggara berizin, bukan kabur. Pelajarannya: menghadapi utang secara resmi jauh lebih menyelamatkan daripada menghindarinya.",
      },
      {
        type: "takeaways",
        items: [
          "Langkah pertama dan terpenting: berhenti menambah utang baru.",
          "Data semua utang lengkap dengan saldo, bunga, dan jatuh tempo.",
          "Restrukturisasi lewat pemberi pinjaman resmi bila cicilan tak terjangkau.",
          "Serang utang dengan metode bola salju atau longsor secara konsisten.",
          "Gali lubang tutup lubang hanya memperdalam jerat, bukan solusi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Langkah pertama keluar dari jerat utang adalah?",
            options: [
              "Menambah pinjaman baru yang lebih besar",
              "Berhenti menambah utang baru",
              "Mengabaikan semua tagihan",
              "Pindah kota",
            ],
            answer: 1,
            explain: "Selama masih menambah utang, pelunasan tidak akan pernah selesai.",
          },
          {
            q: "Restrukturisasi utang sebaiknya ditempuh melalui?",
            options: [
              "Pinjol ilegal",
              "Pemberi pinjaman resmi seperti bank atau pinjol berizin OJK",
              "Meminjam dari rentenir",
              "Diam saja tanpa komunikasi",
            ],
            answer: 1,
            explain: "Jalur resmi punya mekanisme keringanan seperti perpanjangan tenor.",
          },
          {
            q: "Total utang Rp6 juta, setoran pokok Rp1,5 juta per bulan. Perkiraan lama lunas?",
            options: ["2 bulan", "4 bulan", "6 bulan", "12 bulan"],
            answer: 1,
            explain: "Rp6 juta / Rp1,5 juta = 4 bulan (perkiraan sederhana tanpa bunga).",
          },
          {
            q: "Mengapa gali lubang tutup lubang berbahaya?",
            options: [
              "Memindahkan utang sambil menambah bunga sehingga jerat makin dalam",
              "Menghapus semua utang seketika",
              "Menurunkan bunga otomatis",
              "Membuat skor kredit membaik",
            ],
            answer: 0,
            explain: "Menambah utang untuk bayar utang hanya memperbesar total kewajiban.",
          },
          {
            q: "Menunggak pinjol resmi tetap berdampak karena?",
            options: [
              "Tidak berdampak apa-apa",
              "Terekam di SLIK OJK dan menutup akses kredit masa depan",
              "Otomatis dihapus setelah sebulan",
              "Menaikkan limit pinjaman",
            ],
            answer: 1,
            explain: "Tunggakan pinjol berizin tercatat di SLIK OJK dan menghambat kredit berikutnya.",
          },
        ],
      },
    ],
  },
];
