import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "investasi-untuk-tujuan",
    levelId: "investasi",
    order: 1,
    title: "Investasi untuk Tujuan",
    summary: "Menghubungkan investasi dengan tujuan dan jangka waktu, serta memahami kekuatan bunga majemuk untuk pemula.",
    durationMin: 13,
    tags: ["investasi", "tujuan", "bunga majemuk", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah dana darurat dan proteksi aman, barulah kita <strong>berinvestasi</strong>. Tetapi investasi bukan soal ikut-ikutan membeli yang sedang tren. Investasi yang baik selalu dimulai dari <strong>tujuan</strong>: untuk apa, kapan dibutuhkan, dan berapa besarnya.",
      },
      {
        type: "video",
        comp: "PiramidaKeuanganVideo",
        title: "Video: Piramida Perencanaan Keuangan",
        caption: "Investasi berdiri di atas fondasi arus kas sehat, dana darurat, dan proteksi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cocokkan instrumen dengan horizon",
        html: "<strong>Jangka pendek</strong> (di bawah 3 tahun): pilih yang aman, seperti deposito atau reksa dana pasar uang. <strong>Jangka menengah</strong> (3 sampai 5 tahun): reksa dana campuran atau obligasi/SBN ritel. <strong>Jangka panjang</strong> (di atas 5 tahun): boleh lebih agresif, seperti saham atau reksa dana saham.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kekuatan bunga majemuk",
        html: "Investasi bertumbuh karena <strong>bunga majemuk</strong>: hasil yang diinvestasikan ulang ikut menghasilkan lagi. Makin awal mulai, makin besar efek bola saljunya. Waktu adalah sahabat terbesar seorang investor.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana setoran rutin bertumbuh dahsyat dalam jangka panjang berkat bunga majemuk.",
      },
      { type: "widget", widget: "SimulatorBungaMajemuk" },
      {
        type: "chart",
        variant: "area",
        title: "Rp1 Juta per Bulan Bertumbuh 8% per Tahun (ilustrasi)",
        unit: "Rp juta",
        source: "perhitungan future value setoran bulanan pada 8% per tahun",
        note: "Menabung rutin Rp1 juta per bulan bisa menjadi ratusan juta dalam jangka panjang karena bunga majemuk.",
        data: [
          { label: "5 tahun", value: 73 },
          { label: "10 tahun", value: 183 },
          { label: "20 tahun", value: 589 },
          { label: "30 tahun", value: 1490 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Mulai lebih awal menang besar",
        html: "Ani mulai investasi <strong>Rp1 juta per bulan</strong> pada usia 25 dan berhenti menyetor di usia 35 (10 tahun saja). Beni baru mulai di usia 35 dan menyetor sampai 55 (20 tahun). Dengan imbal hasil sama, saat pensiun dana Ani sering kali <strong>tetap lebih besar</strong> meski total setorannya lebih sedikit, karena uangnya bekerja lebih lama. Inilah keajaiban memulai lebih awal.",
      },
      {
        type: "calcExercise",
        prompt: "Menabung Rp1 juta per bulan selama 20 tahun (240 bulan). Berapa total setoran pokoknya, tanpa menghitung hasil investasi (dalam juta)?",
        answer: 240,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Total setoran = 240 bulan x Rp1 juta = <strong>Rp240 juta</strong>. Dengan hasil investasi 8%, nilainya bisa jauh lebih besar (sekitar Rp589 juta).",
        hint: "Kalikan setoran bulanan dengan jumlah bulan.",
      },
      {
        type: "classifyExercise",
        prompt: "Instrumen ini paling cocok untuk horizon yang mana?",
        buckets: ["Jangka pendek", "Jangka menengah", "Jangka panjang"],
        items: [
          { text: "Reksa dana pasar uang", bucket: "Jangka pendek" },
          { text: "SBN ritel / obligasi", bucket: "Jangka menengah" },
          { text: "Reksa dana saham", bucket: "Jangka panjang" },
          { text: "Deposito untuk tujuan tahun depan", bucket: "Jangka pendek" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya Reksa Dana di Indonesia",
        html: "Industri <strong>reksa dana</strong> modern di Indonesia mulai berkembang pada era <strong>1990-an</strong>, terutama setelah UU Pasar Modal <strong>1995</strong>, yang membuka jalan bagi masyarakat awam ikut berinvestasi dengan modal kecil dan dikelola manajer profesional. Kini, lewat aplikasi, siapa pun bisa memulai investasi hanya dengan puluhan ribu rupiah, sesuatu yang dulu hanya bisa dilakukan orang berpunya.",
      },
      {
        type: "takeaways",
        items: [
          "Investasi dimulai setelah dana darurat dan proteksi aman.",
          "Selalu mulai dari tujuan dan jangka waktunya.",
          "Cocokkan instrumen dengan horizon: pendek aman, panjang boleh agresif.",
          "Bunga majemuk membuat memulai lebih awal sangat menguntungkan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Investasi yang baik dimulai dari?",
            options: ["Ikut tren", "Tujuan dan jangka waktunya", "Modal besar", "Utang"],
            answer: 1,
            explain: "Tentukan dulu tujuan dan kapan dana dibutuhkan, baru pilih instrumen.",
          },
          {
            q: "Untuk tujuan di bawah 3 tahun, instrumen yang cocok?",
            options: ["Saham agresif", "Reksa dana pasar uang / deposito", "Kripto", "Semua saham"],
            answer: 1,
            explain: "Jangka pendek butuh instrumen aman dan stabil.",
          },
          {
            q: "Bunga majemuk berarti?",
            options: [
              "Bunga yang dihapus",
              "Hasil diinvestasikan ulang sehingga ikut menghasilkan",
              "Bunga pinjaman",
              "Pajak investasi",
            ],
            answer: 1,
            explain: "Hasil yang diputar ulang membuat pertumbuhan menumpuk seperti bola salju.",
          },
          {
            q: "Menabung Rp2 juta/bulan selama 10 tahun, total setoran pokoknya?",
            options: ["Rp120 juta", "Rp240 juta", "Rp24 juta", "Rp1,2 miliar"],
            answer: 1,
            explain: "120 bulan x Rp2 juta = Rp240 juta (belum termasuk hasil investasi).",
          },
          {
            q: "Mengapa memulai investasi lebih awal menguntungkan?",
            options: [
              "Karena harga selalu naik",
              "Karena uang punya lebih banyak waktu bertumbuh lewat bunga majemuk",
              "Karena bebas risiko",
              "Karena tanpa pajak",
            ],
            answer: 1,
            explain: "Waktu memperbesar efek bunga majemuk secara dramatis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "profil-risiko-alokasi-aset",
    levelId: "investasi",
    order: 2,
    title: "Profil Risiko & Alokasi Aset",
    summary: "Mengenali profil risiko konservatif, moderat, dan agresif, lalu menyusun alokasi aset yang cocok dengan usia dan ketahanan tidur nyenyak Anda.",
    durationMin: 14,
    tags: ["profil risiko", "alokasi aset", "diversifikasi", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum memilih instrumen, kenali dulu diri sendiri. <strong>Profil risiko</strong> adalah seberapa besar naik-turun nilai investasi yang sanggup Anda tanggung, baik secara keuangan maupun secara perasaan. Investasi terbaik bukan yang imbal hasilnya paling tinggi, melainkan yang bisa Anda pegang dengan tenang sampai tujuan tercapai.",
      },
      {
        type: "paragraph",
        html: "Dari profil risiko lahirlah <strong>alokasi aset</strong>, yaitu bagaimana uang dibagi ke saham, obligasi, dan kas. Alokasi inilah yang paling menentukan hasil jangka panjang, jauh lebih penting daripada menebak saham mana yang akan naik besok.",
      },
      {
        type: "video",
        comp: "PiramidaKeuanganVideo",
        title: "Video: Piramida Perencanaan Keuangan",
        caption: "Alokasi aset yang sehat berdiri di atas dana darurat dan proteksi yang sudah beres.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga profil risiko",
        html: "<strong>Konservatif</strong>: tidak nyaman melihat nilai turun, utamakan keamanan (banyak kas dan obligasi). <strong>Moderat</strong>: siap menerima naik-turun sedang demi hasil lebih baik (campuran seimbang). <strong>Agresif</strong>: tahan melihat nilai anjlok sementara demi potensi pertumbuhan besar (banyak saham).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Aturan sederhana sesuai usia",
        html: "Pedoman kasar yang populer: porsi saham kira-kira <strong>110 dikurangi usia</strong>. Usia 30 berarti sekitar 80% saham, usia 60 berarti sekitar 50% saham. Ini hanya titik awal, bukan hukum mati. Sesuaikan dengan tujuan dan rasa nyaman Anda.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan lebih berani dari kemampuan tidur nyenyak",
        html: "Banyak orang mengaku agresif saat pasar naik, lalu panik menjual saat pasar turun 30%. Panik menjual di titik terendah mengubah kerugian sementara menjadi kerugian permanen. Pilih alokasi yang tetap membuat Anda bisa tidur nyenyak saat pasar bergejolak.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser porsi saham, obligasi, dan kas, lalu lihat bagaimana perkiraan hasil dan risikonya berubah sesuai profil.",
      },
      { type: "widget", widget: "SimulatorAlokasiAset" },
      {
        type: "chart",
        variant: "bar",
        title: "Contoh Alokasi Aset per Profil Risiko (ilustrasi)",
        unit: "% saham",
        source: "ilustrasi edukatif porsi saham per profil risiko",
        note: "Makin agresif profilnya, makin besar porsi saham dan makin besar pula ayunan nilainya.",
        data: [
          { label: "Konservatif", value: 20, color: "#38bdf8" },
          { label: "Moderat", value: 50, color: "#22c55e" },
          { label: "Agresif", value: 80, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua profil, dua ketenangan",
        html: "Sari (konservatif) menaruh 70% di deposito dan SBN, 30% di reksa dana saham. Saat pasar saham turun 25%, total portofolionya hanya turun sekitar 7,5% sehingga ia tetap tenang. Doni (agresif) menaruh 90% di saham; portofolionya turun sekitar 22,5%. Keduanya benar selama Doni memang sanggup menahan penurunan itu tanpa panik menjual dan punya horizon panjang.",
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya Teori Portofolio Modern (1952)",
        html: "Pada <strong>1952</strong>, ekonom <strong>Harry Markowitz</strong> menerbitkan makalah <em>Portfolio Selection</em> yang memperkenalkan gagasan bahwa risiko sebuah portofolio bukan sekadar jumlah risiko tiap aset, melainkan bergantung pada bagaimana aset-aset bergerak bersama. Menggabungkan aset yang tidak searah bisa menurunkan risiko tanpa mengorbankan banyak imbal hasil. Gagasan diversifikasi ini membuat Markowitz meraih Nobel Ekonomi pada <strong>1990</strong> dan menjadi dasar cara kita menyusun alokasi aset sampai sekarang.",
      },
      {
        type: "calcExercise",
        prompt: "Mengikuti aturan '110 dikurangi usia', berapa persen porsi saham yang disarankan untuk orang berusia 35 tahun?",
        answer: 75,
        tolerance: 0,
        suffix: "%",
        solution: "110 - 35 = <strong>75%</strong> saham, sisanya sekitar 25% di obligasi dan kas. Ini hanya titik awal yang perlu disesuaikan dengan tujuan dan rasa nyaman.",
        hint: "Kurangi 110 dengan usia.",
      },
      {
        type: "classifyExercise",
        prompt: "Sikap atau kondisi ini paling menggambarkan profil risiko yang mana?",
        buckets: ["Konservatif", "Moderat", "Agresif"],
        items: [
          { text: "Panik dan ingin menjual saat nilai turun sedikit", bucket: "Konservatif" },
          { text: "Siap menahan turun-naik sedang demi hasil lebih baik", bucket: "Moderat" },
          { text: "Muda, horizon panjang, tahan lihat nilai anjlok sementara", bucket: "Agresif" },
          { text: "Butuh dananya tahun depan dan tak mau rugi", bucket: "Konservatif" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Kenali profil risiko dulu: konservatif, moderat, atau agresif.",
          "Alokasi aset (bagi ke saham, obligasi, kas) paling menentukan hasil jangka panjang.",
          "Pedoman '110 dikurangi usia' hanya titik awal, bukan hukum mati.",
          "Jangan lebih berani dari kemampuan tidur nyenyak; panik menjual mengubah rugi sementara jadi permanen.",
          "Diversifikasi ala Markowitz menurunkan risiko dengan menggabungkan aset yang tak searah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa yang dimaksud profil risiko?",
            options: [
              "Jumlah uang yang dimiliki",
              "Seberapa besar naik-turun nilai yang sanggup ditanggung, secara keuangan dan perasaan",
              "Nama produk investasi",
              "Besarnya pajak",
            ],
            answer: 1,
            explain: "Profil risiko mengukur ketahanan Anda terhadap fluktuasi nilai investasi.",
          },
          {
            q: "Faktor yang paling menentukan hasil investasi jangka panjang adalah?",
            options: ["Menebak saham harian", "Alokasi aset", "Berita pasar", "Nama sekuritas"],
            answer: 1,
            explain: "Alokasi aset (pembagian ke saham, obligasi, kas) berdampak paling besar.",
          },
          {
            q: "Menurut aturan '110 dikurangi usia', porsi saham untuk usia 40 tahun sekitar?",
            options: ["40%", "50%", "70%", "110%"],
            answer: 2,
            explain: "110 - 40 = 70% saham sebagai titik awal.",
          },
          {
            q: "Investor konservatif sebaiknya?",
            options: [
              "Menaruh 100% di saham",
              "Memperbanyak kas dan obligasi, sedikit saham",
              "Berutang untuk investasi",
              "Menghindari semua investasi",
            ],
            answer: 1,
            explain: "Profil konservatif mengutamakan keamanan dengan porsi besar di kas dan obligasi.",
          },
          {
            q: "Bahaya terbesar bila memilih alokasi lebih agresif dari kemampuan diri?",
            options: [
              "Pajak naik",
              "Panik menjual di titik terendah sehingga rugi jadi permanen",
              "Tidak ada bahaya",
              "Bunga majemuk hilang",
            ],
            answer: 1,
            explain: "Panik menjual saat pasar anjlok mengunci kerugian yang seharusnya hanya sementara.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengenal-instrumen-investasi",
    levelId: "investasi",
    order: 3,
    title: "Mengenal Instrumen Investasi",
    summary: "Peta ringkas instrumen investasi di Indonesia: reksa dana, saham, SBN ritel, emas, dan deposito, termasuk pilihan syariahnya.",
    durationMin: 15,
    tags: ["reksa dana", "saham", "SBN ritel", "emas", "syariah"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah tahu profil risiko, saatnya berkenalan dengan menu investasi yang tersedia di Indonesia. Setiap instrumen punya karakter berbeda dalam hal <strong>risiko</strong>, <strong>potensi imbal hasil</strong>, dan <strong>likuiditas</strong> (mudah tidaknya dicairkan). Tidak ada yang paling bagus untuk semua orang; yang ada adalah yang paling cocok untuk tujuan Anda.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat jenis reksa dana",
        html: "<strong>Pasar uang</strong>: paling aman, untuk jangka pendek. <strong>Pendapatan tetap</strong>: isi obligasi, risiko sedang. <strong>Campuran</strong>: gado-gado saham dan obligasi. <strong>Saham</strong>: paling agresif, untuk jangka panjang. Semua dikelola manajer investasi profesional, cocok bagi pemula yang belum mau memilih saham sendiri.",
      },
      {
        type: "callout",
        tone: "info",
        title: "SBN ritel: memberi utang ke negara",
        html: "Surat Berharga Negara ritel adalah surat utang negara untuk masyarakat, mulai dari Rp1 juta. <strong>ORI</strong> (Obligasi Negara Ritel) dan <strong>SBR</strong> (Savings Bond Ritel) bersifat konvensional, sedangkan <strong>SR</strong> (Sukuk Ritel) dan <strong>ST</strong> (Sukuk Tabungan) berbasis syariah. Kuponnya rutin dan dijamin undang-undang, dengan pajak kupon final hanya 10%, lebih rendah dari bunga deposito.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Ada pilihan syariah",
        html: "Bagi yang ingin sesuai prinsip syariah, tersedia <strong>reksa dana syariah</strong>, <strong>sukuk ritel</strong> (SR/ST), dan <strong>saham syariah</strong> yang masuk Daftar Efek Syariah dan Indeks Saham Syariah Indonesia (ISSI). Prinsipnya menghindari riba, judi, dan usaha yang tidak halal, dengan pengawasan Dewan Pengawas Syariah.",
      },
      {
        type: "video",
        comp: "BungaMajemukVideo",
        title: "Video: Kekuatan Bunga Majemuk",
        caption: "Apa pun instrumennya, imbal hasil yang diputar ulang membuat nilai bertumbuh menumpuk.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan bagaimana reksa dana pasar uang, campuran, dan saham bisa bertumbuh berbeda sesuai potensi imbal hasil dan risikonya.",
      },
      { type: "widget", widget: "SimulatorReksaDana" },
      {
        type: "chart",
        variant: "bar",
        title: "Perkiraan Imbal Hasil Tahunan per Instrumen (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi edukatif kisaran imbal hasil historis jangka panjang",
        note: "Potensi imbal hasil lebih tinggi selalu datang bersama risiko naik-turun yang lebih besar. Tidak ada yang gratis.",
        data: [
          { label: "Deposito", value: 4, color: "#38bdf8" },
          { label: "RD Pasar Uang", value: 5, color: "#0ea5e9" },
          { label: "SBN Ritel", value: 6, color: "#22c55e" },
          { label: "RD Pendapatan Tetap", value: 7, color: "#16a34a" },
          { label: "Emas", value: 8, color: "#eab308" },
          { label: "RD Saham", value: 11, color: "#f59e0b" },
        ],
      },
      {
        type: "table",
        headers: ["Instrumen", "Risiko", "Horizon ideal", "Catatan"],
        rows: [
          ["Deposito", "Sangat rendah", "Pendek", "Dijamin LPS sampai batas tertentu"],
          ["Reksa dana pasar uang", "Rendah", "Pendek", "Mudah dicairkan, hasil di atas tabungan"],
          ["SBN ritel (ORI/SR/SBR/ST)", "Rendah", "Menengah", "Kupon rutin, dijamin negara"],
          ["Emas", "Sedang", "Menengah-panjang", "Lindung nilai terhadap inflasi"],
          ["Reksa dana saham", "Tinggi", "Panjang", "Potensi tinggi, fluktuasi besar"],
        ],
        caption: "Peta ringkas instrumen dari yang paling aman ke paling agresif.",
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih instrumen sesuai tujuan",
        html: "Rina punya tiga tujuan. Dana liburan tahun depan (Rp20 juta) ia taruh di <strong>reksa dana pasar uang</strong> agar aman dan mudah dicairkan. Uang muka rumah 4 tahun lagi ia taruh di <strong>SBN ritel</strong> agar kuponnya rutin. Dana pensiun 25 tahun lagi ia taruh di <strong>reksa dana saham</strong> agar tumbuh maksimal. Satu orang, tiga instrumen, sesuai jarak waktu.",
      },
      {
        type: "case",
        title: "Sejarah: Negara Membuka Investasi untuk Rakyat",
        html: "Dulu surat utang negara hanya dibeli institusi besar. Pemerintah lalu menerbitkan <strong>Obligasi Negara Ritel (ORI)</strong> pertama pada <strong>2006</strong>, disusul <strong>Sukuk Ritel (SR)</strong> pertama pada <strong>2009</strong>. Untuk pertama kalinya rakyat biasa bisa ikut mendanai pembangunan negara mulai dari Rp1 juta sambil menerima kupon. Kini penjualannya sepenuhnya online, menjangkau jutaan investor muda lewat aplikasi.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen dengan ciri khasnya.",
        pairs: [
          { left: "Reksa dana pasar uang", right: "Aman dan mudah dicairkan untuk jangka pendek" },
          { left: "SBN ritel (ORI/SR)", right: "Memberi pinjaman ke negara, dapat kupon rutin" },
          { left: "Reksa dana saham", right: "Potensi tinggi untuk jangka panjang, fluktuatif" },
          { left: "Emas", right: "Lindung nilai terhadap inflasi jangka panjang" },
          { left: "Deposito", right: "Bunga tetap, dijamin LPS sampai batas tertentu" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Instrumen ini termasuk konvensional atau punya versi syariah yang setara?",
        buckets: ["Berbasis syariah", "Konvensional"],
        items: [
          { text: "Sukuk Ritel (SR)", bucket: "Berbasis syariah" },
          { text: "Reksa dana syariah", bucket: "Berbasis syariah" },
          { text: "Obligasi Negara Ritel (ORI)", bucket: "Konvensional" },
          { text: "Saham anggota ISSI (Daftar Efek Syariah)", bucket: "Berbasis syariah" },
          { text: "Savings Bond Ritel (SBR)", bucket: "Konvensional" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Setiap instrumen beda dalam risiko, imbal hasil, dan likuiditas; tidak ada yang paling bagus untuk semua.",
          "Reksa dana ada empat jenis: pasar uang, pendapatan tetap, campuran, dan saham.",
          "SBN ritel (ORI, SR, SBR, ST) memberi kupon rutin dan dijamin negara mulai Rp1 juta.",
          "Tersedia pilihan syariah: reksa dana syariah, sukuk ritel, dan saham syariah (ISSI).",
          "Imbal hasil lebih tinggi selalu datang bersama risiko yang lebih besar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Reksa dana yang paling cocok untuk tujuan jangka pendek dan aman adalah?",
            options: ["Reksa dana saham", "Reksa dana pasar uang", "Reksa dana campuran", "Reksa dana indeks"],
            answer: 1,
            explain: "Reksa dana pasar uang paling stabil dan mudah dicairkan.",
          },
          {
            q: "Apa itu ORI?",
            options: [
              "Saham perusahaan negara",
              "Obligasi Negara Ritel, surat utang negara untuk masyarakat",
              "Reksa dana asing",
              "Deposito bank",
            ],
            answer: 1,
            explain: "ORI adalah surat utang negara ritel yang bisa dibeli masyarakat mulai Rp1 juta.",
          },
          {
            q: "Manakah instrumen berbasis syariah?",
            options: ["ORI", "SBR", "Sukuk Ritel (SR)", "Deposito biasa"],
            answer: 2,
            explain: "Sukuk Ritel (SR) dan Sukuk Tabungan (ST) berbasis prinsip syariah.",
          },
          {
            q: "Pernyataan yang benar tentang imbal hasil dan risiko?",
            options: [
              "Imbal hasil tinggi selalu tanpa risiko",
              "Potensi imbal hasil lebih tinggi datang bersama risiko lebih besar",
              "Deposito lebih berisiko dari saham",
              "Risiko tidak berhubungan dengan hasil",
            ],
            answer: 1,
            explain: "Tidak ada makan siang gratis; hasil lebih tinggi menuntut toleransi risiko lebih besar.",
          },
          {
            q: "Siapa yang mengelola dana pada reksa dana?",
            options: ["Nasabah sendiri", "Manajer investasi profesional", "Pemerintah", "Bank sentral"],
            answer: 1,
            explain: "Reksa dana dikelola manajer investasi, cocok untuk pemula yang belum memilih sendiri.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "investasi-rutin-dca",
    levelId: "investasi",
    order: 4,
    title: "Investasi Rutin: Dollar Cost Averaging",
    summary: "Menyetor nominal tetap secara rutin membuat Anda otomatis membeli lebih banyak saat harga murah dan mengurangi risiko salah waktu.",
    durationMin: 14,
    tags: ["dca", "nabung rutin", "reksa dana", "disiplin"],
    blocks: [
      {
        type: "paragraph",
        html: "Salah satu ketakutan terbesar pemula adalah <strong>salah waktu</strong>: takut membeli saat harga sedang tinggi lalu langsung turun. Kabar baiknya, ada strategi sederhana yang menghapus kebutuhan menebak waktu, yaitu <strong>Dollar Cost Averaging</strong> (DCA) atau nabung rutin.",
      },
      {
        type: "paragraph",
        html: "Idenya: setor <strong>nominal tetap</strong> pada jadwal tetap, misalnya Rp1 juta setiap tanggal 1, apa pun kondisi pasar. Karena nominalnya tetap, saat harga turun Anda otomatis membeli lebih banyak unit, dan saat harga naik Anda membeli lebih sedikit. Hasilnya, harga beli rata-rata Anda menjadi lebih halus.",
      },
      {
        type: "video",
        comp: "DollarCostAveragingVideo",
        title: "Video: Dollar Cost Averaging",
        caption: "Menyetor rutin dengan nominal tetap otomatis membeli lebih banyak saat harga murah.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Nominal tetap, bukan unit tetap",
        html: "Kuncinya adalah menjaga <strong>rupiah yang disetor</strong> tetap sama, bukan jumlah unit. Rp1 juta saat harga unit Rp1.000 dapat 1.000 unit; saat harga turun ke Rp800 dapat 1.250 unit. Otomatis Anda memborong lebih banyak ketika sedang diskon.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Disiplin mengalahkan menebak",
        html: "DCA mengubah investasi menjadi kebiasaan, bukan drama menebak pasar. Aktifkan <strong>autodebet</strong> agar setoran jalan sendiri. Konsistensi selama bertahun-tahun jauh lebih menentukan daripada keberuntungan menebak titik terbawah.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "DCA bukan sihir anti rugi",
        html: "DCA menurunkan risiko salah waktu, tetapi tidak menjamin untung. Bila instrumen yang dipilih memang buruk atau horizonnya terlalu pendek, nabung rutin pun bisa rugi. DCA tetap perlu instrumen yang tepat dan waktu yang cukup.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur nominal setoran dan lihat bagaimana pembelian rutin menghaluskan harga beli rata-rata Anda dari waktu ke waktu.",
      },
      { type: "widget", widget: "SimulatorDCA" },
      {
        type: "chart",
        variant: "line",
        title: "Harga Unit Bergejolak, Setoran Tetap Rp1 Juta (ilustrasi)",
        unit: "Rp per unit",
        source: "ilustrasi edukatif DCA selama 5 bulan",
        note: "Saat harga turun, Rp1 juta yang sama membeli lebih banyak unit sehingga harga rata-rata Anda lebih rendah dari rata-rata harga pasar.",
        data: [
          { label: "Bln 1", value: 1000 },
          { label: "Bln 2", value: 800 },
          { label: "Bln 3", value: 500 },
          { label: "Bln 4", value: 800 },
          { label: "Bln 5", value: 1000 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung harga beli rata-rata",
        html: "Budi menyetor <strong>Rp1 juta</strong> selama 3 bulan. Bulan 1 harga Rp1.000 (dapat 1.000 unit), bulan 2 harga Rp500 (dapat 2.000 unit), bulan 3 harga Rp1.000 (dapat 1.000 unit). Total setoran Rp3 juta, total unit 4.000. Harga beli rata-ratanya = Rp3.000.000 / 4.000 = <strong>Rp750</strong> per unit, lebih murah dari rata-rata harga pasar Rp833. Membeli saat murah menariknya turun.",
      },
      {
        type: "case",
        title: "Sejarah: Nabung Saham dan Reksa Dana Lewat Aplikasi",
        html: "Selama bertahun-tahun berinvestasi terasa rumit dan mahal. Perubahan besar datang ketika Bursa Efek Indonesia meluncurkan kampanye <strong>Yuk Nabung Saham pada 2015</strong> dan menurunkan minimal pembelian menjadi 1 lot (100 lembar). Ditambah ledakan aplikasi investasi sekitar <strong>2017 sampai 2021</strong>, jumlah investor ritel di Indonesia melonjak dari ratusan ribu menjadi lebih dari 10 juta. DCA bulanan lewat autodebet menjadi kebiasaan jutaan anak muda.",
      },
      {
        type: "calcExercise",
        prompt: "Anda menyetor Rp600.000 dua kali. Pembelian pertama harga unit Rp1.000 (dapat 600 unit), kedua harga unit Rp600 (dapat 1.000 unit). Berapa harga beli rata-rata Anda per unit?",
        answer: 750,
        tolerance: 5,
        prefix: "Rp",
        solution: "Total setoran = Rp1.200.000. Total unit = 600 + 1.000 = 1.600. Harga rata-rata = 1.200.000 / 1.600 = <strong>Rp750</strong> per unit, lebih rendah dari rata-rata harga (Rp800) karena membeli lebih banyak saat murah.",
        hint: "Bagi total rupiah yang disetor dengan total unit yang didapat.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan DCA Rp500.000 per bulan selama 3 tahun (36 bulan), berapa total pokok yang Anda setorkan (dalam juta)?",
        answer: 18,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "36 bulan x Rp500.000 = Rp18.000.000 = <strong>Rp18 juta</strong> pokok, belum termasuk hasil investasi.",
        hint: "Kalikan setoran bulanan dengan jumlah bulan.",
      },
      {
        type: "takeaways",
        items: [
          "DCA berarti menyetor nominal tetap secara rutin, apa pun kondisi pasar.",
          "Karena nominal tetap, Anda otomatis membeli lebih banyak unit saat harga murah.",
          "Strategi ini menghapus kebutuhan menebak waktu dan membangun disiplin lewat autodebet.",
          "Harga beli rata-rata menjadi lebih halus, tetapi DCA tidak menjamin bebas rugi.",
          "Konsistensi bertahun-tahun lebih menentukan daripada keberuntungan menebak titik terbawah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti dari Dollar Cost Averaging adalah?",
            options: [
              "Membeli jumlah unit yang sama tiap bulan",
              "Menyetor nominal rupiah yang tetap secara rutin",
              "Membeli hanya saat harga naik",
              "Menebak titik terbawah pasar",
            ],
            answer: 1,
            explain: "DCA menjaga rupiah setoran tetap, bukan jumlah unit.",
          },
          {
            q: "Saat harga unit turun, setoran nominal tetap akan?",
            options: ["Membeli lebih sedikit unit", "Membeli lebih banyak unit", "Berhenti otomatis", "Membeli unit sama"],
            answer: 1,
            explain: "Rupiah yang sama membeli lebih banyak unit ketika harga sedang murah.",
          },
          {
            q: "Setoran Rp1 juta di harga Rp1.000 lalu Rp1 juta di harga Rp500. Berapa harga rata-rata belinya?",
            options: ["Rp1.000", "Rp750", "Rp667", "Rp500"],
            answer: 2,
            explain: "Total Rp2 juta / (1.000 + 2.000 unit) = Rp2.000.000 / 3.000 = sekitar Rp667.",
          },
          {
            q: "Pernyataan yang benar tentang DCA?",
            options: [
              "Menjamin selalu untung",
              "Menurunkan risiko salah waktu tetapi tidak menjamin bebas rugi",
              "Hanya untuk orang kaya",
              "Membutuhkan menebak pasar tiap hari",
            ],
            answer: 1,
            explain: "DCA mengurangi risiko timing, namun tetap butuh instrumen tepat dan horizon cukup.",
          },
          {
            q: "Cara terbaik menjaga disiplin DCA adalah?",
            options: ["Menyetor kalau ingat", "Mengaktifkan autodebet rutin", "Menunggu berita bagus", "Menyetor saat harga naik saja"],
            answer: 1,
            explain: "Autodebet membuat setoran berjalan otomatis dan konsisten.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "diversifikasi-rebalancing",
    levelId: "investasi",
    order: 5,
    title: "Diversifikasi & Rebalancing",
    summary: "Menyebar risiko ke banyak keranjang dan mengembalikan porsi ke target lewat rebalancing agar portofolio tetap sesuai rencana.",
    durationMin: 14,
    tags: ["diversifikasi", "rebalancing", "risiko", "portofolio"],
    blocks: [
      {
        type: "paragraph",
        html: "Ada satu nasihat investasi tertua yang tak pernah usang: <strong>jangan taruh semua telur dalam satu keranjang</strong>. Kalau keranjang itu jatuh, semua telur pecah sekaligus. <strong>Diversifikasi</strong> adalah menyebar uang ke banyak aset agar satu kejadian buruk tidak menghancurkan seluruh portofolio.",
      },
      {
        type: "paragraph",
        html: "Tetapi diversifikasi saja belum cukup. Seiring waktu, aset yang tumbuh cepat akan membesar porsinya dan diam-diam membuat portofolio Anda lebih berisiko dari rencana. Di sinilah <strong>rebalancing</strong> berperan: mengembalikan porsi setiap aset ke target semula.",
      },
      {
        type: "video",
        comp: "DiversifikasiVideo",
        title: "Video: Diversifikasi",
        caption: "Menyebar telur ke banyak keranjang membuat satu keranjang jatuh tidak menghabiskan semuanya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rebalancing: jual yang naik, beli yang turun",
        html: "Misal target Anda 60% saham dan 40% obligasi. Setelah saham melonjak, porsinya jadi 75%. Rebalancing berarti menjual sebagian saham dan membeli obligasi agar kembali 60:40. Ini memaksa Anda <strong>mengambil untung dari yang mahal dan memborong yang murah</strong> secara otomatis dan tanpa emosi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kapan rebalancing?",
        html: "Dua pendekatan umum: <strong>berkala</strong> (mis. sekali setahun) atau <strong>berbasis ambang</strong> (rebalancing bila porsi melenceng lebih dari 5% dari target). Tidak perlu terlalu sering; setahun sekali sudah cukup untuk sebagian besar orang dan menghemat biaya transaksi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Diversifikasi palsu",
        html: "Punya 10 reksa dana saham yang isinya saham-saham besar yang sama bukanlah diversifikasi, itu pengulangan. Diversifikasi sejati menyebar ke aset yang <strong>tidak bergerak searah</strong>, seperti campuran saham, obligasi, emas, dan kas. Cek isi, bukan sekadar jumlah produk.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser porsi aset dan bayangkan setelah setahun. Lihat bagaimana rebalancing mengembalikan komposisi ke target risiko yang Anda pilih.",
      },
      { type: "widget", widget: "SimulatorAlokasiAset" },
      {
        type: "chart",
        variant: "bar",
        title: "Porsi Saham Melenceng Lalu Dikembalikan (ilustrasi)",
        unit: "% saham",
        source: "ilustrasi edukatif drift dan rebalancing terhadap target 60%",
        note: "Tanpa rebalancing, portofolio perlahan menjadi lebih agresif dari yang Anda rencanakan.",
        data: [
          { label: "Target awal", value: 60, color: "#22c55e" },
          { label: "Setelah saham naik", value: 75, color: "#f59e0b" },
          { label: "Sesudah rebalancing", value: 60, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung langkah rebalancing",
        html: "Portofolio Wati Rp100 juta dengan target 60% saham (Rp60 juta) dan 40% obligasi (Rp40 juta). Setahun kemudian saham naik menjadi Rp75 juta, obligasi tetap Rp40 juta, total Rp115 juta. Porsi saham kini 65%. Untuk kembali ke 60%, target saham = 60% x Rp115 juta = Rp69 juta. Wati <strong>menjual Rp6 juta saham</strong> dan memindahkannya ke obligasi. Ia mengambil untung dari yang mahal secara disiplin.",
      },
      {
        type: "case",
        title: "Sejarah: Bahaya Menaruh Semua di Satu Aset",
        html: "Sejarah pasar penuh pelajaran tentang investor yang all-in satu aset lalu hancur. Karyawan <strong>Enron</strong> menaruh sebagian besar dana pensiun mereka di saham perusahaan sendiri; ketika Enron bangkrut pada <strong>2001</strong>, banyak yang kehilangan pekerjaan sekaligus seluruh tabungan pensiun. Pola serupa terjadi pada gelembung dot-com <strong>2000</strong> dan mania kripto <strong>2021 sampai 2022</strong>. Diversifikasi memang membosankan, tetapi itulah yang menjaga Anda tetap berdiri saat satu keranjang jatuh.",
      },
      {
        type: "calcExercise",
        prompt: "Portofolio Rp200 juta, target 70% saham. Berapa rupiah yang seharusnya ada di saham (dalam juta)?",
        answer: 140,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "70% x Rp200 juta = <strong>Rp140 juta</strong> di saham, sisanya Rp60 juta di obligasi dan kas.",
        hint: "Kalikan total portofolio dengan persentase target.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Diversifikasi", right: "Menyebar uang ke banyak aset agar risiko tidak menumpuk" },
          { left: "Rebalancing", right: "Mengembalikan porsi aset ke target semula" },
          { left: "Drift", right: "Porsi aset melenceng dari target karena pergerakan harga" },
          { left: "Diversifikasi palsu", right: "Banyak produk tetapi isinya aset yang sama" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Jangan taruh semua telur dalam satu keranjang; sebar risiko ke banyak aset.",
          "Diversifikasi sejati menggabungkan aset yang tidak bergerak searah, bukan sekadar banyak produk.",
          "Seiring waktu porsi aset melenceng (drift) dan diam-diam menambah risiko.",
          "Rebalancing mengembalikan porsi ke target: jual yang mahal, beli yang murah, tanpa emosi.",
          "Cukup rebalancing setahun sekali atau saat melenceng lebih dari 5% dari target.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama diversifikasi adalah?",
            options: [
              "Menjamin untung besar",
              "Menyebar risiko agar satu kejadian buruk tak menghancurkan semua",
              "Menghindari pajak",
              "Menebak pasar",
            ],
            answer: 1,
            explain: "Diversifikasi menyebar telur ke banyak keranjang agar risiko tidak menumpuk.",
          },
          {
            q: "Rebalancing berarti?",
            options: [
              "Menjual semua aset",
              "Mengembalikan porsi aset ke target semula",
              "Membeli aset yang sedang tren",
              "Berhenti berinvestasi",
            ],
            answer: 1,
            explain: "Rebalancing menyetel ulang komposisi agar sesuai target risiko.",
          },
          {
            q: "Saat rebalancing setelah saham naik pesat, biasanya Anda?",
            options: [
              "Menjual sebagian saham dan menambah obligasi",
              "Membeli lebih banyak saham",
              "Menjual semua obligasi",
              "Tidak melakukan apa-apa",
            ],
            answer: 0,
            explain: "Anda menjual yang mahal (saham) dan membeli yang relatif murah agar kembali ke target.",
          },
          {
            q: "Manakah yang termasuk diversifikasi palsu?",
            options: [
              "Campuran saham, obligasi, emas, dan kas",
              "Sepuluh reksa dana saham berisi saham besar yang sama",
              "Saham lokal dan obligasi negara",
              "Emas dan deposito",
            ],
            answer: 1,
            explain: "Banyak produk berisi aset yang sama hanyalah pengulangan, bukan diversifikasi.",
          },
          {
            q: "Seberapa sering sebaiknya rebalancing untuk kebanyakan orang?",
            options: ["Setiap hari", "Sekali setahun atau saat melenceng lebih dari 5%", "Tidak pernah", "Setiap jam"],
            answer: 1,
            explain: "Setahun sekali atau berbasis ambang sudah cukup dan hemat biaya transaksi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "biaya-pajak-compounding",
    levelId: "investasi",
    order: 6,
    title: "Biaya, Pajak & Compounding Jangka Panjang",
    summary: "Biaya dan pajak yang tampak kecil bisa menggerus hasil investasi secara dramatis dalam jangka panjang karena bekerja melawan bunga majemuk.",
    durationMin: 15,
    tags: ["biaya", "pajak", "compounding", "reksa dana"],
    blocks: [
      {
        type: "paragraph",
        html: "Dua musuh diam-diam menggerogoti hasil investasi Anda: <strong>biaya</strong> dan <strong>pajak</strong>. Keduanya sering diabaikan karena terlihat kecil per tahun. Tetapi karena bunga majemuk bekerja selama puluhan tahun, selisih biaya 1% saja bisa berarti puluhan bahkan ratusan juta rupiah di akhir.",
      },
      {
        type: "paragraph",
        html: "Kabar baiknya, biaya dan pajak adalah dua hal yang bisa Anda <strong>kendalikan</strong>. Anda tidak bisa mengatur pasar naik atau turun, tetapi Anda bisa memilih produk berbiaya rendah dan memanfaatkan instrumen yang efisien pajak.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Biaya reksa dana yang perlu dicek",
        html: "<strong>Management fee</strong> (biaya pengelolaan tahunan) dipotong diam-diam dari nilai aset, biasanya 0,5% sampai 3% per tahun. Ada juga <strong>biaya pembelian</strong> dan <strong>penjualan</strong> (subscription/redemption fee). Reksa dana indeks dan pasar uang umumnya paling murah; reksa dana saham aktif paling mahal.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pajak investasi di Indonesia",
        html: "<strong>Bunga deposito</strong>: PPh final 20%. <strong>Penjualan saham</strong> di bursa: PPh final 0,1% dari nilai transaksi jual. <strong>Kupon SBN ritel</strong>: PPh final 10%. <strong>Dividen</strong> untuk orang pribadi dalam negeri bisa bebas pajak bila diinvestasikan kembali di Indonesia sesuai ketentuan (sejak UU Cipta Kerja). Keuntungan reksa dana bukan objek pajak di tingkat investor.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "1% bukan angka kecil",
        html: "Selisih biaya 1% per tahun terasa sepele, tetapi selama 30 tahun ia bisa memangkas hasil akhir sekitar seperempatnya. Biaya bekerja seperti bunga majemuk terbalik: menumpuk melawan Anda tanpa terlihat.",
      },
      {
        type: "video",
        comp: "BungaMajemukVideo",
        title: "Video: Kekuatan Bunga Majemuk",
        caption: "Bunga majemuk memperbesar hasil; sayangnya biaya dan pajak juga menumpuk melawan Anda.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan pertumbuhan pada imbal hasil bersih yang berbeda. Kurangi imbal hasil sebesar biaya untuk melihat dampak nyata dalam jangka panjang.",
      },
      { type: "widget", widget: "SimulatorBungaMajemuk" },
      {
        type: "chart",
        variant: "line",
        title: "Rp100 Juta Selama 30 Tahun: Dampak Selisih Biaya (ilustrasi)",
        unit: "Rp juta",
        source: "perhitungan pertumbuhan majemuk pada 9% versus 8% versus 7% per tahun",
        note: "Selisih 1% biaya per tahun berujung selisih ratusan juta setelah 30 tahun. Biaya adalah bunga majemuk yang melawan Anda.",
        data: [
          { label: "8% bersih (biaya 1%)", value: 1006 },
          { label: "7% bersih (biaya 2%)", value: 761 },
          { label: "9% tanpa biaya", value: 1327 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua reksa dana, satu selisih biaya",
        html: "Dana Rp100 juta ditaruh 20 tahun dengan imbal hasil kotor 10%. Reksa dana A berbiaya 1% (bersih 9%), reksa dana B berbiaya 2,5% (bersih 7,5%). Setelah 20 tahun, A tumbuh menjadi sekitar <strong>Rp560 juta</strong>, sedangkan B hanya sekitar <strong>Rp425 juta</strong>. Selisih <strong>Rp135 juta</strong> menguap hanya karena beda biaya 1,5% per tahun. Selalu cek biaya sebelum membeli.",
      },
      {
        type: "case",
        title: "Sejarah: Biaya Kecil, Dampak Raksasa",
        html: "Pada <strong>1976</strong>, John Bogle mendirikan Vanguard dan meluncurkan reksa dana indeks pertama untuk publik dengan biaya sangat rendah. Idenya sederhana: karena biaya pasti menggerus hasil sementara imbal hasil tak pernah pasti, tekan biaya serendah mungkin. Selama puluhan tahun, dana indeks berbiaya rendah terbukti mengalahkan mayoritas reksa dana aktif yang mahal, semata karena selisih biaya yang menumpuk. Pelajarannya universal: biaya kecil berlipat menjadi besar dalam jangka panjang.",
      },
      {
        type: "calcExercise",
        prompt: "Deposito memberi bunga Rp10 juta setahun. Berapa pajak PPh final yang dipotong (20%), dalam juta?",
        answer: 2,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "PPh final bunga deposito = 20% x Rp10 juta = <strong>Rp2 juta</strong>. Bunga bersih yang Anda terima Rp8 juta.",
        hint: "Kalikan bunga dengan tarif 20%.",
      },
      {
        type: "calcExercise",
        prompt: "Reksa dana Anda bernilai Rp50 juta dengan management fee 2% per tahun. Berapa rupiah biaya pengelolaan setahun (dalam ribu)?",
        answer: 1000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "2% x Rp50 juta = Rp1.000.000 = <strong>Rp1.000 ribu</strong> per tahun, dipotong diam-diam dari nilai aset.",
        hint: "Kalikan nilai investasi dengan 2%.",
      },
      {
        type: "classifyExercise",
        prompt: "Manakah yang bisa Anda kendalikan dan mana yang di luar kendali Anda sebagai investor?",
        buckets: ["Bisa dikendalikan", "Di luar kendali"],
        items: [
          { text: "Memilih reksa dana berbiaya rendah", bucket: "Bisa dikendalikan" },
          { text: "Arah pasar naik atau turun", bucket: "Di luar kendali" },
          { text: "Memanfaatkan instrumen efisien pajak", bucket: "Bisa dikendalikan" },
          { text: "Krisis ekonomi global", bucket: "Di luar kendali" },
          { text: "Seberapa sering bertransaksi (menekan biaya)", bucket: "Bisa dikendalikan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Biaya dan pajak menggerus hasil dan bekerja seperti bunga majemuk yang melawan Anda.",
          "Cek management fee reksa dana; indeks dan pasar uang umumnya termurah.",
          "Pajak Indonesia: bunga deposito 20%, jual saham 0,1%, kupon SBN 10%.",
          "Selisih biaya 1% per tahun bisa berarti ratusan juta setelah puluhan tahun.",
          "Biaya dan pajak adalah hal yang bisa Anda kendalikan, tidak seperti arah pasar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Management fee reksa dana adalah?",
            options: [
              "Bonus untuk investor",
              "Biaya pengelolaan tahunan yang dipotong dari nilai aset",
              "Pajak negara",
              "Bunga tambahan",
            ],
            answer: 1,
            explain: "Management fee dipotong diam-diam dari aset dan menggerus hasil.",
          },
          {
            q: "Tarif PPh final atas bunga deposito di Indonesia adalah?",
            options: ["0,1%", "10%", "20%", "30%"],
            answer: 2,
            explain: "Bunga deposito dikenakan PPh final 20%.",
          },
          {
            q: "Pajak atas penjualan saham di bursa adalah?",
            options: ["0,1% dari nilai transaksi jual", "20% dari keuntungan", "10% dari nilai beli", "Bebas pajak"],
            answer: 0,
            explain: "Penjualan saham di bursa dikenakan PPh final 0,1% dari nilai transaksi.",
          },
          {
            q: "Mengapa selisih biaya 1% per tahun penting?",
            options: [
              "Karena sangat kecil dan tidak berdampak",
              "Karena menumpuk lewat bunga majemuk dan bisa memangkas hasil ratusan juta",
              "Karena dikembalikan di akhir",
              "Karena mengurangi pajak",
            ],
            answer: 1,
            explain: "Biaya menumpuk seperti bunga majemuk terbalik selama puluhan tahun.",
          },
          {
            q: "Manakah yang bisa Anda kendalikan sebagai investor?",
            options: [
              "Arah pasar",
              "Krisis global",
              "Memilih produk berbiaya rendah dan efisien pajak",
              "Suku bunga bank sentral",
            ],
            answer: 2,
            explain: "Anda tak bisa mengatur pasar, tetapi bisa menekan biaya dan pajak.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "dana-pendidikan-anak",
    levelId: "investasi",
    order: 7,
    title: "Merencanakan Dana Pendidikan Anak",
    summary: "Biaya pendidikan naik lebih cepat dari inflasi umum. Pelajari cara menghitung biaya masa depan dan setoran bulanan yang dibutuhkan.",
    durationMin: 15,
    tags: ["dana pendidikan", "inflasi pendidikan", "tujuan", "keluarga"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagi banyak keluarga, pendidikan anak adalah tujuan keuangan terbesar setelah rumah. Masalahnya, <strong>biaya pendidikan naik jauh lebih cepat</strong> daripada inflasi umum. Bila inflasi biasa sekitar 3 sampai 4% per tahun, biaya sekolah dan kuliah di Indonesia sering naik 8 sampai 15% per tahun.",
      },
      {
        type: "paragraph",
        html: "Karena itu menabung biasa tidak cukup. Anda perlu menghitung <strong>biaya masa depan</strong> lebih dulu, baru menghitung mundur berapa yang harus disisihkan tiap bulan dan pada instrumen apa, sesuai jarak waktu ke masuk sekolah atau kuliah.",
      },
      {
        type: "video",
        comp: "SiklusHidupKeuanganVideo",
        title: "Video: Siklus Hidup Keuangan",
        caption: "Dana pendidikan direncanakan jauh hari, menyesuaikan tahap hidup keluarga.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Hitung dulu biaya masa depannya",
        html: "Pakai rumus nilai masa depan: <strong>Biaya nanti = Biaya sekarang x (1 + inflasi pendidikan) pangkat jumlah tahun</strong>. Contoh: kuliah yang kini Rp100 juta, dengan inflasi pendidikan 10% per tahun selama 10 tahun, akan menjadi sekitar Rp259 juta. Angka inilah target Anda, bukan harga hari ini.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Cocokkan instrumen dengan jarak waktu",
        html: "<strong>Kurang dari 3 tahun</strong> ke sekolah: instrumen aman seperti deposito atau reksa dana pasar uang. <strong>3 sampai 7 tahun</strong>: reksa dana campuran atau SBN ritel. <strong>Lebih dari 7 tahun</strong> (mis. dana kuliah bayi): boleh reksa dana saham agar mengejar inflasi pendidikan yang tinggi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jangan pakai harga hari ini",
        html: "Kesalahan paling umum adalah menargetkan biaya kuliah versi hari ini. Saat waktunya tiba, biayanya sudah berlipat. Selalu proyeksikan ke depan dengan inflasi pendidikan, lalu sisihkan sesuai target masa depan itu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan biaya sekarang, tahun tersisa, dan asumsi inflasi pendidikan. Lihat berapa biaya nanti dan setoran bulanan yang perlu Anda siapkan.",
      },
      { type: "widget", widget: "KalkulatorDanaPendidikan" },
      {
        type: "chart",
        variant: "area",
        title: "Kuliah Rp100 Juta Hari Ini, Inflasi Pendidikan 10% (ilustrasi)",
        unit: "Rp juta",
        source: "perhitungan nilai masa depan pada inflasi pendidikan 10% per tahun",
        note: "Biaya yang sama berlipat lebih dari dua kali dalam 10 tahun. Menunda perencanaan membuat targetnya makin jauh.",
        data: [
          { label: "Sekarang", value: 100 },
          { label: "5 tahun", value: 161 },
          { label: "10 tahun", value: 259 },
          { label: "15 tahun", value: 418 },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Inflasi Umum vs Inflasi Pendidikan (ilustrasi)",
        unit: "% per tahun",
        source: "ilustrasi edukatif kisaran umum di Indonesia",
        note: "Biaya pendidikan menanjak jauh lebih cepat dari harga barang sehari-hari, jadi butuh instrumen yang tumbuh lebih tinggi.",
        data: [
          { label: "Inflasi umum", value: 4, color: "#38bdf8" },
          { label: "Inflasi pendidikan", value: 12, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menyiapkan dana kuliah si kecil",
        html: "Pak Andi punya bayi dan menargetkan biaya kuliah yang kini Rp150 juta. Dengan inflasi pendidikan 10% dan waktu 18 tahun, biayanya nanti sekitar <strong>Rp834 juta</strong>. Karena horizonnya panjang, ia memilih reksa dana saham dengan asumsi hasil 12% per tahun. Berkat bunga majemuk, setoran sekitar <strong>Rp1,1 juta per bulan</strong> sudah bisa mendekati target itu. Semakin cepat mulai, semakin ringan cicilannya.",
      },
      {
        type: "case",
        title: "Sejarah: Lonjakan Biaya Kuliah di Indonesia",
        html: "Selama dua dekade terakhir, biaya kuliah di Indonesia menanjak jauh melampaui inflasi umum. Uang pangkal dan biaya semester di banyak perguruan tinggi meningkat berlipat, terutama setelah perluasan sistem <strong>Uang Kuliah Tunggal (UKT)</strong> yang mulai diberlakukan sekitar <strong>2013</strong>. Isu kenaikan UKT bahkan kembali memicu protes mahasiswa secara nasional pada <strong>2024</strong>. Pesannya jelas: menunda menyiapkan dana pendidikan berarti mengejar target yang terus berlari menjauh.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya sekolah kini Rp50 juta. Dengan inflasi pendidikan 10% per tahun selama 3 tahun, berapa perkiraan biayanya nanti (dalam juta, bulatkan)?",
        answer: 67,
        tolerance: 1,
        prefix: "Rp",
        suffix: " juta",
        solution: "Biaya nanti = Rp50 juta x (1,10) pangkat 3 = Rp50 juta x 1,331 = sekitar <strong>Rp66,5 juta</strong>, dibulatkan Rp67 juta.",
        hint: "Kalikan biaya sekarang dengan (1,10) dipangkatkan jumlah tahun.",
      },
      {
        type: "calcExercise",
        prompt: "Anda menargetkan dana pendidikan Rp240 juta dalam 10 tahun (120 bulan). Bila hanya menabung tanpa hasil investasi, berapa setoran bulanannya (dalam juta)?",
        answer: 2,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Rp240 juta / 120 bulan = <strong>Rp2 juta</strong> per bulan tanpa hasil investasi. Dengan investasi yang bertumbuh, setoran yang dibutuhkan bisa lebih kecil.",
        hint: "Bagi target dengan jumlah bulan.",
      },
      {
        type: "takeaways",
        items: [
          "Biaya pendidikan naik jauh lebih cepat (8 sampai 15%) daripada inflasi umum.",
          "Hitung dulu biaya masa depan dengan rumus nilai masa depan, jangan pakai harga hari ini.",
          "Dari biaya masa depan, hitung mundur setoran bulanan yang dibutuhkan.",
          "Cocokkan instrumen dengan jarak waktu: dekat pilih aman, jauh boleh agresif.",
          "Semakin cepat mulai, semakin ringan setoran karena bunga majemuk membantu.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa dana pendidikan butuh perhitungan khusus?",
            options: [
              "Karena biayanya tetap",
              "Karena biaya pendidikan naik lebih cepat dari inflasi umum",
              "Karena tidak kena pajak",
              "Karena selalu turun",
            ],
            answer: 1,
            explain: "Inflasi pendidikan yang tinggi membuat biaya berlipat lebih cepat.",
          },
          {
            q: "Langkah pertama merencanakan dana pendidikan adalah?",
            options: [
              "Langsung menabung sedikit-sedikit",
              "Menghitung biaya masa depan dengan inflasi pendidikan",
              "Membeli saham berisiko",
              "Menunggu anak besar",
            ],
            answer: 1,
            explain: "Proyeksikan dulu biaya nanti, baru hitung setoran yang dibutuhkan.",
          },
          {
            q: "Biaya sekolah Rp50 juta, inflasi pendidikan 10%, 3 tahun lagi. Perkiraan biayanya?",
            options: ["Rp50 juta", "Sekitar Rp67 juta", "Rp150 juta", "Rp45 juta"],
            answer: 1,
            explain: "Rp50 juta x 1,331 = sekitar Rp66,5 juta.",
          },
          {
            q: "Untuk dana kuliah bayi (18 tahun lagi), instrumen yang cocok?",
            options: [
              "Deposito jangka pendek saja",
              "Reksa dana saham agar mengejar inflasi pendidikan",
              "Uang tunai di rumah",
              "Kartu kredit",
            ],
            answer: 1,
            explain: "Horizon panjang memungkinkan instrumen agresif untuk mengejar inflasi tinggi.",
          },
          {
            q: "Kesalahan umum dalam merencanakan dana pendidikan adalah?",
            options: [
              "Mulai terlalu cepat",
              "Menargetkan biaya versi hari ini, bukan biaya masa depan",
              "Menghitung inflasi pendidikan",
              "Memakai instrumen sesuai horizon",
            ],
            answer: 1,
            explain: "Memakai harga hari ini membuat dana kurang saat waktunya tiba.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "psikologi-investasi-dan-bias",
    levelId: "investasi",
    order: 8,
    title: "Psikologi Investasi & Jebakan Bias",
    summary: "Mengenali bias mental yang membuat investor beli di puncak dan jual di dasar, lalu melawannya dengan rencana tertulis dan investasi rutin otomatis.",
    durationMin: 14,
    tags: ["investasi", "psikologi", "bias", "FOMO", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Musuh terbesar seorang investor sering kali bukan pasar, melainkan <strong>dirinya sendiri</strong>. Otak kita dirancang untuk bertahan hidup, bukan untuk berinvestasi, sehingga kita mudah panik saat harga turun dan serakah saat harga naik. Mengenali jebakan mental ini adalah setengah dari kemenangan.",
      },
      {
        type: "paragraph",
        html: "Return investor rata-rata sering lebih kecil daripada return produk yang ia beli. Penyebabnya bukan produknya, melainkan <strong>perilaku</strong>: masuk saat ramai, keluar saat takut. Disiplin mengalahkan kepintaran.",
      },
      {
        type: "video",
        comp: "PsikologiUangVideo",
        title: "Video: Psikologi Uang & Emosi Investor",
        caption: "Rasa takut dan serakah bergantian menyetir keputusan; rencana tertulis menjadi rem.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "FOMO: takut ketinggalan",
        html: "<strong>FOMO</strong> (fear of missing out) mendorong kita membeli aset yang sedang meroket karena semua orang membicarakannya. Akibatnya kita sering <strong>beli di puncak</strong>, tepat sebelum harga terkoreksi. Kalau alasan membeli hanya karena takut ketinggalan, itu tanda bahaya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Herding, loss aversion, dan recency bias",
        html: "<strong>Herding</strong>: ikut kerumunan tanpa berpikir. <strong>Loss aversion</strong>: rasa sakit rugi terasa sekitar dua kali lebih kuat daripada nikmat untung senilai sama, membuat kita terlalu takut rugi. <strong>Recency bias</strong>: menyangka tren terakhir akan berlanjut selamanya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lawan bias dengan sistem, bukan tekad",
        html: "Dua senjata ampuh: <strong>rencana tertulis</strong> (tujuan, alokasi, dan aturan kapan membeli/menjual) dan <strong>investasi rutin otomatis</strong> (autodebet tiap bulan). Sistem yang berjalan sendiri membuat emosi tidak sempat ikut campur.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Investor emosional vs investor disiplin (ilustrasi Rp juta)",
        unit: "Rp juta",
        source: "Ilustrasi edukatif",
        note: "Investor disiplin yang setor rutin menang jangka panjang; yang emosional beli di puncak dan jual di dasar.",
        data: [
          { label: "Tahun 1", value: 12 },
          { label: "Tahun 2", value: 20, color: "#22c55e" },
          { label: "Tahun 3", value: 35 },
          { label: "Tahun 4", value: 28, color: "#ef4444" },
          { label: "Tahun 5", value: 60, color: "#22c55e" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur alokasi aset yang sesuai dengan profil risikomu, lalu lihat bagaimana campuran itu mengubah potensi hasil dan gejolaknya.",
      },
      {
        type: "widget",
        widget: "SimulatorAlokasiAset",
      },
      {
        type: "classifyExercise",
        prompt: "Perilaku ini contoh bias yang mana?",
        buckets: ["FOMO / Herding", "Loss aversion / Panic selling", "Recency bias"],
        items: [
          { text: "Beli koin karena teman-teman ramai membelinya", bucket: "FOMO / Herding" },
          { text: "Menjual rugi saat pasar anjlok karena panik", bucket: "Loss aversion / Panic selling" },
          { text: "Menahan saham merugi terlalu lama demi menghindari rasa rugi", bucket: "Loss aversion / Panic selling" },
          { text: "Yakin harga akan terus naik karena naik 3 bulan terakhir", bucket: "Recency bias" },
          { text: "Ikut menjual karena semua orang menjual", bucket: "FOMO / Herding" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Kamu setor rutin Rp500 ribu per bulan selama 60 bulan lewat autodebet. Berapa total setoran pokoknya (dalam juta)?",
        answer: 30,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Total = 60 bulan x Rp500 ribu = <strong>Rp30 juta</strong>. Karena autodebet, kamu membeli di harga tinggi maupun rendah secara rata (dollar cost averaging), sehingga emosi tidak ikut menentukan.",
        hint: "Kalikan setoran bulanan dengan jumlah bulan, lalu ubah ke juta.",
      },
      {
        type: "case",
        title: "Studi Kasus: Budi terjebak FOMO",
        html: "Budi melihat sebuah aset naik tajam dan semua temannya untung. Karena takut ketinggalan, ia membeli Rp20 juta di harga puncak. Sebulan kemudian harga turun 40%, nilainya tinggal Rp12 juta. Panik, Budi menjual dan rugi <strong>Rp8 juta</strong>. Andai ia punya rencana tertulis dan setor rutin, ia tidak akan mempertaruhkan dana besar sekaligus di satu titik.",
      },
      {
        type: "case",
        title: "Sejarah: Tulip Mania di Belanda, 1637",
        html: "Pada masa <strong>1634 sampai 1637</strong>, harga umbi bunga <strong>tulip</strong> di Belanda melonjak gila-gilaan karena orang berlomba membeli demi menjual lebih mahal, bukan karena nilai bunganya. Sebagian umbi langka konon dihargai setara sebuah rumah. Pada Februari <strong>1637</strong> gelembung itu pecah dalam hitungan hari dan harga runtuh. Ini sering disebut gelembung spekulasi tercatat pertama, contoh klasik FOMO dan herding yang berulang sampai era kripto.",
      },
      {
        type: "takeaways",
        items: [
          "Musuh terbesar investor sering kali emosinya sendiri.",
          "FOMO dan herding membuat kita beli di puncak; panik membuat kita jual di dasar.",
          "Loss aversion membuat rasa rugi terasa sekitar dua kali lebih kuat daripada untung.",
          "Rencana tertulis dan investasi rutin otomatis meredam emosi.",
          "Gelembung spekulasi berulang sepanjang sejarah, dari tulip 1637 sampai kini.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "FOMO paling sering membuat investor melakukan apa?",
            options: [
              "Membeli di puncak karena takut ketinggalan",
              "Menabung dana darurat",
              "Membuat rencana tertulis",
              "Menunda pembelian",
            ],
            answer: 0,
            explain: "FOMO mendorong pembelian impulsif saat harga sudah tinggi.",
          },
          {
            q: "Loss aversion berarti...",
            options: [
              "Suka mengambil risiko besar",
              "Rasa sakit rugi terasa lebih kuat daripada nikmat untung senilai sama",
              "Tidak peduli pada kerugian",
              "Selalu untung",
            ],
            answer: 1,
            explain: "Rugi terasa sekitar dua kali lebih menyakitkan daripada untung senilai sama.",
          },
          {
            q: "Herding adalah kecenderungan untuk...",
            options: [
              "Berpikir mandiri",
              "Ikut kerumunan tanpa analisis sendiri",
              "Menghindari pasar",
              "Membaca laporan keuangan",
            ],
            answer: 1,
            explain: "Herding adalah mengikuti tindakan orang banyak begitu saja.",
          },
          {
            q: "Senjata paling ampuh melawan bias emosional adalah...",
            options: [
              "Menonton berita pasar tiap jam",
              "Rencana tertulis dan investasi rutin otomatis",
              "Mengandalkan firasat",
              "Menjual saat panik",
            ],
            answer: 1,
            explain: "Sistem otomatis membuat emosi tidak sempat ikut campur.",
          },
          {
            q: "Tulip mania yang gelembungnya pecah pada 1637 terjadi di negara mana?",
            options: ["Inggris", "Belanda", "Jepang", "Indonesia"],
            answer: 1,
            explain: "Tulip mania terjadi di Belanda dan pecah pada Februari 1637.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "investasi-properti-dan-emas",
    levelId: "investasi",
    order: 9,
    title: "Investasi Properti & Emas",
    summary: "Membandingkan properti dan emas sebagai aset riil: potensi, kelemahan likuiditas dan modal, arus kas, serta sudut pandang syariah.",
    durationMin: 14,
    tags: ["investasi", "properti", "emas", "syariah", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain saham dan reksa dana, banyak orang Indonesia menyukai <strong>aset riil</strong> yang bisa dipegang: <strong>properti</strong> dan <strong>emas</strong>. Keduanya punya daya tarik dan jebakan masing-masing. Memahami karakternya membantu kita menaruhnya di porsi yang tepat, bukan menjadikannya satu-satunya keranjang.",
      },
      {
        type: "paragraph",
        html: "Kunci memilih aset riil adalah jujur pada dua hal: seberapa cepat kita butuh dananya (<strong>likuiditas</strong>) dan apakah aset itu memberi <strong>arus kas</strong> atau hanya bertumpu pada kenaikan harga.",
      },
      {
        type: "video",
        comp: "PiramidaKeuanganVideo",
        title: "Video: Piramida Perencanaan Keuangan",
        caption: "Aset riil seperti properti dan emas berada di lapis investasi, di atas fondasi yang kokoh.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Properti: potensi besar, tapi berat",
        html: "<strong>Properti</strong> bisa memberi dua hasil: <strong>sewa</strong> (arus kas rutin) dan <strong>kenaikan harga</strong>. Kelemahannya: butuh <strong>modal besar</strong>, biaya perawatan dan pajak, serta <strong>likuiditas rendah</strong> karena menjual rumah bisa makan waktu berbulan-bulan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Emas: lindung nilai yang likuid",
        html: "<strong>Emas</strong> menjadi <strong>lindung nilai terhadap inflasi</strong> dan mudah dijual (<strong>likuid</strong>). Tetapi emas <strong>tidak memberi arus kas</strong>: ia tidak menghasilkan sewa atau bunga, hanya bergantung pada perubahan harga. Cocok sebagai penyeimbang, bukan mesin pertumbuhan utama.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Sudut pandang syariah",
        html: "Dalam Islam, jual beli <strong>emas</strong> harus <strong>tunai dan serah terima</strong> (tidak boleh tempo), karena emas tergolong barang ribawi. Untuk properti, tersedia <strong>KPR syariah</strong> dengan akad seperti murabahah (jual beli) atau musyarakah mutanaqishah (kepemilikan bertahap), tanpa bunga.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan sifat aset riil (skor ilustrasi 1-5)",
        unit: "skor",
        source: "Ilustrasi edukatif",
        note: "Emas unggul di likuiditas; properti unggul di potensi arus kas sewa. Keduanya saling melengkapi.",
        data: [
          { label: "Likuiditas emas", value: 5, color: "#eab308" },
          { label: "Likuiditas properti", value: 2, color: "#f97316" },
          { label: "Arus kas emas", value: 1, color: "#eab308" },
          { label: "Arus kas properti", value: 4, color: "#f97316" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Kalau membeli properti lewat KPR, hitung dulu cicilan bulanannya. Ubah harga rumah, uang muka, tenor, dan bunga untuk melihat dampaknya.",
      },
      {
        type: "widget",
        widget: "SimulatorKPR",
      },
      {
        type: "calcExercise",
        prompt: "Harga rumah Rp500 juta, uang muka (DP) 20%. Berapa nilai DP yang harus disiapkan (dalam juta)?",
        answer: 100,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "DP = 20% x Rp500 juta = <strong>Rp100 juta</strong>. Sisanya Rp400 juta yang dibiayai KPR. DP besar menekan cicilan dan total bunga.",
        hint: "Kalikan harga rumah dengan persentase DP.",
      },
      {
        type: "calcExercise",
        prompt: "Kamu beli emas 10 gram di harga Rp1 juta per gram. Tiga tahun kemudian harganya Rp1,3 juta per gram. Berapa keuntungan kotornya (dalam juta)?",
        answer: 3,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Nilai awal = 10 x Rp1 juta = Rp10 juta. Nilai akhir = 10 x Rp1,3 juta = Rp13 juta. Keuntungan kotor = Rp13 juta - Rp10 juta = <strong>Rp3 juta</strong>, belum dikurangi selisih harga beli-jual (spread).",
        hint: "Hitung nilai akhir dikurangi nilai awal.",
      },
      {
        type: "case",
        title: "Studi Kasus: Sari menyeimbangkan aset",
        html: "Sari punya Rp600 juta. Ia menaruh Rp400 juta di properti kontrakan yang menghasilkan sewa Rp30 juta per tahun (yield sekitar <strong>7,5%</strong>), dan Rp100 juta di emas sebagai dana darurat likuid, sisanya di reksa dana. Saat butuh dana cepat untuk biaya rumah sakit, ia menjual emas dalam sehari tanpa mengganggu kontrakan yang sulit dijual mendadak. Likuiditas emas menyelamatkannya.",
      },
      {
        type: "case",
        title: "Sejarah: Emas sebagai penyimpan nilai lintas zaman",
        html: "Sejak peradaban kuno seperti <strong>Mesir</strong> dan <strong>Lydia</strong> (yang mencetak koin emas sekitar <strong>600 SM</strong>), emas dipakai sebagai penyimpan nilai dan alat tukar karena langka, tahan lama, dan mudah dibagi. Standar emas mendominasi keuangan dunia hingga awal abad ke-20 dan baru sepenuhnya ditinggalkan pada <strong>1971</strong> saat AS menutup konvertibilitas dolar ke emas. Meski begitu, emas tetap bertahan sebagai lindung nilai favorit hingga hari ini, bukti daya tahannya melintasi ribuan tahun.",
      },
      {
        type: "takeaways",
        items: [
          "Properti memberi sewa dan kenaikan harga, tetapi butuh modal besar dan likuiditasnya rendah.",
          "Emas likuid dan menjadi lindung nilai inflasi, tetapi tidak memberi arus kas.",
          "Jual beli emas syariah harus tunai dan serah terima; properti bisa lewat KPR syariah tanpa bunga.",
          "Seimbangkan aset riil sesuai kebutuhan likuiditas dan tujuan.",
          "Emas terbukti menyimpan nilai lintas peradaban selama ribuan tahun.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kelemahan utama properti sebagai investasi adalah...",
            options: [
              "Terlalu likuid",
              "Butuh modal besar dan likuiditas rendah",
              "Tidak bisa disewakan",
              "Tidak pernah naik harga",
            ],
            answer: 1,
            explain: "Properti mahal dan lambat dijual, sehingga likuiditasnya rendah.",
          },
          {
            q: "Ciri khas emas dibanding properti adalah...",
            options: [
              "Memberi arus kas sewa",
              "Likuid tetapi tidak memberi arus kas",
              "Selalu naik harga tiap hari",
              "Butuh perawatan tinggi",
            ],
            answer: 1,
            explain: "Emas mudah dijual, tetapi tidak menghasilkan sewa atau bunga.",
          },
          {
            q: "Dalam syariah, jual beli emas harus dilakukan secara...",
            options: [
              "Tempo / cicilan",
              "Tunai dan serah terima",
              "Lewat kartu kredit",
              "Dengan bunga",
            ],
            answer: 1,
            explain: "Emas termasuk barang ribawi, sehingga transaksinya harus tunai dan serah terima.",
          },
          {
            q: "Emas paling tepat diposisikan sebagai...",
            options: [
              "Mesin pertumbuhan utama portofolio",
              "Penyeimbang dan lindung nilai yang likuid",
              "Sumber arus kas bulanan",
              "Pengganti dana pensiun sepenuhnya",
            ],
            answer: 1,
            explain: "Emas cocok sebagai penyeimbang dan lindung nilai, bukan mesin pertumbuhan.",
          },
          {
            q: "Standar emas dunia sepenuhnya ditinggalkan pada tahun...",
            options: ["1945", "1971", "1998", "2008"],
            answer: 1,
            explain: "Pada 1971 AS menutup konvertibilitas dolar ke emas (Nixon Shock).",
          },
        ],
      },
    ],
  },
];
