import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "membangun-dana-darurat",
    levelId: "aruskas",
    order: 1,
    title: "Membangun Dana Darurat",
    summary: "Mengapa dana darurat adalah fondasi keuangan, berapa besarnya, dan di mana sebaiknya disimpan.",
    durationMin: 12,
    tags: ["dana darurat", "arus kas", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum berpikir investasi, ada satu hal yang wajib dibereskan lebih dulu: <strong>dana darurat</strong>. Ini adalah tabungan khusus untuk keadaan mendesak, seperti kehilangan pekerjaan, sakit, atau kendaraan rusak. Dana darurat menahan agar satu musibah tidak menghancurkan seluruh rencana keuanganmu.",
      },
      {
        type: "video",
        comp: "DanaDaruratVideo",
        title: "Video: Dana Darurat, Bantalan Hidup",
        caption: "Menyerap guncangan agar kamu tidak perlu berutang atau menjual investasi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Berapa besarnya?",
        html: "Ukurannya dalam kelipatan <strong>pengeluaran bulanan</strong>, bukan penghasilan. Panduan umum: lajang <strong>3 sampai 6 bulan</strong>, keluarga dengan anak <strong>6 sampai 12 bulan</strong>. Makin banyak tanggungan dan makin tidak tetap penghasilan, makin besar targetnya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Di mana disimpan?",
        html: "Dana darurat harus <strong>mudah dicairkan</strong> tetapi tidak tergoda dipakai. Cocoknya di tabungan terpisah, deposito jangka pendek, atau <strong>reksa dana pasar uang</strong>. Jangan diinvestasikan di saham yang harganya bisa turun saat kamu butuh.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung target dana daruratmu sesuai pengeluaran dan kondisi keluarga, lalu lihat seberapa jauh progresnya.",
      },
      { type: "widget", widget: "KalkulatorDanaDarurat" },
      {
        type: "chart",
        variant: "bar",
        title: "Target Dana Darurat menurut Kondisi (pengeluaran Rp4 juta/bulan)",
        unit: "Rp juta",
        source: "ilustrasi panduan umum dana darurat",
        note: "Makin banyak tanggungan, makin besar bantalan yang dibutuhkan untuk rasa aman.",
        data: [
          { label: "Lajang (4 bln)", value: 16, color: "#34d399" },
          { label: "Menikah (6 bln)", value: 24, color: "#10b981" },
          { label: "Keluarga (9 bln)", value: 36, color: "#0ea5e9" },
          { label: "Freelance (12 bln)", value: 48, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Ada dan tidak ada dana darurat",
        html: "Dua karyawan sama-sama terkena PHK. Sari punya dana darurat <strong>6 bulan pengeluaran</strong>, jadi ia tenang mencari kerja baru tanpa panik. Rian tidak punya, sehingga terpaksa berutang lewat pinjol berbunga tinggi untuk bertahan, dan masalahnya menumpuk. Dana darurat mengubah krisis menjadi sekadar masa transisi.",
      },
      {
        type: "calcExercise",
        prompt: "Pengeluaran wajib Rp4 juta per bulan. Berapa target dana darurat untuk keluarga (9 bulan) dalam juta?",
        answer: 36,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Target = 9 x Rp4 juta = <strong>Rp36 juta</strong>.",
        hint: "Kalikan pengeluaran bulanan dengan jumlah bulan.",
      },
      {
        type: "classifyExercise",
        prompt: "Tempat ini cocok atau tidak untuk menyimpan dana darurat?",
        buckets: ["Cocok", "Tidak cocok"],
        items: [
          { text: "Tabungan terpisah yang mudah dicairkan", bucket: "Cocok" },
          { text: "Reksa dana pasar uang", bucket: "Cocok" },
          { text: "Saham yang harganya fluktuatif", bucket: "Tidak cocok" },
          { text: "Aset kripto yang bergejolak", bucket: "Tidak cocok" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Krisis Moneter 1998",
        html: "Saat <strong>krisis moneter 1997-1998</strong>, banyak orang kehilangan pekerjaan saat harga-harga melonjak. Mereka yang punya simpanan darurat mampu bertahan melewati masa sulit, sementara yang tidak terpaksa menjual aset murah atau menumpuk utang. Pelajaran itu tetap relevan: dana darurat adalah pertahanan pertama menghadapi guncangan ekonomi yang tak terduga.",
      },
      {
        type: "takeaways",
        items: [
          "Dana darurat adalah fondasi sebelum investasi.",
          "Besarnya diukur dari pengeluaran bulanan, bukan penghasilan.",
          "Lajang 3-6 bulan, keluarga 6-12 bulan pengeluaran.",
          "Simpan di tempat mudah dicairkan dan tidak fluktuatif.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dana darurat sebaiknya diukur dari?",
            options: ["Penghasilan bulanan", "Pengeluaran bulanan", "Harga rumah", "Jumlah teman"],
            answer: 1,
            explain: "Ukurannya kelipatan pengeluaran bulanan agar cukup menutup biaya hidup.",
          },
          {
            q: "Berapa dana darurat yang umum disarankan untuk keluarga dengan anak?",
            options: ["1 bulan", "6 sampai 12 bulan pengeluaran", "50 tahun", "Tidak perlu"],
            answer: 1,
            explain: "Keluarga dengan tanggungan disarankan 6 sampai 12 bulan pengeluaran.",
          },
          {
            q: "Tempat yang TIDAK cocok untuk dana darurat adalah?",
            options: ["Tabungan", "Reksa dana pasar uang", "Saham fluktuatif", "Deposito jangka pendek"],
            answer: 2,
            explain: "Saham bisa turun saat kamu butuh dana, jadi tidak cocok untuk darurat.",
          },
          {
            q: "Pengeluaran Rp5 juta/bulan, target lajang 4 bulan. Dana daruratnya?",
            options: ["Rp20 juta", "Rp5 juta", "Rp40 juta", "Rp10 juta"],
            answer: 0,
            explain: "4 x Rp5 juta = Rp20 juta.",
          },
          {
            q: "Manfaat utama dana darurat adalah?",
            options: [
              "Membuat kaya cepat",
              "Menahan agar musibah tidak menghancurkan rencana keuangan",
              "Menghindari pajak",
              "Menaikkan gaji",
            ],
            answer: 1,
            explain: "Dana darurat menyerap guncangan sehingga rencana tetap utuh.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "mengelola-arus-kas",
    levelId: "aruskas",
    order: 2,
    title: "Mengelola Arus Kas & Menutup Kebocoran",
    summary: "Mencatat pemasukan dan pengeluaran, mengenali bocor halus, serta memahami selisih surplus dan defisit.",
    durationMin: 13,
    tags: ["arus kas", "anggaran", "pemula"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Arus kas</strong> adalah aliran uang yang masuk dan keluar dari kantongmu setiap bulan. Uang masuk disebut <strong>pemasukan</strong>, uang keluar disebut <strong>pengeluaran</strong>. Selama pemasukan lebih besar daripada pengeluaran, kamu punya <strong>surplus</strong> yang bisa ditabung. Jika sebaliknya, kamu mengalami <strong>defisit</strong> dan mulai menggerus tabungan atau berutang.",
      },
      {
        type: "paragraph",
        html: "Langkah pertama mengatur uang bukan berhemat besar-besaran, melainkan <strong>mencatat</strong>. Kalau tidak dicatat, kita sering tidak sadar ke mana uang pergi. Catatan sederhana selama satu bulan sudah cukup untuk membuka mata.",
      },
      {
        type: "video",
        comp: "DanaDaruratVideo",
        title: "Video: Ke Mana Uang Pergi?",
        caption: "Mencatat arus kas membuat kebocoran kecil menjadi terlihat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Surplus vs defisit",
        html: "Rumus intinya sederhana: <strong>Surplus = Pemasukan - Pengeluaran</strong>. Kalau hasilnya positif, kamu bisa menabung. Kalau negatif, ada yang harus dibenahi sebelum uangmu habis.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bocor halus (latte factor)",
        html: "<strong>Bocor halus</strong> adalah pengeluaran kecil yang tampak sepele tetapi menumpuk besar dalam setahun. Contohnya kopi kekinian Rp25 ribu tiap hari kerja. Terlihat kecil, padahal setahun bisa lebih dari Rp6 juta.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan pemasukan dan pos-pos pengeluaranmu untuk melihat berapa surplus yang tersisa tiap bulan.",
      },
      { type: "widget", widget: "KalkulatorAnggaran" },
      {
        type: "chart",
        variant: "bar",
        title: "Bocor Halus Kopi Harian dalam Setahun",
        unit: "Rp ribu",
        source: "ilustrasi: Rp25 ribu x 22 hari kerja x 12 bulan",
        note: "Pengeluaran kecil harian menumpuk menjadi jutaan rupiah dalam setahun.",
        data: [
          { label: "Per hari", value: 25, color: "#94a3b8" },
          { label: "Per bulan", value: 550, color: "#f59e0b" },
          { label: "Per tahun", value: 6600, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menemukan surplus tanpa terasa",
        html: "Dina berpenghasilan Rp5 juta dan merasa uangnya selalu habis. Setelah mencatat sebulan, ia menemukan bocor halus: kopi harian, langganan aplikasi yang jarang dipakai, dan ongkos kirim jajan online. Total bocornya sekitar Rp900 ribu. Dengan menutup sebagian saja, Dina kini surplus <strong>Rp600 ribu</strong> per bulan tanpa merasa hidupnya lebih susah.",
      },
      {
        type: "case",
        title: "Sejarah: Budaya mencatat keuangan rumah tangga",
        html: "Mencatat uang bukan hal baru. Di Jepang sejak tahun <strong>1904</strong>, jurnalis Hani Motoko memperkenalkan buku catatan rumah tangga <strong>kakeibo</strong> yang membantu keluarga menata belanja harian. Di Indonesia, kebiasaan mencatat lewat buku warung, buku kas, hingga aplikasi keuangan meneruskan semangat yang sama: yang dicatat lebih mudah dikendalikan.",
      },
      {
        type: "calcExercise",
        prompt: "Pemasukan Rp6 juta, total pengeluaran Rp4,5 juta. Berapa surplus bulanan dalam juta rupiah?",
        answer: 1.5,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Surplus = Rp6 juta - Rp4,5 juta = <strong>Rp1,5 juta</strong>.",
        hint: "Kurangi pengeluaran dari pemasukan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi arus kas ini surplus atau defisit?",
        buckets: ["Surplus", "Defisit"],
        items: [
          { text: "Pemasukan Rp5 juta, pengeluaran Rp4 juta", bucket: "Surplus" },
          { text: "Pemasukan Rp3 juta, pengeluaran Rp3,8 juta", bucket: "Defisit" },
          { text: "Pemasukan Rp8 juta, pengeluaran Rp6 juta", bucket: "Surplus" },
          { text: "Pemasukan Rp4 juta, pengeluaran Rp4,5 juta", bucket: "Defisit" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Arus kas adalah aliran uang masuk dan keluar tiap bulan.",
          "Surplus = pemasukan dikurangi pengeluaran; usahakan selalu positif.",
          "Mencatat sebulan membuka mata ke mana uang pergi.",
          "Bocor halus kecil bisa menumpuk jutaan rupiah dalam setahun.",
          "Menutup kebocoran sering lebih mudah daripada menambah penghasilan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Surplus keuangan terjadi ketika?",
            options: ["Pengeluaran lebih besar dari pemasukan", "Pemasukan lebih besar dari pengeluaran", "Pemasukan sama dengan utang", "Tabungan habis"],
            answer: 1,
            explain: "Surplus muncul saat pemasukan melebihi pengeluaran sehingga ada sisa untuk ditabung.",
          },
          {
            q: "Apa yang dimaksud bocor halus (latte factor)?",
            options: ["Utang besar sekali bayar", "Pengeluaran kecil yang menumpuk besar dalam setahun", "Pajak penghasilan", "Bonus tahunan"],
            answer: 1,
            explain: "Bocor halus adalah pengeluaran kecil rutin yang totalnya besar dalam setahun.",
          },
          {
            q: "Langkah pertama mengatur uang sebaiknya?",
            options: ["Langsung investasi saham", "Berhenti makan", "Mencatat pemasukan dan pengeluaran", "Berutang dulu"],
            answer: 2,
            explain: "Mencatat membuat kita sadar ke mana uang pergi sebelum mengambil keputusan.",
          },
          {
            q: "Pemasukan Rp7 juta, pengeluaran Rp5 juta. Surplusnya?",
            options: ["Rp2 juta", "Rp12 juta", "Rp5 juta", "Rp0"],
            answer: 0,
            explain: "Rp7 juta - Rp5 juta = Rp2 juta.",
          },
          {
            q: "Jika pengeluaran melebihi pemasukan, itu disebut?",
            options: ["Surplus", "Defisit", "Bonus", "Deposito"],
            answer: 1,
            explain: "Defisit terjadi saat pengeluaran lebih besar daripada pemasukan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "menabung-otomatis",
    levelId: "aruskas",
    order: 3,
    title: "Menabung Otomatis: Bayar Diri Sendiri Dulu",
    summary: "Prinsip pay yourself first dan autodebet menabung di awal bulan sebelum uang habis untuk belanja.",
    durationMin: 13,
    tags: ["menabung", "autodebet", "kebiasaan"],
    blocks: [
      {
        type: "paragraph",
        html: "Banyak orang menabung dengan pola: belanja dulu, sisanya baru ditabung. Masalahnya, uang sering habis sebelum sempat disisihkan. Solusinya adalah membalik urutan: <strong>bayar diri sendiri dulu</strong> (<em>pay yourself first</em>). Begitu gaji masuk, sisihkan tabungan lebih dulu, baru sisanya dipakai belanja.",
      },
      {
        type: "paragraph",
        html: "Agar tidak lupa dan tidak tergoda, gunakan <strong>autodebet</strong>: bank memindahkan sejumlah uang secara otomatis ke rekening tabungan atau <strong>reksa dana</strong> tiap awal bulan. Menabung jadi berjalan sendiri tanpa mengandalkan niat harian.",
      },
      {
        type: "video",
        comp: "SiklusHidupKeuanganVideo",
        title: "Video: Bayar Diri Sendiri Dulu",
        caption: "Menyisihkan tabungan di depan membuat kebiasaan menabung tahan godaan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Balik urutannya",
        html: "Pola lama: <strong>Penghasilan - Pengeluaran = Tabungan</strong> (sering nol). Pola baru: <strong>Penghasilan - Tabungan = Pengeluaran</strong>. Tabungan dikunci lebih dulu, sisanya baru dibelanjakan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Mulai dari kecil",
        html: "Tidak harus besar. Mulai <strong>10 persen</strong> dari penghasilan, lalu naikkan sedikit tiap kali gaji naik. Yang penting rutin dan otomatis, bukan besar tapi bolong-bolong.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kenapa otomatis penting?",
        html: "Menabung manual mengandalkan disiplin harian yang mudah goyah. Autodebet mengubah menabung menjadi <strong>kebiasaan tanpa keputusan</strong>, sehingga tetap jalan walau kamu sedang sibuk atau lupa.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana setoran rutin kecil tumbuh besar berkat bunga majemuk bila dilakukan konsisten bertahun-tahun.",
      },
      { type: "widget", widget: "SimulatorBungaMajemuk" },
      {
        type: "chart",
        variant: "line",
        title: "Menabung Rutin Rp500 ribu/bulan (asumsi imbal hasil 6 persen/tahun)",
        unit: "Rp juta",
        source: "ilustrasi edukatif pertumbuhan setoran rutin",
        note: "Setoran kecil yang otomatis dan konsisten tumbuh jauh lebih besar dari total setoran karena bunga majemuk.",
        data: [
          { label: "Tahun 1", value: 6.2, color: "#34d399" },
          { label: "Tahun 3", value: 19.7, color: "#10b981" },
          { label: "Tahun 5", value: 34.9, color: "#0ea5e9" },
          { label: "Tahun 10", value: 81.9, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Autodebet mengubah kebiasaan Rangga",
        html: "Rangga selalu gagal menabung karena selalu ada saja pengeluaran. Ia lalu mengatur <strong>autodebet Rp700 ribu</strong> ke reksa dana tiap tanggal gajian. Karena uangnya sudah 'hilang' otomatis di awal, ia menyesuaikan gaya hidup dengan sisanya. Setelah setahun, tabungannya mencapai lebih dari <strong>Rp8,4 juta</strong> tanpa terasa berat.",
      },
      {
        type: "case",
        title: "Sejarah: Autodebet dan tabungan berjangka bank",
        html: "Bank di Indonesia sejak lama menawarkan <strong>tabungan berjangka</strong> dengan setoran otomatis, misalnya Tahapan Berjangka dan produk sejenis yang populer sejak awal tahun <strong>2000-an</strong>. Nasabah menetapkan setoran bulanan dan tenor, lalu dana ditarik otomatis dari rekening utama. Fitur autodebet inilah yang membuat prinsip bayar diri sendiri dulu mudah dijalankan siapa saja.",
      },
      {
        type: "calcExercise",
        prompt: "Penghasilan Rp6 juta. Jika kamu menerapkan bayar diri sendiri 15 persen, berapa yang disisihkan tiap bulan (dalam ribu rupiah)?",
        answer: 900,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "15 persen x Rp6 juta = 0,15 x 6.000.000 = <strong>Rp900 ribu</strong>.",
        hint: "Kalikan penghasilan dengan 0,15.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "Pay yourself first", right: "Menyisihkan tabungan lebih dulu sebelum belanja" },
          { left: "Autodebet", right: "Pemindahan dana otomatis oleh bank tiap periode" },
          { left: "Tabungan berjangka", right: "Setoran rutin dengan tenor tertentu" },
          { left: "Reksa dana", right: "Wadah investasi kumpulan dana yang dikelola manajer" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Bayar diri sendiri dulu: sisihkan tabungan sebelum belanja.",
          "Balik rumusnya jadi Penghasilan - Tabungan = Pengeluaran.",
          "Autodebet membuat menabung otomatis dan tahan godaan.",
          "Mulai dari 10 persen, naikkan saat penghasilan bertambah.",
          "Konsisten lebih penting daripada nominal besar sesekali.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Prinsip pay yourself first berarti?",
            options: ["Belanja dulu, sisanya ditabung", "Menyisihkan tabungan dulu sebelum belanja", "Membayar utang orang lain", "Menghabiskan gaji di awal"],
            answer: 1,
            explain: "Tabungan disisihkan lebih dulu sebelum uang terpakai untuk belanja.",
          },
          {
            q: "Fungsi autodebet dalam menabung adalah?",
            options: ["Menaikkan gaji", "Memindahkan dana ke tabungan secara otomatis", "Menghapus utang", "Menambah pengeluaran"],
            answer: 1,
            explain: "Autodebet memindahkan dana otomatis sehingga menabung tidak bergantung ingatan.",
          },
          {
            q: "Rumus menabung yang disarankan adalah?",
            options: ["Penghasilan - Pengeluaran = Tabungan", "Penghasilan - Tabungan = Pengeluaran", "Tabungan - Utang = Penghasilan", "Pengeluaran + Utang"],
            answer: 1,
            explain: "Dengan menabung dulu, sisanya menjadi batas belanja.",
          },
          {
            q: "Penghasilan Rp5 juta, disisihkan 10 persen. Berapa tabungannya?",
            options: ["Rp500 ribu", "Rp50 ribu", "Rp1 juta", "Rp5 juta"],
            answer: 0,
            explain: "10 persen x Rp5 juta = Rp500 ribu.",
          },
          {
            q: "Mengapa menabung otomatis lebih efektif?",
            options: ["Karena bunganya lebih tinggi selalu", "Karena tidak bergantung pada disiplin harian", "Karena bebas pajak", "Karena tanpa risiko sama sekali"],
            answer: 1,
            explain: "Otomatisasi menghilangkan godaan dan lupa, sehingga kebiasaan tetap jalan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sinking-fund",
    levelId: "aruskas",
    order: 4,
    title: "Sinking Fund untuk Tujuan Spesifik",
    summary: "Menabung khusus untuk pengeluaran besar yang bisa diprediksi agar tidak kaget saat waktunya tiba.",
    durationMin: 13,
    tags: ["sinking fund", "menabung", "perencanaan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Sinking fund</strong> adalah dana yang dikumpulkan sedikit demi sedikit untuk pengeluaran besar yang <strong>sudah bisa diprediksi</strong>. Berbeda dengan dana darurat yang untuk kejadian tak terduga, sinking fund justru untuk hal yang pasti datang: THR karyawan, pajak kendaraan tahunan, liburan, kurban, atau biaya masuk sekolah.",
      },
      {
        type: "paragraph",
        html: "Idenya sederhana: daripada kaget membayar Rp2,4 juta sekaligus untuk pajak mobil, kamu menyisihkan <strong>Rp200 ribu tiap bulan</strong> selama setahun. Saat tagihan datang, uangnya sudah siap dan arus kas tidak terguncang.",
      },
      {
        type: "video",
        comp: "DanaDaruratVideo",
        title: "Video: Menyiapkan Pengeluaran Besar",
        caption: "Memecah biaya besar menjadi setoran kecil bulanan agar tidak kaget.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus sisihan bulanan",
        html: "<strong>Sisihan per bulan = Total kebutuhan / Jumlah bulan tersisa</strong>. Contoh: kurban Rp3,6 juta yang jatuh 12 bulan lagi berarti menyisihkan Rp300 ribu per bulan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Beda dengan dana darurat",
        html: "Dana darurat untuk kejadian <strong>tak terduga</strong> (PHK, sakit). Sinking fund untuk kejadian <strong>terduga</strong> (pajak tahunan, Lebaran, liburan). Keduanya penting dan sebaiknya dipisah rekeningnya agar tidak tercampur.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Tentukan target dan tenggat sinking fund-mu, lalu lihat berapa yang perlu disisihkan tiap bulan.",
      },
      { type: "widget", widget: "KalkulatorDanaDarurat" },
      {
        type: "chart",
        variant: "bar",
        title: "Sisihan Bulanan untuk Beberapa Tujuan (tenor 12 bulan)",
        unit: "Rp ribu",
        source: "ilustrasi: total kebutuhan dibagi 12 bulan",
        note: "Biaya besar terasa ringan bila dipecah menjadi setoran bulanan yang teratur.",
        data: [
          { label: "Pajak motor (Rp600rb)", value: 50, color: "#34d399" },
          { label: "Liburan (Rp3,6jt)", value: 300, color: "#0ea5e9" },
          { label: "Kurban (Rp3,6jt)", value: 300, color: "#10b981" },
          { label: "Pajak mobil (Rp2,4jt)", value: 200, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Lebaran tanpa panik",
        html: "Bu Wati tiap tahun kelabakan saat Lebaran karena butuh dana besar untuk mudik, THR asisten, dan hidangan. Tahun ini ia membuat sinking fund <strong>Rp500 ribu per bulan</strong> mulai sepuluh bulan sebelum Lebaran. Ketika hari raya tiba, ia sudah punya <strong>Rp5 juta</strong> siap pakai dan tidak perlu berutang atau menjual barang.",
      },
      {
        type: "case",
        title: "Sejarah: Tabungan Lebaran dan arisan",
        html: "Budaya menyiapkan dana untuk momen besar sudah lama hidup di Indonesia lewat <strong>arisan</strong> dan <strong>tabungan Lebaran</strong>. Sejak dulu warga menyisihkan uang bersama tetangga atau lewat kelompok pengajian, lalu dicairkan menjelang hari raya. Bank dan koperasi kemudian mengemasnya menjadi produk tabungan hari raya. Semangatnya sama dengan sinking fund modern: menabung terarah untuk kebutuhan yang sudah pasti datang.",
      },
      {
        type: "calcExercise",
        prompt: "Pajak mobil tahunan Rp2,4 juta jatuh 12 bulan lagi. Berapa sisihan per bulan (dalam ribu rupiah)?",
        answer: 200,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "Rp2,4 juta / 12 bulan = Rp2.400.000 / 12 = <strong>Rp200 ribu</strong> per bulan.",
        hint: "Bagi total kebutuhan dengan jumlah bulan tersisa.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebutuhan ini sebaiknya dibiayai dari dana darurat atau sinking fund?",
        buckets: ["Dana darurat", "Sinking fund"],
        items: [
          { text: "Pajak kendaraan tahunan", bucket: "Sinking fund" },
          { text: "Kehilangan pekerjaan mendadak", bucket: "Dana darurat" },
          { text: "Biaya kurban Iduladha", bucket: "Sinking fund" },
          { text: "Rawat inap darurat tak terduga", bucket: "Dana darurat" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Sinking fund untuk pengeluaran besar yang bisa diprediksi.",
          "Sisihan bulanan = total kebutuhan dibagi jumlah bulan tersisa.",
          "Berbeda dari dana darurat yang untuk kejadian tak terduga.",
          "Memecah biaya besar jadi setoran kecil menjaga arus kas tetap tenang.",
          "Pisahkan rekening tiap tujuan agar tidak tercampur.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Sinking fund paling tepat digunakan untuk?",
            options: ["Kehilangan pekerjaan mendadak", "Pengeluaran besar yang bisa diprediksi", "Menutup utang pinjol", "Belanja impulsif"],
            answer: 1,
            explain: "Sinking fund menyiapkan dana untuk kebutuhan besar yang sudah pasti datang.",
          },
          {
            q: "Apa beda utama sinking fund dan dana darurat?",
            options: ["Tidak ada bedanya", "Sinking fund untuk terduga, dana darurat untuk tak terduga", "Sinking fund hanya untuk orang kaya", "Dana darurat untuk liburan"],
            answer: 1,
            explain: "Sinking fund untuk kejadian terduga, dana darurat untuk yang tak terduga.",
          },
          {
            q: "Kebutuhan Rp6 juta jatuh 12 bulan lagi. Sisihan per bulan?",
            options: ["Rp500 ribu", "Rp6 juta", "Rp50 ribu", "Rp1 juta"],
            answer: 0,
            explain: "Rp6 juta / 12 = Rp500 ribu per bulan.",
          },
          {
            q: "Manfaat memecah biaya besar menjadi setoran bulanan?",
            options: ["Arus kas tidak terguncang saat tagihan datang", "Membuat biaya jadi lebih mahal", "Menaikkan pajak", "Menghapus kebutuhan"],
            answer: 0,
            explain: "Dengan menabung bertahap, saat tagihan tiba dananya sudah siap.",
          },
          {
            q: "Contoh tujuan yang cocok dibiayai sinking fund?",
            options: ["Rawat inap darurat", "Pajak kendaraan tahunan", "PHK mendadak", "Kecelakaan tak terduga"],
            answer: 1,
            explain: "Pajak tahunan sudah bisa diprediksi, jadi cocok untuk sinking fund.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "produk-simpanan",
    levelId: "aruskas",
    order: 5,
    title: "Mengenal Produk Simpanan",
    summary: "Tabungan, deposito, dan reksa dana pasar uang: menimbang likuiditas, imbal hasil, serta penjaminan LPS.",
    durationMin: 14,
    tags: ["deposito", "tabungan", "LPS"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah punya uang lebih, muncul pertanyaan: disimpan di mana? Ada tiga produk simpanan yang aman dan populer untuk pemula: <strong>tabungan biasa</strong>, <strong>deposito</strong>, dan <strong>reksa dana pasar uang</strong>. Ketiganya berbeda dalam dua hal utama: <strong>likuiditas</strong> (kemudahan dicairkan) dan <strong>imbal hasil</strong> (bunga atau keuntungan).",
      },
      {
        type: "paragraph",
        html: "Aturan mainnya: makin mudah dicairkan, biasanya makin kecil imbal hasilnya. Tabungan paling likuid tetapi bunganya kecil. Deposito memberi bunga lebih besar tetapi uang terkunci selama jangka waktu tertentu.",
      },
      {
        type: "video",
        comp: "DanaDaruratVideo",
        title: "Video: Memilih Tempat Menyimpan Uang",
        caption: "Menimbang antara mudah dicairkan dan imbal hasil yang didapat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Likuiditas vs imbal hasil",
        html: "Ini pertukaran (<em>trade-off</em>) klasik. <strong>Tabungan</strong>: sangat likuid, bunga kecil. <strong>Deposito</strong>: terkunci 1 sampai 12 bulan, bunga lebih besar. <strong>Reksa dana pasar uang</strong>: cukup likuid (cair 1 sampai 2 hari kerja), imbal hasil biasanya di atas tabungan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Penjaminan LPS",
        html: "Simpanan di bank dijamin <strong>Lembaga Penjamin Simpanan (LPS)</strong> hingga <strong>Rp2 miliar per nasabah per bank</strong>, dengan syarat memenuhi ketentuan (antara lain suku bunga tidak melebihi batas penjaminan LPS). Reksa dana bukan produk bank, jadi tidak dijamin LPS, tetapi diawasi OJK.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung perkiraan hasil deposito dari nominal, tenor, dan suku bunga yang kamu masukkan.",
      },
      { type: "widget", widget: "KalkulatorDeposito" },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Produk Simpanan (ilustrasi imbal hasil per tahun)",
        unit: "persen/tahun",
        source: "ilustrasi edukatif kisaran umum, bukan angka pasti",
        note: "Makin tinggi imbal hasil, biasanya likuiditas makin rendah atau ada syarat penguncian dana.",
        data: [
          { label: "Tabungan", value: 1, color: "#94a3b8" },
          { label: "Reksa dana pasar uang", value: 4, color: "#0ea5e9" },
          { label: "Deposito", value: 5, color: "#10b981" },
        ],
      },
      {
        type: "table",
        headers: ["Produk", "Likuiditas", "Imbal hasil", "Penjaminan"],
        rows: [
          ["Tabungan", "Sangat tinggi", "Kecil", "LPS"],
          ["Deposito", "Terkunci tenor", "Lebih besar", "LPS"],
          ["Reksa dana pasar uang", "Cair 1-2 hari", "Menengah", "Diawasi OJK"],
        ],
        caption: "Tiga produk simpanan dan karakteristiknya.",
      },
      {
        type: "case",
        title: "Studi Kasus: Menempatkan uang sesuai kebutuhan",
        html: "Pak Yoga punya Rp30 juta. Ia menaruh <strong>Rp10 juta</strong> di tabungan untuk kebutuhan sehari-hari, <strong>Rp10 juta</strong> di reksa dana pasar uang sebagai dana darurat yang tetap tumbuh, dan <strong>Rp10 juta</strong> di deposito 6 bulan yang belum akan dipakai. Dengan begitu ia mendapat keseimbangan antara akses cepat dan imbal hasil yang lebih baik.",
      },
      {
        type: "case",
        title: "Sejarah: Pembentukan LPS 2005 pasca krisis 1998",
        html: "Saat <strong>krisis 1998</strong>, kepercayaan pada bank runtuh dan pemerintah memberi jaminan menyeluruh (blanket guarantee) yang membebani anggaran. Untuk sistem yang lebih tertata, dibentuklah <strong>Lembaga Penjamin Simpanan (LPS)</strong> lewat undang-undang tahun <strong>2004</strong> yang mulai beroperasi tahun <strong>2005</strong>. Sejak itu simpanan nasabah dijamin sampai batas tertentu, sehingga masyarakat lebih tenang menyimpan uang di bank.",
      },
      {
        type: "calcExercise",
        prompt: "Deposito Rp20 juta, bunga 5 persen per tahun. Berapa bunga kotor setahun (dalam ribu rupiah, abaikan pajak)?",
        answer: 1000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "5 persen x Rp20 juta = 0,05 x 20.000.000 = Rp1.000.000 = <strong>Rp1.000 ribu</strong> setahun.",
        hint: "Kalikan nominal dengan suku bunga 0,05.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan produk dengan ciri utamanya.",
        pairs: [
          { left: "Tabungan biasa", right: "Paling mudah dicairkan, bunga kecil" },
          { left: "Deposito", right: "Terkunci tenor, bunga lebih besar" },
          { left: "Reksa dana pasar uang", right: "Diawasi OJK, cair 1-2 hari kerja" },
          { left: "LPS", right: "Menjamin simpanan bank sampai batas tertentu" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Tiga produk simpanan populer: tabungan, deposito, reksa dana pasar uang.",
          "Likuiditas dan imbal hasil saling bertukar: yang gampang cair, bunganya kecil.",
          "Deposito mengunci dana selama tenor demi bunga lebih besar.",
          "LPS menjamin simpanan bank hingga Rp2 miliar per nasabah per bank.",
          "Reksa dana bukan produk bank; diawasi OJK, tidak dijamin LPS.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Produk simpanan yang paling mudah dicairkan adalah?",
            options: ["Deposito 12 bulan", "Tabungan biasa", "Properti", "Emas batangan"],
            answer: 1,
            explain: "Tabungan biasa paling likuid meski bunganya kecil.",
          },
          {
            q: "Ciri khas deposito adalah?",
            options: ["Bisa dicairkan kapan saja tanpa syarat", "Dana terkunci selama tenor dengan bunga lebih besar", "Tanpa bunga", "Tidak dijamin sama sekali"],
            answer: 1,
            explain: "Deposito mengunci dana selama jangka waktu tertentu untuk bunga lebih tinggi.",
          },
          {
            q: "LPS menjamin simpanan bank hingga?",
            options: ["Rp10 juta per nasabah", "Rp2 miliar per nasabah per bank", "Tak terbatas", "Rp100 ribu"],
            answer: 1,
            explain: "Batas penjaminan LPS adalah Rp2 miliar per nasabah per bank.",
          },
          {
            q: "Deposito Rp10 juta bunga 6 persen setahun. Bunga kotornya?",
            options: ["Rp600 ribu", "Rp60 ribu", "Rp6 juta", "Rp16 juta"],
            answer: 0,
            explain: "6 persen x Rp10 juta = Rp600 ribu.",
          },
          {
            q: "Reksa dana pasar uang diawasi oleh?",
            options: ["LPS", "OJK", "Dukcapil", "Bea Cukai"],
            answer: 1,
            explain: "Reksa dana adalah produk pasar modal yang diawasi OJK, bukan dijamin LPS.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "inflasi-dan-daya-beli",
    levelId: "aruskas",
    order: 6,
    title: "Inflasi & Menjaga Daya Beli",
    summary: "Bagaimana inflasi menggerus nilai uang dan mengapa menabung di bawah inflasi membuat uang menyusut secara riil.",
    durationMin: 14,
    tags: ["inflasi", "daya beli", "nilai riil"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Inflasi</strong> adalah kenaikan harga barang dan jasa secara umum dari waktu ke waktu. Akibatnya, uang yang jumlahnya sama membeli barang lebih sedikit tahun depan. Inilah yang disebut menurunnya <strong>daya beli</strong>. Uang Rp100 ribu hari ini tidak akan sekuat Rp100 ribu sepuluh tahun lagi.",
      },
      {
        type: "paragraph",
        html: "Kalau kamu menabung dengan bunga <strong>di bawah</strong> inflasi, secara nominal uangmu bertambah, tetapi secara <strong>riil</strong> (dari sisi barang yang bisa dibeli) justru menyusut. Karena itu, uang yang tidak akan dipakai dalam waktu lama perlu ditaruh di instrumen yang imbal hasilnya mampu mengalahkan inflasi.",
      },
      {
        type: "video",
        comp: "InflasiVideo",
        title: "Video: Diam-diam Uang Menyusut",
        caption: "Inflasi menggerus daya beli walau angka di rekening tidak berkurang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Nilai riil",
        html: "Kasarnya: <strong>Imbal hasil riil = Imbal hasil nominal - Inflasi</strong>. Jika tabungan memberi 2 persen sementara inflasi 4 persen, imbal hasil riilmu sekitar <strong>minus 2 persen</strong>. Uangmu bertambah di angka, tetapi kalah oleh harga.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bahaya menabung saja",
        html: "Menyimpan seluruh uang di bawah bantal atau tabungan berbunga kecil terasa aman, tetapi diam-diam <strong>daya belinya tergerus</strong> tiap tahun. Aman dari maling belum tentu aman dari inflasi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Lihat berapa nilai riil uangmu beberapa tahun ke depan pada tingkat inflasi tertentu.",
      },
      { type: "widget", widget: "KalkulatorInflasi" },
      {
        type: "chart",
        variant: "line",
        title: "Daya Beli Rp10 juta jika Inflasi 4 persen/tahun",
        unit: "Rp juta (nilai riil)",
        source: "ilustrasi edukatif pada asumsi inflasi 4 persen per tahun",
        note: "Nominal tetap Rp10 juta, tetapi kemampuannya membeli barang menyusut tiap tahun.",
        data: [
          { label: "Sekarang", value: 10, color: "#34d399" },
          { label: "5 tahun", value: 8.2, color: "#f59e0b" },
          { label: "10 tahun", value: 6.8, color: "#ef4444" },
          { label: "20 tahun", value: 4.6, color: "#b91c1c" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Uang di bawah bantal",
        html: "Pak Sarno menyimpan <strong>Rp50 juta</strong> di lemari selama 10 tahun karena takut dengan bank. Angkanya tetap Rp50 juta, tetapi dengan inflasi rata-rata sekitar 4 persen per tahun, daya belinya turun menjadi setara <strong>Rp33 juta</strong> saja. Tetangganya yang menaruh di reksa dana yang tumbuh di atas inflasi tetap mempertahankan, bahkan menambah, daya belinya.",
      },
      {
        type: "case",
        title: "Sejarah: Hiperinflasi Indonesia pertengahan 1960-an",
        html: "Indonesia pernah mengalami <strong>hiperinflasi</strong> pada pertengahan tahun <strong>1960-an</strong>, dengan laju inflasi menembus ratusan persen per tahun sekitar <strong>1965-1966</strong>. Uang cepat kehilangan nilai sehingga pemerintah melakukan pemotongan nilai mata uang (<em>sanering</em>) pada <strong>1965</strong>, mengubah Rp1.000 lama menjadi Rp1 baru. Peristiwa itu menjadi pengingat keras bahwa daya beli bisa runtuh bila inflasi tak terkendali.",
      },
      {
        type: "calcExercise",
        prompt: "Tabungan memberi bunga 3 persen, inflasi 5 persen. Berapa imbal hasil riil (dalam persen)?",
        answer: -2,
        tolerance: 0,
        suffix: " persen",
        solution: "Imbal hasil riil = 3 persen - 5 persen = <strong>minus 2 persen</strong>. Secara riil uang menyusut.",
        hint: "Kurangi inflasi dari bunga nominal.",
      },
      {
        type: "classifyExercise",
        prompt: "Terhadap inflasi, keputusan ini cenderung menjaga atau menggerus daya beli?",
        buckets: ["Menjaga daya beli", "Menggerus daya beli"],
        items: [
          { text: "Menaruh uang jangka panjang di reksa dana yang tumbuh di atas inflasi", bucket: "Menjaga daya beli" },
          { text: "Menyimpan seluruh dana di bawah bantal bertahun-tahun", bucket: "Menggerus daya beli" },
          { text: "Investasi imbal hasil di atas laju inflasi", bucket: "Menjaga daya beli" },
          { text: "Tabungan berbunga 1 persen saat inflasi 4 persen", bucket: "Menggerus daya beli" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Inflasi menaikkan harga sehingga uang yang sama membeli lebih sedikit.",
          "Imbal hasil riil = imbal hasil nominal dikurangi inflasi.",
          "Menabung di bawah inflasi membuat uang menyusut secara riil.",
          "Uang jangka panjang perlu instrumen yang mengalahkan inflasi.",
          "Aman dari maling belum tentu aman dari inflasi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inflasi menyebabkan?",
            options: ["Harga barang naik dan daya beli uang turun", "Uang bertambah otomatis", "Pajak hilang", "Bunga bank naik pasti"],
            answer: 0,
            explain: "Inflasi menaikkan harga sehingga daya beli uang menurun.",
          },
          {
            q: "Imbal hasil riil dihitung dengan?",
            options: ["Nominal + inflasi", "Nominal - inflasi", "Inflasi x 2", "Nominal x inflasi"],
            answer: 1,
            explain: "Imbal hasil riil kira-kira imbal hasil nominal dikurangi inflasi.",
          },
          {
            q: "Bunga tabungan 2 persen, inflasi 5 persen. Imbal hasil riilnya?",
            options: ["Plus 7 persen", "Minus 3 persen", "Plus 3 persen", "Nol"],
            answer: 1,
            explain: "2 persen - 5 persen = minus 3 persen, uang menyusut secara riil.",
          },
          {
            q: "Mengapa menyimpan semua uang di bawah bantal berisiko?",
            options: ["Karena kena pajak tinggi", "Karena daya belinya tergerus inflasi", "Karena bunganya terlalu besar", "Karena dilarang hukum"],
            answer: 1,
            explain: "Nominal tetap, tetapi inflasi menggerus daya belinya tiap tahun.",
          },
          {
            q: "Agar uang jangka panjang tidak kalah inflasi, sebaiknya?",
            options: ["Disimpan tunai saja", "Ditaruh di instrumen dengan imbal hasil di atas inflasi", "Dibiarkan di celengan", "Dihabiskan segera"],
            answer: 1,
            explain: "Instrumen yang tumbuh di atas inflasi menjaga bahkan menambah daya beli.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "menabung-tujuan-besar",
    levelId: "aruskas",
    order: 7,
    title: "Menabung untuk Tujuan Besar",
    summary: "Menyiapkan DP rumah, biaya nikah, dan umrah atau haji lewat kombinasi tabungan berjangka dan investasi sesuai jangka waktu.",
    durationMin: 15,
    tags: ["tujuan besar", "tabungan berjangka", "syariah"],
    blocks: [
      {
        type: "paragraph",
        html: "Ada tujuan hidup yang butuh dana besar: <strong>DP rumah</strong>, <strong>biaya menikah</strong>, atau <strong>umrah dan haji</strong>. Tujuan seperti ini tidak bisa dicapai dengan menabung asal-asalan. Kuncinya adalah menetapkan target angka, tenggat waktu, lalu memilih wadah menabung yang sesuai jangka waktunya.",
      },
      {
        type: "paragraph",
        html: "Prinsipnya: <strong>makin dekat tujuannya, makin aman wadahnya</strong>. Untuk kebutuhan dalam 1 sampai 2 tahun, pakai tabungan berjangka atau deposito yang stabil. Untuk tujuan 5 tahun lebih, boleh dicampur dengan investasi yang berpotensi tumbuh lebih tinggi meski berisiko.",
      },
      {
        type: "video",
        comp: "PiramidaKeuanganVideo",
        title: "Video: Menyusun Tujuan Besar",
        caption: "Menata tujuan besar di atas fondasi dana darurat dan arus kas yang sehat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Target bulanan",
        html: "<strong>Setoran bulanan = Target dana / Jumlah bulan</strong> (versi sederhana tanpa imbal hasil). Contoh: DP rumah Rp60 juta dalam 5 tahun (60 bulan) berarti menabung Rp1 juta per bulan. Dengan imbal hasil investasi, setoran bisa lebih ringan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Cocokkan wadah dengan jangka waktu",
        html: "Tujuan <strong>jangka pendek</strong> (kurang 3 tahun): tabungan berjangka, deposito. Tujuan <strong>jangka menengah-panjang</strong> (5 tahun lebih): boleh kombinasi dengan reksa dana atau instrumen investasi. Jangan menaruh dana yang segera dipakai di aset yang harganya bisa turun.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Opsi syariah",
        html: "Buat yang ingin sesuai prinsip syariah, tersedia <strong>tabungan berjangka syariah</strong> dan <strong>tabungan haji</strong> berbasis akad syariah, serta <strong>reksa dana syariah</strong> yang portofolionya disaring sesuai ketentuan. Mekanismenya mirip, hanya akad dan pengelolaannya mengikuti prinsip syariah.",
      },
      { type: "widget", widget: "KalkulatorDanaPendidikan" },
      {
        type: "chart",
        variant: "bar",
        title: "Setoran Bulanan untuk Tujuan Besar (versi sederhana tanpa imbal hasil)",
        unit: "Rp ribu/bulan",
        source: "ilustrasi: target dana dibagi jumlah bulan",
        note: "Tenor lebih panjang membuat setoran bulanan lebih ringan untuk target yang sama.",
        data: [
          { label: "Nikah Rp50jt / 3 th", value: 1389, color: "#0ea5e9" },
          { label: "DP rumah Rp60jt / 5 th", value: 1000, color: "#6366f1" },
          { label: "Umrah Rp30jt / 3 th", value: 833, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: DP rumah dalam 5 tahun",
        html: "Nadia dan Bima ingin DP rumah <strong>Rp60 juta</strong> dalam 5 tahun. Secara sederhana itu Rp1 juta per bulan. Karena tenornya cukup panjang, mereka menaruh sebagian di tabungan berjangka dan sebagian di reksa dana. Dengan asumsi imbal hasil, setoran mereka cukup sekitar <strong>Rp850 ribu</strong> per bulan untuk mencapai target yang sama. Selisihnya adalah kerja uang lewat investasi.",
      },
      {
        type: "case",
        title: "Sejarah: Tabungan haji dan antrean haji di Indonesia",
        html: "Minat haji di Indonesia sangat tinggi sehingga muncul <strong>antrean (waiting list)</strong> yang di banyak daerah mencapai belasan hingga puluhan tahun. Untuk mendaftar porsi haji, calon jemaah menyetor dana awal melalui bank syariah penerima setoran. Karena itu berkembanglah <strong>tabungan haji</strong> yang membantu masyarakat menyiapkan setoran secara bertahap. Sistem ini menegaskan pentingnya menabung terarah dan lebih dini untuk tujuan besar yang butuh waktu panjang.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya nikah ditargetkan Rp48 juta dalam 4 tahun. Berapa setoran per bulan tanpa imbal hasil (dalam ribu rupiah)?",
        answer: 1000,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "4 tahun = 48 bulan. Rp48 juta / 48 = <strong>Rp1.000 ribu</strong> per bulan.",
        hint: "Ubah tahun ke bulan, lalu bagi target dengan jumlah bulan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tujuan dengan wadah menabung yang paling sesuai.",
        pairs: [
          { left: "Umrah tahun depan", right: "Tabungan berjangka atau deposito" },
          { left: "DP rumah 6 tahun lagi", right: "Kombinasi tabungan dan reksa dana" },
          { left: "Setoran porsi haji", right: "Tabungan haji di bank syariah" },
          { left: "Dana yang segera dipakai", right: "Simpanan stabil, bukan aset fluktuatif" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Tujuan besar butuh target angka, tenggat, dan wadah yang sesuai.",
          "Setoran bulanan sederhana = target dibagi jumlah bulan.",
          "Makin dekat tujuannya, makin aman wadah menabungnya.",
          "Tujuan jangka panjang boleh dikombinasi dengan investasi.",
          "Tersedia opsi syariah seperti tabungan haji dan reksa dana syariah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Prinsip memilih wadah menabung untuk tujuan besar adalah?",
            options: ["Makin dekat tujuan, makin aman wadahnya", "Selalu pakai saham", "Selalu tunai di rumah", "Makin dekat tujuan, makin berisiko"],
            answer: 0,
            explain: "Dana yang segera dipakai sebaiknya di tempat stabil, bukan aset fluktuatif.",
          },
          {
            q: "Target Rp36 juta dalam 3 tahun. Setoran per bulan tanpa imbal hasil?",
            options: ["Rp1 juta", "Rp3 juta", "Rp500 ribu", "Rp12 juta"],
            answer: 0,
            explain: "3 tahun = 36 bulan. Rp36 juta / 36 = Rp1 juta per bulan.",
          },
          {
            q: "Untuk tujuan 6 tahun lagi, kombinasi yang wajar adalah?",
            options: ["Semua di aset kripto", "Tabungan dan reksa dana", "Semua tunai", "Utang pinjol"],
            answer: 1,
            explain: "Tenor panjang memungkinkan sebagian ditaruh di investasi yang berpotensi tumbuh.",
          },
          {
            q: "Contoh opsi syariah untuk tujuan besar adalah?",
            options: ["Tabungan haji dan reksa dana syariah", "Deposito berbunga tinggi", "Pinjaman ribawi", "Saham spekulatif"],
            answer: 0,
            explain: "Tabungan haji dan reksa dana syariah mengikuti prinsip syariah.",
          },
          {
            q: "Mengapa mulai menabung lebih dini untuk tujuan besar?",
            options: ["Agar setoran bulanan lebih ringan dan waktu bekerja untukmu", "Agar cepat berutang", "Agar kena pajak", "Tidak ada manfaatnya"],
            answer: 0,
            explain: "Tenor lebih panjang meringankan setoran dan memberi ruang imbal hasil tumbuh.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "hidup-hemat-frugal-living",
    levelId: "aruskas",
    order: 8,
    title: "Hidup Hemat (Frugal Living)",
    summary: "Hemat berdasarkan nilai, membedakan hemat cerdas dari pelit, dan menekan pengeluaran besar yang paling berdampak.",
    durationMin: 14,
    tags: ["hemat", "frugal living", "gaya hidup"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Hidup hemat</strong> (frugal living) sering disalahpahami sebagai menyiksa diri atau pelit. Padahal inti hemat yang sehat adalah <strong>belanja berdasarkan nilai</strong> (value-based spending): berani mengeluarkan uang untuk hal yang benar-benar penting bagimu, dan tegas memangkas yang tidak. Hemat bukan soal membeli yang paling murah, melainkan tidak membuang uang untuk hal yang tidak kamu pedulikan.",
      },
      {
        type: "paragraph",
        html: "Bedakan <strong>hemat cerdas</strong> dari <strong>pelit</strong>. Hemat cerdas menahan pengeluaran sepele demi tujuan yang lebih besar, tetap menjaga kualitas hidup dan hubungan sosial. Pelit mengorbankan hal penting, seperti kesehatan atau kejujuran, hanya demi menahan uang. Tujuan hemat adalah memberi ruang untuk menabung, bukan membuat hidup terasa sengsara.",
      },
      {
        type: "video",
        comp: "PsikologiUangVideo",
        title: "Video: Hemat Berdasarkan Nilai",
        caption: "Fokuskan uang pada yang penting bagimu, pangkas yang tidak kamu pedulikan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pukul yang besar dulu",
        html: "Tiga pengeluaran terbesar kebanyakan orang adalah <strong>tempat tinggal, kendaraan, dan gaya hidup</strong>. Menekan satu keputusan besar (memilih rumah yang wajar, menunda ganti mobil) jauh lebih berdampak daripada berhemat receh setiap hari. Menghemat 10 persen dari cicilan besar mengalahkan berhenti beli kopi sebulan penuh.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hemat bukan menyiksa diri",
        html: "Berhemat sampai mengorbankan gizi, kesehatan, atau hubungan justru kontraproduktif. Kalau kamu sakit atau kehilangan relasi karena terlalu pelit, biayanya sering lebih mahal. Hemat yang sehat menekan pemborosan, bukan menekan kebutuhan dasar dan kebahagiaan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan pos-pos pengeluaranmu, lalu lihat pos mana yang paling besar dan paling layak dipangkas untuk menambah ruang menabung.",
      },
      { type: "widget", widget: "KalkulatorAnggaran" },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Penghematan: Besar vs Receh (per tahun)",
        unit: "Rp ribu/tahun",
        source: "ilustrasi: memangkas 1 pos besar vs banyak pos kecil",
        note: "Menurunkan satu pengeluaran besar sering menghemat jauh lebih banyak daripada memangkas banyak hal kecil.",
        data: [
          { label: "Stop kopi harian", value: 6600, color: "#94a3b8" },
          { label: "Turunkan paket data", value: 1200, color: "#f59e0b" },
          { label: "Sewa lebih murah Rp1jt/bln", value: 12000, color: "#10b981" },
          { label: "Tunda ganti mobil", value: 24000, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Value-based spending ala Rara",
        html: "Rara suka sekali membaca dan berolahraga, tetapi tidak peduli mode. Ia berani berlangganan buku dan gym, tetapi memangkas anggaran pakaian bermerek yang tak ia butuhkan. Total ia menghemat sekitar <strong>Rp1,5 juta</strong> per bulan tanpa merasa kehilangan apa pun, sebab uangnya justru mengalir ke hal yang benar-benar ia hargai. Itulah hemat berdasarkan nilai.",
      },
      {
        type: "case",
        title: "Sejarah: Budaya hemat dan menabung masyarakat Indonesia",
        html: "Semangat hemat sudah lama mengakar di Indonesia. Pemerintah menggencarkan <strong>Gerakan Nasional Menabung</strong> lewat produk seperti Tabanas pada tahun <strong>1971</strong>, dan sejak <strong>2010</strong> program <strong>TabunganKu</strong> serta Gerakan Indonesia Menabung mendorong kebiasaan menyisihkan uang tanpa biaya administrasi. Nilai <em>hemat pangkal kaya</em> yang diajarkan turun-temurun menegaskan bahwa berhemat bukan pelit, melainkan cara menyiapkan masa depan.",
      },
      {
        type: "calcExercise",
        prompt: "Kamu pindah ke kos yang lebih murah dan hemat Rp1 juta per bulan. Berapa penghematan dalam setahun (dalam juta rupiah)?",
        answer: 12,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Rp1 juta x 12 bulan = <strong>Rp12 juta</strong> per tahun. Satu keputusan besar berdampak sepanjang tahun.",
        hint: "Kalikan penghematan bulanan dengan 12.",
      },
      {
        type: "classifyExercise",
        prompt: "Perilaku ini termasuk hemat cerdas atau pelit?",
        buckets: ["Hemat cerdas", "Pelit"],
        items: [
          { text: "Menunda beli gadget baru yang masih layak pakai", bucket: "Hemat cerdas" },
          { text: "Membawa bekal agar bisa menabung lebih banyak", bucket: "Hemat cerdas" },
          { text: "Menolak berobat saat sakit demi menahan uang", bucket: "Pelit" },
          { text: "Tidak pernah berbagi dan mengorbankan hubungan demi uang", bucket: "Pelit" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Hemat sehat adalah belanja berdasarkan nilai, bukan sekadar paling murah.",
          "Hemat cerdas menjaga kualitas hidup; pelit mengorbankan hal penting.",
          "Menekan pengeluaran besar lebih berdampak daripada memangkas receh.",
          "Tiga pos terbesar: tempat tinggal, kendaraan, dan gaya hidup.",
          "Tujuan hemat adalah memberi ruang menabung, bukan menyiksa diri.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti dari value-based spending adalah?",
            options: ["Selalu beli yang termurah", "Membelanjakan uang untuk yang penting, memangkas yang tidak", "Tidak pernah belanja", "Menghabiskan gaji cepat"],
            answer: 1,
            explain: "Hemat berdasarkan nilai berani berbelanja untuk yang penting dan tegas memotong yang tidak.",
          },
          {
            q: "Apa beda hemat cerdas dan pelit?",
            options: ["Tidak ada bedanya", "Hemat cerdas menjaga hal penting, pelit mengorbankannya", "Pelit lebih baik", "Hemat cerdas berarti tak pernah belanja"],
            answer: 1,
            explain: "Pelit mengorbankan kebutuhan dasar dan hubungan, hemat cerdas tidak.",
          },
          {
            q: "Penghematan mana yang biasanya paling berdampak setahun?",
            options: ["Berhenti beli kopi harian", "Menurunkan biaya sewa tempat tinggal", "Mengurangi jajan sekali", "Mematikan lampu sebentar"],
            answer: 1,
            explain: "Pengeluaran besar seperti tempat tinggal berdampak jauh lebih besar sepanjang tahun.",
          },
          {
            q: "Hemat Rp800 ribu per bulan setara berapa dalam setahun?",
            options: ["Rp9,6 juta", "Rp800 ribu", "Rp1,6 juta", "Rp96 juta"],
            answer: 0,
            explain: "Rp800 ribu x 12 = Rp9,6 juta per tahun.",
          },
          {
            q: "Tujuan utama hidup hemat yang sehat adalah?",
            options: ["Menyiksa diri", "Memberi ruang untuk menabung tanpa mengorbankan kualitas hidup", "Menjadi pelit", "Menghindari pajak"],
            answer: 1,
            explain: "Hemat sehat membebaskan uang untuk ditabung sambil tetap menjaga kualitas hidup.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "menambah-penghasilan",
    levelId: "aruskas",
    order: 9,
    title: "Menambah Penghasilan",
    summary: "Tidak mengandalkan satu sumber, membedakan penghasilan aktif dan pasif, serta meningkatkan nilai diri agar penghasilan naik.",
    durationMin: 15,
    tags: ["penghasilan", "side income", "keterampilan"],
    blocks: [
      {
        type: "paragraph",
        html: "Berhemat punya batas, tetapi <strong>menambah penghasilan</strong> tidak. Mengandalkan satu sumber penghasilan itu rapuh: jika sumber itu terganggu, seluruh keuanganmu ikut goyah. Karena itu, banyak orang mulai membangun sumber penghasilan tambahan agar lebih aman sekaligus mempercepat tujuan keuangan.",
      },
      {
        type: "paragraph",
        html: "Ada dua jenis penghasilan. <strong>Penghasilan aktif</strong> didapat dari waktu dan tenaga: gaji, kerja sampingan, atau jasa dari keterampilan barumu. <strong>Penghasilan pasif</strong> mengalir dari aset yang bekerja untukmu, seperti bunga deposito, dividen, imbal hasil reksa dana, atau sewa. Kuncinya: ubah sebagian penghasilan aktif menjadi aset yang menghasilkan penghasilan pasif.",
      },
      {
        type: "video",
        comp: "KemandirianFinansialVideo",
        title: "Video: Menambah Aliran Penghasilan",
        caption: "Dari satu sumber menjadi beberapa aliran yang saling menopang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aktif vs pasif",
        html: "<strong>Penghasilan aktif</strong> berhenti saat kamu berhenti bekerja (gaji, freelance, ojek online). <strong>Penghasilan pasif</strong> tetap mengalir walau kamu tidak bekerja aktif (dividen, bunga, sewa, royalti). Kemandirian finansial tercapai ketika penghasilan pasif mampu menutup kebutuhan hidupmu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Naikkan nilai dirimu",
        html: "Cara paling andal menaikkan penghasilan adalah <strong>meningkatkan nilai diri</strong>: keterampilan baru, sertifikasi, jaringan, dan reputasi. Semakin langka dan bermanfaat keahlianmu, semakin tinggi imbalan yang bisa kamu minta, baik di pekerjaan utama maupun sampingan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Jangan lupakan risiko dan pajak",
        html: "Kerja sampingan tetap perlu dijaga agar tidak mengganggu pekerjaan utama atau kesehatan. Ingat juga bahwa penghasilan tambahan bisa menjadi objek pajak. Catat pemasukan tambahanmu dan pahami kewajiban pajaknya agar tetap tertib.",
      },
      { type: "widget", widget: "KalkulatorNetWorth" },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Side Income terhadap Tabungan Bulanan",
        unit: "Rp ribu/bulan",
        source: "ilustrasi: surplus gaji Rp1 juta ditambah side income",
        note: "Penghasilan tambahan yang langsung ditabung bisa melipatgandakan kemampuan menabungmu.",
        data: [
          { label: "Hanya gaji", value: 1000, color: "#94a3b8" },
          { label: "+ Side income Rp1jt", value: 2000, color: "#0ea5e9" },
          { label: "+ Side income Rp2jt", value: 3000, color: "#10b981" },
          { label: "+ Side income Rp3jt", value: 4000, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua aliran milik Fajar",
        html: "Fajar bergaji Rp6 juta dengan surplus Rp1 juta per bulan. Ia belajar desain grafis di malam hari, lalu menerima proyek sampingan rata-rata <strong>Rp1,5 juta</strong> per bulan. Karena kebutuhannya sudah tertutup gaji, seluruh side income ia tabung dan investasikan. Tabungan bulanannya melonjak dari Rp1 juta menjadi <strong>Rp2,5 juta</strong>, dan lama-lama sebagian aset itu mulai memberi penghasilan pasif.",
      },
      {
        type: "case",
        title: "Sejarah: Tumbuhnya ekonomi gig dan pekerjaan sampingan digital",
        html: "Sejak kemunculan platform seperti Gojek yang berdiri pada <strong>2010</strong> dan Grab yang masuk Indonesia sekitar <strong>2014</strong>, muncul <strong>ekonomi gig</strong>: orang bisa bekerja fleksibel sebagai mitra pengemudi, kurir, atau pekerja lepas. Pandemi COVID-19 pada <strong>2020</strong> mempercepat tren freelance digital, dari jasa desain, penulisan, hingga jualan online. Kini menambah penghasilan lewat pekerjaan sampingan digital menjadi hal yang lumrah dan mudah diakses.",
      },
      {
        type: "calcExercise",
        prompt: "Surplus dari gaji Rp1 juta per bulan. Jika kamu menambah side income Rp1,5 juta yang seluruhnya ditabung, berapa total tabungan per bulan (dalam juta rupiah)?",
        answer: 2.5,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Rp1 juta + Rp1,5 juta = <strong>Rp2,5 juta</strong> per bulan. Side income yang ditabung utuh melipatkan kemampuan menabung.",
        hint: "Jumlahkan surplus gaji dengan side income yang ditabung.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan sumber penghasilan dengan jenisnya.",
        pairs: [
          { left: "Gaji bulanan", right: "Penghasilan aktif" },
          { left: "Proyek freelance desain", right: "Penghasilan aktif" },
          { left: "Dividen saham", right: "Penghasilan pasif" },
          { left: "Sewa kamar kos", right: "Penghasilan pasif" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Mengandalkan satu sumber penghasilan itu rapuh; bangun aliran tambahan.",
          "Penghasilan aktif dari waktu dan tenaga; penghasilan pasif dari aset.",
          "Ubah sebagian penghasilan aktif menjadi aset yang menghasilkan pasif.",
          "Menaikkan nilai diri lewat keterampilan menaikkan potensi penghasilan.",
          "Kemandirian finansial tercapai saat pasif menutup kebutuhan hidup.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa mengandalkan satu sumber penghasilan berisiko?",
            options: ["Karena pajaknya besar", "Karena jika sumber itu terganggu, seluruh keuangan goyah", "Karena dilarang", "Karena bunganya kecil"],
            answer: 1,
            explain: "Satu sumber membuat keuangan rapuh bila sumber itu hilang atau terganggu.",
          },
          {
            q: "Contoh penghasilan pasif adalah?",
            options: ["Gaji bulanan", "Upah lembur", "Dividen dan sewa", "Bayaran proyek freelance"],
            answer: 2,
            explain: "Penghasilan pasif mengalir dari aset seperti dividen dan sewa, bukan dari kerja aktif.",
          },
          {
            q: "Cara paling andal menaikkan penghasilan jangka panjang adalah?",
            options: ["Berutang lebih banyak", "Meningkatkan nilai diri lewat keterampilan", "Berjudi", "Menunggu keberuntungan"],
            answer: 1,
            explain: "Keterampilan yang langka dan bermanfaat menaikkan imbalan yang bisa kamu minta.",
          },
          {
            q: "Surplus gaji Rp800 ribu ditambah side income Rp1,2 juta yang ditabung. Total tabungan per bulan?",
            options: ["Rp2 juta", "Rp1,2 juta", "Rp800 ribu", "Rp400 ribu"],
            answer: 0,
            explain: "Rp800 ribu + Rp1,2 juta = Rp2 juta per bulan.",
          },
          {
            q: "Kapan kira-kira kemandirian finansial tercapai?",
            options: ["Saat gaji naik sekali", "Saat penghasilan pasif menutup kebutuhan hidup", "Saat punya banyak utang", "Saat berhenti menabung"],
            answer: 1,
            explain: "Kemandirian finansial berarti aset menghasilkan cukup untuk menutup kebutuhan tanpa kerja aktif.",
          },
        ],
      },
    ],
  },
];
