import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "penerimaan-negara",
    levelId: "penerimaan",
    order: 1,
    title: "Penerimaan Negara: Pajak & PNBP",
    summary: "Dari mana uang negara berasal: pajak (PPh, PPN, cukai, bea) dan PNBP, serta konsep tax ratio. Dengan video & kalkulator.",
    durationMin: 14,
    tags: ["pajak", "PNBP", "tax ratio"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebagian besar uang negara berasal dari <strong>pajak</strong>. Jenis utamanya: <strong>PPh</strong> (Pajak Penghasilan), <strong>PPN</strong> (Pajak Pertambahan Nilai), <strong>cukai</strong> (mis. rokok), dan <strong>bea</strong> (masuk/keluar). Selain pajak, ada <strong>PNBP</strong> (Penerimaan Negara Bukan Pajak) dari sumber daya alam, layanan, dan dividen BUMN.",
      },
      {
        type: "video",
        comp: "SumberPenerimaanNegara",
        title: "Video: Sumber Penerimaan Negara",
        caption: "Animasi porsi pajak dan PNBP dalam penerimaan APBN.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tax ratio",
        html: "<strong>Tax ratio</strong> = penerimaan pajak / PDB. Indonesia berkisar 10-11%, relatif rendah dibanding negara maju (di atas 20%). Menaikkannya adalah tantangan besar fiskal.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung tax ratio dari penerimaan pajak dan PDB, serta perkirakan potensi tambahan penerimaan.",
      },
      { type: "widget", widget: "KalkulatorTaxRatio" },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi Penerimaan Negara (ilustrasi)",
        unit: "% penerimaan",
        source: "ilustrasi pola umum",
        note: "Pajak (PPh + PPN + cukai + bea) mendominasi, sisanya PNBP dan hibah.",
        data: [
          { label: "PPh", value: 38, color: "#10b981" },
          { label: "PPN", value: 30, color: "#0ea5e9" },
          { label: "Cukai & Bea", value: 12, color: "#f59e0b" },
          { label: "PNBP", value: 18, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Mengapa reformasi pajak penting",
        html: "Dengan tax ratio sekitar 10%, ruang fiskal Indonesia terbatas untuk membiayai pembangunan tanpa berutang. Reformasi seperti penerapan <strong>NIK sebagai NPWP</strong>, <strong>coretax</strong>, dan perluasan basis pajak bertujuan menaikkan penerimaan tanpa selalu menaikkan tarif. Naik 1% PDB saja setara ratusan triliun rupiah.",
      },
      {
        type: "calcExercise",
        prompt: "Penerimaan pajak Rp2.200 triliun, PDB Rp22.000 triliun. Berapa tax ratio (%)?",
        answer: 10,
        tolerance: 0,
        suffix: "%",
        solution: "Tax ratio = 2.200 / 22.000 x 100 = <strong>10%</strong>.",
        hint: "Penerimaan pajak dibagi PDB, dikali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Penerimaan ini termasuk pajak atau PNBP?",
        buckets: ["Pajak", "PNBP"],
        items: [
          { text: "PPN atas pembelian barang", bucket: "Pajak" },
          { text: "Royalti tambang ke negara", bucket: "PNBP" },
          { text: "Cukai rokok", bucket: "Pajak" },
          { text: "Dividen BUMN", bucket: "PNBP" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis penerimaan negara dengan contohnya.",
        pairs: [
          { left: "PPh", right: "Pajak atas penghasilan orang dan badan" },
          { left: "PPN", right: "Pajak atas konsumsi barang dan jasa" },
          { left: "Cukai", right: "Pungutan atas rokok dan minuman beralkohol" },
          { left: "PNBP", right: "Royalti tambang dan dividen BUMN" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren Tax Ratio Indonesia (ilustrasi)",
        unit: "% PDB",
        source: "ilustrasi pola umum",
        note: "Tax ratio bergerak di kisaran 10-11% dalam beberapa tahun terakhir.",
        data: [
          { label: "2020", value: 8.3, color: "#0ea5e9" },
          { label: "2021", value: 9.1, color: "#0ea5e9" },
          { label: "2022", value: 10.4, color: "#10b981" },
          { label: "2023", value: 10.2, color: "#10b981" },
          { label: "2024", value: 10.1, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Dari penerimaan migas ke pajak",
        html: "Pada era <strong>bonanza minyak 1970-an</strong>, penerimaan negara Indonesia sangat bertumpu pada migas yang sempat menyumbang sekitar dua pertiga pendapatan. Ketika harga minyak jatuh pada pertengahan 1980-an, penerimaan anjlok dan pemerintah mulai serius membangun sistem <strong>perpajakan</strong> modern lewat reformasi pajak 1983. Sejak itu pajak menjadi penopang utama, meski <strong>tax ratio</strong> Indonesia masih tergolong rendah di kisaran 10%.",
      },
      {
        type: "takeaways",
        items: [
          "Penerimaan negara didominasi pajak: PPh, PPN, cukai, bea.",
          "PNBP berasal dari SDA, layanan, dan dividen BUMN.",
          "Tax ratio = penerimaan pajak / PDB; Indonesia masih rendah (~10%).",
          "Reformasi pajak memperluas basis untuk menaikkan penerimaan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Penyumbang terbesar penerimaan negara adalah?",
            options: ["Hibah", "Pajak", "Penjualan aset", "Cetak uang"],
            answer: 1,
            explain: "Pajak (PPh, PPN, cukai, bea) adalah penyumbang terbesar.",
          },
          {
            q: "Dividen BUMN termasuk?",
            options: ["Pajak", "PNBP", "Hibah", "Utang"],
            answer: 1,
            explain: "Dividen BUMN adalah Penerimaan Negara Bukan Pajak (PNBP).",
          },
          {
            q: "Tax ratio adalah?",
            options: ["Pajak / belanja", "Pajak / PDB", "Pajak / penduduk", "Utang / PDB"],
            answer: 1,
            explain: "Tax ratio adalah penerimaan pajak dibagi PDB.",
          },
          {
            q: "PPN adalah pajak atas?",
            options: ["Penghasilan", "Konsumsi/pertambahan nilai barang & jasa", "Tanah", "Ekspor"],
            answer: 1,
            explain: "PPN adalah Pajak Pertambahan Nilai atas konsumsi barang dan jasa.",
          },
          {
            q: "Pajak Rp1.800 T, PDB Rp20.000 T. Tax ratio?",
            options: ["9%", "11%", "18%", "90%"],
            answer: 0,
            explain: "1.800 / 20.000 x 100 = 9%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jenis-pajak",
    levelId: "penerimaan",
    order: 2,
    title: "Jenis-Jenis Pajak di Indonesia",
    summary: "Mengenal PPh, PPN, PBB, cukai, dan bea; perbedaan pajak pusat dan pajak daerah; serta konsep pajak progresif.",
    durationMin: 13,
    tags: ["PPh", "PPN", "PBB", "cukai", "pajak progresif"],
    blocks: [
      {
        type: "paragraph",
        html: "Pajak di Indonesia dibagi menjadi banyak jenis sesuai objek yang dikenakan. Yang utama: <strong>PPh</strong> (Pajak Penghasilan) atas penghasilan orang dan badan, <strong>PPN</strong> (Pajak Pertambahan Nilai) atas konsumsi barang dan jasa, <strong>PBB</strong> (Pajak Bumi dan Bangunan) atas kepemilikan properti, <strong>cukai</strong> atas barang tertentu yang dibatasi peredarannya seperti rokok dan minuman beralkohol, serta <strong>bea</strong> masuk dan keluar atas kegiatan ekspor-impor.",
      },
      {
        type: "paragraph",
        html: "Berdasarkan lembaga pemungutnya, ada <strong>pajak pusat</strong> yang dikelola pemerintah pusat melalui Direktorat Jenderal Pajak (PPh, PPN, cukai, bea) dan <strong>pajak daerah</strong> yang dikelola pemerintah daerah (PBB perdesaan-perkotaan, Bea Perolehan Hak atas Tanah dan Bangunan, pajak kendaraan bermotor, pajak hotel, dan pajak restoran).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pajak progresif",
        html: "Tarif <strong>PPh orang pribadi</strong> bersifat progresif: makin tinggi penghasilan, makin tinggi tarifnya. Lapisan tarif berkisar dari 5% untuk penghasilan kena pajak terendah hingga 35% untuk lapisan teratas (di atas Rp5 miliar per tahun).",
      },
      {
        type: "callout",
        tone: "info",
        title: "PPN bersifat tidak langsung",
        html: "PPN dipungut oleh penjual lalu disetor ke negara, tetapi beban sebenarnya ditanggung konsumen akhir. Tarif umum PPN saat ini <strong>11%</strong> dan dijadwalkan menjadi 12% sesuai amanat undang-undang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hubungkan ke tax ratio",
        html: "Komposisi jenis pajak menentukan ketahanan penerimaan. Gunakan kalkulator di bawah untuk melihat dampak perubahan penerimaan pajak terhadap tax ratio.",
      },
      { type: "widget", widget: "KalkulatorTaxRatio" },
      {
        type: "chart",
        variant: "donut",
        title: "Porsi Jenis Pajak Pusat (ilustrasi)",
        unit: "% penerimaan pajak",
        source: "ilustrasi pola umum APBN",
        note: "PPh dan PPN menjadi tulang punggung penerimaan pajak pusat.",
        data: [
          { label: "PPh", value: 45, color: "#10b981" },
          { label: "PPN & PPnBM", value: 38, color: "#0ea5e9" },
          { label: "Cukai", value: 13, color: "#f59e0b" },
          { label: "Pajak lainnya & bea", value: 4, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: PPh progresif Pak Budi",
        html: "Penghasilan kena pajak Pak Budi Rp100 juta setahun. Dengan tarif progresif: lapisan pertama Rp60 juta dikenai 5% = Rp3 juta, sisa Rp40 juta dikenai 15% = Rp6 juta. Total PPh terutang <strong>Rp9 juta</strong>. Tarif efektifnya 9%, lebih rendah dari tarif marginal 15% karena sistem berlapis.",
      },
      {
        type: "calcExercise",
        prompt: "PPN tarif 11%. Harga barang sebelum pajak Rp250.000. Berapa rupiah PPN yang dikenakan?",
        answer: 27500,
        tolerance: 0,
        prefix: "Rp",
        solution: "PPN = 11% x Rp250.000 = <strong>Rp27.500</strong>.",
        hint: "Kalikan harga dasar dengan tarif 11% (0,11).",
      },
      {
        type: "classifyExercise",
        prompt: "Jenis pajak ini termasuk pajak pusat atau pajak daerah?",
        buckets: ["Pajak Pusat", "Pajak Daerah"],
        items: [
          { text: "PPh badan", bucket: "Pajak Pusat" },
          { text: "PPN", bucket: "Pajak Pusat" },
          { text: "Cukai rokok", bucket: "Pajak Pusat" },
          { text: "Pajak kendaraan bermotor", bucket: "Pajak Daerah" },
          { text: "Pajak hotel dan restoran", bucket: "Pajak Daerah" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Penghasilan kena pajak Rp200 juta. Dengan tarif progresif (5% untuk 0-60 jt, 15% untuk 60-250 jt), berapa PPh terutang (rupiah)?",
        answer: 24000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Lapisan 1: 5% x Rp60 jt = Rp3 jt. Lapisan 2: 15% x Rp140 jt = Rp21 jt. Total = <strong>Rp24 juta</strong>.",
        hint: "Rp60 juta pertama kena 5%, sisa Rp140 juta kena 15%, lalu dijumlahkan.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Lapisan Tarif PPh Orang Pribadi (UU HPP)",
        unit: "% tarif",
        source: "UU Harmonisasi Peraturan Perpajakan",
        note: "Tarif progresif dari 5% hingga 35% sesuai lapisan penghasilan kena pajak.",
        data: [
          { label: "0-60 jt", value: 5, color: "#10b981" },
          { label: "60-250 jt", value: 15, color: "#0ea5e9" },
          { label: "250-500 jt", value: 25, color: "#f59e0b" },
          { label: "500 jt-5 M", value: 30, color: "#ef4444" },
          { label: "> 5 M", value: 35, color: "#8b5cf6" },
        ],
      },
      {
        type: "video",
        comp: "JenisPajakVideo",
        title: "Video: Mengenal Jenis-Jenis Pajak",
        caption: "Animasi perbedaan PPh, PPN, PBB, cukai, dan bea serta pajak pusat dan daerah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulator PPh",
        html: "Hitung PPh terutang dengan tarif progresif berlapis dari penghasilan kena pajak.",
      },
      { type: "widget", widget: "KalkulatorPPh" },
      {
        type: "case",
        title: "Sejarah: Tax amnesty 2016",
        html: "Program <strong>pengampunan pajak (tax amnesty)</strong> pada 2016-2017 mengajak wajib pajak mendeklarasikan harta yang belum dilaporkan dengan membayar uang tebusan. Total uang tebusan mencapai sekitar <strong>Rp114 triliun</strong> dengan harta dideklarasikan sekitar Rp4.800 triliun. Tujuannya memperluas basis terutama <strong>PPh</strong>, agar lebih banyak penghasilan dan aset masuk ke dalam sistem pajak.",
      },
      {
        type: "takeaways",
        items: [
          "Jenis pajak utama: PPh, PPN, PBB, cukai, dan bea.",
          "Pajak pusat dikelola DJP; pajak daerah dikelola pemda.",
          "PPh orang pribadi bersifat progresif (5% hingga 35%).",
          "PPN adalah pajak tidak langsung atas konsumsi dengan tarif 11%.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pajak atas konsumsi barang dan jasa adalah?",
            options: ["PPh", "PPN", "PBB", "Cukai"],
            answer: 1,
            explain: "PPN (Pajak Pertambahan Nilai) dikenakan atas konsumsi barang dan jasa.",
          },
          {
            q: "Manakah yang termasuk pajak daerah?",
            options: ["PPN", "PPh badan", "Pajak kendaraan bermotor", "Bea masuk"],
            answer: 2,
            explain: "Pajak kendaraan bermotor dipungut dan dikelola pemerintah daerah.",
          },
          {
            q: "Cukai biasanya dikenakan atas?",
            options: ["Gaji karyawan", "Rokok dan minuman beralkohol", "Tanah dan bangunan", "Dividen"],
            answer: 1,
            explain: "Cukai dikenakan atas barang yang peredarannya dibatasi seperti rokok dan minuman beralkohol.",
          },
          {
            q: "Pajak progresif berarti?",
            options: ["Tarif tetap untuk semua", "Tarif naik seiring naiknya penghasilan", "Tarif turun seiring naiknya penghasilan", "Tanpa tarif"],
            answer: 1,
            explain: "Pada pajak progresif, makin tinggi basis (penghasilan), makin tinggi tarifnya.",
          },
          {
            q: "PPN tarif 11% atas barang Rp500.000. Berapa PPN-nya?",
            options: ["Rp45.000", "Rp50.000", "Rp55.000", "Rp60.000"],
            answer: 2,
            explain: "11% x Rp500.000 = Rp55.000.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pnbp",
    levelId: "penerimaan",
    order: 3,
    title: "PNBP: Penerimaan Negara Bukan Pajak",
    summary: "Sumber penerimaan di luar pajak: SDA migas dan minerba, pendapatan layanan (BLU), serta dividen BUMN dan kekayaan negara dipisahkan.",
    durationMin: 12,
    tags: ["PNBP", "SDA", "BUMN", "dividen"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Penerimaan Negara Bukan Pajak (PNBP)</strong> adalah seluruh penerimaan pemerintah pusat yang bukan berasal dari pajak. PNBP menjadi penopang kedua APBN setelah pajak dan sangat dipengaruhi harga komoditas global, terutama minyak dan batu bara.",
      },
      {
        type: "paragraph",
        html: "Sumber utama PNBP: <strong>SDA migas</strong> (bagi hasil minyak dan gas bumi), <strong>SDA minerba</strong> (royalti mineral dan batu bara), <strong>pendapatan layanan</strong> dari kementerian dan Badan Layanan Umum (mis. biaya paspor, pendidikan, dan kesehatan), serta <strong>dividen BUMN</strong> dari bagian laba kekayaan negara yang dipisahkan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Rentan harga komoditas",
        html: "PNBP SDA sangat fluktuatif karena bergantung pada harga minyak dan batu bara dunia serta nilai tukar rupiah. Saat harga komoditas turun, penerimaan PNBP bisa anjlok dan menekan APBN.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dividen BUMN",
        html: "Negara sebagai pemegang saham menerima <strong>dividen</strong> dari laba BUMN seperti bank pelat merah dan perusahaan energi. Ini bagian dari pengelolaan kekayaan negara yang dipisahkan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Diversifikasi penerimaan",
        html: "Memperbesar PNBP dari layanan dan dividen membantu mengurangi ketergantungan pada SDA yang harganya tidak stabil.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi PNBP (ilustrasi)",
        unit: "% PNBP",
        source: "ilustrasi pola umum",
        note: "SDA dan layanan menjadi penyumbang terbesar PNBP.",
        data: [
          { label: "SDA Migas", value: 28, color: "#10b981" },
          { label: "SDA Minerba", value: 22, color: "#f59e0b" },
          { label: "Layanan/BLU", value: 30, color: "#0ea5e9" },
          { label: "Dividen BUMN", value: 20, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Anjloknya harga batu bara",
        html: "Misal PNBP minerba ditargetkan Rp120 triliun dengan asumsi harga acuan tertentu. Jika harga batu bara turun 25%, penerimaan royalti bisa berkurang sekitar Rp30 triliun menjadi Rp90 triliun. Selisih Rp30 triliun ini harus ditutup dari sumber lain atau menambah defisit.",
      },
      {
        type: "calcExercise",
        prompt: "PNBP SDA migas Rp110 T, minerba Rp130 T, layanan Rp150 T, dividen BUMN Rp80 T. Berapa total PNBP (triliun rupiah)?",
        answer: 470,
        tolerance: 0,
        suffix: " T",
        solution: "Total = 110 + 130 + 150 + 80 = <strong>Rp470 triliun</strong>.",
        hint: "Jumlahkan keempat komponen PNBP.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan sumber PNBP dengan contohnya.",
        pairs: [
          { left: "SDA Migas", right: "Bagi hasil minyak dan gas bumi" },
          { left: "SDA Minerba", right: "Royalti batu bara" },
          { left: "Layanan/BLU", right: "Biaya pembuatan paspor" },
          { left: "Dividen BUMN", right: "Bagian laba bank pelat merah" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan PNBP ini: berasal dari SDA atau non-SDA?",
        buckets: ["PNBP SDA", "PNBP Non-SDA"],
        items: [
          { text: "Bagi hasil minyak dan gas bumi", bucket: "PNBP SDA" },
          { text: "Royalti batu bara", bucket: "PNBP SDA" },
          { text: "Biaya pembuatan paspor", bucket: "PNBP Non-SDA" },
          { text: "Dividen bank pelat merah", bucket: "PNBP Non-SDA" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Sensitivitas PNBP terhadap SDA (ilustrasi)",
        unit: "% PNBP",
        source: "ilustrasi pola umum",
        note: "Sekitar separuh PNBP berasal dari SDA yang harganya fluktuatif.",
        data: [
          { label: "PNBP SDA", value: 50, color: "#f59e0b" },
          { label: "Layanan/BLU", value: 30, color: "#0ea5e9" },
          { label: "Dividen BUMN", value: 20, color: "#8b5cf6" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulator PNBP",
        html: "Jumlahkan komponen PNBP dari SDA, layanan, dan dividen BUMN, lalu lihat dampak perubahan harga komoditas.",
      },
      { type: "widget", widget: "KalkulatorPNBP" },
      {
        type: "case",
        title: "Sejarah: PNBP migas dan risiko Dutch disease",
        html: "Lonjakan harga minyak pada 1970-an membuat <strong>PNBP migas</strong> membanjiri kas negara, tetapi sekaligus memunculkan risiko <strong>Dutch disease</strong>: sektor lain melemah karena ekonomi terlalu bergantung pada satu komoditas. Ketika harga minyak jatuh pada pertengahan 1980-an, penerimaan PNBP anjlok tajam. Pengalaman ini menegaskan mengapa PNBP berbasis SDA bersifat <strong>fluktuatif</strong> dan perlu didiversifikasi.",
      },
      {
        type: "takeaways",
        items: [
          "PNBP adalah penerimaan negara di luar pajak.",
          "Sumbernya: SDA migas, SDA minerba, layanan/BLU, dan dividen BUMN.",
          "PNBP SDA rentan terhadap fluktuasi harga komoditas global.",
          "Diversifikasi PNBP mengurangi ketergantungan pada SDA.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "PNBP adalah penerimaan negara yang berasal dari?",
            options: ["Pajak", "Selain pajak", "Utang", "Hibah luar negeri saja"],
            answer: 1,
            explain: "PNBP adalah Penerimaan Negara Bukan Pajak, yaitu penerimaan di luar pajak.",
          },
          {
            q: "Royalti batu bara termasuk PNBP dari?",
            options: ["SDA Minerba", "Layanan", "Dividen BUMN", "Cukai"],
            answer: 0,
            explain: "Royalti batu bara adalah PNBP dari Sumber Daya Alam minerba.",
          },
          {
            q: "Dividen BUMN merupakan?",
            options: ["Pajak penghasilan", "Bagian laba kekayaan negara dipisahkan", "Cukai", "Bea masuk"],
            answer: 1,
            explain: "Dividen BUMN berasal dari laba kekayaan negara yang dipisahkan.",
          },
          {
            q: "Mengapa PNBP SDA dianggap rentan?",
            options: ["Tarifnya tetap", "Bergantung harga komoditas global", "Tidak diatur undang-undang", "Selalu naik"],
            answer: 1,
            explain: "PNBP SDA sangat dipengaruhi harga minyak dan batu bara dunia yang fluktuatif.",
          },
          {
            q: "Biaya pembuatan paspor termasuk PNBP jenis?",
            options: ["SDA Migas", "Dividen BUMN", "Pendapatan layanan", "Bea keluar"],
            answer: 2,
            explain: "Biaya paspor adalah PNBP dari pendapatan layanan kementerian/lembaga.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "reformasi-perpajakan",
    levelId: "penerimaan",
    order: 4,
    title: "Reformasi Perpajakan",
    summary: "Mengapa tax ratio Indonesia rendah dan bagaimana memperbaikinya: perluasan basis pajak, integrasi NIK sebagai NPWP, sistem Coretax, dan peningkatan kepatuhan.",
    durationMin: 13,
    tags: ["reformasi", "coretax", "NIK NPWP", "kepatuhan"],
    blocks: [
      {
        type: "paragraph",
        html: "Tax ratio Indonesia yang berkisar 10-11% tergolong rendah dibanding negara sekawasan. Penyebabnya antara lain basis pajak yang sempit, besarnya sektor informal, serta tingkat <strong>kepatuhan</strong> wajib pajak yang belum optimal. <strong>Reformasi perpajakan</strong> berfokus memperluas basis dan memperbaiki administrasi agar penerimaan naik tanpa selalu menaikkan tarif.",
      },
      {
        type: "paragraph",
        html: "Langkah kunci reformasi: integrasi <strong>NIK sebagai NPWP</strong> agar setiap penduduk terhubung ke sistem pajak, pembangunan sistem administrasi terpadu <strong>Coretax</strong> untuk modernisasi layanan, perluasan basis pajak ke ekonomi digital, dan program peningkatan kepatuhan melalui data dan pengawasan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "NIK menjadi NPWP",
        html: "Mulai diberlakukan penuh, <strong>NIK</strong> (Nomor Induk Kependudukan) digunakan sebagai NPWP orang pribadi. Tujuannya menyederhanakan administrasi dan memperluas cakupan wajib pajak melalui satu basis data kependudukan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Coretax",
        html: "<strong>Coretax</strong> adalah sistem inti administrasi perpajakan baru DJP yang mengintegrasikan pendaftaran, pelaporan, pembayaran, dan pengawasan dalam satu platform digital untuk meningkatkan efisiensi dan kepatuhan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bukan sekadar menaikkan tarif",
        html: "Menaikkan tarif tanpa memperluas basis berisiko menekan kelompok yang sudah patuh dan mendorong penghindaran pajak. Perluasan basis dan perbaikan kepatuhan lebih berkelanjutan.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren Tax Ratio Indonesia (ilustrasi)",
        unit: "% PDB",
        source: "ilustrasi pola umum",
        note: "Target reformasi adalah menaikkan tax ratio secara bertahap.",
        data: [
          { label: "2020", value: 8.3, color: "#0ea5e9" },
          { label: "2021", value: 9.1, color: "#0ea5e9" },
          { label: "2022", value: 10.4, color: "#10b981" },
          { label: "2023", value: 10.2, color: "#10b981" },
          { label: "2024", value: 10.1, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dampak menaikkan tax ratio 1%",
        html: "Dengan PDB sekitar Rp22.000 triliun, menaikkan tax ratio sebesar <strong>1 poin persen</strong> setara tambahan penerimaan Rp220 triliun per tahun. Angka ini cukup untuk membiayai banyak program prioritas tanpa menambah utang, sehingga reformasi basis pajak bernilai sangat strategis.",
      },
      {
        type: "calcExercise",
        prompt: "PDB Rp22.000 triliun. Jika tax ratio naik dari 10% menjadi 11%, berapa tambahan penerimaan pajak (triliun rupiah)?",
        answer: 220,
        tolerance: 0,
        suffix: " T",
        solution: "Kenaikan 1% x Rp22.000 T = <strong>Rp220 triliun</strong>.",
        hint: "Selisih tax ratio (1%) dikalikan PDB.",
      },
      {
        type: "classifyExercise",
        prompt: "Apakah langkah ini bagian dari reformasi perpajakan (perluasan basis & administrasi) atau bukan?",
        buckets: ["Reformasi Perpajakan", "Bukan Reformasi"],
        items: [
          { text: "Integrasi NIK sebagai NPWP", bucket: "Reformasi Perpajakan" },
          { text: "Penerapan sistem Coretax", bucket: "Reformasi Perpajakan" },
          { text: "Perluasan basis ke ekonomi digital", bucket: "Reformasi Perpajakan" },
          { text: "Mencetak uang untuk menutup defisit", bucket: "Bukan Reformasi" },
          { text: "Menjual aset negara satu kali", bucket: "Bukan Reformasi" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan langkah reformasi perpajakan dengan tujuannya.",
        pairs: [
          { left: "NIK sebagai NPWP", right: "Menyatukan basis data wajib pajak" },
          { left: "Coretax", right: "Modernisasi administrasi DJP" },
          { left: "Perluasan basis ke ekonomi digital", right: "Menjangkau transaksi yang belum terpajaki" },
          { left: "Program kepatuhan", right: "Meningkatkan ketaatan wajib pajak" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Tax Ratio Antarnegara (ilustrasi)",
        unit: "% PDB",
        source: "ilustrasi pola umum",
        note: "Tax ratio Indonesia tertinggal dibanding beberapa negara sekawasan dan maju.",
        data: [
          { label: "Indonesia", value: 10, color: "#ef4444" },
          { label: "Vietnam", value: 19, color: "#f59e0b" },
          { label: "Malaysia", value: 12, color: "#0ea5e9" },
          { label: "Rata-rata OECD", value: 34, color: "#10b981" },
        ],
      },
      {
        type: "video",
        comp: "ReformasiPerpajakan",
        title: "Video: Reformasi Perpajakan",
        caption: "Animasi perluasan basis pajak, integrasi NIK sebagai NPWP, dan sistem Coretax.",
      },
      {
        type: "case",
        title: "Sejarah: Tax amnesty 2016 sebagai langkah reformasi",
        html: "Salah satu episode besar reformasi perpajakan adalah <strong>tax amnesty 2016-2017</strong> yang menarik uang tebusan sekitar <strong>Rp114 triliun</strong> dan deklarasi harta sekitar Rp4.800 triliun. Program ini bertujuan memperluas basis pajak dan memutakhirkan data wajib pajak, bukan sekadar menaikkan tarif. Datanya menjadi pondasi bagi reformasi lanjutan seperti integrasi <strong>NIK sebagai NPWP</strong> dan sistem Coretax.",
      },
      {
        type: "takeaways",
        items: [
          "Tax ratio Indonesia rendah karena basis sempit dan kepatuhan belum optimal.",
          "Reformasi mengutamakan perluasan basis, bukan hanya kenaikan tarif.",
          "NIK menjadi NPWP menyatukan basis data wajib pajak.",
          "Coretax memodernisasi administrasi dan mendorong kepatuhan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Salah satu sebab tax ratio Indonesia rendah adalah?",
            options: ["Basis pajak sempit", "Tarif terlalu tinggi", "Tidak ada pajak", "PDB terlalu kecil"],
            answer: 0,
            explain: "Basis pajak yang sempit dan sektor informal besar membuat tax ratio rendah.",
          },
          {
            q: "NIK menjadi NPWP bertujuan untuk?",
            options: ["Menaikkan tarif PPN", "Menyatukan basis data dan memperluas cakupan wajib pajak", "Menghapus pajak", "Mengurangi PNBP"],
            answer: 1,
            explain: "Integrasi NIK-NPWP menyederhanakan administrasi dan memperluas cakupan wajib pajak.",
          },
          {
            q: "Coretax adalah?",
            options: ["Jenis pajak baru", "Sistem inti administrasi perpajakan DJP", "Nama BUMN", "Tarif cukai"],
            answer: 1,
            explain: "Coretax adalah sistem administrasi perpajakan terpadu milik DJP.",
          },
          {
            q: "Fokus utama reformasi perpajakan yang berkelanjutan adalah?",
            options: ["Menaikkan tarif setinggi mungkin", "Perluasan basis dan peningkatan kepatuhan", "Menambah utang", "Mengurangi belanja"],
            answer: 1,
            explain: "Reformasi menekankan perluasan basis dan kepatuhan, bukan sekadar menaikkan tarif.",
          },
          {
            q: "PDB Rp20.000 T, tax ratio naik 1%. Tambahan penerimaan?",
            options: ["Rp20 T", "Rp200 T", "Rp2.000 T", "Rp100 T"],
            answer: 1,
            explain: "1% x Rp20.000 T = Rp200 triliun.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "cukai-dan-kepabeanan",
    levelId: "penerimaan",
    order: 5,
    title: "Cukai & Kepabeanan",
    summary: "Penerimaan yang dikelola Bea dan Cukai: cukai atas barang yang dibatasi, bea masuk, dan bea keluar, serta fungsi pengendaliannya bukan sekadar pemasukan.",
    durationMin: 13,
    tags: ["cukai", "bea masuk", "bea keluar", "DJBC", "CHT"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain pajak yang dikelola DJP, ada penerimaan negara yang dipungut <strong>Direktorat Jenderal Bea dan Cukai (DJBC)</strong>. Dua kelompoknya: <strong>cukai</strong> atas barang tertentu yang peredarannya dibatasi, dan <strong>kepabeanan</strong> berupa <strong>bea masuk</strong> (atas impor) serta <strong>bea keluar</strong> (atas ekspor komoditas tertentu).",
      },
      {
        type: "paragraph",
        html: "Di Indonesia hanya tiga <strong>Barang Kena Cukai (BKC)</strong> yang dipungut cukai: <strong>hasil tembakau</strong> (rokok), <strong>etil alkohol</strong>, dan <strong>minuman mengandung etil alkohol (MMEA)</strong>. Cukai berbeda dari pajak biasa karena tujuan utamanya <strong>mengendalikan konsumsi</strong> barang yang menimbulkan dampak negatif, sementara penerimaan adalah efek sampingnya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cukai = pengendalian, bukan sekadar pemasukan",
        html: "Barang kena cukai dikenai pungutan karena konsumsinya perlu <strong>dibatasi</strong> (kesehatan, ketertiban). Maka tarif cukai juga dipakai sebagai alat kebijakan, misalnya menaikkan harga rokok agar konsumsi turun.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bea masuk dan bea keluar",
        html: "<strong>Bea masuk</strong> dikenakan atas barang impor, antara lain untuk melindungi industri dalam negeri. <strong>Bea keluar</strong> dikenakan atas ekspor komoditas tertentu (mis. produk sawit atau mineral) untuk menjaga pasokan dalam negeri dan mendorong hilirisasi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hubungkan ke penerimaan negara",
        html: "Cukai dan bea adalah bagian dari penerimaan perpajakan. Gunakan kalkulator untuk melihat dampak penerimaan terhadap tax ratio.",
      },
      { type: "widget", widget: "KalkulatorTaxRatio" },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Penerimaan Cukai Indonesia",
        unit: "% penerimaan cukai",
        source: "pola umum penerimaan cukai, Kemenkeu/DJBC",
        note: "Cukai hasil tembakau menyumbang sekitar 95% penerimaan cukai; etil alkohol dan MMEA sangat kecil.",
        data: [
          { label: "Hasil tembakau (CHT)", value: 95, color: "#ef4444" },
          { label: "MMEA", value: 4, color: "#0ea5e9" },
          { label: "Etil alkohol", value: 1, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Cukai sebungkus rokok",
        html: "Misalkan tarif cukai hasil tembakau sebuah merek Rp800 per batang (ilustrasi). Untuk sebungkus berisi 16 batang, cukai yang melekat = 16 x Rp800 = <strong>Rp12.800</strong> per bungkus. Itu baru cukai, belum termasuk PPN hasil tembakau dan margin. Karena itu kenaikan tarif cukai langsung terasa pada harga jual eceran rokok.",
      },
      {
        type: "calcExercise",
        prompt: "Tarif cukai Rp800 per batang. Sebungkus berisi 16 batang. Berapa cukai yang melekat per bungkus (rupiah)?",
        answer: 12800,
        tolerance: 0,
        prefix: "Rp",
        solution: "Cukai = 16 x Rp800 = <strong>Rp12.800</strong> per bungkus.",
        hint: "Kalikan jumlah batang dengan tarif cukai per batang.",
      },
      {
        type: "classifyExercise",
        prompt: "Mana yang termasuk Barang Kena Cukai di Indonesia, dan mana yang bukan?",
        buckets: ["Barang Kena Cukai", "Bukan Barang Kena Cukai"],
        items: [
          { text: "Rokok (hasil tembakau)", bucket: "Barang Kena Cukai" },
          { text: "Minuman beralkohol (MMEA)", bucket: "Barang Kena Cukai" },
          { text: "Etil alkohol", bucket: "Barang Kena Cukai" },
          { text: "Beras", bucket: "Bukan Barang Kena Cukai" },
          { text: "Buku pelajaran", bucket: "Bukan Barang Kena Cukai" },
        ],
      },
      {
        type: "video",
        comp: "SumberPenerimaanNegara",
        title: "Video: Sumber Penerimaan Negara",
        caption: "Cukai dan bea sebagai bagian penerimaan perpajakan di samping pajak.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Penerimaan yang Dikelola Bea dan Cukai (ilustrasi)",
        unit: "Rp triliun",
        source: "ilustrasi pola umum, DJBC",
        note: "Cukai (terutama hasil tembakau) jauh lebih besar daripada bea masuk dan bea keluar.",
        data: [
          { label: "Cukai", value: 220, color: "#ef4444" },
          { label: "Bea masuk", value: 50, color: "#0ea5e9" },
          { label: "Bea keluar", value: 20, color: "#f59e0b" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah kepabeanan dan cukai dengan maknanya.",
        pairs: [
          { left: "Cukai", right: "Pungutan atas barang yang dibatasi peredarannya" },
          { left: "Bea masuk", right: "Pungutan atas barang impor" },
          { left: "Bea keluar", right: "Pungutan atas ekspor komoditas tertentu" },
          { left: "CHT", right: "Cukai hasil tembakau, penyumbang cukai terbesar" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Kenaikan tarif cukai rokok 2020",
        html: "Pada <strong>2020</strong>, pemerintah menaikkan tarif <strong>cukai hasil tembakau</strong> rata-rata sekitar <strong>23%</strong>, kenaikan yang tergolong besar. Tujuannya ganda: menambah penerimaan negara sekaligus menekan konsumsi rokok demi kesehatan masyarakat. Kebijakan ini menegaskan watak cukai sebagai instrumen <strong>pengendalian</strong>, sebab tarif sengaja dipakai untuk mengubah perilaku, bukan semata mengejar pemasukan.",
      },
      {
        type: "takeaways",
        items: [
          "DJBC memungut cukai serta bea masuk dan bea keluar.",
          "Hanya tiga BKC: hasil tembakau, etil alkohol, dan MMEA.",
          "Cukai hasil tembakau menyumbang sekitar 95% penerimaan cukai.",
          "Cukai bertujuan mengendalikan konsumsi, bukan sekadar pemasukan.",
          "Bea masuk melindungi industri; bea keluar menjaga pasokan domestik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Lembaga yang memungut cukai dan bea adalah?",
            options: ["DJP", "DJBC (Bea dan Cukai)", "OJK", "Bank Indonesia"],
            answer: 1,
            explain: "Cukai dan kepabeanan dikelola Direktorat Jenderal Bea dan Cukai.",
          },
          {
            q: "Manakah Barang Kena Cukai di Indonesia?",
            options: ["Beras", "Hasil tembakau", "Buku", "Sayur"],
            answer: 1,
            explain: "BKC di Indonesia: hasil tembakau, etil alkohol, dan MMEA.",
          },
          {
            q: "Tujuan utama pungutan cukai adalah?",
            options: ["Mengendalikan konsumsi barang tertentu", "Menaikkan ekspor", "Mengganti PPN", "Membayar gaji ASN"],
            answer: 0,
            explain: "Cukai dikenakan agar konsumsi barang yang berdampak negatif dibatasi.",
          },
          {
            q: "Bea keluar dikenakan atas?",
            options: ["Barang impor", "Ekspor komoditas tertentu", "Gaji", "Tabungan"],
            answer: 1,
            explain: "Bea keluar dipungut atas ekspor komoditas tertentu, mis. produk sawit.",
          },
          {
            q: "Tarif cukai Rp1.000/batang, sebungkus 12 batang. Cukai per bungkus?",
            options: ["Rp10.000", "Rp12.000", "Rp1.200", "Rp120.000"],
            answer: 1,
            explain: "12 x Rp1.000 = Rp12.000.",
          },
        ],
      },
    ],
  },
];
