import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "apa-itu-kebijakan-fiskal",
    levelId: "dasar",
    order: 1,
    title: "Apa Itu Kebijakan Fiskal?",
    summary: "Bagaimana pemerintah memakai belanja dan pajak untuk mengelola ekonomi, lewat tiga fungsi utamanya. Dengan video.",
    durationMin: 13,
    tags: ["kebijakan fiskal", "APBN", "fungsi fiskal"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Kebijakan fiskal</strong> adalah kebijakan pemerintah mengatur <strong>penerimaan</strong> (terutama pajak) dan <strong>belanja</strong> negara untuk memengaruhi perekonomian. Instrumen utamanya adalah <strong>APBN</strong> (Anggaran Pendapatan dan Belanja Negara). Berbeda dari kebijakan moneter yang dijalankan Bank Indonesia, kebijakan fiskal dijalankan pemerintah.",
      },
      {
        type: "video",
        comp: "FungsiFiskal",
        title: "Video: Tiga Fungsi Kebijakan Fiskal",
        caption: "Animasi fungsi alokasi, distribusi, dan stabilisasi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga fungsi fiskal",
        html: "<strong>Alokasi</strong>: menyediakan barang publik (jalan, sekolah, pertahanan). <strong>Distribusi</strong>: memeratakan lewat pajak progresif, subsidi, dan bansos. <strong>Stabilisasi</strong>: meredam gejolak ekonomi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ekspansif vs kontraktif",
        html: "<strong>Ekspansif</strong>: menambah belanja dan/atau menurunkan pajak untuk mendorong ekonomi saat lesu. <strong>Kontraktif</strong>: kebalikannya, untuk meredam ekonomi yang terlalu panas.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Porsi Tiga Fungsi dalam Belanja Negara (ilustrasi)",
        unit: "% belanja",
        source: "ilustrasi edukatif",
        note: "Ketiga fungsi sering tumpang tindih dalam satu pos belanja.",
        data: [
          { label: "Alokasi (barang publik)", value: 45, color: "#10b981" },
          { label: "Distribusi (subsidi/bansos)", value: 35, color: "#0ea5e9" },
          { label: "Stabilisasi", value: 20, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Stimulus saat pandemi",
        html: "Saat pandemi 2020 menekan ekonomi, pemerintah menjalankan kebijakan fiskal <strong>ekspansif</strong>: menambah belanja kesehatan dan bansos, serta memberi insentif pajak. Defisit APBN melebar sementara (sempat dilonggarkan dari batas 3% PDB lewat Perppu) untuk menahan ekonomi agar tidak jatuh lebih dalam. Ini contoh fungsi stabilisasi.",
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan negara Rp2.000 triliun, belanja Rp2.500 triliun. Berapa defisit anggaran (triliun)?",
        answer: 500,
        tolerance: 0,
        solution: "Defisit = belanja - pendapatan = 2.500 - 2.000 = <strong>Rp500 triliun</strong>.",
        hint: "Defisit terjadi saat belanja melebihi pendapatan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kebijakan ini termasuk fungsi fiskal yang mana?",
        buckets: ["Alokasi", "Distribusi", "Stabilisasi"],
        items: [
          { text: "Membangun jalan tol dan sekolah", bucket: "Alokasi" },
          { text: "Bansos untuk keluarga miskin", bucket: "Distribusi" },
          { text: "Menambah belanja saat resesi", bucket: "Stabilisasi" },
          { text: "Pajak progresif untuk yang kaya", bucket: "Distribusi" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Struktur APBN: Pendapatan, Belanja, dan Defisit (ilustrasi)",
        unit: "Rp triliun",
        source: "ilustrasi edukatif",
        note: "Defisit muncul saat belanja melebihi pendapatan: 2.500 - 2.000 = 500.",
        data: [
          { label: "Pendapatan", value: 2000, color: "#10b981" },
          { label: "Belanja", value: 2500, color: "#0ea5e9" },
          { label: "Defisit", value: 500, color: "#ef4444" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah kebijakan fiskal dengan penjelasannya.",
        pairs: [
          { left: "Penerimaan negara terbesar", right: "Pajak" },
          { left: "Instrumen utama kebijakan fiskal", right: "APBN" },
          { left: "Belanja melebihi pendapatan", right: "Defisit" },
          { left: "Menyediakan barang publik", right: "Fungsi alokasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: New Deal Amerika Serikat",
        html: "Saat <strong>Depresi Besar</strong> melanda Amerika Serikat pada 1930-an, pemerintahan Presiden Franklin D. Roosevelt menjalankan program <strong>New Deal</strong> (mulai 1933) dengan belanja pemerintah besar-besaran untuk proyek publik dan penciptaan lapangan kerja. Ini contoh klasik kebijakan fiskal <strong>ekspansif</strong>: negara sengaja memperbesar belanja untuk menarik ekonomi keluar dari resesi. Peristiwa ini menegaskan bahwa belanja dan penerimaan negara bisa dipakai sebagai alat mengelola perekonomian.",
      },
      {
        type: "takeaways",
        items: [
          "Kebijakan fiskal mengatur penerimaan dan belanja negara lewat APBN.",
          "Dijalankan pemerintah (berbeda dari moneter oleh BI).",
          "Tiga fungsi: alokasi, distribusi, stabilisasi.",
          "Ekspansif mendorong ekonomi; kontraktif meredam.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kebijakan fiskal dijalankan oleh?",
            options: ["Bank Indonesia", "Pemerintah lewat APBN", "OJK", "Bursa Efek"],
            answer: 1,
            explain: "Kebijakan fiskal dijalankan pemerintah melalui penerimaan dan belanja (APBN).",
          },
          {
            q: "Menyediakan jalan dan sekolah adalah fungsi?",
            options: ["Alokasi", "Distribusi", "Stabilisasi", "Spekulasi"],
            answer: 0,
            explain: "Menyediakan barang publik adalah fungsi alokasi.",
          },
          {
            q: "Kebijakan fiskal ekspansif berarti?",
            options: ["Kurangi belanja, naikkan pajak", "Tambah belanja dan/atau turunkan pajak", "Tidak berbuat apa-apa", "Menaikkan suku bunga"],
            answer: 1,
            explain: "Ekspansif mendorong ekonomi lewat tambahan belanja atau pengurangan pajak.",
          },
          {
            q: "Instrumen utama kebijakan fiskal adalah?",
            options: ["Suku bunga", "APBN (pajak & belanja)", "Nilai tukar", "Cadangan devisa"],
            answer: 1,
            explain: "APBN, lewat penerimaan dan belanja, adalah instrumen kebijakan fiskal.",
          },
          {
            q: "Pendapatan Rp1.800 T, belanja Rp2.100 T. Defisit?",
            options: ["Rp300 T", "Rp3.900 T", "Surplus Rp300 T", "Nol"],
            answer: 0,
            explain: "2.100 - 1.800 = Rp300 triliun defisit.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "fungsi-fiskal",
    levelId: "dasar",
    order: 2,
    title: "Tiga Fungsi Fiskal: Alokasi, Distribusi, Stabilisasi",
    summary: "Memahami secara rinci tiga fungsi kebijakan fiskal lewat contoh nyata di APBN Indonesia.",
    durationMin: 13,
    tags: ["fungsi fiskal", "alokasi", "distribusi", "stabilisasi", "APBN"],
    blocks: [
      {
        type: "paragraph",
        html: "Kebijakan fiskal punya <strong>tiga fungsi</strong> klasik yang sering tumpang tindih dalam satu APBN. <strong>Alokasi</strong> menyediakan barang dan jasa publik yang tidak disediakan pasar. <strong>Distribusi</strong> memeratakan pendapatan antarwarga dan antardaerah. <strong>Stabilisasi</strong> menjaga ekonomi tetap stabil saat ada gejolak.",
      },
      {
        type: "paragraph",
        html: "Di Indonesia, satu pos belanja bisa melayani lebih dari satu fungsi sekaligus. Subsidi BBM, misalnya, sebagian bersifat distribusi (membantu rakyat) sekaligus stabilisasi (menahan inflasi saat harga minyak dunia naik).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Fungsi alokasi",
        html: "Pemerintah menyediakan <strong>barang publik</strong> yang sulit dijual per unit di pasar: jalan, jembatan, pertahanan, penegakan hukum, dan pendidikan dasar. Contoh APBN: belanja infrastruktur dan anggaran pendidikan 20% sesuai amanat konstitusi.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Fungsi distribusi",
        html: "Memeratakan kesejahteraan lewat <strong>pajak progresif</strong> (PPh orang kaya bertarif lebih tinggi), <strong>subsidi</strong>, <strong>bansos</strong> (PKH, BPNT), dan <strong>Dana Alokasi Umum</strong> ke daerah tertinggal.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Fungsi stabilisasi",
        html: "Meredam gejolak: menambah belanja saat ekonomi lesu, atau menahan belanja saat ekonomi terlalu panas, agar inflasi dan pengangguran tetap terkendali.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Contoh Pos Belanja per Fungsi (ilustrasi APBN)",
        unit: "Rp triliun",
        source: "ilustrasi edukatif berbasis pola APBN",
        note: "Angka disederhanakan untuk pembelajaran.",
        data: [
          { label: "Infrastruktur (alokasi)", value: 420, color: "#10b981" },
          { label: "Pendidikan (alokasi)", value: 660, color: "#22c55e" },
          { label: "Bansos (distribusi)", value: 500, color: "#0ea5e9" },
          { label: "Subsidi (distribusi)", value: 300, color: "#38bdf8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Program Keluarga Harapan (PKH)",
        html: "PKH menyalurkan bantuan tunai bersyarat ke keluarga miskin. Misal 10 juta keluarga penerima dengan rata-rata Rp2,4 juta per tahun, total anggaran = 10 juta x Rp2,4 juta = <strong>Rp24 triliun</strong>. Ini murni fungsi <strong>distribusi</strong>: memindahkan daya beli ke kelompok rentan.",
      },
      {
        type: "calcExercise",
        prompt: "Total APBN belanja Rp2.500 triliun. Anggaran pendidikan wajib minimal 20%. Berapa anggaran pendidikan minimal (triliun)?",
        answer: 500,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "20% x 2.500 = 0,20 x 2.500 = <strong>Rp500 triliun</strong>.",
        hint: "Kalikan total belanja dengan 20%.",
      },
      {
        type: "classifyExercise",
        prompt: "Setiap kebijakan ini paling tepat masuk fungsi yang mana?",
        buckets: ["Alokasi", "Distribusi", "Stabilisasi"],
        items: [
          { text: "Membangun bendungan dan irigasi", bucket: "Alokasi" },
          { text: "PPh progresif untuk berpenghasilan tinggi", bucket: "Distribusi" },
          { text: "Tambah belanja saat pertumbuhan melambat", bucket: "Stabilisasi" },
          { text: "Dana Desa untuk daerah tertinggal", bucket: "Distribusi" },
          { text: "Anggaran pertahanan dan kepolisian", bucket: "Alokasi" },
        ],
      },
      {
        type: "chart",
        variant: "area",
        title: "Tren Anggaran Bansos (fungsi distribusi, ilustrasi)",
        unit: "Rp triliun",
        source: "ilustrasi edukatif berbasis pola APBN",
        note: "Belanja distribusi cenderung naik saat kebutuhan perlindungan sosial meningkat.",
        data: [
          { label: "2019", value: 310, color: "#0ea5e9" },
          { label: "2020", value: 498, color: "#38bdf8" },
          { label: "2021", value: 468, color: "#0ea5e9" },
          { label: "2022", value: 431, color: "#38bdf8" },
          { label: "2023", value: 476, color: "#0ea5e9" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Dana Desa diberikan Rp1 miliar per desa untuk 75.000 desa. Berapa total anggaran (triliun)?",
        answer: 75,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "Total = Rp1 miliar x 75.000 = 75.000 miliar = <strong>Rp75 triliun</strong> (1.000 miliar = 1 triliun).",
        hint: "1.000 miliar sama dengan 1 triliun.",
      },
      {
        type: "case",
        title: "Sejarah: Stimulus fiskal krisis global 2008",
        html: "Ketika krisis keuangan global 2008 mengancam ekonomi, Indonesia meluncurkan paket <strong>stimulus fiskal sekitar Rp73 triliun</strong> pada 2009 berupa keringanan pajak dan tambahan belanja infrastruktur. Langkah ini wujud nyata fungsi <strong>stabilisasi</strong>: pemerintah menambah dorongan ke ekonomi agar pertumbuhan tidak anjlok. Indonesia pun tetap tumbuh sekitar 4,6% pada 2009 saat banyak negara mengalami resesi.",
      },
      {
        type: "takeaways",
        items: [
          "Alokasi menyediakan barang publik yang tak disediakan pasar.",
          "Distribusi memeratakan lewat pajak progresif, subsidi, dan bansos.",
          "Stabilisasi meredam gejolak ekonomi.",
          "Satu pos APBN bisa melayani beberapa fungsi sekaligus.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Anggaran pendidikan 20% APBN adalah contoh fungsi?",
            options: ["Distribusi", "Alokasi", "Stabilisasi", "Spekulasi"],
            answer: 1,
            explain: "Pendidikan dasar adalah barang publik, masuk fungsi alokasi.",
          },
          {
            q: "Pajak progresif untuk orang kaya mencerminkan fungsi?",
            options: ["Alokasi", "Stabilisasi", "Distribusi", "Moneter"],
            answer: 2,
            explain: "Pajak progresif memeratakan pendapatan, yaitu fungsi distribusi.",
          },
          {
            q: "Menambah belanja saat ekonomi lesu termasuk fungsi?",
            options: ["Stabilisasi", "Alokasi", "Distribusi", "Privatisasi"],
            answer: 0,
            explain: "Meredam gejolak siklus ekonomi adalah fungsi stabilisasi.",
          },
          {
            q: "PKH 8 juta keluarga x Rp2 juta/tahun butuh anggaran?",
            options: ["Rp16 triliun", "Rp1,6 triliun", "Rp160 triliun", "Rp16 miliar"],
            answer: 0,
            explain: "8 juta x Rp2 juta = Rp16 triliun.",
          },
          {
            q: "Pernyataan yang benar tentang fungsi fiskal?",
            options: ["Satu pos hanya boleh satu fungsi", "Subsidi bisa melayani distribusi dan stabilisasi", "Alokasi mengurus pajak progresif", "Stabilisasi hanya soal infrastruktur"],
            answer: 1,
            explain: "Subsidi BBM membantu rakyat (distribusi) sekaligus menahan inflasi (stabilisasi).",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekspansif-vs-kontraktif",
    levelId: "dasar",
    order: 3,
    title: "Fiskal Ekspansif vs Kontraktif",
    summary: "Kapan pemerintah mendorong atau merem ekonomi, dampaknya, dan peran automatic stabilizer.",
    durationMin: 14,
    tags: ["ekspansif", "kontraktif", "automatic stabilizer", "siklus ekonomi"],
    blocks: [
      {
        type: "paragraph",
        html: "Arah kebijakan fiskal mengikuti kondisi ekonomi. <strong>Fiskal ekspansif</strong> dipakai saat ekonomi <strong>lesu atau resesi</strong>: pemerintah menambah belanja dan/atau memangkas pajak agar permintaan naik. <strong>Fiskal kontraktif</strong> dipakai saat ekonomi <strong>terlalu panas</strong> dan inflasi tinggi: belanja ditahan dan/atau pajak dinaikkan.",
      },
      {
        type: "paragraph",
        html: "Sebagian penyesuaian terjadi <strong>otomatis</strong> tanpa keputusan baru. Inilah <strong>automatic stabilizer</strong>: saat resesi, penerimaan pajak turun (karena pendapatan turun) dan belanja bansos/jaminan sosial naik, sehingga ekonomi tertahan tanpa perlu kebijakan baru.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kapan ekspansif?",
        html: "Saat pertumbuhan melambat, pengangguran naik, atau resesi. Tujuannya menaikkan permintaan agregat. Risikonya: <strong>defisit melebar</strong> dan utang naik.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kapan kontraktif?",
        html: "Saat ekonomi <strong>overheating</strong> dan inflasi tinggi. Belanja direm dan/atau pajak dinaikkan untuk mendinginkan permintaan. Risikonya: pertumbuhan bisa melambat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Automatic stabilizer",
        html: "Mekanisme yang bekerja sendiri mengikuti siklus: <strong>pajak progresif</strong> dan <strong>bansos</strong>. Saat ekonomi turun, pajak otomatis berkurang dan bantuan otomatis bertambah, meredam guncangan tanpa keputusan baru.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Defisit APBN terhadap PDB sepanjang Siklus (ilustrasi)",
        unit: "% PDB",
        source: "ilustrasi edukatif",
        note: "Defisit cenderung melebar saat ekonomi lesu (fiskal ekspansif/automatic stabilizer).",
        data: [
          { label: "2019 (normal)", value: 2.2, color: "#0ea5e9" },
          { label: "2020 (resesi)", value: 6.1, color: "#ef4444" },
          { label: "2021 (pemulihan)", value: 4.6, color: "#f59e0b" },
          { label: "2022 (konsolidasi)", value: 2.4, color: "#10b981" },
          { label: "2023 (normal)", value: 1.6, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Konsolidasi fiskal 2022-2023",
        html: "Setelah defisit melebar saat pandemi, pemerintah kembali ke disiplin <strong>defisit maksimal 3% PDB</strong> pada 2023. Belanja darurat dikurangi dan penerimaan pulih, sehingga defisit menyempit. Ini contoh pergeseran dari ekspansif menuju arah lebih <strong>kontraktif/konsolidatif</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "PDB Rp20.000 triliun. Batas defisit aman 3% PDB. Berapa defisit maksimal (triliun)?",
        answer: 600,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "3% x 20.000 = 0,03 x 20.000 = <strong>Rp600 triliun</strong>.",
        hint: "Kalikan PDB dengan 3%.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kondisi dengan respons fiskal yang tepat.",
        pairs: [
          { left: "Resesi, pengangguran naik", right: "Fiskal ekspansif" },
          { left: "Inflasi tinggi, ekonomi panas", right: "Fiskal kontraktif" },
          { left: "Pajak turun otomatis saat resesi", right: "Automatic stabilizer" },
          { left: "Bansos naik otomatis saat krisis", right: "Automatic stabilizer" },
        ],
      },
      {
        type: "video",
        comp: "EkspansifKontraktif",
        title: "Video: Fiskal Ekspansif vs Kontraktif",
        caption: "Animasi arah kebijakan fiskal mengikuti siklus ekonomi.",
      },
      {
        type: "widget",
        widget: "SimulatorStabilisasiFiskal",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Arah Fiskal terhadap Permintaan Agregat (ilustrasi)",
        unit: "indeks dorongan",
        source: "ilustrasi edukatif",
        note: "Ekspansif mendorong permintaan; kontraktif menahannya.",
        data: [
          { label: "Ekspansif (tambah belanja)", value: 8, color: "#10b981" },
          { label: "Netral", value: 0, color: "#94a3b8" },
          { label: "Kontraktif (rem belanja)", value: -6, color: "#ef4444" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini termasuk fiskal ekspansif atau kontraktif?",
        buckets: ["Ekspansif", "Kontraktif"],
        items: [
          { text: "Menambah belanja infrastruktur saat resesi", bucket: "Ekspansif" },
          { text: "Menaikkan tarif pajak saat inflasi tinggi", bucket: "Kontraktif" },
          { text: "Memberi insentif pajak saat ekonomi lesu", bucket: "Ekspansif" },
          { text: "Menahan belanja saat ekonomi terlalu panas", bucket: "Kontraktif" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Defisit melebar saat pandemi COVID-19",
        html: "Menghadapi pandemi <strong>COVID-19</strong> pada 2020, pemerintah menempuh kebijakan fiskal sangat <strong>ekspansif</strong>. Lewat <strong>Perppu 1/2020</strong>, batas defisit yang biasanya maksimal 3% PDB dilonggarkan, dan realisasi defisit 2020 mencapai sekitar <strong>6,1% PDB</strong>. Setelah ekonomi pulih, arah kebijakan bergeser kembali ke konsolidasi untuk menurunkan defisit.",
      },
      {
        type: "takeaways",
        items: [
          "Ekspansif dipakai saat ekonomi lesu; kontraktif saat ekonomi panas.",
          "Ekspansif memperlebar defisit; kontraktif menyempitkan.",
          "Automatic stabilizer bekerja sendiri lewat pajak progresif dan bansos.",
          "Indonesia menjaga batas defisit maksimal 3% PDB.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Saat resesi, kebijakan fiskal yang tepat adalah?",
            options: ["Kontraktif", "Ekspansif", "Netral total", "Menaikkan suku bunga"],
            answer: 1,
            explain: "Saat resesi pemerintah menambah belanja/memangkas pajak (ekspansif).",
          },
          {
            q: "Contoh automatic stabilizer adalah?",
            options: ["Keputusan baru naikkan belanja", "Pajak turun otomatis saat pendapatan turun", "BI menurunkan suku bunga", "Devaluasi rupiah"],
            answer: 1,
            explain: "Automatic stabilizer bekerja tanpa keputusan baru, seperti pajak yang otomatis turun.",
          },
          {
            q: "Fiskal kontraktif cocok ketika?",
            options: ["Inflasi tinggi/ekonomi panas", "Pengangguran tinggi", "Resesi dalam", "Deflasi parah"],
            answer: 0,
            explain: "Kontraktif mendinginkan ekonomi yang terlalu panas.",
          },
          {
            q: "PDB Rp22.000 T, batas defisit 3%. Defisit maksimal?",
            options: ["Rp660 T", "Rp66 T", "Rp6.600 T", "Rp330 T"],
            answer: 0,
            explain: "3% x 22.000 = Rp660 triliun.",
          },
          {
            q: "Dampak khas fiskal ekspansif terhadap APBN?",
            options: ["Defisit menyempit", "Defisit cenderung melebar", "Selalu surplus", "Tidak berpengaruh"],
            answer: 1,
            explain: "Menambah belanja/memangkas pajak cenderung memperlebar defisit.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "fiskal-vs-moneter",
    levelId: "dasar",
    order: 4,
    title: "Fiskal vs Moneter: Beda dan Sinergi",
    summary: "Perbedaan kebijakan fiskal pemerintah dan moneter BI, serta pentingnya bauran kebijakan.",
    durationMin: 13,
    tags: ["kebijakan moneter", "Bank Indonesia", "bauran kebijakan", "policy mix"],
    blocks: [
      {
        type: "paragraph",
        html: "Ada dua tuas besar pengelola ekonomi makro. <strong>Kebijakan fiskal</strong> dipegang <strong>pemerintah</strong> lewat APBN (pajak dan belanja). <strong>Kebijakan moneter</strong> dipegang <strong>Bank Indonesia</strong> lewat suku bunga acuan (BI-Rate), pengelolaan likuiditas, dan nilai tukar. Keduanya berbeda pelaku dan instrumen.",
      },
      {
        type: "paragraph",
        html: "Meski terpisah, keduanya harus selaras. Ketika dipadukan, lahirlah <strong>bauran kebijakan</strong> (policy mix): pemerintah dan BI mengoordinasikan langkah agar pertumbuhan terjaga dan inflasi terkendali tanpa saling menggagalkan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Siapa pegang apa",
        html: "<strong>Fiskal</strong>: pemerintah, instrumen pajak dan belanja (APBN), tujuan pertumbuhan dan pemerataan. <strong>Moneter</strong>: Bank Indonesia, instrumen suku bunga dan likuiditas, tujuan utama menjaga inflasi dan stabilitas rupiah.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bauran kebijakan (policy mix)",
        html: "Saat ekonomi lesu, fiskal ekspansif (tambah belanja) bisa dipadu moneter longgar (turunkan BI-Rate) agar dorongan ke ekonomi makin kuat dan saling menguatkan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Jika tidak selaras",
        html: "Bila fiskal sangat ekspansif tapi moneter sangat ketat, dampaknya bisa saling meniadakan: defisit besar tertekan suku bunga tinggi, biaya utang naik, dan efek stimulus berkurang.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Pembagian Peran Pengelola Ekonomi Makro",
        unit: "fokus",
        source: "ilustrasi edukatif",
        note: "Keduanya berbagi tujuan stabilitas, dengan instrumen berbeda.",
        data: [
          { label: "Fiskal: pajak & belanja (pemerintah)", value: 50, color: "#10b981" },
          { label: "Moneter: suku bunga & likuiditas (BI)", value: 50, color: "#0ea5e9" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Koordinasi pemulihan 2020-2021",
        html: "Saat pandemi, pemerintah menjalankan fiskal ekspansif (defisit melebar) sementara BI menurunkan BI-Rate dan ikut menyerap Surat Berharga Negara lewat skema berbagi beban (burden sharing). Jika BI menaikkan bunga tinggi saat itu, biaya utang pemerintah melonjak dan pemulihan terhambat. Koordinasi ini contoh nyata <strong>bauran kebijakan</strong>.",
      },
      {
        type: "calcExercise",
        prompt: "Utang pemerintah Rp8.000 triliun. Jika BI-Rate naik dan rata-rata bunga utang naik 1 poin persen (dari 6% ke 7%), berapa tambahan beban bunga per tahun (triliun)?",
        answer: 80,
        tolerance: 0,
        prefix: "Rp",
        suffix: " triliun",
        solution: "Tambahan = 1% x 8.000 = 0,01 x 8.000 = <strong>Rp80 triliun</strong> per tahun.",
        hint: "Kenaikan 1 poin persen = 1% dari total utang.",
      },
      {
        type: "classifyExercise",
        prompt: "Instrumen ini milik kebijakan fiskal atau moneter?",
        buckets: ["Fiskal (pemerintah)", "Moneter (BI)"],
        items: [
          { text: "Menaikkan tarif PPN", bucket: "Fiskal (pemerintah)" },
          { text: "Menurunkan BI-Rate", bucket: "Moneter (BI)" },
          { text: "Menambah belanja infrastruktur", bucket: "Fiskal (pemerintah)" },
          { text: "Operasi pasar terbuka likuiditas", bucket: "Moneter (BI)" },
          { text: "Memberi insentif pajak", bucket: "Fiskal (pemerintah)" },
        ],
      },
      {
        type: "video",
        comp: "FiskalVsMoneter",
        title: "Video: Fiskal vs Moneter",
        caption: "Animasi perbedaan pelaku, instrumen, dan sinergi kebijakan.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Ilustrasi BI-Rate dan Beban Bunga Utang",
        unit: "% per tahun",
        source: "ilustrasi edukatif",
        note: "Saat suku bunga acuan naik, biaya utang pemerintah ikut terdorong naik.",
        data: [
          { label: "2019", value: 5.0, color: "#0ea5e9" },
          { label: "2020", value: 3.75, color: "#10b981" },
          { label: "2021", value: 3.5, color: "#22c55e" },
          { label: "2022", value: 5.5, color: "#f59e0b" },
          { label: "2023", value: 6.0, color: "#ef4444" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen atau tujuan dengan pelaku kebijakannya.",
        pairs: [
          { left: "Menetapkan BI-Rate", right: "Moneter (BI)" },
          { left: "Menyusun belanja APBN", right: "Fiskal (pemerintah)" },
          { left: "Menjaga stabilitas nilai rupiah", right: "Moneter (BI)" },
          { left: "Menarik pajak dan memberi subsidi", right: "Fiskal (pemerintah)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Fiskal dan moneter saat Krisis Moneter 1997-1998",
        html: "Pada <strong>krisis moneter 1997-1998</strong>, rupiah anjlok dari sekitar Rp2.500 menjadi belasan ribu per dolar AS, dan suku bunga acuan sempat dinaikkan sangat tinggi untuk menahan pelarian modal. Di saat bersamaan, APBN tertekan berat oleh beban subsidi dan biaya penyelamatan perbankan, dengan paket dukungan <strong>IMF</strong>. Kondisi ini menunjukkan kebijakan fiskal pemerintah dan moneter Bank Indonesia harus dikoordinasikan agar tidak saling memperburuk keadaan.",
      },
      {
        type: "takeaways",
        items: [
          "Fiskal dipegang pemerintah (pajak & belanja); moneter dipegang BI (suku bunga & likuiditas).",
          "Tujuan utama moneter BI adalah menjaga inflasi dan stabilitas rupiah.",
          "Bauran kebijakan menyelaraskan fiskal dan moneter agar saling menguatkan.",
          "Jika tidak selaras, efek keduanya bisa saling meniadakan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kebijakan moneter di Indonesia dijalankan oleh?",
            options: ["Kementerian Keuangan", "Bank Indonesia", "DPR", "OJK"],
            answer: 1,
            explain: "Kebijakan moneter adalah wewenang Bank Indonesia.",
          },
          {
            q: "Instrumen utama kebijakan moneter adalah?",
            options: ["Pajak dan belanja", "Suku bunga dan likuiditas", "Subsidi bansos", "Anggaran pendidikan"],
            answer: 1,
            explain: "Moneter memakai suku bunga (BI-Rate) dan pengelolaan likuiditas.",
          },
          {
            q: "Bauran kebijakan (policy mix) berarti?",
            options: ["Fiskal menggantikan moneter", "Koordinasi fiskal dan moneter agar selaras", "BI mengelola APBN", "Pemerintah menetapkan suku bunga"],
            answer: 1,
            explain: "Policy mix adalah koordinasi kebijakan fiskal dan moneter.",
          },
          {
            q: "Utang Rp10.000 T, bunga naik 1 poin persen. Tambahan beban/tahun?",
            options: ["Rp100 T", "Rp10 T", "Rp1.000 T", "Rp1 T"],
            answer: 0,
            explain: "1% x 10.000 = Rp100 triliun per tahun.",
          },
          {
            q: "Tujuan utama kebijakan moneter BI adalah?",
            options: ["Memeratakan pendapatan", "Menjaga inflasi dan stabilitas rupiah", "Membangun infrastruktur", "Menarik pajak"],
            answer: 1,
            explain: "Mandat utama BI adalah menjaga kestabilan nilai rupiah, termasuk inflasi.",
          },
        ],
      },
    ],
  },
];
