import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "defisit-utang-keberlanjutan",
    levelId: "defisit",
    order: 1,
    title: "Defisit, Utang & Keberlanjutan Fiskal",
    summary: "Memahami defisit APBN, batas 3% PDB, rasio utang dan ambang 60%, serta menjaga fiskal tetap sehat. Dengan video & kalkulator.",
    durationMin: 14,
    tags: ["defisit", "utang", "SBN", "keberlanjutan fiskal"],
    blocks: [
      {
        type: "paragraph",
        html: "Ketika belanja melebihi pendapatan, terjadi <strong>defisit</strong> yang ditutup dengan <strong>utang</strong>, terutama lewat penerbitan <strong>SBN</strong> (Surat Berharga Negara seperti SUN dan sukuk). Agar fiskal tetap sehat, ada rambu hukum yang membatasi seberapa besar defisit dan utang boleh menumpuk.",
      },
      {
        type: "video",
        comp: "DefisitUtangFiskal",
        title: "Video: Defisit, Utang & Batas Hukum",
        caption: "Animasi rasio utang terhadap PDB dan batas 60%.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua rambu hukum",
        html: "UU Keuangan Negara membatasi <strong>defisit maksimal 3% PDB</strong> dan <strong>rasio utang maksimal 60% PDB</strong>. Rasio utang Indonesia umumnya jauh di bawah 60% (kisaran 30-40%).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ruang fiskal & keberlanjutan",
        html: "<strong>Ruang fiskal</strong> adalah keleluasaan anggaran setelah dikurangi belanja wajib (gaji, bunga utang, transfer). Makin besar bunga utang, makin sempit ruang untuk pembangunan. Keberlanjutan menuntut utang tumbuh lebih lambat dari ekonomi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung rasio utang terhadap PDB dan lihat proyeksinya tahun depan saat PDB tumbuh.",
      },
      { type: "widget", widget: "KalkulatorRasioUtang" },
      {
        type: "case",
        title: "Studi Kasus: Mengapa pertumbuhan menjaga utang",
        html: "Utang Rp8.000 triliun terdengar besar, tetapi yang menentukan kesehatan adalah <strong>rasionya terhadap PDB</strong>. Jika PDB Rp22.000 triliun, rasio utang sekitar 36%, masih jauh di bawah batas 60%. Selama ekonomi tumbuh lebih cepat dari penambahan utang, rasio ini terkendali. Pertumbuhan ekonomi adalah kunci keberlanjutan fiskal.",
      },
      {
        type: "calcExercise",
        prompt: "Utang Rp8.000 triliun, PDB Rp22.000 triliun. Berapa rasio utang terhadap PDB (%)?",
        answer: 36.4,
        tolerance: 0.3,
        suffix: "%",
        solution: "Rasio = 8.000 / 22.000 x 100 = <strong>36,4%</strong> PDB, masih jauh di bawah batas 60%.",
        hint: "Utang dibagi PDB, dikali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi ini mendukung keberlanjutan fiskal atau mengancamnya?",
        buckets: ["Mendukung", "Mengancam"],
        items: [
          { text: "PDB tumbuh lebih cepat dari utang", bucket: "Mendukung" },
          { text: "Defisit terus melebihi 3% PDB", bucket: "Mengancam" },
          { text: "Belanja diarahkan ke yang produktif", bucket: "Mendukung" },
          { text: "Bunga utang menyita ruang fiskal makin besar", bucket: "Mengancam" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren Rasio Utang terhadap PDB Indonesia",
        unit: "% PDB",
        source: "Ilustrasi pola rasio utang tahunan",
        note: "Seluruh nilai berada jauh di bawah batas hukum 60% PDB.",
        data: [
          { label: "2019", value: 30.2, color: "#22c55e" },
          { label: "2020", value: 39.4, color: "#f59e0b" },
          { label: "2021", value: 40.7, color: "#f59e0b" },
          { label: "2022", value: 39.7, color: "#f59e0b" },
          { label: "2023", value: 39.2, color: "#22c55e" },
          { label: "2024", value: 39.0, color: "#22c55e" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Utang Rp8.000 T naik jadi Rp8.400 T, sementara PDB tumbuh dari Rp22.000 T menjadi Rp24.200 T. Berapa rasio utang tahun depan (%)?",
        answer: 34.7,
        tolerance: 0.3,
        suffix: "%",
        solution: "Rasio = 8.400 / 24.200 x 100 = <strong>34,7%</strong> PDB. Karena PDB tumbuh lebih cepat dari utang, rasio justru turun dari 36,4%.",
        hint: "Bagi utang baru dengan PDB baru, lalu kali 100.",
      },
      {
        type: "case",
        title: "Sejarah: Rasio utang naik akibat pandemi",
        html: "Pandemi <strong>COVID-19</strong> mendorong rasio utang Indonesia naik dari sekitar 30% PDB pada 2019 menjadi sekitar <strong>39% PDB</strong> pada 2020, seiring defisit yang melebar hingga sekitar 6,1% PDB. Meski naik, rasio ini tetap berada di bawah batas hukum <strong>60% PDB</strong>. Pemulihan pertumbuhan ekonomi setelahnya menjadi kunci agar rasio utang kembali terkendali.",
      },
      {
        type: "takeaways",
        items: [
          "Defisit ditutup utang, terutama lewat SBN (SUN & sukuk).",
          "Batas hukum: defisit maksimal 3% PDB, utang maksimal 60% PDB.",
          "Yang dinilai adalah rasio utang terhadap PDB, bukan nominalnya.",
          "Pertumbuhan ekonomi adalah kunci keberlanjutan fiskal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Batas rasio utang terhadap PDB menurut UU?",
            options: ["30%", "60%", "100%", "Tidak dibatasi"],
            answer: 1,
            explain: "UU Keuangan Negara membatasi rasio utang maksimal 60% PDB.",
          },
          {
            q: "Batas defisit APBN terhadap PDB?",
            options: ["1%", "3%", "10%", "Tidak ada"],
            answer: 1,
            explain: "Defisit APBN dibatasi maksimal 3% PDB.",
          },
          {
            q: "Defisit umumnya ditutup dengan?",
            options: ["Mencetak uang", "Penerbitan SBN (utang)", "Menaikkan suku bunga", "Menjual cadangan emas"],
            answer: 1,
            explain: "Pembiayaan defisit terutama lewat penerbitan SBN.",
          },
          {
            q: "Kunci utama keberlanjutan utang adalah?",
            options: ["Nominal utang kecil", "Pertumbuhan ekonomi lebih cepat dari utang", "Tidak pernah berutang", "Menaikkan pajak ekstrem"],
            answer: 1,
            explain: "Selama PDB tumbuh lebih cepat dari utang, rasio utang terkendali.",
          },
          {
            q: "Utang Rp9.000 T, PDB Rp30.000 T. Rasio utang?",
            options: ["30%", "60%", "3%", "90%"],
            answer: 0,
            explain: "9.000 / 30.000 x 100 = 30% PDB.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "defisit-dan-pembiayaan",
    levelId: "defisit",
    order: 2,
    title: "Defisit & Pembiayaannya",
    summary: "Jenis defisit, cara menutupnya lewat SBN domestik & valas serta pinjaman, dan batas hukum 3% PDB. Dengan simulator APBN.",
    durationMin: 13,
    tags: ["defisit", "pembiayaan", "SBN", "pinjaman"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Defisit anggaran</strong> terjadi saat belanja negara lebih besar dari pendapatan. Selisih ini disebut <strong>defisit keseluruhan</strong> dan harus ditutup dengan <strong>pembiayaan</strong>. Sumber pembiayaan utama adalah penerbitan <strong>SBN</strong> (Surat Berharga Negara) di pasar domestik maupun valuta asing, serta <strong>pinjaman</strong> dari kreditor dalam dan luar negeri.",
      },
      {
        type: "paragraph",
        html: "Pemerintah memilih komposisi pembiayaan yang menyeimbangkan biaya bunga, risiko nilai tukar, dan kedalaman pasar. Mayoritas pembiayaan diambil dari <strong>SBN domestik dalam rupiah</strong> untuk menekan risiko valas, sisanya dari SBN valas dan pinjaman.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Batas defisit 3% PDB",
        html: "UU Keuangan Negara membatasi <strong>defisit APBN maksimal 3% PDB</strong>. Pada 2020-2022 batas ini sempat dilonggarkan untuk penanganan pandemi, lalu dikembalikan ke bawah 3% sejak 2023.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga jalur pembiayaan",
        html: "(1) <strong>SBN domestik</strong> dalam rupiah, porsi terbesar; (2) <strong>SBN valas</strong> untuk diversifikasi investor; (3) <strong>pinjaman</strong> program/proyek dari lembaga multilateral dan bilateral.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur pendapatan dan belanja untuk melihat besar defisit dan apakah masih di bawah batas 3% PDB.",
      },
      { type: "widget", widget: "SimulatorAPBN" },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Sumber Pembiayaan Defisit",
        unit: "% dari total pembiayaan",
        source: "Ilustrasi pola pembiayaan APBN",
        note: "SBN domestik mendominasi untuk menekan risiko nilai tukar.",
        data: [
          { label: "SBN domestik (rupiah)", value: 70, color: "#2563eb" },
          { label: "SBN valas", value: 18, color: "#0ea5e9" },
          { label: "Pinjaman", value: 12, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menutup defisit Rp500 triliun",
        html: "Pendapatan negara Rp2.800 triliun, belanja Rp3.300 triliun, sehingga defisit Rp500 triliun. Dengan PDB Rp22.000 triliun, defisit setara 2,27% PDB, masih di bawah batas 3%. Defisit ditutup dengan menerbitkan SBN (porsi terbesar di pasar domestik) dan sebagian pinjaman.",
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan Rp2.800 T, belanja Rp3.300 T, PDB Rp22.000 T. Berapa defisit terhadap PDB (%)?",
        answer: 2.27,
        tolerance: 0.05,
        suffix: "%",
        solution: "Defisit = 3.300 - 2.800 = Rp500 T. Rasio = 500 / 22.000 x 100 = <strong>2,27%</strong> PDB, di bawah batas 3%.",
        hint: "Cari defisit dulu (belanja - pendapatan), lalu bagi PDB dan kali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap item sebagai sumber pembiayaan atau bukan.",
        buckets: ["Sumber pembiayaan", "Bukan pembiayaan"],
        items: [
          { text: "Penerbitan SBN domestik", bucket: "Sumber pembiayaan" },
          { text: "Penerbitan SBN valas", bucket: "Sumber pembiayaan" },
          { text: "Pinjaman dari lembaga multilateral", bucket: "Sumber pembiayaan" },
          { text: "Penerimaan pajak", bucket: "Bukan pembiayaan" },
          { text: "Penerimaan bea cukai", bucket: "Bukan pembiayaan" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tren Defisit APBN terhadap PDB",
        unit: "% PDB",
        source: "Ilustrasi pola defisit tahunan",
        note: "Batas 3% dilonggarkan 2020-2022 untuk pandemi, lalu dikembalikan di bawah 3% sejak 2023.",
        data: [
          { label: "2020", value: 6.14, color: "#ef4444" },
          { label: "2021", value: 4.57, color: "#ef4444" },
          { label: "2022", value: 2.38, color: "#22c55e" },
          { label: "2023", value: 1.65, color: "#22c55e" },
          { label: "2024", value: 2.29, color: "#22c55e" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan instrumen pembiayaan dengan ciri utamanya.",
        pairs: [
          { left: "SUN", right: "Surat Utang Negara konvensional dalam rupiah" },
          { left: "Sukuk negara", right: "SBN berbasis prinsip syariah" },
          { left: "SBN valas", right: "Diversifikasi investor, terpapar risiko nilai tukar" },
          { left: "Pinjaman program", right: "Dana dari lembaga multilateral/bilateral" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Pelonggaran lalu kembali ke batas 3% PDB",
        html: "Lewat <strong>Perppu 1/2020</strong>, batas defisit 3% PDB dilonggarkan sementara untuk 2020-2022 guna menangani pandemi, dengan defisit 2020 mencapai sekitar 6,1% PDB. Sesuai amanat aturan yang sama, pemerintah wajib mengembalikan defisit ke bawah <strong>3% PDB pada 2023</strong>, dan realisasinya tercapai sekitar 1,65% PDB. Ini menegaskan batas defisit adalah rambu hukum yang dijaga, bukan sekadar imbauan.",
      },
      {
        type: "takeaways",
        items: [
          "Defisit terjadi saat belanja melebihi pendapatan dan ditutup dengan pembiayaan.",
          "Jalur pembiayaan: SBN domestik, SBN valas, dan pinjaman.",
          "SBN domestik rupiah mendominasi untuk menekan risiko nilai tukar.",
          "Batas hukum defisit adalah 3% PDB.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Defisit anggaran ditutup dengan?",
            options: ["Pembiayaan (utang)", "Mengurangi pajak", "Menaikkan inflasi", "Membekukan belanja"],
            answer: 0,
            explain: "Selisih belanja di atas pendapatan ditutup lewat pembiayaan, terutama utang.",
          },
          {
            q: "Sumber pembiayaan dengan porsi terbesar biasanya?",
            options: ["SBN valas", "SBN domestik rupiah", "Pinjaman bilateral", "Hibah"],
            answer: 1,
            explain: "SBN domestik rupiah mendominasi untuk menekan risiko nilai tukar.",
          },
          {
            q: "Batas hukum defisit APBN terhadap PDB?",
            options: ["1%", "3%", "6%", "Tidak ada"],
            answer: 1,
            explain: "UU Keuangan Negara membatasi defisit maksimal 3% PDB.",
          },
          {
            q: "Pendapatan Rp2.800 T, belanja Rp3.300 T. Berapa defisit?",
            options: ["Rp300 T", "Rp500 T", "Rp600 T", "Rp6.100 T"],
            answer: 1,
            explain: "Defisit = 3.300 - 2.800 = Rp500 T.",
          },
          {
            q: "Mengapa SBN valas porsinya dijaga tidak terlalu besar?",
            options: ["Bunganya nol", "Untuk menekan risiko nilai tukar", "Dilarang UU", "Tidak ada peminat"],
            answer: 1,
            explain: "Utang valas menambah risiko nilai tukar, sehingga porsinya dijaga.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "utang-pemerintah",
    levelId: "defisit",
    order: 3,
    title: "Utang Pemerintah & Komposisinya",
    summary: "Komposisi utang SBN vs pinjaman, rupiah vs valas, rasio batas 60% PDB, dan profil jatuh tempo. Dengan kalkulator rasio utang.",
    durationMin: 14,
    tags: ["utang", "SBN", "valas", "jatuh tempo"],
    blocks: [
      {
        type: "paragraph",
        html: "Utang pemerintah punya dua bentuk utama: <strong>SBN</strong> (Surat Berharga Negara, mencakup SUN dan sukuk) dan <strong>pinjaman</strong> (dalam dan luar negeri). Porsi SBN jauh lebih besar karena pemerintah memilih membiayai diri lewat pasar surat berharga yang likuid.",
      },
      {
        type: "paragraph",
        html: "Dua dimensi penting dalam mengelola utang adalah <strong>mata uang</strong> (rupiah vs valas) dan <strong>profil jatuh tempo</strong>. Dominasi rupiah menekan risiko nilai tukar, sementara jatuh tempo yang tersebar mencegah penumpukan kewajiban pada satu tahun.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rasio utang maksimal 60% PDB",
        html: "UU Keuangan Negara membatasi <strong>rasio utang maksimal 60% PDB</strong>. Rasio utang Indonesia umumnya berada di kisaran 30-40%, masih jauh di bawah ambang tersebut.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Komposisi yang dijaga",
        html: "Mayoritas utang berbentuk <strong>SBN dalam rupiah</strong>. Porsi <strong>valas</strong> dijaga agar gejolak nilai tukar tidak melonjakkan beban utang. Profil jatuh tempo disebar agar refinancing tidak menumpuk.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko yang dipantau",
        html: "Tiga risiko utama: <strong>risiko nilai tukar</strong> (utang valas), <strong>risiko tingkat bunga</strong> (saat refinancing), dan <strong>risiko refinancing</strong> (jatuh tempo menumpuk). Pengelolaan komposisi bertujuan menekan ketiganya.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi Utang Pemerintah Berdasarkan Instrumen",
        unit: "% dari total utang",
        source: "Ilustrasi pola komposisi utang",
        note: "SBN mendominasi; pinjaman berperan sebagai pelengkap.",
        data: [
          { label: "SBN domestik", value: 71, color: "#2563eb" },
          { label: "SBN valas", value: 17, color: "#0ea5e9" },
          { label: "Pinjaman", value: 12, color: "#f59e0b" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hitung rasio utang",
        html: "Masukkan nominal utang dan PDB untuk melihat rasio terhadap PDB dan jaraknya dari batas 60%.",
      },
      { type: "widget", widget: "KalkulatorRasioUtang" },
      {
        type: "case",
        title: "Studi Kasus: Membaca rasio utang",
        html: "Total utang Rp8.500 triliun dengan PDB Rp23.000 triliun menghasilkan rasio sekitar 36,96% PDB, masih jauh di bawah batas 60%. Dari utang itu, sekitar 71% berbentuk SBN domestik rupiah, sehingga sebagian besar tidak terpapar risiko nilai tukar. Profil jatuh tempo yang tersebar menjaga kewajiban tahunan tetap terkelola.",
      },
      {
        type: "calcExercise",
        prompt: "Total utang Rp8.500 T, PDB Rp23.000 T. Berapa rasio utang terhadap PDB (%)?",
        answer: 36.96,
        tolerance: 0.3,
        suffix: "%",
        solution: "Rasio = 8.500 / 23.000 x 100 = <strong>36,96%</strong> PDB, masih jauh di bawah batas 60%.",
        hint: "Bagi total utang dengan PDB, lalu kali 100.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah utang dengan penjelasannya.",
        pairs: [
          { left: "SBN", right: "Surat berharga negara: SUN & sukuk" },
          { left: "Utang valas", right: "Terpapar risiko nilai tukar" },
          { left: "Batas 60% PDB", right: "Ambang rasio utang menurut UU" },
          { left: "Profil jatuh tempo", right: "Sebaran waktu kewajiban harus dilunasi" },
        ],
      },
      {
        type: "video",
        comp: "UtangPemerintah",
        title: "Video: Komposisi & Pengelolaan Utang Pemerintah",
        caption: "Animasi SBN vs pinjaman, rupiah vs valas, dan profil jatuh tempo.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Utang Berdasarkan Mata Uang",
        unit: "% dari total utang",
        source: "Ilustrasi pola komposisi mata uang utang",
        note: "Dominasi rupiah menekan paparan terhadap risiko nilai tukar.",
        data: [
          { label: "Rupiah", value: 72, color: "#2563eb" },
          { label: "Valuta asing", value: 28, color: "#f59e0b" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap kondisi: menambah atau mengurangi risiko utang?",
        buckets: ["Menambah risiko", "Mengurangi risiko"],
        items: [
          { text: "Porsi utang valas membesar", bucket: "Menambah risiko" },
          { text: "Jatuh tempo menumpuk di satu tahun", bucket: "Menambah risiko" },
          { text: "Dominasi utang dalam rupiah", bucket: "Mengurangi risiko" },
          { text: "Profil jatuh tempo tersebar merata", bucket: "Mengurangi risiko" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Rasio utang melonjak pada Krisis 1997-1998",
        html: "<strong>Krisis 1997-1998</strong> membuat rasio utang Indonesia melonjak hingga mendekati <strong>100% PDB</strong> pada akhir 1990-an, akibat anjloknya rupiah, obligasi rekapitalisasi perbankan, dan pinjaman <strong>IMF</strong> dalam valuta asing. Besarnya porsi utang valas saat itu membuat beban melonjak setiap kali rupiah melemah. Pelajaran inilah yang mendorong kebijakan menjaga dominasi utang dalam <strong>rupiah</strong> di kemudian hari.",
      },
      {
        type: "takeaways",
        items: [
          "Utang terdiri dari SBN (dominan) dan pinjaman.",
          "Mayoritas utang dalam rupiah untuk menekan risiko nilai tukar.",
          "Batas hukum rasio utang adalah 60% PDB; Indonesia di kisaran 30-40%.",
          "Profil jatuh tempo disebar agar refinancing tidak menumpuk.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Bentuk utang dengan porsi terbesar adalah?",
            options: ["Pinjaman bilateral", "SBN", "Pinjaman multilateral", "Hibah"],
            answer: 1,
            explain: "SBN (SUN & sukuk) mendominasi komposisi utang pemerintah.",
          },
          {
            q: "Batas rasio utang terhadap PDB menurut UU?",
            options: ["30%", "60%", "90%", "Tidak dibatasi"],
            answer: 1,
            explain: "UU Keuangan Negara membatasi rasio utang maksimal 60% PDB.",
          },
          {
            q: "Mengapa porsi utang rupiah dijaga dominan?",
            options: ["Bunganya nol", "Menekan risiko nilai tukar", "Diwajibkan investor asing", "Agar PDB naik"],
            answer: 1,
            explain: "Utang rupiah tidak terpapar gejolak nilai tukar seperti utang valas.",
          },
          {
            q: "Profil jatuh tempo disebar agar?",
            options: ["Bunga jadi nol", "Refinancing tidak menumpuk di satu tahun", "Utang hilang", "PDB turun"],
            answer: 1,
            explain: "Sebaran jatuh tempo mencegah penumpukan kewajiban dan risiko refinancing.",
          },
          {
            q: "Utang Rp8.500 T, PDB Rp23.000 T. Rasio utang mendekati?",
            options: ["27%", "37%", "60%", "85%"],
            answer: 1,
            explain: "8.500 / 23.000 x 100 = 36,96%, mendekati 37%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "keberlanjutan-fiskal",
    levelId: "defisit",
    order: 4,
    title: "Keberlanjutan Fiskal",
    summary: "Ruang fiskal, kualitas belanja, keseimbangan primer, risiko fiskal, dan disiplin fiskal sebagai penjaga kesehatan APBN jangka panjang.",
    durationMin: 13,
    tags: ["keberlanjutan fiskal", "ruang fiskal", "keseimbangan primer", "disiplin fiskal"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Keberlanjutan fiskal</strong> berarti negara mampu memenuhi kewajibannya tanpa membahayakan kesehatan anggaran jangka panjang. Kuncinya bukan sekadar nominal utang, melainkan <strong>ruang fiskal</strong>, <strong>kualitas belanja</strong>, dan <strong>keseimbangan primer</strong> yang terjaga.",
      },
      {
        type: "paragraph",
        html: "<strong>Ruang fiskal</strong> adalah keleluasaan anggaran setelah dikurangi belanja wajib seperti gaji, bunga utang, dan transfer ke daerah. Makin besar bunga utang, makin sempit ruang untuk pembangunan. <strong>Keseimbangan primer</strong> mengukur keseimbangan anggaran sebelum memperhitungkan pembayaran bunga.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Keseimbangan primer",
        html: "<strong>Keseimbangan primer = pendapatan - belanja di luar pembayaran bunga utang</strong>. Setara dengan defisit keseluruhan ditambah pembayaran bunga. Surplus primer berarti utang baru hanya dipakai membayar bunga, bukan menambah beban pokok.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kualitas belanja",
        html: "Belanja yang <strong>produktif</strong> (infrastruktur, pendidikan, kesehatan) mendorong pertumbuhan sehingga PDB naik dan rasio utang turun. Belanja konsumtif tanpa hasil justru mempersempit ruang fiskal di masa depan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko fiskal",
        html: "Risiko fiskal mencakup pelemahan nilai tukar, kenaikan suku bunga, kewajiban kontingensi (penjaminan), dan perlambatan ekonomi. <strong>Disiplin fiskal</strong> menjaga defisit di bawah 3% PDB dan utang di bawah 60% PDB agar guncangan tetap terkendali.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Tren Keseimbangan Primer Menuju Surplus",
        unit: "Rp triliun",
        source: "Ilustrasi arah konsolidasi fiskal",
        note: "Nilai negatif berarti defisit primer; arah menuju positif menandakan konsolidasi.",
        data: [
          { label: "2020", value: -600, color: "#ef4444" },
          { label: "2021", value: -430, color: "#f59e0b" },
          { label: "2022", value: -150, color: "#f59e0b" },
          { label: "2023", value: 90, color: "#22c55e" },
          { label: "2024", value: 120, color: "#22c55e" },
          { label: "2025", value: 50, color: "#22c55e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membaca keseimbangan primer",
        html: "Sebuah APBN punya defisit keseluruhan Rp500 triliun, sementara pembayaran bunga utang Rp450 triliun. Keseimbangan primer = bunga - defisit keseluruhan = 450 - 500 = minus Rp50 triliun. Artinya masih defisit primer kecil: utang baru hampir seluruhnya dipakai membayar bunga, bukan menambah beban pokok. Konsolidasi tinggal sedikit lagi untuk mencapai surplus primer.",
      },
      {
        type: "calcExercise",
        prompt: "Defisit keseluruhan Rp500 T, pembayaran bunga utang Rp450 T. Berapa keseimbangan primer (Rp T)?",
        answer: -50,
        tolerance: 5,
        suffix: " T",
        solution: "Keseimbangan primer = bunga - defisit keseluruhan = 450 - 500 = <strong>minus Rp50 T</strong> (defisit primer kecil).",
        hint: "Keseimbangan primer = pembayaran bunga dikurangi defisit keseluruhan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap kondisi: memperluas atau mempersempit ruang fiskal?",
        buckets: ["Memperluas ruang fiskal", "Mempersempit ruang fiskal"],
        items: [
          { text: "Belanja diarahkan ke proyek produktif", bucket: "Memperluas ruang fiskal" },
          { text: "Surplus keseimbangan primer", bucket: "Memperluas ruang fiskal" },
          { text: "Beban bunga utang membengkak", bucket: "Mempersempit ruang fiskal" },
          { text: "Defisit terus di atas 3% PDB", bucket: "Mempersempit ruang fiskal" },
          { text: "Pertumbuhan ekonomi melemah", bucket: "Mempersempit ruang fiskal" },
        ],
      },
      {
        type: "video",
        comp: "KeberlanjutanFiskal",
        title: "Video: Menjaga Keberlanjutan Fiskal",
        caption: "Animasi ruang fiskal, keseimbangan primer, dan disiplin fiskal.",
      },
      {
        type: "widget",
        widget: "KalkulatorPrimaryBalance",
      },
      {
        type: "chart",
        variant: "area",
        title: "Tren Beban Bunga Utang terhadap PDB",
        unit: "% PDB",
        source: "Ilustrasi pola beban bunga tahunan",
        note: "Beban bunga yang naik mempersempit ruang fiskal untuk pembangunan.",
        data: [
          { label: "2020", value: 1.92, color: "#f59e0b" },
          { label: "2021", value: 2.03, color: "#f59e0b" },
          { label: "2022", value: 1.94, color: "#f59e0b" },
          { label: "2023", value: 1.98, color: "#f59e0b" },
          { label: "2024", value: 2.06, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan negara Rp3.000 T, belanja di luar pembayaran bunga Rp2.880 T. Berapa keseimbangan primer (Rp T)?",
        answer: 120,
        tolerance: 5,
        suffix: " T",
        solution: "Keseimbangan primer = pendapatan - belanja non-bunga = 3.000 - 2.880 = <strong>plus Rp120 T</strong> (surplus primer).",
        hint: "Kurangkan belanja di luar bunga dari pendapatan.",
      },
      {
        type: "case",
        title: "Sejarah: Konsolidasi fiskal pascapandemi 2023",
        html: "Setelah defisit melebar hingga sekitar 6,1% PDB pada 2020, pemerintah menjalankan <strong>konsolidasi fiskal</strong> dan berhasil mengembalikan defisit ke bawah <strong>3% PDB pada 2023</strong> dengan realisasi sekitar 1,65% PDB. Keseimbangan primer pun bergerak dari defisit dalam menuju arah yang lebih sehat. Capaian ini menunjukkan <strong>disiplin fiskal</strong> dijaga agar anggaran tetap berkelanjutan dalam jangka panjang.",
      },
      {
        type: "takeaways",
        items: [
          "Keberlanjutan fiskal menjaga kesehatan anggaran jangka panjang.",
          "Ruang fiskal adalah keleluasaan setelah belanja wajib; bunga utang menggerusnya.",
          "Keseimbangan primer = pendapatan dikurangi belanja di luar bunga utang.",
          "Disiplin fiskal: jaga defisit di bawah 3% dan utang di bawah 60% PDB.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa itu ruang fiskal?",
            options: [
              "Total utang negara",
              "Keleluasaan anggaran setelah belanja wajib",
              "Jumlah pajak yang ditarik",
              "Cadangan devisa",
            ],
            answer: 1,
            explain: "Ruang fiskal adalah keleluasaan anggaran setelah dikurangi belanja wajib.",
          },
          {
            q: "Keseimbangan primer dihitung dengan?",
            options: [
              "Pendapatan dikurangi seluruh belanja",
              "Pendapatan dikurangi belanja di luar pembayaran bunga",
              "Belanja dikurangi pajak",
              "Utang dibagi PDB",
            ],
            answer: 1,
            explain: "Keseimbangan primer mengeluarkan pembayaran bunga dari belanja.",
          },
          {
            q: "Belanja yang menjaga keberlanjutan fiskal adalah belanja yang?",
            options: ["Konsumtif", "Produktif", "Tanpa rencana", "Hanya untuk bunga"],
            answer: 1,
            explain: "Belanja produktif mendorong pertumbuhan sehingga rasio utang turun.",
          },
          {
            q: "Defisit Rp500 T, bunga utang Rp450 T. Keseimbangan primer?",
            options: ["Minus Rp50 T", "Plus Rp50 T", "Minus Rp950 T", "Rp0"],
            answer: 0,
            explain: "Keseimbangan primer = 450 - 500 = minus Rp50 T.",
          },
          {
            q: "Disiplin fiskal menjaga defisit dan utang di bawah?",
            options: ["1% dan 30% PDB", "3% dan 60% PDB", "5% dan 90% PDB", "Tidak ada batas"],
            answer: 1,
            explain: "Batas hukum: defisit maksimal 3% PDB dan utang maksimal 60% PDB.",
          },
        ],
      },
    ],
  },
];
