import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "struktur-dan-siklus-apbn",
    levelId: "apbn",
    order: 1,
    title: "Struktur & Siklus APBN",
    summary: "Tiga bagian APBN (pendapatan, belanja, pembiayaan) dan siklus tahunannya. Dengan video & simulator APBN.",
    durationMin: 14,
    tags: ["APBN", "postur", "siklus anggaran"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>APBN</strong> adalah rencana keuangan tahunan negara yang disetujui DPR. Strukturnya terdiri dari tiga bagian: <strong>pendapatan negara</strong>, <strong>belanja negara</strong>, dan <strong>pembiayaan</strong> (untuk menutup defisit bila belanja melebihi pendapatan).",
      },
      {
        type: "video",
        comp: "SiklusAPBN",
        title: "Video: Siklus APBN",
        caption: "Animasi dari perencanaan, penetapan DPR, pelaksanaan, sampai audit BPK.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Postur APBN",
        html: "<strong>Pendapatan - Belanja = Surplus/Defisit</strong>. Bila defisit, ditutup oleh <strong>pembiayaan</strong>, terutama penerbitan SBN (Surat Berharga Negara).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Asumsi makro",
        html: "APBN disusun atas asumsi dasar ekonomi makro: pertumbuhan ekonomi, inflasi, nilai tukar rupiah, harga minyak (ICP), dan suku bunga. Bila realisasi meleset, postur APBN ikut bergeser.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur pendapatan dan belanja, lihat saldo anggaran dan rasionya terhadap PDB (batas defisit 3% PDB).",
      },
      { type: "widget", widget: "SimulatorAPBN" },
      {
        type: "case",
        title: "Studi Kasus: Siklus satu tahun anggaran",
        html: "Pertengahan tahun, pemerintah (Kemenkeu & Bappenas) menyusun <strong>RAPBN</strong> dan Nota Keuangan, lalu dibahas dan disahkan <strong>DPR</strong> menjadi UU APBN sebelum tahun berjalan. Sepanjang tahun, kementerian melaksanakannya. Tahun berikutnya, realisasi diaudit <strong>BPK</strong> dan dipertanggungjawabkan ke DPR. Siklus ini menjamin akuntabilitas keuangan negara.",
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan Rp2.800 T, belanja Rp3.300 T, PDB Rp22.000 T. Berapa rasio defisit terhadap PDB (%)?",
        answer: 2.27,
        tolerance: 0.05,
        suffix: "%",
        solution: "Defisit = 3.300 - 2.800 = Rp500 T. Rasio = 500 / 22.000 x 100 = <strong>2,27%</strong> PDB (masih di bawah batas 3%).",
        hint: "Defisit dibagi PDB, dikali 100.",
      },
      {
        type: "classifyExercise",
        prompt: "Komponen ini bagian APBN yang mana?",
        buckets: ["Pendapatan", "Belanja", "Pembiayaan"],
        items: [
          { text: "Penerimaan pajak", bucket: "Pendapatan" },
          { text: "Subsidi & bansos", bucket: "Belanja" },
          { text: "Penerbitan SBN", bucket: "Pembiayaan" },
          { text: "Gaji pegawai negeri", bucket: "Belanja" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Postur APBN ilustratif",
        unit: "Rp triliun",
        source: "Ilustrasi postur APBN, Kemenkeu",
        note: "Belanja melebihi pendapatan, selisihnya menjadi defisit yang ditutup pembiayaan.",
        data: [
          { label: "Pendapatan", value: 2800, color: "#16a34a" },
          { label: "Belanja", value: 3300, color: "#dc2626" },
          { label: "Defisit", value: 500, color: "#f59e0b" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah postur APBN dengan maknanya.",
        pairs: [
          { left: "Pendapatan negara", right: "Uang yang masuk ke kas negara" },
          { left: "Belanja negara", right: "Uang yang dikeluarkan negara" },
          { left: "Defisit", right: "Belanja lebih besar daripada pendapatan" },
          { left: "Pembiayaan", right: "Sumber dana untuk menutup defisit" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Postur APBN berubah lewat Perppu 1/2020",
        html: "Pandemi 2020 memaksa pemerintah mengubah postur APBN secara drastis lewat <strong>Perppu 1/2020</strong>. Pendapatan negara turun karena ekonomi melemah, sementara belanja kesehatan dan bansos melonjak, sehingga defisit melebar hingga sekitar <strong>6,1% PDB</strong>, jauh di atas batas normal 3%. Selisih besar ini ditutup dengan lonjakan <strong>pembiayaan</strong>, terutama penerbitan SBN.",
      },
      {
        type: "takeaways",
        items: [
          "APBN terdiri dari pendapatan, belanja, dan pembiayaan.",
          "Pendapatan dikurangi belanja menghasilkan surplus atau defisit.",
          "Defisit ditutup pembiayaan, terutama SBN.",
          "Siklus: perencanaan, penetapan DPR, pelaksanaan, audit BPK.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tiga bagian utama APBN adalah?",
            options: ["Aktiva, pasiva, modal", "Pendapatan, belanja, pembiayaan", "Pajak, utang, subsidi", "C, I, G"],
            answer: 1,
            explain: "APBN terdiri dari pendapatan negara, belanja negara, dan pembiayaan.",
          },
          {
            q: "Yang mengesahkan APBN menjadi undang-undang?",
            options: ["BPK", "DPR", "Bank Indonesia", "MA"],
            answer: 1,
            explain: "RAPBN dibahas dan disahkan DPR menjadi UU APBN.",
          },
          {
            q: "Defisit APBN umumnya ditutup dengan?",
            options: ["Mencetak uang", "Penerbitan SBN", "Menjual aset BUMN saja", "Menaikkan suku bunga"],
            answer: 1,
            explain: "Pembiayaan defisit terutama lewat penerbitan Surat Berharga Negara.",
          },
          {
            q: "Yang mengaudit pelaksanaan APBN?",
            options: ["DPR", "BPK", "OJK", "BI"],
            answer: 1,
            explain: "Badan Pemeriksa Keuangan (BPK) mengaudit pelaksanaan APBN.",
          },
          {
            q: "Defisit Rp600 T, PDB Rp24.000 T. Rasio defisit?",
            options: ["2,5%", "5%", "0,25%", "25%"],
            answer: 0,
            explain: "600 / 24.000 x 100 = 2,5% PDB.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pendapatan-belanja-pembiayaan",
    levelId: "apbn",
    order: 2,
    title: "Pendapatan, Belanja & Pembiayaan",
    summary: "Membedah tiga bagian APBN secara rinci: sumber pendapatan, jenis belanja, dan cara pembiayaan defisit. Dengan simulator APBN.",
    durationMin: 13,
    tags: ["pendapatan", "belanja", "pembiayaan", "APBN"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap rupiah dalam APBN masuk ke salah satu dari tiga bagian. <strong>Pendapatan negara</strong> adalah uang yang masuk ke kas negara, <strong>belanja negara</strong> adalah uang yang dikeluarkan, dan <strong>pembiayaan</strong> adalah sumber dana untuk menutup selisih ketika belanja lebih besar daripada pendapatan (defisit).",
      },
      {
        type: "paragraph",
        html: "Pendapatan negara terdiri dari <strong>penerimaan perpajakan</strong> (pajak dan kepabeanan/cukai), <strong>Penerimaan Negara Bukan Pajak (PNBP)</strong> seperti royalti sumber daya alam dan dividen BUMN, serta <strong>hibah</strong>. Belanja negara terbagi menjadi <strong>belanja pemerintah pusat</strong> (belanja K/L dan non-K/L) dan <strong>Transfer ke Daerah (TKD)</strong> termasuk Dana Desa.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tulang punggung pendapatan",
        html: "Penerimaan <strong>perpajakan</strong> menyumbang sekitar 80% pendapatan negara. Karena itu rasio pajak (tax ratio) menjadi indikator penting kesehatan fiskal Indonesia.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Jenis belanja pemerintah pusat",
        html: "Belanja dikelompokkan menurut jenis: <strong>belanja pegawai</strong> (gaji), <strong>belanja barang</strong> (operasional), <strong>belanja modal</strong> (aset tetap), <strong>bunga utang</strong>, <strong>subsidi</strong>, dan <strong>bantuan sosial</strong>.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Pembiayaan bukan pendapatan",
        html: "Penerbitan SBN dan pinjaman dicatat sebagai <strong>pembiayaan</strong>, bukan pendapatan. Keliru menggabungkannya akan membuat postur APBN tampak surplus padahal negara sedang berutang.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi pendapatan negara",
        unit: "%",
        source: "Ilustrasi struktur APBN, Kemenkeu",
        note: "Perpajakan mendominasi; PNBP dan hibah melengkapi.",
        data: [
          { label: "Penerimaan perpajakan", value: 82, color: "#2563eb" },
          { label: "PNBP", value: 17, color: "#16a34a" },
          { label: "Hibah", value: 1, color: "#f59e0b" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser pendapatan dan belanja untuk melihat bagaimana defisit dan kebutuhan pembiayaan berubah.",
      },
      { type: "widget", widget: "SimulatorAPBN" },
      {
        type: "case",
        title: "Studi Kasus: Menutup defisit Rp500 T",
        html: "Andai pendapatan negara Rp2.800 T (perpajakan Rp2.300 T, PNBP Rp490 T, hibah Rp10 T) dan belanja Rp3.300 T, maka defisit = Rp500 T. Defisit ini ditutup lewat <strong>pembiayaan</strong>, terutama penerbitan SBN neto sekitar Rp500 T. Jadi nilai SBN yang diterbitkan tidak menambah pendapatan, melainkan menambah utang yang harus dibayar kelak.",
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan negara Rp2.800 T, dengan penerimaan perpajakan Rp2.300 T. Berapa persen kontribusi perpajakan terhadap total pendapatan?",
        answer: 82.14,
        tolerance: 0.1,
        suffix: "%",
        solution: "Kontribusi = 2.300 / 2.800 x 100 = <strong>82,14%</strong>. Perpajakan jelas menjadi penopang utama pendapatan negara.",
        hint: "Bagi perpajakan dengan total pendapatan, lalu kali 100.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis belanja dengan contohnya.",
        pairs: [
          { left: "Belanja pegawai", right: "Gaji dan tunjangan ASN, TNI, dan Polri" },
          { left: "Belanja modal", right: "Pembangunan jalan, jembatan, dan gedung" },
          { left: "Belanja barang", right: "Operasional dan pemeliharaan rutin kantor" },
          { left: "Subsidi", right: "Menahan harga BBM, listrik, dan pupuk" },
          { left: "Bunga utang", right: "Beban bunga atas SBN dan pinjaman" },
        ],
      },
      {
        type: "video",
        comp: "PosturAPBN",
        title: "Video: Membedah postur APBN",
        caption: "Visualisasi aliran pendapatan, belanja, dan pembiayaan dalam satu postur APBN.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi belanja pemerintah pusat per jenis",
        unit: "%",
        source: "Ilustrasi struktur belanja, Kemenkeu",
        note: "Subsidi, belanja pegawai, dan bunga utang menyerap porsi besar belanja pusat.",
        data: [
          { label: "Belanja pegawai", value: 24, color: "#2563eb" },
          { label: "Belanja barang", value: 20, color: "#16a34a" },
          { label: "Belanja modal", value: 16, color: "#7c3aed" },
          { label: "Subsidi & bansos", value: 22, color: "#f59e0b" },
          { label: "Bunga utang", value: 18, color: "#dc2626" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Setiap pos di bawah masuk bagian APBN yang mana?",
        buckets: ["Pendapatan", "Belanja", "Pembiayaan"],
        items: [
          { text: "Cukai hasil tembakau", bucket: "Pendapatan" },
          { text: "Dividen BUMN", bucket: "Pendapatan" },
          { text: "Transfer ke Daerah & Dana Desa", bucket: "Belanja" },
          { text: "Bunga utang", bucket: "Belanja" },
          { text: "Pinjaman luar negeri neto", bucket: "Pembiayaan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Bonanza minyak 1970-an",
        html: "Saat harga minyak dunia melonjak pada 1970-an, penerimaan negara Indonesia membengkak karena <strong>migas</strong> sempat menyumbang sekitar dua pertiga pendapatan negara. Ketergantungan pada satu sumber ini membuat struktur pendapatan rapuh dan memunculkan risiko <strong>Dutch disease</strong>. Pengalaman ini mendorong upaya memperkuat penerimaan <strong>perpajakan</strong> sebagai tulang punggung yang lebih stabil.",
      },
      {
        type: "takeaways",
        items: [
          "Pendapatan, belanja, dan pembiayaan adalah tiga bagian APBN.",
          "Perpajakan menyumbang sekitar 80% pendapatan negara.",
          "Belanja pusat terbagi atas belanja pegawai, barang, modal, bunga utang, subsidi, dan bansos.",
          "Penerbitan SBN adalah pembiayaan, bukan pendapatan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Komponen pendapatan negara yang paling besar adalah?",
            options: ["PNBP", "Hibah", "Penerimaan perpajakan", "Penerbitan SBN"],
            answer: 2,
            explain: "Penerimaan perpajakan menyumbang sekitar 80% pendapatan negara.",
          },
          {
            q: "Royalti tambang dan dividen BUMN termasuk?",
            options: ["Perpajakan", "PNBP", "Hibah", "Pembiayaan"],
            answer: 1,
            explain: "Penerimaan Negara Bukan Pajak (PNBP) mencakup royalti SDA dan dividen BUMN.",
          },
          {
            q: "Penerbitan SBN dalam APBN dicatat sebagai?",
            options: ["Pendapatan", "Belanja", "Pembiayaan", "Hibah"],
            answer: 2,
            explain: "Penerbitan SBN adalah pembiayaan untuk menutup defisit, bukan pendapatan.",
          },
          {
            q: "Pembangunan jalan dan jembatan termasuk jenis belanja?",
            options: ["Belanja pegawai", "Belanja barang", "Belanja modal", "Subsidi"],
            answer: 2,
            explain: "Pembelian atau pembangunan aset tetap masuk belanja modal.",
          },
          {
            q: "Pendapatan Rp3.000 T, perpajakan Rp2.400 T. Kontribusi perpajakan?",
            options: ["60%", "70%", "80%", "90%"],
            answer: 2,
            explain: "2.400 / 3.000 x 100 = 80%.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "asumsi-makro-apbn",
    levelId: "apbn",
    order: 3,
    title: "Asumsi Dasar Ekonomi Makro",
    summary: "Lima asumsi makro yang menjadi pondasi seluruh angka APBN, plus bagaimana meleset sedikit saja bisa menggeser postur lewat sensitivitas.",
    durationMin: 13,
    tags: ["asumsi makro", "ICP", "kurs", "sensitivitas"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum angka APBN disusun, pemerintah dan DPR menyepakati <strong>asumsi dasar ekonomi makro</strong>. Lima asumsi utama adalah <strong>pertumbuhan ekonomi</strong>, <strong>inflasi</strong>, <strong>nilai tukar rupiah</strong>, <strong>harga minyak mentah Indonesia (ICP)</strong>, dan <strong>suku bunga SBN</strong>. Asumsi inilah yang menjadi pondasi proyeksi pendapatan dan belanja.",
      },
      {
        type: "paragraph",
        html: "Karena seluruh angka APBN dihitung di atas asumsi ini, perubahan kecil pada satu asumsi bisa menggeser triliunan rupiah. Hubungan ini disebut <strong>sensitivitas APBN</strong>. Misalnya pelemahan rupiah menaikkan penerimaan migas (dalam rupiah) tetapi sekaligus menambah beban subsidi energi dan bunga utang valas.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lima asumsi makro",
        html: "Pertumbuhan ekonomi (%), inflasi (%), nilai tukar (Rp/USD), ICP (USD/barel), dan suku bunga SBN (%). Lifting minyak dan gas sering ditambahkan sebagai asumsi pelengkap.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa ICP penting",
        html: "ICP memengaruhi dua sisi sekaligus: penerimaan negara dari migas naik saat harga minyak tinggi, tetapi <strong>subsidi energi</strong> juga membengkak. Dampak bersihnya bergantung pada apakah Indonesia net importir atau eksportir komoditas tersebut.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Asumsi yang terlalu optimistis",
        html: "Jika asumsi pertumbuhan dipatok terlalu tinggi, target pajak ikut tinggi dan berisiko tidak tercapai (shortfall), sehingga defisit riil bisa melebar dari rencana.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Asumsi nilai tukar rupiah dalam APBN",
        unit: "Rp/USD",
        source: "Ilustrasi asumsi makro APBN, Kemenkeu",
        note: "Tren asumsi kurs cenderung melemah dari tahun ke tahun.",
        data: [
          { label: "2021", value: 14350, color: "#2563eb" },
          { label: "2022", value: 14450, color: "#2563eb" },
          { label: "2023", value: 14800, color: "#2563eb" },
          { label: "2024", value: 15000, color: "#2563eb" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Rupiah melemah Rp500",
        html: "Misalkan setiap pelemahan rupiah sebesar Rp100/USD menambah beban bunga utang valas Rp1,2 T. Saat rupiah bergerak dari asumsi Rp15.000 ke Rp15.500/USD, beban bunga bertambah 5 x Rp1,2 T = Rp6 T. Inilah sebabnya pemerintah memantau kurs harian, karena efeknya langsung ke postur APBN.",
      },
      {
        type: "calcExercise",
        prompt: "Setiap pelemahan Rp100/USD menambah beban bunga utang valas Rp1,2 T. Bila rupiah melemah dari Rp15.000 menjadi Rp15.500/USD, berapa tambahan beban bunga (Rp triliun)?",
        answer: 6,
        tolerance: 0.1,
        suffix: " T",
        solution: "Pelemahan = (15.500 - 15.000) / 100 = 5 langkah. Tambahan = 5 x Rp1,2 T = <strong>Rp6 T</strong>.",
        hint: "Hitung berapa kelipatan Rp100, lalu kali Rp1,2 T.",
      },
      {
        type: "classifyExercise",
        prompt: "Mana yang termasuk asumsi dasar ekonomi makro APBN?",
        buckets: ["Asumsi makro APBN", "Bukan asumsi makro"],
        items: [
          { text: "Pertumbuhan ekonomi", bucket: "Asumsi makro APBN" },
          { text: "Tingkat inflasi", bucket: "Asumsi makro APBN" },
          { text: "Harga minyak (ICP)", bucket: "Asumsi makro APBN" },
          { text: "Suku bunga SBN", bucket: "Asumsi makro APBN" },
          { text: "Tarif PPN", bucket: "Bukan asumsi makro" },
          { text: "Jumlah kementerian", bucket: "Bukan asumsi makro" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser asumsi kurs dan ICP, lihat bagaimana pergeserannya berdampak pada penerimaan dan beban subsidi.",
      },
      { type: "widget", widget: "SimulatorAsumsiMakro" },
      {
        type: "chart",
        variant: "area",
        title: "Asumsi harga minyak (ICP) dalam APBN",
        unit: "USD/barel",
        source: "Ilustrasi asumsi makro APBN, Kemenkeu",
        note: "Asumsi ICP berfluktuasi mengikuti perkiraan harga minyak dunia.",
        data: [
          { label: "2021", value: 45, color: "#2563eb" },
          { label: "2022", value: 63, color: "#2563eb" },
          { label: "2023", value: 90, color: "#2563eb" },
          { label: "2024", value: 82, color: "#2563eb" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Setiap kenaikan ICP sebesar USD1/barel menambah penerimaan migas Rp0,8 T. Bila ICP naik dari asumsi USD80 menjadi USD90/barel, berapa tambahan penerimaan migas (Rp triliun)?",
        answer: 8,
        tolerance: 0.1,
        suffix: " T",
        solution: "Kenaikan = 90 - 80 = 10 USD/barel. Tambahan = 10 x Rp0,8 T = <strong>Rp8 T</strong>.",
        hint: "Hitung selisih ICP, lalu kali Rp0,8 T.",
      },
      {
        type: "case",
        title: "Sejarah: Asumsi kurs jebol pada 1997-1998",
        html: "Selama <strong>krisis moneter 1997-1998</strong>, asumsi nilai tukar dalam APBN jebol total ketika rupiah merosot dari sekitar Rp2.500 menjadi sempat menembus Rp16.000 per dolar AS. Pelemahan ekstrem ini melipatgandakan beban subsidi dan bunga utang valas dalam rupiah. Peristiwa ini menjadi pelajaran nyata tentang besarnya <strong>sensitivitas APBN</strong> terhadap perubahan satu asumsi makro.",
      },
      {
        type: "takeaways",
        items: [
          "Lima asumsi makro: pertumbuhan, inflasi, kurs, ICP, dan suku bunga SBN.",
          "Seluruh angka APBN dihitung di atas asumsi ini.",
          "Sensitivitas: perubahan kecil asumsi menggeser triliunan rupiah.",
          "Asumsi terlalu optimistis berisiko shortfall dan defisit melebar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Berikut yang BUKAN asumsi dasar ekonomi makro APBN?",
            options: ["Pertumbuhan ekonomi", "Inflasi", "Nilai tukar rupiah", "Jumlah penduduk miskin"],
            answer: 3,
            explain: "Asumsi makro mencakup pertumbuhan, inflasi, kurs, ICP, dan suku bunga SBN.",
          },
          {
            q: "ICP dalam asumsi makro merujuk pada?",
            options: ["Inflasi inti", "Harga minyak mentah Indonesia", "Indeks harga konsumen", "Suku bunga acuan"],
            answer: 1,
            explain: "ICP adalah Indonesian Crude Price, harga minyak mentah Indonesia.",
          },
          {
            q: "Pelemahan rupiah cenderung membuat beban bunga utang valas?",
            options: ["Turun", "Tetap", "Naik", "Hilang"],
            answer: 2,
            explain: "Utang dalam valuta asing menjadi lebih mahal dalam rupiah saat kurs melemah.",
          },
          {
            q: "Risiko utama bila asumsi pertumbuhan dipatok terlalu tinggi?",
            options: ["Inflasi pasti turun", "Target pajak berisiko tidak tercapai", "Kurs pasti menguat", "Defisit pasti hilang"],
            answer: 1,
            explain: "Target pajak yang terlalu tinggi berisiko shortfall sehingga defisit melebar.",
          },
          {
            q: "Setiap Rp100 pelemahan menambah bunga Rp1 T. Rupiah melemah Rp300, tambahan bunga?",
            options: ["Rp1 T", "Rp2 T", "Rp3 T", "Rp30 T"],
            answer: 2,
            explain: "300 / 100 = 3 langkah, 3 x Rp1 T = Rp3 T.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "siklus-penyusunan-apbn",
    levelId: "apbn",
    order: 4,
    title: "Siklus Penyusunan APBN",
    summary: "Empat tahap APBN dari perencanaan, penetapan oleh DPR, pelaksanaan, hingga pertanggungjawaban yang diaudit BPK, beserta peran tiap lembaga.",
    durationMin: 13,
    tags: ["siklus APBN", "DPR", "BPK", "Bappenas"],
    blocks: [
      {
        type: "paragraph",
        html: "APBN berputar dalam siklus tahunan empat tahap: <strong>perencanaan dan penganggaran</strong>, <strong>penetapan oleh DPR</strong>, <strong>pelaksanaan</strong>, lalu <strong>pelaporan dan pertanggungjawaban</strong> yang diaudit BPK. Setiap tahap melibatkan lembaga berbeda agar ada pembagian wewenang dan pengawasan.",
      },
      {
        type: "paragraph",
        html: "Perencanaan dimulai dari <strong>Bappenas</strong> yang menyusun Rencana Kerja Pemerintah (RKP) dan <strong>Kementerian Keuangan</strong> yang menyiapkan kerangka anggaran. Pemerintah menyampaikan RAPBN dan Nota Keuangan kepada DPR, yang membahas dan mengesahkannya menjadi UU APBN sebelum tahun anggaran berjalan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat tahap siklus",
        html: "1) Perencanaan & penganggaran, 2) Penetapan UU APBN oleh DPR, 3) Pelaksanaan oleh kementerian/lembaga, 4) Pertanggungjawaban (LKPP) yang diaudit BPK.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran lembaga",
        html: "<strong>Bappenas</strong> merencanakan, <strong>Kemenkeu</strong> menganggarkan dan mengelola kas, <strong>DPR</strong> membahas dan menetapkan (hak budget), <strong>K/L</strong> melaksanakan, dan <strong>BPK</strong> mengaudit secara independen.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Audit lalu lapor",
        html: "Setelah tahun anggaran berakhir, pemerintah menyusun LKPP yang diaudit BPK, kemudian disahkan DPR menjadi UU Pertanggungjawaban Pelaksanaan APBN. Inilah penutup siklus sekaligus pembuka akuntabilitas.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Pola penyerapan belanja per triwulan",
        unit: "%",
        source: "Ilustrasi pelaksanaan APBN, Kemenkeu",
        note: "Penyerapan cenderung menumpuk di akhir tahun (back-loaded).",
        data: [
          { label: "Triwulan I", value: 15, color: "#2563eb" },
          { label: "Triwulan II", value: 25, color: "#16a34a" },
          { label: "Triwulan III", value: 28, color: "#f59e0b" },
          { label: "Triwulan IV", value: 32, color: "#dc2626" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Satu putaran siklus",
        html: "Pada Mei, pemerintah menyampaikan kerangka ekonomi makro dan pokok kebijakan fiskal ke DPR. Pertengahan Agustus, Presiden menyampaikan RAPBN dan Nota Keuangan. DPR membahas dan mengesahkan UU APBN sebelum tahun anggaran. Sepanjang tahun, K/L melaksanakan belanja. Tahun berikutnya, LKPP disusun, diaudit BPK, lalu dipertanggungjawabkan ke DPR. Satu putaran penuh berlangsung lebih dari dua tahun.",
      },
      {
        type: "calcExercise",
        prompt: "Pagu belanja sebuah kementerian Rp1.100 T, realisasi sampai akhir tahun Rp990 T. Berapa persen tingkat penyerapan anggarannya?",
        answer: 90,
        tolerance: 0.1,
        suffix: "%",
        solution: "Penyerapan = 990 / 1.100 x 100 = <strong>90%</strong>. Sisa Rp110 T tidak terserap pada tahun tersebut.",
        hint: "Bagi realisasi dengan pagu, lalu kali 100.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan lembaga dengan perannya dalam siklus APBN.",
        pairs: [
          { left: "Bappenas", right: "Menyusun rencana pembangunan (RKP)" },
          { left: "Kementerian Keuangan", right: "Menganggarkan dan mengelola kas negara" },
          { left: "DPR", right: "Membahas dan menetapkan UU APBN" },
          { left: "BPK", right: "Mengaudit laporan keuangan pemerintah" },
          { left: "Kementerian/Lembaga", right: "Melaksanakan program dan belanja" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Durasi tiap tahap dalam satu putaran siklus APBN",
        unit: "bulan",
        source: "Ilustrasi siklus APBN, Kemenkeu & Bappenas",
        note: "Satu putaran penuh, dari perencanaan hingga pertanggungjawaban, berlangsung lebih dari dua tahun.",
        data: [
          { label: "Perencanaan & penganggaran", value: 8, color: "#2563eb" },
          { label: "Penetapan DPR", value: 4, color: "#16a34a" },
          { label: "Pelaksanaan", value: 12, color: "#f59e0b" },
          { label: "Pertanggungjawaban & audit BPK", value: 6, color: "#dc2626" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Pagu belanja Rp1.200 T, sampai akhir Triwulan III realisasi baru Rp780 T. Berapa persen anggaran yang masih harus diserap pada Triwulan IV?",
        answer: 35,
        tolerance: 0.1,
        suffix: "%",
        solution: "Sisa = 1.200 - 780 = Rp420 T. Persentase = 420 / 1.200 x 100 = <strong>35%</strong> yang harus diserap di Triwulan IV (pola back-loaded).",
        hint: "Hitung sisa pagu, lalu bagi dengan total pagu dan kali 100.",
      },
      {
        type: "case",
        title: "Sejarah: APBN direvisi berulang pada 1998",
        html: "Krisis 1997-1998 membuat asumsi APBN cepat usang, sehingga pemerintah harus <strong>merevisi APBN beberapa kali</strong> dalam tempo singkat mengikuti perubahan kurs dan harga. Ini menunjukkan siklus APBN bukan dokumen kaku, melainkan dapat disesuaikan lewat APBN Perubahan saat kondisi berubah drastis. Mekanisme perubahan ini tetap melalui pembahasan dan persetujuan <strong>DPR</strong>.",
      },
      {
        type: "takeaways",
        items: [
          "Siklus APBN: perencanaan, penetapan DPR, pelaksanaan, pertanggungjawaban.",
          "Bappenas merencanakan, Kemenkeu menganggarkan dan mengelola kas.",
          "DPR memegang hak budget untuk membahas dan menetapkan UU APBN.",
          "BPK mengaudit LKPP secara independen sebelum dipertanggungjawabkan ke DPR.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Urutan tahap siklus APBN yang benar?",
            options: [
              "Pelaksanaan, perencanaan, penetapan, audit",
              "Perencanaan, penetapan DPR, pelaksanaan, pertanggungjawaban",
              "Audit, pelaksanaan, perencanaan, penetapan",
              "Penetapan, audit, perencanaan, pelaksanaan",
            ],
            answer: 1,
            explain: "Siklus berjalan dari perencanaan, penetapan DPR, pelaksanaan, lalu pertanggungjawaban.",
          },
          {
            q: "Lembaga yang menyusun Rencana Kerja Pemerintah (RKP)?",
            options: ["BPK", "Bappenas", "DPR", "Bank Indonesia"],
            answer: 1,
            explain: "Bappenas menyusun perencanaan pembangunan termasuk RKP.",
          },
          {
            q: "Yang memegang hak budget untuk menetapkan UU APBN?",
            options: ["Presiden", "DPR", "BPK", "Kemenkeu"],
            answer: 1,
            explain: "DPR membahas bersama pemerintah dan menetapkan UU APBN.",
          },
          {
            q: "LKPP sebelum dipertanggungjawabkan ke DPR diaudit oleh?",
            options: ["OJK", "BPK", "Bappenas", "BI"],
            answer: 1,
            explain: "BPK mengaudit Laporan Keuangan Pemerintah Pusat (LKPP) secara independen.",
          },
          {
            q: "Pagu Rp800 T, realisasi Rp720 T. Tingkat penyerapan?",
            options: ["80%", "85%", "90%", "95%"],
            answer: 2,
            explain: "720 / 800 x 100 = 90%.",
          },
        ],
      },
    ],
  },
];
