import type { Lesson } from "../../../types";

export const level6: Lesson[] = [
  // ============================================================
  {
    id: "strategi-net-zero",
    levelId: "strategi",
    order: 1,
    title: "Strategi Perusahaan Menuju Net-Zero",
    summary: "Bagaimana perusahaan menyusun jalur kredibel ke net-zero, dari pengukuran sampai offset.",
    durationMin: 14,
    tags: ["bisnis", "net-zero", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Net-zero</strong> berarti menyeimbangkan emisi yang dilepas dengan yang diserap atau dikurangi, hingga bersih nol. Strategi yang kredibel bukan sekadar membeli offset, melainkan jalur bertahap yang dimulai dari pengukuran dan pengurangan nyata.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Jalur Dekarbonisasi Menuju Net-Zero",
        unit: "tCO2e per tahun (ilustrasi)",
        source: "ilustrasi pathway perusahaan",
        note: "Emisi diturunkan bertahap lewat efisiensi dan energi bersih; offset hanya menutup sisa kecil di akhir.",
        data: [
          { label: "2025", value: 100 },
          { label: "2030", value: 70 },
          { label: "2035", value: 45 },
          { label: "2040", value: 25 },
          { label: "2045", value: 10 },
          { label: "2050", value: 2 },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Langkah strategi net-zero",
        html: "1) Ukur jejak (Scope 1, 2, 3). 2) Tetapkan target berbasis sains (SBTi). 3) Kurangi lewat efisiensi & energi bersih. 4) Beralih teknologi. 5) Offset sisa emisi yang sulit dihilangkan dengan kredit berkualitas.",
      },
      {
        type: "stats",
        items: [
          { value: "SBTi", label: "Target berbasis sains", sub: "selaras jalur 1,5°C", color: "#10b981" },
          { value: "Scope 1-3", label: "Cakupan menyeluruh", sub: "termasuk rantai nilai", color: "#0ea5e9" },
          { value: "Sisa", label: "Baru di-offset", sub: "setelah dikurangi maksimal", color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua jalur net-zero",
        html: "Perusahaan A langsung membeli offset untuk seluruh emisinya dan mengklaim net-zero, tanpa mengubah operasi. Perusahaan B menurunkan emisi 60% lewat efisiensi dan PLTS, lalu meng-offset 40% sisanya dengan kredit berkualitas. Saat investor dan regulator memeriksa, hanya klaim B yang dianggap kredibel. Net-zero yang sehat menempatkan pengurangan nyata sebagai inti.",
      },
      {
        type: "calcExercise",
        prompt: "Emisi awal perusahaan 100.000 tCO2e. Setelah efisiensi dan energi bersih, turun 65%. Berapa sisa emisi yang perlu di-offset?",
        answer: 35000,
        tolerance: 0,
        suffix: "tCO2e",
        solution: "Sisa = 100.000 x (1 - 0,65) = 100.000 x 0,35 = <strong>35.000 tCO2e</strong> yang perlu di-offset.",
        hint: "Hitung sisa setelah pengurangan persentase.",
      },
      {
        type: "classifyExercise",
        prompt: "Langkah ini bagian dari strategi net-zero yang kredibel atau jalan pintas yang berisiko?",
        buckets: ["Kredibel", "Jalan pintas berisiko"],
        items: [
          { text: "Mengukur emisi Scope 1, 2, dan 3", bucket: "Kredibel" },
          { text: "Menetapkan target berbasis sains (SBTi)", bucket: "Kredibel" },
          { text: "Membeli offset murah untuk semua emisi tanpa mengubah operasi", bucket: "Jalan pintas berisiko" },
          { text: "Memasang energi terbarukan", bucket: "Kredibel" },
          { text: "Mengabaikan Scope 3", bucket: "Jalan pintas berisiko" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tahap mitigation hierarchy dengan contoh aksinya.",
        pairs: [
          { left: "Hindari", right: "Mendesain ulang proses agar tidak ada emisi sejak awal" },
          { left: "Kurangi", right: "Efisiensi energi dan pengurangan limbah" },
          { left: "Substitusi", right: "Mengganti boiler gas dengan pompa panas listrik" },
          { left: "Offset", right: "Membeli kredit berkualitas untuk emisi residual" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik semen menyusun target SBTi",
        html: "Sebuah pabrik semen mengukur emisi 2025 sebesar 2.000.000 tCO2e. Mereka menetapkan target near-term SBTi: turun 42% pada 2030 (sejalan jalur 1,5°C), sehingga emisi target 2030 = 2.000.000 x 0,58 = 1.160.000 tCO2e. Caranya: substitusi bahan bakar dengan biomassa (turun 300.000 tCO2e), efisiensi panas (turun 240.000 tCO2e), dan klinker faktor rendah (turun 300.000 tCO2e). Total pengurangan 840.000 tCO2e tercapai tanpa offset. Sisa emisi residual yang sulit dihilangkan, seperti proses kalsinasi, baru direncanakan ditangani lewat CCS dan offset menjelang 2050.",
      },
      {
        type: "takeaways",
        items: [
          "Net-zero menyeimbangkan emisi yang dilepas dengan yang dikurangi/diserap.",
          "Mulai dari mengukur, lalu target berbasis sains, lalu kurangi nyata.",
          "Offset hanya untuk sisa emisi yang sulit dihilangkan.",
          "Klaim kredibel mengutamakan pengurangan, bukan pembelian offset semata.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Langkah pertama strategi net-zero yang baik adalah?",
            options: ["Membeli offset", "Mengukur jejak emisi (Scope 1-3)", "Mengumumkan ke media", "Menaikkan produksi"],
            answer: 1,
            explain: "Tanpa mengukur emisi lebih dulu, target dan strategi tidak punya dasar.",
          },
          {
            q: "SBTi mendorong perusahaan menetapkan target yang?",
            options: ["Asal-asalan", "Berbasis sains, selaras jalur 1,5°C", "Tanpa batas waktu", "Hanya Scope 1"],
            answer: 1,
            explain: "Science Based Targets initiative memastikan target selaras dengan sains iklim.",
          },
          {
            q: "Offset dalam strategi net-zero sebaiknya?",
            options: [
              "Menggantikan semua pengurangan",
              "Menutup sisa emisi yang sulit dihilangkan",
              "Jadi langkah pertama",
              "Dihindari total",
            ],
            answer: 1,
            explain: "Offset adalah pelengkap untuk emisi residual, bukan pengganti pengurangan.",
          },
          {
            q: "Emisi 100.000 tCO2e turun 65%. Sisa yang di-offset?",
            options: ["65.000", "35.000", "100.000", "50.000"],
            answer: 1,
            explain: "100.000 x 0,35 = 35.000 tCO2e.",
          },
          {
            q: "Mengapa klaim net-zero tanpa pengurangan nyata berisiko?",
            options: [
              "Karena terlalu mahal",
              "Karena dianggap greenwashing dan merusak kepercayaan",
              "Karena dilarang menanam pohon",
              "Karena tidak ada offset",
            ],
            answer: 1,
            explain: "Net-zero yang hanya bergantung offset tanpa menurunkan emisi sendiri rawan dinilai greenwashing.",
          },
          {
            q: "Urutan mitigation hierarchy yang benar adalah?",
            options: [
              "Offset, kurangi, hindari",
              "Hindari/kurangi emisi, ganti teknologi, baru offset sisa",
              "Offset dulu, lalu abaikan sisanya",
              "Beli kredit, lalu naikkan produksi",
            ],
            answer: 1,
            explain: "Mitigation hierarchy: hindari dan kurangi emisi dulu, substitusi teknologi bersih, baru offset emisi residual.",
          },
          {
            q: "Target SBTi 'near-term' biasanya mencakup horizon waktu?",
            options: ["1 tahun", "5 sampai 10 tahun", "100 tahun", "Tanpa batas"],
            answer: 1,
            explain: "SBTi mensyaratkan target jangka pendek (umumnya 5-10 tahun) sebagai batu loncatan menuju net-zero jangka panjang.",
          },
          {
            q: "Apa yang dimaksud 'emisi residual' dalam net-zero?",
            options: [
              "Seluruh emisi perusahaan",
              "Emisi yang tersisa setelah pengurangan maksimal, yang sulit dihilangkan",
              "Emisi yang sudah di-offset",
              "Emisi Scope 2 saja",
            ],
            answer: 1,
            explain: "Emisi residual adalah sisa yang sulit dihilangkan secara teknis/ekonomi, dan hanya inilah yang boleh di-offset/di-neutralisasi.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "keunggulan-kompetitif",
    levelId: "strategi",
    order: 2,
    title: "Karbon sebagai Keunggulan Kompetitif",
    summary: "Bagaimana kinerja iklim menjadi sumber daya saing, akses pasar, dan akses modal.",
    durationMin: 13,
    tags: ["bisnis", "strategi", "daya saing"],
    blocks: [
      {
        type: "paragraph",
        html: "Mengelola karbon bukan sekadar biaya kepatuhan, tetapi bisa menjadi <strong>keunggulan kompetitif</strong>. Perusahaan rendah karbon menarik investor ESG, lolos persyaratan rantai pasok global, dan lebih tahan terhadap kebijakan iklim yang makin ketat.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Manfaat Bisnis dari Kepemimpinan Iklim",
        unit: "skor dampak (ilustrasi)",
        source: "ilustrasi persepsi manfaat",
        note: "Akses modal dan akses pasar global sering menjadi pendorong terbesar bagi korporasi.",
        data: [
          { label: "Akses modal (ESG)", value: 85 },
          { label: "Akses pasar global", value: 80 },
          { label: "Efisiensi biaya", value: 65 },
          { label: "Citra & loyalitas", value: 60 },
          { label: "Tahan regulasi", value: 75 },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Rantai pasok memaksa perubahan",
        html: "Banyak perusahaan global menuntut pemasoknya melaporkan dan menurunkan emisi (bagian dari Scope 3 mereka). Pemasok yang tidak siap bisa kehilangan kontrak. Karbon menjadi syarat masuk, bukan sekadar nilai tambah.",
      },
      {
        type: "case",
        title: "Studi Kasus: Pemasok yang kalah tender",
        html: "Dua pemasok komponen bersaing untuk kontrak besar dari merek elektronik global. Keduanya seharga, tetapi merek itu mensyaratkan data emisi dan rencana penurunan. Pemasok yang sudah memetakan jejak karbonnya dan memakai energi terbarukan memenangkan kontrak. Pesaingnya, meski produknya bagus, gugur karena tidak siap soal karbon. Kesiapan iklim menjadi pembeda nyata.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan manfaat kompetitif dengan contohnya.",
        pairs: [
          { left: "Akses modal", right: "Menarik investor dan pinjaman ESG" },
          { left: "Akses pasar", right: "Lolos syarat rantai pasok global" },
          { left: "Efisiensi", right: "Hemat energi menurunkan biaya operasi" },
          { left: "Ketahanan regulasi", right: "Lebih siap saat aturan iklim diperketat" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Tindakan ini memperkuat atau melemahkan daya saing iklim perusahaan?",
        buckets: ["Memperkuat", "Melemahkan"],
        items: [
          { text: "Memetakan jejak karbon dan menetapkan target", bucket: "Memperkuat" },
          { text: "Beralih ke energi terbarukan", bucket: "Memperkuat" },
          { text: "Mengabaikan permintaan data emisi pembeli", bucket: "Melemahkan" },
          { text: "Menunda semua aksi iklim", bucket: "Melemahkan" },
          { text: "Transparan dalam pelaporan ESG", bucket: "Memperkuat" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Efisiensi energi memangkas 8.000 tCO2e dan sekaligus menghemat biaya energi Rp1.200 per tCO2e yang dipangkas? Anggap penghematan = 8.000 x Rp150.000. Berapa total penghematan energinya?",
        answer: 1200000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Penghematan = 8.000 x Rp150.000 = <strong>Rp1.200.000.000</strong>. Pengurangan emisi dan penghematan biaya bisa berjalan bersama.",
        hint: "Kalikan jumlah ton yang dipangkas dengan penghematan per ton (Rp150.000).",
      },
      {
        type: "case",
        title: "Studi Kasus: Eksportir tekstil dan CBAM",
        html: "Sebuah eksportir tekstil mengirim 10.000 ton produk per tahun ke Uni Eropa dengan intensitas emisi 2 tCO2e per ton, sehingga total 20.000 tCO2e. Dengan harga karbon UE sekitar EUR 80 per tCO2e, potensi pungutan CBAM mencapai 20.000 x EUR 80 = EUR 1.600.000 per tahun. Perusahaan lalu memasang PLTS atap dan beralih ke pewarnaan hemat energi, menurunkan intensitas menjadi 1,2 tCO2e per ton (total 12.000 tCO2e). Pungutan turun menjadi 12.000 x EUR 80 = EUR 960.000, hemat EUR 640.000 per tahun sekaligus memperkuat posisi tawar terhadap pesaing yang belum berbenah.",
      },
      {
        type: "takeaways",
        items: [
          "Kinerja karbon dapat menjadi keunggulan kompetitif, bukan sekadar biaya.",
          "Akses modal ESG dan akses pasar global adalah pendorong terbesar.",
          "Rantai pasok global menuntut data dan penurunan emisi pemasok.",
          "Kesiapan iklim makin menjadi syarat masuk, bukan nilai tambah opsional.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mengapa karbon bisa jadi keunggulan kompetitif?",
            options: [
              "Karena menambah emisi",
              "Karena membuka akses modal ESG dan pasar global",
              "Karena tidak ada gunanya",
              "Karena menaikkan biaya saja",
            ],
            answer: 1,
            explain: "Kinerja iklim yang baik menarik modal dan membuka akses pasar yang menuntut keberlanjutan.",
          },
          {
            q: "Bagaimana rantai pasok memengaruhi pemasok soal karbon?",
            options: [
              "Tidak berpengaruh",
              "Pembeli global menuntut data dan penurunan emisi pemasok",
              "Pemasok bebas mengabaikan",
              "Hanya soal harga",
            ],
            answer: 1,
            explain: "Emisi pemasok adalah Scope 3 pembeli, sehingga pembeli menuntut transparansi dan penurunan.",
          },
          {
            q: "Manakah yang memperkuat daya saing iklim?",
            options: ["Mengabaikan ESG", "Beralih ke energi terbarukan", "Menunda aksi", "Menyembunyikan data"],
            answer: 1,
            explain: "Beralih ke energi bersih menurunkan emisi dan memperkuat posisi kompetitif.",
          },
          {
            q: "Efisiensi energi dapat memberi manfaat ganda berupa?",
            options: [
              "Menambah emisi dan biaya",
              "Menurunkan emisi sekaligus menghemat biaya",
              "Hanya citra",
              "Tidak ada manfaat",
            ],
            answer: 1,
            explain: "Efisiensi memangkas emisi dan biaya energi sekaligus.",
          },
          {
            q: "Kesiapan iklim kini cenderung menjadi?",
            options: ["Nilai tambah opsional saja", "Syarat masuk untuk banyak pasar dan kontrak", "Hal yang tidak relevan", "Beban tanpa manfaat"],
            answer: 1,
            explain: "Makin banyak pasar menjadikan kesiapan iklim sebagai prasyarat, bukan sekadar bonus.",
          },
          {
            q: "Mekanisme seperti CBAM (Carbon Border Adjustment Mechanism) Uni Eropa mendorong eksportir untuk?",
            options: [
              "Mengabaikan emisi produksi",
              "Menurunkan emisi produk agar tidak kena pungutan karbon di perbatasan",
              "Menaikkan emisi",
              "Berhenti mengekspor",
            ],
            answer: 1,
            explain: "CBAM mengenakan biaya karbon pada produk impor berkarbon tinggi, sehingga eksportir rendah karbon lebih kompetitif di pasar UE.",
          },
          {
            q: "Investor sering memakai skor ESG untuk?",
            options: [
              "Menilai risiko dan keberlanjutan perusahaan sebelum berinvestasi",
              "Menentukan warna logo",
              "Menghitung pajak penjualan",
              "Memilih lokasi kantor",
            ],
            answer: 0,
            explain: "Skor ESG menjadi penyaring risiko bagi investor; kinerja iklim yang baik memperluas akses ke modal.",
          },
          {
            q: "Keuntungan 'first mover' dalam dekarbonisasi adalah?",
            options: [
              "Selalu rugi",
              "Mendahului pesaing dalam efisiensi, reputasi, dan akses pasar saat regulasi mengetat",
              "Tidak ada bedanya",
              "Hanya soal pajak",
            ],
            answer: 1,
            explain: "Perusahaan yang bergerak lebih awal mengunci penghematan, reputasi, dan posisi pasar sebelum aturan memaksa semua pemain.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "dampak-sosial-keadilan",
    levelId: "strategi",
    order: 3,
    title: "Dampak Sosial & Keadilan Iklim",
    summary: "Memastikan perdagangan karbon adil bagi masyarakat lokal dan masyarakat adat.",
    durationMin: 14,
    tags: ["sosial", "keadilan iklim", "masyarakat adat"],
    blocks: [
      {
        type: "paragraph",
        html: "Proyek karbon sering berada di wilayah masyarakat lokal dan adat. Tanpa perhatian pada <strong>keadilan</strong>, proyek bisa merugikan mereka yang justru paling menjaga alam. Karbon yang baik harus memberi manfaat, bukan merampas hak.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Keadilan iklim",
        html: "<strong>Keadilan iklim</strong> menyoroti ketimpangan: negara dan masyarakat miskin paling sedikit menyumbang emisi, tetapi paling menderita dampaknya. Perdagangan karbon harus tidak memperparah ketimpangan ini.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Emisi per Kapita vs Kerentanan Iklim (Ilustrasi)",
        unit: "indeks relatif",
        source: "ilustrasi prinsip keadilan iklim",
        note: "Kelompok dengan emisi per kapita rendah sering justru paling rentan terhadap dampak iklim.",
        data: [
          { label: "Negara kaya: emisi", value: 90, color: "#ef4444" },
          { label: "Negara kaya: kerentanan", value: 30, color: "#0ea5e9" },
          { label: "Negara miskin: emisi", value: 20, color: "#ef4444" },
          { label: "Negara miskin: kerentanan", value: 85, color: "#0ea5e9" },
        ],
      },
      {
        type: "table",
        caption: "Prinsip sosial proyek karbon",
        headers: ["Prinsip", "Maksud"],
        rows: [
          ["FPIC", "Free, Prior, Informed Consent: persetujuan masyarakat tanpa paksaan"],
          ["Benefit sharing", "Pembagian manfaat ekonomi yang adil ke masyarakat"],
          ["Pengakuan hak", "Menghormati hak tanah dan hutan adat"],
          ["Co-benefit", "Manfaat tambahan: lapangan kerja, air bersih, biodiversitas"],
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Masyarakat adat penjaga hutan",
        html: "Sebuah proyek REDD+ dibangun di hutan adat. Pada model buruk, perusahaan mengambil hampir seluruh hasil penjualan kredit, sementara masyarakat yang menjaga hutan turun-temurun hanya menerima sedikit. Pada model baik, ada perjanjian FPIC dan benefit sharing yang jelas, sehingga masyarakat menerima bagian adil dan termotivasi terus menjaga hutan. Keadilan bukan hanya etis, tetapi membuat proyek lebih lestari.",
      },
      {
        type: "calcExercise",
        prompt: "Proyek menghasilkan pendapatan kredit Rp10.000.000.000 setahun. Jika skema benefit sharing memberi 40% ke masyarakat, berapa bagian masyarakat?",
        answer: 4000000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Bagian masyarakat = 40% x Rp10.000.000.000 = <strong>Rp4.000.000.000</strong> per tahun.",
        hint: "Kalikan total pendapatan dengan persentase bagi hasil masyarakat.",
      },
      {
        type: "classifyExercise",
        prompt: "Praktik ini adil bagi masyarakat atau berisiko merugikan?",
        buckets: ["Adil", "Berisiko merugikan"],
        items: [
          { text: "Meminta persetujuan FPIC sebelum proyek", bucket: "Adil" },
          { text: "Skema benefit sharing yang transparan", bucket: "Adil" },
          { text: "Mengambil hampir seluruh hasil ke perusahaan", bucket: "Berisiko merugikan" },
          { text: "Menggusur akses masyarakat ke hutan", bucket: "Berisiko merugikan" },
          { text: "Mempekerjakan warga lokal sebagai penjaga hutan", bucket: "Adil" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan komponen FPIC dan keadilan sosial dengan maknanya.",
        pairs: [
          { left: "Free", right: "Tanpa tekanan, intimidasi, atau manipulasi" },
          { left: "Prior", right: "Sebelum proyek dimulai, dengan waktu memadai" },
          { left: "Informed", right: "Berdasarkan informasi lengkap dan dapat dipahami" },
          { left: "Benefit sharing", right: "Pembagian hasil ekonomi yang adil ke masyarakat" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua skema bagi hasil REDD+",
        html: "Proyek REDD+ menghasilkan 200.000 kredit per tahun yang terjual seharga USD 8 per kredit, total pendapatan USD 1.600.000. Pada skema buruk, masyarakat hanya menerima 5% atau USD 80.000, sementara sisanya diambil pengembang dan perantara, sehingga warga kehilangan motivasi menjaga hutan. Pada skema adil dengan FPIC, masyarakat menerima 50% atau USD 800.000 yang dialokasikan untuk dana desa, beasiswa, dan gaji 40 penjaga hutan. Hasilnya laju deforestasi turun drastis, karena masyarakat melihat hutan bernilai lebih besar saat dijaga daripada saat ditebang.",
      },
      {
        type: "takeaways",
        items: [
          "Proyek karbon harus adil bagi masyarakat lokal dan adat.",
          "Keadilan iklim: yang paling sedikit menyumbang emisi sering paling menderita.",
          "FPIC dan benefit sharing adalah prinsip kunci.",
          "Keadilan membuat proyek lebih lestari, bukan sekadar etis.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "FPIC adalah?",
            options: [
              "Jenis pajak",
              "Persetujuan masyarakat secara bebas, didahulukan, dan terinformasi",
              "Nama bursa",
              "Standar akuntansi",
            ],
            answer: 1,
            explain: "FPIC (Free, Prior, Informed Consent) memastikan masyarakat setuju tanpa paksaan dan dengan informasi cukup.",
          },
          {
            q: "Inti keadilan iklim adalah?",
            options: [
              "Yang kaya paling menderita",
              "Yang paling sedikit menyumbang emisi sering paling terdampak",
              "Semua sama rata emisinya",
              "Tidak ada ketimpangan",
            ],
            answer: 1,
            explain: "Keadilan iklim menyoroti ketimpangan antara penyumbang emisi dan korban dampaknya.",
          },
          {
            q: "Benefit sharing berarti?",
            options: [
              "Perusahaan ambil semua",
              "Pembagian manfaat ekonomi yang adil ke masyarakat",
              "Pajak baru",
              "Larangan proyek",
            ],
            answer: 1,
            explain: "Benefit sharing memastikan masyarakat penjaga alam menerima bagian yang adil.",
          },
          {
            q: "Pendapatan Rp5 miliar, bagi hasil masyarakat 30%. Bagian masyarakat?",
            options: ["Rp1,5 miliar", "Rp500 juta", "Rp3 miliar", "Rp150 juta"],
            answer: 0,
            explain: "30% x Rp5 miliar = Rp1,5 miliar.",
          },
          {
            q: "Mengapa keadilan membuat proyek lebih lestari?",
            options: [
              "Karena masyarakat termotivasi terus menjaga alam",
              "Karena harga naik",
              "Karena pajak turun",
              "Tidak ada hubungannya",
            ],
            answer: 0,
            explain: "Masyarakat yang menerima manfaat adil punya insentif menjaga proyek dalam jangka panjang.",
          },
          {
            q: "Huruf 'P' (Prior) dalam FPIC menekankan bahwa persetujuan harus?",
            options: [
              "Diberikan setelah proyek berjalan",
              "Diperoleh sebelum keputusan dan aktivitas proyek dimulai",
              "Tidak perlu waktu",
              "Diberikan oleh pemerintah saja",
            ],
            answer: 1,
            explain: "Prior berarti persetujuan harus didapatkan sebelum kegiatan dimulai, dengan waktu cukup untuk pertimbangan.",
          },
          {
            q: "Apa contoh 'co-benefit' sosial dari proyek karbon yang baik?",
            options: [
              "Penggusuran warga",
              "Lapangan kerja, air bersih, dan pemulihan biodiversitas",
              "Kenaikan harga karbon",
              "Pengurangan transparansi",
            ],
            answer: 1,
            explain: "Co-benefit adalah manfaat tambahan di luar penyerapan karbon, seperti pekerjaan, air bersih, dan keanekaragaman hayati.",
          },
          {
            q: "Prinsip 'tanggung jawab bersama tetapi berbeda' (CBDR) menyiratkan?",
            options: [
              "Semua negara menanggung beban sama persis",
              "Negara yang lebih kaya dan lebih banyak menyumbang emisi historis menanggung beban lebih besar",
              "Negara miskin menanggung paling banyak",
              "Tidak ada yang bertanggung jawab",
            ],
            answer: 1,
            explain: "CBDR mengakui kapasitas dan tanggung jawab historis yang berbeda antarnegara dalam menangani iklim.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "etika-karbon",
    levelId: "strategi",
    order: 4,
    title: "Etika Carbon Trading",
    summary: "Dilema moral: additionality, moral hazard, dan carbon colonialism.",
    durationMin: 13,
    tags: ["etika", "moral hazard", "carbon colonialism"],
    blocks: [
      {
        type: "paragraph",
        html: "Perdagangan karbon menimbulkan pertanyaan etis. Apakah membayar untuk mencemari itu adil? Apakah offset membuat orang malas mengurangi emisi sendiri? Bab ini membedah dilema moral yang sering luput dibahas.",
      },
      {
        type: "table",
        caption: "Dilema etika utama",
        headers: ["Isu", "Pertanyaan moral"],
        rows: [
          ["Moral hazard", "Apakah offset membuat orang merasa boleh terus mencemari?"],
          ["Additionality", "Apakah kredit benar-benar menambah pengurangan, atau cuma klaim?"],
          ["Carbon colonialism", "Apakah negara kaya 'membeli' hak mencemari di tanah negara miskin?"],
          ["Right to develop", "Apakah adil melarang negara miskin tumbuh seperti negara kaya dulu?"],
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Carbon colonialism",
        html: "<strong>Carbon colonialism</strong> adalah kritik bahwa negara/korporasi kaya memakai lahan dan hutan di negara berkembang untuk meng-offset emisinya, alih-alih menurunkan emisi di negeri sendiri, kadang mengorbankan masyarakat lokal.",
      },
      {
        type: "case",
        title: "Studi Kasus: Offset vs pengurangan di sumber",
        html: "Sebuah maskapai negara maju membeli offset hutan murah di negara tropis untuk mengklaim penerbangan 'hijau', sementara tetap menambah jumlah penerbangan tiap tahun. Kritikus menyebut ini moral hazard: offset dipakai sebagai izin untuk terus mencemari, bukan sebagai pelengkap pengurangan nyata. Pertanyaan etisnya: apakah uang bisa benar-benar 'menghapus' emisi, atau hanya memindahkan tanggung jawab?",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini menggambarkan isu etika yang mana?",
        buckets: ["Moral hazard", "Carbon colonialism", "Additionality"],
        items: [
          { text: "Perusahaan terus menambah emisi karena merasa cukup beli offset", bucket: "Moral hazard" },
          { text: "Negara kaya meng-offset di tanah negara miskin alih-alih mengurangi sendiri", bucket: "Carbon colonialism" },
          { text: "Kredit terbit untuk hutan yang memang tidak akan ditebang", bucket: "Additionality" },
          { text: "Offset jadi alasan menunda transisi nyata", bucket: "Moral hazard" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan konsep etika dengan maknanya.",
        pairs: [
          { left: "Moral hazard", right: "Offset jadi izin untuk terus mencemari" },
          { left: "Carbon colonialism", right: "Beban pengurangan dilempar ke negara miskin" },
          { left: "Additionality", right: "Syarat agar kredit benar-benar bermakna" },
          { left: "Right to develop", right: "Hak negara berkembang untuk tumbuh secara adil" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah proyek menerbitkan 100.000 kredit, tetapi audit independen menemukan baseline dilebihkan sehingga pengurangan nyata hanya 60.000 tCO2e. Berapa kredit 'hantu' (tanpa additionality) yang seharusnya tidak terbit?",
        answer: 40000,
        tolerance: 0,
        suffix: "kredit",
        solution: "Kredit hantu = 100.000 - 60.000 = <strong>40.000 kredit</strong>. Inilah kredit yang melanggar additionality dan menyesatkan pembeli.",
        hint: "Selisih antara kredit terbit dan pengurangan nyata yang terverifikasi.",
      },
      {
        type: "case",
        title: "Studi Kasus: Maskapai, offset, dan additionality",
        html: "Sebuah maskapai mengemisi 500.000 tCO2e per tahun dan membeli 500.000 kredit hutan seharga USD 4 per kredit (total USD 2.000.000) untuk mengklaim 'penerbangan netral karbon', sambil menambah 5% kapasitas penerbangan tiap tahun. Investigasi menemukan 90% kredit berasal dari hutan yang memang tidak terancam ditebang, sehingga tanpa additionality. Artinya hanya 50.000 kredit yang benar-benar bermakna, dan 450.000 sisanya tidak menghapus emisi apa pun. Kasus ini menggabungkan tiga dilema sekaligus: moral hazard (offset jadi izin terus terbang), additionality yang gagal, dan carbon colonialism karena beban dilempar ke hutan negara berkembang.",
      },
      {
        type: "takeaways",
        items: [
          "Perdagangan karbon membawa dilema etika yang nyata.",
          "Moral hazard: offset bisa jadi alasan menunda pengurangan nyata.",
          "Carbon colonialism mengkritik pelemparan beban ke negara berkembang.",
          "Offset etis adalah pelengkap pengurangan, bukan penggantinya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Moral hazard dalam karbon berarti?",
            options: [
              "Kredit terlalu mahal",
              "Offset membuat pihak merasa boleh terus mencemari",
              "Tidak ada offset",
              "Pajak ganda",
            ],
            answer: 1,
            explain: "Moral hazard: keberadaan offset mengurangi dorongan untuk benar-benar menurunkan emisi.",
          },
          {
            q: "Carbon colonialism mengkritik?",
            options: [
              "Negara miskin yang mencemari",
              "Negara/korporasi kaya yang meng-offset di tanah negara berkembang alih-alih mengurangi sendiri",
              "Harga karbon yang rendah",
              "Pajak karbon",
            ],
            answer: 1,
            explain: "Kritik ini menyoroti pelemparan beban pengurangan ke negara berkembang.",
          },
          {
            q: "Mengapa additionality juga isu etis?",
            options: [
              "Karena soal harga",
              "Karena kredit tanpa additionality adalah klaim kosong yang menyesatkan",
              "Karena soal pajak",
              "Karena tidak relevan",
            ],
            answer: 1,
            explain: "Tanpa additionality, kredit tidak menambah pengurangan nyata, sehingga klaimnya tidak jujur.",
          },
          {
            q: "Offset yang etis sebaiknya berperan sebagai?",
            options: [
              "Pengganti seluruh pengurangan",
              "Pelengkap setelah pengurangan nyata dilakukan",
              "Izin mencemari tanpa batas",
              "Alat menunda transisi",
            ],
            answer: 1,
            explain: "Secara etis, offset melengkapi pengurangan nyata, bukan menggantikannya.",
          },
          {
            q: "Right to develop menyangkut?",
            options: [
              "Hak perusahaan menaikkan harga",
              "Hak negara berkembang untuk tumbuh secara adil",
              "Hak mencemari tanpa batas",
              "Hak menolak MRV",
            ],
            answer: 1,
            explain: "Isu ini menimbang keadilan antara kebutuhan pembangunan dan tanggung jawab iklim.",
          },
          {
            q: "Mengapa 'over-crediting' (kredit melebihi pengurangan nyata) bermasalah secara etis?",
            options: [
              "Karena harga jadi terlalu murah",
              "Karena emisi yang diklaim terhapus sebenarnya masih terjadi, sehingga merugikan iklim",
              "Karena kredit habis cepat",
              "Karena pajak naik",
            ],
            answer: 1,
            explain: "Over-crediting membuat pembeli mengira emisinya netral padahal emisi nyata tetap ada, memperburuk kondisi iklim.",
          },
          {
            q: "Konsep 'baseline gaming' terkait erat dengan pelanggaran?",
            options: ["Transparansi harga", "Additionality", "Hak cipta", "Pajak ganda"],
            answer: 1,
            explain: "Menetapkan baseline yang sengaja dilebih-lebihkan menghasilkan kredit semu, melanggar prinsip additionality.",
          },
          {
            q: "Salah satu cara mengurangi risiko carbon colonialism adalah?",
            options: [
              "Mengabaikan masyarakat lokal",
              "Memastikan negara tuan rumah dan masyarakat mendapat manfaat serta kendali nyata atas proyek",
              "Memusatkan semua keputusan di negara pembeli",
              "Menghapus FPIC",
            ],
            answer: 1,
            explain: "Kepemilikan, kendali, dan manfaat yang adil bagi tuan rumah mengurangi kritik bahwa proyek hanya mengeksploitasi negara berkembang.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "politik-geopolitik",
    levelId: "strategi",
    order: 5,
    title: "Politik & Geopolitik Karbon",
    summary: "Diplomasi iklim, kepentingan nasional, dan pergeseran geopolitik energi.",
    durationMin: 13,
    tags: ["politik", "geopolitik", "diplomasi iklim"],
    blocks: [
      {
        type: "paragraph",
        html: "Karbon bukan hanya isu lingkungan dan ekonomi, tetapi juga <strong>politik</strong>. Negosiasi iklim global adalah arena tarik menarik kepentingan, dan transisi energi menggeser peta kekuatan dunia.",
      },
      {
        type: "stats",
        items: [
          { value: "COP", label: "Konferensi iklim PBB", sub: "arena negosiasi tahunan", color: "#10b981" },
          { value: "Energi", label: "Geopolitik bergeser", sub: "dari fosil ke mineral kritis", color: "#0ea5e9" },
          { value: "NDC", label: "Komitmen nasional", sub: "cermin kepentingan negara", color: "#8b5cf6" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Pergeseran Sumber Daya Strategis",
        unit: "indeks kepentingan strategis (ilustrasi)",
        source: "ilustrasi tren geopolitik",
        note: "Transisi energi menaikkan nilai mineral seperti nikel, litium, dan tembaga, peluang besar bagi Indonesia.",
        data: [
          { label: "Minyak & gas", value: 70 },
          { label: "Batu bara", value: 45 },
          { label: "Nikel", value: 88 },
          { label: "Litium", value: 90 },
          { label: "Tembaga", value: 82 },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Diplomasi karbon",
        html: "Lewat Pasal 6 dan kerja sama bilateral, karbon menjadi alat diplomasi. Negara berhutan seperti Indonesia dan Brasil punya posisi tawar kuat, sementara negara maju butuh mitra untuk memenuhi targetnya.",
      },
      {
        type: "case",
        title: "Studi Kasus: Nikel dan transisi kendaraan listrik",
        html: "Indonesia memiliki cadangan nikel terbesar dunia, bahan utama baterai kendaraan listrik. Transisi energi global menaikkan nilai strategis Indonesia. Namun ada dilema: penambangan nikel juga menghasilkan emisi dan dampak lingkungan. Politik karbon menuntut Indonesia menyeimbangkan peluang ekonomi dari mineral transisi dengan komitmen iklimnya sendiri.",
      },
      {
        type: "classifyExercise",
        prompt: "Faktor ini termasuk dimensi apa dari politik karbon?",
        buckets: ["Diplomasi iklim", "Geopolitik energi", "Kepentingan nasional"],
        items: [
          { text: "Negosiasi target di konferensi COP", bucket: "Diplomasi iklim" },
          { text: "Naiknya nilai nikel dan litium untuk baterai", bucket: "Geopolitik energi" },
          { text: "Indonesia menjaga NDC sambil mengejar pertumbuhan", bucket: "Kepentingan nasional" },
          { text: "Kerja sama bilateral menjual ITMO", bucket: "Diplomasi iklim" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah politik iklim dengan artinya.",
        pairs: [
          { left: "COP", right: "Konferensi iklim tahunan PBB" },
          { left: "Diplomasi karbon", right: "Memakai karbon sebagai alat kerja sama antarnegara" },
          { left: "Mineral kritis", right: "Bahan seperti nikel dan litium untuk transisi energi" },
          { left: "Posisi tawar", right: "Kekuatan negosiasi negara berhutan luas" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Indonesia menjual 5.000.000 ITMO ke negara maju seharga USD 12 per ITMO lewat kerja sama Pasal 6.2. Berapa total nilai transaksinya?",
        answer: 60000000,
        tolerance: 0,
        prefix: "USD ",
        solution: "Nilai = 5.000.000 x USD 12 = <strong>USD 60.000.000</strong>. Pendapatan ini dapat membiayai aksi iklim domestik, tetapi capaiannya harus dipotong dari neraca NDC Indonesia (corresponding adjustment).",
        hint: "Kalikan jumlah ITMO dengan harga per unit.",
      },
      {
        type: "case",
        title: "Studi Kasus: Diplomasi mineral kritis dan rantai pasok baterai",
        html: "Indonesia menguasai sekitar 22% cadangan nikel dunia. Saat permintaan baterai EV melonjak, sebuah negara maju menawarkan kemitraan: investasi smelter dan transfer teknologi, dengan syarat akses jangka panjang ke nikel olahan. Indonesia menimbang tiga hal: nilai ekonomi (hilirisasi menaikkan nilai ekspor dari USD 1 miliar bijih mentah menjadi belasan miliar produk olahan), jejak iklim (smelter berbasis batu bara menaikkan emisi Scope 1 dan 2), serta posisi geopolitik (menghindari ketergantungan pada satu mitra). Keputusan akhirnya: menerima investasi tetapi mensyaratkan pasokan listrik terbarukan, sehingga peluang ekonomi dan komitmen iklim NDC dapat berjalan seiring.",
      },
      {
        type: "takeaways",
        items: [
          "Karbon adalah isu politik dan geopolitik, bukan hanya lingkungan.",
          "Negosiasi iklim (COP) adalah arena tarik menarik kepentingan.",
          "Transisi energi menggeser nilai dari fosil ke mineral kritis.",
          "Indonesia punya posisi tawar kuat lewat hutan dan mineral transisi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "COP dalam konteks iklim adalah?",
            options: ["Jenis kredit", "Konferensi iklim tahunan PBB", "Pajak karbon", "Bursa karbon"],
            answer: 1,
            explain: "COP (Conference of the Parties) adalah konferensi iklim PBB tempat negara bernegosiasi.",
          },
          {
            q: "Transisi energi menggeser nilai strategis ke?",
            options: ["Batu bara", "Mineral kritis seperti nikel dan litium", "Emas saja", "Tidak ada perubahan"],
            answer: 1,
            explain: "Baterai dan teknologi bersih meningkatkan permintaan mineral kritis.",
          },
          {
            q: "Mengapa Indonesia punya posisi tawar kuat?",
            options: [
              "Karena tidak punya hutan",
              "Karena memiliki hutan luas dan cadangan mineral transisi besar",
              "Karena emisinya nol",
              "Karena tidak ikut Paris",
            ],
            answer: 1,
            explain: "Hutan luas (untuk kredit) dan mineral seperti nikel memberi Indonesia daya tawar besar.",
          },
          {
            q: "Diplomasi karbon memanfaatkan mekanisme seperti?",
            options: ["Pasal 6 dan kerja sama bilateral", "Larangan dagang", "Embargo", "Tidak ada"],
            answer: 0,
            explain: "Pasal 6 Paris Agreement dan kerja sama bilateral menjadikan karbon alat diplomasi.",
          },
          {
            q: "Dilema nikel bagi Indonesia adalah?",
            options: [
              "Tidak ada permintaan",
              "Peluang ekonomi besar tetapi penambangannya juga menimbulkan emisi dan dampak lingkungan",
              "Harganya turun terus",
              "Dilarang diekspor",
            ],
            answer: 1,
            explain: "Nikel bernilai strategis untuk transisi, tetapi penambangannya harus diseimbangkan dengan komitmen iklim.",
          },
          {
            q: "Apa yang dimaksud ITMO dalam Pasal 6.2 Paris Agreement?",
            options: [
              "Pajak karbon domestik",
              "Internationally Transferred Mitigation Outcomes: hasil mitigasi yang ditransfer antarnegara",
              "Jenis bursa saham",
              "Nama konferensi iklim",
            ],
            answer: 1,
            explain: "ITMO adalah unit hasil mitigasi yang diperdagangkan antarnegara di bawah Pasal 6.2 untuk memenuhi NDC.",
          },
          {
            q: "Risiko geopolitik dari konsentrasi mineral kritis adalah?",
            options: [
              "Tidak ada risiko",
              "Ketergantungan rantai pasok pada sedikit negara dapat dipakai sebagai alat tekanan",
              "Harga selalu stabil",
              "Mineral menjadi tidak bernilai",
            ],
            answer: 1,
            explain: "Konsentrasi cadangan dan pemrosesan di sedikit negara menimbulkan risiko rantai pasok dan leverage geopolitik.",
          },
          {
            q: "Untuk menghindari double counting di Pasal 6, negara penjual harus melakukan?",
            options: [
              "Mengabaikan pencatatan",
              "Corresponding adjustment: mengurangi capaian dari neraca NDC-nya sendiri",
              "Menjual ulang kredit yang sama",
              "Menaikkan emisi",
            ],
            answer: 1,
            explain: "Corresponding adjustment memastikan satu pengurangan tidak diklaim dua kali oleh penjual dan pembeli sekaligus.",
          },
        ],
      },
    ],
  },
];
