import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "mrv",
    levelId: "teknologi",
    order: 1,
    title: "MRV: Measurement, Reporting, Verification",
    summary: "Tulang punggung kepercayaan pasar karbon. Tanpa MRV, kredit tidak kredibel. Dengan video MRV.",
    durationMin: 15,
    tags: ["MRV", "teknologi", "integritas"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>MRV (Measurement, Reporting, Verification)</strong> adalah proses memastikan bahwa pengurangan emisi yang diklaim benar-benar terjadi. Inilah pembeda antara kredit yang kredibel dan janji kosong.",
      },
      {
        type: "video",
        comp: "MRV",
        title: "Video: Tiga Tahap MRV",
        caption: "Animasi alur Measurement, Reporting, Verification.",
      },
      {
        type: "table",
        caption: "Tiga tahap MRV",
        headers: ["Tahap", "Kegiatan", "Output"],
        rows: [
          ["Measurement", "Mengukur emisi/serapan dengan data & metode baku", "Data emisi terukur"],
          ["Reporting", "Menyusun laporan terstruktur dan transparan", "Laporan yang dapat ditelusuri"],
          ["Verification", "Audit oleh pihak ketiga independen", "Pernyataan keyakinan (assurance)"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Akurasi vs Biaya Metode Pengukuran",
        unit: "skor relatif (ilustrasi)",
        source: "ilustrasi trade-off",
        note: "Metode lebih canggih (satelit, sensor) umumnya lebih akurat namun lebih mahal. Pilihan metode menyeimbangkan akurasi dan biaya.",
        data: [
          { label: "Estimasi default", value: 40 },
          { label: "Survei lapangan", value: 70 },
          { label: "Sensor IoT", value: 85 },
          { label: "Satelit + AI", value: 90 },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Mengapa verifikasi pihak ketiga?",
        html: "Jika pengembang menilai proyeknya sendiri, ada konflik kepentingan. Verifikator <strong>independen</strong> memberi keyakinan kepada pembeli bahwa kredit itu nyata, sehingga harga dan kepercayaan terjaga.",
      },
      {
        type: "case",
        title: "Studi Kasus: MRV lemah memicu over-crediting",
        html: "Beberapa proyek karbon hutan terbukti menerbitkan kredit jauh lebih banyak dari pengurangan nyata karena pengukuran dan baseline-nya lemah. Ketika investigasi independen menggunakan citra satelit, banyak kredit ternyata 'phantom'. Akibatnya harga anjlok dan reputasi seluruh sektor terpukul. MRV yang kuat sebenarnya melindungi nilai pasar.",
      },
      {
        type: "classifyExercise",
        prompt: "Kegiatan ini termasuk tahap MRV yang mana?",
        buckets: ["Measurement", "Reporting", "Verification"],
        items: [
          { text: "Memasang sensor untuk mengukur emisi metana", bucket: "Measurement" },
          { text: "Menyusun laporan tahunan pengurangan emisi", bucket: "Reporting" },
          { text: "Auditor independen memeriksa data proyek", bucket: "Verification" },
          { text: "Menggunakan citra satelit menghitung tutupan hutan", bucket: "Measurement" },
          { text: "Menerbitkan pernyataan assurance", bucket: "Verification" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah proyek mengklaim 100.000 tCO2e, tetapi verifikasi independen menemukan hanya 70.000 yang valid. Berapa persen kredit yang ternyata 'phantom'?",
        answer: 30,
        tolerance: 0,
        suffix: "%",
        solution: "Phantom = (100.000 - 70.000) / 100.000 x 100% = 30.000 / 100.000 = <strong>30%</strong>.",
        hint: "Bagi selisih klaim dan yang valid dengan klaim, lalu kali 100%.",
      },
      {
        type: "case",
        title: "Studi Kasus: Biaya MRV vs nilai integritas",
        html: "Proyek mangrove di pesisir menganggarkan Rp1,2 miliar per tahun untuk MRV (survei lapangan, sensor, audit independen). Proyek menerbitkan 60.000 kredit setahun dengan harga Rp150.000 per kredit, total pendapatan Rp9 miliar. Biaya MRV hanya sekitar 13% dari pendapatan, namun tanpa MRV ini kredit bisa kehilangan label berkualitas dan harganya jatuh ke Rp40.000. Artinya investasi MRV Rp1,2 miliar melindungi selisih nilai sekitar Rp6,6 miliar (60.000 x (Rp150.000 - Rp40.000)). MRV bukan beban, melainkan asuransi nilai.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tahap MRV dengan outputnya.",
        pairs: [
          { left: "Measurement", right: "Data emisi atau serapan terukur" },
          { left: "Reporting", right: "Laporan terstruktur yang dapat ditelusuri" },
          { left: "Verification", right: "Pernyataan keyakinan (assurance) independen" },
          { left: "MRV lemah", right: "Risiko over-crediting dan kredit phantom" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya MRV proyek Rp1,2 miliar per tahun, pendapatan kredit Rp9 miliar. Berapa persen biaya MRV terhadap pendapatan? Bulatkan satu angka di belakang koma.",
        answer: 13.3,
        tolerance: 0.3,
        suffix: "%",
        solution: "Persentase = Rp1,2 miliar / Rp9 miliar x 100% = <strong>13,3%</strong>. Porsi yang relatif kecil untuk menjaga integritas kredit.",
        hint: "Bagi biaya MRV dengan pendapatan lalu kali 100%.",
      },
      {
        type: "takeaways",
        items: [
          "MRV memastikan pengurangan yang diklaim benar-benar terjadi.",
          "Tiga tahap: Measurement, Reporting, Verification.",
          "Verifikasi independen menghindari konflik kepentingan.",
          "MRV lemah memicu over-crediting dan merusak nilai pasar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "MRV adalah singkatan dari?",
            options: [
              "Market, Risk, Value",
              "Measurement, Reporting, Verification",
              "Monitoring, Review, Validation",
              "Measure, Report, Value",
            ],
            answer: 1,
            explain: "MRV adalah Measurement, Reporting, Verification.",
          },
          {
            q: "Mengapa verifikasi dilakukan pihak ketiga independen?",
            options: [
              "Agar lebih murah",
              "Untuk menghindari konflik kepentingan dan menjaga kepercayaan",
              "Karena wajib pajak",
              "Agar lebih cepat",
            ],
            answer: 1,
            explain: "Verifikator independen memberi keyakinan objektif bahwa kredit nyata.",
          },
          {
            q: "Dampak MRV yang lemah adalah?",
            options: ["Harga naik", "Over-crediting dan kredit phantom", "Pasar lebih kuat", "Tidak ada dampak"],
            answer: 1,
            explain: "MRV lemah memungkinkan kredit terbit melebihi pengurangan nyata (over-crediting).",
          },
          {
            q: "Metode pengukuran yang umumnya paling akurat namun mahal?",
            options: ["Estimasi default", "Satelit dan AI", "Tebakan", "Survei singkat"],
            answer: 1,
            explain: "Satelit dan AI memberi akurasi tinggi namun biayanya lebih besar.",
          },
          {
            q: "Output utama tahap Verification adalah?",
            options: ["Data mentah", "Laporan kasar", "Pernyataan keyakinan (assurance)", "Kontrak jual beli"],
            answer: 2,
            explain: "Verifikasi menghasilkan pernyataan keyakinan independen atas klaim pengurangan.",
          },
          {
            q: "Bagaimana MRV yang kuat mencegah over-crediting?",
            options: [
              "Dengan menaikkan harga kredit",
              "Dengan memastikan kredit terbit hanya sebanyak pengurangan yang benar-benar terukur dan terverifikasi",
              "Dengan menghapus baseline",
              "Dengan mempercepat penjualan",
            ],
            answer: 1,
            explain: "MRV mengikat penerbitan kredit pada pengurangan yang nyata dan terverifikasi, sehingga jumlah kredit tidak melebihi pengurangan aktual.",
          },
          {
            q: "Baseline yang dilebih-lebihkan akan menyebabkan?",
            options: [
              "Kredit lebih sedikit dari seharusnya",
              "Kredit terbit berlebih (over-crediting) karena pengurangan terlihat lebih besar",
              "Tidak ada efek",
              "Verifikasi lebih murah",
            ],
            answer: 1,
            explain: "Baseline yang terlalu tinggi membuat selisih pengurangan tampak besar, sehingga kredit yang terbit melebihi pengurangan nyata.",
          },
          {
            q: "Mana urutan yang benar dalam MRV?",
            options: [
              "Verification, Measurement, Reporting",
              "Reporting, Verification, Measurement",
              "Measurement, Reporting, Verification",
              "Measurement, Verification, Reporting",
            ],
            answer: 2,
            explain: "Pertama mengukur, lalu menyusun laporan, baru kemudian diverifikasi pihak ketiga.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "teknologi-monitoring",
    levelId: "teknologi",
    order: 2,
    title: "Blockchain, IoT & AI untuk Karbon",
    summary: "Teknologi yang membuat MRV lebih murah, akurat, dan tahan kecurangan.",
    durationMin: 13,
    tags: ["teknologi", "blockchain", "AI"],
    blocks: [
      {
        type: "paragraph",
        html: "Teknologi digital mengubah cara karbon diukur dan dicatat. <strong>IoT</strong> memberi data real-time, <strong>satelit dan AI</strong> memantau hutan dari angkasa, dan <strong>blockchain</strong> mencatat kepemilikan kredit secara transparan dan sulit dipalsukan.",
      },
      {
        type: "table",
        caption: "Peran teknologi dalam pasar karbon",
        headers: ["Teknologi", "Fungsi utama"],
        rows: [
          ["IoT (sensor)", "Mengukur emisi/parameter secara real-time di lapangan"],
          ["Satelit", "Memantau tutupan hutan dan deforestasi dari angkasa"],
          ["AI / machine learning", "Menganalisis citra, mendeteksi anomali dan kebakaran"],
          ["Blockchain", "Registry transparan, anti double counting dan pemalsuan"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Manfaat Teknologi terhadap Biaya MRV",
        unit: "indeks biaya MRV (ilustrasi, makin rendah makin baik)",
        source: "ilustrasi tren penurunan biaya",
        note: "Otomasi pengukuran menurunkan biaya MRV sehingga proyek kecil pun jadi layak.",
        data: [
          { label: "Manual", value: 100 },
          { label: "+ IoT", value: 70 },
          { label: "+ Satelit/AI", value: 45 },
          { label: "+ Blockchain registry", value: 35 },
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Mengapa blockchain cocok untuk kredit",
        html: "Masalah terbesar kredit adalah <strong>double counting</strong> (dipakai dua kali). Blockchain memberi catatan tunggal yang transparan: setiap kredit punya jejak digital dari terbit sampai retire, sehingga sulit diklaim ganda.",
      },
      {
        type: "case",
        title: "Studi Kasus: Satelit membongkar klaim hutan",
        html: "Sebuah proyek mengklaim melindungi area hutan tertentu. Analisis citra satelit selama beberapa tahun menunjukkan sebagian area sebenarnya tetap gundul atau tidak pernah terancam. Tanpa teknologi pemantauan, klaim ini sulit diuji. Dengan satelit dan AI, verifikasi jadi objektif dan murah, memperkuat integritas pasar.",
      },
      {
        type: "classifyExercise",
        prompt: "Teknologi mana yang paling tepat untuk tugas ini?",
        buckets: ["IoT", "Satelit/AI", "Blockchain"],
        items: [
          { text: "Memantau deforestasi area luas dari angkasa", bucket: "Satelit/AI" },
          { text: "Mencatat kepemilikan kredit anti pemalsuan", bucket: "Blockchain" },
          { text: "Mengukur emisi cerobong pabrik real-time", bucket: "IoT" },
          { text: "Mendeteksi titik kebakaran otomatis dari citra", bucket: "Satelit/AI" },
          { text: "Mencegah satu kredit dipakai dua kali", bucket: "Blockchain" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan teknologi dengan manfaat utamanya.",
        pairs: [
          { left: "IoT", right: "Data emisi real-time di lapangan" },
          { left: "Satelit", right: "Pemantauan hutan dari angkasa" },
          { left: "AI", right: "Analisis citra dan deteksi anomali" },
          { left: "Blockchain", right: "Registry transparan anti double counting" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: IoT menurunkan biaya MRV proyek metana",
        html: "Sebuah peternakan memasang 25 sensor IoT untuk memantau tangkapan metana dari biodigester, dengan investasi awal Rp500 juta dan biaya operasi Rp80 juta per tahun. Sebelumnya, MRV manual lewat survei berkala menelan Rp250 juta per tahun dan hanya memberi data bulanan. Dengan IoT, data tersedia per jam, akurasi naik, dan klaim kredit lebih kredibel. Dalam 5 tahun total biaya IoT sekitar Rp900 juta versus Rp1,25 miliar untuk manual, dan kualitas data jauh lebih tinggi. Hasil sensor lalu dicatat ke registry blockchain agar tidak bisa dimanipulasi.",
      },
      {
        type: "calcExercise",
        prompt: "MRV manual berbiaya Rp250 juta per tahun. Dengan IoT, biaya operasi tahunan turun jadi Rp80 juta. Berapa persen penghematan biaya operasi tahunan? Bulatkan ke bilangan bulat.",
        answer: 68,
        tolerance: 0,
        suffix: "%",
        solution: "Penghematan = (250 - 80) / 250 x 100% = 170 / 250 = <strong>68%</strong>. Otomasi IoT memangkas biaya operasi MRV secara signifikan.",
        hint: "Selisih biaya dibagi biaya manual, lalu kali 100%.",
      },
      {
        type: "takeaways",
        items: [
          "IoT memberi data emisi real-time di lapangan.",
          "Satelit dan AI memantau hutan dan mendeteksi anomali secara objektif.",
          "Blockchain menyediakan registry transparan yang menghindari double counting.",
          "Teknologi menurunkan biaya MRV sehingga proyek kecil pun layak.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Masalah double counting paling cocok diatasi dengan?",
            options: ["IoT", "Blockchain registry transparan", "Kertas", "Telepon"],
            answer: 1,
            explain: "Blockchain memberi catatan tunggal dan transparan sehingga kredit sulit diklaim dua kali.",
          },
          {
            q: "Untuk memantau deforestasi area luas, teknologi terbaik adalah?",
            options: ["Sensor di satu titik", "Satelit dan AI", "Wawancara", "Buku catatan"],
            answer: 1,
            explain: "Satelit memberi cakupan luas dan AI menganalisis perubahan tutupan hutan.",
          },
          {
            q: "IoT berperan dalam MRV untuk?",
            options: ["Menjual kredit", "Mengukur parameter emisi real-time", "Membuat kontrak", "Membayar pajak"],
            answer: 1,
            explain: "Sensor IoT memberi data pengukuran emisi secara langsung dan terus-menerus.",
          },
          {
            q: "Dampak teknologi terhadap biaya MRV umumnya?",
            options: ["Menaikkan biaya", "Menurunkan biaya lewat otomasi", "Tidak berpengaruh", "Menghapus MRV"],
            answer: 1,
            explain: "Otomasi pengukuran dan verifikasi menurunkan biaya MRV.",
          },
          {
            q: "AI dalam konteks ini paling berguna untuk?",
            options: [
              "Menggantikan regulasi",
              "Menganalisis citra dan mendeteksi anomali seperti kebakaran",
              "Menentukan harga pasar saja",
              "Membuat kopi",
            ],
            answer: 1,
            explain: "AI menganalisis data dan citra dalam skala besar untuk mendeteksi pola dan anomali.",
          },
          {
            q: "Sifat blockchain yang membuatnya sulit dipalsukan adalah?",
            options: [
              "Data disimpan di satu komputer pusat",
              "Catatan tidak dapat diubah (immutable) dan terdistribusi serta transparan",
              "Hanya admin yang bisa melihat",
              "Tidak ada jejak transaksi",
            ],
            answer: 1,
            explain: "Catatan blockchain bersifat immutable dan terdistribusi, sehingga riwayat kredit sulit diubah diam-diam.",
          },
          {
            q: "Mengapa kombinasi IoT, satelit/AI, dan blockchain saling melengkapi?",
            options: [
              "Semuanya melakukan hal yang sama",
              "IoT dan satelit/AI menghasilkan data MRV yang andal, blockchain mencatat dan mengamankan hasilnya",
              "Hanya blockchain yang penting",
              "Mereka saling bersaing dan tidak boleh digabung",
            ],
            answer: 1,
            explain: "Sensor dan AI memperkuat tahap Measurement, blockchain mengamankan pencatatan dan retirement.",
          },
          {
            q: "Garbage in, garbage out dalam konteks blockchain karbon berarti?",
            options: [
              "Blockchain otomatis menjamin kebenaran data",
              "Blockchain hanya menjaga integritas pencatatan; jika data input salah, catatannya tetap salah",
              "Blockchain menghapus data buruk",
              "Blockchain mengukur emisi sendiri",
            ],
            answer: 1,
            explain: "Blockchain menjamin data tidak diubah setelah masuk, tetapi tidak menjamin kebenaran data awal, sehingga MRV tetap krusial.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "tata-kelola-transparansi",
    levelId: "teknologi",
    order: 3,
    title: "Tata Kelola: Transparansi & Anti-Fraud",
    summary: "Registry, akuntabilitas, dan prinsip integritas yang menjaga pasar karbon tetap dipercaya.",
    durationMin: 13,
    tags: ["governance", "transparansi", "integritas"],
    blocks: [
      {
        type: "paragraph",
        html: "Pasar karbon hanya berfungsi jika dipercaya. <strong>Tata kelola (governance)</strong> yang baik berarti transparansi, akuntabilitas, registry yang andal, dan mekanisme mencegah kecurangan seperti double counting dan kredit palsu.",
      },
      {
        type: "table",
        caption: "Tata kelola baik vs buruk",
        headers: ["Aspek", "Tata kelola baik", "Tata kelola buruk"],
        rows: [
          ["Registry", "Publik, dapat ditelusuri, retirement tercatat", "Tertutup, mudah dimanipulasi"],
          ["Verifikasi", "Independen dan berkala", "Dilakukan sendiri tanpa audit"],
          ["Baseline", "Konservatif dan transparan", "Dilebih-lebihkan diam-diam"],
          ["Pengungkapan", "Metodologi dan data terbuka", "Rahasia, sulit diperiksa"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Core Carbon Principles (ICVCM)",
        html: "Untuk membersihkan pasar sukarela, <strong>ICVCM</strong> menetapkan <strong>Core Carbon Principles</strong>: kredit berkualitas harus additional, permanen, diukur konservatif, diverifikasi independen, dan didukung tata kelola yang kuat.",
      },
      {
        type: "stats",
        items: [
          { value: "1=1", label: "Satu kredit satu retirement", sub: "anti double counting", color: "#10b981" },
          { value: "Open", label: "Registry transparan", sub: "dapat ditelusuri publik", color: "#0ea5e9" },
          { value: "Audit", label: "Verifikasi independen", sub: "berkala dan objektif", color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Double counting antarnegara",
        html: "Sebuah pengurangan emisi di negara berkembang dijual ke perusahaan asing sebagai offset, tetapi negara tuan rumah juga menghitungnya untuk NDC-nya. Satu ton diklaim dua pihak. Tanpa corresponding adjustment dan registry yang terhubung, kecurangan semacam ini menggerus kepercayaan. Tata kelola yang menautkan registry dan menerapkan penyesuaian adalah obatnya.",
      },
      {
        type: "classifyExercise",
        prompt: "Praktik ini memperkuat atau merusak tata kelola pasar?",
        buckets: ["Memperkuat", "Merusak"],
        items: [
          { text: "Registry publik yang mencatat retirement", bucket: "Memperkuat" },
          { text: "Verifikasi independen berkala", bucket: "Memperkuat" },
          { text: "Menjual kredit yang sama ke dua pembeli", bucket: "Merusak" },
          { text: "Menyembunyikan metodologi baseline", bucket: "Merusak" },
          { text: "Mengungkap data dan metode secara terbuka", bucket: "Memperkuat" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan prinsip tata kelola dengan tujuannya.",
        pairs: [
          { left: "Transparansi", right: "Data dan metode dapat diperiksa publik" },
          { left: "Akuntabilitas", right: "Ada pihak yang bertanggung jawab dan dapat ditagih" },
          { left: "Registry retirement", right: "Mencegah kredit dipakai dua kali" },
          { left: "Core Carbon Principles", right: "Standar mutu kredit pasar sukarela" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Registry ganda dan kredit yang dipakai dua kali",
        html: "Sebuah proyek terdaftar di dua registry berbeda yang tidak saling terhubung. Pengembang menerbitkan 80.000 kredit di registry A dan diam-diam mendaftarkan proyek yang sama di registry B untuk 80.000 kredit lagi. Total 160.000 kredit beredar untuk pengurangan yang hanya 80.000 ton: 80.000 kredit adalah kredit ganda yang tidak punya dasar. Saat auditor membandingkan koordinat geografis dan metodologi, duplikasi terbongkar dan 80.000 kredit (50% dari total) harus dibatalkan. Registry yang saling terhubung dan unik secara geospasial mencegah hal ini.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah proyek mendaftar ganda: 80.000 kredit di registry A dan 80.000 kredit lagi di registry B untuk pengurangan yang sama. Berapa persen dari total kredit beredar yang merupakan kredit ganda tidak sah?",
        answer: 50,
        tolerance: 0,
        suffix: "%",
        solution: "Total beredar = 160.000, yang sah hanya 80.000. Kredit ganda = 80.000 / 160.000 x 100% = <strong>50%</strong>. Inilah dampak double counting tanpa registry terhubung.",
        hint: "Kredit ganda dibagi total kredit beredar, lalu kali 100%.",
      },
      {
        type: "takeaways",
        items: [
          "Pasar karbon hanya berjalan bila dipercaya.",
          "Registry transparan dan verifikasi independen adalah pilar utama.",
          "Double counting dicegah lewat retirement dan corresponding adjustment.",
          "ICVCM Core Carbon Principles menetapkan standar kredit berkualitas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan utama tata kelola pasar karbon adalah?",
            options: ["Menaikkan harga", "Menjaga kepercayaan lewat transparansi dan akuntabilitas", "Menambah birokrasi", "Mengurangi pembeli"],
            answer: 1,
            explain: "Tata kelola baik menjaga integritas dan kepercayaan pasar.",
          },
          {
            q: "Apa fungsi registry yang transparan?",
            options: [
              "Menyembunyikan transaksi",
              "Mencatat penerbitan, kepemilikan, dan retirement secara dapat ditelusuri",
              "Menaikkan pajak",
              "Mengganti verifikasi",
            ],
            answer: 1,
            explain: "Registry transparan memungkinkan publik menelusuri status kredit dan mencegah klaim ganda.",
          },
          {
            q: "ICVCM Core Carbon Principles bertujuan?",
            options: [
              "Melarang pasar",
              "Menetapkan standar kredit berkualitas tinggi",
              "Menaikkan harga listrik",
              "Menghapus MRV",
            ],
            answer: 1,
            explain: "Core Carbon Principles adalah standar mutu untuk membersihkan pasar sukarela.",
          },
          {
            q: "Double counting paling tepat dicegah dengan?",
            options: [
              "Registry terhubung dan corresponding adjustment",
              "Menaikkan harga",
              "Menghapus laporan",
              "Menambah pembeli",
            ],
            answer: 0,
            explain: "Registry yang menautkan data dan penyesuaian klaim mencegah satu ton dihitung dua kali.",
          },
          {
            q: "Manakah tanda tata kelola buruk?",
            options: [
              "Verifikasi independen",
              "Baseline dilebih-lebihkan secara diam-diam",
              "Registry publik",
              "Pengungkapan metodologi",
            ],
            answer: 1,
            explain: "Baseline yang dilebihkan tanpa transparansi adalah ciri tata kelola yang buruk.",
          },
          {
            q: "Apa yang dimaksud corresponding adjustment dalam Pasal 6 Paris Agreement?",
            options: [
              "Menaikkan harga kredit secara berkala",
              "Negara penjual mengurangi klaim NDC-nya saat kredit dijual ke pihak lain agar tidak dihitung dua kali",
              "Menggandakan kredit untuk dua pembeli",
              "Menghapus registry",
            ],
            answer: 1,
            explain: "Corresponding adjustment memastikan satu pengurangan tidak diklaim oleh penjual dan pembeli sekaligus.",
          },
          {
            q: "Pemisahan tugas (segregation of duties) sebagai kontrol anti-fraud berarti?",
            options: [
              "Satu orang mengukur, melaporkan, dan memverifikasi sekaligus",
              "Pihak yang mengukur, melaporkan, dan yang memverifikasi adalah entitas berbeda dan independen",
              "Tidak ada audit sama sekali",
              "Semua data dirahasiakan",
            ],
            answer: 1,
            explain: "Memisahkan peran mengurangi peluang manipulasi dan konflik kepentingan.",
          },
          {
            q: "Manakah praktik tata kelola yang memperkuat akuntabilitas?",
            options: [
              "Tidak ada penanggung jawab yang jelas",
              "Jejak audit (audit trail) lengkap dan pihak yang dapat dimintai pertanggungjawaban",
              "Metodologi dirahasiakan",
              "Registry tertutup",
            ],
            answer: 1,
            explain: "Audit trail dan penanggung jawab yang jelas memungkinkan kesalahan ditelusuri dan ditindak.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "manajemen-risiko",
    levelId: "teknologi",
    order: 4,
    title: "Manajemen Risiko Carbon Trading",
    summary: "Mengenali dan memitigasi risiko regulasi, harga, reputasi, dan likuiditas.",
    durationMin: 13,
    tags: ["risiko", "mitigasi", "manajemen"],
    blocks: [
      {
        type: "paragraph",
        html: "Carbon trading menjanjikan peluang, tetapi juga membawa risiko khas. Pelaku yang sukses bukan yang menghindari semua risiko, melainkan yang <strong>mengenali dan mengelolanya</strong>.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Peta Risiko Carbon Trading",
        unit: "skor paparan (ilustrasi, dampak x kemungkinan)",
        source: "ilustrasi penilaian risiko",
        note: "Risiko regulasi dan harga umumnya paling menonjol di pasar yang masih muda dan berkembang.",
        data: [
          { label: "Regulasi", value: 85, color: "#ef4444" },
          { label: "Harga/volatilitas", value: 80, color: "#f59e0b" },
          { label: "Reputasi", value: 70, color: "#f59e0b" },
          { label: "Likuiditas", value: 55, color: "#0ea5e9" },
          { label: "Kontraparti", value: 50, color: "#0ea5e9" },
        ],
      },
      {
        type: "table",
        caption: "Jenis risiko dan mitigasinya",
        headers: ["Risiko", "Contoh", "Mitigasi"],
        rows: [
          ["Regulasi", "Aturan berubah, kredit jadi tidak diakui", "Pantau kebijakan, klausul kontrak fleksibel"],
          ["Harga", "Harga karbon anjlok", "Hedging lewat futures, diversifikasi"],
          ["Reputasi", "Tuduhan greenwashing", "Beli kredit berkualitas, transparan"],
          ["Likuiditas", "Sulit menjual kredit", "Pilih kredit dengan permintaan kuat"],
          ["Kontraparti", "Mitra gagal menyerahkan kredit", "Due diligence, jaminan, buffer"],
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko reputasi paling halus",
        html: "Membeli kredit murah berkualitas rendah bisa berbalik menyerang: jika kredit itu kelak terbukti palsu, perusahaan dituduh greenwashing dan kepercayaan publik runtuh. Kualitas lebih penting dari harga.",
      },
      {
        type: "case",
        title: "Studi Kasus: Perusahaan menarik klaim net-zero",
        html: "Sebuah perusahaan besar pernah harus menarik klaim 'carbon neutral' setelah kredit hutan yang dibelinya dikritik tidak kredibel. Harga sahamnya sempat tertekan dan kepercayaan konsumen turun. Kerugian reputasi ini jauh lebih besar dari uang yang dihemat saat membeli kredit murah. Manajemen risiko reputasi seharusnya menempatkan mutu kredit di atas harga.",
      },
      {
        type: "classifyExercise",
        prompt: "Mitigasi ini paling tepat untuk risiko apa?",
        buckets: ["Risiko harga", "Risiko reputasi", "Risiko kontraparti"],
        items: [
          { text: "Mengunci harga dengan kontrak futures", bucket: "Risiko harga" },
          { text: "Membeli hanya kredit berkualitas tinggi dan transparan", bucket: "Risiko reputasi" },
          { text: "Due diligence dan jaminan penyerahan dari mitra", bucket: "Risiko kontraparti" },
          { text: "Diversifikasi portofolio kredit", bucket: "Risiko harga" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Perusahaan memegang 40.000 kredit senilai Rp70.000. Jika harga turun 25%, berapa nilai kerugian (belum terealisasi)?",
        answer: 700000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Penurunan harga = 25% x Rp70.000 = Rp17.500/ton. Kerugian = 40.000 x Rp17.500 = <strong>Rp700.000.000</strong>. Inilah risiko volatilitas harga.",
        hint: "Hitung penurunan harga per ton lalu kalikan volume.",
      },
      {
        type: "case",
        title: "Studi Kasus: Buffer pool menyelamatkan proyek dari reversal",
        html: "Sebuah proyek reforestasi menerbitkan 200.000 kredit dan wajib menyisihkan 20% (40.000 kredit) ke buffer pool sebagai cadangan risiko permanence. Tiga tahun kemudian kebakaran melahap 15% area, melepas karbon setara 30.000 kredit. Karena buffer pool tersedia 40.000 kredit, registry membatalkan 30.000 kredit dari buffer untuk menutup reversal tanpa membebani pembeli yang sudah me-retire kreditnya. Sisa buffer 10.000 kredit. Tanpa buffer, kerugian dan tuntutan hukum bisa menimpa pembeli. Ini contoh mitigasi risiko permanence yang dirancang dalam tata kelola proyek.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan jenis risiko dengan instrumen mitigasinya.",
        pairs: [
          { left: "Risiko harga", right: "Hedging futures dan diversifikasi" },
          { left: "Risiko permanence", right: "Buffer pool cadangan kredit" },
          { left: "Risiko kontraparti", right: "Due diligence dan jaminan penyerahan" },
          { left: "Risiko reputasi", right: "Membeli kredit berkualitas tinggi dan transparan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Risiko utama: regulasi, harga, reputasi, likuiditas, kontraparti.",
          "Risiko harga dapat dikelola dengan hedging dan diversifikasi.",
          "Risiko reputasi diatasi dengan memilih kredit berkualitas dan transparan.",
          "Kualitas kredit lebih penting daripada harga termurah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Mitigasi untuk risiko harga karbon adalah?",
            options: ["Mengabaikannya", "Hedging lewat futures dan diversifikasi", "Membeli kredit termurah", "Berhenti melapor"],
            answer: 1,
            explain: "Hedging mengunci harga dan diversifikasi menyebar risiko.",
          },
          {
            q: "Risiko reputasi muncul terutama saat?",
            options: [
              "Membeli kredit berkualitas",
              "Membeli kredit murah berkualitas rendah yang kelak terbukti palsu",
              "Transparan",
              "Mengikuti standar",
            ],
            answer: 1,
            explain: "Kredit murah berkualitas rendah berisiko memicu tuduhan greenwashing.",
          },
          {
            q: "Risiko regulasi berarti?",
            options: [
              "Harga naik",
              "Aturan berubah sehingga kredit bisa jadi tidak diakui",
              "Mitra gagal bayar",
              "Sulit menjual",
            ],
            answer: 1,
            explain: "Perubahan kebijakan dapat mengubah nilai atau pengakuan kredit.",
          },
          {
            q: "Due diligence mitra bertujuan mengelola risiko?",
            options: ["Kontraparti", "Cuaca", "Pajak", "Bahasa"],
            answer: 0,
            explain: "Due diligence menilai kemampuan mitra memenuhi kewajiban, mengelola risiko kontraparti.",
          },
          {
            q: "Pelajaran utama manajemen risiko karbon adalah?",
            options: [
              "Hindari semua risiko",
              "Kenali dan kelola risiko, utamakan kualitas kredit",
              "Beli sebanyak mungkin",
              "Abaikan reputasi",
            ],
            answer: 1,
            explain: "Sukses berarti mengelola risiko secara sadar dan mengutamakan mutu, bukan menghindari semua.",
          },
          {
            q: "Risiko likuiditas dalam carbon trading berarti?",
            options: [
              "Harga karbon naik tajam",
              "Sulit menjual kredit dengan cepat tanpa menekan harga",
              "Mitra gagal menyerahkan kredit",
              "Aturan berubah",
            ],
            answer: 1,
            explain: "Likuiditas rendah membuat kredit sulit dijual cepat pada harga wajar.",
          },
          {
            q: "Mekanisme buffer pool pada proyek karbon hutan berfungsi untuk?",
            options: [
              "Menaikkan harga kredit",
              "Menyisihkan sebagian kredit sebagai cadangan jika terjadi reversal seperti kebakaran",
              "Menghindari pajak",
              "Mempercepat penjualan",
            ],
            answer: 1,
            explain: "Buffer pool adalah cadangan kredit untuk menutup risiko permanence (reversal), bentuk mitigasi risiko.",
          },
          {
            q: "Diversifikasi portofolio kredit membantu mengelola risiko karena?",
            options: [
              "Menghapus seluruh risiko",
              "Menyebar paparan ke berbagai jenis proyek dan wilayah sehingga satu kegagalan tidak fatal",
              "Menjamin harga selalu naik",
              "Menggantikan due diligence",
            ],
            answer: 1,
            explain: "Diversifikasi menyebar risiko sehingga kerugian pada satu proyek tidak menghancurkan seluruh portofolio.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "greenwashing",
    levelId: "teknologi",
    order: 5,
    title: "Greenwashing & Integritas Kredit",
    summary: "Mengenali kredit berkualitas rendah: additionality, permanence, leakage, dan over-crediting. Dengan simulator integritas.",
    durationMin: 15,
    tags: ["greenwashing", "integritas", "additionality"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Greenwashing</strong> adalah klaim ramah lingkungan yang menyesatkan. Dalam karbon, ini sering terjadi ketika perusahaan mengandalkan kredit berkualitas rendah untuk mengklaim net-zero tanpa benar-benar menurunkan emisinya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat penguji integritas kredit",
        html: "<strong>Additionality</strong>: apakah pengurangan tidak akan terjadi tanpa dana karbon? <strong>Permanence</strong>: apakah karbon tetap tersimpan jangka panjang? <strong>Leakage</strong>: apakah emisi hanya berpindah tempat? <strong>Akurasi baseline</strong>: apakah perhitungan tidak dilebih-lebihkan?",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Uji sendiri integritasnya",
        html: "Pada simulator berikut, matikan additionality atau permanence dan perhatikan skor integritas anjlok. Harga boleh sama, tetapi nilai lingkungannya sangat berbeda.",
      },
      {
        type: "widget",
        widget: "SimulatorOffset",
      },
      {
        type: "case",
        title: "Studi Kasus: Net-zero di atas kertas",
        html: "Sebuah perusahaan mengklaim net-zero hanya dengan membeli offset murah, sambil emisinya sendiri terus naik tiap tahun. Ketika diperiksa, sebagian besar kreditnya tidak additional. Publik dan regulator menilai ini greenwashing. Klaim net-zero yang kredibel harus menempatkan pengurangan emisi nyata lebih dulu, dan offset hanya untuk sisa yang sulit dihilangkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Masalah integritas ini termasuk konsep yang mana?",
        buckets: ["Additionality", "Permanence", "Leakage"],
        items: [
          { text: "Proyek tetap berjalan walau tanpa dana karbon", bucket: "Additionality" },
          { text: "Hutan terbakar dan karbonnya lepas kembali", bucket: "Permanence" },
          { text: "Penebangan hanya pindah ke hutan sebelah", bucket: "Leakage" },
          { text: "Kredit terbit untuk pengurangan yang akan terjadi sendiri", bucket: "Additionality" },
          { text: "Karbon tersimpan hanya bertahan 2 tahun", bucket: "Permanence" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah integritas dengan definisinya.",
        pairs: [
          { left: "Additionality", right: "Pengurangan tidak akan terjadi tanpa dana karbon" },
          { left: "Permanence", right: "Karbon tetap tersimpan dalam jangka panjang" },
          { left: "Leakage", right: "Emisi hanya berpindah, bukan berkurang" },
          { left: "Over-crediting", right: "Kredit terbit melebihi pengurangan nyata" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Baseline berlebihan memicu over-crediting 65%",
        html: "Sebuah proyek REDD+ menetapkan baseline deforestasi 5% per tahun dan menerbitkan kredit atas dasar 'menghindari' laju itu. Investigasi independen dengan citra satelit menemukan laju deforestasi historis area sebanding hanya 1,75% per tahun. Artinya baseline dilebihkan hampir 3 kali lipat. Dari 1.000.000 kredit yang terbit, hanya sekitar 350.000 yang mencerminkan pengurangan nyata, sehingga 650.000 kredit (65%) adalah over-crediting. Sebagian pembeli sudah memakai kredit ini untuk klaim net-zero, dan saat skandal terungkap mereka dituduh greenwashing. Baseline konservatif dan MRV berbasis satelit akan mencegahnya.",
      },
      {
        type: "calcExercise",
        prompt: "Proyek menerbitkan 1.000.000 kredit, tetapi verifikasi independen menemukan hanya 350.000 yang mencerminkan pengurangan nyata. Berapa persen kredit yang merupakan over-crediting?",
        answer: 65,
        tolerance: 0,
        suffix: "%",
        solution: "Over-crediting = (1.000.000 - 350.000) / 1.000.000 x 100% = 650.000 / 1.000.000 = <strong>65%</strong>. Akibat baseline yang dilebih-lebihkan.",
        hint: "Selisih kredit terbit dan yang valid dibagi kredit terbit, lalu kali 100%.",
      },
      {
        type: "takeaways",
        items: [
          "Greenwashing adalah klaim hijau yang menyesatkan.",
          "Uji kredit lewat additionality, permanence, leakage, dan akurasi baseline.",
          "Ikuti hierarki mitigasi: kurangi dulu, offset belakangan.",
          "Klaim net-zero kredibel mengutamakan pengurangan emisi nyata.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Greenwashing dalam karbon adalah?",
            options: [
              "Menanam pohon sungguhan",
              "Klaim ramah lingkungan yang menyesatkan, mis. net-zero dari kredit palsu",
              "Mengurangi emisi nyata",
              "Melapor jujur",
            ],
            answer: 1,
            explain: "Greenwashing adalah klaim hijau yang tidak didukung pengurangan nyata.",
          },
          {
            q: "Additionality berarti?",
            options: [
              "Proyek tetap terjadi tanpa dana karbon",
              "Pengurangan tidak akan terjadi tanpa dana karbon",
              "Karbon lepas kembali",
              "Emisi berpindah",
            ],
            answer: 1,
            explain: "Additionality memastikan kredit hanya untuk pengurangan yang benar-benar tambahan.",
          },
          {
            q: "Hutan terbakar setelah kredit terjual adalah masalah?",
            options: ["Additionality", "Permanence", "Likuiditas", "Pajak"],
            answer: 1,
            explain: "Karbon yang lepas kembali menyangkut permanence (ketahanan jangka panjang).",
          },
          {
            q: "Menurut hierarki mitigasi, offset sebaiknya?",
            options: [
              "Jadi langkah pertama",
              "Jadi pilihan terakhir untuk emisi yang sulit dihilangkan",
              "Menggantikan semua pengurangan",
              "Dihindari sepenuhnya",
            ],
            answer: 1,
            explain: "Kurangi emisi nyata dulu; offset hanya untuk sisa yang sulit dihilangkan.",
          },
          {
            q: "Leakage terjadi ketika?",
            options: [
              "Karbon berkurang permanen",
              "Emisi hanya berpindah ke tempat lain",
              "Kredit di-retire",
              "Baseline konservatif",
            ],
            answer: 1,
            explain: "Leakage berarti aktivitas penghasil emisi pindah tempat sehingga total emisi tidak benar-benar turun.",
          },
          {
            q: "Over-crediting paling tepat didefinisikan sebagai?",
            options: [
              "Kredit terbit lebih sedikit dari pengurangan nyata",
              "Kredit terbit melebihi pengurangan emisi yang benar-benar terjadi",
              "Kredit yang sudah di-retire",
              "Kredit dengan harga tinggi",
            ],
            answer: 1,
            explain: "Over-crediting berarti jumlah kredit melampaui pengurangan aktual, sering akibat baseline berlebihan atau MRV lemah.",
          },
          {
            q: "Tuduhan greenwashing pada klaim net-zero biasanya muncul ketika?",
            options: [
              "Perusahaan menurunkan emisi nyata lebih dulu",
              "Perusahaan hanya membeli offset murah sementara emisinya sendiri terus naik",
              "Perusahaan mengikuti hierarki mitigasi",
              "Perusahaan transparan soal data",
            ],
            answer: 1,
            explain: "Mengandalkan offset tanpa menurunkan emisi sendiri adalah pola khas greenwashing.",
          },
          {
            q: "Proyek menerbitkan kredit untuk pengurangan yang akan terjadi sendiri tanpa dana karbon. Konsep yang dilanggar adalah?",
            options: ["Permanence", "Additionality", "Likuiditas", "Leakage"],
            answer: 1,
            explain: "Jika pengurangan terjadi tanpa dana karbon, kredit itu tidak additional.",
          },
        ],
      },
    ],
  },
];
