import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "regulasi-indonesia",
    levelId: "regulasi",
    order: 1,
    title: "Regulasi Carbon Trading di Indonesia",
    summary: "Kerangka hukum Nilai Ekonomi Karbon, peran KLHK dan OJK, serta Bursa Karbon IDX.",
    durationMin: 15,
    tags: ["hukum", "regulasi", "Indonesia"],
    blocks: [
      {
        type: "paragraph",
        html: "Indonesia membangun kerangka perdagangan karbon lewat <strong>Nilai Ekonomi Karbon (NEK)</strong>. Aturan payungnya adalah <strong>Perpres 98/2021</strong>, didukung peraturan KLHK dan OJK. Tujuannya: mendukung target NDC (Nationally Determined Contribution) Indonesia sekaligus membuka peluang ekonomi dari karbon.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tonggak Regulasi Karbon Indonesia",
        unit: "tahun",
        source: "ilustrasi linimasa kebijakan",
        note: "Kerangka berkembang cepat dari komitmen Paris sampai peluncuran bursa karbon.",
        data: [
          { label: "Ratifikasi Paris (UU 16)", value: 2016 },
          { label: "Perpres NEK 98", value: 2021 },
          { label: "Pajak karbon (UU HPP)", value: 2021 },
          { label: "Bursa Karbon IDX", value: 2023 },
        ],
      },
      {
        type: "table",
        caption: "Pemain kunci dalam regulasi karbon Indonesia",
        headers: ["Lembaga", "Peran"],
        rows: [
          ["KLHK", "Mengatur tata laksana NEK, SRN-PPI, sertifikasi pengurangan emisi (SPE-GRK)"],
          ["OJK", "Mengatur dan mengawasi Bursa Karbon"],
          ["Bursa Efek Indonesia (IDX)", "Penyelenggara Bursa Karbon (IDXCarbon)"],
          ["Kementerian Keuangan", "Mengatur pajak karbon dan aspek fiskal"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "SRN-PPI dan SPE-GRK",
        html: "Setiap aksi iklim dicatat di <strong>SRN-PPI</strong> (Sistem Registri Nasional). Pengurangan emisi yang terverifikasi diterbitkan sebagai <strong>SPE-GRK</strong> (Sertifikat Pengurangan Emisi Gas Rumah Kaca), unit yang diperdagangkan di IDXCarbon.",
      },
      {
        type: "case",
        title: "Studi Kasus: PLTU dan perdagangan emisi sektor energi",
        html: "Indonesia memulai perdagangan karbon wajib pada subsektor pembangkit listrik. Tiap PLTU mendapat batas emisi (PTBAE-PU). Pembangkit yang emisinya di atas batas harus membeli SPE atau izin dari pembangkit yang di bawah batas. Inilah penerapan nyata cap-and-trade dalam kerangka regulasi Indonesia.",
      },
      {
        type: "case",
        title: "Studi Kasus: Dua PLTU saling berdagang kuota",
        html: "PLTU Alfa mendapat jatah (PTBAE-PU) 1.000.000 tCO2e tetapi beremisi 1.050.000 tCO2e, jadi defisit 50.000 ton. PLTU Beta mendapat jatah 800.000 tCO2e dan hanya beremisi 770.000 ton, jadi surplus 30.000 ton. Alfa membeli 30.000 SPE dari Beta seharga Rp69.000 per ton, total Rp2,07 miliar. Sisa defisit 20.000 ton ditutup Alfa dengan membeli SPE-GRK di IDXCarbon. Transaksi tercatat di SRN-PPI sehingga tidak ada klaim ganda, dan Beta memperoleh pendapatan baru dari efisiensinya.",
      },
      {
        type: "classifyExercise",
        prompt: "Cocokkan tugas berikut ke lembaga yang tepat.",
        buckets: ["KLHK", "OJK", "Kemenkeu"],
        items: [
          { text: "Mengawasi Bursa Karbon", bucket: "OJK" },
          { text: "Mengelola SRN-PPI dan SPE-GRK", bucket: "KLHK" },
          { text: "Menetapkan pajak karbon", bucket: "Kemenkeu" },
          { text: "Sertifikasi pengurangan emisi GRK", bucket: "KLHK" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah regulasi dengan artinya.",
        pairs: [
          { left: "NEK", right: "Nilai Ekonomi Karbon (kerangka Perpres 98/2021)" },
          { left: "SRN-PPI", right: "Sistem Registri Nasional aksi iklim" },
          { left: "SPE-GRK", right: "Sertifikat pengurangan emisi yang diperdagangkan" },
          { left: "IDXCarbon", right: "Bursa Karbon Indonesia (sejak 2023)" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "PLTU beremisi 1.050.000 tCO2e dengan jatah (PTBAE-PU) 1.000.000 tCO2e. Berapa ton SPE-GRK yang harus dibeli untuk menutup defisit?",
        answer: 50000,
        tolerance: 0,
        suffix: "tCO2e",
        solution: "Defisit = emisi - jatah = 1.050.000 - 1.000.000 = <strong>50.000 tCO2e</strong> yang harus ditutup dengan SPE-GRK.",
        hint: "Defisit adalah selisih emisi di atas batas yang diberikan.",
      },
      {
        type: "calcExercise",
        prompt: "PLTU membeli 30.000 SPE-GRK seharga Rp69.000 per ton. Berapa total biaya yang dikeluarkan?",
        answer: 2070000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Biaya = 30.000 x Rp69.000 = <strong>Rp2.070.000.000</strong>.",
        hint: "Kalikan jumlah ton dengan harga per ton.",
      },
      {
        type: "takeaways",
        items: [
          "Perpres 98/2021 adalah payung Nilai Ekonomi Karbon di Indonesia.",
          "KLHK mengatur registri (SRN-PPI) dan sertifikat (SPE-GRK); OJK mengawasi bursa.",
          "IDXCarbon diluncurkan 26 September 2023 sebagai bursa karbon nasional.",
          "Perdagangan wajib dimulai dari subsektor pembangkit listrik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa payung hukum utama Nilai Ekonomi Karbon di Indonesia?",
            options: ["UU Cipta Kerja", "Perpres 98/2021", "UU Minerba", "PP 23"],
            answer: 1,
            explain: "Perpres 98/2021 mengatur penyelenggaraan Nilai Ekonomi Karbon.",
          },
          {
            q: "Lembaga yang mengawasi Bursa Karbon adalah?",
            options: ["KLHK", "OJK", "BPK", "BPS"],
            answer: 1,
            explain: "OJK mengatur dan mengawasi penyelenggaraan Bursa Karbon.",
          },
          {
            q: "SPE-GRK adalah?",
            options: [
              "Sistem registri",
              "Sertifikat pengurangan emisi yang diperdagangkan",
              "Nama bursa",
              "Jenis pajak",
            ],
            answer: 1,
            explain: "SPE-GRK adalah sertifikat pengurangan emisi yang menjadi unit perdagangan.",
          },
          {
            q: "IDXCarbon mulai beroperasi pada?",
            options: ["2016", "26 September 2023", "2030", "2019"],
            answer: 1,
            explain: "Bursa Karbon IDX (IDXCarbon) diluncurkan 26 September 2023.",
          },
          {
            q: "Perdagangan karbon wajib di Indonesia pertama diterapkan pada subsektor?",
            options: ["Perbankan", "Pembangkit listrik (PLTU)", "Pariwisata", "Tekstil"],
            answer: 1,
            explain: "Penerapan awal cap-and-trade di Indonesia dimulai pada subsektor pembangkit listrik.",
          },
          {
            q: "Batas emisi yang diberikan tiap PLTU dalam skema ini disebut?",
            options: ["PTBAE-PU", "PBB", "PKB", "PPh"],
            answer: 0,
            explain: "PTBAE-PU adalah Persetujuan Teknis Batas Atas Emisi pelaku usaha pembangkit.",
          },
          {
            q: "PLTU beremisi 1.050.000 tCO2e dengan jatah 1.000.000 tCO2e. Berapa defisit yang harus ditutup?",
            options: ["50.000 tCO2e", "500.000 tCO2e", "5.000 tCO2e", "1.050.000 tCO2e"],
            answer: 0,
            explain: "Defisit = 1.050.000 - 1.000.000 = 50.000 tCO2e.",
          },
          {
            q: "Mengapa pencatatan transaksi di SRN-PPI penting?",
            options: [
              "Untuk menaikkan harga",
              "Agar tidak terjadi klaim ganda atas pengurangan yang sama",
              "Untuk menghindari pajak",
              "Agar PLTU bebas emisi",
            ],
            answer: 1,
            explain: "Registri nasional mencatat unit agar satu pengurangan tidak diklaim lebih dari sekali.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "pajak-karbon",
    levelId: "regulasi",
    order: 2,
    title: "Pajak Karbon",
    summary: "Instrumen fiskal untuk memberi harga emisi. Tarif UU HPP dan kalkulator pajak interaktif.",
    durationMin: 14,
    tags: ["pajak karbon", "kebijakan", "fiskal"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Pajak karbon</strong> adalah pungutan atas emisi karbon dari aktivitas yang menghasilkan emisi. Di Indonesia, dasar hukumnya adalah <strong>UU Harmonisasi Peraturan Perpajakan (UU HPP) 2021</strong>, dengan tarif minimal <strong>Rp30 per kg CO₂e</strong> (setara Rp30.000 per ton).",
      },
      {
        type: "stats",
        items: [
          { value: "Rp30", label: "per kg CO₂e", sub: "tarif minimal UU HPP", color: "#10b981" },
          { value: "Rp30.000", label: "per ton CO₂e", sub: "setara tarif minimal", color: "#0ea5e9" },
          { value: "Fiskal", label: "Instrumen", sub: "harga ditetapkan, emisi mengikuti", color: "#8b5cf6" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Perbandingan Tarif Pajak Karbon (Ilustrasi)",
        unit: "USD per tCO2e",
        source: "ilustrasi perbandingan kasar",
        note: "Tarif Indonesia tergolong rendah dibanding negara maju, mencerminkan tahap awal penerapan.",
        data: [
          { label: "Swedia", value: 130 },
          { label: "Kanada", value: 60 },
          { label: "Singapura", value: 18 },
          { label: "Indonesia", value: 2 },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Pajak karbon vs cap-and-trade",
        html: "Pada <strong>pajak</strong>, pemerintah menetapkan harga (Rp per ton), jumlah emisi menyesuaikan. Pada <strong>cap-and-trade</strong>, pemerintah menetapkan jumlah (cap), harga menyesuaikan. Keduanya memberi harga pada karbon dengan cara berbeda.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Hitung dampaknya",
        html: "Gunakan kalkulator berikut untuk melihat beban pajak karbon dan berapa yang bisa dihemat jika perusahaan menurunkan emisinya.",
      },
      {
        type: "widget",
        widget: "KalkulatorPajakKarbon",
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik memilih efisiensi karena pajak",
        html: "Pabrik beremisi 50.000 tCO2e per tahun menghadapi pajak Rp30.000 per ton, jadi Rp1,5 miliar setahun. Dengan berinvestasi Rp2 miliar pada efisiensi energi yang memangkas emisi 40%, pajak turun jadi Rp900 juta. Penghematan Rp600 juta per tahun membuat investasi itu balik modal dalam waktu wajar, sekaligus menurunkan emisi.",
      },
      {
        type: "case",
        title: "Studi Kasus: Skema cap-tax-trade dan payback investasi",
        html: "Indonesia memakai mekanisme campuran: pelaku usaha boleh menutup emisi di atas batas dengan membeli SPE-GRK; sisa yang tidak tertutup dikenai pajak karbon. Sebuah pabrik semen beremisi 200.000 tCO2e dengan jatah 180.000 ton. Defisit 20.000 ton: 15.000 ton ditutup dengan SPE seharga Rp60.000 per ton (Rp900 juta), sisa 5.000 ton kena pajak Rp30.000 per ton (Rp150 juta). Total beban karbon Rp1,05 miliar setahun. Jika pabrik memasang co-firing biomassa senilai Rp1,8 miliar yang memangkas emisi 12.000 ton, beban karbon turun drastis dan investasi balik modal dalam sekitar dua tahun.",
      },
      {
        type: "calcExercise",
        prompt: "Emisi 50.000 tCO2e, tarif pajak Rp30.000/ton. Berapa pajak karbon per tahun?",
        answer: 1500000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Pajak = 50.000 x Rp30.000 = <strong>Rp1.500.000.000</strong> per tahun.",
        hint: "Kalikan emisi dengan tarif per ton.",
      },
      {
        type: "calcExercise",
        prompt: "Jika emisi tersebut turun 40% menjadi 30.000 tCO2e, berapa penghematan pajaknya (tarif Rp30.000/ton)?",
        answer: 600000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Pajak baru = 30.000 x Rp30.000 = Rp900 juta. Penghematan = Rp1,5 miliar - Rp900 juta = <strong>Rp600.000.000</strong>.",
        hint: "Hitung pajak setelah pengurangan, lalu kurangkan dari pajak awal.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri ini milik pajak karbon atau cap-and-trade?",
        buckets: ["Pajak karbon", "Cap-and-trade"],
        items: [
          { text: "Pemerintah menetapkan harga per ton", bucket: "Pajak karbon" },
          { text: "Pemerintah menetapkan batas total emisi", bucket: "Cap-and-trade" },
          { text: "Jumlah emisi pasti, harga menyesuaikan", bucket: "Cap-and-trade" },
          { text: "Harga pasti, jumlah emisi menyesuaikan", bucket: "Pajak karbon" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Pabrik defisit 20.000 tCO2e: 15.000 ton ditutup SPE (Rp60.000/ton) dan 5.000 ton kena pajak (Rp30.000/ton). Berapa total beban karbon?",
        answer: 1050000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "SPE = 15.000 x Rp60.000 = Rp900 juta. Pajak = 5.000 x Rp30.000 = Rp150 juta. Total = <strong>Rp1.050.000.000</strong>.",
        hint: "Hitung biaya SPE dan biaya pajak terpisah, lalu jumlahkan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah fiskal karbon dengan artinya.",
        pairs: [
          { left: "UU HPP", right: "Dasar hukum pajak karbon Indonesia" },
          { left: "Rp30 per kg CO₂e", right: "Tarif minimal pajak karbon" },
          { left: "Cap-and-trade", right: "Pemerintah menetapkan batas, harga menyesuaikan" },
          { left: "Pajak karbon", right: "Pemerintah menetapkan harga, emisi menyesuaikan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Pajak karbon menetapkan harga emisi; jumlah emisi menyesuaikan.",
          "Dasar hukum Indonesia adalah UU HPP, tarif minimal Rp30 per kg CO₂e.",
          "Tarif Indonesia masih relatif rendah dibanding negara maju.",
          "Pajak mendorong perusahaan berinvestasi efisiensi untuk menekan beban.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tarif minimal pajak karbon menurut UU HPP adalah?",
            options: ["Rp3 per kg", "Rp30 per kg CO₂e", "Rp300 per kg", "Rp30 per ton"],
            answer: 1,
            explain: "UU HPP menetapkan tarif minimal Rp30 per kg CO₂e, setara Rp30.000 per ton.",
          },
          {
            q: "Pada pajak karbon, yang ditetapkan pemerintah adalah?",
            options: ["Jumlah emisi total", "Harga per ton emisi", "Jumlah perusahaan", "Lokasi pabrik"],
            answer: 1,
            explain: "Pajak menetapkan harga; jumlah emisi mengikuti respons pelaku usaha.",
          },
          {
            q: "Emisi 20.000 tCO2e, tarif Rp30.000/ton. Pajaknya?",
            options: ["Rp600 juta", "Rp60 juta", "Rp6 miliar", "Rp6 juta"],
            answer: 0,
            explain: "20.000 x Rp30.000 = Rp600.000.000.",
          },
          {
            q: "Dibanding negara maju, tarif pajak karbon Indonesia umumnya?",
            options: ["Lebih tinggi", "Relatif rendah", "Identik", "Tidak ada"],
            answer: 1,
            explain: "Tarif Indonesia tergolong rendah karena masih tahap awal penerapan.",
          },
          {
            q: "Mengapa pajak karbon mendorong efisiensi?",
            options: [
              "Karena melarang produksi",
              "Karena menurunkan emisi langsung mengurangi pajak yang dibayar",
              "Karena menambah subsidi fosil",
              "Karena tidak ada hubungannya",
            ],
            answer: 1,
            explain: "Semakin rendah emisi, semakin kecil pajak, sehingga ada insentif finansial untuk efisiensi.",
          },
          {
            q: "Tarif Rp30 per kg CO₂e setara berapa per ton?",
            options: ["Rp300 per ton", "Rp3.000 per ton", "Rp30.000 per ton", "Rp300.000 per ton"],
            answer: 2,
            explain: "1 ton = 1.000 kg, jadi Rp30 x 1.000 = Rp30.000 per ton CO₂e.",
          },
          {
            q: "Dalam skema campuran, emisi di atas batas yang tidak ditutup SPE akan?",
            options: [
              "Dibiarkan gratis",
              "Dikenai pajak karbon",
              "Dihapus otomatis",
              "Dijual ke luar negeri",
            ],
            answer: 1,
            explain: "Sisa defisit yang tidak ditutup dengan SPE dikenai pajak karbon.",
          },
          {
            q: "Defisit 5.000 tCO2e kena pajak Rp30.000/ton. Berapa pajaknya?",
            options: ["Rp15 juta", "Rp150 juta", "Rp1,5 miliar", "Rp1,5 juta"],
            answer: 1,
            explain: "5.000 x Rp30.000 = Rp150.000.000.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "kontrak-dan-sengketa",
    levelId: "regulasi",
    order: 3,
    title: "Kontrak Karbon & Penyelesaian Sengketa",
    summary: "Aspek hukum perjanjian jual beli pengurangan emisi (ERPA), tanggung jawab, dan risiko sengketa.",
    durationMin: 13,
    tags: ["hukum", "kontrak", "sengketa"],
    blocks: [
      {
        type: "paragraph",
        html: "Transaksi karbon dituangkan dalam kontrak, yang paling umum adalah <strong>ERPA (Emission Reduction Purchase Agreement)</strong>. Kontrak ini mengatur siapa menanggung risiko jika kredit gagal terbit, batal, atau dipersengketakan.",
      },
      {
        type: "table",
        caption: "Klausul penting dalam kontrak karbon (ERPA)",
        headers: ["Klausul", "Mengatur tentang"],
        rows: [
          ["Volume & harga", "Berapa ton, harga per ton, jadwal penyerahan"],
          ["Delivery risk", "Apa terjadi jika kredit gagal terbit sesuai target"],
          ["Title & ownership", "Siapa pemilik sah kredit dan kapan beralih"],
          ["Representations & warranties", "Jaminan keabsahan, additionality, bebas klaim ganda"],
          ["Force majeure", "Kebakaran hutan, bencana, perubahan regulasi"],
          ["Dispute resolution", "Forum penyelesaian: pengadilan atau arbitrase"],
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Risiko hukum yang khas",
        html: "Karbon adalah aset baru, sehingga status hukumnya belum seragam antarnegara. Risiko meliputi: perubahan regulasi mendadak, sengketa kepemilikan lahan/hutan, klaim masyarakat adat, dan pembatalan kredit oleh registry.",
      },
      {
        type: "case",
        title: "Studi Kasus: Hutan terbakar setelah kredit dijual",
        html: "Pengembang menjual 100.000 kredit dari proyek hutan. Tahun berikutnya, sebagian hutan terbakar sehingga karbon yang seharusnya tersimpan lepas kembali (non-permanence). Siapa bertanggung jawab? Tergantung kontrak: banyak ERPA mewajibkan <strong>buffer pool</strong> (cadangan kredit) dan klausul penggantian. Tanpa klausul jelas, muncul sengketa panjang antara pembeli, penjual, dan registry.",
      },
      {
        type: "case",
        title: "Studi Kasus: Delivery shortfall dan klausul penalti ERPA",
        html: "Sebuah ERPA menetapkan penyerahan 200.000 kredit selama tiga tahun pada harga Rp75.000 per ton, total kontrak Rp15 miliar. Proyek hanya mampu menerbitkan 150.000 kredit (shortfall 50.000 ton). Kontrak memuat klausul <strong>delivery shortfall</strong>: penjual wajib mengganti dengan kredit setara di pasar atau membayar penalti selisih harga. Jika harga pasar pengganti naik menjadi Rp90.000 per ton, penjual menanggung selisih Rp15.000 per ton x 50.000 ton = Rp750 juta. Klausul yang jelas inilah yang mengubah potensi sengketa menjadi mekanisme penyelesaian yang terukur.",
      },
      {
        type: "classifyExercise",
        prompt: "Klausul kontrak ini menjawab risiko apa?",
        buckets: ["Risiko gagal terbit", "Risiko kepemilikan", "Risiko bencana"],
        items: [
          { text: "Delivery guarantee dan penalti", bucket: "Risiko gagal terbit" },
          { text: "Title transfer dan bukti kepemilikan lahan", bucket: "Risiko kepemilikan" },
          { text: "Force majeure dan buffer pool", bucket: "Risiko bencana" },
          { text: "Warranty bebas klaim pihak ketiga", bucket: "Risiko kepemilikan" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah hukum karbon dengan artinya.",
        pairs: [
          { left: "ERPA", right: "Perjanjian jual beli pengurangan emisi" },
          { left: "Buffer pool", right: "Cadangan kredit untuk menutup risiko non-permanence" },
          { left: "Arbitrase", right: "Forum penyelesaian sengketa di luar pengadilan" },
          { left: "Force majeure", right: "Keadaan kahar seperti bencana yang membebaskan kewajiban" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Shortfall 50.000 ton harus diganti. Harga kontrak Rp75.000/ton, harga pasar pengganti Rp90.000/ton. Berapa selisih biaya yang ditanggung penjual?",
        answer: 750000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Selisih harga = Rp90.000 - Rp75.000 = Rp15.000 per ton. Total = 50.000 x Rp15.000 = <strong>Rp750.000.000</strong>.",
        hint: "Hitung selisih harga per ton dulu, lalu kalikan dengan volume shortfall.",
      },
      {
        type: "calcExercise",
        prompt: "Proyek hutan menjual 100.000 kredit, tetapi registry mensyaratkan buffer pool 20%. Berapa kredit yang harus disisihkan ke buffer pool?",
        answer: 20000,
        tolerance: 0,
        suffix: "kredit",
        solution: "Buffer pool = 20% x 100.000 = <strong>20.000 kredit</strong> disisihkan sebagai cadangan non-permanence.",
        hint: "Kalikan total kredit dengan persentase buffer.",
      },
      {
        type: "takeaways",
        items: [
          "ERPA adalah kontrak utama jual beli pengurangan emisi.",
          "Kontrak mengalokasikan risiko gagal terbit, kepemilikan, dan bencana.",
          "Buffer pool menutup risiko karbon lepas kembali (non-permanence).",
          "Status hukum karbon yang belum seragam membuat klausul yang jelas sangat penting.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kontrak utama dalam transaksi karbon disebut?",
            options: ["MoU", "ERPA", "SPK", "NDA"],
            answer: 1,
            explain: "ERPA (Emission Reduction Purchase Agreement) adalah kontrak jual beli pengurangan emisi.",
          },
          {
            q: "Buffer pool berfungsi untuk?",
            options: [
              "Menaikkan harga",
              "Menutup risiko karbon lepas kembali (non-permanence)",
              "Menghindari pajak",
              "Mempercepat penerbitan",
            ],
            answer: 1,
            explain: "Buffer pool adalah cadangan kredit untuk mengganti bila karbon yang tersimpan lepas kembali.",
          },
          {
            q: "Force majeure dalam ERPA mencakup?",
            options: ["Kenaikan harga biasa", "Bencana seperti kebakaran hutan", "Keterlambatan email", "Pergantian direktur"],
            answer: 1,
            explain: "Force majeure adalah keadaan kahar di luar kendali, seperti bencana alam.",
          },
          {
            q: "Mengapa risiko hukum karbon relatif tinggi?",
            options: [
              "Karena karbon aset lama yang baku",
              "Karena status hukum karbon belum seragam antarnegara",
              "Karena tidak ada kontrak",
              "Karena harganya tetap",
            ],
            answer: 1,
            explain: "Sebagai aset baru, kerangka hukum karbon masih berkembang dan berbeda antaryurisdiksi.",
          },
          {
            q: "Forum penyelesaian sengketa di luar pengadilan disebut?",
            options: ["Mediasi paksa", "Arbitrase", "Demonstrasi", "Lelang"],
            answer: 1,
            explain: "Arbitrase adalah mekanisme penyelesaian sengketa di luar pengadilan yang sering dipilih dalam kontrak lintas negara.",
          },
          {
            q: "Klausul yang mengatur ganti rugi bila kredit gagal terbit sesuai target disebut?",
            options: ["Delivery shortfall", "Force majeure", "Title transfer", "Confidentiality"],
            answer: 0,
            explain: "Delivery shortfall mengatur kewajiban penjual mengganti atau membayar penalti atas kredit yang kurang terbit.",
          },
          {
            q: "Shortfall 50.000 ton, selisih harga Rp15.000/ton. Berapa biaya yang ditanggung penjual?",
            options: ["Rp75 juta", "Rp750 juta", "Rp7,5 miliar", "Rp7,5 juta"],
            answer: 1,
            explain: "50.000 x Rp15.000 = Rp750.000.000.",
          },
          {
            q: "Klausul representations and warranties dalam ERPA menjamin antara lain?",
            options: [
              "Harga selalu naik",
              "Additionality dan bebas klaim ganda",
              "Cuaca cerah",
              "Pengiriman lewat laut",
            ],
            answer: 1,
            explain: "Klausul ini menjamin keabsahan kredit, additionality, dan bebas dari klaim ganda.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "paris-agreement",
    levelId: "regulasi",
    order: 4,
    title: "Paris Agreement & Pasal 6",
    summary: "Kerangka iklim global, NDC, dan perdagangan karbon antarnegara lewat ITMO. Dengan video Pasal 6.",
    durationMin: 15,
    tags: ["internasional", "Paris", "Pasal 6"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Paris Agreement (2015)</strong> menyatukan dunia menahan kenaikan suhu di bawah 2°C dan mengupayakan 1,5°C. Tiap negara menetapkan target sendiri, disebut <strong>NDC (Nationally Determined Contribution)</strong>. Pasal 6 mengatur bagaimana negara boleh bekerja sama lewat perdagangan karbon.",
      },
      {
        type: "video",
        comp: "ParisArticle6",
        title: "Video: Paris Agreement Pasal 6",
        caption: "Animasi perpindahan ITMO antarnegara dan corresponding adjustment.",
      },
      {
        type: "table",
        caption: "Mekanisme di bawah Pasal 6",
        headers: ["Pasal", "Mekanisme", "Inti"],
        rows: [
          ["6.2", "Cooperative approaches (ITMO)", "Negara saling memperdagangkan hasil pengurangan emisi"],
          ["6.4", "Mekanisme tersentral (PACM)", "Mekanisme kredit global di bawah PBB"],
          ["6.8", "Non-market approaches", "Kerja sama tanpa perdagangan (mis. bantuan teknis)"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Kunci integritas: corresponding adjustment",
        html: "Ketika negara A menjual pengurangan ke negara B, negara A harus <strong>tidak lagi menghitungnya</strong> dalam NDC-nya. Tanpa penyesuaian ini, satu ton bisa diklaim dua negara (double counting), dan target global jadi semu.",
      },
      {
        type: "case",
        title: "Studi Kasus: Indonesia dan kerja sama bilateral",
        html: "Indonesia, sebagai negara dengan hutan luas, berpotensi menjual ITMO ke negara seperti Jepang atau Singapura yang sulit memenuhi NDC-nya di dalam negeri. Namun Indonesia harus berhati-hati: jika menjual terlalu banyak pengurangan murah ke luar negeri, target NDC sendiri bisa terancam. Karena itu pemerintah mengatur ambang dan persetujuan (otorisasi) untuk setiap ekspor kredit.",
      },
      {
        type: "case",
        title: "Studi Kasus: Transfer ITMO Singapura dengan corresponding adjustment",
        html: "Singapura ingin mengimpor 500.000 ITMO dari proyek di Indonesia pada harga USD 25 per ton, total USD 12,5 juta. Aturan main Pasal 6.2: Indonesia harus melakukan <strong>corresponding adjustment</strong>, yaitu menambah 500.000 tCO2e ke neraca emisinya sendiri sehingga pengurangan itu tidak lagi dihitung untuk NDC Indonesia. Singapura lalu mengurangi 500.000 tCO2e dari neracanya. Hasilnya satu ton hanya diklaim sekali. Jika NDC Indonesia membutuhkan pengurangan 100 juta ton, mengekspor 500.000 ton berarti Indonesia harus mencari pengganti 500.000 ton dari sumber lain. Inilah alasan otorisasi ekspor diperketat.",
      },
      {
        type: "classifyExercise",
        prompt: "Mekanisme Pasal 6 yang mana?",
        buckets: ["Pasal 6.2 (ITMO)", "Pasal 6.4 (PBB)", "Pasal 6.8 (non-pasar)"],
        items: [
          { text: "Perdagangan bilateral hasil pengurangan antarnegara", bucket: "Pasal 6.2 (ITMO)" },
          { text: "Mekanisme kredit tersentral di bawah PBB", bucket: "Pasal 6.4 (PBB)" },
          { text: "Kerja sama berupa bantuan teknis tanpa jual beli", bucket: "Pasal 6.8 (non-pasar)" },
          { text: "Transfer ITMO dengan corresponding adjustment", bucket: "Pasal 6.2 (ITMO)" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah internasional dengan artinya.",
        pairs: [
          { left: "NDC", right: "Target iklim nasional tiap negara" },
          { left: "ITMO", right: "Hasil pengurangan emisi yang diperdagangkan antarnegara" },
          { left: "Corresponding adjustment", right: "Mencegah satu ton diklaim dua negara" },
          { left: "Paris Agreement", right: "Perjanjian iklim global 2015" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Singapura mengimpor 500.000 ITMO pada harga USD 25 per ton. Berapa nilai total transaksinya (dalam USD)?",
        answer: 12500000,
        tolerance: 0,
        prefix: "USD ",
        solution: "Nilai = 500.000 x USD 25 = <strong>USD 12.500.000</strong>.",
        hint: "Kalikan volume ITMO dengan harga per ton.",
      },
      {
        type: "calcExercise",
        prompt: "NDC Indonesia butuh pengurangan 100 juta ton. Setelah mengekspor 500.000 ton sebagai ITMO (dengan corresponding adjustment), berapa ton lagi yang harus dipenuhi dari sumber dalam negeri?",
        answer: 100500000,
        tolerance: 0,
        suffix: "tCO2e",
        solution: "Pengurangan yang diekspor tidak boleh dihitung untuk NDC sendiri, jadi target efektif = 100.000.000 + 500.000 = <strong>100.500.000 tCO2e</strong>.",
        hint: "Karena diekspor, pengurangan itu dikeluarkan dari neraca NDC sehingga target dalam negeri bertambah.",
      },
      {
        type: "takeaways",
        items: [
          "Paris Agreement menargetkan menahan pemanasan di bawah 2°C, idealnya 1,5°C.",
          "Tiap negara menetapkan target sendiri (NDC).",
          "Pasal 6 mengatur perdagangan karbon antarnegara lewat ITMO dan mekanisme PBB.",
          "Corresponding adjustment mencegah double counting agar perdagangan kredibel.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "NDC adalah?",
            options: ["Nama bursa", "Target iklim nasional tiap negara", "Jenis pajak", "Satuan emisi"],
            answer: 1,
            explain: "NDC adalah komitmen pengurangan emisi yang ditetapkan tiap negara.",
          },
          {
            q: "Pasal 6.2 Paris Agreement mengatur?",
            options: [
              "Larangan perdagangan",
              "Pendekatan kerja sama lewat ITMO antarnegara",
              "Pajak global",
              "Subsidi fosil",
            ],
            answer: 1,
            explain: "Pasal 6.2 memungkinkan negara memperdagangkan hasil pengurangan (ITMO).",
          },
          {
            q: "Fungsi corresponding adjustment adalah?",
            options: [
              "Menaikkan harga ITMO",
              "Mencegah satu ton pengurangan diklaim dua negara",
              "Mempercepat transaksi",
              "Menghapus NDC",
            ],
            answer: 1,
            explain: "Penyesuaian ini memastikan hanya satu negara yang mengklaim pengurangan tersebut.",
          },
          {
            q: "Mengapa Indonesia harus hati-hati menjual ITMO?",
            options: [
              "Karena dilarang",
              "Karena menjual terlalu banyak pengurangan murah bisa mengancam NDC sendiri",
              "Karena tidak ada pembeli",
              "Karena harganya tetap",
            ],
            answer: 1,
            explain: "Pengurangan yang dijual ke luar tidak bisa dihitung untuk NDC sendiri, sehingga perlu pengaturan ambang.",
          },
          {
            q: "Tanpa corresponding adjustment, risikonya?",
            options: ["Harga naik", "Double counting yang membuat target global semu", "Transaksi lebih cepat", "Tidak ada risiko"],
            answer: 1,
            explain: "Tanpa penyesuaian, satu ton bisa dihitung dua kali sehingga pengurangan global dilebih-lebihkan.",
          },
          {
            q: "Mekanisme kredit tersentral di bawah PBB pada Paris Agreement diatur oleh?",
            options: ["Pasal 6.2", "Pasal 6.4 (PACM)", "Pasal 6.8", "Pasal 12"],
            answer: 1,
            explain: "Pasal 6.4 mengatur mekanisme kredit global tersentral (PACM) di bawah PBB.",
          },
          {
            q: "Singapura mengimpor 500.000 ITMO pada USD 25 per ton. Nilai transaksinya?",
            options: ["USD 1,25 juta", "USD 12,5 juta", "USD 125 juta", "USD 1,25 miliar"],
            answer: 1,
            explain: "500.000 x USD 25 = USD 12.500.000.",
          },
          {
            q: "Saat negara penjual melakukan corresponding adjustment, ia harus?",
            options: [
              "Menghapus NDC-nya",
              "Menambah jumlah yang dijual ke neraca emisinya sendiri",
              "Menurunkan harga",
              "Membayar pajak ke PBB",
            ],
            answer: 1,
            explain: "Penjual menambahkan kembali jumlah yang ditransfer ke neracanya agar tidak diklaim ganda.",
          },
        ],
      },
    ],
  },

  // ============================================================
  {
    id: "perdagangan-global",
    levelId: "regulasi",
    order: 5,
    title: "Perdagangan Karbon Global",
    summary: "Lanskap pasar karbon dunia: EU ETS, China, dan kebijakan lintas batas seperti CBAM.",
    durationMin: 13,
    tags: ["internasional", "global", "CBAM"],
    blocks: [
      {
        type: "paragraph",
        html: "Pasar karbon kini tersebar di puluhan yurisdiksi. <strong>EU ETS</strong> adalah yang tertua dan paling besar nilainya, sementara <strong>China</strong> menjalankan ETS dengan cakupan emisi terbesar di dunia. Kebijakan lintas batas seperti <strong>CBAM</strong> mulai menghubungkan pasar-pasar ini.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Cakupan Emisi oleh Sistem ETS Utama",
        unit: "miliar tCO2e tercakup (ilustrasi)",
        source: "ilustrasi perbandingan cakupan",
        note: "China memiliki cakupan emisi terbesar karena sektor listriknya raksasa, meski harga per ton masih rendah.",
        data: [
          { label: "China ETS", value: 5.1 },
          { label: "EU ETS", value: 1.4 },
          { label: "Amerika (gabungan)", value: 0.6 },
          { label: "Lainnya", value: 1.0 },
        ],
      },
      {
        type: "stats",
        items: [
          { value: "70+", label: "Instrumen carbon pricing", sub: "pajak & ETS di dunia (ilustrasi)", color: "#10b981" },
          { value: "~24%", label: "Emisi global tercakup", sub: "oleh carbon pricing (ilustrasi)", color: "#0ea5e9" },
          { value: "2026", label: "CBAM penuh berlaku", sub: "fase definitif Uni Eropa", color: "#f59e0b" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "CBAM: pasar yang saling terhubung",
        html: "<strong>CBAM (Carbon Border Adjustment Mechanism)</strong> Uni Eropa mengenakan biaya karbon pada impor produk padat emisi seperti baja, semen, aluminium, dan pupuk. Eksportir Indonesia ke Uni Eropa perlu menghitung dan melaporkan jejak karbon produknya.",
      },
      {
        type: "case",
        title: "Studi Kasus: Eksportir Indonesia menghadapi CBAM",
        html: "Produsen aluminium Indonesia yang mengekspor ke Uni Eropa akan dikenai biaya CBAM berdasarkan emisi produksinya. Jika listrik pabriknya masih dari batu bara, biayanya tinggi. Memasang PLTS atau membeli energi terbarukan tidak hanya menurunkan emisi, tetapi juga menjaga daya saing ekspor. Regulasi negara lain ternyata bisa langsung memengaruhi strategi perusahaan Indonesia.",
      },
      {
        type: "case",
        title: "Studi Kasus: CBAM dan kredit pajak karbon dalam negeri",
        html: "Eksportir baja Indonesia mengirim 10.000 ton baja ke Uni Eropa dengan jejak 2 tCO2e per ton, jadi 20.000 tCO2e. Pada harga CBAM Rp900.000 per tCO2e, biaya kotornya Rp18 miliar. CBAM mengizinkan pengurangan atas harga karbon yang sudah dibayar di negara asal. Bila eksportir telah membayar pajak karbon Indonesia Rp30.000 per ton atas 20.000 ton (Rp600 juta), kewajiban CBAM bersih turun menjadi Rp18 miliar - Rp600 juta = Rp17,4 miliar. Memperkuat carbon pricing dalam negeri ternyata mengurangi setoran ke kas Uni Eropa.",
      },
      {
        type: "case",
        title: "Studi Kasus: Selisih harga antar pasar (EU ETS vs IDXCarbon)",
        html: "Harga di EU ETS sekitar EUR 70 per tCO2e, sementara SPE-GRK di IDXCarbon berkisar Rp60.000 per tCO2e (sekitar EUR 3,5). Selisih besar ini menjelaskan mengapa kredit murah dari negara berkembang menarik bagi pembeli Eropa, tetapi juga memunculkan risiko jika kredit mengalir keluar tanpa corresponding adjustment. Untuk 100.000 ton, pembeli Eropa membayar sekitar EUR 7 juta di EU ETS, sedangkan kredit setara di IDXCarbon hanya sekitar EUR 350 ribu. Perbedaan inilah yang mendorong perlunya aturan integritas lintas pasar.",
      },
      {
        type: "calcExercise",
        prompt: "Eksportir mengirim 10.000 ton baja dengan jejak 2 tCO2e per ton baja. Pada harga CBAM Rp900.000 per tCO2e, berapa total biaya karbonnya?",
        answer: 18000000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Emisi total = 10.000 x 2 = 20.000 tCO2e. Biaya = 20.000 x Rp900.000 = <strong>Rp18.000.000.000</strong>.",
        hint: "Hitung emisi total dulu (ton baja x emisi per ton), lalu kalikan harga.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini benar tentang pasar global yang mana?",
        buckets: ["EU ETS", "China ETS", "CBAM"],
        items: [
          { text: "ETS tertua dan paling besar nilainya", bucket: "EU ETS" },
          { text: "Cakupan emisi terbesar di dunia", bucket: "China ETS" },
          { text: "Mengenakan biaya karbon pada produk impor", bucket: "CBAM" },
          { text: "Harga per ton tinggi dan likuid", bucket: "EU ETS" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya CBAM kotor Rp18 miliar. Eksportir sudah membayar pajak karbon Indonesia Rp600 juta. Berapa kewajiban CBAM bersih yang masih harus dibayar?",
        answer: 17400000000,
        tolerance: 0,
        prefix: "Rp",
        solution: "CBAM mengakui harga karbon yang sudah dibayar di negara asal: Rp18.000.000.000 - Rp600.000.000 = <strong>Rp17.400.000.000</strong>.",
        hint: "Kurangkan pajak karbon yang sudah dibayar dari biaya CBAM kotor.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pasar atau kebijakan karbon global dengan cirinya.",
        pairs: [
          { left: "EU ETS", right: "Pasar tertua dan terbesar nilainya, harga per ton tinggi" },
          { left: "China ETS", right: "Cakupan emisi terbesar di dunia" },
          { left: "CBAM", right: "Biaya karbon atas impor produk padat emisi ke Uni Eropa" },
          { left: "IDXCarbon", right: "Bursa karbon Indonesia dengan SPE-GRK" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "EU ETS adalah pasar karbon tertua dan terbesar nilainya.",
          "China ETS punya cakupan emisi terbesar di dunia.",
          "Puluhan yurisdiksi kini menerapkan carbon pricing.",
          "CBAM menghubungkan pasar dan langsung memengaruhi eksportir Indonesia.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pasar karbon tertua dan terbesar nilainya adalah?",
            options: ["China ETS", "EU ETS", "IDXCarbon", "RGGI"],
            answer: 1,
            explain: "EU ETS, beroperasi sejak 2005, adalah yang tertua dan terbesar dari sisi nilai.",
          },
          {
            q: "ETS dengan cakupan emisi terbesar di dunia adalah?",
            options: ["EU ETS", "China ETS", "California", "Korea"],
            answer: 1,
            explain: "China ETS mencakup emisi terbesar karena sektor pembangkit listriknya raksasa.",
          },
          {
            q: "CBAM mengenakan biaya karbon pada?",
            options: ["Ekspor jasa", "Impor produk padat emisi", "Wisatawan", "Transaksi bank"],
            answer: 1,
            explain: "CBAM mengenakan biaya karbon pada impor barang padat emisi seperti baja dan semen.",
          },
          {
            q: "Mengapa CBAM penting bagi eksportir Indonesia?",
            options: [
              "Tidak berpengaruh",
              "Karena produk ekspor ke Uni Eropa dikenai biaya berdasarkan jejak karbonnya",
              "Karena melarang ekspor",
              "Karena menaikkan subsidi",
            ],
            answer: 1,
            explain: "Eksportir harus menghitung jejak karbon; produk berkarbon tinggi jadi lebih mahal dan kurang bersaing.",
          },
          {
            q: "Tren global carbon pricing menunjukkan?",
            options: [
              "Makin sedikit negara menerapkannya",
              "Makin banyak yurisdiksi menerapkan pajak atau ETS",
              "Sudah dihapus",
              "Hanya ada di Eropa",
            ],
            answer: 1,
            explain: "Jumlah instrumen carbon pricing terus bertambah di berbagai negara dan wilayah.",
          },
          {
            q: "Fase definitif CBAM Uni Eropa mulai berlaku penuh pada?",
            options: ["2021", "2023", "2026", "2035"],
            answer: 2,
            explain: "Setelah masa transisi, fase definitif CBAM berlaku penuh mulai 2026.",
          },
          {
            q: "Biaya CBAM kotor Rp18 miliar, pajak karbon dalam negeri yang sudah dibayar Rp600 juta. CBAM bersihnya?",
            options: ["Rp18,6 miliar", "Rp17,4 miliar", "Rp600 juta", "Rp18 miliar"],
            answer: 1,
            explain: "Rp18 miliar - Rp600 juta = Rp17,4 miliar, karena harga karbon di negara asal diakui.",
          },
          {
            q: "Mengapa selisih harga EU ETS dan IDXCarbon penting diperhatikan?",
            options: [
              "Tidak penting",
              "Kredit murah menarik bagi pembeli, memunculkan risiko bila mengalir tanpa corresponding adjustment",
              "Karena harga selalu sama",
              "Karena melarang ekspor",
            ],
            answer: 1,
            explain: "Selisih besar mendorong aliran kredit lintas pasar, sehingga aturan integritas seperti corresponding adjustment menjadi krusial.",
          },
        ],
      },
    ],
  },
];
