import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faGraduationCap,
  faRocket,
  faPlay,
  faArrowRight,
  faArrowLeft,
  faChevronRight,
  faCheck,
  faCircleCheck,
  faClock,
  faTag,
  faBookOpen,
  faLayerGroup,
  faFilm,
  faQuestion,
  faListCheck,
  faChartColumn,
  faChartLine,
  faChartPie,
  faMagnifyingGlass,
  faBullseye,
  faLightbulb,
  faTriangleExclamation,
  faKey,
  faCircleInfo,
  faSeedling,
  faTrophy,
  faRightFromBracket,
  faFlask,
  faPuzzlePiece,
  faWandMagicSparkles,
  faCompass,
  faStar,
  faHandPointer,
  faSliders,
  faFlagCheckered,
  faMedal,
  faRoute,
  faGears,
  faGlobe,
  faPenToSquare,
  faThumbsUp,
  faThumbsDown,
  faSpinner,
  faHashtag,
  faLock,
  faLockOpen,
  faCalculator,
  faBrain,
  faCoins,
  faLandmark,
  faUser,
  faGaugeHigh,
  faBookmark,
  faFire,
  faScaleBalanced,
  faRightToBracket,
  faFolderOpen,
  faChartArea,
  faCircleNotch,
  faArrowRightLong,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { faCirclePlay } from "@fortawesome/free-regular-svg-icons";

const registry = {
  "graduation-cap": faGraduationCap,
  rocket: faRocket,
  play: faPlay,
  "play-circle": faCirclePlay,
  "arrow-right": faArrowRight,
  "arrow-left": faArrowLeft,
  "chevron-right": faChevronRight,
  check: faCheck,
  "check-circle": faCircleCheck,
  clock: faClock,
  tag: faTag,
  hashtag: faHashtag,
  book: faBookOpen,
  layers: faLayerGroup,
  film: faFilm,
  question: faQuestion,
  "list-check": faListCheck,
  "chart-bar": faChartColumn,
  "chart-line": faChartLine,
  "chart-pie": faChartPie,
  search: faMagnifyingGlass,
  target: faBullseye,
  lightbulb: faLightbulb,
  warn: faTriangleExclamation,
  key: faKey,
  info: faCircleInfo,
  seedling: faSeedling,
  trophy: faTrophy,
  logout: faRightFromBracket,
  flask: faFlask,
  puzzle: faPuzzlePiece,
  magic: faWandMagicSparkles,
  compass: faCompass,
  star: faStar,
  pointer: faHandPointer,
  sliders: faSliders,
  flag: faFlagCheckered,
  medal: faMedal,
  route: faRoute,
  gears: faGears,
  globe: faGlobe,
  edit: faPenToSquare,
  "thumbs-up": faThumbsUp,
  "thumbs-down": faThumbsDown,
  spinner: faSpinner,
  lock: faLock,
  "lock-open": faLockOpen,
  calculator: faCalculator,
  brain: faBrain,
  coins: faCoins,
  landmark: faLandmark,
  user: faUser,
  gauge: faGaugeHigh,
  bookmark: faBookmark,
  fire: faFire,
  scale: faScaleBalanced,
  "sign-in": faRightToBracket,
  folder: faFolderOpen,
  "chart-area": faChartArea,
  loading: faCircleNotch,
  "arrow-long": faArrowRightLong,
  close: faXmark,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof registry;

export function Icon({
  name,
  className,
  spin,
}: {
  name: IconName;
  className?: string;
  spin?: boolean;
}) {
  return <FontAwesomeIcon icon={registry[name]} className={className} spin={spin} />;
}
