import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "elastisitas-permintaan",
    levelId: "elastisitas",
    order: 1,
    title: "Elastisitas Permintaan",
    summary: "Mengukur seberapa peka jumlah terhadap perubahan harga, dan mengapa itu penting bagi penjual. Dengan video & kalkulator.",
    durationMin: 13,
    tags: ["elastisitas", "permintaan", "pendapatan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Elastisitas harga permintaan</strong> mengukur seberapa besar jumlah yang diminta berubah ketika harga berubah. Rumusnya: persentase perubahan jumlah dibagi persentase perubahan harga. Ini menentukan apakah menaikkan harga akan menambah atau justru mengurangi pendapatan penjual.",
      },
      {
        type: "video",
        comp: "ElastisitasVideo",
        title: "Video: Elastis vs Inelastis",
        caption: "Animasi kurva permintaan curam (inelastis) vs landai (elastis).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Elastis vs inelastis",
        html: "<strong>Elastis (E {'>'} 1)</strong>: jumlah sangat peka, menaikkan harga menurunkan total pendapatan. <strong>Inelastis (E {'<'} 1)</strong>: jumlah kurang peka, menaikkan harga menambah pendapatan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan harga dan jumlah sebelum-sesudah untuk menghitung elastisitas dengan metode titik tengah.",
      },
      { type: "widget", widget: "KalkulatorElastisitas" },
      {
        type: "chart",
        variant: "bar",
        title: "Elastisitas Beberapa Barang (ilustrasi)",
        unit: "nilai elastisitas",
        source: "ilustrasi pola umum",
        note: "Kebutuhan pokok cenderung inelastis; barang dengan banyak substitusi cenderung elastis.",
        data: [
          { label: "Garam", value: 0.2, color: "#f59e0b" },
          { label: "BBM", value: 0.4, color: "#fb923c" },
          { label: "Restoran", value: 1.3, color: "#10b981" },
          { label: "Merek tertentu", value: 2.5, color: "#059669" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Warung menaikkan harga",
        html: "Sebuah warung kopi menaikkan harga 10%. Jika permintaannya <strong>inelastis</strong> (pelanggan setia), jumlah hanya turun 3%, sehingga pendapatan naik. Jika <strong>elastis</strong> (banyak pesaing di sekitar), jumlah turun 20%, sehingga pendapatan justru anjlok. Memahami elastisitas membantu menetapkan harga.",
      },
      {
        type: "calcExercise",
        prompt: "Harga naik 10%, jumlah diminta turun 20%. Berapa elastisitas (nilai absolut)?",
        answer: 2,
        tolerance: 0,
        solution: "E = %perubahan jumlah / %perubahan harga = 20% / 10% = <strong>2</strong> (elastis).",
        hint: "Bagi persentase perubahan jumlah dengan persentase perubahan harga.",
      },
      {
        type: "classifyExercise",
        prompt: "Barang ini cenderung elastis atau inelastis?",
        buckets: ["Elastis", "Inelastis"],
        items: [
          { text: "Obat penyakit kronis", bucket: "Inelastis" },
          { text: "Tiket bioskop", bucket: "Elastis" },
          { text: "Garam dapur", bucket: "Inelastis" },
          { text: "Soda merek tertentu (banyak substitusi)", bucket: "Elastis" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Total Pendapatan saat Harga Naik (ilustrasi)",
        unit: "indeks pendapatan",
        source: "ilustrasi pola umum",
        note: "Pada barang inelastis pendapatan ikut naik; pada barang elastis pendapatan justru turun saat harga dinaikkan.",
        data: [
          { label: "Inelastis (E=0,3)", value: 107, color: "#10b981" },
          { label: "Elastis (E=2,0)", value: 90, color: "#ef4444" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan nilai elastisitas dengan kategorinya.",
        pairs: [
          { left: "E = 0,2", right: "Inelastis (jumlah kurang peka)" },
          { left: "E = 1", right: "Elastis uniter (pendapatan tetap)" },
          { left: "E = 2,5", right: "Elastis (jumlah sangat peka)" },
          { left: "E = 0", right: "Inelastis sempurna (jumlah tetap)" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Elastisitas = %perubahan jumlah dibagi %perubahan harga.",
          "Elastis (E {'>'} 1): jumlah sangat peka terhadap harga.",
          "Inelastis (E {'<'} 1): jumlah kurang peka.",
          "Pada barang inelastis, menaikkan harga menambah pendapatan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Elastisitas mengukur?",
            options: ["Total pendapatan", "Kepekaan jumlah terhadap perubahan harga", "Biaya produksi", "Pajak"],
            answer: 1,
            explain: "Elastisitas mengukur respons jumlah terhadap perubahan harga.",
          },
          {
            q: "Permintaan inelastis berarti?",
            options: ["Jumlah sangat peka harga", "Jumlah kurang peka terhadap harga", "Harga tetap", "Tidak ada permintaan"],
            answer: 1,
            explain: "Inelastis: perubahan harga sedikit mengubah jumlah yang diminta.",
          },
          {
            q: "Pada barang inelastis, menaikkan harga akan?",
            options: ["Menurunkan pendapatan", "Menaikkan total pendapatan", "Tidak berpengaruh", "Menghapus permintaan"],
            answer: 1,
            explain: "Karena jumlah turun sedikit, total pendapatan justru naik.",
          },
          {
            q: "Harga turun 5%, jumlah naik 15%. Elastisitas?",
            options: ["3", "0,33", "1", "10"],
            answer: 0,
            explain: "15% / 5% = 3 (elastis).",
          },
          {
            q: "Faktor yang membuat permintaan lebih elastis?",
            options: ["Tidak ada substitusi", "Banyak barang substitusi", "Kebutuhan pokok", "Bagian kecil dari anggaran"],
            answer: 1,
            explain: "Makin banyak substitusi, makin mudah konsumen beralih, makin elastis.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "jenis-elastisitas",
    levelId: "elastisitas",
    order: 2,
    title: "Jenis-Jenis Elastisitas",
    summary: "Selain elastisitas harga permintaan, ada elastisitas penawaran, elastisitas pendapatan, dan elastisitas silang. Pahami faktor penentu dan cara membacanya.",
    durationMin: 14,
    tags: ["elastisitas", "penawaran", "pendapatan", "silang"],
    blocks: [
      {
        type: "paragraph",
        html: "Elastisitas bukan hanya soal harga dan permintaan. <strong>Elastisitas penawaran</strong> mengukur kepekaan jumlah yang ditawarkan terhadap harga. <strong>Elastisitas pendapatan</strong> mengukur kepekaan permintaan terhadap perubahan pendapatan konsumen. <strong>Elastisitas silang</strong> mengukur kepekaan permintaan satu barang terhadap perubahan harga barang lain.",
      },
      {
        type: "paragraph",
        html: "Ketiganya memakai pola yang sama: persentase perubahan jumlah dibagi persentase perubahan faktor pemicunya. Yang membedakan hanya faktor pemicunya: harga barang itu sendiri, pendapatan, atau harga barang lain.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga rumus inti",
        html: "<strong>Penawaran</strong> = %perubahan jumlah ditawarkan / %perubahan harga. <strong>Pendapatan</strong> = %perubahan jumlah diminta / %perubahan pendapatan. <strong>Silang</strong> = %perubahan jumlah barang A / %perubahan harga barang B.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Membaca tanda elastisitas silang",
        html: "Jika hasilnya <strong>positif</strong>, kedua barang bersifat <strong>substitusi</strong> (mis. teh dan kopi). Jika <strong>negatif</strong>, keduanya bersifat <strong>komplementer</strong> (mis. mobil dan bensin).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Elastisitas pendapatan dan jenis barang",
        html: "Hasil <strong>positif</strong> menandakan barang normal; lebih dari 1 berarti barang mewah. Hasil <strong>negatif</strong> menandakan barang inferior, yang justru dibeli lebih sedikit saat pendapatan naik.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Elastisitas Pendapatan Beberapa Barang (ilustrasi)",
        unit: "nilai elastisitas pendapatan",
        source: "ilustrasi pola umum",
        note: "Nilai negatif menandai barang inferior; nilai di atas 1 menandai barang mewah.",
        data: [
          { label: "Mi instan", value: -0.3, color: "#ef4444" },
          { label: "Beras", value: 0.3, color: "#f59e0b" },
          { label: "Pakaian", value: 1.0, color: "#10b981" },
          { label: "Liburan", value: 2.2, color: "#059669" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Harga bensin dan penjualan mobil",
        html: "Saat harga bensin naik 25%, penjualan mobil baru turun 5%. Elastisitas silangnya = -5% / 25% = <strong>-0,2</strong>. Tandanya negatif, jadi bensin dan mobil adalah barang <strong>komplementer</strong>: konsumen mengurangi pembelian mobil ketika biaya menggunakannya ikut naik.",
      },
      {
        type: "calcExercise",
        prompt: "Harga teh naik 20%, lalu jumlah kopi yang diminta naik 10%. Berapa elastisitas silangnya?",
        answer: 0.5,
        tolerance: 0.01,
        solution: "Silang = %perubahan jumlah kopi / %perubahan harga teh = 10% / 20% = <strong>0,5</strong>. Positif, jadi teh dan kopi bersifat substitusi.",
        hint: "Bagi persentase perubahan jumlah barang A dengan persentase perubahan harga barang B.",
      },
      {
        type: "classifyExercise",
        prompt: "Hubungan antar barang ini substitusi atau komplementer?",
        buckets: ["Substitusi", "Komplementer"],
        items: [
          { text: "Teh dan kopi", bucket: "Substitusi" },
          { text: "Mobil dan bensin", bucket: "Komplementer" },
          { text: "Mentega dan margarin", bucket: "Substitusi" },
          { text: "Ponsel dan casing ponsel", bucket: "Komplementer" },
        ],
      },
      {
        type: "video",
        comp: "ElastisitasPenawaran",
        title: "Video: Elastisitas Penawaran",
        caption: "Animasi kurva penawaran yang curam (inelastis) versus landai (elastis) saat harga berubah.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Elastisitas Silang Beberapa Pasangan Barang (ilustrasi)",
        unit: "nilai elastisitas silang",
        source: "ilustrasi pola umum",
        note: "Nilai positif menandai barang substitusi; nilai negatif menandai barang komplementer.",
        data: [
          { label: "Mobil & bensin", value: -0.2, color: "#ef4444" },
          { label: "Ponsel & casing", value: -0.6, color: "#fb923c" },
          { label: "Teh & kopi", value: 0.5, color: "#34d399" },
          { label: "Mentega & margarin", value: 1.1, color: "#059669" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Harga naik 10% dan jumlah yang ditawarkan naik 25%. Berapa elastisitas penawaran?",
        answer: 2.5,
        tolerance: 0.01,
        solution: "Penawaran = %perubahan jumlah ditawarkan / %perubahan harga = 25% / 10% = <strong>2,5</strong> (penawaran elastis).",
        hint: "Bagi persentase perubahan jumlah yang ditawarkan dengan persentase perubahan harga.",
      },
      {
        type: "takeaways",
        items: [
          "Semua elastisitas memakai pola %perubahan jumlah dibagi %perubahan pemicunya.",
          "Elastisitas penawaran mengukur respons jumlah ditawarkan terhadap harga.",
          "Elastisitas pendapatan positif = barang normal, negatif = barang inferior.",
          "Elastisitas silang positif = substitusi, negatif = komplementer.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Elastisitas penawaran mengukur kepekaan?",
            options: ["Jumlah ditawarkan terhadap harga", "Pendapatan terhadap pajak", "Harga terhadap biaya", "Permintaan terhadap iklan"],
            answer: 0,
            explain: "Elastisitas penawaran = %perubahan jumlah ditawarkan / %perubahan harga.",
          },
          {
            q: "Elastisitas silang bernilai negatif menandakan kedua barang?",
            options: ["Substitusi", "Komplementer", "Tidak berhubungan", "Sama persis"],
            answer: 1,
            explain: "Tanda negatif berarti kenaikan harga satu barang menurunkan permintaan barang lain, ciri komplementer.",
          },
          {
            q: "Barang inferior memiliki elastisitas pendapatan?",
            options: ["Lebih dari 1", "Positif kecil", "Negatif", "Nol"],
            answer: 2,
            explain: "Barang inferior dibeli lebih sedikit saat pendapatan naik, sehingga elastisitas pendapatannya negatif.",
          },
          {
            q: "Harga gula naik 10%, permintaan kopi turun 5%. Elastisitas silangnya?",
            options: ["-0,5", "0,5", "2", "-2"],
            answer: 0,
            explain: "-5% / 10% = -0,5; tanda negatif menandakan keduanya komplementer.",
          },
          {
            q: "Elastisitas pendapatan sebesar 2,2 menandakan barang?",
            options: ["Inferior", "Kebutuhan pokok", "Mewah", "Bebas"],
            answer: 2,
            explain: "Nilai di atas 1 berarti permintaan tumbuh lebih cepat dari pendapatan, ciri barang mewah.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "perilaku-konsumen",
    levelId: "elastisitas",
    order: 3,
    title: "Perilaku Konsumen",
    summary: "Memahami utilitas total dan marginal, hukum utilitas marginal yang menurun, serta bagaimana konsumen mencapai keseimbangan.",
    durationMin: 13,
    tags: ["utilitas", "marginal", "konsumen", "keseimbangan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Utilitas</strong> adalah kepuasan yang diperoleh konsumen dari mengonsumsi barang. <strong>Utilitas total (TU)</strong> adalah jumlah seluruh kepuasan dari semua unit yang dikonsumsi. <strong>Utilitas marginal (MU)</strong> adalah tambahan kepuasan dari mengonsumsi satu unit tambahan.",
      },
      {
        type: "paragraph",
        html: "Hubungannya: MU = perubahan TU dibagi perubahan jumlah unit. Selama MU masih positif, TU terus naik; ketika MU mencapai nol, TU berada di puncaknya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Hukum utilitas marginal yang menurun",
        html: "Semakin banyak unit suatu barang dikonsumsi dalam satu waktu, <strong>tambahan kepuasan (MU) dari setiap unit berikutnya cenderung menurun</strong>. Gelas air pertama saat haus terasa nikmat; gelas kelima nyaris tak menambah kepuasan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kaitan TU dan MU",
        html: "Saat MU positif, TU naik. Saat MU = 0, TU maksimum. Jika konsumsi diteruskan hingga MU negatif, TU justru turun (mis. kekenyangan).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Keseimbangan konsumen",
        html: "Konsumen mencapai kepuasan maksimum ketika <strong>utilitas marginal per rupiah sama untuk semua barang</strong>: MUx/Px = MUy/Py. Jika belum sama, geser belanja ke barang yang MU per rupiahnya lebih tinggi.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Utilitas Marginal Menurun (ilustrasi)",
        unit: "util per unit",
        source: "ilustrasi pola umum",
        note: "Tambahan kepuasan menyusut seiring bertambahnya unit yang dikonsumsi.",
        data: [
          { label: "Unit 1", value: 10, color: "#10b981" },
          { label: "Unit 2", value: 8, color: "#34d399" },
          { label: "Unit 3", value: 6, color: "#fbbf24" },
          { label: "Unit 4", value: 4, color: "#fb923c" },
          { label: "Unit 5", value: 2, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Makan bakso",
        html: "Andi makan bakso. Mangkuk pertama memberi 10 util, kedua 8 util, ketiga 6 util. Utilitas totalnya naik dari 10 menjadi 18 lalu 24 util, tetapi <strong>tambahan kepuasannya terus menurun</strong>. Inilah hukum utilitas marginal yang menurun: setiap mangkuk berikutnya menambah kepuasan lebih sedikit.",
      },
      {
        type: "calcExercise",
        prompt: "Utilitas total naik dari 24 util (4 unit) menjadi 28 util (5 unit). Berapa utilitas marginal unit ke-5?",
        answer: 4,
        tolerance: 0,
        solution: "MU = perubahan TU / perubahan unit = (28 - 24) / (5 - 4) = <strong>4 util</strong>.",
        hint: "Kurangi TU sesudah dengan TU sebelum, lalu bagi dengan tambahan unit.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan pengertiannya.",
        pairs: [
          { left: "Utilitas total", right: "Jumlah seluruh kepuasan dari semua unit" },
          { left: "Utilitas marginal", right: "Tambahan kepuasan dari satu unit lagi" },
          { left: "MU = 0", right: "Utilitas total mencapai puncak" },
          { left: "Keseimbangan konsumen", right: "MU per rupiah sama untuk semua barang" },
        ],
      },
      {
        type: "video",
        comp: "UtilitasMarginal",
        title: "Video: Utilitas Marginal yang Menurun",
        caption: "Animasi bagaimana tambahan kepuasan menyusut tiap unit, sementara utilitas total tetap naik lalu mendatar.",
      },
      { type: "widget", widget: "KalkulatorUtilitas" },
      {
        type: "chart",
        variant: "area",
        title: "Utilitas Total Naik Melambat (ilustrasi)",
        unit: "util",
        source: "ilustrasi pola umum",
        note: "Utilitas total terus naik selama MU positif, tetapi kenaikannya makin kecil tiap unit.",
        data: [
          { label: "Unit 1", value: 10, color: "#10b981" },
          { label: "Unit 2", value: 18, color: "#34d399" },
          { label: "Unit 3", value: 24, color: "#fbbf24" },
          { label: "Unit 4", value: 28, color: "#fb923c" },
          { label: "Unit 5", value: 30, color: "#ef4444" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Barang X memberi MU 20 util dengan harga Rp4.000. Berapa utilitas marginal per Rp1.000?",
        answer: 5,
        tolerance: 0,
        suffix: " util",
        solution: "MU per Rp1.000 = 20 util / 4 (ribu rupiah) = <strong>5 util</strong> per Rp1.000. Bandingkan angka ini antarbarang untuk mencari keseimbangan.",
        hint: "Bagi utilitas marginal dengan harga dalam satuan ribuan rupiah.",
      },
      {
        type: "takeaways",
        items: [
          "Utilitas total = jumlah seluruh kepuasan; utilitas marginal = tambahan kepuasan per unit.",
          "MU = perubahan TU dibagi perubahan jumlah unit.",
          "Hukum utilitas marginal menurun: tambahan kepuasan menyusut tiap unit berikutnya.",
          "Keseimbangan konsumen tercapai saat MUx/Px = MUy/Py.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Utilitas marginal adalah?",
            options: ["Total seluruh kepuasan", "Tambahan kepuasan dari satu unit tambahan", "Biaya satu unit", "Harga rata-rata"],
            answer: 1,
            explain: "MU adalah tambahan kepuasan saat konsumsi bertambah satu unit.",
          },
          {
            q: "Utilitas total mencapai maksimum ketika?",
            options: ["MU paling tinggi", "MU = 0", "MU negatif", "Harga = 0"],
            answer: 1,
            explain: "Saat MU = 0, tidak ada lagi tambahan kepuasan, sehingga TU di puncaknya.",
          },
          {
            q: "Hukum utilitas marginal yang menurun menyatakan bahwa?",
            options: ["MU naik tiap unit", "MU cenderung turun tiap unit tambahan", "TU selalu tetap", "Harga selalu naik"],
            answer: 1,
            explain: "Tambahan kepuasan menyusut seiring bertambahnya unit yang dikonsumsi.",
          },
          {
            q: "TU naik dari 18 (3 unit) ke 24 (4 unit). MU unit ke-4?",
            options: ["6", "24", "42", "4"],
            answer: 0,
            explain: "(24 - 18) / (4 - 3) = 6 util.",
          },
          {
            q: "Keseimbangan konsumen tercapai saat?",
            options: ["MU semua barang nol", "Harga semua barang sama", "MU per rupiah sama untuk semua barang", "Pendapatan habis untuk satu barang"],
            answer: 2,
            explain: "Kepuasan maksimum tercapai ketika MUx/Px = MUy/Py.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "utilitas-dan-pilihan",
    levelId: "elastisitas",
    order: 4,
    title: "Utilitas dan Pilihan",
    summary: "Bagaimana konsumen memaksimalkan kepuasan dengan anggaran terbatas, dan mengapa air murah sementara berlian mahal (paradoks nilai).",
    durationMin: 13,
    tags: ["utilitas", "anggaran", "pilihan", "paradoks-nilai"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap konsumen menghadapi <strong>anggaran terbatas</strong>. Tujuannya memilih kombinasi barang yang memberi kepuasan total tertinggi tanpa melebihi anggaran. Kuncinya membandingkan <strong>utilitas marginal per rupiah</strong> dari tiap barang, bukan sekadar utilitas total atau harga sendiri-sendiri.",
      },
      {
        type: "paragraph",
        html: "Aturannya: belanjakan rupiah berikutnya pada barang dengan MU per rupiah tertinggi. Lanjutkan menggeser belanja sampai MU per rupiah semua barang sama, yaitu MUx/Px = MUy/Py. Saat itulah anggaran terpakai paling efisien.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aturan memaksimalkan kepuasan",
        html: "Kepuasan maksimum dengan anggaran terbatas tercapai ketika <strong>utilitas marginal per rupiah sama untuk semua barang</strong> dan seluruh anggaran habis terpakai.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Paradoks nilai air-berlian",
        html: "Air sangat penting untuk hidup namun harganya murah, sedangkan berlian tidak vital namun mahal. Penjelasannya: harga ditentukan oleh <strong>utilitas marginal</strong>, bukan utilitas total. Karena air melimpah, MU unit terakhirnya rendah; karena berlian langka, MU-nya tinggi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Kelangkaan menggerakkan harga",
        html: "Bukan total manfaat yang menentukan harga, melainkan manfaat dari satu unit tambahan. Semakin langka suatu barang, semakin tinggi utilitas marginal dan harganya.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Paradoks Nilai: Air vs Berlian (ilustrasi)",
        unit: "util",
        source: "ilustrasi pola umum",
        note: "Air memiliki utilitas total tinggi tetapi utilitas marginal rendah; berlian sebaliknya.",
        data: [
          { label: "Air: utilitas total", value: 100, color: "#3b82f6" },
          { label: "Air: utilitas marginal", value: 2, color: "#93c5fd" },
          { label: "Berlian: utilitas total", value: 20, color: "#8b5cf6" },
          { label: "Berlian: utilitas marginal", value: 50, color: "#c4b5fd" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membagi anggaran jajan",
        html: "Beni punya Rp10.000. Camilan memberi MU 40 util seharga Rp2.000 (20 util per Rp1.000), sedangkan minuman memberi MU 30 util seharga Rp1.000 (30 util per Rp1.000). Karena minuman memberi MU per rupiah lebih tinggi, Beni sebaiknya menambah minuman dulu. Ia terus menggeser belanja sampai <strong>MU per rupiah keduanya sama</strong>, di situ kepuasannya maksimum.",
      },
      {
        type: "calcExercise",
        prompt: "Sepotong roti memberi 30 util dan berharga Rp6.000. Berapa utilitas marginal per Rp1.000 yang dibelanjakan?",
        answer: 5,
        tolerance: 0,
        suffix: " util",
        solution: "MU per Rp1.000 = 30 util / 6 (ribu rupiah) = <strong>5 util</strong> per Rp1.000.",
        hint: "Bagi utilitas marginal dengan harga dalam satuan ribuan rupiah.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri berikut menggambarkan air atau berlian?",
        buckets: ["Air", "Berlian"],
        items: [
          { text: "Melimpah di alam", bucket: "Air" },
          { text: "Utilitas marginal rendah", bucket: "Air" },
          { text: "Langka dan sulit didapat", bucket: "Berlian" },
          { text: "Harga per unit sangat tinggi", bucket: "Berlian" },
        ],
      },
      { type: "widget", widget: "KalkulatorUtilitas" },
      {
        type: "chart",
        variant: "bar",
        title: "Membandingkan MU per Rupiah (ilustrasi)",
        unit: "util per Rp1.000",
        source: "ilustrasi pola umum",
        note: "Konsumen menambah belanja pada barang dengan MU per rupiah tertinggi sampai semuanya setara.",
        data: [
          { label: "Camilan", value: 20, color: "#fb923c" },
          { label: "Minuman", value: 30, color: "#10b981" },
          { label: "Roti", value: 5, color: "#ef4444" },
          { label: "Buah", value: 25, color: "#34d399" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Barang A: MU 60 util, harga Rp3.000. Barang B: MU 40 util, harga Rp1.000. Selisih MU per Rp1.000 (B dikurangi A)?",
        answer: 20,
        tolerance: 0,
        suffix: " util",
        solution: "A: 60/3 = 20 util per Rp1.000. B: 40/1 = 40 util per Rp1.000. Selisih = 40 - 20 = <strong>20 util</strong>. Karena B lebih tinggi, geser belanja ke barang B.",
        hint: "Hitung MU per Rp1.000 tiap barang, lalu kurangkan nilai A dari nilai B.",
      },
      {
        type: "takeaways",
        items: [
          "Konsumen memaksimalkan kepuasan dengan menyamakan MU per rupiah semua barang.",
          "Aturan: MUx/Px = MUy/Py dengan seluruh anggaran terpakai.",
          "Harga ditentukan oleh utilitas marginal, bukan utilitas total.",
          "Paradoks nilai: air murah karena melimpah (MU rendah), berlian mahal karena langka (MU tinggi).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Konsumen memaksimalkan kepuasan dengan anggaran terbatas ketika?",
            options: ["Membeli barang termurah saja", "MU per rupiah sama untuk semua barang", "Utilitas total tiap barang nol", "Menghabiskan untuk satu barang"],
            answer: 1,
            explain: "Syaratnya MUx/Px = MUy/Py dengan anggaran habis terpakai.",
          },
          {
            q: "Paradoks nilai menjelaskan bahwa air murah karena?",
            options: ["Tidak berguna", "Melimpah sehingga utilitas marginalnya rendah", "Utilitas totalnya rendah", "Tidak ada permintaan"],
            answer: 1,
            explain: "Air melimpah, sehingga MU unit terakhirnya rendah meski utilitas totalnya tinggi.",
          },
          {
            q: "Harga sebuah barang lebih ditentukan oleh?",
            options: ["Utilitas total", "Utilitas marginal", "Biaya iklan", "Jumlah penjual"],
            answer: 1,
            explain: "Harga mencerminkan manfaat dari satu unit tambahan, yaitu utilitas marginal.",
          },
          {
            q: "Barang A: MU per rupiah 6; Barang B: MU per rupiah 4. Konsumen sebaiknya?",
            options: ["Menambah barang B", "Menambah barang A", "Berhenti membeli", "Membeli sama banyak"],
            answer: 1,
            explain: "Geser belanja ke barang dengan MU per rupiah lebih tinggi, yaitu barang A.",
          },
          {
            q: "Berlian mahal terutama karena?",
            options: ["Utilitas totalnya tinggi", "Langka sehingga utilitas marginalnya tinggi", "Dibutuhkan untuk hidup", "Tidak punya substitusi sama sekali"],
            answer: 1,
            explain: "Kelangkaan membuat utilitas marginal berlian tinggi, sehingga harganya mahal.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kurva-indiferensi-garis-anggaran",
    levelId: "elastisitas",
    order: 5,
    title: "Kurva Indiferensi & Garis Anggaran",
    summary: "Pendekatan ordinal perilaku konsumen: kurva indiferensi menggambarkan kepuasan yang sama, garis anggaran membatasi pilihan, dan titik optimum ada di persinggungan keduanya.",
    durationMin: 14,
    tags: ["kurva indiferensi", "garis anggaran", "konsumen", "MRS"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain mengukur utilitas dengan angka (pendekatan kardinal), ekonom memakai pendekatan <strong>ordinal</strong>: konsumen cukup mampu <strong>mengurutkan</strong> kombinasi barang dari yang lebih disukai ke yang kurang disukai. Alatnya adalah <strong>kurva indiferensi</strong>, yaitu kumpulan kombinasi dua barang yang memberi <strong>tingkat kepuasan yang sama</strong>.",
      },
      {
        type: "paragraph",
        html: "Pilihan konsumen dibatasi oleh <strong>garis anggaran</strong>, yaitu semua kombinasi barang yang tepat menghabiskan pendapatannya pada harga yang berlaku. Kemiringan garis anggaran sama dengan <strong>rasio harga</strong> kedua barang. Kepuasan tertinggi yang masih terjangkau tercapai di titik <strong>persinggungan (tangensi)</strong> garis anggaran dengan kurva indiferensi.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Titik optimum: MRS = rasio harga",
        html: "Di titik optimum, kemiringan kurva indiferensi, yaitu <strong>tingkat substitusi marginal (MRS)</strong>, sama dengan <strong>rasio harga Px/Py</strong>. Pada titik itu konsumen tidak bisa lagi menambah kepuasan dengan menggeser belanja antar barang.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ciri kurva indiferensi",
        html: "1) <strong>Menurun</strong> dari kiri atas ke kanan bawah; 2) <strong>Cembung</strong> ke titik asal (karena MRS menurun); 3) <strong>Tidak saling berpotongan</strong>; 4) Kurva yang <strong>lebih jauh</strong> dari titik asal berarti kepuasan lebih tinggi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Apa itu MRS?",
        html: "<strong>MRS</strong> adalah jumlah barang Y yang rela dilepas konsumen untuk menambah satu unit barang X tanpa mengubah kepuasan. MRS cenderung menurun: makin banyak X dimiliki, makin sedikit Y yang rela dikorbankan demi tambahan X.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Garis Anggaran: Pendapatan Rp120 ribu (Px Rp12 ribu, Py Rp8 ribu)",
        unit: "unit barang Y",
        source: "ilustrasi edukatif",
        note: "Tiap menambah 1 unit X (Rp12 ribu) berarti melepas 1,5 unit Y (Rp8 ribu). Kemiringan 1,5 sama dengan rasio harga Px/Py.",
        data: [
          { label: "0 X", value: 15, color: "#8b5cf6" },
          { label: "2 X", value: 12, color: "#8b5cf6" },
          { label: "4 X", value: 9, color: "#8b5cf6" },
          { label: "6 X", value: 6, color: "#8b5cf6" },
          { label: "8 X", value: 3, color: "#8b5cf6" },
          { label: "10 X", value: 0, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih makanan dan minuman",
        html: "Sari punya Rp120.000. Harga sepiring makanan (X) Rp12.000 dan segelas minuman (Y) Rp8.000. Jika ia membeli <strong>4 makanan</strong> (Rp48.000), tersisa Rp72.000 untuk <strong>9 minuman</strong>. Kombinasi (4, 9) tepat menghabiskan anggaran, jadi berada di garis anggaran. Kepuasan maksimum tercapai bila pada titik itu MRS-nya sama dengan rasio harga 12.000/8.000 = 1,5.",
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya kurva indiferensi (1881-1906)",
        html: "Konsep kurva indiferensi pertama digambar oleh ekonom Inggris <strong>Francis Y. Edgeworth</strong> dalam 'Mathematical Psychics' (<strong>1881</strong>). Ekonom Italia <strong>Vilfredo Pareto</strong> mengembangkannya dalam 'Manuale di economia politica' (<strong>1906</strong>) dengan menegaskan bahwa konsumen tidak perlu mengukur kepuasan dalam angka, cukup mengurutkan preferensi. Pendekatan ordinal inilah yang kini menjadi dasar teori perilaku konsumen modern.",
      },
      {
        type: "calcExercise",
        prompt: "Pendapatan Rp120.000, harga makanan (X) Rp12.000, harga minuman (Y) Rp8.000. Jika membeli 4 makanan, berapa unit minuman maksimum yang masih terbeli?",
        answer: 9,
        tolerance: 0,
        suffix: " unit",
        solution: "Sisa anggaran = 120.000 - (4 x 12.000) = 120.000 - 48.000 = 72.000. Jumlah minuman = 72.000 / 8.000 = <strong>9 unit</strong>.",
        hint: "Kurangi anggaran dengan total belanja makanan, lalu bagi dengan harga minuman.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Kurva indiferensi", right: "Kombinasi barang dengan kepuasan yang sama" },
          { left: "Garis anggaran", right: "Kombinasi barang yang tepat menghabiskan pendapatan" },
          { left: "MRS", right: "Jumlah Y yang rela dilepas demi 1 unit X" },
          { left: "Titik optimum", right: "Persinggungan garis anggaran dengan kurva indiferensi tertinggi" },
        ],
      },
      {
        type: "video",
        comp: "UtilitasMarginal",
        title: "Video: Utilitas Marginal yang Menurun",
        caption: "MRS yang menurun pada kurva indiferensi sejalan dengan hukum utilitas marginal yang menurun.",
      },
      { type: "widget", widget: "KalkulatorUtilitas" },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini benar atau salah tentang kurva indiferensi?",
        buckets: ["Benar", "Salah"],
        items: [
          { text: "Kurva indiferensi melandai turun ke kanan", bucket: "Benar" },
          { text: "Dua kurva indiferensi bisa saling berpotongan", bucket: "Salah" },
          { text: "Kurva yang lebih jauh dari titik asal berarti kepuasan lebih tinggi", bucket: "Benar" },
          { text: "Kemiringan garis anggaran sama dengan rasio harga", bucket: "Benar" },
          { text: "MRS biasanya naik saat jumlah X bertambah", bucket: "Salah" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Harga barang X Rp12.000 dan harga barang Y Rp8.000. Berapa rasio harga Px/Py (kemiringan garis anggaran)?",
        answer: 1.5,
        tolerance: 0.01,
        solution: "Px/Py = 12.000 / 8.000 = <strong>1,5</strong>. Artinya untuk menambah 1 unit X, konsumen melepas 1,5 unit Y.",
        hint: "Bagi harga barang X dengan harga barang Y.",
      },
      {
        type: "takeaways",
        items: [
          "Kurva indiferensi memuat kombinasi barang dengan kepuasan yang sama (pendekatan ordinal).",
          "Garis anggaran membatasi pilihan; kemiringannya sama dengan rasio harga Px/Py.",
          "Titik optimum konsumen ada di persinggungan: MRS = Px/Py.",
          "Kurva indiferensi menurun, cembung ke titik asal, dan tidak berpotongan.",
          "Konsep ini dirintis Edgeworth (1881) dan dikembangkan Pareto (1906).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kurva indiferensi menunjukkan?",
            options: ["Kombinasi barang dengan biaya sama", "Kombinasi barang dengan kepuasan yang sama", "Harga semua barang", "Jumlah penjual"],
            answer: 1,
            explain: "Setiap titik di satu kurva indiferensi memberi tingkat kepuasan yang sama.",
          },
          {
            q: "Kemiringan garis anggaran sama dengan?",
            options: ["Rasio harga Px/Py", "Jumlah pendapatan", "Tingkat pajak", "Selisih utilitas"],
            answer: 0,
            explain: "Garis anggaran memiliki kemiringan sebesar rasio harga kedua barang.",
          },
          {
            q: "Titik optimum konsumen tercapai ketika?",
            options: ["MRS = Px/Py", "Anggaran tidak terpakai", "Utilitas nol", "MRS = 0"],
            answer: 0,
            explain: "Pada persinggungan, tingkat substitusi marginal sama dengan rasio harga.",
          },
          {
            q: "Manakah ciri kurva indiferensi yang BENAR?",
            options: ["Saling berpotongan", "Naik ke kanan", "Tidak saling berpotongan dan cembung ke titik asal", "Selalu garis lurus vertikal"],
            answer: 2,
            explain: "Kurva indiferensi tidak berpotongan dan cembung ke titik asal karena MRS menurun.",
          },
          {
            q: "Pendapatan Rp120.000, harga X Rp12.000. Berapa maksimum unit X jika hanya membeli X?",
            options: ["8", "10", "12", "15"],
            answer: 1,
            explain: "120.000 / 12.000 = 10 unit X.",
          },
        ],
      },
    ],
  },
];
