import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "produksi-dan-biaya",
    levelId: "produksi",
    order: 1,
    title: "Produksi & Biaya",
    summary: "Bagaimana perusahaan mengubah input menjadi output, dan struktur biayanya. Dengan video & simulator biaya.",
    durationMin: 14,
    tags: ["produksi", "biaya", "skala ekonomi"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan mengubah <strong>input</strong> (tenaga kerja, bahan, modal) menjadi <strong>output</strong>. Biayanya terbagi menjadi <strong>biaya tetap</strong> (tidak berubah dengan produksi, mis. sewa) dan <strong>biaya variabel</strong> (naik seiring produksi, mis. bahan baku).",
      },
      {
        type: "video",
        comp: "BiayaProduksi",
        title: "Video: Kurva Biaya Produksi",
        caption: "Animasi kurva biaya rata-rata (ATC) berbentuk U dan biaya marginal (MC).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Skala ekonomi",
        html: "Saat produksi naik, biaya tetap tersebar ke lebih banyak unit, sehingga <strong>biaya rata-rata turun</strong>. Inilah skala ekonomi. Tetapi pada titik tertentu biaya bisa naik lagi (skala disekonomi).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur biaya tetap, biaya variabel per unit, dan jumlah produksi untuk melihat biaya rata-rata per unit (ATC).",
      },
      { type: "widget", widget: "SimulatorBiayaProduksi" },
      {
        type: "chart",
        variant: "line",
        title: "Biaya Rata-Rata Turun saat Produksi Naik (ilustrasi)",
        unit: "Rp ribu per unit",
        source: "ilustrasi edukatif",
        note: "Biaya tetap dibagi ke lebih banyak unit, sehingga biaya rata-rata menurun (skala ekonomi).",
        data: [
          { label: "100 unit", value: 120, color: "#6366f1" },
          { label: "300 unit", value: 73, color: "#6366f1" },
          { label: "600 unit", value: 57, color: "#6366f1" },
          { label: "1000 unit", value: 50, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik roti",
        html: "Sebuah pabrik roti menanggung biaya tetap Rp10 juta per bulan (sewa & mesin) dan biaya variabel Rp5.000 per roti. Memproduksi 1.000 roti: biaya total Rp15 juta, biaya rata-rata Rp15.000. Memproduksi 5.000 roti: biaya total Rp35 juta, biaya rata-rata turun ke Rp7.000. Produksi lebih besar menurunkan biaya per unit.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya tetap Rp10 juta, biaya variabel Rp5.000/unit, produksi 1.000 unit. Berapa biaya rata-rata per unit (Rp)?",
        answer: 15000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Total = Rp10 juta + (Rp5.000 x 1.000) = Rp15 juta. Rata-rata = Rp15 juta / 1.000 = <strong>Rp15.000</strong>.",
        hint: "Total biaya dibagi jumlah unit.",
      },
      {
        type: "classifyExercise",
        prompt: "Biaya ini termasuk tetap atau variabel?",
        buckets: ["Biaya tetap", "Biaya variabel"],
        items: [
          { text: "Sewa pabrik bulanan", bucket: "Biaya tetap" },
          { text: "Bahan baku per produk", bucket: "Biaya variabel" },
          { text: "Gaji tetap manajer", bucket: "Biaya tetap" },
          { text: "Upah lembur per jam produksi", bucket: "Biaya variabel" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Rincian Biaya pada 5.000 Roti (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Biaya variabel (Rp25 juta) jauh lebih besar dari biaya tetap (Rp10 juta) saat produksi tinggi, tetapi biaya tetap per unit jadi sangat kecil.",
        data: [
          { label: "Biaya tetap", value: 10, color: "#f59e0b" },
          { label: "Biaya variabel", value: 25, color: "#6366f1" },
          { label: "Biaya total", value: 35, color: "#10b981" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya tetap Rp10 juta, biaya variabel Rp5.000/unit, produksi 5.000 unit. Berapa biaya rata-rata per unit (Rp)?",
        answer: 7000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Total = Rp10 juta + (Rp5.000 x 5.000) = Rp35 juta. Rata-rata = Rp35 juta / 5.000 = <strong>Rp7.000</strong>. Lebih rendah dari saat 1.000 unit (skala ekonomi).",
        hint: "Hitung biaya total dulu, lalu bagi jumlah unit.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah biaya dengan contohnya.",
        pairs: [
          { left: "Biaya tetap", right: "Sewa pabrik bulanan" },
          { left: "Biaya variabel", right: "Bahan baku per roti" },
          { left: "Biaya total", right: "Biaya tetap + biaya variabel" },
          { left: "Biaya rata-rata", right: "Biaya total dibagi jumlah unit" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Biaya tetap tidak berubah dengan produksi; biaya variabel berubah.",
          "Biaya total = biaya tetap + biaya variabel.",
          "Biaya rata-rata (ATC) sering berbentuk U.",
          "Skala ekonomi: biaya per unit turun saat produksi membesar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Biaya tetap adalah biaya yang?",
            options: ["Berubah dengan produksi", "Tidak berubah dengan jumlah produksi", "Selalu nol", "Sama dengan harga"],
            answer: 1,
            explain: "Biaya tetap seperti sewa tidak berubah walau produksi naik atau turun.",
          },
          {
            q: "Skala ekonomi terjadi saat?",
            options: ["Biaya per unit naik", "Biaya per unit turun seiring produksi membesar", "Produksi berhenti", "Harga naik"],
            answer: 1,
            explain: "Biaya tetap tersebar ke lebih banyak unit, biaya rata-rata turun.",
          },
          {
            q: "Bahan baku per produk termasuk?",
            options: ["Biaya tetap", "Biaya variabel", "Biaya peluang", "Pajak"],
            answer: 1,
            explain: "Bahan baku naik seiring jumlah produksi, jadi biaya variabel.",
          },
          {
            q: "FC Rp20 jt, VC Rp10 rb/unit, 2.000 unit. ATC?",
            options: ["Rp20.000", "Rp10.000", "Rp30.000", "Rp15.000"],
            answer: 0,
            explain: "Total = 20jt + 20jt = 40jt; /2.000 = Rp20.000.",
          },
          {
            q: "Biaya total adalah?",
            options: ["Hanya biaya tetap", "Biaya tetap + biaya variabel", "Hanya biaya variabel", "Harga jual"],
            answer: 1,
            explain: "Biaya total menjumlahkan biaya tetap dan variabel.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "fungsi-produksi",
    levelId: "produksi",
    order: 2,
    title: "Fungsi Produksi",
    summary: "Hubungan antara input dan output, produk marginal, hukum hasil yang semakin berkurang, serta beda jangka pendek dan panjang.",
    durationMin: 13,
    tags: ["fungsi produksi", "produk marginal", "diminishing returns"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Fungsi produksi</strong> menggambarkan hubungan antara jumlah <strong>input</strong> (mis. pekerja) dan <strong>output</strong> yang dihasilkan. Saat satu input ditambah sementara input lain tetap, kita dapat menghitung <strong>produk marginal (MP)</strong>, yaitu tambahan output dari menambah satu unit input.",
      },
      {
        type: "paragraph",
        html: "Pada awalnya menambah pekerja bisa menaikkan output dengan cepat karena pembagian tugas. Namun di titik tertentu, tambahan output mulai mengecil. Inilah <strong>hukum hasil yang semakin berkurang (diminishing returns)</strong>: dengan input tetap yang terbatas (mis. mesin), setiap pekerja tambahan memberi kontribusi yang makin kecil.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Produk marginal",
        html: "MP = perubahan output dibagi perubahan input. Jika output naik dari 30 ke 40 unit karena menambah 1 pekerja, maka MP = 10 unit per pekerja.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Jangka pendek vs jangka panjang",
        html: "Dalam <strong>jangka pendek</strong>, setidaknya satu input bersifat tetap (mis. ukuran pabrik). Dalam <strong>jangka panjang</strong>, semua input bisa diubah, termasuk membangun pabrik baru. Diminishing returns adalah konsep jangka pendek.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati salah tafsir",
        html: "Produk marginal yang menurun <strong>bukan berarti output total turun</strong>. Output total masih bisa naik, tetapi naiknya makin lambat selama MP masih positif.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Produk Marginal per Pekerja (ilustrasi)",
        unit: "unit per pekerja",
        source: "ilustrasi edukatif",
        note: "MP naik dahulu lalu menurun mulai pekerja ke-4: inilah hukum hasil yang semakin berkurang.",
        data: [
          { label: "Pekerja 1", value: 8, color: "#10b981" },
          { label: "Pekerja 2", value: 10, color: "#10b981" },
          { label: "Pekerja 3", value: 12, color: "#10b981" },
          { label: "Pekerja 4", value: 10, color: "#f59e0b" },
          { label: "Pekerja 5", value: 6, color: "#f59e0b" },
          { label: "Pekerja 6", value: 2, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Warung mie ayam",
        html: "Sebuah warung punya 1 kompor (input tetap). Dengan 1 pekerja, output 8 porsi/jam. Pekerja ke-2 menambah 10 porsi (total 18), pekerja ke-3 menambah 12 porsi (total 30). Tetapi pekerja ke-4 hanya menambah 10 porsi (total 40), dan pekerja ke-5 menambah 6 porsi (total 46) karena mereka berebut satu kompor. Produk marginal mulai turun sejak pekerja ke-4.",
      },
      {
        type: "calcExercise",
        prompt: "Output naik dari 30 porsi menjadi 40 porsi setelah menambah 1 pekerja. Berapa produk marginal pekerja itu (porsi)?",
        answer: 10,
        tolerance: 0,
        suffix: " porsi",
        solution: "MP = perubahan output / perubahan input = (40 - 30) / 1 = <strong>10 porsi</strong> per pekerja.",
        hint: "Selisih output dibagi tambahan pekerja.",
      },
      {
        type: "classifyExercise",
        prompt: "Dalam jangka pendek, input ini tetap atau variabel?",
        buckets: ["Input tetap", "Input variabel"],
        items: [
          { text: "Ukuran gedung pabrik", bucket: "Input tetap" },
          { text: "Jumlah pekerja harian", bucket: "Input variabel" },
          { text: "Mesin produksi utama", bucket: "Input tetap" },
          { text: "Bahan baku yang dipakai", bucket: "Input variabel" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Output Total Naik Makin Lambat (ilustrasi)",
        unit: "porsi per jam",
        source: "ilustrasi edukatif",
        note: "Output total terus naik (8, 18, 30, 40, 46) tetapi tambahannya mengecil sejak pekerja ke-4: hasil yang semakin berkurang.",
        data: [
          { label: "1 pekerja", value: 8, color: "#10b981" },
          { label: "2 pekerja", value: 18, color: "#10b981" },
          { label: "3 pekerja", value: 30, color: "#10b981" },
          { label: "4 pekerja", value: 40, color: "#f59e0b" },
          { label: "5 pekerja", value: 46, color: "#f59e0b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Output total naik dari 40 porsi (4 pekerja) menjadi 46 porsi (5 pekerja). Berapa produk marginal pekerja ke-5 (porsi)?",
        answer: 6,
        tolerance: 0,
        suffix: " porsi",
        solution: "MP = (46 - 40) / 1 = <strong>6 porsi</strong>. Lebih kecil dari MP pekerja ke-3 (12 porsi), tanda diminishing returns.",
        hint: "Selisih output total dibagi tambahan pekerja.",
      },
      {
        type: "takeaways",
        items: [
          "Fungsi produksi menghubungkan input dengan output.",
          "Produk marginal = tambahan output dari satu unit input tambahan.",
          "Hukum hasil yang semakin berkurang: MP menurun saat input tetap terbatas.",
          "Jangka pendek punya input tetap; jangka panjang semua input variabel.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Produk marginal adalah?",
            options: ["Total output", "Tambahan output dari satu unit input tambahan", "Harga output", "Biaya per unit"],
            answer: 1,
            explain: "MP mengukur tambahan output dari menambah satu unit input.",
          },
          {
            q: "Hukum hasil yang semakin berkurang menyatakan?",
            options: ["Output total selalu turun", "Tambahan output mengecil saat input tetap terbatas", "Biaya selalu naik", "Harga selalu turun"],
            answer: 1,
            explain: "Dengan input tetap, setiap input variabel tambahan memberi kontribusi makin kecil.",
          },
          {
            q: "Output naik 18 ke 30 karena 1 pekerja tambahan. MP-nya?",
            options: ["12", "30", "18", "48"],
            answer: 0,
            explain: "MP = (30 - 18) / 1 = 12.",
          },
          {
            q: "Dalam jangka panjang?",
            options: ["Semua input tetap", "Semua input bisa diubah", "Output selalu nol", "Tidak ada biaya"],
            answer: 1,
            explain: "Jangka panjang berarti semua input, termasuk pabrik, bisa diubah.",
          },
          {
            q: "MP menurun namun masih positif. Output total?",
            options: ["Pasti turun", "Tetap naik tapi makin lambat", "Selalu nol", "Tidak berubah"],
            answer: 1,
            explain: "Selama MP positif, output total tetap naik walau melambat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "biaya-marginal-rata-rata",
    levelId: "produksi",
    order: 3,
    title: "Biaya Marginal & Rata-Rata",
    summary: "Memahami MC, ATC, AVC, AFC dan hubungannya, serta mengapa MC selalu memotong ATC di titik minimumnya.",
    durationMin: 14,
    tags: ["biaya marginal", "ATC", "AVC", "AFC"],
    blocks: [
      {
        type: "paragraph",
        html: "Ada empat ukuran biaya penting per unit. <strong>MC (biaya marginal)</strong> adalah tambahan biaya untuk memproduksi satu unit lagi. <strong>ATC (biaya total rata-rata)</strong> = biaya total dibagi jumlah unit. <strong>AVC (biaya variabel rata-rata)</strong> dan <strong>AFC (biaya tetap rata-rata)</strong> membagi masing-masing biaya variabel dan tetap dengan jumlah unit.",
      },
      {
        type: "paragraph",
        html: "Hubungannya: <strong>ATC = AVC + AFC</strong>. AFC selalu menurun saat produksi naik karena biaya tetap tersebar ke lebih banyak unit. ATC biasanya berbentuk U: turun dahulu lalu naik kembali.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Mengapa MC memotong ATC di titik minimum",
        html: "Selama <strong>MC &lt; ATC</strong>, menambah unit menarik rata-rata turun. Saat <strong>MC &gt; ATC</strong>, rata-rata terdorong naik. Maka ATC mencapai titik terendah tepat ketika <strong>MC = ATC</strong>. Sama seperti nilai ujian: jika nilai baru di bawah rata-rata, rata-rata turun.",
      },
      {
        type: "callout",
        tone: "info",
        title: "ATC = AVC + AFC",
        html: "Karena AFC terus menurun, jarak antara ATC dan AVC makin menyempit saat produksi bertambah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur biaya tetap, biaya variabel per unit, dan jumlah produksi untuk melihat bagaimana ATC berubah.",
      },
      { type: "widget", widget: "SimulatorBiayaProduksi" },
      {
        type: "chart",
        variant: "line",
        title: "ATC Berbentuk U (ilustrasi)",
        unit: "Rp ribu per unit",
        source: "ilustrasi edukatif",
        note: "ATC turun lalu naik; titik terendah sekitar 5 unit, tepat saat MC memotong ATC.",
        data: [
          { label: "1 unit", value: 150, color: "#6366f1" },
          { label: "2 unit", value: 95, color: "#6366f1" },
          { label: "3 unit", value: 73, color: "#6366f1" },
          { label: "4 unit", value: 65, color: "#6366f1" },
          { label: "5 unit", value: 64, color: "#10b981" },
          { label: "6 unit", value: 67, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Bengkel sablon",
        html: "Biaya tetap Rp100 ribu. Saat produksi 4 kaos, biaya variabel Rp160 ribu, jadi biaya total Rp260 ribu. Maka AFC = Rp25 ribu, AVC = Rp40 ribu, dan ATC = Rp65 ribu. Menaikkan produksi ke 5 kaos menambah biaya total menjadi Rp320 ribu, sehingga MC unit ke-5 = Rp60 ribu. Karena MC (60) masih di bawah ATC (65), ATC turun menjadi Rp64 ribu.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya total naik dari Rp220 ribu (3 unit) menjadi Rp260 ribu (4 unit). Berapa biaya marginal unit ke-4 (Rp ribu)?",
        answer: 40,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "MC = perubahan biaya total / perubahan unit = (260 - 220) / 1 = <strong>Rp40 ribu</strong>.",
        hint: "Selisih biaya total dibagi tambahan unit.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah biaya dengan definisinya.",
        pairs: [
          { left: "MC", right: "Tambahan biaya untuk satu unit lagi" },
          { left: "ATC", right: "Biaya total dibagi jumlah unit" },
          { left: "AVC", right: "Biaya variabel dibagi jumlah unit" },
          { left: "AFC", right: "Biaya tetap dibagi jumlah unit" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "AFC Selalu Menurun saat Produksi Naik (ilustrasi)",
        unit: "Rp ribu per unit",
        source: "ilustrasi edukatif",
        note: "Biaya tetap Rp100 ribu dibagi jumlah unit: AFC turun terus (100, 50, 33, 25, 20). Inilah sebab jarak ATC dan AVC menyempit.",
        data: [
          { label: "1 unit", value: 100, color: "#f59e0b" },
          { label: "2 unit", value: 50, color: "#f59e0b" },
          { label: "3 unit", value: 33, color: "#f59e0b" },
          { label: "4 unit", value: 25, color: "#f59e0b" },
          { label: "5 unit", value: 20, color: "#f59e0b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya tetap Rp100 ribu, biaya variabel Rp160 ribu, produksi 4 unit. Berapa ATC per unit (Rp ribu)?",
        answer: 65,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "Biaya total = 100 + 160 = Rp260 ribu. ATC = 260 / 4 = <strong>Rp65 ribu</strong> (sama dengan AFC Rp25 ribu + AVC Rp40 ribu).",
        hint: "ATC = biaya total dibagi jumlah unit, atau AFC + AVC.",
      },
      {
        type: "classifyExercise",
        prompt: "Saat produksi bertambah, biaya rata-rata ini cenderung naik atau turun?",
        buckets: ["Cenderung turun", "Bisa naik kembali"],
        items: [
          { text: "AFC (biaya tetap rata-rata)", bucket: "Cenderung turun" },
          { text: "ATC setelah melewati titik minimum", bucket: "Bisa naik kembali" },
          { text: "AFC saat unit makin banyak", bucket: "Cenderung turun" },
          { text: "ATC di sisi kanan kurva U", bucket: "Bisa naik kembali" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "MC adalah tambahan biaya untuk satu unit lagi.",
          "ATC = AVC + AFC; AFC selalu menurun saat produksi naik.",
          "ATC biasanya berbentuk U.",
          "MC memotong ATC dan AVC tepat di titik minimumnya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Biaya marginal (MC) adalah?",
            options: ["Biaya total dibagi unit", "Tambahan biaya untuk satu unit lagi", "Biaya tetap", "Harga jual"],
            answer: 1,
            explain: "MC mengukur tambahan biaya total dari memproduksi satu unit tambahan.",
          },
          {
            q: "Hubungan yang benar adalah?",
            options: ["ATC = AVC - AFC", "ATC = AVC + AFC", "ATC = MC + AFC", "ATC = AVC x AFC"],
            answer: 1,
            explain: "Biaya total rata-rata adalah jumlah AVC dan AFC.",
          },
          {
            q: "MC memotong ATC tepat di?",
            options: ["Titik maksimum ATC", "Titik minimum ATC", "Awal kurva", "Tidak pernah memotong"],
            answer: 1,
            explain: "Saat MC = ATC, rata-rata berhenti turun dan mulai naik, yaitu titik minimum.",
          },
          {
            q: "FC Rp100 rb, 4 unit. Berapa AFC?",
            options: ["Rp25 ribu", "Rp40 ribu", "Rp65 ribu", "Rp100 ribu"],
            answer: 0,
            explain: "AFC = 100 / 4 = Rp25 ribu.",
          },
          {
            q: "Jika MC di bawah ATC, maka ATC?",
            options: ["Naik", "Turun", "Tetap", "Nol"],
            answer: 1,
            explain: "MC di bawah ATC menarik rata-rata turun.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "laba-maksimum",
    levelId: "produksi",
    order: 4,
    title: "Laba Maksimum",
    summary: "Aturan MR = MC untuk keputusan produksi optimal, dan kapan perusahaan sebaiknya berhenti berproduksi (shutdown point).",
    durationMin: 13,
    tags: ["laba maksimum", "MR=MC", "shutdown point"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan ingin memaksimalkan <strong>laba</strong> = penerimaan total (TR) dikurangi biaya total (TC). Aturan kuncinya: produksi pada tingkat di mana <strong>penerimaan marginal (MR) = biaya marginal (MC)</strong>. Di pasar persaingan, harga pasar sama dengan MR, sehingga perusahaan menambah produksi selama harga masih di atas MC.",
      },
      {
        type: "paragraph",
        html: "Jika MC unit berikutnya lebih kecil dari MR, menambah produksi masih menambah laba. Jika MC sudah melebihi MR, unit itu merugikan. Maka titik optimal tercapai tepat saat <strong>MR = MC</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aturan MR = MC",
        html: "Tambah produksi selama <strong>MR &gt; MC</strong>; berhenti menambah saat <strong>MC mulai melebihi MR</strong>. Output optimal ada di titik MR = MC.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Shutdown point",
        html: "Dalam jangka pendek, perusahaan tetap berproduksi selama <strong>harga &ge; AVC</strong> (masih menutup biaya variabel). Jika <strong>harga &lt; AVC</strong>, lebih baik berhenti (shutdown) karena memproduksi malah memperbesar kerugian.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Geser harga pasar dan lihat output optimal serta laba yang dihasilkan saat MR = MC.",
      },
      { type: "widget", widget: "SimulatorLabaMaksimum" },
      {
        type: "chart",
        variant: "bar",
        title: "MC per Unit vs Harga (MR = Rp50 ribu)",
        unit: "Rp ribu per unit",
        source: "ilustrasi edukatif",
        note: "Output optimal di unit ke-4, tempat MC = MR = Rp50 ribu. Unit ke-5 (MC Rp60 ribu) merugikan.",
        data: [
          { label: "Unit 1", value: 20, color: "#10b981" },
          { label: "Unit 2", value: 30, color: "#10b981" },
          { label: "Unit 3", value: 40, color: "#10b981" },
          { label: "Unit 4", value: 50, color: "#10b981" },
          { label: "Unit 5", value: 60, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Produsen kerajinan",
        html: "Harga pasar Rp50 ribu per unit (jadi MR = Rp50 ribu). Biaya marginal naik: unit ke-1 Rp20 ribu, ke-2 Rp30 ribu, ke-3 Rp40 ribu, ke-4 Rp50 ribu, ke-5 Rp60 ribu. Output optimal adalah 4 unit, karena unit ke-4 tepat MC = MR. Biaya total 4 unit Rp150 ribu, sedangkan TR = Rp50 ribu x 4 = Rp200 ribu, sehingga laba = Rp50 ribu. Unit ke-5 tidak dibuat karena MC Rp60 ribu melebihi harga.",
      },
      {
        type: "calcExercise",
        prompt: "Output 4 unit, harga Rp50 ribu per unit, biaya total Rp150 ribu. Berapa laba (Rp ribu)?",
        answer: 50,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "TR = Rp50 ribu x 4 = Rp200 ribu. Laba = TR - TC = 200 - 150 = <strong>Rp50 ribu</strong>.",
        hint: "Laba = penerimaan total dikurangi biaya total.",
      },
      {
        type: "classifyExercise",
        prompt: "Dalam jangka pendek, sebaiknya lanjut produksi atau shutdown?",
        buckets: ["Lanjut produksi", "Shutdown"],
        items: [
          { text: "Harga Rp50 rb, AVC Rp40 rb", bucket: "Lanjut produksi" },
          { text: "Harga Rp30 rb, AVC Rp40 rb", bucket: "Shutdown" },
          { text: "Harga Rp60 rb, AVC Rp45 rb", bucket: "Lanjut produksi" },
          { text: "Harga Rp35 rb, AVC Rp50 rb", bucket: "Shutdown" },
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Titik impas (break-even point)",
        html: "<strong>Titik impas</strong> adalah jumlah unit ketika laba = 0, yaitu saat penerimaan total tepat menutup biaya total. Rumusnya: <strong>BEP = biaya tetap / margin kontribusi per unit</strong>, dengan margin kontribusi = harga jual dikurangi biaya variabel per unit.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulator titik impas",
        html: "Atur biaya tetap, harga jual, dan biaya variabel per unit untuk menemukan berapa unit yang harus terjual agar impas, sekaligus melihat titik shutdown.",
      },
      { type: "widget", widget: "SimulatorTitikImpas" },
      {
        type: "chart",
        variant: "area",
        title: "Penerimaan vs Biaya Total menuju Titik Impas (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Biaya tetap Rp10 juta, harga Rp50 ribu, biaya variabel Rp30 ribu/unit. Impas pada 500 unit, tempat penerimaan total (Rp25 juta) sama dengan biaya total (Rp25 juta).",
        data: [
          { label: "Penerimaan total", value: 25, color: "#10b981" },
          { label: "Biaya total", value: 25, color: "#ef4444" },
          { label: "Biaya tetap", value: 10, color: "#f59e0b" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya tetap Rp10 juta, harga jual Rp50 ribu/unit, biaya variabel Rp30 ribu/unit. Berapa unit titik impas (BEP)?",
        answer: 500,
        tolerance: 0,
        suffix: " unit",
        solution: "Margin kontribusi = Rp50 ribu - Rp30 ribu = Rp20 ribu per unit. BEP = biaya tetap / margin kontribusi = Rp10.000.000 / Rp20.000 = <strong>500 unit</strong>.",
        hint: "Margin kontribusi = harga - biaya variabel; BEP = biaya tetap / margin kontribusi.",
      },
      {
        type: "takeaways",
        items: [
          "Laba = penerimaan total (TR) dikurangi biaya total (TC).",
          "Output optimal ada di titik MR = MC.",
          "Di pasar persaingan, harga = MR.",
          "Shutdown jangka pendek jika harga di bawah AVC.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Aturan output optimal adalah produksi sampai?",
            options: ["MR = MC", "MR = 0", "MC = 0", "Harga = biaya tetap"],
            answer: 0,
            explain: "Laba maksimum tercapai saat penerimaan marginal sama dengan biaya marginal.",
          },
          {
            q: "Di pasar persaingan, MR sama dengan?",
            options: ["Biaya tetap", "Harga pasar", "Biaya variabel", "Nol"],
            answer: 1,
            explain: "Perusahaan persaingan menjual pada harga pasar, sehingga MR = harga.",
          },
          {
            q: "Perusahaan sebaiknya shutdown jangka pendek jika?",
            options: ["Harga di atas AVC", "Harga di bawah AVC", "Laba positif", "MC = MR"],
            answer: 1,
            explain: "Jika harga tak menutup biaya variabel (harga < AVC), berproduksi memperbesar rugi.",
          },
          {
            q: "Harga Rp50 rb, MC unit berikut Rp60 rb. Tambah produksi?",
            options: ["Ya, masih untung", "Tidak, unit itu merugikan", "Wajib", "Tidak bisa ditentukan"],
            answer: 1,
            explain: "MC (60) melebihi MR (50), jadi unit itu menambah rugi.",
          },
          {
            q: "TR Rp200 rb, TC Rp150 rb. Labanya?",
            options: ["Rp350 ribu", "Rp50 ribu", "Rp150 ribu", "Rp0"],
            answer: 1,
            explain: "Laba = 200 - 150 = Rp50 ribu.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "skala-ekonomi-jangka-panjang",
    levelId: "produksi",
    order: 5,
    title: "Skala Ekonomi & Biaya Jangka Panjang",
    summary: "Dalam jangka panjang semua input bisa diubah. Pelajari kurva biaya rata-rata jangka panjang (LRAC), sumber skala ekonomi, dan kapan muncul skala disekonomi.",
    durationMin: 14,
    tags: ["skala ekonomi", "LRAC", "jangka panjang", "skala disekonomi"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam <strong>jangka panjang</strong>, perusahaan bebas mengubah semua input, termasuk ukuran pabrik. Ia dapat memilih skala produksi yang membuat biaya per unit serendah mungkin. Kumpulan biaya rata-rata terendah pada setiap tingkat output membentuk <strong>kurva biaya rata-rata jangka panjang (LRAC)</strong> yang umumnya berbentuk U.",
      },
      {
        type: "paragraph",
        html: "Saat output naik dan biaya per unit <strong>turun</strong>, perusahaan menikmati <strong>skala ekonomi (economies of scale)</strong>. Setelah titik tertentu, biaya per unit bisa <strong>naik kembali</strong> karena pengelolaan jadi rumit; inilah <strong>skala disekonomi (diseconomies of scale)</strong>. Di antara keduanya ada rentang <strong>skala hasil konstan</strong>.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Skala ekonomi vs skala disekonomi",
        html: "<strong>Skala ekonomi</strong>: LRAC menurun saat produksi membesar. <strong>Skala disekonomi</strong>: LRAC naik karena koordinasi, birokrasi, dan komunikasi makin sulit pada perusahaan yang terlalu besar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Sumber skala ekonomi",
        html: "Spesialisasi tenaga kerja, pembelian bahan dalam jumlah besar yang lebih murah, pemakaian mesin dan teknologi canggih, serta penyebaran biaya tetap (riset, merek) ke lebih banyak unit.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Terlalu besar bisa merugikan",
        html: "Perusahaan raksasa rentan <strong>skala disekonomi</strong>: rantai komando panjang, keputusan lambat, dan pengawasan sulit. Membesar tidak selalu menurunkan biaya per unit.",
      },
      {
        type: "video",
        comp: "BiayaProduksi",
        title: "Video: Kurva Biaya Produksi",
        caption: "Kurva biaya rata-rata berbentuk U juga muncul di jangka panjang sebagai LRAC.",
      },
      { type: "widget", widget: "SimulatorBiayaProduksi" },
      {
        type: "chart",
        variant: "line",
        title: "Harga Ford Model T Turun seiring Produksi Massal (data historis)",
        unit: "harga (USD)",
        source: "data historis Ford Motor Company",
        note: "Lini perakitan berjalan (1913) memangkas biaya per unit drastis, sehingga harga Model T turun dari sekitar 850 dolar (1909) menjadi sekitar 290 dolar (1924): contoh nyata skala ekonomi.",
        data: [
          { label: "1909", value: 850, color: "#6366f1" },
          { label: "1913", value: 550, color: "#6366f1" },
          { label: "1916", value: 360, color: "#6366f1" },
          { label: "1924", value: 290, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik kecil vs pabrik besar",
        html: "Sebuah produsen sepatu kecil memproduksi 1.000 pasang per bulan dengan biaya rata-rata Rp50.000 per pasang. Setelah memperbesar pabrik dan memproduksi 5.000 pasang, biaya rata-rata turun menjadi Rp35.000 per pasang karena bahan dibeli grosir dan mesin terpakai penuh. Penurunan biaya per unit ini adalah <strong>skala ekonomi</strong>.",
      },
      {
        type: "case",
        title: "Sejarah: Lini perakitan Ford (1913)",
        html: "Pada <strong>1913</strong>, <strong>Henry Ford</strong> menerapkan <strong>lini perakitan berjalan</strong> di pabrik Highland Park. Waktu merakit satu sasis Model T turun dari sekitar 12,5 jam menjadi sekitar 1,5 jam. Produksi massal menekan biaya per mobil sehingga harga Model T merosot dan penjualannya melonjak; pada 1914 Ford bahkan menetapkan upah 5 dolar per hari. Ini ilustrasi klasik bagaimana skala ekonomi menurunkan biaya per unit.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya rata-rata turun dari Rp50.000 per pasang (1.000 pasang) menjadi Rp35.000 per pasang (5.000 pasang). Berapa persen penurunan biaya per unitnya?",
        answer: 30,
        tolerance: 0,
        suffix: "%",
        solution: "Penurunan = (50.000 - 35.000) / 50.000 x 100% = 15.000 / 50.000 x 100% = <strong>30%</strong>. Inilah manfaat skala ekonomi.",
        hint: "Selisih biaya dibagi biaya awal, lalu kali 100%.",
      },
      {
        type: "classifyExercise",
        prompt: "Faktor berikut menimbulkan skala ekonomi atau skala disekonomi?",
        buckets: ["Skala ekonomi", "Skala disekonomi"],
        items: [
          { text: "Membeli bahan baku dalam jumlah besar lebih murah", bucket: "Skala ekonomi" },
          { text: "Spesialisasi dan pembagian kerja", bucket: "Skala ekonomi" },
          { text: "Rantai komando panjang memperlambat keputusan", bucket: "Skala disekonomi" },
          { text: "Biaya riset disebar ke jutaan unit", bucket: "Skala ekonomi" },
          { text: "Pengawasan sulit pada perusahaan terlalu besar", bucket: "Skala disekonomi" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Biaya tetap riset dan mesin Rp200 juta. Jika disebar ke 10.000 unit produk, berapa biaya tetap per unit (Rp)?",
        answer: 20000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Biaya tetap per unit = 200.000.000 / 10.000 = <strong>Rp20.000</strong>. Makin banyak unit, makin kecil biaya tetap per unit, sumber utama skala ekonomi.",
        hint: "Bagi total biaya tetap dengan jumlah unit.",
      },
      {
        type: "takeaways",
        items: [
          "Dalam jangka panjang semua input variabel; perusahaan memilih skala paling efisien.",
          "LRAC berbentuk U: skala ekonomi, lalu skala hasil konstan, lalu skala disekonomi.",
          "Sumber skala ekonomi: spesialisasi, pembelian grosir, teknologi, dan penyebaran biaya tetap.",
          "Skala disekonomi muncul saat perusahaan terlalu besar dan sulit dikoordinasi.",
          "Lini perakitan Ford (1913) adalah contoh nyata skala ekonomi menurunkan biaya per unit.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kurva LRAC menggambarkan?",
            options: ["Biaya rata-rata terendah pada tiap output di jangka panjang", "Harga jual produk", "Jumlah pekerja", "Pajak per unit"],
            answer: 0,
            explain: "LRAC adalah kurva biaya rata-rata terendah yang dapat dicapai di jangka panjang.",
          },
          {
            q: "Skala ekonomi terjadi ketika?",
            options: ["Biaya per unit naik", "Biaya per unit turun saat produksi membesar", "Output berhenti", "Harga naik"],
            answer: 1,
            explain: "Skala ekonomi berarti biaya rata-rata menurun seiring naiknya output.",
          },
          {
            q: "Manakah sumber skala ekonomi?",
            options: ["Rantai komando panjang", "Pembelian bahan grosir yang lebih murah", "Birokrasi berlebih", "Pengawasan yang sulit"],
            answer: 1,
            explain: "Pembelian dalam jumlah besar menurunkan biaya per unit, sumber skala ekonomi.",
          },
          {
            q: "Skala disekonomi biasanya disebabkan oleh?",
            options: ["Spesialisasi", "Koordinasi yang makin sulit pada perusahaan besar", "Teknologi canggih", "Biaya tetap tersebar"],
            answer: 1,
            explain: "Perusahaan yang terlalu besar sulit dikoordinasi, sehingga biaya per unit naik kembali.",
          },
          {
            q: "Biaya rata-rata turun dari Rp50.000 ke Rp40.000 per unit. Berapa persen penurunannya?",
            options: ["10%", "20%", "25%", "40%"],
            answer: 1,
            explain: "(50.000 - 40.000) / 50.000 x 100% = 20%.",
          },
        ],
      },
    ],
  },
];
