import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "kelangkaan-dan-pilihan",
    levelId: "fondasi",
    order: 1,
    title: "Kelangkaan, Pilihan & Biaya Peluang",
    summary: "Inti ilmu ekonomi: sumber daya terbatas memaksa kita memilih, dan setiap pilihan punya biaya peluang. Dengan video & kalkulator.",
    durationMin: 13,
    tags: ["kelangkaan", "biaya peluang", "pilihan"],
    blocks: [
      {
        type: "paragraph",
        html: "Ilmu <strong>ekonomi</strong> lahir dari satu kenyataan: sumber daya <strong>terbatas</strong>, sedangkan kebutuhan manusia tak terbatas. Karena itu kita harus <strong>memilih</strong>, dan setiap pilihan berarti mengorbankan alternatif lain. Nilai alternatif terbaik yang dikorbankan disebut <strong>biaya peluang</strong>.",
      },
      {
        type: "video",
        comp: "KelangkaanPilihan",
        title: "Video: Kelangkaan Memaksa Pilihan",
        caption: "Animasi kurva kemungkinan produksi (PPF) dan trade-off antar barang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Berpikir di tepi (marginal)",
        html: "Ekonom menilai keputusan dari <strong>tambahan</strong>: manfaat marginal vs biaya marginal. Lakukan sesuatu selama tambahan manfaatnya melebihi tambahan biayanya.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Bandingkan hasil pilihanmu dengan alternatif terbaik yang dilepas untuk menghitung biaya peluang dan laba ekonomi.",
      },
      { type: "widget", widget: "KalkulatorBiayaPeluang" },
      {
        type: "chart",
        variant: "bar",
        title: "Biaya Peluang Kuliah vs Bekerja (ilustrasi per tahun)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Biaya kuliah bukan hanya uang SPP, tetapi juga gaji yang dilepas selama kuliah (biaya peluang).",
        data: [
          { label: "SPP & buku", value: 25, color: "#0ea5e9" },
          { label: "Gaji yang dilepas", value: 60, color: "#ef4444" },
          { label: "Biaya total ekonomi", value: 85, color: "#8b5cf6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih akhir pekan",
        html: "Rina punya satu hari libur. Ia bisa kerja paruh waktu dengan upah Rp200.000, atau ikut seminar gratis yang ia nilai setara manfaat Rp150.000. Jika ia memilih seminar, <strong>biaya peluangnya</strong> adalah Rp200.000 (upah yang dilepas). Secara ekonomi, memilih seminar berarti mengorbankan nilai yang lebih besar, kecuali ia menilai manfaat seminar melebihi Rp200.000.",
      },
      {
        type: "calcExercise",
        prompt: "Andi memilih berbisnis dengan laba Rp80 juta/tahun, melepas pekerjaan bergaji Rp95 juta/tahun. Berapa biaya peluangnya (Rp juta)?",
        answer: 95,
        tolerance: 0,
        suffix: " juta",
        solution: "Biaya peluang = alternatif terbaik yang dilepas = <strong>Rp95 juta</strong> (gaji). Laba ekonominya negatif Rp15 juta, jadi secara ekonomi kurang menguntungkan.",
        hint: "Biaya peluang adalah nilai alternatif terbaik yang dikorbankan.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini termasuk konsep apa?",
        buckets: ["Kelangkaan", "Biaya peluang"],
        items: [
          { text: "Waktu 24 jam sehari harus dibagi", bucket: "Kelangkaan" },
          { text: "Memilih tidur berarti melepas belajar", bucket: "Biaya peluang" },
          { text: "Anggaran terbatas untuk banyak kebutuhan", bucket: "Kelangkaan" },
          { text: "Membangun sekolah berarti melepas membangun jalan", bucket: "Biaya peluang" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Kurva Kemungkinan Produksi: Beras vs Mesin (ilustrasi)",
        unit: "unit mesin",
        source: "ilustrasi edukatif",
        note: "Semakin banyak beras diproduksi, semakin sedikit mesin yang bisa dibuat. Inilah trade-off pada PPF.",
        data: [
          { label: "0 ribu ton beras", value: 100, color: "#0ea5e9" },
          { label: "25 ribu ton beras", value: 90, color: "#0ea5e9" },
          { label: "50 ribu ton beras", value: 70, color: "#0ea5e9" },
          { label: "75 ribu ton beras", value: 40, color: "#0ea5e9" },
          { label: "100 ribu ton beras", value: 0, color: "#0ea5e9" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah lahan bisa menghasilkan 100 unit mesin atau 100 ribu ton beras. Jika produksi beras dinaikkan dari 50 menjadi 75 ribu ton, produksi mesin turun dari 70 menjadi 40 unit. Berapa biaya peluang tambahan 25 ribu ton beras itu (dalam unit mesin)?",
        answer: 30,
        tolerance: 0,
        suffix: " unit",
        solution: "Biaya peluang = mesin yang dilepas = 70 - 40 = <strong>30 unit mesin</strong>. Perhatikan biaya peluang makin besar saat sumber daya digeser, ciri PPF cekung.",
        hint: "Hitung selisih jumlah mesin sebelum dan sesudah produksi beras dinaikkan.",
      },
      {
        type: "takeaways",
        items: [
          "Ekonomi mempelajari pilihan di tengah kelangkaan.",
          "Setiap pilihan punya biaya peluang: alternatif terbaik yang dikorbankan.",
          "Ekonom berpikir marginal: bandingkan tambahan manfaat dan tambahan biaya.",
          "Laba ekonomi memperhitungkan biaya peluang, bukan hanya biaya uang.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Masalah dasar ekonomi adalah?",
            options: ["Uang habis", "Kelangkaan: sumber daya terbatas, kebutuhan tak terbatas", "Inflasi", "Pajak"],
            answer: 1,
            explain: "Kelangkaan memaksa manusia memilih, inilah inti ilmu ekonomi.",
          },
          {
            q: "Biaya peluang adalah?",
            options: ["Biaya uang yang dibayar", "Nilai alternatif terbaik yang dikorbankan", "Pajak", "Total biaya produksi"],
            answer: 1,
            explain: "Biaya peluang adalah nilai dari pilihan terbaik yang kita lepas.",
          },
          {
            q: "Berpikir marginal berarti?",
            options: ["Melihat total saja", "Membandingkan tambahan manfaat dan tambahan biaya", "Mengabaikan biaya", "Selalu memilih termurah"],
            answer: 1,
            explain: "Keputusan marginal menimbang manfaat dan biaya dari satu tambahan unit.",
          },
          {
            q: "Mahasiswa kuliah melepas gaji Rp50 juta. Itu disebut?",
            options: ["Biaya eksplisit", "Biaya peluang (implisit)", "Pajak", "Subsidi"],
            answer: 1,
            explain: "Gaji yang dilepas adalah biaya implisit, yaitu biaya peluang.",
          },
          {
            q: "Memilih A berlaba Rp70 jt dan melepas B berlaba Rp90 jt. Biaya peluang A?",
            options: ["Rp70 juta", "Rp90 juta", "Rp20 juta", "Rp160 juta"],
            answer: 1,
            explain: "Biaya peluang = alternatif terbaik yang dilepas = Rp90 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sepuluh-prinsip-ekonomi",
    levelId: "fondasi",
    order: 2,
    title: "Prinsip Dasar Ekonomi",
    summary: "Empat gagasan inti yang memandu cara ekonom berpikir: trade-off, insentif, perdagangan yang saling menguntungkan, serta peran pasar dan pemerintah.",
    durationMin: 13,
    tags: ["prinsip ekonomi", "insentif", "trade-off", "pasar"],
    blocks: [
      {
        type: "paragraph",
        html: "Ilmu ekonomi bisa diringkas menjadi sejumlah <strong>prinsip dasar</strong>. Intinya: setiap orang menghadapi <strong>trade-off</strong>, bereaksi terhadap <strong>insentif</strong>, dan dapat memperoleh keuntungan dari <strong>perdagangan</strong>. Dalam skala besar, <strong>pasar</strong> biasanya cara yang baik untuk mengatur kegiatan ekonomi, walau ada kalanya <strong>pemerintah</strong> perlu turun tangan.",
      },
      {
        type: "paragraph",
        html: "Prinsip-prinsip ini bukan rumus kaku, melainkan cara pandang. Dengan memahaminya, kita bisa menjelaskan keputusan rumah tangga, perusahaan, hingga kebijakan negara secara konsisten.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tidak ada makan siang gratis",
        html: "Untuk mendapatkan sesuatu, biasanya kita harus melepaskan sesuatu yang lain. Inilah inti <strong>trade-off</strong>: efisiensi versus pemerataan, konsumsi sekarang versus tabungan masa depan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Orang bereaksi pada insentif",
        html: "Ketika harga, pajak, atau subsidi berubah, perilaku ikut berubah. Kebijakan yang baik mempertimbangkan bagaimana insentif menggeser pilihan orang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Perdagangan saling menguntungkan",
        html: "Perdagangan bukan permainan menang-kalah. Lewat <strong>spesialisasi</strong>, setiap pihak mengerjakan yang paling efisien lalu saling menukar, sehingga total barang dan jasa bertambah.",
      },
      {
        type: "case",
        title: "Studi Kasus: Insentif pajak rokok",
        html: "Pemerintah menaikkan cukai sehingga harga sebungkus rokok naik dari Rp25.000 menjadi Rp35.000 (naik 40%). Konsumsi turun dari 100 juta bungkus menjadi 80 juta bungkus per bulan. Penurunan konsumsi 20% ini menunjukkan orang <strong>bereaksi pada insentif</strong>: harga lebih tinggi mendorong sebagian orang berhenti atau mengurangi.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah negara bisa memproduksi 1.000 ton beras ATAU 400 unit mesin dengan sumber daya yang sama. Jika memilih memproduksi mesin, berapa biaya peluang per unit mesin (dalam ton beras)?",
        answer: 2.5,
        tolerance: 0.1,
        suffix: " ton",
        solution: "Biaya peluang 400 mesin = 1.000 ton beras. Maka per unit mesin = 1.000 / 400 = <strong>2,5 ton beras</strong>. Ini contoh trade-off dalam alokasi sumber daya.",
        hint: "Bagi total beras yang dilepas dengan jumlah mesin yang diperoleh.",
      },
      {
        type: "classifyExercise",
        prompt: "Setiap contoh menggambarkan prinsip yang mana?",
        buckets: ["Trade-off", "Insentif", "Perdagangan saling untung"],
        items: [
          { text: "Pemerintah memilih antara anggaran kesehatan dan pendidikan", bucket: "Trade-off" },
          { text: "Subsidi mobil listrik mendorong orang beralih membeli", bucket: "Insentif" },
          { text: "Indonesia ekspor kelapa sawit, impor gandum", bucket: "Perdagangan saling untung" },
          { text: "Diskon besar membuat antrean panjang di kasir", bucket: "Insentif" },
          { text: "Belajar lebih lama berarti waktu istirahat berkurang", bucket: "Trade-off" },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Konsumsi Rokok Sebelum dan Sesudah Kenaikan Cukai (ilustrasi)",
        unit: "juta bungkus/bulan",
        source: "ilustrasi edukatif",
        note: "Saat harga naik karena cukai, konsumsi turun. Orang bereaksi pada insentif harga.",
        data: [
          { label: "Sebelum cukai", value: 100, color: "#22c55e" },
          { label: "Bulan ke-1", value: 92, color: "#22c55e" },
          { label: "Bulan ke-2", value: 86, color: "#22c55e" },
          { label: "Bulan ke-3", value: 80, color: "#22c55e" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan prinsip ekonomi dengan contoh penerapannya.",
        pairs: [
          { left: "Menghadapi trade-off", right: "Memilih menonton film atau belajar di malam yang sama" },
          { left: "Bereaksi pada insentif", right: "Pajak rokok naik, perokok mengurangi konsumsi" },
          { left: "Perdagangan saling untung", right: "Petani menukar beras dengan ikan dari nelayan" },
          { left: "Pasar menata kegiatan", right: "Harga cabai naik saat panen gagal, lalu turun saat panen melimpah" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Setiap pilihan melibatkan trade-off: untuk mendapat sesuatu kita melepas hal lain.",
          "Orang bereaksi pada insentif, sehingga kebijakan harus memperhitungkan perubahan perilaku.",
          "Perdagangan dan spesialisasi membuat semua pihak bisa lebih sejahtera.",
          "Pasar mengoordinasikan kegiatan ekonomi, tetapi pemerintah kadang perlu memperbaiki kegagalan pasar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Ungkapan 'tidak ada makan siang gratis' paling tepat menggambarkan?",
            options: ["Inflasi", "Trade-off", "Monopoli", "Pajak"],
            answer: 1,
            explain: "Untuk memperoleh sesuatu kita harus melepas sesuatu yang lain, itulah trade-off.",
          },
          {
            q: "Kenaikan cukai membuat konsumsi rokok turun. Ini menunjukkan?",
            options: ["Orang mengabaikan harga", "Orang bereaksi pada insentif", "Perdagangan bebas", "Kegagalan pasar"],
            answer: 1,
            explain: "Perubahan harga adalah insentif yang menggeser perilaku konsumen.",
          },
          {
            q: "Mengapa perdagangan dianggap saling menguntungkan?",
            options: ["Selalu ada yang kalah", "Spesialisasi menambah total barang dan jasa", "Menghapus persaingan", "Menaikkan pajak"],
            answer: 1,
            explain: "Lewat spesialisasi dan pertukaran, setiap pihak bisa memperoleh lebih banyak.",
          },
          {
            q: "Pasar mengoordinasikan ekonomi terutama melalui?",
            options: ["Perintah pemerintah", "Harga sebagai sinyal", "Undian", "Larangan impor"],
            answer: 1,
            explain: "Harga memberi sinyal kelangkaan dan mengarahkan keputusan produsen dan konsumen.",
          },
          {
            q: "Negara bisa membuat 1.000 ton beras atau 500 mesin. Biaya peluang 1 mesin?",
            options: ["0,5 ton beras", "2 ton beras", "5 ton beras", "1.000 ton beras"],
            answer: 1,
            explain: "1.000 ton / 500 mesin = 2 ton beras per mesin.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pelaku-ekonomi",
    levelId: "fondasi",
    order: 3,
    title: "Pelaku Ekonomi & Diagram Arus Melingkar",
    summary: "Mengenal rumah tangga, perusahaan, dan pemerintah, serta bagaimana mereka saling terhubung lewat diagram arus melingkar (circular flow).",
    durationMin: 13,
    tags: ["pelaku ekonomi", "circular flow", "rumah tangga", "perusahaan"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam perekonomian ada beberapa <strong>pelaku ekonomi</strong> utama: <strong>rumah tangga konsumen</strong>, <strong>perusahaan</strong> (produsen), dan <strong>pemerintah</strong>. Dalam ekonomi terbuka ditambah <strong>masyarakat luar negeri</strong>. Mereka saling bergantung: rumah tangga menyediakan faktor produksi, perusahaan menghasilkan barang dan jasa, dan pemerintah mengatur serta menyediakan barang publik.",
      },
      {
        type: "paragraph",
        html: "Hubungan antarpelaku ini digambarkan lewat <strong>diagram arus melingkar</strong> (circular flow). Diagram ini menunjukkan dua arus yang berlawanan: arus barang dan faktor produksi (arus riil), serta arus uang berupa pembayaran (arus moneter).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua pasar, dua arah",
        html: "Di <strong>pasar barang</strong>, rumah tangga membeli barang dari perusahaan. Di <strong>pasar faktor produksi</strong>, perusahaan membeli tenaga kerja, tanah, dan modal dari rumah tangga. Uang dan barang mengalir berlawanan arah.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Peran rumah tangga",
        html: "Rumah tangga adalah <strong>pemilik faktor produksi</strong> (tenaga kerja, tanah, modal, kewirausahaan) sekaligus <strong>konsumen</strong>. Mereka menerima balas jasa berupa upah, sewa, bunga, dan laba.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Peran pemerintah",
        html: "Pemerintah memungut <strong>pajak</strong>, menyediakan <strong>barang publik</strong> (jalan, keamanan), dan memberi <strong>subsidi</strong>. Ia menjadi pelaku sekaligus pengatur agar perekonomian berjalan adil dan stabil.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Sumber Pendapatan Rumah Tangga (ilustrasi)",
        unit: "% pendapatan",
        source: "ilustrasi edukatif",
        note: "Balas jasa faktor produksi: upah dari tenaga kerja paling dominan bagi mayoritas rumah tangga.",
        data: [
          { label: "Upah (tenaga kerja)", value: 65, color: "#0ea5e9" },
          { label: "Bunga (modal)", value: 12, color: "#8b5cf6" },
          { label: "Sewa (tanah)", value: 10, color: "#22c55e" },
          { label: "Laba (usaha)", value: 13, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Satu putaran arus melingkar",
        html: "Bu Sari bekerja di pabrik roti dan menerima upah Rp4.000.000 per bulan (arus faktor produksi: tenaga kerja ke perusahaan, uang ke rumah tangga). Dari upah itu, ia membelanjakan Rp3.200.000 untuk barang dan jasa, termasuk membeli roti dari pabrik lain (arus pasar barang). Pemerintah memungut pajak Rp200.000 dan memakainya membangun jalan yang dipakai pabrik dan rumah tangga. Inilah satu putaran lengkap arus melingkar.",
      },
      {
        type: "calcExercise",
        prompt: "Rumah tangga menerima upah Rp4.000.000. Mereka membayar pajak Rp300.000 dan menabung Rp500.000. Berapa konsumsi mereka (Rp)?",
        answer: 3200000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Konsumsi = pendapatan - pajak - tabungan = 4.000.000 - 300.000 - 500.000 = <strong>Rp3.200.000</strong>. Konsumsi inilah yang mengalir ke pasar barang menuju perusahaan.",
        hint: "Pendapatan dipakai untuk konsumsi, ditambah tabungan dan pajak.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan pelaku ekonomi dengan perannya.",
        pairs: [
          { left: "Rumah tangga", right: "Pemilik faktor produksi & konsumen" },
          { left: "Perusahaan", right: "Memproduksi barang dan jasa" },
          { left: "Pemerintah", right: "Memungut pajak & sediakan barang publik" },
          { left: "Masyarakat luar negeri", right: "Mitra ekspor dan impor" },
        ],
      },
      {
        type: "video",
        comp: "CircularFlow",
        title: "Video: Diagram Arus Melingkar",
        caption: "Animasi arus riil (barang dan faktor produksi) dan arus moneter (uang) antara rumah tangga, perusahaan, dan pemerintah.",
      },
      {
        type: "classifyExercise",
        prompt: "Setiap aliran berikut terjadi di pasar yang mana?",
        buckets: ["Pasar barang", "Pasar faktor produksi"],
        items: [
          { text: "Rumah tangga membeli beras dari perusahaan", bucket: "Pasar barang" },
          { text: "Perusahaan membayar upah kepada pekerja", bucket: "Pasar faktor produksi" },
          { text: "Rumah tangga menyewakan tanah kepada perusahaan", bucket: "Pasar faktor produksi" },
          { text: "Keluarga membayar tagihan listrik dan internet", bucket: "Pasar barang" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Pelaku ekonomi utama: rumah tangga, perusahaan, pemerintah, dan masyarakat luar negeri.",
          "Rumah tangga memiliki faktor produksi dan menjadi konsumen sekaligus.",
          "Diagram arus melingkar menggambarkan arus barang/faktor dan arus uang yang berlawanan.",
          "Pasar barang dan pasar faktor produksi menghubungkan semua pelaku.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Di pasar faktor produksi, rumah tangga berperan sebagai?",
            options: ["Pembeli barang", "Penjual tenaga kerja, tanah, dan modal", "Pemungut pajak", "Produsen barang"],
            answer: 1,
            explain: "Rumah tangga menjual faktor produksi kepada perusahaan dan menerima balas jasa.",
          },
          {
            q: "Diagram arus melingkar menunjukkan?",
            options: ["Hanya arus uang", "Arus barang/faktor dan arus uang yang berlawanan", "Tingkat inflasi", "Jadwal produksi pabrik"],
            answer: 1,
            explain: "Ada dua arus berlawanan: arus riil (barang/faktor) dan arus moneter (uang).",
          },
          {
            q: "Balas jasa atas penggunaan modal disebut?",
            options: ["Upah", "Sewa", "Bunga", "Laba"],
            answer: 2,
            explain: "Modal memperoleh bunga, tenaga kerja upah, tanah sewa, dan kewirausahaan laba.",
          },
          {
            q: "Peran utama pemerintah dalam arus melingkar adalah?",
            options: ["Hanya membeli barang", "Memungut pajak dan menyediakan barang publik", "Mengekspor barang", "Menjadi pemilik tunggal pabrik"],
            answer: 1,
            explain: "Pemerintah memungut pajak, memberi subsidi, dan menyediakan barang publik.",
          },
          {
            q: "Perusahaan membeli tenaga kerja dari rumah tangga terjadi di?",
            options: ["Pasar barang", "Pasar faktor produksi", "Pasar valuta asing", "Pasar modal saja"],
            answer: 1,
            explain: "Tenaga kerja adalah faktor produksi, sehingga transaksinya di pasar faktor produksi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sistem-ekonomi",
    levelId: "fondasi",
    order: 4,
    title: "Sistem Ekonomi & Ekonomi Pancasila",
    summary: "Membandingkan sistem ekonomi pasar, komando, dan campuran, lalu memahami sistem ekonomi Indonesia yang berlandaskan Pancasila.",
    durationMin: 14,
    tags: ["sistem ekonomi", "pasar", "komando", "ekonomi pancasila"],
    blocks: [
      {
        type: "paragraph",
        html: "Setiap negara harus menjawab tiga pertanyaan pokok: <strong>apa</strong> yang diproduksi, <strong>bagaimana</strong> memproduksinya, dan <strong>untuk siapa</strong>. Cara menjawabnya menentukan <strong>sistem ekonomi</strong> yang dianut. Secara umum dikenal tiga bentuk: ekonomi <strong>pasar</strong>, ekonomi <strong>komando</strong>, dan ekonomi <strong>campuran</strong>.",
      },
      {
        type: "paragraph",
        html: "Dalam ekonomi <strong>pasar</strong>, keputusan diserahkan pada mekanisme harga dan swasta. Dalam ekonomi <strong>komando</strong>, pemerintah pusat mengendalikan produksi dan distribusi. Sebagian besar negara, termasuk Indonesia, menganut ekonomi <strong>campuran</strong> yang memadukan keduanya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ekonomi pasar (liberal)",
        html: "Kelebihan: efisien, inovatif, dan responsif terhadap permintaan. Kekurangan: rawan <strong>ketimpangan</strong> dan kegagalan pasar seperti monopoli serta polusi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Ekonomi komando (terpusat)",
        html: "Kelebihan: pemerataan dan kontrol kuat. Kekurangan: kurang insentif, lambat berinovasi, dan sering tidak efisien karena minim sinyal harga.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ekonomi Pancasila",
        html: "Sistem Indonesia adalah ekonomi campuran berlandaskan <strong>Pasal 33 UUD 1945</strong>: usaha bersama atas asas kekeluargaan, cabang produksi penting dikuasai negara, dan bumi serta air untuk sebesar-besarnya kemakmuran rakyat.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Porsi Peran Pemerintah vs Swasta per Sistem (ilustrasi)",
        unit: "% kendali",
        source: "ilustrasi edukatif",
        note: "Ekonomi campuran seperti Indonesia berada di tengah, memadukan peran pemerintah dan swasta.",
        data: [
          { label: "Pasar (swasta)", value: 15, color: "#0ea5e9" },
          { label: "Campuran (Indonesia)", value: 45, color: "#22c55e" },
          { label: "Komando (negara)", value: 90, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: BBM dan listrik di Indonesia",
        html: "Listrik dikelola BUMN PLN dan harga sebagian disubsidi pemerintah, karena listrik termasuk cabang produksi penting yang menguasai hajat hidup orang banyak (Pasal 33). Sementara itu, harga ponsel dan pakaian dibiarkan ditentukan <strong>pasar</strong>. Perpaduan ini, sebagian diatur negara dan sebagian oleh pasar, adalah ciri khas <strong>ekonomi campuran</strong> ala Pancasila.",
      },
      {
        type: "calcExercise",
        prompt: "Pemerintah memberi subsidi listrik Rp300 per kWh. Tarif keekonomian Rp1.500/kWh. Berapa tarif yang dibayar rumah tangga bersubsidi (Rp/kWh)?",
        answer: 1200,
        tolerance: 0,
        prefix: "Rp",
        solution: "Tarif dibayar = tarif keekonomian - subsidi = 1.500 - 300 = <strong>Rp1.200/kWh</strong>. Subsidi adalah bentuk campur tangan pemerintah dalam ekonomi campuran.",
        hint: "Kurangi tarif keekonomian dengan besarnya subsidi per kWh.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri berikut termasuk sistem ekonomi yang mana?",
        buckets: ["Ekonomi pasar", "Ekonomi komando", "Ekonomi campuran"],
        items: [
          { text: "Harga ditentukan permintaan dan penawaran, peran negara minim", bucket: "Ekonomi pasar" },
          { text: "Pemerintah pusat menentukan apa dan berapa yang diproduksi", bucket: "Ekonomi komando" },
          { text: "Swasta bebas berusaha, tetapi cabang vital dikuasai negara", bucket: "Ekonomi campuran" },
          { text: "Indonesia berdasarkan Pasal 33 UUD 1945", bucket: "Ekonomi campuran" },
          { text: "Negara memiliki hampir seluruh alat produksi", bucket: "Ekonomi komando" },
        ],
      },
      {
        type: "video",
        comp: "SistemEkonomi",
        title: "Video: Membandingkan Sistem Ekonomi",
        caption: "Animasi perbedaan ekonomi pasar, komando, dan campuran, serta posisi Ekonomi Pancasila berdasarkan Pasal 33 UUD 1945.",
      },
      {
        type: "chart",
        variant: "area",
        title: "Cakupan BUMN pada Cabang Produksi Penting (ilustrasi)",
        unit: "% kendali negara",
        source: "ilustrasi edukatif",
        note: "Cabang yang menguasai hajat hidup orang banyak cenderung dikuasai negara sesuai Pasal 33 UUD 1945.",
        data: [
          { label: "Listrik", value: 85, color: "#ef4444" },
          { label: "Air bersih", value: 80, color: "#0ea5e9" },
          { label: "BBM", value: 70, color: "#f59e0b" },
          { label: "Telekomunikasi", value: 40, color: "#8b5cf6" },
          { label: "Pakaian", value: 5, color: "#22c55e" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan sistem ekonomi dengan ciri utamanya.",
        pairs: [
          { left: "Ekonomi pasar", right: "Harga dan swasta menentukan, peran negara minim" },
          { left: "Ekonomi komando", right: "Pemerintah pusat mengendalikan produksi dan distribusi" },
          { left: "Ekonomi campuran", right: "Memadukan mekanisme pasar dengan peran pemerintah" },
          { left: "Ekonomi Pancasila", right: "Usaha bersama asas kekeluargaan berdasar Pasal 33 UUD 1945" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Tarif keekonomian air bersih Rp5.000/m3. Pemerintah menetapkan subsidi 40% dari tarif itu untuk rumah tangga. Berapa tarif yang dibayar rumah tangga (Rp/m3)?",
        answer: 3000,
        tolerance: 0,
        prefix: "Rp",
        solution: "Subsidi = 40% x 5.000 = 2.000. Tarif dibayar = 5.000 - 2.000 = <strong>Rp3.000/m3</strong>. Subsidi adalah campur tangan negara, ciri ekonomi campuran.",
        hint: "Hitung dulu nilai subsidi 40%, lalu kurangkan dari tarif keekonomian.",
      },
      {
        type: "takeaways",
        items: [
          "Sistem ekonomi menjawab pertanyaan apa, bagaimana, dan untuk siapa barang diproduksi.",
          "Ekonomi pasar efisien tetapi rawan ketimpangan; ekonomi komando merata tetapi kurang insentif.",
          "Sebagian besar negara menganut ekonomi campuran.",
          "Indonesia menganut Ekonomi Pancasila berlandaskan Pasal 33 UUD 1945: usaha bersama dan kemakmuran rakyat.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tiga pertanyaan pokok ekonomi adalah?",
            options: ["Kapan, di mana, siapa", "Apa, bagaimana, untuk siapa", "Untung, rugi, impas", "Beli, jual, simpan"],
            answer: 1,
            explain: "Setiap sistem ekonomi menjawab apa, bagaimana, dan untuk siapa diproduksi.",
          },
          {
            q: "Kelemahan utama ekonomi komando adalah?",
            options: ["Terlalu efisien", "Kurang insentif dan lambat berinovasi", "Ketimpangan tinggi", "Tidak ada pemerintah"],
            answer: 1,
            explain: "Tanpa sinyal harga dan insentif, ekonomi komando cenderung tidak efisien.",
          },
          {
            q: "Landasan konstitusional ekonomi Indonesia adalah?",
            options: ["Pasal 27 UUD 1945", "Pasal 33 UUD 1945", "Pasal 1 UUD 1945", "Tap MPR No. 1"],
            answer: 1,
            explain: "Pasal 33 UUD 1945 menjadi dasar Ekonomi Pancasila yang bersifat campuran.",
          },
          {
            q: "Ciri khas ekonomi campuran adalah?",
            options: ["Hanya swasta", "Hanya negara", "Perpaduan peran pasar dan pemerintah", "Tanpa harga"],
            answer: 2,
            explain: "Ekonomi campuran memadukan mekanisme pasar dengan peran pemerintah.",
          },
          {
            q: "Listrik dikuasai negara di Indonesia karena?",
            options: ["Tidak laku di pasar", "Cabang produksi penting yang menguasai hajat hidup orang banyak", "Permintaan rendah", "Larangan impor"],
            answer: 1,
            explain: "Sesuai Pasal 33, cabang vital dikuasai negara demi kemakmuran rakyat.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kebutuhan-dan-skala-prioritas",
    levelId: "fondasi",
    order: 5,
    title: "Kebutuhan, Keinginan & Skala Prioritas",
    summary: "Membedakan kebutuhan dari keinginan, mengenal jenis kebutuhan, dan menyusun skala prioritas agar anggaran terbatas dipakai untuk yang paling penting dulu.",
    durationMin: 13,
    tags: ["kebutuhan", "keinginan", "skala prioritas"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua yang kita inginkan benar-benar kita butuhkan. <strong>Kebutuhan</strong> adalah sesuatu yang harus dipenuhi agar hidup layak (makanan, tempat tinggal, kesehatan), sedangkan <strong>keinginan</strong> adalah hasrat tambahan yang bila tidak terpenuhi tidak mengancam kelangsungan hidup (gawai terbaru, liburan mewah). Karena sumber daya terbatas, kita perlu memilah keduanya.",
      },
      {
        type: "paragraph",
        html: "Kebutuhan bisa digolongkan menurut <strong>intensitasnya</strong> (primer, sekunder, tersier), menurut <strong>waktunya</strong> (sekarang dan masa depan), serta menurut <strong>sifatnya</strong> (jasmani dan rohani). Penggolongan ini membantu menyusun <strong>skala prioritas</strong>, yaitu daftar kebutuhan yang diurutkan dari yang paling mendesak ke yang bisa ditunda.",
      },
      {
        type: "video",
        comp: "KelangkaanPilihan",
        title: "Video: Kelangkaan Memaksa Pilihan",
        caption: "Sumber daya terbatas menuntut kita memilih kebutuhan mana yang didahulukan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Skala prioritas",
        html: "Dahulukan kebutuhan yang <strong>paling mendesak dan paling penting</strong>. Urutkan dari kebutuhan primer (pangan, papan, sandang), lalu sekunder, baru tersier. Keinginan yang bisa ditunda diletakkan paling bawah.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga cara menggolongkan kebutuhan",
        html: "Menurut <strong>intensitas</strong>: primer, sekunder, tersier. Menurut <strong>waktu</strong>: sekarang dan masa depan. Menurut <strong>sifat</strong>: jasmani (makan, olahraga) dan rohani (ibadah, hiburan sehat).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Bandingkan pilihan membelanjakan uang untuk kebutuhan vs keinginan, dan lihat biaya peluang dari mendahulukan satu di atas yang lain.",
      },
      { type: "widget", widget: "KalkulatorBiayaPeluang" },
      {
        type: "chart",
        variant: "bar",
        title: "Pangsa Pengeluaran Makanan Menurun saat Pendapatan Naik",
        unit: "% pengeluaran untuk makanan",
        source: "pola umum (Hukum Engel)",
        note: "Hukum Engel: makin tinggi pendapatan, makin kecil porsi yang dibelanjakan untuk makanan (kebutuhan primer), karena sebagian beralih ke kebutuhan sekunder dan tersier.",
        data: [
          { label: "Kelompok termiskin", value: 62, color: "#ef4444" },
          { label: "Menengah bawah", value: 53, color: "#f59e0b" },
          { label: "Menengah atas", value: 44, color: "#0ea5e9" },
          { label: "Kelompok terkaya", value: 35, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Uang saku terbatas",
        html: "Dina punya Rp1.500.000 untuk sebulan. Kebutuhan primernya: makan Rp900.000 dan transportasi ke kampus Rp300.000, sehingga tersisa Rp300.000. Ia ingin sepatu baru Rp500.000 (keinginan) dan buku kuliah Rp250.000 (kebutuhan sekunder). Dengan <strong>skala prioritas</strong>, Dina mendahulukan buku kuliah, menyisihkan Rp50.000 untuk menabung, dan menunda sepatu sampai bulan depan.",
      },
      {
        type: "case",
        title: "Sejarah: Hierarki kebutuhan Maslow (1943)",
        html: "Pada tahun <strong>1943</strong>, psikolog <strong>Abraham Maslow</strong> menerbitkan teori 'A Theory of Human Motivation' yang menyusun kebutuhan manusia berjenjang: kebutuhan <strong>fisiologis</strong> (makan, minum), <strong>rasa aman</strong>, <strong>sosial</strong>, <strong>penghargaan</strong>, dan <strong>aktualisasi diri</strong>. Gagasannya menegaskan bahwa manusia cenderung memenuhi kebutuhan dasar lebih dulu sebelum mengejar kebutuhan yang lebih tinggi, sebuah landasan logika skala prioritas dalam ekonomi.",
      },
      {
        type: "calcExercise",
        prompt: "Pengeluaran rumah tangga sebulan Rp4.000.000, dan Rp2.400.000 di antaranya untuk makanan. Berapa persen pangsa pengeluaran makanannya?",
        answer: 60,
        tolerance: 0,
        suffix: "%",
        solution: "Pangsa makanan = 2.400.000 / 4.000.000 x 100% = <strong>60%</strong>. Pangsa makanan yang tinggi menandakan rumah tangga berpendapatan rendah (sesuai Hukum Engel).",
        hint: "Bagi pengeluaran makanan dengan total pengeluaran, lalu kali 100%.",
      },
      {
        type: "classifyExercise",
        prompt: "Pengeluaran berikut termasuk kebutuhan atau keinginan?",
        buckets: ["Kebutuhan", "Keinginan"],
        items: [
          { text: "Beras dan lauk untuk makan harian", bucket: "Kebutuhan" },
          { text: "Tas bermerek edisi terbatas", bucket: "Keinginan" },
          { text: "Biaya berobat saat sakit", bucket: "Kebutuhan" },
          { text: "Gawai terbaru padahal yang lama masih bagus", bucket: "Keinginan" },
          { text: "Seragam dan buku sekolah", bucket: "Kebutuhan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Kebutuhan harus dipenuhi untuk hidup layak; keinginan adalah hasrat tambahan yang bisa ditunda.",
          "Kebutuhan digolongkan menurut intensitas, waktu, dan sifat.",
          "Skala prioritas mengurutkan kebutuhan dari yang paling mendesak.",
          "Hukum Engel: makin tinggi pendapatan, makin kecil porsi pengeluaran untuk makanan.",
          "Hierarki Maslow (1943) menegaskan kebutuhan dasar dipenuhi lebih dulu.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Perbedaan utama kebutuhan dan keinginan adalah?",
            options: ["Sama saja", "Kebutuhan harus dipenuhi untuk hidup layak, keinginan bisa ditunda", "Keinginan selalu lebih murah", "Kebutuhan hanya soal makanan"],
            answer: 1,
            explain: "Kebutuhan menyangkut kelayakan hidup; keinginan adalah hasrat tambahan yang dapat ditunda.",
          },
          {
            q: "Kebutuhan menurut intensitas terbagi menjadi?",
            options: ["Jasmani dan rohani", "Sekarang dan masa depan", "Primer, sekunder, tersier", "Wajib dan sunah"],
            answer: 2,
            explain: "Menurut intensitasnya, kebutuhan terbagi atas primer, sekunder, dan tersier.",
          },
          {
            q: "Skala prioritas berguna untuk?",
            options: ["Menambah pendapatan", "Mengurutkan kebutuhan dari yang paling mendesak", "Menghapus pajak", "Menaikkan harga"],
            answer: 1,
            explain: "Skala prioritas membantu mendahulukan kebutuhan paling penting saat anggaran terbatas.",
          },
          {
            q: "Hukum Engel menyatakan bahwa saat pendapatan naik?",
            options: ["Porsi pengeluaran makanan naik", "Porsi pengeluaran makanan turun", "Total pengeluaran nol", "Harga makanan naik"],
            answer: 1,
            explain: "Pangsa pengeluaran untuk makanan menurun seiring naiknya pendapatan.",
          },
          {
            q: "Dalam hierarki Maslow (1943), kebutuhan yang dipenuhi paling awal adalah?",
            options: ["Aktualisasi diri", "Penghargaan", "Fisiologis", "Sosial"],
            answer: 2,
            explain: "Kebutuhan fisiologis seperti makan dan minum berada di dasar hierarki dan dipenuhi lebih dulu.",
          },
        ],
      },
    ],
  },
];
