import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "metafisika-kehendak-bebas",
    levelId: "metafisika",
    order: 1,
    title: "Metafisika & Kehendak Bebas",
    summary: "Pertanyaan tentang hakikat kenyataan, serta perdebatan kehendak bebas vs determinisme. Dengan video.",
    durationMin: 14,
    tags: ["metafisika", "kehendak bebas", "determinisme"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Metafisika</strong> menanyakan apa yang sungguh-sungguh <strong>ada</strong>. Apakah kenyataan terdiri dari materi (<strong>materialisme</strong>) atau ide/pikiran (<strong>idealisme</strong>)? Salah satu perdebatan terbesarnya: apakah manusia punya <strong>kehendak bebas</strong>, atau semua sudah ditentukan (<strong>determinisme</strong>)?",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_001.jpg?width=400",
        alt: "Potret Karl Marx",
        caption: "Karl Marx, tokoh materialisme yang memandang materi dan kondisi ekonomi sebagai dasar kenyataan sosial.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "KehendakBebas",
        title: "Video: Kehendak Bebas vs Determinisme",
        caption: "Animasi tiga posisi: determinisme, kehendak bebas, dan kompatibilisme.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Baruch_de_Spinoza.jpg?width=400",
        alt: "Potret Baruch Spinoza",
        caption: "Baruch Spinoza, penganut determinisme yang menilai segala sesuatu mengikuti hukum yang niscaya sehingga kehendak bebas mutlak ditolaknya.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga posisi",
        html: "<strong>Determinisme</strong>: semua peristiwa ditentukan sebab sebelumnya. <strong>Libertarianisme</strong> (kehendak bebas): kita benar-benar bisa memilih bebas. <strong>Kompatibilisme</strong>: kebebasan dan sebab-akibat bisa berdampingan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa ini penting",
        html: "Jika tidak ada kehendak bebas, bisakah seseorang benar-benar bertanggung jawab atau disalahkan atas perbuatannya? Pertanyaan metafisik ini berdampak langsung pada moral dan hukum.",
      },
      {
        type: "case",
        title: "Studi Kasus: Otak dan pilihan",
        html: "Eksperimen menunjukkan aktivitas otak muncul sepersekian detik sebelum kita 'sadar' memutuskan. Penganut <strong>determinisme</strong> melihat ini sebagai bukti pilihan ditentukan proses fisik. Pembela <strong>kehendak bebas</strong> menjawab bahwa kesadaran tetap berperan menyetujui atau membatalkan dorongan itu. Perdebatan ini belum tuntas dan tetap hidup.",
      },
      {
        type: "calcExercise",
        prompt: "Dalam debat kehendak bebas, berapa posisi utama yang dibahas pelajaran ini?",
        answer: 3,
        tolerance: 0,
        solution: "Tiga posisi: <strong>determinisme</strong>, <strong>kehendak bebas (libertarianisme)</strong>, dan <strong>kompatibilisme</strong>.",
        hint: "Hitung posisi pada callout 'Tiga posisi'.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini mencerminkan pandangan yang mana?",
        buckets: ["Determinisme", "Kehendak Bebas", "Kompatibilisme"],
        items: [
          { text: "Setiap pilihan sudah ditentukan sebab sebelumnya", bucket: "Determinisme" },
          { text: "Manusia benar-benar bisa memilih lain dari yang terjadi", bucket: "Kehendak Bebas" },
          { text: "Bebas berarti bertindak sesuai keinginan sendiri, walau ada sebab", bucket: "Kompatibilisme" },
          { text: "Alam semesta seperti jam yang sudah diatur", bucket: "Determinisme" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi: kecenderungan tokoh menurut posisi metafisika (angka ilustratif)",
        unit: "tokoh",
        source: "ilustrasi edukatif",
        note: "Angka rekaan untuk menggambarkan sebaran, bukan hitungan nyata.",
        data: [
          { label: "Materialisme", value: 9, color: "#2563eb" },
          { label: "Idealisme", value: 6, color: "#10b981" },
          { label: "Dualisme", value: 4, color: "#f59e0b" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan filsuf dengan posisi yang paling dikaitkan dengannya.",
        pairs: [
          { left: "Karl Marx", right: "Materialisme" },
          { left: "Plato", right: "Idealisme" },
          { left: "Baruch Spinoza", right: "Determinisme" },
          { left: "Rene Descartes", right: "Dualisme tubuh-pikiran" },
        ],
      },
      {
        type: "widget",
        widget: "GarisWaktuFilsuf",
      },
      {
        type: "takeaways",
        items: [
          "Metafisika menanyakan hakikat keberadaan dan kenyataan.",
          "Materialisme vs idealisme: realitas itu materi atau ide.",
          "Tiga posisi kehendak bebas: determinisme, libertarianisme, kompatibilisme.",
          "Isu ini berdampak pada tanggung jawab moral dan hukum.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Metafisika terutama menanyakan?",
            options: ["Cara memungut pajak", "Apa yang sungguh-sungguh ada", "Cara berdebat", "Harga barang"],
            answer: 1,
            explain: "Metafisika membahas hakikat keberadaan dan kenyataan.",
          },
          {
            q: "Determinisme berpendapat?",
            options: ["Semua peristiwa ditentukan sebab sebelumnya", "Manusia bebas mutlak", "Tidak ada sebab-akibat", "Realitas adalah ilusi"],
            answer: 0,
            explain: "Determinisme: setiap peristiwa adalah akibat dari sebab sebelumnya.",
          },
          {
            q: "Kompatibilisme berusaha?",
            options: ["Menolak kebebasan", "Menyatukan kebebasan dan sebab-akibat", "Menolak sebab-akibat", "Mengabaikan moral"],
            answer: 1,
            explain: "Kompatibilisme menilai kebebasan tetap mungkin meski ada determinisme.",
          },
          {
            q: "Pandangan bahwa realitas pada dasarnya materi disebut?",
            options: ["Idealisme", "Materialisme", "Skeptisisme", "Empirisme"],
            answer: 1,
            explain: "Materialisme: kenyataan tersusun dari materi.",
          },
          {
            q: "Mengapa kehendak bebas penting secara praktis?",
            options: ["Menentukan harga", "Menyangkut tanggung jawab moral & hukum", "Tidak penting", "Soal selera"],
            answer: 1,
            explain: "Tanpa kehendak bebas, dasar menyalahkan/menghukum menjadi dipertanyakan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "materialisme-vs-idealisme",
    levelId: "metafisika",
    order: 2,
    title: "Materialisme vs Idealisme",
    summary: "Apakah realitas pada dasarnya materi atau ide? Dualisme tubuh-pikiran Descartes dan jawaban monisme.",
    durationMin: 13,
    tags: ["metafisika", "materialisme", "idealisme", "dualisme"],
    blocks: [
      {
        type: "paragraph",
        html: "Salah satu pertanyaan tertua metafisika: apa bahan dasar kenyataan? <strong>Materialisme</strong> menjawab bahwa segala sesuatu pada akhirnya adalah materi dan interaksi fisiknya, termasuk pikiran. <strong>Idealisme</strong> sebaliknya menempatkan ide, kesadaran, atau pikiran sebagai yang paling mendasar, sehingga dunia materi bergantung pada budi yang mengalaminya.",
      },
      {
        type: "video",
        comp: "MaterialismeIdealisme",
        title: "Video: Materialisme vs Idealisme",
        caption: "Dua cara memandang kenyataan: yang utama itu materi, atau ide/pikiran.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_001.jpg?width=400",
        alt: "Potret Karl Marx",
        caption: "Karl Marx, wakil materialisme yang menjadi tesis dalam banyak perdebatan modern tentang hakikat kenyataan.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Plato_Silanion_Musei_Capitolini_MC1377.jpg?width=400",
        alt: "Potret Plato",
        caption: "Plato, wakil idealisme yang menempatkan dunia ide sebagai kenyataan yang paling mendasar.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "paragraph",
        html: "Di tengah keduanya muncul perdebatan <strong>dualisme vs monisme</strong>. <strong>Rene Descartes</strong> mengajukan <strong>dualisme tubuh-pikiran</strong>: tubuh adalah substansi yang berukuran dan menempati ruang (<em>res extensa</em>), sedangkan pikiran adalah substansi yang berpikir dan tidak berukuran (<em>res cogitans</em>). <strong>Monisme</strong> menolak pembagian ini dan menyatakan kenyataan hanya tersusun dari satu jenis substansi, entah seluruhnya materi atau seluruhnya pikiran.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga posisi inti",
        html: "<strong>Materialisme</strong>: yang nyata adalah materi. <strong>Idealisme</strong>: yang nyata adalah ide/pikiran. <strong>Dualisme</strong>: keduanya substansi terpisah yang sama-sama nyata.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Masalah interaksi",
        html: "Kritik klasik atas dualisme Descartes: jika pikiran tak berukuran dan tubuh bersifat fisik, bagaimana keduanya bisa saling memengaruhi? Inilah <strong>problem interaksi</strong> yang sulit dijawab dualisme.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Cara mengingat",
        html: "<em>Materi</em> = benda, <em>idea</em> = pikiran. Dua-listik = dua substansi, mono-istik = satu substansi.",
      },
      {
        type: "paragraph",
        html: "Perdebatan materialisme lawan idealisme paling jernih dipahami lewat <strong>dialektika</strong> ala <strong>G.W.F. Hegel</strong>. Dialektika adalah pola perkembangan ide: sebuah pandangan (<strong>tesis</strong>) memancing pandangan lawan (<strong>antitesis</strong>), lalu keduanya didamaikan dalam pandangan baru yang lebih kaya (<strong>sintesis</strong>). Sintesis itu kemudian menjadi tesis baru, dan proses berputar lagi. Begitulah sejarah pemikiran bergerak dari era ke era.",
      },
      {
        type: "video",
        comp: "DialektikaHegel",
        title: "Video: Dialektika Hegel (Tesis, Antitesis, Sintesis)",
        caption: "Contoh klasik ada, tiada, lalu menjadi: bagaimana dua gagasan berlawanan melahirkan sintesis baru.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Hegel_portrait_by_Schlesinger_1831.jpg?width=400",
        alt: "Potret G.W.F. Hegel",
        caption: "G.W.F. Hegel, pencetus dialektika yang melihat sejarah ide bergerak lewat tesis, antitesis, dan sintesis.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Heraclitus,_Johannes_Moreelse.jpg?width=400",
        alt: "Potret Herakleitos",
        caption: "Herakleitos, filsuf perubahan yang menegaskan segala sesuatu selalu menjadi, gagasan yang menggemakan unsur menjadi dalam dialektika.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pola tesis, antitesis, sintesis",
        html: "<strong>Tesis</strong> adalah pendirian awal. <strong>Antitesis</strong> adalah penyangkalan atau lawannya. <strong>Sintesis</strong> bukan sekadar jalan tengah, melainkan pandangan baru yang menyerap kebenaran kedua sisi sekaligus mengatasinya. Contoh Hegel: <em>ada</em> (tesis) dan <em>tiada</em> (antitesis) berpadu menjadi <em>menjadi</em> (sintesis). Dalam metafisika, <strong>materialisme</strong> sering berperan sebagai tesis dan <strong>idealisme</strong> sebagai antitesis, lalu lahir sintesis seperti monisme dwiaspek.",
      },
      {
        type: "case",
        title: "Studi Kasus: Perkembangan dialektis gagasan kenyataan",
        html: "Lihat bagaimana satu pertanyaan berkembang dari era ke era. <strong>Tesis</strong>: para filsuf alam Yunani dan kemudian materialisme menyatakan kenyataan pada dasarnya adalah materi. <strong>Antitesis</strong>: Plato lalu idealisme Berkeley menjawab bahwa yang paling nyata justru ide dan pikiran. <strong>Sintesis</strong>: Spinoza mengajukan monisme dwiaspek, materi dan pikiran adalah dua sisi dari satu substansi yang sama, dan Hegel menyatukannya dalam idealisme mutlak yang melihat kenyataan sebagai proses budi yang berkembang. Marx kemudian membalik dialektika Hegel menjadi materialisme dialektis, menjadikan sintesis tadi tesis baru. Satu masalah, tetapi jawabannya terus naik tingkat lewat tesis, antitesis, dan sintesis.",
      },
      {
        type: "widget",
        widget: "SimulatorDialektika",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi: tahap dialektika menuju kematangan gagasan (angka ilustratif)",
        unit: "tingkat",
        source: "ilustrasi edukatif",
        note: "Skala konseptual rekaan: sintesis menyerap dan melampaui tesis dan antitesis.",
        data: [
          { label: "Tesis", value: 3, color: "#2563eb" },
          { label: "Antitesis", value: 3, color: "#ef4444" },
          { label: "Sintesis", value: 6, color: "#10b981" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Dalam alur dialektika tentang hakikat kenyataan, tiap pernyataan berperan sebagai apa?",
        buckets: ["Tesis", "Antitesis", "Sintesis"],
        items: [
          { text: "Kenyataan pada dasarnya adalah materi", bucket: "Tesis" },
          { text: "Yang paling nyata justru ide dan pikiran", bucket: "Antitesis" },
          { text: "Materi dan pikiran adalah dua sisi dari satu substansi", bucket: "Sintesis" },
          { text: "Ada dan tiada berpadu menjadi menjadi", bucket: "Sintesis" },
          { text: "Segala sesuatu hanyalah susunan partikel fisik", bucket: "Tesis" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan filsuf dengan peran atau posisinya dalam perkembangan ide.",
        pairs: [
          { left: "G.W.F. Hegel", right: "Pencetus dialektika tesis-antitesis-sintesis" },
          { left: "Karl Marx", right: "Materialisme dialektis" },
          { left: "Plato", right: "Idealisme klasik" },
          { left: "Baruch Spinoza", right: "Monisme dwiaspek" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Ilustrasi: kecenderungan posisi filsuf (angka ilustratif)",
        unit: "%",
        source: "Data ilustratif untuk pembelajaran",
        note: "Angka rekaan untuk menggambarkan sebaran, bukan survei nyata.",
        data: [
          { label: "Materialisme/Fisikalisme", value: 52, color: "#2563eb" },
          { label: "Dualisme", value: 28, color: "#f59e0b" },
          { label: "Idealisme", value: 12, color: "#10b981" },
          { label: "Lainnya", value: 8, color: "#94a3b8" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Rasa sakit di gigi",
        html: "Saat gigi berlubang, ada kerusakan fisik pada saraf (materi) tetapi juga pengalaman <em>rasa sakit</em> yang terasa bagi Anda. <strong>Materialis</strong> berkata rasa sakit itu hanyalah keadaan otak tertentu. <strong>Dualis</strong> berkata pengalaman sakit adalah kejadian mental yang berbeda dari keadaan otak. <strong>Idealis</strong> menekankan bahwa yang benar-benar kita kenal hanyalah pengalaman itu sendiri. Satu peristiwa, tiga tafsir berbeda.",
      },
      {
        type: "calcExercise",
        prompt: "Descartes membagi kenyataan menjadi berapa jenis substansi mendasar?",
        answer: 2,
        tolerance: 0,
        solution: "Dua substansi: <em>res extensa</em> (tubuh/materi) dan <em>res cogitans</em> (pikiran). Karena itu disebut <strong>dualisme</strong>.",
        hint: "Awalan 'du-' pada kata dualisme.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan ke posisi yang sesuai.",
        buckets: ["Materialisme", "Idealisme", "Dualisme"],
        items: [
          { text: "Pikiran hanyalah hasil kerja kimiawi otak", bucket: "Materialisme" },
          { text: "Tubuh dan pikiran adalah dua substansi terpisah", bucket: "Dualisme" },
          { text: "Dunia hanya ada sejauh dialami oleh kesadaran", bucket: "Idealisme" },
          { text: "Segala sesuatu pada akhirnya tersusun dari partikel fisik", bucket: "Materialisme" },
          { text: "Pikiran yang tak berukuran bisa terpisah dari tubuh", bucket: "Dualisme" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Materialisme menempatkan materi sebagai dasar kenyataan.",
          "Idealisme menempatkan ide/pikiran sebagai dasar kenyataan.",
          "Descartes mengajukan dualisme: res extensa dan res cogitans.",
          "Monisme menyatakan hanya ada satu jenis substansi.",
          "Problem interaksi adalah kritik utama atas dualisme.",
          "Dialektika Hegel: tesis bertemu antitesis lalu lahir sintesis.",
          "Materialisme kerap jadi tesis, idealisme antitesis, sintesisnya antara lain monisme dwiaspek.",
          "Sejarah ide bergerak dari era ke era lewat putaran dialektis ini.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Materialisme berpendapat bahwa yang paling mendasar adalah?",
            options: ["Ide", "Materi", "Tuhan", "Bahasa"],
            answer: 1,
            explain: "Materialisme: kenyataan pada dasarnya tersusun dari materi.",
          },
          {
            q: "Dalam dualisme Descartes, pikiran disebut?",
            options: ["Res extensa", "Res cogitans", "Res publica", "Res nullius"],
            answer: 1,
            explain: "Pikiran adalah res cogitans (substansi yang berpikir); tubuh adalah res extensa.",
          },
          {
            q: "Idealisme menekankan bahwa yang paling nyata adalah?",
            options: ["Atom", "Energi", "Ide atau pikiran", "Uang"],
            answer: 2,
            explain: "Idealisme menempatkan ide/kesadaran sebagai yang paling mendasar.",
          },
          {
            q: "Monisme menyatakan bahwa kenyataan tersusun dari?",
            options: ["Dua substansi", "Tiga substansi", "Satu jenis substansi", "Tanpa substansi"],
            answer: 2,
            explain: "Monisme: hanya ada satu jenis substansi dasar.",
          },
          {
            q: "Kritik utama atas dualisme tubuh-pikiran adalah?",
            options: ["Terlalu murah", "Problem interaksi", "Tidak logis sama sekali", "Soal bahasa"],
            answer: 1,
            explain: "Sulit menjelaskan bagaimana pikiran tak berukuran dapat memengaruhi tubuh fisik.",
          },
          {
            q: "Dalam dialektika Hegel, hasil perpaduan tesis dan antitesis disebut?",
            options: ["Hipotesis", "Sintesis", "Analisis", "Parentesis"],
            answer: 1,
            explain: "Sintesis adalah pandangan baru yang menyerap dan melampaui tesis serta antitesis.",
          },
          {
            q: "Contoh dialektika Hegel ada lalu tiada menghasilkan?",
            options: ["Kekal", "Menjadi", "Diam", "Hampa"],
            answer: 1,
            explain: "Ada (tesis) dan tiada (antitesis) berpadu menjadi menjadi (sintesis).",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "identitas-diri",
    levelId: "metafisika",
    order: 3,
    title: "Identitas Diri Sepanjang Waktu",
    summary: "Apa yang membuat seseorang tetap 'dirinya' meski berubah? Ship of Theseus serta teori memori vs tubuh.",
    durationMin: 13,
    tags: ["metafisika", "identitas", "diri", "memori"],
    blocks: [
      {
        type: "paragraph",
        html: "Sel-sel tubuh Anda berganti, kepribadian berubah, kenangan memudar. Namun kita tetap menganggap diri kita hari ini adalah orang yang sama dengan diri kita sepuluh tahun lalu. Pertanyaan <strong>identitas pribadi</strong> menanyakan: apa sebenarnya yang membuat seseorang <strong>tetap dirinya</strong> sepanjang waktu meskipun terus berubah?",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Heraclitus,_Johannes_Moreelse.jpg?width=400",
        alt: "Potret Herakleitos",
        caption: "Herakleitos, filsuf perubahan yang berkata kita tak bisa menginjak sungai yang sama dua kali, gambaran tajam tentang diri yang terus menjadi.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "DialektikaHegel",
        title: "Video: Perubahan dan Menjadi (Dialektika)",
        caption: "Gagasan menjadi membantu memahami bagaimana sesuatu berubah namun tetap bisa disebut satu identitas.",
      },
      {
        type: "paragraph",
        html: "Dua jawaban besar bersaing. <strong>Teori memori</strong> (sering dikaitkan dengan John Locke) menyatakan yang menjadikan Anda tetap sama adalah <strong>kesinambungan ingatan dan kesadaran</strong>. <strong>Teori tubuh/biologis</strong> menyatakan identitas terletak pada kelangsungan organisme atau otak fisik yang sama. Keduanya menabrak kasus-kasus sulit yang menguji batas intuisi kita.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Plato_Silanion_Musei_Capitolini_MC1377.jpg?width=400",
        alt: "Potret Plato",
        caption: "Plato, yang memandang jiwa sebagai inti diri yang kekal dan menjadi dasar identitas seseorang.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua kriteria identitas",
        html: "<strong>Kriteria psikologis (memori)</strong>: sama bila ada kesinambungan ingatan/kesadaran. <strong>Kriteria fisik (tubuh)</strong>: sama bila tubuh atau otak yang sama berlanjut.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa penting",
        html: "Identitas diri menyangkut tanggung jawab: apakah adil menghukum seseorang atas perbuatan masa lalu jika ia 'sudah menjadi orang lain'? Juga relevan untuk warisan, janji, dan hubungan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati intuisi",
        html: "Kasus pikiran (thought experiment) seperti pertukaran ingatan bisa membuat teori memori dan teori tubuh memberi jawaban berlawanan. Tidak ada jawaban yang lolos semua kasus tanpa biaya.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi: pergantian komponen kapal Theseus per tahun (angka ilustratif)",
        unit: "papan",
        source: "Data ilustratif untuk pembelajaran",
        note: "Setelah beberapa tahun seluruh 100 papan asli telah diganti.",
        data: [
          { label: "Tahun 1", value: 20, color: "#2563eb" },
          { label: "Tahun 2", value: 40, color: "#2563eb" },
          { label: "Tahun 3", value: 70, color: "#f59e0b" },
          { label: "Tahun 4", value: 100, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Ship of Theseus (Kapal Theseus)",
        html: "Sebuah kapal kayu dipelihara bertahun-tahun. Setiap papan yang lapuk diganti satu per satu hingga akhirnya <strong>tidak ada satu pun papan asli</strong> yang tersisa. Apakah kapal itu masih kapal yang sama? Lalu muncul versi lebih tajam: seseorang mengumpulkan semua papan lama yang dibuang dan merakitnya kembali menjadi sebuah kapal. <strong>Kapal mana yang merupakan kapal Theseus asli</strong>: yang papannya terus diganti, atau yang dirakit dari papan asli? Kasus ini menggambarkan betapa sulit menetapkan apa yang membuat sesuatu (atau seseorang) tetap identitasnya.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah kapal punya 100 papan. Setiap tahun 20 papan asli diganti yang baru. Setelah berapa tahun seluruh papan asli sudah tergantikan?",
        answer: 5,
        tolerance: 0,
        solution: "100 papan dibagi 20 papan per tahun = 5 tahun. Setelah tahun ke-5 tidak ada papan asli tersisa.",
        hint: "Bagi total papan dengan jumlah yang diganti tiap tahun.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan penjelasannya.",
        pairs: [
          { left: "Teori memori", right: "Identitas dijaga oleh kesinambungan ingatan" },
          { left: "Teori tubuh", right: "Identitas dijaga oleh tubuh/otak yang sama" },
          { left: "Ship of Theseus", right: "Kasus tentang penggantian bagian secara bertahap" },
          { left: "John Locke", right: "Tokoh yang menautkan diri dengan kesadaran" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Ilustrasi: bobot intuisi orang atas kriteria identitas (angka ilustratif)",
        unit: "%",
        source: "ilustrasi edukatif",
        note: "Angka rekaan untuk menggambarkan kecenderungan intuisi, bukan survei nyata.",
        data: [
          { label: "Kriteria memori", value: 55, color: "#2563eb" },
          { label: "Kriteria tubuh/otak", value: 35, color: "#f59e0b" },
          { label: "Tidak yakin", value: 10, color: "#94a3b8" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini mendukung teori identitas yang mana?",
        buckets: ["Teori Memori", "Teori Tubuh"],
        items: [
          { text: "Saya tetap saya karena ingat pengalaman masa lalu saya", bucket: "Teori Memori" },
          { text: "Saya tetap saya selama otak yang sama berlanjut", bucket: "Teori Tubuh" },
          { text: "Kesinambungan kesadaran menjaga identitas", bucket: "Teori Memori" },
          { text: "Organisme biologis yang sama yang membuat saya tetap saya", bucket: "Teori Tubuh" },
        ],
      },
      {
        type: "widget",
        widget: "TebakFilsuf",
      },
      {
        type: "takeaways",
        items: [
          "Identitas pribadi menanyakan apa yang membuat seseorang tetap sama.",
          "Teori memori: kesinambungan ingatan dan kesadaran.",
          "Teori tubuh: kelangsungan organisme atau otak yang sama.",
          "Ship of Theseus menguji identitas saat semua bagian diganti.",
          "Isu ini berdampak pada tanggung jawab moral dan hukum.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pertanyaan inti identitas pribadi adalah?",
            options: ["Berapa berat tubuh", "Apa yang membuat seseorang tetap dirinya sepanjang waktu", "Cara mengubah nama", "Harga identitas"],
            answer: 1,
            explain: "Identitas pribadi menyangkut kesamaan diri dari waktu ke waktu.",
          },
          {
            q: "Teori memori mengaitkan identitas dengan?",
            options: ["Tubuh fisik", "Kesinambungan ingatan/kesadaran", "Nama keluarga", "Alamat"],
            answer: 1,
            explain: "Teori memori (a la Locke) menekankan kesinambungan kesadaran dan ingatan.",
          },
          {
            q: "Ship of Theseus menggambarkan masalah?",
            options: ["Ekonomi pelayaran", "Identitas ketika semua bagian diganti", "Cuaca laut", "Hukum dagang"],
            answer: 1,
            explain: "Kapal yang seluruh papannya diganti menguji apakah ia tetap kapal yang sama.",
          },
          {
            q: "Teori tubuh berpendapat identitas terletak pada?",
            options: ["Ingatan", "Tubuh atau otak yang berlanjut sama", "Perasaan", "Status sosial"],
            answer: 1,
            explain: "Teori tubuh menekankan kelangsungan organisme atau otak fisik.",
          },
          {
            q: "Mengapa identitas pribadi penting secara praktis?",
            options: ["Menentukan harga", "Menyangkut tanggung jawab moral dan hukum", "Tidak penting", "Soal selera"],
            answer: 1,
            explain: "Tanggung jawab atas perbuatan masa lalu bergantung pada kesamaan diri.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "filsafat-pikiran",
    levelId: "metafisika",
    order: 4,
    title: "Filsafat Pikiran & Kesadaran",
    summary: "Kesadaran dan hard problem of consciousness, AI dan apakah mesin bisa berpikir: Turing Test dan Chinese Room.",
    durationMin: 14,
    tags: ["filsafat pikiran", "kesadaran", "AI", "Turing"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Filsafat pikiran</strong> mempelajari hakikat <strong>kesadaran</strong> dan hubungannya dengan otak. Sebagian persoalan relatif mudah, misalnya menjelaskan bagaimana otak memproses informasi. Namun ada <strong>hard problem of consciousness</strong> (David Chalmers): mengapa proses fisik di otak disertai pengalaman subjektif, rasa <em>seperti apa</em> melihat warna merah atau merasakan sakit?",
      },
      {
        type: "video",
        comp: "MaterialismeIdealisme",
        title: "Video: Materialisme vs Idealisme",
        caption: "Apakah pikiran sekadar materi otak, atau justru kesadaran yang paling mendasar? Inti filsafat pikiran.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/George_Berkeley_by_John_Smibert.jpg?width=400",
        alt: "Potret George Berkeley",
        caption: "George Berkeley, idealis yang menyatakan ada adalah dipersepsi, sehingga pikiran lebih mendasar daripada materi.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "paragraph",
        html: "Pertanyaan ini menjadi tajam ketika kita bertanya: <strong>apakah mesin bisa berpikir</strong>? <strong>Alan Turing</strong> mengusulkan ujian perilaku: jika sebuah mesin lewat percakapan tak bisa dibedakan dari manusia, ia layak disebut 'berpikir' (<strong>Turing Test</strong>). <strong>John Searle</strong> membantah lewat argumen <strong>Chinese Room</strong>: memanipulasi simbol sesuai aturan bukanlah <em>memahami</em> maknanya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Baruch_de_Spinoza.jpg?width=400",
        alt: "Potret Baruch Spinoza",
        caption: "Baruch Spinoza, pengusung monisme dwiaspek yang memandang pikiran dan tubuh sebagai dua sisi dari satu kenyataan yang sama.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Istilah kunci",
        html: "<strong>Hard problem</strong>: mengapa ada pengalaman subjektif. <strong>Turing Test</strong>: uji apakah mesin tak terbedakan dari manusia dalam percakapan. <strong>Chinese Room</strong>: simulasi pemahaman bukan pemahaman sejati.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Sintaks vs semantik",
        html: "Inti argumen Searle: komputer hanya mengolah <strong>sintaks</strong> (bentuk simbol), sedangkan pikiran memiliki <strong>semantik</strong> (makna). Mengikuti aturan tidak otomatis berarti mengerti.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Cara mengingat",
        html: "Turing menguji dari <em>luar</em> (perilaku), Searle menyoroti dari <em>dalam</em> (apakah ada pemahaman). Keduanya soal yang sama dari sisi berbeda.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Ilustrasi: skor 'lolos uji peniruan' menurut penilai (angka ilustratif)",
        unit: "%",
        source: "Data ilustratif untuk pembelajaran",
        note: "Angka rekaan untuk menggambarkan tren, bukan hasil eksperimen nyata.",
        data: [
          { label: "Sistem 2010", value: 20, color: "#2563eb" },
          { label: "Sistem 2015", value: 35, color: "#2563eb" },
          { label: "Sistem 2020", value: 55, color: "#f59e0b" },
          { label: "Sistem 2025", value: 75, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Chinese Room (Kamar Cina) John Searle",
        html: "Bayangkan seseorang yang tidak mengerti bahasa Mandarin dikurung dalam sebuah kamar. Ia menerima kertas berisi simbol Mandarin dan, dengan mengikuti buku aturan berbahasa Inggris, menyusun simbol balasan yang tepat. Bagi orang di luar, jawaban dari kamar itu tampak fasih seakan kamar tersebut <em>memahami</em> Mandarin. Padahal orang di dalam sama sekali tidak mengerti makna apa pun, ia hanya mencocokkan bentuk. <strong>Searle</strong> menyimpulkan: komputer yang menjalankan program juga begitu. Lulus Turing Test belum membuktikan adanya pemahaman atau kesadaran sejati.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah uji peniruan memakai 10 penilai. Mesin dianggap 'lolos' jika menipu minimal 30% penilai. Berapa jumlah penilai minimal yang harus tertipu?",
        answer: 3,
        tolerance: 0,
        solution: "30% dari 10 penilai = 0,30 x 10 = 3 penilai. Jadi minimal 3 penilai harus tertipu.",
        hint: "Hitung 30 persen dari 10.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini paling dekat dengan gagasan siapa/apa?",
        buckets: ["Turing Test", "Chinese Room", "Hard Problem"],
        items: [
          { text: "Jika tak terbedakan dari manusia dalam percakapan, sebut saja berpikir", bucket: "Turing Test" },
          { text: "Mengikuti aturan simbol tidak sama dengan memahami makna", bucket: "Chinese Room" },
          { text: "Mengapa proses otak disertai pengalaman subjektif sama sekali", bucket: "Hard Problem" },
          { text: "Penilaian kecerdasan mesin lewat tes perilaku percakapan", bucket: "Turing Test" },
          { text: "Sintaks tanpa semantik bukanlah pemahaman", bucket: "Chinese Room" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi: fokus tiga gagasan kunci filsafat pikiran (angka ilustratif)",
        unit: "bobot",
        source: "ilustrasi edukatif",
        note: "Skala konseptual rekaan untuk membandingkan penekanan tiap gagasan.",
        data: [
          { label: "Turing Test (perilaku)", value: 5, color: "#2563eb" },
          { label: "Chinese Room (makna)", value: 7, color: "#f59e0b" },
          { label: "Hard Problem (pengalaman)", value: 9, color: "#10b981" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh atau gagasan dengan rumusannya.",
        pairs: [
          { left: "Alan Turing", right: "Turing Test" },
          { left: "John Searle", right: "Chinese Room" },
          { left: "David Chalmers", right: "Hard problem of consciousness" },
          { left: "George Berkeley", right: "Idealisme: ada adalah dipersepsi" },
        ],
      },
      {
        type: "widget",
        widget: "PencocokAliranFilsafat",
      },
      {
        type: "takeaways",
        items: [
          "Filsafat pikiran mengkaji kesadaran dan hubungannya dengan otak.",
          "Hard problem: mengapa ada pengalaman subjektif sama sekali.",
          "Turing Test menilai kecerdasan mesin dari perilaku percakapan.",
          "Chinese Room (Searle): simulasi pemahaman bukan pemahaman sejati.",
          "Inti perdebatan: apakah sintaks bisa menghasilkan semantik.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Hard problem of consciousness menyangkut?",
            options: ["Kecepatan otak", "Mengapa ada pengalaman subjektif", "Biaya riset otak", "Ukuran otak"],
            answer: 1,
            explain: "Hard problem menanyakan mengapa proses fisik disertai pengalaman subjektif.",
          },
          {
            q: "Turing Test menilai mesin berdasarkan?",
            options: ["Berat perangkat", "Apakah ia tak terbedakan dari manusia dalam percakapan", "Harga komputer", "Jumlah kabel"],
            answer: 1,
            explain: "Turing mengusulkan uji perilaku percakapan untuk menilai 'berpikir'.",
          },
          {
            q: "Argumen Chinese Room dikemukakan oleh?",
            options: ["Alan Turing", "John Searle", "David Hume", "Rene Descartes"],
            answer: 1,
            explain: "John Searle merumuskan eksperimen pikiran Chinese Room.",
          },
          {
            q: "Inti kritik Chinese Room adalah?",
            options: ["Mesin terlalu lambat", "Memanipulasi simbol bukan memahami makna", "Mesin terlalu mahal", "Bahasa Mandarin sulit"],
            answer: 1,
            explain: "Mengolah sintaks tidak otomatis menghasilkan semantik/pemahaman.",
          },
          {
            q: "Perbedaan sudut pandang Turing dan Searle adalah?",
            options: ["Keduanya identik", "Turing menilai dari perilaku luar, Searle menyoroti pemahaman dalam", "Keduanya menolak AI", "Tidak ada kaitan"],
            answer: 1,
            explain: "Turing menguji perilaku eksternal; Searle mempersoalkan ada-tidaknya pemahaman internal.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "argumen-keberadaan-tuhan",
    levelId: "metafisika",
    order: 5,
    title: "Argumen Keberadaan Tuhan",
    summary: "Tiga argumen klasik metafisika tentang wujud tertinggi: kosmologis, ontologis, dan teleologis, beserta kritik klasik dari Kant dan Hume.",
    durationMin: 14,
    tags: ["metafisika", "Tuhan", "argumen kosmologis", "argumen ontologis"],
    blocks: [
      {
        type: "paragraph",
        html: "Salah satu pertanyaan metafisika terbesar adalah apakah ada wujud tertinggi atau penyebab pertama dari segala yang ada. Sepanjang sejarah, filsuf merumuskan tiga jenis argumen utama: <strong>kosmologis</strong>, <strong>ontologis</strong>, dan <strong>teleologis</strong>. Penting dicatat, ini adalah kajian penalaran filosofis, bukan urusan iman semata.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga argumen klasik",
        html: "<strong>Kosmologis</strong>: alam butuh penyebab pertama. <strong>Ontologis</strong>: dari konsep wujud sempurna disimpulkan keberadaannya. <strong>Teleologis</strong>: keteraturan alam menyiratkan adanya perancang.",
      },
      {
        type: "paragraph",
        html: "Argumen <strong>kosmologis</strong> berangkat dari sebab-akibat: segala sesuatu punya sebab, dan rantai sebab tidak mungkin mundur tak terhingga, maka harus ada <strong>penyebab pertama</strong>. <strong>Aristoteles</strong> menyebutnya 'penggerak yang tak tergerak', dan <strong>Thomas Aquinas</strong> mengembangkannya dalam Lima Jalan (Quinque viae) pada abad ke-13.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg?width=400",
        alt: "Potret patung Aristoteles",
        caption: "Aristoteles, perumus gagasan 'penggerak yang tak tergerak' yang mengawali argumen kosmologis.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "info",
        title: "Argumen ontologis dan kritik Kant",
        html: "<strong>Anselmus dari Canterbury</strong> (abad ke-11) berargumen: Tuhan adalah 'sesuatu yang lebih besar darinya tak terbayangkan', dan wujud yang ada nyata lebih besar daripada yang hanya ada dalam pikiran. <strong>Immanuel Kant</strong> menolaknya dengan tegas: 'ada' bukanlah sifat (predikat) yang menambah kesempurnaan sebuah konsep.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Immanuel_Kant_(painted_portrait).jpg?width=400",
        alt: "Potret Immanuel Kant",
        caption: "Immanuel Kant, pengkritik argumen ontologis dengan tesis 'ada bukan predikat'.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Argumen teleologis dan kritik Hume",
        html: "Argumen <strong>teleologis</strong> (desain) dirumuskan tajam oleh <strong>William Paley</strong> lewat perumpamaan jam tangan. <strong>David Hume</strong> mengkritiknya: keteraturan alam bisa lahir dari sebab lain, dan analogi alam dengan mesin buatan manusia rapuh. Belakangan, teori evolusi Darwin memberi penjelasan alternatif atas keteraturan makhluk hidup.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/David_Hume.jpg?width=400",
        alt: "Potret David Hume",
        caption: "David Hume, pengkritik argumen desain dalam Dialog tentang Agama Alamiah.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "video",
        comp: "DialektikaHegel",
        title: "Video: Tesis, Antitesis, Sintesis",
        caption: "Argumen dan kritiknya bergerak dialektis: setiap argumen memicu sanggahan, lalu rumusan yang lebih cermat.",
      },
      { type: "widget", widget: "GarisWaktuFilsuf" },
      {
        type: "chart",
        variant: "bar",
        title: "Garis waktu tokoh argumen keberadaan Tuhan (tahun lahir)",
        unit: "tahun lahir",
        source: "Tahun lahir historis para tokoh",
        note: "Argumen dan kritik saling menanggapi dari abad ke abad, dari Anselmus hingga Kant dan Paley.",
        data: [
          { label: "Anselmus", value: 1033, color: "#6366f1" },
          { label: "Thomas Aquinas", value: 1225, color: "#0ea5e9" },
          { label: "Descartes", value: 1596, color: "#10b981" },
          { label: "Hume", value: 1711, color: "#f59e0b" },
          { label: "Kant", value: 1724, color: "#ec4899" },
          { label: "Paley", value: 1743, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Jam tangan Paley",
        html: "Bayangkan kamu menemukan sebuah <strong>jam tangan</strong> tergeletak di padang. Mekanismenya yang rumit dan teratur membuatmu menyimpulkan pasti ada <strong>pembuatnya</strong>, bukan terbentuk acak. <strong>Paley</strong> berargumen alam yang jauh lebih teratur pun menyiratkan perancang. <strong>Hume</strong> membantah: alam bukan jam tangan, dan dari satu kasus alam semesta kita tak bisa menyimpulkan analogi mesin secara sah. Satu perumpamaan, dua tafsir yang berbeda.",
      },
      {
        type: "calcExercise",
        prompt: "Thomas Aquinas merumuskan argumennya dalam 'Quinque viae'. Berapa jumlah jalan (argumen) yang ia susun?",
        answer: 5,
        tolerance: 0,
        solution: "'Quinque' berarti lima, jadi Aquinas menyusun <strong>5</strong> jalan menuju kesimpulan adanya penyebab pertama.",
        hint: "'Quinque' dalam bahasa Latin berarti lima.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini termasuk jenis argumen yang mana?",
        buckets: ["Kosmologis", "Ontologis", "Teleologis"],
        items: [
          { text: "Rantai sebab tak mungkin tak berujung, maka ada penyebab pertama", bucket: "Kosmologis" },
          { text: "Keteraturan rumit alam menyiratkan adanya perancang", bucket: "Teleologis" },
          { text: "Wujud sempurna yang ada nyata lebih besar daripada yang hanya dipikirkan", bucket: "Ontologis" },
          { text: "Harus ada penggerak yang tak tergerak di awal segala gerak", bucket: "Kosmologis" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh dengan peran atau gagasannya.",
        pairs: [
          { left: "Anselmus", right: "Perumus argumen ontologis" },
          { left: "Thomas Aquinas", right: "Lima Jalan (argumen kosmologis)" },
          { left: "William Paley", right: "Perumpamaan jam tangan (teleologis)" },
          { left: "Immanuel Kant", right: "Kritik: 'ada' bukan predikat" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Tiga argumen klasik: kosmologis, ontologis, dan teleologis.",
          "Kosmologis (Aristoteles, Aquinas): alam butuh penyebab pertama.",
          "Ontologis (Anselmus): dari konsep wujud sempurna ke keberadaannya.",
          "Teleologis (Paley): keteraturan menyiratkan perancang.",
          "Kant mengkritik ontologis, Hume mengkritik teleologis.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Argumen kosmologis menyimpulkan adanya?",
            options: ["Banyak dunia", "Penyebab pertama", "Perancang jam", "Ide bawaan"],
            answer: 1,
            explain: "Kosmologis menuntut penyebab pertama karena rantai sebab tak bisa mundur tanpa batas.",
          },
          {
            q: "Siapa perumus argumen ontologis?",
            options: ["Anselmus", "Paley", "Hume", "Aristoteles"],
            answer: 0,
            explain: "Anselmus dari Canterbury merumuskan argumen ontologis.",
          },
          {
            q: "Perumpamaan jam tangan adalah inti argumen?",
            options: ["Kosmologis", "Ontologis", "Teleologis", "Moral"],
            answer: 2,
            explain: "Paley memakai jam tangan untuk argumen teleologis (desain).",
          },
          {
            q: "Kritik Kant atas argumen ontologis adalah?",
            options: ["Tuhan tidak sempurna", "'Ada' bukan predikat yang menambah kesempurnaan", "Alam tidak teratur", "Sebab tidak ada"],
            answer: 1,
            explain: "Bagi Kant, keberadaan bukan sifat yang bisa menambah konsep.",
          },
          {
            q: "Tokoh yang mengkritik argumen desain (teleologis) adalah?",
            options: ["Anselmus", "Aquinas", "David Hume", "Paley"],
            answer: 2,
            explain: "Hume membantah analogi alam dengan mesin buatan manusia.",
          },
        ],
      },
    ],
  },
];
