import type { Lesson } from "../../../types";

export const level5: Lesson[] = [
  // ============================================================
  {
    id: "filsafat-dan-kehidupan",
    levelId: "terapan",
    order: 1,
    title: "Filsafat & Makna Hidup",
    summary: "Eksistensialisme dan pencarian makna, filsafat Timur, serta Pancasila sebagai filsafat bangsa. Dengan video & pencocok aliran.",
    durationMin: 14,
    tags: ["eksistensialisme", "makna hidup", "Pancasila"],
    blocks: [
      {
        type: "paragraph",
        html: "Filsafat tidak berhenti di teori; ia menjawab pertanyaan paling personal: <strong>untuk apa hidup ini?</strong> Aliran <strong>eksistensialisme</strong> menegaskan bahwa manusia menciptakan maknanya sendiri lewat pilihan bebas dan tanggung jawab.",
      },
      {
        type: "video",
        comp: "DilemaTrolley",
        title: "Video: Dilema Trolley",
        caption: "Animasi eksperimen pikiran klasik yang menguji intuisi moral kita.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Eksistensialisme",
        html: "Sartre: <strong>'eksistensi mendahului esensi'</strong>, manusia ada dulu, baru menentukan siapa dirinya lewat pilihan. Camus menambahkan: meski hidup tampak absurd, kita bisa memberinya makna dengan menjalaninya secara sadar.",
      },
      {
        type: "video",
        comp: "EksistensialismeVideo",
        title: "Video: Eksistensialisme & Makna Hidup",
        caption: "Eksistensi mendahului esensi, kebebasan, makna, dan absurditas dijelaskan secara ringkas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Akar gagasan eksistensialisme",
        html: "Tema ini berkembang dari era ke era: <strong>Soren Kierkegaard</strong> (abad ke-19) menekankan pilihan personal dan iman, lalu <strong>Friedrich Nietzsche</strong> menggugat nilai lama, dan pada abad ke-20 <strong>Sartre</strong> serta <strong>Camus</strong> merumuskan kebebasan dan absurditas secara penuh.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Kierkegaard.jpg?width=400",
        alt: "Potret Soren Kierkegaard",
        caption: "Soren Kierkegaard, perintis tema eksistensialis tentang pilihan personal",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "info",
        title: "Filsafat Timur & Pancasila",
        html: "Filsafat tidak hanya Barat. Tradisi Timur (Konfusianisme, Buddhisme) menekankan keselarasan dan etika hidup. Di Indonesia, <strong>Pancasila</strong> adalah filsafat bangsa yang memadukan ketuhanan, kemanusiaan, persatuan, kerakyatan, dan keadilan.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Confucius_Tang_Dynasty.jpg?width=400",
        alt: "Potret Konfusius",
        caption: "Konfusius, peletak dasar Konfusianisme yang menekankan keselarasan dan etika hubungan",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba pencocoknya",
        html: "Jawab beberapa pertanyaan untuk melihat aliran filsafat mana yang paling dekat dengan cara berpikirmu.",
      },
      { type: "widget", widget: "PencocokAliranFilsafat" },
      {
        type: "case",
        title: "Studi Kasus: Mencari makna dalam kesulitan",
        html: "Viktor Frankl, yang selamat dari kamp konsentrasi, menyimpulkan bahwa manusia bisa bertahan dalam penderitaan terberat asalkan menemukan <strong>makna</strong>. Ini sejalan dengan eksistensialisme: makna bukan diberikan, melainkan ditemukan dan diciptakan lewat sikap kita terhadap hidup. Filsafat menjadi sangat praktis di sini.",
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan ini lebih dekat ke aliran yang mana?",
        buckets: ["Eksistensialisme", "Filsafat Timur/Pancasila"],
        items: [
          { text: "Manusia menciptakan makna lewat pilihan bebas", bucket: "Eksistensialisme" },
          { text: "Keselarasan dan gotong royong dalam masyarakat", bucket: "Filsafat Timur/Pancasila" },
          { text: "Eksistensi mendahului esensi", bucket: "Eksistensialisme" },
          { text: "Keadilan sosial bagi seluruh rakyat", bucket: "Filsafat Timur/Pancasila" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan tokoh atau gagasan dengan intinya.",
        pairs: [
          { left: "Sartre", right: "Eksistensi mendahului esensi" },
          { left: "Camus", right: "Absurditas dan menjalani hidup secara sadar" },
          { left: "Konfusius", right: "Keselarasan dan etika hubungan" },
          { left: "Pancasila", right: "Filsafat bangsa dengan lima sila" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Filsafat menjawab pertanyaan praktis tentang makna hidup.",
          "Eksistensialisme: manusia menciptakan makna lewat pilihan bebas.",
          "Filsafat Timur menekankan keselarasan dan etika hidup.",
          "Pancasila adalah filsafat bangsa Indonesia dengan lima sila.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti eksistensialisme adalah?",
            options: ["Makna sudah ditentukan", "Manusia menciptakan makna lewat pilihan", "Hidup tanpa tujuan", "Mengikuti tradisi saja"],
            answer: 1,
            explain: "Eksistensialisme menegaskan manusia memberi makna lewat pilihan bebas.",
          },
          {
            q: "Menurut eksistensialisme, kebebasan memilih membuat manusia?",
            options: [
              "Lepas dari tanggung jawab",
              "Bertanggung jawab atas pilihannya",
              "Ditentukan nasib",
              "Tak perlu bertindak",
            ],
            answer: 1,
            explain: "Kebebasan eksistensial selalu disertai tanggung jawab atas setiap pilihan yang diambil.",
          },
          {
            q: "Pancasila bagi Indonesia berfungsi sebagai?",
            options: ["Sekadar slogan", "Filsafat dan dasar negara", "Teori ekonomi", "Aliran seni"],
            answer: 1,
            explain: "Pancasila adalah filsafat bangsa dan dasar negara Indonesia.",
          },
          {
            q: "Pelajaran Viktor Frankl tentang penderitaan?",
            options: ["Hidup tak bermakna", "Makna membantu manusia bertahan", "Hindari semua kesulitan", "Makna mustahil ditemukan"],
            answer: 1,
            explain: "Menemukan makna membantu manusia bertahan bahkan dalam penderitaan.",
          },
          {
            q: "Pancasila terdiri dari berapa sila?",
            options: ["3", "5", "7", "10"],
            answer: 1,
            explain: "Panca (lima) sila (dasar) = 5 sila.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "eksistensialisme",
    levelId: "terapan",
    order: 2,
    title: "Eksistensialisme & Kebebasan",
    summary: "Kierkegaard, Nietzsche, Sartre, dan Camus tentang kebebasan, absurditas, dan penciptaan makna. Dengan pencocok aliran & grafik.",
    durationMin: 13,
    tags: ["eksistensialisme", "kebebasan", "absurditas"],
    blocks: [
      {
        type: "paragraph",
        html: "Eksistensialisme adalah aliran yang menempatkan <strong>individu yang bebas dan bertanggung jawab</strong> sebagai pusat. Berakar pada Soren Kierkegaard yang menekankan pilihan personal dan iman, aliran ini berkembang lewat Friedrich Nietzsche, Jean-Paul Sartre, hingga Albert Camus.",
      },
      {
        type: "video",
        comp: "EksistensialismeVideo",
        title: "Video: Eksistensialisme & Kebebasan",
        caption: "Eksistensi mendahului esensi, kebebasan, makna, dan absurditas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Perkembangan dari era ke era",
        html: "Gagasan ini berevolusi: <strong>Kierkegaard</strong> (abad ke-19) memulai dengan pilihan dan iman, <strong>Nietzsche</strong> menggugat nilai lama dan menyerukan penciptaan nilai baru, lalu di abad ke-20 <strong>Sartre</strong> merumuskan kebebasan radikal dan <strong>Camus</strong> menjawab absurditas. Tiap tokoh membangun di atas pertanyaan yang ditinggalkan pendahulunya.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Kierkegaard.jpg?width=400",
        alt: "Potret Soren Kierkegaard",
        caption: "Soren Kierkegaard, perintis eksistensialisme lewat tema pilihan personal dan iman",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "paragraph",
        html: "Slogan paling terkenal datang dari Sartre: <strong>'eksistensi mendahului esensi'</strong>. Artinya, manusia tidak lahir dengan tujuan yang sudah jadi; ia ada lebih dulu, lalu menciptakan dirinya lewat tindakan dan pilihan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Eksistensi mendahului esensi",
        html: "Berbeda dari benda buatan (gunting dibuat untuk memotong), manusia tidak punya fungsi bawaan. Bagi <strong>Sartre</strong>, kita 'dihukum untuk bebas': setiap pilihan adalah tanggung jawab penuh kita.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Camus & absurditas",
        html: "Albert <strong>Camus</strong> menyebut benturan antara kerinduan manusia akan makna dan diamnya alam semesta sebagai <strong>absurditas</strong>. Solusinya bukan bunuh diri atau lari ke ilusi, melainkan memberontak dengan menjalani hidup secara sadar dan penuh.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Nietzsche187a.jpg?width=400",
        alt: "Potret Friedrich Nietzsche",
        caption: "Friedrich Nietzsche, penggugat nilai lama dan penyeru penciptaan nilai baru",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bukan nihilisme pasif",
        html: "Kebebasan tanpa tanggung jawab menjadi sekadar kekosongan. Eksistensialisme menuntut keberanian memilih, bukan menyerah pada kehampaan.",
      },
      { type: "widget", widget: "PencocokAliranFilsafat" },
      {
        type: "case",
        title: "Studi Kasus: Memilih jalan hidup sendiri",
        html: "Seorang mahasiswa diterima di jurusan yang diinginkan orang tuanya, tetapi hatinya tertarik pada bidang lain. Dalam kerangka Sartre, ia tidak bisa berlindung di balik 'sudah ditakdirkan' atau 'disuruh orang tua'. Ia <strong>bebas memilih</strong> dan harus menanggung konsekuensinya. Camus menambahkan bahwa meski tidak ada jawaban pasti tentang jalan 'benar', ia tetap bisa memberi makna dengan menjalani pilihannya secara sadar.",
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan tokoh dengan gagasan utamanya.",
        pairs: [
          { left: "Kierkegaard", right: "Pilihan personal dan iman" },
          { left: "Nietzsche", right: "Penciptaan nilai dan kehendak" },
          { left: "Sartre", right: "Eksistensi mendahului esensi" },
          { left: "Camus", right: "Absurditas dan pemberontakan" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan berikut paling dekat dengan tokoh yang mana?",
        buckets: ["Kierkegaard", "Nietzsche", "Sartre", "Camus"],
        items: [
          { text: "Pilihan personal dan lompatan iman", bucket: "Kierkegaard" },
          { text: "Menggugat nilai lama dan menciptakan nilai baru", bucket: "Nietzsche" },
          { text: "Manusia dihukum untuk bebas", bucket: "Sartre" },
          { text: "Memberontak menghadapi absurditas", bucket: "Camus" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Eksistensialisme menempatkan individu yang bebas dan bertanggung jawab.",
          "Sartre: eksistensi mendahului esensi, manusia menciptakan dirinya.",
          "Camus: hidup absurd, tetapi makna lahir dari menjalaninya secara sadar.",
          "Kebebasan menuntut keberanian memilih, bukan menyerah pada kehampaan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "'Eksistensi mendahului esensi' berarti?",
            options: ["Tujuan manusia sudah ditetapkan sejak lahir", "Manusia ada dulu lalu menciptakan dirinya lewat pilihan", "Esensi lebih penting dari keberadaan", "Manusia sama dengan benda buatan"],
            answer: 1,
            explain: "Bagi Sartre, manusia tidak punya fungsi bawaan; ia menciptakan dirinya lewat pilihan.",
          },
          {
            q: "Konsep absurditas dikemukakan terutama oleh?",
            options: ["Kierkegaard", "Nietzsche", "Camus", "Sartre"],
            answer: 2,
            explain: "Albert Camus menyoroti absurditas, benturan kerinduan akan makna dengan diamnya alam.",
          },
          {
            q: "Menurut Sartre, manusia 'dihukum untuk bebas' artinya?",
            options: ["Kebebasan itu ilusi", "Setiap pilihan adalah tanggung jawab penuh kita", "Manusia tidak punya pilihan", "Kebebasan hanya milik segelintir orang"],
            answer: 1,
            explain: "Kebebasan tidak bisa dihindari; setiap pilihan menuntut tanggung jawab.",
          },
          {
            q: "Tokoh yang menekankan pilihan personal dan iman sebagai akar eksistensialisme?",
            options: ["Kierkegaard", "Camus", "Sartre", "Hume"],
            answer: 0,
            explain: "Soren Kierkegaard dianggap perintis tema pilihan personal dan iman.",
          },
          {
            q: "Respons Camus terhadap absurditas adalah?",
            options: ["Menyerah pada kehampaan", "Lari ke ilusi", "Memberontak dengan menjalani hidup secara sadar", "Mengabaikan makna sepenuhnya"],
            answer: 2,
            explain: "Camus mengajak memberontak dengan tetap hidup penuh dan sadar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "filsafat-timur-dan-pancasila",
    levelId: "terapan",
    order: 3,
    title: "Filsafat Timur & Pancasila",
    summary: "Konfusianisme, Buddhisme, dan Stoikisme bertemu Pancasila sebagai filsafat bangsa dan semangat gotong royong. Dengan grafik & latihan.",
    durationMin: 13,
    tags: ["filsafat Timur", "Pancasila", "gotong royong"],
    blocks: [
      {
        type: "paragraph",
        html: "Tradisi filsafat tidak hanya tumbuh di Barat. Di Timur, <strong>Konfusianisme</strong> menekankan keselarasan sosial dan etika hubungan, <strong>Buddhisme</strong> menelaah penderitaan serta jalan melepaskan diri darinya, dan <strong>Stoikisme</strong> mengajarkan ketenangan dengan membedakan apa yang bisa dan tidak bisa kita kendalikan.",
      },
      {
        type: "paragraph",
        html: "Di Indonesia, kekayaan ini berpadu dalam <strong>Pancasila</strong>, yang dirumuskan sebagai filsafat bangsa. Kelima silanya memadukan ketuhanan, kemanusiaan, persatuan, kerakyatan, dan keadilan, dengan semangat <strong>gotong royong</strong> sebagai intinya.",
      },
      {
        type: "video",
        comp: "FilsafatTimurVideo",
        title: "Video: Filsafat Timur & Pancasila",
        caption: "Konfusianisme, Taoisme, Buddhisme, dan Pancasila sebagai filsafat bangsa.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Confucius_Tang_Dynasty.jpg?width=400",
        alt: "Potret Konfusius",
        caption: "Konfusius, peletak dasar Konfusianisme yang menekankan keselarasan sosial",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "info",
        title: "Taoisme & Laozi",
        html: "Selain Konfusianisme, tradisi Tiongkok mengenal <strong>Taoisme</strong> yang dirintis <strong>Laozi</strong>. Taoisme mengajarkan keselarasan dengan <em>Tao</em> (jalan alam) dan <strong>wu wei</strong>, yaitu bertindak tanpa memaksa, mengalir selaras dengan kodrat.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Laozi_002.jpg?width=400",
        alt: "Potret Laozi",
        caption: "Laozi, perintis Taoisme dengan ajaran keselarasan dengan alam (wu wei)",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga tradisi Timur",
        html: "Konfusianisme: keselarasan dan etika hubungan. Buddhisme: memahami dan mengatasi penderitaan. Stoikisme (lintas Timur-Barat): fokus pada yang bisa dikendalikan, terima sisanya dengan tenang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Pancasila sebagai filsafat bangsa",
        html: "Lima sila: <strong>(1)</strong> Ketuhanan Yang Maha Esa, <strong>(2)</strong> Kemanusiaan yang adil dan beradab, <strong>(3)</strong> Persatuan Indonesia, <strong>(4)</strong> Kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan/perwakilan, <strong>(5)</strong> Keadilan sosial bagi seluruh rakyat Indonesia.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Gotong royong",
        html: "Soekarno pernah menyebut gotong royong sebagai perasan Pancasila: kerja sama dan saling menanggung sebagai roh kehidupan bersama bangsa.",
      },
      { type: "widget", widget: "TebakFilsuf" },
      {
        type: "case",
        title: "Studi Kasus: Kerja bakti membersihkan kampung",
        html: "Warga sebuah kampung sepakat membersihkan saluran air bersama menjelang musim hujan. Tidak ada upah, tetapi semua ikut karena beban dirasakan bersama. Ini adalah wujud nyata <strong>gotong royong</strong> dan sila kelima, keadilan sosial: hasil baik (kampung bebas banjir) dinikmati seluruh warga karena ditanggung bersama.",
      },
      {
        type: "classifyExercise",
        prompt: "Gagasan berikut paling dekat dengan tradisi yang mana?",
        buckets: ["Konfusianisme", "Buddhisme", "Stoikisme", "Pancasila"],
        items: [
          { text: "Keselarasan dan etika dalam hubungan sosial", bucket: "Konfusianisme" },
          { text: "Memahami penderitaan dan jalan melepaskannya", bucket: "Buddhisme" },
          { text: "Fokus pada yang bisa dikendalikan, terima sisanya", bucket: "Stoikisme" },
          { text: "Gotong royong dan keadilan sosial bagi seluruh rakyat", bucket: "Pancasila" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan tokoh atau tradisi dengan gagasan khasnya.",
        pairs: [
          { left: "Konfusius", right: "Keselarasan dan etika hubungan sosial" },
          { left: "Laozi", right: "Wu wei, selaras dengan Tao" },
          { left: "Buddhisme", right: "Memahami dan mengatasi penderitaan" },
          { left: "Pancasila", right: "Gotong royong dan keadilan sosial" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Filsafat Timur kaya: Konfusianisme, Buddhisme, dan Stoikisme.",
          "Pancasila adalah filsafat bangsa Indonesia dengan lima sila.",
          "Gotong royong adalah roh kehidupan bersama dalam Pancasila.",
          "Sila kelima menegaskan keadilan sosial bagi seluruh rakyat.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Konfusianisme paling menekankan?",
            options: ["Keselarasan dan etika hubungan", "Melepaskan diri dari penderitaan", "Kebebasan radikal individu", "Penolakan semua tradisi"],
            answer: 0,
            explain: "Konfusianisme berpusat pada keselarasan sosial dan etika hubungan.",
          },
          {
            q: "Inti ajaran Stoikisme adalah?",
            options: ["Mengejar kekayaan", "Membedakan yang bisa dan tidak bisa dikendalikan", "Menolak emosi sepenuhnya", "Hidup tanpa aturan"],
            answer: 1,
            explain: "Stoikisme mengajak fokus pada yang bisa dikendalikan dan menerima sisanya dengan tenang.",
          },
          {
            q: "Sila pertama Pancasila adalah?",
            options: ["Persatuan Indonesia", "Ketuhanan Yang Maha Esa", "Keadilan sosial", "Kerakyatan"],
            answer: 1,
            explain: "Sila pertama: Ketuhanan Yang Maha Esa.",
          },
          {
            q: "Sila kelima Pancasila menegaskan?",
            options: ["Persatuan", "Kemanusiaan", "Keadilan sosial bagi seluruh rakyat Indonesia", "Ketuhanan"],
            answer: 2,
            explain: "Sila kelima: Keadilan sosial bagi seluruh rakyat Indonesia.",
          },
          {
            q: "Semangat kerja sama dan saling menanggung dalam Pancasila disebut?",
            options: ["Individualisme", "Gotong royong", "Absurditas", "Kontrak sosial"],
            answer: 1,
            explain: "Gotong royong adalah roh kebersamaan dalam Pancasila.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "filsafat-politik",
    levelId: "terapan",
    order: 4,
    title: "Filsafat Politik & Keadilan",
    summary: "Keadilan ala Rawls, kontrak sosial, ketegangan kebebasan vs kesetaraan, dan landasan demokrasi. Dengan grafik & latihan.",
    durationMin: 13,
    tags: ["keadilan", "kontrak sosial", "demokrasi"],
    blocks: [
      {
        type: "paragraph",
        html: "Filsafat politik bertanya: bagaimana hidup bersama yang adil seharusnya diatur? Gagasan <strong>kontrak sosial</strong> (Hobbes, Locke, Rousseau) menyatakan bahwa otoritas negara bersumber dari kesepakatan warga untuk hidup tertib demi kebaikan bersama.",
      },
      {
        type: "video",
        comp: "KeadilanVideo",
        title: "Video: Keadilan & Kontrak Sosial",
        caption: "Utilitarianisme, kontrak sosial, dan keadilan-sebagai-fairness ala Rawls.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Evolusi gagasan dari era ke era",
        html: "Ide kontrak sosial berkembang: <strong>Thomas Hobbes</strong> (abad ke-17) menekankan ketertiban untuk keluar dari 'perang semua melawan semua', lalu <strong>Jean-Jacques Rousseau</strong> (abad ke-18) menekankan kehendak umum rakyat. Pada abad ke-20, <strong>John Rawls</strong> memperbarui tradisi ini dengan keadilan-sebagai-fairness lewat tabir ketidaktahuan.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Hobbes_(portrait).jpg?width=400",
        alt: "Potret Thomas Hobbes",
        caption: "Thomas Hobbes, perumus awal kontrak sosial yang menekankan ketertiban",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jean-Jacques_Rousseau_(painted_portrait).jpg?width=400",
        alt: "Potret Jean-Jacques Rousseau",
        caption: "Jean-Jacques Rousseau, penggagas kehendak umum rakyat dalam kontrak sosial",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "paragraph",
        html: "John <strong>Rawls</strong> mengusulkan menguji keadilan lewat <strong>tabir ketidaktahuan</strong> (veil of ignorance): bayangkan merancang aturan masyarakat tanpa tahu akan terlahir kaya atau miskin. Aturan yang dipilih dalam posisi itu cenderung adil bagi semua, terutama melindungi yang paling lemah.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tabir ketidaktahuan (Rawls)",
        html: "Karena tidak tahu posisi kita kelak, kita akan memilih prinsip yang melindungi semua orang. Rawls menyebut ketimpangan hanya dapat dibenarkan jika menguntungkan pihak yang <strong>paling tidak beruntung</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kontrak sosial",
        html: "Hobbes menekankan ketertiban demi keamanan, Locke menekankan perlindungan hak (hidup, kebebasan, milik), Rousseau menekankan kehendak umum rakyat. Semua sepakat: kekuasaan sah berasal dari persetujuan warga.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Kebebasan vs kesetaraan",
        html: "Kebebasan penuh tanpa batas bisa memperlebar ketimpangan; pemerataan yang dipaksakan bisa menekan kebebasan. Demokrasi yang sehat terus mencari <strong>keseimbangan</strong> di antara keduanya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dari pasar bebas ke kritik ketimpangan",
        html: "Perdebatan ini punya akar ekonomi-politik. <strong>Adam Smith</strong> (abad ke-18) menjelaskan bagaimana pasar bebas mengoordinasikan kepentingan lewat 'tangan tak terlihat', sementara <strong>Karl Marx</strong> (abad ke-19) mengkritik ketimpangan kelas yang lahir dari kepemilikan modal. Rawls kemudian menengahi: ketimpangan hanya adil bila menguntungkan yang paling lemah.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/AdamSmith.jpg?width=400",
        alt: "Potret Adam Smith",
        caption: "Adam Smith, perumus gagasan pasar bebas dan 'tangan tak terlihat'",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Karl_Marx_001.jpg?width=400",
        alt: "Potret Karl Marx",
        caption: "Karl Marx, pengkritik ketimpangan kelas dalam masyarakat kapitalis",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "case",
        title: "Studi Kasus: Merancang aturan beasiswa",
        html: "Sebuah kampus menyusun aturan beasiswa. Dengan logika <strong>tabir ketidaktahuan</strong> Rawls, perancang membayangkan dirinya bisa saja menjadi mahasiswa termiskin. Hasilnya, mereka memprioritaskan calon dari keluarga paling tidak mampu sambil tetap membuka jalur prestasi. Ketimpangan kuota dibenarkan justru karena menguntungkan pihak yang paling membutuhkan.",
      },
      {
        type: "matchExercise",
        prompt: "Cocokkan pemikir dengan penekanannya.",
        pairs: [
          { left: "Hobbes", right: "Ketertiban dan keamanan" },
          { left: "Locke", right: "Perlindungan hak individu" },
          { left: "Rousseau", right: "Kehendak umum rakyat" },
          { left: "Rawls", right: "Keadilan lewat tabir ketidaktahuan" },
        ],
      },
      {
        type: "classifyExercise",
        prompt: "Pandangan berikut paling dekat dengan pemikir yang mana?",
        buckets: ["Hobbes", "Rousseau", "Smith", "Marx"],
        items: [
          { text: "Negara kuat dibutuhkan demi ketertiban dan keamanan", bucket: "Hobbes" },
          { text: "Kekuasaan sah bersandar pada kehendak umum rakyat", bucket: "Rousseau" },
          { text: "Pasar bebas mengoordinasikan kepentingan lewat tangan tak terlihat", bucket: "Smith" },
          { text: "Ketimpangan kelas lahir dari kepemilikan modal", bucket: "Marx" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Kontrak sosial: kekuasaan negara bersumber dari persetujuan warga.",
          "Rawls menguji keadilan lewat tabir ketidaktahuan.",
          "Ketimpangan dibenarkan hanya jika menguntungkan yang paling lemah.",
          "Demokrasi menyeimbangkan kebebasan dan kesetaraan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tabir ketidaktahuan Rawls meminta kita?",
            options: ["Merancang aturan tahu posisi sendiri", "Merancang aturan tanpa tahu akan jadi kaya atau miskin", "Mengabaikan yang lemah", "Memilih aturan untuk diri sendiri"],
            answer: 1,
            explain: "Tanpa tahu posisi kita kelak, kita cenderung memilih aturan yang adil bagi semua.",
          },
          {
            q: "Gagasan kontrak sosial menyatakan otoritas negara berasal dari?",
            options: ["Kekuatan militer", "Persetujuan warga", "Warisan turun-temurun", "Kekayaan penguasa"],
            answer: 1,
            explain: "Kontrak sosial: kekuasaan sah bersumber dari kesepakatan warga.",
          },
          {
            q: "Menurut Rawls, ketimpangan dapat dibenarkan jika?",
            options: ["Menguntungkan yang paling tidak beruntung", "Menguntungkan yang terkaya", "Tidak boleh ada sama sekali", "Ditentukan penguasa"],
            answer: 0,
            explain: "Ketimpangan hanya adil bila menguntungkan pihak yang paling lemah.",
          },
          {
            q: "Pemikir yang menekankan perlindungan hak hidup, kebebasan, dan milik adalah?",
            options: ["Hobbes", "Locke", "Rousseau", "Rawls"],
            answer: 1,
            explain: "John Locke menekankan perlindungan hak-hak alami individu.",
          },
          {
            q: "Ketegangan inti dalam demokrasi modern adalah antara?",
            options: ["Tradisi dan agama", "Kebebasan dan kesetaraan", "Perang dan damai", "Desa dan kota"],
            answer: 1,
            explain: "Demokrasi terus menyeimbangkan kebebasan individu dan kesetaraan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "filsafat-ilmu",
    levelId: "terapan",
    order: 5,
    title: "Filsafat Ilmu: Bagaimana Sains Bekerja",
    summary: "Apa yang membuat sesuatu ilmiah? Masalah induksi Hume, falsifikasi Popper, dan revolusi paradigma Kuhn yang mengubah cara kita memandang sains.",
    durationMin: 14,
    tags: ["filsafat ilmu", "Popper", "Kuhn", "falsifikasi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Filsafat ilmu</strong> bertanya: apa yang membuat sebuah pengetahuan layak disebut <strong>ilmiah</strong>, dan apa yang membedakannya dari sekadar opini atau pseudosains? Ini disebut <strong>masalah demarkasi</strong>, garis batas antara sains dan bukan-sains.",
      },
      {
        type: "paragraph",
        html: "Akarnya kita temui di Level 2: <strong>David Hume</strong> menunjukkan <strong>masalah induksi</strong>, bahwa sebanyak apa pun pengamatan tidak pernah menjamin hukum umum pasti benar. Jika sains bertumpu pada induksi, dari mana kepastiannya? Pertanyaan inilah yang menggerakkan filsuf abad ke-20.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/David_Hume.jpg?width=400",
        alt: "Potret David Hume",
        caption: "David Hume, yang masalah induksinya menjadi titik tolak filsafat ilmu modern.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Falsifikasi (Karl Popper)",
        html: "<strong>Karl Popper</strong> (1902-1994) menjawab: sains tidak pernah membuktikan teori benar, ia hanya <strong>menguji untuk menyalahkannya</strong>. Sebuah klaim ilmiah harus <strong>dapat difalsifikasi</strong>, yaitu bisa dibayangkan bukti yang akan membuktikannya salah. Teori yang tak mungkin salah bukanlah sains.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Revolusi paradigma (Thomas Kuhn)",
        html: "<strong>Thomas Kuhn</strong> (1922-1996) dalam 'The Structure of Scientific Revolutions' (1962) menambahkan sisi sejarah: sains berjalan dalam <strong>paradigma</strong>. Selama 'sains normal', ilmuwan bekerja dalam kerangka yang sama. Saat anomali menumpuk, terjadi krisis, lalu <strong>revolusi</strong> menggantinya dengan paradigma baru.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tanda pseudosains",
        html: "Menurut Popper, pseudosains kerap dirumuskan agar <strong>tak pernah bisa salah</strong>: setiap bukti tandingan ditampik dengan dalih baru. Ramalannya kabur dan aman, sehingga apa pun yang terjadi tetap dianggap cocok.",
      },
      {
        type: "video",
        comp: "TeoriKebenaran",
        title: "Video: Apa Artinya Benar",
        caption: "Sains adalah salah satu cara paling ketat menguji kebenaran klaim tentang dunia.",
      },
      { type: "widget", widget: "TebakFilsuf" },
      {
        type: "table",
        caption: "Membedakan sains dari pseudosains menurut kriteria Popper",
        headers: ["Pertanyaan", "Sains", "Pseudosains"],
        rows: [
          ["Bisakah dibuktikan salah?", "Ya, dapat difalsifikasi lewat uji", "Tidak, selalu ada dalih baru"],
          ["Bagaimana menanggapi bukti tandingan?", "Merevisi atau menolak teori", "Mengabaikan atau menambalnya"],
          ["Seberapa berani ramalannya?", "Spesifik dan berisiko", "Kabur dan selalu aman"],
        ],
      },
      {
        type: "case",
        title: "Sejarah: Gerhana 1919 menguji Einstein",
        html: "Teori relativitas umum Albert Einstein (1915) meramalkan bahwa cahaya bintang akan <strong>dibelokkan</strong> oleh gravitasi Matahari, sebuah prediksi spesifik yang berisiko salah. Pada gerhana matahari 1919, ekspedisi pimpinan Arthur Eddington mengukur posisi bintang di dekat Matahari dan hasilnya <strong>cocok dengan ramalan Einstein</strong>. Bagi Popper, inilah teladan sains sejati: teori berani membuat ramalan yang bisa saja menggugurkannya, lalu lolos dari uji yang sungguh menantang.",
      },
      {
        type: "classifyExercise",
        prompt: "Klaim berikut bersifat ilmiah (dapat difalsifikasi) atau pseudosains (tak terfalsifikasi)?",
        buckets: ["Ilmiah", "Pseudosains"],
        items: [
          { text: "Logam ini akan memuai bila dipanaskan sampai 200 derajat", bucket: "Ilmiah" },
          { text: "Ramalan ini benar; kalau tampak meleset, energimu sedang menghalangi", bucket: "Pseudosains" },
          { text: "Obat ini menurunkan demam pada uji terkontrol", bucket: "Ilmiah" },
          { text: "Apa pun yang terjadi, sudah pasti sesuai ramalan saya", bucket: "Pseudosains" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan tokoh dengan gagasan kunci filsafat ilmunya.",
        pairs: [
          { left: "Francis Bacon", right: "Metode empiris dan pengamatan sistematis" },
          { left: "David Hume", right: "Masalah induksi" },
          { left: "Karl Popper", right: "Falsifikasi sebagai batas sains" },
          { left: "Thomas Kuhn", right: "Revolusi dan pergeseran paradigma" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Filsafat ilmu mencari batas antara sains dan bukan-sains (demarkasi).",
          "Masalah induksi Hume: pengamatan tak pernah menjamin hukum umum pasti.",
          "Popper: sains bersifat dapat difalsifikasi, bukan sekadar dibuktikan benar.",
          "Kuhn: sains berkembang lewat paradigma dan revolusi, bukan hanya akumulasi.",
          "Pseudosains dirancang agar tak pernah bisa dibuktikan salah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Masalah demarkasi dalam filsafat ilmu menyangkut?",
            options: ["Biaya riset", "Batas antara sains dan bukan-sains", "Jumlah ilmuwan", "Bahasa laporan"],
            answer: 1,
            explain: "Demarkasi adalah soal membedakan sains dari pseudosains.",
          },
          {
            q: "Menurut Popper, ciri klaim ilmiah adalah?",
            options: ["Tidak mungkin salah", "Dapat difalsifikasi", "Disetujui mayoritas", "Selalu terbukti benar"],
            answer: 1,
            explain: "Klaim ilmiah harus bisa dibayangkan cara untuk membuktikannya salah.",
          },
          {
            q: "Konsep 'pergeseran paradigma' dikemukakan oleh?",
            options: ["Hume", "Popper", "Thomas Kuhn", "Bacon"],
            answer: 2,
            explain: "Kuhn menjelaskan sains berubah lewat revolusi paradigma.",
          },
          {
            q: "Masalah induksi Hume menyatakan bahwa?",
            options: ["Pengamatan menjamin hukum pasti", "Banyak pengamatan tetap tak menjamin hukum umum pasti benar", "Sains tidak ada gunanya", "Teori selalu benar"],
            answer: 1,
            explain: "Sebanyak apa pun pengamatan, kesimpulan induktif tidak pernah terjamin pasti.",
          },
          {
            q: "Gerhana 1919 penting karena?",
            options: ["Menggagalkan teori Einstein", "Menguji dan mengukuhkan ramalan relativitas umum", "Membuktikan astrologi", "Tidak ada kaitannya dengan sains"],
            answer: 1,
            explain: "Pengamatan gerhana mengonfirmasi prediksi pembelokan cahaya Einstein.",
          },
        ],
      },
    ],
  },
];
