import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "koreksi-fiskal",
    levelId: "pphbadan",
    order: 1,
    title: "Koreksi Fiskal: Positif & Negatif",
    summary: "Menjembatani laba akuntansi dan laba fiskal lewat koreksi atas biaya dan penghasilan, dasar perhitungan PPh Badan.",
    durationMin: 14,
    tags: ["koreksi fiskal", "PPh Badan", "deductible"],
    blocks: [
      {
        type: "paragraph",
        html: "Laba pada laporan keuangan (<strong>laba komersial</strong>) hampir selalu berbeda dari <strong>laba fiskal</strong> yang dipakai menghitung pajak. Aturan akuntansi (SAK) dan aturan pajak (UU PPh) tidak sama, sehingga laba komersial harus disesuaikan lewat <strong>koreksi fiskal</strong> sebelum dikalikan tarif 22%.",
      },
      {
        type: "video",
        comp: "KoreksiFiskalVideo",
        title: "Video: Dari Laba Komersial ke Laba Fiskal",
        caption: "Koreksi positif menambah penghasilan kena pajak, koreksi negatif menguranginya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua arah koreksi",
        html: "<strong>Koreksi positif</strong> menambah PKP: biaya yang tidak boleh dikurangkan (Pasal 9) atau penyusutan komersial yang lebih besar dari fiskal. <strong>Koreksi negatif</strong> mengurangi PKP: penghasilan yang sudah dikenai pajak final atau bukan objek pajak.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Biaya 3M (Pasal 6) vs non-deductible (Pasal 9)",
        html: "Biaya untuk <strong>mendapatkan, menagih, dan memelihara</strong> penghasilan boleh dikurangkan. Yang <strong>tidak boleh</strong> antara lain: pembagian laba/dividen, sanksi pajak, PPh, biaya kepentingan pribadi pemegang saham, dan cadangan tertentu.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Contoh Koreksi atas Laba Komersial Rp5 Miliar (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi perhitungan rekonsiliasi fiskal",
        note: "Koreksi positif menaikkan, koreksi negatif menurunkan. PKP akhir Rp5,3 M, bukan Rp5 M seperti laba akuntansi.",
        data: [
          { label: "Laba komersial", value: 5000, color: "#60a5fa" },
          { label: "+ Sanksi pajak", value: 200, color: "#fbbf24" },
          { label: "+ Sumbangan", value: 400, color: "#fbbf24" },
          { label: "- Bunga deposito (final)", value: -300, color: "#34d399" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur laba komersial dan besaran koreksi positif/negatif untuk melihat penghasilan kena pajak dan PPh Badan yang terbentuk.",
      },
      { type: "widget", widget: "KalkulatorKoreksiFiskal" },
      {
        type: "case",
        title: "Studi Kasus: Sumbangan dan denda yang tak bisa dibebankan",
        html: "PT Sentosa mencatat laba komersial Rp5 miliar. Di dalamnya ada beban sanksi pajak Rp200 juta dan sumbangan non-fasilitas Rp400 juta yang menurut Pasal 9 <strong>tidak boleh dikurangkan</strong>, serta penghasilan bunga deposito Rp300 juta yang sudah kena <strong>PPh final</strong>. Maka PKP = 5.000 + 200 + 400 - 300 = <strong>Rp5,3 miliar</strong>, dan PPh Badan = 22% x 5,3 = Rp1,166 miliar. Tanpa rekonsiliasi, pajak akan salah hitung.",
      },
      {
        type: "calcExercise",
        prompt: "Laba komersial Rp5.000 juta, koreksi positif Rp600 juta, koreksi negatif Rp300 juta. Berapa penghasilan kena pajak (PKP) dalam juta?",
        answer: 5300,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "PKP = 5.000 + 600 - 300 = <strong>Rp5.300 juta</strong> (Rp5,3 miliar).",
        hint: "PKP = laba komersial + koreksi positif - koreksi negatif.",
      },
      {
        type: "calcExercise",
        prompt: "Dari PKP Rp5.300 juta di atas, berapa PPh Badan terutang (tarif 22%) dalam juta?",
        answer: 1166,
        tolerance: 1,
        prefix: "Rp",
        suffix: "juta",
        solution: "PPh = 22% x 5.300 = <strong>Rp1.166 juta</strong> (Rp1,166 miliar).",
        hint: "Kalikan PKP dengan 22%.",
      },
      {
        type: "classifyExercise",
        prompt: "Item ini menimbulkan koreksi positif atau negatif?",
        buckets: ["Koreksi positif", "Koreksi negatif"],
        items: [
          { text: "Beban sanksi/denda pajak", bucket: "Koreksi positif" },
          { text: "Biaya jamuan tanpa daftar nominatif", bucket: "Koreksi positif" },
          { text: "Penghasilan bunga deposito (sudah final)", bucket: "Koreksi negatif" },
          { text: "Dividen yang memenuhi syarat pengecualian", bucket: "Koreksi negatif" },
          { text: "Sumbangan yang bukan fasilitas pajak", bucket: "Koreksi positif" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Reformasi Perpajakan 1983",
        html: "Sebelum <strong>1983</strong>, pajak Indonesia memakai sistem official assessment: petugas yang menetapkan pajak. Reformasi <strong>1983 sampai 1984</strong> memperkenalkan <strong>self assessment</strong>, di mana wajib pajak menghitung, menyetor, dan melaporkan sendiri pajaknya. Sejak itu, kemampuan menyusun <strong>rekonsiliasi fiskal</strong> yang benar menjadi tanggung jawab perusahaan, dan koreksi fiskal menjadi keterampilan inti agar SPT akurat dan tahan pemeriksaan.",
      },
      {
        type: "takeaways",
        items: [
          "Laba komersial belum tentu sama dengan laba fiskal.",
          "Koreksi positif menambah PKP, koreksi negatif menguranginya.",
          "Pasal 6 mengatur biaya yang boleh dikurangkan, Pasal 9 yang tidak.",
          "PKP = laba komersial + koreksi positif - koreksi negatif, lalu x 22%.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Koreksi fiskal positif akan?",
            options: ["Mengurangi PKP", "Menambah PKP", "Tidak berpengaruh", "Menghapus pajak"],
            answer: 1,
            explain: "Koreksi positif menambah penghasilan kena pajak, sehingga pajak naik.",
          },
          {
            q: "Manakah biaya yang TIDAK boleh dikurangkan (Pasal 9)?",
            options: ["Gaji karyawan", "Biaya bahan baku", "Sanksi/denda pajak", "Sewa kantor"],
            answer: 2,
            explain: "Sanksi pajak termasuk biaya yang tidak boleh dikurangkan secara fiskal.",
          },
          {
            q: "Penghasilan bunga deposito yang sudah kena PPh final menimbulkan?",
            options: ["Koreksi positif", "Koreksi negatif", "Tambahan tarif", "Denda"],
            answer: 1,
            explain: "Karena sudah final, dikeluarkan dari PKP lewat koreksi negatif agar tidak kena pajak dua kali.",
          },
          {
            q: "Laba komersial Rp4 M, koreksi positif Rp500 jt, negatif Rp200 jt. PKP-nya?",
            options: ["Rp3,7 M", "Rp4,3 M", "Rp4,5 M", "Rp4 M"],
            answer: 1,
            explain: "4.000 + 500 - 200 = Rp4.300 juta = Rp4,3 M.",
          },
          {
            q: "Tujuan rekonsiliasi fiskal adalah?",
            options: [
              "Mengganti laporan keuangan",
              "Menyesuaikan laba akuntansi menjadi dasar pajak yang benar",
              "Menambah omzet",
              "Menghapus koreksi",
            ],
            answer: 1,
            explain: "Rekonsiliasi menyesuaikan laba komersial menjadi laba fiskal sesuai UU PPh.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "penyusutan-amortisasi-fiskal",
    levelId: "pphbadan",
    order: 2,
    title: "Penyusutan & Amortisasi Fiskal",
    summary: "Mengelompokkan harta dan memilih metode penyusutan (garis lurus atau saldo menurun) sesuai Pasal 11 & 11A UU PPh.",
    durationMin: 15,
    tags: ["penyusutan", "amortisasi", "Pasal 11", "PPh Badan"],
    blocks: [
      {
        type: "paragraph",
        html: "Aset perusahaan yang dipakai lebih dari satu tahun tidak boleh dibebankan sekaligus, melainkan disusutkan selama <strong>masa manfaat</strong>. Pajak punya aturan sendiri lewat <strong>Pasal 11 UU PPh</strong>: harta berwujud bukan bangunan dibagi menjadi empat kelompok, masing-masing dengan masa manfaat dan tarif baku.",
      },
      {
        type: "paragraph",
        html: "Ada dua metode yang boleh dipilih: <strong>garis lurus</strong> (beban sama tiap tahun) dan <strong>saldo menurun</strong> (beban besar di awal lalu mengecil). Khusus <strong>bangunan</strong>, hanya boleh memakai garis lurus.",
      },
      {
        type: "video",
        comp: "PenyusutanFiskalVideo",
        title: "Video: Kelompok Harta dan Metode Penyusutan",
        caption: "Garis lurus vs saldo menurun, dan empat kelompok harta berwujud bukan bangunan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat kelompok harta (bukan bangunan)",
        html: "<strong>Kelompok 1</strong>: 4 tahun, garis lurus 25%, saldo menurun 50%. <strong>Kelompok 2</strong>: 8 tahun, GL 12,5%, SM 25%. <strong>Kelompok 3</strong>: 16 tahun, GL 6,25%, SM 12,5%. <strong>Kelompok 4</strong>: 20 tahun, GL 5%, SM 10%.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Bangunan: hanya garis lurus",
        html: "<strong>Bangunan permanen</strong> disusutkan 20 tahun (garis lurus 5%). <strong>Bangunan tidak permanen</strong> disusutkan 10 tahun (garis lurus 10%). Bangunan tidak boleh memakai metode saldo menurun.",
      },
      {
        type: "table",
        headers: ["Kelompok / Jenis", "Masa manfaat", "Garis lurus", "Saldo menurun"],
        rows: [
          ["Kelompok 1", "4 tahun", "25%", "50%"],
          ["Kelompok 2", "8 tahun", "12,5%", "25%"],
          ["Kelompok 3", "16 tahun", "6,25%", "12,5%"],
          ["Kelompok 4", "20 tahun", "5%", "10%"],
          ["Bangunan permanen", "20 tahun", "5%", "-"],
          ["Bangunan tidak permanen", "10 tahun", "10%", "-"],
        ],
        caption: "Tarif penyusutan fiskal menurut Pasal 11 UU PPh.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pilih harga perolehan, kelompok harta, dan metode untuk melihat beban penyusutan tiap tahun dan bagaimana saldo menurun menumpuk beban di awal.",
      },
      { type: "widget", widget: "SimulatorPenyusutanFiskal" },
      {
        type: "chart",
        variant: "line",
        title: "Beban Penyusutan Aset Kelompok 1 Rp400 juta: GL vs SM",
        unit: "Rp juta",
        source: "ilustrasi perhitungan Pasal 11 UU PPh",
        note: "Saldo menurun memberi beban lebih besar di awal (menunda pajak), tetapi total beban sepanjang umur sama.",
        data: [
          { label: "Tahun 1 GL", value: 100, color: "#60a5fa" },
          { label: "Tahun 1 SM", value: 200, color: "#fbbf24" },
          { label: "Tahun 2 SM", value: 100, color: "#fbbf24" },
          { label: "Tahun 3 SM", value: 50, color: "#fbbf24" },
          { label: "Tahun 4 SM", value: 50, color: "#fbbf24" },
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Amortisasi untuk harta tak berwujud",
        html: "<strong>Pasal 11A</strong> mengatur amortisasi atas harta tak berwujud (mis. hak paten, lisensi, goodwill). Pengelompokan masa manfaatnya mengikuti pola yang sama dengan harta berwujud bukan bangunan.",
      },
      {
        type: "case",
        title: "Studi Kasus: Memilih metode untuk mesin Rp400 juta",
        html: "PT Karya membeli mesin (Kelompok 1) seharga Rp400 juta. Dengan <strong>garis lurus</strong>, beban = 25% x 400 = <strong>Rp100 juta per tahun</strong> selama 4 tahun. Dengan <strong>saldo menurun</strong> (50%), tahun 1 = 50% x 400 = Rp200 juta, tahun 2 = 50% x 200 = Rp100 juta, tahun 3 = Rp50 juta, dan tahun terakhir nilai sisa Rp50 juta dibebankan sekaligus. Total tetap Rp400 juta, tetapi saldo menurun menggeser beban (dan penghematan pajak) ke awal.",
      },
      {
        type: "case",
        title: "Sejarah: Penyusutan dipercepat sebagai stimulus investasi",
        html: "Penyusutan dipercepat (accelerated depreciation) lama dipakai pemerintah sebagai stimulus. Di Amerika Serikat, sistem <strong>MACRS</strong> dan kebijakan <strong>bonus depreciation</strong> berulang dipakai untuk mendorong belanja modal saat ekonomi lesu. Di Indonesia, fasilitas <strong>super deduction</strong> dan percepatan penyusutan diberikan untuk industri tertentu (mis. industri padat karya dan kegiatan litbang) agar investasi mengalir. Logikanya sama: mempercepat beban berarti menunda pajak, sehingga kas perusahaan untuk berinvestasi bertambah.",
      },
      {
        type: "calcExercise",
        prompt: "Aset Kelompok 1 seharga Rp400 juta disusutkan garis lurus. Berapa beban penyusutan per tahun (dalam juta)?",
        answer: 100,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Garis lurus Kelompok 1 = 25% x 400 = <strong>Rp100 juta per tahun</strong>.",
        hint: "Tarif garis lurus Kelompok 1 adalah 25%.",
      },
      {
        type: "calcExercise",
        prompt: "Aset Kelompok 2 seharga Rp800 juta disusutkan saldo menurun (25%). Berapa beban penyusutan tahun pertama (dalam juta)?",
        answer: 200,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Saldo menurun Kelompok 2 = 25% x 800 = <strong>Rp200 juta</strong> di tahun pertama.",
        hint: "Tarif saldo menurun Kelompok 2 adalah 25%, dikalikan harga perolehan di tahun pertama.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kelompok/jenis harta dengan masa manfaat fiskalnya.",
        pairs: [
          { left: "Kelompok 1", right: "4 tahun" },
          { left: "Kelompok 2", right: "8 tahun" },
          { left: "Kelompok 3", right: "16 tahun" },
          { left: "Bangunan tidak permanen", right: "10 tahun" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Harta berwujud bukan bangunan dibagi 4 kelompok dengan tarif baku.",
          "Dua metode: garis lurus (rata) dan saldo menurun (besar di awal).",
          "Bangunan hanya boleh memakai garis lurus.",
          "Saldo menurun menunda pajak, tetapi total beban sepanjang umur sama.",
          "Harta tak berwujud diamortisasi menurut Pasal 11A.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tarif garis lurus untuk harta Kelompok 1 adalah?",
            options: ["12,5%", "25%", "50%", "5%"],
            answer: 1,
            explain: "Kelompok 1 memiliki masa manfaat 4 tahun, sehingga tarif garis lurus 100%/4 = 25%.",
          },
          {
            q: "Metode penyusutan apa yang boleh dipakai untuk bangunan?",
            options: ["Saldo menurun saja", "Garis lurus saja", "Keduanya bebas", "Tidak disusutkan"],
            answer: 1,
            explain: "Bangunan hanya boleh memakai metode garis lurus.",
          },
          {
            q: "Dibanding garis lurus, metode saldo menurun memberi beban yang?",
            options: ["Lebih besar di awal", "Lebih besar di akhir", "Selalu sama tiap tahun", "Nol di tahun pertama"],
            answer: 0,
            explain: "Saldo menurun menumpuk beban di awal, lalu mengecil seiring waktu.",
          },
          {
            q: "Bangunan permanen disusutkan selama berapa tahun?",
            options: ["10 tahun", "16 tahun", "20 tahun", "4 tahun"],
            answer: 2,
            explain: "Bangunan permanen disusutkan 20 tahun dengan garis lurus 5%.",
          },
          {
            q: "Pasal berapa yang mengatur amortisasi harta tak berwujud?",
            options: ["Pasal 6", "Pasal 9", "Pasal 11A", "Pasal 25"],
            answer: 2,
            explain: "Amortisasi harta tak berwujud diatur dalam Pasal 11A UU PPh.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kompensasi-kerugian",
    levelId: "pphbadan",
    order: 3,
    title: "Kompensasi Kerugian Fiskal",
    summary: "Memanfaatkan rugi fiskal untuk mengurangi laba tahun-tahun berikutnya selama maksimal 5 tahun menurut Pasal 6 ayat (2) UU PPh.",
    durationMin: 14,
    tags: ["kompensasi kerugian", "Pasal 6", "rugi fiskal", "PPh Badan"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan tidak selalu untung. Bila tahun ini <strong>rugi fiskal</strong>, kerugian itu tidak hilang begitu saja. <strong>Pasal 6 ayat (2) UU PPh</strong> mengizinkan rugi dikompensasikan ke laba <strong>5 tahun berikutnya</strong>, sehingga pajak di tahun-tahun pemulihan menjadi lebih ringan.",
      },
      {
        type: "paragraph",
        html: "Kompensasi hanya berlaku <strong>maju</strong> (carry forward). Indonesia <strong>tidak mengenal carry back</strong>, yaitu rugi tidak bisa dikompensasikan mundur ke laba tahun-tahun sebelumnya.",
      },
      {
        type: "video",
        comp: "KompensasiKerugianVideo",
        title: "Video: Mengangsur Rugi ke Laba Tahun Berikutnya",
        caption: "Rugi fiskal mengurangi PKP sampai 5 tahun ke depan; sisa yang tersisa setelah itu hangus.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aturan inti kompensasi",
        html: "Rugi fiskal dikompensasikan ke laba <strong>5 tahun berikutnya</strong>. Sisa rugi yang belum terkompensasi setelah 5 tahun <strong>hangus</strong>. Untuk fasilitas tertentu (mis. penanaman modal di bidang/daerah tertentu), jangka waktu bisa diperpanjang hingga <strong>10 tahun</strong>.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tidak bisa mundur",
        html: "Di Indonesia berlaku <strong>no carry back</strong>. Rugi tahun ini tidak bisa dipakai meminta restitusi atas pajak tahun lalu, hanya bisa mengurangi laba ke depan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Masukkan rugi awal dan laba beberapa tahun ke depan untuk melihat berapa rugi yang terpakai tiap tahun dan kapan rugi habis atau hangus.",
      },
      { type: "widget", widget: "KalkulatorKompensasiKerugian" },
      {
        type: "chart",
        variant: "bar",
        title: "Pemakaian Rugi Fiskal 2024 Rp2 M ke Tahun-Tahun Berikutnya",
        unit: "Rp juta",
        source: "ilustrasi Pasal 6 ayat (2) UU PPh",
        note: "Rugi Rp2 M habis terkompensasi dalam beberapa tahun laba; selama saldo rugi ada, PKP tahun itu menjadi nol.",
        data: [
          { label: "Rugi 2024", value: 2000, color: "#f87171" },
          { label: "Laba 2025", value: 500, color: "#34d399" },
          { label: "Laba 2026", value: 600, color: "#34d399" },
          { label: "Laba 2027", value: 900, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Rugi Rp2 miliar diangsur sampai habis",
        html: "PT Bangkit rugi fiskal <strong>Rp2 miliar</strong> pada 2024. Tahun 2025 laba Rp500 juta (terpakai 500, sisa rugi Rp1.500 juta, PKP 2025 = 0). Tahun 2026 laba Rp600 juta (terpakai 600, sisa rugi Rp900 juta, PKP 2026 = 0). Tahun 2027 laba Rp900 juta (terpakai 900, sisa rugi habis, PKP 2027 = 0). Baru pada 2028 dan seterusnya perusahaan kembali membayar PPh. Seluruh rugi terkompensasi dalam 4 tahun, masih di dalam batas 5 tahun.",
      },
      {
        type: "case",
        title: "Sejarah: Kompensasi kerugian saat pandemi COVID-19",
        html: "Saat pandemi <strong>COVID-19 (2020)</strong>, banyak perusahaan, terutama sektor pariwisata, transportasi, dan ritel, mencatat rugi fiskal besar akibat aktivitas yang anjlok. Ketika ekonomi pulih pada 2021 sampai 2023, kemampuan <strong>mengompensasikan rugi 2020</strong> ke laba tahun-tahun pemulihan membuat beban pajak mereka jauh lebih ringan. Mekanisme ini menjadi penyangga arus kas yang penting agar perusahaan bisa bangkit tanpa langsung terbebani PPh penuh.",
      },
      {
        type: "calcExercise",
        prompt: "Rugi fiskal 2024 Rp2.000 juta. Laba 2025 Rp500 juta dipakai mengompensasi. Berapa sisa rugi yang bisa dibawa ke 2026 (dalam juta)?",
        answer: 1500,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Sisa rugi = 2.000 - 500 = <strong>Rp1.500 juta</strong> dibawa ke 2026.",
        hint: "Kurangi rugi awal dengan laba yang dikompensasikan tahun itu.",
      },
      {
        type: "calcExercise",
        prompt: "Sisa rugi Rp1.500 juta, laba 2026 Rp600 juta, laba 2027 Rp900 juta. Setelah 2027, berapa sisa rugi yang belum terpakai (dalam juta)?",
        answer: 0,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "1.500 - 600 - 900 = <strong>Rp0</strong>. Rugi habis terkompensasi tepat di 2027.",
        hint: "Kurangi sisa rugi dengan laba 2026 lalu laba 2027.",
      },
      {
        type: "classifyExercise",
        prompt: "Pernyataan ini benar atau salah tentang kompensasi kerugian fiskal?",
        buckets: ["Benar", "Salah"],
        items: [
          { text: "Rugi fiskal bisa dikompensasi ke 5 tahun berikutnya", bucket: "Benar" },
          { text: "Sisa rugi setelah 5 tahun hangus", bucket: "Benar" },
          { text: "Rugi bisa dikompensasi mundur ke tahun lalu", bucket: "Salah" },
          { text: "Fasilitas tertentu bisa memperpanjang sampai 10 tahun", bucket: "Benar" },
          { text: "Selama saldo rugi ada, PKP tahun itu bisa menjadi nol", bucket: "Benar" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Rugi fiskal dikompensasikan ke laba 5 tahun berikutnya (Pasal 6 ayat 2).",
          "Sisa rugi yang belum terpakai setelah 5 tahun hangus.",
          "Indonesia hanya mengenal carry forward, tidak ada carry back.",
          "Fasilitas tertentu bisa memperpanjang jangka waktu sampai 10 tahun.",
          "Selama rugi masih ada saldo, PKP tahun itu bisa nol.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Berapa lama rugi fiskal umumnya boleh dikompensasikan?",
            options: ["3 tahun", "5 tahun", "10 tahun", "Selamanya"],
            answer: 1,
            explain: "Pasal 6 ayat (2) UU PPh mengizinkan kompensasi ke 5 tahun berikutnya.",
          },
          {
            q: "Apa yang terjadi pada sisa rugi yang belum terkompensasi setelah 5 tahun?",
            options: ["Diperpanjang otomatis", "Hangus", "Dikembalikan tunai", "Jadi kredit pajak"],
            answer: 1,
            explain: "Sisa rugi yang belum terkompensasi setelah 5 tahun hangus.",
          },
          {
            q: "Apakah rugi bisa dikompensasikan ke tahun-tahun sebelumnya?",
            options: ["Bisa, carry back", "Tidak, hanya carry forward", "Bisa, tanpa batas", "Hanya untuk UMKM"],
            answer: 1,
            explain: "Indonesia tidak mengenal carry back; kompensasi hanya berlaku maju.",
          },
          {
            q: "Untuk fasilitas penanaman modal tertentu, jangka kompensasi bisa diperpanjang sampai?",
            options: ["7 tahun", "10 tahun", "15 tahun", "20 tahun"],
            answer: 1,
            explain: "Untuk fasilitas tertentu, jangka waktu kompensasi bisa diperpanjang hingga 10 tahun.",
          },
          {
            q: "Rugi 2024 Rp2 M, laba 2025 Rp500 jt. Berapa PKP 2025?",
            options: ["Rp500 jt", "Rp2 M", "Rp0", "Rp1,5 M"],
            answer: 2,
            explain: "Laba Rp500 jt habis dipakai mengompensasi rugi, sehingga PKP 2025 = 0.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "rekonsiliasi-spt-1771",
    levelId: "pphbadan",
    order: 4,
    title: "Rekonsiliasi Fiskal & SPT Tahunan Badan 1771",
    summary: "Merangkai laba komersial, koreksi fiskal, kompensasi rugi, kredit pajak, hingga PPh kurang atau lebih bayar dalam formulir 1771.",
    durationMin: 16,
    tags: ["SPT 1771", "rekonsiliasi fiskal", "kredit pajak", "PPh Badan"],
    blocks: [
      {
        type: "paragraph",
        html: "Semua materi sebelumnya bermuara di sini: <strong>SPT Tahunan PPh Badan</strong> yang dilaporkan memakai <strong>formulir 1771</strong>. Rekonsiliasi fiskal adalah proses menyusun laba komersial menjadi PPh yang benar-benar harus dibayar atau dikembalikan.",
      },
      {
        type: "paragraph",
        html: "Alurnya: <strong>laba komersial</strong> disesuaikan dengan <strong>koreksi fiskal</strong> (positif dan negatif) dan dikurangi <strong>kompensasi rugi</strong> menjadi <strong>Penghasilan Kena Pajak</strong>. PKP dikali tarif <strong>22%</strong> menghasilkan PPh terutang, lalu dikurangi <strong>kredit pajak</strong> yang sudah dibayar selama tahun berjalan.",
      },
      {
        type: "video",
        comp: "KoreksiFiskalVideo",
        title: "Video: Menyusun SPT 1771 dari Laba ke PPh",
        caption: "Dari laba komersial sampai PPh Pasal 29 (kurang bayar) atau Pasal 28A (lebih bayar).",
      },
      {
        type: "callout",
        tone: "key",
        title: "Susunan rekonsiliasi 1771",
        html: "Laba komersial &rarr; (+/-) koreksi fiskal &rarr; (-) kompensasi rugi &rarr; <strong>PKP</strong> &rarr; x 22% = <strong>PPh terutang</strong> &rarr; (-) kredit pajak (PPh 22, 23, 24, 25) &rarr; <strong>PPh 29</strong> (kurang bayar) atau <strong>PPh 28A</strong> (lebih bayar).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Kredit pajak: cicilan sepanjang tahun",
        html: "PPh terutang dikurangi pajak yang sudah disetor: <strong>PPh 22</strong> (impor/transaksi tertentu), <strong>PPh 23</strong> (jasa, sewa, royalti), <strong>PPh 24</strong> (pajak luar negeri), dan <strong>PPh 25</strong> (angsuran bulanan).",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Batas lapor SPT Badan",
        html: "SPT Tahunan Badan wajib dilaporkan paling lambat <strong>4 bulan</strong> setelah akhir tahun pajak. Untuk tahun buku Januari sampai Desember, batasnya umumnya <strong>30 April</strong>.",
      },
      {
        type: "table",
        headers: ["Komponen", "Contoh (Rp juta)"],
        rows: [
          ["Laba komersial", "5.000"],
          ["(+) Koreksi positif", "600"],
          ["(-) Koreksi negatif", "(300)"],
          ["(-) Kompensasi rugi", "(300)"],
          ["Penghasilan Kena Pajak", "5.000"],
          ["PPh terutang (22%)", "1.100"],
          ["(-) Kredit pajak (PPh 22/23/25)", "(900)"],
          ["PPh 29 kurang bayar", "200"],
        ],
        caption: "Susunan rekonsiliasi fiskal dalam SPT 1771 (ilustrasi).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur laba, koreksi, kompensasi rugi, dan kredit pajak untuk melihat apakah hasilnya PPh kurang bayar (29) atau lebih bayar (28A).",
      },
      { type: "widget", widget: "KalkulatorKoreksiFiskal" },
      {
        type: "chart",
        variant: "bar",
        title: "Dari PPh Terutang ke PPh Kurang Bayar (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi susunan SPT 1771",
        note: "Kredit pajak yang sudah disetor sepanjang tahun mengurangi PPh terutang; sisanya menjadi PPh 29 kurang bayar.",
        data: [
          { label: "PPh terutang", value: 1100, color: "#60a5fa" },
          { label: "Kredit pajak", value: 900, color: "#34d399" },
          { label: "PPh 29 (kurang bayar)", value: 200, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menutup SPT dengan PPh 29",
        html: "PT Maju punya laba komersial Rp5 miliar, koreksi positif Rp600 juta, koreksi negatif Rp300 juta, dan kompensasi rugi Rp300 juta. PKP = 5.000 + 600 - 300 - 300 = <strong>Rp5.000 juta</strong>. PPh terutang = 22% x 5.000 = <strong>Rp1.100 juta</strong>. Selama tahun berjalan sudah disetor kredit pajak (PPh 22, 23, 25) total Rp900 juta. Maka <strong>PPh 29 kurang bayar = 1.100 - 900 = Rp200 juta</strong> yang harus dilunasi sebelum lapor SPT.",
      },
      {
        type: "case",
        title: "Sejarah: Dari SPT kertas ke e-Filing dan e-Form",
        html: "Dulu SPT diisi di atas kertas dan diantar ke kantor pajak. Sekitar <strong>2014 sampai 2016</strong>, DJP mendorong pelaporan elektronik lewat <strong>e-Filing</strong> dan <strong>e-Form</strong>. Wajib pajak bisa mengunggah SPT secara daring, mendapat bukti penerimaan elektronik, dan menyusun rekonsiliasi langsung dalam aplikasi. Perubahan ini memangkas antrean, mempercepat proses, dan meningkatkan kepatuhan karena pelaporan jadi jauh lebih mudah.",
      },
      {
        type: "calcExercise",
        prompt: "PKP Rp5.000 juta, PPh terutang 22%, kredit pajak yang sudah disetor Rp900 juta. Berapa PPh 29 kurang bayar (dalam juta)?",
        answer: 200,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "PPh terutang = 22% x 5.000 = 1.100. PPh 29 = 1.100 - 900 = <strong>Rp200 juta</strong>.",
        hint: "Hitung PPh terutang dulu (22% x PKP), lalu kurangi kredit pajak.",
      },
      {
        type: "calcExercise",
        prompt: "PPh terutang Rp1.100 juta, kredit pajak yang sudah disetor Rp1.250 juta. Berapa PPh 28A lebih bayar (dalam juta)?",
        answer: 150,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Kredit pajak lebih besar dari terutang: 1.250 - 1.100 = <strong>Rp150 juta</strong> lebih bayar (PPh 28A).",
        hint: "Bila kredit pajak melebihi PPh terutang, selisihnya adalah lebih bayar (28A).",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya dalam SPT 1771.",
        pairs: [
          { left: "Formulir 1771", right: "SPT Tahunan PPh Badan" },
          { left: "PPh 29", right: "Pajak kurang bayar" },
          { left: "PPh 28A", right: "Pajak lebih bayar" },
          { left: "PPh 25", right: "Angsuran pajak bulanan" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "SPT Tahunan PPh Badan memakai formulir 1771.",
          "Alur: laba komersial, koreksi fiskal, kompensasi rugi, PKP, x 22%, kredit pajak.",
          "Kredit pajak (PPh 22, 23, 24, 25) mengurangi PPh terutang.",
          "PPh 29 jika kurang bayar, PPh 28A jika lebih bayar.",
          "Batas lapor SPT Badan: 4 bulan setelah akhir tahun pajak (umumnya 30 April).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Formulir apa yang dipakai untuk SPT Tahunan PPh Badan?",
            options: ["1770", "1771", "1721", "1111"],
            answer: 1,
            explain: "SPT Tahunan PPh Badan menggunakan formulir 1771.",
          },
          {
            q: "Bila PPh terutang lebih besar dari kredit pajak, hasilnya disebut?",
            options: ["PPh 28A lebih bayar", "PPh 29 kurang bayar", "Nihil", "Restitusi"],
            answer: 1,
            explain: "Selisih kurang bayar disebut PPh Pasal 29 yang harus dilunasi sebelum lapor.",
          },
          {
            q: "Manakah yang termasuk kredit pajak pengurang PPh terutang?",
            options: ["PPh 22, 23, 24, 25", "PPN", "Bea materai", "PBB"],
            answer: 0,
            explain: "Kredit pajak dalam SPT 1771 meliputi PPh 22, 23, 24, dan 25 yang sudah disetor.",
          },
          {
            q: "Batas akhir pelaporan SPT Tahunan Badan untuk tahun buku kalender adalah?",
            options: ["31 Maret", "30 April", "31 Mei", "30 Juni"],
            answer: 1,
            explain: "Batasnya 4 bulan setelah akhir tahun pajak, umumnya 30 April.",
          },
          {
            q: "PKP Rp5.000 juta, kredit pajak Rp900 juta. Berapa PPh 29 kurang bayar?",
            options: ["Rp200 juta", "Rp900 juta", "Rp1.100 juta", "Rp0"],
            answer: 0,
            explain: "PPh terutang 22% x 5.000 = 1.100, dikurangi kredit 900 = Rp200 juta kurang bayar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "biaya-deductible-pasal6",
    levelId: "pphbadan",
    order: 5,
    title: "Biaya yang Boleh Dikurangkan (Pasal 6)",
    summary: "Memetakan biaya 3M yang boleh menjadi pengurang penghasilan bruto menurut Pasal 6 UU PPh, beserta syarat khusus piutang tak tertagih, sumbangan, dan daftar nominatif.",
    durationMin: 15,
    tags: ["Pasal 6", "deductible", "biaya 3M", "PPh Badan"],
    blocks: [
      {
        type: "paragraph",
        html: "Inti dari biaya yang boleh dikurangkan ada pada satu prinsip: biaya itu dipakai untuk <strong>mendapatkan, menagih, dan memelihara</strong> penghasilan (sering disingkat <strong>biaya 3M</strong>). Selama biaya berhubungan langsung dengan kegiatan usaha yang menghasilkan penghasilan objek pajak, <strong>Pasal 6 UU PPh</strong> mengizinkannya menjadi pengurang penghasilan bruto.",
      },
      {
        type: "paragraph",
        html: "Sebaliknya, biaya untuk kepentingan pribadi, biaya yang berhubungan dengan penghasilan final atau bukan objek pajak, tidak boleh dikurangkan. Memahami daftar Pasal 6 membuat rekonsiliasi fiskal lebih akurat dan menghindari koreksi positif yang tidak perlu.",
      },
      {
        type: "video",
        comp: "KoreksiFiskalVideo",
        title: "Video: Biaya 3M sebagai Pengurang Penghasilan",
        caption: "Biaya untuk mendapatkan, menagih, dan memelihara penghasilan boleh dikurangkan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Daftar biaya 3M (Pasal 6 ayat 1)",
        html: "Antara lain: pembelian bahan, gaji dan upah, bunga, sewa, royalti, biaya perjalanan, biaya pengolahan limbah, premi asuransi usaha, penyusutan dan amortisasi, iuran ke dana pensiun yang disahkan, kerugian penjualan harta, kerugian selisih kurs, biaya penelitian dan pengembangan di Indonesia, serta biaya beasiswa, magang, dan pelatihan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Syarat piutang yang nyata-nyata tak dapat ditagih",
        html: "Piutang tak tertagih boleh dibebankan bila memenuhi tiga syarat: <strong>(1)</strong> sudah dibebankan sebagai kerugian di laporan laba rugi komersial, <strong>(2)</strong> diserahkan perkaranya ke pengadilan/DJP atau ada perjanjian tertulis penghapusan, dan <strong>(3)</strong> diumumkan dalam penerbitan umum atau khusus.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Promosi & entertainment butuh daftar nominatif",
        html: "Biaya promosi dan jamuan (entertainment) boleh dikurangkan, tetapi wajib dilampiri <strong>daftar nominatif</strong> yang memuat penerima, tempat, tanggal, dan jumlahnya. Tanpa daftar nominatif, biaya ini dikoreksi positif.",
      },
      {
        type: "table",
        headers: ["Jenis biaya", "Boleh dikurangkan?", "Syarat khusus"],
        rows: [
          ["Gaji, upah, bonus", "Ya", "Terkait pekerjaan, bukan natura rezim lama"],
          ["Bunga, sewa, royalti", "Ya", "Untuk kegiatan usaha (3M)"],
          ["Penyusutan & amortisasi", "Ya", "Sesuai Pasal 11 dan 11A"],
          ["Promosi & entertainment", "Ya", "Wajib daftar nominatif"],
          ["Piutang tak tertagih", "Ya", "3 syarat (dibebankan, diserahkan, diumumkan)"],
          ["Sumbangan tertentu", "Ya", "Bencana nasional, litbang, pendidikan, olahraga, infrastruktur sosial"],
          ["Iuran dana pensiun", "Ya", "Dana pensiun yang disahkan Menteri Keuangan"],
        ],
        caption: "Ringkasan biaya yang boleh dikurangkan menurut Pasal 6 UU PPh.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Pisahkan biaya yang deductible dan non-deductible untuk melihat bagaimana koreksi fiskal terbentuk dan dampaknya pada PKP.",
      },
      { type: "widget", widget: "KalkulatorKoreksiFiskal" },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Biaya Deductible PT Sejahtera (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi struktur biaya usaha",
        note: "Gaji dan pembelian bahan biasanya mendominasi biaya 3M; promosi kecil tetapi tetap wajib daftar nominatif.",
        data: [
          { label: "Pembelian bahan", value: 4000, color: "#60a5fa" },
          { label: "Gaji & upah", value: 2500, color: "#34d399" },
          { label: "Sewa & bunga", value: 900, color: "#fbbf24" },
          { label: "Penyusutan", value: 600, color: "#a78bfa" },
          { label: "Promosi (nominatif)", value: 300, color: "#f472b6" },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Daftar Nominatif pada Biaya Promosi Rp300 juta",
        unit: "Rp juta",
        source: "ilustrasi penerapan PMK 02/PMK.03/2010",
        note: "Tanpa daftar nominatif, seluruh biaya promosi dikoreksi positif sehingga PKP naik dan pajak ikut naik.",
        data: [
          { label: "Promosi diakui (ada nominatif)", value: 300, color: "#34d399" },
          { label: "Promosi dikoreksi (tanpa nominatif)", value: 300, color: "#f87171" },
          { label: "Tambahan PPh 22% jika dikoreksi", value: 66, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Promosi Rp300 juta tanpa daftar nominatif",
        html: "PT Sejahtera membebankan biaya promosi <strong>Rp300 juta</strong>, tetapi tidak menyiapkan daftar nominatif. Saat pemeriksaan, seluruh Rp300 juta <strong>dikoreksi positif</strong> karena tidak memenuhi syarat administratif. PKP naik Rp300 juta, sehingga tambahan PPh = 22% x 300 = <strong>Rp66 juta</strong>. Padahal biaya itu nyata terjadi; yang kurang hanya dokumen pendukung. Disiplin administrasi langsung berdampak pada pajak.",
      },
      {
        type: "case",
        title: "Sejarah: Daftar nominatif diperketat lewat PMK 02/PMK.03/2010",
        html: "Sebelumnya, syarat dokumentasi biaya jamuan dan promosi bersumber dari surat edaran lama DJP. Pada <strong>2010</strong>, terbit <strong>PMK 02/PMK.03/2010</strong> yang menegaskan bahwa biaya promosi hanya boleh dikurangkan bila dibuatkan <strong>daftar nominatif</strong> dan dilampirkan pada SPT Tahunan. Aturan ini menutup celah pembebanan biaya promosi fiktif dan menjadikan dokumentasi sebagai syarat mutlak, bukan sekadar formalitas.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya promosi Rp300 juta dikoreksi positif karena tanpa daftar nominatif. Berapa tambahan PPh Badan (tarif 22%) dalam juta?",
        answer: 66,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Tambahan PPh = 22% x 300 = <strong>Rp66 juta</strong>.",
        hint: "Kalikan nilai biaya yang dikoreksi dengan tarif 22%.",
      },
      {
        type: "calcExercise",
        prompt: "Penghasilan bruto Rp10.000 juta, total biaya 3M yang boleh dikurangkan Rp7.500 juta. Berapa penghasilan neto fiskal (dalam juta)?",
        answer: 2500,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Penghasilan neto = 10.000 - 7.500 = <strong>Rp2.500 juta</strong>.",
        hint: "Kurangi penghasilan bruto dengan biaya yang boleh dikurangkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Biaya ini boleh dikurangkan (deductible) atau tidak menurut Pasal 6?",
        buckets: ["Boleh dikurangkan", "Perlu syarat khusus"],
        items: [
          { text: "Gaji dan upah karyawan", bucket: "Boleh dikurangkan" },
          { text: "Bunga pinjaman untuk usaha", bucket: "Boleh dikurangkan" },
          { text: "Biaya penelitian & pengembangan di Indonesia", bucket: "Boleh dikurangkan" },
          { text: "Biaya promosi dan entertainment", bucket: "Perlu syarat khusus" },
          { text: "Piutang yang nyata-nyata tak dapat ditagih", bucket: "Perlu syarat khusus" },
          { text: "Sumbangan penanggulangan bencana nasional", bucket: "Perlu syarat khusus" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Biaya boleh dikurangkan bila untuk mendapatkan, menagih, dan memelihara penghasilan (3M).",
          "Pasal 6 ayat (1) memuat daftar biaya 3M, termasuk penyusutan dan litbang di Indonesia.",
          "Promosi dan entertainment wajib dilampiri daftar nominatif.",
          "Piutang tak tertagih boleh dibebankan bila memenuhi tiga syarat.",
          "Sumbangan tertentu (bencana nasional, pendidikan, olahraga) boleh dikurangkan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Prinsip utama biaya yang boleh dikurangkan adalah biaya untuk?",
            options: [
              "Kepentingan pribadi pemilik",
              "Mendapatkan, menagih, dan memelihara penghasilan",
              "Membayar dividen",
              "Membayar sanksi pajak",
            ],
            answer: 1,
            explain: "Pasal 6 mengizinkan biaya 3M, yaitu untuk mendapatkan, menagih, dan memelihara penghasilan.",
          },
          {
            q: "Agar biaya promosi boleh dikurangkan, perusahaan wajib menyiapkan?",
            options: ["Daftar nominatif", "Akta notaris", "Surat kuasa", "Faktur pajak masukan"],
            answer: 0,
            explain: "Biaya promosi hanya deductible bila dilampiri daftar nominatif sesuai PMK 02/PMK.03/2010.",
          },
          {
            q: "Manakah yang termasuk biaya 3M Pasal 6?",
            options: ["Sanksi pajak", "Pembagian dividen", "Biaya litbang di Indonesia", "PPh Badan"],
            answer: 2,
            explain: "Biaya penelitian dan pengembangan di Indonesia termasuk biaya yang boleh dikurangkan.",
          },
          {
            q: "Salah satu syarat piutang tak tertagih boleh dibebankan adalah?",
            options: [
              "Cukup dicatat di buku besar",
              "Diumumkan dalam penerbitan umum atau khusus",
              "Disetujui pemegang saham",
              "Dibayar lunas dulu",
            ],
            answer: 1,
            explain: "Salah satu syaratnya adalah piutang itu diumumkan dalam penerbitan umum atau khusus.",
          },
          {
            q: "Biaya promosi Rp300 juta dikoreksi karena tanpa nominatif. Tambahan PPh (22%)?",
            options: ["Rp30 juta", "Rp66 juta", "Rp300 juta", "Rp22 juta"],
            answer: 1,
            explain: "Tambahan PPh = 22% x Rp300 juta = Rp66 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "biaya-nondeductible-natura",
    levelId: "pphbadan",
    order: 6,
    title: "Biaya Non-Deductible & Natura pasca UU HPP",
    summary: "Mengenali biaya yang tidak boleh dikurangkan menurut Pasal 9 dan memahami pergeseran perlakuan natura dari rezim lama ke UU HPP (PP 55/2022, PMK 66/2023).",
    durationMin: 16,
    tags: ["Pasal 9", "non-deductible", "natura", "UU HPP"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua biaya di laporan komersial boleh menjadi pengurang pajak. <strong>Pasal 9 UU PPh</strong> mendaftar biaya yang <strong>tidak boleh dikurangkan</strong> (non-deductible). Biaya seperti ini memicu <strong>koreksi positif</strong> saat menyusun laba fiskal.",
      },
      {
        type: "paragraph",
        html: "Salah satu perubahan terbesar datang dari <strong>UU HPP (2021)</strong> yang mengubah perlakuan <strong>natura dan kenikmatan</strong>. Aturan turunannya, <strong>PP 55/2022</strong> dan <strong>PMK 66/2023</strong>, membalik logika lama: kini natura umumnya boleh dikurangkan pemberi, tetapi menjadi objek pajak bagi penerima.",
      },
      {
        type: "video",
        comp: "KoreksiFiskalVideo",
        title: "Video: Biaya Non-Deductible Pasal 9",
        caption: "Dividen, sanksi pajak, PPh, dan biaya pribadi pemegang saham tidak boleh dikurangkan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Biaya yang TIDAK boleh dikurangkan (Pasal 9)",
        html: "Antara lain: <strong>pembagian laba/dividen</strong>, biaya untuk kepentingan pribadi pemegang saham, pembentukan dana cadangan (kecuali jenis tertentu seperti cadangan bank dan asuransi), <strong>premi asuransi kesehatan/jiwa pribadi</strong> yang dibayar sendiri, <strong>sanksi pajak</strong> (bunga, denda, kenaikan), <strong>Pajak Penghasilan</strong> itu sendiri, serta gaji anggota persekutuan (CV/firma) yang modalnya tidak terbagi atas saham.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Pergeseran perlakuan natura",
        html: "<strong>Rezim lama:</strong> natura/kenikmatan TIDAK boleh dikurangkan pemberi dan BUKAN objek pajak bagi penerima. <strong>Sejak UU HPP:</strong> natura UMUMNYA boleh dikurangkan pemberi (deductible) dan menjadi OBJEK PPh bagi penerima.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Natura yang dikecualikan dari objek pajak",
        html: "Tetap bukan objek bagi penerima: makanan/minuman bagi <strong>seluruh pegawai</strong> di tempat kerja, natura di <strong>daerah tertentu</strong>, natura karena <strong>keharusan pekerjaan</strong> (mis. seragam, alat keselamatan), natura yang bersumber dari <strong>APBN/APBD</strong>, dan jenis tertentu sampai batas nilai (mis. bingkisan hari raya dan fasilitas olahraga sampai ambang tertentu).",
      },
      {
        type: "table",
        headers: ["Aspek", "Rezim lama (sebelum UU HPP)", "UU HPP (PP 55/2022, PMK 66/2023)"],
        rows: [
          ["Bagi pemberi kerja", "Tidak boleh dikurangkan", "Umumnya boleh dikurangkan (deductible)"],
          ["Bagi penerima", "Bukan objek pajak", "Umumnya menjadi objek PPh"],
          ["Makan/minum seluruh pegawai", "Bukan objek", "Tetap dikecualikan (bukan objek)"],
          ["Natura keharusan pekerjaan", "Bukan objek", "Tetap dikecualikan (bukan objek)"],
          ["Natura daerah tertentu", "Bukan objek", "Tetap dikecualikan (bukan objek)"],
        ],
        caption: "Perbandingan perlakuan natura sebelum dan sesudah UU HPP.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur jenis dan nilai natura untuk melihat apakah ia menjadi objek pajak bagi pegawai dan boleh dikurangkan bagi perusahaan.",
      },
      { type: "widget", widget: "SimulatorNatura" },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Pergeseran Natura Rp500 juta pada Pajak (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi penerapan PP 55/2022 dan PMK 66/2023",
        note: "Pemberi kini menghemat PPh Badan karena natura deductible, tetapi nilainya menjadi penghasilan yang dipotong PPh 21 bagi pegawai.",
        data: [
          { label: "Penghematan PPh Badan (22%)", value: 110, color: "#34d399" },
          { label: "Natura jadi objek (basis PPh 21)", value: 500, color: "#60a5fa" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Komposisi Biaya yang Dikoreksi Positif (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi koreksi Pasal 9",
        note: "Sanksi pajak, dividen, dan biaya pribadi pemegang saham adalah penyumbang koreksi positif yang umum.",
        data: [
          { label: "Sanksi pajak", value: 200, color: "#f87171" },
          { label: "Biaya pribadi pemegang saham", value: 350, color: "#fbbf24" },
          { label: "Premi asuransi pribadi", value: 150, color: "#a78bfa" },
          { label: "Cadangan tak diizinkan", value: 300, color: "#f472b6" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Natura Rp500 juta pasca UU HPP",
        html: "PT Anugerah memberi fasilitas natura (di luar yang dikecualikan) senilai <strong>Rp500 juta</strong>. Di rezim lama, biaya ini dikoreksi positif (tidak deductible) dan tidak dipajaki di pegawai. Sejak UU HPP, biaya itu kini <strong>boleh dikurangkan</strong>, sehingga perusahaan hemat PPh Badan = 22% x 500 = <strong>Rp110 juta</strong>. Sebagai konsekuensinya, Rp500 juta menjadi <strong>objek PPh 21</strong> bagi pegawai penerima. Bebannya bergeser dari perusahaan ke pegawai, dengan basis pajak yang lebih luas.",
      },
      {
        type: "case",
        title: "Sejarah: Dari UU PPh lama ke UU HPP 2021 dan PMK 66/2023",
        html: "Selama puluhan tahun, natura diperlakukan dengan prinsip <strong>non-deductible, non-taxable</strong>: perusahaan tidak boleh membebankan, pegawai tidak dipajaki. Lewat <strong>UU HPP yang disahkan 2021</strong>, prinsip itu dibalik. Aturan pelaksana <strong>PP 55/2022</strong> lalu <strong>PMK 66/2023</strong> menetapkan natura umumnya <strong>deductible</strong> bagi pemberi dan <strong>objek pajak</strong> bagi penerima, dengan sederet pengecualian. Tujuannya memperluas basis pajak orang pribadi sekaligus menyamakan perlakuan antara gaji tunai dan fasilitas non-tunai.",
      },
      {
        type: "calcExercise",
        prompt: "Natura Rp500 juta kini boleh dikurangkan pemberi. Berapa penghematan PPh Badan (tarif 22%) dalam juta?",
        answer: 110,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Penghematan PPh Badan = 22% x 500 = <strong>Rp110 juta</strong>.",
        hint: "Kalikan nilai natura yang kini deductible dengan tarif 22%.",
      },
      {
        type: "calcExercise",
        prompt: "Laba komersial Rp4.000 juta memuat sanksi pajak Rp200 juta dan biaya pribadi pemegang saham Rp300 juta (keduanya non-deductible). Berapa PKP setelah koreksi positif itu (dalam juta)?",
        answer: 4500,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "PKP = 4.000 + 200 + 300 = <strong>Rp4.500 juta</strong>.",
        hint: "Tambahkan biaya non-deductible ke laba komersial sebagai koreksi positif.",
      },
      {
        type: "classifyExercise",
        prompt: "Biaya ini boleh dikurangkan (deductible) atau tidak (non-deductible) menurut Pasal 9?",
        buckets: ["Deductible", "Non-deductible"],
        items: [
          { text: "Pembagian dividen ke pemegang saham", bucket: "Non-deductible" },
          { text: "Sanksi/denda pajak", bucket: "Non-deductible" },
          { text: "Pajak Penghasilan (PPh) itu sendiri", bucket: "Non-deductible" },
          { text: "Biaya pribadi pemegang saham", bucket: "Non-deductible" },
          { text: "Natura (di luar pengecualian) sejak UU HPP", bucket: "Deductible" },
          { text: "Gaji karyawan untuk kegiatan usaha", bucket: "Deductible" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Pasal 9 mendaftar biaya non-deductible: dividen, sanksi pajak, PPh, biaya pribadi pemegang saham.",
          "Premi asuransi kesehatan/jiwa pribadi yang dibayar sendiri tidak boleh dikurangkan.",
          "Rezim lama: natura non-deductible bagi pemberi dan bukan objek bagi penerima.",
          "Sejak UU HPP: natura umumnya deductible bagi pemberi dan objek pajak bagi penerima.",
          "Pengecualian tetap ada: makan/minum seluruh pegawai, daerah tertentu, keharusan kerja, APBN/APBD.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Manakah yang termasuk biaya non-deductible menurut Pasal 9?",
            options: ["Gaji karyawan", "Bunga pinjaman usaha", "Pembagian dividen", "Sewa kantor"],
            answer: 2,
            explain: "Pembagian laba/dividen tidak boleh dikurangkan dari penghasilan bruto.",
          },
          {
            q: "Di rezim lama, natura/kenikmatan bagi penerima diperlakukan sebagai?",
            options: ["Objek pajak", "Bukan objek pajak", "Kredit pajak", "Dividen"],
            answer: 1,
            explain: "Di rezim lama, natura bukan objek pajak bagi penerima dan tidak deductible bagi pemberi.",
          },
          {
            q: "Sejak UU HPP, perlakuan natura bagi pemberi kerja umumnya menjadi?",
            options: ["Tetap non-deductible", "Boleh dikurangkan (deductible)", "Dikenai PPN", "Dilarang"],
            answer: 1,
            explain: "Sejak UU HPP, natura umumnya boleh dikurangkan oleh pemberi kerja.",
          },
          {
            q: "Manakah natura yang TETAP dikecualikan (bukan objek pajak)?",
            options: [
              "Bonus tunai akhir tahun",
              "Makanan/minuman bagi seluruh pegawai di tempat kerja",
              "Mobil dinas mewah direksi",
              "Dividen saham",
            ],
            answer: 1,
            explain: "Makanan/minuman bagi seluruh pegawai di tempat kerja tetap dikecualikan dari objek pajak.",
          },
          {
            q: "Aturan pelaksana yang menegaskan perlakuan natura pasca UU HPP adalah?",
            options: ["PMK 02/2010", "PP 55/2022 dan PMK 66/2023", "UU PPh 1983", "PMK 18/2021"],
            answer: 1,
            explain: "PP 55/2022 dan PMK 66/2023 mengatur perlakuan natura setelah UU HPP.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "angsuran-pph-25",
    levelId: "pphbadan",
    order: 7,
    title: "Angsuran PPh 25 & Arus Kas Pajak",
    summary: "Mencicil PPh badan tahun berjalan setiap bulan agar tidak menumpuk di akhir tahun, dan dampaknya pada arus kas.",
    durationMin: 13,
    tags: ["PPh 25", "angsuran", "arus kas", "kredit pajak"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan tidak menunggu akhir tahun untuk membayar PPh badan. Lewat <strong>angsuran PPh 25</strong>, pajak tahun berjalan dicicil setiap bulan. Cicilan ini lalu diperhitungkan sebagai <strong>kredit pajak</strong> di SPT Tahunan, sehingga akhir tahun hanya tinggal melunasi kekurangannya.",
      },
      {
        type: "video",
        comp: "PPh25AngsuranVideo",
        title: "Video: Angsuran PPh 25 Bulanan",
        caption: "Dua belas cicilan yang menjadi kredit pajak dan mengurangi PPh terutang di SPT Tahunan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rumus angsuran",
        html: "Angsuran PPh 25 per bulan = (<strong>PPh terutang menurut SPT Tahunan tahun lalu</strong> dikurangi kredit pajak PPh 22, 23, dan 24) dibagi <strong>12</strong>. Disetor paling lambat tanggal 15 bulan berikutnya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Akhir tahun: kurang atau lebih bayar",
        html: "Total angsuran yang sudah disetor menjadi kredit pajak. Jika PPh terutang lebih besar, sisanya <strong>PPh 29</strong> (disetor sebelum lapor). Jika lebih kecil, ada <strong>lebih bayar (PPh 28A)</strong> yang bisa direstitusi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Atur PPh terutang tahun lalu dan kredit pajaknya untuk melihat besar angsuran bulanan yang harus disetor.",
      },
      { type: "widget", widget: "KalkulatorAngsuranPPh25" },
      {
        type: "chart",
        variant: "bar",
        title: "Angsuran Bulanan vs Pelunasan Sekaligus (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi konsep arus kas pajak",
        note: "Mencicil Rp80 juta per bulan jauh lebih ringan bagi kas daripada menyetor Rp960 juta sekaligus di akhir tahun.",
        data: [
          { label: "Angsuran/bulan", value: 80, color: "#34d399" },
          { label: "Bila sekaligus", value: 960, color: "#fb7185" },
        ],
      },
      {
        type: "chart",
        variant: "area",
        title: "Akumulasi Angsuran PPh 25 Sepanjang Tahun (ilustrasi)",
        unit: "Rp juta kumulatif",
        source: "perhitungan 12 x Rp80 juta",
        note: "Pada akhir tahun, kredit pajak dari angsuran mencapai Rp960 juta dan langsung mengurangi PPh terutang.",
        data: [
          { label: "Mar", value: 240 },
          { label: "Jun", value: 480 },
          { label: "Sep", value: 720 },
          { label: "Des", value: 960 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menghitung angsuran dan kekurangan akhir tahun",
        html: "PPh terutang PT Andal tahun lalu Rp1.200 juta, dengan kredit pajak PPh 22/23 sebesar Rp240 juta. Dasar angsuran = 1.200 - 240 = Rp960 juta, sehingga angsuran PPh 25 = 960 / 12 = <strong>Rp80 juta per bulan</strong>. Bila tahun ini PPh terutang ternyata Rp1.100 juta dan total kredit pajak (angsuran Rp960 juta + potongan Rp200 juta) = Rp1.160 juta, maka terjadi <strong>lebih bayar Rp60 juta</strong> yang bisa direstitusi.",
      },
      {
        type: "calcExercise",
        prompt: "PPh terutang tahun lalu Rp1.200 juta, kredit pajak PPh 22/23 Rp240 juta. Berapa angsuran PPh 25 per bulan (dalam juta)?",
        answer: 80,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Angsuran = (1.200 - 240) / 12 = 960 / 12 = <strong>Rp80 juta per bulan</strong>.",
        hint: "Kurangi kredit pajak dari PPh terutang, lalu bagi 12.",
      },
      {
        type: "calcExercise",
        prompt: "Jika sepanjang tahun perusahaan menyetor 12 angsuran @ Rp80 juta, berapa total kredit pajak dari PPh 25 (dalam juta)?",
        answer: 960,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "12 x 80 = <strong>Rp960 juta</strong>, seluruhnya menjadi kredit pajak di SPT Tahunan.",
        hint: "Kalikan angsuran bulanan dengan 12.",
      },
      {
        type: "classifyExercise",
        prompt: "Kondisi akhir tahun ini menghasilkan kurang bayar (PPh 29) atau lebih bayar (PPh 28A)?",
        buckets: ["PPh 29 (kurang bayar)", "PPh 28A (lebih bayar)"],
        items: [
          { text: "PPh terutang lebih besar dari total kredit pajak", bucket: "PPh 29 (kurang bayar)" },
          { text: "Total angsuran melebihi PPh terutang", bucket: "PPh 28A (lebih bayar)" },
          { text: "Laba melonjak jauh di atas tahun lalu", bucket: "PPh 29 (kurang bayar)" },
          { text: "Usaha menurun sehingga PPh terutang kecil", bucket: "PPh 28A (lebih bayar)" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Sistem Angsuran sejak UU PPh 1984",
        html: "Sistem pembayaran pajak secara mengangsur dalam tahun berjalan diperkenalkan lewat <strong>UU PPh 1983</strong> yang berlaku mulai <strong>1984</strong>, menggantikan pola pembayaran sekaligus. Dengan mengangsur, beban kas perusahaan tersebar merata sepanjang tahun dan negara menerima penerimaan lebih stabil. Mekanisme ini menjadi tulang punggung arus kas pajak korporat sampai sekarang.",
      },
      {
        type: "takeaways",
        items: [
          "Angsuran PPh 25 mencicil PPh badan tahun berjalan setiap bulan.",
          "Angsuran = (PPh terutang tahun lalu - kredit pajak) dibagi 12.",
          "Angsuran disetor paling lambat tanggal 15 bulan berikutnya.",
          "Akhir tahun bisa kurang bayar (PPh 29) atau lebih bayar (PPh 28A).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Angsuran PPh 25 dihitung dari?",
            options: ["Omzet bulan ini", "PPh terutang tahun lalu dikurangi kredit pajak, dibagi 12", "Laba bulan berjalan", "Total aset"],
            answer: 1,
            explain: "Dasarnya PPh terutang SPT tahun lalu dikurangi kredit pajak, lalu dibagi 12.",
          },
          {
            q: "Angsuran PPh 25 disetor paling lambat?",
            options: ["Tanggal 15 bulan berikutnya", "Akhir tahun", "Tanggal 30 April", "Setiap minggu"],
            answer: 0,
            explain: "Batas setor angsuran masa umumnya tanggal 15 bulan berikutnya.",
          },
          {
            q: "Angsuran yang sudah disetor sepanjang tahun berperan sebagai?",
            options: ["Beban tambahan", "Kredit pajak di SPT Tahunan", "Denda", "Dividen"],
            answer: 1,
            explain: "Angsuran menjadi kredit pajak yang mengurangi PPh terutang akhir tahun.",
          },
          {
            q: "PPh terutang lalu Rp600 juta, kredit pajak Rp120 juta. Angsuran per bulan?",
            options: ["Rp40 juta", "Rp50 juta", "Rp60 juta", "Rp10 juta"],
            answer: 0,
            explain: "(600 - 120) / 12 = 480 / 12 = Rp40 juta.",
          },
          {
            q: "Bila total kredit pajak melebihi PPh terutang, terjadi?",
            options: ["PPh 29 kurang bayar", "PPh 28A lebih bayar", "Tidak ada apa-apa", "Sanksi"],
            answer: 1,
            explain: "Kelebihan pembayaran menjadi PPh 28A yang dapat direstitusi.",
          },
        ],
      },
    ],
  },
];
