import type { Lesson } from "../../../types";

export const level3: Lesson[] = [
  // ============================================================
  {
    id: "fasilitas-31e-umkm",
    levelId: "strategi",
    order: 1,
    title: "Fasilitas Pasal 31E & Tarif Final UMKM",
    summary: "Diskon 50% PPh Badan untuk badan kecil dan skema final 0,5%, dua fasilitas yang sering terlewat.",
    durationMin: 14,
    tags: ["Pasal 31E", "PP 55/2022", "fasilitas", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua perusahaan harus membayar 22% penuh. Undang-undang menyediakan <strong>fasilitas Pasal 31E</strong> berupa pengurangan tarif 50% untuk badan dengan peredaran bruto kecil, serta skema <strong>PPh final 0,5%</strong> (PP 55/2022) bagi usaha mikro. Memilih dan memakai fasilitas ini adalah langkah perencanaan paling dasar.",
      },
      {
        type: "video",
        comp: "Fasilitas31EVideo",
        title: "Video: Fasilitas Pasal 31E",
        caption: "Diskon 50% atas bagian PKP dari peredaran bruto sampai Rp4,8 M, berlaku jika omzet sampai Rp50 M.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Cara kerja Pasal 31E",
        html: "Badan dengan peredaran bruto sampai <strong>Rp50 miliar</strong> mendapat pengurangan tarif 50% (tarif efektif 11%) atas bagian PKP yang berasal dari peredaran bruto sampai <strong>Rp4,8 miliar</strong>. Sisanya kena tarif penuh 22%.",
      },
      {
        type: "callout",
        tone: "info",
        title: "PPh Final 0,5% (PP 55/2022)",
        html: "Usaha dengan omzet sampai <strong>Rp4,8 miliar</strong> setahun dapat memakai PPh final <strong>0,5% dari omzet</strong>. Untuk PT, jangka waktunya <strong>3 tahun</strong>; CV/firma 4 tahun; orang pribadi 7 tahun. Setelah itu wajib pembukuan dan tarif normal.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tarif Efektif PPh Badan menurut Skala Omzet (ilustrasi)",
        unit: "% efektif",
        source: "ilustrasi konsep berdasarkan Pasal 31E & PP 55/2022",
        note: "Badan kecil bisa menikmati tarif efektif jauh di bawah 22%. Fasilitas ini otomatis bagi yang memenuhi syarat, tetapi harus dihitung benar.",
        data: [
          { label: "Omzet < 4,8 M (final 0,5%)", value: 6, color: "#34d399" },
          { label: "Omzet < 4,8 M (31E)", value: 11, color: "#60a5fa" },
          { label: "Omzet 4,8-50 M", value: 16, color: "#fbbf24" },
          { label: "Omzet > 50 M", value: 22, color: "#fb7185" },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur omzet dan margin untuk melihat bagaimana fasilitas Pasal 31E menurunkan tarif efektif PPh Badan.",
      },
      { type: "widget", widget: "SimulatorPPhBadan" },
      {
        type: "case",
        title: "Studi Kasus: Memanfaatkan Pasal 31E",
        html: "PT Karya beromzet Rp8 miliar dengan PKP Rp960 juta. Bagian PKP dari omzet Rp4,8 M = (4.800/8.000) x 960 = Rp576 juta kena tarif efektif 11% = Rp63,36 juta. Sisanya Rp384 juta kena 22% = Rp84,48 juta. Total PPh = <strong>Rp147,84 juta</strong>, lebih rendah dari 22% x 960 = Rp211,2 juta. Fasilitas ini menghemat sekitar Rp63 juta tanpa rekayasa apa pun.",
      },
      {
        type: "calcExercise",
        prompt: "Omzet Rp4 miliar (di bawah Rp4,8 M), PKP Rp500 juta, seluruhnya dapat fasilitas 31E (tarif efektif 11%). Berapa PPh Badan dalam juta?",
        answer: 55,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Karena omzet di bawah Rp4,8 M, seluruh PKP kena tarif efektif 11%: 11% x 500 = <strong>Rp55 juta</strong>.",
        hint: "Tarif efektif fasilitas penuh = 50% x 22% = 11%.",
      },
      {
        type: "calcExercise",
        prompt: "Usaha mikro dengan omzet Rp3 miliar memakai PPh final 0,5%. Berapa PPh final setahun dalam juta?",
        answer: 15,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "PPh final = 0,5% x 3.000 juta = <strong>Rp15 juta</strong>, dihitung dari omzet, bukan laba.",
        hint: "Kalikan omzet dengan 0,5%.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kondisi dengan fasilitas yang tepat.",
        pairs: [
          { left: "Omzet sampai Rp4,8 M, ingin sederhana", right: "PPh final 0,5% dari omzet" },
          { left: "Omzet sampai Rp50 M, pakai pembukuan", right: "Diskon tarif 50% (Pasal 31E)" },
          { left: "Omzet di atas Rp50 M", right: "Tarif penuh 22%" },
          { left: "PT yang sudah 3 tahun pakai final", right: "Beralih ke tarif normal/pembukuan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Tax Holiday Pertama Indonesia 2011",
        html: "Untuk menarik investasi industri pionir, pemerintah menerbitkan <strong>PMK 130/2011</strong> yang menghidupkan kembali <strong>tax holiday</strong>: pembebasan PPh Badan selama periode tertentu. Kebijakan ini melengkapi fasilitas seperti Pasal 31E dengan insentif yang lebih besar bagi investasi strategis. Sejak itu, peta fasilitas pajak Indonesia berkembang, dan memahami fasilitas mana yang berhak dipakai menjadi bagian penting tax planning.",
      },
      {
        type: "takeaways",
        items: [
          "Pasal 31E memberi diskon tarif 50% bagi badan beromzet sampai Rp50 M.",
          "Diskon berlaku atas bagian PKP dari peredaran bruto sampai Rp4,8 M.",
          "PP 55/2022 menawarkan PPh final 0,5% dari omzet untuk usaha mikro.",
          "Fasilitas ini sah dan otomatis bagi yang memenuhi syarat, asal dihitung benar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fasilitas Pasal 31E berupa?",
            options: ["Pembebasan total", "Pengurangan tarif 50%", "Tarif naik 50%", "Tambahan denda"],
            answer: 1,
            explain: "Pasal 31E memberi pengurangan tarif 50%, sehingga efektif 11% atas bagian PKP tertentu.",
          },
          {
            q: "Batas peredaran bruto agar berhak fasilitas Pasal 31E?",
            options: ["Rp4,8 M", "Rp50 M", "Rp500 juta", "Tanpa batas"],
            answer: 1,
            explain: "Fasilitas berlaku untuk badan dengan peredaran bruto sampai Rp50 miliar.",
          },
          {
            q: "PPh final PP 55/2022 dihitung dari?",
            options: ["Laba bersih", "Omzet/peredaran bruto", "Aset", "Modal"],
            answer: 1,
            explain: "Tarif final 0,5% dikenakan atas omzet, bukan laba.",
          },
          {
            q: "Jangka waktu PPh final 0,5% untuk PT adalah?",
            options: ["1 tahun", "3 tahun", "7 tahun", "Selamanya"],
            answer: 1,
            explain: "Untuk wajib pajak badan berbentuk PT, jangka waktunya 3 tahun.",
          },
          {
            q: "Omzet Rp2 M memakai final 0,5%, PPh setahunnya?",
            options: ["Rp10 juta", "Rp20 juta", "Rp100 juta", "Rp1 juta"],
            answer: 0,
            explain: "0,5% x Rp2.000 juta = Rp10 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "thin-capitalization-der",
    levelId: "strategi",
    order: 2,
    title: "Thin Capitalization & Rasio Utang-Modal (DER 4:1)",
    summary: "PMK 169/2015 membatasi rasio utang terhadap modal maksimal 4:1; bunga atas utang berlebih tidak boleh dikurangkan.",
    durationMin: 14,
    tags: ["thin capitalization", "DER", "PMK 169/2015", "bunga", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "Perusahaan bisa tergoda menumpuk <strong>utang</strong> (sering dari pihak afiliasi) agar beban bunganya besar dan menggerus laba kena pajak. Praktik ini disebut <strong>thin capitalization</strong>: modal sengaja dibuat tipis, utang dibuat tebal. Untuk mencegahnya, pemerintah membatasi perbandingan utang terhadap modal.",
      },
      {
        type: "paragraph",
        html: "Aturannya ada di <strong>PMK 169/PMK.010/2015</strong>: untuk keperluan PPh, perbandingan utang terhadap modal (<strong>Debt-to-Equity Ratio / DER</strong>) dibatasi maksimal <strong>4 : 1</strong>. Bunga atas bagian utang yang melebihi 4 kali ekuitas tidak boleh dikurangkan dan harus dikoreksi positif saat menghitung penghasilan kena pajak.",
      },
      {
        type: "video",
        comp: "ThinCapVideo",
        title: "Video: Thin Capitalization & DER 4:1",
        caption: "Bagaimana bunga atas utang berlebih dikoreksi agar tidak menggerus pajak secara tidak wajar.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Aturan DER 4:1",
        html: "Utang yang bunganya boleh dibebankan dibatasi maksimal <strong>4 kali ekuitas</strong>. Jika utang melebihi batas itu, bunga atas kelebihannya <strong>dikoreksi positif</strong> (tidak deductible).",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hati-hati utang afiliasi",
        html: "Thin capitalization sering terjadi lewat pinjaman dari induk atau perusahaan satu grup. Selain batas DER 4:1, bunga pinjaman afiliasi juga harus wajar (<em>arm's length</em>); bila tidak, bisa dikoreksi lewat aturan transfer pricing.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur nilai ekuitas, utang, dan tarif bunga untuk melihat berapa bunga yang boleh dibebankan dan berapa yang dikoreksi.",
      },
      { type: "widget", widget: "KalkulatorThinCap" },
      {
        type: "chart",
        variant: "bar",
        title: "Bunga Boleh Dibebankan vs Dikoreksi (ekuitas Rp1 M, utang Rp5 M, bunga 12%)",
        unit: "Rp juta",
        source: "ilustrasi berdasarkan PMK 169/2015 (DER 4:1)",
        note: "Dengan ekuitas Rp1 M, utang yang diakui maksimal Rp4 M; bunga atas Rp1 M sisanya dikoreksi positif.",
        data: [
          { label: "Bunga boleh dibebankan (4 M)", value: 480, color: "#34d399" },
          { label: "Bunga dikoreksi (1 M)", value: 120, color: "#fb7185" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Koreksi Bunga karena DER",
        html: "PT Modal Tipis punya ekuitas <strong>Rp1 miliar</strong> dan utang <strong>Rp5 miliar</strong> berbunga 12% per tahun. Batas utang yang diakui = 4 x Rp1 M = <strong>Rp4 miliar</strong>. Bunga total = 12% x Rp5 M = Rp600 juta, tetapi yang boleh dibebankan hanya 12% x Rp4 M = <strong>Rp480 juta</strong>. Selisih <strong>Rp120 juta</strong> dikoreksi positif. Dengan tarif PPh 22%, koreksi ini menambah pajak sekitar Rp26,4 juta dibanding bila seluruh bunga diakui.",
      },
      {
        type: "case",
        title: "Sejarah: Aturan Thin Cap yang Tertunda Sejak 1984",
        html: "Pembatasan DER sebenarnya sudah lama dikenal. Lewat <strong>KMK Nomor 1002/KMK.04/1984</strong>, pemerintah pernah menetapkan batas perbandingan utang dan modal. Namun penerapannya kemudian <strong>ditunda</strong> karena dikhawatirkan menghambat dunia usaha yang saat itu butuh pembiayaan. Aturan ini baru benar-benar efektif kembali tiga dekade kemudian lewat <strong>PMK 169/PMK.010/2015</strong> dengan batas DER 4:1 yang berlaku sejak tahun pajak 2016.",
      },
      {
        type: "calcExercise",
        prompt: "Ekuitas Rp2 miliar, utang Rp12 miliar, bunga 10% per tahun. Berapa bunga (dalam juta) yang BOLEH dibebankan menurut batas DER 4:1?",
        answer: 800,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Utang diakui maksimal = 4 x Rp2 M = Rp8 M. Bunga boleh dibebankan = 10% x Rp8.000 juta = <strong>Rp800 juta</strong>.",
        hint: "Batasi utang dulu ke 4 x ekuitas, baru kalikan tarif bunga.",
      },
      {
        type: "calcExercise",
        prompt: "Dari soal di atas (ekuitas Rp2 M, utang Rp12 M, bunga 10%), berapa bunga (dalam juta) yang DIKOREKSI positif?",
        answer: 400,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Bunga total = 10% x Rp12 M = Rp1.200 juta. Yang boleh dibebankan Rp800 juta, jadi dikoreksi = 1.200 - 800 = <strong>Rp400 juta</strong>.",
        hint: "Bunga total dikurangi bunga yang boleh dibebankan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan berikut tentang thin capitalization.",
        buckets: ["Sesuai aturan", "Melanggar/dikoreksi"],
        items: [
          { text: "Utang 3 kali ekuitas, semua bunga dibebankan", bucket: "Sesuai aturan" },
          { text: "Utang 4 kali ekuitas, semua bunga dibebankan", bucket: "Sesuai aturan" },
          { text: "Utang 6 kali ekuitas, semua bunga dibebankan", bucket: "Melanggar/dikoreksi" },
          { text: "Bunga atas utang di atas 4x ekuitas tetap dibebankan", bucket: "Melanggar/dikoreksi" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Thin capitalization adalah modal tipis-utang tebal untuk menggerus pajak lewat bunga.",
          "PMK 169/2015 membatasi rasio utang terhadap modal (DER) maksimal 4:1.",
          "Bunga atas bagian utang di atas 4x ekuitas dikoreksi positif (non-deductible).",
          "Utang afiliasi juga harus wajar (arm's length), bukan hanya patuh DER.",
          "Aturan ini sempat ada sejak 1984, ditunda, lalu efektif lagi via PMK 169/2015.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Batas rasio utang terhadap modal (DER) untuk keperluan PPh menurut PMK 169/2015 adalah?",
            options: ["1:1", "2:1", "4:1", "Tanpa batas"],
            answer: 2,
            explain: "PMK 169/2015 menetapkan batas DER maksimal 4:1.",
          },
          {
            q: "Apa yang terjadi pada bunga atas utang yang melebihi 4 kali ekuitas?",
            options: ["Tetap boleh dibebankan", "Dikoreksi positif (tidak boleh dikurangkan)", "Dikenai PPN", "Dibebaskan pajak"],
            answer: 1,
            explain: "Bunga atas kelebihan utang dikoreksi positif sehingga tidak mengurangi penghasilan kena pajak.",
          },
          {
            q: "Tujuan utama aturan thin capitalization adalah?",
            options: ["Menaikkan tarif PPN", "Mencegah penumpukan utang untuk menggerus pajak", "Mempercepat penyusutan", "Membebaskan UMKM"],
            answer: 1,
            explain: "Aturan ini mencegah perusahaan menumpuk utang (sering dari afiliasi) hanya agar bunga menggerus pajak.",
          },
          {
            q: "Ekuitas Rp1 M, utang Rp5 M. Berapa utang maksimal yang bunganya diakui?",
            options: ["Rp1 M", "Rp4 M", "Rp5 M", "Rp20 M"],
            answer: 1,
            explain: "Utang diakui maksimal 4 x ekuitas = 4 x Rp1 M = Rp4 M.",
          },
          {
            q: "Selain batas DER, bunga pinjaman dari afiliasi juga harus?",
            options: ["Bebas pajak", "Wajar sesuai prinsip arm's length", "Lebih tinggi dari pasar", "Tanpa bunga"],
            answer: 1,
            explain: "Bunga pinjaman afiliasi harus wajar (arm's length); bila tidak, dapat dikoreksi lewat aturan transfer pricing.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "insentif-pajak",
    levelId: "strategi",
    order: 3,
    title: "Insentif Pajak: Tax Holiday, Tax Allowance & Super Deduction",
    summary: "Tiga insentif besar untuk investasi: pembebasan PPh, pengurangan penghasilan neto, dan pengurangan biaya sampai 300%.",
    durationMin: 15,
    tags: ["tax holiday", "tax allowance", "super deduction", "insentif", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain fasilitas dasar, pemerintah menyediakan <strong>insentif pajak</strong> yang lebih besar untuk mendorong investasi, hilirisasi, dan pengembangan sumber daya manusia. Tiga yang paling penting: <strong>tax holiday</strong>, <strong>tax allowance</strong>, dan <strong>super deduction</strong>.",
      },
      {
        type: "paragraph",
        html: "Memilih insentif yang tepat adalah inti tax planning untuk perusahaan besar. Setiap insentif punya syarat sektor, nilai investasi, dan komitmen tertentu, jadi tidak bisa dipakai sembarangan.",
      },
      {
        type: "video",
        comp: "Fasilitas31EVideo",
        title: "Video: Peta Fasilitas & Insentif Pajak",
        caption: "Dari fasilitas dasar sampai insentif besar untuk investasi pionir.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tax Holiday (mis. PMK 130/2020)",
        html: "Pembebasan atau pengurangan <strong>PPh Badan</strong> untuk <strong>industri pionir</strong>. Jangka waktunya <strong>5 sampai 20 tahun</strong> tergantung nilai investasi, lalu ada masa transisi pengurangan setelahnya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tax Allowance (PP 78/2019)",
        html: "Pengurangan penghasilan neto sebesar <strong>30% dari nilai penanaman modal</strong>, dibebankan <strong>5% per tahun selama 6 tahun</strong>, ditambah penyusutan dan amortisasi dipercepat. Cocok untuk sektor dan daerah tertentu.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Super Deduction (PP 45/2019)",
        html: "Biaya kegiatan <strong>vokasi</strong> boleh dikurangkan sampai <strong>200%</strong>, dan biaya <strong>penelitian & pengembangan (litbang)</strong> sampai <strong>300%</strong>. Insentif ini mendorong perusahaan melatih SDM dan berinovasi.",
      },
      { type: "widget", widget: "SimulatorInsentifPajak" },
      {
        type: "chart",
        variant: "bar",
        title: "Maksimal Pengurangan Biaya menurut Jenis Insentif Super Deduction",
        unit: "% dari biaya",
        source: "PP 45/2019",
        note: "Biaya litbang mendapat pengurangan paling besar (sampai 300%) untuk mendorong inovasi dalam negeri.",
        data: [
          { label: "Biaya normal (tanpa insentif)", value: 100, color: "#94a3b8" },
          { label: "Kegiatan vokasi", value: 200, color: "#60a5fa" },
          { label: "Litbang", value: 300, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Super Deduction Vokasi",
        html: "PT Terampil mengeluarkan biaya program <strong>vokasi Rp1 miliar</strong> (pelatihan dan magang siswa SMK). Dengan fasilitas super deduction <strong>200%</strong>, perusahaan boleh mengurangkan <strong>Rp2 miliar</strong> dari penghasilan bruto. Tambahan pengurangan Rp1 miliar di atas biaya riil menghemat PPh Badan sekitar 22% x Rp1 M = <strong>Rp220 juta</strong>.",
      },
      {
        type: "case",
        title: "Sejarah: Dari UU Penanaman Modal 2007 ke UU Cipta Kerja 2020",
        html: "Setelah era deregulasi, Indonesia menerbitkan <strong>UU Nomor 25 Tahun 2007</strong> tentang Penanaman Modal yang menegaskan fasilitas bagi investor. Dorongan menarik investasi langsung berlanjut lewat <strong>UU Cipta Kerja 2020</strong> dan turunannya, yang memperluas serta menyederhanakan insentif seperti tax holiday, tax allowance, dan super deduction agar Indonesia lebih bersaing menarik penanaman modal.",
      },
      {
        type: "calcExercise",
        prompt: "Biaya litbang Rp500 juta dengan super deduction maksimal 300%. Berapa total (dalam juta) yang boleh dikurangkan dari penghasilan bruto?",
        answer: 1500,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "300% x Rp500 juta = <strong>Rp1.500 juta</strong> (Rp1,5 miliar) boleh dikurangkan.",
        hint: "Kalikan biaya dengan 300%.",
      },
      {
        type: "calcExercise",
        prompt: "Nilai penanaman modal Rp10 miliar mendapat tax allowance 30%. Berapa pengurangan penghasilan neto (dalam juta) yang dibebankan PER TAHUN selama 6 tahun?",
        answer: 500,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "30% x Rp10 M = Rp3 M dibebankan 5% per tahun dari Rp10 M = Rp500 juta per tahun selama 6 tahun (total Rp3 M).",
        hint: "5% per tahun dari nilai penanaman modal.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan insentif dengan ciri utamanya.",
        pairs: [
          { left: "Tax holiday", right: "Pembebasan PPh Badan untuk industri pionir" },
          { left: "Tax allowance", right: "Pengurangan penghasilan neto 30% dari investasi" },
          { left: "Super deduction vokasi", right: "Biaya pelatihan dikurangkan sampai 200%" },
          { left: "Super deduction litbang", right: "Biaya penelitian dikurangkan sampai 300%" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Tax holiday membebaskan/mengurangi PPh Badan untuk industri pionir, 5 sampai 20 tahun.",
          "Tax allowance memberi pengurangan penghasilan neto 30% (5% per tahun, 6 tahun) plus penyusutan dipercepat.",
          "Super deduction: biaya vokasi sampai 200%, biaya litbang sampai 300%.",
          "Setiap insentif punya syarat sektor, nilai investasi, dan komitmen tersendiri.",
          "Memilih insentif yang tepat adalah inti tax planning bagi investor besar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tax holiday ditujukan terutama untuk?",
            options: ["UMKM", "Industri pionir", "Karyawan", "Importir kecil"],
            answer: 1,
            explain: "Tax holiday memberi pembebasan/pengurangan PPh Badan untuk industri pionir.",
          },
          {
            q: "Tax allowance memberi pengurangan penghasilan neto sebesar?",
            options: ["10% dari investasi", "30% dari nilai penanaman modal", "50% dari laba", "100% dari biaya"],
            answer: 1,
            explain: "PP 78/2019: pengurangan penghasilan neto 30% dari nilai penanaman modal, dibebankan 5% per tahun selama 6 tahun.",
          },
          {
            q: "Pengurangan maksimal biaya litbang lewat super deduction adalah?",
            options: ["100%", "150%", "200%", "300%"],
            answer: 3,
            explain: "PP 45/2019: biaya litbang dapat dikurangkan sampai 300%.",
          },
          {
            q: "Biaya vokasi Rp1 M dengan super deduction 200% boleh dikurangkan sebesar?",
            options: ["Rp1 M", "Rp2 M", "Rp3 M", "Rp500 juta"],
            answer: 1,
            explain: "200% x Rp1 M = Rp2 M boleh dikurangkan dari penghasilan bruto.",
          },
          {
            q: "Jangka waktu tax holiday umumnya berkisar?",
            options: ["1 sampai 2 tahun", "5 sampai 20 tahun", "30 tahun tetap", "Selamanya"],
            answer: 1,
            explain: "Tax holiday berlaku 5 sampai 20 tahun tergantung nilai investasi.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pph21-gross-nett-grossup",
    levelId: "strategi",
    order: 4,
    title: "Strategi PPh 21 Karyawan: Gross, Nett & Gross-up",
    summary: "Tiga cara menanggung PPh 21 karyawan dan mengapa metode gross-up bisa menghemat PPh Badan.",
    durationMin: 14,
    tags: ["PPh 21", "gross-up", "tunjangan pajak", "deductible", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "Saat memberi gaji, perusahaan harus memutuskan siapa yang menanggung <strong>PPh Pasal 21</strong>. Ada tiga metode populer: <strong>gross</strong>, <strong>nett</strong>, dan <strong>gross-up</strong>. Pilihan ini memengaruhi take-home pay karyawan sekaligus beban pajak perusahaan.",
      },
      {
        type: "video",
        comp: "WithholdingTaxVideo",
        title: "Video: Pemotongan PPh 21 & Pilihan Metode",
        caption: "Bagaimana satu rupiah pajak karyawan bisa berbeda dampaknya bagi perusahaan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Metode Gross",
        html: "Karyawan <strong>menanggung sendiri</strong> PPh 21-nya. Pajak dipotong dari gaji, sehingga <strong>take-home pay berkurang</strong>. Bagi perusahaan, gaji bruto adalah biaya yang deductible seperti biasa.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Metode Nett",
        html: "Perusahaan <strong>menanggung pajak</strong> karyawan agar take-home pay utuh. Masalahnya, penanggungan pajak ini dianggap <strong>bukan biaya</strong> dan <strong>tidak boleh dikurangkan</strong> (non-deductible) dari penghasilan bruto badan, jadi kurang efisien secara pajak.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Metode Gross-up",
        html: "Perusahaan memberi <strong>tunjangan pajak</strong> yang dihitung dengan rumus <strong>tunjangan = pajak / (1 - tarif)</strong> agar take-home pay tetap utuh. Karena berbentuk tunjangan, ini <strong>boleh dikurangkan (deductible)</strong>, sehingga menghemat PPh Badan sebesar 22% dari nilai tunjangan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Masukkan pajak terutang dan tarif efektif untuk melihat besar tunjangan gross-up dan penghematan PPh Badan.",
      },
      { type: "widget", widget: "SimulatorGrossUpPPh21" },
      {
        type: "chart",
        variant: "bar",
        title: "Dampak Metode pada Take-home & Deductibility (pajak Rp10 jt, tarif 15%)",
        unit: "Rp juta",
        source: "ilustrasi perhitungan PPh 21",
        note: "Gross-up menjaga take-home utuh dan tunjangannya deductible, beda dengan nett yang non-deductible.",
        data: [
          { label: "Tunjangan gross-up", value: 11.76, color: "#34d399" },
          { label: "Pajak nett (non-deductible)", value: 10, color: "#fb7185" },
          { label: "Hemat PPh Badan (gross-up)", value: 2.59, color: "#60a5fa" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Gross-up Menghemat PPh Badan",
        html: "PPh 21 seorang karyawan terutang <strong>Rp10 juta</strong> dengan tarif efektif <strong>15%</strong>. Dengan gross-up, tunjangan pajak = 10 / (1 - 0,15) = <strong>Rp11,76 juta</strong>. Tunjangan ini deductible, sehingga menghemat PPh Badan = 22% x Rp11,76 juta = sekitar <strong>Rp2,59 juta</strong>. Dibanding metode nett (pajak Rp10 juta non-deductible), gross-up lebih efisien meski nominal tunjangannya sedikit lebih besar.",
      },
      {
        type: "case",
        title: "Sejarah: Populernya Gross-up & Paket Take-home Pasti",
        html: "Seiring tumbuhnya kelas pekerja formal di Indonesia, perusahaan, terutama <strong>multinasional</strong>, makin sering menawarkan paket <strong>take-home pay yang pasti</strong> kepada karyawan. Konsep <strong>gross-up</strong> jadi populer karena memberi kepastian gaji bersih bagi karyawan sekaligus menjaga tunjangan pajak tetap deductible bagi perusahaan, sebuah solusi yang menguntungkan kedua pihak.",
      },
      {
        type: "calcExercise",
        prompt: "PPh 21 terutang Rp17 juta dengan tarif efektif 15%. Berapa tunjangan gross-up (dalam juta, bulatkan 2 desimal)?",
        answer: 20,
        tolerance: 0.1,
        prefix: "Rp",
        suffix: "juta",
        solution: "Tunjangan = pajak / (1 - tarif) = 17 / (1 - 0,15) = 17 / 0,85 = <strong>Rp20 juta</strong>.",
        hint: "Bagi pajak dengan (1 - tarif).",
      },
      {
        type: "calcExercise",
        prompt: "Tunjangan gross-up Rp20 juta bersifat deductible. Berapa penghematan PPh Badan (dalam juta) dengan tarif 22%?",
        answer: 4.4,
        tolerance: 0.05,
        prefix: "Rp",
        suffix: "juta",
        solution: "Hemat = 22% x Rp20 juta = <strong>Rp4,4 juta</strong>, karena tunjangan mengurangi penghasilan kena pajak badan.",
        hint: "Kalikan tunjangan dengan 22%.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan karakteristik berikut menurut metode PPh 21.",
        buckets: ["Nett", "Gross-up"],
        items: [
          { text: "Penanggungan pajak non-deductible", bucket: "Nett" },
          { text: "Perusahaan tanggung pajak tanpa tunjangan resmi", bucket: "Nett" },
          { text: "Tunjangan pajak deductible", bucket: "Gross-up" },
          { text: "Tunjangan = pajak / (1 - tarif)", bucket: "Gross-up" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Gross: karyawan menanggung pajak sendiri, take-home pay berkurang.",
          "Nett: perusahaan menanggung pajak, tetapi penanggungan itu non-deductible.",
          "Gross-up: tunjangan pajak = pajak / (1 - tarif), dan tunjangannya deductible.",
          "Gross-up menghemat PPh Badan sebesar 22% dari nilai tunjangan.",
          "Gross-up menjaga take-home utuh sekaligus efisien secara pajak bagi perusahaan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pada metode gross, siapa yang menanggung PPh 21?",
            options: ["Perusahaan penuh", "Karyawan (dipotong dari gaji)", "Pemerintah", "Pihak ketiga"],
            answer: 1,
            explain: "Metode gross berarti karyawan menanggung pajaknya sendiri sehingga take-home pay berkurang.",
          },
          {
            q: "Mengapa metode nett kurang efisien bagi perusahaan?",
            options: ["Tarifnya lebih tinggi", "Penanggungan pajak tidak boleh dikurangkan (non-deductible)", "Wajib lapor harian", "Kena PPN"],
            answer: 1,
            explain: "Pada metode nett, penanggungan pajak dianggap bukan biaya dan tidak boleh dikurangkan dari penghasilan bruto badan.",
          },
          {
            q: "Rumus tunjangan gross-up adalah?",
            options: ["pajak x tarif", "pajak / (1 - tarif)", "pajak + tarif", "pajak / tarif"],
            answer: 1,
            explain: "Tunjangan gross-up = pajak / (1 - tarif) agar take-home pay tetap utuh.",
          },
          {
            q: "Pajak Rp10 juta, tarif efektif 15%. Tunjangan gross-up-nya sekitar?",
            options: ["Rp8,5 juta", "Rp10 juta", "Rp11,76 juta", "Rp15 juta"],
            answer: 2,
            explain: "10 / (1 - 0,15) = 10 / 0,85 = sekitar Rp11,76 juta.",
          },
          {
            q: "Keunggulan utama gross-up dibanding nett adalah?",
            options: ["Take-home lebih kecil", "Tunjangannya deductible sehingga hemat PPh Badan", "Tanpa lapor pajak", "Bebas dari PPh 21"],
            answer: 1,
            explain: "Tunjangan gross-up bersifat deductible sehingga menghemat PPh Badan 22% dari nilai tunjangan.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "pemilihan-bentuk-usaha",
    levelId: "strategi",
    order: 5,
    title: "Memilih Bentuk Usaha: PT, CV, atau Orang Pribadi",
    summary: "Bentuk usaha menentukan jumlah lapisan pajak. PT bisa kena pajak dua lapis, CV hanya satu, orang pribadi punya jalurnya sendiri.",
    durationMin: 15,
    tags: ["bentuk usaha", "PT", "CV", "dividen", "strategi"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebelum bicara tarif dan fasilitas, ada keputusan yang lebih mendasar: <strong>bentuk usaha</strong> apa yang dipakai. Pilihan antara <strong>Perseroan Terbatas (PT)</strong>, <strong>CV/firma</strong>, atau <strong>orang pribadi</strong> menentukan berapa lapis pajak yang harus dilewati laba sebelum sampai ke kantong pemilik.",
      },
      {
        type: "paragraph",
        html: "Keputusan ini tidak murni soal pajak. Tanggung jawab hukum, akses modal, kredibilitas, dan kemudahan administrasi sama pentingnya. Tetapi memahami sisi pajaknya membuat keputusan jauh lebih sadar.",
      },
      {
        type: "video",
        comp: "BentukUsahaVideo",
        title: "Video: PT vs CV vs Orang Pribadi",
        caption: "Menelusuri perjalanan satu rupiah laba sampai ke kantong pemilik di tiap bentuk usaha.",
      },
      {
        type: "callout",
        tone: "key",
        title: "PT: dua lapis, tetapi tanggung jawab terbatas",
        html: "Laba PT kena <strong>PPh Badan 22%</strong>. Saat dibagikan sebagai <strong>dividen</strong> ke pemegang saham orang pribadi dalam negeri, kena <strong>PPh final 10%</strong>. Pengecualian penting: bila dividen <strong>diinvestasikan kembali di Indonesia</strong> memenuhi syarat UU HPP, lapisan kedua ini dikecualikan. Keunggulan PT: tanggung jawab terbatas dan akses modal lebih luas.",
      },
      {
        type: "callout",
        tone: "info",
        title: "CV/Firma: hanya satu lapis pajak",
        html: "Laba CV/firma juga kena <strong>PPh Badan 22%</strong>, tetapi bagian laba yang dibagikan ke sekutu <strong>BUKAN objek pajak</strong>. Tidak ada lapisan kedua, sehingga total pajak bisa lebih ringan dibanding PT yang membagi dividen.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Orang pribadi/UMKM: tarif progresif atau final",
        html: "Usaha atas nama orang pribadi memakai <strong>PPh orang pribadi progresif 5% sampai 35%</strong>, atau skema <strong>PPh final 0,5% dari omzet</strong> (PP 55/2022) bila omzet sampai Rp4,8 miliar. Cocok untuk usaha kecil yang belum butuh badan hukum.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Atur laba dan kebijakan pembagian untuk membandingkan total pajak PT, CV, dan orang pribadi.",
      },
      { type: "widget", widget: "SimulatorBentukUsaha" },
      {
        type: "chart",
        variant: "bar",
        title: "Total Pajak atas Laba Rp2 M, Seluruhnya Dibagikan ke Pemilik (OP)",
        unit: "Rp juta",
        source: "ilustrasi berdasarkan UU PPh & UU HPP (tarif Badan 22%, dividen final 10%)",
        note: "PT membayar dua lapis bila dividen tidak diinvestasikan kembali, sementara CV hanya satu lapis.",
        data: [
          { label: "CV (Badan 22% saja)", value: 440, color: "#34d399" },
          { label: "PT (Badan 22% + dividen 10%)", value: 596, color: "#fb7185" },
        ],
      },
      {
        type: "table",
        headers: ["Aspek", "PT", "CV/Firma", "Orang Pribadi"],
        rows: [
          ["Tarif atas laba", "PPh Badan 22%", "PPh Badan 22%", "Progresif 5-35% atau final 0,5%"],
          ["Pajak saat bagi hasil", "Dividen final 10% (OP DN)", "Bukan objek pajak", "Tidak ada (laba = milik pribadi)"],
          ["Tanggung jawab", "Terbatas pada modal", "Sekutu aktif tidak terbatas", "Tidak terbatas"],
          ["Akses modal", "Luas (saham, investor)", "Terbatas", "Sangat terbatas"],
        ],
        caption: "Perbandingan ringkas tiga bentuk usaha dari sisi pajak dan non-pajak.",
      },
      {
        type: "case",
        title: "Studi Kasus: Laba Rp2 M, PT vs CV",
        html: "Sebuah usaha membukukan laba <strong>Rp2 miliar</strong> dan seluruh laba dibagikan ke pemilik orang pribadi. <strong>CV</strong>: PPh Badan 22% x 2.000 = <strong>Rp440 juta</strong>, bagian laba ke sekutu bukan objek pajak, jadi total tetap Rp440 juta. <strong>PT</strong>: PPh Badan 22% x 2.000 = Rp440 juta, sisa laba Rp1.560 juta dibagikan sebagai dividen kena 10% = Rp156 juta, total <strong>Rp596 juta</strong>. Selisihnya Rp156 juta. Namun bila dividen PT diinvestasikan kembali di Indonesia sesuai syarat HPP, lapisan Rp156 juta itu bisa dikecualikan.",
      },
      {
        type: "case",
        title: "Sejarah: Dari CV Keluarga ke PT saat Butuh Modal",
        html: "Selama bertahun-tahun banyak <strong>usaha keluarga</strong> di Indonesia sengaja memilih bentuk <strong>CV</strong> untuk menghindari pajak berganda atas dividen, karena bagian laba ke sekutu bukan objek pajak. Saat usaha membesar dan butuh <strong>modal besar</strong> atau investor, mereka beralih ke <strong>PT</strong>. Lewat <strong>UU HPP 2021</strong>, aturan dividen diperbarui: dividen ke orang pribadi dapat dikecualikan dari pajak bila diinvestasikan kembali di Indonesia, sehingga jarak keunggulan CV dan PT menyempit.",
      },
      {
        type: "calcExercise",
        prompt: "PT membukukan laba Rp1 miliar dan membagikan seluruh sisa laba sebagai dividen ke pemilik orang pribadi (tidak diinvestasikan kembali). Berapa TOTAL pajak (PPh Badan + dividen) dalam juta?",
        answer: 298,
        tolerance: 1,
        prefix: "Rp",
        suffix: "juta",
        solution: "PPh Badan 22% x 1.000 = Rp220 juta. Sisa laba 1.000 - 220 = Rp780 juta dibagikan sebagai dividen kena 10% = Rp78 juta. Total = 220 + 78 = <strong>Rp298 juta</strong>.",
        hint: "Hitung PPh Badan dulu, lalu dividen 10% atas sisa laba.",
      },
      {
        type: "calcExercise",
        prompt: "CV membukukan laba Rp1 miliar dan membagikan seluruhnya ke sekutu. Berapa total pajak (dalam juta)?",
        answer: 220,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "PPh Badan 22% x 1.000 = Rp220 juta. Bagian laba ke sekutu bukan objek pajak, jadi total tetap <strong>Rp220 juta</strong>.",
        hint: "CV hanya satu lapis: PPh Badan saja.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan ciri berikut menurut bentuk usaha yang paling tepat.",
        buckets: ["PT", "CV/Firma", "Orang Pribadi"],
        items: [
          { text: "Dividen ke OP dalam negeri kena final 10%", bucket: "PT" },
          { text: "Tanggung jawab pemilik terbatas pada modal", bucket: "PT" },
          { text: "Bagian laba ke sekutu bukan objek pajak", bucket: "CV/Firma" },
          { text: "Bisa pakai PPh final 0,5% dari omzet", bucket: "Orang Pribadi" },
          { text: "Tarif progresif 5% sampai 35%", bucket: "Orang Pribadi" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Bentuk usaha menentukan jumlah lapisan pajak atas laba.",
          "PT: PPh Badan 22% lalu dividen final 10%, kecuali diinvestasikan kembali (UU HPP).",
          "CV/firma: hanya PPh Badan 22%; bagian laba ke sekutu bukan objek pajak.",
          "Orang pribadi: progresif 5-35% atau final 0,5% dari omzet (PP 55/2022).",
          "Keputusan menimbang pajak DAN non-pajak: tanggung jawab dan akses modal.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dividen dari PT ke pemegang saham orang pribadi dalam negeri umumnya kena?",
            options: ["PPh final 10%", "PPh 25%", "PPN 11%", "Bebas selamanya"],
            answer: 0,
            explain: "Dividen ke orang pribadi dalam negeri kena PPh final 10%, kecuali diinvestasikan kembali di Indonesia sesuai syarat UU HPP.",
          },
          {
            q: "Bagian laba CV/firma yang dibagikan ke sekutu bersifat?",
            options: ["Objek pajak 15%", "Bukan objek pajak", "Kena PPN", "Kena final 10%"],
            answer: 1,
            explain: "Bagian laba yang dibagikan ke sekutu CV/firma bukan objek pajak, sehingga tidak ada lapisan kedua.",
          },
          {
            q: "Skema PPh final untuk usaha orang pribadi dengan omzet sampai Rp4,8 M adalah?",
            options: ["0,5% dari omzet", "22% dari laba", "10% dari laba", "35% dari omzet"],
            answer: 0,
            explain: "PP 55/2022 menyediakan PPh final 0,5% dari omzet bagi usaha kecil.",
          },
          {
            q: "Laba Rp2 M dibagikan penuh: total pajak PT (Badan + dividen, tanpa reinvestasi) sekitar?",
            options: ["Rp440 juta", "Rp596 juta", "Rp200 juta", "Rp880 juta"],
            answer: 1,
            explain: "Badan 22% x 2.000 = Rp440 juta, dividen 10% x 1.560 = Rp156 juta, total Rp596 juta.",
          },
          {
            q: "Keunggulan utama PT dibanding CV dari sisi non-pajak adalah?",
            options: ["Bebas pajak", "Tanggung jawab terbatas dan akses modal luas", "Tanpa pembukuan", "Tarif lebih rendah"],
            answer: 1,
            explain: "PT menawarkan tanggung jawab terbatas pada modal dan akses modal yang lebih luas lewat saham.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "holding-dividen-antarperusahaan",
    levelId: "strategi",
    order: 6,
    title: "Struktur Holding & Dividen Antarperusahaan",
    summary: "Memanfaatkan pengecualian dividen dalam negeri menurut UU HPP agar laba mengalir antarperusahaan satu grup tanpa lapisan pajak baru.",
    durationMin: 14,
    tags: ["holding", "dividen", "UU HPP", "struktur grup"],
    blocks: [
      {
        type: "paragraph",
        html: "Saat sebuah grup terdiri dari banyak perusahaan, laba sering perlu dipindahkan dari anak usaha ke induk. Tanpa aturan yang tepat, satu rupiah laba bisa dipajaki berlapis setiap kali berpindah. <strong>UU HPP</strong> menutup masalah ini dengan mengecualikan dividen dalam negeri dari objek pajak.",
      },
      {
        type: "video",
        comp: "HoldingDividenVideo",
        title: "Video: Holding & Dividen Antarperusahaan",
        caption: "Dividen dari anak usaha dalam negeri naik ke induk tanpa lapisan PPh tambahan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dividen dalam negeri dikecualikan",
        html: "Sejak UU HPP, dividen yang berasal dari dalam negeri dan diterima <strong>Wajib Pajak badan dalam negeri</strong> dikecualikan dari objek pajak. Sebelumnya, dividen bisa dipotong PPh 23 sebesar 15% bila kepemilikan di bawah 25%.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Untuk orang pribadi: syarat investasi",
        html: "Dividen dalam negeri yang diterima <strong>orang pribadi</strong> dikecualikan dari pajak bila <strong>diinvestasikan kembali di Indonesia</strong> dalam jangka waktu tertentu (minimal 3 tahun). Bila tidak, dikenai PPh final 10%.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Substansi tetap diuji",
        html: "Struktur holding harus punya tujuan bisnis nyata (pengelolaan grup, sentralisasi kas), bukan semata memindahkan laba untuk menghindari pajak. Ketentuan anti-penghindaran tetap berlaku.",
      },
      {
        type: "widget",
        widget: "KalkulatorDividenHolding",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Dividen Rp2 Miliar ke Induk: Aturan Lama vs UU HPP",
        unit: "Rp juta",
        source: "ilustrasi penerapan UU HPP",
        note: "Pengecualian dividen menghemat Rp300 juta pajak yang dulu dipotong, sehingga laba utuh sampai ke induk.",
        data: [
          { label: "Potongan 15% (aturan lama)", value: 300, color: "#fb7185" },
          { label: "Potongan UU HPP", value: 0, color: "#34d399" },
          { label: "Hemat pajak", value: 300, color: "#60a5fa" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Aliran Dividen dalam Struktur Holding (ilustrasi)",
        unit: "Rp juta dividen",
        source: "ilustrasi struktur grup",
        note: "Tiga anak usaha menyalurkan dividen ke induk; seluruhnya dikecualikan dari objek pajak.",
        data: [
          { label: "Dari Anak A", value: 900, color: "#60a5fa" },
          { label: "Dari Anak B", value: 700, color: "#34d399" },
          { label: "Dari Anak C", value: 400, color: "#fbbf24" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dividen naik tanpa terpotong",
        html: "PT Induk memiliki tiga anak usaha. Anak A membagikan dividen <strong>Rp2 miliar</strong> ke induk. Dengan aturan lama (kepemilikan di bawah 25%), dividen ini dipotong PPh 23 15% = Rp300 juta, sehingga induk hanya menerima Rp1,7 miliar. Dengan <strong>UU HPP</strong>, dividen dalam negeri ke badan dikecualikan, sehingga <strong>seluruh Rp2 miliar</strong> diterima utuh. Penghematan Rp300 juta ini membuat struktur holding jauh lebih efisien.",
      },
      {
        type: "calcExercise",
        prompt: "Dividen Rp2.000 juta dari anak ke induk. Dengan aturan lama dipotong PPh 23 15%. Berapa potongan pajaknya (dalam juta)?",
        answer: 300,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Potongan = 15% x 2.000 = <strong>Rp300 juta</strong>. Dengan UU HPP, potongan ini menjadi nol.",
        hint: "Kalikan dividen dengan 15%.",
      },
      {
        type: "calcExercise",
        prompt: "Total dividen yang naik ke induk Rp2.000 juta dan seluruhnya dikecualikan UU HPP. Berapa pajak yang dipotong (dalam juta)?",
        answer: 0,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Dividen dalam negeri ke WP badan dikecualikan dari objek pajak, sehingga potongan = <strong>Rp0</strong>.",
        hint: "Dividen dalam negeri ke badan bukan objek pajak.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan kondisi penerima dividen dengan perlakuan pajaknya menurut UU HPP.",
        pairs: [
          { left: "WP badan dalam negeri", right: "Dikecualikan dari objek pajak" },
          { left: "Orang pribadi, diinvestasikan kembali", right: "Dikecualikan bila memenuhi syarat" },
          { left: "Orang pribadi, tidak diinvestasikan", right: "PPh final 10%" },
          { left: "Dividen dari luar negeri", right: "Diatur tersendiri dengan syarat investasi" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Pembentukan Holding BUMN MIND ID 2017",
        html: "Pada <strong>2017</strong>, pemerintah membentuk <strong>holding industri pertambangan</strong> yang kemudian dikenal sebagai <strong>MIND ID</strong>, menyatukan beberapa BUMN tambang di bawah satu induk. Struktur holding seperti ini memudahkan sinergi, sentralisasi pendanaan, dan pengelolaan dividen antaranggota grup. Contoh ini menunjukkan bahwa struktur grup bukan sekadar soal pajak, melainkan strategi korporasi yang didukung perlakuan dividen yang efisien.",
      },
      {
        type: "takeaways",
        items: [
          "UU HPP mengecualikan dividen dalam negeri yang diterima WP badan dari objek pajak.",
          "Orang pribadi bebas pajak dividen bila diinvestasikan kembali, jika tidak kena 10% final.",
          "Struktur holding membuat laba mengalir ke induk tanpa lapisan pajak baru.",
          "Holding harus punya tujuan bisnis nyata; anti-penghindaran tetap berlaku.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dividen dalam negeri yang diterima WP badan menurut UU HPP?",
            options: ["Dipotong 15%", "Dikecualikan dari objek pajak", "Kena 22%", "Kena 10% final"],
            answer: 1,
            explain: "Dividen dalam negeri ke WP badan dalam negeri dikecualikan dari objek pajak.",
          },
          {
            q: "Dividen ke orang pribadi bisa bebas pajak bila?",
            options: ["Selalu bebas", "Diinvestasikan kembali di Indonesia sesuai syarat", "Dibagikan tunai", "Disimpan di luar negeri"],
            answer: 1,
            explain: "Syaratnya diinvestasikan kembali di Indonesia dalam jangka waktu tertentu.",
          },
          {
            q: "Sebelum UU HPP, dividen dengan kepemilikan di bawah 25% bisa dipotong?",
            options: ["PPh 23 15%", "PPh 21 5%", "PPN 11%", "Bea meterai"],
            answer: 0,
            explain: "Dahulu dividen tertentu dipotong PPh 23 sebesar 15%.",
          },
          {
            q: "Dividen Rp1 miliar ke induk (WP badan), berapa pajak menurut UU HPP?",
            options: ["Rp150 juta", "Rp0", "Rp220 juta", "Rp100 juta"],
            answer: 1,
            explain: "Dikecualikan dari objek pajak, sehingga potongannya nol.",
          },
          {
            q: "Syarat agar struktur holding aman dari koreksi adalah?",
            options: ["Tanpa dokumentasi", "Punya tujuan bisnis nyata", "Berada di luar negeri", "Tanpa laporan"],
            answer: 1,
            explain: "Struktur harus memiliki substansi dan tujuan bisnis nyata, bukan semata menghindari pajak.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kek-fasilitas-kawasan",
    levelId: "strategi",
    order: 7,
    title: "Fasilitas Kawasan: KEK, Kawasan Berikat & KITE",
    summary: "Memanfaatkan fasilitas pajak dan kepabeanan di kawasan khusus untuk mendorong ekspor dan menekan biaya investasi.",
    durationMin: 14,
    tags: ["KEK", "kawasan berikat", "KITE", "fasilitas", "ekspor"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain fasilitas yang melekat pada PPh, pemerintah menyiapkan <strong>fasilitas berbasis kawasan</strong>. Perusahaan yang beroperasi di kawasan tertentu bisa menikmati pembebasan pajak dan bea, terutama bila berorientasi ekspor atau investasi besar.",
      },
      {
        type: "video",
        comp: "Fasilitas31EVideo",
        title: "Video: Fasilitas Berbasis Kawasan",
        caption: "Kawasan khusus menawarkan pembebasan pajak dan bea untuk menarik investasi dan mendorong ekspor.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga fasilitas kawasan utama",
        html: "<strong>KEK (Kawasan Ekonomi Khusus):</strong> tax holiday atau tax allowance, pembebasan bea masuk, PPN dan PPnBM tidak dipungut atas penyerahan tertentu. <strong>Kawasan Berikat:</strong> penangguhan bea masuk dan pajak dalam rangka impor untuk bahan baku yang diolah lalu diekspor. <strong>KITE:</strong> pembebasan atau pengembalian bea masuk atas bahan baku yang diekspor kembali.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tujuan: ekspor & investasi",
        html: "Fasilitas kawasan dirancang agar Indonesia menarik bagi pabrik berorientasi ekspor. Dengan menekan bea dan pajak atas bahan baku impor, biaya produksi turun dan produk lebih bersaing di pasar global.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Ibn_Khaldoun-Kassus.jpg?width=400",
        alt: "Patung Ibn Khaldun",
        caption: "Ibn Khaldun (1332-1406), dalam Muqaddimah menjelaskan bahwa tarif pajak yang terlalu tinggi justru menurunkan penerimaan negara.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "widget",
        widget: "SimulatorInsentifPajak",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komponen Biaya Impor Bahan Baku: Tanpa vs Dengan Fasilitas Kawasan (ilustrasi)",
        unit: "Rp juta per kontainer",
        source: "ilustrasi konsep Kawasan Berikat/KITE",
        note: "Penangguhan bea masuk dan PDRI atas bahan baku ekspor memangkas biaya di muka secara signifikan.",
        data: [
          { label: "Nilai bahan baku", value: 500, color: "#60a5fa" },
          { label: "Bea masuk (tanpa fasilitas)", value: 50, color: "#fb7185" },
          { label: "PDRI (tanpa fasilitas)", value: 60, color: "#f59e0b" },
          { label: "Beban dengan fasilitas", value: 0, color: "#34d399" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pabrik ekspor di Kawasan Berikat",
        html: "Sebuah pabrik garmen mengimpor kain senilai <strong>Rp500 juta</strong> per kontainer untuk dijahit lalu diekspor. Di luar kawasan, ia harus membayar bea masuk sekitar Rp50 juta dan pajak dalam rangka impor (PDRI) sekitar Rp60 juta di muka. Di <strong>Kawasan Berikat</strong>, kedua pungutan itu <strong>ditangguhkan</strong> karena barang akan diekspor kembali. Pabrik menghemat <strong>Rp110 juta arus kas</strong> per kontainer, modal yang bisa diputar untuk produksi.",
      },
      {
        type: "calcExercise",
        prompt: "Bahan baku impor Rp500 juta. Tanpa fasilitas: bea masuk Rp50 juta dan PDRI Rp60 juta. Berapa total pungutan di muka yang dihemat di Kawasan Berikat (dalam juta)?",
        answer: 110,
        tolerance: 0,
        prefix: "Rp",
        suffix: "juta",
        solution: "Penghematan arus kas = bea masuk + PDRI = 50 + 60 = <strong>Rp110 juta</strong> yang ditangguhkan.",
        hint: "Jumlahkan bea masuk dan PDRI yang ditangguhkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Fasilitas ini melekat pada skema yang mana?",
        buckets: ["KEK", "Kawasan Berikat / KITE"],
        items: [
          { text: "Tax holiday PPh Badan untuk investasi besar", bucket: "KEK" },
          { text: "Penangguhan bea masuk bahan baku untuk diekspor", bucket: "Kawasan Berikat / KITE" },
          { text: "PPN dan PPnBM tidak dipungut atas penyerahan tertentu", bucket: "KEK" },
          { text: "Pengembalian bea masuk atas bahan yang diekspor kembali", bucket: "Kawasan Berikat / KITE" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Ibn Khaldun & Cikal Bakal Kurva Laffer",
        html: "Gagasan bahwa tarif pajak yang terlalu tinggi justru menurunkan penerimaan sudah ditulis <strong>Ibn Khaldun</strong> dalam <strong>Muqaddimah</strong> sekitar <strong>1377</strong>. Ia mengamati bahwa di awal sebuah dinasti, tarif rendah mendorong usaha dan penerimaan besar; ketika tarif dinaikkan berlebihan, kegiatan ekonomi melambat dan penerimaan malah turun. Hampir enam abad kemudian, ide ini dikenal sebagai <strong>kurva Laffer</strong> (1974). Logika inilah yang mendasari pemberian insentif dan fasilitas kawasan: tarif yang lebih ringan dapat menumbuhkan investasi sehingga penerimaan jangka panjang justru naik.",
      },
      {
        type: "takeaways",
        items: [
          "KEK menggabungkan fasilitas PPh, bea masuk, serta PPN/PPnBM tidak dipungut.",
          "Kawasan Berikat menangguhkan bea masuk dan PDRI atas bahan baku yang diekspor.",
          "KITE membebaskan atau mengembalikan bea masuk bahan baku yang diekspor kembali.",
          "Fasilitas kawasan menekan biaya dan mendorong ekspor serta investasi.",
          "Logika Ibn Khaldun/Laffer: tarif moderat bisa menumbuhkan penerimaan jangka panjang.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kawasan Berikat memberi fasilitas berupa?",
            options: [
              "Penangguhan bea masuk & pajak impor bahan baku untuk diekspor",
              "Pembebasan PPh karyawan",
              "Dividen bebas pajak",
              "Tarif PPN naik",
            ],
            answer: 0,
            explain: "Kawasan Berikat menangguhkan bea masuk dan PDRI atas bahan baku yang akan diekspor.",
          },
          {
            q: "KEK umumnya menawarkan, kecuali?",
            options: ["Tax holiday/allowance", "Pembebasan bea masuk", "PPN tidak dipungut tertentu", "Pembebasan iuran BPJS"],
            answer: 3,
            explain: "Fasilitas KEK berkisar pada pajak dan kepabeanan, bukan iuran jaminan sosial.",
          },
          {
            q: "KITE adalah kepanjangan dari?",
            options: ["Kemudahan Impor Tujuan Ekspor", "Kawasan Industri Terpadu Ekonomi", "Kredit Investasi Tarif Ekspor", "Kantor Imigrasi Tenaga Ekspor"],
            answer: 0,
            explain: "KITE adalah Kemudahan Impor Tujuan Ekspor.",
          },
          {
            q: "Bahan baku Rp500 juta, bea masuk Rp50 juta, PDRI Rp60 juta. Penghematan di Kawasan Berikat?",
            options: ["Rp50 juta", "Rp60 juta", "Rp110 juta", "Rp500 juta"],
            answer: 2,
            explain: "Bea masuk + PDRI = 50 + 60 = Rp110 juta yang ditangguhkan.",
          },
          {
            q: "Siapa yang menulis cikal bakal kurva Laffer sekitar 1377?",
            options: ["Adam Smith", "Ibn Khaldun", "David Ricardo", "Arthur Laffer"],
            answer: 1,
            explain: "Ibn Khaldun menulis gagasan itu dalam Muqaddimah sekitar 1377.",
          },
        ],
      },
    ],
  },
];
