import type { Lesson } from "../../../types";

export const level2: Lesson[] = [
  // ============================================================
  {
    id: "mengenal-akad-syariah",
    levelId: "akad",
    order: 1,
    title: "Mengenal Akad & Jenis-jenisnya",
    summary: "Akad sebagai fondasi transaksi syariah, rukun dan syaratnya, serta pengelompokan akad jual beli, sewa, bagi hasil, dan jasa.",
    durationMin: 14,
    tags: ["akad", "murabahah", "ijarah", "mudharabah"],
    blocks: [
      {
        type: "paragraph",
        html: "Semua transaksi syariah bertumpu pada <strong>akad</strong>, yaitu kesepakatan yang mengikat dua pihak sesuai aturan syariah. Sah atau tidaknya suatu transaksi ditentukan oleh akadnya, bukan sekadar nama produknya.",
      },
      {
        type: "video",
        comp: "AkadJualBeliVideo",
        title: "Video: Akad Murabahah (Jual Beli)",
        caption: "Bank membeli barang lalu menjualnya dengan margin yang disepakati terbuka.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Rukun akad",
        html: "Sebuah akad membutuhkan: <strong>pihak</strong> yang berakad, <strong>objek</strong> yang jelas dan halal, serta <strong>ijab kabul</strong> (pernyataan serah terima). Objek harus ada, dimiliki, dan bisa diserahkan, agar terhindar dari gharar.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Empat kelompok akad",
        html: "<strong>Jual beli:</strong> murabahah, salam, istishna. <strong>Sewa:</strong> ijarah. <strong>Bagi hasil:</strong> mudharabah, musyarakah. <strong>Jasa & tolong-menolong:</strong> wakalah, kafalah, rahn (gadai), qard (pinjaman kebajikan).",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Hitung cicilan dan margin pada pembiayaan murabahah, salah satu akad jual beli yang paling umum di bank syariah.",
      },
      { type: "widget", widget: "KalkulatorMurabahah" },
      {
        type: "table",
        caption: "Ragam akad dan penggunaannya",
        headers: ["Akad", "Jenis", "Contoh penggunaan"],
        rows: [
          ["Murabahah", "Jual beli (cost plus)", "Pembiayaan mobil, rumah"],
          ["Salam", "Jual beli pesanan (bayar di muka)", "Produk pertanian"],
          ["Istishna", "Jual beli pesanan (barang dibuat)", "Konstruksi, manufaktur"],
          ["Ijarah", "Sewa manfaat", "Sewa aset, jasa"],
          ["Mudharabah", "Bagi hasil (modal vs kelola)", "Deposito, pembiayaan"],
          ["Musyarakah", "Bagi hasil (kongsi modal)", "Pembiayaan proyek bersama"],
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Contoh Komposisi Akad Pembiayaan Bank Syariah (ilustrasi)",
        unit: "% pembiayaan",
        source: "ilustrasi konsep, pola umum industri",
        note: "Murabahah kerap mendominasi karena sederhana; akad bagi hasil (musyarakah, mudharabah) terus didorong tumbuh.",
        data: [
          { label: "Murabahah", value: 45, color: "#34d399" },
          { label: "Musyarakah", value: 35, color: "#10b981" },
          { label: "Mudharabah", value: 10, color: "#0ea5e9" },
          { label: "Ijarah & lainnya", value: 10, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membeli mobil lewat murabahah",
        html: "Seorang nasabah ingin mobil seharga <strong>Rp200 juta</strong>. Bank membelinya dari dealer, lalu menjualnya kepada nasabah dengan margin disepakati <strong>15%</strong> = Rp30 juta, sehingga harga jual <strong>Rp230 juta</strong> yang dicicil, misalnya 36 bulan. Karena harga total dikunci di awal, cicilan tetap dan nasabah tahu persis kewajibannya. Margin ini adalah laba jual beli, bukan bunga berjalan.",
      },
      {
        type: "calcExercise",
        prompt: "Harga pokok mobil Rp200 juta, margin murabahah disepakati 15%. Berapa total harga jual bank ke nasabah (dalam juta)?",
        answer: 230,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Margin = 15% x 200 = Rp30 juta. Harga jual = 200 + 30 = <strong>Rp230 juta</strong>.",
        hint: "Tambahkan margin ke harga pokok.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan akad dengan jenisnya.",
        pairs: [
          { left: "Murabahah", right: "Jual beli dengan margin" },
          { left: "Ijarah", right: "Sewa manfaat" },
          { left: "Mudharabah", right: "Bagi hasil modal dan pengelola" },
          { left: "Rahn", right: "Gadai sebagai jaminan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Akad dalam Perdagangan Islam Klasik",
        html: "Akad seperti <strong>mudharabah</strong> dan <strong>musyarakah</strong> sudah dipraktikkan pedagang Muslim sejak masa awal Islam, termasuk dalam perdagangan lintas benua di sepanjang Jalur Sutra dan jalur laut. Modal pemodal dan keahlian pedagang digabung, laba dibagi sesuai kesepakatan. Model berbagi risiko ini turut menopang perdagangan dunia Islam selama berabad-abad.",
      },
      {
        type: "takeaways",
        items: [
          "Akad adalah fondasi sah-tidaknya transaksi syariah.",
          "Rukun akad: pihak, objek yang jelas dan halal, serta ijab kabul.",
          "Empat kelompok: jual beli, sewa, bagi hasil, dan jasa/tolong-menolong.",
          "Murabahah mengunci harga di awal; marginnya laba jual beli, bukan bunga.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Yang menentukan sah tidaknya transaksi syariah adalah?",
            options: ["Nama produk", "Akadnya", "Besar keuntungan", "Jenis bank"],
            answer: 1,
            explain: "Akad menentukan keabsahan transaksi, bukan sekadar nama produk.",
          },
          {
            q: "Murabahah termasuk akad?",
            options: ["Sewa", "Jual beli", "Bagi hasil", "Gadai"],
            answer: 1,
            explain: "Murabahah adalah akad jual beli dengan margin yang disepakati.",
          },
          {
            q: "Akad bagi hasil antara pemilik modal dan pengelola disebut?",
            options: ["Ijarah", "Mudharabah", "Rahn", "Salam"],
            answer: 1,
            explain: "Mudharabah adalah kerja sama modal (shahibul maal) dan pengelola (mudharib).",
          },
          {
            q: "Ijarah adalah akad?",
            options: ["Sewa manfaat", "Perjudian", "Pinjaman berbunga", "Hibah"],
            answer: 0,
            explain: "Ijarah adalah akad sewa atas manfaat suatu barang atau jasa.",
          },
          {
            q: "Pokok Rp100 juta, margin murabahah 10%. Harga jualnya?",
            options: ["Rp90 juta", "Rp110 juta", "Rp100 juta", "Rp10 juta"],
            answer: 1,
            explain: "100 + (10% x 100) = Rp110 juta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-jual-beli-detail",
    levelId: "akad",
    order: 2,
    title: "Akad Jual Beli: Murabahah, Salam, Istishna",
    summary: "Tiga akad jual beli dalam ekonomi syariah: murabahah (barang sudah ada), salam (bayar di muka untuk pertanian), dan istishna (pesan barang yang dibuat untuk konstruksi/manufaktur).",
    durationMin: 15,
    tags: ["murabahah", "salam", "istishna", "jual beli"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam syariah, <strong>jual beli (bai)</strong> adalah tukar-menukar barang atau jasa dengan harga yang jelas dan disepakati. Dari sinilah keuntungan yang halal muncul: dari selisih harga jual dan harga beli, bukan dari bunga atas uang.",
      },
      {
        type: "paragraph",
        html: "Ada tiga akad jual beli yang paling penting dan berbeda berdasarkan <strong>kapan barang ada</strong> dan <strong>kapan dibayar</strong>: murabahah, salam, dan istishna.",
      },
      {
        type: "video",
        comp: "AkadJualBeliVideo",
        title: "Video: Alur Akad Jual Beli",
        caption: "Penjual memiliki barang, mengungkap harga pokok, lalu menambah margin yang disepakati.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Beda tiga akad ini",
        html: "<strong>Murabahah:</strong> barang sudah ada, harga pokok + margin diungkap terbuka. <strong>Salam:</strong> dibayar penuh di muka, barang diserahkan kemudian (cocok untuk hasil pertanian). <strong>Istishna:</strong> memesan barang yang harus dibuat dulu, pembayaran bisa bertahap (cocok untuk konstruksi dan manufaktur).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dasar fatwa",
        html: "Murabahah diatur dalam Fatwa DSN-MUI No. 04/DSN-MUI/IV/2000, salam dalam No. 05/DSN-MUI/IV/2000, dan istishna dalam No. 06/DSN-MUI/IV/2000. Ketiganya menegaskan kejelasan barang, harga, dan waktu penyerahan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Ubah harga pokok, margin, dan tenor untuk melihat bagaimana cicilan murabahah terbentuk dan tetap sampai lunas.",
      },
      { type: "widget", widget: "KalkulatorMurabahah" },
      {
        type: "table",
        caption: "Perbandingan tiga akad jual beli",
        headers: ["Aspek", "Murabahah", "Salam", "Istishna"],
        rows: [
          ["Keberadaan barang", "Sudah ada", "Belum ada", "Belum ada, dibuat"],
          ["Pembayaran", "Tunai/cicil", "Penuh di muka", "Di muka/bertahap"],
          ["Penyerahan", "Segera", "Waktu tertentu", "Setelah selesai dibuat"],
          ["Contoh umum", "Mobil, rumah", "Gabah, beras", "Rumah, kapal, mesin"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Contoh Struktur Harga Murabahah Rp200 Juta (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Harga jual dikunci di awal: harga pokok ditambah margin yang disepakati terbuka, lalu tetap sampai lunas.",
        data: [
          { label: "Harga pokok", value: 200, color: "#34d399" },
          { label: "Margin 15%", value: 30, color: "#10b981" },
          { label: "Harga jual", value: 230, color: "#0ea5e9" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Petani memakai akad salam",
        html: "Seorang pembeli memesan <strong>10 ton gabah</strong> panen 4 bulan lagi dengan harga <strong>Rp5.000/kg</strong>, dibayar penuh di muka = <strong>Rp50 juta</strong>. Petani memakai uang itu untuk benih dan pupuk, lalu menyerahkan gabah saat panen. Ini akad salam: uang di muka, barang menyusul, dengan spesifikasi mutu dan waktu yang jelas agar tidak ada gharar.",
      },
      {
        type: "calcExercise",
        prompt: "Harga pokok laptop Rp12 juta, margin murabahah disepakati 20%. Berapa total harga jual (dalam juta)?",
        answer: 14.4,
        tolerance: 0.1,
        prefix: "Rp",
        suffix: " juta",
        solution: "Margin = 20% x 12 = Rp2,4 juta. Harga jual = 12 + 2,4 = <strong>Rp14,4 juta</strong>.",
        hint: "Margin = 20% dari harga pokok, lalu jumlahkan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap transaksi ke akad jual beli yang tepat.",
        buckets: ["Murabahah", "Salam", "Istishna"],
        items: [
          { text: "Beli mobil yang sudah ready di dealer, dicicil", bucket: "Murabahah" },
          { text: "Bayar penuh di muka untuk 5 ton beras panen depan", bucket: "Salam" },
          { text: "Pesan rumah yang dibangun sesuai spesifikasi", bucket: "Istishna" },
          { text: "Pembiayaan HP yang stoknya tersedia", bucket: "Murabahah" },
          { text: "Pesan kapal yang harus diproduksi galangan", bucket: "Istishna" },
          { text: "Uang muka penuh untuk hasil cabai musim tanam", bucket: "Salam" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Salam sebagai solusi pembiayaan petani",
        html: "Akad <strong>salam</strong> sudah dikenal sejak masa Nabi Muhammad sekitar abad ke-7 M. Saat hijrah ke Madinah, penduduk terbiasa membayar di muka untuk kurma yang diserahkan setahun atau dua tahun kemudian. Nabi menetapkan syaratnya: takaran, timbangan, dan tempo yang jelas. Skema ini menolong petani memperoleh modal tanam lebih awal, sebuah pembiayaan pertanian yang adil tanpa riba.",
      },
      {
        type: "takeaways",
        items: [
          "Jual beli syariah menghasilkan laba dari selisih harga, bukan bunga uang.",
          "Murabahah: barang ada, harga pokok + margin diungkap terbuka.",
          "Salam: bayar penuh di muka, barang menyusul, cocok untuk pertanian.",
          "Istishna: pesan barang yang dibuat, cocok untuk konstruksi dan manufaktur.",
          "Kejelasan barang, harga, dan waktu menjauhkan transaksi dari gharar.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Akad jual beli dengan barang sudah ada dan margin diungkap terbuka adalah?",
            options: ["Salam", "Istishna", "Murabahah", "Ijarah"],
            answer: 2,
            explain: "Murabahah mengungkap harga pokok lalu menambah margin yang disepakati.",
          },
          {
            q: "Akad yang dibayar penuh di muka untuk barang yang diserahkan kemudian, cocok untuk pertanian?",
            options: ["Salam", "Murabahah", "Rahn", "Kafalah"],
            answer: 0,
            explain: "Salam adalah pembayaran di muka untuk barang menyusul, banyak dipakai untuk hasil tani.",
          },
          {
            q: "Memesan rumah atau kapal yang harus dibuat dulu termasuk akad?",
            options: ["Murabahah", "Istishna", "Ijarah", "Qard"],
            answer: 1,
            explain: "Istishna adalah pesanan barang yang diproduksi, cocok untuk konstruksi dan manufaktur.",
          },
          {
            q: "Harga pokok Rp50 juta, margin 10%. Harga jual murabahah?",
            options: ["Rp45 juta", "Rp55 juta", "Rp60 juta", "Rp50 juta"],
            answer: 1,
            explain: "50 + (10% x 50) = 50 + 5 = Rp55 juta.",
          },
          {
            q: "Syarat penting agar salam sah adalah?",
            options: ["Barang dirahasiakan", "Takaran, mutu, dan tempo jelas", "Harga mengambang", "Tanpa pembayaran"],
            answer: 1,
            explain: "Salam menuntut spesifikasi mutu, takaran, dan waktu penyerahan yang jelas agar tidak gharar.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-ijarah-sewa",
    levelId: "akad",
    order: 3,
    title: "Akad Ijarah (Sewa) & IMBT",
    summary: "Ijarah adalah akad sewa atas manfaat aset atau jasa. IMBT (Ijarah Muntahiyah Bittamlik) adalah sewa yang berakhir dengan perpindahan kepemilikan, mirip leasing versi syariah.",
    durationMin: 14,
    tags: ["ijarah", "imbt", "sewa", "leasing"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Ijarah</strong> adalah akad sewa: satu pihak menyewakan <em>manfaat</em> suatu aset (rumah, kendaraan, mesin) atau <em>jasa</em> tenaga kerja, dan pihak lain membayar ujrah (upah/sewa). Yang berpindah adalah manfaatnya, bukan kepemilikan barangnya.",
      },
      {
        type: "paragraph",
        html: "<strong>IMBT (Ijarah Muntahiyah Bittamlik)</strong> adalah ijarah yang di akhir masa sewa diikuti perpindahan kepemilikan aset kepada penyewa, lewat hibah atau jual beli. Inilah padanan syariah dari leasing atau sewa-beli.",
      },
      {
        type: "video",
        comp: "AkadJualBeliVideo",
        title: "Video: Perpindahan Manfaat dalam Akad",
        caption: "Dalam ijarah yang berpindah adalah manfaat aset, bukan barangnya.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ijarah vs IMBT",
        html: "<strong>Ijarah murni:</strong> setelah masa sewa selesai, aset kembali ke pemilik. <strong>IMBT:</strong> setelah masa sewa, aset menjadi milik penyewa lewat akad hibah atau jual beli yang terpisah dari akad sewanya.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dasar fatwa",
        html: "Ijarah diatur dalam Fatwa DSN-MUI No. 09/DSN-MUI/IV/2000, dan IMBT dalam Fatwa No. 27/DSN-MUI/III/2002. Objek sewa harus jelas manfaatnya, halal, dan bisa diserahkan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Gunakan kalkulator untuk membandingkan struktur pembayaran bertahap, prinsip yang sama dipakai untuk menghitung total sewa ijarah.",
      },
      { type: "widget", widget: "KalkulatorMurabahah" },
      {
        type: "table",
        caption: "Ijarah, IMBT, dan leasing konvensional",
        headers: ["Aspek", "Ijarah", "IMBT", "Leasing konvensional"],
        rows: [
          ["Objek", "Manfaat aset", "Manfaat + opsi milik", "Pembiayaan berbunga"],
          ["Akhir masa", "Aset kembali", "Aset jadi milik penyewa", "Opsi beli"],
          ["Dasar untung", "Ujrah sewa", "Ujrah + akad pindah milik", "Bunga"],
          ["Risiko aset", "Pada pemilik", "Pada pemilik selama sewa", "Sering ke penyewa"],
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Contoh Akumulasi Pembayaran Sewa IMBT 24 Bulan (ilustrasi)",
        unit: "Rp juta kumulatif",
        source: "ilustrasi edukatif",
        note: "Ujrah dibayar rutin dan terkumpul; di akhir masa aset berpindah milik lewat akad terpisah.",
        data: [
          { label: "Bln 6", value: 12, color: "#34d399" },
          { label: "Bln 12", value: 24, color: "#10b981" },
          { label: "Bln 18", value: 36, color: "#0ea5e9" },
          { label: "Bln 24", value: 48, color: "#6366f1" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Sewa mesin produksi",
        html: "Sebuah UMKM menyewa mesin jahit lewat ijarah dengan ujrah <strong>Rp2 juta per bulan</strong> selama <strong>24 bulan</strong>. Total sewa = 2 x 24 = <strong>Rp48 juta</strong>. Jika memakai skema IMBT, di akhir bulan ke-24 mesin bisa berpindah menjadi milik UMKM lewat akad hibah. Selama masa sewa, tanggung jawab perawatan besar tetap pada pemilik aset.",
      },
      {
        type: "calcExercise",
        prompt: "Ujrah sewa mobil Rp4,5 juta per bulan selama 36 bulan pada akad IMBT. Berapa total sewa (dalam juta)?",
        answer: 162,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Total = ujrah x tenor = 4,5 x 36 = <strong>Rp162 juta</strong>.",
        hint: "Kalikan ujrah bulanan dengan jumlah bulan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan maknanya.",
        pairs: [
          { left: "Ijarah", right: "Sewa manfaat aset atau jasa" },
          { left: "Ujrah", right: "Upah atau uang sewa" },
          { left: "IMBT", right: "Sewa berakhir dengan kepemilikan" },
          { left: "Objek ijarah", right: "Manfaat yang halal dan jelas" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Ijarah dalam praktik upah dan sewa klasik",
        html: "Akad <strong>ijarah</strong> telah dipraktikkan sejak masa awal Islam abad ke-7 M, baik sebagai sewa aset maupun sewa jasa. Salah satu contoh masyhur, saat hijrah sekitar tahun 622 M, Nabi Muhammad dan Abu Bakar menyewa jasa seorang penunjuk jalan yang ahli. Para ulama fikih klasik kemudian merumuskan rukun dan syarat ijarah secara rinci, termasuk kewajaran ujrah dan kejelasan manfaat yang disewakan.",
      },
      {
        type: "takeaways",
        items: [
          "Ijarah adalah sewa atas manfaat aset atau jasa, bukan pindah kepemilikan.",
          "Ujrah (sewa/upah) adalah imbalan yang halal dalam ijarah.",
          "IMBT menambahkan perpindahan kepemilikan di akhir masa sewa.",
          "Perpindahan milik pada IMBT lewat akad terpisah (hibah atau jual beli).",
          "Objek sewa harus jelas manfaatnya, halal, dan dapat diserahkan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Dalam ijarah, yang berpindah kepada penyewa adalah?",
            options: ["Kepemilikan barang", "Manfaat aset atau jasa", "Utang", "Saham"],
            answer: 1,
            explain: "Ijarah memindahkan manfaat, bukan kepemilikan barangnya.",
          },
          {
            q: "Imbalan sewa atau upah dalam ijarah disebut?",
            options: ["Nisbah", "Ujrah", "Margin", "Riba"],
            answer: 1,
            explain: "Ujrah adalah upah atau uang sewa dalam akad ijarah.",
          },
          {
            q: "Ijarah yang berakhir dengan kepemilikan penyewa disebut?",
            options: ["Salam", "IMBT", "Rahn", "Wakalah"],
            answer: 1,
            explain: "IMBT (Ijarah Muntahiyah Bittamlik) adalah sewa yang berujung kepemilikan.",
          },
          {
            q: "Ujrah Rp3 juta per bulan selama 12 bulan. Total sewa?",
            options: ["Rp24 juta", "Rp36 juta", "Rp15 juta", "Rp30 juta"],
            answer: 1,
            explain: "3 x 12 = Rp36 juta.",
          },
          {
            q: "Perpindahan kepemilikan pada IMBT dilakukan lewat?",
            options: ["Bunga", "Akad terpisah hibah atau jual beli", "Undian", "Gharar"],
            answer: 1,
            explain: "Kepemilikan berpindah lewat akad hibah atau jual beli yang terpisah dari sewanya.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-bagi-hasil-detail",
    levelId: "akad",
    order: 4,
    title: "Bagi Hasil: Mudharabah & Musyarakah",
    summary: "Dua akad bagi hasil inti syariah: mudharabah (satu pihak modal, satu pihak kelola) dan musyarakah (kongsi modal bersama). Laba dibagi per nisbah, kerugian diperlakukan berbeda.",
    durationMin: 15,
    tags: ["mudharabah", "musyarakah", "bagi hasil", "nisbah"],
    blocks: [
      {
        type: "paragraph",
        html: "Inti ekonomi syariah adalah <strong>berbagi hasil dan risiko</strong>, bukan meminjamkan uang dengan bunga tetap. Dua akadnya adalah mudharabah dan musyarakah, yang membagi laba sesuai <strong>nisbah</strong> (rasio) yang disepakati di awal.",
      },
      {
        type: "paragraph",
        html: "<strong>Mudharabah:</strong> pemodal (shahibul maal) menyerahkan modal, pengelola (mudharib) menjalankan usaha. <strong>Musyarakah:</strong> semua pihak sama-sama menyetor modal dan boleh ikut mengelola. Perbedaan besar ada pada siapa yang menanggung kerugian.",
      },
      {
        type: "video",
        comp: "BagiHasilSyariahVideo",
        title: "Video: Bagi Hasil Syariah",
        caption: "Laba dibagi menurut nisbah yang disepakati, bukan bunga tetap atas modal.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Kunci: laba per nisbah, rugi berbeda",
        html: "<strong>Laba</strong> selalu dibagi menurut nisbah yang disepakati (mis. 60:40). <strong>Rugi</strong> pada mudharabah ditanggung pemodal (mudharib rugi tenaga dan waktu), sedangkan pada musyarakah rugi ditanggung <em>proporsional terhadap modal</em> masing-masing.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Nisbah bukan bunga",
        html: "Nisbah adalah rasio pembagian laba, misalnya 70:30. Ia dikenakan pada <strong>laba nyata</strong>, jadi jika usaha tidak untung, tidak ada yang dibagi. Ini berbeda dari bunga yang tetap ditagih meski usaha rugi.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Ubah modal, laba, dan nisbah untuk melihat berapa bagian pemodal dan pengelola pada skema bagi hasil.",
      },
      { type: "widget", widget: "SimulatorBagiHasil" },
      {
        type: "table",
        caption: "Mudharabah vs Musyarakah",
        headers: ["Aspek", "Mudharabah", "Musyarakah"],
        rows: [
          ["Sumber modal", "100% pemodal", "Patungan semua pihak"],
          ["Pengelolaan", "Oleh mudharib saja", "Bisa semua pihak"],
          ["Pembagian laba", "Per nisbah sepakat", "Per nisbah sepakat"],
          ["Penanggung rugi", "Pemodal (kecuali lalai)", "Proporsional modal"],
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Contoh Pembagian Laba Nisbah 60:40 dari Laba Rp100 Juta (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif",
        note: "Laba dibagi menurut nisbah yang disepakati; angka nyata bergantung pada laba yang benar-benar diperoleh.",
        data: [
          { label: "Pemodal 60%", value: 60, color: "#34d399" },
          { label: "Pengelola 40%", value: 40, color: "#0ea5e9" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Deposito mudharabah",
        html: "Seorang nasabah menaruh dana deposito mudharabah, bank menjadi pengelola. Disepakati nisbah <strong>nasabah 55% : bank 45%</strong>. Jika bulan itu porsi laba dana nasabah adalah <strong>Rp1 juta</strong>, maka nasabah menerima 55% x 1 juta = <strong>Rp550 ribu</strong> dan bank Rp450 ribu. Jika bank rugi tanpa kelalaian, nasabah menanggung risiko kehilangan sebagian modal, bukan mendapat imbal hasil tetap seperti bunga.",
      },
      {
        type: "calcExercise",
        prompt: "Laba usaha mudharabah Rp80 juta dengan nisbah pemodal 65% : pengelola 35%. Berapa bagian pengelola (dalam juta)?",
        answer: 28,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Bagian pengelola = 35% x 80 = <strong>Rp28 juta</strong>. Pemodal mendapat 65% x 80 = Rp52 juta.",
        hint: "Kalikan nisbah pengelola dengan total laba.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan pernyataan berdasarkan akad yang tepat.",
        buckets: ["Mudharabah", "Musyarakah"],
        items: [
          { text: "Semua pihak menyetor modal bersama", bucket: "Musyarakah" },
          { text: "Satu pihak modal, satu pihak kelola", bucket: "Mudharabah" },
          { text: "Rugi ditanggung proporsional modal", bucket: "Musyarakah" },
          { text: "Rugi murni ditanggung pemodal jika bukan kelalaian", bucket: "Mudharabah" },
          { text: "Cocok untuk pembiayaan proyek patungan", bucket: "Musyarakah" },
          { text: "Pengelola menyumbang keahlian, bukan modal", bucket: "Mudharabah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Qirad/mudharabah dalam perdagangan Arab",
        html: "Skema <strong>qirad</strong> atau <strong>mudharabah</strong> sudah berjalan di jazirah Arab sebelum dan pada awal Islam abad ke-6 sampai ke-7 M. Pemilik modal yang tak bisa berdagang sendiri menyerahkan barang dagangan kepada pedagang yang berkelana, lalu laba dibagi sesuai kesepakatan. Sebelum kenabian, Nabi Muhammad sendiri pernah menjalankan usaha dagang dengan modal Khadijah dalam pola bagi hasil semacam ini. Para ulama kemudian meneguhkannya sebagai akad yang sah dalam Islam.",
      },
      {
        type: "takeaways",
        items: [
          "Bagi hasil membagi laba sesuai nisbah, bukan menagih bunga tetap.",
          "Mudharabah: satu pihak modal, satu pihak kelola.",
          "Musyarakah: semua pihak patungan modal dan boleh ikut kelola.",
          "Rugi mudharabah ditanggung pemodal; rugi musyarakah proporsional modal.",
          "Jika usaha tidak untung, tidak ada bagi hasil yang dibagikan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Akad di mana satu pihak memberi modal dan satu pihak mengelola disebut?",
            options: ["Musyarakah", "Mudharabah", "Murabahah", "Ijarah"],
            answer: 1,
            explain: "Mudharabah memisahkan pemodal (shahibul maal) dan pengelola (mudharib).",
          },
          {
            q: "Pada musyarakah, kerugian ditanggung?",
            options: ["Hanya pengelola", "Proporsional terhadap modal", "Hanya satu pihak", "Bank saja"],
            answer: 1,
            explain: "Kerugian musyarakah dibagi sesuai porsi modal masing-masing pihak.",
          },
          {
            q: "Nisbah adalah?",
            options: ["Bunga tetap", "Rasio pembagian laba", "Denda", "Pajak"],
            answer: 1,
            explain: "Nisbah adalah rasio pembagian laba yang disepakati di awal.",
          },
          {
            q: "Laba Rp50 juta, nisbah pemodal 70%. Bagian pemodal?",
            options: ["Rp15 juta", "Rp35 juta", "Rp50 juta", "Rp20 juta"],
            answer: 1,
            explain: "70% x 50 = Rp35 juta untuk pemodal.",
          },
          {
            q: "Perbedaan bagi hasil dengan bunga adalah?",
            options: ["Bagi hasil selalu lebih besar", "Bagi hasil bergantung laba nyata", "Bunga lebih adil", "Keduanya sama"],
            answer: 1,
            explain: "Bagi hasil hanya ada jika usaha untung, sedangkan bunga ditagih tetap.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-jasa-dan-jaminan",
    levelId: "akad",
    order: 5,
    title: "Akad Jasa & Jaminan",
    summary: "Akad pelengkap yang menopang transaksi: wakalah (perwakilan), kafalah (penjaminan), hawalah (pengalihan utang), dan rahn (gadai).",
    durationMin: 14,
    tags: ["wakalah", "kafalah", "hawalah", "rahn"],
    blocks: [
      {
        type: "paragraph",
        html: "Selain jual beli dan bagi hasil, ada akad <strong>jasa dan jaminan</strong> yang menopang transaksi agar berjalan aman. Empat yang terpenting: wakalah, kafalah, hawalah, dan rahn.",
      },
      {
        type: "paragraph",
        html: "Akad-akad ini jarang berdiri sendiri; mereka menyertai transaksi lain. Misalnya bank memakai <strong>wakalah</strong> saat mewakili nasabah membeli barang, dan <strong>rahn</strong> saat meminta agunan atas pembiayaan.",
      },
      {
        type: "video",
        comp: "AlurBankSyariahVideo",
        title: "Video: Alur Layanan Bank Syariah",
        caption: "Bank sering bertindak sebagai wakil (wakalah) dan penjamin (kafalah) nasabah.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Empat akad jasa dan jaminan",
        html: "<strong>Wakalah:</strong> pemberian kuasa/perwakilan untuk suatu urusan. <strong>Kafalah:</strong> penjaminan, penjamin menanggung kewajiban pihak lain. <strong>Hawalah:</strong> pengalihan utang dari satu pihak ke pihak lain. <strong>Rahn:</strong> gadai, menahan barang sebagai jaminan utang.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dasar fatwa",
        html: "Wakalah diatur Fatwa DSN-MUI No. 10/2000, kafalah No. 11/2000, hawalah No. 12/2000, dan rahn No. 25/2002. Atas jasa ini boleh dikenakan ujrah wajar, tetapi bukan bunga atas pinjaman.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan skema riba dan bagi hasil untuk memahami mengapa akad jasa dikenai ujrah tetap, bukan bunga atas pinjaman.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "table",
        caption: "Empat akad jasa dan jaminan",
        headers: ["Akad", "Fungsi", "Contoh"],
        rows: [
          ["Wakalah", "Perwakilan/kuasa", "L/C, transfer, beli atas nama nasabah"],
          ["Kafalah", "Penjaminan", "Bank garansi, jaminan tender"],
          ["Hawalah", "Pengalihan utang", "Anjak piutang, pengalihan tagihan"],
          ["Rahn", "Gadai/agunan", "Gadai emas, agunan pembiayaan"],
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Gadai emas (rahn)",
        html: "Seorang nasabah menggadaikan emas untuk memperoleh pinjaman <strong>Rp10 juta</strong>. Emas menjadi barang jaminan (marhun). Bank tidak boleh mengambil bunga atas pinjaman, tetapi boleh menarik <strong>ujrah penyimpanan</strong> yang wajar atas jasa menjaga emas, misalnya Rp50 ribu per bulan. Jika utang lunas, emas dikembalikan; jika gagal bayar, emas boleh dijual untuk menutup utang dan sisanya dikembalikan.",
      },
      {
        type: "calcExercise",
        prompt: "Pinjaman rahn Rp10 juta dengan ujrah penyimpanan Rp50 ribu per bulan selama 6 bulan. Berapa total ujrah yang dibayar (dalam ribu rupiah)?",
        answer: 300,
        tolerance: 0,
        prefix: "Rp",
        suffix: " ribu",
        solution: "Total ujrah = 50 ribu x 6 = <strong>Rp300 ribu</strong>. Ini biaya jasa simpan, bukan bunga atas pinjaman.",
        hint: "Kalikan ujrah bulanan dengan jumlah bulan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap situasi ke akad jasa/jaminan yang tepat.",
        buckets: ["Wakalah", "Kafalah", "Hawalah", "Rahn"],
        items: [
          { text: "Bank membeli barang atas nama nasabah", bucket: "Wakalah" },
          { text: "Bank menjamin kontraktor menyelesaikan proyek", bucket: "Kafalah" },
          { text: "Tagihan dialihkan dari pihak A ke pihak B", bucket: "Hawalah" },
          { text: "Emas ditahan sebagai agunan pinjaman", bucket: "Rahn" },
          { text: "Nasabah memberi kuasa transfer dana", bucket: "Wakalah" },
          { text: "Menggadaikan sertifikat untuk pembiayaan", bucket: "Rahn" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Hawalah dan cikal bakal cek",
        html: "Akad <strong>hawalah</strong> (pengalihan utang) dipakai luas oleh pedagang Muslim pada masa keemasan Islam, sekitar abad ke-8 sampai ke-12 M. Instrumen seperti <strong>suftaja</strong> dan <strong>hawala</strong> memungkinkan seorang pedagang menyetor uang di satu kota dan menariknya di kota lain lewat mitra terpercaya, tanpa membawa emas rentan rampok sepanjang perjalanan dagang. Banyak sejarawan menilai praktik ini turut memengaruhi berkembangnya sistem cek dan transfer di kemudian hari.",
      },
      {
        type: "takeaways",
        items: [
          "Akad jasa dan jaminan menopang transaksi lain agar aman.",
          "Wakalah: perwakilan; kafalah: penjaminan.",
          "Hawalah: pengalihan utang; rahn: gadai sebagai jaminan.",
          "Atas jasa boleh ujrah wajar, tetapi bukan bunga atas pinjaman.",
          "Barang gadai (marhun) dikembalikan bila utang lunas.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Akad pemberian kuasa atau perwakilan disebut?",
            options: ["Kafalah", "Wakalah", "Rahn", "Hawalah"],
            answer: 1,
            explain: "Wakalah adalah akad perwakilan atau pemberian kuasa.",
          },
          {
            q: "Akad penjaminan kewajiban pihak lain adalah?",
            options: ["Kafalah", "Wakalah", "Salam", "Ijarah"],
            answer: 0,
            explain: "Kafalah adalah penjaminan, penjamin menanggung kewajiban pihak lain.",
          },
          {
            q: "Menahan barang sebagai jaminan utang disebut?",
            options: ["Hawalah", "Rahn", "Wakalah", "Mudharabah"],
            answer: 1,
            explain: "Rahn adalah gadai, menahan barang sebagai jaminan utang.",
          },
          {
            q: "Pada rahn, atas jasa menjaga barang bank boleh menarik?",
            options: ["Bunga", "Ujrah penyimpanan wajar", "Denda tetap", "Nisbah"],
            answer: 1,
            explain: "Boleh ujrah penyimpanan yang wajar, bukan bunga atas pinjaman.",
          },
          {
            q: "Pengalihan utang dari satu pihak ke pihak lain adalah akad?",
            options: ["Rahn", "Hawalah", "Kafalah", "Wakalah"],
            answer: 1,
            explain: "Hawalah adalah pengalihan utang atau tagihan antarpihak.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-tolong-menolong",
    levelId: "akad",
    order: 6,
    title: "Akad Tolong-Menolong (Tabarru)",
    summary: "Akad kebajikan yang tidak mencari untung: qard (pinjaman), qardhul hasan (pinjaman kebajikan tanpa tambahan), tabarru (dana kebajikan dasar asuransi syariah), dan hibah.",
    durationMin: 13,
    tags: ["qard", "qardhul hasan", "tabarru", "hibah"],
    blocks: [
      {
        type: "paragraph",
        html: "Tidak semua akad mencari laba. Ada kelompok <strong>akad tabarru</strong>, yaitu akad tolong-menolong yang berorientasi kebaikan, bukan keuntungan. Di sinilah dimensi sosial ekonomi syariah paling terasa.",
      },
      {
        type: "paragraph",
        html: "Empat bentuk pentingnya: <strong>qard</strong> (pinjaman), <strong>qardhul hasan</strong> (pinjaman kebajikan tanpa tambahan apa pun), <strong>tabarru</strong> (dana kebajikan bersama, dasar asuransi syariah), dan <strong>hibah</strong> (pemberian).",
      },
      {
        type: "video",
        comp: "BagiHasilSyariahVideo",
        title: "Video: Semangat Berbagi dalam Syariah",
        caption: "Selain bagi hasil, syariah menempatkan tolong-menolong sebagai akad tersendiri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Ciri akad tabarru",
        html: "<strong>Qard:</strong> pinjaman yang wajib dikembalikan sejumlah pokok. <strong>Qardhul hasan:</strong> qard tanpa tambahan apa pun; peminjam hanya mengembalikan pokok. <strong>Tabarru:</strong> peserta menyumbang ke dana bersama untuk saling menanggung risiko. <strong>Hibah:</strong> pemberian sukarela tanpa imbalan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tambahan yang disyaratkan = riba",
        html: "Pada qard, setiap <strong>tambahan yang disyaratkan di awal</strong> atas pengembalian pinjaman adalah riba dan dilarang. Peminjam boleh memberi kelebihan sebagai tanda terima kasih secara sukarela, tetapi tidak boleh diperjanjikan.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana skema berbasis bunga membebani peminjam, lalu bandingkan dengan qardhul hasan yang hanya mengembalikan pokok.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "table",
        caption: "Akad tolong-menolong (tabarru)",
        headers: ["Akad", "Sifat", "Contoh penerapan"],
        rows: [
          ["Qard", "Pinjaman pokok", "Talangan jangka pendek"],
          ["Qardhul hasan", "Pinjaman kebajikan", "Bantuan modal usaha kecil"],
          ["Tabarru", "Dana kebajikan bersama", "Asuransi syariah (takaful)"],
          ["Hibah", "Pemberian sukarela", "Bonus, hadiah, wakaf tunai"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Qardhul Hasan vs Pinjaman Berbunga Rp5 Juta, 10 Bulan (ilustrasi)",
        unit: "Rp juta total dikembalikan",
        source: "ilustrasi edukatif",
        note: "Qardhul hasan hanya mengembalikan pokok; pinjaman berbunga menambah beban di atas pokok.",
        data: [
          { label: "Qardhul hasan", value: 5, color: "#34d399" },
          { label: "Bunga 2%/bln", value: 6, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dana tabarru asuransi syariah",
        html: "Dalam asuransi syariah (takaful), setiap peserta menyumbang <strong>Rp200 ribu per bulan</strong> ke <strong>dana tabarru</strong> bersama. Jika ada 1.000 peserta, dana terkumpul Rp200 juta per bulan. Saat seorang peserta tertimpa musibah, santunan diambil dari dana tabarru ini. Konsepnya saling menanggung (taawun), bukan jual beli risiko seperti asuransi konvensional. Surplus dana bisa dibagikan kembali kepada peserta sesuai ketentuan.",
      },
      {
        type: "calcExercise",
        prompt: "Pinjaman qardhul hasan Rp5 juta tanpa tambahan apa pun, dikembalikan dalam 10 bulan. Berapa total yang wajib dikembalikan peminjam (dalam juta)?",
        answer: 5,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Qardhul hasan tanpa tambahan, jadi peminjam hanya mengembalikan pokok = <strong>Rp5 juta</strong>.",
        hint: "Qardhul hasan tidak menambahkan apa pun di atas pokok.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan akad dengan cirinya.",
        pairs: [
          { left: "Qard", right: "Pinjaman yang dikembalikan sebesar pokok" },
          { left: "Qardhul hasan", right: "Pinjaman kebajikan tanpa tambahan" },
          { left: "Tabarru", right: "Dana kebajikan untuk saling menanggung" },
          { left: "Hibah", right: "Pemberian sukarela tanpa imbalan" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Baitul maal dan qardhul hasan",
        html: "Pada masa awal Islam abad ke-7 M, <strong>baitul maal</strong> (kas negara/umat) menjadi lembaga yang menghimpun zakat, infak, dan harta umum, lalu menyalurkannya untuk kemaslahatan. Salah satu fungsinya adalah memberi <strong>qardhul hasan</strong>, pinjaman kebajikan tanpa tambahan, kepada yang membutuhkan modal atau terlilit kesulitan. Pada masa Khalifah Umar bin Khattab, pengelolaan baitul maal ditata lebih rapi sebagai sarana keadilan sosial ekonomi.",
      },
      {
        type: "takeaways",
        items: [
          "Akad tabarru adalah akad tolong-menolong, bukan mencari untung.",
          "Qard dikembalikan sebesar pokok; qardhul hasan tanpa tambahan apa pun.",
          "Tambahan yang disyaratkan atas qard adalah riba dan dilarang.",
          "Tabarru adalah dana kebajikan bersama, dasar asuransi syariah (takaful).",
          "Hibah adalah pemberian sukarela tanpa mengharap imbalan.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Pinjaman kebajikan tanpa tambahan apa pun disebut?",
            options: ["Murabahah", "Qardhul hasan", "Ijarah", "Kafalah"],
            answer: 1,
            explain: "Qardhul hasan adalah pinjaman kebajikan; peminjam hanya mengembalikan pokok.",
          },
          {
            q: "Dana bersama untuk saling menanggung risiko dalam asuransi syariah disebut?",
            options: ["Nisbah", "Tabarru", "Ujrah", "Rahn"],
            answer: 1,
            explain: "Dana tabarru dihimpun untuk saling menanggung (taawun) antarpeserta.",
          },
          {
            q: "Tambahan yang disyaratkan di awal atas pengembalian qard termasuk?",
            options: ["Sedekah", "Riba", "Hibah", "Nisbah"],
            answer: 1,
            explain: "Tambahan yang disyaratkan atas pinjaman adalah riba dan dilarang.",
          },
          {
            q: "Pemberian sukarela tanpa mengharap imbalan disebut?",
            options: ["Hibah", "Qard", "Kafalah", "Salam"],
            answer: 0,
            explain: "Hibah adalah pemberian sukarela tanpa imbalan.",
          },
          {
            q: "Qardhul hasan Rp3 juta dikembalikan penuh. Total yang dikembalikan?",
            options: ["Rp3,3 juta", "Rp3 juta", "Rp3,5 juta", "Rp2,7 juta"],
            answer: 1,
            explain: "Tanpa tambahan, peminjam mengembalikan pokok Rp3 juta saja.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-yang-dilarang",
    levelId: "akad",
    order: 7,
    title: "Akad yang Batil, Fasid & Riba Terselubung",
    summary: "Membedakan akad batil (rukun tak terpenuhi) dan akad fasid (rukun ada tapi syarat cacat), larangan dua akad dalam satu transaksi, rekayasa akad (hilah) seperti bai al-inah dan tawarruq, serta riba yang disamarkan berkedok jual beli.",
    durationMin: 14,
    tags: ["batil", "fasid", "hilah", "riba", "bai al-inah", "tawarruq"],
    blocks: [
      {
        type: "paragraph",
        html: "Setelah mengenal aneka akad yang sah, penting memahami kapan sebuah akad <strong>gugur atau cacat</strong>. Fikih muamalah membedakan dua tingkat kerusakan: <strong>akad batil</strong> dan <strong>akad fasid</strong>. Keduanya berbeda dari sekadar akad yang sah tetapi kurang sempurna.",
      },
      {
        type: "paragraph",
        html: "Selain itu ada praktik <strong>rekayasa akad (hilah)</strong>, yaitu menyusun transaksi agar tampak syar'i di permukaan padahal hasil ekonominya sama dengan pinjaman berbunga. Bab ini melatih kepekaan agar tidak tertipu <strong>riba terselubung</strong> yang berkedok jual beli.",
      },
      {
        type: "video",
        comp: "AkadJualBeliVideo",
        title: "Video: Kapan Akad Jual Beli Menjadi Cacat",
        caption: "Rukun dan syarat yang tidak terpenuhi membuat akad jual beli batil atau fasid.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Batil vs fasid",
        html: "<strong>Batil:</strong> salah satu <em>rukun</em> tidak terpenuhi, mis. objek haram (khamar, babi), objek tidak ada, atau tidak jelas pihaknya. Akad dianggap tidak pernah ada. <strong>Fasid:</strong> rukun lengkap tetapi ada <em>syarat</em> yang cacat, mis. harga tidak pasti atau ada syarat yang merusak. Menurut mayoritas ulama non-Hanafi, batil dan fasid sama-sama tidak sah; mazhab Hanafi membedakan keduanya dan menilai akad fasid bisa diperbaiki bila cacatnya dihilangkan.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Larangan dua akad dalam satu transaksi",
        html: "Ada larangan <strong>dua jual beli dalam satu jual beli</strong> (safqatain fi safqah) dan menggabungkan akad utang dengan jual beli. Menggabungkan pinjaman dengan syarat harus membeli sesuatu, atau satu transaksi berharga ganda yang tidak jelas mana yang mengikat, memicu gharar dan sering menjadi pintu riba.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Hilah: rekayasa akad yang dipersoalkan",
        html: "<strong>Bai al-inah:</strong> menjual barang secara tunai lalu membelinya kembali secara kredit lebih mahal, sehingga hasil bersihnya sama dengan pinjaman berbunga. <strong>Tawarruq:</strong> membeli barang secara kredit lalu menjualnya kepada pihak ketiga untuk memperoleh uang tunai. Jumhur ulama menolak bai al-inah, dan tawarruq yang direkayasa (munazzam) dikritik keras karena substansinya riba meski bentuknya jual beli.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan skema berbunga dengan bagi hasil untuk melihat mengapa rekayasa akad yang hasil ekonominya sama persis dengan bunga tetap dinilai bermasalah, bukan sekadar soal nama.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "table",
        caption: "Tingkat keabsahan akad",
        headers: ["Status", "Kondisi", "Contoh"],
        rows: [
          ["Sah", "Rukun dan syarat lengkap", "Murabahah dengan harga jelas"],
          ["Fasid", "Rukun ada, syarat cacat", "Jual beli dengan harga tak pasti"],
          ["Batil", "Rukun tidak terpenuhi", "Menjual barang haram atau fiktif"],
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Bai al-Inah: Hasil Bersih Sama dengan Pinjaman Berbunga (ilustrasi)",
        unit: "Rp juta",
        source: "ilustrasi edukatif fikih muamalah",
        note: "Dua akad jual beli disusun bolak-balik, tetapi arus kas bersihnya identik dengan meminjam Rp10 juta dan mengembalikan Rp12 juta.",
        data: [
          { label: "Uang tunai diterima", value: 10, color: "#0ea5e9" },
          { label: "Kewajiban kredit", value: 12, color: "#ef4444" },
          { label: "Selisih (spt bunga)", value: 2, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Membedah bai al-inah",
        html: "Pak Andi butuh uang tunai. Sebuah lembaga menjual sebidang barang kepadanya seharga <strong>Rp12 juta</strong> secara kredit 12 bulan, lalu <em>seketika</em> membeli kembali barang yang sama dari Pak Andi seharga <strong>Rp10 juta</strong> tunai. Hasilnya: Pak Andi memegang Rp10 juta tunai dan berutang Rp12 juta. Barangnya tidak ke mana-mana, hanya berpindah nama sesaat. Substansinya adalah pinjaman Rp10 juta yang dikembalikan Rp12 juta, selisih Rp2 juta berperan seperti bunga. Karena itu jumhur ulama menilai akad ini sebagai hilah menuju riba, bukan jual beli yang sesungguhnya.",
      },
      {
        type: "calcExercise",
        prompt: "Dalam skema bai al-inah, barang dijual kredit Rp12 juta lalu dibeli kembali tunai Rp10 juta. Berapa selisih yang berperan seperti bunga (dalam juta)?",
        answer: 2,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Selisih = 12 - 10 = <strong>Rp2 juta</strong>. Inilah tambahan atas dana Rp10 juta yang substansinya menyerupai bunga.",
        hint: "Kurangi harga beli kembali dari harga jual kredit.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan tiap transaksi sebagai sah atau batil/fasid menurut fikih muamalah.",
        buckets: ["Sah", "Batil / Fasid"],
        items: [
          { text: "Murabahah mobil dengan harga jual dikunci jelas di awal", bucket: "Sah" },
          { text: "Jual beli minuman keras (objek haram)", bucket: "Batil / Fasid" },
          { text: "Menjual barang yang belum ada dan tidak jelas wujudnya", bucket: "Batil / Fasid" },
          { text: "Ijarah mesin dengan ujrah dan masa sewa yang pasti", bucket: "Sah" },
          { text: "Jual beli dengan harga dibiarkan mengambang tanpa kepastian", bucket: "Batil / Fasid" },
          { text: "Salam gabah dengan takaran, mutu, dan tempo yang jelas", bucket: "Sah" },
        ],
      },
      {
        type: "case",
        title: "Sejarah: Perdebatan ulama soal hilah sepanjang fikih",
        html: "Perdebatan tentang <strong>hilah</strong> (rekayasa akad) sudah berlangsung berabad-abad. Pada masa klasik sekitar abad ke-8 sampai ke-14 M, sebagian ulama mazhab menoleransi rekayasa tertentu bila rukun formalnya terpenuhi, sementara Imam Malik menolak lewat kaidah <em>saddu dzari'ah</em> (menutup jalan menuju keharaman) dan menilai <strong>bai al-inah</strong> sebagai celah menuju riba. Ibnu Taimiyah dan muridnya Ibnul Qayyim pada abad ke-13 sampai ke-14 M menegaskan bahwa yang dinilai adalah <em>maksud dan substansi</em> akad, bukan sekadar bentuk lahirnya. Perdebatan ini berlanjut hingga era modern: forum fikih seperti Majma al-Fiqh al-Islami membolehkan <strong>tawarruq</strong> yang murni (haqiqi) tetapi mengharamkan tawarruq terorganisir (munazzam) yang direkayasa bank, karena hakikatnya menyamarkan riba.",
      },
      {
        type: "takeaways",
        items: [
          "Akad batil: rukun tidak terpenuhi, akad dianggap tidak pernah ada.",
          "Akad fasid: rukun lengkap tetapi ada syarat yang cacat.",
          "Menggabungkan dua akad atau utang dengan jual beli bisa memicu gharar dan riba.",
          "Bai al-inah dan tawarruq munazzam dikritik sebagai hilah menuju riba terselubung.",
          "Fikih menimbang substansi dan maksud akad, bukan sekadar bentuk lahirnya.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Akad yang gugur karena salah satu rukunnya tidak terpenuhi disebut?",
            options: ["Sah", "Fasid", "Batil", "Makruh"],
            answer: 2,
            explain: "Akad batil terjadi ketika rukun tidak terpenuhi, mis. objek haram atau fiktif.",
          },
          {
            q: "Akad yang rukunnya lengkap tetapi ada syarat yang cacat disebut?",
            options: ["Batil", "Fasid", "Sah", "Tabarru"],
            answer: 1,
            explain: "Akad fasid memiliki rukun lengkap namun cacat pada syarat, mis. harga tidak pasti.",
          },
          {
            q: "Menjual barang tunai lalu membelinya kembali secara kredit lebih mahal disebut?",
            options: ["Tawarruq", "Bai al-inah", "Salam", "Musyarakah"],
            answer: 1,
            explain: "Bai al-inah menyusun dua jual beli yang hasil bersihnya menyerupai pinjaman berbunga.",
          },
          {
            q: "Yang menjadi dasar penilaian ulama seperti Ibnul Qayyim atas rekayasa akad adalah?",
            options: ["Bentuk lahir akad saja", "Maksud dan substansi akad", "Besar keuntungan", "Nama produk"],
            answer: 1,
            explain: "Substansi dan maksud akad dinilai, bukan sekadar bentuk formalnya, untuk menutup jalan menuju riba.",
          },
          {
            q: "Barang dijual kredit Rp15 juta lalu dibeli kembali tunai Rp12 juta. Selisih yang berperan seperti bunga?",
            options: ["Rp3 juta", "Rp27 juta", "Rp12 juta", "Rp15 juta"],
            answer: 0,
            explain: "15 - 12 = Rp3 juta, tambahan atas dana Rp12 juta yang substansinya menyerupai bunga.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "akad-di-fintech-syariah",
    levelId: "akad",
    order: 8,
    title: "Akad dalam Fintech Syariah",
    summary: "Bagaimana layanan pinjam-meminjam (P2P) dan uang elektronik syariah menyusun akad qardh, murabahah, musyarakah, dan wadiah sesuai fatwa DSN-MUI.",
    durationMin: 15,
    tags: ["fintech", "p2p", "qardh", "murabahah", "wadiah"],
    blocks: [
      {
        type: "paragraph",
        html: "Teknologi mengubah cara orang bertransaksi, tetapi tidak mengubah aturan syariah. Sebuah aplikasi pinjam-meminjam atau dompet digital tetap dinilai dari <strong>akad</strong> yang dipakai, bukan dari tampilan aplikasinya. Fintech syariah menuangkan akad klasik ke dalam platform modern.",
      },
      {
        type: "paragraph",
        html: "Di layanan <strong>peer to peer (P2P) lending syariah</strong>, platform mempertemukan pemberi dana dan penerima dana. Akad yang dipakai bergantung pada tujuan pembiayaan: <strong>qardh</strong> untuk pinjaman kebajikan tanpa tambahan, <strong>murabahah</strong> untuk pengadaan barang, serta <strong>musyarakah</strong> atau <strong>mudharabah</strong> untuk usaha bagi hasil. Platform sendiri biasanya memakai akad <strong>wakalah bil ujrah</strong>, yaitu bertindak sebagai wakil dengan imbalan jasa.",
      },
      {
        type: "video",
        comp: "AkadJualBeliVideo",
        title: "Video: Akad Murabahah di Platform Digital",
        caption: "Prinsip jual beli yang sama, kini dijalankan lewat aplikasi fintech syariah.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Fatwa DSN-MUI No 117 Tahun 2018",
        html: "DSN-MUI menerbitkan <strong>Fatwa No 117/DSN-MUI/II/2018</strong> tentang Layanan Pembiayaan Berbasis Teknologi Informasi Berdasarkan Prinsip Syariah. Fatwa ini mengatur para pihak (penyelenggara, pemberi, penerima pembiayaan) dan membolehkan beberapa model akad selama bebas riba, gharar, dan maysir.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Uang elektronik syariah",
        html: "Untuk dompet digital, DSN-MUI mengeluarkan <strong>Fatwa No 116/DSN-MUI/IX/2017</strong>. Hubungan penerbit dengan pemegang uang elektronik memakai akad <strong>wadiah</strong> (titipan) atau <strong>qardh</strong> (pinjaman), sedangkan layanannya bisa memakai <strong>ijarah</strong>, <strong>ju'alah</strong>, atau <strong>wakalah</strong>. Saldo tidak boleh menghasilkan bunga.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pada pembiayaan usaha berbasis bagi hasil, keuntungan dibagi sesuai nisbah, bukan bunga tetap. Coba simulator untuk melihat bagaimana laba usaha mengalir ke pemberi dana.",
      },
      { type: "widget", widget: "SimulatorBagiHasil" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Pertumbuhan Fintech Syariah Indonesia",
        unit: "indeks (2017 = 100)",
        source: "ilustrasi konsep, pola pertumbuhan industri",
        note: "Sejak layanan pertama terdaftar sekitar 2017, jumlah penyelenggara dan penyaluran fintech syariah tumbuh pesat meski basisnya masih kecil dibanding fintech konvensional.",
        data: [
          { label: "2017", value: 100, color: "#34d399" },
          { label: "2019", value: 320, color: "#10b981" },
          { label: "2021", value: 640, color: "#0ea5e9" },
          { label: "2023", value: 980, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pembiayaan modal usaha lewat P2P syariah",
        html: "Seorang pemilik warung butuh <strong>Rp10 juta</strong> untuk menambah stok. Melalui platform P2P syariah dengan akad <strong>murabahah</strong>, platform (mewakili pemberi dana) membeli barang lalu menjualnya ke pemilik warung dengan margin disepakati <strong>12%</strong> = Rp1,2 juta, sehingga total kewajiban <strong>Rp11,2 juta</strong> yang dibayar bertahap. Margin ini adalah laba jual beli yang tetap, bukan bunga yang bertambah bila telat. Platform mengambil <strong>ujrah</strong> (fee) atas jasanya, bukan bunga atas dana.",
      },
      {
        type: "case",
        title: "Sejarah: Lahirnya fintech syariah Indonesia (sekitar 2017)",
        html: "Layanan fintech P2P syariah pertama di Indonesia mulai terdaftar di OJK sekitar <strong>2017</strong>, di antaranya platform seperti Ammana dan ALAMI. Kehadiran <strong>Fatwa DSN-MUI No 117 Tahun 2018</strong> memberi kepastian akad, sehingga industri tumbuh cepat. Meski nilainya masih jauh di bawah fintech konvensional, fintech syariah menjadi jalur pembiayaan baru bagi UMKM yang ingin menghindari riba.",
      },
      {
        type: "calcExercise",
        prompt: "Pembiayaan murabahah lewat P2P syariah senilai Rp10 juta dengan margin disepakati 12%. Berapa total kewajiban penerima dana (dalam juta)?",
        answer: 11.2,
        tolerance: 0.05,
        prefix: "Rp",
        suffix: " juta",
        solution: "Margin = 12% x 10 juta = 1,2 juta. Total = 10 + 1,2 = Rp11,2 juta. Karena harga dikunci di awal, kewajiban tidak bertambah bila terlambat.",
        hint: "Tambahkan margin ke pokok pembiayaan.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan akad fintech syariah dengan fungsinya.",
        pairs: [
          { left: "Qardh", right: "Pinjaman kebajikan tanpa tambahan" },
          { left: "Murabahah", right: "Jual beli dengan margin yang disepakati" },
          { left: "Musyarakah", right: "Kongsi modal dengan bagi hasil" },
          { left: "Wakalah bil ujrah", right: "Platform sebagai wakil yang mengambil fee jasa" },
          { left: "Wadiah", right: "Titipan saldo pada uang elektronik" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Fintech syariah tetap dinilai dari akadnya, bukan dari teknologinya.",
          "P2P syariah memakai qardh, murabahah, musyarakah, atau mudharabah sesuai tujuan pembiayaan.",
          "Platform mengambil ujrah (fee jasa) lewat akad wakalah bil ujrah, bukan bunga atas dana.",
          "Uang elektronik syariah memakai akad wadiah atau qardh; saldo tidak boleh berbunga.",
          "Landasannya adalah Fatwa DSN-MUI No 117 Tahun 2018 (P2P) dan No 116 Tahun 2017 (uang elektronik).",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fatwa DSN-MUI yang mengatur layanan pembiayaan berbasis teknologi informasi syariah adalah?",
            options: ["No 116 Tahun 2017", "No 117 Tahun 2018", "No 7 Tahun 1989", "No 3 Tahun 2006"],
            answer: 1,
            explain: "Fatwa No 117/DSN-MUI/II/2018 mengatur layanan pembiayaan berbasis teknologi informasi (P2P) berdasarkan prinsip syariah.",
          },
          {
            q: "Akad yang biasa dipakai platform fintech untuk mengambil imbalan jasa adalah?",
            options: ["Riba", "Wakalah bil ujrah", "Bai al-inah", "Gharar"],
            answer: 1,
            explain: "Platform bertindak sebagai wakil (wakalah) dan berhak atas ujrah, yaitu imbalan jasa, bukan bunga atas dana.",
          },
          {
            q: "Untuk uang elektronik syariah, hubungan penerbit dengan pemegang saldo memakai akad?",
            options: ["Murabahah atau salam", "Wadiah atau qardh", "Ijarah muntahiyah", "Istishna"],
            answer: 1,
            explain: "Fatwa No 116 Tahun 2017 menetapkan akad wadiah (titipan) atau qardh (pinjaman) untuk saldo, tanpa memberi bunga.",
          },
          {
            q: "Pembiayaan qardh dalam P2P syariah bercirikan?",
            options: ["Ada bunga harian", "Pinjaman kebajikan tanpa tambahan", "Wajib bagi hasil", "Denda berbunga"],
            answer: 1,
            explain: "Qardh adalah pinjaman kebajikan; yang dikembalikan sebesar pokok tanpa tambahan yang disyaratkan.",
          },
          {
            q: "Pembiayaan murabahah Rp8 juta dengan margin 10% menghasilkan total kewajiban?",
            options: ["Rp8 juta", "Rp8,8 juta", "Rp9 juta", "Rp10 juta"],
            answer: 1,
            explain: "Margin = 10% x 8 juta = 0,8 juta, sehingga total = 8 + 0,8 = Rp8,8 juta yang dikunci di awal.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "sengketa-ekonomi-syariah",
    levelId: "akad",
    order: 9,
    title: "Menyelesaikan Sengketa Ekonomi Syariah",
    summary: "Jalur penyelesaian sengketa dari musyawarah, arbitrase melalui Basyarnas, hingga kewenangan Pengadilan Agama berdasarkan UU No 3 Tahun 2006.",
    durationMin: 14,
    tags: ["sengketa", "basyarnas", "arbitrase", "pengadilan-agama"],
    blocks: [
      {
        type: "paragraph",
        html: "Sebaik apa pun akad disusun, perselisihan bisa saja muncul, misalnya soal penafsiran nisbah bagi hasil atau keterlambatan pembayaran. Islam menganjurkan menyelesaikan sengketa dengan cara yang menjaga hubungan baik, sehingga jalur <strong>musyawarah</strong> selalu didahulukan sebelum menempuh jalur formal.",
      },
      {
        type: "paragraph",
        html: "Bila musyawarah gagal, para pihak bisa memilih <strong>arbitrase</strong> melalui <strong>Basyarnas (Badan Arbitrase Syariah Nasional)</strong> yang putusannya final dan mengikat, atau membawa perkara ke <strong>Pengadilan Agama</strong>. Sejak <strong>UU No 3 Tahun 2006</strong>, Pengadilan Agama berwenang mengadili sengketa ekonomi syariah, termasuk perbankan, asuransi, dan pembiayaan syariah.",
      },
      {
        type: "video",
        comp: "AlurBankSyariahVideo",
        title: "Video: Alur Penyelesaian di Ekosistem Syariah",
        caption: "Dari akad hingga jalur penyelesaian bila terjadi perselisihan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga jalur penyelesaian",
        html: "<strong>1. Musyawarah (sulh):</strong> berdamai, menghasilkan akta perdamaian. <strong>2. Arbitrase (Basyarnas):</strong> arbiter memutus, hasilnya final dan mengikat tanpa banding. <strong>3. Pengadilan Agama:</strong> lembaga peradilan negara yang berwenang atas sengketa ekonomi syariah.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Apa itu Basyarnas?",
        html: "Basyarnas adalah lembaga arbitrase khusus untuk sengketa muamalah yang bernaung di bawah MUI. Para pihak menyepakati klausul arbitrase dalam akad; bila sengketa muncul, arbiter yang memahami fikih muamalah memutus perkara secara tertutup, cepat, dan mengikat.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Perhatikan klausul akad",
        html: "Pilihan forum penyelesaian sebaiknya ditulis jelas dalam akad. Bila akad menyebut arbitrase Basyarnas, para pihak terikat jalur itu. Menyeret perkara ke forum yang tidak disepakati bisa membuat gugatan tidak diterima.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Banyak sengketa berakar pada salah paham antara bunga tetap dan bagi hasil. Coba simulator untuk melihat perbedaan keduanya agar hak tiap pihak jelas sejak awal.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "chart",
        variant: "bar",
        title: "Ilustrasi Perkiraan Lama Penyelesaian per Jalur",
        unit: "bulan (perkiraan)",
        source: "ilustrasi konsep, gambaran umum",
        note: "Musyawarah paling cepat dan murah; arbitrase Basyarnas relatif ringkas karena final; jalur pengadilan bisa lebih lama bila berlanjut ke tingkat banding dan kasasi.",
        data: [
          { label: "Musyawarah", value: 1, color: "#34d399" },
          { label: "Basyarnas", value: 6, color: "#10b981" },
          { label: "Pengadilan (tingkat 1)", value: 8, color: "#0ea5e9" },
          { label: "Hingga kasasi", value: 20, color: "#f59e0b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Selisih paham nisbah bagi hasil",
        html: "Sebuah usaha bermodal mudharabah menghasilkan laba <strong>Rp20 juta</strong>. Akad menetapkan nisbah pemodal (shahibul maal) : pengelola (mudharib) = <strong>40 : 60</strong>. Pengelola mengira pemodal hanya berhak atas modal, padahal akad jelas menyebut bagi hasil, sehingga bagian pemodal = 40% x Rp20 juta = <strong>Rp8 juta</strong>. Karena klausul akad menunjuk Basyarnas, sengketa diselesaikan lewat arbitrase dan putusannya final.",
      },
      {
        type: "case",
        title: "Sejarah: Dari BAMUI (1993) ke Basyarnas (2003)",
        html: "Lembaga arbitrase syariah pertama Indonesia berdiri pada <strong>1993</strong> dengan nama <strong>BAMUI (Badan Arbitrase Muamalat Indonesia)</strong>, seiring lahirnya perbankan syariah. Pada <strong>2003</strong> namanya diubah menjadi <strong>Basyarnas (Badan Arbitrase Syariah Nasional)</strong> di bawah MUI, memperluas cakupan ke seluruh sengketa ekonomi syariah. Tiga tahun kemudian, <strong>UU No 3 Tahun 2006</strong> menegaskan kewenangan Pengadilan Agama atas perkara ekonomi syariah.",
      },
      {
        type: "calcExercise",
        prompt: "Laba usaha mudharabah Rp20 juta dengan nisbah pemodal : pengelola = 40 : 60. Berapa bagian pemodal (dalam juta)?",
        answer: 8,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Bagian pemodal = 40% x 20 juta = Rp8 juta. Bagi hasil dihitung dari laba, bukan dari modal, sesuai nisbah yang disepakati.",
        hint: "Kalikan persentase nisbah pemodal dengan total laba.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan ciri berikut ke jalur penyelesaian yang tepat.",
        buckets: ["Musyawarah", "Basyarnas", "Pengadilan Agama"],
        items: [
          { text: "Kedua pihak berdamai tanpa pihak ketiga memutus", bucket: "Musyawarah" },
          { text: "Menghasilkan akta perdamaian (sulh)", bucket: "Musyawarah" },
          { text: "Arbiter memutus, hasilnya final dan mengikat", bucket: "Basyarnas" },
          { text: "Lembaga arbitrase di bawah MUI", bucket: "Basyarnas" },
          { text: "Lembaga peradilan negara", bucket: "Pengadilan Agama" },
          { text: "Berwenang sejak UU No 3 Tahun 2006", bucket: "Pengadilan Agama" },
        ],
      },
      {
        type: "takeaways",
        items: [
          "Musyawarah (sulh) selalu didahulukan karena menjaga hubungan dan paling cepat.",
          "Basyarnas adalah lembaga arbitrase syariah di bawah MUI; putusannya final dan mengikat.",
          "Pengadilan Agama berwenang atas sengketa ekonomi syariah sejak UU No 3 Tahun 2006.",
          "Forum penyelesaian sebaiknya ditulis jelas sebagai klausul dalam akad.",
          "Basyarnas berawal dari BAMUI (1993) dan berganti nama pada 2003.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Jalur yang paling dianjurkan untuk didahulukan dalam menyelesaikan sengketa adalah?",
            options: ["Kasasi", "Musyawarah (sulh)", "Eksekusi lelang", "Gugatan pidana"],
            answer: 1,
            explain: "Islam menganjurkan perdamaian; musyawarah didahulukan karena menjaga hubungan dan paling cepat.",
          },
          {
            q: "Basyarnas adalah kependekan dari?",
            options: ["Badan Syariah Nasional", "Badan Arbitrase Syariah Nasional", "Balai Sengketa Syariah", "Badan Amil Syariah Nasional"],
            answer: 1,
            explain: "Basyarnas adalah Badan Arbitrase Syariah Nasional, lembaga arbitrase muamalah di bawah MUI.",
          },
          {
            q: "Undang-undang yang menegaskan kewenangan Pengadilan Agama atas sengketa ekonomi syariah adalah?",
            options: ["UU No 7 Tahun 1992", "UU No 3 Tahun 2006", "UU No 21 Tahun 2008", "UU No 40 Tahun 2007"],
            answer: 1,
            explain: "UU No 3 Tahun 2006 (perubahan UU Peradilan Agama) memberi Pengadilan Agama kewenangan atas ekonomi syariah.",
          },
          {
            q: "Ciri putusan arbitrase Basyarnas adalah?",
            options: ["Bisa dibanding berkali-kali", "Final dan mengikat", "Hanya saran", "Selalu diumumkan ke publik"],
            answer: 1,
            explain: "Putusan arbitrase bersifat final dan mengikat para pihak, tanpa upaya banding biasa.",
          },
          {
            q: "Laba mudharabah Rp30 juta dengan nisbah pemodal : pengelola = 50 : 50. Bagian pemodal adalah?",
            options: ["Rp10 juta", "Rp15 juta", "Rp20 juta", "Rp30 juta"],
            answer: 1,
            explain: "Bagian pemodal = 50% x 30 juta = Rp15 juta, dihitung dari laba sesuai nisbah.",
          },
        ],
      },
    ],
  },
];
