import type { Lesson } from "../../../types";

export const level1: Lesson[] = [
  // ============================================================
  {
    id: "apa-itu-ekonomi-syariah",
    levelId: "dasar",
    order: 1,
    title: "Apa Itu Ekonomi Syariah",
    summary: "Sistem ekonomi berlandaskan nilai Islam, tujuannya (maqashid syariah), dan tiga larangan inti: riba, gharar, dan maysir.",
    durationMin: 13,
    tags: ["dasar", "prinsip", "riba", "maqashid"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Ekonomi syariah</strong> adalah sistem ekonomi yang berpijak pada nilai dan aturan Islam, bersumber dari Al-Quran dan Sunnah. Tujuannya bukan sekadar mengejar keuntungan, melainkan mencapai <strong>falah</strong>, yaitu kesejahteraan yang adil di dunia dan akhirat.",
      },
      {
        type: "paragraph",
        html: "Kerangka tujuannya disebut <strong>maqashid syariah</strong>: menjaga agama, jiwa, akal, keturunan, dan harta. Ekonomi dipandang sebagai sarana memelihara kelima hal ini, bukan tujuan akhir itu sendiri.",
      },
      {
        type: "video",
        comp: "LaranganRibaVideo",
        title: "Video: Tiga Larangan Inti Ekonomi Syariah",
        caption: "Riba, gharar, dan maysir adalah pagar utama agar transaksi tetap adil.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Ibn_Khaldoun-Kassus.jpg?width=400",
        alt: "Patung Ibn Khaldun",
        caption: "Ibn Khaldun (1332-1406), cendekiawan Muslim yang menulis gagasan ekonomi awal dalam Muqaddimah.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga larangan inti",
        html: "<strong>Riba:</strong> tambahan tanpa imbangan yang sah, terutama bunga. <strong>Gharar:</strong> ketidakpastian berlebihan dalam akad. <strong>Maysir:</strong> perjudian dan spekulasi murni. Ketiganya dianggap menimbulkan ketidakadilan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Ganti bunga: berbagi risiko",
        html: "Sebagai pengganti bunga, ekonomi syariah memakai <strong>jual beli</strong>, <strong>sewa</strong>, dan <strong>bagi hasil</strong>. Imbalan harus datang bersama risiko dan usaha nyata, bukan sekadar meminjamkan uang.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan pinjaman berbunga dengan pembiayaan bagi hasil pada saat usaha untung maupun rugi.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "chart",
        variant: "bar",
        title: "Aset Keuangan Syariah Indonesia Terus Tumbuh (ilustrasi tren)",
        unit: "pangsa pasar keuangan syariah (%)",
        source: "ilustrasi tren, bukan angka resmi tahunan",
        note: "Pangsa keuangan syariah Indonesia terus naik meski masih di bawah konvensional, menunjukkan minat yang tumbuh.",
        data: [
          { label: "2015", value: 4.9, color: "#34d399" },
          { label: "2018", value: 8.1, color: "#10b981" },
          { label: "2021", value: 10.2, color: "#059669" },
          { label: "2023", value: 11.0, color: "#047857" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Pinjaman berbunga vs bagi hasil saat rugi",
        html: "Seorang pengusaha meminjam Rp100 juta. Skema <strong>bunga</strong> 12% mewajibkannya membayar Rp12 juta apa pun hasilnya, sehingga saat usahanya rugi ia makin terpuruk. Skema <strong>bagi hasil (mudharabah)</strong> membuat pemodal ikut menanggung: bila untung dibagi sesuai nisbah, bila rugi (bukan karena lalai) kerugian ditanggung pemodal. Inilah inti keadilan berbagi risiko dalam ekonomi syariah.",
      },
      {
        type: "classifyExercise",
        prompt: "Praktik ini melanggar larangan yang mana?",
        buckets: ["Riba", "Gharar", "Maysir"],
        items: [
          { text: "Bunga tetap atas pinjaman uang", bucket: "Riba" },
          { text: "Menjual ikan yang masih di laut, jumlah tak jelas", bucket: "Gharar" },
          { text: "Taruhan pada hasil pertandingan", bucket: "Maysir" },
          { text: "Menukar 1 gram emas dengan 1,1 gram emas", bucket: "Riba" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Pinjaman Rp100 juta dengan bunga tetap 12% per tahun. Berapa bunga yang wajib dibayar setahun (dalam juta), meski usaha merugi?",
        answer: 12,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Bunga = 12% x 100 = <strong>Rp12 juta</strong>, tetap wajib dibayar terlepas dari hasil usaha. Inilah yang dikritik sebagai riba.",
        hint: "Kalikan pokok pinjaman dengan tarif bunga.",
      },
      {
        type: "case",
        title: "Sejarah: Ibn Khaldun & Muqaddimah",
        html: "Jauh sebelum ilmu ekonomi modern lahir, <strong>Ibn Khaldun</strong> dalam <strong>Muqaddimah</strong> (sekitar 1377) sudah membahas pembagian kerja, mekanisme harga, peran negara, dan dampak pajak terhadap kegiatan usaha. Pemikirannya menunjukkan bahwa tradisi intelektual Islam memberi sumbangan penting bagi pemikiran ekonomi, jauh sebelum Adam Smith.",
      },
      {
        type: "takeaways",
        items: [
          "Ekonomi syariah berpijak pada Al-Quran dan Sunnah, bertujuan falah.",
          "Kerangkanya maqashid syariah: menjaga agama, jiwa, akal, keturunan, harta.",
          "Tiga larangan inti: riba, gharar, dan maysir.",
          "Sebagai ganti bunga, dipakai jual beli, sewa, dan bagi hasil yang berbagi risiko.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Tujuan akhir ekonomi syariah adalah?",
            options: ["Laba sebesar-besarnya", "Falah (kesejahteraan dunia dan akhirat)", "Menghindari pajak", "Menimbun harta"],
            answer: 1,
            explain: "Ekonomi syariah mengejar falah, kesejahteraan yang adil dunia dan akhirat.",
          },
          {
            q: "Riba secara umum berarti?",
            options: [
              "Keuntungan jual beli",
              "Tambahan tanpa imbangan yang sah, terutama bunga",
              "Sewa barang",
              "Bagi hasil usaha",
            ],
            answer: 1,
            explain: "Riba adalah tambahan tanpa imbangan yang sah, mencakup bunga pinjaman.",
          },
          {
            q: "Gharar adalah?",
            options: ["Perjudian", "Ketidakpastian berlebihan dalam akad", "Bunga", "Sedekah"],
            answer: 1,
            explain: "Gharar adalah ketidakpastian atau ketidakjelasan berlebihan dalam transaksi.",
          },
          {
            q: "Sebagai pengganti bunga, ekonomi syariah memakai?",
            options: ["Judi", "Jual beli, sewa, dan bagi hasil", "Riba terselubung", "Spekulasi"],
            answer: 1,
            explain: "Instrumen sahnya adalah jual beli, sewa (ijarah), dan bagi hasil.",
          },
          {
            q: "Maqashid syariah menjaga lima hal, kecuali?",
            options: ["Agama dan jiwa", "Akal dan keturunan", "Harta", "Kekuasaan politik"],
            answer: 3,
            explain: "Lima maqashid: agama, jiwa, akal, keturunan, dan harta.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "prinsip-dasar-ekonomi-islam",
    levelId: "dasar",
    order: 2,
    title: "Prinsip Dasar Ekonomi Islam",
    summary: "Tauhid, keadilan, manusia sebagai khalifah, harta sebagai amanah, keseimbangan, dan larangan menimbun barang.",
    durationMin: 14,
    tags: ["dasar", "tauhid", "keadilan", "khalifah", "amanah"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi Islam berdiri di atas beberapa <strong>prinsip fondasi</strong> yang membedakannya dari sistem lain. Prinsip ini bukan sekadar aturan teknis, melainkan cara pandang tentang siapa pemilik sejati harta, untuk apa harta dipakai, dan bagaimana manusia bertanggung jawab atasnya.",
      },
      {
        type: "paragraph",
        html: "Titik pusatnya adalah <strong>tauhid</strong>: keyakinan bahwa segala sesuatu, termasuk harta, pada hakikatnya milik Allah. Manusia hanya diberi amanah untuk mengelola, sehingga setiap keputusan ekonomi terikat pada tanggung jawab moral.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tauhid: semua milik Allah",
        html: "Dalam pandangan Islam, harta adalah <strong>amanah</strong>, bukan milik mutlak manusia. Kesadaran ini melahirkan sikap tidak rakus, jujur dalam usaha, dan peduli pada sesama, karena semua akan dipertanggungjawabkan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Keadilan ('adl) dan keseimbangan (tawazun)",
        html: "<strong>Keadilan</strong> menuntut setiap pihak memperoleh hak secara wajar tanpa zalim. <strong>Keseimbangan</strong> menuntut keselarasan antara kepentingan pribadi dan sosial, dunia dan akhirat, materi dan spiritual.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Larangan menimbun (ihtikar)",
        html: "Menimbun barang kebutuhan pokok untuk menaikkan harga saat langka disebut <strong>ihtikar</strong> dan dilarang. Ia merugikan masyarakat dan merusak keadilan pasar.",
      },
      {
        type: "video",
        comp: "LaranganRibaVideo",
        title: "Video: Mengapa Harta Adalah Amanah",
        caption: "Prinsip tauhid menjadikan setiap transaksi terikat tanggung jawab moral.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat bagaimana prinsip keadilan berbagi risiko bekerja saat usaha untung maupun rugi.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "case",
        title: "Studi Kasus: Pedagang menimbun beras saat langka",
        html: "Ketika pasokan beras menipis, seorang pedagang membeli dan menyimpan stok besar agar harga melonjak, lalu menjualnya mahal. Praktik <strong>ihtikar</strong> ini dilarang karena mengambil untung dari penderitaan orang banyak. Prinsip keadilan menuntut barang tetap mengalir dengan harga wajar, bukan ditahan demi keuntungan sepihak.",
      },
      {
        type: "case",
        title: "Sejarah: Pasar Madinah masa Nabi (abad 7 M)",
        html: "Saat sebagian sahabat meminta Nabi Muhammad menetapkan harga karena melonjak, beliau menolak dan menyatakan bahwa <strong>Allah-lah yang menentukan harga</strong>. Nabi menekankan pasar yang jujur, melarang penipuan takaran dan penimbunan, serta menugaskan pengawas pasar (kelak dikenal sebagai <strong>hisbah</strong>). Sikap ini menunjukkan penghargaan pada mekanisme pasar yang adil, bukan penetapan harga sewenang-wenang.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan perilaku berikut sesuai prinsipnya.",
        buckets: ["Sesuai prinsip Islam", "Melanggar prinsip Islam"],
        items: [
          { text: "Menjual dengan takaran jujur", bucket: "Sesuai prinsip Islam" },
          { text: "Menimbun sembako agar harga naik", bucket: "Melanggar prinsip Islam" },
          { text: "Menyisihkan sebagian harta untuk sedekah", bucket: "Sesuai prinsip Islam" },
          { text: "Menzalimi pekerja dengan upah tak wajar", bucket: "Melanggar prinsip Islam" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Pedagang menimbun beras yang dibeli seharga Rp10.000/kg lalu menjualnya Rp16.000/kg saat langka. Berapa persen kenaikan harga yang ia paksakan?",
        answer: 60,
        tolerance: 1,
        suffix: "%",
        solution: "Kenaikan = (16.000 - 10.000) / 10.000 x 100% = 6.000/10.000 x 100% = <strong>60%</strong>. Keuntungan dari kelangkaan yang ditahan sengaja inilah yang dilarang sebagai ihtikar.",
        hint: "Selisih harga dibagi harga awal, lalu dikali 100%.",
      },
      {
        type: "takeaways",
        items: [
          "Tauhid menempatkan Allah sebagai pemilik sejati; harta adalah amanah.",
          "Manusia berperan sebagai khalifah, pengelola yang bertanggung jawab.",
          "Keadilan dan keseimbangan menuntut keselarasan hak pribadi dan sosial.",
          "Menimbun barang pokok (ihtikar) dilarang karena merusak keadilan.",
          "Pasar Madinah masa Nabi menolak penetapan harga sewenang-wenang.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Prinsip tauhid dalam ekonomi Islam berarti?",
            options: ["Harta milik mutlak manusia", "Segala sesuatu pada hakikatnya milik Allah", "Negara memiliki semua harta", "Harta tak boleh dimiliki"],
            answer: 1,
            explain: "Tauhid menegaskan Allah sebagai pemilik sejati; manusia hanya diberi amanah.",
          },
          {
            q: "Peran manusia atas harta disebut?",
            options: ["Pemilik mutlak", "Khalifah (pengelola yang bertanggung jawab)", "Penonton", "Penimbun"],
            answer: 1,
            explain: "Manusia adalah khalifah, pengelola amanah yang akan dimintai pertanggungjawaban.",
          },
          {
            q: "Ihtikar adalah?",
            options: ["Sedekah", "Menimbun barang pokok agar harga naik", "Jual beli jujur", "Bagi hasil"],
            answer: 1,
            explain: "Ihtikar adalah penimbunan barang kebutuhan untuk menaikkan harga, dan dilarang.",
          },
          {
            q: "Ketika diminta menetapkan harga yang melonjak, Nabi Muhammad?",
            options: ["Langsung menetapkan harga", "Menolak dan menekankan pasar yang jujur", "Menutup pasar", "Menaikkan pajak"],
            answer: 1,
            explain: "Nabi menolak menetapkan harga sewenang-wenang dan menekankan pasar yang adil dan jujur.",
          },
          {
            q: "Tawazun dalam ekonomi Islam berarti?",
            options: ["Menimbun harta", "Keseimbangan antara kepentingan pribadi dan sosial", "Bunga majemuk", "Spekulasi"],
            answer: 1,
            explain: "Tawazun adalah keseimbangan, termasuk antara kepentingan pribadi dan sosial.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "riba-gharar-maysir",
    levelId: "dasar",
    order: 3,
    title: "Memahami Riba, Gharar & Maysir",
    summary: "Tiga larangan inti: riba (nasiah dan fadl), gharar (ketidakpastian akad), dan maysir (judi/spekulasi).",
    durationMin: 15,
    tags: ["dasar", "riba", "gharar", "maysir"],
    blocks: [
      {
        type: "paragraph",
        html: "Tiga larangan menjadi pagar utama transaksi syariah: <strong>riba</strong>, <strong>gharar</strong>, dan <strong>maysir</strong>. Ketiganya dilarang karena sama-sama membuka pintu ketidakadilan dan mengambil harta orang lain secara batil.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Dua jenis riba",
        html: "<strong>Riba nasiah</strong>: tambahan yang dikenakan atas pinjaman karena tempo waktu, inti dari bunga. <strong>Riba fadl</strong>: tukar-menukar barang ribawi sejenis dalam jumlah tak setara, misalnya menukar 1 kg kurma bagus dengan 2 kg kurma jelek.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Gharar: ketidakpastian berlebihan",
        html: "<strong>Gharar</strong> muncul saat objek, harga, atau penyerahan tidak jelas. Contoh: menjual barang yang belum ada atau belum dimiliki, atau menjual ikan yang masih berenang di laut.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Maysir: judi dan spekulasi murni",
        html: "<strong>Maysir</strong> adalah memperoleh harta bergantung untung-untungan tanpa usaha nyata, di mana satu pihak untung mutlak dari kerugian pihak lain. Judi dan taruhan adalah contoh paling jelas.",
      },
      {
        type: "video",
        comp: "LaranganRibaVideo",
        title: "Video: Mengapa Riba Dilarang",
        caption: "Bunga menuntut tambahan atas waktu tanpa berbagi risiko usaha.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan beban riba yang tetap dengan bagi hasil yang menyesuaikan hasil usaha.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "chart",
        variant: "line",
        title: "Bunga Majemuk vs Pokok Tetap (ilustrasi matematis)",
        unit: "nilai utang (juta rupiah)",
        source: "ilustrasi matematis akurat, bunga 20% per tahun atas pokok Rp10 juta",
        note: "Bunga majemuk membuat utang membengkak jauh melampaui pokok seiring waktu, inti kritik terhadap riba.",
        data: [
          { label: "Tahun 0", value: 10, color: "#ef4444" },
          { label: "Tahun 2", value: 14.4, color: "#ef4444" },
          { label: "Tahun 4", value: 20.7, color: "#dc2626" },
          { label: "Tahun 6", value: 29.9, color: "#b91c1c" },
          { label: "Tahun 8", value: 43.0, color: "#991b1b" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Menukar emas tak setara (riba fadl)",
        html: "Seseorang menukar 5 gram emas 24 karat dengan 6 gram emas 18 karat dengan alasan berat lebih banyak. Meski beratnya berbeda, ini tergolong <strong>riba fadl</strong> karena emas ditukar emas harus sama takaran dan tunai. Solusinya: jual emas lama dengan uang, lalu beli emas baru dengan uang, sehingga nilai wajar terbentuk lewat harga.",
      },
      {
        type: "case",
        title: "Sejarah: Pelarangan riba yang bertahap",
        html: "Larangan riba dalam Al-Quran turun secara <strong>bertahap</strong>. Mula-mula riba dinilai tak menambah keberkahan (QS Ar-Rum), lalu diingatkan lewat kisah kaum terdahulu (QS An-Nisa), kemudian dilarang riba yang berlipat ganda (QS Ali Imran), dan akhirnya diharamkan tegas dengan penegasan hanya boleh mengambil pokok (QS Al-Baqarah 275-279). Pola bertahap ini mengubah kebiasaan masyarakat secara bijak, bukan mendadak.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan contohnya.",
        pairs: [
          { left: "Riba nasiah", right: "Bunga tetap atas pinjaman uang" },
          { left: "Riba fadl", right: "Tukar 1 kg kurma bagus dengan 2 kg kurma jelek" },
          { left: "Gharar", right: "Menjual ikan yang masih di laut" },
          { left: "Maysir", right: "Taruhan pada hasil pertandingan" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Utang Rp10 juta dengan bunga majemuk 20% per tahun. Berapa nilai utang setelah 2 tahun (dalam juta)?",
        answer: 14.4,
        tolerance: 0.1,
        prefix: "Rp",
        suffix: " juta",
        solution: "Nilai = 10 x (1 + 0,20)^2 = 10 x 1,44 = <strong>Rp14,4 juta</strong>. Tambahan Rp4,4 juta murni dari waktu, tanpa berbagi risiko usaha, inilah riba nasiah.",
        hint: "Gunakan rumus bunga majemuk: pokok x (1 + i)^n.",
      },
      {
        type: "takeaways",
        items: [
          "Riba nasiah adalah tambahan atas waktu (bunga); riba fadl atas tukar barang ribawi tak setara.",
          "Gharar adalah ketidakpastian berlebihan pada objek, harga, atau penyerahan.",
          "Maysir adalah untung-untungan tanpa usaha nyata, seperti judi.",
          "Ketiganya dilarang karena membuka ketidakadilan.",
          "Larangan riba dalam Al-Quran turun secara bertahap.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Riba nasiah adalah?",
            options: ["Tukar barang tak setara", "Tambahan atas pinjaman karena tempo waktu", "Sedekah", "Bagi hasil"],
            answer: 1,
            explain: "Riba nasiah adalah tambahan yang dikenakan karena penundaan waktu, inti dari bunga.",
          },
          {
            q: "Menukar 1 kg kurma bagus dengan 2 kg kurma jelek termasuk?",
            options: ["Riba fadl", "Gharar", "Maysir", "Jual beli sah"],
            answer: 0,
            explain: "Tukar barang ribawi sejenis dalam jumlah tak setara adalah riba fadl.",
          },
          {
            q: "Menjual ikan yang masih berenang di laut termasuk?",
            options: ["Riba", "Gharar (ketidakpastian)", "Sedekah", "Ijarah"],
            answer: 1,
            explain: "Objek yang belum jelas dan belum dikuasai menimbulkan gharar.",
          },
          {
            q: "Maysir paling tepat dicontohkan oleh?",
            options: ["Jual beli tunai", "Sewa rumah", "Taruhan atau judi", "Bagi hasil usaha"],
            answer: 2,
            explain: "Maysir adalah untung-untungan tanpa usaha nyata, seperti taruhan dan judi.",
          },
          {
            q: "Larangan riba dalam Al-Quran turun secara?",
            options: ["Sekaligus di awal", "Bertahap dalam beberapa ayat", "Tidak pernah ada", "Hanya dalam Sunnah"],
            answer: 1,
            explain: "Larangan riba turun bertahap hingga penegasan di QS Al-Baqarah 275-279.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "maqashid-syariah",
    levelId: "dasar",
    order: 4,
    title: "Maqashid Syariah & Maslahah",
    summary: "Lima tujuan syariah (agama, jiwa, akal, keturunan, harta), konsep maslahah, dan tingkatan dharuriyat, hajiyat, tahsiniyat.",
    durationMin: 14,
    tags: ["dasar", "maqashid", "maslahah", "tujuan"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Maqashid syariah</strong> adalah tujuan-tujuan yang hendak dicapai oleh aturan Islam. Memahaminya membuat kita mengerti <em>mengapa</em> sebuah aturan ada, bukan sekadar menghafal boleh atau tidak boleh.",
      },
      {
        type: "paragraph",
        html: "Inti dari maqashid adalah mewujudkan <strong>maslahah</strong>, yaitu kemaslahatan atau kebaikan bagi manusia, sekaligus menolak kerusakan (mafsadah). Setiap kebijakan ekonomi syariah dinilai dari sejauh mana ia melindungi kemaslahatan.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Lima tujuan (kulliyat al-khams)",
        html: "Syariah bertujuan menjaga lima hal pokok: <strong>agama</strong> (din), <strong>jiwa</strong> (nafs), <strong>akal</strong> ('aql), <strong>keturunan</strong> (nasl), dan <strong>harta</strong> (mal). Aturan ekonomi seperti larangan riba dan kewajiban zakat sebenarnya menjaga harta dan kemaslahatan bersama.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tiga tingkatan kebutuhan",
        html: "<strong>Dharuriyat</strong> (primer): tanpanya kehidupan rusak, seperti pangan dan keamanan. <strong>Hajiyat</strong> (sekunder): mempermudah dan menghilangkan kesulitan. <strong>Tahsiniyat</strong> (tersier): penyempurna dan keindahan. Prioritas selalu mendahulukan yang primer.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Ketimpangan yang ekstrem mengancam maslahah. Coba lihat bagaimana distribusi memengaruhi ukuran ketimpangan.",
      },
      {
        type: "video",
        comp: "ZiswafVideo",
        title: "Video: Zakat, Infak, Sedekah, Wakaf",
        caption: "Instrumen distribusi yang menjaga kemaslahatan harta bagi semua.",
      },
      { type: "widget", widget: "KalkulatorGini" },
      {
        type: "case",
        title: "Studi Kasus: Menyusun prioritas anggaran keluarga",
        html: "Sebuah keluarga dengan dana terbatas mendahulukan <strong>pangan, tempat tinggal, dan pendidikan anak</strong> (dharuriyat), baru kendaraan yang mempermudah kerja (hajiyat), lalu perabot mewah (tahsiniyat). Kerangka maqashid membantu memutuskan mana yang tak boleh dikorbankan saat dana menipis.",
      },
      {
        type: "case",
        title: "Sejarah: Al-Ghazali merumuskan maqashid (abad 11-12)",
        html: "Imam <strong>Al-Ghazali</strong> (1058-1111) dalam kitab <strong>Al-Mustashfa</strong> merumuskan secara sistematis kelima tujuan syariah: menjaga agama, jiwa, akal, keturunan, dan harta. Rumusan ini kemudian diperkaya ulama seperti Asy-Syatibi (wafat 1388) dan menjadi kerangka baku yang dipakai hingga kini untuk menilai kemaslahatan sebuah kebijakan.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan kebutuhan berikut menurut tingkatannya.",
        buckets: ["Dharuriyat", "Hajiyat", "Tahsiniyat"],
        items: [
          { text: "Makanan pokok sehari-hari", bucket: "Dharuriyat" },
          { text: "Kendaraan untuk mempermudah bekerja", bucket: "Hajiyat" },
          { text: "Perhiasan dan dekorasi mewah", bucket: "Tahsiniyat" },
          { text: "Keamanan jiwa dan tempat tinggal", bucket: "Dharuriyat" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Dari lima tujuan maqashid syariah, berapa banyak yang tergolong pokok (kulliyat al-khams)?",
        answer: 5,
        tolerance: 0,
        solution: "Kulliyat al-khams berarti lima yang pokok: agama, jiwa, akal, keturunan, dan harta. Jadi ada <strong>5</strong>.",
        hint: "Al-khams artinya lima.",
      },
      {
        type: "takeaways",
        items: [
          "Maqashid syariah adalah tujuan aturan Islam, intinya mewujudkan maslahah.",
          "Lima tujuan pokok: menjaga agama, jiwa, akal, keturunan, dan harta.",
          "Tiga tingkatan: dharuriyat (primer), hajiyat (sekunder), tahsiniyat (tersier).",
          "Prioritas mendahulukan yang primer saat sumber daya terbatas.",
          "Al-Ghazali merumuskan maqashid secara sistematis pada abad 11-12.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Inti tujuan maqashid syariah adalah mewujudkan?",
            options: ["Keuntungan maksimal", "Maslahah (kemaslahatan)", "Kekuasaan", "Penimbunan"],
            answer: 1,
            explain: "Maqashid bertujuan mewujudkan maslahah dan menolak kerusakan (mafsadah).",
          },
          {
            q: "Yang termasuk lima tujuan pokok maqashid adalah?",
            options: ["Agama, jiwa, akal, keturunan, harta", "Uang, tanah, emas, rumah, saham", "Perdagangan saja", "Politik dan militer"],
            answer: 0,
            explain: "Kulliyat al-khams: agama, jiwa, akal, keturunan, dan harta.",
          },
          {
            q: "Kebutuhan primer yang tanpanya kehidupan rusak disebut?",
            options: ["Tahsiniyat", "Hajiyat", "Dharuriyat", "Maysir"],
            answer: 2,
            explain: "Dharuriyat adalah kebutuhan primer yang harus dipenuhi lebih dulu.",
          },
          {
            q: "Ulama yang merumuskan maqashid secara sistematis pada abad 11-12 adalah?",
            options: ["Adam Smith", "Al-Ghazali", "Ibn Sina", "Al-Khawarizmi"],
            answer: 1,
            explain: "Al-Ghazali (1058-1111) merumuskan lima tujuan syariah dalam Al-Mustashfa.",
          },
          {
            q: "Saat dana terbatas, prioritas didahulukan untuk?",
            options: ["Tahsiniyat", "Dharuriyat", "Barang mewah", "Hiburan"],
            answer: 1,
            explain: "Yang primer (dharuriyat) selalu didahulukan atas sekunder dan tersier.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "uang-dalam-islam",
    levelId: "dasar",
    order: 5,
    title: "Konsep Uang dalam Islam",
    summary: "Uang sebagai alat tukar dan satuan nilai, bukan komoditas yang disewakan, serta sejarah dinar dan dirham.",
    durationMin: 14,
    tags: ["dasar", "uang", "dinar", "dirham", "riba"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam Islam, <strong>uang</strong> berfungsi sebagai <strong>alat tukar</strong> dan <strong>satuan nilai</strong>, alat untuk memudahkan pertukaran barang dan jasa. Uang bukan barang yang punya nilai pada dirinya untuk diperjualbelikan demi keuntungan dari waktu.",
      },
      {
        type: "paragraph",
        html: "Karena uang hanya alat ukur, ia <strong>bukan komoditas yang bisa disewakan</strong>. Menyewakan uang dan menuntut tambahan tetap atas waktu adalah inti dari riba. Inilah dasar konseptual mengapa bunga dilarang.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Uang bukan komoditas",
        html: "Barang bisa disewa karena punya manfaat yang tetap ada meski dipakai, misalnya rumah atau mobil. Uang habis saat dipakai (dibelanjakan), sehingga menuntut sewa atasnya (bunga) dianggap tidak adil dan tergolong <strong>riba</strong>.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Dinar dan dirham",
        html: "Peradaban Islam memakai <strong>dinar</strong> (koin emas) dan <strong>dirham</strong> (koin perak) sebagai uang. Karena nilainya melekat pada logam mulia, keduanya relatif stabil dibanding uang kertas yang nilainya bisa tergerus inflasi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Bahaya menjadikan uang barang dagangan",
        html: "Ketika uang diperlakukan sebagai komoditas yang menghasilkan uang lagi lewat bunga, kekayaan menumpuk pada pemilik modal tanpa produksi nyata. Islam mendorong uang mengalir ke sektor riil lewat jual beli, sewa, dan bagi hasil.",
      },
      {
        type: "video",
        comp: "LaranganRibaVideo",
        title: "Video: Uang, Waktu, dan Riba",
        caption: "Mengapa menuntut tambahan atas waktu meminjam uang dianggap tidak adil.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Lihat perbedaan saat uang menuntut bunga tetap versus saat modal ikut berbagi risiko usaha.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "chart",
        variant: "area",
        title: "Daya Beli Uang Kertas Tergerus Inflasi (ilustrasi)",
        unit: "daya beli relatif (%)",
        source: "ilustrasi konsep inflasi 5% per tahun",
        note: "Uang kertas kehilangan daya beli seiring inflasi, sementara nilai logam mulia cenderung lebih terjaga. Ini konteks daya tarik dinar-dirham.",
        data: [
          { label: "Tahun 0", value: 100, color: "#f59e0b" },
          { label: "Tahun 5", value: 78, color: "#f59e0b" },
          { label: "Tahun 10", value: 61, color: "#d97706" },
          { label: "Tahun 15", value: 48, color: "#b45309" },
          { label: "Tahun 20", value: 38, color: "#92400e" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Meminjamkan uang vs menyewakan mobil",
        html: "Pak Budi menyewakan <strong>mobil</strong> Rp200 ribu/hari, sah karena mobil punya manfaat yang tetap ada meski dipakai lalu dikembalikan utuh. Namun bila Pak Budi meminjamkan <strong>uang</strong> Rp10 juta dan menuntut kembali Rp11 juta, tambahan Rp1 juta itu adalah riba, sebab uang habis saat dibelanjakan dan tak melahirkan manfaat sewa yang sah.",
      },
      {
        type: "case",
        title: "Sejarah: Standar dinar-dirham dalam peradaban Islam",
        html: "Pada masa Khalifah <strong>Abdul Malik bin Marwan</strong> (sekitar 696 M), negara Islam mencetak <strong>dinar emas</strong> dan <strong>dirham perak</strong> sendiri dengan standar berat yang baku (dinar sekitar 4,25 gram emas, dirham sekitar 2,975 gram perak). Standar ini memberi kestabilan nilai dan memperlancar perdagangan lintas wilayah selama berabad-abad.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan keterangannya.",
        pairs: [
          { left: "Dinar", right: "Koin emas" },
          { left: "Dirham", right: "Koin perak" },
          { left: "Fungsi uang", right: "Alat tukar dan satuan nilai" },
          { left: "Sewa uang dengan bunga", right: "Tergolong riba" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Uang senilai daya beli 100 tergerus inflasi 5% per tahun. Berapa daya belinya (dibulatkan) setelah 2 tahun?",
        answer: 90.25,
        tolerance: 0.5,
        solution: "Daya beli = 100 x (1 - 0,05)^2 = 100 x 0,9025 = <strong>90,25</strong>. Uang kertas kehilangan daya beli seiring inflasi.",
        hint: "Kalikan dengan (1 - 0,05) sebanyak dua kali.",
      },
      {
        type: "takeaways",
        items: [
          "Uang adalah alat tukar dan satuan nilai, bukan komoditas.",
          "Menyewakan uang dan menuntut tambahan tetap atas waktu adalah riba.",
          "Dinar (emas) dan dirham (perak) adalah mata uang peradaban Islam.",
          "Uang kertas tergerus inflasi; logam mulia relatif lebih stabil.",
          "Islam mendorong uang mengalir ke sektor riil lewat jual beli, sewa, dan bagi hasil.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Fungsi utama uang dalam Islam adalah?",
            options: ["Komoditas yang disewakan", "Alat tukar dan satuan nilai", "Sumber bunga", "Barang spekulasi"],
            answer: 1,
            explain: "Uang berfungsi sebagai alat tukar dan satuan nilai, bukan barang dagangan.",
          },
          {
            q: "Mengapa menyewakan uang dengan tambahan tetap dilarang?",
            options: ["Karena uang mahal", "Karena uang habis saat dipakai, tambahan atas waktu itu riba", "Karena dilarang negara", "Karena tidak praktis"],
            answer: 1,
            explain: "Uang habis saat dibelanjakan; menuntut tambahan tetap atas waktu tergolong riba.",
          },
          {
            q: "Dinar dalam peradaban Islam terbuat dari?",
            options: ["Perak", "Emas", "Tembaga", "Kertas"],
            answer: 1,
            explain: "Dinar adalah koin emas, sedangkan dirham adalah koin perak.",
          },
          {
            q: "Khalifah yang membakukan pencetakan dinar-dirham (sekitar 696 M) adalah?",
            options: ["Umar bin Khattab", "Abdul Malik bin Marwan", "Harun Al-Rasyid", "Ali bin Abi Thalib"],
            answer: 1,
            explain: "Abdul Malik bin Marwan membakukan standar berat dinar emas dan dirham perak.",
          },
          {
            q: "Dibanding logam mulia, uang kertas cenderung?",
            options: ["Lebih stabil nilainya", "Tergerus daya belinya oleh inflasi", "Tak terpengaruh apa pun", "Selalu naik nilainya"],
            answer: 1,
            explain: "Uang kertas kehilangan daya beli seiring inflasi; logam mulia relatif lebih terjaga.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "kepemilikan-dan-harta",
    levelId: "dasar",
    order: 6,
    title: "Kepemilikan & Etika Harta",
    summary: "Tiga jenis kepemilikan (pribadi, umum, negara), mencari harta halal dan thayyib, serta kewajiban sosial atas harta.",
    durationMin: 14,
    tags: ["dasar", "kepemilikan", "halal", "harta", "sosial"],
    blocks: [
      {
        type: "paragraph",
        html: "Islam mengakui <strong>kepemilikan pribadi</strong>, tetapi tidak menjadikannya mutlak. Ada harta yang menjadi <strong>milik umum</strong> dan ada yang dikelola <strong>negara</strong> demi kemaslahatan bersama. Kepemilikan selalu disertai tanggung jawab.",
      },
      {
        type: "paragraph",
        html: "Bukan hanya cara memperoleh yang diatur, tetapi juga sifat hartanya. Harta harus <strong>halal</strong> (cara dan sumbernya sah) dan <strong>thayyib</strong> (baik, tidak merugikan). Di dalam harta pribadi pun melekat <strong>hak orang lain</strong> lewat zakat dan sedekah.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga jenis kepemilikan",
        html: "<strong>Pribadi</strong>: hasil usaha halal, boleh dimiliki dan dikembangkan. <strong>Umum</strong>: sumber daya yang dibutuhkan banyak orang seperti air, api (energi), dan padang rumput, tak boleh dikuasai perorangan. <strong>Negara</strong>: harta yang dikelola pemerintah untuk kepentingan publik.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Halal dan thayyib",
        html: "<strong>Halal</strong> menyangkut keabsahan cara memperoleh (bukan mencuri, menipu, atau riba). <strong>Thayyib</strong> menyangkut kebaikan zat dan dampaknya. Keduanya harus dipenuhi bersama.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Hak sosial dalam harta",
        html: "Islam menolak penumpukan harta yang mengabaikan sesama. Dalam setiap harta ada <strong>hak orang lain</strong> yang wajib ditunaikan lewat zakat, dan dianjurkan lewat infak serta sedekah.",
      },
      {
        type: "video",
        comp: "ZiswafVideo",
        title: "Video: Menunaikan Hak Sosial atas Harta",
        caption: "Zakat, infak, sedekah, dan wakaf mengalirkan kembali harta kepada yang berhak.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Distribusi harta yang timpang menandakan hak sosial belum mengalir. Coba lihat ukuran ketimpangannya.",
      },
      { type: "widget", widget: "KalkulatorGini" },
      {
        type: "case",
        title: "Studi Kasus: Sumber air desa dikuasai satu orang",
        html: "Seorang pengusaha ingin memagari mata air satu-satunya di sebuah desa dan menjual airnya mahal. Dalam Islam, <strong>air</strong> termasuk milik umum yang tak boleh dimonopoli perorangan bila menjadi hajat orang banyak. Sumber daya vital seperti air, energi, dan padang gembala harus tetap dapat diakses masyarakat.",
      },
      {
        type: "case",
        title: "Sejarah: Pengelolaan tanah dan sumber daya masa khalifah awal",
        html: "Pada masa Khalifah <strong>Umar bin Khattab</strong> (memerintah 634-644 M), tanah taklukan yang subur di Irak dan sekitarnya tidak dibagikan habis kepada pasukan, melainkan dibiarkan digarap penduduk dengan kewajiban pajak (kharaj), agar manfaatnya mengalir ke generasi berikutnya dan kas negara. Nabi juga menegaskan manusia berserikat dalam tiga hal: <strong>air, padang rumput, dan api (energi)</strong>. Prinsip ini menjaga sumber daya publik tetap milik bersama.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan menurut jenis kepemilikannya.",
        buckets: ["Milik pribadi", "Milik umum", "Milik negara"],
        items: [
          { text: "Gaji hasil bekerja", bucket: "Milik pribadi" },
          { text: "Sungai dan mata air", bucket: "Milik umum" },
          { text: "Padang rumput penggembalaan bersama", bucket: "Milik umum" },
          { text: "Kas dan aset pemerintah untuk publik", bucket: "Milik negara" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Seseorang memiliki tabungan Rp50 juta yang telah mencapai haul dan nisab. Berapa zakat maal 2,5% yang wajib ia keluarkan (dalam juta)?",
        answer: 1.25,
        tolerance: 0.01,
        prefix: "Rp",
        suffix: " juta",
        solution: "Zakat maal = 2,5% x 50 = <strong>Rp1,25 juta</strong>. Inilah hak orang lain yang melekat dalam harta.",
        hint: "Kalikan harta dengan 2,5% (0,025).",
      },
      {
        type: "takeaways",
        items: [
          "Islam mengakui kepemilikan pribadi, tetapi tidak mutlak.",
          "Ada tiga jenis kepemilikan: pribadi, umum, dan negara.",
          "Sumber daya vital (air, energi, padang rumput) adalah milik umum.",
          "Harta harus halal (cara) dan thayyib (baik dan berdampak baik).",
          "Dalam harta pribadi melekat hak sosial lewat zakat dan sedekah.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Kepemilikan pribadi dalam Islam bersifat?",
            options: ["Mutlak tanpa batas", "Diakui tetapi disertai tanggung jawab", "Dilarang", "Hanya untuk negara"],
            answer: 1,
            explain: "Kepemilikan pribadi diakui namun tidak mutlak; ada hak sosial dan batasan.",
          },
          {
            q: "Menurut Islam, manusia berserikat dalam tiga hal, yaitu?",
            options: ["Emas, perak, uang", "Air, padang rumput, dan api (energi)", "Rumah, tanah, kendaraan", "Saham, obligasi, deposito"],
            answer: 1,
            explain: "Nabi menegaskan manusia berserikat dalam air, padang rumput, dan api (energi).",
          },
          {
            q: "Harta yang halal dan thayyib berarti?",
            options: ["Banyak jumlahnya", "Sah caranya dan baik zat serta dampaknya", "Milik negara", "Bebas pajak"],
            answer: 1,
            explain: "Halal menyangkut keabsahan cara, thayyib menyangkut kebaikan zat dan dampak.",
          },
          {
            q: "Memonopoli satu-satunya mata air desa dan menjualnya mahal?",
            options: ["Boleh karena hak pribadi", "Bertentangan karena air termasuk milik umum", "Dianjurkan", "Wajib"],
            answer: 1,
            explain: "Air adalah milik umum yang tak boleh dimonopoli bila menjadi hajat orang banyak.",
          },
          {
            q: "Zakat maal atas tabungan yang mencukupi syarat besarnya?",
            options: ["10%", "5%", "2,5%", "20%"],
            answer: 2,
            explain: "Zakat maal atas harta seperti tabungan adalah 2,5% bila mencapai nisab dan haul.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "ekonomi-syariah-vs-konvensional",
    levelId: "dasar",
    order: 7,
    title: "Ekonomi Syariah vs Konvensional",
    summary: "Perbedaan cara pandang (tauhid vs sekuler), tujuan (falah/maslahah vs utilitas maksimal), instrumen (bagi hasil vs bunga), dan peran nilai serta moral.",
    durationMin: 14,
    tags: ["dasar", "perbandingan", "worldview", "falah", "bagi hasil"],
    blocks: [
      {
        type: "paragraph",
        html: "Ekonomi syariah dan ekonomi konvensional sama-sama membahas cara manusia memenuhi kebutuhan dengan sumber daya terbatas. Bedanya bukan pada rumus atau teknik, melainkan pada <strong>cara pandang dasar</strong> (worldview) tentang siapa manusia, apa tujuan hidupnya, dan untuk apa harta dikejar.",
      },
      {
        type: "paragraph",
        html: "Ekonomi konvensional arus utama berangkat dari pandangan <strong>sekuler</strong>: nilai agama dipisahkan dari analisis, manusia diasumsikan rasional yang memaksimalkan kepuasan pribadi. Ekonomi syariah berangkat dari <strong>tauhid</strong>: harta adalah amanah Allah, dan setiap keputusan terikat tanggung jawab dunia serta akhirat.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Akar perbedaan: worldview",
        html: "Konvensional memandang manusia sebagai <strong>homo economicus</strong> yang mengejar utilitas maksimal. Syariah memandang manusia sebagai <strong>khalifah</strong> dan hamba: mengejar keuntungan boleh, tetapi dibatasi halal-haram dan tujuan <strong>falah</strong> (kesejahteraan adil dunia-akhirat).",
      },
      {
        type: "callout",
        tone: "info",
        title: "Tujuan: maslahah, bukan sekadar utilitas",
        html: "Tujuan konvensional umumnya <strong>memaksimalkan kepuasan dan laba</strong>, dengan nilai moral dianggap di luar analisis. Tujuan syariah adalah <strong>maslahah</strong>: kebaikan yang menjaga agama, jiwa, akal, keturunan, dan harta, sehingga moral menjadi bagian tak terpisahkan dari keputusan ekonomi.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Instrumen: bagi hasil vs bunga",
        html: "Instrumen utama konvensional adalah <strong>bunga</strong> (imbalan tetap atas pinjaman uang). Syariah menggantinya dengan <strong>jual beli, sewa, dan bagi hasil</strong> yang menuntut adanya risiko dan usaha nyata. Inilah beda paling praktis yang langsung terasa di produk keuangan.",
      },
      {
        type: "video",
        comp: "LaranganRibaVideo",
        title: "Video: Bunga vs Bagi Hasil",
        caption: "Mengapa syariah mengganti bunga dengan skema yang berbagi risiko dan usaha nyata.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan hasil akhir antara pinjaman berbunga tetap dan pembiayaan bagi hasil saat usaha untung maupun rugi.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "table",
        headers: ["Aspek", "Ekonomi Konvensional", "Ekonomi Syariah"],
        rows: [
          ["Cara pandang", "Sekuler, nilai agama dipisah", "Tauhid, harta adalah amanah"],
          ["Tujuan akhir", "Utilitas dan laba maksimal", "Falah dan maslahah"],
          ["Kedudukan manusia", "Homo economicus", "Khalifah dan hamba"],
          ["Instrumen imbalan", "Bunga (riba)", "Bagi hasil, jual beli, sewa"],
          ["Peran moral", "Di luar analisis", "Menyatu dalam keputusan"],
          ["Kepemilikan", "Mutlak pada individu", "Amanah, disertai hak sosial"],
        ],
        caption: "Perbedaan inti tampak pada landasan nilai, bukan sekadar teknik.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Hasil Bersih Pemodal: Bunga Tetap vs Bagi Hasil (ilustrasi)",
        unit: "hasil bersih pemodal (juta rupiah)",
        source: "ilustrasi matematis: modal Rp100 juta, bunga 12%, nisbah bagi hasil 50:50",
        note: "Bunga memberi hasil tetap apa pun kondisi usaha; bagi hasil ikut naik saat untung besar dan ikut turun saat rugi, sehingga risiko dibagi lebih adil.",
        data: [
          { label: "Rugi (bunga)", value: 12, color: "#ef4444" },
          { label: "Rugi (bagi hasil)", value: -10, color: "#059669" },
          { label: "Untung besar (bunga)", value: 12, color: "#ef4444" },
          { label: "Untung besar (bagi hasil)", value: 20, color: "#10b981" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Dua bank membiayai usaha yang sama",
        html: "Bu Sari butuh Rp100 juta untuk usaha katering. <strong>Bank konvensional</strong> memberi kredit bunga 12%, sehingga apa pun hasil usahanya, Bu Sari wajib membayar Rp12 juta bunga. <strong>Bank syariah</strong> memakai <strong>mudharabah</strong> nisbah 50:50: bila laba usaha Rp40 juta, bank menerima Rp20 juta; bila usaha rugi karena musibah (bukan kelalaian), bank ikut menanggung kerugian. Instrumen syariah mengaitkan imbalan dengan risiko dan hasil nyata.",
      },
      {
        type: "case",
        title: "Sejarah: Konferensi Internasional Ekonomi Islam pertama di Makkah 1976",
        html: "<strong>Konferensi Internasional Ekonomi Islam yang pertama</strong> diselenggarakan di <strong>Makkah pada 1976</strong> oleh King Abdulaziz University. Pertemuan ini mempertemukan ekonom, ahli fikih, dan cendekiawan Muslim untuk pertama kalinya secara sistematis merumuskan ekonomi Islam sebagai disiplin ilmu modern. Peristiwa ini dianggap menandai <strong>kebangkitan ekonomi Islam modern</strong>, dan menjadi cikal bakal berkembangnya lembaga keuangan syariah serta kajian akademis di berbagai negara.",
      },
      {
        type: "classifyExercise",
        prompt: "Ciri berikut lebih tepat menggambarkan sistem yang mana?",
        buckets: ["Ekonomi Konvensional", "Ekonomi Syariah"],
        items: [
          { text: "Imbalan pinjaman berupa bunga tetap", bucket: "Ekonomi Konvensional" },
          { text: "Pembiayaan lewat bagi hasil (mudharabah)", bucket: "Ekonomi Syariah" },
          { text: "Nilai moral dipisahkan dari analisis", bucket: "Ekonomi Konvensional" },
          { text: "Tujuan akhir adalah falah dan maslahah", bucket: "Ekonomi Syariah" },
          { text: "Harta dipandang sebagai amanah dengan hak sosial", bucket: "Ekonomi Syariah" },
          { text: "Manusia diasumsikan homo economicus", bucket: "Ekonomi Konvensional" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Modal Rp100 juta. Skema bunga menuntut 12% tetap; skema bagi hasil nisbah 50:50 atas laba usaha Rp40 juta. Berapa selisih hasil pemodal (bagi hasil dikurangi bunga, dalam juta) saat usaha untung?",
        answer: 8,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Bunga = 12% x 100 = Rp12 juta. Bagi hasil = 50% x 40 = Rp20 juta. Selisih = 20 - 12 = <strong>Rp8 juta</strong>. Saat usaha untung besar, pemodal bagi hasil menerima lebih banyak karena ikut menanggung risiko.",
        hint: "Hitung hasil bunga (12% x 100) dan hasil bagi hasil (50% x 40), lalu kurangkan.",
      },
      {
        type: "takeaways",
        items: [
          "Beda utama bukan pada teknik, melainkan cara pandang: tauhid vs sekuler.",
          "Tujuan syariah adalah falah dan maslahah, bukan sekadar utilitas dan laba maksimal.",
          "Instrumen bunga diganti dengan bagi hasil, jual beli, dan sewa yang berbagi risiko.",
          "Dalam syariah, nilai moral menyatu dalam keputusan ekonomi, bukan di luarnya.",
          "Konferensi Ekonomi Islam pertama di Makkah 1976 menandai kebangkitan ekonomi Islam modern.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Akar perbedaan ekonomi syariah dan konvensional terletak pada?",
            options: ["Rumus matematikanya", "Cara pandang dasar (worldview)", "Jenis mata uang", "Jumlah bank"],
            answer: 1,
            explain: "Bedanya bukan teknik, melainkan worldview: tauhid pada syariah vs sekuler pada konvensional.",
          },
          {
            q: "Tujuan akhir ekonomi syariah adalah?",
            options: ["Utilitas dan laba maksimal", "Falah dan maslahah", "Menghindari pajak", "Menumpuk modal"],
            answer: 1,
            explain: "Syariah mengejar falah dan maslahah, sedangkan konvensional menekankan utilitas dan laba maksimal.",
          },
          {
            q: "Sebagai ganti bunga, ekonomi syariah memakai instrumen?",
            options: ["Spekulasi", "Bagi hasil, jual beli, dan sewa", "Bunga terselubung", "Judi"],
            answer: 1,
            explain: "Instrumen syariah menuntut risiko dan usaha nyata lewat bagi hasil, jual beli, dan sewa.",
          },
          {
            q: "Dalam ekonomi konvensional arus utama, nilai moral umumnya?",
            options: ["Menyatu dalam analisis", "Dianggap di luar analisis", "Menjadi tujuan utama", "Dilarang"],
            answer: 1,
            explain: "Konvensional cenderung memisahkan nilai moral dari analisis; syariah menyatukannya.",
          },
          {
            q: "Peristiwa yang dianggap menandai kebangkitan ekonomi Islam modern adalah?",
            options: [
              "Konferensi Internasional Ekonomi Islam pertama di Makkah 1976",
              "Krisis moneter 1998",
              "Pendirian VOC",
              "Depresi Besar 1929",
            ],
            answer: 0,
            explain: "Konferensi Internasional Ekonomi Islam pertama di Makkah pada 1976 menandai kebangkitan ekonomi Islam modern.",
          },
        ],
      },
    ],
  },
  {
    id: "etika-bisnis-islam",
    levelId: "dasar",
    order: 8,
    title: "Etika Bisnis dalam Islam",
    summary: "Kejujuran (sidq), amanah, dan keadilan sebagai fondasi bisnis; larangan menipu lewat tadlis, najsy, dan ihtikar; serta hak khiyar untuk membatalkan jual beli.",
    durationMin: 14,
    tags: ["dasar", "etika bisnis", "khiyar", "tadlis", "ihtikar"],
    blocks: [
      {
        type: "paragraph",
        html: "Dalam Islam, berdagang adalah pekerjaan mulia, tetapi keuntungan tidak boleh diraih dengan cara apa pun. Bisnis diikat oleh <strong>akhlak</strong>: apa yang dilarang di masjid juga dilarang di pasar. Karena itu setiap transaksi menuntut kejujuran, kepercayaan, dan keadilan bagi kedua pihak.",
      },
      {
        type: "paragraph",
        html: "Tiga nilai menjadi fondasi: <strong>sidq</strong> (jujur), <strong>amanah</strong> (dapat dipercaya), dan <strong>adl</strong> (adil). Dari sini lahir aturan yang melarang segala bentuk penipuan dan manipulasi, sekaligus memberi pembeli hak untuk melindungi diri.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Tiga pilar akhlak dagang",
        html: "<strong>Sidq</strong>: menyampaikan keadaan barang apa adanya. <strong>Amanah</strong>: menjaga hak orang lain seperti menjaga hak sendiri. <strong>Adl</strong>: takaran, timbangan, dan harga yang tidak merugikan salah satu pihak. Ketiganya menjadikan bisnis sebagai ibadah, bukan sekadar cari untung.",
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tiga bentuk kecurangan yang dilarang",
        html: "<strong>Tadlis</strong>: menyembunyikan cacat atau informasi barang agar pembeli tertipu. <strong>Najsy</strong>: pura-pura menawar tinggi tanpa niat membeli untuk memancing harga naik palsu. <strong>Ihtikar</strong>: menimbun barang kebutuhan agar langka lalu dijual mahal. Semuanya merusak kejujuran pasar dan diharamkan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Khiyar: hak untuk berpikir ulang",
        html: "<strong>Khiyar</strong> adalah hak memilih melanjutkan atau membatalkan jual beli. Bentuknya antara lain <strong>khiyar majlis</strong> (selama penjual dan pembeli masih di tempat akad), <strong>khiyar syarat</strong> (masa tenggang yang disepakati), dan <strong>khiyar aib</strong> (membatalkan bila menemukan cacat tersembunyi). Khiyar menjaga kerelaan kedua pihak.",
      },
      {
        type: "video",
        comp: "EtikaBisnisIslamVideo",
        title: "Video: Jujur di Pasar",
        caption: "Bagaimana sidq, amanah, dan adl mengubah transaksi biasa menjadi ibadah.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Bandingkan skema bunga tetap dengan bagi hasil untuk merasakan kembali bagaimana keadilan berbagi risiko menjadi inti etika bisnis Islam.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "chart",
        variant: "bar",
        title: "Harga Wajar vs Harga Hasil Manipulasi Pasar (ilustrasi)",
        unit: "harga per kg (ribu rupiah)",
        source: "ilustrasi edukatif: dampak najsy dan ihtikar terhadap harga sebuah komoditas",
        note: "Najsy menaikkan harga lewat penawaran palsu, sedangkan ihtikar menaikkan harga dengan menahan pasokan; keduanya mendorong harga jauh di atas harga wajar dan merugikan pembeli.",
        data: [
          { label: "Harga wajar", value: 12, color: "#10b981" },
          { label: "Setelah najsy", value: 16, color: "#f59e0b" },
          { label: "Setelah ihtikar", value: 20, color: "#ef4444" },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Cacat mesin yang disembunyikan",
        html: "Pak Budi menjual mobil bekas dan sengaja tidak memberi tahu bahwa mesinnya sering overheat, bahkan menutupi tanda kebocoran. Ini adalah <strong>tadlis</strong> (menyembunyikan cacat). Ketika pembeli menemukan cacat itu beberapa hari kemudian, ia berhak memakai <strong>khiyar aib</strong> untuk membatalkan jual beli dan meminta uangnya kembali. Islam menuntut penjual mengungkap cacat, bukan menyembunyikannya.",
      },
      {
        type: "case",
        title: "Sejarah: Al-Amin dan lembaga hisbah",
        html: "Sebelum diangkat menjadi nabi, <strong>Muhammad</strong> berdagang dan dikenal masyarakat Makkah dengan gelar <strong>Al-Amin</strong> (yang terpercaya) karena kejujuran dan amanahnya, termasuk saat menjalankan dagangan milik Khadijah. Setelah Islam berkembang, kejujuran pasar dijaga lewat lembaga <strong>hisbah</strong>: seorang <strong>muhtasib</strong> (pengawas pasar) memeriksa timbangan, mencegah penipuan, dan menindak penimbunan. Pada masa Khulafaur Rasyidin, Khalifah Umar bin Khattab bahkan menugaskan pengawas pasar di Madinah. Etika bisnis Islam tidak berhenti sebagai nasihat, tetapi ditegakkan sebagai pengawasan nyata.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan praktik berikut sebagai dilarang (curang) atau dibolehkan (etis).",
        buckets: ["Dilarang (curang)", "Dibolehkan (etis)"],
        items: [
          { text: "Menyembunyikan cacat barang dari pembeli", bucket: "Dilarang (curang)" },
          { text: "Pura-pura menawar tinggi agar harga naik palsu", bucket: "Dilarang (curang)" },
          { text: "Menimbun beras saat langka agar harganya melonjak", bucket: "Dilarang (curang)" },
          { text: "Menjelaskan kondisi apa adanya sebelum akad", bucket: "Dibolehkan (etis)" },
          { text: "Memberi pembeli hak khiyar untuk membatalkan", bucket: "Dibolehkan (etis)" },
          { text: "Menggunakan timbangan yang benar", bucket: "Dibolehkan (etis)" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Harga wajar sebuah komoditas adalah Rp12.000 per kg. Akibat najsy, harga terdorong naik menjadi Rp18.000 per kg. Berapa persen kenaikan harga yang tidak wajar itu?",
        answer: 50,
        tolerance: 0,
        suffix: "%",
        solution: "Kenaikan = 18.000 - 12.000 = Rp6.000. Persentase = 6.000 / 12.000 x 100% = <strong>50%</strong>. Manipulasi seperti najsy membuat pembeli membayar jauh di atas nilai sebenarnya.",
        hint: "Selisih harga dibagi harga wajar, lalu kalikan 100%.",
      },
      {
        type: "takeaways",
        items: [
          "Bisnis dalam Islam diikat akhlak: sidq (jujur), amanah, dan adl (adil).",
          "Tadlis, najsy, dan ihtikar adalah bentuk kecurangan yang diharamkan.",
          "Khiyar memberi pembeli hak melanjutkan atau membatalkan jual beli, termasuk saat menemukan cacat.",
          "Nabi Muhammad dikenal sebagai Al-Amin, teladan kejujuran dalam berdagang.",
          "Lembaga hisbah dan muhtasib menegakkan etika pasar sebagai pengawasan nyata.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Menyembunyikan cacat barang agar pembeli tertipu disebut?",
            options: ["Najsy", "Tadlis", "Ihtikar", "Khiyar"],
            answer: 1,
            explain: "Tadlis adalah menyembunyikan cacat atau informasi barang sehingga pembeli tertipu.",
          },
          {
            q: "Pura-pura menawar tinggi tanpa niat membeli agar harga naik palsu disebut?",
            options: ["Najsy", "Amanah", "Sidq", "Khiyar aib"],
            answer: 0,
            explain: "Najsy adalah penawaran palsu untuk memancing harga naik, dan hukumnya dilarang.",
          },
          {
            q: "Menimbun barang kebutuhan agar langka lalu dijual mahal disebut?",
            options: ["Sidq", "Ihtikar", "Adl", "Khiyar syarat"],
            answer: 1,
            explain: "Ihtikar adalah penimbunan barang untuk menaikkan harga, dan diharamkan karena merugikan masyarakat.",
          },
          {
            q: "Hak pembeli untuk membatalkan jual beli setelah menemukan cacat tersembunyi disebut?",
            options: ["Khiyar majlis", "Khiyar aib", "Najsy", "Tadlis"],
            answer: 1,
            explain: "Khiyar aib adalah hak membatalkan akad karena ditemukannya cacat pada barang.",
          },
          {
            q: "Gelar yang diberikan kepada Nabi Muhammad karena kejujurannya dalam berdagang adalah?",
            options: ["Al-Faruq", "Al-Amin", "Ash-Shiddiq", "Al-Muhtasib"],
            answer: 1,
            explain: "Al-Amin berarti yang terpercaya, gelar yang diberikan masyarakat Makkah kepada Nabi Muhammad.",
          },
        ],
      },
    ],
  },
  {
    id: "pemikiran-ekonomi-islam-klasik",
    levelId: "dasar",
    order: 9,
    title: "Warisan Pemikiran Ekonomi Islam",
    summary: "Gagasan para ilmuwan Muslim klasik tentang pajak, fungsi uang, harga adil, pembagian kerja, dan inflasi yang sering mendahului ekonom Barat berabad-abad.",
    durationMin: 15,
    tags: ["dasar", "sejarah pemikiran", "Ibn Khaldun", "Al-Ghazali", "harga adil"],
    blocks: [
      {
        type: "paragraph",
        html: "Jauh sebelum ilmu ekonomi modern lahir di Eropa, para ilmuwan Muslim sudah menuliskan gagasan tajam tentang pajak, uang, harga, dan produksi. Karya mereka bukan sekadar sejarah, melainkan fondasi yang banyak konsepnya baru ditemukan kembali oleh ekonom Barat berabad-abad kemudian.",
      },
      {
        type: "paragraph",
        html: "Dari <strong>Abu Yusuf</strong> soal perpajakan, <strong>Al-Ghazali</strong> soal fungsi uang, <strong>Ibn Taymiyyah</strong> soal harga adil, <strong>Ibn Khaldun</strong> soal pembagian kerja dan tarif pajak, hingga <strong>Al-Maqrizi</strong> soal inflasi, kita melihat tradisi ilmiah yang kaya dan berkesinambungan.",
      },
      {
        type: "image",
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Ibn_Khaldoun-Kassus.jpg?width=400",
        alt: "Patung Ibn Khaldun",
        caption: "Ibn Khaldun (1332-1406), peletak banyak gagasan ekonomi jauh sebelum ekonom Barat.",
        credit: "Sumber: Wikimedia Commons, domain publik",
      },
      {
        type: "callout",
        tone: "key",
        title: "Mendahului zamannya",
        html: "<strong>Ibn Khaldun</strong> dalam <strong>Muqaddimah</strong> (sekitar 1377) menjelaskan bahwa <strong>pembagian kerja</strong> meningkatkan produktivitas, dan bahwa tarif pajak yang terlalu tinggi justru menurunkan penerimaan negara karena mematikan usaha. Gagasan terakhir ini mirip dengan kurva Laffer yang baru populer pada 1974.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Uang sebagai alat, bukan tujuan",
        html: "<strong>Al-Ghazali</strong> (abad 11-12) menerangkan bahwa uang diciptakan sebagai <strong>alat tukar</strong> dan pengukur nilai untuk mengatasi kesulitan barter. Ia mengecam penimbunan uang dan pemalsuan mata uang, karena keduanya merusak fungsi uang bagi masyarakat.",
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Gunakan kembali simulator bagi hasil untuk melihat bagaimana imbalan yang terkait usaha nyata, seperti dianjurkan para ilmuwan ini, berbeda dari bunga tetap.",
      },
      {
        type: "video",
        comp: "EtikaBisnisIslamVideo",
        title: "Video: Warisan Para Ilmuwan",
        caption: "Bagaimana gagasan ekonomi Islam klasik berpijak pada kejujuran dan keadilan.",
      },
      { type: "widget", widget: "SimulatorRibaVsBagiHasil" },
      {
        type: "table",
        headers: ["Ilmuwan", "Masa", "Gagasan utama"],
        rows: [
          ["Abu Yusuf", "Abad 8", "Perpajakan dalam Kitab al-Kharaj"],
          ["Al-Ghazali", "Abad 11-12", "Fungsi uang sebagai alat tukar"],
          ["Ibn Taymiyyah", "Abad 13-14", "Harga adil dan mekanisme pasar"],
          ["Ibn Khaldun", "Abad 14", "Pembagian kerja dan pengaruh tarif pajak"],
          ["Al-Maqrizi", "Abad 15", "Inflasi dan mata uang buruk"],
        ],
        caption: "Rangkaian pemikir yang membangun tradisi ekonomi Islam klasik.",
      },
      {
        type: "chart",
        variant: "line",
        title: "Gagasan Ibn Khaldun: Tarif Pajak vs Penerimaan Negara (ilustrasi)",
        unit: "penerimaan negara (indeks)",
        source: "ilustrasi edukatif berdasarkan gagasan Ibn Khaldun dalam Muqaddimah",
        note: "Saat tarif rendah, penerimaan terbatas; pada tarif menengah penerimaan puncak; bila tarif terlalu tinggi, usaha melemah dan penerimaan justru turun, jauh mendahului gagasan kurva Laffer.",
        data: [
          { label: "0%", value: 0 },
          { label: "20%", value: 60 },
          { label: "40%", value: 90 },
          { label: "60%", value: 70 },
          { label: "80%", value: 35 },
          { label: "100%", value: 0 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Tarif tinggi yang justru merugikan negara",
        html: "Sebuah negeri mengenakan pajak <strong>20%</strong> atas basis produksi senilai Rp500 juta, sehingga penerimaan Rp100 juta. Ingin penerimaan lebih besar, tarif dinaikkan menjadi <strong>50%</strong>. Namun tarif yang berat membuat banyak pengusaha berhenti, basis produksi menyusut menjadi Rp160 juta, sehingga penerimaan hanya Rp80 juta. Sesuai gagasan Ibn Khaldun, menaikkan tarif terlalu tinggi justru menurunkan penerimaan.",
      },
      {
        type: "case",
        title: "Sejarah: Muqaddimah mendahului kurva Laffer",
        html: "<strong>Ibn Khaldun</strong> menulis <strong>Muqaddimah</strong> sekitar tahun <strong>1377</strong> dan menjelaskan bahwa pada awal sebuah dinasti, tarif pajak yang ringan mendorong usaha sehingga penerimaan besar, sedangkan pada akhir dinasti tarif yang berat mematikan usaha dan menurunkan penerimaan. Gagasan serupa baru dipopulerkan ekonom <strong>Arthur Laffer</strong> pada <strong>1974</strong> sebagai kurva Laffer, hampir enam abad kemudian. Al-Maqrizi (abad 15) pun lebih dahulu menganalisis bagaimana mata uang buruk dan pencetakan berlebihan memicu inflasi di Mesir.",
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan setiap ilmuwan dengan gagasan utamanya.",
        pairs: [
          { left: "Abu Yusuf", right: "Perpajakan dalam Kitab al-Kharaj" },
          { left: "Al-Ghazali", right: "Fungsi uang sebagai alat tukar" },
          { left: "Ibn Taymiyyah", right: "Harga adil dan mekanisme pasar" },
          { left: "Ibn Khaldun", right: "Pembagian kerja dan pengaruh tarif pajak" },
          { left: "Al-Maqrizi", right: "Inflasi dan mata uang buruk" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Tarif pajak 20% dikenakan atas basis produksi Rp500 juta. Bila tarif dinaikkan ke 50% tetapi basis menyusut menjadi Rp160 juta, berapa juta rupiah penurunan penerimaan negara dibanding tarif semula?",
        answer: 20,
        tolerance: 0,
        prefix: "Rp",
        suffix: " juta",
        solution: "Penerimaan awal = 20% x 500 = Rp100 juta. Penerimaan baru = 50% x 160 = Rp80 juta. Penurunan = 100 - 80 = <strong>Rp20 juta</strong>. Tarif lebih tinggi malah menghasilkan penerimaan lebih kecil, persis gagasan Ibn Khaldun.",
        hint: "Hitung 20% x 500 dan 50% x 160, lalu cari selisihnya.",
      },
      {
        type: "takeaways",
        items: [
          "Abu Yusuf membahas perpajakan yang adil dalam Kitab al-Kharaj pada abad 8.",
          "Al-Ghazali menjelaskan uang sebagai alat tukar dan mengecam penimbunan serta pemalsuannya.",
          "Ibn Taymiyyah merumuskan harga adil dan bekerjanya mekanisme pasar.",
          "Ibn Khaldun menulis soal pembagian kerja dan pengaruh tarif pajak, mendahului kurva Laffer.",
          "Al-Maqrizi menganalisis inflasi dan mata uang buruk pada abad 15.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Karya Abu Yusuf yang membahas perpajakan berjudul?",
            options: ["Muqaddimah", "Ihya Ulumuddin", "Kitab al-Kharaj", "Al-Hisbah"],
            answer: 2,
            explain: "Abu Yusuf menulis Kitab al-Kharaj yang membahas kebijakan perpajakan pada abad 8.",
          },
          {
            q: "Ilmuwan yang menjelaskan fungsi uang sebagai alat tukar adalah?",
            options: ["Al-Ghazali", "Ibn Khaldun", "Al-Maqrizi", "Abu Yusuf"],
            answer: 0,
            explain: "Al-Ghazali menerangkan uang sebagai alat tukar dan pengukur nilai untuk mengatasi kesulitan barter.",
          },
          {
            q: "Konsep harga adil dan mekanisme pasar banyak dibahas oleh?",
            options: ["Ibn Taymiyyah", "Al-Ghazali", "Abu Yusuf", "Al-Maqrizi"],
            answer: 0,
            explain: "Ibn Taymiyyah merumuskan harga adil (thaman al-mithl) dan bekerjanya mekanisme pasar.",
          },
          {
            q: "Gagasan bahwa tarif pajak terlalu tinggi menurunkan penerimaan negara ditulis oleh Ibn Khaldun dalam?",
            options: ["Ihya Ulumuddin", "Muqaddimah", "Kitab al-Kharaj", "Ighathat al-Ummah"],
            answer: 1,
            explain: "Ibn Khaldun menuliskannya dalam Muqaddimah sekitar 1377, mendahului kurva Laffer 1974.",
          },
          {
            q: "Ilmuwan abad 15 yang menganalisis inflasi dan mata uang buruk adalah?",
            options: ["Al-Maqrizi", "Ibn Taymiyyah", "Al-Ghazali", "Abu Yusuf"],
            answer: 0,
            explain: "Al-Maqrizi menganalisis inflasi dan dampak mata uang buruk di Mesir pada abad 15.",
          },
        ],
      },
    ],
  },
];
