import type { Lesson } from "../../../types";

export const level4: Lesson[] = [
  // ============================================================
  {
    id: "tcfd-issb",
    levelId: "pengungkapan",
    order: 1,
    title: "Pengungkapan Iklim: TCFD & ISSB",
    summary: "Kerangka agar perusahaan mengungkap risiko dan peluang iklim secara konsisten dan dapat dibandingkan.",
    durationMin: 12,
    tags: ["TCFD", "ISSB", "pengungkapan"],
    blocks: [
      {
        type: "paragraph",
        html: "Investor butuh tahu bagaimana iklim memengaruhi sebuah perusahaan. <strong>Pengungkapan iklim</strong> menyediakan informasi itu secara terstruktur. Kerangka paling berpengaruh adalah <strong>TCFD</strong>, yang kini dilanjutkan oleh standar global <strong>ISSB (IFRS S2)</strong>.",
      },
      {
        type: "table",
        caption: "Empat pilar TCFD",
        headers: ["Pilar", "Pertanyaan inti"],
        rows: [
          ["Governance (Tata Kelola)", "Siapa yang mengawasi isu iklim?"],
          ["Strategy (Strategi)", "Bagaimana iklim memengaruhi bisnis & strategi?"],
          ["Risk Management", "Bagaimana risiko iklim diidentifikasi & dikelola?"],
          ["Metrics & Targets", "Metrik apa yang dipakai, termasuk emisi & target?"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Dari TCFD ke ISSB",
        html: "<strong>ISSB</strong> menerbitkan <strong>IFRS S2</strong> tentang pengungkapan iklim, yang menyatukan dan menggantikan TCFD sebagai standar global. Banyak regulator (termasuk arah di Indonesia) mengadopsinya, sehingga pengungkapan iklim makin menjadi kewajiban, bukan sukarela.",
      },
      {
        type: "chart",
        variant: "donut",
        title: "Apa yang Paling Dicari Investor dari Pengungkapan (ilustrasi)",
        unit: "% bobot perhatian",
        source: "ilustrasi konsep",
        note: "Emisi (termasuk Scope 1/2/3) dan analisis skenario menjadi sorotan utama.",
        data: [
          { label: "Emisi & target", value: 40 },
          { label: "Risiko & skenario", value: 30 },
          { label: "Strategi transisi", value: 20 },
          { label: "Tata kelola", value: 10 },
        ],
      },
      {
        type: "chart",
        variant: "line",
        title: "Pertumbuhan Adopsi Pengungkapan Iklim (ilustrasi)",
        unit: "% perusahaan besar yang mengungkap",
        source: "ilustrasi konsep",
        note: "Tren mengarah naik seiring TCFD bergeser menjadi ISSB (IFRS S2) dan diadopsi regulator.",
        data: [
          { label: "2018", value: 20 },
          { label: "2020", value: 38 },
          { label: "2022", value: 60 },
          { label: "2024", value: 78 },
        ],
      },
      {
        type: "case",
        title: "Studi Kasus: Klaim hijau tanpa data",
        html: "Sebuah perusahaan mempromosikan diri 'ramah lingkungan' namun tidak mengungkap emisinya, target, atau rencana transisi. Saat investor meminta data sesuai kerangka TCFD/ISSB, perusahaan tidak bisa menunjukkannya. Klaim tanpa pengungkapan terukur inilah yang sering disebut <strong>greenwashing</strong>. Pengungkapan yang baik justru melindungi perusahaan dari tuduhan tersebut.",
      },
      {
        type: "classifyExercise",
        prompt: "Informasi ini masuk pilar TCFD yang mana?",
        buckets: ["Governance", "Strategy", "Risk Management", "Metrics & Targets"],
        items: [
          { text: "Komite dewan yang mengawasi isu iklim", bucket: "Governance" },
          { text: "Dampak skenario 1,5°C terhadap bisnis", bucket: "Strategy" },
          { text: "Proses mengidentifikasi risiko banjir di pabrik", bucket: "Risk Management" },
          { text: "Total emisi Scope 1, 2, 3 dan target net-zero", bucket: "Metrics & Targets" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "TCFD", right: "Kerangka pengungkapan risiko iklim (4 pilar)" },
          { left: "ISSB / IFRS S2", right: "Standar global pengungkapan iklim" },
          { left: "Greenwashing", right: "Klaim hijau yang menyesatkan tanpa bukti" },
          { left: "Analisis skenario", right: "Menguji bisnis pada berbagai jalur iklim" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Adopsi pengungkapan iklim naik dari 20% (2018) menjadi 78% (2024). Berapa kenaikan dalam poin persen?",
        answer: 58,
        tolerance: 0,
        suffix: " poin persen",
        solution: "78% - 20% = 58 poin persen, menggambarkan tren pengungkapan yang makin meluas.",
        hint: "Kurangkan angka 2018 dari angka 2024.",
      },
      {
        type: "case",
        title: "Sejarah: Dari TCFD 2015 ke ISSB 2023",
        html: "Dewan Stabilitas Keuangan membentuk <strong>TCFD</strong> pada <strong>2015</strong> dan menerbitkan rekomendasi pengungkapan iklimnya pada 2017. Pada <strong>2023</strong>, <strong>ISSB</strong> menerbitkan standar global <strong>IFRS S1 dan S2</strong> yang melanjutkan kerangka TCFD, menjadikan pengungkapan risiko iklim makin terstandar dan dapat dibandingkan antarnegara.",
      },
      {
        type: "takeaways",
        items: [
          "Pengungkapan iklim memberi investor informasi terstruktur.",
          "TCFD punya 4 pilar: governance, strategy, risk management, metrics & targets.",
          "ISSB (IFRS S2) menjadi standar global yang melanjutkan TCFD.",
          "Pengungkapan yang baik melindungi dari tuduhan greenwashing.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "TCFD memiliki berapa pilar?",
            options: ["2", "4", "6", "10"],
            answer: 1,
            explain: "TCFD punya 4 pilar: governance, strategy, risk management, metrics & targets.",
          },
          {
            q: "Standar global pengungkapan iklim yang melanjutkan TCFD adalah?",
            options: ["ISSB (IFRS S2)", "Basel III", "PSAK 1", "ISO 9001"],
            answer: 0,
            explain: "ISSB menerbitkan IFRS S2 sebagai standar global pengungkapan iklim.",
          },
          {
            q: "Total emisi dan target net-zero masuk pilar?",
            options: ["Governance", "Metrics & Targets", "Strategy", "Risk Management"],
            answer: 1,
            explain: "Emisi dan target adalah bagian pilar Metrics & Targets.",
          },
          {
            q: "Klaim hijau tanpa data dan pengungkapan disebut?",
            options: ["Transparansi", "Greenwashing", "Audit", "Mitigasi"],
            answer: 1,
            explain: "Klaim ramah lingkungan yang menyesatkan tanpa bukti adalah greenwashing.",
          },
          {
            q: "Mengapa pengungkapan iklim makin menjadi kewajiban?",
            options: [
              "Karena tren sesaat",
              "Karena regulator mengadopsi standar seperti ISSB",
              "Karena dilarang",
              "Karena tidak penting",
            ],
            answer: 1,
            explain: "Adopsi ISSB oleh regulator membuat pengungkapan iklim bergeser dari sukarela ke wajib.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "taksonomi-hijau",
    levelId: "pengungkapan",
    order: 2,
    title: "Taksonomi Hijau",
    summary: "Sistem klasifikasi yang menentukan aktivitas ekonomi mana yang dianggap hijau atau berkelanjutan.",
    durationMin: 12,
    tags: ["taksonomi", "OJK", "greenwashing"],
    blocks: [
      {
        type: "paragraph",
        html: "Bagaimana kita tahu sebuah aktivitas benar-benar 'hijau'? <strong>Taksonomi hijau</strong> adalah sistem klasifikasi resmi yang menetapkan kriteria aktivitas ekonomi yang dianggap hijau atau berkelanjutan. Tujuannya dua: mencegah <strong>greenwashing</strong> dan mengarahkan aliran modal ke aktivitas yang benar-benar mendukung transisi.",
      },
      {
        type: "video",
        comp: "TaksonomiHijauVideo",
        title: "Memahami Taksonomi Hijau",
        caption: "Bagaimana klasifikasi hijau, transisi, dan belum memenuhi bekerja untuk mengarahkan modal.",
      },
      {
        type: "table",
        caption: "Contoh taksonomi di berbagai wilayah",
        headers: ["Taksonomi", "Penerbit", "Cakupan"],
        rows: [
          ["Taksonomi Hijau Indonesia", "OJK", "Klasifikasi aktivitas berkelanjutan nasional"],
          ["EU Taxonomy", "Uni Eropa", "Kriteria aktivitas ramah iklim & lingkungan"],
          ["ASEAN Taxonomy", "ASEAN", "Acuan regional untuk negara anggota"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Taksonomi Hijau Indonesia oleh OJK",
        html: "Di Indonesia, <strong>Taksonomi Hijau Indonesia disusun oleh OJK</strong>. Taksonomi ini memakai sistem klasifikasi bertingkat (mis. hijau, transisi, tidak memenuhi) sehingga aktivitas tidak sekadar dilabeli 'hijau' atau 'tidak', melainkan dinilai sejauh mana mendukung tujuan keberlanjutan.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Mengapa penting bagi modal",
        html: "Dengan kriteria yang jelas, bank dan investor bisa menyalurkan dana ke proyek yang memenuhi taksonomi, dan produk seperti green bond bisa diverifikasi labelnya. Taksonomi menjadi 'kamus bersama' agar klaim hijau bisa dibandingkan.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Komposisi Klasifikasi Sebuah Portofolio Kredit (ilustrasi)",
        unit: "% nilai portofolio",
        source: "ilustrasi konsep",
        note: "Taksonomi membantu memetakan seberapa besar portofolio sudah selaras dengan kriteria hijau.",
        data: [
          { label: "Hijau", value: 25 },
          { label: "Transisi", value: 35 },
          { label: "Belum memenuhi", value: 40 },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Pangsa Aktivitas menurut Klasifikasi Taksonomi (ilustrasi)",
        unit: "% jumlah aktivitas",
        source: "ilustrasi konsep",
        note: "Sebagian besar aktivitas sering berada di kategori transisi, bukan langsung hijau penuh.",
        data: [
          { label: "Hijau", value: 30 },
          { label: "Transisi", value: 45 },
          { label: "Belum memenuhi", value: 25 },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba kalkulatornya",
        html: "Gunakan kalkulator di bawah untuk memetakan porsi hijau, transisi, dan belum memenuhi dari sebuah portofolio, lalu lihat berapa persen yang sudah selaras taksonomi.",
      },
      {
        type: "widget",
        widget: "KalkulatorTaksonomi",
      },
      {
        type: "case",
        title: "Studi Kasus: Memilah portofolio Rp 10 triliun",
        html: "Sebuah bank memiliki portofolio kredit Rp 10 triliun. Setelah dipetakan ke taksonomi, ditemukan Rp 2,5 triliun masuk kategori 'hijau' (mis. PLTS, transportasi listrik), Rp 3,5 triliun kategori 'transisi' (mis. efisiensi energi di pabrik), dan Rp 4 triliun 'belum memenuhi'. Dengan peta ini, bank bisa menetapkan target menaikkan porsi hijau dan transisi, serta menerbitkan green bond yang asetnya jelas memenuhi kriteria.",
      },
      {
        type: "classifyExercise",
        prompt: "Kelompokkan aktivitas berikut menurut klasifikasi taksonomi yang umum.",
        buckets: ["Hijau", "Transisi", "Belum memenuhi"],
        items: [
          { text: "Pembangkit listrik tenaga surya skala besar", bucket: "Hijau" },
          { text: "Kereta listrik untuk transportasi publik", bucket: "Hijau" },
          { text: "Retrofit pabrik agar lebih hemat energi", bucket: "Transisi" },
          { text: "Pembangkit batu bara tanpa rencana pengurangan emisi", bucket: "Belum memenuhi" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "Taksonomi hijau", right: "Sistem klasifikasi aktivitas berkelanjutan" },
          { left: "OJK", right: "Penerbit Taksonomi Hijau Indonesia" },
          { left: "Kategori transisi", right: "Aktivitas yang bergerak menuju lebih hijau" },
          { left: "EU Taxonomy", right: "Taksonomi acuan dari Uni Eropa" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Dari portofolio Rp 10 triliun, Rp 2,5 triliun 'hijau' dan Rp 3,5 triliun 'transisi'. Berapa persen porsi yang TIDAK termasuk hijau maupun transisi?",
        answer: 40,
        tolerance: 1,
        suffix: "%",
        solution: "Hijau + transisi = Rp 6 triliun (60%). Sisanya Rp 4 triliun, yaitu 40% belum memenuhi.",
      },
      {
        type: "calcExercise",
        prompt: "Sebuah bank menargetkan porsi 'hijau' dan 'transisi' gabungan minimal 70% dari portofolio. Jika saat ini hijau 30% dan transisi 45%, berapa poin persen kelebihannya di atas target?",
        answer: 5,
        tolerance: 0,
        suffix: " poin persen",
        solution: "Hijau + transisi = 30% + 45% = 75%. Selisih di atas target = 75% - 70% = 5 poin persen.",
        hint: "Jumlahkan porsi hijau dan transisi, lalu kurangi target 70%.",
      },
      {
        type: "case",
        title: "Sejarah: Taksonomi Hijau EU 2020 & OJK 2022",
        html: "Uni Eropa memberlakukan <strong>EU Taxonomy Regulation</strong> pada <strong>2020</strong> sebagai sistem klasifikasi resmi aktivitas berkelanjutan. Indonesia menyusul lewat <strong>OJK</strong> yang meluncurkan <strong>Taksonomi Hijau Indonesia Edisi 1.0 pada 2022</strong> (kemudian dikembangkan menjadi taksonomi keuangan berkelanjutan), agar klaim hijau memiliki kriteria yang jelas dan dapat diverifikasi.",
      },
      {
        type: "takeaways",
        items: [
          "Taksonomi hijau adalah sistem klasifikasi aktivitas ekonomi yang dianggap hijau/berkelanjutan.",
          "Tujuannya mencegah greenwashing dan mengarahkan modal ke aktivitas yang tepat.",
          "Taksonomi Hijau Indonesia disusun oleh OJK dengan klasifikasi bertingkat.",
          "Taksonomi menjadi 'kamus bersama' agar klaim hijau dapat dibandingkan dan diverifikasi.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa fungsi utama taksonomi hijau?",
            options: [
              "Menaikkan suku bunga",
              "Mengklasifikasikan aktivitas yang dianggap hijau/berkelanjutan",
              "Menghapus pajak karbon",
              "Mengatur kurs valuta",
            ],
            answer: 1,
            explain: "Taksonomi hijau adalah sistem klasifikasi aktivitas ekonomi yang dianggap berkelanjutan.",
          },
          {
            q: "Siapa penerbit Taksonomi Hijau Indonesia?",
            options: ["OJK", "BPK", "WTO", "OPEC"],
            answer: 0,
            explain: "Taksonomi Hijau Indonesia disusun oleh OJK.",
          },
          {
            q: "Salah satu tujuan utama taksonomi adalah?",
            options: [
              "Mempercepat inflasi",
              "Mencegah greenwashing",
              "Menghapus pengungkapan",
              "Melarang investasi",
            ],
            answer: 1,
            explain: "Taksonomi membantu mencegah greenwashing dengan kriteria yang jelas.",
          },
          {
            q: "Kategori 'transisi' dalam taksonomi menggambarkan aktivitas yang?",
            options: [
              "Sudah sepenuhnya hijau",
              "Bergerak menuju lebih hijau namun belum penuh",
              "Dilarang total",
              "Tidak ada kaitannya dengan iklim",
            ],
            answer: 1,
            explain: "Kategori transisi adalah aktivitas yang sedang menuju lebih hijau.",
          },
          {
            q: "Contoh aktivitas yang umumnya masuk kategori 'hijau' adalah?",
            options: [
              "Pembangkit batu bara baru",
              "Pembangkit listrik tenaga surya",
              "Penambangan tanpa rehabilitasi",
              "Pembakaran limbah terbuka",
            ],
            answer: 1,
            explain: "PLTS adalah contoh aktivitas yang umumnya memenuhi kriteria hijau.",
          },
          {
            q: "Mengapa taksonomi membantu produk seperti green bond?",
            options: [
              "Karena menaikkan kuponnya otomatis",
              "Karena aset proyeknya bisa diverifikasi memenuhi kriteria",
              "Karena menghapus risiko gagal bayar",
              "Karena membebaskan dari pelaporan",
            ],
            answer: 1,
            explain: "Taksonomi memberi kriteria sehingga label hijau pada green bond dapat diverifikasi.",
          },
          {
            q: "Taksonomi sering disebut sebagai 'kamus bersama' karena?",
            options: [
              "Membuat semua aktivitas otomatis hijau",
              "Menyediakan kriteria yang sama agar klaim bisa dibandingkan",
              "Menggantikan laporan keuangan",
              "Menetapkan harga saham",
            ],
            answer: 1,
            explain: "Dengan kriteria yang sama, klaim hijau menjadi dapat dibandingkan antar pihak.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "esg-rating",
    levelId: "pengungkapan",
    order: 3,
    title: "ESG Rating & Data",
    summary: "Bagaimana lembaga menilai kinerja ESG perusahaan, apa kegunaannya, dan mengapa hasilnya bisa berbeda antar lembaga.",
    durationMin: 12,
    tags: ["ESG", "rating", "data"],
    blocks: [
      {
        type: "paragraph",
        html: "Investor butuh cara cepat menilai apakah sebuah perusahaan dikelola secara bertanggung jawab di sisi lingkungan, sosial, dan tata kelola. <strong>ESG rating</strong> mencoba meringkas hal itu menjadi satu skor atau peringkat. Lembaga pemeringkat mengumpulkan data publik dan kuesioner, lalu menilai perusahaan pada banyak indikator E, S, dan G.",
      },
      {
        type: "table",
        caption: "Tiga dimensi ESG",
        headers: ["Dimensi", "Contoh indikator"],
        rows: [
          ["Environmental (E)", "Emisi, penggunaan air, limbah, energi"],
          ["Social (S)", "Keselamatan kerja, hak pekerja, dampak komunitas"],
          ["Governance (G)", "Independensi dewan, anti-korupsi, transparansi"],
        ],
      },
      {
        type: "callout",
        tone: "key",
        title: "Rating bisa berbeda antar lembaga",
        html: "Keterbatasan penting: <strong>skor ESG untuk perusahaan yang sama bisa sangat berbeda antar lembaga pemeringkat</strong>. Penyebabnya antara lain indikator yang dipilih berbeda, bobot yang berbeda, dan data yang tidak lengkap. Jadi ESG rating berguna sebagai titik awal, bukan kebenaran mutlak.",
      },
      {
        type: "callout",
        tone: "info",
        title: "Hubungan dengan pengungkapan",
        html: "Kualitas rating bergantung pada kualitas data. Semakin baik pengungkapan perusahaan (lihat TCFD/ISSB), semakin sedikit lembaga rating harus menebak, dan semakin konsisten penilaiannya.",
      },
      {
        type: "heading",
        text: "Mengapa Skor Bisa Berbeda (ilustrasi)",
      },
      {
        type: "stats",
        items: [
          { label: "Perbedaan indikator yang dipakai", value: "~50%", sub: "ilustrasi konsep" },
          { label: "Perbedaan bobot tiap indikator", value: "~40%", sub: "ilustrasi konsep" },
          { label: "Perbedaan kelengkapan data", value: "~10%", sub: "ilustrasi konsep" },
        ],
      },
      {
        type: "chart",
        variant: "donut",
        title: "Contoh Bobot Pilar E, S, G dalam Sebuah Metodologi Rating (ilustrasi)",
        unit: "% bobot skor",
        source: "ilustrasi konsep",
        note: "Bobot tiap pilar berbeda antar lembaga, sehingga skor akhir bisa berbeda untuk perusahaan yang sama.",
        data: [
          { label: "Environmental", value: 45 },
          { label: "Social", value: 30 },
          { label: "Governance", value: 25 },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba simulatornya",
        html: "Pakai simulator di bawah untuk mengubah skor E, S, dan G beserta bobotnya, lalu lihat bagaimana skor ESG gabungan berubah.",
      },
      {
        type: "widget",
        widget: "SimulatorESGRating",
      },
      {
        type: "case",
        title: "Studi Kasus: Satu perusahaan, dua skor",
        html: "Perusahaan A dinilai oleh dua lembaga. Lembaga X memberi skor 80/100 karena memberi bobot besar pada tata kelola yang kuat. Lembaga Y hanya memberi 55/100 karena memberi bobot besar pada emisi Scope 3 yang masih tinggi dan datanya tidak lengkap. Selisih 25 poin ini bukan berarti salah satu salah: keduanya menilai hal berbeda dengan bobot berbeda. Investor perlu memahami metodologi di balik angka.",
      },
      {
        type: "classifyExercise",
        prompt: "Indikator berikut termasuk dimensi ESG yang mana?",
        buckets: ["Environmental", "Social", "Governance"],
        items: [
          { text: "Intensitas emisi karbon", bucket: "Environmental" },
          { text: "Penggunaan air dan limbah", bucket: "Environmental" },
          { text: "Tingkat kecelakaan kerja", bucket: "Social" },
          { text: "Independensi anggota dewan komisaris", bucket: "Governance" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan istilah dengan artinya.",
        pairs: [
          { left: "ESG rating", right: "Skor ringkas kinerja E, S, dan G perusahaan" },
          { left: "Divergensi rating", right: "Skor berbeda antar lembaga untuk perusahaan sama" },
          { left: "Metodologi", right: "Cara lembaga memilih indikator dan bobot" },
          { left: "Kualitas data", right: "Faktor yang memengaruhi keandalan skor" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Lembaga X memberi skor 80 dan lembaga Y memberi 55 untuk perusahaan yang sama. Berapa selisih poinnya?",
        answer: 25,
        tolerance: 0,
        suffix: " poin",
        solution: "80 - 55 = 25 poin. Selisih ini menunjukkan divergensi rating antar lembaga.",
      },
      {
        type: "calcExercise",
        prompt: "Dengan bobot E 45%, S 30%, G 25%, sebuah perusahaan punya skor E=60, S=80, G=90. Berapa skor ESG gabungannya?",
        answer: 73.5,
        tolerance: 0.5,
        suffix: " poin",
        solution: "0,45 x 60 + 0,30 x 80 + 0,25 x 90 = 27 + 24 + 22,5 = 73,5 poin.",
        hint: "Kalikan tiap skor dengan bobotnya, lalu jumlahkan.",
      },
      {
        type: "case",
        title: "Sejarah: Principles for Responsible Investment 2006",
        html: "Pada <strong>2006</strong>, dengan dukungan PBB diluncurkan <strong>Principles for Responsible Investment (PRI)</strong> yang mendorong investor memasukkan faktor <strong>ESG</strong> ke dalam keputusan investasi. Dari segelintir penanda tangan awal, PRI kini diikuti ribuan institusi yang mengelola dana lebih dari <strong>USD 100 triliun</strong>, memicu tumbuhnya industri ESG rating dan data.",
      },
      {
        type: "takeaways",
        items: [
          "ESG rating meringkas kinerja lingkungan, sosial, dan tata kelola menjadi skor/peringkat.",
          "Rating berguna sebagai titik awal penilaian, bukan kebenaran mutlak.",
          "Skor untuk perusahaan yang sama bisa berbeda antar lembaga karena indikator, bobot, dan data berbeda.",
          "Kualitas pengungkapan meningkatkan keandalan dan konsistensi rating.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "ESG rating berusaha meringkas kinerja perusahaan dalam aspek?",
            options: [
              "Hanya keuangan",
              "Lingkungan, sosial, dan tata kelola",
              "Hanya pemasaran",
              "Hanya pajak",
            ],
            answer: 1,
            explain: "ESG = Environmental, Social, Governance.",
          },
          {
            q: "Mengapa skor ESG bisa berbeda antar lembaga?",
            options: [
              "Karena salah satu pasti salah",
              "Karena indikator, bobot, dan data yang dipakai berbeda",
              "Karena perusahaan berbeda",
              "Karena mata uang berbeda",
            ],
            answer: 1,
            explain: "Perbedaan metodologi (indikator, bobot, kelengkapan data) menyebabkan divergensi.",
          },
          {
            q: "Intensitas emisi karbon termasuk dimensi?",
            options: ["Environmental", "Social", "Governance", "Finansial"],
            answer: 0,
            explain: "Emisi adalah indikator dimensi Environmental.",
          },
          {
            q: "Independensi dewan komisaris termasuk dimensi?",
            options: ["Environmental", "Social", "Governance", "Marketing"],
            answer: 2,
            explain: "Struktur dewan adalah indikator tata kelola (Governance).",
          },
          {
            q: "Bagaimana sebaiknya investor memperlakukan ESG rating?",
            options: [
              "Sebagai kebenaran mutlak",
              "Sebagai titik awal yang perlu dipahami metodologinya",
              "Diabaikan sepenuhnya",
              "Sebagai jaminan keuntungan",
            ],
            answer: 1,
            explain: "Rating adalah titik awal; metodologinya perlu dipahami.",
          },
          {
            q: "Apa yang meningkatkan keandalan ESG rating?",
            options: [
              "Pengungkapan yang lebih lengkap dan berkualitas",
              "Menyembunyikan data",
              "Menghapus indikator emisi",
              "Mengurangi transparansi",
            ],
            answer: 0,
            explain: "Data pengungkapan yang baik mengurangi tebakan dan meningkatkan konsistensi rating.",
          },
          {
            q: "Selisih skor yang besar antar lembaga untuk satu perusahaan disebut?",
            options: [
              "Konvergensi rating",
              "Divergensi rating",
              "Audit rating",
              "Inflasi rating",
            ],
            answer: 1,
            explain: "Perbedaan skor antar lembaga untuk perusahaan sama disebut divergensi rating.",
          },
        ],
      },
    ],
  },
  // ============================================================
  {
    id: "greenwashing",
    levelId: "pengungkapan",
    order: 4,
    title: "Greenwashing & Integritas Klaim",
    summary: "Mengenali klaim hijau yang menyesatkan, regulasi anti-greenwashing, serta peran pengungkapan dan taksonomi menjaga integritas.",
    durationMin: 12,
    tags: ["greenwashing", "integritas", "regulasi"],
    blocks: [
      {
        type: "paragraph",
        html: "<strong>Greenwashing</strong> adalah praktik membuat klaim ramah lingkungan yang menyesatkan atau dilebih-lebihkan, tanpa bukti yang memadai. Akibatnya, modal bisa salah arah dan kepercayaan publik tergerus. Bab ini membahas cara mengenali greenwashing serta bagaimana pengungkapan, taksonomi, dan regulasi menjaga integritas klaim hijau.",
      },
      {
        type: "video",
        comp: "GreenwashingVideo",
        title: "Mengenali Greenwashing",
        caption: "Pola klaim hijau yang menyesatkan dan cara membedakannya dari klaim yang kredibel.",
      },
      {
        type: "list",
        items: [
          "Klaim samar tanpa angka, mis. 'ramah lingkungan' tanpa data emisi.",
          "Menonjolkan satu produk hijau sambil menyembunyikan dampak besar di bagian lain.",
          "Memakai label atau warna hijau tanpa sertifikasi atau verifikasi.",
          "Target jauh di masa depan tanpa rencana dan tonggak yang jelas.",
        ],
      },
      {
        type: "callout",
        tone: "warn",
        title: "Tanda bahaya greenwashing",
        html: "Waspadai klaim yang <strong>tidak dapat diverifikasi</strong>: tidak ada data, tidak mengacu pada taksonomi atau standar, dan tidak ada pihak ketiga yang menilai. Klaim yang baik selalu bisa ditelusuri ke bukti.",
      },
      {
        type: "callout",
        tone: "key",
        title: "Regulasi & alat anti-greenwashing",
        html: "Regulator makin menegakkan aturan agar klaim hijau berdasar bukti. Tiga alat saling melengkapi: <strong>pengungkapan</strong> (TCFD/ISSB) menyediakan data, <strong>taksonomi</strong> (mis. OJK) memberi kriteria apa yang hijau, dan <strong>verifikasi pihak ketiga</strong> mengecek klaim. Bersama, ketiganya mempersempit ruang greenwashing.",
      },
      {
        type: "chart",
        variant: "bar",
        title: "Klaim Hijau yang Tidak Dapat Dibuktikan saat Diperiksa (ilustrasi)",
        unit: "% klaim diperiksa",
        source: "ilustrasi konsep",
        note: "Angka ilustrasi untuk menggambarkan besarnya masalah, bukan data riil.",
        data: [
          { label: "Bisa dibuktikan", value: 45 },
          { label: "Sebagian/ambigu", value: 35 },
          { label: "Tidak dapat dibuktikan", value: 20 },
        ],
      },
      {
        type: "chart",
        variant: "bar",
        title: "Tanda Bahaya Greenwashing yang Paling Sering Muncul (ilustrasi)",
        unit: "% klaim bermasalah yang memuatnya",
        source: "ilustrasi konsep",
        note: "Klaim samar tanpa data adalah pola yang paling sering ditemukan.",
        data: [
          { label: "Klaim samar tanpa data", value: 70 },
          { label: "Tanpa verifikasi pihak ketiga", value: 55 },
          { label: "Sorot 1 produk, sembunyikan dampak lain", value: 40 },
          { label: "Target tanpa tonggak jelas", value: 35 },
        ],
      },
      {
        type: "callout",
        tone: "tip",
        title: "Coba detektornya",
        html: "Gunakan detektor di bawah untuk menguji sebuah klaim hijau: cek apakah ada data, acuan taksonomi/standar, dan verifikasi pihak ketiga.",
      },
      {
        type: "widget",
        widget: "DetektorGreenwashing",
      },
      {
        type: "case",
        title: "Studi Kasus: 'Dana hijau' yang tidak hijau",
        html: "Sebuah produk investasi dipasarkan sebagai 'dana hijau'. Setelah diperiksa, hanya 8% asetnya memenuhi kriteria taksonomi, sementara 60% justru di sektor intensif emisi tanpa rencana transisi. Klaim 'hijau' pada nama produk tidak didukung komposisi aset. Regulator dapat menilai ini menyesatkan. Andai produk memakai taksonomi dan mengungkap komposisi aset sejak awal, klaim seperti ini tidak akan lolos.",
      },
      {
        type: "classifyExercise",
        prompt: "Mana klaim yang berisiko greenwashing dan mana yang kredibel?",
        buckets: ["Berisiko greenwashing", "Klaim kredibel"],
        items: [
          { text: "'100% ramah lingkungan' tanpa data apa pun", bucket: "Berisiko greenwashing" },
          { text: "Label hijau tanpa sertifikasi atau verifikasi", bucket: "Berisiko greenwashing" },
          { text: "Mengungkap emisi Scope 1, 2, 3 dengan target bertonggak jelas", bucket: "Klaim kredibel" },
          { text: "Aset diverifikasi memenuhi taksonomi oleh pihak ketiga", bucket: "Klaim kredibel" },
        ],
      },
      {
        type: "matchExercise",
        prompt: "Pasangkan alat dengan perannya melawan greenwashing.",
        pairs: [
          { left: "Pengungkapan (TCFD/ISSB)", right: "Menyediakan data yang dapat diverifikasi" },
          { left: "Taksonomi (OJK)", right: "Memberi kriteria aktivitas yang dianggap hijau" },
          { left: "Verifikasi pihak ketiga", right: "Mengecek kebenaran klaim secara independen" },
          { left: "Greenwashing", right: "Klaim hijau menyesatkan tanpa bukti memadai" },
        ],
      },
      {
        type: "calcExercise",
        prompt: "Sebuah 'dana hijau' memiliki 8% aset memenuhi taksonomi dan 60% di sektor intensif emisi. Berapa selisih persentase poin antara keduanya?",
        answer: 52,
        tolerance: 0,
        suffix: " poin persen",
        solution: "60% - 8% = 52 poin persen, menunjukkan klaim 'hijau' tidak sesuai komposisi aset.",
      },
      {
        type: "calcExercise",
        prompt: "Pada 'dana hijau' tersebut, hanya 8% aset memenuhi kriteria taksonomi. Berapa persen aset yang TIDAK memenuhi taksonomi?",
        answer: 92,
        tolerance: 0,
        suffix: "%",
        solution: "100% - 8% = 92% aset tidak memenuhi kriteria taksonomi, sehingga label 'hijau' menyesatkan.",
        hint: "Kurangkan 8% dari 100%.",
      },
      {
        type: "case",
        title: "Sejarah: Kasus Greenwashing DWS 2022",
        html: "Pada <strong>2022</strong>, manajer aset <strong>DWS</strong> (bagian dari Deutsche Bank) digeledah otoritas Jerman atas dugaan <strong>greenwashing</strong> karena melebih-lebihkan kredensial ESG produknya, dan CEO-nya kemudian mundur. Pada <strong>2023</strong>, DWS sepakat membayar denda <strong>sekitar USD 19 juta</strong> kepada regulator AS, menegaskan bahwa klaim hijau tanpa bukti kini berisiko hukum dan reputasi.",
      },
      {
        type: "takeaways",
        items: [
          "Greenwashing adalah klaim hijau yang menyesatkan tanpa bukti memadai.",
          "Tanda bahaya: klaim samar, tanpa data, tanpa acuan standar/taksonomi, tanpa verifikasi.",
          "Pengungkapan, taksonomi, dan verifikasi pihak ketiga saling melengkapi menjaga integritas klaim.",
          "Regulasi anti-greenwashing menuntut klaim hijau berbasis bukti yang dapat ditelusuri.",
        ],
      },
      {
        type: "quiz",
        questions: [
          {
            q: "Apa itu greenwashing?",
            options: [
              "Audit lingkungan independen",
              "Klaim ramah lingkungan yang menyesatkan tanpa bukti memadai",
              "Pajak karbon",
              "Standar pengungkapan",
            ],
            answer: 1,
            explain: "Greenwashing adalah klaim hijau yang dilebih-lebihkan atau menyesatkan tanpa bukti.",
          },
          {
            q: "Mana yang merupakan tanda bahaya greenwashing?",
            options: [
              "Data emisi lengkap dengan target bertonggak",
              "Klaim 'ramah lingkungan' tanpa angka atau verifikasi",
              "Verifikasi pihak ketiga",
              "Mengacu pada taksonomi resmi",
            ],
            answer: 1,
            explain: "Klaim samar tanpa data dan verifikasi adalah tanda bahaya greenwashing.",
          },
          {
            q: "Peran taksonomi dalam melawan greenwashing adalah?",
            options: [
              "Menentukan harga saham",
              "Memberi kriteria aktivitas yang dianggap hijau",
              "Menghapus pelaporan",
              "Menaikkan kupon obligasi",
            ],
            answer: 1,
            explain: "Taksonomi memberi kriteria objektif tentang apa yang hijau.",
          },
          {
            q: "Peran pengungkapan (TCFD/ISSB) terhadap integritas klaim adalah?",
            options: [
              "Menyediakan data yang dapat diverifikasi",
              "Menyembunyikan emisi",
              "Mengganti dewan komisaris",
              "Menentukan kurs",
            ],
            answer: 0,
            explain: "Pengungkapan menyediakan data terstruktur yang bisa diuji kebenarannya.",
          },
          {
            q: "Mengapa verifikasi pihak ketiga penting?",
            options: [
              "Agar klaim tidak perlu data",
              "Untuk mengecek kebenaran klaim secara independen",
              "Untuk menaikkan skor otomatis",
              "Untuk menghapus regulasi",
            ],
            answer: 1,
            explain: "Pihak ketiga independen memberi keyakinan bahwa klaim sesuai bukti.",
          },
          {
            q: "Pada studi kasus 'dana hijau', apa yang membuat klaim menyesatkan?",
            options: [
              "Seluruh aset memenuhi taksonomi",
              "Hanya 8% aset memenuhi taksonomi sementara 60% intensif emisi",
              "Tidak ada aset sama sekali",
              "Aset hanya berupa kas",
            ],
            answer: 1,
            explain: "Komposisi aset tidak mendukung label 'hijau', sehingga klaim menyesatkan.",
          },
          {
            q: "Tiga alat yang saling melengkapi melawan greenwashing adalah?",
            options: [
              "Pengungkapan, taksonomi, verifikasi pihak ketiga",
              "Inflasi, suku bunga, kurs",
              "Pajak, subsidi, tarif",
              "Iklan, merek, logo",
            ],
            answer: 0,
            explain: "Pengungkapan, taksonomi, dan verifikasi pihak ketiga bersama menjaga integritas klaim.",
          },
        ],
      },
    ],
  },
];
